Battery Simulator Documentation: C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/os/OSWrappers.cpp File Reference
OSWrappers.cpp File Reference
#include <touchgfx/hal/OSWrappers.hpp>
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include <touchgfx/hal/GPIO.hpp>
#include <touchgfx/hal/HAL.hpp>
Functions
static portBASE_TYPE IdleTaskHook (void *p)
void vApplicationIdleHook (void)
void vApplicationMallocFailedHook (xTaskHandle xTask, signed portCHAR *pcTaskName)
void vApplicationStackOverflowHook (xTaskHandle xTask, signed portCHAR *pcTaskName)
Variables
static uint8_t dummy = 0x5a
static xSemaphoreHandle frame_buffer_sem
static xQueueHandle vsync_q = 0
Function Documentation
IdleTaskHook()
static portBASE_TYPE IdleTaskHook (void * p) static
{
    if ((int)p) // Idle task sched out
    {
        touchgfx::HAL::getInstance()->setMCUActive(true);
    }
    else // Idle task sched in
    {
        touchgfx::HAL::getInstance()->setMCUActive(false);
    }
    return pdTRUE;
}
References HAL::getInstance().
Referenced by vApplicationIdleHook().
vApplicationIdleHook()
void vApplicationIdleHook (void)
    {
        // Set task tag in order to have the "IdleTaskHook" function called when the idle task is
        // switched in/out. Used solely for measuring MCU load, and can be removed if MCU load
        // readout is not needed.
        vTaskSetApplicationTaskTag(NULL, IdleTaskHook);
    }
References IdleTaskHook(), and NULL.
vApplicationMallocFailedHook()
void vApplicationMallocFailedHook (xTaskHandle xTask, signed portCHAR * pcTaskName)
    {
        while (1);
    }
vApplicationStackOverflowHook()
void vApplicationStackOverflowHook (xTaskHandle xTask, signed portCHAR * pcTaskName)
    {
        while (1);
    }
Variable Documentation
dummy
uint8_t dummy = 0x5a static
Referenced by FontCache::cacheSortedString(), OSWrappers::signalVSync(), and touchgfx::simulator_enable_stdio().
frame_buffer_sem
xSemaphoreHandle frame_buffer_sem static
vsync_q
xQueueHandle vsync_q = 0 static
Referenced by OSWrappers::signalVSync().