Battery Simulator Documentation: C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/platform/hal/simulator/sdl2/vendor/SDL2/SDL_video.h File Reference
SDL_video.h File Reference
#include "SDL_stdinc.h"
#include "SDL_pixels.h"
#include "SDL_rect.h"
#include "SDL_surface.h"
#include "begin_code.h"
#include "close_code.h"
Classes
struct SDL_DisplayMode
The structure that defines a display mode.
Macros
#define SDL_WINDOWPOS_CENTERED SDL_WINDOWPOS_CENTERED_DISPLAY(0)
#define SDL_WINDOWPOS_CENTERED_DISPLAY(X) (SDL_WINDOWPOS_CENTERED_MASK|(X))
#define SDL_WINDOWPOS_CENTERED_MASK 0x2FFF0000
Used to indicate that the window position should be centered.
#define SDL_WINDOWPOS_ISCENTERED(X) (((X)&0xFFFF0000) == SDL_WINDOWPOS_CENTERED_MASK)
#define SDL_WINDOWPOS_ISUNDEFINED(X) (((X)&0xFFFF0000) == SDL_WINDOWPOS_UNDEFINED_MASK)
#define SDL_WINDOWPOS_UNDEFINED SDL_WINDOWPOS_UNDEFINED_DISPLAY(0)
#define SDL_WINDOWPOS_UNDEFINED_DISPLAY(X) (SDL_WINDOWPOS_UNDEFINED_MASK|(X))
#define SDL_WINDOWPOS_UNDEFINED_MASK 0x1FFF0000
Used to indicate that you don't care what the window position is.
Typedefs
typedef void * SDL_GLContext
An opaque handle to an OpenGL context.
typedef SDL_HitTestResult(SDLCALL * SDL_HitTest) (SDL_Window *win, const SDL_Point *area, void *data)
Callback used for hit-testing.
typedef struct SDL_Window SDL_Window
The type used to identify a window.
Enumerations
enum SDL_GLattr {
SDL_GL_RED_SIZE , SDL_GL_GREEN_SIZE , SDL_GL_BLUE_SIZE , SDL_GL_ALPHA_SIZE ,
SDL_GL_BUFFER_SIZE , SDL_GL_DOUBLEBUFFER , SDL_GL_DEPTH_SIZE , SDL_GL_STENCIL_SIZE ,
SDL_GL_ACCUM_RED_SIZE , SDL_GL_ACCUM_GREEN_SIZE , SDL_GL_ACCUM_BLUE_SIZE , SDL_GL_ACCUM_ALPHA_SIZE ,
SDL_GL_STEREO , SDL_GL_MULTISAMPLEBUFFERS , SDL_GL_MULTISAMPLESAMPLES , SDL_GL_ACCELERATED_VISUAL ,
SDL_GL_RETAINED_BACKING , SDL_GL_CONTEXT_MAJOR_VERSION , SDL_GL_CONTEXT_MINOR_VERSION , SDL_GL_CONTEXT_EGL ,
SDL_GL_CONTEXT_FLAGS , SDL_GL_CONTEXT_PROFILE_MASK , SDL_GL_SHARE_WITH_CURRENT_CONTEXT , SDL_GL_FRAMEBUFFER_SRGB_CAPABLE ,
SDL_GL_CONTEXT_RELEASE_BEHAVIOR
}
OpenGL configuration attributes.
enum SDL_GLcontextFlag { SDL_GL_CONTEXT_DEBUG_FLAG = 0x0001 , SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG = 0x0002 , SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG = 0x0004 , SDL_GL_CONTEXT_RESET_ISOLATION_FLAG = 0x0008 }
enum SDL_GLcontextReleaseFlag { SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE = 0x0000 , SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH = 0x0001 }
enum SDL_GLprofile { SDL_GL_CONTEXT_PROFILE_CORE = 0x0001 , SDL_GL_CONTEXT_PROFILE_COMPATIBILITY = 0x0002 , SDL_GL_CONTEXT_PROFILE_ES = 0x0004 }
enum SDL_HitTestResult {
SDL_HITTEST_NORMAL , SDL_HITTEST_DRAGGABLE , SDL_HITTEST_RESIZE_TOPLEFT , SDL_HITTEST_RESIZE_TOP ,
SDL_HITTEST_RESIZE_TOPRIGHT , SDL_HITTEST_RESIZE_RIGHT , SDL_HITTEST_RESIZE_BOTTOMRIGHT , SDL_HITTEST_RESIZE_BOTTOM ,
SDL_HITTEST_RESIZE_BOTTOMLEFT , SDL_HITTEST_RESIZE_LEFT
}
Possible return values from the SDL_HitTest callback.
enum SDL_WindowEventID {
SDL_WINDOWEVENT_NONE , SDL_WINDOWEVENT_SHOWN , SDL_WINDOWEVENT_HIDDEN , SDL_WINDOWEVENT_EXPOSED ,
SDL_WINDOWEVENT_MOVED , SDL_WINDOWEVENT_RESIZED , SDL_WINDOWEVENT_SIZE_CHANGED , SDL_WINDOWEVENT_MINIMIZED ,
SDL_WINDOWEVENT_MAXIMIZED , SDL_WINDOWEVENT_RESTORED , SDL_WINDOWEVENT_ENTER , SDL_WINDOWEVENT_LEAVE ,
SDL_WINDOWEVENT_FOCUS_GAINED , SDL_WINDOWEVENT_FOCUS_LOST , SDL_WINDOWEVENT_CLOSE
}
Event subtype for window events.
enum SDL_WindowFlags {
SDL_WINDOW_FULLSCREEN = 0x00000001 , SDL_WINDOW_OPENGL = 0x00000002 , SDL_WINDOW_SHOWN = 0x00000004 , SDL_WINDOW_HIDDEN = 0x00000008 ,
SDL_WINDOW_BORDERLESS = 0x00000010 , SDL_WINDOW_RESIZABLE = 0x00000020 , SDL_WINDOW_MINIMIZED = 0x00000040 , SDL_WINDOW_MAXIMIZED = 0x00000080 ,
SDL_WINDOW_INPUT_GRABBED = 0x00000100 , SDL_WINDOW_INPUT_FOCUS = 0x00000200 , SDL_WINDOW_MOUSE_FOCUS = 0x00000400 , SDL_WINDOW_FULLSCREEN_DESKTOP = (SDL_WINDOW_FULLSCREEN | 0x00001000) ,
SDL_WINDOW_FOREIGN = 0x00000800 , SDL_WINDOW_ALLOW_HIGHDPI = 0x00002000 , SDL_WINDOW_MOUSE_CAPTURE = 0x00004000
}
The flags on a window.
Functions
DECLSPEC SDL_Window *SDLCALL SDL_CreateWindow (const char *title, int x, int y, int w, int h, Uint32 flags)
Create a window with the specified position, dimensions, and flags.
DECLSPEC SDL_Window *SDLCALL SDL_CreateWindowFrom (const void *data)
Create an SDL window from an existing native window.
DECLSPEC void SDLCALL SDL_DestroyWindow (SDL_Window *window)
Destroy a window.
DECLSPEC void SDLCALL SDL_DisableScreenSaver (void)
Prevent the screen from being blanked by a screensaver.
DECLSPEC void SDLCALL SDL_EnableScreenSaver (void)
Allow the screen to be blanked by a screensaver.
DECLSPEC SDL_DisplayMode *SDLCALL SDL_GetClosestDisplayMode (int displayIndex, const SDL_DisplayMode *mode, SDL_DisplayMode *closest)
Get the closest match to the requested display mode.
DECLSPEC int SDLCALL SDL_GetCurrentDisplayMode (int displayIndex, SDL_DisplayMode *mode)
Fill in information about the current display mode.
DECLSPEC const char *SDLCALL SDL_GetCurrentVideoDriver (void)
Returns the name of the currently initialized video driver.
DECLSPEC int SDLCALL SDL_GetDesktopDisplayMode (int displayIndex, SDL_DisplayMode *mode)
Fill in information about the desktop display mode.
DECLSPEC int SDLCALL SDL_GetDisplayBounds (int displayIndex, SDL_Rect *rect)
Get the desktop area represented by a display, with the primary display located at 0,0.
DECLSPEC int SDLCALL SDL_GetDisplayDPI (int displayIndex, float *ddpi, float *hdpi, float *vdpi)
Get the dots/pixels-per-inch for a display.
DECLSPEC int SDLCALL SDL_GetDisplayMode (int displayIndex, int modeIndex, SDL_DisplayMode *mode)
Fill in information about a specific display mode.
DECLSPEC const char *SDLCALL SDL_GetDisplayName (int displayIndex)
Get the name of a display in UTF-8 encoding.
DECLSPEC SDL_Window *SDLCALL SDL_GetGrabbedWindow (void)
Get the window that currently has an input grab enabled.
DECLSPEC int SDLCALL SDL_GetNumDisplayModes (int displayIndex)
Returns the number of available display modes.
DECLSPEC int SDLCALL SDL_GetNumVideoDisplays (void)
Returns the number of available video displays.
DECLSPEC int SDLCALL SDL_GetNumVideoDrivers (void)
Get the number of video drivers compiled into SDL.
DECLSPEC const char *SDLCALL SDL_GetVideoDriver (int index)
Get the name of a built in video driver.
DECLSPEC float SDLCALL SDL_GetWindowBrightness (SDL_Window *window)
Get the brightness (gamma correction) for a window.
DECLSPEC void *SDLCALL SDL_GetWindowData (SDL_Window *window, const char *name)
Retrieve the data pointer associated with a window.
DECLSPEC int SDLCALL SDL_GetWindowDisplayIndex (SDL_Window *window)
Get the display index associated with a window.
DECLSPEC int SDLCALL SDL_GetWindowDisplayMode (SDL_Window *window, SDL_DisplayMode *mode)
Fill in information about the display mode used when a fullscreen window is visible.
DECLSPEC Uint32 SDLCALL SDL_GetWindowFlags (SDL_Window *window)
Get the window flags.
DECLSPEC SDL_Window *SDLCALL SDL_GetWindowFromID (Uint32 id)
Get a window from a stored ID, or NULL if it doesn't exist.
DECLSPEC int SDLCALL SDL_GetWindowGammaRamp (SDL_Window *window, Uint16 *red, Uint16 *green, Uint16 *blue)
Get the gamma ramp for a window.
DECLSPEC SDL_bool SDLCALL SDL_GetWindowGrab (SDL_Window *window)
Get a window's input grab mode.
DECLSPEC Uint32 SDLCALL SDL_GetWindowID (SDL_Window *window)
Get the numeric ID of a window, for logging purposes.
DECLSPEC void SDLCALL SDL_GetWindowMaximumSize (SDL_Window *window, int *w, int *h)
Get the maximum size of a window's client area.
DECLSPEC void SDLCALL SDL_GetWindowMinimumSize (SDL_Window *window, int *w, int *h)
Get the minimum size of a window's client area.
DECLSPEC Uint32 SDLCALL SDL_GetWindowPixelFormat (SDL_Window *window)
Get the pixel format associated with the window.
DECLSPEC void SDLCALL SDL_GetWindowPosition (SDL_Window *window, int *x, int *y)
Get the position of a window.
DECLSPEC void SDLCALL SDL_GetWindowSize (SDL_Window *window, int *w, int *h)
Get the size of a window's client area.
DECLSPEC SDL_Surface *SDLCALL SDL_GetWindowSurface (SDL_Window *window)
Get the SDL surface associated with the window.
DECLSPEC const char *SDLCALL SDL_GetWindowTitle (SDL_Window *window)
Get the title of a window, in UTF-8 format.
DECLSPEC void SDLCALL SDL_HideWindow (SDL_Window *window)
Hide a window.
DECLSPEC SDL_bool SDLCALL SDL_IsScreenSaverEnabled (void)
Returns whether the screensaver is currently enabled (default on).
DECLSPEC void SDLCALL SDL_MaximizeWindow (SDL_Window *window)
Make a window as large as possible.
DECLSPEC void SDLCALL SDL_MinimizeWindow (SDL_Window *window)
Minimize a window to an iconic representation.
DECLSPEC void SDLCALL SDL_RaiseWindow (SDL_Window *window)
Raise a window above other windows and set the input focus.
DECLSPEC void SDLCALL SDL_RestoreWindow (SDL_Window *window)
Restore the size and position of a minimized or maximized window.
DECLSPEC void SDLCALL SDL_SetWindowBordered (SDL_Window *window, SDL_bool bordered)
Set the border state of a window.
DECLSPEC int SDLCALL SDL_SetWindowBrightness (SDL_Window *window, float brightness)
Set the brightness (gamma correction) for a window.
DECLSPEC void *SDLCALL SDL_SetWindowData (SDL_Window *window, const char *name, void *userdata)
Associate an arbitrary named pointer with a window.
DECLSPEC int SDLCALL SDL_SetWindowDisplayMode (SDL_Window *window, const SDL_DisplayMode *mode)
Set the display mode used when a fullscreen window is visible.
DECLSPEC int SDLCALL SDL_SetWindowFullscreen (SDL_Window *window, Uint32 flags)
Set a window's fullscreen state.
DECLSPEC int SDLCALL SDL_SetWindowGammaRamp (SDL_Window *window, const Uint16 *red, const Uint16 *green, const Uint16 *blue)
Set the gamma ramp for a window.
DECLSPEC void SDLCALL SDL_SetWindowGrab (SDL_Window *window, SDL_bool grabbed)
Set a window's input grab mode.
DECLSPEC int SDLCALL SDL_SetWindowHitTest (SDL_Window *window, SDL_HitTest callback, void *callback_data)
Provide a callback that decides if a window region has special properties.
DECLSPEC void SDLCALL SDL_SetWindowIcon (SDL_Window *window, SDL_Surface *icon)
Set the icon for a window.
DECLSPEC void SDLCALL SDL_SetWindowMaximumSize (SDL_Window *window, int max_w, int max_h)
Set the maximum size of a window's client area.
DECLSPEC void SDLCALL SDL_SetWindowMinimumSize (SDL_Window *window, int min_w, int min_h)
Set the minimum size of a window's client area.
DECLSPEC void SDLCALL SDL_SetWindowPosition (SDL_Window *window, int x, int y)
Set the position of a window.
DECLSPEC void SDLCALL SDL_SetWindowSize (SDL_Window *window, int w, int h)
Set the size of a window's client area.
DECLSPEC void SDLCALL SDL_SetWindowTitle (SDL_Window *window, const char *title)
Set the title of a window, in UTF-8 format.
DECLSPEC void SDLCALL SDL_ShowWindow (SDL_Window *window)
Show a window.
DECLSPEC int SDLCALL SDL_UpdateWindowSurface (SDL_Window *window)
Copy the window surface to the screen.
DECLSPEC int SDLCALL SDL_UpdateWindowSurfaceRects (SDL_Window *window, const SDL_Rect *rects, int numrects)
Copy a number of rectangles on the window surface to the screen.
DECLSPEC int SDLCALL SDL_VideoInit (const char *driver_name)
Initialize the video subsystem, optionally specifying a video driver.
DECLSPEC void SDLCALL SDL_VideoQuit (void)
Shuts down the video subsystem.
OpenGL support functions
DECLSPEC SDL_GLContext SDLCALL SDL_GL_CreateContext (SDL_Window *window)
Create an OpenGL context for use with an OpenGL window, and make it current.
DECLSPEC void SDLCALL SDL_GL_DeleteContext (SDL_GLContext context)
Delete an OpenGL context.
DECLSPEC SDL_bool SDLCALL SDL_GL_ExtensionSupported (const char *extension)
Return true if an OpenGL extension is supported for the current context.
DECLSPEC int SDLCALL SDL_GL_GetAttribute (SDL_GLattr attr, int *value)
Get the actual value for an attribute from the current context.
DECLSPEC SDL_GLContext SDLCALL SDL_GL_GetCurrentContext (void)
Get the currently active OpenGL context.
DECLSPEC SDL_Window *SDLCALL SDL_GL_GetCurrentWindow (void)
Get the currently active OpenGL window.
DECLSPEC void SDLCALL SDL_GL_GetDrawableSize (SDL_Window *window, int *w, int *h)
Get the size of a window's underlying drawable in pixels (for use with glViewport).
DECLSPEC void *SDLCALL SDL_GL_GetProcAddress (const char *proc)
Get the address of an OpenGL function.
DECLSPEC int SDLCALL SDL_GL_GetSwapInterval (void)
Get the swap interval for the current OpenGL context.
DECLSPEC int SDLCALL SDL_GL_LoadLibrary (const char *path)
Dynamically load an OpenGL library.
DECLSPEC int SDLCALL SDL_GL_MakeCurrent (SDL_Window *window, SDL_GLContext context)
Set up an OpenGL context for rendering into an OpenGL window.
DECLSPEC void SDLCALL SDL_GL_ResetAttributes (void)
Reset all previously set OpenGL context attributes to their default values.
DECLSPEC int SDLCALL SDL_GL_SetAttribute (SDL_GLattr attr, int value)
Set an OpenGL window attribute before window creation.
DECLSPEC int SDLCALL SDL_GL_SetSwapInterval (int interval)
Set the swap interval for the current OpenGL context.
DECLSPEC void SDLCALL SDL_GL_SwapWindow (SDL_Window *window)
Swap the OpenGL buffers for a window, if double-buffering is supported.
DECLSPEC void SDLCALL SDL_GL_UnloadLibrary (void)
Unload the OpenGL library previously loaded by SDL_GL_LoadLibrary().
Detailed Description
Header file for SDL video functions.
Definition in file SDL_video.h.
Macro Definition Documentation
SDL_WINDOWPOS_CENTERED
#define SDL_WINDOWPOS_CENTERED SDL_WINDOWPOS_CENTERED_DISPLAY(0)
SDL_WINDOWPOS_CENTERED_DISPLAY
#define SDL_WINDOWPOS_CENTERED_DISPLAY (X) (SDL_WINDOWPOS_CENTERED_MASK|(X))
SDL_WINDOWPOS_CENTERED_MASK
#define SDL_WINDOWPOS_CENTERED_MASK 0x2FFF0000
Used to indicate that the window position should be centered.
SDL_WINDOWPOS_ISCENTERED
#define SDL_WINDOWPOS_ISCENTERED (X) (((X)&0xFFFF0000) == SDL_WINDOWPOS_CENTERED_MASK)
#define SDL_WINDOWPOS_ISCENTERED(X)    \
            (((X)&0xFFFF0000) == SDL_WINDOWPOS_CENTERED_MASK)
SDL_WINDOWPOS_ISUNDEFINED
#define SDL_WINDOWPOS_ISUNDEFINED (X) (((X)&0xFFFF0000) == SDL_WINDOWPOS_UNDEFINED_MASK)
#define SDL_WINDOWPOS_ISUNDEFINED(X)    \
            (((X)&0xFFFF0000) == SDL_WINDOWPOS_UNDEFINED_MASK)
SDL_WINDOWPOS_UNDEFINED
#define SDL_WINDOWPOS_UNDEFINED SDL_WINDOWPOS_UNDEFINED_DISPLAY(0)
Referenced by HALSDL2::recreateWindow().
SDL_WINDOWPOS_UNDEFINED_DISPLAY
#define SDL_WINDOWPOS_UNDEFINED_DISPLAY (X) (SDL_WINDOWPOS_UNDEFINED_MASK|(X))
SDL_WINDOWPOS_UNDEFINED_MASK
#define SDL_WINDOWPOS_UNDEFINED_MASK 0x1FFF0000
Used to indicate that you don't care what the window position is.
Typedef Documentation
SDL_GLContext
typedef void* SDL_GLContext
An opaque handle to an OpenGL context.
SDL_HitTest
typedef SDL_HitTestResult(SDLCALL * SDL_HitTest) (SDL_Window *win, const SDL_Point *area, void *data)
Callback used for hit-testing.
See also
SDL_SetWindowHitTest
SDL_Window
typedef struct SDL_Window SDL_Window
The type used to identify a window.
See also
SDL_CreateWindow()
SDL_CreateWindowFrom()
SDL_DestroyWindow()
SDL_GetWindowData()
SDL_GetWindowFlags()
SDL_GetWindowGrab()
SDL_GetWindowPosition()
SDL_GetWindowSize()
SDL_GetWindowTitle()
SDL_HideWindow()
SDL_MaximizeWindow()
SDL_MinimizeWindow()
SDL_RaiseWindow()
SDL_RestoreWindow()
SDL_SetWindowData()
SDL_SetWindowFullscreen()
SDL_SetWindowGrab()
SDL_SetWindowIcon()
SDL_SetWindowPosition()
SDL_SetWindowSize()
SDL_SetWindowBordered()
SDL_SetWindowTitle()
SDL_ShowWindow()
Enumeration Type Documentation
SDL_GLattr
enum SDL_GLattr
OpenGL configuration attributes.
Enumerator
SDL_GL_RED_SIZE
SDL_GL_GREEN_SIZE
SDL_GL_BLUE_SIZE
SDL_GL_ALPHA_SIZE
SDL_GL_BUFFER_SIZE
SDL_GL_DOUBLEBUFFER
SDL_GL_DEPTH_SIZE
SDL_GL_STENCIL_SIZE
SDL_GL_ACCUM_RED_SIZE
SDL_GL_ACCUM_GREEN_SIZE
SDL_GL_ACCUM_BLUE_SIZE
SDL_GL_ACCUM_ALPHA_SIZE
SDL_GL_STEREO
SDL_GL_MULTISAMPLEBUFFERS
SDL_GL_MULTISAMPLESAMPLES
SDL_GL_ACCELERATED_VISUAL
SDL_GL_RETAINED_BACKING
SDL_GL_CONTEXT_MAJOR_VERSION
SDL_GL_CONTEXT_MINOR_VERSION
SDL_GL_CONTEXT_EGL
SDL_GL_CONTEXT_FLAGS
SDL_GL_CONTEXT_PROFILE_MASK
SDL_GL_SHARE_WITH_CURRENT_CONTEXT
SDL_GL_FRAMEBUFFER_SRGB_CAPABLE
SDL_GL_CONTEXT_RELEASE_BEHAVIOR
{
    SDL_GL_RED_SIZE,
    SDL_GL_GREEN_SIZE,
    SDL_GL_BLUE_SIZE,
    SDL_GL_ALPHA_SIZE,
    SDL_GL_BUFFER_SIZE,
    SDL_GL_DOUBLEBUFFER,
    SDL_GL_DEPTH_SIZE,
    SDL_GL_STENCIL_SIZE,
    SDL_GL_ACCUM_RED_SIZE,
    SDL_GL_ACCUM_GREEN_SIZE,
    SDL_GL_ACCUM_BLUE_SIZE,
    SDL_GL_ACCUM_ALPHA_SIZE,
    SDL_GL_STEREO,
    SDL_GL_MULTISAMPLEBUFFERS,
    SDL_GL_MULTISAMPLESAMPLES,
    SDL_GL_ACCELERATED_VISUAL,
    SDL_GL_RETAINED_BACKING,
    SDL_GL_CONTEXT_MAJOR_VERSION,
    SDL_GL_CONTEXT_MINOR_VERSION,
    SDL_GL_CONTEXT_EGL,
    SDL_GL_CONTEXT_FLAGS,
    SDL_GL_CONTEXT_PROFILE_MASK,
    SDL_GL_SHARE_WITH_CURRENT_CONTEXT,
    SDL_GL_FRAMEBUFFER_SRGB_CAPABLE,
    SDL_GL_CONTEXT_RELEASE_BEHAVIOR
} SDL_GLattr;
SDL_GLcontextFlag
enum SDL_GLcontextFlag
Enumerator
SDL_GL_CONTEXT_DEBUG_FLAG
SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG
SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG
SDL_GL_CONTEXT_RESET_ISOLATION_FLAG
{
    SDL_GL_CONTEXT_DEBUG_FLAG              = 0x0001,
    SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG = 0x0002,
    SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG      = 0x0004,
    SDL_GL_CONTEXT_RESET_ISOLATION_FLAG    = 0x0008
} SDL_GLcontextFlag;
SDL_GLcontextReleaseFlag
enum SDL_GLcontextReleaseFlag
Enumerator
SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE
SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH
{
    SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE   = 0x0000,
    SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH  = 0x0001
} SDL_GLcontextReleaseFlag;
SDL_GLprofile
enum SDL_GLprofile
Enumerator
SDL_GL_CONTEXT_PROFILE_CORE
SDL_GL_CONTEXT_PROFILE_COMPATIBILITY
SDL_GL_CONTEXT_PROFILE_ES
{
    SDL_GL_CONTEXT_PROFILE_CORE           = 0x0001,
    SDL_GL_CONTEXT_PROFILE_COMPATIBILITY  = 0x0002,
    SDL_GL_CONTEXT_PROFILE_ES             = 0x0004 /* GLX_CONTEXT_ES2_PROFILE_BIT_EXT */
} SDL_GLprofile;
SDL_HitTestResult
enum SDL_HitTestResult
Possible return values from the SDL_HitTest callback.
See also
SDL_HitTest
Enumerator
SDL_HITTEST_NORMAL
Region is normal. No special properties.
SDL_HITTEST_DRAGGABLE
Region can drag entire window.
SDL_HITTEST_RESIZE_TOPLEFT
SDL_HITTEST_RESIZE_TOP
SDL_HITTEST_RESIZE_TOPRIGHT
SDL_HITTEST_RESIZE_RIGHT
SDL_HITTEST_RESIZE_BOTTOMRIGHT
SDL_HITTEST_RESIZE_BOTTOM
SDL_HITTEST_RESIZE_BOTTOMLEFT
SDL_HITTEST_RESIZE_LEFT
{
    SDL_HITTEST_NORMAL,
    SDL_HITTEST_DRAGGABLE,
    SDL_HITTEST_RESIZE_TOPLEFT,
    SDL_HITTEST_RESIZE_TOP,
    SDL_HITTEST_RESIZE_TOPRIGHT,
    SDL_HITTEST_RESIZE_RIGHT,
    SDL_HITTEST_RESIZE_BOTTOMRIGHT,
    SDL_HITTEST_RESIZE_BOTTOM,
    SDL_HITTEST_RESIZE_BOTTOMLEFT,
    SDL_HITTEST_RESIZE_LEFT
} SDL_HitTestResult;
SDL_WindowEventID
enum SDL_WindowEventID
Event subtype for window events.
Enumerator
SDL_WINDOWEVENT_NONE
Never used
SDL_WINDOWEVENT_SHOWN
Window has been shown
SDL_WINDOWEVENT_HIDDEN
Window has been hidden
SDL_WINDOWEVENT_EXPOSED
Window has been exposed and should be redrawn
SDL_WINDOWEVENT_MOVED
Window has been moved to data1, data2
SDL_WINDOWEVENT_RESIZED
Window has been resized to data1xdata2
SDL_WINDOWEVENT_SIZE_CHANGED
The window size has changed, either as a result of an API call or through the system or user changing the window size.
SDL_WINDOWEVENT_MINIMIZED
Window has been minimized
SDL_WINDOWEVENT_MAXIMIZED
Window has been maximized
SDL_WINDOWEVENT_RESTORED
Window has been restored to normal size and position
SDL_WINDOWEVENT_ENTER
Window has gained mouse focus
SDL_WINDOWEVENT_LEAVE
Window has lost mouse focus
SDL_WINDOWEVENT_FOCUS_GAINED
Window has gained keyboard focus
SDL_WINDOWEVENT_FOCUS_LOST
Window has lost keyboard focus
SDL_WINDOWEVENT_CLOSE
The window manager requests that the window be closed
{
    SDL_WINDOWEVENT_NONE,
    SDL_WINDOWEVENT_SHOWN,
    SDL_WINDOWEVENT_HIDDEN,
    SDL_WINDOWEVENT_EXPOSED,
    SDL_WINDOWEVENT_MOVED,
    SDL_WINDOWEVENT_RESIZED,
    SDL_WINDOWEVENT_SIZE_CHANGED,
    SDL_WINDOWEVENT_MINIMIZED,
    SDL_WINDOWEVENT_MAXIMIZED,
    SDL_WINDOWEVENT_RESTORED,
    SDL_WINDOWEVENT_ENTER,
    SDL_WINDOWEVENT_LEAVE,
    SDL_WINDOWEVENT_FOCUS_GAINED,
    SDL_WINDOWEVENT_FOCUS_LOST,
    SDL_WINDOWEVENT_CLOSE
} SDL_WindowEventID;
SDL_WindowFlags
enum SDL_WindowFlags
The flags on a window.
See also
SDL_GetWindowFlags()
Enumerator
SDL_WINDOW_FULLSCREEN
fullscreen window
SDL_WINDOW_OPENGL
window usable with OpenGL context
SDL_WINDOW_SHOWN
window is visible
SDL_WINDOW_HIDDEN
window is not visible
SDL_WINDOW_BORDERLESS
no window decoration
SDL_WINDOW_RESIZABLE
window can be resized
SDL_WINDOW_MINIMIZED
window is minimized
SDL_WINDOW_MAXIMIZED
window is maximized
SDL_WINDOW_INPUT_GRABBED
window has grabbed input focus
SDL_WINDOW_INPUT_FOCUS
window has input focus
SDL_WINDOW_MOUSE_FOCUS
window has mouse focus
SDL_WINDOW_FULLSCREEN_DESKTOP
SDL_WINDOW_FOREIGN
window not created by SDL
SDL_WINDOW_ALLOW_HIGHDPI
window should be created in high-DPI mode if supported
SDL_WINDOW_MOUSE_CAPTURE
window has mouse captured (unrelated to INPUT_GRABBED)
{
    SDL_WINDOW_FULLSCREEN = 0x00000001,
    SDL_WINDOW_OPENGL = 0x00000002,
    SDL_WINDOW_SHOWN = 0x00000004,
    SDL_WINDOW_HIDDEN = 0x00000008,
    SDL_WINDOW_BORDERLESS = 0x00000010,
    SDL_WINDOW_RESIZABLE = 0x00000020,
    SDL_WINDOW_MINIMIZED = 0x00000040,
    SDL_WINDOW_MAXIMIZED = 0x00000080,
    SDL_WINDOW_INPUT_GRABBED = 0x00000100,
    SDL_WINDOW_INPUT_FOCUS = 0x00000200,
    SDL_WINDOW_MOUSE_FOCUS = 0x00000400,
    SDL_WINDOW_FULLSCREEN_DESKTOP = ( SDL_WINDOW_FULLSCREEN | 0x00001000 ),
    SDL_WINDOW_FOREIGN = 0x00000800,
    SDL_WINDOW_ALLOW_HIGHDPI = 0x00002000,
    SDL_WINDOW_MOUSE_CAPTURE = 0x00004000
} SDL_WindowFlags;
Function Documentation
SDL_CreateWindow()
DECLSPEC SDL_Window *SDLCALL SDL_CreateWindow (const char * title, int x, int y, int w, int h, Uint32 flags) extern
Create a window with the specified position, dimensions, and flags.
Parameters
title The title of the window, in UTF-8 encoding.
x The x position of the window, SDL_WINDOWPOS_CENTERED, or SDL_WINDOWPOS_UNDEFINED.
y The y position of the window, SDL_WINDOWPOS_CENTERED, or SDL_WINDOWPOS_UNDEFINED.
w The width of the window, in screen coordinates.
h The height of the window, in screen coordinates.
flags The flags for the window, a mask of any of the following: SDL_WINDOW_FULLSCREEN, SDL_WINDOW_OPENGL, SDL_WINDOW_HIDDEN, SDL_WINDOW_BORDERLESS, SDL_WINDOW_RESIZABLE, SDL_WINDOW_MAXIMIZED, SDL_WINDOW_MINIMIZED, SDL_WINDOW_INPUT_GRABBED, SDL_WINDOW_ALLOW_HIGHDPI.
Returns
The id of the window created, or zero if window creation failed.
If the window is created with the SDL_WINDOW_ALLOW_HIGHDPI flag, its size in pixels may differ from its size in screen coordinates on platforms with high-DPI support (e.g. iOS and Mac OS X). Use SDL_GetWindowSize() to query the client area's size in screen coordinates, and SDL_GL_GetDrawableSize() or SDL_GetRendererOutputSize() to query the drawable size in pixels.
See also
SDL_DestroyWindow()
Referenced by HALSDL2::recreateWindow().
SDL_CreateWindowFrom()
DECLSPEC SDL_Window *SDLCALL SDL_CreateWindowFrom (const void * data) extern
Create an SDL window from an existing native window.
Parameters
data A pointer to driver-dependent window creation data
Returns
The id of the window created, or zero if window creation failed.
See also
SDL_DestroyWindow()
SDL_DestroyWindow()
DECLSPEC void SDLCALL SDL_DestroyWindow (SDL_Window * window) extern
Destroy a window.
Referenced by HALSDL2::recreateWindow(), and touchgfx::sdlCleanup2().
SDL_DisableScreenSaver()
DECLSPEC void SDLCALL SDL_DisableScreenSaver (void) extern
Prevent the screen from being blanked by a screensaver.
See also
SDL_IsScreenSaverEnabled()
SDL_EnableScreenSaver()
SDL_EnableScreenSaver()
DECLSPEC void SDLCALL SDL_EnableScreenSaver (void) extern
Allow the screen to be blanked by a screensaver.
See also
SDL_IsScreenSaverEnabled()
SDL_DisableScreenSaver()
SDL_GetClosestDisplayMode()
DECLSPEC SDL_DisplayMode *SDLCALL SDL_GetClosestDisplayMode (int displayIndex, const SDL_DisplayMode * mode, SDL_DisplayMode * closest) extern
Get the closest match to the requested display mode.
Parameters
displayIndex The index of display from which mode should be queried.
mode The desired display mode
closest A pointer to a display mode to be filled in with the closest match of the available display modes.
Returns
The passed in value closest, or NULL if no matching video mode was available.
The available display modes are scanned, and closest is filled in with the closest mode matching the requested mode and returned. The mode format and refresh_rate default to the desktop mode if they are 0. The modes are scanned with size being first priority, format being second priority, and finally checking the refresh_rate. If all the available modes are too small, then NULL is returned.
See also
SDL_GetNumDisplayModes()
SDL_GetDisplayMode()
SDL_GetCurrentDisplayMode()
DECLSPEC int SDLCALL SDL_GetCurrentDisplayMode (int displayIndex, SDL_DisplayMode * mode) extern
Fill in information about the current display mode.
SDL_GetCurrentVideoDriver()
DECLSPEC const char *SDLCALL SDL_GetCurrentVideoDriver (void) extern
Returns the name of the currently initialized video driver.
Returns
The name of the current video driver or NULL if no driver has been initialized
See also
SDL_GetNumVideoDrivers()
SDL_GetVideoDriver()
SDL_GetDesktopDisplayMode()
DECLSPEC int SDLCALL SDL_GetDesktopDisplayMode (int displayIndex, SDL_DisplayMode * mode) extern
Fill in information about the desktop display mode.
SDL_GetDisplayBounds()
DECLSPEC int SDLCALL SDL_GetDisplayBounds (int displayIndex, SDL_Rect * rect) extern
Get the desktop area represented by a display, with the primary display located at 0,0.
Returns
0 on success, or -1 if the index is out of range.
See also
SDL_GetNumVideoDisplays()
SDL_GetDisplayDPI()
DECLSPEC int SDLCALL SDL_GetDisplayDPI (int displayIndex, float * ddpi, float * hdpi, float * vdpi) extern
Get the dots/pixels-per-inch for a display.
Note
Diagonal, horizontal and vertical DPI can all be optionally returned if the parameter is non-NULL.
Returns
0 on success, or -1 if no DPI information is available or the index is out of range.
See also
SDL_GetNumVideoDisplays()
SDL_GetDisplayMode()
DECLSPEC int SDLCALL SDL_GetDisplayMode (int displayIndex, int modeIndex, SDL_DisplayMode * mode) extern
Fill in information about a specific display mode.
Note
The display modes are sorted in this priority:
bits per pixel -> more colors to fewer colors
width -> largest to smallest
height -> largest to smallest
refresh rate -> highest to lowest
See also
SDL_GetNumDisplayModes()
SDL_GetDisplayName()
DECLSPEC const char *SDLCALL SDL_GetDisplayName (int displayIndex) extern
Get the name of a display in UTF-8 encoding.
Returns
The name of a display, or NULL for an invalid display index.
See also
SDL_GetNumVideoDisplays()
SDL_GetGrabbedWindow()
DECLSPEC SDL_Window *SDLCALL SDL_GetGrabbedWindow (void) extern
Get the window that currently has an input grab enabled.
Returns
This returns the window if input is grabbed, and NULL otherwise.
See also
SDL_SetWindowGrab()
SDL_GetNumDisplayModes()
DECLSPEC int SDLCALL SDL_GetNumDisplayModes (int displayIndex) extern
Returns the number of available display modes.
See also
SDL_GetDisplayMode()
SDL_GetNumVideoDisplays()
DECLSPEC int SDLCALL SDL_GetNumVideoDisplays (void) extern
Returns the number of available video displays.
See also
SDL_GetDisplayBounds()
SDL_GetNumVideoDrivers()
DECLSPEC int SDLCALL SDL_GetNumVideoDrivers (void) extern
Get the number of video drivers compiled into SDL.
See also
SDL_GetVideoDriver()
SDL_GetVideoDriver()
DECLSPEC const char *SDLCALL SDL_GetVideoDriver (int index) extern
Get the name of a built in video driver.
Note
The video drivers are presented in the order in which they are normally checked during initialization.
See also
SDL_GetNumVideoDrivers()
SDL_GetWindowBrightness()
DECLSPEC float SDLCALL SDL_GetWindowBrightness (SDL_Window * window) extern
Get the brightness (gamma correction) for a window.
Returns
The last brightness value passed to SDL_SetWindowBrightness()
See also
SDL_SetWindowBrightness()
SDL_GetWindowData()
DECLSPEC void *SDLCALL SDL_GetWindowData (SDL_Window * window, const char * name) extern
Retrieve the data pointer associated with a window.
Parameters
window The window to query.
name The name of the pointer.
Returns
The value associated with 'name'
See also
SDL_SetWindowData()
SDL_GetWindowDisplayIndex()
DECLSPEC int SDLCALL SDL_GetWindowDisplayIndex (SDL_Window * window) extern
Get the display index associated with a window.
Returns
the display index of the display containing the center of the window, or -1 on error.
SDL_GetWindowDisplayMode()
DECLSPEC int SDLCALL SDL_GetWindowDisplayMode (SDL_Window * window, SDL_DisplayMode * mode) extern
Fill in information about the display mode used when a fullscreen window is visible.
See also
SDL_SetWindowDisplayMode()
SDL_SetWindowFullscreen()
SDL_GetWindowFlags()
DECLSPEC Uint32 SDLCALL SDL_GetWindowFlags (SDL_Window * window) extern
Get the window flags.
SDL_GetWindowFromID()
DECLSPEC SDL_Window *SDLCALL SDL_GetWindowFromID (Uint32 id) extern
Get a window from a stored ID, or NULL if it doesn't exist.
SDL_GetWindowGammaRamp()
DECLSPEC int SDLCALL SDL_GetWindowGammaRamp (SDL_Window * window, Uint16 * red, Uint16 * green, Uint16 * blue) extern
Get the gamma ramp for a window.
Parameters
window The window from which the gamma ramp should be queried.
red A pointer to a 256 element array of 16-bit quantities to hold the translation table for the red channel, or NULL.
green A pointer to a 256 element array of 16-bit quantities to hold the translation table for the green channel, or NULL.
blue A pointer to a 256 element array of 16-bit quantities to hold the translation table for the blue channel, or NULL.
Returns
0 on success, or -1 if gamma ramps are unsupported.
See also
SDL_SetWindowGammaRamp()
SDL_GetWindowGrab()
DECLSPEC SDL_bool SDLCALL SDL_GetWindowGrab (SDL_Window * window) extern
Get a window's input grab mode.
Returns
This returns SDL_TRUE if input is grabbed, and SDL_FALSE otherwise.
See also
SDL_SetWindowGrab()
SDL_GetWindowID()
DECLSPEC Uint32 SDLCALL SDL_GetWindowID (SDL_Window * window) extern
Get the numeric ID of a window, for logging purposes.
SDL_GetWindowMaximumSize()
DECLSPEC void SDLCALL SDL_GetWindowMaximumSize (SDL_Window * window, int * w, int * h) extern
Get the maximum size of a window's client area.
Parameters
window The window to query.
w Pointer to variable for storing the maximum width, may be NULL
h Pointer to variable for storing the maximum height, may be NULL
See also
SDL_GetWindowMinimumSize()
SDL_SetWindowMaximumSize()
SDL_GetWindowMinimumSize()
DECLSPEC void SDLCALL SDL_GetWindowMinimumSize (SDL_Window * window, int * w, int * h) extern
Get the minimum size of a window's client area.
Parameters
window The window to query.
w Pointer to variable for storing the minimum width, may be NULL
h Pointer to variable for storing the minimum height, may be NULL
See also
SDL_GetWindowMaximumSize()
SDL_SetWindowMinimumSize()
SDL_GetWindowPixelFormat()
DECLSPEC Uint32 SDLCALL SDL_GetWindowPixelFormat (SDL_Window * window) extern
Get the pixel format associated with the window.
Referenced by HALSDL2::saveScreenshot().
SDL_GetWindowPosition()
DECLSPEC void SDLCALL SDL_GetWindowPosition (SDL_Window * window, int * x, int * y) extern
Get the position of a window.
Parameters
window The window to query.
x Pointer to variable for storing the x position, in screen coordinates. May be NULL.
y Pointer to variable for storing the y position, in screen coordinates. May be NULL.
See also
SDL_SetWindowPosition()
Referenced by HALSDL2::recreateWindow(), and HALSDL2::taskEntry().
SDL_GetWindowSize()
DECLSPEC void SDLCALL SDL_GetWindowSize (SDL_Window * window, int * w, int * h) extern
Get the size of a window's client area.
Parameters
window The window to query.
w Pointer to variable for storing the width, in screen coordinates. May be NULL.
h Pointer to variable for storing the height, in screen coordinates. May be NULL.
The window size in screen coordinates may differ from the size in pixels, if the window was created with SDL_WINDOW_ALLOW_HIGHDPI on a platform with high-dpi support (e.g. iOS or OS X). Use SDL_GL_GetDrawableSize() or SDL_GetRendererOutputSize() to get the real client area size in pixels.
See also
SDL_SetWindowSize()
SDL_GetWindowSurface()
DECLSPEC SDL_Surface *SDLCALL SDL_GetWindowSurface (SDL_Window * window) extern
Get the SDL surface associated with the window.
Returns
The window's framebuffer surface, or NULL on error.
A new surface will be created with the optimal format for the window, if necessary. This surface will be freed when the window is destroyed.
Note
You may not combine this with 3D or the rendering API on this window.
See also
SDL_UpdateWindowSurface()
SDL_UpdateWindowSurfaceRects()
SDL_GetWindowTitle()
DECLSPEC const char *SDLCALL SDL_GetWindowTitle (SDL_Window * window) extern
Get the title of a window, in UTF-8 format.
See also
SDL_SetWindowTitle()
SDL_GL_CreateContext()
DECLSPEC SDL_GLContext SDLCALL SDL_GL_CreateContext (SDL_Window * window) extern
Create an OpenGL context for use with an OpenGL window, and make it current.
See also
SDL_GL_DeleteContext()
SDL_GL_DeleteContext()
DECLSPEC void SDLCALL SDL_GL_DeleteContext (SDL_GLContext context) extern
Delete an OpenGL context.
See also
SDL_GL_CreateContext()
SDL_GL_ExtensionSupported()
DECLSPEC SDL_bool SDLCALL SDL_GL_ExtensionSupported (const char * extension) extern
Return true if an OpenGL extension is supported for the current context.
SDL_GL_GetAttribute()
DECLSPEC int SDLCALL SDL_GL_GetAttribute (SDL_GLattr attr, int * value) extern
Get the actual value for an attribute from the current context.
SDL_GL_GetCurrentContext()
DECLSPEC SDL_GLContext SDLCALL SDL_GL_GetCurrentContext (void) extern
Get the currently active OpenGL context.
SDL_GL_GetCurrentWindow()
DECLSPEC SDL_Window *SDLCALL SDL_GL_GetCurrentWindow (void) extern
Get the currently active OpenGL window.
SDL_GL_GetDrawableSize()
DECLSPEC void SDLCALL SDL_GL_GetDrawableSize (SDL_Window * window, int * w, int * h) extern
Get the size of a window's underlying drawable in pixels (for use with glViewport).
Parameters
window Window from which the drawable size should be queried
w Pointer to variable for storing the width in pixels, may be NULL
h Pointer to variable for storing the height in pixels, may be NULL
This may differ from SDL_GetWindowSize() if we're rendering to a high-DPI drawable, i.e. the window was created with SDL_WINDOW_ALLOW_HIGHDPI on a platform with high-DPI support (Apple calls this "Retina"), and not disabled by the SDL_HINT_VIDEO_HIGHDPI_DISABLED hint.
See also
SDL_GetWindowSize()
SDL_CreateWindow()
SDL_GL_GetProcAddress()
DECLSPEC void *SDLCALL SDL_GL_GetProcAddress (const char * proc) extern
Get the address of an OpenGL function.
SDL_GL_GetSwapInterval()
DECLSPEC int SDLCALL SDL_GL_GetSwapInterval (void) extern
Get the swap interval for the current OpenGL context.
Returns
0 if there is no vertical retrace synchronization, 1 if the buffer swap is synchronized with the vertical retrace, and -1 if late swaps happen immediately instead of waiting for the next retrace. If the system can't determine the swap interval, or there isn't a valid current context, this will return 0 as a safe default.
See also
SDL_GL_SetSwapInterval()
SDL_GL_LoadLibrary()
DECLSPEC int SDLCALL SDL_GL_LoadLibrary (const char * path) extern
Dynamically load an OpenGL library.
Parameters
path The platform dependent OpenGL library name, or NULL to open the default OpenGL library.
Returns
0 on success, or -1 if the library couldn't be loaded.
This should be done after initializing the video driver, but before creating any OpenGL windows. If no OpenGL library is loaded, the default library will be loaded upon creation of the first OpenGL window.
Note
If you do this, you need to retrieve all of the GL functions used in your program from the dynamic library using SDL_GL_GetProcAddress().
See also
SDL_GL_GetProcAddress()
SDL_GL_UnloadLibrary()
SDL_GL_MakeCurrent()
DECLSPEC int SDLCALL SDL_GL_MakeCurrent (SDL_Window * window, SDL_GLContext context) extern
Set up an OpenGL context for rendering into an OpenGL window.
Note
The context must have been created with a compatible window.
SDL_GL_ResetAttributes()
DECLSPEC void SDLCALL SDL_GL_ResetAttributes (void) extern
Reset all previously set OpenGL context attributes to their default values.
SDL_GL_SetAttribute()
DECLSPEC int SDLCALL SDL_GL_SetAttribute (SDL_GLattr attr, int value) extern
Set an OpenGL window attribute before window creation.
SDL_GL_SetSwapInterval()
DECLSPEC int SDLCALL SDL_GL_SetSwapInterval (int interval) extern
Set the swap interval for the current OpenGL context.
Parameters
interval 0 for immediate updates, 1 for updates synchronized with the vertical retrace. If the system supports it, you may specify -1 to allow late swaps to happen immediately instead of waiting for the next retrace.
Returns
0 on success, or -1 if setting the swap interval is not supported.
See also
SDL_GL_GetSwapInterval()
SDL_GL_SwapWindow()
DECLSPEC void SDLCALL SDL_GL_SwapWindow (SDL_Window * window) extern
Swap the OpenGL buffers for a window, if double-buffering is supported.
SDL_GL_UnloadLibrary()
DECLSPEC void SDLCALL SDL_GL_UnloadLibrary (void) extern
Unload the OpenGL library previously loaded by SDL_GL_LoadLibrary().
See also
SDL_GL_LoadLibrary()
SDL_HideWindow()
DECLSPEC void SDLCALL SDL_HideWindow (SDL_Window * window) extern
Hide a window.
See also
SDL_ShowWindow()
SDL_IsScreenSaverEnabled()
DECLSPEC SDL_bool SDLCALL SDL_IsScreenSaverEnabled (void) extern
Returns whether the screensaver is currently enabled (default on).
See also
SDL_EnableScreenSaver()
SDL_DisableScreenSaver()
SDL_MaximizeWindow()
DECLSPEC void SDLCALL SDL_MaximizeWindow (SDL_Window * window) extern
Make a window as large as possible.
See also
SDL_RestoreWindow()
SDL_MinimizeWindow()
DECLSPEC void SDLCALL SDL_MinimizeWindow (SDL_Window * window) extern
Minimize a window to an iconic representation.
See also
SDL_RestoreWindow()
SDL_RaiseWindow()
DECLSPEC void SDLCALL SDL_RaiseWindow (SDL_Window * window) extern
Raise a window above other windows and set the input focus.
SDL_RestoreWindow()
DECLSPEC void SDLCALL SDL_RestoreWindow (SDL_Window * window) extern
Restore the size and position of a minimized or maximized window.
See also
SDL_MaximizeWindow()
SDL_MinimizeWindow()
SDL_SetWindowBordered()
DECLSPEC void SDLCALL SDL_SetWindowBordered (SDL_Window * window, SDL_bool bordered) extern
Set the border state of a window.
This will add or remove the window's SDL_WINDOW_BORDERLESS flag and add or remove the border from the actual window. This is a no-op if the window's border already matches the requested state.
Parameters
window The window of which to change the border state.
bordered SDL_FALSE to remove border, SDL_TRUE to add border.
Note
You can't change the border state of a fullscreen window.
See also
SDL_GetWindowFlags()
SDL_SetWindowBrightness()
DECLSPEC int SDLCALL SDL_SetWindowBrightness (SDL_Window * window, float brightness) extern
Set the brightness (gamma correction) for a window.
Returns
0 on success, or -1 if setting the brightness isn't supported.
See also
SDL_GetWindowBrightness()
SDL_SetWindowGammaRamp()
SDL_SetWindowData()
DECLSPEC void *SDLCALL SDL_SetWindowData (SDL_Window * window, const char * name, void * userdata) extern
Associate an arbitrary named pointer with a window.
Parameters
window The window to associate with the pointer.
name The name of the pointer.
userdata The associated pointer.
Returns
The previous value associated with 'name'
Note
The name is case-sensitive.
See also
SDL_GetWindowData()
SDL_SetWindowDisplayMode()
DECLSPEC int SDLCALL SDL_SetWindowDisplayMode (SDL_Window * window, const SDL_DisplayMode * mode) extern
Set the display mode used when a fullscreen window is visible.
By default the window's dimensions and the desktop format and refresh rate are used.
Parameters
window The window for which the display mode should be set.
mode The mode to use, or NULL for the default mode.
Returns
0 on success, or -1 if setting the display mode failed.
See also
SDL_GetWindowDisplayMode()
SDL_SetWindowFullscreen()
SDL_SetWindowFullscreen()
DECLSPEC int SDLCALL SDL_SetWindowFullscreen (SDL_Window * window, Uint32 flags) extern
Set a window's fullscreen state.
Returns
0 on success, or -1 if setting the display mode failed.
See also
SDL_SetWindowDisplayMode()
SDL_GetWindowDisplayMode()
SDL_SetWindowGammaRamp()
DECLSPEC int SDLCALL SDL_SetWindowGammaRamp (SDL_Window * window, const Uint16 * red, const Uint16 * green, const Uint16 * blue) extern
Set the gamma ramp for a window.
Parameters
window The window for which the gamma ramp should be set.
red The translation table for the red channel, or NULL.
green The translation table for the green channel, or NULL.
blue The translation table for the blue channel, or NULL.
Returns
0 on success, or -1 if gamma ramps are unsupported.
Set the gamma translation table for the red, green, and blue channels of the video hardware. Each table is an array of 256 16-bit quantities, representing a mapping between the input and output for that channel. The input is the index into the array, and the output is the 16-bit gamma value at that index, scaled to the output color precision.
See also
SDL_GetWindowGammaRamp()
SDL_SetWindowGrab()
DECLSPEC void SDLCALL SDL_SetWindowGrab (SDL_Window * window, SDL_bool grabbed) extern
Set a window's input grab mode.
Parameters
window The window for which the input grab mode should be set.
grabbed This is SDL_TRUE to grab input, and SDL_FALSE to release input.
If the caller enables a grab while another window is currently grabbed, the other window loses its grab in favor of the caller's window.
See also
SDL_GetWindowGrab()
SDL_SetWindowHitTest()
DECLSPEC int SDLCALL SDL_SetWindowHitTest (SDL_Window * window, SDL_HitTest callback, void * callback_data) extern
Provide a callback that decides if a window region has special properties.
Normally windows are dragged and resized by decorations provided by the system window manager (a title bar, borders, etc), but for some apps, it makes sense to drag them from somewhere else inside the window itself; for example, one might have a borderless window that wants to be draggable from any part, or simulate its own title bar, etc.
This function lets the app provide a callback that designates pieces of a given window as special. This callback is run during event processing if we need to tell the OS to treat a region of the window specially; the use of this callback is known as "hit testing."
Mouse input may not be delivered to your application if it is within a special area; the OS will often apply that input to moving the window or resizing the window and not deliver it to the application.
Specifying NULL for a callback disables hit-testing. Hit-testing is disabled by default.
Platforms that don't support this functionality will return -1 unconditionally, even if you're attempting to disable hit-testing.
Your callback may fire at any time, and its firing does not indicate any specific behavior (for example, on Windows, this certainly might fire when the OS is deciding whether to drag your window, but it fires for lots of other reasons, too, some unrelated to anything you probably care about and when the mouse isn't actually at the location it is testing). Since this can fire at any time, you should try to keep your callback efficient, devoid of allocations, etc.
Parameters
window The window to set hit-testing on.
callback The callback to call when doing a hit-test.
callback_data An app-defined void pointer passed to the callback.
Returns
0 on success, -1 on error (including unsupported).
SDL_SetWindowIcon()
DECLSPEC void SDLCALL SDL_SetWindowIcon (SDL_Window * window, SDL_Surface * icon) extern
Set the icon for a window.
Parameters
window The window for which the icon should be set.
icon The icon for the window.
Referenced by HALSDL2::recreateWindow(), and HALSDL2::sdl_init().
SDL_SetWindowMaximumSize()
DECLSPEC void SDLCALL SDL_SetWindowMaximumSize (SDL_Window * window, int max_w, int max_h) extern
Set the maximum size of a window's client area.
Parameters
window The window to set a new maximum size.
max_w The maximum width of the window, must be >0
max_h The maximum height of the window, must be >0
Note
You can't change the maximum size of a fullscreen window, it automatically matches the size of the display mode.
See also
SDL_GetWindowMaximumSize()
SDL_SetWindowMinimumSize()
SDL_SetWindowMinimumSize()
DECLSPEC void SDLCALL SDL_SetWindowMinimumSize (SDL_Window * window, int min_w, int min_h) extern
Set the minimum size of a window's client area.
Parameters
window The window to set a new minimum size.
min_w The minimum width of the window, must be >0
min_h The minimum height of the window, must be >0
Note
You can't change the minimum size of a fullscreen window, it automatically matches the size of the display mode.
See also
SDL_GetWindowMinimumSize()
SDL_SetWindowMaximumSize()
SDL_SetWindowPosition()
DECLSPEC void SDLCALL SDL_SetWindowPosition (SDL_Window * window, int x, int y) extern
Set the position of a window.
Parameters
window The window to reposition.
x The x coordinate of the window in screen coordinates, or SDL_WINDOWPOS_CENTERED or SDL_WINDOWPOS_UNDEFINED.
y The y coordinate of the window in screen coordinates, or SDL_WINDOWPOS_CENTERED or SDL_WINDOWPOS_UNDEFINED.
Note
The window coordinate origin is the upper left of the display.
See also
SDL_GetWindowPosition()
Referenced by HALSDL2::recreateWindow(), and HALSDL2::taskEntry().
SDL_SetWindowSize()
DECLSPEC void SDLCALL SDL_SetWindowSize (SDL_Window * window, int w, int h) extern
Set the size of a window's client area.
Parameters
window The window to resize.
w The width of the window, in screen coordinates. Must be >0.
h The height of the window, in screen coordinates. Must be >0.
Note
You can't change the size of a fullscreen window, it automatically matches the size of the display mode.
The window size in screen coordinates may differ from the size in pixels, if the window was created with SDL_WINDOW_ALLOW_HIGHDPI on a platform with high-dpi support (e.g. iOS or OS X). Use SDL_GL_GetDrawableSize() or SDL_GetRendererOutputSize() to get the real client area size in pixels.
See also
SDL_GetWindowSize()
Referenced by HALSDL2::recreateWindow().
SDL_SetWindowTitle()
DECLSPEC void SDLCALL SDL_SetWindowTitle (SDL_Window * window, const char * title) extern
Set the title of a window, in UTF-8 format.
See also
SDL_GetWindowTitle()
Referenced by HALSDL2::updateTitle().
SDL_ShowWindow()
DECLSPEC void SDLCALL SDL_ShowWindow (SDL_Window * window) extern
Show a window.
See also
SDL_HideWindow()
SDL_UpdateWindowSurface()
DECLSPEC int SDLCALL SDL_UpdateWindowSurface (SDL_Window * window) extern
Copy the window surface to the screen.
Returns
0 on success, or -1 on error.
See also
SDL_GetWindowSurface()
SDL_UpdateWindowSurfaceRects()
SDL_UpdateWindowSurfaceRects()
DECLSPEC int SDLCALL SDL_UpdateWindowSurfaceRects (SDL_Window * window, const SDL_Rect * rects, int numrects) extern
Copy a number of rectangles on the window surface to the screen.
Returns
0 on success, or -1 on error.
See also
SDL_GetWindowSurface()
SDL_UpdateWindowSurfaceRect()
SDL_VideoInit()
DECLSPEC int SDLCALL SDL_VideoInit (const char * driver_name) extern
Initialize the video subsystem, optionally specifying a video driver.
Parameters
driver_name Initialize a specific driver by name, or NULL for the default video driver.
Returns
0 on success, -1 on error
This function initializes the video subsystem; setting up a connection to the window manager, etc, and determines the available display modes and pixel formats, but does not initialize a window or graphics mode.
See also
SDL_VideoQuit()
SDL_VideoQuit()
DECLSPEC void SDLCALL SDL_VideoQuit (void) extern
Shuts down the video subsystem.
This function closes all windows, and restores the original video mode.
See also
SDL_VideoInit()
Referenced by touchgfx::sdlCleanup2().