Battery Simulator Documentation: C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/platform/hal/simulator/sdl2/vendor/SDL2/SDL_render.h File Reference
SDL_render.h File Reference
#include "SDL_stdinc.h"
#include "SDL_rect.h"
#include "SDL_video.h"
#include "begin_code.h"
#include "close_code.h"
Classes
struct SDL_RendererInfo
Information on the capabilities of a render driver or context.
Typedefs
typedef struct SDL_Renderer SDL_Renderer
typedef struct SDL_RendererInfo SDL_RendererInfo
Information on the capabilities of a render driver or context.
typedef struct SDL_Texture SDL_Texture
Enumerations
enum SDL_RendererFlags { SDL_RENDERER_SOFTWARE = 0x00000001 , SDL_RENDERER_ACCELERATED = 0x00000002 , SDL_RENDERER_PRESENTVSYNC = 0x00000004 , SDL_RENDERER_TARGETTEXTURE = 0x00000008 }
Flags used when creating a rendering context.
enum SDL_RendererFlip { SDL_FLIP_NONE = 0x00000000 , SDL_FLIP_HORIZONTAL = 0x00000001 , SDL_FLIP_VERTICAL = 0x00000002 }
Flip constants for SDL_RenderCopyEx.
enum SDL_TextureAccess { SDL_TEXTUREACCESS_STATIC , SDL_TEXTUREACCESS_STREAMING , SDL_TEXTUREACCESS_TARGET }
The access pattern allowed for a texture.
enum SDL_TextureModulate { SDL_TEXTUREMODULATE_NONE = 0x00000000 , SDL_TEXTUREMODULATE_COLOR = 0x00000001 , SDL_TEXTUREMODULATE_ALPHA = 0x00000002 }
The texture channel modulation used in SDL_RenderCopy().
Functions
DECLSPEC SDL_Renderer *SDLCALL SDL_CreateRenderer (SDL_Window *window, int index, Uint32 flags)
Create a 2D rendering context for a window.
DECLSPEC SDL_Renderer *SDLCALL SDL_CreateSoftwareRenderer (SDL_Surface *surface)
Create a 2D software rendering context for a surface.
DECLSPEC SDL_Texture *SDLCALL SDL_CreateTexture (SDL_Renderer *renderer, Uint32 format, int access, int w, int h)
Create a texture for a rendering context.
DECLSPEC SDL_Texture *SDLCALL SDL_CreateTextureFromSurface (SDL_Renderer *renderer, SDL_Surface *surface)
Create a texture from an existing surface.
DECLSPEC int SDLCALL SDL_CreateWindowAndRenderer (int width, int height, Uint32 window_flags, SDL_Window **window, SDL_Renderer **renderer)
Create a window and default renderer.
DECLSPEC void SDLCALL SDL_DestroyRenderer (SDL_Renderer *renderer)
Destroy the rendering context for a window and free associated textures.
DECLSPEC void SDLCALL SDL_DestroyTexture (SDL_Texture *texture)
Destroy the specified texture.
DECLSPEC int SDLCALL SDL_GetNumRenderDrivers (void)
Get the number of 2D rendering drivers available for the current display.
DECLSPEC int SDLCALL SDL_GetRenderDrawBlendMode (SDL_Renderer *renderer, SDL_BlendMode *blendMode)
Get the blend mode used for drawing operations.
DECLSPEC int SDLCALL SDL_GetRenderDrawColor (SDL_Renderer *renderer, Uint8 *r, Uint8 *g, Uint8 *b, Uint8 *a)
Get the color used for drawing operations (Rect, Line and Clear).
DECLSPEC int SDLCALL SDL_GetRenderDriverInfo (int index, SDL_RendererInfo *info)
Get information about a specific 2D rendering driver for the current display.
DECLSPEC SDL_Renderer *SDLCALL SDL_GetRenderer (SDL_Window *window)
Get the renderer associated with a window.
DECLSPEC int SDLCALL SDL_GetRendererInfo (SDL_Renderer *renderer, SDL_RendererInfo *info)
Get information about a rendering context.
DECLSPEC int SDLCALL SDL_GetRendererOutputSize (SDL_Renderer *renderer, int *w, int *h)
Get the output size in pixels of a rendering context.
DECLSPEC SDL_Texture *SDLCALL SDL_GetRenderTarget (SDL_Renderer *renderer)
Get the current render target or NULL for the default render target.
DECLSPEC int SDLCALL SDL_GetTextureAlphaMod (SDL_Texture *texture, Uint8 *alpha)
Get the additional alpha value used in render copy operations.
DECLSPEC int SDLCALL SDL_GetTextureBlendMode (SDL_Texture *texture, SDL_BlendMode *blendMode)
Get the blend mode used for texture copy operations.
DECLSPEC int SDLCALL SDL_GetTextureColorMod (SDL_Texture *texture, Uint8 *r, Uint8 *g, Uint8 *b)
Get the additional color value used in render copy operations.
DECLSPEC int SDLCALL SDL_GL_BindTexture (SDL_Texture *texture, float *texw, float *texh)
Bind the texture to the current OpenGL/ES/ES2 context for use with OpenGL instructions.
DECLSPEC int SDLCALL SDL_GL_UnbindTexture (SDL_Texture *texture)
Unbind a texture from the current OpenGL/ES/ES2 context.
DECLSPEC int SDLCALL SDL_LockTexture (SDL_Texture *texture, const SDL_Rect *rect, void **pixels, int *pitch)
Lock a portion of the texture for write-only pixel access.
DECLSPEC int SDLCALL SDL_QueryTexture (SDL_Texture *texture, Uint32 *format, int *access, int *w, int *h)
Query the attributes of a texture.
DECLSPEC int SDLCALL SDL_RenderClear (SDL_Renderer *renderer)
Clear the current rendering target with the drawing color.
DECLSPEC int SDLCALL SDL_RenderCopy (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_Rect *srcrect, const SDL_Rect *dstrect)
Copy a portion of the texture to the current rendering target.
DECLSPEC int SDLCALL SDL_RenderCopyEx (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_Rect *srcrect, const SDL_Rect *dstrect, const double angle, const SDL_Point *center, const SDL_RendererFlip flip)
Copy a portion of the source texture to the current rendering target, rotating it by angle around the given center.
DECLSPEC int SDLCALL SDL_RenderDrawLine (SDL_Renderer *renderer, int x1, int y1, int x2, int y2)
Draw a line on the current rendering target.
DECLSPEC int SDLCALL SDL_RenderDrawLines (SDL_Renderer *renderer, const SDL_Point *points, int count)
Draw a series of connected lines on the current rendering target.
DECLSPEC int SDLCALL SDL_RenderDrawPoint (SDL_Renderer *renderer, int x, int y)
Draw a point on the current rendering target.
DECLSPEC int SDLCALL SDL_RenderDrawPoints (SDL_Renderer *renderer, const SDL_Point *points, int count)
Draw multiple points on the current rendering target.
DECLSPEC int SDLCALL SDL_RenderDrawRect (SDL_Renderer *renderer, const SDL_Rect *rect)
Draw a rectangle on the current rendering target.
DECLSPEC int SDLCALL SDL_RenderDrawRects (SDL_Renderer *renderer, const SDL_Rect *rects, int count)
Draw some number of rectangles on the current rendering target.
DECLSPEC int SDLCALL SDL_RenderFillRect (SDL_Renderer *renderer, const SDL_Rect *rect)
Fill a rectangle on the current rendering target with the drawing color.
DECLSPEC int SDLCALL SDL_RenderFillRects (SDL_Renderer *renderer, const SDL_Rect *rects, int count)
Fill some number of rectangles on the current rendering target with the drawing color.
DECLSPEC void SDLCALL SDL_RenderGetClipRect (SDL_Renderer *renderer, SDL_Rect *rect)
Get the clip rectangle for the current target.
DECLSPEC void SDLCALL SDL_RenderGetLogicalSize (SDL_Renderer *renderer, int *w, int *h)
Get device independent resolution for rendering.
DECLSPEC void SDLCALL SDL_RenderGetScale (SDL_Renderer *renderer, float *scaleX, float *scaleY)
Get the drawing scale for the current target.
DECLSPEC void SDLCALL SDL_RenderGetViewport (SDL_Renderer *renderer, SDL_Rect *rect)
Get the drawing area for the current target.
DECLSPEC SDL_bool SDLCALL SDL_RenderIsClipEnabled (SDL_Renderer *renderer)
Get whether clipping is enabled on the given renderer.
DECLSPEC void SDLCALL SDL_RenderPresent (SDL_Renderer *renderer)
Update the screen with rendering performed.
DECLSPEC int SDLCALL SDL_RenderReadPixels (SDL_Renderer *renderer, const SDL_Rect *rect, Uint32 format, void *pixels, int pitch)
Read pixels from the current rendering target.
DECLSPEC int SDLCALL SDL_RenderSetClipRect (SDL_Renderer *renderer, const SDL_Rect *rect)
Set the clip rectangle for the current target.
DECLSPEC int SDLCALL SDL_RenderSetLogicalSize (SDL_Renderer *renderer, int w, int h)
Set device independent resolution for rendering.
DECLSPEC int SDLCALL SDL_RenderSetScale (SDL_Renderer *renderer, float scaleX, float scaleY)
Set the drawing scale for rendering on the current target.
DECLSPEC int SDLCALL SDL_RenderSetViewport (SDL_Renderer *renderer, const SDL_Rect *rect)
Set the drawing area for rendering on the current target.
DECLSPEC SDL_bool SDLCALL SDL_RenderTargetSupported (SDL_Renderer *renderer)
Determines whether a window supports the use of render targets.
DECLSPEC int SDLCALL SDL_SetRenderDrawBlendMode (SDL_Renderer *renderer, SDL_BlendMode blendMode)
Set the blend mode used for drawing operations (Fill and Line).
DECLSPEC int SDLCALL SDL_SetRenderDrawColor (SDL_Renderer *renderer, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
Set the color used for drawing operations (Rect, Line and Clear).
DECLSPEC int SDLCALL SDL_SetRenderTarget (SDL_Renderer *renderer, SDL_Texture *texture)
Set a texture as the current rendering target.
DECLSPEC int SDLCALL SDL_SetTextureAlphaMod (SDL_Texture *texture, Uint8 alpha)
Set an additional alpha value used in render copy operations.
DECLSPEC int SDLCALL SDL_SetTextureBlendMode (SDL_Texture *texture, SDL_BlendMode blendMode)
Set the blend mode used for texture copy operations.
DECLSPEC int SDLCALL SDL_SetTextureColorMod (SDL_Texture *texture, Uint8 r, Uint8 g, Uint8 b)
Set an additional color value used in render copy operations.
DECLSPEC void SDLCALL SDL_UnlockTexture (SDL_Texture *texture)
Unlock a texture, uploading the changes to video memory, if needed.
DECLSPEC int SDLCALL SDL_UpdateTexture (SDL_Texture *texture, const SDL_Rect *rect, const void *pixels, int pitch)
Update the given texture rectangle with new pixel data.
DECLSPEC int SDLCALL SDL_UpdateYUVTexture (SDL_Texture *texture, const SDL_Rect *rect, const Uint8 *Yplane, int Ypitch, const Uint8 *Uplane, int Upitch, const Uint8 *Vplane, int Vpitch)
Update a rectangle within a planar YV12 or IYUV texture with new pixel data.
Detailed Description
Header file for SDL 2D rendering functions.
This API supports the following features:
single pixel points
single pixel lines
filled rectangles
texture images
The primitives may be drawn in opaque, blended, or additive modes.
The texture images may be drawn in opaque, blended, or additive modes. They can have an additional color tint or alpha modulation applied to them, and may also be stretched with linear interpolation.
This API is designed to accelerate simple 2D operations. You may want more functionality such as polygons and particle effects and in that case you should use SDL's OpenGL/Direct3D support or one of the many good 3D engines.
These functions must be called from the main thread. See this bug for details: http://bugzilla.libsdl.org/show_bug.cgi?id=1995
Definition in file SDL_render.h.
Typedef Documentation
SDL_Renderer
typedef struct SDL_Renderer SDL_Renderer
SDL_RendererInfo
typedef struct SDL_RendererInfo SDL_RendererInfo
Information on the capabilities of a render driver or context.
SDL_Texture
typedef struct SDL_Texture SDL_Texture
Enumeration Type Documentation
SDL_RendererFlags
enum SDL_RendererFlags
Flags used when creating a rendering context.
Enumerator
SDL_RENDERER_SOFTWARE
The renderer is a software fallback
SDL_RENDERER_ACCELERATED
The renderer uses hardware acceleration
SDL_RENDERER_PRESENTVSYNC
Present is synchronized with the refresh rate
SDL_RENDERER_TARGETTEXTURE
The renderer supports rendering to texture
{
    SDL_RENDERER_SOFTWARE = 0x00000001,
    SDL_RENDERER_ACCELERATED = 0x00000002,
    SDL_RENDERER_PRESENTVSYNC = 0x00000004,
    SDL_RENDERER_TARGETTEXTURE = 0x00000008
} SDL_RendererFlags;
SDL_RendererFlip
enum SDL_RendererFlip
Flip constants for SDL_RenderCopyEx.
Enumerator
SDL_FLIP_NONE
Do not flip
SDL_FLIP_HORIZONTAL
flip horizontally
SDL_FLIP_VERTICAL
flip vertically
{
    SDL_FLIP_NONE = 0x00000000,
    SDL_FLIP_HORIZONTAL = 0x00000001,
    SDL_FLIP_VERTICAL = 0x00000002
} SDL_RendererFlip;
SDL_TextureAccess
enum SDL_TextureAccess
The access pattern allowed for a texture.
Enumerator
SDL_TEXTUREACCESS_STATIC
Changes rarely, not lockable
SDL_TEXTUREACCESS_STREAMING
Changes frequently, lockable
SDL_TEXTUREACCESS_TARGET
Texture can be used as a render target
{
    SDL_TEXTUREACCESS_STATIC,
    SDL_TEXTUREACCESS_STREAMING,
    SDL_TEXTUREACCESS_TARGET
} SDL_TextureAccess;
SDL_TextureModulate
enum SDL_TextureModulate
The texture channel modulation used in SDL_RenderCopy().
Enumerator
SDL_TEXTUREMODULATE_NONE
No modulation
SDL_TEXTUREMODULATE_COLOR
srcC = srcC * color
SDL_TEXTUREMODULATE_ALPHA
srcA = srcA * alpha
{
    SDL_TEXTUREMODULATE_NONE = 0x00000000,
    SDL_TEXTUREMODULATE_COLOR = 0x00000001,
    SDL_TEXTUREMODULATE_ALPHA = 0x00000002
} SDL_TextureModulate;
Function Documentation
SDL_CreateRenderer()
DECLSPEC SDL_Renderer *SDLCALL SDL_CreateRenderer (SDL_Window * window, int index, Uint32 flags) extern
Create a 2D rendering context for a window.
Parameters
window The window where rendering is displayed.
index The index of the rendering driver to initialize, or -1 to initialize the first one supporting the requested flags.
flags SDL_RendererFlags.
Returns
A valid rendering context or NULL if there was an error.
See also
SDL_CreateSoftwareRenderer()
SDL_GetRendererInfo()
SDL_DestroyRenderer()
Referenced by HALSDL2::recreateWindow().
SDL_CreateSoftwareRenderer()
DECLSPEC SDL_Renderer *SDLCALL SDL_CreateSoftwareRenderer (SDL_Surface * surface) extern
Create a 2D software rendering context for a surface.
Parameters
surface The surface where rendering is done.
Returns
A valid rendering context or NULL if there was an error.
See also
SDL_CreateRenderer()
SDL_DestroyRenderer()
SDL_CreateTexture()
DECLSPEC SDL_Texture *SDLCALL SDL_CreateTexture (SDL_Renderer * renderer, Uint32 format, int access, int w, int h) extern
Create a texture for a rendering context.
Parameters
renderer The renderer.
format The format of the texture.
access One of the enumerated values in SDL_TextureAccess.
w The width of the texture in pixels.
h The height of the texture in pixels.
Returns
The created texture is returned, or NULL if no rendering context was active, the format was unsupported, or the width or height were out of range.
See also
SDL_QueryTexture()
SDL_UpdateTexture()
SDL_DestroyTexture()
SDL_CreateTextureFromSurface()
DECLSPEC SDL_Texture *SDLCALL SDL_CreateTextureFromSurface (SDL_Renderer * renderer, SDL_Surface * surface) extern
Create a texture from an existing surface.
Parameters
renderer The renderer.
surface The surface containing pixel data used to fill the texture.
Returns
The created texture is returned, or NULL on error.
Note
The surface is not modified or freed by this function.
See also
SDL_QueryTexture()
SDL_DestroyTexture()
Referenced by HALSDL2::renderLCD_FrameBufferToMemory().
SDL_CreateWindowAndRenderer()
DECLSPEC int SDLCALL SDL_CreateWindowAndRenderer (int width, int height, Uint32 window_flags, SDL_Window ** window, SDL_Renderer ** renderer) extern
Create a window and default renderer.
Parameters
width The width of the window
height The height of the window
window_flags The flags used to create the window
window A pointer filled with the window, or NULL on error
renderer A pointer filled with the renderer, or NULL on error
Returns
0 on success, or -1 on error
SDL_DestroyRenderer()
DECLSPEC void SDLCALL SDL_DestroyRenderer (SDL_Renderer * renderer) extern
Destroy the rendering context for a window and free associated textures.
See also
SDL_CreateRenderer()
Referenced by HALSDL2::recreateWindow(), and touchgfx::sdlCleanup2().
SDL_DestroyTexture()
DECLSPEC void SDLCALL SDL_DestroyTexture (SDL_Texture * texture) extern
Destroy the specified texture.
See also
SDL_CreateTexture()
SDL_CreateTextureFromSurface()
Referenced by HALSDL2::renderLCD_FrameBufferToMemory().
SDL_GetNumRenderDrivers()
DECLSPEC int SDLCALL SDL_GetNumRenderDrivers (void) extern
Get the number of 2D rendering drivers available for the current display.
A render driver is a set of code that handles rendering and texture management on a particular display. Normally there is only one, but some drivers may have several available with different capabilities.
See also
SDL_GetRenderDriverInfo()
SDL_CreateRenderer()
SDL_GetRenderDrawBlendMode()
DECLSPEC int SDLCALL SDL_GetRenderDrawBlendMode (SDL_Renderer * renderer, SDL_BlendMode * blendMode) extern
Get the blend mode used for drawing operations.
Parameters
renderer The renderer from which blend mode should be queried.
blendMode A pointer filled in with the current blend mode.
Returns
0 on success, or -1 on error
See also
SDL_SetRenderDrawBlendMode()
SDL_GetRenderDrawColor()
DECLSPEC int SDLCALL SDL_GetRenderDrawColor (SDL_Renderer * renderer, Uint8 * r, Uint8 * g, Uint8 * b, Uint8 * a) extern
Get the color used for drawing operations (Rect, Line and Clear).
Parameters
renderer The renderer from which drawing color should be queried.
r A pointer to the red value used to draw on the rendering target.
g A pointer to the green value used to draw on the rendering target.
b A pointer to the blue value used to draw on the rendering target.
a A pointer to the alpha value used to draw on the rendering target, usually SDL_ALPHA_OPAQUE (255).
Returns
0 on success, or -1 on error
SDL_GetRenderDriverInfo()
DECLSPEC int SDLCALL SDL_GetRenderDriverInfo (int index, SDL_RendererInfo * info) extern
Get information about a specific 2D rendering driver for the current display.
Parameters
index The index of the driver to query information about.
info A pointer to an SDL_RendererInfo struct to be filled with information on the rendering driver.
Returns
0 on success, -1 if the index was out of range.
See also
SDL_CreateRenderer()
SDL_GetRenderer()
DECLSPEC SDL_Renderer *SDLCALL SDL_GetRenderer (SDL_Window * window) extern
Get the renderer associated with a window.
SDL_GetRendererInfo()
DECLSPEC int SDLCALL SDL_GetRendererInfo (SDL_Renderer * renderer, SDL_RendererInfo * info) extern
Get information about a rendering context.
SDL_GetRendererOutputSize()
DECLSPEC int SDLCALL SDL_GetRendererOutputSize (SDL_Renderer * renderer, int * w, int * h) extern
Get the output size in pixels of a rendering context.
Referenced by HALSDL2::saveScreenshot().
SDL_GetRenderTarget()
DECLSPEC SDL_Texture *SDLCALL SDL_GetRenderTarget (SDL_Renderer * renderer) extern
Get the current render target or NULL for the default render target.
Returns
The current render target
See also
SDL_SetRenderTarget()
SDL_GetTextureAlphaMod()
DECLSPEC int SDLCALL SDL_GetTextureAlphaMod (SDL_Texture * texture, Uint8 * alpha) extern
Get the additional alpha value used in render copy operations.
Parameters
texture The texture to query.
alpha A pointer filled in with the current alpha value.
Returns
0 on success, or -1 if the texture is not valid.
See also
SDL_SetTextureAlphaMod()
SDL_GetTextureBlendMode()
DECLSPEC int SDLCALL SDL_GetTextureBlendMode (SDL_Texture * texture, SDL_BlendMode * blendMode) extern
Get the blend mode used for texture copy operations.
Parameters
texture The texture to query.
blendMode A pointer filled in with the current blend mode.
Returns
0 on success, or -1 if the texture is not valid.
See also
SDL_SetTextureBlendMode()
SDL_GetTextureColorMod()
DECLSPEC int SDLCALL SDL_GetTextureColorMod (SDL_Texture * texture, Uint8 * r, Uint8 * g, Uint8 * b) extern
Get the additional color value used in render copy operations.
Parameters
texture The texture to query.
r A pointer filled in with the current red color value.
g A pointer filled in with the current green color value.
b A pointer filled in with the current blue color value.
Returns
0 on success, or -1 if the texture is not valid.
See also
SDL_SetTextureColorMod()
SDL_GL_BindTexture()
DECLSPEC int SDLCALL SDL_GL_BindTexture (SDL_Texture * texture, float * texw, float * texh) extern
Bind the texture to the current OpenGL/ES/ES2 context for use with OpenGL instructions.
Parameters
texture The SDL texture to bind
texw A pointer to a float that will be filled with the texture width
texh A pointer to a float that will be filled with the texture height
Returns
0 on success, or -1 if the operation is not supported
SDL_GL_UnbindTexture()
DECLSPEC int SDLCALL SDL_GL_UnbindTexture (SDL_Texture * texture) extern
Unbind a texture from the current OpenGL/ES/ES2 context.
Parameters
texture The SDL texture to unbind
Returns
0 on success, or -1 if the operation is not supported
SDL_LockTexture()
DECLSPEC int SDLCALL SDL_LockTexture (SDL_Texture * texture, const SDL_Rect * rect, void ** pixels, int * pitch) extern
Lock a portion of the texture for write-only pixel access.
Parameters
texture The texture to lock for access, which was created with SDL_TEXTUREACCESS_STREAMING.
rect A pointer to the rectangle to lock for access. If the rect is NULL, the entire texture will be locked.
pixels This is filled in with a pointer to the locked pixels, appropriately offset by the locked area.
pitch This is filled in with the pitch of the locked pixels.
Returns
0 on success, or -1 if the texture is not valid or was not created with SDL_TEXTUREACCESS_STREAMING.
See also
SDL_UnlockTexture()
SDL_QueryTexture()
DECLSPEC int SDLCALL SDL_QueryTexture (SDL_Texture * texture, Uint32 * format, int * access, int * w, int * h) extern
Query the attributes of a texture.
Parameters
texture A texture to be queried.
format A pointer filled in with the raw format of the texture. The actual format may differ, but pixel transfers will use this format.
access A pointer filled in with the actual access to the texture.
w A pointer filled in with the width of the texture in pixels.
h A pointer filled in with the height of the texture in pixels.
Returns
0 on success, or -1 if the texture is not valid.
SDL_RenderClear()
DECLSPEC int SDLCALL SDL_RenderClear (SDL_Renderer * renderer) extern
Clear the current rendering target with the drawing color.
This function clears the entire rendering target, ignoring the viewport.
Returns
0 on success, or -1 on error
Referenced by HALSDL2::renderLCD_FrameBufferToMemory().
SDL_RenderCopy()
DECLSPEC int SDLCALL SDL_RenderCopy (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_Rect * srcrect, const SDL_Rect * dstrect) extern
Copy a portion of the texture to the current rendering target.
Parameters
renderer The renderer which should copy parts of a texture.
texture The source texture.
srcrect A pointer to the source rectangle, or NULL for the entire texture.
dstrect A pointer to the destination rectangle, or NULL for the entire rendering target.
Returns
0 on success, or -1 on error
Referenced by HALSDL2::renderLCD_FrameBufferToMemory().
SDL_RenderCopyEx()
DECLSPEC int SDLCALL SDL_RenderCopyEx (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_Rect * srcrect, const SDL_Rect * dstrect, const double angle, const SDL_Point * center, const SDL_RendererFlip flip) extern
Copy a portion of the source texture to the current rendering target, rotating it by angle around the given center.
Parameters
renderer The renderer which should copy parts of a texture.
texture The source texture.
srcrect A pointer to the source rectangle, or NULL for the entire texture.
dstrect A pointer to the destination rectangle, or NULL for the entire rendering target.
angle An angle in degrees that indicates the rotation that will be applied to dstrect
center A pointer to a point indicating the point around which dstrect will be rotated (if NULL, rotation will be done around dstrect.w/2, dstrect.h/2).
flip An SDL_RendererFlip value stating which flipping actions should be performed on the texture
Returns
0 on success, or -1 on error
SDL_RenderDrawLine()
DECLSPEC int SDLCALL SDL_RenderDrawLine (SDL_Renderer * renderer, int x1, int y1, int x2, int y2) extern
Draw a line on the current rendering target.
Parameters
renderer The renderer which should draw a line.
x1 The x coordinate of the start point.
y1 The y coordinate of the start point.
x2 The x coordinate of the end point.
y2 The y coordinate of the end point.
Returns
0 on success, or -1 on error
SDL_RenderDrawLines()
DECLSPEC int SDLCALL SDL_RenderDrawLines (SDL_Renderer * renderer, const SDL_Point * points, int count) extern
Draw a series of connected lines on the current rendering target.
Parameters
renderer The renderer which should draw multiple lines.
points The points along the lines
count The number of points, drawing count-1 lines
Returns
0 on success, or -1 on error
SDL_RenderDrawPoint()
DECLSPEC int SDLCALL SDL_RenderDrawPoint (SDL_Renderer * renderer, int x, int y) extern
Draw a point on the current rendering target.
Parameters
renderer The renderer which should draw a point.
x The x coordinate of the point.
y The y coordinate of the point.
Returns
0 on success, or -1 on error
SDL_RenderDrawPoints()
DECLSPEC int SDLCALL SDL_RenderDrawPoints (SDL_Renderer * renderer, const SDL_Point * points, int count) extern
Draw multiple points on the current rendering target.
Parameters
renderer The renderer which should draw multiple points.
points The points to draw
count The number of points to draw
Returns
0 on success, or -1 on error
SDL_RenderDrawRect()
DECLSPEC int SDLCALL SDL_RenderDrawRect (SDL_Renderer * renderer, const SDL_Rect * rect) extern
Draw a rectangle on the current rendering target.
Parameters
renderer The renderer which should draw a rectangle.
rect A pointer to the destination rectangle, or NULL to outline the entire rendering target.
Returns
0 on success, or -1 on error
SDL_RenderDrawRects()
DECLSPEC int SDLCALL SDL_RenderDrawRects (SDL_Renderer * renderer, const SDL_Rect * rects, int count) extern
Draw some number of rectangles on the current rendering target.
Parameters
renderer The renderer which should draw multiple rectangles.
rects A pointer to an array of destination rectangles.
count The number of rectangles.
Returns
0 on success, or -1 on error
SDL_RenderFillRect()
DECLSPEC int SDLCALL SDL_RenderFillRect (SDL_Renderer * renderer, const SDL_Rect * rect) extern
Fill a rectangle on the current rendering target with the drawing color.
Parameters
renderer The renderer which should fill a rectangle.
rect A pointer to the destination rectangle, or NULL for the entire rendering target.
Returns
0 on success, or -1 on error
Referenced by HALSDL2::flushFrameBuffer().
SDL_RenderFillRects()
DECLSPEC int SDLCALL SDL_RenderFillRects (SDL_Renderer * renderer, const SDL_Rect * rects, int count) extern
Fill some number of rectangles on the current rendering target with the drawing color.
Parameters
renderer The renderer which should fill multiple rectangles.
rects A pointer to an array of destination rectangles.
count The number of rectangles.
Returns
0 on success, or -1 on error
SDL_RenderGetClipRect()
DECLSPEC void SDLCALL SDL_RenderGetClipRect (SDL_Renderer * renderer, SDL_Rect * rect) extern
Get the clip rectangle for the current target.
Parameters
renderer The renderer from which clip rectangle should be queried.
rect A pointer filled in with the current clip rectangle, or an empty rectangle if clipping is disabled.
See also
SDL_RenderSetClipRect()
SDL_RenderGetLogicalSize()
DECLSPEC void SDLCALL SDL_RenderGetLogicalSize (SDL_Renderer * renderer, int * w, int * h) extern
Get device independent resolution for rendering.
Parameters
renderer The renderer from which resolution should be queried.
w A pointer filled with the width of the logical resolution
h A pointer filled with the height of the logical resolution
See also
SDL_RenderSetLogicalSize()
SDL_RenderGetScale()
DECLSPEC void SDLCALL SDL_RenderGetScale (SDL_Renderer * renderer, float * scaleX, float * scaleY) extern
Get the drawing scale for the current target.
Parameters
renderer The renderer from which drawing scale should be queried.
scaleX A pointer filled in with the horizontal scaling factor
scaleY A pointer filled in with the vertical scaling factor
See also
SDL_RenderSetScale()
SDL_RenderGetViewport()
DECLSPEC void SDLCALL SDL_RenderGetViewport (SDL_Renderer * renderer, SDL_Rect * rect) extern
Get the drawing area for the current target.
See also
SDL_RenderSetViewport()
SDL_RenderIsClipEnabled()
DECLSPEC SDL_bool SDLCALL SDL_RenderIsClipEnabled (SDL_Renderer * renderer) extern
Get whether clipping is enabled on the given renderer.
Parameters
renderer The renderer from which clip state should be queried.
See also
SDL_RenderGetClipRect()
SDL_RenderPresent()
DECLSPEC void SDLCALL SDL_RenderPresent (SDL_Renderer * renderer) extern
Update the screen with rendering performed.
Referenced by HALSDL2::flushFrameBuffer(), and HALSDL2::renderLCD_FrameBufferToMemory().
SDL_RenderReadPixels()
DECLSPEC int SDLCALL SDL_RenderReadPixels (SDL_Renderer * renderer, const SDL_Rect * rect, Uint32 format, void * pixels, int pitch) extern
Read pixels from the current rendering target.
Parameters
renderer The renderer from which pixels should be read.
rect A pointer to the rectangle to read, or NULL for the entire render target.
format The desired format of the pixel data, or 0 to use the format of the rendering target
pixels A pointer to be filled in with the pixel data
pitch The pitch of the pixels parameter.
Returns
0 on success, or -1 if pixel reading is not supported.
Warning
This is a very slow operation, and should not be used frequently.
Referenced by HALSDL2::saveScreenshot().
SDL_RenderSetClipRect()
DECLSPEC int SDLCALL SDL_RenderSetClipRect (SDL_Renderer * renderer, const SDL_Rect * rect) extern
Set the clip rectangle for the current target.
Parameters
renderer The renderer for which clip rectangle should be set.
rect A pointer to the rectangle to set as the clip rectangle, or NULL to disable clipping.
Returns
0 on success, or -1 on error
See also
SDL_RenderGetClipRect()
SDL_RenderSetLogicalSize()
DECLSPEC int SDLCALL SDL_RenderSetLogicalSize (SDL_Renderer * renderer, int w, int h) extern
Set device independent resolution for rendering.
Parameters
renderer The renderer for which resolution should be set.
w The width of the logical resolution
h The height of the logical resolution
This function uses the viewport and scaling functionality to allow a fixed logical resolution for rendering, regardless of the actual output resolution. If the actual output resolution doesn't have the same aspect ratio the output rendering will be centered within the output display.
If the output display is a window, mouse events in the window will be filtered and scaled so they seem to arrive within the logical resolution.
Note
If this function results in scaling or subpixel drawing by the rendering backend, it will be handled using the appropriate quality hints.
See also
SDL_RenderGetLogicalSize()
SDL_RenderSetScale()
SDL_RenderSetViewport()
SDL_RenderSetScale()
DECLSPEC int SDLCALL SDL_RenderSetScale (SDL_Renderer * renderer, float scaleX, float scaleY) extern
Set the drawing scale for rendering on the current target.
Parameters
renderer The renderer for which the drawing scale should be set.
scaleX The horizontal scaling factor
scaleY The vertical scaling factor
The drawing coordinates are scaled by the x/y scaling factors before they are used by the renderer. This allows resolution independent drawing with a single coordinate system.
Note
If this results in scaling or subpixel drawing by the rendering backend, it will be handled using the appropriate quality hints. For best results use integer scaling factors.
See also
SDL_RenderGetScale()
SDL_RenderSetLogicalSize()
SDL_RenderSetViewport()
DECLSPEC int SDLCALL SDL_RenderSetViewport (SDL_Renderer * renderer, const SDL_Rect * rect) extern
Set the drawing area for rendering on the current target.
Parameters
renderer The renderer for which the drawing area should be set.
rect The rectangle representing the drawing area, or NULL to set the viewport to the entire target.
The x,y of the viewport rect represents the origin for rendering.
Returns
0 on success, or -1 on error
Note
If the window associated with the renderer is resized, the viewport is automatically reset.
See also
SDL_RenderGetViewport()
SDL_RenderSetLogicalSize()
SDL_RenderTargetSupported()
DECLSPEC SDL_bool SDLCALL SDL_RenderTargetSupported (SDL_Renderer * renderer) extern
Determines whether a window supports the use of render targets.
Parameters
renderer The renderer that will be checked
Returns
SDL_TRUE if supported, SDL_FALSE if not.
SDL_SetRenderDrawBlendMode()
DECLSPEC int SDLCALL SDL_SetRenderDrawBlendMode (SDL_Renderer * renderer, SDL_BlendMode blendMode) extern
Set the blend mode used for drawing operations (Fill and Line).
Parameters
renderer The renderer for which blend mode should be set.
blendMode SDL_BlendMode to use for blending.
Returns
0 on success, or -1 on error
Note
If the blend mode is not supported, the closest supported mode is chosen.
See also
SDL_GetRenderDrawBlendMode()
Referenced by HALSDL2::flushFrameBuffer(), and HALSDL2::recreateWindow().
SDL_SetRenderDrawColor()
DECLSPEC int SDLCALL SDL_SetRenderDrawColor (SDL_Renderer * renderer, Uint8 r, Uint8 g, Uint8 b, Uint8 a) extern
Set the color used for drawing operations (Rect, Line and Clear).
Parameters
renderer The renderer for which drawing color should be set.
r The red value used to draw on the rendering target.
g The green value used to draw on the rendering target.
b The blue value used to draw on the rendering target.
a The alpha value used to draw on the rendering target, usually SDL_ALPHA_OPAQUE (255).
Returns
0 on success, or -1 on error
Referenced by HALSDL2::flushFrameBuffer().
SDL_SetRenderTarget()
DECLSPEC int SDLCALL SDL_SetRenderTarget (SDL_Renderer * renderer, SDL_Texture * texture) extern
Set a texture as the current rendering target.
Parameters
renderer The renderer.
texture The targeted texture, which must be created with the SDL_TEXTUREACCESS_TARGET flag, or NULL for the default render target
Returns
0 on success, or -1 on error
See also
SDL_GetRenderTarget()
SDL_SetTextureAlphaMod()
DECLSPEC int SDLCALL SDL_SetTextureAlphaMod (SDL_Texture * texture, Uint8 alpha) extern
Set an additional alpha value used in render copy operations.
Parameters
texture The texture to update.
alpha The alpha value multiplied into copy operations.
Returns
0 on success, or -1 if the texture is not valid or alpha modulation is not supported.
See also
SDL_GetTextureAlphaMod()
SDL_SetTextureBlendMode()
DECLSPEC int SDLCALL SDL_SetTextureBlendMode (SDL_Texture * texture, SDL_BlendMode blendMode) extern
Set the blend mode used for texture copy operations.
Parameters
texture The texture to update.
blendMode SDL_BlendMode to use for texture blending.
Returns
0 on success, or -1 if the texture is not valid or the blend mode is not supported.
Note
If the blend mode is not supported, the closest supported mode is chosen.
See also
SDL_GetTextureBlendMode()
SDL_SetTextureColorMod()
DECLSPEC int SDLCALL SDL_SetTextureColorMod (SDL_Texture * texture, Uint8 r, Uint8 g, Uint8 b) extern
Set an additional color value used in render copy operations.
Parameters
texture The texture to update.
r The red color value multiplied into copy operations.
g The green color value multiplied into copy operations.
b The blue color value multiplied into copy operations.
Returns
0 on success, or -1 if the texture is not valid or color modulation is not supported.
See also
SDL_GetTextureColorMod()
SDL_UnlockTexture()
DECLSPEC void SDLCALL SDL_UnlockTexture (SDL_Texture * texture) extern
Unlock a texture, uploading the changes to video memory, if needed.
See also
SDL_LockTexture()
SDL_UpdateTexture()
DECLSPEC int SDLCALL SDL_UpdateTexture (SDL_Texture * texture, const SDL_Rect * rect, const void * pixels, int pitch) extern
Update the given texture rectangle with new pixel data.
Parameters
texture The texture to update
rect A pointer to the rectangle of pixels to update, or NULL to update the entire texture.
pixels The raw pixel data.
pitch The number of bytes in a row of pixel data, including padding between lines.
Returns
0 on success, or -1 if the texture is not valid.
Note
This is a fairly slow function.
SDL_UpdateYUVTexture()
DECLSPEC int SDLCALL SDL_UpdateYUVTexture (SDL_Texture * texture, const SDL_Rect * rect, const Uint8 * Yplane, int Ypitch, const Uint8 * Uplane, int Upitch, const Uint8 * Vplane, int Vpitch) extern
Update a rectangle within a planar YV12 or IYUV texture with new pixel data.
Parameters
texture The texture to update
rect A pointer to the rectangle of pixels to update, or NULL to update the entire texture.
Yplane The raw pixel data for the Y plane.
Ypitch The number of bytes between rows of pixel data for the Y plane.
Uplane The raw pixel data for the U plane.
Upitch The number of bytes between rows of pixel data for the U plane.
Vplane The raw pixel data for the V plane.
Vpitch The number of bytes between rows of pixel data for the V plane.
Returns
0 on success, or -1 if the texture is not valid.
Note
You can use SDL_UpdateTexture() as long as your pixel data is a contiguous block of Y and U/V planes in the proper order, but this function is available if your pixel data is not contiguous.