Battery Simulator Documentation: C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/target/generated/STM32DMA.cpp File Reference
STM32DMA.cpp File Reference
#include "stm32h7xx_hal.h"
#include "stm32h7xx_hal_dma2d.h"
#include <STM32DMA.hpp>
#include <cassert>
#include <touchgfx/Color.hpp>
#include <touchgfx/hal/HAL.hpp>
#include <touchgfx/hal/Paint.hpp>
#include <touchgfx/lcd/LCD.hpp>
Classes
struct clutData_t
Namespaces
namespace touchgfx
namespace touchgfx::paint
namespace touchgfx::paint::anonymous_namespace{STM32DMA.cpp}
namespace touchgfx::paint::rgb888
Functions
static void DMA2D_XferCpltCallback (DMA2D_HandleTypeDef *handle)
void lineFromARGB8888 (uint8_t *const ptr, const uint32_t *const data, const unsigned count, const uint8_t alpha)
void lineFromColor (uint8_t *const ptr, const unsigned count, const uint32_t color, const uint8_t alpha)
void lineFromL8ARGB8888 (uint8_t *const ptr, const uint8_t *const data, const unsigned count, const uint8_t alpha)
void lineFromL8RGB888 (uint8_t *const ptr, const uint8_t *const data, const unsigned count, const uint8_t alpha)
void lineFromRGB888 (uint8_t *const ptr, const uint8_t *const data, const unsigned count, const uint8_t alpha)
void setL8Palette (const uint8_t *const data)
void tearDown (void)
Waits until previous DMA drawing operation has finished.
Variables
DMA2D_HandleTypeDef hdma2d
const clutData_t * L8CLUT = 0
uint32_t L8ClutLoaded = 0
Function Documentation
DMA2D_XferCpltCallback()
static void DMA2D_XferCpltCallback (DMA2D_HandleTypeDef * handle) static
    {
        (void)handle; // Unused argument
        HAL::getInstance()->signalDMAInterrupt();
    }
References HAL::getInstance(), and void().
Referenced by STM32DMA::initialize().
Variable Documentation
hdma2d
DMA2D_HandleTypeDef hdma2d
Referenced by DMA2D_IRQHandler(), and STM32DMA::initialize().