Battery Simulator Documentation: C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/target/generated/TouchGFXGeneratedHAL.cpp File Reference
TouchGFXGeneratedHAL.cpp File Reference
#include <TouchGFXGeneratedHAL.hpp>
#include <touchgfx/hal/OSWrappers.hpp>
#include <gui/common/FrontendHeap.hpp>
#include <touchgfx/hal/GPIO.hpp>
#include <touchgfx/widgets/canvas/CWRVectorRenderer.hpp>
#include <HardwareMJPEGDecoder.hpp>
#include <DoubleBufferedVideoController.hpp>
#include <stm32h7xx_hal.h>
#include "stm32h7xx.h"
#include "stm32h7xx_hal_ltdc.h"
Namespaces
namespace anonymous_namespace{TouchGFXGeneratedHAL.cpp}
namespace touchgfx
Functions
void HAL_LTDC_LineEventCallback (LTDC_HandleTypeDef *hltdc)
LOCATION_PRAGMA_NOLOAD ("Video_RGB_Buffer") uint32_t videoRGBBuffer[576000] LOCATION_ATTRIBUTE_NOLOAD("Video_RGB_Buffer")
void videoTaskFunc (void *argument)
Variables
static uint16_t lcd_int_active_line
static uint16_t lcd_int_porch_line
HardwareMJPEGDecoder mjpegdecoder1
DoubleBufferedVideoController< 1, 800, 480, 800 *3U, Bitmap::RGB888 > videoController
Function Documentation
HAL_LTDC_LineEventCallback()
void HAL_LTDC_LineEventCallback (LTDC_HandleTypeDef * hltdc)
    {
        if (!HAL::getInstance())
        {
            return;
        }
        if (LTDC->LIPCR == lcd_int_active_line)
        {
            //entering active area
            HAL_LTDC_ProgramLineEvent(hltdc, lcd_int_porch_line);
            HAL::getInstance()->vSync();
            OSWrappers::signalVSync();
            // Swap frame buffers immediately instead of waiting for the task to be scheduled in.
            // Note: task will also swap when it wakes up, but that operation is guarded and will not have
            // any effect if already swapped.
            HAL::getInstance()->swapFrameBuffers();
            GPIO::set(GPIO::VSYNC_FREQ);
        }
        else
        {
            //exiting active area
            HAL_LTDC_ProgramLineEvent(hltdc, lcd_int_active_line);
            // Signal to the framework that display update has finished.
            HAL::getInstance()->frontPorchEntered();
            GPIO::clear(GPIO::VSYNC_FREQ);
        }
    }
References GPIO::clear(), HAL::getInstance(), hltdc, anonymous_namespace{TouchGFXGeneratedHAL.cpp}::lcd_int_active_line, anonymous_namespace{TouchGFXGeneratedHAL.cpp}::lcd_int_porch_line, GPIO::set(), OSWrappers::signalVSync(), and GPIO::VSYNC_FREQ.
videoTaskFunc()
void videoTaskFunc (void * argument)
{
    videoController.decoderTaskEntry();
}
References anonymous_namespace{TouchGFXGeneratedHAL.cpp}::videoController.
Referenced by MX_FREERTOS_Init().
Variable Documentation
mjpegdecoder1
HardwareMJPEGDecoder mjpegdecoder1
File Name : TouchGFXGeneratedHAL.cpp
This file is generated by TouchGFX Generator 4.23.1. Please, do not edit!
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Referenced by TouchGFXGeneratedHAL::initialize().