Battery Simulator Documentation: C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/target/generated/TouchGFXConfiguration.cpp File Reference
TouchGFXConfiguration.cpp File Reference
#include <texts/TypedTextDatabase.hpp>
#include <fonts/ApplicationFontProvider.hpp>
#include <gui/common/FrontendHeap.hpp>
#include <BitmapDatabase.hpp>
#include <touchgfx/VectorFontRendererImpl.hpp>
#include <platform/driver/lcd/LCD24bpp.hpp>
#include <STM32DMA.hpp>
#include <TouchGFXHAL.hpp>
#include <STM32TouchController.hpp>
#include <stm32h7xx_hal.h>
Functions
static TouchGFXHAL hal (dma, display, tc, 1024, 600)
void touchgfx_components_init ()
void touchgfx_init ()
void touchgfx_taskEntry ()
Variables
static LCD24bpp display
static STM32DMA dma
static ApplicationFontProvider fontProvider
static STM32TouchController tc
static Texts texts
static VectorFontRendererImpl vectorFontRenderer
Function Documentation
hal()
static TouchGFXHAL hal (dma , display , tc , 1024 , 600) static
Referenced by setupSimulator(), touchgfx::simulator_enable_stdio(), touchgfx::simulator_printf(), touchgfx::touchgfx_generic_init(), touchgfx::touchgfx_init(), touchgfx_taskEntry(), and WinMain().
touchgfx_components_init()
void touchgfx_components_init (void)
{
}
Referenced by MX_TouchGFX_Init().
touchgfx_init()
void touchgfx_init (void)
File Name : TouchGFXConfiguration.cpp
This file is generated by TouchGFX Generator 4.23.1. Please, do not edit!
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
{
    Bitmap::registerBitmapDatabase(BitmapDatabase::getInstance(), BitmapDatabase::getInstanceSize());
    TypedText::registerTexts(&texts);
    Texts::setLanguage(0);
    display.setVectorFontRenderer(&vectorFontRenderer);
    FontManager::setFontProvider(&fontProvider);
    FrontendHeap& heap = FrontendHeap::getInstance();
    /*
     * we need to obtain the reference above to initialize the frontend heap.
     */
    (void)heap;
    /*
     * Initialize TouchGFX
     */
    hal.initialize();
}
Referenced by MX_TouchGFX_Init().
touchgfx_taskEntry()
void touchgfx_taskEntry (void)
{
    /*
     * Main event loop. Will wait for VSYNC signal, and then process next frame. Call
     * this function from your GUI task.
     *
     * Note This function never returns
     */
    hal.taskEntry();
}
References hal().
Referenced by MX_TouchGFX_Process(), and TouchGFX_Task().
Variable Documentation
display
LCD24bpp display static
Referenced by HALSDL2::flushFrameBuffer(), HALSDL2::recreateWindow(), HALSDL2::taskEntry(), touchgfx::touchgfx_generic_init(), and touchgfx::touchgfx_init().
dma
STM32DMA dma static
Referenced by touchgfx::touchgfx_generic_init(), and WinMain().
fontProvider
ApplicationFontProvider fontProvider static
Referenced by touchgfx::touchgfx_init().
tc
STM32TouchController tc static
texts
Texts texts static
Referenced by touchgfx::touchgfx_generic_init(), and touchgfx::touchgfx_init().
vectorFontRenderer
VectorFontRendererImpl vectorFontRenderer static
Referenced by touchgfx::touchgfx_init().