Battery Simulator Documentation: C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/texts/src/TypedTextDatabase.cpp File Reference
TypedTextDatabase.cpp File Reference
#include <touchgfx/TypedText.hpp>
#include <fonts/GeneratedFont.hpp>
#include <texts/TypedTextDatabase.hpp>
Namespaces
namespace TypedTextDatabase
Functions
touchgfx::GeneratedFont & getFont_verdana_10_4bpp ()
touchgfx::GeneratedFont & getFont_verdana_20_4bpp ()
touchgfx::GeneratedFont & getFont_verdana_40_4bpp ()
const touchgfx::Font ** getFonts ()
const touchgfx::TypedText::TypedTextData * getInstance (touchgfx::LanguageId id)
uint16_t getInstanceSize ()
void resetFont (touchgfx::FontId fontId)
const touchgfx::Font * setFont (touchgfx::FontId fontId, const touchgfx::Font *)
Variables
TEXT_LOCATION_FLASH_PRAGMA const touchgfx::TypedText::TypedTextData typedText_database_DEFAULT[] TEXT_LOCATION_FLASH_ATTRIBUTE
const touchgfx::Font * touchgfx_fonts []
const touchgfx::TypedText::TypedTextData typedText_database_DEFAULT []
const touchgfx::TypedText::TypedTextData *const typedTextDatabaseArray []
Function Documentation
getFont_verdana_10_4bpp()
touchgfx::GeneratedFont & getFont_verdana_10_4bpp () extern
{
    static touchgfx::GeneratedFont verdana_10_4bpp(glyphs_verdana_10_4bpp, 1, 10, 10, 0, 0, 4, 0, 0, 0, unicodes_verdana_10_4bpp, kerning_verdana_10_4bpp, 63, 0, 0, 0);
    return verdana_10_4bpp;
}
Referenced by TypedTextDatabase::resetFont().
getFont_verdana_20_4bpp()
touchgfx::GeneratedFont & getFont_verdana_20_4bpp () extern
{
    static touchgfx::GeneratedFont verdana_20_4bpp(glyphs_verdana_20_4bpp, 1, 20, 20, 0, 0, 4, 0, 0, 0, unicodes_verdana_20_4bpp, kerning_verdana_20_4bpp, 63, 0, 0, 0);
    return verdana_20_4bpp;
}
Referenced by TypedTextDatabase::resetFont().
getFont_verdana_40_4bpp()
touchgfx::GeneratedFont & getFont_verdana_40_4bpp () extern
{
    static touchgfx::GeneratedFont verdana_40_4bpp(glyphs_verdana_40_4bpp, 1, 40, 40, 0, 0, 4, 0, 0, 0, unicodes_verdana_40_4bpp, kerning_verdana_40_4bpp, 63, 0, 0, 0);
    return verdana_40_4bpp;
}
Referenced by TypedTextDatabase::resetFont().
Variable Documentation
TEXT_LOCATION_FLASH_ATTRIBUTE
TEXT_LOCATION_FLASH_PRAGMA const touchgfx::TypedText::TypedTextData* const typedTextDatabaseArray [] TEXT_LOCATION_FLASH_ATTRIBUTE
Initial value:
= {
    { 0, touchgfx::LEFT, touchgfx::TEXT_DIRECTION_LTR }
}
{
    { 0, touchgfx::LEFT, touchgfx::TEXT_DIRECTION_LTR }
};
touchgfx_fonts
const touchgfx::Font* touchgfx_fonts[]
Initial value:
= {
    &(getFont_verdana_20_4bpp()),
    &(getFont_verdana_40_4bpp()),
    &(getFont_verdana_10_4bpp())
}
{
    &(getFont_verdana_20_4bpp()),
    &(getFont_verdana_40_4bpp()),
    &(getFont_verdana_10_4bpp())
};
Referenced by TypedTextDatabase::getFonts(), TypedTextDatabase::resetFont(), and TypedTextDatabase::setFont().
typedText_database_DEFAULT
const touchgfx::TypedText::TypedTextData typedText_database_DEFAULT[] extern
typedTextDatabaseArray
const touchgfx::TypedText::TypedTextData* const typedTextDatabaseArray[] extern