Battery Simulator Documentation: C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/App/app_touchgfx.c File Reference
app_touchgfx.c File Reference
#include "app_touchgfx.h"
Functions
void MX_TouchGFX_Init (void)
void MX_TouchGFX_PreOSInit (void)
void MX_TouchGFX_Process (void)
void touchgfx_components_init (void)
void touchgfx_init (void)
void TouchGFX_Task (void *argument)
void touchgfx_taskEntry (void)
Function Documentation
MX_TouchGFX_Init()
void MX_TouchGFX_Init (void)
Initialize TouchGFX application
{
    // Calling forward to touchgfx_init in C++ domain
    touchgfx_components_init();
    touchgfx_init();
}
References touchgfx_components_init(), and touchgfx_init().
Referenced by main().
MX_TouchGFX_PreOSInit()
void MX_TouchGFX_PreOSInit (void)
PreOS Initialization function
{
}
Referenced by main().
MX_TouchGFX_Process()
void MX_TouchGFX_Process (void)
TouchGFX application entry function
{
    // Calling forward to touchgfx_taskEntry in C++ domain
    touchgfx_taskEntry();
}
References touchgfx_taskEntry().
touchgfx_components_init()
void touchgfx_components_init (void)
{
}
Referenced by MX_TouchGFX_Init().
touchgfx_init()
void touchgfx_init (void)
File Name : app_touchgfx.c
This file was created by TouchGFX Generator 4.23.1. This file is only generated once! Delete this file from your project and re-generate code using STM32CubeMX or change this file manually to update it.
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
File Name : TouchGFXConfiguration.cpp
This file is generated by TouchGFX Generator 4.23.1. Please, do not edit!
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
{
    Bitmap::registerBitmapDatabase(BitmapDatabase::getInstance(), BitmapDatabase::getInstanceSize());
    TypedText::registerTexts(&texts);
    Texts::setLanguage(0);
    display.setVectorFontRenderer(&vectorFontRenderer);
    FontManager::setFontProvider(&fontProvider);
    FrontendHeap& heap = FrontendHeap::getInstance();
    /*
     * we need to obtain the reference above to initialize the frontend heap.
     */
    (void)heap;
    /*
     * Initialize TouchGFX
     */
    hal.initialize();
}
Referenced by MX_TouchGFX_Init().
TouchGFX_Task()
void TouchGFX_Task (void * argument)
TouchGFX application thread
{
    // Calling forward to touchgfx_taskEntry in C++ domain
    touchgfx_taskEntry();
}
References touchgfx_taskEntry().
Referenced by MX_FREERTOS_Init().
touchgfx_taskEntry()
void touchgfx_taskEntry (void)
{
    /*
     * Main event loop. Will wait for VSYNC signal, and then process next frame. Call
     * this function from your GUI task.
     *
     * Note This function never returns
     */
    hal.taskEntry();
}
References hal().
Referenced by MX_TouchGFX_Process(), and TouchGFX_Task().