Battery Simulator Documentation: C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/App/app_touchgfx.h File Reference
app_touchgfx.h File Reference
Functions
void MX_TouchGFX_Init (void)
void MX_TouchGFX_PreOSInit (void)
void MX_TouchGFX_Process (void)
void TouchGFX_Task (void *argument)
Function Documentation
MX_TouchGFX_Init()
void MX_TouchGFX_Init (void)
Initialize TouchGFX application
{
    // Calling forward to touchgfx_init in C++ domain
    touchgfx_components_init();
    touchgfx_init();
}
References touchgfx_components_init(), and touchgfx_init().
Referenced by main().
MX_TouchGFX_PreOSInit()
void MX_TouchGFX_PreOSInit (void)
File Name : app_touchgfx.h
This file was created by TouchGFX Generator 4.23.1. This file is only generated once! Delete this file from your project and re-generate code using STM32CubeMX or change this file manually to update it.
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
PreOS Initialization function
{
}
Referenced by main().
MX_TouchGFX_Process()
void MX_TouchGFX_Process (void)
TouchGFX application entry function
{
    // Calling forward to touchgfx_taskEntry in C++ domain
    touchgfx_taskEntry();
}
References touchgfx_taskEntry().
TouchGFX_Task()
void TouchGFX_Task (void * argument)
TouchGFX application thread
{
    // Calling forward to touchgfx_taskEntry in C++ domain
    touchgfx_taskEntry();
}