Battery Simulator Documentation: PainterRGB565
PainterRGB565
#include "PainterRGB565.hpp"
Public Member Functions
PainterRGB565 (colortype color=0)
virtual HAL::RenderingMethod getRenderingMethod () const
virtual void paint (uint8_t *destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const
virtual void setColor (colortype color)
virtual void tearDown () const
Public Member Functions inherited from AbstractPainterRGB565
AbstractPainterRGB565 ()
FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t newpix, uint16_t bufpix, uint8_t alpha) const
FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t R, uint16_t G, uint16_t B, uint16_t bufpix, uint8_t alpha) const
Public Member Functions inherited from AbstractPainter
AbstractPainter ()
virtual ~AbstractPainter ()
void framebufferToDisplay (int16_t &widgetX, int16_t &widgetY) const
virtual bool setup (const Rect &widgetRect) const
Public Member Functions inherited from AbstractPainterColor
AbstractPainterColor (colortype color=0)
virtual ~AbstractPainterColor ()
colortype getColor () const
Protected Attributes
uint16_t color565
The native color in 565 format (for speed reasons)
Protected Attributes inherited from AbstractPainter
int16_t widgetWidth
The width of the widget on screen, used by framebufferToDisplay()
Protected Attributes inherited from AbstractPainterColor
colortype painterColor
The color.
Additional Inherited Members
Static Public Attributes inherited from AbstractPainterRGB565
static const uint16_t BMASK = 0x001F
Mask for blue (0000000000011111)
static const uint16_t GMASK = 0x07E0
Mask for green (0000011111100000)
static const uint16_t RMASK = 0xF800
Mask for red (1111100000000000)
Static Protected Member Functions inherited from AbstractPainter
static FORCE_INLINE_FUNCTION bool compatibleFramebuffer (Bitmap::BitmapFormat format)
Detailed Description
The PainterRGB565 class allows a shape to be filled with a given color and alpha value. This allows transparent, anti-aliased elements to be drawn.
See also
AbstractPainter
Constructor & Destructor Documentation
PainterRGB565()
PainterRGB565 (colortype color = 0) inline
Initializes a new instance of the PainterRGB565 class.
Parameters
color (Optional) the color, default is black.
        : AbstractPainterRGB565(), AbstractPainterColor(color)
    {
    }
Member Function Documentation
getRenderingMethod()
virtual HAL::RenderingMethod getRenderingMethod () const inline virtual
Return the applicable rendering method of the painter. HARDWARE if the painter uses hardware based drawing, SOFTWARE otherwise. Relevant on platforms using DCACHE.
Returns
HARDWARE if painter uses hardware based drawing, SOFTWARE otherwise.
Reimplemented from AbstractPainter.
    {
        return HAL::getInstance()->getDMAType() == DMA_TYPE_CHROMART ? HAL::HARDWARE : HAL::SOFTWARE;
    }
References touchgfx::DMA_TYPE_CHROMART, HAL::getInstance(), HAL::HARDWARE, and HAL::SOFTWARE.
paint()
void paint (uint8_t * destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const virtual
Paints a streak of pixels (all with the same alpha) in the framebuffer. The first pixel to paint is at 'offset' relative to 'destination' (to be able to support 1bpp, 2bpp and 4bpp). The first pixel to paint is at the given 'widgetX', 'widgetY' coordinate. The number of pixels to paint is 'count' and the alpha to apply is 'alpha'.
Note that the widgetX, widgetY is relative to the widget in the framebuffer, not the display. To convert the coordinate to display widget coordinates, use framebufferToDisplay().
Parameters
[in] destination If non-null, the pointer.
offset The offset to add to the destination.
widgetX The widget x coordinate.
widgetY The widget y coordinate.
count Number of pixels.
alpha The alpha of the pixels.
See also
AbstractPainter::setup, AbstractPainter::tearDown, AbstractPainter::framebufferToDisplay
Implements AbstractPainter.
{
    uint16_t* const framebuffer = reinterpret_cast<uint16_t*>(destination) + offset;
    paint::rgb565::lineFromColor(framebuffer, count, painterColor, alpha, color565);
}
References PainterRGB565::color565, touchgfx::paint::rgb565::lineFromColor(), and AbstractPainterColor::painterColor.
setColor()
virtual void setColor (colortype color) inline virtual
Sets color to use when drawing the CanvasWidget.
Parameters
color The color.
Reimplemented from AbstractPainterColor.
    {
        AbstractPainterColor::setColor(color);
        color565 = LCD16bpp::getNativeColor(painterColor);
    }
References PainterRGB565::color565, LCD16bpp::getNativeColor(), AbstractPainterColor::painterColor, and AbstractPainterColor::setColor().
tearDown()
void tearDown () const virtual
This function is called after all paint operation have finished. This allows the painter to close down dma queues etc. This happens after the last scan line segment has been drawn.
See also
AbstractPainter::paint, AbstractPainter::setup
Reimplemented from AbstractPainter.
{
    paint::tearDown();
}
References touchgfx::paint::tearDown().
Member Data Documentation
color565
uint16_t color565 protected
The native color in 565 format (for speed reasons)
Referenced by PainterRGB565::paint(), and PainterRGB565::setColor().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/PainterRGB565.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/PainterRGB565.cpp