Battery Simulator Documentation: CoverTransition< templateDirection >
CoverTransition< templateDirection >
#include "CoverTransition.hpp"
Public Member Functions
CoverTransition (const uint8_t transitionSteps=20)
virtual void handleTickEvent ()
virtual void init ()
virtual void tearDown ()
Public Member Functions inherited from Transition
Transition ()
virtual ~Transition ()
virtual void invalidate ()
bool isDone () const
virtual void setScreenContainer (Container &cont)
Private Attributes
uint8_t animationCounter
Current step in the transition animation.
const uint8_t animationSteps
Number of steps the transition should move per complete animation.
int16_t calculatedValue
The current X or Y value.
FullSolidRect solid
A solid rect that covers the entire screen to avoid copying elements outside.
int16_t targetValue
The target value for the transition animation.
Additional Inherited Members
Protected Attributes inherited from Transition
bool done
Flag that indicates when the transition is done. This should be set by implementing classes.
Container * screenContainer
The screen Container of the Screen transitioning to.
Detailed Description
template<Direction templateDirection>
class touchgfx::CoverTransition< templateDirection >
A Transition that slides the new screen over the previous from the given direction.
Constructor & Destructor Documentation
CoverTransition()
template<Direction templateDirection> CoverTransition (const uint8_t transitionSteps = 20) inline
Initializes a new instance of the CoverTransition class.
Parameters
transitionSteps (Optional) Number of steps in the transition animation.
        : Transition(),
          animationSteps(transitionSteps),
          animationCounter(0),
          calculatedValue(0),
          solid()
    {
        switch (templateDirection)
        {
        case EAST:
            targetValue = -HAL::DISPLAY_WIDTH;
            break;
        case WEST:
            targetValue = HAL::DISPLAY_WIDTH;
            break;
        case NORTH:
            targetValue = HAL::DISPLAY_HEIGHT;
            break;
        case SOUTH:
            targetValue = -HAL::DISPLAY_HEIGHT;
            break;
        default:
            done = true;
            // Nothing to do here
            break;
        }
        // Ensure that the solid area covers the entire screen
        solid.setPosition(0, 0, HAL::DISPLAY_WIDTH, HAL::DISPLAY_HEIGHT);
    }
References HAL::DISPLAY_HEIGHT, HAL::DISPLAY_WIDTH, Transition::done, touchgfx::EAST, touchgfx::NORTH, Drawable::setPosition(), CoverTransition< templateDirection >::solid, touchgfx::SOUTH, CoverTransition< templateDirection >::targetValue, and touchgfx::WEST.
Member Function Documentation
handleTickEvent()
template<Direction templateDirection> virtual void handleTickEvent () inline virtual
Handles the tick event when transitioning. It moves the contents of the Screen's container. The direction of the transition determines the direction the contents of the container moves.
Reimplemented from Transition.
    {
        Transition::handleTickEvent();
        // Calculate new position or stop animation
        animationCounter++;
        if (animationCounter > animationSteps)
        {
            // Final step: stop the animation
            done = true;
            animationCounter = 0;
            return;
        }
        const int16_t oldValue = calculatedValue;
        // Calculate value in [0;targetValue]
        calculatedValue = EasingEquations::cubicEaseOut(animationCounter, 0, targetValue, animationSteps);
        // Note: Result of "calculatedValue & 1" is compiler dependent for negative values of calculatedValue
        if ((calculatedValue % 2) != 0)
        {
            // Optimization: calculatedValue is odd, add 1/-1 to move drawables modulo 32 bits in framebuffer
            calculatedValue += (calculatedValue > 0 ? 1 : -1);
        }
        // Convert the calculated value to delta value relative to current moved-to position
        const int16_t relativeValue = calculatedValue - oldValue;
        // The Cover Transition only draws to parts of the non-TFT framebuffer. To avoid glitches
        // In Double buffering mode both framebuffers must be identical.
        if (animationCounter == 1 && HAL::USE_DOUBLE_BUFFERING)
        {
            // Synchronize framebuffers
            Application::getInstance()->copyInvalidatedAreasFromTFTToClientBuffer();
        }
        Rect rect;
        switch (templateDirection)
        {
        case EAST:
            rect.x = HAL::DISPLAY_WIDTH + calculatedValue;
            rect.y = 0;
            rect.width = -calculatedValue;
            rect.height = HAL::DISPLAY_HEIGHT;
            break;
        case WEST:
            rect.x = 0;
            rect.y = 0;
            rect.width = calculatedValue;
            rect.height = HAL::DISPLAY_HEIGHT;
            break;
        case NORTH:
            rect.x = 0;
            rect.y = 0;
            rect.width = HAL::DISPLAY_WIDTH;
            rect.height = calculatedValue;
            break;
        case SOUTH:
            rect.x = 0;
            rect.y = HAL::DISPLAY_HEIGHT + calculatedValue;
            rect.width = HAL::DISPLAY_WIDTH;
            rect.height = -calculatedValue;
            break;
        }
        Application::getInstance()->invalidateArea(rect);
        // Move children with delta value for X or Y
        Drawable* d = screenContainer->getFirstChild();
        while (d)
        {
            switch (templateDirection)
            {
            case EAST:
            case WEST:
                d->setX(d->getX() + relativeValue);
                break;
            case NORTH:
            case SOUTH:
                d->setY(d->getY() + relativeValue);
                break;
            }
            d = d->getNextSibling();
        }
    }
References CoverTransition< templateDirection >::animationCounter, CoverTransition< templateDirection >::animationSteps, CoverTransition< templateDirection >::calculatedValue, EasingEquations::cubicEaseOut(), HAL::DISPLAY_HEIGHT, HAL::DISPLAY_WIDTH, Transition::done, touchgfx::EAST, Container::getFirstChild(), Application::getInstance(), Transition::handleTickEvent(), Rect::height, touchgfx::NORTH, Transition::screenContainer, touchgfx::SOUTH, CoverTransition< templateDirection >::targetValue, HAL::USE_DOUBLE_BUFFERING, touchgfx::WEST, Rect::width, Rect::x, and Rect::y.
init()
template<Direction templateDirection> virtual void init () inline virtual
Initializes the transition. Called after the constructor is called, when the application changes the transition.
Reimplemented from Transition.
    {
        Transition::init();
        // Move snapshot and its children with delta value for X or Y
        Drawable* d = screenContainer->getFirstChild();
        while (d)
        {
            switch (templateDirection)
            {
            case EAST:
            case WEST:
                d->setX(d->getX() - targetValue);
                break;
            case NORTH:
            case SOUTH:
                d->setY(d->getY() - targetValue);
                break;
            }
            d = d->getNextSibling();
        }
        screenContainer->add(solid);
    }
References Container::add(), touchgfx::EAST, Container::getFirstChild(), Transition::init(), touchgfx::NORTH, Transition::screenContainer, CoverTransition< templateDirection >::solid, touchgfx::SOUTH, CoverTransition< templateDirection >::targetValue, and touchgfx::WEST.
tearDown()
template<Direction templateDirection> virtual void tearDown () inline virtual
Tears down the Animation. Called before the destructor is called, when the application changes the transition.
Reimplemented from Transition.
    {
        screenContainer->remove(solid);
    }
References Container::remove(), Transition::screenContainer, and CoverTransition< templateDirection >::solid.
Member Data Documentation
animationCounter
template<Direction templateDirection> uint8_t animationCounter private
Current step in the transition animation.
Referenced by CoverTransition< templateDirection >::handleTickEvent().
animationSteps
template<Direction templateDirection> const uint8_t animationSteps private
Number of steps the transition should move per complete animation.
Referenced by CoverTransition< templateDirection >::handleTickEvent().
calculatedValue
template<Direction templateDirection> int16_t calculatedValue private
The current X or Y value.
Referenced by CoverTransition< templateDirection >::handleTickEvent().
solid
template<Direction templateDirection> FullSolidRect solid private
A solid rect that covers the entire screen to avoid copying elements outside.
Referenced by CoverTransition< templateDirection >::CoverTransition(), CoverTransition< templateDirection >::init(), and CoverTransition< templateDirection >::tearDown().
targetValue
template<Direction templateDirection> int16_t targetValue private
The target value for the transition animation.
Referenced by CoverTransition< templateDirection >::CoverTransition(), CoverTransition< templateDirection >::handleTickEvent(), and CoverTransition< templateDirection >::init().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/transitions/CoverTransition.hpp