Battery Simulator Documentation: Font
Font abstract
#include "Font.hpp"
Public Member Functions
virtual ~Font ()
virtual FORCE_INLINE_FUNCTION uint16_t getBaseline () const
virtual FORCE_INLINE_FUNCTION uint8_t getBitsPerPixel () const
virtual FORCE_INLINE_FUNCTION uint8_t getByteAlignRow () const
virtual uint16_t getCharWidth (const Unicode::UnicodeChar c) const
virtual const FontContextualFormsTable * getContextualFormsTable () const
virtual Unicode::UnicodeChar getEllipsisChar () const
virtual Unicode::UnicodeChar getFallbackChar () const
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode) const
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, const uint8_t *&pixelData, uint8_t &bitsPerPixel) const =0
virtual const uint16_t * getGSUBTable () const
virtual FORCE_INLINE_FUNCTION uint16_t getHeight () const
virtual int8_t getKerning (Unicode::UnicodeChar prevChar, const GlyphNode *glyph) const
FORCE_INLINE_FUNCTION uint8_t getMaxPixelsLeft () const
FORCE_INLINE_FUNCTION uint8_t getMaxPixelsRight () const
virtual uint16_t getNumberOfLines (const Unicode::UnicodeChar *text,...) const
FORCE_INLINE_FUNCTION uint16_t getPixelsAboveTop () const
FORCE_INLINE_FUNCTION uint16_t getPixelsBelowBottom () const
virtual float getScaleFactor () const
virtual int16_t getSpacingAbove (const Unicode::UnicodeChar *text,...) const
virtual uint16_t getStringWidth (const Unicode::UnicodeChar *text,...) const
virtual uint16_t getStringWidth (TextDirection textDirection, const Unicode::UnicodeChar *text,...) const
virtual bool isVectorBasedFont () const
TOUCHGFX_DEPRECATED ("Please use getBaseline() instead.", virtual uint16_t getFontHeight() const)
TOUCHGFX_DEPRECATED ("Please use getHeight() instead.", virtual uint16_t getMaxTextHeight(const Unicode::UnicodeChar *text,...) const)
TOUCHGFX_DEPRECATED ("Please use getHeight() instead.", virtual uint16_t getMinimumTextHeight() const)
Static Public Member Functions
static FORCE_INLINE_FUNCTION bool isInvisibleZeroWidth (Unicode::UnicodeChar character)
Protected Member Functions
Font (uint16_t height, uint16_t baseline, uint8_t pixAboveTop, uint8_t pixBelowBottom, uint8_t bitsPerPixel, uint8_t byteAlignRow, uint8_t maxLeft, uint8_t maxRight, const Unicode::UnicodeChar fallbackChar, const Unicode::UnicodeChar ellipsisChar)
uint16_t getStringWidthLTR (TextDirection textDirection, const Unicode::UnicodeChar *text, va_list pArg) const
uint16_t getStringWidthRTL (TextDirection textDirection, const Unicode::UnicodeChar *text, va_list pArg) const
Protected Attributes
uint8_t bAlignRow: 1
The glyphs are saved with each row byte aligned.
uint16_t baselineHeight
The baseline.
uint8_t bPerPixel: 7
The number of bits per pixel.
Unicode::UnicodeChar ellipsisCharacter
The ellipsis character used for truncating long texts.
Unicode::UnicodeChar fallbackCharacter
The fallback character to use when no glyph exists for the wanted character.
uint16_t fontHeight
The font height in pixels.
uint8_t maxPixelsLeft
The maximum number of pixels a glyph extends to the left.
uint8_t maxPixelsRight
The maximum number of pixels a glyph extends to the right.
uint8_t pixelsAboveTop
The number of pixels above the top.
uint8_t pixelsBelowBottom
The number of pixels below the bottom.
Private Member Functions
Font ()
Detailed Description
The font base class. This class is abstract and requires the implementation of getGlyph. It provides utility functions such as obtaining string width and font height.
Constructor & Destructor Documentation
~Font()
virtual ~Font () inline virtual
Finalizes an instance of the Font class.
    {
    }
Font() [1/2]
Font (uint16_t height, uint16_t baseline, uint8_t pixAboveTop, uint8_t pixBelowBottom, uint8_t bitsPerPixel, uint8_t byteAlignRow, uint8_t maxLeft, uint8_t maxRight, const Unicode::UnicodeChar fallbackChar, const Unicode::UnicodeChar ellipsisChar) inline protected
Initializes a new instance of the Font class. The protected constructor of a Font.
Parameters
height The font height in pixels.
baseline The baseline.
pixAboveTop The maximum number of pixels above the top of the text.
pixBelowBottom The number of pixels below the base line.
bitsPerPixel The number of bits per pixel.
byteAlignRow The glyphs are saved with each row byte aligned.
maxLeft The maximum left extend for a glyph in the font.
maxRight The maximum right extend for a glyph in the font.
fallbackChar The fallback character for the typography in case no glyph is available.
ellipsisChar The ellipsis character used for truncating long texts.
        : fontHeight(height),
          baselineHeight(baseline),
          pixelsAboveTop(pixAboveTop),
          pixelsBelowBottom(pixBelowBottom),
          bPerPixel(bitsPerPixel),
          bAlignRow(byteAlignRow),
          maxPixelsLeft(maxLeft),
          maxPixelsRight(maxRight),
          fallbackCharacter(fallbackChar),
          ellipsisCharacter(ellipsisChar)
    {
    }
Font() [2/2]
Font () private
Member Function Documentation
getBaseline()
virtual FORCE_INLINE_FUNCTION uint16_t getBaseline () const inline virtual
Returns the position of the baseline of this font in pixels from the top of the line.
Returns
The baseline position.
Note
It is not sufficient to allocate text areas with this height. Use getHeight for this.
    {
        return baselineHeight;
    }
References Font::baselineHeight.
getBitsPerPixel()
virtual FORCE_INLINE_FUNCTION uint8_t getBitsPerPixel () const inline virtual
Gets bits per pixel for this font.
Returns
The number of bits used per pixel in this font.
    {
        return bPerPixel;
    }
References Font::bPerPixel.
Referenced by CachedFont::getGlyph(), and UnmappedDataFont::getGlyph().
getByteAlignRow()
virtual FORCE_INLINE_FUNCTION uint8_t getByteAlignRow () const inline virtual
Are the glyphs saved with each glyph row byte aligned?
Returns
True if each glyph row is stored byte aligned, false otherwise.
    {
        return bAlignRow;
    }
References Font::bAlignRow.
getCharWidth()
virtual uint16_t getCharWidth (const Unicode::UnicodeChar c) const virtual
Gets the width in pixels of the specified character.
Parameters
c The Unicode character.
Returns
The width in pixels of the specified character.
getContextualFormsTable()
virtual const FontContextualFormsTable * getContextualFormsTable () const inline virtual
Gets the contextual forms table used in arabic fonts.
Returns
The FontContextualFormsTable or null if the font has no table.
Reimplemented in CachedFont, GeneratedFont, GeneratedVectorFont, and UnmappedDataFont.
    {
        return 0;
    }
getEllipsisChar()
virtual Unicode::UnicodeChar getEllipsisChar () const inline virtual
Gets ellipsis character for the given font. This is the character which is used when truncating long lines.
Returns
The ellipsis character for the typography.
See also
TextArea::setWideTextAction
    {
        return ellipsisCharacter;
    }
References Font::ellipsisCharacter.
getFallbackChar()
virtual Unicode::UnicodeChar getFallbackChar () const inline virtual
Gets fallback character for the given font. The fallback character is the character used when no glyph is available for some character. If 0 (zero) is returned, there is no default character.
Returns
The default character for the typography in case no glyph is available.
    {
        return fallbackCharacter;
    }
References Font::fallbackCharacter.
getGlyph() [1/2]
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode) const inline virtual
Gets the glyph data associated with the specified Unicode. Please note that in case of Thai letters and Arabic letters where diacritics can be placed relative to the previous character(s), please use TextProvider::getNextLigature() instead as it will create a temporary GlyphNode that will be adjusted with respect to X/Y position.
Parameters
unicode The character to look up.
Returns
A pointer to the glyph node or null if the glyph was not found.
See also
TextProvider::getNextLigature
Reimplemented in ConstFont, GeneratedFont, FusedFont, GeneratedVectorFont, and UnmappedDataFont.
    {
        if (unicode == 0)
        {
            return 0;
        }
        const uint8_t* dummyPixelDataPointer = 0;
        uint8_t bitsPerPixelDummy = 0;
        const GlyphNode* glyph = getGlyph(unicode, dummyPixelDataPointer, bitsPerPixelDummy);
        return glyph;
    }
References Font::getGlyph().
getGlyph() [2/2]
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, const uint8_t *& pixelData, uint8_t & bitsPerPixel) const pure virtual
Gets the glyph data associated with the specified Unicode. Please note that in case of Thai letters and Arabic letters where diacritics can be placed relative to the previous character(s), please use TextProvider::getNextLigature() instead as it will create a temporary GlyphNode that will be adjusted with respect to X/Y position.
Parameters
unicode The character to look up.
pixelData Pointer to the pixel data for the glyph if the glyph is found. This is set by this method.
[out] bitsPerPixel Reference where to place the number of bits per pixel.
Returns
A pointer to the glyph node or null if the glyph was not found.
Implemented in ConstFont, CachedFont, GeneratedFont, FusedFont, FusedFont, GeneratedVectorFont, UnmappedDataFont, GeneratedFont, ConstFont, FusedFont, and UnmappedDataFont.
Referenced by Font::getGlyph().
getGSUBTable()
virtual const uint16_t * getGSUBTable () const inline virtual
Gets GSUB table. Currently only used for Devanagari fonts.
Returns
The GSUB table or null if font has GSUB no table.
Reimplemented in CachedFont, GeneratedFont, GeneratedVectorFont, and UnmappedDataFont.
    {
        return 0;
    }
getHeight()
virtual FORCE_INLINE_FUNCTION uint16_t getHeight () const inline virtual
Returns the height of a font. The font may exceed the top by getPixelsAboveTop() or the bottom by getPixelsBelowBottom.
Returns
The font height.
    {
        return fontHeight;
    }
References Font::fontHeight.
Referenced by Keyboard::draw().
getKerning()
virtual int8_t getKerning (Unicode::UnicodeChar prevChar, const GlyphNode * glyph) const inline virtual
Gets the kerning distance between two characters.
Parameters
prevChar The Unicode value of the previous character.
glyph the glyph object for the current character.
Returns
The kerning distance between prevChar and glyph char.
Reimplemented in InternalFlashFont, CachedFont, GeneratedFont, GeneratedVectorFont, UnmappedDataFont, and ConstFont.
    {
        (void)prevChar; // Unused variable
        (void)glyph;    // Unused variable
        return 0;
    }
References void().
getMaxPixelsLeft()
FORCE_INLINE_FUNCTION uint8_t getMaxPixelsLeft () const inline
Gets maximum pixels left of any glyph in the font. This is the max value of "left" for all glyphs. The value is negated so if a "g" has left=-6 maxPixelsLeft is 6. This value is calculated by the font converter.
Returns
The maximum pixels left.
    {
        return maxPixelsLeft;
    }
References Font::maxPixelsLeft.
getMaxPixelsRight()
FORCE_INLINE_FUNCTION uint8_t getMaxPixelsRight () const inline
Gets maximum pixels right of any glyph in the font. This is the max value of "width+left-advance" for all glyphs. The is the number of pixels a glyph reaches to the right of its normal area. This value is calculated by the font converter.
Returns
The maximum pixels right.
    {
        return maxPixelsRight;
    }
References Font::maxPixelsRight.
getNumberOfLines()
virtual uint16_t getNumberOfLines (const Unicode::UnicodeChar * text, ...) const virtual
Count the number of lines in a given text.
Parameters
text The text.
... Variable arguments providing additional information.
Returns
The number of lines.
getPixelsAboveTop()
FORCE_INLINE_FUNCTION uint16_t getPixelsAboveTop () const inline
Gets pixels above top of the normal text height. For most fonts this is 0, for some 'wedding' fonts the number may be positive.
Returns
The pixels above top of normal text.
    {
        return pixelsAboveTop;
    }
References Font::pixelsAboveTop.
getPixelsBelowBottom()
FORCE_INLINE_FUNCTION uint16_t getPixelsBelowBottom () const inline
Gets number of pixel rows below the bottom of the font.
Returns
The pixels below bottom.
    {
        return pixelsBelowBottom;
    }
References Font::pixelsBelowBottom.
getScaleFactor()
virtual float getScaleFactor () const inline virtual
Returns the scale factor
Returns
The scale factor
Reimplemented in GeneratedVectorFont.
    {
        return 0;
    }
getSpacingAbove()
virtual int16_t getSpacingAbove (const Unicode::UnicodeChar * text, ...) const virtual
Gets the number of blank pixels at the top of the given text.
Parameters
text A null-terminated Unicode string.
... Variable arguments providing additional information inserted at wildcard placeholders.
Returns
The number of blank pixels above the text.
getStringWidth() [1/2]
uint16_t getStringWidth (const Unicode::UnicodeChar * text, ...) const virtual
Gets the width in pixels of the specified string. If the string contains multiple lines, the width of the widest line is found. Please note that the correct number of arguments must be given if the text contains wildcards.
It is recommended to use the getStringWidth() implementation with the TextDirection parameter to ensure correct calculation of the width. Kerning could result in different results depending on the TextDirection. This method assumes TextDirection to be TEXT_DIRECTION_LTR.
Parameters
text A null-terminated Unicode string with arguments to insert if the text contains wildcards.
... Variable arguments providing additional information inserted at wildcard placeholders.
Returns
The width in pixels of the longest line of the specified string.
{
    va_list pArg;
    va_start(pArg, text);
    uint16_t width = getStringWidthLTR(TEXT_DIRECTION_LTR, text, pArg);
    va_end(pArg);
    return width;
}
References Font::getStringWidthLTR(), and touchgfx::TEXT_DIRECTION_LTR.
getStringWidth() [2/2]
uint16_t getStringWidth (touchgfx::TextDirection textDirection, const Unicode::UnicodeChar * text, ...) const virtual
Gets the width in pixels of the specified string. If the string contains multiple lines, the width of the widest line is found. Please note that the correct number of arguments must be given if the text contains wildcards.
The TextDirection should be set correctly for the text supplied. For example the string "10 20 30" will be calculated differently depending on the TextDirection. If TextDirection is TEXT_DIRECTION_LTR the width is calculated as the with of "10 20 30" (with kerning between all characters) but for TEXT_DIRECTION_RTL it is calculated as "10"+" "+"20"+" "+"30" (with kerning only between characters in the substrings and not between substrings). For most fonts there might not be a difference between the two calculations, but some fonts might cause slightly different results.
Parameters
textDirection The text direction.
text A null-terminated Unicode string with arguments to insert if the text contains wildcards.
... Variable arguments providing additional information inserted at wildcard placeholders.
Returns
The width in pixels of the longest line of the specified string.
{
    va_list pArg;
    va_start(pArg, text);
    uint16_t width = getStringWidthLTR(textDirection, text, pArg);
    va_end(pArg);
    return width;
}
getStringWidthLTR()
uint16_t getStringWidthLTR (TextDirection textDirection, const Unicode::UnicodeChar * text, va_list pArg) const protected
Gets the width in pixels of the specified string. If the string contains multiple lines, the width of the widest line is found. Please note that the correct number of arguments must be given if the text contains wildcards.
Parameters
textDirection The text direction.
text A null-terminated Unicode string with arguments to insert if the text contains wildcards.
pArg Variable arguments providing additional information inserted at wildcard placeholders.
Returns
The width in pixels of the longest line of the specified string.
Note
The string is assumed to be purely left-to-right.
Referenced by Font::getStringWidth().
getStringWidthRTL()
uint16_t getStringWidthRTL (TextDirection textDirection, const Unicode::UnicodeChar * text, va_list pArg) const protected
Gets the width in pixels of the specified string. If the string contains multiple lines, the width of the widest line is found. Please note that the correct number of arguments must be given if the text contains wildcards.
The string is handled as a right-to-left string and subdivided into smaller text strings to correctly handle mixing of left-to-right and right-to-left strings.
Parameters
textDirection The text direction.
text A null-terminated Unicode string with arguments to insert if the text contains wildcards.
pArg Variable arguments providing additional information inserted at wildcard placeholders.
Returns
The string width RTL.
isInvisibleZeroWidth()
static FORCE_INLINE_FUNCTION bool isInvisibleZeroWidth (Unicode::UnicodeChar character) inline static
Query if 'character' is invisible, zero width.
Parameters
character The character.
Returns
True if invisible, zero width, false if not.
    {
        return character == 0xFEFF || character == 0x200B;
    }
isVectorBasedFont()
virtual bool isVectorBasedFont () const inline virtual
Returns true if this Font is vector based. Default is false.
Returns
True if this Font is vector based.
Reimplemented in GeneratedVectorFont.
    {
        return false;
    }
TOUCHGFX_DEPRECATED() [1/3]
TOUCHGFX_DEPRECATED ("Please use getBaseline() instead." , virtual uint16_t getFontHeight() const)
Returns the height in pixels of this font. The returned value corresponds to the maximum height occupied by a character in the font.
Returns
The height in pixels of this font.
Note
It is not sufficient to allocate text areas with this height. Use getMinimumTextHeight for this.
Deprecated
Please use getBaseline() instead.
TOUCHGFX_DEPRECATED() [2/3]
TOUCHGFX_DEPRECATED ("Please use getHeight() instead." , virtual uint16_t getMaxTextHeight(const Unicode::UnicodeChar *text,...) const)
Gets the height of the highest character in a given string. The height includes the spacing above the text which is included in the font.
Returns
The height if the given text.
Deprecated
Please use getHeight instead.
TOUCHGFX_DEPRECATED() [3/3]
TOUCHGFX_DEPRECATED ("Please use getHeight() instead." , virtual uint16_t getMinimumTextHeight() const)
Returns the height of a font. The font may exceed the top by getPixelsAboveTop().
Returns
The font height.
Deprecated
Please use getHeight() instead.
Member Data Documentation
bAlignRow
uint8_t bAlignRow protected
The glyphs are saved with each row byte aligned.
Referenced by Font::getByteAlignRow().
baselineHeight
uint16_t baselineHeight protected
The baseline.
Referenced by Font::getBaseline().
bPerPixel
uint8_t bPerPixel protected
The number of bits per pixel.
Referenced by Font::getBitsPerPixel().
ellipsisCharacter
Unicode::UnicodeChar ellipsisCharacter protected
The ellipsis character used for truncating long texts.
Referenced by Font::getEllipsisChar().
fallbackCharacter
Unicode::UnicodeChar fallbackCharacter protected
The fallback character to use when no glyph exists for the wanted character.
Referenced by Font::getFallbackChar().
fontHeight
uint16_t fontHeight protected
The font height in pixels.
Referenced by Font::getHeight().
maxPixelsLeft
uint8_t maxPixelsLeft protected
The maximum number of pixels a glyph extends to the left.
Referenced by Font::getMaxPixelsLeft().
maxPixelsRight
uint8_t maxPixelsRight protected
The maximum number of pixels a glyph extends to the right.
Referenced by Font::getMaxPixelsRight().
pixelsAboveTop
uint8_t pixelsAboveTop protected
The number of pixels above the top.
Referenced by Font::getPixelsAboveTop().
pixelsBelowBottom
uint8_t pixelsBelowBottom protected
The number of pixels below the bottom.
Referenced by Font::getPixelsBelowBottom().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/Font.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/texts/src/Texts.cpp