Battery Simulator Documentation: TextButtonStyle< T >
TextButtonStyle< T >
#include "TextButtonStyle.hpp"
Public Member Functions
TextButtonStyle ()
void setText (TypedText t)
void setTextColors (colortype newColorReleased, colortype newColorPressed)
void setTextPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTextRotation (TextRotation rotation)
void setTextX (int16_t x)
void setTextXY (int16_t x, int16_t y)
void setTextY (int16_t y)
Protected Member Functions
virtual void handleAlphaUpdated ()
virtual void handlePressedUpdated ()
Protected Attributes
colortype colorPressed
The color pressed.
colortype colorReleased
The color released.
TextArea text
The text.
Detailed Description
template<class T>
class touchgfx::TextButtonStyle< T >
A text button style. This class is supposed to be used with one of the ButtonTrigger classes to create a functional button. This class will show a text in one of two colors depending on the state of the button (pressed or released).
The TextButtonStyle does not set the size of the enclosing container (normally AbstractButtonContainer). The size must be set manually.
To get a background behind the text, use TextButtonStyle together with e.g. ImageButtonStyle: TextButtonStyle<ImageButtonStyle<ClickButtonTrigger> > myButton;
The position of the text can be adjusted with setTextXY (default is centered).
See also
AbstractButtonContainer
Constructor & Destructor Documentation
TextButtonStyle()
template<class T > TextButtonStyle () inline
        : T()
    {
        T::add(text);
    }
References TextButtonStyle< T >::text.
Member Function Documentation
handleAlphaUpdated()
template<class T > virtual void handleAlphaUpdated () inline protected virtual
Handles what should happen when the alpha is updated.
    {
        text.setAlpha(T::getAlpha());
        T::handleAlphaUpdated();
    }
References TextArea::setAlpha(), and TextButtonStyle< T >::text.
handlePressedUpdated()
template<class T > virtual void handlePressedUpdated () inline protected virtual
Handles what should happen when the pressed state is updated.
    {
        text.setColor(T::getPressed() ? colorPressed : colorReleased);
        T::handlePressedUpdated();
    }
References TextButtonStyle< T >::colorPressed, TextButtonStyle< T >::colorReleased, TextArea::setColor(), and TextButtonStyle< T >::text.
Referenced by TextButtonStyle< T >::setTextColors().
setText()
template<class T > void setText (TypedText t) inline
Sets a text.
Parameters
t A TypedText to process.
    {
        text.setTypedText(t);
        text.setWidthHeight(*this);
    }
References TextArea::setTypedText(), Drawable::setWidthHeight(), and TextButtonStyle< T >::text.
setTextColors()
template<class T > void setTextColors (colortype newColorReleased, colortype newColorPressed) inline
Sets text colors.
Parameters
newColorReleased The new color released.
newColorPressed The new color pressed.
    {
        colorReleased = newColorReleased;
        colorPressed = newColorPressed;
        handlePressedUpdated();
    }
References TextButtonStyle< T >::colorPressed, TextButtonStyle< T >::colorReleased, and TextButtonStyle< T >::handlePressedUpdated().
setTextPosition()
template<class T > void setTextPosition (int16_t x, int16_t y, int16_t width, int16_t height) inline
Sets text position.
Parameters
x The x coordinate.
y The y coordinate.
width The width of the text.
height The height of the text.
    {
        text.setPosition(x, y, width, height);
    }
References Drawable::setPosition(), and TextButtonStyle< T >::text.
setTextRotation()
template<class T > void setTextRotation (TextRotation rotation) inline
Sets text rotation.
Parameters
rotation The rotation.
    {
        text.setRotation(rotation);
    }
References TextArea::setRotation(), and TextButtonStyle< T >::text.
setTextX()
template<class T > void setTextX (int16_t x) inline
Sets text x coordinate.
Parameters
x The x coordinate.
    {
        text.setX(x);
    }
References Drawable::setX(), and TextButtonStyle< T >::text.
Referenced by TextButtonStyle< T >::setTextXY().
setTextXY()
template<class T > void setTextXY (int16_t x, int16_t y) inline
Sets text x and y.
Parameters
x The x coordinate.
y The y coordinate.
    {
        setTextX(x);
        setTextY(y);
    }
References TextButtonStyle< T >::setTextX(), and TextButtonStyle< T >::setTextY().
setTextY()
template<class T > void setTextY (int16_t y) inline
Sets text y coordinate.
Parameters
y The y coordinate.
    {
        text.setY(y);
    }
References Drawable::setY(), and TextButtonStyle< T >::text.
Referenced by TextButtonStyle< T >::setTextXY().
Member Data Documentation
colorPressed
template<class T > colortype colorPressed protected
The color pressed.
Referenced by TextButtonStyle< T >::handlePressedUpdated(), and TextButtonStyle< T >::setTextColors().
colorReleased
template<class T > colortype colorReleased protected
The color released.
Referenced by TextButtonStyle< T >::handlePressedUpdated(), and TextButtonStyle< T >::setTextColors().
text
template<class T > TextArea text protected
The text.
Referenced by TextButtonStyle< T >::TextButtonStyle(), TextButtonStyle< T >::handleAlphaUpdated(), TextButtonStyle< T >::handlePressedUpdated(), TextButtonStyle< T >::setText(), TextButtonStyle< T >::setTextPosition(), TextButtonStyle< T >::setTextRotation(), TextButtonStyle< T >::setTextX(), and TextButtonStyle< T >::setTextY().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/buttons/TextButtonStyle.hpp