Battery Simulator Documentation: EasingEquations
EasingEquations
#include "EasingEquations.hpp"
Static Public Member Functions
static int16_t backEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t backEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t backEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t bounceEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t bounceEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t bounceEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t circEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t circEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t circEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t cubicEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t cubicEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t cubicEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t elasticEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t elasticEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t elasticEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t expoEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t expoEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t expoEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t linearEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t linearEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t linearEaseNone (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t linearEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t quadEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t quadEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t quadEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t quartEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t quartEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t quartEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t quintEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t quintEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t quintEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t sineEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t sineEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
static int16_t sineEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d)
Static Private Member Functions
static FORCE_INLINE_FUNCTION int16_t roundRespectSign (float resultFloating)
Detailed Description
Defines the "Penner easing functions", which are a de facto standard for computing aesthetically pleasing motion animations. See http://easings.net/ for visual illustrations of the easing equations.
Member Function Documentation
backEaseIn()
static int16_t backEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Back easing in: Overshooting cubic easing: (s+1)*t^3 - s*t^2. Backtracking slightly, then reversing direction and moving to target.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
backEaseInOut()
static int16_t backEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Back easing in/out: Overshooting cubic easing: (s+1)*t^3 - s*t^2. Backtracking slightly, then reversing direction and moving to target, then overshooting target, reversing, and finally coming back to target.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
backEaseOut()
static int16_t backEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Back easing out: Overshooting cubic easing: (s+1)*t^3 - s*t^2. Moving towards target, overshooting it slightly, then reversing and coming back to target.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
Referenced by SwipeContainer::animateSwipeCancelledLeft(), and SwipeContainer::animateSwipeCancelledRight().
bounceEaseIn()
static int16_t bounceEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Bounce easing in - exponentially decaying parabolic bounce.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
bounceEaseInOut()
static int16_t bounceEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Bounce easing in/out - exponentially decaying parabolic bounce.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
bounceEaseOut()
static int16_t bounceEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Bounce easing out - exponentially decaying parabolic bounce.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
circEaseIn()
static int16_t circEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Circular easing in: sqrt(1-t^2). Accelerating from zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
circEaseInOut()
static int16_t circEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Circular easing in/out: sqrt(1-t^2). Acceleration until halfway, then deceleration.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
circEaseOut()
static int16_t circEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Circular easing out: sqrt(1-t^2). Decelerating to zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
cubicEaseIn()
static int16_t cubicEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Cubic easing in: t^3. Accelerating from zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
cubicEaseInOut()
static int16_t cubicEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Cubic easing in/out: t^3. Acceleration until halfway, then deceleration.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
cubicEaseOut()
static int16_t cubicEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Cubic easing out: t^3. Decelerating to zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
Referenced by SwipeContainer::animateLeft(), SwipeContainer::animateLeftWithButton(), SwipeContainer::animateRight(), SwipeContainer::animateRightWithButton(), ScrollableContainer::handleTickEvent(), CoverTransition< templateDirection >::handleTickEvent(), SlideTransition< templateDirection >::handleTickEvent(), and WipeTransition< templateDirection >::handleTickEvent().
elasticEaseIn()
static int16_t elasticEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Elastic easing in - exponentially decaying sine wave.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
elasticEaseInOut()
static int16_t elasticEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Elastic easing in/out - exponentially decaying sine wave.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
elasticEaseOut()
static int16_t elasticEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Elastic easing out - exponentially decaying sine wave.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
expoEaseIn()
static int16_t expoEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Exponential easing in: 2^t. Accelerating from zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
expoEaseInOut()
static int16_t expoEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Exponential easing in/out: 2^t. Accelerating until halfway, then decelerating.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
expoEaseOut()
static int16_t expoEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Exponential easing out: 2^t. Deceleration to zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
linearEaseIn()
static int16_t linearEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Simple linear tweening - no easing.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
linearEaseInOut()
static int16_t linearEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Simple linear tweening - no easing.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
linearEaseNone()
static int16_t linearEaseNone (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Simple linear tweening - no easing.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
linearEaseOut()
static int16_t linearEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Simple linear tweening - no easing.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
quadEaseIn()
static int16_t quadEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Quadratic easing in: t^2. Accelerating from zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
quadEaseInOut()
static int16_t quadEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Quadratic easing in/out: t^2. Acceleration until halfway, then deceleration.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
quadEaseOut()
static int16_t quadEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Quadratic easing out: t^2. Decelerating to zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
quartEaseIn()
static int16_t quartEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Quartic easing in: t^4. Accelerating from zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
quartEaseInOut()
static int16_t quartEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Quartic easing in/out: t^4. Acceleration until halfway, then deceleration.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
quartEaseOut()
static int16_t quartEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Quartic easing out: t^4. Decelerating to zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
quintEaseIn()
static int16_t quintEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Quintic/strong easing in: t^5. Accelerating from zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
quintEaseInOut()
static int16_t quintEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Quintic/strong easing in/out: t^5. Acceleration until halfway, then deceleration.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
quintEaseOut()
static int16_t quintEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Quintic/strong easing out: t^5. Decelerating to zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
roundRespectSign()
static FORCE_INLINE_FUNCTION int16_t roundRespectSign (float resultFloating) inline static private
Round respect sign.
Parameters
resultFloating The result floating.
Returns
An int16_t.
    {
        return static_cast<int16_t>((resultFloating > 0.0f) ? (resultFloating + 0.5f) : (resultFloating - 0.5f));
    }
sineEaseIn()
static int16_t sineEaseIn (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Sinusoidal easing in: sin(t). Accelerating from zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
sineEaseInOut()
static int16_t sineEaseInOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Sinusoidal easing in/out: sin(t). Acceleration until halfway, then deceleration.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
sineEaseOut()
static int16_t sineEaseOut (uint16_t t, int16_t b, int16_t c, uint16_t d) static
Sinusoidal easing out: sin(t). Decelerating to zero velocity.
Parameters
t Time. The current time or step.
b Beginning. The beginning value.
c Change. The change between the beginning value and the destination value.
d Duration. The total time or total number of steps.
Returns
The current value as a function of the current time or step.
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/EasingEquations.hpp