Battery Simulator Documentation: Slider
Slider
#include "Slider.hpp"
Public Member Functions
Slider ()
virtual int16_t getIndicatorMax () const
virtual int16_t getIndicatorMin () const
virtual int16_t getMaxValue () const
virtual int16_t getMinValue () const
int getValue ()
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
void setBitmaps (const Bitmap &sliderBackground, const Bitmap &sliderBackgroundSelected, const Bitmap &indicator)
void setBitmaps (const BitmapId sliderBackground, const BitmapId sliderBackgroundSelected, const BitmapId indicator)
void setNewValueCallback (GenericCallback< const Slider &, int > &callback)
void setStartValueCallback (GenericCallback< const Slider &, int > &callback)
void setStopValueCallback (GenericCallback< const Slider &, int > &callback)
virtual void setupHorizontalSlider (int16_t backgroundX, int16_t backgroundY, int16_t indicatorY, int16_t indicatorMinX, int16_t indicatorMaxX)
virtual void setupVerticalSlider (int16_t backgroundX, int16_t backgroundY, int16_t indicatorX, int16_t indicatorMinY, int16_t indicatorMaxY)
virtual void setValue (int16_t value)
virtual void setValueRange (int16_t minValue, int16_t maxValue)
virtual void setValueRange (int16_t minValue, int16_t maxValue, int16_t newValue)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Types
enum SliderOrientation { HORIZONTAL , VERTICAL }
Protected Member Functions
virtual int getIndicatorPositionRangeSize () const
virtual int16_t getIndicatorRadius () const
virtual int getValueRangeSize () const
virtual int positionToValue (int16_t position) const
virtual void updateIndicatorPosition (int16_t position)
virtual int16_t valueToPosition (int value) const
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
Image background
The background image.
Image backgroundSelected
The backgroundSelected image.
Container backgroundSelectedViewPort
The backgroundSelected view port. Controls the visible part of the backgroundSelected image.
int16_t currentValue
The current value represented by the slider.
Image indicator
The indicator image.
int16_t indicatorMaxPosition
The maximum position of the indicator (either x coordinate in horizontal mode or y coordinate in vertical mode)
int16_t indicatorMinPosition
The minimum position of the indicator (either x coordinate in horizontal mode or y coordinate in vertical mode)
GenericCallback< const Slider &, int > * newValueCallback
The new value callback (called when the indicator is moved)
SliderOrientation sliderOrientation
The selected slider orientation.
GenericCallback< const Slider &, int > * startValueCallback
The start value callback (called when an interaction with the indicator is initiated)
GenericCallback< const Slider &, int > * stopValueCallback
The stop value callback (called when an interaction with the indicator ends)
int16_t valueRangeMax
The value range max.
int16_t valueRangeMin
The value range min.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A slider is a graphical element with which the user may set a value by moving an indicator on a slider, or simply by clicking the slider. The slider can operate in horizontal or vertical mode. The slider has two bitmaps. One bitmap is used on one side of the indicator. The other is used on the other side. They can be used in indicating the part of the slider value range that is currently selected.
The slider operates on an integer value range that can be set by the user.
Member Enumeration Documentation
SliderOrientation
enum SliderOrientation protected
Values that represent slider orientations.
Enumerator
HORIZONTAL
The Slider can be moved horizontally between left and right.
VERTICAL
The Slider can be moved vertically between top and bottom.
    {
        HORIZONTAL,
        VERTICAL
    };
Constructor & Destructor Documentation
Slider()
Slider ()
    : Container(),
      sliderOrientation(HORIZONTAL),
      currentValue(0),
      valueRangeMin(0),
      valueRangeMax(100),
      background(),
      backgroundSelected(),
      indicator(),
      backgroundSelectedViewPort(),
      indicatorMinPosition(0),
      indicatorMaxPosition(1),
      startValueCallback(0),
      stopValueCallback(0),
      newValueCallback(0)
{
    setTouchable(true);
    // The backgroundSelectedViewPort is a container into which the bitmap for the "filled" background
    // is placed. Containers are viewports, so the dimensions of this container controls how
    // much of the filled background is visible.
    backgroundSelectedViewPort.add(backgroundSelected);
    Container::add(background);
    Container::add(backgroundSelectedViewPort);
    Container::add(indicator);
    // Default value range
    Slider::updateIndicatorPosition(indicatorMinPosition);
}
References Container::add(), Slider::background, Slider::backgroundSelected, Slider::backgroundSelectedViewPort, Slider::indicator, Slider::indicatorMinPosition, Drawable::setTouchable(), and Slider::updateIndicatorPosition().
Member Function Documentation
getIndicatorMax()
virtual int16_t getIndicatorMax () const inline virtual
Gets indicator maximum previous set using setupHorizontalSlider() or setupVerticalSlider().
Returns
The calculated indicator maximum.
See also
setupHorizontalSlider, setupVerticalSlider, getIndicatorMin
    {
        return indicatorMaxPosition;
    }
References Slider::indicatorMaxPosition.
getIndicatorMin()
virtual int16_t getIndicatorMin () const inline virtual
Gets indicator minimum previously set using setupHorizontalSlider() or setupVerticalSlider().
Returns
The indicator minimum.
See also
setupHorizontalSlider, setupVerticalSlider, getIndicatorMax
    {
        return indicatorMinPosition;
    }
References Slider::indicatorMinPosition.
getIndicatorPositionRangeSize()
int getIndicatorPositionRangeSize () const protected virtual
Gets the indicator position range, i.e. the difference between max and min for the position of the indicator.
Returns
The indicator position range.
{
    return indicatorMaxPosition - indicatorMinPosition;
}
References Slider::indicatorMaxPosition, and Slider::indicatorMinPosition.
Referenced by Slider::positionToValue(), and Slider::valueToPosition().
getIndicatorRadius()
int16_t getIndicatorRadius () const protected virtual
Gets the indicator radius, which is half the size of the indicator.
Returns
The the indicator radius.
{
    return (sliderOrientation == HORIZONTAL ? indicator.getWidth() : indicator.getHeight()) / 2;
}
References Drawable::getHeight(), Drawable::getWidth(), Slider::HORIZONTAL, Slider::indicator, and Slider::sliderOrientation.
Referenced by Slider::handleClickEvent(), Slider::handleDragEvent(), and Slider::updateIndicatorPosition().
getMaxValue()
virtual int16_t getMaxValue () const inline virtual
Gets the maximum value previously set using setValueRange().
Returns
The maximum value.
See also
setValueRange, getMinValue
    {
        return valueRangeMax;
    }
References Slider::valueRangeMax.
getMinValue()
virtual int16_t getMinValue () const inline virtual
Gets the minimum value previously set using setValueRange().
Returns
The minimum value.
See also
setValueRange, getMaxValue
    {
        return valueRangeMin;
    }
References Slider::valueRangeMin.
getValue()
int getValue () inline
Gets the current value represented by the indicator.
Returns
The current value.
    {
        return currentValue;
    }
References Slider::currentValue.
getValueRangeSize()
int getValueRangeSize () const protected virtual
Gets the value range, i.e. the difference between max and min for the value range.
Returns
The value range.
{
    return valueRangeMax - valueRangeMin;
}
References Slider::valueRangeMax, and Slider::valueRangeMin.
Referenced by Slider::positionToValue(), and Slider::valueToPosition().
handleClickEvent()
void handleClickEvent (const ClickEvent & event) virtual
Defines the event handler interface for ClickEvents. The default implementation ignores the event. The event is only received if the Drawable is touchable and visible.
Parameters
event The ClickEvent received from the HAL.
Reimplemented from Drawable.
{
    if ((event.getType() == ClickEvent::PRESSED) || (event.getType() == ClickEvent::RELEASED))
    {
        // Communicate the start value if a listener is registered
        if ((event.getType() == ClickEvent::PRESSED) && (startValueCallback != 0) && startValueCallback->isValid())
        {
            startValueCallback->execute(*this, currentValue);
        }
        updateIndicatorPosition((sliderOrientation == HORIZONTAL ? event.getX() : event.getY()) - getIndicatorRadius());
        // Communicate the stop value if a listener is registered
        if ((event.getType() == ClickEvent::RELEASED) && (stopValueCallback != 0) && stopValueCallback->isValid())
        {
            stopValueCallback->execute(*this, currentValue);
        }
    }
}
References Slider::currentValue, Slider::getIndicatorRadius(), Slider::HORIZONTAL, ClickEvent::PRESSED, ClickEvent::RELEASED, Slider::sliderOrientation, Slider::startValueCallback, Slider::stopValueCallback, and Slider::updateIndicatorPosition().
handleDragEvent()
void handleDragEvent (const DragEvent & event) virtual
Defines the event handler interface for DragEvents. The default implementation ignores the event. The event is only received if the drawable is touchable and visible.
Parameters
event The DragEvent received from the HAL.
Reimplemented from Drawable.
{
    updateIndicatorPosition((sliderOrientation == HORIZONTAL ? event.getNewX() : event.getNewY()) - getIndicatorRadius());
}
References Slider::getIndicatorRadius(), Slider::HORIZONTAL, Slider::sliderOrientation, and Slider::updateIndicatorPosition().
positionToValue()
int positionToValue (int16_t position) const protected virtual
Translate a position (x coordinate in horizontal mode and y in vertical mode) in the indicator position range to the corresponding value in the value range.
Parameters
position The position.
Returns
The value that corresponds to the coordinate.
{
    position = MIN(indicatorMaxPosition, position);
    position = MAX(position, indicatorMinPosition);
    const int16_t relativePosition = sliderOrientation == VERTICAL ? indicatorMaxPosition - position : position - indicatorMinPosition;
    return valueRangeMin + muldiv(relativePosition, getValueRangeSize(), getIndicatorPositionRangeSize());
}
References Slider::getIndicatorPositionRangeSize(), Slider::getValueRangeSize(), Slider::indicatorMaxPosition, Slider::indicatorMinPosition, MAX, MIN, touchgfx::muldiv(), Slider::sliderOrientation, Slider::valueRangeMin, and Slider::VERTICAL.
Referenced by Slider::updateIndicatorPosition().
setBitmaps() [1/2]
void setBitmaps (const Bitmap & sliderBackground, const Bitmap & sliderBackgroundSelected, const Bitmap & indicator)
Sets all the bitmaps for the Slider. The Slider shows the sliderBackgroundSelected bitmap in the region of the Slider that is selected, that is the area to the left of the indicator for a horizontal Slider and below the indicator for a vertical Slider. The sliderBackground is shown on the other side of the Slider. To ignore this effect simply use the same bitmap for both the sliderBackground and the sliderBackgroundSelected.
Parameters
sliderBackground The slider background with the slider range unselected.
sliderBackgroundSelected The slider background with the slider range selected.
indicator The indicator.
{
    assert(sliderBackground.getWidth() == sliderBackgroundSelected.getWidth() &&
           sliderBackground.getHeight() == sliderBackgroundSelected.getHeight() &&
           "Slider::setBitmaps - background and backgroundFilled must have same dimensions");
    // Invalidate before and after in case size changes from previous bitmaps
    background.invalidate(); // Redraw slider
    indicator.invalidate();  // Redraw indicator
    background.setBitmap(sliderBackground);
    backgroundSelected.setBitmap(sliderBackgroundSelected);
    indicator.setBitmap(indicatorBitmap);
    backgroundSelectedViewPort.setWidthHeight(backgroundSelected);
    setValue(currentValue); // Update size of backgroundSelectedViewPort
    background.invalidate(); // Redraw slider
    indicator.invalidate();  // Redraw indicator
}
References Slider::background, Slider::backgroundSelected, Slider::backgroundSelectedViewPort, Slider::currentValue, Slider::indicator, Drawable::invalidate(), Image::setBitmap(), Slider::setValue(), and Drawable::setWidthHeight().
setBitmaps() [2/2]
void setBitmaps (const BitmapId sliderBackground, const BitmapId sliderBackgroundSelected, const BitmapId indicator)
Sets all the bitmaps for the Slider. The Slider shows the sliderBackgroundSelected bitmap in the region of the Slider that is selected, that is the area to the left of the indicator for a horizontal Slider and below the indicator for a vertical Slider. The sliderBackground is shown on the other side of the Slider. To ignore this effect simply use the same bitmap for both the sliderBackground and the sliderBackgroundSelected.
Parameters
sliderBackground The slider background with the slider range unselected.
sliderBackgroundSelected The slider background with the slider range selected.
indicator The indicator.
{
    setBitmaps(Bitmap(sliderBackground), Bitmap(sliderBackgroundSelected), Bitmap(indicatorBitmap));
}
References Slider::setBitmaps().
Referenced by Slider::setBitmaps().
setNewValueCallback()
void setNewValueCallback (GenericCallback< const Slider &, int > & callback) inline
Associates an action to be performed when the slider changes its value.
Parameters
callback The callback to be executed. The callback will be given a reference to the Slider and the current value of the slider.
See also
GenericCallback
    {
        newValueCallback = &callback;
    }
References Slider::newValueCallback.
setStartValueCallback()
void setStartValueCallback (GenericCallback< const Slider &, int > & callback) inline
Associates an action to be performed when an interaction with the slider is initiated (click or drag).
Parameters
callback The callback to be executed. The callback will be given a reference to the Slider and the current value of the slider at interaction start.
See also
GenericCallback
    {
        startValueCallback = &callback;
    }
References Slider::startValueCallback.
setStopValueCallback()
void setStopValueCallback (GenericCallback< const Slider &, int > & callback) inline
Associates an action to be performed when an interaction with the slider ends (click or drag).
Parameters
callback The callback to be executed. The callback will be given a reference to the Slider and the current value of the slider at interaction end.
See also
GenericCallback
    {
        stopValueCallback = &callback;
    }
References Slider::stopValueCallback.
setupHorizontalSlider()
void setupHorizontalSlider (int16_t backgroundX, int16_t backgroundY, int16_t indicatorY, int16_t indicatorMinX, int16_t indicatorMaxX) virtual
Sets up the slider in horizontal mode with the range going from the left to right.
Places the backgrounds and the indicator inside the Slider container. It is possible to place the end points of the indicator outside the background image if it needs to go beyond the boundaries of the background. The width and height of the Slider will be adjusted appropriately so that both the background and the indicator will be fully visible in both the minimum and maximum indicator positions.
Calls setValue() with the current value (default 0) and triggers the newSliderValue callback.
Parameters
backgroundX The background x coordinate inside the slider.
backgroundY The background y coordinate inside the slider.
indicatorY The indicator y coordinate inside the slider.
indicatorMinX The indicator minimum x coordinate inside the slider. This is the position used when the slider is at its minimum value. Must be less than indicatorMaxX.
indicatorMaxX The indicator maximum x coordinate inside the slider. This is the position used when the slider is at its maximum value. Must be greater than indicatorMinX.
Note
The x and y position of the Slider will either be the left/top of the background or the left/top of the indicator in its minimum x coordinate.
{
    assert(indicatorMinX < indicatorMaxX && "Slider::setupHorizontalSlider - indicatorMinX must be smaller than indicatorMaxX");
    sliderOrientation = HORIZONTAL;
    background.setXY(backgroundX, backgroundY);
    backgroundSelectedViewPort.setPosition(background);
    backgroundSelected.setXY(0, 0);
    indicator.setY(indicatorY);
    const int16_t backgroundWidth = backgroundX + background.getWidth();
    const int16_t indicatorWidth = indicatorMaxX + indicator.getWidth();
    const int16_t newWidth = MAX(backgroundWidth, indicatorWidth);
    const int16_t backgroundHeight = backgroundY + background.getHeight();
    const int16_t indicatorHeight = indicatorY + indicator.getHeight();
    const int16_t newHeight = MAX(backgroundHeight, indicatorHeight);
    indicatorMinPosition = indicatorMinX;
    indicatorMaxPosition = indicatorMaxX;
    setWidthHeight(newWidth, newHeight);
    setValue(currentValue);
}
References Slider::background, Slider::backgroundSelected, Slider::backgroundSelectedViewPort, Slider::currentValue, Drawable::getHeight(), Drawable::getWidth(), Slider::HORIZONTAL, Slider::indicator, Slider::indicatorMaxPosition, Slider::indicatorMinPosition, MAX, Drawable::setPosition(), Slider::setValue(), Drawable::setWidthHeight(), Drawable::setXY(), Drawable::setY(), and Slider::sliderOrientation.
setupVerticalSlider()
void setupVerticalSlider (int16_t backgroundX, int16_t backgroundY, int16_t indicatorX, int16_t indicatorMinY, int16_t indicatorMaxY) virtual
Sets up the slider in vertical mode with the range going from the bottom to top.
Places the backgrounds and the indicator inside the Slider container. It is possible to place the end points of the indicator outside the background image if it needs to go beyond the boundaries of the background. The width and height of the Slider will be adjusted appropriately so that both the background and the indicator will be fully visible in both the minimum and maximum indicator positions.
Calls setValue with the current value (default 0) and triggers the newSliderValue callback.
Parameters
backgroundX The background x coordinate inside the slider.
backgroundY The background y coordinate inside the slider.
indicatorX The indicator x coordinate inside the slider.
indicatorMinY The indicator minimum y coordinate inside the slider. This is the position used when the slider is at its maximum value. Must be less than indicatorMaxX.
indicatorMaxY The indicator maximum y coordinate inside the slider. This is the position used when the slider is at its minimum value. Must be greater than indicatorMinX.
Note
The x and y position of the Slider will either be the left/top of the background or the left/top of the indicator in its minimum y coordinate.
{
    assert(indicatorMinY < indicatorMaxY && "Slider::setupVerticalSlider - indicatorMinY must be smaller than indicatorMaxY");
    sliderOrientation = VERTICAL;
    background.setXY(backgroundX, backgroundY);
    backgroundSelectedViewPort.setPosition(background);
    indicator.setX(indicatorX);
    const int16_t backgroundWidth = backgroundX + background.getWidth();
    const int16_t indicatorWidth = indicatorX + indicator.getWidth();
    const int16_t newWidth = MAX(backgroundWidth, indicatorWidth);
    const int16_t backgroundHeight = backgroundY + background.getHeight();
    const int16_t indicatorHeight = indicatorMaxY + indicator.getHeight();
    const int16_t newHeight = MAX(backgroundHeight, indicatorHeight);
    indicatorMinPosition = indicatorMinY;
    indicatorMaxPosition = indicatorMaxY;
    setWidthHeight(newWidth, newHeight);
    setValue(currentValue);
}
References Slider::background, Slider::backgroundSelectedViewPort, Slider::currentValue, Drawable::getHeight(), Drawable::getWidth(), Slider::indicator, Slider::indicatorMaxPosition, Slider::indicatorMinPosition, MAX, Drawable::setPosition(), Slider::setValue(), Drawable::setWidthHeight(), Drawable::setX(), Drawable::setXY(), Slider::sliderOrientation, and Slider::VERTICAL.
setValue()
void setValue (int16_t value) virtual
Places the indicator at the specified value relative to the specified value range. Values beyond the value range will be rounded to the min/max value in the value range.
Parameters
value The value.
See also
setValueRange
Note
The value update triggers a newSliderValue callback just as a drag or click does.
If the value range is larger than the number of pixels specified for the indicator min and indicator max, some values will not be represented by the slider and thus is not possible to set with this method. In this case the value will be rounded to the nearest value that is represented in the current setting.
{
    updateIndicatorPosition(valueToPosition(value));
}
References Slider::updateIndicatorPosition(), and Slider::valueToPosition().
Referenced by Slider::setBitmaps(), Slider::setupHorizontalSlider(), Slider::setupVerticalSlider(), and Slider::setValueRange().
setValueRange() [1/2]
void setValueRange (int16_t minValue, int16_t maxValue) virtual
Sets the value range of the slider. Values accepted and returned by the slider will be in this range.
The slider will set its value to the current value or round to minValue or maxValue if the current value is outside the new range.
Parameters
minValue The minimum value. Must be less than maxValue.
maxValue The maximum value. Must be greater than minValue.
Note
If the range is larger than the number of pixels specified for the indicator min and indicator max, some values will not be represented by the slider.
{
    const int16_t newValue = currentValue < minValue ? minValue : (currentValue > maxValue ? maxValue : currentValue);
    setValueRange(minValue, maxValue, newValue);
}
References Slider::currentValue, and Slider::setValueRange().
setValueRange() [2/2]
void setValueRange (int16_t minValue, int16_t maxValue, int16_t newValue) virtual
Sets the value range of the slider. Values accepted and returned by the slider will be in this range.
The slider will set its value to the specified new value.
Parameters
minValue The minimum value. Must be less than maxValue.
maxValue The maximum value. Must be greater than minValue.
newValue The new value.
Note
If the range is larger than the number of pixels specified for the indicator min and max some values will not be represented by the slider.
{
    assert(minValue < maxValue && "Slider::setValueRange - minValue must be smaller than maxValue");
    valueRangeMin = minValue;
    valueRangeMax = maxValue;
    setValue(newValue);
}
References Slider::setValue(), Slider::valueRangeMax, and Slider::valueRangeMin.
Referenced by Slider::setValueRange().
updateIndicatorPosition()
void updateIndicatorPosition (int16_t position) protected virtual
Updates the indicator position described by position. Calls the newSliderValueCallback with the new value.
Parameters
position The position (x coordinate in horizontal mode and y coordinate in vertical mode).
{
    // Cut off positions outside the slider area
    position = MAX(position, indicatorMinPosition);
    position = MIN(position, indicatorMaxPosition);
    if (sliderOrientation == HORIZONTAL)
    {
        indicator.moveTo(position, indicator.getY());
        backgroundSelectedViewPort.invalidate();
        backgroundSelectedViewPort.setWidth((position - backgroundSelectedViewPort.getX()) + getIndicatorRadius());
        backgroundSelectedViewPort.invalidate();
    }
    else
    {
        indicator.moveTo(indicator.getX(), position);
        backgroundSelectedViewPort.invalidate();
        const int16_t newViewPortHeight = background.getRect().bottom() - (position + getIndicatorRadius());
        backgroundSelectedViewPort.setPosition(backgroundSelectedViewPort.getX(), position + getIndicatorRadius(), backgroundSelectedViewPort.getWidth(), newViewPortHeight);
        backgroundSelected.setY(-(backgroundSelected.getHeight() - newViewPortHeight));
        backgroundSelectedViewPort.invalidate();
    }
    currentValue = positionToValue(position);
    // Communicate the new value if a listener is registered
    if ((newValueCallback != 0) && newValueCallback->isValid())
    {
        newValueCallback->execute(*this, currentValue);
    }
}
References Slider::background, Slider::backgroundSelected, Slider::backgroundSelectedViewPort, Slider::currentValue, Drawable::getHeight(), Slider::getIndicatorRadius(), Drawable::getRect(), Drawable::getWidth(), Drawable::getX(), Drawable::getY(), Slider::HORIZONTAL, Slider::indicator, Slider::indicatorMaxPosition, Slider::indicatorMinPosition, Drawable::invalidate(), MAX, MIN, Drawable::moveTo(), Slider::newValueCallback, Slider::positionToValue(), Drawable::setPosition(), Drawable::setWidth(), Drawable::setY(), and Slider::sliderOrientation.
Referenced by Slider::Slider(), Slider::handleClickEvent(), Slider::handleDragEvent(), and Slider::setValue().
valueToPosition()
int16_t valueToPosition (int value) const protected virtual
Translate a value in the value range to the corresponding position in the indicator position range (x coordinate in horizontal mode and y in vertical mode).
Parameters
value The value.
Returns
The coordinate that corresponds to the value.
{
    value = MIN(valueRangeMax, value);
    value = MAX(value, valueRangeMin);
    const int16_t relativePosition = muldiv(value - valueRangeMin, getIndicatorPositionRangeSize(), getValueRangeSize());
    return sliderOrientation == VERTICAL ? indicatorMaxPosition - relativePosition : indicatorMinPosition + relativePosition;
}
References Slider::getIndicatorPositionRangeSize(), Slider::getValueRangeSize(), Slider::indicatorMaxPosition, Slider::indicatorMinPosition, MAX, MIN, touchgfx::muldiv(), Slider::sliderOrientation, Slider::valueRangeMax, Slider::valueRangeMin, and Slider::VERTICAL.
Referenced by Slider::setValue().
Member Data Documentation
background
Image background protected
The background image.
Referenced by Slider::Slider(), Slider::setBitmaps(), Slider::setupHorizontalSlider(), Slider::setupVerticalSlider(), and Slider::updateIndicatorPosition().
backgroundSelected
Image backgroundSelected protected
The backgroundSelected image.
Referenced by Slider::Slider(), Slider::setBitmaps(), Slider::setupHorizontalSlider(), and Slider::updateIndicatorPosition().
backgroundSelectedViewPort
Container backgroundSelectedViewPort protected
The backgroundSelected view port. Controls the visible part of the backgroundSelected image.
Referenced by Slider::Slider(), Slider::setBitmaps(), Slider::setupHorizontalSlider(), Slider::setupVerticalSlider(), and Slider::updateIndicatorPosition().
currentValue
int16_t currentValue protected
The current value represented by the slider.
Referenced by Slider::getValue(), Slider::handleClickEvent(), Slider::setBitmaps(), Slider::setupHorizontalSlider(), Slider::setupVerticalSlider(), Slider::setValueRange(), and Slider::updateIndicatorPosition().
indicator
Image indicator protected
The indicator image.
Referenced by Slider::Slider(), Slider::getIndicatorRadius(), Slider::setBitmaps(), Slider::setupHorizontalSlider(), Slider::setupVerticalSlider(), and Slider::updateIndicatorPosition().
indicatorMaxPosition
int16_t indicatorMaxPosition protected
The maximum position of the indicator (either x coordinate in horizontal mode or y coordinate in vertical mode)
Referenced by Slider::getIndicatorMax(), Slider::getIndicatorPositionRangeSize(), Slider::positionToValue(), Slider::setupHorizontalSlider(), Slider::setupVerticalSlider(), Slider::updateIndicatorPosition(), and Slider::valueToPosition().
indicatorMinPosition
int16_t indicatorMinPosition protected
The minimum position of the indicator (either x coordinate in horizontal mode or y coordinate in vertical mode)
Referenced by Slider::Slider(), Slider::getIndicatorMin(), Slider::getIndicatorPositionRangeSize(), Slider::positionToValue(), Slider::setupHorizontalSlider(), Slider::setupVerticalSlider(), Slider::updateIndicatorPosition(), and Slider::valueToPosition().
newValueCallback
GenericCallback<const Slider&, int>* newValueCallback protected
The new value callback (called when the indicator is moved)
Referenced by Slider::setNewValueCallback(), and Slider::updateIndicatorPosition().
sliderOrientation
SliderOrientation sliderOrientation protected
The selected slider orientation.
Referenced by Slider::getIndicatorRadius(), Slider::handleClickEvent(), Slider::handleDragEvent(), Slider::positionToValue(), Slider::setupHorizontalSlider(), Slider::setupVerticalSlider(), Slider::updateIndicatorPosition(), and Slider::valueToPosition().
startValueCallback
GenericCallback<const Slider&, int>* startValueCallback protected
The start value callback (called when an interaction with the indicator is initiated)
Referenced by Slider::handleClickEvent(), and Slider::setStartValueCallback().
stopValueCallback
GenericCallback<const Slider&, int>* stopValueCallback protected
The stop value callback (called when an interaction with the indicator ends)
Referenced by Slider::handleClickEvent(), and Slider::setStopValueCallback().
valueRangeMax
int16_t valueRangeMax protected
The value range max.
Referenced by Slider::getMaxValue(), Slider::getValueRangeSize(), Slider::setValueRange(), and Slider::valueToPosition().
valueRangeMin
int16_t valueRangeMin protected
The value range min.
Referenced by Slider::getMinValue(), Slider::getValueRangeSize(), Slider::positionToValue(), Slider::setValueRange(), and Slider::valueToPosition().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/Slider.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/Slider.cpp