Battery Simulator Documentation: CWRUtil::Q15
CWRUtil::Q15
#include "CWRUtil.hpp"
Public Member Functions
Q15 (int i)
operator int () const
Q15 operator+ (const Q15 &q15) const
Q15 operator- () const
Q10 operator/ (const Q5 &q5) const
Private Attributes
int32_t v
Detailed Description
Defines a "floating point number" with 15 bits reserved for the fractional part of the decimal number. Q15 is only used for sine/cosine and for intermediate calculations when multiplying.
Q5*Q5=Q10, Q10/Q5=Q5, ...
See also
Q5, Q10
Constructor & Destructor Documentation
Q15()
Q15 (int i) inline explicit
Constructor from integer. No conversion is done - the integer is assumed to already be in Q15 format.
Parameters
i int pre-formattet in Q15 format.
            : v(i)
        {
        }
Referenced by CWRUtil::Q15::operator+(), and CWRUtil::Q15::operator-().
Member Function Documentation
operator int()
operator int () const inline
Gets the Q15 as an integer without conversion.
Returns
The unconverted Q15 value.
        {
            return v;
        }
References CWRUtil::Q15::v.
operator+()
Q15 operator+ (const Q15 & q15) const inline
Addition operator.
Parameters
q15 The Q15 to add to this.
Returns
The result of the operation.
        {
            return Q15(v + q15.v);
        }
References CWRUtil::Q15::Q15().
operator-()
Q15 operator- () const inline
Negation operator.
Returns
The negative value of this.
        {
            return Q15(-v);
        }
References CWRUtil::Q15::Q15().
operator/()
Q10 operator/ (const Q5 & q5) const inline
Calculate Q15 / Q5 as a Q10.
Parameters
q5 The Q5 to divide this by.
Returns
The result of the operation.
        {
            return Q10(v / (int)q5);
        }
Member Data Documentation
v
int32_t v private
Referenced by CWRUtil::Q15::operator int().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/CWRUtil.hpp