Battery Simulator Documentation: CircleProgress
CircleProgress
#include "CircleProgress.hpp"
Public Member Functions
CircleProgress ()
virtual int getCapPrecision () const
virtual void getCenter (int &x, int &y) const
virtual int getEndAngle () const
virtual int getLineWidth () const
virtual int getRadius () const
virtual int getStartAngle () const
virtual void setAlpha (uint8_t newAlpha)
virtual void setCapPrecision (int precision)
virtual void setCenter (int x, int y)
virtual void setLineWidth (int width)
virtual void setPainter (AbstractPainter &painter)
virtual void setProgressIndicatorPosition (int16_t x, int16_t y, int16_t width, int16_t height)
virtual void setRadius (int r)
virtual void setStartEndAngle (int startAngle, int endAngle)
virtual void setValue (int value)
Public Member Functions inherited from AbstractProgressIndicator
AbstractProgressIndicator ()
virtual uint8_t getAlpha () const
virtual uint16_t getProgress (uint16_t range=100) const
virtual int16_t getProgressIndicatorHeight () const
virtual int16_t getProgressIndicatorWidth () const
virtual int16_t getProgressIndicatorX () const
virtual int16_t getProgressIndicatorY () const
virtual void getRange (int &min, int &max) const
virtual void getRange (int &min, int &max, uint16_t &steps) const
virtual void getRange (int &min, int &max, uint16_t &steps, uint16_t &minStep) const
virtual int getValue () const
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void setBackground (const Bitmap &bitmapBackground)
virtual void setEasingEquation (EasingEquation easingEquation)
virtual void setRange (int min, int max, uint16_t steps=0, uint16_t minStep=0)
void setValueSetAction (GenericCallback< const AbstractProgressIndicator & > &callback)
void setValueUpdatedAction (GenericCallback< const AbstractProgressIndicator & > &callback)
virtual void updateValue (int value, uint16_t duration)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
Circle circle
The circle.
int circleEndAngle
The end angle.
Protected Attributes inherited from AbstractProgressIndicator
int animationDuration
Duration of the animation.
int animationEndValue
The animation end value.
bool animationRunning
Is the animation running.
int animationStartValue
The animation start value.
int animationStep
The current animation step.
Image background
The background image.
int currentValue
The current value.
EasingEquation equation
The equation used in updateValue()
Container progressIndicatorContainer
The container that holds the actual progress indicator.
int rangeMax
The range maximum.
int rangeMin
The range minimum.
uint16_t rangeSteps
The range steps.
uint16_t rangeStepsMin
The range steps minimum.
GenericCallback< const AbstractProgressIndicator & > * valueSetCallback
New value assigned Callback.
GenericCallback< const AbstractProgressIndicator & > * valueUpdatedCallback
Animation ended Callback.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Detailed Description
A circle progress indicator uses CanvasWidgetRenderer for drawing the arc of a Circle to show progress. This means that the user must create a painter for painting the circle. The circle progress is defined by setting the minimum and maximum angle of the arc.
Note
As CircleProgress uses CanvasWidgetRenderer, it is important that a buffer is set up by calling CanvasWidgetRendere::setBuffer().
Constructor & Destructor Documentation
CircleProgress()
CircleProgress ()
    : AbstractProgressIndicator(), circle(), circleEndAngle(360)
{
    progressIndicatorContainer.add(circle);
    circle.setPosition(0, 0, getWidth(), getHeight());
    CircleProgress::setStartEndAngle(0, 360);
}
References Container::add(), CircleProgress::circle, Drawable::getHeight(), Drawable::getWidth(), AbstractProgressIndicator::progressIndicatorContainer, Drawable::setPosition(), and CircleProgress::setStartEndAngle().
Member Function Documentation
getCapPrecision()
virtual int getCapPrecision () const inline virtual
Gets the cap precision.
Returns
The cap precision.
See also
setCapPrecision
    {
        return circle.getCapPrecision();
    }
References CircleProgress::circle, and Circle::getCapPrecision().
getCenter()
void getCenter (int & x, int & y) const virtual
Gets the circle center coordinates.
Parameters
[out] x The x coordinate of the center of the circle.
[out] y The y coordinate of the center of the circle.
{
    circle.getCenter(x, y);
}
References CircleProgress::circle, and Circle::getCenter().
getEndAngle()
int getEndAngle () const virtual
Gets end angle in degrees. Beware that the value returned is not related to the current progress of the circle but rather the end point of the circle when it is at 100%.
Returns
The end angle.
See also
setStartEndAngle
Note
Angles are given in degrees, so a full circle is 360.
{
    return circleEndAngle;
}
References CircleProgress::circleEndAngle.
getLineWidth()
int getLineWidth () const virtual
Gets line width.
Returns
The line width.
See also
setLineWidth
{
    int width;
    circle.getLineWidth(width);
    return width;
}
References CircleProgress::circle, and Circle::getLineWidth().
getRadius()
int getRadius () const virtual
Gets the radius of the circle.
Returns
The radius.
{
    int radius;
    circle.getRadius(radius);
    return radius;
}
References CircleProgress::circle, and Circle::getRadius().
getStartAngle()
int getStartAngle () const virtual
Gets start angle in degrees.
Returns
The start angle.
See also
setStartEndAngle, getEndAngle
Note
Angles are given in degrees, so a full circle is 360.
{
    return circle.getArcStart();
}
References CircleProgress::circle, and Circle::getArcStart().
setAlpha()
void setAlpha (uint8_t newAlpha) virtual
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
The alpha can also be set on the Painter, but this can be controlled directly from the user app, setting alpha for the CircleProgress will set the alpha of the actual circle.
Reimplemented from AbstractProgressIndicator.
{
    AbstractProgressIndicator::setAlpha(newAlpha);
    circle.setAlpha(newAlpha);
}
References CircleProgress::circle, AbstractProgressIndicator::setAlpha(), and CanvasWidget::setAlpha().
setCapPrecision()
void setCapPrecision (int precision) virtual
Sets the cap precision of end of the circle arc. This is not used if line width is zero.
Parameters
precision The cap precision.
See also
Circle::setCapPrecision, getCapPrecision
{
    circle.setCapPrecision(precision);
}
References CircleProgress::circle, and Circle::setCapPrecision().
setCenter()
void setCenter (int x, int y) virtual
Sets the center of the circle / arc.
Parameters
x The x coordinate of the center of the circle.
y The y coordinate of the center of the circle.
{
    circle.setCenter(x, y);
}
References CircleProgress::circle, and Circle::setCenter().
setLineWidth()
void setLineWidth (int width) virtual
Sets line width of the circle. If a line width of zero is specified, it has a special meaning of drawing a filled circle (with the set radius) instead of just the circle arc.
Parameters
width The width of the line (0 produces a filled circle with the given radius).
See also
Circle::setLineWidth, setRadius
{
    circle.setLineWidth(width);
}
References CircleProgress::circle, and Circle::setLineWidth().
setPainter()
void setPainter (AbstractPainter & painter) virtual
Sets the painter to use for drawing the circle progress.
Parameters
[in] painter The painter.
See also
Circle::setPainter, AbstractPainter
{
    circle.setPainter(painter);
}
References CircleProgress::circle, and CanvasWidget::setPainter().
setProgressIndicatorPosition()
void setProgressIndicatorPosition (int16_t x, int16_t y, int16_t width, int16_t height) virtual
Sets the position and dimensions of the actual progress indicator relative to the background image.
Parameters
x The x coordinate.
y The y coordinate.
width The width of the box progress indicator.
height The height of the box progress indicator.
See also
getProgressIndicatorX, getProgressIndicatorY, getProgressIndicatorWidth, getProgressIndicatorHeight
Reimplemented from AbstractProgressIndicator.
{
    circle.setPosition(0, 0, width, height);
    AbstractProgressIndicator::setProgressIndicatorPosition(x, y, width, height);
}
References CircleProgress::circle, Drawable::setPosition(), and AbstractProgressIndicator::setProgressIndicatorPosition().
setRadius()
void setRadius (int r) virtual
Sets the radius of the circle.
Parameters
r The radius.
See also
Circle::setRadius
{
    circle.setRadius(r);
}
References CircleProgress::circle, and Circle::setRadius().
setStartEndAngle()
void setStartEndAngle (int startAngle, int endAngle) virtual
Sets start angle and end angle in degrees. By swapping end and start angles, circles can progress backwards.
Parameters
startAngle The start angle.
endAngle The end angle.
Note
Angles are given in degrees, so a full circle is 360.
{
    assert(startAngle != endAngle);
    circle.setArc(startAngle, endAngle);
    circleEndAngle = endAngle;
    CircleProgress::setValue(CircleProgress::getValue());
}
References CircleProgress::circle, CircleProgress::circleEndAngle, AbstractProgressIndicator::getValue(), Circle::setArc(), and CircleProgress::setValue().
Referenced by CircleProgress::CircleProgress().
setValue()
void setValue (int value) virtual
Sets the current value in the range (min..max) set by setRange(). Values lower than min are mapped to min, values higher than max are mapped to max. If a callback function has been set using setValueSetAction, that callback will be called (unless the new value is the same as the current value).
Parameters
value The value.
See also
getValue, updateValue, setValueSetAction
Note
if value is equal to the current value, nothing happens, and the callback will not be called.
Reimplemented from AbstractProgressIndicator.
{
    AbstractProgressIndicator::setValue(value);
    CWRUtil::Q5 startAngle;
    CWRUtil::Q5 const endAngle = CWRUtil::toQ5(circleEndAngle);
    circle.getArcStart<CWRUtil::Q5>(startAngle);
    const uint16_t rangeAngleSteps = endAngle < startAngle ? (int)(startAngle - endAngle) : (int)(endAngle - startAngle);
    CWRUtil::Q5 const progress = CWRUtil::Q5(AbstractProgressIndicator::getProgress(rangeAngleSteps));
    if (endAngle < startAngle)
    {
        circle.updateArcEnd<CWRUtil::Q5>(startAngle - progress);
    }
    else
    {
        circle.updateArcEnd<CWRUtil::Q5>(startAngle + progress);
    }
}
References CircleProgress::circle, CircleProgress::circleEndAngle, Circle::getArcStart(), AbstractProgressIndicator::getProgress(), progress, AbstractProgressIndicator::setValue(), CWRUtil::toQ5(), and Circle::updateArcEnd().
Referenced by CircleProgress::setStartEndAngle().
Member Data Documentation
circle
Circle circle protected
The circle.
Referenced by CircleProgress::CircleProgress(), CircleProgress::getCapPrecision(), CircleProgress::getCenter(), CircleProgress::getLineWidth(), CircleProgress::getRadius(), CircleProgress::getStartAngle(), CircleProgress::setAlpha(), CircleProgress::setCapPrecision(), CircleProgress::setCenter(), CircleProgress::setLineWidth(), CircleProgress::setPainter(), CircleProgress::setProgressIndicatorPosition(), CircleProgress::setRadius(), CircleProgress::setStartEndAngle(), and CircleProgress::setValue().
circleEndAngle
int circleEndAngle protected
The end angle.
Referenced by CircleProgress::getEndAngle(), CircleProgress::setStartEndAngle(), and CircleProgress::setValue().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/progress_indicators/CircleProgress.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/progress_indicators/CircleProgress.cpp