Battery Simulator Documentation: DoubleBufferedVideoController< no_streams, width, height, stride, output_format >
DoubleBufferedVideoController< no_streams, width, height, stride, output_format >
#include "DoubleBufferedVideoController.hpp"
Classes
class Stream
Public Member Functions
DoubleBufferedVideoController ()
void addDecoder (MJPEGDecoder &decoder, uint32_t index)
void decoderTaskEntry ()
virtual void draw (const Handle handle, const touchgfx::Rect &invalidatedArea, const touchgfx::VideoWidget &widget)
void endFrame ()
virtual uint32_t getCurrentFrameNumber (const Handle handle)
virtual bool getIsPlaying (const Handle handle)
virtual void getVideoInformation (const Handle handle, touchgfx::VideoInformation *data)
virtual Handle registerVideoWidget (touchgfx::VideoWidget &widget)
virtual void setCommand (const Handle handle, Command cmd, uint32_t param)
virtual void setFrameRate (const Handle handle, uint32_t ui_frames, uint32_t video_frames)
void setRGBBuffer (uint8_t *buffer, size_t sizeOfBuffer)
virtual void setVideoData (const Handle handle, const uint8_t *movie, const uint32_t length)
virtual void setVideoData (const Handle handle, VideoDataReader &reader)
virtual void setVideoFrameRateCompensation (bool allow)
virtual void unregisterVideoWidget (const Handle handle)
virtual bool updateFrame (const Handle handle, touchgfx::VideoWidget &widget)
Public Member Functions inherited from VideoController
virtual ~VideoController ()
virtual void setVideoData (const Handle handle, VideoDataReader &reader)=0
Private Types
enum { NO_STREAM = 0xFFFF }
Private Member Functions
void clearState (const Handle handle)
bool decodeForNextTick (Stream &stream)
Handle getFreeHandle ()
uint32_t getStreamIndexToDecode ()
Private Attributes
bool allowSkipFrames
uint8_t * bufferRGB
MJPEGDecoder * mjpegDecoders [no_streams]
MUTEX_TYPE mutexBuffers
SEM_TYPE semDecode
size_t sizeBufferRGB
Stream streams [no_streams]
uint8_t * topBufferRGB
Additional Inherited Members
Public Types inherited from VideoController
enum Command {
PLAY , PAUSE , SEEK , SHOW ,
STOP , SET_REPEAT
}
typedef uint32_t Handle
Static Public Member Functions inherited from VideoController
static VideoController & getInstance ()
Detailed Description
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format>
class DoubleBufferedVideoController< no_streams, width, height, stride, output_format >
Member Enumeration Documentation
anonymous enum
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> anonymous enum private
Enumerator
NO_STREAM
    {
        NO_STREAM = 0xFFFF
    };
Constructor & Destructor Documentation
DoubleBufferedVideoController()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> DoubleBufferedVideoController () inline
        : VideoController(),
          bufferRGB(0), sizeBufferRGB(0), topBufferRGB(0), allowSkipFrames(true),
          semDecode(0), mutexBuffers(0)
    {
        assert((no_streams > 0) && "Video: Number of streams zero!");
        // Clear decoder array
        memset(mjpegDecoders, 0, sizeof(mjpegDecoders));
        // Initialize synchronization primitives
        semDecode = SEM_CREATE(); // Binary semaphore
        mutexBuffers = MUTEX_CREATE();
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::mjpegDecoders, MUTEX_CREATE, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::mutexBuffers, SEM_CREATE, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::semDecode.
Member Function Documentation
addDecoder()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> void addDecoder (MJPEGDecoder & decoder, uint32_t index) inline
    {
        // Running in UI thread / main
        assert(index < no_streams);
        mjpegDecoders[index] = &decoder;
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::mjpegDecoders.
clearState()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> void clearState (const Handle handle) inline private
    {
        // Stop playing, and clear next buffer if any, cancel ongoing decoding
        setCommand(handle, STOP, 0);
        MUTEX_LOCK(mutexBuffers);
        Stream& stream = streams[handle];
        if (stream.nextBuffer != 0)
        {
            // Ignore any decoded buffer
            stream.nextBuffer = 0;
        }
        stream.cancelDecoding = true;
        stream.isPlaying = false;
        MUTEX_UNLOCK(mutexBuffers);
    }
References MUTEX_LOCK, MUTEX_UNLOCK, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::mutexBuffers, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::Stream::nextBuffer, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setCommand(), VideoController::STOP, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::streams.
Referenced by DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setVideoData(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setVideoData().
decodeForNextTick()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> bool decodeForNextTick (Stream & stream) inline private
    {
        // Running in UI thread
        // Compare tickCount/frameCount to frame_rate_ticks/frame_rate_video
        if ((stream.tickCount * stream.frame_rate_video) >= (stream.frame_rate_ticks * stream.frameCount))
        {
            if (allowSkipFrames)
            {
                stream.skip_frames = (stream.tickCount * stream.frame_rate_video - stream.frame_rate_ticks * stream.frameCount) / stream.frame_rate_ticks;
                if (stream.skip_frames > 0)
                {
                    stream.skip_frames--;
                }
            }
            return true;
        }
        return false;
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::allowSkipFrames.
Referenced by DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::updateFrame().
decoderTaskEntry()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> void decoderTaskEntry () inline
    {
        // Running in Decoder thread!!
        while (1)
        {
            // Look for a stream to decode
            uint32_t stream_index = getStreamIndexToDecode();
            if ((stream_index == NO_STREAM))
            {
                // All streams decoded, wait for synchronisation signal from UI thread
                SEM_WAIT(semDecode);
                // Try from the beginning
                continue;
            }
            // Lock out UI by taking the mutex
            MUTEX_LOCK(mutexBuffers);
            // Now decode the stream
            Stream& stream = streams[stream_index];
            // Select the unused buffer for decoding
            uint8_t* decodeBuffer = (stream.currentBuffer == stream.bufferA) ? stream.bufferB : stream.bufferA;
            MJPEGDecoder* const decoder = mjpegDecoders[stream_index];
            // Seek or increment video frame
            if (stream.seek_to_frame > 0)
            {
                decoder->gotoFrame(stream.seek_to_frame);
                stream.seek_to_frame = 0;
                stream.cancelDecoding = false;
            }
            else
            {
                if (stream.skip_frames > 0)
                {
                    decoder->gotoFrame(decoder->getCurrentFrameNumber() + stream.skip_frames);
                    stream.frameCount += stream.skip_frames;
                    stream.skip_frames = 0;
                }
            }
            // Unlock mutex while decoding
            MUTEX_UNLOCK(mutexBuffers);
            // Decode frame
            const bool hasMoreFrames = decoder->decodeNextFrame(decodeBuffer, width, height, stride);
            MUTEX_LOCK(mutexBuffers);
            // Save new frame in stream unless cancelled
            if (stream.cancelDecoding)
            {
                stream.cancelDecoding = false;
            }
            else
            {
                stream.nextBuffer = decodeBuffer;
                if (hasMoreFrames)
                {
                    stream.frameNumberNext = decoder->getCurrentFrameNumber() - 1; // Points to frame after this
                }
                else
                {
                    stream.frameNumberNext = 1;
                }
                stream.hasMoreFramesAfterNext = hasMoreFrames;
                // Lower decode flag
                stream.doDecodeNewFrame = false;
            }
            // Release the mutex
            MUTEX_UNLOCK(mutexBuffers);
        }
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::Stream::bufferB, MJPEGDecoder::decodeNextFrame(), MJPEGDecoder::getCurrentFrameNumber(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::getStreamIndexToDecode(), MJPEGDecoder::gotoFrame(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::mjpegDecoders, MUTEX_LOCK, MUTEX_UNLOCK, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::mutexBuffers, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::NO_STREAM, SEM_WAIT, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::semDecode, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::streams.
draw()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> virtual void draw (const Handle handle, const touchgfx::Rect & invalidatedArea, const touchgfx::VideoWidget & widget) inline virtual
Draw the video content.
Parameters
handle The stream handle.
invalidatedArea The area of the widget that must be redrawn.
widget Reference to the widget.
Implements VideoController.
    {
        // Running in UI thread
        // Nothing in this decoder
    }
endFrame()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> void endFrame () inline
    {
        // Running in UI thread
        // Nothing to do
    }
getCurrentFrameNumber()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> virtual uint32_t getCurrentFrameNumber (const Handle handle) inline virtual
Get the current frame number.
Parameters
handle The stream handle.
Returns
Return the current frame number.
Implements VideoController.
    {
        assert(handle < no_streams);
        const Stream& stream = streams[handle];
        return stream.frameNumberShown;
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::Stream::frameNumberShown, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::streams.
getFreeHandle()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> Handle getFreeHandle () inline private
    {
        // Running in UI thread
        for (uint32_t i = 0; i < no_streams; i++)
        {
            if (streams[i].isActive == false)
            {
                // Reset stream parameters
                streams[i] = Stream();
                return static_cast<VideoController::Handle>(i);
            }
        }
        assert(0 && "Unable to find free video stream handle!");
        return static_cast<VideoController::Handle>(0);
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::streams.
Referenced by DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::registerVideoWidget().
getIsPlaying()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> virtual bool getIsPlaying (const Handle handle) inline virtual
Check if the video stream is playing (not paused or stopped).
Parameters
handle The stream handle.
Returns
Returns true if the video is playing.
Implements VideoController.
    {
        assert(handle < no_streams);
        Stream& stream = streams[handle];
        return stream.isPlaying;
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::Stream::isPlaying, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::streams.
getStreamIndexToDecode()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> uint32_t getStreamIndexToDecode () inline private
    {
        for (uint32_t i = 0; i < no_streams; i++)
        {
            Stream& stream = streams[i];
            if (stream.doDecodeNewFrame) // Marked by UI for decoding
            {
                return i;
            }
        }
        return NO_STREAM;
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::NO_STREAM, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::streams.
Referenced by DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::decoderTaskEntry().
getVideoInformation()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> virtual void getVideoInformation (const Handle handle, touchgfx::VideoInformation * data) inline virtual
Get Video information.
Get information from the video data.
Parameters
handle The stream handle.
[in,out] data Pointer to VideoInformation where information should be stored.
Implements VideoController.
    {
        assert(handle < no_streams);
        mjpegDecoders[handle]->getVideoInfo(data);
    }
References MJPEGDecoder::getVideoInfo(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::mjpegDecoders.
registerVideoWidget()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> virtual Handle registerVideoWidget (touchgfx::VideoWidget & widget) inline virtual
Register a VideoWidget to get a Handle.
Parameters
[in,out] widget The VideoWidget.
Returns
A video stream handle.
Implements VideoController.
    {
        // Running in UI thread
        // Find stream handle for Widget
        Handle handle = getFreeHandle();
        streams[handle].isActive = true;
        // Set Widget buffer format and address
        widget.setVideoBufferFormat(output_format, width, height);
        widget.setVideoBuffer((uint8_t*)0);
        streams[handle].frameNumberShown = 0;
        // Todo, make buffer size depending on widget
        const uint32_t sizeOfOneDecodeBuffer = height * stride;
        // Allocate two buffers for this stream, if possible
        if (topBufferRGB + 2 * sizeOfOneDecodeBuffer > (bufferRGB + sizeBufferRGB))
        {
            assert(0 && "registerVideoWidget: Unable to allocate two RGB buffers!");
            return 0xFFFFFFFF;
        }
        streams[handle].bufferA = (uint8_t*)topBufferRGB;
        topBufferRGB += sizeOfOneDecodeBuffer;
        streams[handle].bufferB = (uint8_t*)topBufferRGB;
        topBufferRGB += sizeOfOneDecodeBuffer;
        return handle;
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::Stream::bufferA, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::Stream::bufferB, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::bufferRGB, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::Stream::frameNumberShown, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::getFreeHandle(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::Stream::isActive, VideoWidget::setVideoBuffer(), VideoWidget::setVideoBufferFormat(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::sizeBufferRGB, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::streams, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::topBufferRGB.
setCommand()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> virtual void setCommand (const Handle handle, Command cmd, uint32_t param) inline virtual
Pass a command from the Widget to the Controller.
Parameters
handle The stream handle.
cmd The Command.
param A parameter.
Implements VideoController.
    {
        // Running in UI thread
        assert(handle < no_streams);
        Stream& stream = streams[handle];
        switch (cmd)
        {
        case PLAY:
            // Cannot Play without movie
            if (mjpegDecoders[handle]->hasVideo())
            {
                MUTEX_LOCK(mutexBuffers);
                stream.isPlaying = true;
                stream.cancelDecoding = false;
                // Reset counters
                stream.frameCount = 0;
                stream.tickCount = 0;
                // Seek to start of video if stopped
                if (stream.isStopped)
                {
                    stream.seek_to_frame = 1;
                }
                stream.isStopped = false;
                // Kick decoder if next buffer is available
                stream.skip_frames = 0;
                if (stream.nextBuffer == 0)
                {
                    stream.doDecodeNewFrame = true;
                    SEM_POST(semDecode);
                }
                MUTEX_UNLOCK(mutexBuffers);
            }
            break;
        case PAUSE:
            stream.isPlaying = false;
            stream.isStopped = false;
            break;
        case SEEK:
            stream.seek_to_frame = param;
            // Reset counters
            stream.frameCount = 0;
            stream.tickCount = 0;
            break;
        case SHOW:
            stream.seek_to_frame = param;
            // Reset counters
            stream.frameCount = 0;
            stream.tickCount = 0;
            stream.isStopped = false;
            break;
        case STOP:
            stream.isPlaying = false;
            stream.isStopped = true;
            break;
        case SET_REPEAT:
            stream.repeat = (param > 0);
            break;
        }
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::mjpegDecoders, MUTEX_LOCK, MUTEX_UNLOCK, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::mutexBuffers, VideoController::PAUSE, VideoController::PLAY, VideoController::SEEK, SEM_POST, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::semDecode, VideoController::SET_REPEAT, VideoController::SHOW, VideoController::STOP, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::streams.
Referenced by DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::clearState().
setFrameRate()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> virtual void setFrameRate (const Handle handle, uint32_t ui_frames, uint32_t video_frames) inline virtual
Set the framerate for video using a qoutient of screen frames /video frames.
To get 20 video frames pr second on a 60 fps display use video_frames = 20 and ui_frames = 60.
Parameters
handle The stream handle.
ui_frames Number of UI frames (divider)
video_frames Number of video_frames (dividend)
Implements VideoController.
    {
        // Running in UI thread
        assert(handle < no_streams);
        Stream& stream = streams[handle];
        // Reset counters
        stream.tickCount = 0;
        stream.frameCount = 0;
        // Save requested frame rate ratio
        stream.frame_rate_ticks = ui_frames;
        stream.frame_rate_video = video_frames;
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::streams, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::Stream::tickCount.
setRGBBuffer()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> void setRGBBuffer (uint8_t * buffer, size_t sizeOfBuffer) inline
    {
        // Running in UI thread / main
        bufferRGB = buffer;
        topBufferRGB = bufferRGB;
        sizeBufferRGB = sizeOfBuffer;
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::bufferRGB, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::sizeBufferRGB, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::topBufferRGB.
setVideoData() [1/2]
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> virtual void setVideoData (const Handle handle, const uint8_t * movie, const uint32_t length) inline virtual
Set the video data for the stream.
Parameters
handle The stream handle.
movie Pointer to the video data.
length Length of the video data.
Implements VideoController.
    {
        // Running in UI thread
        mjpegDecoders[handle]->setVideoData(movie, length);
        clearState(handle);
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::clearState(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::mjpegDecoders, and MJPEGDecoder::setVideoData().
setVideoData() [2/2]
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> virtual void setVideoData (const Handle handle, VideoDataReader & reader) inline virtual
    {
        // Running in UI thread
        mjpegDecoders[handle]->setVideoData(reader);
        clearState(handle);
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::clearState(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::mjpegDecoders, and MJPEGDecoder::setVideoData().
setVideoFrameRateCompensation()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> virtual void setVideoFrameRateCompensation (bool allow) inline virtual
Allow skipping of video frames to compensate for long decoding times.
Parameters
allow true if compensation is allowed.
Implements VideoController.
    {
        allowSkipFrames = allow;
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::allowSkipFrames.
unregisterVideoWidget()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> virtual void unregisterVideoWidget (const Handle handle) inline virtual
Unregister a VideoWidget to release the handle.
Parameters
handle The stream handle.
Implements VideoController.
    {
        // Running in UI thread
        // Reset active for this handle
        streams[handle].isActive = false;
        // If all handles are free, reset top pointer
        bool oneIsActive = false;
        for (uint32_t i = 0; i < no_streams; i++)
        {
            oneIsActive |= streams[i].isActive;
        }
        if (oneIsActive == false)
        {
            // Reset memory usage
            topBufferRGB = bufferRGB;
        }
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::bufferRGB, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::Stream::isActive, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::streams, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::topBufferRGB.
updateFrame()
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> virtual bool updateFrame (const Handle handle, touchgfx::VideoWidget & widget) inline virtual
Called by VideoWidget::handleTickEvent. Update frame counters. Decide if widget should be invalidated.
Implements VideoController.
    {
        // Running in UI thread
        assert(handle < no_streams);
        Stream& stream = streams[handle];
        // Increase tickCount if playing
        if (stream.isPlaying)
        {
            stream.tickCount += HAL::getInstance()->getLCDRefreshCount();
        }
        // Assume more frames are available, flag is lowered once, when changing to the last frame
        bool hasMoreFrames = true;
        // See if we have a nextBuffer and if next frame of specific frame is to be decoded
        if (stream.nextBuffer && (decodeForNextTick(stream) || stream.seek_to_frame > 0))
        {
            MUTEX_LOCK(mutexBuffers);
            // Do nothing if seek to frame
            if (stream.seek_to_frame > 0)
            {
                stream.nextBuffer = 0;
            }
            if (stream.nextBuffer != 0)
            {
                // Use nextBuffer as current
                stream.currentBuffer = stream.nextBuffer;
                stream.nextBuffer = 0;
                // Copy frameNumber, increase count
                stream.frameNumberShown = stream.frameNumberNext;
                stream.frameCount++;
                hasMoreFrames = stream.hasMoreFramesAfterNext;
                // Update widget to show current buffer
                widget.setVideoBuffer(stream.currentBuffer);
                widget.invalidate();
                if (!hasMoreFrames && !stream.repeat)
                {
                    stream.isPlaying = false;
                }
            }
            MUTEX_UNLOCK(mutexBuffers);
        }
        // Kick decoder if playing or seeking frame and next buffer is ready
        if ((stream.isPlaying || stream.seek_to_frame > 0) && (stream.nextBuffer == 0))
        {
            stream.doDecodeNewFrame = true;
            SEM_POST(semDecode);
        }
        return hasMoreFrames;
    }
References DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::decodeForNextTick(), Drawable::invalidate(), MUTEX_LOCK, MUTEX_UNLOCK, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::mutexBuffers, SEM_POST, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::semDecode, VideoWidget::setVideoBuffer(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::streams, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::Stream::tickCount.
Member Data Documentation
allowSkipFrames
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> bool allowSkipFrames private
Referenced by DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::decodeForNextTick(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setVideoFrameRateCompensation().
bufferRGB
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> uint8_t* bufferRGB private
Referenced by DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::registerVideoWidget(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setRGBBuffer(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::unregisterVideoWidget().
mjpegDecoders
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> MJPEGDecoder* mjpegDecoders[no_streams] private
Referenced by DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::DoubleBufferedVideoController(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::addDecoder(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::decoderTaskEntry(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::getVideoInformation(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setCommand(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setVideoData(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setVideoData().
mutexBuffers
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> MUTEX_TYPE mutexBuffers private
Referenced by DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::DoubleBufferedVideoController(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::clearState(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::decoderTaskEntry(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setCommand(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::updateFrame().
semDecode
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> SEM_TYPE semDecode private
Referenced by DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::DoubleBufferedVideoController(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::decoderTaskEntry(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setCommand(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::updateFrame().
sizeBufferRGB
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> size_t sizeBufferRGB private
Referenced by DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::registerVideoWidget(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setRGBBuffer().
streams
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> Stream streams[no_streams] private
Referenced by DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::clearState(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::decoderTaskEntry(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::getCurrentFrameNumber(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::getFreeHandle(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::getIsPlaying(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::getStreamIndexToDecode(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::registerVideoWidget(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setCommand(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setFrameRate(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::unregisterVideoWidget(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::updateFrame().
topBufferRGB
template<uint32_t no_streams, uint32_t width, uint32_t height, uint32_t stride, touchgfx::Bitmap::BitmapFormat output_format> uint8_t* topBufferRGB private
Referenced by DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::registerVideoWidget(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setRGBBuffer(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::unregisterVideoWidget().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/target/generated/DoubleBufferedVideoController.hpp