Battery Simulator Documentation: TextArea
TextArea
#include "TextArea.hpp"
Classes
class BoundingArea
Public Member Functions
TextArea ()
virtual int16_t calculateTextHeight (const Unicode::UnicodeChar *format,...) const
virtual void draw (const Rect &area) const
virtual Alignment getAlignment () const
uint8_t getAlpha () const
FORCE_INLINE_FUNCTION colortype getColor () const
FORCE_INLINE_FUNCTION uint8_t getIndentation ()
FORCE_INLINE_FUNCTION int16_t getLinespacing () const
TextRotation getRotation () const
virtual Rect getSolidRect () const
virtual int16_t getTextHeight () const
virtual uint16_t getTextWidth () const
const TypedText & getTypedText () const
WideTextAction getWideTextAction () const
virtual const Unicode::UnicodeChar * getWildcard1 () const
virtual const Unicode::UnicodeChar * getWildcard2 () const
virtual void invalidateContent () const
void resizeHeightToCurrentText ()
void resizeHeightToCurrentTextWithRotation ()
void resizeToCurrentText ()
void resizeToCurrentTextWithAlignment ()
virtual void setAlpha (uint8_t newAlpha)
virtual void setBaselineY (int16_t baselineY)
FORCE_INLINE_FUNCTION void setColor (colortype newColor)
virtual void setHeight (int16_t height)
FORCE_INLINE_FUNCTION void setIndentation (uint8_t indent)
FORCE_INLINE_FUNCTION void setLinespacing (int16_t space)
FORCE_INLINE_FUNCTION void setRotation (const TextRotation textRotation)
void setTypedText (const TypedText &t)
FORCE_INLINE_FUNCTION void setWideTextAction (WideTextAction action)
virtual void setWidth (int16_t width)
virtual void setXBaselineY (int16_t x, int16_t baselineY)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual TextArea::BoundingArea calculateBoundingArea () const
Protected Attributes
uint8_t alpha
The alpha to use.
BoundingArea boundingArea
Bounding area of this text area.
colortype color
The color to use for the text.
uint8_t indentation
The indentation of the text inside the text area.
int16_t linespace
The extra space between lines of text, measured in pixels.
TextRotation rotation
The text rotation to use in steps of 90 degrees.
TypedText typedText
The TypedText to display.
WideTextAction wideTextAction
What to do if the lines of text are wider than the text area.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Static Protected Attributes
static const uint16_t newLine = 10
NewLine value.
Detailed Description
This widget is capable of showing a text area on the screen. The text must be a predefined TypedText in the text sheet in the assets folder. In order to display a dynamic text, use TextAreaWithOneWildcard or TextAreaWithTwoWildcards.
See also
TypedText, TextAreaWithOneWildcard, TextAreaWithTwoWildcards
Note
A TextArea just holds a pointer to the text displayed. The developer must ensure that the pointer remains valid when drawing.
Constructor & Destructor Documentation
TextArea()
TextArea () inline
        : Widget(), typedText(TYPED_TEXT_INVALID), color(0), linespace(0), alpha(255), indentation(0), rotation(TEXT_ROTATE_0), wideTextAction(WIDE_TEXT_NONE), boundingArea()
    {
    }
Member Function Documentation
calculateBoundingArea()
TextArea::BoundingArea calculateBoundingArea () const protected virtual
Calculates the minimum bounding rectangle of this text area and correlates it with the containing text, to get the bounding area. Note: The bounding rectangle is adjusted according to alignment and rotation.
Returns
The bounding area.
Reimplemented in TextAreaWithWildcardBase.
{
    if (!typedText.hasValidId())
    {
        return TextArea::BoundingArea(); // Return Invalid BoundingArea
    }
    const Font* fontToDraw = typedText.getFont();
    const Unicode::UnicodeChar* textToDraw = typedText.getText();
    const int16_t fontHeight = fontToDraw->getHeight();
    const int16_t lineHeight = fontHeight + linespace;
    int16_t width = 0;
    uint16_t numberOfLines = 0;
    if (wideTextAction == WIDE_TEXT_NONE)
    {
        TextProvider textProvider;
        textProvider.initialize(textToDraw, fontToDraw->getGSUBTable(), fontToDraw->getContextualFormsTable(), getWildcard1(), getWildcard2());
        int16_t widgetRectHeight = (rotation == TEXT_ROTATE_0 || rotation == TEXT_ROTATE_180) ? getHeight() : getWidth();
        // Iterate through each line, find the longest line width and sum up the total height of the bounding rectangle
        do
        {
            const uint16_t lineWidth = LCD::stringWidth(textProvider, *(fontToDraw), 0x7FFF, typedText.getTextDirection());
            width = MAX(width, lineWidth);
            numberOfLines++;
            widgetRectHeight -= lineHeight;
            // Keep reading until end of string or next line completely invisible.
        } while (!textProvider.endOfString() && widgetRectHeight + fontToDraw->getPixelsAboveTop() > 0);
    }
    else
    {
        TextProvider wideTextProvider;
        wideTextProvider.initialize(textToDraw, fontToDraw->getGSUBTable(), fontToDraw->getContextualFormsTable(), getWildcard1(), getWildcard2());
        const int16_t widgetRectWidth = (rotation == TEXT_ROTATE_0 || rotation == TEXT_ROTATE_180) ? getWidth() : getHeight();
        int16_t widgetRectHeight = (rotation == TEXT_ROTATE_0 || rotation == TEXT_ROTATE_180) ? getHeight() : getWidth();
        LCD::WideTextInternalStruct wtis(wideTextProvider, widgetRectWidth - indentation, widgetRectHeight, typedText.getTextDirection(), fontToDraw, linespace, wideTextAction);
        // Iterate through each line, find the longest line width and sum up the total height of the bounding rectangle
        do
        {
            wtis.scanStringLengthForLine();
            const uint16_t lineWidth = wtis.getLineWidth();
            width = MAX(width, lineWidth);
            numberOfLines++;
            widgetRectHeight -= lineHeight;
            // Keep reading until end of string, ellipsis inserted or next line completely invisible.
        } while (wtis.getCurrChar() != 0 && !wtis.ellipsisAtEndOfLine() && widgetRectHeight + fontToDraw->getPixelsAboveTop() > 0);
    }
    int16_t height = (numberOfLines * lineHeight) - linespace;
    height = MAX(height, fontHeight) + fontToDraw->getPixelsBelowBottom();
    Rect boundingRect(0, 0, width, height);
    // Adjust for alignment
    const int16_t areaWidth = (rotation == TEXT_ROTATE_0 || rotation == TEXT_ROTATE_180) ? getWidth() : getHeight();
    switch (getAlignment())
    {
    default:
    case LEFT:
        boundingRect.x = indentation;
        break;
    case CENTER:
        boundingRect.x = ((areaWidth - boundingRect.width) / 2);
        break;
    case RIGHT:
        boundingRect.x = areaWidth - (boundingRect.width + indentation);
        break;
    }
    // Adjust for left and right pixels offsets
    const uint8_t maxPixelsLeft = fontToDraw->getMaxPixelsLeft();
    const uint8_t maxPixelsRight = fontToDraw->getMaxPixelsRight();
    boundingRect.x -= maxPixelsLeft;
    boundingRect.width += (maxPixelsLeft + maxPixelsRight);
    // Adjust for rotation
    switch (rotation)
    {
    case TEXT_ROTATE_0:
        break;
    case TEXT_ROTATE_90:
        boundingRect = Rect(getWidth() - boundingRect.bottom(), boundingRect.x, boundingRect.height, boundingRect.width);
        break;
    case TEXT_ROTATE_180:
        boundingRect = Rect(getWidth() - boundingRect.right(), getHeight() - boundingRect.bottom(), boundingRect.width, boundingRect.height);
        break;
    case TEXT_ROTATE_270:
        boundingRect = Rect(boundingRect.y, getHeight() - boundingRect.right(), boundingRect.height, boundingRect.width);
        break;
    }
    return TextArea::BoundingArea(boundingRect, typedText.getText());
}
References touchgfx::CENTER, TextArea::getAlignment(), TypedText::getFont(), Drawable::getHeight(), TypedText::getText(), TypedText::getTextDirection(), Drawable::getWidth(), TextArea::getWildcard1(), TextArea::getWildcard2(), TypedText::hasValidId(), TextArea::indentation, touchgfx::LEFT, TextArea::linespace, MAX, touchgfx::RIGHT, TextArea::rotation, LCD::stringWidth(), touchgfx::TEXT_ROTATE_0, touchgfx::TEXT_ROTATE_180, touchgfx::TEXT_ROTATE_270, touchgfx::TEXT_ROTATE_90, TextArea::typedText, touchgfx::WIDE_TEXT_NONE, and TextArea::wideTextAction.
Referenced by TextArea::setHeight(), TextArea::setIndentation(), TextArea::setLinespacing(), TextArea::setRotation(), TextArea::setTypedText(), TextArea::setWideTextAction(), and TextArea::setWidth().
calculateTextHeight()
int16_t calculateTextHeight (const Unicode::UnicodeChar * format, ...) const virtual
Gets the total height needed by the text. Determined by number of lines and linespace. The number of parameters passed after the format, must match the number of wildcards in the TypedText.
Parameters
format The text containing <placeholder> wildcards.
... Variable arguments providing additional information.
Returns
the total height needed by the text.
{
    if (!typedText.hasValidId())
    {
        return 0;
    }
    va_list pArg;
    va_start(pArg, format);
    const Font* fontToDraw = typedText.getFont();
    const int16_t textHeight = fontToDraw->getHeight();
    TextProvider textProvider;
    textProvider.initialize(format, pArg, fontToDraw->getGSUBTable(), fontToDraw->getContextualFormsTable());
    const int16_t numLines = LCD::getNumLines(textProvider, wideTextAction, typedText.getTextDirection(), typedText.getFont(), getWidth() - indentation);
    va_end(pArg);
    return textHeight + linespace > 0 ? numLines * textHeight + (numLines - 1) * linespace : (numLines > 0 ? textHeight : 0);
}
References TypedText::getFont(), LCD::getNumLines(), TypedText::getTextDirection(), Drawable::getWidth(), TypedText::hasValidId(), TextArea::indentation, TextArea::linespace, TextArea::typedText, and TextArea::wideTextAction.
Referenced by TextArea::getTextHeight().
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Implements Drawable.
Reimplemented in TextAreaWithWildcardBase.
{
    if (typedText.hasValidId())
    {
        Rect rectToDraw = area;
        if (typedText.hasValidId() && boundingArea.isValid(typedText.getText()))
        {
            rectToDraw &= boundingArea.getRect();
        }
        if (!rectToDraw.isEmpty())
        {
            const Font* fontToDraw = typedText.getFont();
            if (fontToDraw != 0)
            {
                const LCD::StringVisuals visuals(fontToDraw, color, alpha, getAlignment(), linespace, rotation, typedText.getTextDirection(), indentation, wideTextAction);
                HAL::lcd().drawString(getAbsoluteRect(), rectToDraw, visuals, typedText.getText(), getWildcard1(), getWildcard2());
            }
        }
    }
}
References TextArea::boundingArea, Drawable::getAbsoluteRect(), TextArea::getAlignment(), TypedText::getFont(), TextArea::BoundingArea::getRect(), TypedText::getText(), TypedText::getTextDirection(), TextArea::getWildcard1(), TextArea::getWildcard2(), TypedText::hasValidId(), TextArea::indentation, TextArea::BoundingArea::isValid(), HAL::lcd(), TextArea::linespace, TextArea::rotation, TextArea::typedText, and TextArea::wideTextAction.
getAlignment()
Alignment getAlignment () const virtual
Gets the alignment of text inside the TextArea.
Returns
The alignment.
{
    if (typedText.hasValidId())
    {
        return typedText.getAlignment();
    }
    return LEFT;
}
References TypedText::getAlignment(), TypedText::hasValidId(), touchgfx::LEFT, and TextArea::typedText.
Referenced by TextArea::calculateBoundingArea(), TextArea::draw(), and TextArea::resizeToCurrentTextWithAlignment().
getAlpha()
uint8_t getAlpha () const inline
Gets the current alpha value of the widget. The alpha value is in range 255 (solid) to 0 (invisible).
Returns
The current alpha value.
See also
setAlpha
    {
        return alpha;
    }
References TextArea::alpha.
Referenced by DigitalClock::getAlpha().
getColor()
FORCE_INLINE_FUNCTION colortype getColor () const inline
Gets the color of the text. If no color has been set, the default color, black, is returned.
Returns
The color to used for drawing the text.
    {
        return color;
    }
References TextArea::color.
Referenced by DigitalClock::getColor(), and TextProgress::getColor().
getIndentation()
FORCE_INLINE_FUNCTION uint8_t getIndentation () inline
Gets the indentation of text inside the TextArea.
Returns
The indentation.
See also
setIndentation
    {
        return indentation;
    }
References TextArea::indentation.
getLinespacing()
FORCE_INLINE_FUNCTION int16_t getLinespacing () const inline
Gets the line spacing of the TextArea. If no line spacing has been set, the line spacing is 0.
Returns
The line spacing.
See also
setLinespacing
    {
        return linespace;
    }
References TextArea::linespace.
getRotation()
TextRotation getRotation () const inline
Gets rotation of the text in the TextArea.
Returns
The rotation of the text.
See also
setRotation
    {
        return rotation;
    }
References TextArea::rotation.
getSolidRect()
virtual Rect getSolidRect () const inline virtual
Get (the largest possible) rectangle that is guaranteed to be solid (opaque). This information is important, as any Drawable underneath the solid area does not need to be drawn.
Returns
The solid rectangle part of the Drawable.
Note
The rectangle returned must be relative to upper left corner of the Drawable, meaning that a completely solid widget should return the full size Rect(0, 0, getWidth(), getHeight()). If no area can be guaranteed to be solid, an empty Rect must be returned. Failing to return the correct rectangle may result in errors on the display.
Implements Drawable.
    {
        return Rect();
    }
getTextHeight()
int16_t getTextHeight () const virtual
Gets the total height needed by the text, taking number of lines and line spacing into consideration.
Returns
the total height needed by the text.
{
    return typedText.hasValidId() ? calculateTextHeight(typedText.getText(), getWildcard1(), getWildcard2()) : 0;
}
References TextArea::calculateTextHeight(), TypedText::getText(), TextArea::getWildcard1(), TextArea::getWildcard2(), TypedText::hasValidId(), and TextArea::typedText.
Referenced by TextArea::resizeHeightToCurrentText(), TextArea::resizeHeightToCurrentTextWithRotation(), TextArea::resizeToCurrentText(), and TextArea::resizeToCurrentTextWithAlignment().
getTextWidth()
uint16_t getTextWidth () const virtual
Gets the width in pixels of the current associated text in the current selected language. In case of multi-lined text the width of the widest line is returned.
Returns
The width in pixels of the current text.
{
    return typedText.hasValidId() ? typedText.getFont()->getStringWidth(typedText.getTextDirection(), typedText.getText(), getWildcard1(), getWildcard2()) : 0;
}
References TypedText::getFont(), TypedText::getText(), TypedText::getTextDirection(), TextArea::getWildcard1(), TextArea::getWildcard2(), TypedText::hasValidId(), and TextArea::typedText.
Referenced by DigitalClock::getTextWidth(), TextArea::resizeToCurrentText(), and TextArea::resizeToCurrentTextWithAlignment().
getTypedText()
const TypedText & getTypedText () const inline
Gets the TypedText of the text area.
Returns
The currently used TypedText.
    {
        return typedText;
    }
References TextArea::typedText.
Referenced by TextProgress::getTypedText(), DigitalClock::setBaselineY(), and TextArea::setBaselineY().
getWideTextAction()
WideTextAction getWideTextAction () const inline
Gets wide text action previously set using setWideTextAction.
Returns
current WideTextAction setting.
See also
setWideTextAction, WideTextAction
    {
        return wideTextAction;
    }
References TextArea::wideTextAction.
getWildcard1()
virtual const Unicode::UnicodeChar * getWildcard1 () const inline virtual
Gets the first wildcard used in the TypedText.
Returns
A pointer to the first wildcard, if this text area has a wildcard, otherwise 0.
See also
TextAreaWithOneWildcard, TextAreaWithTwoWildcards
Reimplemented in TextAreaWithOneWildcard, and TextAreaWithTwoWildcards.
    {
        return 0;
    }
Referenced by TextArea::calculateBoundingArea(), TextArea::draw(), TextAreaWithWildcardBase::draw(), TextArea::getTextHeight(), and TextArea::getTextWidth().
getWildcard2()
virtual const Unicode::UnicodeChar * getWildcard2 () const inline virtual
Gets the second wildcard used in the TypedText.
Returns
A pointer to the second wildcard, if this text area has two wildcards, otherwise 0.
See also
TextAreaWithOneWildcard, TextAreaWithTwoWildcards
Reimplemented in TextAreaWithTwoWildcards.
    {
        return 0;
    }
Referenced by TextArea::calculateBoundingArea(), TextArea::draw(), TextAreaWithWildcardBase::draw(), TextArea::getTextHeight(), and TextArea::getTextWidth().
invalidateContent()
void invalidateContent () const virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from Drawable.
Reimplemented in TextAreaWithWildcardBase.
{
    if (alpha == 0 || !typedText.hasValidId() || rect.isEmpty())
    {
        return;
    }
    if (boundingArea.isValid(typedText.getText()))
    {
        Rect boundingRect = boundingArea.getRect();
        invalidateRect(boundingRect);
        return;
    }
    invalidate();
}
References TextArea::boundingArea, TextArea::BoundingArea::getRect(), TypedText::getText(), TypedText::hasValidId(), Drawable::invalidate(), Drawable::invalidateRect(), Rect::isEmpty(), TextArea::BoundingArea::isValid(), Drawable::rect, and TextArea::typedText.
resizeHeightToCurrentText()
void resizeHeightToCurrentText ()
Sets the height of the TextArea to match the height of the current associated text for the current selected language. This is especially useful for texts with WordWrap enabled.
See also
resizeToCurrentText, setWideTextAction, setRotation, resizeHeightToCurrentTextWithRotation
Note
If the current text rotation is either 90 or 270 degrees, the width of the text area will be set and not the height, as the text is rotated.
If the current text is rotated, the x/y coordinate is not updated, which means that the text will be repositioned on the display.
{
    if (typedText.hasValidId())
    {
        const uint16_t h = getTextHeight();
        if (rotation == TEXT_ROTATE_0 || rotation == TEXT_ROTATE_180)
        {
            setHeight(h);
        }
        else
        {
            setWidth(h);
        }
    }
}
References TextArea::getTextHeight(), TypedText::hasValidId(), TextArea::rotation, TextArea::setHeight(), TextArea::setWidth(), touchgfx::TEXT_ROTATE_0, touchgfx::TEXT_ROTATE_180, and TextArea::typedText.
resizeHeightToCurrentTextWithRotation()
void resizeHeightToCurrentTextWithRotation ()
Sets the height of the TextArea to match the height of the current associated text for the current selected language. This is especially useful for texts with WordWrap enabled.
See also
resizeToCurrentText, setWideTextAction, setRotation, resizeHeightToCurrentText
Note
If the current text rotation is either 90 or 270 degrees, the width of the text area will be set and not the height, as the text is rotated. Also, the x or y coordinates will be updated.
{
    if (typedText.hasValidId())
    {
        const uint16_t h = getTextHeight();
        switch (rotation)
        {
        case TEXT_ROTATE_0:
            setHeight(h);
            break;
        case TEXT_ROTATE_90:
            setX(rect.right() - h);
            setWidth(h);
            break;
        case TEXT_ROTATE_180:
            setY(rect.bottom() - h);
            setHeight(h);
            break;
        case TEXT_ROTATE_270:
            setWidth(h);
            break;
        }
    }
}
References Rect::bottom(), TextArea::getTextHeight(), TypedText::hasValidId(), Drawable::rect, Rect::right(), TextArea::rotation, TextArea::setHeight(), TextArea::setWidth(), Drawable::setX(), Drawable::setY(), touchgfx::TEXT_ROTATE_0, touchgfx::TEXT_ROTATE_180, touchgfx::TEXT_ROTATE_270, touchgfx::TEXT_ROTATE_90, and TextArea::typedText.
resizeToCurrentText()
void resizeToCurrentText ()
Sets the dimensions of the TextArea to match the width and height of the current associated text for the current selected language.
If WordWrap is turned on for the TextArea, the height might be set to an unexpected value, as only manually insert line breaks in the text will be respected - use resizeHeightToCurrentText() to keep the width of the TextArea and therefore retain word wrapping.
If the text is centered or right aligned, calling resizeToCurrentText() will actually move the text on the screen, as the x and y coordinates of the TextArea widget is not changed. To simply minimize the size of the TextArea but keep the TypedText in the same position on the screen, use resizeToCurrentTextWithAlignment(). This is also the case if the text is rotated, e.g. 180 degrees.
See also
setRotation, resizeHeightToCurrentText
Note
If the current text rotation is either 90 or 270 degrees, the width of the text area will be set to the height of the text and vice versa, as the text is rotated.
{
    if (typedText.hasValidId())
    {
        const uint16_t w = getTextWidth();
        const uint16_t h = getTextHeight();
        if (rotation == TEXT_ROTATE_0 || rotation == TEXT_ROTATE_180)
        {
            setWidthHeight(w, h);
        }
        else
        {
            setWidthHeight(h, w);
        }
    }
}
References TextArea::getTextHeight(), TextArea::getTextWidth(), TypedText::hasValidId(), TextArea::rotation, Drawable::setWidthHeight(), touchgfx::TEXT_ROTATE_0, touchgfx::TEXT_ROTATE_180, and TextArea::typedText.
Referenced by TextArea::setTypedText().
resizeToCurrentTextWithAlignment()
void resizeToCurrentTextWithAlignment ()
Sets the dimensions of the TextArea to match the width and height of the current associated text for the current selected language, and for centered and right aligned text, the position of the TextArea widget is also updated to keep the text in the same position on the display. Text that is rotated is also handled properly.
See also
setRotation, resizeHeightToCurrentText
Note
If the current text rotation is either 90 or 270 degrees, the width of the text area will be set to the height of the text and vice versa, as the text is rotated.
{
    if (typedText.hasValidId())
    {
        const Alignment alignment = getAlignment();
        const uint16_t text_width = getTextWidth();
        const uint16_t text_height = getTextHeight();
        if (rotation == TEXT_ROTATE_0 || rotation == TEXT_ROTATE_180)
        {
            // (rotate-0 && left-align) or (rotate-180 && right-align) places text to the left
            if (!((rotation == TEXT_ROTATE_0 && alignment == LEFT) || (rotation == TEXT_ROTATE_180 && alignment == RIGHT)))
            {
                const uint16_t old_width = getWidth();
                const uint16_t old_x = getX();
                if (alignment == CENTER)
                {
                    setX(old_x + (old_width - text_width) / 2);
                }
                else
                {
                    setX(old_x + (old_width - text_width));
                }
            }
            if (rotation == TEXT_ROTATE_180)
            {
                const uint16_t old_height = getHeight();
                const uint16_t old_y = getY();
                setY(old_y + (old_height - text_height));
            }
            setWidthHeight(text_width, text_height);
        }
        else
        {
            // 90+left or 270+right places text at the same y coordinate
            if (!((rotation == TEXT_ROTATE_90 && alignment == LEFT) || (rotation == TEXT_ROTATE_270 && alignment == RIGHT)))
            {
                const uint16_t old_height = getHeight();
                const uint16_t old_y = getY();
                if (alignment == CENTER)
                {
                    setY(old_y + (old_height - text_width) / 2);
                }
                else
                {
                    setY(old_y + (old_height - text_width));
                }
            }
            if (rotation == TEXT_ROTATE_90)
            {
                const uint16_t old_width = getWidth();
                const uint16_t old_x = getX();
                setX(old_x + (old_width - text_height));
            }
            setWidthHeight(text_height, text_width);
        }
    }
}
References touchgfx::CENTER, TextArea::getAlignment(), Drawable::getHeight(), TextArea::getTextHeight(), TextArea::getTextWidth(), Drawable::getWidth(), Drawable::getX(), Drawable::getY(), TypedText::hasValidId(), touchgfx::LEFT, touchgfx::RIGHT, TextArea::rotation, Drawable::setWidthHeight(), Drawable::setX(), Drawable::setY(), touchgfx::TEXT_ROTATE_0, touchgfx::TEXT_ROTATE_180, touchgfx::TEXT_ROTATE_270, touchgfx::TEXT_ROTATE_90, and TextArea::typedText.
setAlpha()
virtual void setAlpha (uint8_t newAlpha) inline virtual
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
    {
        alpha = newAlpha;
    }
Referenced by TextButtonStyle< T >::handleAlphaUpdated(), TwoWildcardTextButtonStyle< T >::handleAlphaUpdated(), WildcardTextButtonStyle< T >::handleAlphaUpdated(), DigitalClock::setAlpha(), and TextProgress::setAlpha().
setBaselineY()
virtual void setBaselineY (int16_t baselineY) inline virtual
Adjusts the TextArea y coordinate so the text will have its baseline at the specified value. The placements is relative to the specified TypedText so if the TypedText is changed, you have to set the baseline again.
Parameters
baselineY The y coordinate of the baseline of the text.
Note
setTypedText() must be called prior to setting the baseline.
    {
        setY(baselineY - getTypedText().getFont()->getBaseline());
    }
References TextArea::getTypedText(), and Drawable::setY().
Referenced by TextArea::setXBaselineY().
setColor()
FORCE_INLINE_FUNCTION void setColor (colortype newColor) inline
Sets the color of the text. If no color is set, the default color (black) is used.
Parameters
newColor The color to use.
    {
        color = newColor;
    }
Referenced by Keyboard::Keyboard(), TextButtonStyle< T >::handlePressedUpdated(), TwoWildcardTextButtonStyle< T >::handlePressedUpdated(), WildcardTextButtonStyle< T >::handlePressedUpdated(), DigitalClock::setColor(), TextProgress::setColor(), and Keyboard::setLayout().
setHeight()
virtual void setHeight (int16_t height) inline virtual
Sets the height of this drawable.
Parameters
height The new height.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Reimplemented from Drawable.
    {
        Widget::setHeight(height);
        boundingArea = calculateBoundingArea();
    }
References TextArea::boundingArea, TextArea::calculateBoundingArea(), and Drawable::setHeight().
Referenced by TextArea::resizeHeightToCurrentText(), TextArea::resizeHeightToCurrentTextWithRotation(), and DigitalClock::setHeight().
setIndentation()
FORCE_INLINE_FUNCTION void setIndentation (uint8_t indent) inline
Sets the indentation for the text. This can be very useful when a font is an italic font where letters such as "j" and "g" extend a lot to the left under the previous character(s). if a line starts with a "j" or "g" this letter would either have to be pushed to the right to be able to see all of it, e.g. using spaces (which would ruin a multi line text which is left aligned) - or by clipping the first letter (which could ruin the nice graphics). The solution is to change
textarea.setPosition(50, 50, 100, 100);
to
textarea.setPosition(45, 50, 110, 100);
textarea.setIndentation(5);
Characters that do not extend to the left under the previous characters will be drawn in the same position in either case, but "j" and "g" will be aligned with other lines.
The function Font::getMaxPixelsLeft() will give you the maximum number of pixels any glyph in the font extends to the left.
Parameters
indent The indentation from left (when left aligned text) and right (when right aligned text).
See also
Font::getMaxPixelsLeft
    {
        indentation = indent;
        boundingArea = calculateBoundingArea();
    }
References TextArea::boundingArea, TextArea::calculateBoundingArea(), and TextArea::indentation.
Referenced by Keyboard::setTextIndentation().
setLinespacing()
FORCE_INLINE_FUNCTION void setLinespacing (int16_t space) inline
Sets the line spacing of the TextArea. Setting a larger value will increase the space between lines. It is possible to set a negative value to have lines (partially) overlap. Default line spacing, if not set, is 0.
Parameters
space The line spacing of use in the TextArea.
See also
getLinespacing
    {
        linespace = space;
        boundingArea = calculateBoundingArea();
    }
References TextArea::boundingArea, TextArea::calculateBoundingArea(), and TextArea::linespace.
setRotation()
FORCE_INLINE_FUNCTION void setRotation (const TextRotation textRotation) inline
Sets rotation of the text in the TextArea. The value TEXT_ROTATE_0 is the default for normal text. The value TEXT_ROTATE_90 will rotate the text clockwise, thus writing from the top of the display and down. Similarly TEXT_ROTATE_180 and TEXT_ROTATE_270 will each rotate the text further 90 degrees clockwise.
Parameters
textRotation The rotation of the text.
    {
        rotation = textRotation;
        boundingArea = calculateBoundingArea();
    }
References TextArea::boundingArea, TextArea::calculateBoundingArea(), and TextArea::rotation.
Referenced by TextButtonStyle< T >::setTextRotation(), TwoWildcardTextButtonStyle< T >::setTwoWildcardTextRotation(), and WildcardTextButtonStyle< T >::setWildcardTextRotation().
setTypedText()
void setTypedText (const TypedText & t)
Sets the TypedText of the text area. If no prior size has been set, the TextArea will be resized to fit the new TypedText.
Parameters
t The TypedText for this widget to display.
See also
resizeToCurrentText
{
    typedText = t;
    // If this TextArea does not yet have a width and height,
    // just assign the smallest possible size to fit current text.
    if (getWidth() == 0 && getHeight() == 0)
    {
        resizeToCurrentText();
    }
    boundingArea = calculateBoundingArea();
}
References TextArea::boundingArea, TextArea::calculateBoundingArea(), Drawable::getHeight(), Drawable::getWidth(), TextArea::resizeToCurrentText(), and TextArea::typedText.
Referenced by Keyboard::setLayout(), TextButtonStyle< T >::setText(), TwoWildcardTextButtonStyle< T >::setTwoWildcardText(), TextProgress::setTypedText(), DigitalClock::setTypedText(), and WildcardTextButtonStyle< T >::setWildcardText().
setWideTextAction()
FORCE_INLINE_FUNCTION void setWideTextAction (WideTextAction action) inline
Defines what to do if a line of text is wider than the text area. Default action is WIDE_TEXT_NONE which means that text lines are only broken if there is a manually inserted newline in the text.
If wrapping is enabled and the text would occupy more lines than the size of the TextArea, the end of the last line will get an ellipsis (often …) to signal that some text is missing. The character used for ellipsis is taken from the text spreadsheet.
Parameters
action The action to perform for wide lines of text.
See also
WideTextAction, getWideTextAction, resizeHeightToCurrentText
    {
        wideTextAction = action;
        boundingArea = calculateBoundingArea();
    }
References TextArea::boundingArea, TextArea::calculateBoundingArea(), and TextArea::wideTextAction.
setWidth()
virtual void setWidth (int16_t width) inline virtual
Sets the width of this drawable.
Parameters
width The new width.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Reimplemented from Drawable.
    {
        Widget::setWidth(width);
        boundingArea = calculateBoundingArea();
    }
References TextArea::boundingArea, TextArea::calculateBoundingArea(), and Drawable::setWidth().
Referenced by TextArea::resizeHeightToCurrentText(), TextArea::resizeHeightToCurrentTextWithRotation(), and DigitalClock::setWidth().
setXBaselineY()
virtual void setXBaselineY (int16_t x, int16_t baselineY) inline virtual
Adjusts the TextArea x and y coordinates so the text will have its baseline at the specified y value. The placements is relative to the specified TypedText so if the TypedText is changed you have to set the baseline again. The specified x coordinate will be used as the x coordinate of the TextArea.
Parameters
x The x coordinate of the TextArea.
baselineY The y coordinate of the baseline of the text.
Note
setTypedText() must be called prior to setting the baseline.
    {
        setX(x);
        setBaselineY(baselineY);
    }
References TextArea::setBaselineY(), and Drawable::setX().
Member Data Documentation
alpha
uint8_t alpha protected
The alpha to use.
Referenced by TextArea::getAlpha().
boundingArea
BoundingArea boundingArea protected
Bounding area of this text area.
Referenced by TextArea::draw(), TextArea::invalidateContent(), TextArea::setHeight(), TextArea::setIndentation(), TextArea::setLinespacing(), TextArea::setRotation(), TextArea::setTypedText(), TextArea::setWideTextAction(), and TextArea::setWidth().
color
colortype color protected
The color to use for the text.
Referenced by TextArea::getColor().
indentation
uint8_t indentation protected
The indentation of the text inside the text area.
Referenced by TextArea::calculateBoundingArea(), TextArea::calculateTextHeight(), TextArea::draw(), TextAreaWithWildcardBase::draw(), TextArea::getIndentation(), and TextArea::setIndentation().
linespace
int16_t linespace protected
The extra space between lines of text, measured in pixels.
Referenced by TextArea::calculateBoundingArea(), TextArea::calculateTextHeight(), TextArea::draw(), TextAreaWithWildcardBase::draw(), TextArea::getLinespacing(), and TextArea::setLinespacing().
newLine
const uint16_t newLine = 10 static protected
NewLine value.
rotation
TextRotation rotation protected
The text rotation to use in steps of 90 degrees.
Referenced by TextArea::calculateBoundingArea(), TextArea::draw(), TextAreaWithWildcardBase::draw(), TextArea::getRotation(), TextArea::resizeHeightToCurrentText(), TextArea::resizeHeightToCurrentTextWithRotation(), TextArea::resizeToCurrentText(), TextArea::resizeToCurrentTextWithAlignment(), and TextArea::setRotation().
typedText
TypedText typedText protected
The TypedText to display.
Referenced by TextArea::calculateBoundingArea(), TextArea::calculateTextHeight(), TextArea::draw(), TextAreaWithWildcardBase::draw(), TextArea::getAlignment(), TextArea::getTextHeight(), TextArea::getTextWidth(), TextArea::getTypedText(), TextArea::invalidateContent(), TextArea::resizeHeightToCurrentText(), TextArea::resizeHeightToCurrentTextWithRotation(), TextArea::resizeToCurrentText(), TextArea::resizeToCurrentTextWithAlignment(), and TextArea::setTypedText().
wideTextAction
WideTextAction wideTextAction protected
What to do if the lines of text are wider than the text area.
Referenced by TextArea::calculateBoundingArea(), TextArea::calculateTextHeight(), TextArea::draw(), TextAreaWithWildcardBase::draw(), TextArea::getWideTextAction(), and TextArea::setWideTextAction().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/TextArea.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/TextArea.cpp