Battery Simulator Documentation: WildcardTextButtonStyle< T >
WildcardTextButtonStyle< T >
#include "WildcardTextButtonStyle.hpp"
Public Member Functions
WildcardTextButtonStyle ()
void setWildcardText (TypedText t)
void setWildcardTextBuffer (const Unicode::UnicodeChar *buffer)
void setWildcardTextColors (colortype newColorReleased, colortype newColorPressed)
void setWildcardTextPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setWildcardTextRotation (TextRotation rotation)
void setWildcardTextX (int16_t x)
void setWildcardTextXY (int16_t x, int16_t y)
void setWildcardTextY (int16_t y)
Protected Member Functions
virtual void handleAlphaUpdated ()
virtual void handlePressedUpdated ()
Protected Attributes
colortype colorPressed
The color pressed.
colortype colorReleased
The color released.
TextAreaWithOneWildcard wildcardText
The wildcard text.
Detailed Description
template<class T>
class touchgfx::WildcardTextButtonStyle< T >
A wildcard text button style.
An wildcard text button style. This class is supposed to be used with one of the ButtonTrigger classes to create a functional button. This class will show a text with a wildcard in one of two colors depending on the state of the button (pressed or released).
The WildcardTextButtonStyle does not set the size of the enclosing container (normally AbstractButtonContainer). The size must be set manually.
To get a background behind the text, use WildcardTextButtonStyle together with e.g. ImageButtonStyle:
WildcardTextButtonStyle<ImageButtonStyle<ClickButtonTrigger> > myButton;
The position of the text can be adjusted with setTextXY (default is centered).
Template Parameters
T Generic type parameter. Typically a AbstractButtonContainer subclass.
See also
AbstractButtonContainer
Constructor & Destructor Documentation
WildcardTextButtonStyle()
template<class T > WildcardTextButtonStyle () inline
        : T()
    {
        T::add(wildcardText);
    }
References WildcardTextButtonStyle< T >::wildcardText.
Member Function Documentation
handleAlphaUpdated()
template<class T > virtual void handleAlphaUpdated () inline protected virtual
Handles what should happen when the alpha is updated.
    {
        wildcardText.setAlpha(T::getAlpha());
        T::handleAlphaUpdated();
    }
References TextArea::setAlpha(), and WildcardTextButtonStyle< T >::wildcardText.
handlePressedUpdated()
template<class T > virtual void handlePressedUpdated () inline protected virtual
Handles what should happen when the pressed state is updated.
    {
        wildcardText.setColor(T::getPressed() ? colorPressed : colorReleased);
        T::handlePressedUpdated();
    }
References WildcardTextButtonStyle< T >::colorPressed, WildcardTextButtonStyle< T >::colorReleased, TextArea::setColor(), and WildcardTextButtonStyle< T >::wildcardText.
Referenced by WildcardTextButtonStyle< T >::setWildcardTextColors().
setWildcardText()
template<class T > void setWildcardText (TypedText t) inline
Sets wildcard text.
Parameters
t A TypedText to process.
    {
        wildcardText.setTypedText(t);
        wildcardText.setWidthHeight(T::getWidth(), T::getHeight());
    }
References TextArea::setTypedText(), Drawable::setWidthHeight(), and WildcardTextButtonStyle< T >::wildcardText.
setWildcardTextBuffer()
template<class T > void setWildcardTextBuffer (const Unicode::UnicodeChar * buffer) inline
Sets wildcard text buffer.
Parameters
buffer If non-null, the buffer.
    {
        wildcardText.setWildcard(buffer);
    }
References TextAreaWithOneWildcard::setWildcard(), and WildcardTextButtonStyle< T >::wildcardText.
setWildcardTextColors()
template<class T > void setWildcardTextColors (colortype newColorReleased, colortype newColorPressed) inline
Sets wild card text colors.
Parameters
newColorReleased The new color released.
newColorPressed The new color pressed.
    {
        colorReleased = newColorReleased;
        colorPressed = newColorPressed;
        handlePressedUpdated();
    }
References WildcardTextButtonStyle< T >::colorPressed, WildcardTextButtonStyle< T >::colorReleased, and WildcardTextButtonStyle< T >::handlePressedUpdated().
setWildcardTextPosition()
template<class T > void setWildcardTextPosition (int16_t x, int16_t y, int16_t width, int16_t height) inline
Sets text position and dimensions.
Parameters
x The x coordinate.
y The y coordinate.
width The width of the text.
height The height of the text.
    {
        wildcardText.setPosition(x, y, width, height);
    }
References Drawable::setPosition(), and WildcardTextButtonStyle< T >::wildcardText.
setWildcardTextRotation()
template<class T > void setWildcardTextRotation (TextRotation rotation) inline
Sets wildcard text rotation.
Parameters
rotation The rotation.
    {
        wildcardText.setRotation(rotation);
    }
References TextArea::setRotation(), and WildcardTextButtonStyle< T >::wildcardText.
setWildcardTextX()
template<class T > void setWildcardTextX (int16_t x) inline
Sets wildcard text x coordinate.
Parameters
x The x coordinate.
    {
        wildcardText.setX(x);
    }
References Drawable::setX(), and WildcardTextButtonStyle< T >::wildcardText.
Referenced by WildcardTextButtonStyle< T >::setWildcardTextXY().
setWildcardTextXY()
template<class T > void setWildcardTextXY (int16_t x, int16_t y) inline
Sets wildcard text position.
Parameters
x The x coordinate.
y The y coordinate.
    {
        setWildcardTextX(x);
        setWildcardTextY(y);
    }
References WildcardTextButtonStyle< T >::setWildcardTextX(), and WildcardTextButtonStyle< T >::setWildcardTextY().
setWildcardTextY()
template<class T > void setWildcardTextY (int16_t y) inline
Sets wildcard text y coordinate.
Parameters
y The y coordinate.
    {
        wildcardText.setY(y);
    }
References Drawable::setY(), and WildcardTextButtonStyle< T >::wildcardText.
Referenced by WildcardTextButtonStyle< T >::setWildcardTextXY().
Member Data Documentation
colorPressed
template<class T > colortype colorPressed protected
The color pressed.
Referenced by WildcardTextButtonStyle< T >::handlePressedUpdated(), and WildcardTextButtonStyle< T >::setWildcardTextColors().
colorReleased
template<class T > colortype colorReleased protected
The color released.
Referenced by WildcardTextButtonStyle< T >::handlePressedUpdated(), and WildcardTextButtonStyle< T >::setWildcardTextColors().
wildcardText
template<class T > TextAreaWithOneWildcard wildcardText protected
The wildcard text.
Referenced by WildcardTextButtonStyle< T >::WildcardTextButtonStyle(), WildcardTextButtonStyle< T >::handleAlphaUpdated(), WildcardTextButtonStyle< T >::handlePressedUpdated(), WildcardTextButtonStyle< T >::setWildcardText(), WildcardTextButtonStyle< T >::setWildcardTextBuffer(), WildcardTextButtonStyle< T >::setWildcardTextPosition(), WildcardTextButtonStyle< T >::setWildcardTextRotation(), WildcardTextButtonStyle< T >::setWildcardTextX(), and WildcardTextButtonStyle< T >::setWildcardTextY().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/buttons/WildcardTextButtonStyle.hpp