Battery Simulator Documentation: FontManager
FontManager
#include "FontManager.hpp"
Static Public Member Functions
static Font * getFont (FontId fontId)
static void setFontProvider (FontProvider *fontProvider)
Static Private Attributes
static FontProvider * provider
Detailed Description
This class is the entry point for looking up a font based on a font id. Must be initialized with the appropriate FontProvider by the application.
Member Function Documentation
getFont()
static Font * getFont (FontId fontId) static
Gets a font.
Parameters
fontId The FontId of the font to get.
Returns
The font with a FontId of fontId.
Referenced by Keyboard::draw().
setFontProvider()
static void setFontProvider (FontProvider * fontProvider) static
Sets the font provider. Must be initialized with the appropriate FontProvider by the application.
Parameters
[in] fontProvider Sets the font provider. Must be initialized with the appropriate FontProvider by the application.
Referenced by touchgfx::touchgfx_generic_init(), and touchgfx::touchgfx_init().
Member Data Documentation
provider
FontProvider* provider static private
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/FontManager.hpp