Battery Simulator Documentation: VideoDataReader
VideoDataReader abstract
#include "VideoController.hpp"
Public Member Functions
virtual ~VideoDataReader ()
virtual uint32_t getDataLength ()=0
virtual bool readData (void *dst, uint32_t bytes)=0
virtual void seek (uint32_t position)=0
Detailed Description
Interface for classes reading video data from non-memory-mapped flash storage.
Constructor & Destructor Documentation
~VideoDataReader()
virtual ~VideoDataReader () inline virtual
Virtual destructor.
    {
    }
Member Function Documentation
getDataLength()
virtual uint32_t getDataLength () pure virtual
Get the length of the data (file).
Returns
The length of the data.
Referenced by SoftwareMJPEGDecoder::setVideoData(), and HardwareMJPEGDecoder::setVideoData().
readData()
virtual bool readData (void * dst, uint32_t bytes) pure virtual
Read data from flash to a buffer. This must be a synchrony method that does not return until the copy is done.
Parameters
[in,out] dst Address of destination buffer in RAM.
bytes Number of bytes to copy.
Returns
Returns true if read was successful.
Referenced by SoftwareMJPEGDecoder::readData(), and HardwareMJPEGDecoder::readData().
seek()
virtual void seek (uint32_t position) pure virtual
Seek to a specific position in the data (file).
Parameters
position Byte position in the data that is needed next.
Referenced by SoftwareMJPEGDecoder::readData(), and HardwareMJPEGDecoder::readData().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/hal/VideoController.hpp