Battery Simulator Documentation: CWRVectorRenderer
CWRVectorRenderer abstract
#include "CWRVectorRenderer.hpp"
Classes
class CanvasWidgetProxy
class StrokeCanvas
Public Member Functions
virtual void drawPath (const uint8_t *cmds, uint32_t nCmds, const float *points, uint32_t nPoints, const float *bbox=0)
virtual void setAlpha (uint8_t a)
virtual void setColor (colortype c)
virtual void setLinearGradient (float x0, float y0, float x1, float y1, uint32_t stops, const float *stopPositions, const uint32_t *stopColors, float width, float height, bool solid, const uint32_t *palette)
virtual void setMode (DrawMode mode)
virtual void setStrokeLineCap (VGStrokeLineCap lineCap)
virtual void setStrokeLineJoin (VGStrokeLineJoin lineJoin)
virtual void setStrokeMiterLimit (float miterLimit)
virtual void setStrokeWidth (float w)
virtual void setTransformationMatrix (const Matrix3x3 &m)
virtual void setup (const Rect &canvasAreaAbs, const Rect &invalidatedAreaRel)
virtual void tearDown ()
Public Member Functions inherited from VectorRenderer
virtual ~VectorRenderer ()
Private Member Functions
bool drawFill (const uint8_t *cmds, uint32_t nCmds, const float *points, uint32_t nPoints, const Rect &area) const
bool drawPathArea (const uint8_t *cmds, uint32_t nCmds, const float *points, uint32_t nPoints, const Rect &area) const
bool drawStroke (const uint8_t *cmds, uint32_t nCmds, const float *points, uint32_t nPoints, const Rect &area) const
void drawStrokeBackwards (uint32_t cmdInxPathStart, uint32_t cmdInx, uint32_t pointInx, const uint8_t *cmds, const float *points, bool drawLineCaps, StrokeCanvas &canvas) const
virtual AbstractPainter & getColorPainter ()=0
virtual AbstractPainterColor & getColorPainterColor ()=0
virtual AbstractPainterLinearGradient & getLinearPainter ()=0
void getPreviousDestination (float &positionX, float &positionY, uint32_t cmdInx, uint32_t pointInx, const uint8_t *cmds, const float *points) const
Private Attributes
uint8_t alpha
uint8_t canvasAlpha
Rect canvasAreaAbsolute
const AbstractPainter * canvasPainter
uint8_t colorAlpha
Rect dirtyAreaAbsolute
Rect drawArea
DrawMode drawMode
Matrix3x3 matrix
touchgfx::CWRVectorRenderer::CanvasWidgetProxy proxyWidget
VGStrokeLineCap strokeLineCap
VGStrokeLineJoin strokeLineJoin
float strokeMiterLimit
float strokeWidth
Additional Inherited Members
Public Types inherited from VectorRenderer
enum DrawMode { STROKE , FILL_EVEN_ODD , FILL_NON_ZERO }
Static Public Member Functions inherited from VectorRenderer
static VectorRenderer * getInstance ()
Detailed Description
Implementation of the VectorRendererInterface based on the CanvasWidgetRenderer. The class needs to be subclasses to provide the painter objecs.
See also
CWRVectorRendererRGB888, CWRVectorRendererRGB565
Member Function Documentation
drawFill()
bool drawFill (const uint8_t * cmds, uint32_t nCmds, const float * points, uint32_t nPoints, const Rect & area) const private
{
    (void)nPoints;
    uint32_t cmdInx = 0;
    uint32_t pointInx = 0;
    Canvas canvas(canvasPainter, canvasAreaAbsolute, area, 255U);
    canvas.setFillingRule((drawMode == FILL_EVEN_ODD) ? Rasterizer::FILL_EVEN_ODD : Rasterizer::FILL_NON_ZERO);
    float positionX = 0.0f;
    float positionY = 0.0f;
    Matrix3x3::Point transformedPosition = matrix.affineTransform(positionX, positionY);
    while (cmdInx < nCmds)
    {
        switch (static_cast<VectorPrimitives>(cmds[cmdInx]))
        {
        case VECTOR_PRIM_CLOSE:
            assert(pointInx <= nPoints);
            canvas.close();
            break;
        case VECTOR_PRIM_MOVE:
            assert(pointInx + 2 <= nPoints);
            positionX = points[pointInx];
            positionY = points[pointInx + 1];
            transformedPosition = matrix.affineTransform(positionX, positionY);
            canvas.moveTo(transformedPosition.x, transformedPosition.y);
            pointInx += 2;
            break;
        case VECTOR_PRIM_LINE:
            assert(pointInx + 1 <= nPoints);
            positionX = points[pointInx];
            positionY = points[pointInx + 1];
            transformedPosition = matrix.affineTransform(positionX, positionY);
            canvas.lineTo(transformedPosition.x, transformedPosition.y);
            pointInx += 2;
            break;
        case VECTOR_PRIM_HLINE:
            assert(pointInx + 1 <= nPoints);
            positionX = points[pointInx];
            transformedPosition = matrix.affineTransform(positionX, positionY);
            canvas.lineTo(transformedPosition.x, transformedPosition.y);
            pointInx += 1;
            break;
        case VECTOR_PRIM_VLINE:
            assert(pointInx + 1 <= nPoints);
            positionY = points[pointInx];
            transformedPosition = matrix.affineTransform(positionX, positionY);
            canvas.lineTo(transformedPosition.x, transformedPosition.y);
            pointInx += 1;
            break;
        case VECTOR_PRIM_BEZIER_QUAD:
            assert(pointInx + 4 <= nPoints);
            positionX = points[pointInx + 2];
            positionY = points[pointInx + 3];
            {
                const Matrix3x3::Point p1 = matrix.affineTransform(points[pointInx], points[pointInx + 1]);
                const Matrix3x3::Point p2 = matrix.affineTransform(positionX, positionY);
                canvas.quadraticBezierTo(transformedPosition.x, transformedPosition.y, p1.x, p1.y, p2.x, p2.y);
                transformedPosition = p2;
            }
            pointInx += 4;
            break;
        case VECTOR_PRIM_BEZIER_CUBIC:
            assert(pointInx + 6 <= nPoints);
            positionX = points[pointInx + 4];
            positionY = points[pointInx + 5];
            {
                const Matrix3x3::Point p1 = matrix.affineTransform(points[pointInx], points[pointInx + 1]);
                const Matrix3x3::Point p2 = matrix.affineTransform(points[pointInx + 2], points[pointInx + 3]);
                const Matrix3x3::Point p3 = matrix.affineTransform(positionX, positionY);
                canvas.cubicBezierTo(transformedPosition.x, transformedPosition.y, p1.x, p1.y, p2.x, p2.y, p3.x, p3.y);
                transformedPosition = p3;
            }
            pointInx += 6;
            break;
        }
        cmdInx++;
    }
    return canvas.render(LCD::div255(colorAlpha * alpha));
}
References CWRVectorRenderer::canvasAreaAbsolute, CWRVectorRenderer::canvasPainter, CWRVectorRenderer::colorAlpha, LCD::div255(), CWRVectorRenderer::drawMode, VectorRenderer::FILL_EVEN_ODD, touchgfx::VECTOR_PRIM_BEZIER_CUBIC, touchgfx::VECTOR_PRIM_BEZIER_QUAD, touchgfx::VECTOR_PRIM_CLOSE, touchgfx::VECTOR_PRIM_HLINE, touchgfx::VECTOR_PRIM_LINE, touchgfx::VECTOR_PRIM_MOVE, touchgfx::VECTOR_PRIM_VLINE, and void().
Referenced by CWRVectorRenderer::drawPathArea().
drawPath()
void drawPath (const uint8_t * cmds, uint32_t nCmds, const float * points, uint32_t nPoints, const float * bbox = 0) virtual
Draw a Path defined by the given array of primitives (commands) and an array of the corresponding floating point coordinates.
Parameters
cmds An uint8_t array of VectorPrimitives values
nCmds The number of commands in cmds
points An array of coordinates for the commands
nPoints The number of values in the points arrays
bbox Array describing the bounding box of the path [minx,miny,maxx,maxy] or 0 if unknown
Implements VectorRenderer.
{
    // Draw the path. Try reduced areas until success
    Rect area = drawArea;
    if (area.isEmpty())
    {
        return;
    }
    const int16_t bottom = area.bottom();
    while (area.y < bottom)
    {
        while (!drawPathArea(cmds, nCmds, points, nPoints, area))
        {
            if (area.height == 1)
            {
                // Failed on a single line
                break;
            }
            area.height = (area.height + 1) >> 1; // Cannot become 0 as (2+1)>>1=1
        }
        area.y += area.height;
        if (area.bottom() > bottom)
        {
            area.height = bottom - area.y;
        }
    }
}
References Rect::bottom(), CWRVectorRenderer::drawArea, CWRVectorRenderer::drawPathArea(), Rect::height, Rect::isEmpty(), and Rect::y.
drawPathArea()
bool drawPathArea (const uint8_t * cmds, uint32_t nCmds, const float * points, uint32_t nPoints, const Rect & area) const private
{
    assert(cmds);
    assert(points);
    if (drawMode != STROKE)
    {
        return drawFill(cmds, nCmds, points, nPoints, area);
    }
    return drawStroke(cmds, nCmds, points, nPoints, area);
}
References CWRVectorRenderer::drawFill(), CWRVectorRenderer::drawMode, CWRVectorRenderer::drawStroke(), and VectorRenderer::STROKE.
Referenced by CWRVectorRenderer::drawPath().
drawStroke()
bool drawStroke (const uint8_t * cmds, uint32_t nCmds, const float * points, uint32_t nPoints, const Rect & area) const private
{
    (void)nPoints;
    uint32_t cmdInx = 0;
    uint32_t pointInx = 0;
    if (strokeWidth <= 0.0f)
    {
        return true;
    }
    StrokeCanvas canvas(canvasPainter, canvasAreaAbsolute, area, 255U, matrix);
    canvas.setStroke(strokeWidth, strokeMiterLimit, strokeLineJoin, strokeLineCap, LCD::div255(colorAlpha * alpha));
    float positionX = 0.0f;
    float positionY = 0.0f;
    float initialShapeX = 0.0f;
    float initialShapeY = 0.0f;
    uint32_t cmdInxPathStart = 0;
    while (cmdInx < nCmds)
    {
        assert(static_cast<VectorPrimitives>(cmds[cmdInx]) == VECTOR_PRIM_CLOSE || pointInx < nPoints);
        switch (static_cast<VectorPrimitives>(cmds[cmdInx]))
        {
        case VECTOR_PRIM_CLOSE:
            positionX = initialShapeX;
            positionY = initialShapeY;
            if (cmdInxPathStart < cmdInx) // A single "CLOSE" on it's own does nothing
            {
                // In case we are not back at the beginning, draw a line to that point
                canvas.strokeLineTo(positionX, positionY);
                // Check if it a zero-length closed line and draw a double linecap
                if (!canvas.strokeDrawDoubleLineCap())
                {
                    // The line has some extend - close the outside
                    canvas.strokeClose(positionX, positionY);
                    // Move back to the start
                    canvas.strokeMoveTo(positionX, positionY);
                    // Draw inside backwards without linecaps(false)
                    drawStrokeBackwards(cmdInxPathStart, cmdInx + 1, pointInx, cmds, points, false, canvas);
                    // Close the inside of the stroke
                    canvas.strokeClose(positionX, positionY);
                }
            }
            // Next path starts after the CLOSE command
            cmdInxPathStart = cmdInx + 1;
            break;
        case VECTOR_PRIM_MOVE:
            assert(pointInx + 2 <= nPoints);
            if (cmdInxPathStart < cmdInx) // More than a singe "MOVE"
            {
                // Check if it a zero-length line and draw a double linecap
                if (!canvas.strokeDrawDoubleLineCap())
                {
                    // The line has some extend, follow the commands backwards and draw linecaps(true)
                    drawStrokeBackwards(cmdInxPathStart, cmdInx, pointInx, cmds, points, true, canvas);
                }
            }
            cmdInxPathStart = cmdInx;
            initialShapeX = positionX = points[pointInx];
            initialShapeY = positionY = points[pointInx + 1];
            canvas.strokeMoveTo(positionX, positionY);
            pointInx += 2;
            break;
        case VECTOR_PRIM_LINE:
            assert(pointInx + 2 <= nPoints);
            positionX = points[pointInx];
            positionY = points[pointInx + 1];
            canvas.strokeLineTo(positionX, positionY);
            pointInx += 2;
            break;
        case VECTOR_PRIM_HLINE:
            assert(pointInx + 1 <= nPoints);
            positionX = points[pointInx];
            canvas.strokeLineTo(positionX, positionY);
            pointInx += 1;
            break;
        case VECTOR_PRIM_VLINE:
            assert(pointInx + 1 <= nPoints);
            positionY = points[pointInx];
            canvas.strokeLineTo(positionX, positionY);
            pointInx += 1;
            break;
        case VECTOR_PRIM_BEZIER_QUAD:
            assert(pointInx + 4 <= nPoints);
            canvas.strokeBezierQuad(positionX, positionY, points[pointInx], points[pointInx + 1], points[pointInx + 2], points[pointInx + 3]);
            positionX = points[pointInx + 2];
            positionY = points[pointInx + 3];
            pointInx += 4;
            break;
        case VECTOR_PRIM_BEZIER_CUBIC:
            assert(pointInx + 6 <= nPoints);
            canvas.strokeBezierCubic(positionX, positionY, points[pointInx], points[pointInx + 1], points[pointInx + 2], points[pointInx + 3], points[pointInx + 4], points[pointInx + 5]);
            positionX = points[pointInx + 4];
            positionY = points[pointInx + 5];
            pointInx += 6;
            break;
        }
        cmdInx++;
    }
    if (cmdInxPathStart < cmdInx) // More than a singe "MOVE"
    {
        // Check if it a zero-length line and draw a double linecap
        if (!canvas.strokeDrawDoubleLineCap())
        {
            // The line has some extend, follow the commands backwards and draw linecaps(true)
            drawStrokeBackwards(cmdInxPathStart, cmdInx, pointInx, cmds, points, true, canvas);
        }
    }
    return canvas.strokeRender();
}
References CWRVectorRenderer::canvasAreaAbsolute, CWRVectorRenderer::canvasPainter, CWRVectorRenderer::colorAlpha, LCD::div255(), CWRVectorRenderer::drawStrokeBackwards(), CWRVectorRenderer::strokeLineCap, CWRVectorRenderer::strokeLineJoin, CWRVectorRenderer::strokeMiterLimit, CWRVectorRenderer::strokeWidth, touchgfx::VECTOR_PRIM_BEZIER_CUBIC, touchgfx::VECTOR_PRIM_BEZIER_QUAD, touchgfx::VECTOR_PRIM_CLOSE, touchgfx::VECTOR_PRIM_HLINE, touchgfx::VECTOR_PRIM_LINE, touchgfx::VECTOR_PRIM_MOVE, touchgfx::VECTOR_PRIM_VLINE, and void().
Referenced by CWRVectorRenderer::drawPathArea().
drawStrokeBackwards()
void drawStrokeBackwards (uint32_t cmdInxPathStart, uint32_t cmdInx, uint32_t pointInx, const uint8_t * cmds, const float * points, bool drawLineCaps, StrokeCanvas & canvas) const private
{
    float positionX = 0.0f;
    float positionY = 0.0f;
    canvas.lineCapInsteadOfLineJoin(drawLineCaps);
    while (cmdInx > cmdInxPathStart)
    {
        assert(cmdInx > 0);
        cmdInx--;
        switch (static_cast<VectorPrimitives>(cmds[cmdInx]))
        {
        case VECTOR_PRIM_CLOSE:
            getPreviousDestination(positionX, positionY, cmdInx, pointInx, cmds, points);
            canvas.strokeLineTo(positionX, positionY);
            break;
        case VECTOR_PRIM_MOVE:
            assert(cmdInx == cmdInxPathStart);
            break;
        case VECTOR_PRIM_LINE:
            assert(pointInx >= 2);
            pointInx -= 2;
            getPreviousDestination(positionX, positionY, cmdInx, pointInx, cmds, points);
            canvas.strokeLineTo(positionX, positionY);
            break;
        case VECTOR_PRIM_HLINE:
        case VECTOR_PRIM_VLINE:
            assert(pointInx >= 1);
            pointInx -= 1;
            getPreviousDestination(positionX, positionY, cmdInx, pointInx, cmds, points);
            canvas.strokeLineTo(positionX, positionY);
            break;
        case VECTOR_PRIM_BEZIER_QUAD:
            assert(pointInx >= 4);
            pointInx -= 4;
            getPreviousDestination(positionX, positionY, cmdInx, pointInx, cmds, points);
            canvas.strokeBezierQuad(points[pointInx + 2], points[pointInx + 3], //lint !e662 !e661
                                    points[pointInx], points[pointInx + 1],     //lint !e662 !e661
                                    positionX, positionY);
            break;
        case VECTOR_PRIM_BEZIER_CUBIC:
            assert(pointInx >= 6);
            pointInx -= 6;
            getPreviousDestination(positionX, positionY, cmdInx, pointInx, cmds, points);
            canvas.strokeBezierCubic(points[pointInx + 4], points[pointInx + 5], //lint !e662 !e661
                                     points[pointInx + 2], points[pointInx + 3], //lint !e662 !e661
                                     points[pointInx], points[pointInx + 1],     //lint !e662 !e661
                                     positionX, positionY);
            break;
        }
    }
    if (drawLineCaps)
    {
        canvas.drawFinalLineCap();
    }
}
References CWRVectorRenderer::getPreviousDestination(), touchgfx::VECTOR_PRIM_BEZIER_CUBIC, touchgfx::VECTOR_PRIM_BEZIER_QUAD, touchgfx::VECTOR_PRIM_CLOSE, touchgfx::VECTOR_PRIM_HLINE, touchgfx::VECTOR_PRIM_LINE, touchgfx::VECTOR_PRIM_MOVE, and touchgfx::VECTOR_PRIM_VLINE.
Referenced by CWRVectorRenderer::drawStroke().
getColorPainter()
virtual AbstractPainter & getColorPainter () private pure virtual
Implemented in CWRVectorRendererRGB565, CWRVectorRendererRGB888, and CWRVectorRendererARGB8888.
Referenced by CWRVectorRenderer::setColor().
getColorPainterColor()
virtual AbstractPainterColor & getColorPainterColor () private pure virtual
Implemented in CWRVectorRendererRGB565, CWRVectorRendererRGB888, and CWRVectorRendererARGB8888.
Referenced by CWRVectorRenderer::setColor().
getLinearPainter()
virtual AbstractPainterLinearGradient & getLinearPainter () private pure virtual
Implemented in CWRVectorRendererRGB565, CWRVectorRendererRGB888, and CWRVectorRendererARGB8888.
Referenced by CWRVectorRenderer::setLinearGradient().
getPreviousDestination()
void getPreviousDestination (float & positionX, float & positionY, uint32_t cmdInx, uint32_t pointInx, const uint8_t * cmds, const float * points) const private
{
    bool foundX = false;
    bool foundY = false;
    while (cmdInx > 0)
    {
        cmdInx--;
        switch (static_cast<VectorPrimitives>(cmds[cmdInx]))
        {
        case VECTOR_PRIM_CLOSE:
            break;
        case VECTOR_PRIM_MOVE:
        case VECTOR_PRIM_LINE:
        case VECTOR_PRIM_BEZIER_QUAD:
        case VECTOR_PRIM_BEZIER_CUBIC:
            assert(pointInx >= 2);
            pointInx -= 2;
            if (!foundX)
            {
                positionX = points[pointInx]; //lint !e662 !e661
            }
            if (!foundY)
            {
                positionY = points[pointInx + 1]; //lint !e662 !e661
            }
            return;
        case VECTOR_PRIM_HLINE:
            assert(pointInx >= 1);
            pointInx -= 1;
            if (!foundX)
            {
                positionX = points[pointInx]; //lint !e662 !e661
            }
            if (foundY)
            {
                return;
            }
            foundX = true;
            break;
        case VECTOR_PRIM_VLINE:
            assert(pointInx >= 1);
            pointInx -= 1;
            if (!foundY)
            {
                positionY = points[pointInx]; //lint !e662 !e661
            }
            if (foundX)
            {
                return;
            }
            foundY = true;
            break;
        }
    }
    if (!foundX)
    {
        positionX = 0.0f;
    }
    if (!foundY)
    {
        positionY = 0.0f;
    }
}
References touchgfx::VECTOR_PRIM_BEZIER_CUBIC, touchgfx::VECTOR_PRIM_BEZIER_QUAD, touchgfx::VECTOR_PRIM_CLOSE, touchgfx::VECTOR_PRIM_HLINE, touchgfx::VECTOR_PRIM_LINE, touchgfx::VECTOR_PRIM_MOVE, and touchgfx::VECTOR_PRIM_VLINE.
Referenced by CWRVectorRenderer::drawStrokeBackwards().
setAlpha()
void setAlpha (uint8_t a) virtual
Set the alpha value (opacity) used for future drawings. The alpha is specified in the interval [0;1].
Parameters
a The alpha value.
Implements VectorRenderer.
{
    alpha = a;
}
setColor()
void setColor (colortype c) virtual
Set a constant color used for future drawings.
Parameters
c An ARGB color value
Implements VectorRenderer.
{
    // Save color alpha for rendering
    colorAlpha = c >> 24;
    getColorPainterColor().setColor(c);
    canvasPainter = &getColorPainter();
}
References CWRVectorRenderer::canvasPainter, CWRVectorRenderer::colorAlpha, CWRVectorRenderer::getColorPainter(), and CWRVectorRenderer::getColorPainterColor().
Referenced by CWRVectorRenderer::setLinearGradient().
setLinearGradient()
void setLinearGradient (float x0, float y0, float x1, float y1, uint32_t stops, const float * stopPositions, const uint32_t * stopColors, float width, float height, bool solid, const uint32_t * palette) virtual
Set a linear gradient used for future drawings. The linear gradient is transformed using the current transformation matrix. Multiple colors (stops) can be specified for the gradient. The stop positions are given in the range [0;1].
Parameters
x0 X-coordinate for gradient starting point
y0 Y-coordinate for gradient starting point
x1 X-coordinate for gradient end point
y1 Y-coordinate for gradient end point
stops Number of stops
stopPositions Positions of the stops on the line
stopColors Colors of the stops
width Width of the box to fill
height Height of the box to fill
solid True if all colors in the gradient are solid
palette The gradient palette
Implements VectorRenderer.
{
    // If 'x1' = 'x2' and 'y1' = 'y2', then the area to be painted shall be painted
    // as a single color using the color and opacity of the last gradient stop.
    if ((x0 - x1) == 0.0f && (y0 - y1) == 0.0f)
    {
        setColor(stopColors[stops - 1]);
        return;
    }
    // Make colorAlpha neutral
    colorAlpha = 255;
    AbstractPainterLinearGradient& linearPainter = getLinearPainter();
    linearPainter.setGradientEndPoints(x0, y0, x1, y1, width, height, matrix);
    assert(palette && "A gradient palette is required by CWRVectorRenderer");
    linearPainter.setGradientTexture(palette, isSolid);
    canvasPainter = &linearPainter;
}
References CWRVectorRenderer::canvasPainter, CWRVectorRenderer::colorAlpha, CWRVectorRenderer::getLinearPainter(), CWRVectorRenderer::setColor(), AbstractPainterLinearGradient::setGradientEndPoints(), and AbstractPainterLinearGradient::setGradientTexture().
setMode()
virtual void setMode (DrawMode mode) inline virtual
Set the drawing mode for the VectorRenderer. The mode will be used for all subsequent drawings until setMode is called again.
The default mode is non-zero filling.
Parameters
mode The filling mode.
Implements VectorRenderer.
    {
        drawMode = mode;
    }
References CWRVectorRenderer::drawMode.
setStrokeLineCap()
virtual void setStrokeLineCap (VGStrokeLineCap lineCap) inline virtual
Sets stroke line cap type.
Parameters
lineCap The line cap type.
Implements VectorRenderer.
    {
        strokeLineCap = lineCap;
    }
References CWRVectorRenderer::strokeLineCap.
setStrokeLineJoin()
virtual void setStrokeLineJoin (VGStrokeLineJoin lineJoin) inline virtual
Sets stroke line join type.
Parameters
lineJoin The line join type.
Implements VectorRenderer.
    {
        strokeLineJoin = lineJoin;
    }
References CWRVectorRenderer::strokeLineJoin.
setStrokeMiterLimit()
virtual void setStrokeMiterLimit (float miterLimit) inline virtual
Sets stroke miter limit. This the max distance from the Miter point on the stroke to the stroke point that will be used. If the miter limit is exceeded for a stroke join, it will not be drawn as a Miter but as a Bevel.
Parameters
miterLimit The miter limit.
Implements VectorRenderer.
    {
        strokeMiterLimit = miterLimit;
    }
References CWRVectorRenderer::strokeMiterLimit.
setStrokeWidth()
void setStrokeWidth (float w) virtual
Set the width used for future drawings using the VECTOR_STROKE drawing mode.
Parameters
w The width used for stroke drawing.
Implements VectorRenderer.
{
    strokeWidth = w;
}
References CWRVectorRenderer::strokeWidth.
setTransformationMatrix()
void setTransformationMatrix (const Matrix3x3 & m) virtual
Sets the transformation matrix used for future drawings. The transformation is reset when setup is called.
Parameters
m The transformation matrix
Implements VectorRenderer.
{
    matrix = m;
}
setup()
void setup (const Rect & canvasAreaAbs, const Rect & invalidatedAreaRel) virtual
Start a new drawing (invalidated area) within the given canvas area. The canvas area typically corresponds to the area of a Widget and is given in absolute coordinates, whereas the invalidated area is given in relative coordinates. Implementations may lock the framebuffer here.
Parameters
canvasAreaAbs The canvas dimensions in absolute coordinates.
invalidatedAreaRel The area which should be updated in relative coordinates.
Implements VectorRenderer.
{
    canvasAreaAbsolute = canvasAreaAbs;
    drawArea = invalidatedAreaRel;
    canvasPainter = 0;
    // Clear transformation matrix
    matrix.reset();
    // Alpha reset
    alpha = 255;
    colorAlpha = 255;
    // Stroke reset
    strokeWidth = 1.0f;
    strokeLineJoin = VG_STROKE_LINEJOIN_MITER;
    strokeLineCap = VG_STROKE_LINECAP_BUTT;
}
References CWRVectorRenderer::canvasAreaAbsolute, CWRVectorRenderer::canvasPainter, CWRVectorRenderer::colorAlpha, CWRVectorRenderer::drawArea, CWRVectorRenderer::strokeLineCap, CWRVectorRenderer::strokeLineJoin, CWRVectorRenderer::strokeWidth, touchgfx::VG_STROKE_LINECAP_BUTT, and touchgfx::VG_STROKE_LINEJOIN_MITER.
tearDown()
void tearDown () virtual
Finalizes the current drawing. The implementation may block here until the drawing is done.
The implementation is required to unlock the framebuffer when tearDown is called.
Implements VectorRenderer.
{
    // Clear drawing area to avoid drawing any paths until next setup
    drawArea = Rect();
    // Wait for the painter to finish
    if (canvasPainter)
    {
        canvasPainter->tearDown();
    }
}
References CWRVectorRenderer::canvasPainter, and CWRVectorRenderer::drawArea.
Member Data Documentation
alpha
uint8_t alpha private
Referenced by CWRVectorRenderer::StrokeCanvas::setStroke().
canvasAlpha
uint8_t canvasAlpha private
canvasAreaAbsolute
Rect canvasAreaAbsolute private
Referenced by CWRVectorRenderer::drawFill(), CWRVectorRenderer::drawStroke(), and CWRVectorRenderer::setup().
canvasPainter
const AbstractPainter* canvasPainter private
Referenced by CWRVectorRenderer::drawFill(), CWRVectorRenderer::drawStroke(), CWRVectorRenderer::setColor(), CWRVectorRenderer::setLinearGradient(), CWRVectorRenderer::setup(), and CWRVectorRenderer::tearDown().
colorAlpha
uint8_t colorAlpha private
Referenced by CWRVectorRenderer::drawFill(), CWRVectorRenderer::drawStroke(), CWRVectorRenderer::setColor(), CWRVectorRenderer::setLinearGradient(), and CWRVectorRenderer::setup().
dirtyAreaAbsolute
Rect dirtyAreaAbsolute private
drawArea
Rect drawArea private
Referenced by CWRVectorRenderer::drawPath(), CWRVectorRenderer::setup(), and CWRVectorRenderer::tearDown().
drawMode
DrawMode drawMode private
Referenced by CWRVectorRenderer::drawFill(), CWRVectorRenderer::drawPathArea(), and CWRVectorRenderer::setMode().
matrix
Matrix3x3 matrix private
proxyWidget
touchgfx::CWRVectorRenderer::CanvasWidgetProxy proxyWidget private
strokeLineCap
VGStrokeLineCap strokeLineCap private
Referenced by CWRVectorRenderer::drawStroke(), CWRVectorRenderer::setStrokeLineCap(), CWRVectorRenderer::setup(), and CWRVectorRenderer::StrokeCanvas::strokeDrawLineCap().
strokeLineJoin
VGStrokeLineJoin strokeLineJoin private
Referenced by CWRVectorRenderer::drawStroke(), CWRVectorRenderer::setStrokeLineJoin(), CWRVectorRenderer::setup(), and CWRVectorRenderer::StrokeCanvas::strokeDrawLineJoin().
strokeMiterLimit
float strokeMiterLimit private
Referenced by CWRVectorRenderer::drawStroke(), and CWRVectorRenderer::setStrokeMiterLimit().
strokeWidth
float strokeWidth private
Referenced by CWRVectorRenderer::drawStroke(), CWRVectorRenderer::setStrokeWidth(), and CWRVectorRenderer::setup().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/CWRVectorRenderer.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/CWRVectorRenderer.cpp