Battery Simulator Documentation: RadioButtonGroup< CAPACITY >
RadioButtonGroup< CAPACITY >
#include "RadioButtonGroup.hpp"
Public Member Functions
RadioButtonGroup ()
virtual ~RadioButtonGroup ()
virtual void add (RadioButton &radioButton)
virtual bool getDeselectionEnabled () const
virtual RadioButton * getRadioButton (uint16_t index) const
virtual RadioButton * getSelectedRadioButton () const
virtual int32_t getSelectedRadioButtonIndex () const
virtual void setDeselectionEnabled (bool deselectionEnabled)
void setRadioButtonDeselectedHandler (GenericCallback< const AbstractButton & > &callback)
void setRadioButtonSelectedHandler (GenericCallback< const AbstractButton & > &callback)
virtual void setSelected (RadioButton &radioButton)
Protected Member Functions
virtual void radioButtonClickedHandler (const AbstractButton &radioButton)
virtual void radioButtonDeselectedHandler (const AbstractButton &radioButton)
Protected Attributes
Callback< RadioButtonGroup, const AbstractButton & > radioButtonClicked
Callback that is attached to the RadioButtons.
GenericCallback< const AbstractButton & > * radioButtonDeselectedCallback
The callback to be executed when a radio button belonging to this group is deselected.
RadioButton * radioButtons [CAPACITY]
The list of added RadioButtons.
GenericCallback< const AbstractButton & > * radioButtonSelectedCallback
The callback to be executed when a radio button belonging to this group is selected.
Callback< RadioButtonGroup, const AbstractButton & > radioButtonUnselected
Callback that is attached to the RadioButtons.
uint16_t size
The current number of added RadioButtons.
Detailed Description
template<uint16_t CAPACITY>
class touchgfx::RadioButtonGroup< CAPACITY >
Class for handling a collection of RadioButton objects. The RadioButtonGroup handles the automatic deselection of other radio buttons when a new RadioButton is selected. A callback is executed when a new selection occurs reporting the newly selected RadioButton.
Template Parameters
CAPACITY The number of RadioButtons to store in the RadioButtonGroup.
See also
RadioButton
Constructor & Destructor Documentation
RadioButtonGroup()
template<uint16_t CAPACITY> RadioButtonGroup () inline
Initializes a new instance of the RadioButtonGroup class.
        : size(0),
          radioButtonClicked(this, &RadioButtonGroup::radioButtonClickedHandler),
          radioButtonUnselected(this, &RadioButtonGroup::radioButtonDeselectedHandler),
          radioButtonSelectedCallback(0),
          radioButtonDeselectedCallback(0)
    {
    }
~RadioButtonGroup()
template<uint16_t CAPACITY> virtual ~RadioButtonGroup () inline virtual
Finalizes an instance of the RadioButtonGroup class.
    {
    }
Member Function Documentation
add()
template<uint16_t CAPACITY> virtual void add (RadioButton & radioButton) inline virtual
Add the RadioButton to the RadioButtonGroup. Adding more radio buttons than the CAPACITY of the RadioButtonGroup raises an assert.
Parameters
[in] radioButton The RadioButton to add.
    {
        assert(size < CAPACITY && "RadioButtonGroup capacity exceeded!");
        radioButton.setAction(radioButtonClicked);
        radioButton.setDeselectedAction(radioButtonUnselected);
        radioButtons[size++] = &radioButton;
    }
References RadioButtonGroup< CAPACITY >::radioButtonClicked, RadioButtonGroup< CAPACITY >::radioButtons, and RadioButtonGroup< CAPACITY >::radioButtonUnselected.
getDeselectionEnabled()
template<uint16_t CAPACITY> virtual bool getDeselectionEnabled () const inline virtual
Gets the current deselectionEnabled state.
Returns
The current deselectionEnabled state.
See also
setDeselectionEnabled
    {
        return (size > 0) ? radioButtons[0]->getDeselectionEnabled() : false;
    }
References RadioButton::getDeselectionEnabled(), and RadioButtonGroup< CAPACITY >::radioButtons.
getRadioButton()
template<uint16_t CAPACITY> virtual RadioButton * getRadioButton (uint16_t index) const inline virtual
Gets the RadioButton at the specified index.
Parameters
index the index of the RadioButton to return.
Returns
the RadioButton at the specified index. Returns 0 if the index is illegal.
    {
        return (size > index) ? radioButtons[index] : 0;
    }
References RadioButtonGroup< CAPACITY >::radioButtons.
Referenced by RadioButtonGroup< CAPACITY >::getSelectedRadioButton().
getSelectedRadioButton()
template<uint16_t CAPACITY> virtual RadioButton * getSelectedRadioButton () const inline virtual
Gets the currently selected RadioButton
Returns
a pointer to the selected RadioButton. Returns 0 if no RadioButton is selected.
    {
        int32_t index = getSelectedRadioButtonIndex();
        return (index < 0) ? 0 : getRadioButton(index);
    }
References RadioButtonGroup< CAPACITY >::getRadioButton(), and RadioButtonGroup< CAPACITY >::getSelectedRadioButtonIndex().
getSelectedRadioButtonIndex()
template<uint16_t CAPACITY> virtual int32_t getSelectedRadioButtonIndex () const inline virtual
Gets the index of the currently selected RadioButton.
Returns
the index of the selected RadioButton. Returns -1 if no RadioButton is selected.
    {
        for (uint16_t i = 0; i < size; i++)
        {
            if (radioButtons[i]->getSelected())
            {
                return i;
            }
        }
        return -1;
    }
References RadioButtonGroup< CAPACITY >::radioButtons, and RadioButtonGroup< CAPACITY >::size.
Referenced by RadioButtonGroup< CAPACITY >::getSelectedRadioButton().
radioButtonClickedHandler()
template<uint16_t CAPACITY> virtual void radioButtonClickedHandler (const AbstractButton & radioButton) inline protected virtual
Handles the event that a RadioButton has been selected. deselects all other RadioButtons.
Parameters
radioButton the RadioButton that has been selected.
    {
        // Deselect other radio buttons
        for (uint16_t i = 0; i < size; i++)
        {
            if (radioButtons[i] != &radioButton)
            {
                if (radioButtons[i]->getSelected())
                {
                    radioButtons[i]->setSelected(false);
                }
            }
        }
        if (radioButtonSelectedCallback && radioButtonSelectedCallback->isValid())
        {
            radioButtonSelectedCallback->execute(radioButton);
        }
    }
References RadioButtonGroup< CAPACITY >::radioButtons, RadioButtonGroup< CAPACITY >::radioButtonSelectedCallback, RadioButton::setSelected(), and RadioButtonGroup< CAPACITY >::size.
Referenced by RadioButtonGroup< CAPACITY >::setSelected().
radioButtonDeselectedHandler()
template<uint16_t CAPACITY> virtual void radioButtonDeselectedHandler (const AbstractButton & radioButton) inline protected virtual
Handles the event that a RadioButton has been deselected.
Parameters
radioButton the RadioButton that has been deselected.
    {
        if (radioButtonDeselectedCallback && radioButtonDeselectedCallback->isValid())
        {
            radioButtonDeselectedCallback->execute(radioButton);
        }
    }
References RadioButtonGroup< CAPACITY >::radioButtonDeselectedCallback.
setDeselectionEnabled()
template<uint16_t CAPACITY> virtual void setDeselectionEnabled (bool deselectionEnabled) inline virtual
Sets whether or not it is possible to deselect RadioButtons by clicking them when they are selected. If deselection is enabled, it will be possible to select a RadioButton (and as a result deselect all other radio buttons) and the push the same RadioButton again to deselect it. The result is that no RadioButton is selected.
Parameters
deselectionEnabled true if it should be possible to deselect by click.
See also
getDeselectionEnabled
    {
        for (uint16_t i = 0; i < size; i++)
        {
            radioButtons[i]->setDeselectionEnabled(deselectionEnabled);
        }
    }
References RadioButtonGroup< CAPACITY >::radioButtons, RadioButton::setDeselectionEnabled(), and RadioButtonGroup< CAPACITY >::size.
setRadioButtonDeselectedHandler()
template<uint16_t CAPACITY> void setRadioButtonDeselectedHandler (GenericCallback< const AbstractButton & > & callback) inline
Associates an action to be performed when a radio button belonging to this group transition from selected to unselected.
Parameters
callback The callback to be executed. The callback will be given a reference to the RadioButton that was selected.
See also
GenericCallback
    {
        radioButtonDeselectedCallback = &callback;
    }
References RadioButtonGroup< CAPACITY >::radioButtonDeselectedCallback.
setRadioButtonSelectedHandler()
template<uint16_t CAPACITY> void setRadioButtonSelectedHandler (GenericCallback< const AbstractButton & > & callback) inline
Associates an action to be performed when a radio button belonging to this group is selected.
Parameters
callback The callback to be executed. The callback will be given a reference to the RadioButton that was selected.
See also
GenericCallback
    {
        radioButtonSelectedCallback = &callback;
    }
References RadioButtonGroup< CAPACITY >::radioButtonSelectedCallback.
setSelected()
template<uint16_t CAPACITY> virtual void setSelected (RadioButton & radioButton) inline virtual
Sets the specified RadioButton to be selected.
Sets the specified RadioButton to be selected and all other radio buttons to be deselected. Do not call this function before all RadioButton objects have been added to the RadioButtonGroup. Will call the radioButtonSelected callback.
Parameters
[in] radioButton the RadioButton to be selected.
    {
        radioButton.setSelected(true);
        radioButtonClickedHandler(radioButton);
    }
References RadioButtonGroup< CAPACITY >::radioButtonClickedHandler().
Member Data Documentation
radioButtonClicked
template<uint16_t CAPACITY> Callback<RadioButtonGroup, const AbstractButton&> radioButtonClicked protected
Callback that is attached to the RadioButtons.
Referenced by RadioButtonGroup< CAPACITY >::add().
radioButtonDeselectedCallback
template<uint16_t CAPACITY> GenericCallback<const AbstractButton&>* radioButtonDeselectedCallback protected
The callback to be executed when a radio button belonging to this group is deselected.
Referenced by RadioButtonGroup< CAPACITY >::radioButtonDeselectedHandler(), and RadioButtonGroup< CAPACITY >::setRadioButtonDeselectedHandler().
radioButtons
template<uint16_t CAPACITY> RadioButton* radioButtons[CAPACITY] protected
The list of added RadioButtons.
Referenced by RadioButtonGroup< CAPACITY >::add(), RadioButtonGroup< CAPACITY >::getDeselectionEnabled(), RadioButtonGroup< CAPACITY >::getRadioButton(), RadioButtonGroup< CAPACITY >::getSelectedRadioButtonIndex(), RadioButtonGroup< CAPACITY >::radioButtonClickedHandler(), and RadioButtonGroup< CAPACITY >::setDeselectionEnabled().
radioButtonSelectedCallback
template<uint16_t CAPACITY> GenericCallback<const AbstractButton&>* radioButtonSelectedCallback protected
The callback to be executed when a radio button belonging to this group is selected.
Referenced by RadioButtonGroup< CAPACITY >::radioButtonClickedHandler(), and RadioButtonGroup< CAPACITY >::setRadioButtonSelectedHandler().
radioButtonUnselected
template<uint16_t CAPACITY> Callback<RadioButtonGroup, const AbstractButton&> radioButtonUnselected protected
Callback that is attached to the RadioButtons.
Referenced by RadioButtonGroup< CAPACITY >::add().
size
template<uint16_t CAPACITY> uint16_t size protected
The current number of added RadioButtons.
Referenced by RadioButtonGroup< CAPACITY >::getSelectedRadioButtonIndex(), RadioButtonGroup< CAPACITY >::radioButtonClickedHandler(), and RadioButtonGroup< CAPACITY >::setDeselectionEnabled().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/RadioButtonGroup.hpp