Battery Simulator Documentation: UIEventListener
UIEventListener
#include "UIEventListener.hpp"
Public Member Functions
virtual ~UIEventListener ()
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleKeyEvent (uint8_t c)
virtual void handlePendingScreenTransition ()
virtual void handleTickEvent ()
Detailed Description
This class declares a handler interface for user interface events, i.e. events generated by the users interaction with the device. With the exception of the system timer tick, all other system events, which are not related to the user interface device peripherals (display, keys etc.) are not part of this interface.
Constructor & Destructor Documentation
~UIEventListener()
virtual ~UIEventListener () inline virtual
Finalizes an instance of the UIEventListener class.
    {
    }
Member Function Documentation
handleClickEvent()
virtual void handleClickEvent (const ClickEvent & event) inline virtual
This handler is invoked when a mouse click or display touch event has been detected by the system.
Parameters
event The event data.
Reimplemented in Application.
    {
        (void)event; // Unused variable
    }
References void().
handleDragEvent()
virtual void handleDragEvent (const DragEvent & event) inline virtual
This handler is invoked when a drag event has been detected by the system.
Parameters
event The event data.
Reimplemented in Application.
    {
        (void)event; // Unused variable
    }
References void().
handleGestureEvent()
virtual void handleGestureEvent (const GestureEvent & event) inline virtual
This handler is invoked when a gesture event has been detected by the system.
Parameters
event The event data.
Reimplemented in Application.
    {
        (void)event; // Unused variable
    }
References void().
handleKeyEvent()
virtual void handleKeyEvent (uint8_t c) inline virtual
This handler is invoked when a key (or button) event has been detected by the system.
Parameters
c The key or button pressed.
Reimplemented in Application.
    {
        (void)c; // Unused variable
    }
References void().
handlePendingScreenTransition()
virtual void handlePendingScreenTransition () inline virtual
This handler is invoked when a change screen event is pending.
Reimplemented in MVPApplication, and Application.
    {
    }
handleTickEvent()
virtual void handleTickEvent () inline virtual
This handler is invoked when a system tick event has been generated. The system tick period is configured in the HAL.
Reimplemented in Application, and FrontendApplication.
    {
    }
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/UIEventListener.hpp