Battery Simulator Documentation: CanvasWidget
CanvasWidget abstract
#include "CanvasWidget.hpp"
Public Member Functions
CanvasWidget ()
virtual void draw (const Rect &invalidatedArea) const
virtual bool drawCanvasWidget (const Rect &invalidatedArea) const =0
virtual uint8_t getAlpha () const
virtual Rect getMinimalRect () const
const AbstractPainter * getPainter () const
virtual Rect getSolidRect () const
virtual void invalidate () const
virtual void setAlpha (uint8_t newAlpha)
void setPainter (const AbstractPainter &painter)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
uint8_t alpha
The Alpha for this CanvasWidget.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Private Attributes
const AbstractPainter * canvasPainter
Detailed Description
Class for drawing complex polygons on the display using CanvasWidgetRenderer. The CanvasWidget is used by passing it to a Canvas object, drawing the outline of the object and then having CanvasWidget render the outline on the display using the assigned painter.
Constructor & Destructor Documentation
CanvasWidget()
CanvasWidget ()
    : Widget(),
      alpha(255),
      canvasPainter(0)
{
}
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draws the given invalidated area. If the underlying CanvasWidgetRenderer fail to render the widget (if the widget is too complex), the invalidated area is cut into smaller slices (horizontally) which are then drawn separately. If drawing a single raster line fails, that line is considered too complex and skipped (it is left blank/transparent) and drawing continues on the next raster line.
If drawing has failed at least once, which means that the number of horizontal lines draw has been reduced, the number of successfully drawn horizontal lines is remembered for the next invocation of draw(). A future call to draw() would then start off with the reduced number of horizontal lines to prevent potentially drawing the canvas widget in vain, as happened previously in draw().
Parameters
invalidatedArea The invalidated area.
See also
drawCanvasWidget
Note
Subclasses of CanvasWidget should implement drawCanvasWidget(), not draw().
The term "too complex" means that the size of the buffer (assigned to CanvasWidgetRenderer using CanvasWidgetRenderer::setupBuffer()) is too small.
Implements Drawable.
Reimplemented in GraphElementGridBase, GraphElementVerticalGapLine, GraphElementHistogram, GraphElementBoxes, GraphLabelsBase, and GraphTitle.
{
    Rect area = invalidatedArea & getMinimalRect();
    if (!canvasPainter || !canvasPainter->setup(getRect()) || area.isEmpty())
    {
        // Painter not ready to paint or nothing to paint => done
        return;
    }
    switch (HAL::DISPLAY_ROTATION)
    {
    case rotate0:
        {
            const int16_t bottom = area.bottom();
            while (area.y < bottom)
            {
                while (!drawCanvasWidget(area))
                {
                    if (area.height == 1)
                    {
                        // Failed on a single line
                        break;
                    }
                    area.height = (area.height + 1) >> 1; // Cannot become 0 as (2+1)>>1=1
#ifdef SIMULATOR
                    if (CanvasWidgetRenderer::getWriteMemoryUsageReport())
                    {
                        if (area.height > 1)
{
                            touchgfx_printf("CWR will split draw into multiple draws due to limited memory.\n");
                        }
                        else
{
                            touchgfx_printf("CWR was unable to complete a draw operation due to limited memory.\n");
                        }
                    }
#endif
                }
                area.y += area.height;
                if (area.bottom() > bottom)
                {
                    area.height = bottom - area.y;
                }
            }
        }
        break;
    case rotate90:
        {
            const int16_t right = area.right();
            while (area.x < right)
            {
                while (!drawCanvasWidget(area))
                {
                    if (area.width == 1)
                    {
                        break;
                    }
                    area.width = (area.width + 1) >> 1;
#ifdef SIMULATOR
                    if (CanvasWidgetRenderer::getWriteMemoryUsageReport())
                    {
                        if (area.width > 1)
{
                            touchgfx_printf("CWR will split draw into multiple draws due to limited memory.\n");
                        }
                        else
{
                            touchgfx_printf("CWR was unable to complete a draw operation due to limited memory.\n");
                        }
                    }
#endif
                }
                area.x += area.width;
                if (area.right() > right)
                {
                    area.width = right - area.x;
                }
            }
        }
        break;
    }
}
References Rect::bottom(), CanvasWidget::canvasPainter, HAL::DISPLAY_ROTATION, CanvasWidget::drawCanvasWidget(), CanvasWidget::getMinimalRect(), Drawable::getRect(), Rect::height, Rect::isEmpty(), Rect::right(), touchgfx::rotate0, touchgfx::rotate90, touchgfx_printf, Rect::width, Rect::x, and Rect::y.
drawCanvasWidget()
virtual bool drawCanvasWidget (const Rect & invalidatedArea) const pure virtual
Draw canvas widget for the given invalidated area. Similar to draw(), but might be invoked several times with increasingly smaller areas to due to memory constraints from the underlying CanvasWidgetRenderer.
Parameters
invalidatedArea The invalidated area.
Returns
true if the widget was drawn properly, false if not.
See also
draw
Implemented in AbstractGraphElementNoCWR, GraphTitle, AbstractShape, Circle, CWRVectorRenderer::CanvasWidgetProxy, Line, GraphElementArea, GraphElementLine, GraphElementDots, and GraphElementDiamonds.
Referenced by CanvasWidget::draw().
getAlpha()
virtual uint8_t getAlpha () const inline virtual
Gets the current alpha value of the widget. The alpha value is in range 255 (solid) to 0 (invisible).
Returns
The current alpha value.
See also
setAlpha
    {
        return alpha;
    }
References CanvasWidget::alpha.
Referenced by GraphElementGridBase::draw(), GraphElementVerticalGapLine::draw(), GraphElementHistogram::draw(), GraphElementBoxes::draw(), GraphLabelsBase::draw(), GraphTitle::draw(), AbstractShape::drawCanvasWidget(), Circle::drawCanvasWidget(), Line::drawCanvasWidget(), GraphElementArea::drawCanvasWidget(), GraphElementLine::drawCanvasWidget(), GraphElementDots::drawCanvasWidget(), GraphElementDiamonds::drawCanvasWidget(), and GraphLabelsX::invalidateGraphPointAt().
getMinimalRect()
virtual Rect getMinimalRect () const inline virtual
Gets minimal rectangle containing the shape drawn by this widget. Default implementation returns the size of the entire widget, but this function should be overwritten in subclasses and return the minimal rectangle containing the shape. See classes such as Circle for example implementations.
Returns
The minimal rectangle containing the shape drawn.
Reimplemented in AbstractShape, Circle, and Line.
    {
        return Rect(0, 0, getWidth(), getHeight());
    }
References Drawable::getHeight(), and Drawable::getWidth().
Referenced by CanvasWidget::draw(), and CanvasWidget::invalidate().
getPainter()
const AbstractPainter * getPainter () const inline
Gets the current painter for the CanvasWidget.
Returns
The painter.
See also
setPainter
    {
        return canvasPainter;
    }
References CanvasWidget::canvasPainter.
Referenced by AbstractShape::drawCanvasWidget(), Circle::drawCanvasWidget(), Line::drawCanvasWidget(), GraphElementArea::drawCanvasWidget(), GraphElementLine::drawCanvasWidget(), GraphElementDots::drawCanvasWidget(), and GraphElementDiamonds::drawCanvasWidget().
getSolidRect()
virtual Rect getSolidRect () const inline virtual
Gets the largest solid (non-transparent) rectangle. Since canvas widgets typically do not have a solid rect, it is recommended to return an empty rectangle.
Returns
The largest solid (non-transparent) rectangle.
See also
draw
Note
Function draw() might fail for some horizontal lines due to memory constraints. These lines will not be drawn and may cause strange display artifacts.
Implements Drawable.
    {
        return Rect();
    }
invalidate()
void invalidate () const virtual
Invalidates the area covered by this CanvasWidget. Since many widgets are a lot smaller than the actual size of the canvas widget, each widget must be able to tell the smallest rectangle completely containing the shape drawn by the widget. For example a circle arc is typically much smaller than the widget containing the circle.
See also
getMinimalRect
Reimplemented from Drawable.
{
    Rect minimalRect = getMinimalRect();
    minimalRect &= Rect(0, 0, getWidth(), getHeight());
    invalidateRect(minimalRect);
}
References Drawable::getHeight(), CanvasWidget::getMinimalRect(), Drawable::getWidth(), and Drawable::invalidateRect().
setAlpha()
virtual void setAlpha (uint8_t newAlpha) inline virtual
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
    {
        alpha = newAlpha;
    }
Referenced by CircleProgress::setAlpha(), LineProgress::setAlpha(), and Gauge::setAlpha().
setPainter()
void setPainter (const AbstractPainter & painter) inline
Sets a painter for the CanvasWidget.
Parameters
[in] painter The painter for the CanvasWidget.
See also
getPainter
Note
If setPainter() is used to change the painter to a different painter, the area containing the CanvasWidget is not automatically invalidated.
    {
        canvasPainter = &painter;
    }
References CanvasWidget::canvasPainter.
Referenced by CircleProgress::setPainter(), and LineProgress::setPainter().
Member Data Documentation
alpha
uint8_t alpha protected
The Alpha for this CanvasWidget.
Referenced by CanvasWidget::getAlpha().
canvasPainter
const AbstractPainter* canvasPainter private
Referenced by CanvasWidget::draw(), CanvasWidget::getPainter(), and CanvasWidget::setPainter().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/CanvasWidget.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/CanvasWidget.cpp