Battery Simulator Documentation: FrontendHeap
FrontendHeap
#include "FrontendHeap.hpp"
Public Types
typedef touchgfx::meta::TypeList< MaxGeneratedPresenterType, touchgfx::meta::TypeList< MaxUserPresenterType, touchgfx::meta::Nil > > CombinedPresenterTypes
typedef touchgfx::meta::TypeList< MaxGeneratedTransitionType, touchgfx::meta::TypeList< MaxUserTransitionType, touchgfx::meta::Nil > > CombinedTransitionTypes
typedef touchgfx::meta::TypeList< MaxGeneratedViewType, touchgfx::meta::TypeList< MaxUserViewType, touchgfx::meta::Nil > > CombinedViewTypes
typedef touchgfx::meta::select_type_maxsize< CombinedPresenterTypes >::type MaxPresenterType
typedef touchgfx::meta::select_type_maxsize< CombinedTransitionTypes >::type MaxTransitionType
typedef touchgfx::meta::select_type_maxsize< UserDefinedPresenterTypes >::type MaxUserPresenterType
typedef touchgfx::meta::select_type_maxsize< UserDefinedTransitionTypes >::type MaxUserTransitionType
typedef touchgfx::meta::select_type_maxsize< UserDefinedViewTypes >::type MaxUserViewType
typedef touchgfx::meta::select_type_maxsize< CombinedViewTypes >::type MaxViewType
typedef touchgfx::meta::TypeList< touchgfx::meta::Nil, touchgfx::meta::Nil > UserDefinedPresenterTypes
typedef touchgfx::meta::TypeList< touchgfx::meta::Nil, touchgfx::meta::Nil > UserDefinedTransitionTypes
typedef touchgfx::meta::TypeList< touchgfx::meta::Nil, touchgfx::meta::Nil > UserDefinedViewTypes
Public Types inherited from FrontendHeapBase
typedef touchgfx::meta::TypeList< Screen1Presenter, touchgfx::meta::Nil > GeneratedPresenterTypes
typedef touchgfx::meta::TypeList< touchgfx::NoTransition, touchgfx::meta::Nil > GeneratedTransitionTypes
typedef touchgfx::meta::TypeList< Screen1View, touchgfx::meta::Nil > GeneratedViewTypes
typedef touchgfx::meta::select_type_maxsize< GeneratedPresenterTypes >::type MaxGeneratedPresenterType
typedef touchgfx::meta::select_type_maxsize< GeneratedTransitionTypes >::type MaxGeneratedTransitionType
typedef touchgfx::meta::select_type_maxsize< GeneratedViewTypes >::type MaxGeneratedViewType
Static Public Member Functions
static FrontendHeap & getInstance ()
Public Attributes
FrontendApplication app
Model model
touchgfx::Partition< CombinedPresenterTypes, 1 > presenters
touchgfx::Partition< CombinedTransitionTypes, 1 > transitions
touchgfx::Partition< CombinedViewTypes, 1 > views
Public Attributes inherited from MVPHeap
MVPApplication & frontendApplication
A reference to the MVPApplication instance.
AbstractPartition & presenterStorage
A memory partition containing enough memory to hold the largest presenter.
AbstractPartition & screenStorage
A memory partition containing enough memory to hold the largest view.
AbstractPartition & transitionStorage
A memory partition containing enough memory to hold the largest transition.
Private Member Functions
FrontendHeap ()
Additional Inherited Members
Public Member Functions inherited from FrontendHeapBase
virtual void gotoStartScreen (FrontendApplication &app)
Public Member Functions inherited from MVPHeap
MVPHeap (AbstractPartition &pres, AbstractPartition &scr, AbstractPartition &tra, MVPApplication &app)
virtual ~MVPHeap ()
Protected Member Functions inherited from FrontendHeapBase
FrontendHeapBase (touchgfx::AbstractPartition &presenters, touchgfx::AbstractPartition &views, touchgfx::AbstractPartition &transitions, FrontendApplication &app)
Detailed Description
Member Typedef Documentation
CombinedPresenterTypes
typedef touchgfx::meta::TypeList< MaxGeneratedPresenterType, touchgfx::meta::TypeList< MaxUserPresenterType, touchgfx::meta::Nil > > CombinedPresenterTypes
CombinedTransitionTypes
typedef touchgfx::meta::TypeList< MaxGeneratedTransitionType, touchgfx::meta::TypeList< MaxUserTransitionType, touchgfx::meta::Nil > > CombinedTransitionTypes
CombinedViewTypes
typedef touchgfx::meta::TypeList< MaxGeneratedViewType, touchgfx::meta::TypeList< MaxUserViewType, touchgfx::meta::Nil > > CombinedViewTypes
MaxPresenterType
typedef touchgfx::meta::select_type_maxsize<CombinedPresenterTypes>::type MaxPresenterType
MaxTransitionType
typedef touchgfx::meta::select_type_maxsize<CombinedTransitionTypes>::type MaxTransitionType
MaxUserPresenterType
typedef touchgfx::meta::select_type_maxsize<UserDefinedPresenterTypes>::type MaxUserPresenterType
MaxUserTransitionType
typedef touchgfx::meta::select_type_maxsize<UserDefinedTransitionTypes>::type MaxUserTransitionType
MaxUserViewType
typedef touchgfx::meta::select_type_maxsize<UserDefinedViewTypes>::type MaxUserViewType
MaxViewType
typedef touchgfx::meta::select_type_maxsize<CombinedViewTypes>::type MaxViewType
UserDefinedPresenterTypes
typedef touchgfx::meta::TypeList< touchgfx::meta::Nil, touchgfx::meta::Nil > UserDefinedPresenterTypes
UserDefinedTransitionTypes
typedef touchgfx::meta::TypeList< touchgfx::meta::Nil, touchgfx::meta::Nil > UserDefinedTransitionTypes
UserDefinedViewTypes
typedef touchgfx::meta::TypeList< touchgfx::meta::Nil, touchgfx::meta::Nil > UserDefinedViewTypes
Constructor & Destructor Documentation
FrontendHeap()
FrontendHeap () inline private
                   : FrontendHeapBase(presenters, views, transitions, app),
                     app(model, *this)
    {
        gotoStartScreen(app);
    }
References app, and FrontendHeapBase::gotoStartScreen().
Member Function Documentation
getInstance()
static FrontendHeap & getInstance () inline static
    {
        static FrontendHeap instance;
        return instance;
    }
Referenced by touchgfx::touchgfx_generic_init(), and touchgfx::touchgfx_init().
Member Data Documentation
app
FrontendApplication app
Referenced by FrontendHeap().
model
Model model
presenters
touchgfx::Partition< CombinedPresenterTypes, 1 > presenters
transitions
touchgfx::Partition< CombinedTransitionTypes, 1 > transitions
views
touchgfx::Partition< CombinedViewTypes, 1 > views
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/gui/include/gui/common/FrontendHeap.hpp