Battery Simulator Documentation: PainterRGB888
PainterRGB888
#include "PainterRGB888.hpp"
Public Member Functions
PainterRGB888 (colortype color=0)
virtual HAL::RenderingMethod getRenderingMethod () const
virtual void paint (uint8_t *destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const
virtual void setColor (colortype color)
virtual void tearDown () const
Public Member Functions inherited from AbstractPainterRGB888
AbstractPainterRGB888 ()
Public Member Functions inherited from AbstractPainter
AbstractPainter ()
virtual ~AbstractPainter ()
void framebufferToDisplay (int16_t &widgetX, int16_t &widgetY) const
virtual bool setup (const Rect &widgetRect) const
Public Member Functions inherited from AbstractPainterColor
AbstractPainterColor (colortype color=0)
virtual ~AbstractPainterColor ()
colortype getColor () const
Protected Attributes
uint8_t painterBlue
The blue part of the color.
uint8_t painterGreen
The green part of the color.
uint8_t painterRed
The red part of the color.
Protected Attributes inherited from AbstractPainter
int16_t widgetWidth
The width of the widget on screen, used by framebufferToDisplay()
Protected Attributes inherited from AbstractPainterColor
colortype painterColor
The color.
Additional Inherited Members
Static Protected Member Functions inherited from AbstractPainter
static FORCE_INLINE_FUNCTION bool compatibleFramebuffer (Bitmap::BitmapFormat format)
Detailed Description
The PainterRGB888 class allows a shape to be filled with a given color value. This allows anti-aliased elements to be drawn.
See also
AbstractPainter
Constructor & Destructor Documentation
PainterRGB888()
PainterRGB888 (colortype color = 0) inline
Initializes a new instance of the PainterRGB888 class.
Parameters
color (Optional) the color, default is black.
        : AbstractPainterRGB888(), AbstractPainterColor(color)
    {
    }
Member Function Documentation
getRenderingMethod()
virtual HAL::RenderingMethod getRenderingMethod () const inline virtual
Return the applicable rendering method of the painter. HARDWARE if the painter uses hardware based drawing, SOFTWARE otherwise. Relevant on platforms using DCACHE.
Returns
HARDWARE if painter uses hardware based drawing, SOFTWARE otherwise.
Reimplemented from AbstractPainter.
    {
        return HAL::getInstance()->getDMAType() == DMA_TYPE_CHROMART ? HAL::HARDWARE : HAL::SOFTWARE;
    }
References touchgfx::DMA_TYPE_CHROMART, HAL::getInstance(), HAL::HARDWARE, and HAL::SOFTWARE.
paint()
void paint (uint8_t * destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const virtual
Paints a streak of pixels (all with the same alpha) in the framebuffer. The first pixel to paint is at 'offset' relative to 'destination' (to be able to support 1bpp, 2bpp and 4bpp). The first pixel to paint is at the given 'widgetX', 'widgetY' coordinate. The number of pixels to paint is 'count' and the alpha to apply is 'alpha'.
Note that the widgetX, widgetY is relative to the widget in the framebuffer, not the display. To convert the coordinate to display widget coordinates, use framebufferToDisplay().
Parameters
[in] destination If non-null, the pointer.
offset The offset to add to the destination.
widgetX The widget x coordinate.
widgetY The widget y coordinate.
count Number of pixels.
alpha The alpha of the pixels.
See also
AbstractPainter::setup, AbstractPainter::tearDown, AbstractPainter::framebufferToDisplay
Implements AbstractPainter.
{
    uint8_t* RESTRICT framebuffer = destination + offset * 3;
    paint::rgb888::lineFromColor(framebuffer, count, painterColor, alpha);
}
References touchgfx::paint::rgb888::lineFromColor(), AbstractPainterColor::painterColor, and RESTRICT.
setColor()
virtual void setColor (colortype color) inline virtual
Sets color to use when drawing the CanvasWidget.
Parameters
color The color.
Reimplemented from AbstractPainterColor.
    {
        AbstractPainterColor::setColor(color);
        painterRed = Color::getRed(color);
        painterGreen = Color::getGreen(color);
        painterBlue = Color::getBlue(color);
    }
References Color::getBlue(), Color::getGreen(), Color::getRed(), PainterRGB888::painterBlue, PainterRGB888::painterGreen, PainterRGB888::painterRed, and AbstractPainterColor::setColor().
tearDown()
void tearDown () const virtual
This function is called after all paint operation have finished. This allows the painter to close down dma queues etc. This happens after the last scan line segment has been drawn.
See also
AbstractPainter::paint, AbstractPainter::setup
Reimplemented from AbstractPainter.
{
    paint::tearDown();
}
References touchgfx::paint::tearDown().
Member Data Documentation
painterBlue
uint8_t painterBlue protected
The blue part of the color.
Referenced by PainterRGB888::setColor().
painterGreen
uint8_t painterGreen protected
The green part of the color.
Referenced by PainterRGB888::setColor().
painterRed
uint8_t painterRed protected
The red part of the color.
Referenced by PainterRGB888::setColor().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/PainterRGB888.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/PainterRGB888.cpp