Battery Simulator Documentation: SwipeContainer
SwipeContainer
#include "SwipeContainer.hpp"
Classes
class PageIndicator
Public Member Functions
SwipeContainer ()
virtual ~SwipeContainer ()
virtual void add (Drawable &page)
uint8_t getAnimationDuration () const
uint8_t getNumberOfPages ()
uint8_t getSelectedPage () const
void goNextPage (uint8_t duration=20)
void goPreviousPage (uint8_t duration=20)
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void remove (Drawable &page)
void setAnimationDuration (uint8_t newDuration)
void setEndSwipeElasticWidth (uint16_t width)
void setPageIndicatorBitmaps (const Bitmap &normalPage, const Bitmap &highlightedPage)
void setPageIndicatorCenteredX ()
void setPageIndicatorCenteredX (int16_t x)
void setPageIndicatorXY (int16_t x, int16_t y)
void setPageIndicatorXYWithCenteredX (int16_t x, int16_t y)
void setSelectedPage (uint8_t pageIndex)
virtual void setSwipeCutoff (uint16_t cutoff)
Public Member Functions inherited from Container
Container ()
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Private Types
enum States {
ANIMATE_SWIPE_CANCELLED_LEFT , ANIMATE_SWIPE_CANCELLED_RIGHT , ANIMATE_LEFT , ANIMATE_RIGHT ,
ANIMATE_LEFT_WITH_BUTTON , ANIMATE_RIGHT_WITH_BUTTON , NO_ANIMATION
}
Private Member Functions
void adjustPages ()
void animateLeft ()
void animateLeftWithButton ()
void animateRight ()
void animateRightWithButton ()
void animateSwipeCancelledLeft ()
void animateSwipeCancelledRight ()
Private Attributes
int16_t animateDistance
uint8_t animationCounter
uint8_t animationDuration
enum touchgfx::SwipeContainer::States currentState
int16_t dragX
uint16_t endElasticWidth
touchgfx::SwipeContainer::PageIndicator pageIndicator
ListLayout pages
int16_t startX
uint16_t swipeCutoff
Static Private Attributes
static const int16_t DRAG_CANCEL_THRESHOLD = 3
Additional Inherited Members
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A SwipeContainer is a Container with a horizontally laid out list of identically sized Drawables. The bottom of the SwipeContainer shows a page indicator to indicate the position in the horizontal list of items in the SwipeContainer.
See also
ListLayout
Member Enumeration Documentation
States
enum States private
Enumerator
ANIMATE_SWIPE_CANCELLED_LEFT
ANIMATE_SWIPE_CANCELLED_RIGHT
ANIMATE_LEFT
ANIMATE_RIGHT
ANIMATE_LEFT_WITH_BUTTON
ANIMATE_RIGHT_WITH_BUTTON
NO_ANIMATION
    {
        ANIMATE_SWIPE_CANCELLED_LEFT,
        ANIMATE_SWIPE_CANCELLED_RIGHT,
        ANIMATE_LEFT,
        ANIMATE_RIGHT,
        ANIMATE_LEFT_WITH_BUTTON,
        ANIMATE_RIGHT_WITH_BUTTON,
        NO_ANIMATION
    } currentState;
Constructor & Destructor Documentation
SwipeContainer()
SwipeContainer ()
    : Container(),
      currentState(NO_ANIMATION),
      animationCounter(0),
      swipeCutoff(80),
      dragX(0),
      animateDistance(0),
      startX(0),
      endElasticWidth(30),
      animationDuration(20),
      pages(EAST),
      pageIndicator()
{
    Application::getInstance()->registerTimerWidget(this);
    setTouchable(true);
    Container::add(pages);
    Container::add(pageIndicator);
}
References Container::add(), Application::getInstance(), SwipeContainer::pageIndicator, SwipeContainer::pages, and Drawable::setTouchable().
~SwipeContainer()
~SwipeContainer () virtual
{
    Application::getInstance()->unregisterTimerWidget(this);
}
References Application::getInstance().
Member Function Documentation
add()
void add (Drawable & page) virtual
Adds a page to the container.
Parameters
[in] page The page to add.
Note
All pages must have the same width and height.
Reimplemented from Container.
{
    pages.add(page);
    pageIndicator.setNumberOfPages(getNumberOfPages() + 1);
    setSelectedPage(getSelectedPage());
    setWidthHeight(page);
}
References ListLayout::add(), SwipeContainer::getNumberOfPages(), SwipeContainer::getSelectedPage(), SwipeContainer::pageIndicator, SwipeContainer::pages, SwipeContainer::PageIndicator::setNumberOfPages(), SwipeContainer::setSelectedPage(), and Drawable::setWidthHeight().
adjustPages()
void adjustPages () private
{
    pages.moveTo(-static_cast<int16_t>(getSelectedPage() * getWidth()) + dragX, 0);
}
References SwipeContainer::dragX, SwipeContainer::getSelectedPage(), Drawable::getWidth(), Drawable::moveTo(), and SwipeContainer::pages.
Referenced by SwipeContainer::animateLeft(), SwipeContainer::animateLeftWithButton(), SwipeContainer::animateRight(), SwipeContainer::animateRightWithButton(), SwipeContainer::animateSwipeCancelledLeft(), SwipeContainer::animateSwipeCancelledRight(), SwipeContainer::handleDragEvent(), and SwipeContainer::setSelectedPage().
animateLeft()
void animateLeft () private
{
    const uint8_t duration = 10;
    if (animationCounter <= duration)
    {
        const int16_t delta = EasingEquations::cubicEaseOut(animationCounter, 0, getWidth() + animateDistance, duration);
        dragX = animateDistance - delta;
    }
    else
    {
        // Final step: stop the animation
        currentState = NO_ANIMATION;
        animationCounter = 0;
        dragX = 0;
        pageIndicator.goRight();
    }
    adjustPages();
    animationCounter++;
}
References SwipeContainer::adjustPages(), SwipeContainer::animateDistance, SwipeContainer::animationCounter, EasingEquations::cubicEaseOut(), SwipeContainer::currentState, SwipeContainer::dragX, Drawable::getWidth(), SwipeContainer::PageIndicator::goRight(), SwipeContainer::NO_ANIMATION, and SwipeContainer::pageIndicator.
Referenced by SwipeContainer::handleTickEvent().
animateLeftWithButton()
void animateLeftWithButton () private
{
    if (animationCounter <= animationDuration)
    {
        const int16_t delta = EasingEquations::cubicEaseOut(animationCounter, 0, getWidth() + animateDistance, animationDuration);
        dragX = animateDistance - delta;
    }
    else
    {
        // Final step: stop the animation
        currentState = NO_ANIMATION;
        animationCounter = 0;
        dragX = 0;
        pageIndicator.goRight();
    }
    adjustPages();
    animationCounter++;
}
References SwipeContainer::adjustPages(), SwipeContainer::animateDistance, SwipeContainer::animationCounter, SwipeContainer::animationDuration, EasingEquations::cubicEaseOut(), SwipeContainer::currentState, SwipeContainer::dragX, Drawable::getWidth(), SwipeContainer::PageIndicator::goRight(), SwipeContainer::NO_ANIMATION, and SwipeContainer::pageIndicator.
Referenced by SwipeContainer::handleTickEvent().
animateRight()
void animateRight () private
{
    const uint8_t duration = 10;
    if (animationCounter <= duration)
    {
        const int16_t delta = EasingEquations::cubicEaseOut(animationCounter, 0, getWidth() - animateDistance, duration);
        dragX = animateDistance + delta;
    }
    else
    {
        // Final step: stop the animation
        currentState = NO_ANIMATION;
        animationCounter = 0;
        dragX = 0;
        pageIndicator.goLeft();
    }
    adjustPages();
    animationCounter++;
}
References SwipeContainer::adjustPages(), SwipeContainer::animateDistance, SwipeContainer::animationCounter, EasingEquations::cubicEaseOut(), SwipeContainer::currentState, SwipeContainer::dragX, Drawable::getWidth(), SwipeContainer::PageIndicator::goLeft(), SwipeContainer::NO_ANIMATION, and SwipeContainer::pageIndicator.
Referenced by SwipeContainer::handleTickEvent().
animateRightWithButton()
void animateRightWithButton () private
{
    if (animationCounter <= animationDuration)
    {
        const int16_t delta = EasingEquations::cubicEaseOut(animationCounter, 0, getWidth() - animateDistance, animationDuration);
        dragX = animateDistance + delta;
    }
    else
    {
        // Final step: stop the animation
        currentState = NO_ANIMATION;
        animationCounter = 0;
        dragX = 0;
        pageIndicator.goLeft();
    }
    adjustPages();
    animationCounter++;
}
References SwipeContainer::adjustPages(), SwipeContainer::animateDistance, SwipeContainer::animationCounter, SwipeContainer::animationDuration, EasingEquations::cubicEaseOut(), SwipeContainer::currentState, SwipeContainer::dragX, Drawable::getWidth(), SwipeContainer::PageIndicator::goLeft(), SwipeContainer::NO_ANIMATION, and SwipeContainer::pageIndicator.
Referenced by SwipeContainer::handleTickEvent().
animateSwipeCancelledLeft()
void animateSwipeCancelledLeft () private
{
    const uint8_t duration = 14;
    if (animationCounter <= duration)
    {
        const int16_t delta = EasingEquations::backEaseOut(animationCounter, 0, -animateDistance, duration);
        dragX = animateDistance + delta;
        adjustPages();
    }
    else
    {
        // Final step: stop the animation
        currentState = NO_ANIMATION;
        animationCounter = 0;
        dragX = 0;
        adjustPages();
    }
    animationCounter++;
}
References SwipeContainer::adjustPages(), SwipeContainer::animateDistance, SwipeContainer::animationCounter, EasingEquations::backEaseOut(), SwipeContainer::currentState, SwipeContainer::dragX, and SwipeContainer::NO_ANIMATION.
Referenced by SwipeContainer::handleTickEvent().
animateSwipeCancelledRight()
void animateSwipeCancelledRight () private
{
    const uint8_t duration = 14;
    if (animationCounter <= duration)
    {
        const int16_t delta = EasingEquations::backEaseOut(animationCounter, 0, animateDistance, duration);
        dragX = animateDistance - delta;
        adjustPages();
    }
    else
    {
        // Final step: stop the animation
        currentState = NO_ANIMATION;
        animationCounter = 0;
        dragX = 0;
        adjustPages();
    }
    animationCounter++;
}
References SwipeContainer::adjustPages(), SwipeContainer::animateDistance, SwipeContainer::animationCounter, EasingEquations::backEaseOut(), SwipeContainer::currentState, SwipeContainer::dragX, and SwipeContainer::NO_ANIMATION.
Referenced by SwipeContainer::handleTickEvent().
getAnimationDuration()
uint8_t getAnimationDuration () const
Gets the animation duration for swiping with button.
Returns
the animation's duration
See also
setAnimationDuration
{
    return animationDuration;
}
References SwipeContainer::animationDuration.
getNumberOfPages()
uint8_t getNumberOfPages () inline
Gets number of pages.
Returns
The number of pages.
    {
        return pageIndicator.getNumberOfPages();
    }
References SwipeContainer::PageIndicator::getNumberOfPages(), and SwipeContainer::pageIndicator.
Referenced by SwipeContainer::add(), SwipeContainer::goNextPage(), SwipeContainer::handleClickEvent(), SwipeContainer::handleDragEvent(), SwipeContainer::handleGestureEvent(), SwipeContainer::remove(), and SwipeContainer::setSelectedPage().
getSelectedPage()
uint8_t getSelectedPage () const
Gets the currently selected page.
Returns
Zero-based index of the current page. Rage from 0 to numberOfPages-1.
See also
setSelectedPage
{
    return pageIndicator.getCurrentPage();
}
References SwipeContainer::PageIndicator::getCurrentPage(), and SwipeContainer::pageIndicator.
Referenced by SwipeContainer::add(), SwipeContainer::adjustPages(), SwipeContainer::goNextPage(), SwipeContainer::goPreviousPage(), SwipeContainer::handleClickEvent(), SwipeContainer::handleDragEvent(), SwipeContainer::handleGestureEvent(), and SwipeContainer::remove().
goNextPage()
void goNextPage (uint8_t duration = 20)
Go to next page with animation
Parameters
duration duration of the swiping animation when using button.
Note
next page selected
{
    animationDuration = duration;
    if (getSelectedPage() < getNumberOfPages() - 1)
    {
        currentState = ANIMATE_LEFT_WITH_BUTTON;
    }
}
References SwipeContainer::ANIMATE_LEFT_WITH_BUTTON, SwipeContainer::animationDuration, SwipeContainer::currentState, SwipeContainer::getNumberOfPages(), and SwipeContainer::getSelectedPage().
goPreviousPage()
void goPreviousPage (uint8_t duration = 20)
Go to previous page with animation
Parameters
duration duration of the swiping animation when using button.
Note
previous page selected
{
    animationDuration = duration;
    if (getSelectedPage() > 0)
    {
        currentState = ANIMATE_RIGHT_WITH_BUTTON;
    }
}
References SwipeContainer::ANIMATE_RIGHT_WITH_BUTTON, SwipeContainer::animationDuration, SwipeContainer::currentState, and SwipeContainer::getSelectedPage().
handleClickEvent()
void handleClickEvent (const ClickEvent & event) virtual
Defines the event handler interface for ClickEvents. The default implementation ignores the event. The event is only received if the Drawable is touchable and visible.
Parameters
event The ClickEvent received from the HAL.
Reimplemented from Drawable.
{
    // If an animation is already in progress do not
    // react to clicks
    if (currentState != NO_ANIMATION)
    {
        return;
    }
    if (event.getType() == ClickEvent::RELEASED)
    {
        // Save current position for use during animation
        animateDistance = dragX;
        startX = pages.getX();
        const uint8_t curPage = getSelectedPage();
        if (dragX < 0)
        {
            if (curPage == getNumberOfPages() - 1 || dragX > -swipeCutoff)
            {
                currentState = ANIMATE_SWIPE_CANCELLED_LEFT;
            }
            else
            {
                currentState = ANIMATE_LEFT;
            }
        }
        else if (dragX > 0)
        {
            if (curPage == 0 || dragX < swipeCutoff)
            {
                currentState = ANIMATE_SWIPE_CANCELLED_RIGHT;
            }
            else
            {
                currentState = ANIMATE_RIGHT;
            }
        }
    }
}
References SwipeContainer::ANIMATE_LEFT, SwipeContainer::ANIMATE_RIGHT, SwipeContainer::ANIMATE_SWIPE_CANCELLED_LEFT, SwipeContainer::ANIMATE_SWIPE_CANCELLED_RIGHT, SwipeContainer::animateDistance, SwipeContainer::currentState, SwipeContainer::dragX, SwipeContainer::getNumberOfPages(), SwipeContainer::getSelectedPage(), Drawable::getX(), SwipeContainer::NO_ANIMATION, SwipeContainer::pages, ClickEvent::RELEASED, SwipeContainer::startX, and SwipeContainer::swipeCutoff.
handleDragEvent()
void handleDragEvent (const DragEvent & event) virtual
Defines the event handler interface for DragEvents. The default implementation ignores the event. The event is only received if the drawable is touchable and visible.
Parameters
event The DragEvent received from the HAL.
Reimplemented from Drawable.
{
    // If an animation is already in progress do not
    // react to drags
    if (currentState != NO_ANIMATION)
    {
        return;
    }
    dragX += event.getDeltaX();
    // Do not show too much background next to end pages
    const uint8_t curPage = getSelectedPage();
    if (curPage == 0 && dragX > endElasticWidth)
    {
        dragX = static_cast<int16_t>(endElasticWidth);
    }
    else if (curPage == getNumberOfPages() - 1 && dragX < -endElasticWidth)
    {
        dragX = -static_cast<int16_t>(endElasticWidth);
    }
    adjustPages();
}
References SwipeContainer::adjustPages(), SwipeContainer::currentState, SwipeContainer::dragX, SwipeContainer::endElasticWidth, SwipeContainer::getNumberOfPages(), SwipeContainer::getSelectedPage(), and SwipeContainer::NO_ANIMATION.
handleGestureEvent()
void handleGestureEvent (const GestureEvent & event) virtual
Defines the event handler interface for GestureEvents. The default implementation ignores the event. The event is only received if the Drawable is touchable and visible.
Parameters
event The GestureEvent received from the HAL.
Reimplemented from Drawable.
{
    // Do not accept gestures while animating
    if (currentState != NO_ANIMATION)
    {
        return;
    }
    if (event.getType() == GestureEvent::SWIPE_HORIZONTAL)
    {
        // Save current position for use during animation
        animateDistance = dragX;
        startX = pages.getX();
        const uint8_t curPage = getSelectedPage();
        if (event.getVelocity() < 0 && curPage < getNumberOfPages() - 1)
        {
            currentState = ANIMATE_LEFT;
        }
        else if (event.getVelocity() > 0 && curPage > 0)
        {
            currentState = ANIMATE_RIGHT;
        }
    }
}
References SwipeContainer::ANIMATE_LEFT, SwipeContainer::ANIMATE_RIGHT, SwipeContainer::animateDistance, SwipeContainer::currentState, SwipeContainer::dragX, SwipeContainer::getNumberOfPages(), SwipeContainer::getSelectedPage(), Drawable::getX(), SwipeContainer::NO_ANIMATION, SwipeContainer::pages, SwipeContainer::startX, and GestureEvent::SWIPE_HORIZONTAL.
handleTickEvent()
void handleTickEvent () virtual
Called periodically by the framework if the Drawable instance has subscribed to timer ticks.
See also
Application::registerTimerWidget
Reimplemented from Drawable.
{
    if (currentState == ANIMATE_SWIPE_CANCELLED_LEFT)
    {
        animateSwipeCancelledLeft();
    }
    else if (currentState == ANIMATE_SWIPE_CANCELLED_RIGHT)
    {
        animateSwipeCancelledRight();
    }
    else if (currentState == ANIMATE_LEFT)
    {
        animateLeft();
    }
    else if (currentState == ANIMATE_RIGHT)
    {
        animateRight();
    }
    else if (currentState == ANIMATE_LEFT_WITH_BUTTON)
    {
        animateLeftWithButton();
    }
    else if (currentState == ANIMATE_RIGHT_WITH_BUTTON)
    {
        animateRightWithButton();
    }
}
References SwipeContainer::ANIMATE_LEFT, SwipeContainer::ANIMATE_LEFT_WITH_BUTTON, SwipeContainer::ANIMATE_RIGHT, SwipeContainer::ANIMATE_RIGHT_WITH_BUTTON, SwipeContainer::ANIMATE_SWIPE_CANCELLED_LEFT, SwipeContainer::ANIMATE_SWIPE_CANCELLED_RIGHT, SwipeContainer::animateLeft(), SwipeContainer::animateLeftWithButton(), SwipeContainer::animateRight(), SwipeContainer::animateRightWithButton(), SwipeContainer::animateSwipeCancelledLeft(), SwipeContainer::animateSwipeCancelledRight(), and SwipeContainer::currentState.
remove()
void remove (Drawable & page) virtual
Removes the page from the container.
Parameters
[in] page The page to remove.
Note
This is safe to call even if page is not a page (in which case nothing happens).
Reimplemented from Container.
{
    Drawable* tmp = pages.getFirstChild();
    if (pageIndicator.getNumberOfPages() == 0)
    {
        return;
    }
    // looks for the child matching page
    // to ensure that the page indicator only counts down if a page is removed
    while (tmp)
    {
        if (tmp == &page)
        {
            pages.remove(page);
            pageIndicator.setNumberOfPages(getNumberOfPages() - 1);
            const uint8_t numPages = getNumberOfPages();
            if (numPages == 0)
            {
                invalidate();
                setWidthHeight(0, 0);
            }
            else
            {
                const uint8_t curPage = getSelectedPage();
                setSelectedPage(MIN(curPage, numPages - 1));
            }
            return;
        }
        else
        {
            tmp = tmp->getNextSibling();
        }
    }
}
References Container::getFirstChild(), SwipeContainer::getNumberOfPages(), SwipeContainer::PageIndicator::getNumberOfPages(), SwipeContainer::getSelectedPage(), Drawable::invalidate(), MIN, SwipeContainer::pageIndicator, SwipeContainer::pages, ListLayout::remove(), SwipeContainer::PageIndicator::setNumberOfPages(), SwipeContainer::setSelectedPage(), and Drawable::setWidthHeight().
setAnimationDuration()
void setAnimationDuration (uint8_t newDuration)
Sets the animation duration for swiping with button.
Parameters
newDuration duration of the swiping animation when using button.
See also
getAnimationDuration
{
    animationDuration = newDuration > 0 ? newDuration : 0;
}
References SwipeContainer::animationDuration.
setEndSwipeElasticWidth()
void setEndSwipeElasticWidth (uint16_t width)
When dragging either one of the end pages a part of the background will become visible until the user stop dragging and the end page swipes back to its position. The width of this area is set by this method.
Parameters
width The width in pixels.
{
    endElasticWidth = width;
}
References SwipeContainer::endElasticWidth.
setPageIndicatorBitmaps()
void setPageIndicatorBitmaps (const Bitmap & normalPage, const Bitmap & highlightedPage)
Sets the bitmaps that are used by the page indicator. The bitmap for the normal page is repeated side-by-side and the bitmap for a highlighted page is put in the proper position.
Parameters
normalPage The normal page.
highlightedPage The highlighted page.
{
    pageIndicator.setBitmaps(normalPage, highlightedPage);
}
References SwipeContainer::pageIndicator, and SwipeContainer::PageIndicator::setBitmaps().
setPageIndicatorCenteredX() [1/2]
void setPageIndicatorCenteredX ()
Sets the page indicator centered inside the SwipeContainer without changing the y position.
See also
setPageIndicatorXYWithCenteredX, setPageIndicatorXY
Note
This method should not be used until all pages have been added, the setPageIndicatorBitmaps() has been called and the page indicator therefore has the correct width.
{
    setPageIndicatorCenteredX(getWidth() / 2);
}
References Drawable::getWidth(), and SwipeContainer::setPageIndicatorCenteredX().
Referenced by SwipeContainer::setPageIndicatorCenteredX(), and SwipeContainer::setPageIndicatorXYWithCenteredX().
setPageIndicatorCenteredX() [2/2]
void setPageIndicatorCenteredX (int16_t x)
Sets the x position of the page indicator without changing the y position. The value specified as x will be the center coordinate of the page indicators.
Parameters
x The center x coordinate.
See also
setPageIndicatorXYWithCenteredX, setPageIndicatorXY
Note
This method should not be used until all pages have been added, the setPageIndicatorBitmaps() has been called and the page indicator therefore has the correct width.
{
    pageIndicator.setX(x - pageIndicator.getWidth() / 2);
}
References Drawable::getWidth(), SwipeContainer::pageIndicator, and Drawable::setX().
setPageIndicatorXY()
void setPageIndicatorXY (int16_t x, int16_t y)
Sets the x and y position of the page indicator.
Parameters
x The x coordinate.
y The y coordinate.
See also
setPageIndicatorXYWithCenteredX, setPageIndicatorCenteredX
{
    pageIndicator.setXY(x, y);
}
References SwipeContainer::pageIndicator, and Drawable::setXY().
setPageIndicatorXYWithCenteredX()
void setPageIndicatorXYWithCenteredX (int16_t x, int16_t y)
Sets the x and y position of the page indicator. The value specified as x will be the center coordinate of the page indicators.
Parameters
x The center x coordinate.
y The y coordinate.
See also
setPageIndicatorCenteredX, setPageIndicatorXY
Note
This method should not be used until all pages have been added, the setPageIndicatorBitmaps() has been called and the page indicator therefore has the correct width.
{
    setPageIndicatorCenteredX(x);
    pageIndicator.setY(y);
}
References SwipeContainer::pageIndicator, SwipeContainer::setPageIndicatorCenteredX(), and Drawable::setY().
setSelectedPage()
void setSelectedPage (uint8_t pageIndex)
Sets the selected page.
Parameters
pageIndex Zero-based index of the page. Range from 0 to numberOfPages-1.
See also
getSelectedPage
{
    if (pageIndex < getNumberOfPages())
    {
        pageIndicator.setCurrentPage(pageIndex);
        adjustPages();
    }
}
References SwipeContainer::adjustPages(), SwipeContainer::getNumberOfPages(), SwipeContainer::pageIndicator, and SwipeContainer::PageIndicator::setCurrentPage().
Referenced by SwipeContainer::add(), and SwipeContainer::remove().
setSwipeCutoff()
void setSwipeCutoff (uint16_t cutoff) virtual
Set the swipe cutoff which indicates how far you should drag a page before it results in a page change.
Parameters
cutoff The cutoff in pixels.
{
    swipeCutoff = cutoff;
}
References SwipeContainer::swipeCutoff.
Member Data Documentation
animateDistance
int16_t animateDistance private
Referenced by SwipeContainer::animateLeft(), SwipeContainer::animateLeftWithButton(), SwipeContainer::animateRight(), SwipeContainer::animateRightWithButton(), SwipeContainer::animateSwipeCancelledLeft(), SwipeContainer::animateSwipeCancelledRight(), SwipeContainer::handleClickEvent(), and SwipeContainer::handleGestureEvent().
animationCounter
uint8_t animationCounter private
Referenced by SwipeContainer::animateLeft(), SwipeContainer::animateLeftWithButton(), SwipeContainer::animateRight(), SwipeContainer::animateRightWithButton(), SwipeContainer::animateSwipeCancelledLeft(), and SwipeContainer::animateSwipeCancelledRight().
animationDuration
uint8_t animationDuration private
Referenced by SwipeContainer::animateLeftWithButton(), SwipeContainer::animateRightWithButton(), SwipeContainer::getAnimationDuration(), SwipeContainer::goNextPage(), SwipeContainer::goPreviousPage(), and SwipeContainer::setAnimationDuration().
currentState
enum touchgfx::SwipeContainer::States currentState private
Referenced by SwipeContainer::animateLeft(), SwipeContainer::animateLeftWithButton(), SwipeContainer::animateRight(), SwipeContainer::animateRightWithButton(), SwipeContainer::animateSwipeCancelledLeft(), SwipeContainer::animateSwipeCancelledRight(), SwipeContainer::goNextPage(), SwipeContainer::goPreviousPage(), SwipeContainer::handleClickEvent(), SwipeContainer::handleDragEvent(), SwipeContainer::handleGestureEvent(), and SwipeContainer::handleTickEvent().
DRAG_CANCEL_THRESHOLD
const int16_t DRAG_CANCEL_THRESHOLD = 3 static private
dragX
int16_t dragX private
Referenced by SwipeContainer::adjustPages(), SwipeContainer::animateLeft(), SwipeContainer::animateLeftWithButton(), SwipeContainer::animateRight(), SwipeContainer::animateRightWithButton(), SwipeContainer::animateSwipeCancelledLeft(), SwipeContainer::animateSwipeCancelledRight(), SwipeContainer::handleClickEvent(), SwipeContainer::handleDragEvent(), and SwipeContainer::handleGestureEvent().
endElasticWidth
uint16_t endElasticWidth private
Referenced by SwipeContainer::handleDragEvent(), and SwipeContainer::setEndSwipeElasticWidth().
pageIndicator
touchgfx::SwipeContainer::PageIndicator pageIndicator private
Referenced by SwipeContainer::SwipeContainer(), SwipeContainer::add(), SwipeContainer::animateLeft(), SwipeContainer::animateLeftWithButton(), SwipeContainer::animateRight(), SwipeContainer::animateRightWithButton(), SwipeContainer::getNumberOfPages(), SwipeContainer::getSelectedPage(), SwipeContainer::remove(), SwipeContainer::setPageIndicatorBitmaps(), SwipeContainer::setPageIndicatorCenteredX(), SwipeContainer::setPageIndicatorXY(), SwipeContainer::setPageIndicatorXYWithCenteredX(), and SwipeContainer::setSelectedPage().
pages
ListLayout pages private
Referenced by SwipeContainer::SwipeContainer(), SwipeContainer::add(), SwipeContainer::adjustPages(), SwipeContainer::handleClickEvent(), SwipeContainer::handleGestureEvent(), and SwipeContainer::remove().
startX
int16_t startX private
Referenced by SwipeContainer::handleClickEvent(), and SwipeContainer::handleGestureEvent().
swipeCutoff
uint16_t swipeCutoff private
Referenced by SwipeContainer::handleClickEvent(), and SwipeContainer::setSwipeCutoff().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/SwipeContainer.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/SwipeContainer.cpp