Battery Simulator Documentation: AbstractPartition
AbstractPartition abstract
#include "AbstractPartition.hpp"
Public Member Functions
virtual ~AbstractPartition ()
template<typename T >
void * allocate ()
virtual void * allocate (uint16_t size)
template<typename T >
void * allocateAt (uint16_t index)
virtual void * allocateAt (uint16_t index, uint16_t size)
template<typename T >
T & at (const uint16_t index)
template<typename T >
const T & at (const uint16_t index) const
virtual uint16_t capacity () const =0
virtual void clear ()
void dec ()
virtual uint32_t element_size ()=0
template<class T >
Pair< T *, uint16_t > find (const void *pT)
virtual uint16_t getAllocationCount () const
virtual uint16_t indexOf (const void *address)
Protected Member Functions
AbstractPartition ()
virtual const void * element (uint16_t index) const =0
virtual void * element (uint16_t index)=0
Private Attributes
uint16_t allocations
Detailed Description
This type defines an abstract interface to a storage partition for allocating memory slots of equal size. The "partition" is not aware of the actual types stored in the partition memory, hence it provides no mechanism for deleting C++ objects when clear()'ed.
Constructor & Destructor Documentation
~AbstractPartition()
virtual ~AbstractPartition () virtual
Finalizes an instance of the AbstractPartition class.
AbstractPartition()
AbstractPartition () protected
Initializes a new instance of the AbstractPartition class.
Member Function Documentation
allocate() [1/2]
template<typename T > void * allocate () inline
Gets the address of the next available storage slot. The slot size is determined from the size of type T.
Template Parameters
T Generic type parameter.
Returns
The address of an empty storage slot.
Note
Asserts if T is too large, or the storage is depleted.
    {
        return allocate(static_cast<uint16_t>(sizeof(T)));
    }
References AbstractPartition::allocate().
Referenced by AbstractPartition::allocate().
allocate() [2/2]
virtual void * allocate (uint16_t size) virtual
Gets the address of the next available storage slot. The slot size is compared with the specified size.
Parameters
size The size.
Returns
The address of an empty storage slot which contains minimum 'size' bytes.
Note
Asserts if 'size' is too large, or the storage is depleted.
allocateAt() [1/2]
template<typename T > void * allocateAt (uint16_t index) inline
Gets the address of the specified storage slot. The slot size is determined from the size of type T.
Template Parameters
T Generic type parameter.
Parameters
index Zero-based index of the.
Returns
The address of the appropriate storage slot.
Note
Asserts if T is too large.
    {
        return allocateAt(index, static_cast<uint16_t>(sizeof(T)));
    }
References AbstractPartition::allocateAt().
allocateAt() [2/2]
virtual void * allocateAt (uint16_t index, uint16_t size) virtual
Gets the address of the specified index.
Parameters
index Zero-based index of the.
size The size.
Returns
The address of the appropriate storage slot which contains minimum 'size' bytes.
Note
Asserts if 'size' is too large.
Referenced by AbstractPartition::allocateAt().
at() [1/2]
template<typename T > T & at (const uint16_t index) inline
Gets the object at the specified index.
Template Parameters
T Generic type parameter.
Parameters
index The index into the Partition storage where the returned object is located.
Returns
A typed reference to the object at the specified index.
    {
        return *static_cast<T*>(element(index));
    }
References AbstractPartition::element().
at() [2/2]
template<typename T > const T & at (const uint16_t index) const inline
const version of at().
Template Parameters
T Generic type parameter.
Parameters
index Zero-based index of the.
Returns
A T&
    {
        return *static_cast<const T*>(element(index));
    }
References AbstractPartition::element().
capacity()
virtual uint16_t capacity () const pure virtual
Gets the capacity, i.e. the maximum allocation count.
Returns
The maximum allocation count.
Implemented in Partition< touchgfx::meta::TypeList, 1 >, and Partition< ListOfTypes, NUMBER_OF_ELEMENTS >.
clear()
virtual void clear () virtual
Prepares the Partition for new allocations. Any objects present in the Partition shall not be used after invoking this method.
dec()
void dec () inline
Decreases number of allocations.
    {
        if (allocations)
        {
            allocations--;
        }
    }
References AbstractPartition::allocations.
element() [1/2]
virtual const void * element (uint16_t index) const protected pure virtual
Access to stored element, const version.
Parameters
index Zero-based index of the.
Returns
null if it fails, else a void*.
Implemented in Partition< touchgfx::meta::TypeList, 1 >, and Partition< ListOfTypes, NUMBER_OF_ELEMENTS >.
element() [2/2]
virtual void * element (uint16_t index) protected pure virtual
Access to stored element. Used internally.
Parameters
index Zero-based index of the.
Returns
null if it fails, else a void*.
Implemented in Partition< touchgfx::meta::TypeList, 1 >, and Partition< ListOfTypes, NUMBER_OF_ELEMENTS >.
Referenced by AbstractPartition::at(), and AbstractPartition::at().
element_size()
virtual uint32_t element_size () pure virtual
Access to concrete element-size. Used internally.
Returns
An uint32_t.
Implemented in Partition< touchgfx::meta::TypeList, 1 >, and Partition< ListOfTypes, NUMBER_OF_ELEMENTS >.
find()
template<class T > Pair< T *, uint16_t > find (const void * pT) inline
Determines if the specified object could have been previously allocated in the partition. Since the Partition concept is loosely typed this method shall be used with care. The method does not guarantee that the found object at the returned index is a valid object. It only tests whether or not the object is within the bounds of the current partition allocations.
Template Parameters
T Generic type parameter.
Parameters
pT Pointer to the object to look up.
Returns
If the object seems to be allocated in the Partition, a Pair object containing a typed pointer to the object and an index into the Partition storage is returned. Otherwise, a Pair<0, 0> is returned.
    {
        uint16_t index = indexOf(pT);
        if (0 < getAllocationCount() && index < getAllocationCount())
        {
            return Pair<T*, uint16_t>(&at<T>(index), index);
        }
        return Pair<T*, uint16_t>(0, (uint16_t)-1);
    }
References AbstractPartition::getAllocationCount(), and AbstractPartition::indexOf().
getAllocationCount()
virtual uint16_t getAllocationCount () const virtual
Gets allocation count.
Returns
The currently allocated storage slots.
Referenced by AbstractPartition::find().
indexOf()
virtual uint16_t indexOf (const void * address) virtual
Determines index of previously allocated location. Since the Partition concept is loosely typed this method shall be used with care. The method does not guarantee that the found object at the returned index is a valid object. It only tests whether or not the object is within the bounds of the current partition allocations.
Parameters
address The location address to lookup.
Returns
An uint16_t.
Referenced by AbstractPartition::find().
Member Data Documentation
allocations
uint16_t allocations private
Referenced by AbstractPartition::dec().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/common/AbstractPartition.hpp