Battery Simulator Documentation: GraphElementVerticalGapLine
GraphElementVerticalGapLine
#include "GraphElements.hpp"
Public Member Functions
virtual void draw (const Rect &invalidatedArea) const
FORCE_INLINE_FUNCTION uint16_t getGapLineWidth () const
virtual void invalidateGraphPointAt (int16_t index)
FORCE_INLINE_FUNCTION void setGapLineWidth (uint16_t width)
Public Member Functions inherited from AbstractGraphElementNoCWR
AbstractGraphElementNoCWR ()
virtual bool drawCanvasWidget (const Rect &) const
virtual colortype getColor () const
virtual void setColor (colortype newColor)
Public Member Functions inherited from AbstractGraphElement
AbstractGraphElement ()
Public Member Functions inherited from CanvasWidget
CanvasWidget ()
virtual uint8_t getAlpha () const
virtual Rect getMinimalRect () const
const AbstractPainter * getPainter () const
virtual Rect getSolidRect () const
virtual void invalidate () const
virtual void setAlpha (uint8_t newAlpha)
void setPainter (const AbstractPainter &painter)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
uint16_t lineWidth
Width of the line.
Protected Attributes inherited from AbstractGraphElementNoCWR
colortype color
The currently assigned color.
Protected Attributes inherited from CanvasWidget
uint8_t alpha
The Alpha for this CanvasWidget.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Private Member Functions
void invalidateIndex (const AbstractDataGraph *graph, int16_t index) const
Additional Inherited Members
Protected Member Functions inherited from AbstractGraphElementNoCWR
void normalizeRect (Rect &r) const
Protected Member Functions inherited from AbstractGraphElement
FORCE_INLINE_FUNCTION int convertToGraphScaleX (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION int convertToGraphScaleY (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION AbstractDataGraph * getGraph () const
FORCE_INLINE_FUNCTION int getIndexToXAxis (const AbstractDataGraph *graph, const int valueScaled, const int labelScaled) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenXQ5 (const AbstractDataGraph *graph, int16_t index) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenYQ5 (const AbstractDataGraph *graph, int16_t index) const
bool isCenterInvisible (const AbstractDataGraph *graph, int16_t index) const
Rect rectAround (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5, CWRUtil::Q5 diameterQ5) const
Rect rectFromQ5Coordinates (CWRUtil::Q5 screenXminQ5, CWRUtil::Q5 screenYminQ5, CWRUtil::Q5 screenXmaxQ5, CWRUtil::Q5 screenYmaxQ5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 roundQ5 (CWRUtil::Q5 q5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenXQ5 (const AbstractDataGraph *graph, int x) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenYQ5 (const AbstractDataGraph *graph, int y) const
FORCE_INLINE_FUNCTION bool xScreenRangeToIndexRange (const AbstractDataGraph *graph, int16_t xMin, int16_t xMax, int16_t &indexMin, int16_t &indexMax) const
Detailed Description
The GraphElementVerticalGapLine is used to draw a vertical line where the gap in the graph is. This only makes sense to add to a GraphWrapAndOverwrite (or GraphWrapAndOverwriteData).
Note
The vertical line is drawn using LCD::fillRect for higher performance.
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draws the given invalidated area. If the underlying CanvasWidgetRenderer fail to render the widget (if the widget is too complex), the invalidated area is cut into smaller slices (horizontally) which are then drawn separately. If drawing a single raster line fails, that line is considered too complex and skipped (it is left blank/transparent) and drawing continues on the next raster line.
If drawing has failed at least once, which means that the number of horizontal lines draw has been reduced, the number of successfully drawn horizontal lines is remembered for the next invocation of draw(). A future call to draw() would then start off with the reduced number of horizontal lines to prevent potentially drawing the canvas widget in vain, as happened previously in draw().
Parameters
invalidatedArea The invalidated area.
See also
drawCanvasWidget
Note
Subclasses of CanvasWidget should implement drawCanvasWidget(), not draw().
The term "too complex" means that the size of the buffer (assigned to CanvasWidgetRenderer using CanvasWidgetRenderer::setupBuffer()) is too small.
Reimplemented from CanvasWidget.
{
    const AbstractDataGraph* graph = getGraph();
    const int16_t gapIndex = graph->getGapBeforeIndex();
    const uint8_t a = LCD::div255(getAlpha() * graph->getAlpha());
    if (gapIndex == 0 || a == 0)
    {
        return;
    }
    const int16_t screenXmin = indexToScreenXQ5(graph, gapIndex - 1).round();
    int16_t screenXmax = screenXmin + lineWidth;
    if (lineWidth == 0)
    {
        screenXmax = indexToScreenXQ5(graph, gapIndex).round();
    }
    Rect r(screenXmin, graph->getGraphAreaPaddingTop(), screenXmax - screenXmin, graph->getGraphAreaHeight());
    normalizeRect(r);
    r &= invalidatedArea;
    if (!r.isEmpty())
    {
        translateRectToAbsolute(r);
        HAL::lcd().fillRect(r, color, a);
    }
}
References LCD::div255(), CanvasWidget::getAlpha(), AbstractGraphElement::getGraph(), AbstractGraphElement::indexToScreenXQ5(), HAL::lcd(), GraphElementVerticalGapLine::lineWidth, AbstractGraphElementNoCWR::normalizeRect(), CWRUtil::Q5::round(), and Drawable::translateRectToAbsolute().
getGapLineWidth()
FORCE_INLINE_FUNCTION uint16_t getGapLineWidth () const inline
Gets the width of the gap line as set using setGapLineWidth().
Returns
The gap line width.
    {
        return lineWidth;
    }
References GraphElementVerticalGapLine::lineWidth.
invalidateGraphPointAt()
void invalidateGraphPointAt (int16_t index) virtual
Invalidate the point at the given index. This allows a graph element to only invalidate the minimum rectangle required for the given index. The Graph will call this function before and after changing a point to ensure that both the old and the new area are redrawn (invalidated).
Parameters
index Zero-based index of the point.
Implements AbstractGraphElement.
{
    const AbstractDataGraph* graph = getGraph();
    invalidateIndex(graph, graph->getGapBeforeIndex());
    invalidateIndex(graph, index);
}
References AbstractGraphElement::getGraph(), and GraphElementVerticalGapLine::invalidateIndex().
invalidateIndex()
void invalidateIndex (const AbstractDataGraph * graph, int16_t index) const private
{
    if (index > 0)
    {
        const int16_t screenXmin = indexToScreenXQ5(graph, index - 1).round();
        int16_t screenXmax = screenXmin + lineWidth;
        if (lineWidth == 0)
        {
            screenXmax = indexToScreenXQ5(graph, index).round();
        }
        Rect dirty(screenXmin, graph->getGraphAreaPaddingTop(), screenXmax - screenXmin, graph->getGraphAreaHeight());
        normalizeRect(dirty);
        invalidateRect(dirty);
    }
}
References touchgfx::dirty, AbstractGraphElement::indexToScreenXQ5(), Drawable::invalidateRect(), GraphElementVerticalGapLine::lineWidth, AbstractGraphElementNoCWR::normalizeRect(), and CWRUtil::Q5::round().
Referenced by GraphElementVerticalGapLine::invalidateGraphPointAt().
setGapLineWidth()
FORCE_INLINE_FUNCTION void setGapLineWidth (uint16_t width) inline
Sets the width of the gap line in pixels. If the gap line is set to 0 the gap line will extend to the next point in the graph.
Parameters
width The width.
See also
getGapLineWidth
    {
        lineWidth = width;
    }
References GraphElementVerticalGapLine::lineWidth.
Member Data Documentation
lineWidth
uint16_t lineWidth protected
Width of the line.
Referenced by GraphElementVerticalGapLine::draw(), GraphElementVerticalGapLine::getGapLineWidth(), GraphElementVerticalGapLine::invalidateIndex(), and GraphElementVerticalGapLine::setGapLineWidth().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/graph/GraphElements.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph/GraphElements.cpp