Battery Simulator Documentation: AbstractPainter
AbstractPainter abstract
#include "AbstractPainter.hpp"
Public Member Functions
AbstractPainter ()
virtual ~AbstractPainter ()
void framebufferToDisplay (int16_t &widgetX, int16_t &widgetY) const
virtual HAL::RenderingMethod getRenderingMethod () const
virtual void paint (uint8_t *destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const =0
virtual bool setup (const Rect &widgetRect) const
virtual void tearDown () const
Static Protected Member Functions
static FORCE_INLINE_FUNCTION bool compatibleFramebuffer (Bitmap::BitmapFormat format)
Protected Attributes
int16_t widgetWidth
The width of the widget on screen, used by framebufferToDisplay()
Detailed Description
An abstract class for creating painter classes for drawing canvas widgets. All canvas widgets need a painter to fill the shape drawn with a CanvasWidgetRenderer. The painter must provide the color of a pixel on a given coordinate, which will the be blended into the framebuffer depending on the position of the canvas widget and the transparency of the given pixel.
The AbstractPainter also implements a function which will blend each pixel in a scanline snippet into the framebuffer, but for better performance, the function should be reimplemented in each painter.
Constructor & Destructor Documentation
AbstractPainter()
AbstractPainter () inline
Initializes a new instance of the AbstractPainter class.
        : widgetWidth(0)
    {
    }
~AbstractPainter()
virtual ~AbstractPainter () inline virtual
Finalizes an instance of the AbstractPainter class.
    {
    }
Member Function Documentation
compatibleFramebuffer()
static FORCE_INLINE_FUNCTION bool compatibleFramebuffer (Bitmap::BitmapFormat format) inline static protected
Helper function to check if the provided bitmap format matches the current framebuffer format.
Parameters
format A bitmap format.
Returns
True if the format matches the framebuffer format, false otherwise.
    {
        bool compat = HAL::lcd().framebufferFormat() == format;
        if (HAL::getInstance()->getAuxiliaryLCD())
        {
            compat |= HAL::getInstance()->getAuxiliaryLCD()->framebufferFormat() == format;
        }
        return compat;
    }
References HAL::getInstance(), and HAL::lcd().
Referenced by AbstractPainterABGR2222::AbstractPainterABGR2222(), AbstractPainterARGB2222::AbstractPainterARGB2222(), AbstractPainterARGB8888::AbstractPainterARGB8888(), AbstractPainterBGRA2222::AbstractPainterBGRA2222(), AbstractPainterBW::AbstractPainterBW(), AbstractPainterGRAY2::AbstractPainterGRAY2(), AbstractPainterGRAY4::AbstractPainterGRAY4(), AbstractPainterRGB565::AbstractPainterRGB565(), AbstractPainterRGB888::AbstractPainterRGB888(), and AbstractPainterRGBA2222::AbstractPainterRGBA2222().
framebufferToDisplay()
void framebufferToDisplay (int16_t & widgetX, int16_t & widgetY) const inline
Convert Framebuffer widget coordinates to display widget coordinates. This is handy when creating a custom painter and the X,Y is needed in the same coordinate system as the widget on the display.
Parameters
[in,out] widgetX The widget x coordinate.
[in,out] widgetY The widget y coordinate.
See also
AbstractPainter::paint
    {
        if (HAL::DISPLAY_ROTATION == rotate0)
        {
            return;
        }
        const int16_t tmpX = widgetX;
        widgetX = (widgetWidth - 1) - widgetY;
        widgetY = tmpX;
    }
References HAL::DISPLAY_ROTATION, touchgfx::rotate0, and AbstractPainter::widgetWidth.
getRenderingMethod()
virtual HAL::RenderingMethod getRenderingMethod () const inline virtual
Return the applicable rendering method of the painter. HARDWARE if the painter uses hardware based drawing, SOFTWARE otherwise. Relevant on platforms using DCACHE.
Returns
HARDWARE if painter uses hardware based drawing, SOFTWARE otherwise.
Reimplemented in PainterRGB565, PainterRGB565Bitmap, PainterRGB565L8Bitmap, PainterRGB888, PainterRGB888Bitmap, and PainterRGB888L8Bitmap.
    {
        return HAL::SOFTWARE;
    }
References HAL::SOFTWARE.
paint()
virtual void paint (uint8_t * destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const pure virtual
Paints a streak of pixels (all with the same alpha) in the framebuffer. The first pixel to paint is at 'offset' relative to 'destination' (to be able to support 1bpp, 2bpp and 4bpp). The first pixel to paint is at the given 'widgetX', 'widgetY' coordinate. The number of pixels to paint is 'count' and the alpha to apply is 'alpha'.
Note that the widgetX, widgetY is relative to the widget in the framebuffer, not the display. To convert the coordinate to display widget coordinates, use framebufferToDisplay().
Parameters
[in] destination If non-null, the pointer.
offset The offset to add to the destination.
widgetX The widget x coordinate.
widgetY The widget y coordinate.
count Number of pixels.
alpha The alpha of the pixels.
See also
AbstractPainter::setup, AbstractPainter::tearDown, AbstractPainter::framebufferToDisplay
Implemented in PainterABGR2222, PainterABGR2222Bitmap, PainterARGB2222, PainterARGB2222Bitmap, PainterARGB8888, PainterARGB8888Bitmap, PainterARGB8888L8Bitmap, PainterARGB8888LinearGradient, PainterBGRA2222, PainterBGRA2222Bitmap, PainterBW, PainterBWBitmap, PainterGRAY2, PainterGRAY2Bitmap, PainterGRAY4, PainterGRAY4Bitmap, PainterRGB565, PainterRGB565Bitmap, PainterRGB565L8Bitmap, PainterRGB565LinearGradient, PainterRGB888, PainterRGB888Bitmap, PainterRGB888L8Bitmap, PainterRGB888LinearGradient, PainterRGBA2222, PainterRGBA2222Bitmap, PainterXRGB8888, PainterXRGB8888Bitmap, and PainterXRGB8888L8Bitmap.
setup()
virtual bool setup (const Rect & widgetRect) const inline virtual
This function is called before any actual paint operation is started. This allows the painter to initialize variables and optional dma queues. This happens before the first scan line segment is being drawn. If the painter is unable to draw, e.g. no bitmap assigned to a bitmap painter, 'false' should be returned.
Parameters
widgetRect The widget rectangle.
Returns
True if the painter is ready to paint, false otherwise.
See also
AbstractPainter::paint, AbstractPainter::tearDown
Reimplemented in PainterABGR2222Bitmap, PainterARGB2222Bitmap, PainterARGB8888Bitmap, PainterARGB8888L8Bitmap, PainterBGRA2222Bitmap, PainterBWBitmap, PainterGRAY2Bitmap, PainterGRAY4Bitmap, PainterRGB565Bitmap, PainterRGB565L8Bitmap, PainterRGB888Bitmap, PainterRGB888L8Bitmap, PainterRGBA2222Bitmap, PainterXRGB8888Bitmap, and PainterXRGB8888L8Bitmap.
    {
        widgetWidth = widgetRect.width;
        return true;
    }
References AbstractPainter::widgetWidth.
Referenced by PainterABGR2222Bitmap::setup(), PainterARGB2222Bitmap::setup(), PainterARGB8888Bitmap::setup(), PainterARGB8888L8Bitmap::setup(), PainterBGRA2222Bitmap::setup(), PainterBWBitmap::setup(), PainterGRAY2Bitmap::setup(), PainterGRAY4Bitmap::setup(), PainterRGB565Bitmap::setup(), PainterRGB565L8Bitmap::setup(), PainterRGB888Bitmap::setup(), PainterRGB888L8Bitmap::setup(), PainterRGBA2222Bitmap::setup(), PainterXRGB8888Bitmap::setup(), and PainterXRGB8888L8Bitmap::setup().
tearDown()
virtual void tearDown () const inline virtual
This function is called after all paint operation have finished. This allows the painter to close down dma queues etc. This happens after the last scan line segment has been drawn.
See also
AbstractPainter::paint, AbstractPainter::setup
Reimplemented in PainterARGB8888, PainterARGB8888Bitmap, PainterARGB8888L8Bitmap, PainterARGB8888LinearGradient, PainterRGB565, PainterRGB565Bitmap, PainterRGB565L8Bitmap, PainterRGB565LinearGradient, PainterRGB888, PainterRGB888Bitmap, PainterRGB888L8Bitmap, and PainterRGB888LinearGradient.
    {
        return;
    }
Member Data Documentation
widgetWidth
int16_t widgetWidth mutable protected
The width of the widget on screen, used by framebufferToDisplay()
Referenced by AbstractPainter::framebufferToDisplay(), AbstractPainter::setup(), PainterABGR2222Bitmap::setup(), PainterARGB2222Bitmap::setup(), PainterARGB8888Bitmap::setup(), PainterARGB8888L8Bitmap::setup(), PainterBGRA2222Bitmap::setup(), PainterBWBitmap::setup(), PainterGRAY2Bitmap::setup(), PainterGRAY4Bitmap::setup(), PainterRGB565Bitmap::setup(), PainterRGB565L8Bitmap::setup(), PainterRGB888Bitmap::setup(), PainterRGB888L8Bitmap::setup(), PainterRGBA2222Bitmap::setup(), PainterXRGB8888Bitmap::setup(), and PainterXRGB8888L8Bitmap::setup().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/AbstractPainter.hpp