Battery Simulator Documentation: DrawableListItemsInterface
DrawableListItemsInterface abstract
#include "DrawableList.hpp"
Public Member Functions
virtual ~DrawableListItemsInterface ()
virtual Drawable * getDrawable (int16_t index)=0
virtual int16_t getNumberOfDrawables ()=0
Detailed Description
A drawable list items interface. Used to pass the allocated array of drawable elements to ScrollList::setDrawables(), ScrollWheel::setDrawables() or ScrollWheelWithSelectionStyle::setDrawables(). Provides easy access to each element in the array as well as the size of the array.
See also
ScrollList::setDrawables, ScrollWheel::setDrawables, ScrollWheelWithSelectionStyle::setDrawables
Constructor & Destructor Documentation
~DrawableListItemsInterface()
virtual ~DrawableListItemsInterface () inline virtual
Finalizes an instance of the DrawableListItemsInterface class.
    {
    }
Member Function Documentation
getDrawable()
virtual Drawable * getDrawable (int16_t index) pure virtual
Gets a drawable at a given index.
Parameters
index Zero-based index of the drawable.
Returns
Null if it fails, else the drawable.
Implemented in DrawableListItems< TYPE, SIZE >.
Referenced by DrawableList::refreshDrawables(), and DrawableList::setOffset().
getNumberOfDrawables()
virtual int16_t getNumberOfDrawables () pure virtual
Gets number of drawables.
Returns
The number of drawables.
Implemented in DrawableListItems< TYPE, SIZE >.
Referenced by DrawableList::getRequiredNumberOfDrawables().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/scrollers/DrawableList.hpp