Battery Simulator Documentation: BoxWithBorderButtonStyle< T >
BoxWithBorderButtonStyle< T >
#include "BoxWithBorderButtonStyle.hpp"
Public Member Functions
BoxWithBorderButtonStyle ()
void setBorderSize (uint8_t size)
void setBoxWithBorderColors (const colortype colorReleased, const colortype colorPressed, const colortype borderColorReleased, const colortype borderColorPressed)
void setBoxWithBorderHeight (int16_t height)
void setBoxWithBorderPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setBoxWithBorderWidth (int16_t width)
Protected Member Functions
virtual void handleAlphaUpdated ()
virtual void handlePressedUpdated ()
Protected Attributes
BoxWithBorder borderBox
The border box.
colortype borderDown
The border down.
colortype borderUp
The border up.
colortype down
The down.
colortype up
The up.
Detailed Description
template<class T>
class touchgfx::BoxWithBorderButtonStyle< T >
A box with border button style. This class is supposed to be used with one of the ButtonTrigger classes to create a functional button. This class will show a box with a border in different colors depending on the state of the button (pressed or released).
An image button style. This class is supposed to be used with one of the ButtonTrigger classes to create a functional button. This class will show one of two images depending on the state of the button (pressed or released).
Template Parameters
T Generic type parameter. Typically a AbstractButtonContainer subclass.
See also
AbstractButtonContainer, BoxWithBorder
Constructor & Destructor Documentation
BoxWithBorderButtonStyle()
template<class T > BoxWithBorderButtonStyle () inline
        : T(), up(), down()
    {
        borderBox.setXY(0, 0);
        T::add(borderBox);
    }
References BoxWithBorderButtonStyle< T >::borderBox, and Drawable::setXY().
Member Function Documentation
handleAlphaUpdated()
template<class T > virtual void handleAlphaUpdated () inline protected virtual
Handles what should happen when the alpha is updated.
    {
        borderBox.setAlpha(T::getAlpha());
        T::handleAlphaUpdated();
    }
References BoxWithBorderButtonStyle< T >::borderBox, and Box::setAlpha().
handlePressedUpdated()
template<class T > virtual void handlePressedUpdated () inline protected virtual
Handles what should happen when the pressed state is updated.
    {
        borderBox.setColor(T::getPressed() ? down : up);
        borderBox.setBorderColor(T::getPressed() ? borderDown : borderUp);
        T::handlePressedUpdated();
    }
References BoxWithBorderButtonStyle< T >::borderBox, BoxWithBorderButtonStyle< T >::borderDown, BoxWithBorderButtonStyle< T >::borderUp, BoxWithBorderButtonStyle< T >::down, BoxWithBorder::setBorderColor(), Box::setColor(), and BoxWithBorderButtonStyle< T >::up.
Referenced by BoxWithBorderButtonStyle< T >::setBoxWithBorderColors().
setBorderSize()
template<class T > void setBorderSize (uint8_t size) inline
Sets border size.
Parameters
size The size.
    {
        borderBox.setBorderSize(size);
    }
References BoxWithBorderButtonStyle< T >::borderBox, and BoxWithBorder::setBorderSize().
setBoxWithBorderColors()
template<class T > void setBoxWithBorderColors (const colortype colorReleased, const colortype colorPressed, const colortype borderColorReleased, const colortype borderColorPressed) inline
Sets the colors.
Parameters
colorReleased The color released.
colorPressed The color pressed.
borderColorReleased The border color released.
borderColorPressed The border color pressed.
    {
        up = colorReleased;
        down = colorPressed;
        borderUp = borderColorReleased;
        borderDown = borderColorPressed;
        handlePressedUpdated();
    }
References BoxWithBorderButtonStyle< T >::borderDown, BoxWithBorderButtonStyle< T >::borderUp, BoxWithBorderButtonStyle< T >::down, BoxWithBorderButtonStyle< T >::handlePressedUpdated(), and BoxWithBorderButtonStyle< T >::up.
setBoxWithBorderHeight()
template<class T > void setBoxWithBorderHeight (int16_t height) inline
Sets the height.
Parameters
height The height.
    {
        borderBox.setHeight(height);
    }
References BoxWithBorderButtonStyle< T >::borderBox, and Drawable::setHeight().
setBoxWithBorderPosition()
template<class T > void setBoxWithBorderPosition (int16_t x, int16_t y, int16_t width, int16_t height) inline
Sets the size and position of this BoxWithBorderButtonStyle, relative to its parent.
Parameters
x The x coordinate of this BoxWithBorderButtonStyle.
y The y coordinate of this BoxWithBorderButtonStyle.
width The width of this BoxWithBorderButtonStyle.
height The height of this BoxWithBorderButtonStyle.
Note
Changing this does not automatically yield a redraw.
    {
        borderBox.setPosition(x, y, width, height);
    }
References BoxWithBorderButtonStyle< T >::borderBox, and Drawable::setPosition().
setBoxWithBorderWidth()
template<class T > void setBoxWithBorderWidth (int16_t width) inline
Sets the width.
Parameters
width The width.
    {
        borderBox.setWidth(width);
    }
References BoxWithBorderButtonStyle< T >::borderBox, and Drawable::setWidth().
Member Data Documentation
borderBox
template<class T > BoxWithBorder borderBox protected
The border box.
Referenced by BoxWithBorderButtonStyle< T >::BoxWithBorderButtonStyle(), BoxWithBorderButtonStyle< T >::handleAlphaUpdated(), BoxWithBorderButtonStyle< T >::handlePressedUpdated(), BoxWithBorderButtonStyle< T >::setBorderSize(), BoxWithBorderButtonStyle< T >::setBoxWithBorderHeight(), BoxWithBorderButtonStyle< T >::setBoxWithBorderPosition(), and BoxWithBorderButtonStyle< T >::setBoxWithBorderWidth().
borderDown
template<class T > colortype borderDown protected
The border down.
Referenced by BoxWithBorderButtonStyle< T >::handlePressedUpdated(), and BoxWithBorderButtonStyle< T >::setBoxWithBorderColors().
borderUp
template<class T > colortype borderUp protected
The border up.
Referenced by BoxWithBorderButtonStyle< T >::handlePressedUpdated(), and BoxWithBorderButtonStyle< T >::setBoxWithBorderColors().
down
template<class T > colortype down protected
The down.
Referenced by BoxWithBorderButtonStyle< T >::handlePressedUpdated(), and BoxWithBorderButtonStyle< T >::setBoxWithBorderColors().
up
template<class T > colortype up protected
The up.
Referenced by BoxWithBorderButtonStyle< T >::handlePressedUpdated(), and BoxWithBorderButtonStyle< T >::setBoxWithBorderColors().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/buttons/BoxWithBorderButtonStyle.hpp