Battery Simulator Documentation: FrontendApplicationBase
FrontendApplicationBase
#include "FrontendApplicationBase.hpp"
Public Member Functions
FrontendApplicationBase (Model &m, FrontendHeap &heap)
virtual ~FrontendApplicationBase ()
virtual void changeToStartScreen ()
void gotoScreen1ScreenNoTransition ()
Public Member Functions inherited from MVPApplication
MVPApplication ()
virtual void handlePendingScreenTransition ()
Public Member Functions inherited from Application
virtual void appSwitchScreen (uint8_t screenId)
void clearAllTimerWidgets ()
virtual void clearCachedAreas ()
void copyInvalidatedAreasFromTFTToClientBuffer ()
virtual void drawCachedAreas ()
const Vector< Rect, 8 > & getInvalidatedAreas ()
uint16_t getNumberOfRegisteredTimerWidgets () const
uint16_t getTimerWidgetCountForDrawable (const Drawable *w) const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleKeyEvent (uint8_t c)
virtual void handleTickEvent ()
virtual void invalidate ()
virtual void invalidateArea (Rect area)
void registerTimerWidget (Drawable *w)
virtual void requestRedraw ()
virtual void requestRedraw (Rect &rect)
virtual void switchScreen (Screen *newScreen)
void unregisterTimerWidget (const Drawable *w)
Public Member Functions inherited from UIEventListener
virtual ~UIEventListener ()
Protected Member Functions
void gotoScreen1ScreenNoTransitionImpl ()
Protected Member Functions inherited from MVPApplication
void evaluatePendingScreenTransition ()
Protected Member Functions inherited from Application
Application ()
virtual void draw ()
virtual void draw (Rect &rect)
Protected Attributes
FrontendHeap & frontendHeap
Model & model
touchgfx::Callback< FrontendApplicationBase > transitionCallback
Protected Attributes inherited from MVPApplication
Presenter * currentPresenter
Pointer to the currently active presenter.
GenericCallback * pendingScreenTransitionCallback
Callback for screen transitions. Will be set to something valid when a transition request is made.
Protected Attributes inherited from Application
RectVector_t cachedDirtyAreas
When draw caching is enabled, these rects keeps track of the dirty screen area.
RectVector_t lastRects
The dirty areas from last frame that needs to be redrawn because we have swapped frame buffers.
Rect redraw
Rect describing application requested invalidate area.
class touchgfx::Application::TimerWidgets timerWidgets
The timer widgets.
bool transitionHandled
True if the transition is done and Screen::afterTransition has been called.
Additional Inherited Members
Static Public Member Functions inherited from Application
static Screen * getCurrentScreen ()
static DebugPrinter * getDebugPrinter ()
static Application * getInstance ()
static void invalidateDebugRegion ()
static void setDebugPrinter (DebugPrinter *printer)
static void setDebugString (const char *string)
Static Public Attributes inherited from Application
static const uint8_t MAX_TIMER_WIDGETS = 32
Maximum number of widgets receiving ticks.
static const uint16_t TICK_INTERVAL_MS = 10
Deprecated, do not use this constant. Tick interval depends on VSYNC of your target platform.
Protected Types inherited from Application
typedef Vector< Rect, 8 > RectVector_t
Type to ensure the same number of rects are in the Vector.
Static Protected Attributes inherited from Application
static Screen * currentScreen
Pointer to currently displayed Screen.
static Transition * currentTransition
Pointer to current transition.
static DebugPrinter * debugPrinter
Pointer to the DebugPrinter instance.
static Rect debugRegionInvalidRect
Invalidated Debug Region.
static Application * instance
Pointer to the instance of the Application-derived subclass.
Detailed Description
Constructor & Destructor Documentation
FrontendApplicationBase()
FrontendApplicationBase (Model & m, FrontendHeap & heap)
    : touchgfx::MVPApplication(),
      transitionCallback(),
      frontendHeap(heap),
      model(m)
{
    touchgfx::HAL::getInstance()->setDisplayOrientation(touchgfx::ORIENTATION_LANDSCAPE);
    reinterpret_cast<touchgfx::LCD24bpp&>(touchgfx::HAL::lcd()).enableTextureMapperAll();
    reinterpret_cast<touchgfx::LCD24bpp&>(touchgfx::HAL::lcd()).enableDecompressorL8_All();
}
References HAL::getInstance(), HAL::lcd(), and touchgfx::ORIENTATION_LANDSCAPE.
~FrontendApplicationBase()
virtual ~FrontendApplicationBase () inline virtual
{ }
Member Function Documentation
changeToStartScreen()
virtual void changeToStartScreen () inline virtual
This function can be called to send your application back to the start screen. The simulator will call this function when F5 is pressed. To make this work, please implement this function in FrontendApplication.
Note
The application will not make a complete restart - if your Model contains data, this will not be reset, unless this is explicitly done in your FrontendApplication::changeToStartScreen().
Reimplemented from Application.
    {
        gotoScreen1ScreenNoTransition();
    }
References gotoScreen1ScreenNoTransition().
gotoScreen1ScreenNoTransition()
void gotoScreen1ScreenNoTransition ()
{
    transitionCallback = touchgfx::Callback<FrontendApplicationBase>(this, &FrontendApplicationBase::gotoScreen1ScreenNoTransitionImpl);
    pendingScreenTransitionCallback = &transitionCallback;
}
References gotoScreen1ScreenNoTransitionImpl(), MVPApplication::pendingScreenTransitionCallback, and transitionCallback.
Referenced by changeToStartScreen(), and FrontendHeapBase::gotoStartScreen().
gotoScreen1ScreenNoTransitionImpl()
void gotoScreen1ScreenNoTransitionImpl () protected
{
    touchgfx::makeTransition<Screen1View, Screen1Presenter, touchgfx::NoTransition, Model >(&currentScreen, &currentPresenter, frontendHeap, &currentTransition, &model);
}
References MVPApplication::currentPresenter, Application::currentScreen, Application::currentTransition, frontendHeap, and model.
Referenced by gotoScreen1ScreenNoTransition().
Member Data Documentation
frontendHeap
FrontendHeap& frontendHeap protected
Referenced by gotoScreen1ScreenNoTransitionImpl().
model
Model& model protected
Referenced by gotoScreen1ScreenNoTransitionImpl(), and FrontendApplication::handleTickEvent().
transitionCallback
touchgfx::Callback<FrontendApplicationBase> transitionCallback protected
Referenced by gotoScreen1ScreenNoTransition().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/gui_generated/include/gui_generated/common/FrontendApplicationBase.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/gui_generated/src/common/FrontendApplicationBase.cpp