Battery Simulator Documentation: GraphLabelsBase
GraphLabelsBase abstract
#include "GraphLabels.hpp"
Public Member Functions
GraphLabelsBase ()
virtual void draw (const Rect &invalidatedArea) const
virtual int getCorrectlyScaledLabelInterval (const AbstractDataGraph *graph) const =0
virtual int getCorrectlyScaledMajorInterval (const AbstractDataGraph *graph) const
FORCE_INLINE_FUNCTION float getIntervalAsFloat () const
FORCE_INLINE_FUNCTION int getIntervalAsInt () const
FORCE_INLINE_FUNCTION int getIntervalScaled () const
FORCE_INLINE_FUNCTION Unicode::UnicodeChar getLabelDecimalPoint () const
FORCE_INLINE_FUNCTION uint16_t getLabelDecimals () const
FORCE_INLINE_FUNCTION TextRotation getLabelRotation () const
FORCE_INLINE_FUNCTION const TypedText & getLabelTypedText () const
FORCE_INLINE_FUNCTION int getScale () const
virtual void invalidateGraphPointAt (int16_t)
FORCE_INLINE_FUNCTION void setInterval (float interval)
FORCE_INLINE_FUNCTION void setInterval (int interval)
FORCE_INLINE_FUNCTION void setIntervalScaled (int interval)
FORCE_INLINE_FUNCTION void setLabelDecimalPoint (Unicode::UnicodeChar decimalPoint)
FORCE_INLINE_FUNCTION void setLabelDecimals (uint16_t decimals)
FORCE_INLINE_FUNCTION void setLabelRotation (TextRotation rotation)
FORCE_INLINE_FUNCTION void setLabelTypedText (const TypedText &typedText)
FORCE_INLINE_FUNCTION void setMajorLabel (const GraphLabelsBase &major)
FORCE_INLINE_FUNCTION void setScale (int scale)
Public Member Functions inherited from AbstractGraphElementNoCWR
AbstractGraphElementNoCWR ()
virtual bool drawCanvasWidget (const Rect &) const
virtual colortype getColor () const
virtual void setColor (colortype newColor)
Public Member Functions inherited from AbstractGraphElement
AbstractGraphElement ()
Public Member Functions inherited from CanvasWidget
CanvasWidget ()
virtual uint8_t getAlpha () const
virtual Rect getMinimalRect () const
const AbstractPainter * getPainter () const
virtual Rect getSolidRect () const
virtual void invalidate () const
virtual void setAlpha (uint8_t newAlpha)
void setPainter (const AbstractPainter &painter)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual void drawIndexRange (const Rect &invalidatedArea, const Font *fontToDraw, const AbstractDataGraph *graph, const int rangeMin, const int rangeMax, const int minorInterval, const int majorInterval, const uint8_t a) const
virtual void drawString (const Rect &invalidatedArea, const Font *fontToDraw, const AbstractDataGraph *graph, const int valueScaled, const int labelScaled, const uint8_t a) const =0
void formatLabel (Unicode::UnicodeChar *buffer, int16_t bufferSize, int label, int decimals, Unicode::UnicodeChar decimalPoint, int scale) const
virtual int getGraphRangeMaxScaled (const AbstractDataGraph *graph) const =0
virtual int getGraphRangeMinScaled (const AbstractDataGraph *graph) const =0
Protected Member Functions inherited from AbstractGraphElementNoCWR
void normalizeRect (Rect &r) const
Protected Member Functions inherited from AbstractGraphElement
FORCE_INLINE_FUNCTION int convertToGraphScaleX (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION int convertToGraphScaleY (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION AbstractDataGraph * getGraph () const
FORCE_INLINE_FUNCTION int getIndexToXAxis (const AbstractDataGraph *graph, const int valueScaled, const int labelScaled) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenXQ5 (const AbstractDataGraph *graph, int16_t index) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenYQ5 (const AbstractDataGraph *graph, int16_t index) const
bool isCenterInvisible (const AbstractDataGraph *graph, int16_t index) const
Rect rectAround (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5, CWRUtil::Q5 diameterQ5) const
Rect rectFromQ5Coordinates (CWRUtil::Q5 screenXminQ5, CWRUtil::Q5 screenYminQ5, CWRUtil::Q5 screenXmaxQ5, CWRUtil::Q5 screenYmaxQ5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 roundQ5 (CWRUtil::Q5 q5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenXQ5 (const AbstractDataGraph *graph, int x) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenYQ5 (const AbstractDataGraph *graph, int y) const
FORCE_INLINE_FUNCTION bool xScreenRangeToIndexRange (const AbstractDataGraph *graph, int16_t xMin, int16_t xMax, int16_t &indexMin, int16_t &indexMax) const
Protected Attributes
int dataScale
The scaling factor.
Unicode::UnicodeChar labelDecimalPoint
The label decimal point character.
uint16_t labelDecimals
The number of decimals on the label.
int labelInterval
The interval between each label.
TextRotation labelRotation
The TextRotation to use for the label.
TypedText labelTypedText
The TypedText to use for the label.
const GraphLabelsBase * majorLabel
A pointer to a major label, if any.
Protected Attributes inherited from AbstractGraphElementNoCWR
colortype color
The currently assigned color.
Protected Attributes inherited from CanvasWidget
uint8_t alpha
The Alpha for this CanvasWidget.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
Helper class for adding labels on the side of a graph.
See also
GraphLabelsX, GraphLabelsY
Constructor & Destructor Documentation
GraphLabelsBase()
GraphLabelsBase () inline
        : AbstractGraphDecoration(),
          dataScale(1), labelInterval(0), labelTypedText(TYPED_TEXT_INVALID), labelRotation(TEXT_ROTATE_0), labelDecimals(0), labelDecimalPoint('.'), majorLabel(0)
    {
    }
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draws the given invalidated area. If the underlying CanvasWidgetRenderer fail to render the widget (if the widget is too complex), the invalidated area is cut into smaller slices (horizontally) which are then drawn separately. If drawing a single raster line fails, that line is considered too complex and skipped (it is left blank/transparent) and drawing continues on the next raster line.
If drawing has failed at least once, which means that the number of horizontal lines draw has been reduced, the number of successfully drawn horizontal lines is remembered for the next invocation of draw(). A future call to draw() would then start off with the reduced number of horizontal lines to prevent potentially drawing the canvas widget in vain, as happened previously in draw().
Parameters
invalidatedArea The invalidated area.
See also
drawCanvasWidget
Note
Subclasses of CanvasWidget should implement drawCanvasWidget(), not draw().
The term "too complex" means that the size of the buffer (assigned to CanvasWidgetRenderer using CanvasWidgetRenderer::setupBuffer()) is too small.
Reimplemented from CanvasWidget.
{
    if (!labelTypedText.hasValidId())
    {
        return;
    }
    const Font* fontToDraw = labelTypedText.getFont();
    if (!fontToDraw)
    {
        return;
    }
    const AbstractDataGraph* graph = getGraph();
    const uint8_t a = LCD::div255(getAlpha() * graph->getAlpha());
    if (a == 0)
    {
        return;
    }
    const int minorInterval = getCorrectlyScaledLabelInterval(graph);
    const int majorInterval = getCorrectlyScaledMajorInterval(graph);
    if (majorInterval == 0 && minorInterval == 0)
    {
        drawString(invalidatedArea, fontToDraw, graph, 0, 0, a);
    }
    else if (minorInterval > 0)
    {
        int rangeMin = getGraphRangeMinScaled(graph);
        int rangeMax = getGraphRangeMaxScaled(graph);
        if (rangeMin > rangeMax)
        {
            const int tmp = rangeMin;
            rangeMin = rangeMax;
            rangeMax = tmp;
        }
        if ((rangeMax - rangeMin) / minorInterval > 100)
        {
            return; // Too many labels
        }
        drawIndexRange(invalidatedArea, fontToDraw, graph, rangeMin, rangeMax, minorInterval, majorInterval, a);
    }
}
References LCD::div255(), GraphLabelsBase::drawIndexRange(), GraphLabelsBase::drawString(), CanvasWidget::getAlpha(), GraphLabelsBase::getCorrectlyScaledLabelInterval(), GraphLabelsBase::getCorrectlyScaledMajorInterval(), TypedText::getFont(), AbstractGraphElement::getGraph(), GraphLabelsBase::getGraphRangeMaxScaled(), GraphLabelsBase::getGraphRangeMinScaled(), TypedText::hasValidId(), and GraphLabelsBase::labelTypedText.
drawIndexRange()
void drawIndexRange (const Rect & invalidatedArea, const Font * fontToDraw, const AbstractDataGraph * graph, const int rangeMin, const int rangeMax, const int minorInterval, const int majorInterval, const uint8_t a) const protected virtual
Draw labels for all indexes in the given range. This is used where there is a gap in the graph and the labels have to be drawn using different x scales.
Parameters
[in] invalidatedArea The canvas.
fontToDraw The font to draw.
graph The graph.
rangeMin The minimum index.
rangeMax The maximum index.
minorInterval The minor interval.
majorInterval The major interval.
a The alpha of the strings.
Reimplemented in GraphLabelsX.
{
    if (minorInterval == 0)
    {
        if ((0 >= rangeMin && 0 <= rangeMax) || (0 >= rangeMax && 0 <= rangeMin))
        {
            drawString(invalidatedArea, fontToDraw, graph, 0, 0, a);
        }
        return;
    }
    const int minorLo = (int)(rangeMin / minorInterval) - 1;
    const int minorHi = (int)(rangeMax / minorInterval) + 1;
    if (majorInterval == 0)
    {
        for (int minorIndex = minorLo; minorIndex != minorHi + 1; minorIndex++)
        {
            const int minorValue = (int)(minorInterval * minorIndex);
            if ((minorValue >= rangeMin && minorValue <= rangeMax) || (minorValue >= rangeMax && minorValue <= rangeMin))
            {
                drawString(invalidatedArea, fontToDraw, graph, minorValue, labelInterval * minorIndex, a);
            }
        }
    }
    else
    {
        const int majorLo = (int)(rangeMin / majorInterval) - 1;
        const int majorHi = (int)(rangeMax / majorInterval) + 1;
        int majorIndex = majorLo;
        int majorValue = majorInterval * majorIndex;
        int minorIndex = minorLo;
        int minorValue = minorInterval * minorIndex;
        for (;;)
        {
            // Draw strings up to the major
            while (minorValue < majorValue)
            {
                if ((minorValue >= rangeMin && minorValue <= rangeMax) || (minorValue >= rangeMax && minorValue <= rangeMin))
                {
                    drawString(invalidatedArea, fontToDraw, graph, minorValue, labelInterval * minorIndex, a);
                }
                minorIndex++;
                minorValue += minorInterval;
            }
            // Advance minor past the major we are about to draw
            while (minorValue <= majorValue)
            {
                minorIndex++;
                minorValue += minorInterval;
            }
            if (majorValue < minorValue)
            {
                majorIndex++;
                if (majorIndex == majorHi + 1)
                {
                    break;
                }
                majorValue += majorInterval;
            }
        }
    }
}
References GraphLabelsBase::drawString(), and GraphLabelsBase::labelInterval.
Referenced by GraphLabelsBase::draw(), and GraphLabelsX::drawIndexRange().
drawString()
virtual void drawString (const Rect & invalidatedArea, const Font * fontToDraw, const AbstractDataGraph * graph, const int valueScaled, const int labelScaled, const uint8_t a) const protected pure virtual
Draw string.
Parameters
invalidatedArea The invalidated area.
fontToDraw The font to draw.
graph The graph.
valueScaled The value scaled.
labelScaled The label scaled.
a The alpha of the string.
Implemented in GraphLabelsX, and GraphLabelsY.
Referenced by GraphLabelsBase::draw(), and GraphLabelsBase::drawIndexRange().
formatLabel()
void formatLabel (Unicode::UnicodeChar * buffer, int16_t bufferSize, int label, int decimals, Unicode::UnicodeChar decimalPoint, int scale) const protected
Format label according to the set number of decimals and the decimal point.
Parameters
[in,out] buffer The buffer to fill with the formatted number.
bufferSize Size of the buffer.
label The label value.
decimals The number of decimals.
decimalPoint The decimal point.
scale The scale of the label value.
{
    int length = 0;
    if (label < 0 && length < bufferSize - 1)
    {
        buffer[length++] = '-';
        label = -label;
    }
    if (decimals == 0)
    {
        Unicode::snprintf(buffer + length, bufferSize - length, "%d", (label + scale / 2) / scale);
    }
    else if (decimals > 0)
    {
        Unicode::snprintf(buffer + length, bufferSize - length, "%d", label / scale);
        length = Unicode::strlen(buffer);
        if (length < bufferSize - 1)
        {
            buffer[length++] = decimalPoint;
            int remainder = label % scale;
            for (int i = 0; i < decimals && length < bufferSize - 1; i++)
            {
                remainder *= 10;
                if (i == decimals - 1 || length == bufferSize - 1)
                {
                    remainder += scale / 2; // Rounding on the last (visible) digit
                }
                const int digit = (remainder / scale);
                buffer[length++] = (Unicode::UnicodeChar)('0' + digit);
                remainder %= scale;
            }
            buffer[length] = (Unicode::UnicodeChar)0;
        }
    }
}
References Unicode::snprintf(), and Unicode::strlen().
Referenced by GraphLabelsX::drawString(), GraphLabelsY::drawString(), and GraphLabelsX::invalidateGraphPointAt().
getCorrectlyScaledLabelInterval()
virtual int getCorrectlyScaledLabelInterval (const AbstractDataGraph * graph) const pure virtual
Gets correctly scaled minor interval, as the minor label may have a scale that differs the scale of the graph and this label.
Parameters
graph The graph.
Returns
The correctly scaled minor interval.
Implemented in GraphLabelsX, and GraphLabelsY.
Referenced by GraphLabelsBase::draw().
getCorrectlyScaledMajorInterval()
virtual int getCorrectlyScaledMajorInterval (const AbstractDataGraph * graph) const inline virtual
Gets correctly scaled major interval, as the major label may have a scale that differs the scale of the graph and this label.
Parameters
graph The graph.
Returns
The correctly scaled major interval.
    {
        return majorLabel == 0 ? 0 : majorLabel->getCorrectlyScaledLabelInterval(graph);
    }
References GraphLabelsBase::majorLabel.
Referenced by GraphLabelsBase::draw(), and GraphLabelsX::invalidateGraphPointAt().
getGraphRangeMaxScaled()
virtual int getGraphRangeMaxScaled (const AbstractDataGraph * graph) const protected pure virtual
Gets graph range maximum scaled.
Parameters
graph The graph.
Returns
The graph range maximum scaled.
Implemented in GraphLabelsX, and GraphLabelsY.
Referenced by GraphLabelsBase::draw().
getGraphRangeMinScaled()
virtual int getGraphRangeMinScaled (const AbstractDataGraph * graph) const protected pure virtual
Gets graph range minimum scaled.
Parameters
graph The graph.
Returns
The graph range minimum scaled.
Implemented in GraphLabelsX, and GraphLabelsY.
Referenced by GraphLabelsBase::draw().
getIntervalAsFloat()
FORCE_INLINE_FUNCTION float getIntervalAsFloat () const inline
Gets the interval between each label.
Returns
The interval between each label.
See also
setInterval
    {
        return AbstractDataGraph::scaled2float(getIntervalScaled(), dataScale);
    }
References GraphLabelsBase::dataScale, GraphLabelsBase::getIntervalScaled(), and AbstractDataGraph::scaled2float().
getIntervalAsInt()
FORCE_INLINE_FUNCTION int getIntervalAsInt () const inline
Gets the interval between each label.
Returns
The interval between each label.
See also
setInterval
    {
        return AbstractDataGraph::scaled2int(getIntervalScaled(), dataScale);
    }
References GraphLabelsBase::dataScale, GraphLabelsBase::getIntervalScaled(), and AbstractDataGraph::scaled2int().
getIntervalScaled()
FORCE_INLINE_FUNCTION int getIntervalScaled () const inline
Gets the interval between each label.
Returns
The interval between each label.
See also
setInterval
Note
The interval returned here is left unscaled.
    {
        return labelInterval;
    }
References GraphLabelsBase::labelInterval.
Referenced by GraphLabelsBase::getIntervalAsFloat(), and GraphLabelsBase::getIntervalAsInt().
getLabelDecimalPoint()
FORCE_INLINE_FUNCTION Unicode::UnicodeChar getLabelDecimalPoint () const inline
Gets label decimal point previously set.
Returns
The label decimal point.
See also
setLabelDecimalPoint
    {
        return labelDecimalPoint;
    }
References GraphLabelsBase::labelDecimalPoint.
getLabelDecimals()
FORCE_INLINE_FUNCTION uint16_t getLabelDecimals () const inline
Gets number of decimals for labels.
Returns
The number of label decimals.
    {
        return labelDecimals;
    }
References GraphLabelsBase::labelDecimals.
getLabelRotation()
FORCE_INLINE_FUNCTION TextRotation getLabelRotation () const inline
Gets label rotation.
Returns
The label rotation.
See also
setLabelRotation
    {
        return labelRotation;
    }
References GraphLabelsBase::labelRotation.
getLabelTypedText()
FORCE_INLINE_FUNCTION const TypedText & getLabelTypedText () const inline
Gets TypedText label.
Returns
The label typed text.
See also
setLabelTypedText
    {
        return labelTypedText;
    }
References GraphLabelsBase::labelTypedText.
getScale()
FORCE_INLINE_FUNCTION int getScale () const inline
Gets the scaling factor set using setScale.
Returns
The scaling factor.
See also
setScale
    {
        return dataScale;
    }
References GraphLabelsBase::dataScale.
invalidateGraphPointAt()
virtual void invalidateGraphPointAt (int16_t index) inline virtual
Invalidate the point at the given index. This allows a graph element to only invalidate the minimum rectangle required for the given index. The Graph will call this function before and after changing a point to ensure that both the old and the new area are redrawn (invalidated).
Parameters
index Zero-based index of the point.
Implements AbstractGraphElement.
Reimplemented in GraphLabelsX.
    {
    }
setInterval() [1/2]
FORCE_INLINE_FUNCTION void setInterval (float interval) inline
Sets the interval between each label.
Parameters
interval The interval between each label.
See also
getIntervalAsInt, getIntervalAsFloat, setMajorLabel
Note
If interval is 0 only the axis is shown.
    {
        setIntervalScaled(AbstractDataGraph::float2scaled(interval, dataScale));
    }
References GraphLabelsBase::dataScale, AbstractDataGraph::float2scaled(), and GraphLabelsBase::setIntervalScaled().
setInterval() [2/2]
FORCE_INLINE_FUNCTION void setInterval (int interval) inline
Sets the interval between each label.
Parameters
interval The interval between each label.
See also
getIntervalAsInt, getIntervalAsFloat, setMajorLabel
Note
If interval is 0 only the axis is shown.
    {
        setIntervalScaled(AbstractDataGraph::int2scaled(interval, dataScale));
    }
References GraphLabelsBase::dataScale, AbstractDataGraph::int2scaled(), and GraphLabelsBase::setIntervalScaled().
setIntervalScaled()
FORCE_INLINE_FUNCTION void setIntervalScaled (int interval) inline
Sets the interval between each label.
Parameters
interval The interval between each label.
See also
getIntervalAsInt, getIntervalAsFloat, setMajorLabel
Note
If interval is 0 only the axis is shown.
The interval set here must already be scaled.
    {
        labelInterval = abs(interval);
    }
References touchgfx::abs(), and GraphLabelsBase::labelInterval.
Referenced by GraphLabelsBase::setInterval(), and GraphLabelsBase::setInterval().
setLabelDecimalPoint()
FORCE_INLINE_FUNCTION void setLabelDecimalPoint (Unicode::UnicodeChar decimalPoint) inline
Sets label decimal point. Default is to use '.' but this can be changed using this function.
Parameters
decimalPoint The character to use for decimal point.
See also
setLabelDecimals
Note
The decimal point is only set if the label decimals > 0.
    {
        labelDecimalPoint = decimalPoint;
    }
References GraphLabelsBase::labelDecimalPoint.
setLabelDecimals()
FORCE_INLINE_FUNCTION void setLabelDecimals (uint16_t decimals) inline
Sets number of decimals for labels, default is no decimals and no decimal point.
Parameters
decimals The number of label decimals.
See also
setLabelDecimalPoint
    {
        labelDecimals = decimals;
    }
References GraphLabelsBase::labelDecimals.
setLabelRotation()
FORCE_INLINE_FUNCTION void setLabelRotation (TextRotation rotation) inline
Sets label rotation.
Parameters
rotation The rotation or the text.
See also
getLabelRotation
    {
        labelRotation = rotation;
    }
References GraphLabelsBase::labelRotation.
setLabelTypedText()
FORCE_INLINE_FUNCTION void setLabelTypedText (const TypedText & typedText) inline
Sets TypedText to use for the label. The TypedText should contain exactly one wildcard.
Parameters
typedText The typed text.
See also
getLabelTypedText
    {
        labelTypedText = typedText;
    }
References GraphLabelsBase::labelTypedText.
setMajorLabel()
FORCE_INLINE_FUNCTION void setMajorLabel (const GraphLabelsBase & major) inline
Sets "major" label that will be responsible for drawing major labels. If a label would be drawn at the same position as the major label, the label will not be drawn.
Parameters
major Reference to a major label object.
    {
        majorLabel = &major;
    }
References GraphLabelsBase::majorLabel.
setScale()
FORCE_INLINE_FUNCTION void setScale (int scale) inline
Sets a scaling factor to be multiplied on the labelInterval. Any already set labelInterval will be updated to the new correctly scaled value. To avoid this, use setIntervalScaled after setting scale.
Parameters
scale The scaling factor.
See also
getScale
    {
        assert(scale != 0);
        labelInterval = AbstractDataGraph::convertToNewScale(labelInterval, dataScale, scale);
        dataScale = scale;
    }
References AbstractDataGraph::convertToNewScale(), GraphLabelsBase::dataScale, and GraphLabelsBase::labelInterval.
Member Data Documentation
dataScale
int dataScale protected
The scaling factor.
Referenced by GraphLabelsY::drawString(), GraphLabelsX::getCorrectlyScaledLabelInterval(), GraphLabelsY::getCorrectlyScaledLabelInterval(), GraphLabelsBase::getIntervalAsFloat(), GraphLabelsBase::getIntervalAsInt(), GraphLabelsBase::getScale(), GraphLabelsX::invalidateGraphPointAt(), GraphLabelsBase::setInterval(), GraphLabelsBase::setInterval(), and GraphLabelsBase::setScale().
labelDecimalPoint
Unicode::UnicodeChar labelDecimalPoint protected
The label decimal point character.
Referenced by GraphLabelsX::drawString(), GraphLabelsY::drawString(), GraphLabelsBase::getLabelDecimalPoint(), GraphLabelsX::invalidateGraphPointAt(), and GraphLabelsBase::setLabelDecimalPoint().
labelDecimals
uint16_t labelDecimals protected
The number of decimals on the label.
Referenced by GraphLabelsX::drawString(), GraphLabelsY::drawString(), GraphLabelsBase::getLabelDecimals(), GraphLabelsX::invalidateGraphPointAt(), and GraphLabelsBase::setLabelDecimals().
labelInterval
int labelInterval protected
The interval between each label.
Referenced by GraphLabelsBase::drawIndexRange(), GraphLabelsX::getCorrectlyScaledLabelInterval(), GraphLabelsY::getCorrectlyScaledLabelInterval(), GraphLabelsBase::getIntervalScaled(), GraphLabelsX::invalidateGraphPointAt(), GraphLabelsBase::setIntervalScaled(), and GraphLabelsBase::setScale().
labelRotation
TextRotation labelRotation protected
The TextRotation to use for the label.
Referenced by GraphLabelsX::drawString(), GraphLabelsY::drawString(), GraphLabelsBase::getLabelRotation(), GraphLabelsX::invalidateGraphPointAt(), and GraphLabelsBase::setLabelRotation().
labelTypedText
TypedText labelTypedText protected
The TypedText to use for the label.
Referenced by GraphLabelsBase::draw(), GraphLabelsX::drawString(), GraphLabelsY::drawString(), GraphLabelsBase::getLabelTypedText(), GraphLabelsX::invalidateGraphPointAt(), and GraphLabelsBase::setLabelTypedText().
majorLabel
const GraphLabelsBase* majorLabel protected
A pointer to a major label, if any.
Referenced by GraphLabelsBase::getCorrectlyScaledMajorInterval(), and GraphLabelsBase::setMajorLabel().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/graph/GraphLabels.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph/GraphLabels.cpp