Battery Simulator Documentation: Keyboard
Keyboard
#include "Keyboard.hpp"
Classes
struct CallbackArea
struct Key
struct KeyMapping
struct KeyMappingList
struct Layout
Public Member Functions
Keyboard ()
virtual void draw (const Rect &invalidatedArea) const
Unicode::UnicodeChar * getBuffer () const
uint16_t getBufferPosition ()
const KeyMappingList * getKeyMappingList () const
const Layout * getLayout () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
void setBuffer (Unicode::UnicodeChar *newBuffer, uint16_t newBufferSize)
void setBufferPosition (uint16_t newPos)
void setKeyListener (GenericCallback< Unicode::UnicodeChar > &callback)
void setKeymappingList (const KeyMappingList *newKeyMappingList)
void setLayout (const Layout *newLayout)
void setTextIndentation ()
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
CallbackArea getCallbackAreaForCoordinates (int16_t x, int16_t y) const
Unicode::UnicodeChar getCharForKey (uint8_t keyId) const
Key getKeyForCoordinates (int16_t x, int16_t y) const
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
Unicode::UnicodeChar * buffer
Pointer to null-terminated buffer where the entered text is being displayed.
uint16_t bufferPosition
Current position in buffer.
uint16_t bufferSize
Size of the buffer.
bool cancelIsEmitted
Tells if a cancel is emitted to check when a key is released.
TextAreaWithOneWildcard enteredText
Widget capable of displaying the entered text buffer.
Image highlightImage
Image to display when a key is highlighted.
Image image
Layout bitmap.
GenericCallback< Unicode::UnicodeChar > * keyListener
Pointer to callback being executed when a key is pressed.
const KeyMappingList * keyMappingList
Pointer to key mapping.
const Layout * layout
Pointer to layout.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
The keyboard provides text input for touch devices. It is configured using a Layout and a KeyMappingList, both of which can be changed at runtime. The class using the keyboard must provide a buffer where the entered text is placed. The Layout contains a bitmap id for the image to display and two mappings: rectangles to key ids and rectangles to callback methods.
The KeyMappingList maps key ids to Unicode characters. When the user presses a key, the keyboard looks in its layout for a rectangle containing the coordinates pressed. If it finds a mapping to a callback method, it will invoke that method. If it finds a mapping to a key it will look up the Unicode character for that key and place it in a text buffer. The sequence is: (x,y) -> KeyId -> UnicodeChar.
A keyboard with multiple key mappings e.g. lower case alpha, upper case alpha and numeric mappings can be created by implementing callback methods for shift and mode areas in the provided bitmap and then changing the KeyMappingList when those areas are pressed.
Constructor & Destructor Documentation
Keyboard()
Keyboard ()
    : Container(), keyListener(0), buffer(0), bufferSize(0), bufferPosition(0), image(), enteredText(), layout(0), keyMappingList(0), highlightImage(), cancelIsEmitted(false)
{
    setTouchable(true);
    image.setXY(0, 0);
    Keyboard::add(image);
    highlightImage.setVisible(false);
    Keyboard::add(highlightImage);
    enteredText.setColor(Color::getColorFromRGB(0, 0, 0));
    Keyboard::add(enteredText);
}
References Container::add(), Keyboard::enteredText, Color::getColorFromRGB(), Keyboard::highlightImage, TextArea::setColor(), Drawable::setTouchable(), and Drawable::setVisible().
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Overrides the draw implementation on the Container. First invokes the container draw implementation to draw the keyboard bitmap and text area holding the entered text. If additional drawables have been added to the keyboard, they will also be draw. After invoking the container draw, the glyphs mapped to keys are drawn and if a key has been pressed, it will be highlighted.
Parameters
invalidatedArea The area to draw.
Reimplemented from Container.
{
    assert(layout && "No layout configured for Keyboard");
    if (layout != 0)
    {
        Font* font = FontManager::getFont(layout->keyFont);
        assert(font && "Keyboard::draw: Unable to find font, is font db initialized?");
        if (font != 0)
        {
            // Setup visuals for h-center of "string"
            LCD::StringVisuals visuals;
            visuals.font = font;
            visuals.alignment = CENTER;
            visuals.color = layout->keyFontColor;
            // String with room for a single character
            Unicode::UnicodeChar character[2] = { 0, 0 }; // The last is important as string terminator.
            const uint16_t fontHeight = font->getHeight();
            for (uint8_t i = 0; i < layout->numberOfKeys; i++)
            {
                const Key& key = layout->keyArray[i];
                if (key.keyArea.intersect(invalidatedArea))
                {
                    const uint8_t keyId = key.keyId;
                    const Unicode::UnicodeChar c = getCharForKey(keyId);
                    if (c != 0)
                    {
                        // Get a copy of the keyArea and v-center the area for the character
                        Rect keyArea = key.keyArea;
                        const uint16_t offset = (keyArea.height - fontHeight) / 2;
                        keyArea.y += offset;
                        keyArea.height -= offset;
                        // Calculate the invalidated area relative to the key
                        Rect invalidatedAreaRelative = key.keyArea & invalidatedArea;
                        invalidatedAreaRelative.x -= keyArea.x;
                        invalidatedAreaRelative.y -= keyArea.y;
                        // Set up string with one character
                        character[0] = c;
                        translateRectToAbsolute(keyArea);
                        HAL::lcd().drawString(keyArea, invalidatedAreaRelative, visuals, character);
                    }
                }
            }
        }
    }
}
References touchgfx::CENTER, Keyboard::getCharForKey(), FontManager::getFont(), Font::getHeight(), Rect::height, Rect::intersect(), Keyboard::Key::keyArea, Keyboard::Key::keyId, Keyboard::layout, HAL::lcd(), Drawable::translateRectToAbsolute(), Rect::x, and Rect::y.
getBuffer()
Unicode::UnicodeChar * getBuffer () const inline
Gets the buffer.
Returns
The buffer containing entered text currently being displayed.
See also
setBuffer
    {
        return buffer;
    }
References Keyboard::buffer.
getBufferPosition()
uint16_t getBufferPosition () inline
Gets buffer position.
Returns
the buffer position, i.e. the current index where new characters will be placed.
See also
setBufferPosition
    {
        return bufferPosition;
    }
References Keyboard::bufferPosition.
getCallbackAreaForCoordinates()
Keyboard::CallbackArea getCallbackAreaForCoordinates (int16_t x, int16_t y) const protected
Gets the callback area defined by the layout for the specified coordinates.
Parameters
x The x coordinate to perform key look up with.
y The y coordinate to perform key look up with.
Returns
The CallbackArea, which is empty if not found.
{
    CallbackArea area;
    area.callback = reinterpret_cast<GenericCallback<>*>(0);
    if (layout != 0)
    {
        for (uint8_t i = 0; i < layout->numberOfCallbackAreas; i++)
        {
            if (layout->callbackAreaArray[i].keyArea.intersect(x, y))
            {
                area = layout->callbackAreaArray[i];
                break;
            }
        }
    }
    return area;
}
References Keyboard::CallbackArea::callback, and Keyboard::layout.
Referenced by Keyboard::handleClickEvent().
getCharForKey()
Unicode::UnicodeChar getCharForKey (uint8_t keyId) const protected
Maps a keyId to the UnicodeChar being displayed by that key.
Parameters
keyId The id of the key to perform lookup with.
Returns
the UnicodeChar used for the specified key.
{
    Unicode::UnicodeChar ch = 0;
    if (keyMappingList != 0)
    {
        for (uint8_t i = 0; i < keyMappingList->numberOfKeys; i++)
        {
            if (keyMappingList->keyMappingArray[i].keyId == keyId)
            {
                ch = keyMappingList->keyMappingArray[i].keyValue;
                break;
            }
        }
    }
    return ch;
}
References Keyboard::keyMappingList.
Referenced by Keyboard::draw(), and Keyboard::handleClickEvent().
getKeyForCoordinates()
Keyboard::Key getKeyForCoordinates (int16_t x, int16_t y) const protected
Gets key for coordinates.
Parameters
x The x coordinate to perform key look up with.
y The y coordinate to perform key look up with.
Returns
The key for the given coordinates.
{
    Key key;
    key.keyId = 0; // No key
    if (layout != 0)
    {
        for (uint8_t i = 0; i < layout->numberOfKeys; i++)
        {
            if (layout->keyArray[i].keyArea.intersect(x, y))
            {
                key = layout->keyArray[i];
                break;
            }
        }
    }
    return key;
}
References Keyboard::Key::keyId, and Keyboard::layout.
Referenced by Keyboard::handleClickEvent().
getKeyMappingList()
const KeyMappingList * getKeyMappingList () const inline
Gets key mapping list.
Returns
The KeyMappingList used by the Keyboard.
    {
        return keyMappingList;
    }
References Keyboard::keyMappingList.
getLayout()
const Layout * getLayout () const inline
Gets the layout.
Returns
The layout used by the Keyboard.
See also
setLayout
    {
        return layout;
    }
References Keyboard::layout.
handleClickEvent()
void handleClickEvent (const ClickEvent & event) virtual
Overrides the handleClickEvent on the container. The keyboard handles all click events internally and click events are not propagated to drawables added to the keyboard.
Parameters
event The ClickEvent.
Reimplemented from Drawable.
{
    const ClickEvent::ClickEventType type = event.getType();
    if (type == ClickEvent::RELEASED && cancelIsEmitted)
    {
        cancelIsEmitted = false;
        return;
    }
    const int16_t x = event.getX();
    const int16_t y = event.getY();
    Rect toDraw;
    Keyboard::CallbackArea callbackArea = getCallbackAreaForCoordinates(x, y);
    if (callbackArea.callback != 0)
    {
        if (type == ClickEvent::PRESSED)
        {
            highlightImage.setXY(callbackArea.keyArea.x, callbackArea.keyArea.y);
            highlightImage.setBitmap(Bitmap(callbackArea.highlightBitmapId));
            highlightImage.setVisible(true);
            toDraw = highlightImage.getRect();
            invalidateRect(toDraw);
        }
        if ((type == ClickEvent::RELEASED) && callbackArea.callback->isValid())
        {
            callbackArea.callback->execute();
            if (keyListener)
            {
                keyListener->execute(0);
            }
        }
    }
    else
    {
        const Keyboard::Key key = getKeyForCoordinates(x, y);
        if (type == ClickEvent::PRESSED)
        {
            if (key.keyId != 0)
            {
                highlightImage.setXY(key.keyArea.x, key.keyArea.y);
                highlightImage.setBitmap(Bitmap(key.highlightBitmapId));
                highlightImage.setVisible(true);
                toDraw = highlightImage.getRect();
                invalidateRect(toDraw);
            }
        }
        if (type == ClickEvent::RELEASED)
        {
            if (key.keyId != 0 && buffer)
            {
                const Unicode::UnicodeChar c = getCharForKey(key.keyId);
                if (c != 0 && bufferPosition < (bufferSize - 1))
                {
                    enteredText.invalidateContent();
                    buffer[bufferPosition++] = c;
                    buffer[bufferPosition] = 0;
                    enteredText.invalidateContent();
                    if (keyListener)
                    {
                        keyListener->execute(c);
                    }
                }
            }
        }
    }
    if (type == ClickEvent::RELEASED || type == ClickEvent::CANCEL)
    {
        toDraw = highlightImage.getRect();
        highlightImage.setVisible(false);
        invalidateRect(toDraw);
        if (type == ClickEvent::CANCEL)
        {
            cancelIsEmitted = true;
        }
    }
}
References Keyboard::bufferPosition, Keyboard::bufferSize, ClickEvent::CANCEL, Keyboard::cancelIsEmitted, Keyboard::enteredText, GenericCallback< T1, T2, T3 >::execute(), Keyboard::getCallbackAreaForCoordinates(), Keyboard::getCharForKey(), Keyboard::getKeyForCoordinates(), Drawable::getRect(), Keyboard::Key::highlightBitmapId, Keyboard::highlightImage, TextAreaWithWildcardBase::invalidateContent(), Drawable::invalidateRect(), Keyboard::Key::keyArea, Keyboard::Key::keyId, Keyboard::keyListener, ClickEvent::PRESSED, ClickEvent::RELEASED, Image::setBitmap(), Drawable::setVisible(), Drawable::setXY(), Rect::x, and Rect::y.
Referenced by Keyboard::handleDragEvent().
handleDragEvent()
void handleDragEvent (const DragEvent & event) virtual
Overrides the handleDragEvent on the container. The keyboard handles drag events to enable the container to, emit a CANCEL, if the user drags outside the currently pressed key.
Parameters
event The DragEvent.
Reimplemented from Drawable.
{
    if (highlightImage.isVisible() && (!highlightImage.getRect().intersect(static_cast<int16_t>(event.getNewX()), static_cast<int16_t>(event.getNewY()))) && (!cancelIsEmitted))
    {
        // Send a CANCEL click event, if user has dragged out of currently pressed/highlighted key.
        const ClickEvent cancelEvent(ClickEvent::CANCEL, static_cast<int16_t>(event.getOldX()), static_cast<int16_t>(event.getOldY()));
        handleClickEvent(cancelEvent);
    }
}
References ClickEvent::CANCEL, Keyboard::cancelIsEmitted, Drawable::getRect(), Keyboard::handleClickEvent(), Keyboard::highlightImage, and Drawable::isVisible().
setBuffer()
void setBuffer (Unicode::UnicodeChar * newBuffer, uint16_t newBufferSize)
Sets the buffer to be used by the keyboard. Keys entered are added to the buffer.
Parameters
[in] newBuffer Pointer to a buffer holding the text edited by the keyboard. If the buffer is not empty, the edit position for the keyboard will be set to the end of the provided text.
newBufferSize Length of the buffer, i.e. number of UnicodeChar's.
See also
getBuffer
{
    buffer = newBuffer;
    bufferSize = newBufferSize;
    enteredText.setWildcard(buffer);
    // Place cursor at end of string if we already have something
    // in the edit buffer.
    bufferPosition = Unicode::strlen(buffer);
}
References Keyboard::bufferPosition, Keyboard::bufferSize, Keyboard::enteredText, TextAreaWithOneWildcard::setWildcard(), and Unicode::strlen().
setBufferPosition()
void setBufferPosition (uint16_t newPos)
Change the buffer position i.e. the next index to place a character when a key is pressed. This can be used to implement backspace functionality if the class using the Keyboard implements a callback and maps it to a backspace implementation. Setting the position will cause the TextArea displaying the text to be invalidated to request a redraw.
Parameters
newPos The buffer position.
See also
setTextIndentation
{
    bufferPosition = newPos;
    enteredText.invalidate();
}
References Keyboard::bufferPosition, Keyboard::enteredText, and Drawable::invalidate().
setKeyListener()
void setKeyListener (GenericCallback< Unicode::UnicodeChar > & callback) inline
Sets the callback for the keyboard. The callback will be executed every time a key is clicked. The callback argument contains the key that was just pressed.
Parameters
[in] callback The Callback to invoke.
Note
Backspace, shift and mode keys report a 0 as value.
    {
        keyListener = &callback;
    }
References Keyboard::keyListener.
setKeymappingList()
void setKeymappingList (const KeyMappingList * newKeyMappingList)
Set/change the KeyMappingList to use. The Keyboard will invalidate the space it occupies to request a redraw.
Parameters
newKeyMappingList The new KeyMappingList.
{
    keyMappingList = newKeyMappingList;
    invalidate();
}
References Drawable::invalidate(), and Keyboard::keyMappingList.
setLayout()
void setLayout (const Layout * newLayout)
Set/change the Keyboard::Layout to use.The Keyboard will invalidate the space it occupies to request a redraw.
Parameters
newLayout The new layout.
See also
getLayout
{
    layout = newLayout;
    if (newLayout != 0)
    {
        image.setBitmap(Bitmap(newLayout->bitmap));
        enteredText.setTypedText(newLayout->textAreaFont);
        enteredText.setColor(newLayout->textAreaFontColor);
        enteredText.setPosition(newLayout->textAreaPosition.x, newLayout->textAreaPosition.y,
                                newLayout->textAreaPosition.width, newLayout->textAreaPosition.height);
    }
    invalidate();
}
References Keyboard::enteredText, Drawable::invalidate(), Keyboard::layout, TextArea::setColor(), Drawable::setPosition(), and TextArea::setTypedText().
setTextIndentation()
void setTextIndentation ()
Sets text indentation by making the area for entered text slightly larger. The result is that some characters (often 'j' and '_') will not be cut off. Indentation is added to both sides of the text area in case the text is right-to-left. Indentation is automatically set so all characters will display properly.
See also
TextArea::setIndentation
{
    if (layout != 0)
    {
        const uint8_t indentation = layout->textAreaFont.getFont()->getMaxPixelsLeft();
        enteredText.setPosition(layout->textAreaPosition.x - indentation, layout->textAreaPosition.y,
                                layout->textAreaPosition.width + indentation * 2, layout->textAreaPosition.height);
        enteredText.setIndentation(indentation);
    }
}
References Keyboard::enteredText, Keyboard::layout, TextArea::setIndentation(), and Drawable::setPosition().
Member Data Documentation
buffer
Unicode::UnicodeChar* buffer protected
Pointer to null-terminated buffer where the entered text is being displayed.
Referenced by Keyboard::getBuffer().
bufferPosition
uint16_t bufferPosition protected
Current position in buffer.
Referenced by Keyboard::getBufferPosition(), Keyboard::handleClickEvent(), Keyboard::setBuffer(), and Keyboard::setBufferPosition().
bufferSize
uint16_t bufferSize protected
Size of the buffer.
Referenced by Keyboard::handleClickEvent(), and Keyboard::setBuffer().
cancelIsEmitted
bool cancelIsEmitted protected
Tells if a cancel is emitted to check when a key is released.
Referenced by Keyboard::handleClickEvent(), and Keyboard::handleDragEvent().
enteredText
TextAreaWithOneWildcard enteredText protected
Widget capable of displaying the entered text buffer.
Referenced by Keyboard::Keyboard(), Keyboard::handleClickEvent(), Keyboard::setBuffer(), Keyboard::setBufferPosition(), Keyboard::setLayout(), and Keyboard::setTextIndentation().
highlightImage
Image highlightImage protected
Image to display when a key is highlighted.
Referenced by Keyboard::Keyboard(), Keyboard::handleClickEvent(), and Keyboard::handleDragEvent().
image
Image image protected
Layout bitmap.
keyListener
GenericCallback<Unicode::UnicodeChar>* keyListener protected
Pointer to callback being executed when a key is pressed.
Referenced by Keyboard::handleClickEvent(), and Keyboard::setKeyListener().
keyMappingList
const KeyMappingList* keyMappingList protected
Pointer to key mapping.
Referenced by Keyboard::getCharForKey(), Keyboard::getKeyMappingList(), and Keyboard::setKeymappingList().
layout
const Layout* layout protected
Pointer to layout.
Referenced by Keyboard::draw(), Keyboard::getCallbackAreaForCoordinates(), Keyboard::getKeyForCoordinates(), Keyboard::getLayout(), Keyboard::setLayout(), and Keyboard::setTextIndentation().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/Keyboard.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/Keyboard.cpp