Battery Simulator Documentation: ZoomAnimationImage
ZoomAnimationImage
#include "ZoomAnimationImage.hpp"
Public Types
enum ZoomMode {
FIXED_CENTER , FIXED_LEFT , FIXED_RIGHT , FIXED_TOP ,
FIXED_BOTTOM , FIXED_LEFT_AND_TOP , FIXED_RIGHT_AND_TOP , FIXED_LEFT_AND_BOTTOM ,
FIXED_RIGHT_AND_BOTTOM
}
Public Member Functions
ZoomAnimationImage ()
void cancelZoomAnimation ()
virtual uint8_t getAlpha () const
virtual uint16_t getAnimationDelay () const
Bitmap getLargeBitmap () const
virtual ScalableImage::ScalingAlgorithm getScalingMode ()
Bitmap getSmallBitmap () const
virtual void handleTickEvent ()
virtual void invalidateContent () const
bool isZoomAnimationRunning () const
virtual void setAlpha (uint8_t newAlpha)
virtual void setAnimationDelay (uint16_t delay)
void setAnimationEndedCallback (GenericCallback< const ZoomAnimationImage & > &callback)
void setBitmaps (const Bitmap &smallBitmap, const Bitmap &largeBitmap)
virtual void setHeight (int16_t height)
virtual void setScalingMode (ScalableImage::ScalingAlgorithm mode)
virtual void setWidth (int16_t width)
void startZoomAndMoveAnimation (int16_t endX, int16_t endY, int16_t endWidth, int16_t endHeight, uint16_t duration, ZoomMode zoomMode=FIXED_LEFT_AND_TOP, EasingEquation xProgressionEquation=&EasingEquations::linearEaseNone, EasingEquation yProgressionEquation=&EasingEquations::linearEaseNone, EasingEquation widthProgressionEquation=&EasingEquations::linearEaseNone, EasingEquation heightProgressionEquation=&EasingEquations::linearEaseNone)
void startZoomAnimation (int16_t endWidth, int16_t endHeight, uint16_t duration, ZoomMode zoomMode=FIXED_LEFT_AND_TOP, EasingEquation widthProgressionEquation=&EasingEquations::linearEaseNone, EasingEquation heightProgressionEquation=&EasingEquations::linearEaseNone)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Types
enum States { ANIMATE_ZOOM , ANIMATE_ZOOM_AND_MOVE , NO_ANIMATION }
Protected Member Functions
virtual void setCurrentState (States state)
void startTimerAndSetParameters (int16_t endWidth, int16_t endHeight, uint16_t duration, ZoomMode zoomMode, EasingEquation widthProgressionEquation, EasingEquation heightProgressionEquation)
virtual void updateRenderingMethod ()
virtual void updateZoomAnimationDeltaXY ()
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
uint16_t animationCounter
The progress counter for the animation.
uint16_t animationDuration
Duration of the animation.
GenericCallback< const ZoomAnimationImage & > * animationEndedAction
The animation ended action.
States currentState
The current animation state.
ZoomMode currentZoomMode
The ZoomMode to use by the animation.
Image image
The image for displaying the bitmap when the width/height is equal one of the bitmaps.
Bitmap largeBmp
The bitmap representing the large image.
int16_t moveAnimationEndX
The move animation end x coordinate.
int16_t moveAnimationEndY
The move animation end y coordinate.
EasingEquation moveAnimationXEquation
The move animation x coordinate equation.
EasingEquation moveAnimationYEquation
The move animation y coordinate equation.
ScalableImage scalableImage
The scalable image for displaying the bitmap when the width/height is not equal one of the bitmaps.
Bitmap smallBmp
The bitmap representing the small image.
uint16_t zoomAnimationDelay
A delay that is applied before animation start. Expressed in ticks.
int16_t zoomAnimationDeltaX
The zoom animation delta x.
int16_t zoomAnimationDeltaY
The zoom animation delta y.
int16_t zoomAnimationEndHeight
Height of the zoom animation end.
int16_t zoomAnimationEndWidth
Width of the zoom animation end.
EasingEquation zoomAnimationHeightEquation
The zoom animation height equation.
int16_t zoomAnimationStartHeight
Height of the zoom animation start.
int16_t zoomAnimationStartWidth
Width of the zoom animation start.
int16_t zoomAnimationStartX
The zoom animation start x coordinate.
int16_t zoomAnimationStartY
The zoom animation start y coordinate.
EasingEquation zoomAnimationWidthEquation
The zoom animation width equation.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
Class for optimizing and wrapping move and zoom operations on a ScalableImage. The ZoomAnimationImage takes two bitmaps representing the same image but at a small and a large resolution. These bitmaps should be the sizes that are used when not animating the image. The ZoomAnimationImage will use an Image for displaying the Bitmap when its width and height matches either of them. When it does not match the size of one of the bitmaps, it will use a ScalableImage instead. The main idea is that the supplied bitmaps should be the end points of the zoom animation so that it ends up using an Image when not animating. This is, however, not a requirement. You can animate from and to sizes that are not equal the sizes of the bitmaps. The result is a container that has the high performance of an ordinary image when the size matches the pre-rendered bitmaps. Moreover it supplies easy to use animation functions that lets you zoom and move the image.
Note
Since this container uses the ScalableImage it has the same restrictions as a ScaleableImage, i.e. 1bpp is not supported.
Member Enumeration Documentation
States
enum States protected
Animation states.
Enumerator
ANIMATE_ZOOM
Zoom animation state.
ANIMATE_ZOOM_AND_MOVE
Zoom and move animation state.
NO_ANIMATION
No animation state.
    {
        ANIMATE_ZOOM,
        ANIMATE_ZOOM_AND_MOVE,
        NO_ANIMATION
    };
ZoomMode
enum ZoomMode
A ZoomMode describes in which direction the image will grow/shrink when do a zoom animation. A FIXED direction means that the image will not grow/shrink in that direction.
Enumerator
FIXED_CENTER
The small image will grow from the center of the large image.
FIXED_LEFT
The small image will grow from the middle of the left side of the large image.
FIXED_RIGHT
The small image will grow from the middle of the right side of the large image.
FIXED_TOP
The small image will grow from the middle of the top of the large image.
FIXED_BOTTOM
The small image will grow from the middle of the bottom of the large image.
FIXED_LEFT_AND_TOP
The small image will grow from the top left corner of the large image.
FIXED_RIGHT_AND_TOP
The small image will grow from the top right corner of the large image.
FIXED_LEFT_AND_BOTTOM
The small image will grow from the bottom left corner of the large image.
FIXED_RIGHT_AND_BOTTOM
The small image will grow from the bottom right corner of the large image.
    {
        FIXED_CENTER,
        FIXED_LEFT,
        FIXED_RIGHT,
        FIXED_TOP,
        FIXED_BOTTOM,
        FIXED_LEFT_AND_TOP,
        FIXED_RIGHT_AND_TOP,
        FIXED_LEFT_AND_BOTTOM,
        FIXED_RIGHT_AND_BOTTOM
    };
Constructor & Destructor Documentation
ZoomAnimationImage()
ZoomAnimationImage ()
    : Container(),
      currentState(NO_ANIMATION),
      animationCounter(0),
      zoomAnimationDelay(0),
      smallBmp(),
      largeBmp(),
      image(),
      scalableImage(),
      currentZoomMode(FIXED_LEFT_AND_TOP),
      zoomAnimationStartWidth(0),
      zoomAnimationStartHeight(0),
      zoomAnimationEndWidth(0),
      zoomAnimationEndHeight(0),
      zoomAnimationStartX(0),
      zoomAnimationStartY(0),
      zoomAnimationDeltaX(0),
      zoomAnimationDeltaY(0),
      moveAnimationEndX(0),
      moveAnimationEndY(0),
      animationDuration(0),
      zoomAnimationWidthEquation(EasingEquations::linearEaseNone),
      zoomAnimationHeightEquation(EasingEquations::linearEaseNone),
      moveAnimationXEquation(EasingEquations::linearEaseNone),
      moveAnimationYEquation(EasingEquations::linearEaseNone),
      animationEndedAction(0)
{
    image.setXY(0, 0);
    image.setVisible(false);
    scalableImage.setScalingAlgorithm(ScalableImage::NEAREST_NEIGHBOR);
    scalableImage.setXY(0, 0);
    scalableImage.setVisible(false);
    Container::add(image);
    Container::add(scalableImage);
}
References Container::add(), ScalableImage::NEAREST_NEIGHBOR, ZoomAnimationImage::scalableImage, ScalableImage::setScalingAlgorithm(), Drawable::setVisible(), and Drawable::setXY().
Member Function Documentation
cancelZoomAnimation()
void cancelZoomAnimation ()
Cancel zoom animation. The image is left in the position and size it is currently at.
{
    Application::getInstance()->unregisterTimerWidget(this);
    setCurrentState(NO_ANIMATION);
}
References Application::getInstance(), ZoomAnimationImage::NO_ANIMATION, and ZoomAnimationImage::setCurrentState().
Referenced by ZoomAnimationImage::handleTickEvent().
getAlpha()
uint8_t getAlpha () const virtual
Gets the current alpha value of the widget. The alpha value is in range 255 (solid) to 0 (invisible).
Returns
The current alpha value.
See also
setAlpha
{
    return image.getAlpha();
}
Referenced by ZoomAnimationImage::invalidateContent().
getAnimationDelay()
uint16_t getAnimationDelay () const virtual
Gets the current animation delay.
Returns
The current animation delay. Expressed in ticks.
See also
setAnimationDelay
{
    return zoomAnimationDelay;
}
References ZoomAnimationImage::zoomAnimationDelay.
getLargeBitmap()
Bitmap getLargeBitmap () const inline
Gets the large bitmap.
Returns
the large bitmap.
See also
setBitmaps
    {
        return largeBmp;
    }
References ZoomAnimationImage::largeBmp.
getScalingMode()
ScalableImage::ScalingAlgorithm getScalingMode () virtual
Gets the scaling algorithm of the ScalableImage.
Returns
the scaling algorithm used.
See also
setScalingMode
{
    return scalableImage.getScalingAlgorithm();
}
References ScalableImage::getScalingAlgorithm(), and ZoomAnimationImage::scalableImage.
getSmallBitmap()
Bitmap getSmallBitmap () const inline
Gets the small bitmap.
Returns
the small bitmap.
See also
setBitmaps
    {
        return smallBmp;
    }
References ZoomAnimationImage::smallBmp.
handleTickEvent()
void handleTickEvent () virtual
Called periodically by the framework if the Drawable instance has subscribed to timer ticks.
See also
Application::registerTimerWidget
Reimplemented from Drawable.
{
    if ((currentState == ANIMATE_ZOOM) || (currentState == ANIMATE_ZOOM_AND_MOVE))
    {
        animationCounter++;
        if (animationCounter >= zoomAnimationDelay)
        {
            // Adjust the used animationCounter for the startup delay
            const uint16_t actualAnimationCounter = animationCounter - zoomAnimationDelay;
            const int16_t deltaWidth = zoomAnimationWidthEquation(actualAnimationCounter, 0, zoomAnimationEndWidth - zoomAnimationStartWidth, animationDuration);
            const int16_t deltaHeight = zoomAnimationHeightEquation(actualAnimationCounter, 0, zoomAnimationEndHeight - zoomAnimationStartHeight, animationDuration);
            setWidthHeight(zoomAnimationStartWidth + deltaWidth, zoomAnimationStartHeight + deltaHeight);
            int16_t deltaX;
            int16_t deltaY;
            if (currentState == ANIMATE_ZOOM_AND_MOVE)
            {
                deltaX = moveAnimationXEquation(actualAnimationCounter, 0, (moveAnimationEndX - zoomAnimationStartX) + zoomAnimationDeltaX, animationDuration);
                deltaY = moveAnimationYEquation(actualAnimationCounter, 0, (moveAnimationEndY - zoomAnimationStartY) + zoomAnimationDeltaY, animationDuration);
            }
            else
            {
                deltaX = zoomAnimationWidthEquation(actualAnimationCounter, 0, zoomAnimationDeltaX, animationDuration);
                deltaY = zoomAnimationHeightEquation(actualAnimationCounter, 0, zoomAnimationDeltaY, animationDuration);
            }
            moveTo(zoomAnimationStartX + deltaX, zoomAnimationStartY + deltaY);
            if (animationCounter >= zoomAnimationDelay + animationDuration)
            {
                cancelZoomAnimation();
                if (animationEndedAction && animationEndedAction->isValid())
                {
                    animationEndedAction->execute(*this);
                }
            }
        }
    }
}
References ZoomAnimationImage::ANIMATE_ZOOM, ZoomAnimationImage::ANIMATE_ZOOM_AND_MOVE, ZoomAnimationImage::animationCounter, ZoomAnimationImage::animationDuration, ZoomAnimationImage::animationEndedAction, ZoomAnimationImage::cancelZoomAnimation(), ZoomAnimationImage::currentState, ZoomAnimationImage::moveAnimationEndX, ZoomAnimationImage::moveAnimationEndY, ZoomAnimationImage::moveAnimationXEquation, ZoomAnimationImage::moveAnimationYEquation, Drawable::moveTo(), Drawable::setWidthHeight(), ZoomAnimationImage::zoomAnimationDelay, ZoomAnimationImage::zoomAnimationDeltaX, ZoomAnimationImage::zoomAnimationDeltaY, ZoomAnimationImage::zoomAnimationEndHeight, ZoomAnimationImage::zoomAnimationEndWidth, ZoomAnimationImage::zoomAnimationHeightEquation, ZoomAnimationImage::zoomAnimationStartHeight, ZoomAnimationImage::zoomAnimationStartWidth, ZoomAnimationImage::zoomAnimationStartX, ZoomAnimationImage::zoomAnimationStartY, and ZoomAnimationImage::zoomAnimationWidthEquation.
Referenced by ZoomAnimationImage::startTimerAndSetParameters().
invalidateContent()
virtual void invalidateContent () const inline virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from Drawable.
    {
        if (getAlpha() > 0)
        {
            Container::invalidateContent();
        }
    }
References ZoomAnimationImage::getAlpha(), and Drawable::invalidateContent().
isZoomAnimationRunning()
bool isZoomAnimationRunning () const
Is there currently an animation running.
Returns
true if there is an animation running.
{
    return currentState != NO_ANIMATION;
}
References ZoomAnimationImage::currentState, and ZoomAnimationImage::NO_ANIMATION.
setAlpha()
void setAlpha (uint8_t newAlpha) virtual
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
{
    image.setAlpha(newAlpha);
    scalableImage.setAlpha(newAlpha);
}
References ZoomAnimationImage::scalableImage, and Image::setAlpha().
setAnimationDelay()
void setAnimationDelay (uint16_t delay) virtual
Sets a delay on animations done by the ZoomAnimationImage. Defaults to 0 which means that the animation starts immediately.
Parameters
delay The delay in ticks.
See also
getAnimationDelay
{
    zoomAnimationDelay = delay;
}
References ZoomAnimationImage::zoomAnimationDelay.
setAnimationEndedCallback()
void setAnimationEndedCallback (GenericCallback< const ZoomAnimationImage & > & callback) inline
Associates an action to be performed when the animation ends.
Parameters
callback The callback to be executed. The callback will be given a reference to the ZoomAnimationImage.
See also
GenericCallback
    {
        animationEndedAction = &callback;
    }
References ZoomAnimationImage::animationEndedAction.
setBitmaps()
void setBitmaps (const Bitmap & smallBitmap, const Bitmap & largeBitmap)
Initializes the bitmap of the image to be used. The bitmaps should represent the same image in the two needed static resolutions.
Parameters
smallBitmap The image in the smallest resolution.
largeBitmap The image in the largest resolution.
See also
getSmallBitmap, getLargeBitmap
Note
The size of the bitmaps do not in any way limit the size of the ZoomAnimationImage and it is possible to scale the image beyond the sizes of these bitmaps.
{
    smallBmp = smallBitmap;
    largeBmp = largeBitmap;
    scalableImage.setBitmap(largeBmp);
    ZoomAnimationImage::setWidthHeight(largeBmp);
}
References ZoomAnimationImage::largeBmp, ZoomAnimationImage::scalableImage, Image::setBitmap(), Drawable::setWidthHeight(), and ZoomAnimationImage::smallBmp.
setCurrentState()
void setCurrentState (States state) protected virtual
Sets the current animation state and reset the animation counter.
Parameters
state The new state.
{
    currentState = state;
    animationCounter = 0;
}
References ZoomAnimationImage::animationCounter, ZoomAnimationImage::currentState, and state.
Referenced by ZoomAnimationImage::cancelZoomAnimation(), ZoomAnimationImage::startZoomAndMoveAnimation(), and ZoomAnimationImage::startZoomAnimation().
setHeight()
void setHeight (int16_t height) virtual
Sets the height of this drawable.
Parameters
height The new height.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
ZoomAnimationImage diverts from the normal behavior by automatically invalidating which causes a redraw.
Reimplemented from Drawable.
{
    invalidate();
    Container::setHeight(height);
    updateRenderingMethod();
}
References Drawable::invalidate(), Drawable::setHeight(), and ZoomAnimationImage::updateRenderingMethod().
setScalingMode()
void setScalingMode (ScalableImage::ScalingAlgorithm mode) virtual
Sets the algorithm to be used. In short, there is currently a value for fast (nearest neighbor) and a value for slow (bilinear interpolation). Default is ScalableImage::NEAREST_NEIGHBOR since moving images do not need to be of the best quality, until they stop moving. If the image moves only a little bit, or moves/resizes slowly, consider using ScaleableImage::BILINEAR_INTERPOLATION.
Parameters
mode The algorithm to use when rendering.
See also
ScalableImage::ScalingAlgorithm, getScalingMode
{
    scalableImage.setScalingAlgorithm(mode);
}
References ZoomAnimationImage::scalableImage, and ScalableImage::setScalingAlgorithm().
setWidth()
void setWidth (int16_t width) virtual
Sets the width of this drawable.
Parameters
width The new width.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
ZoomAnimationImage diverts from the normal behavior by automatically invalidating which causes a redraw.
Reimplemented from Drawable.
{
    invalidate();
    Container::setWidth(width);
    updateRenderingMethod();
}
References Drawable::invalidate(), Drawable::setWidth(), and ZoomAnimationImage::updateRenderingMethod().
startTimerAndSetParameters()
void startTimerAndSetParameters (int16_t endWidth, int16_t endHeight, uint16_t duration, ZoomMode zoomMode, EasingEquation widthProgressionEquation, EasingEquation heightProgressionEquation) protected
Starts timer and set parameters. Contains code shared between startZoomAnimation() and startZoomAndMoveAnimation(). If both delay and duration is zero, the end position and size is applied and the animation is ended immediately.
Parameters
endWidth The end width.
endHeight The end height.
duration The duration.
zoomMode The zoom mode.
widthProgressionEquation The width progression equation.
heightProgressionEquation The height progression equation.
{
    Application::getInstance()->registerTimerWidget(this);
    currentZoomMode = zoomMode;
    zoomAnimationStartX = getX();
    zoomAnimationStartY = getY();
    zoomAnimationStartWidth = getWidth();
    zoomAnimationStartHeight = getHeight();
    zoomAnimationEndWidth = endWidth;
    zoomAnimationEndHeight = endHeight;
    animationDuration = duration;
    zoomAnimationWidthEquation = widthProgressionEquation;
    zoomAnimationHeightEquation = heightProgressionEquation;
    updateZoomAnimationDeltaXY();
    if (zoomAnimationDelay == 0 && animationDuration == 0)
    {
        handleTickEvent(); // Finish the zoom and move operation immediately
    }
}
References ZoomAnimationImage::animationDuration, ZoomAnimationImage::currentZoomMode, Drawable::getHeight(), Application::getInstance(), Drawable::getWidth(), Drawable::getX(), Drawable::getY(), ZoomAnimationImage::handleTickEvent(), ZoomAnimationImage::updateZoomAnimationDeltaXY(), ZoomAnimationImage::zoomAnimationDelay, ZoomAnimationImage::zoomAnimationEndHeight, ZoomAnimationImage::zoomAnimationEndWidth, ZoomAnimationImage::zoomAnimationHeightEquation, ZoomAnimationImage::zoomAnimationStartHeight, ZoomAnimationImage::zoomAnimationStartWidth, ZoomAnimationImage::zoomAnimationStartX, ZoomAnimationImage::zoomAnimationStartY, and ZoomAnimationImage::zoomAnimationWidthEquation.
Referenced by ZoomAnimationImage::startZoomAndMoveAnimation(), and ZoomAnimationImage::startZoomAnimation().
startZoomAndMoveAnimation()
void startZoomAndMoveAnimation (int16_t endX, int16_t endY, int16_t endWidth, int16_t endHeight, uint16_t duration, ZoomMode zoomMode = FIXED_LEFT_AND_TOP, EasingEquation xProgressionEquation = &EasingEquations::linearEaseNone, EasingEquation yProgressionEquation = &EasingEquations::linearEaseNone, EasingEquation widthProgressionEquation = &EasingEquations::linearEaseNone, EasingEquation heightProgressionEquation = &EasingEquations::linearEaseNone)
Setup and starts the zoom and move animation. At end of the animation the image will have been resized to the endWidth and endHeight and have moved from its original position to the endX and endY. Please note that the ZoomMode might influence the actual end position since the zoom transformation might change the X and Y of the image. The ZoomMode FIXED_LEFT_AND_TOP ensures that the endX and endY will be the actual end position.
The development of the width, height, X and Y during the animation is described by the supplied EasingEquations. The container is registered as a TimerWidget and automatically unregistered when the animation has finished.
Parameters
endX The X position of the image at animation end. Relative to the container or view that holds the ZoomAnimationImage.
endY The Y position of the image at animation end. Relative to the container or view that holds the ZoomAnimationImage.
endWidth The width of the image at animation end.
endHeight The height of the image at animation end.
duration The duration of the animation measured in ticks.
zoomMode (Optional) The zoom mode that will be used during the animation. Default is FIXED_LEFT_AND_TOP.
xProgressionEquation (Optional) The equation that describes the development of the X position during the animation. Default is EasingEquations::linearEaseNone.
yProgressionEquation (Optional) The equation that describes the development of the Y position during the animation. Default is EasingEquations::linearEaseNone.
widthProgressionEquation (Optional) The equation that describes the development of the width during the animation. Default is EasingEquations::linearEaseNone.
heightProgressionEquation (Optional) The equation that describes the development of the height during the animation. Default is EasingEquations::linearEaseNone.
{
    moveAnimationEndX = endX;
    moveAnimationEndY = endY;
    moveAnimationXEquation = xProgressionEquation;
    moveAnimationYEquation = yProgressionEquation;
    setCurrentState(ANIMATE_ZOOM_AND_MOVE);
    startTimerAndSetParameters(endWidth, endHeight, duration, zoomMode, widthProgressionEquation, heightProgressionEquation);
}
References ZoomAnimationImage::ANIMATE_ZOOM_AND_MOVE, ZoomAnimationImage::moveAnimationEndX, ZoomAnimationImage::moveAnimationEndY, ZoomAnimationImage::moveAnimationXEquation, ZoomAnimationImage::moveAnimationYEquation, ZoomAnimationImage::setCurrentState(), and ZoomAnimationImage::startTimerAndSetParameters().
startZoomAnimation()
void startZoomAnimation (int16_t endWidth, int16_t endHeight, uint16_t duration, ZoomMode zoomMode = FIXED_LEFT_AND_TOP, EasingEquation widthProgressionEquation = &EasingEquations::linearEaseNone, EasingEquation heightProgressionEquation = &EasingEquations::linearEaseNone)
Setup and starts the zoom animation. At end of the animation the image will have been resized to the endWidth and endHeight. The development of the width and height during the animation is described by the supplied EasingEquations. The container is registered as a TimerWidget and automatically unregistered when the animation has finished.
Parameters
endWidth The width of the image at animation end.
endHeight The height of the image at animation end.
duration The duration of the animation measured in ticks.
zoomMode (Optional) The zoom mode that will be used during the animation. Default is FIXED_LEFT_AND_TOP.
widthProgressionEquation (Optional) The equation that describes the development of the width during the animation. Default is EasingEquations::linearEaseNone.
heightProgressionEquation (Optional) The equation that describes the development of the height during the animation. Default is EasingEquations::linearEaseNone.
Note
The animation follows the specified ZoomMode so the X and Y coordinates of the image might change during animation.
{
    setCurrentState(ANIMATE_ZOOM);
    startTimerAndSetParameters(endWidth, endHeight, duration, zoomMode, widthProgressionEquation, heightProgressionEquation);
}
References ZoomAnimationImage::ANIMATE_ZOOM, ZoomAnimationImage::setCurrentState(), and ZoomAnimationImage::startTimerAndSetParameters().
updateRenderingMethod()
void updateRenderingMethod () protected virtual
Chooses the optimal rendering of the image given the current width and height. If the dimensions match either the small or large bitmap, that will be used, otherwise the large image will be scaled using the defined scaling mode.
See also
setScalingMode, setBitmaps
{
    if ((smallBmp.getWidth() == getWidth()) && (smallBmp.getHeight() == getHeight()))
    {
        image.setBitmap(smallBmp); // Updates width and height
        image.setVisible(true);
        scalableImage.setVisible(false);
    }
    else if ((largeBmp.getWidth() == getWidth()) && (largeBmp.getHeight() == getHeight()))
    {
        image.setBitmap(largeBmp); // Updates width and height
        image.setVisible(true);
        scalableImage.setVisible(false);
    }
    else
    {
        image.setVisible(false);
        scalableImage.setVisible(true);
        scalableImage.setWidthHeight(*this);
    }
    Container::invalidate();
}
References Bitmap::getHeight(), Drawable::getHeight(), Bitmap::getWidth(), Drawable::getWidth(), Drawable::invalidate(), ZoomAnimationImage::largeBmp, ZoomAnimationImage::scalableImage, Drawable::setVisible(), Drawable::setWidthHeight(), and ZoomAnimationImage::smallBmp.
Referenced by ZoomAnimationImage::setHeight(), and ZoomAnimationImage::setWidth().
updateZoomAnimationDeltaXY()
void updateZoomAnimationDeltaXY () protected virtual
Calculates the change in X and Y caused by the zoom animation given the current ZoomMode.
{
    zoomAnimationDeltaX = zoomAnimationStartWidth - zoomAnimationEndWidth;
    zoomAnimationDeltaY = zoomAnimationStartHeight - zoomAnimationEndHeight;
    switch (currentZoomMode)
    {
    case FIXED_CENTER:
        zoomAnimationDeltaX /= 2;
        zoomAnimationDeltaY /= 2;
        break;
    case FIXED_LEFT:
        zoomAnimationDeltaX = 0;
        zoomAnimationDeltaY /= 2;
        break;
    case FIXED_RIGHT:
        zoomAnimationDeltaY /= 2;
        break;
    case FIXED_TOP:
        zoomAnimationDeltaX /= 2;
        zoomAnimationDeltaY = 0;
        break;
    case FIXED_BOTTOM:
        zoomAnimationDeltaX /= 2;
        break;
    case FIXED_LEFT_AND_TOP:
        zoomAnimationDeltaX = 0;
        zoomAnimationDeltaY = 0;
        break;
    case FIXED_RIGHT_AND_TOP:
        zoomAnimationDeltaY = 0;
        break;
    case FIXED_LEFT_AND_BOTTOM:
        zoomAnimationDeltaX = 0;
        break;
    case FIXED_RIGHT_AND_BOTTOM:
        break;
    }
}
References ZoomAnimationImage::currentZoomMode, ZoomAnimationImage::FIXED_BOTTOM, ZoomAnimationImage::FIXED_CENTER, ZoomAnimationImage::FIXED_LEFT, ZoomAnimationImage::FIXED_LEFT_AND_BOTTOM, ZoomAnimationImage::FIXED_LEFT_AND_TOP, ZoomAnimationImage::FIXED_RIGHT, ZoomAnimationImage::FIXED_RIGHT_AND_BOTTOM, ZoomAnimationImage::FIXED_RIGHT_AND_TOP, ZoomAnimationImage::FIXED_TOP, ZoomAnimationImage::zoomAnimationDeltaX, ZoomAnimationImage::zoomAnimationDeltaY, ZoomAnimationImage::zoomAnimationEndHeight, ZoomAnimationImage::zoomAnimationEndWidth, ZoomAnimationImage::zoomAnimationStartHeight, and ZoomAnimationImage::zoomAnimationStartWidth.
Referenced by ZoomAnimationImage::startTimerAndSetParameters().
Member Data Documentation
animationCounter
uint16_t animationCounter protected
The progress counter for the animation.
Referenced by ZoomAnimationImage::handleTickEvent(), and ZoomAnimationImage::setCurrentState().
animationDuration
uint16_t animationDuration protected
Duration of the animation.
Referenced by ZoomAnimationImage::handleTickEvent(), and ZoomAnimationImage::startTimerAndSetParameters().
animationEndedAction
GenericCallback<const ZoomAnimationImage&>* animationEndedAction protected
The animation ended action.
Referenced by ZoomAnimationImage::handleTickEvent(), and ZoomAnimationImage::setAnimationEndedCallback().
currentState
States currentState protected
The current animation state.
Referenced by ZoomAnimationImage::handleTickEvent(), ZoomAnimationImage::isZoomAnimationRunning(), and ZoomAnimationImage::setCurrentState().
currentZoomMode
ZoomMode currentZoomMode protected
The ZoomMode to use by the animation.
Referenced by ZoomAnimationImage::startTimerAndSetParameters(), and ZoomAnimationImage::updateZoomAnimationDeltaXY().
image
Image image protected
The image for displaying the bitmap when the width/height is equal one of the bitmaps.
largeBmp
Bitmap largeBmp protected
The bitmap representing the large image.
Referenced by ZoomAnimationImage::getLargeBitmap(), ZoomAnimationImage::setBitmaps(), and ZoomAnimationImage::updateRenderingMethod().
moveAnimationEndX
int16_t moveAnimationEndX protected
The move animation end x coordinate.
Referenced by ZoomAnimationImage::handleTickEvent(), and ZoomAnimationImage::startZoomAndMoveAnimation().
moveAnimationEndY
int16_t moveAnimationEndY protected
The move animation end y coordinate.
Referenced by ZoomAnimationImage::handleTickEvent(), and ZoomAnimationImage::startZoomAndMoveAnimation().
moveAnimationXEquation
EasingEquation moveAnimationXEquation protected
The move animation x coordinate equation.
Referenced by ZoomAnimationImage::handleTickEvent(), and ZoomAnimationImage::startZoomAndMoveAnimation().
moveAnimationYEquation
EasingEquation moveAnimationYEquation protected
The move animation y coordinate equation.
Referenced by ZoomAnimationImage::handleTickEvent(), and ZoomAnimationImage::startZoomAndMoveAnimation().
scalableImage
ScalableImage scalableImage protected
The scalable image for displaying the bitmap when the width/height is not equal one of the bitmaps.
Referenced by ZoomAnimationImage::ZoomAnimationImage(), ZoomAnimationImage::getScalingMode(), ZoomAnimationImage::setAlpha(), ZoomAnimationImage::setBitmaps(), ZoomAnimationImage::setScalingMode(), and ZoomAnimationImage::updateRenderingMethod().
smallBmp
Bitmap smallBmp protected
The bitmap representing the small image.
Referenced by ZoomAnimationImage::getSmallBitmap(), ZoomAnimationImage::setBitmaps(), and ZoomAnimationImage::updateRenderingMethod().
zoomAnimationDelay
uint16_t zoomAnimationDelay protected
A delay that is applied before animation start. Expressed in ticks.
Referenced by ZoomAnimationImage::getAnimationDelay(), ZoomAnimationImage::handleTickEvent(), ZoomAnimationImage::setAnimationDelay(), and ZoomAnimationImage::startTimerAndSetParameters().
zoomAnimationDeltaX
int16_t zoomAnimationDeltaX protected
The zoom animation delta x.
Referenced by ZoomAnimationImage::handleTickEvent(), and ZoomAnimationImage::updateZoomAnimationDeltaXY().
zoomAnimationDeltaY
int16_t zoomAnimationDeltaY protected
The zoom animation delta y.
Referenced by ZoomAnimationImage::handleTickEvent(), and ZoomAnimationImage::updateZoomAnimationDeltaXY().
zoomAnimationEndHeight
int16_t zoomAnimationEndHeight protected
Height of the zoom animation end.
Referenced by ZoomAnimationImage::handleTickEvent(), ZoomAnimationImage::startTimerAndSetParameters(), and ZoomAnimationImage::updateZoomAnimationDeltaXY().
zoomAnimationEndWidth
int16_t zoomAnimationEndWidth protected
Width of the zoom animation end.
Referenced by ZoomAnimationImage::handleTickEvent(), ZoomAnimationImage::startTimerAndSetParameters(), and ZoomAnimationImage::updateZoomAnimationDeltaXY().
zoomAnimationHeightEquation
EasingEquation zoomAnimationHeightEquation protected
The zoom animation height equation.
Referenced by ZoomAnimationImage::handleTickEvent(), and ZoomAnimationImage::startTimerAndSetParameters().
zoomAnimationStartHeight
int16_t zoomAnimationStartHeight protected
Height of the zoom animation start.
Referenced by ZoomAnimationImage::handleTickEvent(), ZoomAnimationImage::startTimerAndSetParameters(), and ZoomAnimationImage::updateZoomAnimationDeltaXY().
zoomAnimationStartWidth
int16_t zoomAnimationStartWidth protected
Width of the zoom animation start.
Referenced by ZoomAnimationImage::handleTickEvent(), ZoomAnimationImage::startTimerAndSetParameters(), and ZoomAnimationImage::updateZoomAnimationDeltaXY().
zoomAnimationStartX
int16_t zoomAnimationStartX protected
The zoom animation start x coordinate.
Referenced by ZoomAnimationImage::handleTickEvent(), and ZoomAnimationImage::startTimerAndSetParameters().
zoomAnimationStartY
int16_t zoomAnimationStartY protected
The zoom animation start y coordinate.
Referenced by ZoomAnimationImage::handleTickEvent(), and ZoomAnimationImage::startTimerAndSetParameters().
zoomAnimationWidthEquation
EasingEquation zoomAnimationWidthEquation protected
The zoom animation width equation.
Referenced by ZoomAnimationImage::handleTickEvent(), and ZoomAnimationImage::startTimerAndSetParameters().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/ZoomAnimationImage.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/ZoomAnimationImage.cpp