Battery Simulator Documentation: StaticDataGraph
StaticDataGraph abstract
#include "AbstractDataGraph.hpp"
Public Member Functions
StaticDataGraph (int16_t capacity, int *xvalues, int *yvalues)
FORCE_INLINE_FUNCTION int16_t addDataPoint (float x, float y)
FORCE_INLINE_FUNCTION int16_t addDataPoint (int x, int y)
FORCE_INLINE_FUNCTION int16_t addDataPointScaled (int x, int y)
FORCE_INLINE_FUNCTION int deleteDataPoint (float x)
FORCE_INLINE_FUNCTION int deleteDataPoint (int x)
FORCE_INLINE_FUNCTION int16_t deleteDataPointIndex (int index)
FORCE_INLINE_FUNCTION int16_t deleteDataPointScaled (int x)
virtual int indexToDataPointXScaled (int16_t index) const
virtual int indexToDataPointYScaled (int16_t index) const
virtual void setGraphRangeXAutoScaled (bool showYaxis, int margin)
virtual void setGraphRangeYAutoScaled (bool showXaxis=true, int margin=0)
virtual void setScaleX (int scale, bool updateData=false)
virtual void setScaleY (int scale, bool updateData=false)
Public Member Functions inherited from AbstractDataGraph
AbstractDataGraph (int16_t capacity)
void addBottomElement (AbstractGraphDecoration &d)
void addGraphElement (AbstractGraphElement &d)
void addLeftElement (AbstractGraphDecoration &d)
void addRightElement (AbstractGraphDecoration &d)
void addTopElement (AbstractGraphDecoration &d)
virtual void clear ()
FORCE_INLINE_FUNCTION int float2scaledX (float f) const
FORCE_INLINE_FUNCTION int float2scaledY (float f) const
FORCE_INLINE_FUNCTION uint8_t getAlpha () const
FORCE_INLINE_FUNCTION int16_t getGapBeforeIndex () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaHeight () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaHeightIncludingPadding () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginBottom () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginLeft () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginRight () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginTop () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingBottom () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingLeft () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingRight () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingTop () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaWidth () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaWidthIncludingPadding () const
virtual float getGraphRangeXMaxAsFloat () const
virtual int getGraphRangeXMaxAsInt () const
virtual int getGraphRangeXMaxScaled () const
virtual float getGraphRangeXMinAsFloat () const
virtual int getGraphRangeXMinAsInt () const
virtual int getGraphRangeXMinScaled () const
virtual float getGraphRangeYMaxAsFloat () const
virtual int getGraphRangeYMaxAsInt () const
virtual int getGraphRangeYMaxScaled () const
virtual float getGraphRangeYMinAsFloat () const
virtual int getGraphRangeYMinAsInt () const
virtual int getGraphRangeYMinScaled () const
FORCE_INLINE_FUNCTION int16_t getMaxCapacity () const
virtual bool getNearestIndexForScreenX (int16_t x, int16_t &index) const
virtual bool getNearestIndexForScreenXY (int16_t x, int16_t y, int16_t &index)
virtual int getScaleX () const
virtual int getScaleY () const
FORCE_INLINE_FUNCTION int16_t getUsedCapacity () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
FORCE_INLINE_FUNCTION void indexToDataPoint (int16_t index, float &xvalue, float &yvalue) const
FORCE_INLINE_FUNCTION void indexToDataPoint (int16_t index, int &xvalue, int &yvalue) const
FORCE_INLINE_FUNCTION void indexToDataPointScaled (int16_t index, int &xvalue, int &yvalue) const
FORCE_INLINE_FUNCTION float indexToDataPointXAsFloat (int16_t index) const
FORCE_INLINE_FUNCTION int indexToDataPointXAsInt (int16_t index) const
FORCE_INLINE_FUNCTION float indexToDataPointYAsFloat (int16_t index) const
FORCE_INLINE_FUNCTION int indexToDataPointYAsInt (int16_t index) const
FORCE_INLINE_FUNCTION int16_t indexToScreenX (int16_t index) const
FORCE_INLINE_FUNCTION int16_t indexToScreenY (int16_t index) const
FORCE_INLINE_FUNCTION int int2scaledX (int i) const
FORCE_INLINE_FUNCTION int int2scaledY (int i) const
virtual void invalidateContent () const
FORCE_INLINE_FUNCTION float scaled2floatX (int i) const
FORCE_INLINE_FUNCTION float scaled2floatY (int i) const
FORCE_INLINE_FUNCTION int scaled2intX (int i) const
FORCE_INLINE_FUNCTION int scaled2intY (int i) const
virtual void setAlpha (uint8_t newAlpha)
FORCE_INLINE_FUNCTION void setClickAction (GenericCallback< const AbstractDataGraph &, const GraphClickEvent & > &callback)
FORCE_INLINE_FUNCTION void setDragAction (GenericCallback< const AbstractDataGraph &, const GraphDragEvent & > &callback)
FORCE_INLINE_FUNCTION void setGapBeforeIndex (int16_t index)
void setGraphAreaMargin (int16_t top, int16_t left, int16_t right, int16_t bottom)
void setGraphAreaPadding (int16_t top, int16_t left, int16_t right, int16_t bottom)
FORCE_INLINE_FUNCTION void setGraphRange (float xMin, float xMax, float yMin, float yMax)
FORCE_INLINE_FUNCTION void setGraphRange (float xMin, float xMax, int yMin, int yMax)
FORCE_INLINE_FUNCTION void setGraphRange (int xMin, int xMax, float yMin, float yMax)
FORCE_INLINE_FUNCTION void setGraphRange (int xMin, int xMax, int yMin, int yMax)
FORCE_INLINE_FUNCTION void setGraphRangeScaled (int xMin, int xMax, int yMin, int yMax)
virtual void setGraphRangeX (float min, float max)
virtual void setGraphRangeX (int min, int max)
virtual void setGraphRangeXAuto (bool showYaxis, float margin)
virtual void setGraphRangeXAuto (bool showYaxis=true, int margin=0)
virtual void setGraphRangeXScaled (int min, int max)
virtual void setGraphRangeY (float min, float max)
virtual void setGraphRangeY (int min, int max)
virtual void setGraphRangeYAuto (bool showXaxis, float margin)
virtual void setGraphRangeYAuto (bool showXaxis=true, int margin=0)
virtual void setGraphRangeYScaled (int min, int max)
virtual void setHeight (int16_t height)
virtual void setWidth (int16_t width)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual int16_t addValue (int xvalue, int yvalue)=0
virtual int16_t deleteIndex (int index)
virtual int16_t deleteValue (int xvalue)
virtual CWRUtil::Q5 indexToScreenXQ5 (int16_t index) const
virtual CWRUtil::Q5 indexToScreenYQ5 (int16_t index) const
virtual int indexToXAxis (const int, const int labelScaled) const
virtual bool xScreenRangeToIndexRange (int16_t xMin, int16_t xMax, int16_t &indexMin, int16_t &indexMax) const
Protected Member Functions inherited from AbstractDataGraph
void invalidateAllXAxisPoints ()
FORCE_INLINE_FUNCTION void invalidateGraphArea () const
void invalidateGraphPointAt (int16_t index)
void invalidateXAxisPointAt (int16_t index)
void updateAreasPosition ()
virtual CWRUtil::Q5 valueToScreenXQ5 (int x) const
virtual CWRUtil::Q5 valueToScreenYQ5 (int y) const
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
int * xValues
The x values of the graph.
int * yValues
The y values of the graph.
Protected Attributes inherited from AbstractDataGraph
uint8_t alpha
The alpha of the entire graph.
Container bottomArea
The area below the graph.
int16_t bottomPadding
The graph area bottom padding.
GenericCallback< const AbstractDataGraph &, const GraphClickEvent & > * clickAction
The callback to be executed when this Graph is clicked.
GenericCallback< const AbstractDataGraph &, const GraphDragEvent & > * dragAction
The callback to be executed when this Graph is dragged.
int16_t gapBeforeIndex
The graph is disconnected (there is a gap) before this element index.
Container graphArea
The graph area (the center area)
int graphRangeMaxX
The graph range maximum x coordinate.
int graphRangeMaxY
The graph range maximum y coordinate.
int graphRangeMinX
The graph range minimum x coordinate.
int graphRangeMinY
The graph range minimum y coordinate.
Container leftArea
The area to the left of the graph.
int16_t leftPadding
The graph area left padding.
int16_t maxCapacity
Maximum number of points in the graph.
Container rightArea
The area to the right of the graph.
int16_t rightPadding
The graph area right padding.
Container topArea
The area above the graph.
int16_t topPadding
The graph area top padding.
int16_t usedCapacity
The number of used points in the graph.
int xScale
The data scale for the x values.
int yScale
The data scale for the y values.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataGraph
static int convertToNewScale (int value, int oldScale, int newScale)
static FORCE_INLINE_FUNCTION int float2scaled (float f, int scale)
static FORCE_INLINE_FUNCTION int int2scaled (int i, int scale)
static FORCE_INLINE_FUNCTION float scaled2float (int i, int scale)
static FORCE_INLINE_FUNCTION int scaled2int (int i, int scale)
Detailed Description
Abstract helper class used to implement graphs with the same distance between the x values (i.e. x is ignored).
Constructor & Destructor Documentation
StaticDataGraph()
StaticDataGraph (int16_t capacity, int * xvalues, int * yvalues) inline
Initializes a new instance of the AbstractDataGraphWithY class.
Parameters
capacity The capacity.
[in] xvalues Address where to store the x values of the graph.
[in] yvalues Address where to store the y values of the graph.
        : AbstractDataGraph(capacity), xValues(xvalues), yValues(yvalues)
    {
        StaticDataGraph::setGraphRangeX(0, capacity - 1);
    }
References AbstractDataGraph::setGraphRangeX().
Member Function Documentation
addDataPoint() [1/2]
FORCE_INLINE_FUNCTION int16_t addDataPoint (float x, float y) inline
Adds a new data point to the end of the graph. The part of the graph that is changed, is automatically redrawn (invalidated).
Parameters
x The x value.
y The y value.
Returns
The index of the just added value.
    {
        return addValue(float2scaledX(x), float2scaledY(y));
    }
References StaticDataGraph::addValue(), AbstractDataGraph::float2scaledX(), and AbstractDataGraph::float2scaledY().
addDataPoint() [2/2]
FORCE_INLINE_FUNCTION int16_t addDataPoint (int x, int y) inline
Adds a new data point to the end of the graph. The part of the graph that is changed, is automatically redrawn (invalidated).
Parameters
x The x value.
y The y value.
Returns
The index of the just added value.
    {
        return addValue(int2scaledX(x), int2scaledY(y));
    }
References StaticDataGraph::addValue(), AbstractDataGraph::int2scaledX(), and AbstractDataGraph::int2scaledY().
addDataPointScaled()
FORCE_INLINE_FUNCTION int16_t addDataPointScaled (int x, int y) inline
Adds a new data point to the end of the graph. The part of the graph that is changed, is automatically redrawn (invalidated).
Parameters
x The x value.
y The y value.
Returns
The index of the just added value.
The index of the added data point.
Note
Same as addDataPoint(int, int) except the passed argument is assumed scaled.
    {
        return addValue(x, y);
    }
References StaticDataGraph::addValue().
addValue()
virtual int16_t addValue (int xvalue, int yvalue) protected pure virtual
Adds a value to the internal data array and keeps track of when graph points, graph axis and the entire graph needs to be redrawn (invalidated).
Parameters
xvalue The x value to add to the array.
yvalue The y value to add to the array.
Returns
The index of the newly added value, or -1 if the value could not be added.
Implemented in GraphData.
Referenced by StaticDataGraph::addDataPoint(), StaticDataGraph::addDataPoint(), and StaticDataGraph::addDataPointScaled().
deleteDataPoint() [1/2]
FORCE_INLINE_FUNCTION int deleteDataPoint (float x) inline
Deletes the data point at the given x value.
Parameters
x The x value.
Returns
The index of the deleted value, -1 if the x coordinate was not found.
    {
        return deleteDataPointScaled(float2scaledX(x));
    }
References StaticDataGraph::deleteDataPointScaled(), and AbstractDataGraph::float2scaledX().
deleteDataPoint() [2/2]
FORCE_INLINE_FUNCTION int deleteDataPoint (int x) inline
Deletes the data point at the given x value.
Parameters
x The x value.
Returns
The index of the deleted value, -1 if the x coordinate was not found.
    {
        return deleteDataPointScaled(int2scaledX(x));
    }
References StaticDataGraph::deleteDataPointScaled(), and AbstractDataGraph::int2scaledX().
deleteDataPointIndex()
FORCE_INLINE_FUNCTION int16_t deleteDataPointIndex (int index) inline
Same as deleteDataPoint(int) except the passed argument is the index of the value to delete. Deletes a data point.
Parameters
index Zero-based index of the values to delete.
Returns
The index of the deleted value, -1 if the x coordinate was not found.
    {
        return deleteIndex(index);
    }
References StaticDataGraph::deleteIndex().
deleteDataPointScaled()
FORCE_INLINE_FUNCTION int16_t deleteDataPointScaled (int x) inline
Same as dalateDataPoint(int) except the passed argument is assumed scaled. Deletes a data point scaled.
Parameters
x The x value.
Returns
The index of the deleted value, -1 if the x coordinate was not found.
    {
        return deleteValue(x);
    }
References StaticDataGraph::deleteValue().
Referenced by StaticDataGraph::deleteDataPoint(), and StaticDataGraph::deleteDataPoint().
deleteIndex()
int16_t deleteIndex (int index) protected virtual
Removes a value from the internal data array and keeps track of when graph points, graph axis and the entire graph needs to be redrawn (invalidated).
Parameters
index Zero-based index of the data point to delete.
Returns
The index of the removed value, or -1 if the value could not be removed.
{
    assert(index >= 0 && index < usedCapacity);
    invalidateGraphPointAt(index);
    usedCapacity--;
    for (int i = index; i < usedCapacity; i++)
    {
        xValues[i] = xValues[i + 1];
        yValues[i] = yValues[i + 1];
    }
    return index;
}
References AbstractDataGraph::invalidateGraphPointAt(), AbstractDataGraph::usedCapacity, StaticDataGraph::xValues, and StaticDataGraph::yValues.
Referenced by StaticDataGraph::deleteDataPointIndex(), and StaticDataGraph::deleteValue().
deleteValue()
int16_t deleteValue (int xvalue) protected virtual
Removes a value from the internal data array and keeps track of when graph points, graph axis and the entire graph needs to be redrawn (invalidated).
Parameters
xvalue The x value to remove from the array.
Returns
The index of the removed value, or -1 if the value could not be removed.
{
    for (int index = 0; index < usedCapacity; index++)
    {
        if (xValues[index] == xvalue)
        {
            return deleteIndex(index);
        }
    }
    return -1;
}
References StaticDataGraph::deleteIndex(), AbstractDataGraph::usedCapacity, and StaticDataGraph::xValues.
Referenced by StaticDataGraph::deleteDataPointScaled().
indexToDataPointXScaled()
virtual int indexToDataPointXScaled (int16_t index) const inline virtual
Gets data point x coordinate scaled.
Parameters
index Zero-based index of the value to fetch.
Returns
The data point x coordinate scaled.
See also
indexToDataPointXAsInt, indexToDataPointXAsFloat, indexToDataPointYScaled, indexToDataPoint, indexToDataPointScaled
Implements AbstractDataGraph.
    {
        assert(index >= 0 && index < usedCapacity);
        return xValues[index];
    }
References AbstractDataGraph::usedCapacity, and StaticDataGraph::xValues.
indexToDataPointYScaled()
virtual int indexToDataPointYScaled (int16_t index) const inline virtual
Gets data point y coordinate scaled.
Parameters
index Zero-based index of the value to fetch.
Returns
The data point y coordinate scaled.
See also
indexToDataPointYAsInt, indexToDataPointYAsFloat, indexToDataPointXScaled, indexToDataPoint, indexToDataPointScaled
Implements AbstractDataGraph.
    {
        assert(index >= 0 && index < usedCapacity);
        return yValues[index];
    }
References AbstractDataGraph::usedCapacity, and StaticDataGraph::yValues.
indexToScreenXQ5()
virtual CWRUtil::Q5 indexToScreenXQ5 (int16_t index) const inline protected virtual
Gets screen x coordinate for a specific data point added to the graph.
Parameters
index The index of the element to get the x coordinate for.
Returns
The screen x coordinate for the specific data point.
Implements AbstractDataGraph.
    {
        return valueToScreenXQ5(xValues[index]);
    }
References AbstractDataGraph::valueToScreenXQ5(), and StaticDataGraph::xValues.
indexToScreenYQ5()
virtual CWRUtil::Q5 indexToScreenYQ5 (int16_t index) const inline protected virtual
Gets screen y coordinate for a specific data point added to the graph.
Parameters
index The index of the element to get the y coordinate for.
Returns
The screen x coordinate for the specific data point.
Implements AbstractDataGraph.
    {
        return valueToScreenYQ5(yValues[index]);
    }
References AbstractDataGraph::valueToScreenYQ5(), and StaticDataGraph::yValues.
indexToXAxis()
virtual int indexToXAxis (const int valueScaled, const int labelScaled) const inline protected virtual
Convert the given valueScaled (index) to x axis value.
Parameters
valueScaled The value scaled.
labelScaled The label scaled.
Returns
The x axis value.
Implements AbstractDataGraph.
    {
        return labelScaled;
    }
setGraphRangeXAutoScaled()
void setGraphRangeXAutoScaled (bool showYaxis, int margin) virtual
Sets graph range x coordinate automatic scaled.
Parameters
showYaxis True to show, false to hide the y axis.
margin The margin.
Implements AbstractDataGraph.
{
    if (usedCapacity == 0)
    {
        return;
    }
    int xMin = xValues[0];                // First x value is the lowest
    int xMax = xValues[usedCapacity - 1]; // Last x value is the highest
    if (showYaxis)
    {
        // The y axis (x=0) must be shown, so make sure 0 is included after subtracting/adding the margin
        xMin = MIN(xMin, margin);
        xMax = MAX(xMax, -margin);
    }
    xMin -= margin;
    xMax += margin;
    if (xMin != xMax)
    {
        setGraphRangeXScaled(xMin, xMax);
    }
}
References MAX, MIN, AbstractDataGraph::setGraphRangeXScaled(), AbstractDataGraph::usedCapacity, and StaticDataGraph::xValues.
setGraphRangeYAutoScaled()
void setGraphRangeYAutoScaled (bool showXaxis = true, int margin = 0) virtual
Sets graph range y coordinate automatic scaled.
Parameters
showXaxis (Optional) True to show, false to hide the x axis.
margin (Optional) The margin.
Implements AbstractDataGraph.
{
    if (usedCapacity == 0)
    {
        return;
    }
    int xValueMin = getGraphRangeXMinScaled(); // Get shown x range
    int xValueMax = getGraphRangeXMaxScaled();
    if (xValueMin > xValueMax)
    {
        // Swap so min<=max.
        const int16_t tmp = xValueMin;
        xValueMin = xValueMax;
        xValueMax = tmp;
    }
    int index = 0;
    while (xValues[index] < xValueMin && index < usedCapacity)
    {
        // Skip all indices that have x outside visible area
        index++;
    }
    if (xValues[index] > xValueMax)
    {
        // No x values are in the visible area
        return;
    }
    int yMin = yValues[index++]; // The index'th value must be visible
    int yMax = yMin;
    // Go through all points where x is in the visible range
    while (xValues[index] < xValueMax && index < usedCapacity)
    {
        const int y = yValues[index++];
        yMin = MIN(yMin, y);
        yMax = MAX(yMax, y);
    }
    if (showXaxis)
    {
        // The x axis (y=0) must be shown, so make sure 0 is included after subtracting/adding the margin
        yMin = MIN(yMin, margin);
        yMax = MAX(yMax, -margin);
    }
    yMin -= margin;
    yMax += margin;
    if (yMin != yMax)
    {
        setGraphRangeYScaled(yMin, yMax);
    }
}
References AbstractDataGraph::getGraphRangeXMaxScaled(), AbstractDataGraph::getGraphRangeXMinScaled(), MAX, MIN, AbstractDataGraph::setGraphRangeYScaled(), AbstractDataGraph::usedCapacity, StaticDataGraph::xValues, and StaticDataGraph::yValues.
setScaleX()
void setScaleX (int scale, bool updateData = false) virtual
Sets a scaling factor to be multiplied on each X value added. Since the graph only stores integer values internally, it is possible to set a scale to e.g. 1000 and make the graph work as if there are three digits of precision. The addDataPoint() will multiply the x argument with the scaling factor and store this value. Please note the addDataPointScaled, which allows adding a value that is assumed to have already been multiplied by the scaling factor. Other functions exist in a "scaled" version where the arguments are assumed to already be scaled.
By setting the scale to 1 it is possible to simply use integer values for the graph.
Parameters
scale The scaling factor.
updateData (Optional) True to update all existing x value.
See also
getScaleX, setScaleY, getScaleY
Reimplemented from AbstractDataGraph.
{
    if (updateData)
    {
        const int oldScale = getScaleX();
        for (int16_t index = 0; index < usedCapacity; index++)
        {
            xValues[index] = convertToNewScale(xValues[index], oldScale, scale);
        }
    }
    AbstractDataGraph::setScaleX(scale);
}
References AbstractDataGraph::convertToNewScale(), AbstractDataGraph::getScaleX(), AbstractDataGraph::setScaleX(), AbstractDataGraph::usedCapacity, and StaticDataGraph::xValues.
setScaleY()
void setScaleY (int scale, bool updateData = false) virtual
Sets a scaling factor to be multiplied on each Y value added. Since the graph only stores integer values internally, it is possible to set a scale to e.g. 1000 and make the graph work as if there are three digits of precision. The addDataPoint() will multiply the y argument with the scaling factor and store this value. Please note the addDataPointScaled, which allows adding a value that is assumed to have already been multiplied by the scaling factor. Other functions exist in a "scaled" version where the arguments are assumed to already be scaled.
By setting the scale to 1 it is possible to simply use integer values for the graph.
Parameters
scale The scaling factor.
updateData (Optional) True to update all existing y value.
See also
getScaleY, setScaleX, getScaleX
Reimplemented from AbstractDataGraph.
{
    if (updateData)
    {
        const int oldScale = getScaleY();
        for (int16_t index = 0; index < usedCapacity; index++)
        {
            yValues[index] = convertToNewScale(yValues[index], oldScale, scale);
        }
    }
    AbstractDataGraph::setScaleY(scale);
}
References AbstractDataGraph::convertToNewScale(), AbstractDataGraph::getScaleY(), AbstractDataGraph::setScaleY(), AbstractDataGraph::usedCapacity, and StaticDataGraph::yValues.
xScreenRangeToIndexRange()
bool xScreenRangeToIndexRange (int16_t xMin, int16_t xMax, int16_t & indexMin, int16_t & indexMax) const protected virtual
Gets index range for screen x coordinate range taking the current graph range into account.
Parameters
xMin The low screen x coordinate.
xMax The high screen x coordinate.
[out] indexMin The low element index.
[out] indexMax The high element index.
Returns
True if the range from low index to high index is legal.
Note
For internal use.
Implements AbstractDataGraph.
{
    if (usedCapacity == 0)
    {
        indexMin = indexMax = -1;
        return false;
    }
    if (getGraphAreaWidth() <= 1)
    {
        indexMin = 0;
        indexMax = usedCapacity - 1;
        return true;
    }
    CWRUtil::Q5 xQ5Min = CWRUtil::muldivQ5(CWRUtil::toQ5(xMin - leftPadding), CWRUtil::Q5(graphRangeMaxX - graphRangeMinX), CWRUtil::Q5(getGraphAreaWidth() - 1)) + CWRUtil::toQ5(graphRangeMinX);
    CWRUtil::Q5 xQ5Max = CWRUtil::muldivQ5(CWRUtil::toQ5(xMax - leftPadding), CWRUtil::Q5(graphRangeMaxX - graphRangeMinX), CWRUtil::Q5(getGraphAreaWidth() - 1)) + CWRUtil::toQ5(graphRangeMinX);
    if (xQ5Min > xQ5Max)
    {
        const CWRUtil::Q5 tmp = xQ5Min;
        xQ5Min = xQ5Max;
        xQ5Max = tmp;
    }
    const int xValueMin = xQ5Min.to<int>(); // These are REAL x values
    const int xValueMax = xQ5Max.ceil();
    indexMin = -1;
    while (indexMin < usedCapacity - 1 && xValues[indexMin + 1] <= xValueMin)
    {
        indexMin++;
    }
    indexMax = usedCapacity;
    while (indexMax > 0 && xValues[indexMax - 1] >= xValueMax)
    {
        indexMax--;
    }
    if (indexMax <= 0)
    {
        indexMin = indexMax = 0;
        return false;
    }
    if (indexMin >= usedCapacity - 1)
    {
        indexMin = indexMax = usedCapacity - 1;
        return false;
    }
    indexMin = MAX(0, indexMin);
    indexMax = MIN(usedCapacity - 1, indexMax);
    return true;
}
References AbstractDataGraph::getGraphAreaWidth(), AbstractDataGraph::graphRangeMaxX, AbstractDataGraph::graphRangeMinX, AbstractDataGraph::leftPadding, MAX, MIN, CWRUtil::muldivQ5(), CWRUtil::toQ5(), AbstractDataGraph::usedCapacity, and StaticDataGraph::xValues.
Member Data Documentation
xValues
int* xValues protected
The x values of the graph.
Referenced by GraphData::addValue(), StaticDataGraph::deleteIndex(), StaticDataGraph::deleteValue(), StaticDataGraph::indexToDataPointXScaled(), StaticDataGraph::indexToScreenXQ5(), StaticDataGraph::setGraphRangeXAutoScaled(), StaticDataGraph::setGraphRangeYAutoScaled(), StaticDataGraph::setScaleX(), and StaticDataGraph::xScreenRangeToIndexRange().
yValues
int* yValues protected
The y values of the graph.
Referenced by GraphData::addValue(), StaticDataGraph::deleteIndex(), StaticDataGraph::indexToDataPointYScaled(), StaticDataGraph::indexToScreenYQ5(), StaticDataGraph::setGraphRangeYAutoScaled(), and StaticDataGraph::setScaleY().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/graph/AbstractDataGraph.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph/AbstractDataGraph.cpp