Battery Simulator Documentation: TouchButtonTrigger
TouchButtonTrigger
#include "TouchButtonTrigger.hpp"
Public Member Functions
virtual void handleClickEvent (const ClickEvent &event)
Public Member Functions inherited from AbstractButtonContainer
AbstractButtonContainer ()
virtual void executeAction ()
uint8_t getAlpha () const
bool getPressed () const
void setAction (GenericCallback< const AbstractButtonContainer & > &callback)
void setAlpha (uint8_t newAlpha)
void setPressed (bool isPressed)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Additional Inherited Members
Protected Member Functions inherited from AbstractButtonContainer
virtual void handleAlphaUpdated ()
virtual void handlePressedUpdated ()
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes inherited from AbstractButtonContainer
GenericCallback< const AbstractButtonContainer & > * action
The action to be executed.
uint8_t alpha
The current alpha value. 255 denotes solid, 0 denotes completely invisible.
bool pressed
True if pressed.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A touch button trigger. This trigger will create a button that reacts on touches. This means it will call the set action when it gets a touch pressed event. The TouchButtonTrigger can be combined with one or more of the ButtonStyle classes to create a fully functional button.
See also
ClickButtonTrigger
Member Function Documentation
handleClickEvent()
virtual void handleClickEvent (const ClickEvent & event) inline virtual
Handles a ClickAvent. The action callback is called when the ClickButtonTrigger receives a ClickEvent::PRESSED event. Function setPressed() will be called with the new button state.
Parameters
event The click event.
See also
setAction, setPressed, getPressed
Reimplemented from Drawable.
    {
        bool wasPressed = getPressed();
        bool newPressedValue = (event.getType() == ClickEvent::PRESSED);
        if ((newPressedValue && !wasPressed) || (!newPressedValue && wasPressed))
        {
            setPressed(newPressedValue);
            invalidate();
        }
        if (newPressedValue)
        {
            executeAction();
        }
    }
References AbstractButtonContainer::executeAction(), AbstractButtonContainer::getPressed(), Drawable::invalidate(), ClickEvent::PRESSED, and AbstractButtonContainer::setPressed().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/buttons/TouchButtonTrigger.hpp