Battery Simulator Documentation: AbstractShape
AbstractShape abstract
#include "AbstractShape.hpp"
Classes
struct ShapePoint
Public Member Functions
AbstractShape ()
virtual bool drawCanvasWidget (const Rect &invalidatedArea) const
int getAngle () const
template<typename T >
void getAngle (T &angle)
virtual CWRUtil::Q5 getCornerX (int i) const =0
virtual CWRUtil::Q5 getCornerY (int i) const =0
Rasterizer::FillingRule getFillingRule () const
virtual int getNumPoints () const =0
template<typename T >
void getOrigin (T &xOrigin, T &yOrigin) const
template<typename T >
void getScale (T &x, T &y) const
template<typename T >
void moveOrigin (T x, T y)
template<typename T >
void setAngle (T angle)
virtual void setCorner (int i, CWRUtil::Q5 x, CWRUtil::Q5 y)=0
void setFillingRule (Rasterizer::FillingRule rule)
template<typename T >
void setOrigin (T x, T y)
template<typename T >
void setScale (T newXScale, T newYScale)
template<typename T >
void setScale (T scale)
template<typename T >
void setShape (const ShapePoint< T > *points)
template<typename T >
void setShape (ShapePoint< T > *points)
void updateAbstractShapeCache ()
template<typename T >
void updateAngle (T angle)
template<typename T >
void updateScale (T newXScale, T newYScale)
Public Member Functions inherited from CanvasWidget
CanvasWidget ()
virtual void draw (const Rect &invalidatedArea) const
virtual uint8_t getAlpha () const
const AbstractPainter * getPainter () const
virtual Rect getSolidRect () const
virtual void invalidate () const
virtual void setAlpha (uint8_t newAlpha)
void setPainter (const AbstractPainter &painter)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual CWRUtil::Q5 getCacheX (int i) const =0
virtual CWRUtil::Q5 getCacheY (int i) const =0
virtual Rect getMinimalRect () const
virtual void setCache (int i, CWRUtil::Q5 x, CWRUtil::Q5 y)=0
Protected Attributes
Rasterizer::FillingRule fillingRule
The filling rule used by the rasterizer.
Protected Attributes inherited from CanvasWidget
uint8_t alpha
The Alpha for this CanvasWidget.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Private Attributes
CWRUtil::Q5 dx
CWRUtil::Q5 dy
Rect minimalRect
CWRUtil::Q5 shapeAngle
CWRUtil::Q10 xScale
CWRUtil::Q10 yScale
Detailed Description
Simple widget capable of drawing a abstractShape. The abstractShape can be scaled and rotated around 0,0. The shapes points (corners) are calculated with regards to scaling and rotation to allow for faster redrawing. Care must be taken to call updateAbstractShapeCache() after updating the shape, the scale of the shape or the rotation of the shape.
Constructor & Destructor Documentation
AbstractShape()
AbstractShape ()
    : CanvasWidget(),
      fillingRule(Rasterizer::FILL_NON_ZERO),
      dx(0), dy(0), shapeAngle(0),
      xScale(CWRUtil::toQ10<int>(1)), yScale(CWRUtil::toQ10<int>(1)),
      minimalRect()
{
    Drawable::setWidthHeight(0, 0);
}
References Drawable::setWidthHeight().
Member Function Documentation
drawCanvasWidget()
bool drawCanvasWidget (const Rect & invalidatedArea) const virtual
Draw canvas widget for the given invalidated area. Similar to draw(), but might be invoked several times with increasingly smaller areas to due to memory constraints from the underlying CanvasWidgetRenderer.
Parameters
invalidatedArea The invalidated area.
Returns
true if the widget was drawn properly, false if not.
See also
draw
Implements CanvasWidget.
{
    const int numPoints = getNumPoints();
    if (numPoints == 0)
    {
        return true;
    }
    Canvas canvas(getPainter(), getAbsoluteRect(), invalidatedArea, getAlpha());
    canvas.setFillingRule(fillingRule);
    canvas.moveTo(getCacheX(0), getCacheY(0));
    for (int i = 1; i < numPoints; i++)
    {
        canvas.lineTo(getCacheX(i), getCacheY(i));
        if (canvas.wasOutlineTooComplex())
        {
            return false;
        }
    }
    return canvas.render();
}
References AbstractShape::fillingRule, Drawable::getAbsoluteRect(), CanvasWidget::getAlpha(), AbstractShape::getCacheX(), AbstractShape::getCacheY(), AbstractShape::getNumPoints(), and CanvasWidget::getPainter().
getAngle() [1/2]
int getAngle () const inline
Gets the current angle in degrees of the abstractShape.
Returns
The angle of the AbstractShaperounded down to the precision of int.
Note
Angles are given in degrees, so a full circle is 360.
    {
        return shapeAngle.to<int>();
    }
References AbstractShape::shapeAngle, and CWRUtil::Q5::to().
getAngle() [2/2]
template<typename T > void getAngle (T & angle) inline
Gets the abstractShape's angle in degrees.
Template Parameters
T Generic type parameter.
Parameters
[out] angle The current AbstractShape rotation angle rounded down to the precision of T.
Note
Angles are given in degrees, so a full circle is 360.
    {
        angle = this->shapeAngle.to<T>();
    }
References AbstractShape::shapeAngle, and CWRUtil::Q5::to().
getCacheX()
virtual CWRUtil::Q5 getCacheX (int i) const protected pure virtual
Gets cached x coordinate of a point/corner.
Parameters
i Zero-based index of the point/corner.
Returns
The cached x coordinate, or zero if nothing is cached for the given i.
Implemented in Shape< POINTS >.
Referenced by AbstractShape::drawCanvasWidget().
getCacheY()
virtual CWRUtil::Q5 getCacheY (int i) const protected pure virtual
Gets cached y coordinate of a point/corner.
Parameters
i Zero-based index of the point/corner.
Returns
The cached y coordinate, or zero if nothing is cached for the given i.
Implemented in Shape< POINTS >.
Referenced by AbstractShape::drawCanvasWidget().
getCornerX()
virtual CWRUtil::Q5 getCornerX (int i) const pure virtual
Gets the x coordinate of a corner (a point) of the shape.
Parameters
i Zero-based index of the corner.
Returns
The corner x coordinate in CWRUtil::Q5 format.
Implemented in Shape< POINTS >.
Referenced by AbstractShape::updateAbstractShapeCache().
getCornerY()
virtual CWRUtil::Q5 getCornerY (int i) const pure virtual
Gets the y coordinate of a corner (a point) of the shape.
Parameters
i Zero-based index of the corner.
Returns
The corner y coordinate in CWRUtil::Q5 format.
Implemented in Shape< POINTS >.
Referenced by AbstractShape::updateAbstractShapeCache().
getFillingRule()
Rasterizer::FillingRule getFillingRule () const inline
Gets the filling rule being used when rendering the outline.
Returns
The filling rule.
See also
setFillingRule
    {
        return fillingRule;
    }
References AbstractShape::fillingRule.
getMinimalRect()
Rect getMinimalRect () const protected virtual
Gets minimal rectangle containing the shape drawn by this widget. Default implementation returns the size of the entire widget, but this function should be overwritten in subclasses and return the minimal rectangle containing the shape. See classes such as Circle for example implementations.
Returns
The minimal rectangle containing the shape drawn.
Reimplemented from CanvasWidget.
{
    return minimalRect;
}
References AbstractShape::minimalRect.
Referenced by AbstractShape::moveOrigin(), AbstractShape::updateAngle(), and AbstractShape::updateScale().
getNumPoints()
virtual int getNumPoints () const pure virtual
Gets number of points used to make up the shape.
Returns
The number of points.
Implemented in Shape< POINTS >.
Referenced by AbstractShape::drawCanvasWidget(), AbstractShape::setShape(), AbstractShape::setShape(), and AbstractShape::updateAbstractShapeCache().
getOrigin()
template<typename T > void getOrigin (T & xOrigin, T & yOrigin) const inline
Gets the position of the shapes (0,0).
Template Parameters
T Generic type parameter, either int or float.
Parameters
[out] xOrigin The x coordinate rounded down to the precision of T.
[out] yOrigin The y coordinate rounded down to the precision of T.
    {
        xOrigin = dx.to<T>();
        yOrigin = dy.to<T>();
    }
References AbstractShape::dx, AbstractShape::dy, and CWRUtil::Q5::to().
getScale()
template<typename T > void getScale (T & x, T & y) const inline
Gets the x scale and y scale of the shape as previously set using setScale. Default is 1 for both x scale and y scale.
Template Parameters
T Generic type parameter, either int or float.
Parameters
[out] x Scaling of x coordinates rounded down to the precision of T.
[out] y Scaling of y coordinates rounded down to the precision of T.
See also
setScale
    {
        x = xScale.to<T>();
        y = yScale.to<T>();
    }
References CWRUtil::Q10::to(), AbstractShape::xScale, and AbstractShape::yScale.
moveOrigin()
template<typename T > void moveOrigin (T x, T y) inline
Sets the position of the shape's (0,0) in the widget. This means that all coordinates initially used when created the shape are moved relative to these given offsets. Subsequent calls to moveOrigin() or setOrigin() will replace the old values for origin. The cached outline of the shape is automatically updated.
Template Parameters
T Generic type parameter, either int or float.
Parameters
x The absolute x coordinate of the shapes position (0,0).
y The absolute y coordinate of the shapes position (0,0).
See also
setOrigin
Note
The area containing the AbstractShape is invalidated before and after the change.
    {
        CWRUtil::Q5 xNew = CWRUtil::toQ5<T>(x);
        CWRUtil::Q5 yNew = CWRUtil::toQ5<T>(y);
        if (dx == xNew && dy == yNew)
        {
            return;
        }
        Rect rectBefore = getMinimalRect();
        invalidateRect(rectBefore);
        dx = xNew;
        dy = yNew;
        updateAbstractShapeCache();
        Rect rectAfter = getMinimalRect();
        invalidateRect(rectAfter);
    }
References AbstractShape::dx, AbstractShape::dy, AbstractShape::getMinimalRect(), Drawable::invalidateRect(), and AbstractShape::updateAbstractShapeCache().
setAngle()
template<typename T > void setAngle (T angle) inline
Sets the absolute angle in degrees to turn the AbstractShape. 0 degrees means no rotation and 90 degrees is rotate the shape clockwise. Repeated calls to setAngle(10) will therefore not rotate the shape by an additional 10 degrees. The cached outline of the shape is automatically updated.
Template Parameters
T Generic type parameter.
Parameters
angle The absolute angle to turn the abstractShape to relative to 0 (straight up).
See also
updateAngle
Note
The area containing the AbstractShape is not invalidated.
Angles are given in degrees, so a full circle is 360.
    {
        CWRUtil::Q5 angleQ5 = CWRUtil::toQ5<T>(angle);
        if (shapeAngle != angleQ5)
        {
            shapeAngle = angleQ5;
            updateAbstractShapeCache();
        }
    }
References AbstractShape::shapeAngle, and AbstractShape::updateAbstractShapeCache().
setCache()
virtual void setCache (int i, CWRUtil::Q5 x, CWRUtil::Q5 y) protected pure virtual
Sets the cached coordinates of a given point/corner. The coordinates in the cache are the coordinates from the corners after rotation and scaling has been applied to the coordinate.
Parameters
i Zero-based index of the corner.
x The x coordinate.
y The y coordinate.
Implemented in Shape< POINTS >.
Referenced by AbstractShape::updateAbstractShapeCache().
setCorner()
virtual void setCorner (int i, CWRUtil::Q5 x, CWRUtil::Q5 y) pure virtual
Sets one of the points (a corner) of the shape in CWRUtil::Q5 format.
Parameters
i Zero-based index of the corner.
x The x coordinate in CWRUtil::Q5 format.
y The y coordinate in CWRUtil::Q5 format.
See also
updateAbstractShapeCache
Note
Remember to call updateAbstractShapeCache() after calling setCorner one or more times, to make sure that the cached outline of the shape is correct.
Implemented in Shape< POINTS >.
Referenced by AbstractShape::setShape(), and AbstractShape::setShape().
setFillingRule()
void setFillingRule (Rasterizer::FillingRule rule) inline
Sets the filling rule to be used when rendering the outline.
Parameters
rule The filling rule.
See also
getFillingRule
    {
        fillingRule = rule;
    }
References AbstractShape::fillingRule.
setOrigin()
template<typename T > void setOrigin (T x, T y) inline
Sets the position of the shape's (0,0) in the widget. This means that all coordinates initially used when created the shape are moved relative to these given offsets. Subsequent calls to setOrigin() or moveOrigin() will replace the old values for origin. The cached outline of the shape is automatically updated.
Template Parameters
T Generic type parameter, either int or float.
Parameters
x The absolute x coordinate of the shapes position (0,0).
y The absolute y coordinate of the shapes position (0,0).
See also
moveOrigin
Note
The area containing the AbstractShape is not invalidated.
    {
        CWRUtil::Q5 dxNew = CWRUtil::toQ5<T>(x);
        CWRUtil::Q5 dyNew = CWRUtil::toQ5<T>(y);
        if (dx == dxNew && dy == dyNew)
        {
            return;
        }
        dx = dxNew;
        dy = dyNew;
        updateAbstractShapeCache();
    }
References AbstractShape::dx, AbstractShape::dy, and AbstractShape::updateAbstractShapeCache().
setScale() [1/2]
template<typename T > void setScale (T newXScale, T newYScale) inline
Scale the AbstractShape the given amounts in the x direction and the y direction. The new scaling factors do not multiply to previously set scaling factors, so scaling by 2 and later scaling by 2 again will not scale by 4, only by 2. The cached outline of the shape is automatically updated.
Template Parameters
T Generic type parameter, either int or float.
Parameters
newXScale The new scale in the x direction.
newYScale The new scale in the y direction.
See also
getScale, updateScale
Note
The area containing the AbstractShape is not invalidated.
    {
        xScale = CWRUtil::toQ10<T>(newXScale);
        yScale = CWRUtil::toQ10<T>(newYScale);
        updateAbstractShapeCache();
    }
References AbstractShape::updateAbstractShapeCache(), AbstractShape::xScale, and AbstractShape::yScale.
Referenced by AbstractShape::setScale().
setScale() [2/2]
template<typename T > void setScale (T scale) inline
Scale the AbstractShape the given amount in the x direction and the y direction. The new scaling factors do not multiply to previously set scaling factors, so scaling by 2 and later scaling by 2 again will not scale by 4, only by 2. The cached outline of the shape is automatically updated.
Template Parameters
T Generic type parameter, either int or float.
Parameters
scale The scale in the x direction.
See also
getScale
Note
The area containing the AbstractShape is not invalidated.
    {
        setScale(scale, scale);
    }
References AbstractShape::setScale().
setShape() [1/2]
template<typename T > void setShape (const ShapePoint< T > * points) inline
Sets a shape the struct Points. The cached outline of the shape is automatically updated.
Template Parameters
T Generic type parameter, either int or float.
Parameters
[in] points The points that make up the shape. The pointer must point to an array of getNumPoints() elements of type ShapePoint.
Note
The area containing the shape is not invalidated.
    {
        int numPoints = getNumPoints();
        for (int i = 0; i < numPoints; i++)
        {
            setCorner(i, CWRUtil::toQ5<T>(points[i].x), CWRUtil::toQ5<T>(points[i].y));
        }
        updateAbstractShapeCache();
    }
References AbstractShape::getNumPoints(), AbstractShape::setCorner(), and AbstractShape::updateAbstractShapeCache().
setShape() [2/2]
template<typename T > void setShape (ShapePoint< T > * points) inline
Sets a shape the struct Points. The cached outline of the shape is automatically updated.
Template Parameters
T Generic type parameter, either int or float.
Parameters
[in] points The points that make up the shape. The pointer must point to an array of getNumPoints() elements of type ShapePoint.
Note
The area containing the shape is not invalidated.
    {
        int numPoints = getNumPoints();
        for (int i = 0; i < numPoints; i++)
        {
            setCorner(i, CWRUtil::toQ5<T>(points[i].x), CWRUtil::toQ5<T>(points[i].y));
        }
        updateAbstractShapeCache();
    }
References AbstractShape::getNumPoints(), AbstractShape::setCorner(), and AbstractShape::updateAbstractShapeCache().
updateAbstractShapeCache()
void updateAbstractShapeCache ()
Updates the AbstractShape cache. The cache is used to be able to quickly redraw the AbstractShape without calculating the points that make up the abstractShape (with regards to scaling and rotation).
{
    const int numPoints = getNumPoints();
    int xMin = 0;
    int xMax = 0;
    int yMin = 0;
    int yMax = 0;
    const CWRUtil::Q15 cos = CWRUtil::cosine(shapeAngle);
    const CWRUtil::Q15 sin = CWRUtil::sine(shapeAngle);
    for (int i = 0; i < numPoints; i++)
    {
        CWRUtil::Q5 const xCorner = getCornerX(i);
        CWRUtil::Q5 const yCorner = getCornerY(i);
        CWRUtil::Q5 const xCache = dx + ((CWRUtil::mulQ5(xCorner, xScale) * cos)) - ((CWRUtil::mulQ5(yCorner, yScale) * sin));
        if (i == 0 || xCache.to<int>() > xMax)
        {
            xMax = xCache.to<int>();
        }
        if (i == 0 || xCache.to<int>() < xMin)
        {
            xMin = xCache.to<int>();
        }
        CWRUtil::Q5 const yCache = dy + ((CWRUtil::mulQ5(yCorner, yScale) * cos)) + ((CWRUtil::mulQ5(xCorner, xScale) * sin));
        if (i == 0 || yCache.to<int>() > yMax)
        {
            yMax = yCache.to<int>();
        }
        if (i == 0 || yCache.to<int>() < yMin)
        {
            yMin = yCache.to<int>();
        }
        setCache(i, xCache, yCache);
    }
    minimalRect = Rect(xMin, yMin, (xMax - xMin) + 1, (yMax - yMin) + 1);
}
References CWRUtil::cosine(), AbstractShape::dx, AbstractShape::dy, AbstractShape::getCornerX(), AbstractShape::getCornerY(), AbstractShape::getNumPoints(), AbstractShape::minimalRect, CWRUtil::mulQ5(), AbstractShape::setCache(), AbstractShape::shapeAngle, CWRUtil::sine(), CWRUtil::Q5::to(), AbstractShape::xScale, and AbstractShape::yScale.
Referenced by AbstractShape::moveOrigin(), AbstractShape::setAngle(), AbstractShape::setOrigin(), AbstractShape::setScale(), AbstractShape::setShape(), AbstractShape::setShape(), AbstractShape::updateAngle(), and AbstractShape::updateScale().
updateAngle()
template<typename T > void updateAngle (T angle) inline
Sets the absolute angle in degrees to turn the AbstractShape. 0 degrees means no rotation and 90 degrees is rotate the shape clockwise. Repeated calls to setAngle(10) will therefore not rotate the shape by an additional 10 degrees. The cached outline of the shape is automatically updated.
Template Parameters
T Generic type parameter.
Parameters
angle The angle to turn the abstractShape.
See also
setAngle
Note
The area containing the AbstractShape is invalidated before and after the change.
Angles are given in degrees, so a full circle is 360.
    {
        CWRUtil::Q5 angleQ5 = CWRUtil::toQ5<T>(angle);
        if (shapeAngle != angleQ5)
        {
            Rect rectBefore = getMinimalRect();
            invalidateRect(rectBefore);
            shapeAngle = angleQ5;
            updateAbstractShapeCache();
            Rect rectAfter = getMinimalRect();
            invalidateRect(rectAfter);
        }
    }
References AbstractShape::getMinimalRect(), Drawable::invalidateRect(), AbstractShape::shapeAngle, and AbstractShape::updateAbstractShapeCache().
updateScale()
template<typename T > void updateScale (T newXScale, T newYScale) inline
Scale the AbstractShape the given amount in the x direction and the y direction. The new scaling factors do not multiply to previously set scaling factors, so scaling by 2 and later scaling by 2 again will not scale by 4, only by 2. The cached outline of the shape is automatically updated.
Template Parameters
T Generic type parameter, either int or float.
Parameters
newXScale The new scale in the x direction.
newYScale The new scale in the y direction.
See also
setScale
Note
The area containing the AbstractShape is invalidated before and after the change.
    {
        CWRUtil::Q10 xScaleQ10 = CWRUtil::toQ10<T>(newXScale);
        CWRUtil::Q10 yScaleQ10 = CWRUtil::toQ10<T>(newYScale);
        if (xScale != xScaleQ10 || yScale != yScaleQ10)
        {
            Rect rectBefore = getMinimalRect();
            invalidateRect(rectBefore);
            xScale = xScaleQ10;
            yScale = yScaleQ10;
            updateAbstractShapeCache();
            Rect rectAfter = getMinimalRect();
            invalidateRect(rectAfter);
        }
    }
References AbstractShape::getMinimalRect(), Drawable::invalidateRect(), AbstractShape::updateAbstractShapeCache(), AbstractShape::xScale, and AbstractShape::yScale.
Member Data Documentation
dx
CWRUtil::Q5 dx private
Referenced by AbstractShape::getOrigin(), AbstractShape::moveOrigin(), AbstractShape::setOrigin(), and AbstractShape::updateAbstractShapeCache().
dy
CWRUtil::Q5 dy private
Referenced by AbstractShape::getOrigin(), AbstractShape::moveOrigin(), AbstractShape::setOrigin(), and AbstractShape::updateAbstractShapeCache().
fillingRule
Rasterizer::FillingRule fillingRule protected
The filling rule used by the rasterizer.
Referenced by AbstractShape::drawCanvasWidget(), AbstractShape::getFillingRule(), and AbstractShape::setFillingRule().
minimalRect
Rect minimalRect private
Referenced by AbstractShape::getMinimalRect(), and AbstractShape::updateAbstractShapeCache().
shapeAngle
CWRUtil::Q5 shapeAngle private
Referenced by AbstractShape::getAngle(), AbstractShape::getAngle(), AbstractShape::setAngle(), AbstractShape::updateAbstractShapeCache(), and AbstractShape::updateAngle().
xScale
CWRUtil::Q10 xScale private
Referenced by AbstractShape::getScale(), AbstractShape::setScale(), AbstractShape::updateAbstractShapeCache(), and AbstractShape::updateScale().
yScale
CWRUtil::Q10 yScale private
Referenced by AbstractShape::getScale(), AbstractShape::setScale(), AbstractShape::updateAbstractShapeCache(), and AbstractShape::updateScale().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/AbstractShape.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/AbstractShape.cpp