Battery Simulator Documentation: Drawable
Drawable abstract
#include "Drawable.hpp"
Public Member Functions
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
virtual void draw (const Rect &invalidatedArea) const =0
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)=0
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRect () const =0
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
The Drawable class is an abstract definition of something that can be drawn. In the composite design pattern, the Drawable is the component interface. Drawables can be added to a screen as a tree structure through the leaf node class Widget and the Container class. A Drawable contains a pointer to its next sibling and a pointer to its parent node. These are maintained by the Container to which the Drawable is added.
The Drawable interface contains two pure virtual functions which must be implemented by widgets, namely draw() and getSolidRect(). In addition it contains general functionality for receiving events and navigating the tree structure.
The coordinates of a Drawable are always relative to its parent node.
See also
Widget, Container
Constructor & Destructor Documentation
Drawable()
Drawable () inline
Initializes a new instance of the Drawable class.
        : rect(),
          cachedVisibleRect(),
          parent(0),
          nextSibling(0),
          nextDrawChainElement(0),
          cachedAbsX(0),
          cachedAbsY(0),
          touchable(false),
          visible(true)
    {
    }
~Drawable()
virtual ~Drawable () inline virtual
Finalizes an instance of the Drawable class.
    {
    }
Member Function Documentation
center()
void center () inline
Centers the Drawable inside its parent.
    {
        centerX();
        centerY();
    }
References Drawable::centerX(), and Drawable::centerY().
centerX()
void centerX () inline
Center the Drawable horizontally inside its parent.
    {
        assert(parent && "Cannot center a Drawable with no parent");
        setX((parent->getWidth() - getWidth()) / 2);
    }
References Drawable::getWidth(), Drawable::parent, and Drawable::setX().
Referenced by Drawable::center(), and SVGImage::setRotationCenter().
centerY()
void centerY () inline
Center the Drawable vertically inside its parent.
    {
        assert(parent && "Cannot center a Drawable with no parent");
        setY((parent->getHeight() - getHeight()) / 2);
    }
References Drawable::getHeight(), Drawable::parent, and Drawable::setY().
Referenced by Drawable::center(), and SVGImage::setRotationCenter().
childGeometryChanged()
virtual void childGeometryChanged () inline virtual
This function can be called on parent nodes to signal that the size or position of one or more of its children has changed. Currently only used in ScrollableContainer to redraw scrollbars when the size of the scrolling contents changes.
Reimplemented in ScrollableContainer.
    {
    }
Referenced by ListLayout::add(), ListLayout::insert(), ListLayout::remove(), ListLayout::removeAll(), and ListLayout::setDirection().
draw()
virtual void draw (const Rect & invalidatedArea) const pure virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Implemented in TouchArea, Transition::FullSolidRect, Box, BoxWithBorder, ButtonWithLabel, TextArea, TextAreaWithWildcardBase, Container, Button, ButtonWithIcon, CanvasWidget, GraphElementGridBase, GraphElementVerticalGapLine, GraphElementHistogram, GraphElementBoxes, GraphLabelsBase, GraphTitle, Image, Keyboard, PixelDataWidget, RadioButton, ScalableImage, SnapshotWidget, SVGImage, TextureMapper, TiledImage, and VideoWidget.
drawToDynamicBitmap()
void drawToDynamicBitmap (BitmapId id)
Render the Drawable object into a dynamic bitmap.
Parameters
id The target dynamic bitmap to use for rendering.
expand()
void expand (int margin = 0)
Expands the Drawable to have the same size as its parent with a given margin around the edge. If there is no parent, the position is set to the size of the entire display.
Parameters
margin (Optional) The margin.
getAbsoluteRect()
Rect getAbsoluteRect () const
Helper function for obtaining the rectangle this Drawable covers, expressed in absolute coordinates.
Returns
The rectangle this Drawable covers expressed in absolute coordinates.
See also
getRect, translateRectToAbsolute
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::draw(), TextArea::draw(), TextAreaWithWildcardBase::draw(), PixelDataWidget::draw(), SVGImage::draw(), VideoWidget::draw(), AbstractShape::drawCanvasWidget(), Circle::drawCanvasWidget(), Line::drawCanvasWidget(), GraphElementArea::drawCanvasWidget(), GraphElementLine::drawCanvasWidget(), GraphElementDots::drawCanvasWidget(), GraphElementDiamonds::drawCanvasWidget(), TextureMapper::drawQuad(), Container::getLastChildNear(), ScrollableContainer::handleClickEvent(), ScrollableContainer::handleDragEvent(), and SnapshotWidget::makeSnapshot().
getFirstChild()
virtual Drawable * getFirstChild () inline virtual
Function for obtaining the first child of this drawable if any.
Returns
A pointer on the first child drawable if any.
See also
Container::getFirstChild
Reimplemented in Container.
    {
        return 0;
    }
getHeight()
int16_t getHeight () const inline
Gets the height of this Drawable.
Returns
The height of this Drawable.
    {
        return rect.height;
    }
References Rect::height, and Drawable::rect.
Referenced by CircleProgress::CircleProgress(), LineProgress::LineProgress(), ModalWindow::ModalWindow(), AbstractDataGraph::addBottomElement(), AbstractDataGraph::addGraphElement(), AbstractDataGraph::addLeftElement(), AbstractDataGraph::addRightElement(), AbstractDataGraph::addTopElement(), TextArea::calculateBoundingArea(), Drawable::centerY(), BoxWithBorder::draw(), ButtonWithLabel::draw(), ScalableImage::draw(), TextureMapper::drawQuad(), GraphLabelsX::drawString(), ModalWindow::getBackgroundHeight(), TextureMapper::getBoundingRect(), SlideMenu::getCollapsedYCoordinate(), AbstractDataGraph::getGraphAreaHeight(), AbstractDataGraph::getGraphAreaHeightIncludingPadding(), AbstractDataGraph::getGraphAreaMarginBottom(), AbstractDataGraph::getGraphAreaMarginTop(), Slider::getIndicatorRadius(), CanvasWidget::getMinimalRect(), Circle::getMinimalRect(), ScrollList::getPositionForItem(), AbstractProgressIndicator::getProgressIndicatorHeight(), DrawableList::getRequiredNumberOfDrawables(), PixelDataWidget::getSolidRect(), ScalableImage::getSolidRect(), SnapshotWidget::getSolidRect(), TiledImage::getSolidRect(), AdjustElements::handleInsert(), TiledImageButtonStyle< T >::handlePressedUpdated(), AdjustElements::handleRemove(), WipeTransition< templateDirection >::handleTickEvent(), CanvasWidget::invalidate(), GraphLabelsX::invalidateGraphPointAt(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), DrawableList::refreshDrawables(), TextArea::resizeToCurrentTextWithAlignment(), ModalWindow::setBackground(), AnalogClock::setBackground(), ButtonWithIcon::setBitmaps(), AbstractDataGraph::setGraphAreaMargin(), AbstractDataGraph::setHeight(), AbstractProgressIndicator::setProgressIndicatorPosition(), TextArea::setTypedText(), Slider::setupHorizontalSlider(), Slider::setupVerticalSlider(), BoxProgress::setValue(), ImageProgress::setValue(), ScrollList::setWindowSize(), ZoomAnimationImage::startTimerAndSetParameters(), AbstractDataGraph::updateAreasPosition(), Slider::updateIndicatorPosition(), and ZoomAnimationImage::updateRenderingMethod().
getLastChild()
virtual void getLastChild (int16_t x, int16_t y, Drawable ** last) pure virtual
Function for obtaining the the last child of this drawable that intersects with the specified point. The last child is the Drawable that is drawn last and therefore the topmost child. Used in input event handling for obtaining the appropriate drawable that should receive the event.
Parameters
x The point of intersection expressed in coordinates relative to the parent.
y The point of intersection expressed in coordinates relative to the parent.
[out] last Last (topmost) Drawable on the given coordinate.
Note
Input events must be delegated to the last drawable of the tree (meaning highest z- order / front-most drawable).
Implemented in Container, ScrollableContainer, and Widget.
getNextSibling()
Drawable * getNextSibling () inline
Gets the next sibling node. This will be the next Drawable that has been added to the same Container as this Drawable.
Returns
The next sibling. If there are no more siblings, the return value is 0.
    {
        return nextSibling;
    }
References Drawable::nextSibling.
getParent()
Drawable * getParent () const inline
Returns the parent node. For the root container, the return value is 0.
Returns
The parent node. For the root container, the return value is 0.
Note
A disconnected Drawable also has parent 0 which may cause strange side effects.
    {
        return parent;
    }
References Drawable::parent.
Referenced by AbstractGraphElement::getGraph().
getRect()
const Rect & getRect () const inline
Gets the rectangle this Drawable covers, in coordinates relative to its parent.
Returns
The rectangle this Drawable covers expressed in coordinates relative to its parent.
See also
getAbsoluteRect
    {
        return rect;
    }
References Drawable::rect.
Referenced by CanvasWidget::draw(), TextureMapper::drawQuad(), Keyboard::handleClickEvent(), Keyboard::handleDragEvent(), SlideMenu::setup(), SlideMenu::setup(), and Slider::updateIndicatorPosition().
getSolidRect()
virtual Rect getSolidRect () const pure virtual
Get (the largest possible) rectangle that is guaranteed to be solid (opaque). This information is important, as any Drawable underneath the solid area does not need to be drawn.
Returns
The solid rectangle part of the Drawable.
Note
The rectangle returned must be relative to upper left corner of the Drawable, meaning that a completely solid widget should return the full size Rect(0, 0, getWidth(), getHeight()). If no area can be guaranteed to be solid, an empty Rect must be returned. Failing to return the correct rectangle may result in errors on the display.
Implemented in Container, Transition::FullSolidRect, Box, Button, CanvasWidget, Image, PixelDataWidget, RadioButton, ScalableImage, SnapshotWidget, SVGImage, TextArea, TextureMapper, TiledImage, TouchArea, and VideoWidget.
getSolidRectAbsolute()
virtual Rect getSolidRectAbsolute () virtual
Helper function for obtaining the largest solid rect (as implemented by getSolidRect()) expressed in absolute coordinates. Will recursively traverse to the root of the tree to find the proper location of the rectangle on the display.
Returns
The (largest) solid rect (as implemented by getSolidRect()) expressed in absolute coordinates.
getVisibleRect()
virtual void getVisibleRect (Rect & rect) const virtual
Function for finding the visible part of this drawable. If the parent node has a smaller area than this Drawable, or if the Drawable is placed "over the edge" of the parent, the parent will act as a view port, cutting off the parts of this Drawable that are outside the region. Traverses the tree and yields a result expressed in absolute coordinates.
Parameters
[out] rect The region of the Drawable that is visible.
Referenced by SnapshotWidget::makeSnapshot().
getWidth()
int16_t getWidth () const inline
Gets the width of this Drawable.
Returns
The width of this Drawable.
    {
        return rect.width;
    }
References Drawable::rect, and Rect::width.
Referenced by CircleProgress::CircleProgress(), LineProgress::LineProgress(), ModalWindow::ModalWindow(), AbstractDataGraph::addBottomElement(), AbstractDataGraph::addGraphElement(), AbstractDataGraph::addLeftElement(), AbstractDataGraph::addRightElement(), AbstractDataGraph::addTopElement(), SwipeContainer::adjustPages(), SwipeContainer::animateLeft(), SwipeContainer::animateLeftWithButton(), SwipeContainer::animateRight(), SwipeContainer::animateRightWithButton(), TextArea::calculateBoundingArea(), TextArea::calculateTextHeight(), Drawable::centerX(), BoxWithBorder::draw(), ButtonWithLabel::draw(), ScalableImage::draw(), SnapshotWidget::draw(), TextureMapper::drawQuad(), GraphLabelsY::drawString(), ModalWindow::getBackgroundWidth(), TextureMapper::getBoundingRect(), SlideMenu::getCollapsedXCoordinate(), AbstractDataGraph::getGraphAreaMarginLeft(), AbstractDataGraph::getGraphAreaMarginRight(), AbstractDataGraph::getGraphAreaWidth(), AbstractDataGraph::getGraphAreaWidthIncludingPadding(), Slider::getIndicatorRadius(), CanvasWidget::getMinimalRect(), Circle::getMinimalRect(), ScrollList::getPositionForItem(), AbstractProgressIndicator::getProgressIndicatorWidth(), DrawableList::getRequiredNumberOfDrawables(), PixelDataWidget::getSolidRect(), ScalableImage::getSolidRect(), SnapshotWidget::getSolidRect(), TiledImage::getSolidRect(), AdjustElements::handleInsert(), TiledImageButtonStyle< T >::handlePressedUpdated(), AdjustElements::handleRemove(), WipeTransition< templateDirection >::handleTickEvent(), CanvasWidget::invalidate(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), DrawableList::refreshDrawables(), TextArea::resizeToCurrentTextWithAlignment(), ModalWindow::setBackground(), AnalogClock::setBackground(), ButtonWithIcon::setBitmaps(), AbstractDataGraph::setGraphAreaMargin(), SwipeContainer::setPageIndicatorCenteredX(), SwipeContainer::setPageIndicatorCenteredX(), AbstractProgressIndicator::setProgressIndicatorPosition(), TextArea::setTypedText(), Slider::setupHorizontalSlider(), Slider::setupVerticalSlider(), BoxProgress::setValue(), ImageProgress::setValue(), AbstractDataGraph::setWidth(), ScrollList::setWindowSize(), ZoomAnimationImage::startTimerAndSetParameters(), AbstractDataGraph::updateAreasPosition(), Slider::updateIndicatorPosition(), and ZoomAnimationImage::updateRenderingMethod().
getX()
int16_t getX () const inline
Gets the x coordinate of this Drawable, relative to its parent.
Returns
The x value, relative to the parent.
    {
        return rect.x;
    }
References Drawable::rect, and Rect::x.
Referenced by TextureMapper::applyTransformation(), SlideMenu::getBackgroundX(), IconButtonStyle< T >::getIconX(), AbstractProgressIndicator::getProgressIndicatorX(), SlideMenu::getStateChangeButtonX(), SwipeContainer::handleClickEvent(), AbstractDataGraph::handleClickEvent(), AbstractDataGraph::handleDragEvent(), SwipeContainer::handleGestureEvent(), SlideTransition< templateDirection >::handleTickEvent(), WipeTransition< templateDirection >::handleTickEvent(), ScrollableContainer::invalidateScrollbars(), TextArea::resizeToCurrentTextWithAlignment(), DigitalClock::setBaselineY(), Gauge::setCenter(), BoxProgress::setValue(), ImageProgress::setValue(), ZoomAnimationImage::startTimerAndSetParameters(), and Slider::updateIndicatorPosition().
getY()
int16_t getY () const inline
Gets the y coordinate of this Drawable, relative to its parent.
Returns
The y value, relative to the parent.
    {
        return rect.y;
    }
References Drawable::rect, and Rect::y.
Referenced by TextureMapper::applyTransformation(), SlideMenu::getBackgroundY(), IconButtonStyle< T >::getIconY(), AbstractProgressIndicator::getProgressIndicatorY(), SlideMenu::getStateChangeButtonY(), SlideTransition< templateDirection >::handleTickEvent(), WipeTransition< templateDirection >::handleTickEvent(), ScrollableContainer::invalidateScrollbars(), TextArea::resizeToCurrentTextWithAlignment(), Gauge::setCenter(), BoxProgress::setValue(), ImageProgress::setValue(), ZoomAnimationImage::startTimerAndSetParameters(), and Slider::updateIndicatorPosition().
handleClickEvent()
virtual void handleClickEvent (const ClickEvent & event) inline virtual
Defines the event handler interface for ClickEvents. The default implementation ignores the event. The event is only received if the Drawable is touchable and visible.
Parameters
event The ClickEvent received from the HAL.
Reimplemented in ClickButtonTrigger, RepeatButtonTrigger, ToggleButtonTrigger, TouchButtonTrigger, ScrollableContainer, ScrollList, ScrollWheelBase, Slider, SwipeContainer, AbstractButton, AbstractDataGraph, Keyboard, RadioButton, RepeatButton, ToggleButton, and TouchArea.
    {
        (void)event; // Unused variable
    }
References void().
Referenced by ScrollableContainer::handleClickEvent(), ScrollList::handleClickEvent(), RepeatButton::handleClickEvent(), ToggleButton::handleClickEvent(), ScrollableContainer::handleDragEvent(), and ScrollableContainer::handleGestureEvent().
handleDragEvent()
virtual void handleDragEvent (const DragEvent & event) inline virtual
Defines the event handler interface for DragEvents. The default implementation ignores the event. The event is only received if the drawable is touchable and visible.
Parameters
event The DragEvent received from the HAL.
Reimplemented in TouchArea, ScrollableContainer, ScrollBase, ScrollWheelBase, Slider, SwipeContainer, AbstractDataGraph, and Keyboard.
    {
        (void)event; // Unused variable
    }
References void().
Referenced by ScrollableContainer::handleDragEvent().
handleGestureEvent()
virtual void handleGestureEvent (const GestureEvent & event) inline virtual
Defines the event handler interface for GestureEvents. The default implementation ignores the event. The event is only received if the Drawable is touchable and visible.
Parameters
event The GestureEvent received from the HAL.
Reimplemented in ScrollableContainer, ScrollBase, ScrollWheelBase, and SwipeContainer.
    {
        (void)event; // Unused variable
    }
References void().
handleTickEvent()
virtual void handleTickEvent () inline virtual
Called periodically by the framework if the Drawable instance has subscribed to timer ticks.
See also
Application::registerTimerWidget
Reimplemented in RepeatButtonTrigger, AbstractProgressIndicator, ScrollableContainer, ScrollBase, SlideMenu, SwipeContainer, ZoomAnimationImage, MoveAnimator< touchgfx::Container >, AnimatedImage, AnimationTextureMapper, RepeatButton, and VideoWidget.
    {
    }
Referenced by RepeatButtonTrigger::handleTickEvent(), and RepeatButton::handleTickEvent().
invalidate()
virtual void invalidate () const virtual
Tell the framework that this entire Drawable needs to be redrawn. It is the same as calling invalidateRect() with Rect(0, 0, getWidth(), getHeight()) as argument.
See also
invalidateRect
Reimplemented in CanvasWidget.
Referenced by ClickButtonTrigger::handleClickEvent(), RepeatButtonTrigger::handleClickEvent(), ToggleButtonTrigger::handleClickEvent(), TouchButtonTrigger::handleClickEvent(), AbstractButton::handleClickEvent(), RadioButton::handleClickEvent(), RepeatButton::handleClickEvent(), SlideTransition< templateDirection >::handleTickEvent(), AnimatedImage::handleTickEvent(), ModalWindow::hide(), Screen::invalidate(), AbstractDataGraph::invalidateAllXAxisPoints(), Drawable::invalidateContent(), TextArea::invalidateContent(), AbstractDataGraph::invalidateGraphArea(), ScrollableContainer::invalidateScrollbars(), SwipeContainer::remove(), ModalWindow::setBackground(), Slider::setBitmaps(), Keyboard::setBufferPosition(), AbstractDirectionProgress::setDirection(), AbstractDataGraph::setGraphRangeXScaled(), AbstractDataGraph::setGraphRangeYScaled(), ZoomAnimationImage::setHeight(), Keyboard::setKeymappingList(), Keyboard::setLayout(), Screen1View::SetLevel(), SwipeContainer::PageIndicator::setNumberOfPages(), RadioButton::setSelected(), ModalWindow::setShadeAlpha(), ModalWindow::setShadeColor(), Screen1View::SetState(), SlideMenu::setup(), SlideMenu::setup(), ImageProgress::setValue(), ZoomAnimationImage::setWidth(), ModalWindow::show(), AnimatedImage::startAnimation(), AnimatedImage::stopAnimation(), AbstractDataGraph::updateAreasPosition(), DirectFrameBufferVideoController< no_streams, output_format >::updateFrame(), DedicatedBufferController< no_streams, width, height, stride, output_format >::updateFrame(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::updateFrame(), Slider::updateIndicatorPosition(), and ZoomAnimationImage::updateRenderingMethod().
invalidateContent()
virtual void invalidateContent () const inline virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented in CacheableContainer, AnalogClock, DigitalClock, AbstractProgressIndicator, ZoomAnimationImage, Box, Button, Line, Gauge, AbstractDataGraph, Image, PixelDataWidget, RadioButton, SnapshotWidget, SVGImage, TextArea, TextAreaWithWildcardBase, TextureMapper, and TouchArea.
    {
        // Consider checking if *this is in the draw chain
        if (visible)
        {
            invalidate();
        }
    }
References Drawable::invalidate(), and Drawable::visible.
Referenced by CacheableContainer::invalidateContent(), AnalogClock::invalidateContent(), DigitalClock::invalidateContent(), AbstractProgressIndicator::invalidateContent(), ZoomAnimationImage::invalidateContent(), Box::invalidateContent(), Button::invalidateContent(), AbstractDataGraph::invalidateContent(), Image::invalidateContent(), PixelDataWidget::invalidateContent(), RadioButton::invalidateContent(), SnapshotWidget::invalidateContent(), and TextAreaWithWildcardBase::invalidateContent().
invalidateRect()
virtual void invalidateRect (Rect & invalidatedArea) const virtual
Request that a region of this drawable is redrawn. All invalidated regions are collected and possibly merged with other regions that have been invalidated. Before the next tick, these regions will then be redrawn by the drawables, widgets and containers, covering the regions.
To invalidate the entire Drawable, use invalidate()
Parameters
[in] invalidatedArea The area of this drawable to redraw expressed in relative coordinates.
See also
invalidate
Reimplemented in CacheableContainer.
Referenced by Keyboard::handleClickEvent(), BlockTransition::handleTickEvent(), WipeTransition< templateDirection >::handleTickEvent(), CanvasWidget::invalidate(), Line::invalidateContent(), SVGImage::invalidateContent(), TextArea::invalidateContent(), TextureMapper::invalidateContent(), GraphElementArea::invalidateGraphPointAt(), GraphElementLine::invalidateGraphPointAt(), GraphElementHistogram::invalidateGraphPointAt(), GraphElementBoxes::invalidateGraphPointAt(), GraphElementDots::invalidateGraphPointAt(), GraphElementDiamonds::invalidateGraphPointAt(), GraphLabelsX::invalidateGraphPointAt(), GraphElementVerticalGapLine::invalidateIndex(), CacheableContainer::invalidateRect(), Screen::invalidateRect(), ScrollableContainer::invalidateScrollbars(), AbstractShape::moveOrigin(), BoxProgress::setValue(), ImageProgress::setValue(), AbstractShape::updateAngle(), Circle::updateArc(), Circle::updateArcEnd(), Circle::updateArcStart(), Line::updateLineWidth(), and AbstractShape::updateScale().
isTouchable()
bool isTouchable () const inline
Gets whether this Drawable receives touch events or not.
Returns
True if touch events are received.
See also
setTouchable
    {
        return touchable;
    }
References Drawable::touchable.
Referenced by Container::getLastChild(), ScrollableContainer::getLastChild(), and Widget::getLastChild().
isVisible()
bool isVisible () const inline
Gets whether this Drawable is visible.
Returns
true if the Drawable is visible.
See also
setVisible
    {
        return visible;
    }
References Drawable::visible.
Referenced by Container::draw(), ScrollableContainer::getLastChild(), Widget::getLastChild(), Keyboard::handleDragEvent(), and AnalogClock::updateClock().
moveRelative()
virtual void moveRelative (int16_t x, int16_t y) virtual
Moves the drawable.
Parameters
x The relative position to move to.
y The relative position to move to.
See also
moveTo, setXY
Note
Will redraw the appropriate areas of the screen.
Referenced by Drawable::moveTo().
moveTo()
virtual void moveTo (int16_t x, int16_t y) inline virtual
Moves the drawable.
Parameters
x The absolute position to move to.
y The absolute position to move to.
See also
moveRelative, setXY
Note
Will redraw the appropriate areas of the screen.
    {
        moveRelative(x - rect.x, y - rect.y);
    }
References Drawable::moveRelative(), Drawable::rect, Rect::x, and Rect::y.
Referenced by SwipeContainer::adjustPages(), ZoomAnimationImage::handleTickEvent(), DigitalClock::setBaselineY(), and Slider::updateIndicatorPosition().
setHeight()
virtual void setHeight (int16_t height) inline virtual
Sets the height of this drawable.
Parameters
height The new height.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Reimplemented in DigitalClock, DrawableList, ScrollBase, ScrollList, ScrollWheelWithSelectionStyle, ZoomAnimationImage, Gauge, AbstractDataGraph, and TextArea.
    {
        rect.height = height;
    }
References Rect::height, and Drawable::rect.
Referenced by WipeTransition< templateDirection >::handleTickEvent(), BoxWithBorderButtonStyle< T >::setBoxWithBorderHeight(), TiledImageButtonStyle< T >::setHeight(), DigitalClock::setHeight(), DrawableList::setHeight(), ScrollBase::setHeight(), ZoomAnimationImage::setHeight(), Gauge::setHeight(), AbstractDataGraph::setHeight(), TextArea::setHeight(), AbstractProgressIndicator::setProgressIndicatorPosition(), and Drawable::setWidthHeight().
setPosition() [1/2]
void setPosition (const Drawable & drawable) inline
Sets the position of the Drawable to the same as the given Drawable. This will copy the x, y, width and height.
Parameters
drawable The Drawable.
See also
setPosition(int16_t,int16_t,int16_t,int16_t)
    {
        setPosition(drawable.getX(), drawable.getY(), drawable.getWidth(), drawable.getHeight());
    }
References Drawable::setPosition().
setPosition() [2/2]
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height) inline
Sets the size and position of this Drawable, relative to its parent. The same as calling setXY(), setWidth() and setHeight() in that order.
Parameters
x The x coordinate of this Drawable relative to its parent.
y The y coordinate of this Drawable relative to its parent.
width The width of this Drawable.
height The height of this Drawable.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
See also
setXY,setWidthHeight,setPosition(const Drawable&)
    {
        setXY(x, y);
        setWidthHeight(width, height);
    }
References Drawable::setWidthHeight(), and Drawable::setXY().
Referenced by CircleProgress::CircleProgress(), CoverTransition< templateDirection >::CoverTransition(), LineProgress::LineProgress(), ModalWindow::ModalWindow(), Screen1ViewBase::Screen1ViewBase(), SlideTransition< templateDirection >::SlideTransition(), WipeTransition< templateDirection >::WipeTransition(), ScrollableContainer::invalidateScrollbars(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), Gauge::setArcPosition(), ModalWindow::setBackground(), BoxWithBorderButtonStyle< T >::setBoxWithBorderPosition(), AbstractDataGraph::setGraphAreaMargin(), Keyboard::setLayout(), Drawable::setPosition(), AbstractProgressIndicator::setProgressIndicatorPosition(), BoxProgress::setProgressIndicatorPosition(), CircleProgress::setProgressIndicatorPosition(), ImageProgress::setProgressIndicatorPosition(), LineProgress::setProgressIndicatorPosition(), TextProgress::setProgressIndicatorPosition(), Keyboard::setTextIndentation(), TextButtonStyle< T >::setTextPosition(), TwoWildcardTextButtonStyle< T >::setTwoWildcardTextPosition(), Slider::setupHorizontalSlider(), Slider::setupVerticalSlider(), BoxProgress::setValue(), ImageProgress::setValue(), WildcardTextButtonStyle< T >::setWildcardTextPosition(), and Slider::updateIndicatorPosition().
setTouchable()
void setTouchable (bool touch) inline
Controls whether this Drawable receives touch events or not.
Parameters
touch If true it will receive touch events, if false it will not.
    {
        touchable = touch;
    }
References Drawable::touchable.
Referenced by AbstractButton::AbstractButton(), AbstractButtonContainer::AbstractButtonContainer(), AbstractDataGraph::AbstractDataGraph(), Keyboard::Keyboard(), ModalWindow::ModalWindow(), ScrollableContainer::ScrollableContainer(), ScrollBase::ScrollBase(), ScrollWheelBase::ScrollWheelBase(), Slider::Slider(), SwipeContainer::SwipeContainer(), SlideMenu::animateToState(), and SlideMenu::animationEndedHandler().
setVisible()
void setVisible (bool vis) inline
Controls whether this Drawable should be visible. Only visible Drawables will have their draw function called. Additionally, invisible drawables will not receive input events.
Parameters
vis true if this Drawable should be visible. By default, drawables are visible unless this function has been called with false as argument.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
    {
        visible = vis;
    }
References Drawable::visible.
Referenced by AnalogClock::AnalogClock(), Gauge::Gauge(), Keyboard::Keyboard(), ScrollableContainer::ScrollableContainer(), ZoomAnimationImage::ZoomAnimationImage(), ScrollableContainer::handleClickEvent(), Keyboard::handleClickEvent(), ModalWindow::hide(), Gauge::setArcVisible(), ScrollableContainer::setScrollbarsPermanentlyVisible(), ModalWindow::show(), and ZoomAnimationImage::updateRenderingMethod().
setWidth()
virtual void setWidth (int16_t width) inline virtual
Sets the width of this drawable.
Parameters
width The new width.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Reimplemented in DigitalClock, DrawableList, ScrollBase, ScrollList, ScrollWheelWithSelectionStyle, ZoomAnimationImage, Gauge, AbstractDataGraph, and TextArea.
    {
        rect.width = width;
    }
References Drawable::rect, and Rect::width.
Referenced by WipeTransition< templateDirection >::handleTickEvent(), BoxWithBorderButtonStyle< T >::setBoxWithBorderWidth(), AbstractProgressIndicator::setProgressIndicatorPosition(), TiledImageButtonStyle< T >::setWidth(), DigitalClock::setWidth(), DrawableList::setWidth(), ScrollBase::setWidth(), ZoomAnimationImage::setWidth(), Gauge::setWidth(), AbstractDataGraph::setWidth(), TextArea::setWidth(), Drawable::setWidthHeight(), and Slider::updateIndicatorPosition().
setWidthHeight() [1/4]
void setWidthHeight (const Bitmap & bitmap) inline
Sets the dimensions (width and height) of the Drawable without changing the x and y coordinates).
Parameters
bitmap The Bitmap to copy the width and height from.
See also
setWidthHeight(int16_t,int16_t)
    {
        setWidthHeight(bitmap.getWidth(), bitmap.getHeight());
    }
References Drawable::setWidthHeight().
setWidthHeight() [2/4]
void setWidthHeight (const Drawable & drawable) inline
Sets the dimensions (width and height) of the Drawable without changing the x and y coordinates).
Parameters
drawable The Drawable to copy the width and height from.
See also
setWidthHeight(int16_t,int16_t)
    {
        setWidthHeight(drawable.getWidth(), drawable.getHeight());
    }
References Drawable::setWidthHeight().
setWidthHeight() [3/4]
void setWidthHeight (const Rect & other) inline
Sets the dimensions (width and height) of the Drawable without changing the x and y coordinates).
Parameters
other The Rect to copy the width and height from.
See also
setWidthHeight(int16_t,int16_t)
    {
        setWidthHeight(other.width, other.height);
    }
References Drawable::setWidthHeight().
setWidthHeight() [4/4]
void setWidthHeight (int16_t width, int16_t height) inline
Sets the dimensions (width and height) of the Drawable without changing the x and y coordinates).
Parameters
width The width.
height The height.
    {
        setWidth(width);
        setHeight(height);
    }
References Drawable::setHeight(), and Drawable::setWidth().
Referenced by AbstractShape::AbstractShape(), Circle::Circle(), Line::Line(), ModalWindow::ModalWindow(), SwipeContainer::add(), TiledImageButtonStyle< T >::handlePressedUpdated(), ZoomAnimationImage::handleTickEvent(), SwipeContainer::remove(), ListLayout::removeAll(), SVGImage::resizeToCurrentSVG(), TextArea::resizeToCurrentText(), TextArea::resizeToCurrentTextWithAlignment(), AbstractProgressIndicator::setBackground(), AnalogClock::setBackground(), Image::setBitmap(), Button::setBitmaps(), AnimatedImageButtonStyle< T >::setBitmaps(), RadioButton::setBitmaps(), Slider::setBitmaps(), ZoomAnimationImage::setBitmaps(), ListLayout::setDirection(), SwipeContainer::PageIndicator::setNumberOfPages(), Drawable::setPosition(), TextButtonStyle< T >::setText(), TiledImageButtonStyle< T >::setTileBitmaps(), TwoWildcardTextButtonStyle< T >::setTwoWildcardText(), SlideMenu::setup(), SlideMenu::setup(), Slider::setupHorizontalSlider(), Gauge::setupNeedleTextureMapper(), Slider::setupVerticalSlider(), Drawable::setWidthHeight(), Drawable::setWidthHeight(), Drawable::setWidthHeight(), WildcardTextButtonStyle< T >::setWildcardText(), and ZoomAnimationImage::updateRenderingMethod().
setX()
virtual void setX (int16_t x) inline virtual
Sets the x coordinate of this Drawable, relative to its parent.
Parameters
x The new x value, relative to the parent. A negative value is allowed.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
    {
        rect.x = x;
    }
References Drawable::rect, and Rect::x.
Referenced by Drawable::centerX(), WipeTransition< templateDirection >::handleTickEvent(), TextArea::resizeHeightToCurrentTextWithRotation(), TextArea::resizeToCurrentTextWithAlignment(), IconButtonStyle< T >::setIconX(), SwipeContainer::setPageIndicatorCenteredX(), TextButtonStyle< T >::setTextX(), TwoWildcardTextButtonStyle< T >::setTwoWildcardTextX(), Slider::setupVerticalSlider(), AbstractDataGraph::setWidth(), WildcardTextButtonStyle< T >::setWildcardTextX(), TextArea::setXBaselineY(), and Drawable::setXY().
setXY() [1/2]
void setXY (const Drawable & drawable) inline
Sets the x and y coordinates of this Drawable.
Parameters
drawable The Drawable to copy the x and y coordinates from.
See also
setXY(int16_t,int16_t)
    {
        setXY(drawable.getX(), drawable.getY());
    }
References Drawable::setXY().
setXY() [2/2]
void setXY (int16_t x, int16_t y) inline
Sets the x and y coordinates of this Drawable, relative to its parent. The same as calling setX() followed by calling setY().
Parameters
x The new x value, relative to the parent. A negative value is allowed.
y The new y value, relative to the parent. A negative value is allowed.
See also
moveTo
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
    {
        setX(x);
        setY(y);
    }
References Drawable::setX(), and Drawable::setY().
Referenced by AbstractProgressIndicator::AbstractProgressIndicator(), AnimatedImageButtonStyle< T >::AnimatedImageButtonStyle(), BoxWithBorderButtonStyle< T >::BoxWithBorderButtonStyle(), DigitalClock::DigitalClock(), ImageButtonStyle< T >::ImageButtonStyle(), SwipeContainer::PageIndicator::PageIndicator(), Screen1ViewBase::Screen1ViewBase(), ScrollBase::ScrollBase(), TiledImageButtonStyle< T >::TiledImageButtonStyle(), ZoomAnimationImage::ZoomAnimationImage(), Keyboard::handleClickEvent(), ModalWindow::setBackground(), ModalWindow::setBackground(), Gauge::setBackgroundOffset(), AnimatedImageButtonStyle< T >::setBitmapXY(), ImageButtonStyle< T >::setBitmapXY(), IconButtonStyle< T >::setIconBitmaps(), SwipeContainer::setPageIndicatorXY(), Drawable::setPosition(), SlideMenu::setup(), SlideMenu::setup(), Slider::setupHorizontalSlider(), Gauge::setupNeedleTextureMapper(), Slider::setupVerticalSlider(), and Drawable::setXY().
setY()
virtual void setY (int16_t y) inline virtual
Sets the y coordinate of this Drawable, relative to its parent.
Parameters
y The new y value, relative to the parent. A negative value is allowed.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
    {
        rect.y = y;
    }
References Drawable::rect, and Rect::y.
Referenced by Drawable::centerY(), WipeTransition< templateDirection >::handleTickEvent(), TextArea::resizeHeightToCurrentTextWithRotation(), TextArea::resizeToCurrentTextWithAlignment(), TextArea::setBaselineY(), AbstractDataGraph::setHeight(), IconButtonStyle< T >::setIconY(), SwipeContainer::setPageIndicatorXYWithCenteredX(), TextButtonStyle< T >::setTextY(), TwoWildcardTextButtonStyle< T >::setTwoWildcardTextY(), Slider::setupHorizontalSlider(), WildcardTextButtonStyle< T >::setWildcardTextY(), Drawable::setXY(), and Slider::updateIndicatorPosition().
translateRectToAbsolute()
virtual void translateRectToAbsolute (Rect & r) const virtual
Helper function for converting a region of this Drawable to absolute coordinates.
Parameters
[in,out] r The Rect to translate.
Referenced by Box::draw(), BoxWithBorder::draw(), ButtonWithLabel::draw(), Button::draw(), ButtonWithIcon::draw(), GraphElementVerticalGapLine::draw(), GraphElementHistogram::draw(), GraphElementBoxes::draw(), GraphTitle::draw(), Image::draw(), Keyboard::draw(), RadioButton::draw(), SnapshotWidget::draw(), TiledImage::draw(), GraphElementGridBase::drawLine(), TextureMapper::drawQuad(), GraphLabelsX::drawString(), and GraphLabelsY::drawString().
Member Data Documentation
nextSibling
Drawable* nextSibling protected
Pointer to the next Drawable. Maintained by containers.
Referenced by Container::add(), Container::contains(), Drawable::getNextSibling(), and Container::removeAll().
parent
Drawable* parent protected
Pointer to this drawable's parent.
Referenced by ListLayout::add(), Drawable::centerX(), Drawable::centerY(), AbstractGraphElement::getGraph(), Drawable::getParent(), ListLayout::insert(), ListLayout::remove(), ListLayout::removeAll(), ListLayout::setDirection(), and CWRVectorRenderer::CanvasWidgetProxy::setParent().
rect
Rect rect protected
The coordinates of this Drawable, relative to its parent.
Referenced by Box::Box(), ScrollableContainer::childGeometryChanged(), ScrollableContainer::doScroll(), GraphTitle::draw(), SnapshotWidget::draw(), ScrollableContainer::getContainedArea(), Drawable::getHeight(), Container::getLastChildNear(), Drawable::getRect(), Transition::FullSolidRect::getSolidRect(), Box::getSolidRect(), Drawable::getWidth(), Drawable::getX(), ScrollableContainer::getXBorder(), ScrollableContainer::getXScrollbar(), Drawable::getY(), ScrollableContainer::getYBorder(), ScrollableContainer::getYScrollbar(), ListLayout::internalAddElementAt(), ListLayout::internalRemoveElement(), TextArea::invalidateContent(), ScrollableContainer::invalidateScrollbars(), ScrollableContainer::isScrollableXY(), SnapshotWidget::makeSnapshot(), Drawable::moveTo(), TextArea::resizeHeightToCurrentTextWithRotation(), Drawable::setHeight(), SVGImage::setSVG(), Drawable::setWidth(), Drawable::setX(), and Drawable::setY().
touchable
bool touchable protected
True if this drawable should receive touch events.
Referenced by Drawable::isTouchable(), and Drawable::setTouchable().
visible
bool visible protected
True if this drawable should be drawn.
Referenced by Drawable::invalidateContent(), SVGImage::invalidateContent(), Drawable::isVisible(), and Drawable::setVisible().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/Drawable.hpp