Battery Simulator Documentation: TwoWildcardTextButtonStyle< T >
TwoWildcardTextButtonStyle< T >
#include "TwoWildcardTextButtonStyle.hpp"
Public Member Functions
TwoWildcardTextButtonStyle ()
void setTwoWildcardText (TypedText t)
void setTwoWildcardTextColors (colortype newColorReleased, colortype newColorPressed)
void setTwoWildcardTextPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTwoWildcardTextRotation (TextRotation rotation)
void setTwoWildcardTextX (int16_t x)
void setTwoWildcardTextXY (int16_t x, int16_t y)
void setTwoWildcardTextY (int16_t y)
void setWildcardTextBuffer1 (const Unicode::UnicodeChar *value)
void setWildcardTextBuffer2 (const Unicode::UnicodeChar *value)
Protected Member Functions
virtual void handleAlphaUpdated ()
virtual void handlePressedUpdated ()
Protected Attributes
colortype colorPressed
The color pressed.
colortype colorReleased
The color released.
TextAreaWithTwoWildcards twoWildcardText
The wildcard text.
Detailed Description
template<class T>
class touchgfx::TwoWildcardTextButtonStyle< T >
A wildcard text button style.
An wildcard text button style. This class is supposed to be used with one of the ButtonTrigger classes to create a functional button. This class will show a text with a wildcard in one of two colors depending on the state of the button (pressed or released).
The TwoWildcardTextButtonStyle does not set the size of the enclosing container (normally AbstractButtonContainer). The size must be set manually.
To get a background behind the text, use TwoWildcardTextButtonStyle together with e.g. ImageButtonStyle:
TwoWildcardTextButtonStyle<ImageButtonStyle<ClickButtonTrigger> > myButton;
The position of the text can be adjusted with setTwoWildcardTextXY (default is centered).
Template Parameters
T Generic type parameter. Typically a AbstractButtonContainer subclass.
See also
AbstractButtonContainer
Constructor & Destructor Documentation
TwoWildcardTextButtonStyle()
template<class T > TwoWildcardTextButtonStyle () inline
        : T()
    {
        T::add(twoWildcardText);
    }
References TwoWildcardTextButtonStyle< T >::twoWildcardText.
Member Function Documentation
handleAlphaUpdated()
template<class T > virtual void handleAlphaUpdated () inline protected virtual
Handles what should happen when the alpha is updated.
    {
        twoWildcardText.setAlpha(T::getAlpha());
        T::handleAlphaUpdated();
    }
References TextArea::setAlpha(), and TwoWildcardTextButtonStyle< T >::twoWildcardText.
handlePressedUpdated()
template<class T > virtual void handlePressedUpdated () inline protected virtual
Handles what should happen when the pressed state is updated.
    {
        twoWildcardText.setColor(T::getPressed() ? colorPressed : colorReleased);
        T::handlePressedUpdated();
    }
References TwoWildcardTextButtonStyle< T >::colorPressed, TwoWildcardTextButtonStyle< T >::colorReleased, TextArea::setColor(), and TwoWildcardTextButtonStyle< T >::twoWildcardText.
Referenced by TwoWildcardTextButtonStyle< T >::setTwoWildcardTextColors().
setTwoWildcardText()
template<class T > void setTwoWildcardText (TypedText t) inline
Sets wildcard text.
Parameters
t A TypedText to process.
    {
        twoWildcardText.setTypedText(t);
        twoWildcardText.setWidthHeight(T::getWidth(), T::getHeight());
    }
References TextArea::setTypedText(), Drawable::setWidthHeight(), and TwoWildcardTextButtonStyle< T >::twoWildcardText.
setTwoWildcardTextColors()
template<class T > void setTwoWildcardTextColors (colortype newColorReleased, colortype newColorPressed) inline
Sets wild card text colors.
Parameters
newColorReleased The new color released.
newColorPressed The new color pressed.
    {
        colorReleased = newColorReleased;
        colorPressed = newColorPressed;
        handlePressedUpdated();
    }
References TwoWildcardTextButtonStyle< T >::colorPressed, TwoWildcardTextButtonStyle< T >::colorReleased, and TwoWildcardTextButtonStyle< T >::handlePressedUpdated().
setTwoWildcardTextPosition()
template<class T > void setTwoWildcardTextPosition (int16_t x, int16_t y, int16_t width, int16_t height) inline
Sets text position and dimensions.
Parameters
x The x coordinate.
y The y coordinate.
width The width of the text.
height The height of the text.
    {
        twoWildcardText.setPosition(x, y, width, height);
    }
References Drawable::setPosition(), and TwoWildcardTextButtonStyle< T >::twoWildcardText.
setTwoWildcardTextRotation()
template<class T > void setTwoWildcardTextRotation (TextRotation rotation) inline
Sets wildcard text rotation.
Parameters
rotation The rotation.
    {
        twoWildcardText.setRotation(rotation);
    }
References TextArea::setRotation(), and TwoWildcardTextButtonStyle< T >::twoWildcardText.
setTwoWildcardTextX()
template<class T > void setTwoWildcardTextX (int16_t x) inline
Sets wildcard text x coordinate.
Parameters
x The x coordinate.
    {
        twoWildcardText.setX(x);
    }
References Drawable::setX(), and TwoWildcardTextButtonStyle< T >::twoWildcardText.
Referenced by TwoWildcardTextButtonStyle< T >::setTwoWildcardTextXY().
setTwoWildcardTextXY()
template<class T > void setTwoWildcardTextXY (int16_t x, int16_t y) inline
Sets wildcard text position.
Parameters
x The x coordinate.
y The y coordinate.
    {
        setTwoWildcardTextX(x);
        setTwoWildcardTextY(y);
    }
References TwoWildcardTextButtonStyle< T >::setTwoWildcardTextX(), and TwoWildcardTextButtonStyle< T >::setTwoWildcardTextY().
setTwoWildcardTextY()
template<class T > void setTwoWildcardTextY (int16_t y) inline
Sets wildcard text y coordinate.
Parameters
y The y coordinate.
    {
        twoWildcardText.setY(y);
    }
References Drawable::setY(), and TwoWildcardTextButtonStyle< T >::twoWildcardText.
Referenced by TwoWildcardTextButtonStyle< T >::setTwoWildcardTextXY().
setWildcardTextBuffer1()
template<class T > void setWildcardTextBuffer1 (const Unicode::UnicodeChar * value) inline
Sets the first wildcard in the text. Must be a null-terminated UnicodeChar array.
Parameters
value A pointer to the UnicodeChar to set the wildcard to.
    {
        twoWildcardText.setWildcard1(value);
    }
References TextAreaWithTwoWildcards::setWildcard1(), and TwoWildcardTextButtonStyle< T >::twoWildcardText.
setWildcardTextBuffer2()
template<class T > void setWildcardTextBuffer2 (const Unicode::UnicodeChar * value) inline
Sets the second wildcard in the text. Must be a null-terminated UnicodeChar array.
Parameters
value A pointer to the UnicodeChar to set the wildcard to.
    {
        twoWildcardText.setWildcard2(value);
    }
References TextAreaWithTwoWildcards::setWildcard2(), and TwoWildcardTextButtonStyle< T >::twoWildcardText.
Member Data Documentation
colorPressed
template<class T > colortype colorPressed protected
The color pressed.
Referenced by TwoWildcardTextButtonStyle< T >::handlePressedUpdated(), and TwoWildcardTextButtonStyle< T >::setTwoWildcardTextColors().
colorReleased
template<class T > colortype colorReleased protected
The color released.
Referenced by TwoWildcardTextButtonStyle< T >::handlePressedUpdated(), and TwoWildcardTextButtonStyle< T >::setTwoWildcardTextColors().
twoWildcardText
template<class T > TextAreaWithTwoWildcards twoWildcardText protected
The wildcard text.
Referenced by TwoWildcardTextButtonStyle< T >::TwoWildcardTextButtonStyle(), TwoWildcardTextButtonStyle< T >::handleAlphaUpdated(), TwoWildcardTextButtonStyle< T >::handlePressedUpdated(), TwoWildcardTextButtonStyle< T >::setTwoWildcardText(), TwoWildcardTextButtonStyle< T >::setTwoWildcardTextPosition(), TwoWildcardTextButtonStyle< T >::setTwoWildcardTextRotation(), TwoWildcardTextButtonStyle< T >::setTwoWildcardTextX(), TwoWildcardTextButtonStyle< T >::setTwoWildcardTextY(), TwoWildcardTextButtonStyle< T >::setWildcardTextBuffer1(), and TwoWildcardTextButtonStyle< T >::setWildcardTextBuffer2().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/buttons/TwoWildcardTextButtonStyle.hpp