Battery Simulator Documentation: FontDataReader
FontDataReader abstract
#include "FontCache.hpp"
Public Member Functions
virtual ~FontDataReader ()
virtual void close ()=0
virtual void open ()=0
virtual void readData (void *out, uint32_t numberOfBytes)=0
virtual void setPosition (uint32_t position)=0
Detailed Description
Constructor & Destructor Documentation
~FontDataReader()
virtual ~FontDataReader () inline virtual
    {
    }
Member Function Documentation
close()
virtual void close () pure virtual
Referenced by FontCache::close().
open()
virtual void open () pure virtual
Referenced by FontCache::open().
readData()
virtual void readData (void * out, uint32_t numberOfBytes) pure virtual
Referenced by FontCache::readData().
setPosition()
virtual void setPosition (uint32_t position) pure virtual
Referenced by FontCache::setPosition().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/fonts/include/fonts/FontCache.hpp