Battery Simulator Documentation: LCD1bpp::bwRLEdata
LCD1bpp::bwRLEdata
Public Member Functions
bwRLEdata (const uint8_t *src=0)
uint8_t getColor () const
int32_t getLength () const
void init (const uint8_t *src)
void skipNext (int32_t skip)
Private Member Functions
uint8_t getNextHalfByte ()
void getNextLength ()
Private Attributes
uint8_t color
const uint8_t * data
bool firstHalfByte
int32_t length
uint8_t nextHalfByte
uint8_t rleByte
uint8_t thisHalfByte
Detailed Description
Constructor & Destructor Documentation
bwRLEdata()
bwRLEdata (const uint8_t * src = 0) inline
            : data(src), thisHalfByte(0), nextHalfByte(0), rleByte(0), firstHalfByte(true), color(0), length(0)
        {
            init(src);
        }
References LCD1bpp::bwRLEdata::init().
Member Function Documentation
getColor()
uint8_t getColor () const inline
        {
            return color;
        }
References LCD1bpp::bwRLEdata::color.
getLength()
int32_t getLength () const inline
        {
            return length;
        }
References LCD1bpp::bwRLEdata::length.
getNextHalfByte()
uint8_t getNextHalfByte () inline private
        {
            assert(data != 0 && "class bwRLEdata not properly initialized");
            if (firstHalfByte) // Start of new byte, read data from BW_RLE stream
            {
                rleByte = *data++;
            }
            const uint8_t len = rleByte & 0xF; // Read lower half
            rleByte >>= 4;                     // Shift upper half down to make it ready
            firstHalfByte = !firstHalfByte;    // Toggle 'start of byte'
            return len;
        }
References LCD1bpp::bwRLEdata::firstHalfByte, and LCD1bpp::bwRLEdata::rleByte.
Referenced by LCD1bpp::bwRLEdata::getNextLength(), and LCD1bpp::bwRLEdata::init().
getNextLength()
void getNextLength () inline private
        {
            length = thisHalfByte; // Length is the next byte
            // Update read ahead buffer
            thisHalfByte = nextHalfByte;
            nextHalfByte = getNextHalfByte();
            color = ~color; // Update the color of next run
            // If number after 'length' is 0
            while (thisHalfByte == 0)
            {
                length <<= 4;           // Multiply length by 16 and
                length += nextHalfByte; // add the number after 0
                // We have used the next two half bytes, read two new ones
                thisHalfByte = getNextHalfByte();
                nextHalfByte = getNextHalfByte();
            }
            if (length == 0)
            {
                getNextLength();
            }
        }
References LCD1bpp::bwRLEdata::getNextHalfByte(), LCD1bpp::bwRLEdata::getNextLength(), LCD1bpp::bwRLEdata::nextHalfByte, and LCD1bpp::bwRLEdata::thisHalfByte.
Referenced by LCD1bpp::bwRLEdata::getNextLength(), LCD1bpp::bwRLEdata::init(), and LCD1bpp::bwRLEdata::skipNext().
init()
void init (const uint8_t * src) inline
        {
            data = src;
            rleByte = 0;
            firstHalfByte = true;
            color = ~0; // Will be flipped to 0 by first call to getNextLength() below
            if (src)
            {
                // Read two half-bytes ahead
                thisHalfByte = getNextHalfByte();
                nextHalfByte = getNextHalfByte();
                getNextLength();
            }
        }
References LCD1bpp::bwRLEdata::firstHalfByte, LCD1bpp::bwRLEdata::getNextHalfByte(), LCD1bpp::bwRLEdata::getNextLength(), LCD1bpp::bwRLEdata::nextHalfByte, LCD1bpp::bwRLEdata::rleByte, and LCD1bpp::bwRLEdata::thisHalfByte.
Referenced by LCD1bpp::bwRLEdata::bwRLEdata().
skipNext()
void skipNext (int32_t skip) inline
        {
            for (;;)
            {
                if (length > skip) // Is the current length enough?
                {
                    length -= skip; // Reduce the length
                    skip = 0;       // No more to skip
                    break;          // Done!
                }
                else
                {
                    skip -= length;  // Skip the entire run
                    getNextLength(); // Swap colors and Read length of next run
                }
            }
        }
References LCD1bpp::bwRLEdata::getNextLength(), and LCD1bpp::bwRLEdata::length.
Member Data Documentation
color
uint8_t color private
Referenced by LCD1bpp::bwRLEdata::getColor().
data
const uint8_t* data private
firstHalfByte
bool firstHalfByte private
Referenced by LCD1bpp::bwRLEdata::getNextHalfByte(), and LCD1bpp::bwRLEdata::init().
length
int32_t length private
Referenced by LCD1bpp::bwRLEdata::getLength(), and LCD1bpp::bwRLEdata::skipNext().
nextHalfByte
uint8_t nextHalfByte private
Referenced by LCD1bpp::bwRLEdata::getNextLength(), and LCD1bpp::bwRLEdata::init().
rleByte
uint8_t rleByte private
Referenced by LCD1bpp::bwRLEdata::getNextHalfByte(), and LCD1bpp::bwRLEdata::init().
thisHalfByte
uint8_t thisHalfByte private
Referenced by LCD1bpp::bwRLEdata::getNextLength(), and LCD1bpp::bwRLEdata::init().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/platform/driver/lcd/LCD1bpp.hpp