Battery Simulator Documentation: AbstractPainterRGB565
AbstractPainterRGB565
#include "AbstractPainterRGB565.hpp"
Public Member Functions
AbstractPainterRGB565 ()
FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t newpix, uint16_t bufpix, uint8_t alpha) const
FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t R, uint16_t G, uint16_t B, uint16_t bufpix, uint8_t alpha) const
Public Member Functions inherited from AbstractPainter
AbstractPainter ()
virtual ~AbstractPainter ()
void framebufferToDisplay (int16_t &widgetX, int16_t &widgetY) const
virtual HAL::RenderingMethod getRenderingMethod () const
virtual void paint (uint8_t *destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const =0
virtual bool setup (const Rect &widgetRect) const
virtual void tearDown () const
Static Public Attributes
static const uint16_t BMASK = 0x001F
Mask for blue (0000000000011111)
static const uint16_t GMASK = 0x07E0
Mask for green (0000011111100000)
static const uint16_t RMASK = 0xF800
Mask for red (1111100000000000)
Additional Inherited Members
Static Protected Member Functions inherited from AbstractPainter
static FORCE_INLINE_FUNCTION bool compatibleFramebuffer (Bitmap::BitmapFormat format)
Protected Attributes inherited from AbstractPainter
int16_t widgetWidth
The width of the widget on screen, used by framebufferToDisplay()
Detailed Description
The AbstractPainterRGB565 class is an abstract class for creating a painter to draw on a RGB565 display using CanvasWidgetRenderer.
See also
AbstractPainter
Constructor & Destructor Documentation
AbstractPainterRGB565()
AbstractPainterRGB565 () inline
        : AbstractPainter()
    {
        assert(compatibleFramebuffer(Bitmap::RGB565) && "The chosen painter only works with RGB565 displays");
    }
References AbstractPainter::compatibleFramebuffer(), and Bitmap::RGB565.
Member Function Documentation
alphaBlend() [1/2]
FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t newpix, uint16_t bufpix, uint8_t alpha) const inline
Mix colors from a new pixel and a buffer pixel with the given alpha applied to the new pixel, and the inverse alpha applied to the buffer pixel.
Parameters
newpix The new pixel value.
bufpix The buffer pixel value.
alpha The alpha to apply to the new pixel.
Returns
The result of blending the two colors into a new color.
    {
        return alphaBlend(newpix & RMASK, newpix & GMASK, newpix & BMASK, bufpix, alpha);
    }
References AbstractPainterRGB565::alphaBlend(), AbstractPainterRGB565::BMASK, AbstractPainterRGB565::GMASK, and AbstractPainterRGB565::RMASK.
Referenced by AbstractPainterRGB565::alphaBlend(), PainterRGB565Bitmap::paint(), and PainterRGB565L8Bitmap::paint().
alphaBlend() [2/2]
FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t R, uint16_t G, uint16_t B, uint16_t bufpix, uint8_t alpha) const inline
Mix colors from a new pixel and a buffer pixel with the given alpha applied to the new pixel, and the inverse alpha applied to the buffer pixel.
Parameters
R The red color (0-31 shifted into RMASK).
G The green color (0-63 shifted into GMASK).
B The blue color (0-31 shifted into BMASK).
bufpix The buffer pixel value.
alpha The alpha of the R,G,B.
Returns
The result of blending the two colors into a new color.
    {
        const uint8_t ialpha = 0xFF - alpha;
        return (((R * alpha + (bufpix & RMASK) * ialpha) / 255) & RMASK) |
               (((G * alpha + (bufpix & GMASK) * ialpha) / 255) & GMASK) |
               (((B * alpha + (bufpix & BMASK) * ialpha) / 255) & BMASK);
    }
References AbstractPainterRGB565::BMASK, AbstractPainterRGB565::GMASK, and AbstractPainterRGB565::RMASK.
Member Data Documentation
BMASK
const uint16_t BMASK = 0x001F static
Mask for blue (0000000000011111)
Referenced by AbstractPainterRGB565::alphaBlend(), and AbstractPainterRGB565::alphaBlend().
GMASK
const uint16_t GMASK = 0x07E0 static
Mask for green (0000011111100000)
Referenced by AbstractPainterRGB565::alphaBlend(), and AbstractPainterRGB565::alphaBlend().
RMASK
const uint16_t RMASK = 0xF800 static
Mask for red (1111100000000000)
Referenced by AbstractPainterRGB565::alphaBlend(), and AbstractPainterRGB565::alphaBlend().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/AbstractPainterRGB565.hpp