Battery Simulator Documentation: RepeatButtonTrigger
RepeatButtonTrigger
#include "RepeatButtonTrigger.hpp"
Public Member Functions
RepeatButtonTrigger ()
int getDelay ()
int getInterval ()
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleTickEvent ()
void setDelay (int delay)
void setInterval (int interval)
Public Member Functions inherited from AbstractButtonContainer
AbstractButtonContainer ()
virtual void executeAction ()
uint8_t getAlpha () const
bool getPressed () const
void setAction (GenericCallback< const AbstractButtonContainer & > &callback)
void setAlpha (uint8_t newAlpha)
void setPressed (bool isPressed)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Private Attributes
int16_t ticks
int16_t ticksBeforeContinuous
int16_t ticksDelay
int16_t ticksInterval
Additional Inherited Members
Protected Member Functions inherited from AbstractButtonContainer
virtual void handleAlphaUpdated ()
virtual void handlePressedUpdated ()
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes inherited from AbstractButtonContainer
GenericCallback< const AbstractButtonContainer & > * action
The action to be executed.
uint8_t alpha
The current alpha value. 255 denotes solid, 0 denotes completely invisible.
bool pressed
True if pressed.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A repeat button trigger. This trigger will create a button that reacts to a consistent touch. This means it will call the set action repeatedly as long as it is touched. The RepeatButtonTrigger can be combined with one or more of the ButtonStyle classes to create a fully functional button.
Constructor & Destructor Documentation
RepeatButtonTrigger()
RepeatButtonTrigger () inline
        : AbstractButtonContainer(), ticksDelay(30), ticksInterval(15), ticks(0), ticksBeforeContinuous(0)
    {
    }
Member Function Documentation
getDelay()
int getDelay () inline
Gets the delay in ticks from first button activation until next activation.
Returns
The delay, measured in ticks, between first activation and second activation.
See also
setDelay
    {
        return ticksDelay;
    }
References RepeatButtonTrigger::ticksDelay.
getInterval()
int getInterval () inline
The interval between repeated activations, measured in ticks. This is the number of ticks between the an activation beyond the first and the following activation.
Returns
The interval between repeated activations, measured in ticks.
See also
setInterval
    {
        return ticksInterval;
    }
References RepeatButtonTrigger::ticksInterval.
handleClickEvent()
virtual void handleClickEvent (const ClickEvent & event) inline virtual
Defines the event handler interface for ClickEvents. The default implementation ignores the event. The event is only received if the Drawable is touchable and visible.
Parameters
event The ClickEvent received from the HAL.
Reimplemented from Drawable.
    {
        bool wasPressed = getPressed();
        bool newPressedValue = (event.getType() == ClickEvent::PRESSED);
        if ((newPressedValue && !wasPressed) || (!newPressedValue && wasPressed))
        {
            setPressed(newPressedValue);
            invalidate();
        }
        if (event.getType() == ClickEvent::PRESSED)
        {
            executeAction();
            ticks = 0;
            ticksBeforeContinuous = ticksDelay;
            Application::getInstance()->registerTimerWidget(this);
        }
        else
        {
            Application::getInstance()->unregisterTimerWidget(this);
        }
    }
References AbstractButtonContainer::executeAction(), Application::getInstance(), AbstractButtonContainer::getPressed(), Drawable::invalidate(), ClickEvent::PRESSED, AbstractButtonContainer::setPressed(), RepeatButtonTrigger::ticks, RepeatButtonTrigger::ticksBeforeContinuous, and RepeatButtonTrigger::ticksDelay.
handleTickEvent()
virtual void handleTickEvent () inline virtual
Called periodically by the framework if the Drawable instance has subscribed to timer ticks.
See also
Application::registerTimerWidget
Reimplemented from Drawable.
    {
        AbstractButtonContainer::handleTickEvent();
        if (!pressed)
        {
            return;
        }
        if (ticks == ticksBeforeContinuous)
        {
            executeAction();
            ticks = 0;
            ticksBeforeContinuous = ticksInterval;
        }
        else
        {
            ticks++;
        }
    }
References AbstractButtonContainer::executeAction(), Drawable::handleTickEvent(), AbstractButtonContainer::pressed, RepeatButtonTrigger::ticks, RepeatButtonTrigger::ticksBeforeContinuous, and RepeatButtonTrigger::ticksInterval.
setDelay()
void setDelay (int delay) inline
Sets the delay (in number of ticks) from the first button activation until the next time it will be automatically activated.
Parameters
delay The delay, measured in ticks, between first activation and second activation.
See also
setInterval, getDelay
    {
        ticksDelay = delay;
    }
References RepeatButtonTrigger::ticksDelay.
setInterval()
void setInterval (int interval) inline
Sets the interval in number of ticks between each each activation of the pressed button after the second activation.
Parameters
interval The interval between repeated activations, measured in ticks.
See also
setDelay, getInterval
    {
        ticksInterval = interval;
    }
References RepeatButtonTrigger::ticksInterval.
Member Data Documentation
ticks
int16_t ticks private
Referenced by RepeatButtonTrigger::handleClickEvent(), and RepeatButtonTrigger::handleTickEvent().
ticksBeforeContinuous
int16_t ticksBeforeContinuous private
Referenced by RepeatButtonTrigger::handleClickEvent(), and RepeatButtonTrigger::handleTickEvent().
ticksDelay
int16_t ticksDelay private
Referenced by RepeatButtonTrigger::getDelay(), RepeatButtonTrigger::handleClickEvent(), and RepeatButtonTrigger::setDelay().
ticksInterval
int16_t ticksInterval private
Referenced by RepeatButtonTrigger::getInterval(), RepeatButtonTrigger::handleTickEvent(), and RepeatButtonTrigger::setInterval().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/buttons/RepeatButtonTrigger.hpp