Battery Simulator Documentation: PainterXRGB8888
PainterXRGB8888
#include "PainterXRGB8888.hpp"
Public Member Functions
PainterXRGB8888 (colortype color=0)
virtual void paint (uint8_t *destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const
virtual void setColor (colortype color)
Public Member Functions inherited from AbstractPainterARGB8888
AbstractPainterARGB8888 ()
Public Member Functions inherited from AbstractPainter
AbstractPainter ()
virtual ~AbstractPainter ()
void framebufferToDisplay (int16_t &widgetX, int16_t &widgetY) const
virtual HAL::RenderingMethod getRenderingMethod () const
virtual bool setup (const Rect &widgetRect) const
virtual void tearDown () const
Public Member Functions inherited from AbstractPainterColor
AbstractPainterColor (colortype color=0)
virtual ~AbstractPainterColor ()
colortype getColor () const
Protected Attributes
uint8_t painterBlue
The blue part of the color.
uint8_t painterGreen
The green part of the color.
uint8_t painterRed
The red part of the color.
Protected Attributes inherited from AbstractPainter
int16_t widgetWidth
The width of the widget on screen, used by framebufferToDisplay()
Protected Attributes inherited from AbstractPainterColor
colortype painterColor
The color.
Additional Inherited Members
Static Protected Member Functions inherited from AbstractPainter
static FORCE_INLINE_FUNCTION bool compatibleFramebuffer (Bitmap::BitmapFormat format)
Detailed Description
The PainterXRGB8888 class allows a shape to be filled with a given color value. This allows anti-aliased elements to be drawn.
See also
AbstractPainter
Constructor & Destructor Documentation
PainterXRGB8888()
PainterXRGB8888 (colortype color = 0) inline
Initializes a new instance of the PainterXRGB8888 class.
Parameters
color (Optional) the color, default is black.
        : AbstractPainterARGB8888(), AbstractPainterColor(color)
    {
    }
Member Function Documentation
paint()
void paint (uint8_t * destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const virtual
Paints a streak of pixels (all with the same alpha) in the framebuffer. The first pixel to paint is at 'offset' relative to 'destination' (to be able to support 1bpp, 2bpp and 4bpp). The first pixel to paint is at the given 'widgetX', 'widgetY' coordinate. The number of pixels to paint is 'count' and the alpha to apply is 'alpha'.
Note that the widgetX, widgetY is relative to the widget in the framebuffer, not the display. To convert the coordinate to display widget coordinates, use framebufferToDisplay().
Parameters
[in] destination If non-null, the pointer.
offset The offset to add to the destination.
widgetX The widget x coordinate.
widgetY The widget y coordinate.
count Number of pixels.
alpha The alpha of the pixels.
See also
AbstractPainter::setup, AbstractPainter::tearDown, AbstractPainter::framebufferToDisplay
Implements AbstractPainter.
{
    uint32_t* RESTRICT framebuffer = reinterpret_cast<uint32_t*>(destination) + offset;
    const uint32_t* const lineEnd = framebuffer + count;
    if (alpha == 0xFF)
    {
        do
        {
            *framebuffer = painterColor;
        } while (++framebuffer < lineEnd);
    }
    else
    {
        do
        {
            const uint8_t ialpha = 0xFF - alpha;
            const uint32_t rgbBg = *framebuffer;
            *framebuffer = (LCD::div255(painterBlue * alpha + (rgbBg & 0xFF) * ialpha)) |
                           (LCD::div255(painterGreen * alpha + ((rgbBg >> 8) & 0xFF) * ialpha) << 8) |
                           (LCD::div255(painterRed * alpha + ((rgbBg >> 16) & 0xFF) * ialpha) << 16);
        } while (++framebuffer < lineEnd);
    }
}
References LCD::div255(), PainterXRGB8888::painterBlue, AbstractPainterColor::painterColor, PainterXRGB8888::painterGreen, PainterXRGB8888::painterRed, and RESTRICT.
setColor()
virtual void setColor (colortype color) inline virtual
Sets color to use when drawing the CanvasWidget.
Parameters
color The color.
Reimplemented from AbstractPainterColor.
    {
        AbstractPainterColor::setColor(color);
        painterRed = Color::getRed(color);
        painterGreen = Color::getGreen(color);
        painterBlue = Color::getBlue(color);
    }
References Color::getBlue(), Color::getGreen(), Color::getRed(), PainterXRGB8888::painterBlue, PainterXRGB8888::painterGreen, PainterXRGB8888::painterRed, and AbstractPainterColor::setColor().
Member Data Documentation
painterBlue
uint8_t painterBlue protected
The blue part of the color.
Referenced by PainterXRGB8888::paint(), and PainterXRGB8888::setColor().
painterGreen
uint8_t painterGreen protected
The green part of the color.
Referenced by PainterXRGB8888::paint(), and PainterXRGB8888::setColor().
painterRed
uint8_t painterRed protected
The red part of the color.
Referenced by PainterXRGB8888::paint(), and PainterXRGB8888::setColor().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/PainterXRGB8888.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/PainterXRGB8888.cpp