Battery Simulator Documentation: GeneratedVectorFont
GeneratedVectorFont
#include "GeneratedFont.hpp"
Public Member Functions
GeneratedVectorFont (uint16_t baseline, float scale, const VectorFontNode *vectorGlyphs, const VectorFontData &fontData, const uint16_t *const *glyphData, const VectorKerningNode *kerningTable, const uint16_t *const gsubData, const FontContextualFormsTable *formsTable)
virtual const FontContextualFormsTable * getContextualFormsTable () const
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode) const
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, const uint8_t *&pixelData, uint8_t &bitsPerPixel) const
virtual const uint16_t * getGSUBTable () const
virtual int8_t getKerning (Unicode::UnicodeChar prevChar, const GlyphNode *glyph) const
virtual float getScaleFactor () const
virtual bool isVectorBasedFont () const
Public Member Functions inherited from Font
virtual ~Font ()
virtual FORCE_INLINE_FUNCTION uint16_t getBaseline () const
virtual FORCE_INLINE_FUNCTION uint8_t getBitsPerPixel () const
virtual FORCE_INLINE_FUNCTION uint8_t getByteAlignRow () const
virtual uint16_t getCharWidth (const Unicode::UnicodeChar c) const
virtual Unicode::UnicodeChar getEllipsisChar () const
virtual Unicode::UnicodeChar getFallbackChar () const
virtual FORCE_INLINE_FUNCTION uint16_t getHeight () const
FORCE_INLINE_FUNCTION uint8_t getMaxPixelsLeft () const
FORCE_INLINE_FUNCTION uint8_t getMaxPixelsRight () const
virtual uint16_t getNumberOfLines (const Unicode::UnicodeChar *text,...) const
FORCE_INLINE_FUNCTION uint16_t getPixelsAboveTop () const
FORCE_INLINE_FUNCTION uint16_t getPixelsBelowBottom () const
virtual int16_t getSpacingAbove (const Unicode::UnicodeChar *text,...) const
virtual uint16_t getStringWidth (const Unicode::UnicodeChar *text,...) const
virtual uint16_t getStringWidth (TextDirection textDirection, const Unicode::UnicodeChar *text,...) const
TOUCHGFX_DEPRECATED ("Please use getBaseline() instead.", virtual uint16_t getFontHeight() const)
TOUCHGFX_DEPRECATED ("Please use getHeight() instead.", virtual uint16_t getMaxTextHeight(const Unicode::UnicodeChar *text,...) const)
TOUCHGFX_DEPRECATED ("Please use getHeight() instead.", virtual uint16_t getMinimumTextHeight() const)
Private Member Functions
const VectorFontNode * find (Unicode::UnicodeChar unicode) const
const GlyphNode * getGlyphNode (const VectorFontNode *node) const
Private Attributes
const FontContextualFormsTable * arabicTable
const uint16_t * gsubTable
const VectorKerningNode * kerningTable
uint16_t numberOfGlyphs
float scaleFactor
const VectorFontNode * vectorNodes
const uint16_t *const * vectorTable
Static Private Attributes
static GlyphNode glyphNode
Additional Inherited Members
Static Public Member Functions inherited from Font
static FORCE_INLINE_FUNCTION bool isInvisibleZeroWidth (Unicode::UnicodeChar character)
Protected Member Functions inherited from Font
Font (uint16_t height, uint16_t baseline, uint8_t pixAboveTop, uint8_t pixBelowBottom, uint8_t bitsPerPixel, uint8_t byteAlignRow, uint8_t maxLeft, uint8_t maxRight, const Unicode::UnicodeChar fallbackChar, const Unicode::UnicodeChar ellipsisChar)
uint16_t getStringWidthLTR (TextDirection textDirection, const Unicode::UnicodeChar *text, va_list pArg) const
uint16_t getStringWidthRTL (TextDirection textDirection, const Unicode::UnicodeChar *text, va_list pArg) const
Protected Attributes inherited from Font
uint8_t bAlignRow: 1
The glyphs are saved with each row byte aligned.
uint16_t baselineHeight
The baseline.
uint8_t bPerPixel: 7
The number of bits per pixel.
Unicode::UnicodeChar ellipsisCharacter
The ellipsis character used for truncating long texts.
Unicode::UnicodeChar fallbackCharacter
The fallback character to use when no glyph exists for the wanted character.
uint16_t fontHeight
The font height in pixels.
uint8_t maxPixelsLeft
The maximum number of pixels a glyph extends to the left.
uint8_t maxPixelsRight
The maximum number of pixels a glyph extends to the right.
uint8_t pixelsAboveTop
The number of pixels above the top.
uint8_t pixelsBelowBottom
The number of pixels below the bottom.
Detailed Description
Constructor & Destructor Documentation
GeneratedVectorFont()
GeneratedVectorFont (uint16_t baseline, float scale, const VectorFontNode * vectorGlyphs, const VectorFontData & fontData, const uint16_t *const * glyphData, const VectorKerningNode * kerningTable, const uint16_t *const gsubData, const FontContextualFormsTable * formsTable)
 : Font((int)ceilf((fontData.maxBelowBottom + fontData.baselineHeight) * scale), baseline,
        (uint8_t)ceilf(fontData.maxAboveTop * scale),
        (uint8_t)ceilf(fontData.maxBelowBottom * scale), 0 /*bitsPerPixel*/, 0 /*byteAlignRow*/,
        (uint8_t)ceilf(fontData.maxLeft * scale),
        (uint8_t)ceilf(fontData.maxRight * scale),
        fontData.fallbackChar,
        fontData.ellipsisChar),
   scaleFactor(scale), vectorNodes(vectorGlyphs), vectorTable(glyphData), kerningTable(kerning),
   arabicTable(formsTable), numberOfGlyphs(fontData.numberOfGlyphs)
{
    if (gsubData[0] != 0)
    {
        gsubTable = gsubData;
    }
    else
    {
        gsubTable = 0;
    }
}
References GeneratedVectorFont::gsubTable.
Member Function Documentation
find()
const VectorFontNode * find (Unicode::UnicodeChar unicode) const private
{
    // Some fonts does not have a glyphList. Cannot be searched...
    if (vectorNodes == 0)
    {
        return 0;
    }
    int32_t min = 0;
    int32_t max = numberOfGlyphs - 1;
    int32_t mid = min + (unicode - vectorNodes[min].unicode); // Linear up from [min].unicode
    if (mid < min)
    {
        // Unicode < [min].unicode => not found
        return (VectorFontNode*)0;
    }
    if (mid > max)
    {
        // Linear up ends too high
        mid = max - (vectorNodes[max].unicode - unicode); // Linear down from [max].unicode
        if (mid > max)
        {
            // Unicode > [max].unicode => not found
            return (VectorFontNode*)0;
        }
        if (mid < min)
        {
            // Linear down ends too low, take the middle element
            mid = (min + max) / 2;
        }
    }
    while (min <= max)
    {
        const Unicode::UnicodeChar midUnicode = vectorNodes[mid].unicode;
        if (unicode == midUnicode)
        {
            // Found at [mid]
            return vectorNodes + mid;
        }
        if (unicode < midUnicode)
        {
            // Unicode is in lower half
            max = mid - 1;
            if (max < min)
            {
                // Range is empty => not found
                break;
            }
            // We adjusted max, try linear down from [max].unicode
            mid = max - (vectorNodes[max].unicode - unicode);
            if (mid > max)
            {
                // Unicode > [max].unicode => not found
                break;
            }
            if (mid < min)
            {
                // Linear down ends too low, take the middle element
                mid = (min + max) / 2;
            }
        }
        else
        {
            // Unicode is in upper half
            min = mid + 1;
            if (min > max)
            {
                // Range is empty => not found
                break;
            }
            // We adjusted min, try linear up from [min].unicode
            mid = min + (unicode - vectorNodes[min].unicode);
            if (mid < min)
            {
                // Unicode < [min].unicode => not found
                break;
            }
            if (mid > max)
            {
                // Linear up ends too high, take the middle element
                mid = (min + max) / 2;
            }
        }
    }
    return (VectorFontNode*)0;
}
References GeneratedVectorFont::numberOfGlyphs, and GeneratedVectorFont::vectorNodes.
Referenced by GeneratedVectorFont::getGlyph(), and GeneratedVectorFont::getGlyph().
getContextualFormsTable()
virtual const FontContextualFormsTable * getContextualFormsTable () const inline virtual
Gets the contextual forms table used in arabic fonts.
Returns
The FontContextualFormsTable or null if the font has no table.
Reimplemented from Font.
{ return arabicTable; }
References GeneratedVectorFont::arabicTable.
getGlyph() [1/2]
const GlyphNode * getGlyph (Unicode::UnicodeChar unicode) const virtual
Gets the glyph data associated with the specified Unicode. Please note that in case of Thai letters and Arabic letters where diacritics can be placed relative to the previous character(s), please use TextProvider::getNextLigature() instead as it will create a temporary GlyphNode that will be adjusted with respect to X/Y position.
Parameters
unicode The character to look up.
Returns
A pointer to the glyph node or null if the glyph was not found.
See also
TextProvider::getNextLigature
Reimplemented from Font.
{
    const VectorFontNode* const node = find(unicode);
    if (node == 0)
    {
        return 0;
    }
    else
    {
        return getGlyphNode(node);
    }
}
References GeneratedVectorFont::find(), and GeneratedVectorFont::getGlyphNode().
getGlyph() [2/2]
const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, const uint8_t *& pixelData, uint8_t & bitsPerPixel) const virtual
Gets the glyph data associated with the specified Unicode. Please note that in case of Thai letters and Arabic letters where diacritics can be placed relative to the previous character(s), please use TextProvider::getNextLigature() instead as it will create a temporary GlyphNode that will be adjusted with respect to X/Y position.
Parameters
unicode The character to look up.
pixelData Pointer to the pixel data for the glyph if the glyph is found. This is set by this method.
[out] bitsPerPixel Reference where to place the number of bits per pixel.
Returns
A pointer to the glyph node or null if the glyph was not found.
Implements Font.
{
    const VectorFontNode* const node = find(unicode);
    if (node == 0)
    {
        return 0;
    }
    else
    {
        const uint16_t* contourData = &(vectorTable[unicode / 2048][node->dataOffset]);
        pixelData = (const uint8_t*)contourData;
        bitsPerPixel = 0xFF;
        return getGlyphNode(node);
    }
}
References GeneratedVectorFont::find(), GeneratedVectorFont::getGlyphNode(), and GeneratedVectorFont::vectorTable.
getGlyphNode()
const GlyphNode * getGlyphNode (const VectorFontNode * node) const private
{
    glyphNode.dataOffset = 0;
    uint8_t flags = 0;
    //Convert data from VectorFontNode to glyphNode using scaleFactor
    glyphNode.unicode = node->unicode;
    const int width = (node->width == 0) ? 0 : ((int)ceilf(node->width * scaleFactor) + 1);
    glyphNode._width = width; // Save low 8 bit
    // Set flags bits for values above 8 bit
    if (width > 255)
    {
        flags |= GLYPH_DATA_WIDTH_BIT8;
    }
    const int height = (int)ceilf(node->height * scaleFactor);
    glyphNode._height = height;
    if (height > 255)
    {
        flags |= GLYPH_DATA_HEIGHT_BIT8;
    }
    const int top = (int)ceilf(node->top * scaleFactor);
    glyphNode._top = top;
    if (top > 255)
    {
        flags |= ((top & 0x300) >> 3); // GLYPH_DATA_TOP_BIT8 + 9
    }
    const int left = (int)(node->left * scaleFactor);
    glyphNode.left = left;
    const int advance = (int)(node->advance * scaleFactor + 0.5f);
    glyphNode._advance = advance;
    if (advance > 255)
    {
        flags |= GLYPH_DATA_ADVANCE_BIT8;
    }
    glyphNode._kerningTablePos = (uint8_t)node->kerningTablePos;
    if (node->kerningTablePos > 255)
    {
        flags |= (node->kerningTablePos >> 8) & GLYPH_DATA_KERNINGTABLEPOS_BIT8_10;
    }
    glyphNode.kerningTableSize = node->kerningTableSize;
    glyphNode.flags = flags;
    return &glyphNode;
}
References touchgfx::GLYPH_DATA_ADVANCE_BIT8, touchgfx::GLYPH_DATA_HEIGHT_BIT8, touchgfx::GLYPH_DATA_KERNINGTABLEPOS_BIT8_10, touchgfx::GLYPH_DATA_WIDTH_BIT8, GeneratedVectorFont::glyphNode, and GeneratedVectorFont::scaleFactor.
Referenced by GeneratedVectorFont::getGlyph(), and GeneratedVectorFont::getGlyph().
getGSUBTable()
virtual const uint16_t * getGSUBTable () const inline virtual
Gets GSUB table. Currently only used for Devanagari fonts.
Returns
The GSUB table or null if font has GSUB no table.
Reimplemented from Font.
{ return gsubTable; }
References GeneratedVectorFont::gsubTable.
getKerning()
int8_t getKerning (Unicode::UnicodeChar prevChar, const GlyphNode * glyph) const virtual
Gets the kerning distance between two characters.
Parameters
prevChar The Unicode value of the previous character.
glyph the glyph object for the current character.
Returns
The kerning distance between prevChar and glyph char.
Reimplemented from Font.
{
    if (!glyph || glyph->kerningTableSize == 0)
    {
        return 0;
    }
    const VectorKerningNode* kerndata = kerningTable + glyph->kerningTablePos();
    for (uint16_t i = glyph->kerningTableSize; i > 0; i--, kerndata++)
    {
        if (prevChar == kerndata->unicodePrevChar)
        {
            const float scaledDistance = kerndata->distance * scaleFactor;
            return (int)(scaledDistance >= 0.0f ? (scaledDistance + 0.5f) : (scaledDistance - 0.5f));
        }
        if (prevChar < kerndata->unicodePrevChar)
        {
            break;
        }
    }
    return 0;
}
References GeneratedVectorFont::kerningTable, and GeneratedVectorFont::scaleFactor.
getScaleFactor()
virtual float getScaleFactor () const inline virtual
Returns the scale factor
Returns
The scale factor
Reimplemented from Font.
{ return scaleFactor; }
References GeneratedVectorFont::scaleFactor.
isVectorBasedFont()
virtual bool isVectorBasedFont () const inline virtual
Returns true if this Font is vector based. Default is false.
Returns
True if this Font is vector based.
Reimplemented from Font.
{ return true; }
Member Data Documentation
arabicTable
const FontContextualFormsTable* arabicTable private
Referenced by GeneratedVectorFont::getContextualFormsTable().
glyphNode
GlyphNode glyphNode static private
Referenced by GeneratedVectorFont::getGlyphNode().
gsubTable
const uint16_t* gsubTable private
Referenced by GeneratedVectorFont::GeneratedVectorFont(), and GeneratedVectorFont::getGSUBTable().
kerningTable
const VectorKerningNode* kerningTable private
Referenced by GeneratedVectorFont::getKerning().
numberOfGlyphs
uint16_t numberOfGlyphs private
Referenced by GeneratedVectorFont::find().
scaleFactor
float scaleFactor private
Referenced by GeneratedVectorFont::getGlyphNode(), GeneratedVectorFont::getKerning(), and GeneratedVectorFont::getScaleFactor().
vectorNodes
const VectorFontNode* vectorNodes private
Referenced by GeneratedVectorFont::find().
vectorTable
const uint16_t* const* vectorTable private
Referenced by GeneratedVectorFont::getGlyph().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/fonts/include/fonts/GeneratedFont.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/fonts/src/GeneratedFont.cpp