Battery Simulator Documentation: ToggleButton
ToggleButton
#include "ToggleButton.hpp"
Public Member Functions
void forceState (bool activeState)
bool getState () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void setBitmaps (const Bitmap &bitmapReleased, const Bitmap &bitmapPressed)
Public Member Functions inherited from Button
Button ()
virtual void draw (const Rect &invalidatedArea) const
uint8_t getAlpha () const
Bitmap getCurrentlyDisplayedBitmap () const
virtual Rect getSolidRect () const
virtual void invalidateContent () const
void setAlpha (uint8_t newAlpha)
Public Member Functions inherited from AbstractButton
AbstractButton ()
virtual void executeAction ()
virtual bool getPressedState () const
void setAction (GenericCallback< const AbstractButton & > &callback)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
Bitmap originalPressed
Contains the bitmap that was originally being displayed when button is pressed.
Protected Attributes inherited from Button
uint8_t alpha
The current alpha value. 255=solid, 0=invisible.
Bitmap down
The image to display when button is pressed.
Bitmap up
The image to display when button is released (normal state).
Protected Attributes inherited from AbstractButton
GenericCallback< const AbstractButton & > * action
The callback to be executed when this AbstractButton is clicked.
bool pressed
Is the button pressed or released? True if pressed.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A ToggleButton is a Button specialization that swaps the two bitmaps when clicked, such that the previous "pressed" bitmap, now becomes the one displayed when button is not pressed. This can by used to give the effect of a button that can be pressed in and when it is subsequently pressed, it will pop back out.
Member Function Documentation
forceState()
void forceState (bool activeState)
Allows the ToggleButton to be forced into either the pressed state, or the normal state. In the pressed state, the Button will always be shown as pressed down (and shown as released when the user presses it). In the normal state, the Button will be show as released or pressed depending on its actual state.
Parameters
activeState If true, swap the images for released and pressed. If false display the Button normally.
{
    if (activeState)
    {
        // up should equal originalPressed
        if (up.getId() != originalPressed.getId())
        {
            down = up;
            up = originalPressed;
        }
    }
    else
    {
        // down should equal originalPressed
        if (down.getId() != originalPressed.getId())
        {
            up = down;
            down = originalPressed;
        }
    }
}
References Button::down, Bitmap::getId(), ToggleButton::originalPressed, and Button::up.
getState()
bool getState () const inline
Gets the state of the ToggleButton as set with forceState.
Returns
True if the button has been toggled, i.e. the pressed state is shown when the button is not pressed.
    {
        return up.getId() == originalPressed.getId();
    }
References Bitmap::getId(), ToggleButton::originalPressed, and Button::up.
handleClickEvent()
void handleClickEvent (const ClickEvent & event) virtual
Updates the current state of the button. The state can be either pressed or released, and if the new state is different from the current state, the button is also invalidated to force a redraw.
If the button state is changed from ClickEvent::PRESSED to ClickEvent::RELEASED, the associated action (if any) is also executed.
Parameters
event Information about the click.
Reimplemented from AbstractButton.
{
    if (pressed && (event.getType() == ClickEvent::RELEASED))
    {
        const Bitmap tmp = up;
        up = down;
        down = tmp;
    }
    Button::handleClickEvent(event);
}
References Button::down, Drawable::handleClickEvent(), AbstractButton::pressed, ClickEvent::RELEASED, and Button::up.
setBitmaps()
virtual void setBitmaps (const Bitmap & bitmapReleased, const Bitmap & bitmapPressed) inline virtual
Sets the two bitmaps used by this button. One bitmap for the released (normal) state and one bitmap for the pressed state. The images are expected to be of the same dimensions, and the Button is resized to the dimensions of the pressed Bitmap.
Parameters
bitmapReleased Bitmap to use when button is released.
bitmapPressed Bitmap to use when button is pressed.
Note
It is assumed that the dimensions of the bitmaps are the same. Unexpected (visual) behavior may be observed if the bitmaps are of different sizes.
The user code must call invalidate() in order to update the button on the display.
Reimplemented from Button.
    {
        originalPressed = bitmapPressed;
        Button::setBitmaps(bitmapReleased, bitmapPressed);
    }
References ToggleButton::originalPressed, and Button::setBitmaps().
Member Data Documentation
originalPressed
Bitmap originalPressed protected
Contains the bitmap that was originally being displayed when button is pressed.
Referenced by ToggleButton::forceState(), ToggleButton::getState(), and ToggleButton::setBitmaps().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/ToggleButton.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/ToggleButton.cpp