Battery Simulator Documentation: CWRVectorRenderer::StrokeCanvas
CWRVectorRenderer::StrokeCanvas
Public Member Functions
StrokeCanvas (const AbstractPainter *const painter, const Rect &canvasAreaAbs, const Rect &invalidatedAreaRel, uint8_t globalAlpha, const Matrix3x3 &m)
void drawFinalLineCap ()
void lineCapInsteadOfLineJoin (bool drawLineCaps)
void setStroke (float width, float miterLimit, VGStrokeLineJoin lineJoin, VGStrokeLineCap lineCap, uint8_t alpha)
void strokeBezierCubic (float x0, float y0, float x1, float y1, float x2, float y2, float x, float y)
void strokeBezierQuad (float x0, float y0, const float x1, const float y1, const float x, const float y)
bool strokeClose (float x, float y)
bool strokeDrawDoubleLineCap ()
void strokeLineTo (float x, float y)
void strokeMoveTo (float x, float y)
bool strokeRender ()
Private Member Functions
virtual void lineTo (CWRUtil::Q5 x, CWRUtil::Q5 y)
void lineToWithTransform (float x, float y)
void moveToWithTransform (float x, float y)
void strokeDrawLineCap (float x2, float y2, float x3, float y3)
void strokeDrawLineJoin (float x, float y, float x1, float y1, float x2, float y2, float x3, float y3, float x4, float y4)
void strokeDrawLineJoinRound (float x, float y, float x2, float y2, float x3, float y3, int level)
Private Member Functions inherited from Canvas
Canvas (const AbstractPainter *const painter, const Rect &canvasAreaAbs, const Rect &invalidatedAreaRel, uint8_t globalAlpha)
virtual ~Canvas ()
bool close ()
void cubicBezierTo (float x0, float y0, float x1, float y1, float x2, float y2, float x, float y)
Rasterizer::FillingRule getFillingRule () const
template<typename T >
void lineTo (T x, T y)
void moveTo (CWRUtil::Q5 x, CWRUtil::Q5 y)
template<typename T >
void moveTo (T x, T y)
void quadraticBezierTo (float x0, float y0, const float x1, const float y1, const float x, const float y)
bool render (uint8_t customAlpha=255)
void setFillingRule (Rasterizer::FillingRule rule)
FORCE_INLINE_FUNCTION bool wasOutlineTooComplex ()
Private Attributes
bool drawLineCapInsteadOfLineJoin
bool firstLineTo
float initialStrokeEndX
float initialStrokeEndY
float initialStrokeStartX
float initialStrokeStartY
float lastStrokeEndX
float lastStrokeEndY
float lastStrokeStartX
float lastStrokeStartY
float lastX
float lastY
const Matrix3x3 & matrix
float miterLimitSquared
bool noLineHasBeenDrawn
uint8_t strokeAlpha
VGStrokeLineCap strokeLineCap
VGStrokeLineJoin strokeLineJoin
float strokeWidthHalf
Detailed Description
Constructor & Destructor Documentation
StrokeCanvas()
StrokeCanvas (const AbstractPainter *const painter, const Rect & canvasAreaAbs, const Rect & invalidatedAreaRel, uint8_t globalAlpha, const Matrix3x3 & m) inline
            : Canvas(painter, canvasAreaAbs, invalidatedAreaRel, globalAlpha),
              matrix(m),
              firstLineTo(false), noLineHasBeenDrawn(true), drawLineCapInsteadOfLineJoin(false),
              strokeWidthHalf(1.0f), miterLimitSquared(0.0f), strokeLineJoin(VG_STROKE_LINEJOIN_BEVEL), strokeLineCap(VG_STROKE_LINECAP_BUTT), strokeAlpha(255),
              lastX(0.0f), lastY(0.0f),
              initialStrokeStartX(0.0f), initialStrokeStartY(0.0f), initialStrokeEndX(0.0f), initialStrokeEndY(0.0f),
              lastStrokeStartX(0.0f), lastStrokeStartY(0.0f), lastStrokeEndX(0.0f), lastStrokeEndY(0.0f)
        {
            setFillingRule(Rasterizer::FILL_NON_ZERO);
        }
References Canvas::setFillingRule().
Member Function Documentation
drawFinalLineCap()
void drawFinalLineCap ()
{
    strokeDrawLineCap(lastStrokeEndX, lastStrokeEndY, initialStrokeStartX, initialStrokeStartY);
}
lineCapInsteadOfLineJoin()
void lineCapInsteadOfLineJoin (bool drawLineCaps)
{
    drawLineCapInsteadOfLineJoin = drawLineCaps;
}
lineTo()
virtual void lineTo (CWRUtil::Q5 x, CWRUtil::Q5 y) inline private virtual
Draw line from the current (x, y) to the new (x, y) as part of the shape being drawn. As for moveTo, lineTo commands completely outside the drawing are are discarded.
Parameters
x The x coordinate for the pen position in CWRUtil::Q5 format.
y The y coordinate for the pen position in CWRUtil::Q5 format.
See also
CWRUtil::Q5, moveTo
Reimplemented from Canvas.
        {
            // This function is called from the Canvas Bezier curve functions, so we need to call our own function to draw the stroke.
            strokeLineTo(x.to<float>(), y.to<float>());
        }
References CWRVectorRenderer::StrokeCanvas::strokeLineTo().
lineToWithTransform()
void lineToWithTransform (float x, float y) inline private
        {
            Matrix3x3::Point point = matrix.affineTransform(x, y);
            Canvas::lineTo(CWRUtil::toQ5<float>(point.x), CWRUtil::toQ5<float>(point.y));
        }
References Canvas::lineTo().
moveToWithTransform()
void moveToWithTransform (float x, float y) inline private
        {
            Matrix3x3::Point point = matrix.affineTransform(x, y);
            Canvas::moveTo(CWRUtil::toQ5<float>(point.x), CWRUtil::toQ5<float>(point.y));
        }
References Canvas::moveTo().
setStroke()
void setStroke (float width, float miterLimit, VGStrokeLineJoin lineJoin, VGStrokeLineCap lineCap, uint8_t alpha) inline
        {
            strokeWidthHalf = abs(width) / 2.0f;
            miterLimitSquared = miterLimit * strokeWidthHalf * miterLimit * strokeWidthHalf;
            strokeLineJoin = lineJoin;
            strokeLineCap = lineCap;
            strokeAlpha = alpha;
        }
References touchgfx::abs(), CWRVectorRenderer::alpha, CWRVectorRenderer::StrokeCanvas::miterLimitSquared, CWRVectorRenderer::StrokeCanvas::strokeAlpha, CWRVectorRenderer::StrokeCanvas::strokeLineCap, CWRVectorRenderer::StrokeCanvas::strokeLineJoin, and CWRVectorRenderer::StrokeCanvas::strokeWidthHalf.
strokeBezierCubic()
void strokeBezierCubic (float x0, float y0, float x1, float y1, float x2, float y2, float x, float y) inline
        {
            Canvas::cubicBezierTo(x0, y0, x1, y1, x2, y2, x, y);
        }
References Canvas::cubicBezierTo().
strokeBezierQuad()
void strokeBezierQuad (float x0, float y0, const float x1, const float y1, const float x, const float y) inline
        {
            Canvas::quadraticBezierTo(x0, y0, x1, y1, x, y);
        }
References Canvas::quadraticBezierTo().
strokeClose()
bool strokeClose (float x, float y)
{
    if (strokeDrawDoubleLineCap())
    {
        return false; // Created two line-caps, stop drawing, we are done
    }
    strokeDrawLineJoin(x, y, lastStrokeStartX, lastStrokeStartY,
                       lastStrokeEndX, lastStrokeEndY, initialStrokeStartX, initialStrokeStartY, initialStrokeEndX, initialStrokeEndY);
    return true; // Closed as with a line-join, continue drawing on inside
}
strokeDrawDoubleLineCap()
bool strokeDrawDoubleLineCap ()
{
    if (noLineHasBeenDrawn)
    {
        const float y1 = lastY - strokeWidthHalf;
        const float y2 = lastY + strokeWidthHalf;
        moveToWithTransform(lastX, y1);
        strokeDrawLineCap(lastX, y1, lastX, y2);
        strokeDrawLineCap(lastX, y2, lastX, y1);
        return true;
    }
    return false;
}
strokeDrawLineCap()
void strokeDrawLineCap (float x2, float y2, float x3, float y3) private
{
    if (strokeLineCap == VG_STROKE_LINECAP_BUTT)
    {
        lineToWithTransform(x2, y2);
        lineToWithTransform(x3, y3);
        return;
    }
    const float dx = (x3 - x2) / 2.0f;
    const float dy = (y3 - y2) / 2.0f;
    // dx,dy is from (x2,y2) to the midpoint between (x2,y2) and (x3,y3)
    // +dy,-dx is orthogonal and points in the direction of where the cap should be drawn
    if (strokeLineCap == VG_STROKE_LINECAP_SQUARE)
    {
        lineToWithTransform(x2 + dy, y2 - dx);
        lineToWithTransform(x3 + dy, y3 - dx);
        return;
    }
    // VG_STROKE_LINECAP_ROUND:
    // Using 3^2 + 4^2 = 5^2 as well as 7^2 + 24^2 = 25^2
    lineToWithTransform(x2, y2);
    lineToWithTransform(x2 + dx * 0.04f + dy * 0.28f, y2 + dy * 0.04f - dx * 0.28f);
    lineToWithTransform(x2 + dx * 0.2f + dy * 0.6f, y2 + dy * 0.2f - dx * 0.6f);
    lineToWithTransform(x2 + dx * 0.4f + dy * 0.8f, y2 + dy * 0.4f - dx * 0.8f);
    lineToWithTransform(x2 + dx * 0.72f + dy * 0.96f, y2 + dy * 0.72f - dx * 0.96f);
    lineToWithTransform(x2 + dx + dy, y2 + dy - dx);
    lineToWithTransform(x2 + dx * 1.28f + dy * 0.96f, y2 + dy * 1.28f - dx * 0.96f);
    lineToWithTransform(x2 + dx * 1.6f + dy * 0.8f, y2 + dy * 1.6f - dx * 0.8f);
    lineToWithTransform(x2 + dx * 1.8f + dy * 0.6f, y2 + dy * 1.8f - dx * 0.6f);
    lineToWithTransform(x2 + dx * 1.96f + dy * 0.28f, y2 + dy * 1.96f - dx * 0.28f);
    lineToWithTransform(x3, y3);
}
References CWRVectorRenderer::strokeLineCap, touchgfx::VG_STROKE_LINECAP_BUTT, and touchgfx::VG_STROKE_LINECAP_SQUARE.
strokeDrawLineJoin()
void strokeDrawLineJoin (float x, float y, float x1, float y1, float x2, float y2, float x3, float y3, float x4, float y4) private
{
    if (strokeLineJoin == VG_STROKE_LINEJOIN_ROUND)
    {
        lineToWithTransform(x2, y2);
        // Same formula as used below for MITER
        if ((x1 - x2) * (y3 - y4) >= (y1 - y2) * (x3 - x4))
        {
            strokeDrawLineJoinRound(x, y, x2, y2, x3, y3, 1);
        }
        lineToWithTransform(x3, y3);
        return;
    }
    if (strokeLineJoin == VG_STROKE_LINEJOIN_MITER)
    {
        // https://en.wikipedia.org/wiki/Line%E2%80%93line_intersection#Given_two_points_on_each_line
        const float divisor = (x1 - x2) * (y3 - y4) - (y1 - y2) * (x3 - x4);
        // If divisor>0, we are on the "outside" of the angle
        // If divisor<0, we are on the "inside" of the angle
        if (divisor != 0.0f)
        {
            const float miterX = ((x1 * y2 - y1 * x2) * (x3 - x4) - (x1 - x2) * (x3 * y4 - y3 * x4)) / divisor;
            const float miterY = ((x1 * y2 - y1 * x2) * (y3 - y4) - (y1 - y2) * (x3 * y4 - y3 * x4)) / divisor;
            const float distSquared = (x - miterX) * (x - miterX) + (y - miterY) * (y - miterY);
            if (distSquared <= miterLimitSquared)
            {
                lineToWithTransform(miterX, miterY);
                return;
            }
        }
    }
    // VG_STROKE_LINEJOIN_BEVEL (and fallback for VG_STROKE_LINEJOIN_MITER)
    lineToWithTransform(x2, y2);
    lineToWithTransform(x3, y3);
}
References CWRVectorRenderer::strokeLineJoin, touchgfx::VG_STROKE_LINEJOIN_MITER, and touchgfx::VG_STROKE_LINEJOIN_ROUND.
strokeDrawLineJoinRound()
void strokeDrawLineJoinRound (float x, float y, float x2, float y2, float x3, float y3, int level) private
{
    assert(level >= 1 && level <= 3);
    float midX = (x2 + x3) / 2.0f;
    float midY = (y2 + y3) / 2.0f;
    const float midLen = sqrtf((x - midX) * (x - midX) + (y - midY) * (y - midY));
    if (midLen == 0.0f)
    {
        const float dx = (x3 - x2) / 2.0f;
        const float dy = (y3 - y2) / 2.0f;
        midX = x2 + dx + dy;
        midY = y2 + dy - dx;
    }
    else
    {
        midX = x + (midX - x) * strokeWidthHalf / midLen;
        midY = y + (midY - y) * strokeWidthHalf / midLen;
    }
    if (level < 3)
    {
        strokeDrawLineJoinRound(x, y, x2, y2, midX, midY, level + 1);
        lineToWithTransform(midX, midY);
        strokeDrawLineJoinRound(x, y, midX, midY, x3, y3, level + 1);
    }
    else
    {
        lineToWithTransform(midX, midY);
    }
}
strokeLineTo()
void strokeLineTo (float x, float y)
{
    const float dx = x - lastX;
    const float dy = y - lastY;
    float len = sqrtf(dx * dx + dy * dy);
    if (len > 0.0f)
    {
        noLineHasBeenDrawn = false;
        len /= strokeWidthHalf;
        const float thisStrokeStartX = lastX + dy / len;
        const float thisStrokeStartY = lastY - dx / len;
        const float thisStrokeEndX = x + dy / len;
        const float thisStrokeEndY = y - dx / len;
        if (firstLineTo)
        {
            initialStrokeStartX = thisStrokeStartX;
            initialStrokeStartY = thisStrokeStartY;
            initialStrokeEndX = thisStrokeEndX;
            initialStrokeEndY = thisStrokeEndY;
            moveToWithTransform(thisStrokeStartX, thisStrokeStartY);
            firstLineTo = false;
        }
        else if (drawLineCapInsteadOfLineJoin)
        {
            strokeDrawLineCap(lastStrokeEndX, lastStrokeEndY, thisStrokeStartX, thisStrokeStartY);
            drawLineCapInsteadOfLineJoin = false;
        }
        else
        {
            strokeDrawLineJoin(lastX, lastY, lastStrokeStartX, lastStrokeStartY,
                               lastStrokeEndX, lastStrokeEndY, thisStrokeStartX, thisStrokeStartY, thisStrokeEndX, thisStrokeEndY);
        }
        lastStrokeStartX = thisStrokeStartX;
        lastStrokeStartY = thisStrokeStartY;
        lastStrokeEndX = thisStrokeEndX;
        lastStrokeEndY = thisStrokeEndY;
        lastX = x;
        lastY = y;
    }
}
Referenced by CWRVectorRenderer::StrokeCanvas::lineTo().
strokeMoveTo()
void strokeMoveTo (float x, float y)
{
    lastX = x;
    lastY = y;
    firstLineTo = true;
    noLineHasBeenDrawn = true;
}
References CWRVectorRenderer::StrokeCanvas::firstLineTo, CWRVectorRenderer::StrokeCanvas::lastX, CWRVectorRenderer::StrokeCanvas::lastY, and CWRVectorRenderer::StrokeCanvas::noLineHasBeenDrawn.
strokeRender()
bool strokeRender () inline
        {
            return Canvas::render(strokeAlpha);
        }
References Canvas::render(), and CWRVectorRenderer::StrokeCanvas::strokeAlpha.
Member Data Documentation
drawLineCapInsteadOfLineJoin
bool drawLineCapInsteadOfLineJoin private
firstLineTo
bool firstLineTo private
Referenced by CWRVectorRenderer::StrokeCanvas::strokeMoveTo().
initialStrokeEndX
float initialStrokeEndX private
initialStrokeEndY
float initialStrokeEndY private
initialStrokeStartX
float initialStrokeStartX private
initialStrokeStartY
float initialStrokeStartY private
lastStrokeEndX
float lastStrokeEndX private
lastStrokeEndY
float lastStrokeEndY private
lastStrokeStartX
float lastStrokeStartX private
lastStrokeStartY
float lastStrokeStartY private
lastX
float lastX private
Referenced by CWRVectorRenderer::StrokeCanvas::strokeMoveTo().
lastY
float lastY private
Referenced by CWRVectorRenderer::StrokeCanvas::strokeMoveTo().
matrix
const Matrix3x3& matrix private
miterLimitSquared
float miterLimitSquared private
Referenced by CWRVectorRenderer::StrokeCanvas::setStroke().
noLineHasBeenDrawn
bool noLineHasBeenDrawn private
Referenced by CWRVectorRenderer::StrokeCanvas::strokeMoveTo().
strokeAlpha
uint8_t strokeAlpha private
Referenced by CWRVectorRenderer::StrokeCanvas::setStroke(), and CWRVectorRenderer::StrokeCanvas::strokeRender().
strokeLineCap
VGStrokeLineCap strokeLineCap private
Referenced by CWRVectorRenderer::StrokeCanvas::setStroke().
strokeLineJoin
VGStrokeLineJoin strokeLineJoin private
Referenced by CWRVectorRenderer::StrokeCanvas::setStroke().
strokeWidthHalf
float strokeWidthHalf private
Referenced by CWRVectorRenderer::StrokeCanvas::setStroke().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/CWRVectorRenderer.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/CWRVectorRenderer.cpp