Battery Simulator Documentation: BlockTransition
BlockTransition
#include "BlockTransition.hpp"
Public Member Functions
BlockTransition ()
virtual void handleTickEvent ()
virtual void init ()
virtual void invalidate ()
virtual void tearDown ()
Public Member Functions inherited from Transition
Transition ()
virtual ~Transition ()
bool isDone () const
virtual void setScreenContainer (Container &cont)
Private Attributes
uint8_t animationCounter
Current step in the transition animation.
uint16_t blockHeight
uint16_t blocksHorizontal
uint16_t blockWidth
Additional Inherited Members
Protected Attributes inherited from Transition
bool done
Flag that indicates when the transition is done. This should be set by implementing classes.
Container * screenContainer
The screen Container of the Screen transitioning to.
Detailed Description
A Transition that draws two small blocks in every frame. It is therefore very useful on MCUs with limited performance.
Constructor & Destructor Documentation
BlockTransition()
BlockTransition () inline
Initializes a new instance of the BlockTransition class.
        : Transition(),
          animationCounter(0)
    {
        // 8x6 blocks, with 8 blocks on the longest edge
        if (HAL::DISPLAY_WIDTH > HAL::DISPLAY_HEIGHT)
        {
            blockWidth = (HAL::DISPLAY_WIDTH + 7) / 8;
            blockHeight = (HAL::DISPLAY_HEIGHT + 5) / 6;
            blocksHorizontal = 8;
        }
        else
        {
            blockWidth = (HAL::DISPLAY_WIDTH + 5) / 6;
            blockHeight = (HAL::DISPLAY_HEIGHT + 7) / 8;
            blocksHorizontal = 6;
        }
    }
References BlockTransition::blockHeight, BlockTransition::blocksHorizontal, BlockTransition::blockWidth, HAL::DISPLAY_HEIGHT, and HAL::DISPLAY_WIDTH.
Member Function Documentation
handleTickEvent()
virtual void handleTickEvent () inline virtual
Handles the tick event when transitioning. It uncovers and invalidates two blocks in every frame, for a total of 24 frames.
Reimplemented from Transition.
    {
        const int animationSteps = 48;
        // "Random" sequence of blocks to invalidate
        const int indeces[animationSteps] = { 20, 11, 47, 14, 10, 0, 18, 28, 13, 6, 2, 41,
                                              44, 5, 3, 17, 36, 46, 26, 15, 29, 39, 25, 12,
                                              19, 24, 7, 38, 37, 30, 9, 43, 4, 31, 22, 23,
                                              35, 16, 32, 42, 8, 1, 40, 33, 21, 27, 34, 45 };
        Transition::handleTickEvent();
        if (animationCounter >= animationSteps)
        {
            // Final step: stop the animation
            done = true;
            return;
        }
        if (animationCounter == 0 && HAL::USE_DOUBLE_BUFFERING)
        {
            // Synchronize framebuffers
            Application::getInstance()->copyInvalidatedAreasFromTFTToClientBuffer();
        }
        int blocks_per_tick = 2;
        while (blocks_per_tick-- > 0 && animationCounter <= animationSteps)
        {
            // Invalidate next block in sequence
            const int index = indeces[animationCounter];
            const int16_t x = (index % blocksHorizontal) * blockWidth;
            const int16_t y = (index / blocksHorizontal) * blockHeight;
            Rect invRect(x, y, blockWidth, blockHeight);
            screenContainer->invalidateRect(invRect);
            animationCounter++;
        }
    }
References BlockTransition::animationCounter, BlockTransition::blockHeight, BlockTransition::blocksHorizontal, BlockTransition::blockWidth, Transition::done, Application::getInstance(), Transition::handleTickEvent(), Drawable::invalidateRect(), Transition::screenContainer, and HAL::USE_DOUBLE_BUFFERING.
init()
virtual void init () inline virtual
Initializes the transition. Called after the constructor is called, when the application changes the transition.
Reimplemented from Transition.
    {
        Transition::init();
    }
References Transition::init().
invalidate()
virtual void invalidate () inline virtual
Block transition does not require an invalidation. Invalidation is handled by the class. Do no invalidation initially.
Reimplemented from Transition.
    {
    }
tearDown()
virtual void tearDown () inline virtual
Tears down the Animation. Called before the destructor is called, when the application changes the transition.
Reimplemented from Transition.
    {
    }
Member Data Documentation
animationCounter
uint8_t animationCounter private
Current step in the transition animation.
Referenced by BlockTransition::handleTickEvent().
blockHeight
uint16_t blockHeight private
Referenced by BlockTransition::BlockTransition(), and BlockTransition::handleTickEvent().
blocksHorizontal
uint16_t blocksHorizontal private
Referenced by BlockTransition::BlockTransition(), and BlockTransition::handleTickEvent().
blockWidth
uint16_t blockWidth private
Referenced by BlockTransition::BlockTransition(), and BlockTransition::handleTickEvent().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/transitions/BlockTransition.hpp