Battery Simulator Documentation: VectorRenderer
VectorRenderer abstract
#include "VectorRenderer.hpp"
Public Types
enum DrawMode { STROKE , FILL_EVEN_ODD , FILL_NON_ZERO }
Public Member Functions
virtual ~VectorRenderer ()
virtual void drawPath (const uint8_t *cmds, uint32_t nCmds, const float *points, uint32_t nPoints, const float *bbox=0)=0
virtual void setAlpha (uint8_t a)=0
virtual void setColor (colortype c)=0
virtual void setLinearGradient (float x0, float y0, float x1, float y1, uint32_t stops, const float *stopPositions, const uint32_t *stopColors, float width, float height, bool solid, const uint32_t *palette)=0
virtual void setMode (DrawMode mode)=0
virtual void setStrokeLineCap (VGStrokeLineCap lineCap)=0
virtual void setStrokeLineJoin (VGStrokeLineJoin lineJoin)=0
virtual void setStrokeMiterLimit (float miterLimit)=0
virtual void setStrokeWidth (float w)=0
virtual void setTransformationMatrix (const Matrix3x3 &m)=0
virtual void setup (const Rect &canvasAreaAbs, const Rect &invalidatedAreaRel)=0
virtual void tearDown ()=0
Static Public Member Functions
static VectorRenderer * getInstance ()
Detailed Description
Abstract interface for classes implementing general 2D vector drawing.
Users of this interface are Widgets drawing vector graphics like SVG images.
Implementations draw the path given (in drawPath) using the last color or gradient supplied with setColor or setLinearGradient.
Member Enumeration Documentation
DrawMode
enum DrawMode
A list of vector graphics drawing modes.
Enumerator
STROKE
Draw the outline of the paths.
FILL_EVEN_ODD
Fill the paths using the even-odd filling rule.
FILL_NON_ZERO
Fill the paths using the non-zero filling rule.
    {
        STROKE,
        FILL_EVEN_ODD,
        FILL_NON_ZERO
    };
Constructor & Destructor Documentation
~VectorRenderer()
virtual ~VectorRenderer () inline virtual
Virtual destructor.
    {
    }
Member Function Documentation
drawPath()
virtual void drawPath (const uint8_t * cmds, uint32_t nCmds, const float * points, uint32_t nPoints, const float * bbox = 0) pure virtual
Draw a Path defined by the given array of primitives (commands) and an array of the corresponding floating point coordinates.
Parameters
cmds An uint8_t array of VectorPrimitives values
nCmds The number of commands in cmds
points An array of coordinates for the commands
nPoints The number of values in the points arrays
bbox Array describing the bounding box of the path [minx,miny,maxx,maxy] or 0 if unknown
Implemented in CWRVectorRenderer.
Referenced by SVGImage::draw().
getInstance()
VectorRenderer * getInstance () static
Gets the VectorRenderer instance.
Returns
The VectorRenderer instance.
    {
        static CWRVectorRendererRGB888 renderer;
        return &renderer;
    }
Referenced by SVGImage::draw().
setAlpha()
virtual void setAlpha (uint8_t a) pure virtual
Set the alpha value (opacity) used for future drawings. The alpha is specified in the interval [0;1].
Parameters
a The alpha value.
Implemented in CWRVectorRenderer.
Referenced by SVGImage::draw().
setColor()
virtual void setColor (colortype c) pure virtual
Set a constant color used for future drawings.
Parameters
c An ARGB color value
Implemented in CWRVectorRenderer.
Referenced by SVGImage::draw().
setLinearGradient()
virtual void setLinearGradient (float x0, float y0, float x1, float y1, uint32_t stops, const float * stopPositions, const uint32_t * stopColors, float width, float height, bool solid, const uint32_t * palette) pure virtual
Set a linear gradient used for future drawings. The linear gradient is transformed using the current transformation matrix. Multiple colors (stops) can be specified for the gradient. The stop positions are given in the range [0;1].
Parameters
x0 X-coordinate for gradient starting point
y0 Y-coordinate for gradient starting point
x1 X-coordinate for gradient end point
y1 Y-coordinate for gradient end point
stops Number of stops
stopPositions Positions of the stops on the line
stopColors Colors of the stops
width Width of the box to fill
height Height of the box to fill
solid True if all colors in the gradient are solid
palette The gradient palette
Implemented in CWRVectorRenderer.
Referenced by SVGImage::draw().
setMode()
virtual void setMode (DrawMode mode) pure virtual
Set the drawing mode for the VectorRenderer. The mode will be used for all subsequent drawings until setMode is called again.
The default mode is non-zero filling.
Parameters
mode The filling mode.
Implemented in CWRVectorRenderer.
Referenced by SVGImage::draw().
setStrokeLineCap()
virtual void setStrokeLineCap (VGStrokeLineCap lineCap) pure virtual
Sets stroke line cap type.
Parameters
lineCap The line cap type.
Implemented in CWRVectorRenderer.
Referenced by SVGImage::draw().
setStrokeLineJoin()
virtual void setStrokeLineJoin (VGStrokeLineJoin lineJoin) pure virtual
Sets stroke line join type.
Parameters
lineJoin The line join type.
Implemented in CWRVectorRenderer.
Referenced by SVGImage::draw().
setStrokeMiterLimit()
virtual void setStrokeMiterLimit (float miterLimit) pure virtual
Sets stroke miter limit. This the max distance from the Miter point on the stroke to the stroke point that will be used. If the miter limit is exceeded for a stroke join, it will not be drawn as a Miter but as a Bevel.
Parameters
miterLimit The miter limit.
Implemented in CWRVectorRenderer.
Referenced by SVGImage::draw().
setStrokeWidth()
virtual void setStrokeWidth (float w) pure virtual
Set the width used for future drawings using the VECTOR_STROKE drawing mode.
Parameters
w The width used for stroke drawing.
Implemented in CWRVectorRenderer.
Referenced by SVGImage::draw().
setTransformationMatrix()
virtual void setTransformationMatrix (const Matrix3x3 & m) pure virtual
Sets the transformation matrix used for future drawings. The transformation is reset when setup is called.
Parameters
m The transformation matrix
Implemented in CWRVectorRenderer.
Referenced by SVGImage::draw().
setup()
virtual void setup (const Rect & canvasAreaAbs, const Rect & invalidatedAreaRel) pure virtual
Start a new drawing (invalidated area) within the given canvas area. The canvas area typically corresponds to the area of a Widget and is given in absolute coordinates, whereas the invalidated area is given in relative coordinates. Implementations may lock the framebuffer here.
Parameters
canvasAreaAbs The canvas dimensions in absolute coordinates.
invalidatedAreaRel The area which should be updated in relative coordinates to the canvas area.
Implemented in CWRVectorRenderer.
Referenced by SVGImage::draw().
tearDown()
virtual void tearDown () pure virtual
Finalizes the current drawing. The implementation may block here until the drawing is done.
The implementation is required to unlock the framebuffer when tearDown is called.
Implemented in CWRVectorRenderer.
Referenced by SVGImage::draw().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/hal/VectorRenderer.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/simulator/src/mainBase.cpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/target/generated/TouchGFXGeneratedHAL.cpp