Battery Simulator Documentation: AbstractDirectionProgress
AbstractDirectionProgress
#include "AbstractDirectionProgress.hpp"
Public Types
enum DirectionType { RIGHT , LEFT , DOWN , UP }
Public Member Functions
AbstractDirectionProgress ()
virtual DirectionType getDirection () const
virtual void setDirection (DirectionType direction)
Public Member Functions inherited from AbstractProgressIndicator
AbstractProgressIndicator ()
virtual uint8_t getAlpha () const
virtual uint16_t getProgress (uint16_t range=100) const
virtual int16_t getProgressIndicatorHeight () const
virtual int16_t getProgressIndicatorWidth () const
virtual int16_t getProgressIndicatorX () const
virtual int16_t getProgressIndicatorY () const
virtual void getRange (int &min, int &max) const
virtual void getRange (int &min, int &max, uint16_t &steps) const
virtual void getRange (int &min, int &max, uint16_t &steps, uint16_t &minStep) const
virtual int getValue () const
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void setAlpha (uint8_t newAlpha)
virtual void setBackground (const Bitmap &bitmapBackground)
virtual void setEasingEquation (EasingEquation easingEquation)
virtual void setProgressIndicatorPosition (int16_t x, int16_t y, int16_t width, int16_t height)
virtual void setRange (int min, int max, uint16_t steps=0, uint16_t minStep=0)
virtual void setValue (int value)
void setValueSetAction (GenericCallback< const AbstractProgressIndicator & > &callback)
void setValueUpdatedAction (GenericCallback< const AbstractProgressIndicator & > &callback)
virtual void updateValue (int value, uint16_t duration)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
DirectionType progressDirection
The progress direction.
Protected Attributes inherited from AbstractProgressIndicator
int animationDuration
Duration of the animation.
int animationEndValue
The animation end value.
bool animationRunning
Is the animation running.
int animationStartValue
The animation start value.
int animationStep
The current animation step.
Image background
The background image.
int currentValue
The current value.
EasingEquation equation
The equation used in updateValue()
Container progressIndicatorContainer
The container that holds the actual progress indicator.
int rangeMax
The range maximum.
int rangeMin
The range minimum.
uint16_t rangeSteps
The range steps.
uint16_t rangeStepsMin
The range steps minimum.
GenericCallback< const AbstractProgressIndicator & > * valueSetCallback
New value assigned Callback.
GenericCallback< const AbstractProgressIndicator & > * valueUpdatedCallback
Animation ended Callback.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Detailed Description
An abstract class for progress indicators that need a horizontal or vertical direction to be specified.
Member Enumeration Documentation
DirectionType
enum DirectionType
Values that represent directions.
Enumerator
RIGHT
Progress should be from left to right.
LEFT
Progress should be from right to left.
DOWN
Progress should be down (top to bottom)
UP
Progress should be up (bottom to top)
    {
        RIGHT,
        LEFT,
        DOWN,
        UP
    };
Constructor & Destructor Documentation
AbstractDirectionProgress()
AbstractDirectionProgress ()
    : AbstractProgressIndicator(), progressDirection(RIGHT)
{
    AbstractDirectionProgress::setDirection(RIGHT);
}
References AbstractDirectionProgress::RIGHT, and AbstractDirectionProgress::setDirection().
Member Function Documentation
getDirection()
AbstractDirectionProgress::DirectionType getDirection () const virtual
Gets the current direction for the progress indicator.
Returns
The direction.
See also
setDirection
{
    return progressDirection;
}
References AbstractDirectionProgress::progressDirection.
setDirection()
void setDirection (DirectionType direction) virtual
Sets a direction for the progress indicator. This will re-calculate the current value according to the new direction.
Parameters
direction The direction.
See also
getDirection
{
    if (direction != progressDirection)
    {
        progressDirection = direction;
        progressIndicatorContainer.invalidate();
        setValue(getValue());
    }
}
References AbstractProgressIndicator::getValue(), Drawable::invalidate(), AbstractDirectionProgress::progressDirection, AbstractProgressIndicator::progressIndicatorContainer, and AbstractProgressIndicator::setValue().
Referenced by AbstractDirectionProgress::AbstractDirectionProgress(), and Screen1ViewBase::Screen1ViewBase().
Member Data Documentation
progressDirection
DirectionType progressDirection protected
The progress direction.
Referenced by AbstractDirectionProgress::getDirection(), AbstractDirectionProgress::setDirection(), BoxProgress::setValue(), and ImageProgress::setValue().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/progress_indicators/AbstractDirectionProgress.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/progress_indicators/AbstractDirectionProgress.cpp