Battery Simulator Documentation: AbstractProgressIndicator
AbstractProgressIndicator
#include "AbstractProgressIndicator.hpp"
Public Member Functions
AbstractProgressIndicator ()
virtual uint8_t getAlpha () const
virtual uint16_t getProgress (uint16_t range=100) const
virtual int16_t getProgressIndicatorHeight () const
virtual int16_t getProgressIndicatorWidth () const
virtual int16_t getProgressIndicatorX () const
virtual int16_t getProgressIndicatorY () const
virtual void getRange (int &min, int &max) const
virtual void getRange (int &min, int &max, uint16_t &steps) const
virtual void getRange (int &min, int &max, uint16_t &steps, uint16_t &minStep) const
virtual int getValue () const
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void setAlpha (uint8_t newAlpha)
virtual void setBackground (const Bitmap &bitmapBackground)
virtual void setEasingEquation (EasingEquation easingEquation)
virtual void setProgressIndicatorPosition (int16_t x, int16_t y, int16_t width, int16_t height)
virtual void setRange (int min, int max, uint16_t steps=0, uint16_t minStep=0)
virtual void setValue (int value)
void setValueSetAction (GenericCallback< const AbstractProgressIndicator & > &callback)
void setValueUpdatedAction (GenericCallback< const AbstractProgressIndicator & > &callback)
virtual void updateValue (int value, uint16_t duration)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
int animationDuration
Duration of the animation.
int animationEndValue
The animation end value.
bool animationRunning
Is the animation running.
int animationStartValue
The animation start value.
int animationStep
The current animation step.
Image background
The background image.
int currentValue
The current value.
EasingEquation equation
The equation used in updateValue()
Container progressIndicatorContainer
The container that holds the actual progress indicator.
int rangeMax
The range maximum.
int rangeMin
The range minimum.
uint16_t rangeSteps
The range steps.
uint16_t rangeStepsMin
The range steps minimum.
GenericCallback< const AbstractProgressIndicator & > * valueSetCallback
New value assigned Callback.
GenericCallback< const AbstractProgressIndicator & > * valueUpdatedCallback
Animation ended Callback.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Detailed Description
The AbstractProgressIndicator declares methods that provides the basic mechanisms and tools to implement a progress indicator. For more specific implementations see classes that inherit from AbstractProgressIndicator.
See also
BoxProgress, CircleProgress, ImageProgress, LineProgress, TextProgress
Constructor & Destructor Documentation
AbstractProgressIndicator()
AbstractProgressIndicator ()
Initializes a new instance of the AbstractProgressIndicator class with a default range 0-100.
    : Container(), background(), progressIndicatorContainer(), rangeMin(0), rangeMax(100), currentValue(0), rangeSteps(100), rangeStepsMin(0),
      equation(&EasingEquations::linearEaseNone), animationRunning(false), animationStartValue(0), animationEndValue(0), animationDuration(0), animationStep(0),
      valueSetCallback(0), valueUpdatedCallback(0)
{
    background.setXY(0, 0);
    AbstractProgressIndicator::add(background);
    AbstractProgressIndicator::add(progressIndicatorContainer);
}
References Container::add(), AbstractProgressIndicator::background, AbstractProgressIndicator::progressIndicatorContainer, and Drawable::setXY().
Member Function Documentation
getAlpha()
uint8_t getAlpha () const virtual
Gets the current alpha value of the widget. The alpha value is in range 255 (solid) to 0 (invisible).
Returns
The current alpha value.
See also
setAlpha
{
    return background.getAlpha();
}
References AbstractProgressIndicator::background, and Image::getAlpha().
Referenced by AbstractProgressIndicator::invalidateContent(), and Gauge::invalidateContent().
getProgress()
uint16_t getProgress (uint16_t range = 100) const virtual
Gets the current progress based on the range set by setRange() and the value set by setValue().
Parameters
range (Optional) The range, default is 100.
Returns
The progress.
See also
setRange, setValue, getValue
{
    if (range == 0)
    {
        return 0;
    }
    int32_t remainder; // Not used here
    // Find out at what step the current value is.
    const int32_t step = rangeStepsMin + muldiv(currentValue - rangeMin, rangeSteps - rangeStepsMin, rangeMax - rangeMin, remainder);
    // Scale the step up to [0..range]
    const int32_t prog = muldiv(step, range, rangeSteps, remainder);
    return (uint16_t)prog;
}
References AbstractProgressIndicator::currentValue, touchgfx::muldiv(), AbstractProgressIndicator::rangeMax, AbstractProgressIndicator::rangeMin, AbstractProgressIndicator::rangeSteps, and AbstractProgressIndicator::rangeStepsMin.
Referenced by BoxProgress::setValue(), CircleProgress::setValue(), ImageProgress::setValue(), LineProgress::setValue(), TextProgress::setValue(), and Gauge::setValue().
getProgressIndicatorHeight()
int16_t getProgressIndicatorHeight () const virtual
Gets progress indicator height.
Returns
The progress indicator height.
See also
setProgressIndicatorPosition
{
    return progressIndicatorContainer.getHeight();
}
References Drawable::getHeight(), and AbstractProgressIndicator::progressIndicatorContainer.
getProgressIndicatorWidth()
int16_t getProgressIndicatorWidth () const virtual
Gets progress indicator width.
Returns
The progress indicator width.
See also
setProgressIndicatorPosition
{
    return progressIndicatorContainer.getWidth();
}
References Drawable::getWidth(), and AbstractProgressIndicator::progressIndicatorContainer.
getProgressIndicatorX()
int16_t getProgressIndicatorX () const virtual
Gets progress indicator x coordinate.
Returns
The progress indicator x coordinate.
See also
setProgressIndicatorPosition
{
    return progressIndicatorContainer.getX();
}
References Drawable::getX(), and AbstractProgressIndicator::progressIndicatorContainer.
getProgressIndicatorY()
int16_t getProgressIndicatorY () const virtual
Gets progress indicator y coordinate.
Returns
The progress indicator y coordinate.
See also
setProgressIndicatorPosition
{
    return progressIndicatorContainer.getY();
}
References Drawable::getY(), and AbstractProgressIndicator::progressIndicatorContainer.
getRange() [1/3]
void getRange (int & min, int & max) const virtual
Gets the range set by setRange().
Parameters
[out] min The minimum input value.
[out] max The maximum input value.
See also
setRange
{
    min = rangeMin;
    max = rangeMax;
}
References AbstractProgressIndicator::rangeMax, and AbstractProgressIndicator::rangeMin.
getRange() [2/3]
void getRange (int & min, int & max, uint16_t & steps) const virtual
Gets the range set by setRange().
Parameters
[out] min The minimum input value.
[out] max The maximum input value.
[out] steps The steps in which to report progress.
See also
setRange
{
    min = rangeMin;
    max = rangeMax;
    steps = rangeSteps;
}
References AbstractProgressIndicator::rangeMax, AbstractProgressIndicator::rangeMin, and AbstractProgressIndicator::rangeSteps.
getRange() [3/3]
void getRange (int & min, int & max, uint16_t & steps, uint16_t & minStep) const virtual
Gets the range set by setRange().
Parameters
[out] min The minimum input value.
[out] max The maximum input value.
[out] steps The steps in which to report progress.
[out] minStep The step which the minimum input value is mapped to.
See also
setRange
{
    min = rangeMin;
    max = rangeMax;
    steps = rangeSteps;
    minStep = rangeStepsMin;
}
References AbstractProgressIndicator::rangeMax, AbstractProgressIndicator::rangeMin, AbstractProgressIndicator::rangeSteps, and AbstractProgressIndicator::rangeStepsMin.
getValue()
int getValue () const virtual
Gets the current value set by setValue().
Returns
The value.
See also
setValue
{
    return currentValue;
}
References AbstractProgressIndicator::currentValue.
Referenced by ImageProgress::setAnchorAtZero(), AbstractDirectionProgress::setDirection(), TextProgress::setNumberOfDecimals(), CircleProgress::setStartEndAngle(), Gauge::setStartEndAngle(), and AbstractProgressIndicator::updateValue().
handleTickEvent()
void handleTickEvent () virtual
Called periodically by the framework if the Drawable instance has subscribed to timer ticks.
See also
Application::registerTimerWidget
Reimplemented from Drawable.
{
    if (!animationRunning)
    {
        return;
    }
    animationStep++;
    const int16_t delta = (int16_t)equation(animationStep, 0, animationEndValue - animationStartValue, animationDuration);
    setValue(animationStartValue + delta);
    if (animationStep >= animationDuration)
    {
        animationDuration = 0;
        animationStep = 0;
        Application::getInstance()->unregisterTimerWidget(this);
        animationRunning = false;
        if (valueUpdatedCallback && valueUpdatedCallback->isValid())
        {
            valueUpdatedCallback->execute(*this);
        }
    }
}
References AbstractProgressIndicator::animationDuration, AbstractProgressIndicator::animationEndValue, AbstractProgressIndicator::animationRunning, AbstractProgressIndicator::animationStartValue, AbstractProgressIndicator::animationStep, AbstractProgressIndicator::equation, Application::getInstance(), AbstractProgressIndicator::setValue(), and AbstractProgressIndicator::valueUpdatedCallback.
invalidateContent()
virtual void invalidateContent () const inline virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from Drawable.
Reimplemented in Gauge.
    {
        if (getAlpha() > 0)
        {
            Container::invalidateContent();
        }
    }
References AbstractProgressIndicator::getAlpha(), and Drawable::invalidateContent().
Referenced by Gauge::invalidateContent().
setAlpha()
void setAlpha (uint8_t newAlpha) virtual
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
Reimplemented in BoxProgress, CircleProgress, ImageProgress, LineProgress, TextProgress, and Gauge.
{
    background.setAlpha(newAlpha);
}
References AbstractProgressIndicator::background, and Image::setAlpha().
Referenced by BoxProgress::setAlpha(), CircleProgress::setAlpha(), ImageProgress::setAlpha(), LineProgress::setAlpha(), TextProgress::setAlpha(), and Gauge::setAlpha().
setBackground()
void setBackground (const Bitmap & bitmapBackground) virtual
Sets the background image. The width and height of the progress indicator widget is updated according to the dimensions of the bitmap.
Parameters
bitmapBackground The background bitmap.
{
    background.setBitmap(bitmapBackground);
    setWidthHeight(background);
}
References AbstractProgressIndicator::background, Image::setBitmap(), and Drawable::setWidthHeight().
Referenced by Screen1ViewBase::Screen1ViewBase().
setEasingEquation()
void setEasingEquation (EasingEquation easingEquation) virtual
Sets easing equation to be used in updateValue.
Parameters
easingEquation The easing equation.
See also
updateValue
{
    equation = easingEquation;
}
setProgressIndicatorPosition()
void setProgressIndicatorPosition (int16_t x, int16_t y, int16_t width, int16_t height) virtual
Sets the position and dimensions of the actual progress indicator relative to the background image.
Parameters
x The x coordinate.
y The y coordinate.
width The width of the box progress indicator.
height The height of the box progress indicator.
See also
getProgressIndicatorX, getProgressIndicatorY, getProgressIndicatorWidth, getProgressIndicatorHeight
Reimplemented in BoxProgress, CircleProgress, ImageProgress, LineProgress, TextProgress, and Gauge.
{
    progressIndicatorContainer.setPosition(x, y, width, height);
    if (getWidth() < x + width)
    {
        AbstractProgressIndicator::setWidth(x + width);
    }
    if (getHeight() < y + height)
    {
        AbstractProgressIndicator::setHeight(y + height);
    }
}
References Drawable::getHeight(), Drawable::getWidth(), AbstractProgressIndicator::progressIndicatorContainer, Drawable::setHeight(), Drawable::setPosition(), and Drawable::setWidth().
Referenced by BoxProgress::setProgressIndicatorPosition(), CircleProgress::setProgressIndicatorPosition(), ImageProgress::setProgressIndicatorPosition(), LineProgress::setProgressIndicatorPosition(), and TextProgress::setProgressIndicatorPosition().
setRange()
void setRange (int min, int max, uint16_t steps = 0, uint16_t minStep = 0) virtual
Sets the range for the progress indicator. The range is the values that are given to the progress indicator while progressing through the task at hand. If an app needs to work through 237 items to finish a task, the range should be set to (0, 237) assuming that 0 items is the minimum. Though the minimum is often 0, it is possible to customize this.
The steps parameter is used to specify at what granularity you want the progress indicator to report a new progress value. If the 237 items to be reported as 0%, 10%, 20%, ... 100%, the steps should be set to 10 as there are ten steps from 0% to 100%. If you want to update a widget which is 150 pixels wide, you might want to set steps to 150 to get a new progress value for every pixel. If you are updating a clock and want this to resemble an analog clock, you might want to use 12 or perhaps 60 as number of steps.
The minStep parameter is used when the minimum input value (min) should give a progress different from 0. For example, if progress is a clock face, you want to count from 0..1000 and you want progress per minute, but want to make sure that 0 is not a blank clock face, but instead you want 1 minute to show, use
setRange(0, 1000, 60, 1)
to make sure that as values progress from 0 to 1000, getProgress() start from 1 and goes up to 60. Another example could be a BoxProgress with a TextProgress on top and you want to make sure that "0%" will always show in the box, use something like
setRange(0, 1000, 200, 40)
if your box is 200 pixels wide and "0%" is 40 pixels wide.
Parameters
min The minimum input value.
max The maximum input value.
steps (Optional) The steps in which to report progress.
minStep (Optional) The step which the minimum input value is mapped to.
See also
setValue, getProgress
{
    assert(min < max);
    rangeMin = min;
    rangeMax = max;
    setValue(currentValue);
    if (steps == 0)
    {
        rangeSteps = max - min;
    }
    else
    {
        rangeSteps = steps;
    }
    rangeStepsMin = minStep;
    assert(rangeStepsMin < rangeSteps);
}
References AbstractProgressIndicator::currentValue, AbstractProgressIndicator::rangeMax, AbstractProgressIndicator::rangeMin, AbstractProgressIndicator::rangeSteps, AbstractProgressIndicator::rangeStepsMin, and AbstractProgressIndicator::setValue().
Referenced by Screen1ViewBase::Screen1ViewBase().
setValue()
void setValue (int value) virtual
Sets the current value in the range (min..max) set by setRange(). Values lower than min are mapped to min, values higher than max are mapped to max. If a callback function has been set using setValueSetAction, that callback will be called (unless the new value is the same as the current value).
Parameters
value The value.
See also
getValue, updateValue, setValueSetAction
Note
if value is equal to the current value, nothing happens, and the callback will not be called.
Reimplemented in BoxProgress, CircleProgress, ImageProgress, LineProgress, TextProgress, and Gauge.
{
    value = MAX(value, rangeMin);
    value = MIN(value, rangeMax);
    if (value != currentValue)
    {
        currentValue = value;
        if (valueSetCallback && valueSetCallback->isValid())
        {
            valueSetCallback->execute(*this);
        }
    }
}
References AbstractProgressIndicator::currentValue, MAX, MIN, AbstractProgressIndicator::rangeMax, AbstractProgressIndicator::rangeMin, and AbstractProgressIndicator::valueSetCallback.
Referenced by AbstractProgressIndicator::handleTickEvent(), AbstractDirectionProgress::setDirection(), AbstractProgressIndicator::setRange(), BoxProgress::setValue(), CircleProgress::setValue(), ImageProgress::setValue(), LineProgress::setValue(), TextProgress::setValue(), Gauge::setValue(), and AbstractProgressIndicator::updateValue().
setValueSetAction()
void setValueSetAction (GenericCallback< const AbstractProgressIndicator & > & callback)
Sets callback that will be triggered every time a new value is assigned to the progress indicator. This can happen directly from setValue() or during a gradual change initiated using updateValue().
Parameters
callback The callback.
See also
setValue, updateValue
{
    valueSetCallback = &callback;
}
References AbstractProgressIndicator::valueSetCallback.
setValueUpdatedAction()
void setValueUpdatedAction (GenericCallback< const AbstractProgressIndicator & > & callback)
Sets callback that will be triggered when updateValue has finished animating to the final value.
Parameters
callback The callback.
See also
updateValue, setValueSetAction
{
    valueUpdatedCallback = &callback;
}
References AbstractProgressIndicator::valueUpdatedCallback.
updateValue()
void updateValue (int value, uint16_t duration) virtual
Update the current value in the range (min..max) set by setRange(). Values lower than min are mapped to min, values higher than max are mapped to max. The value is changed gradually in the given number of ticks using the easing equation set in setEasingEquation. Function setValue() is called for every new value during the change of value, and if a callback function has been set using setValueSetAction, that callback will be called for every new value. The callback set using setValueUpdatedCallback is called when the animation has finished.
Parameters
value The value.
duration The duration.
See also
setValue, setEasingEquation, setValueSetAction, setValueUpdatedAction
Note
If duration is 0, setValue will be called immediately and the valueUpdated action is called immediately.
{
    value = MAX(value, rangeMin);
    value = MIN(value, rangeMax);
    if (duration == 0)
    {
        setValue(value);
        if (valueUpdatedCallback && valueUpdatedCallback->isValid())
        {
            valueUpdatedCallback->execute(*this);
        }
        return;
    }
    if (animationDuration > 0)
    {
        // Old animation is running, stop it first
        Application::getInstance()->unregisterTimerWidget(this);
        animationRunning = false;
    }
    animationStartValue = getValue();
    animationEndValue = value;
    animationDuration = duration;
    animationStep = 0;
    Application::getInstance()->registerTimerWidget(this);
    animationRunning = true;
}
References AbstractProgressIndicator::animationDuration, AbstractProgressIndicator::animationEndValue, AbstractProgressIndicator::animationRunning, AbstractProgressIndicator::animationStartValue, AbstractProgressIndicator::animationStep, Application::getInstance(), AbstractProgressIndicator::getValue(), MAX, MIN, AbstractProgressIndicator::rangeMax, AbstractProgressIndicator::rangeMin, AbstractProgressIndicator::setValue(), and AbstractProgressIndicator::valueUpdatedCallback.
Member Data Documentation
animationDuration
int animationDuration protected
Duration of the animation.
Referenced by AbstractProgressIndicator::handleTickEvent(), Gauge::setValue(), and AbstractProgressIndicator::updateValue().
animationEndValue
int animationEndValue protected
The animation end value.
Referenced by AbstractProgressIndicator::handleTickEvent(), and AbstractProgressIndicator::updateValue().
animationRunning
bool animationRunning protected
Is the animation running.
Referenced by AbstractProgressIndicator::handleTickEvent(), and AbstractProgressIndicator::updateValue().
animationStartValue
int animationStartValue protected
The animation start value.
Referenced by AbstractProgressIndicator::handleTickEvent(), and AbstractProgressIndicator::updateValue().
animationStep
int animationStep protected
The current animation step.
Referenced by AbstractProgressIndicator::handleTickEvent(), Gauge::setValue(), and AbstractProgressIndicator::updateValue().
background
Image background protected
The background image.
Referenced by AbstractProgressIndicator::AbstractProgressIndicator(), AbstractProgressIndicator::getAlpha(), AbstractProgressIndicator::setAlpha(), AbstractProgressIndicator::setBackground(), and Gauge::setBackgroundOffset().
currentValue
int currentValue protected
The current value.
Referenced by AbstractProgressIndicator::getProgress(), AbstractProgressIndicator::getValue(), AbstractProgressIndicator::setRange(), and AbstractProgressIndicator::setValue().
equation
EasingEquation equation protected
The equation used in updateValue()
Referenced by AbstractProgressIndicator::handleTickEvent().
progressIndicatorContainer
Container progressIndicatorContainer protected
The container that holds the actual progress indicator.
Referenced by AbstractProgressIndicator::AbstractProgressIndicator(), BoxProgress::BoxProgress(), CircleProgress::CircleProgress(), Gauge::Gauge(), ImageProgress::ImageProgress(), LineProgress::LineProgress(), TextProgress::TextProgress(), AbstractProgressIndicator::getProgressIndicatorHeight(), AbstractProgressIndicator::getProgressIndicatorWidth(), AbstractProgressIndicator::getProgressIndicatorX(), AbstractProgressIndicator::getProgressIndicatorY(), AbstractDirectionProgress::setDirection(), AbstractProgressIndicator::setProgressIndicatorPosition(), BoxProgress::setValue(), and ImageProgress::setValue().
rangeMax
int rangeMax protected
The range maximum.
Referenced by AbstractProgressIndicator::getProgress(), AbstractProgressIndicator::getRange(), AbstractProgressIndicator::getRange(), AbstractProgressIndicator::getRange(), AbstractProgressIndicator::setRange(), AbstractProgressIndicator::setValue(), and AbstractProgressIndicator::updateValue().
rangeMin
int rangeMin protected
The range minimum.
Referenced by AbstractProgressIndicator::getProgress(), AbstractProgressIndicator::getRange(), AbstractProgressIndicator::getRange(), AbstractProgressIndicator::getRange(), AbstractProgressIndicator::setRange(), AbstractProgressIndicator::setValue(), and AbstractProgressIndicator::updateValue().
rangeSteps
uint16_t rangeSteps protected
The range steps.
Referenced by AbstractProgressIndicator::getProgress(), AbstractProgressIndicator::getRange(), AbstractProgressIndicator::getRange(), AbstractProgressIndicator::setRange(), and LineProgress::setValue().
rangeStepsMin
uint16_t rangeStepsMin protected
The range steps minimum.
Referenced by AbstractProgressIndicator::getProgress(), AbstractProgressIndicator::getRange(), and AbstractProgressIndicator::setRange().
valueSetCallback
GenericCallback<const AbstractProgressIndicator&>* valueSetCallback protected
New value assigned Callback.
Referenced by AbstractProgressIndicator::setValue(), and AbstractProgressIndicator::setValueSetAction().
valueUpdatedCallback
GenericCallback<const AbstractProgressIndicator&>* valueUpdatedCallback protected
Animation ended Callback.
Referenced by AbstractProgressIndicator::handleTickEvent(), AbstractProgressIndicator::setValueUpdatedAction(), and AbstractProgressIndicator::updateValue().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/progress_indicators/AbstractProgressIndicator.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/progress_indicators/AbstractProgressIndicator.cpp