Battery Simulator Documentation: AbstractPainterABGR2222
AbstractPainterABGR2222
#include "AbstractPainterABGR2222.hpp"
Public Member Functions
AbstractPainterABGR2222 ()
FORCE_INLINE_FUNCTION uint8_t alphaBlend (uint8_t newpix, uint8_t bufpix, uint8_t alpha) const
FORCE_INLINE_FUNCTION uint8_t alphaBlend (uint8_t R, uint8_t G, uint8_t B, uint8_t bufpix, uint8_t alpha) const
Public Member Functions inherited from AbstractPainter
AbstractPainter ()
virtual ~AbstractPainter ()
void framebufferToDisplay (int16_t &widgetX, int16_t &widgetY) const
virtual HAL::RenderingMethod getRenderingMethod () const
virtual void paint (uint8_t *destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const =0
virtual bool setup (const Rect &widgetRect) const
virtual void tearDown () const
Additional Inherited Members
Static Protected Member Functions inherited from AbstractPainter
static FORCE_INLINE_FUNCTION bool compatibleFramebuffer (Bitmap::BitmapFormat format)
Protected Attributes inherited from AbstractPainter
int16_t widgetWidth
The width of the widget on screen, used by framebufferToDisplay()
Detailed Description
The AbstractPainterABGR2222 class is an abstract class for creating a painter to draw on a ABGR2222 display using CanvasWidgetRenderer.
See also
AbstractPainter
Constructor & Destructor Documentation
AbstractPainterABGR2222()
AbstractPainterABGR2222 () inline
        : AbstractPainter()
    {
        assert(compatibleFramebuffer(Bitmap::ABGR2222) && "The chosen painter only works with ABGR2222 displays");
    }
References Bitmap::ABGR2222, and AbstractPainter::compatibleFramebuffer().
Member Function Documentation
alphaBlend() [1/2]
FORCE_INLINE_FUNCTION uint8_t alphaBlend (uint8_t newpix, uint8_t bufpix, uint8_t alpha) const inline
Mix colors from a new pixel and a buffer pixel with the given alpha applied to the new pixel, and the inverse alpha applied to the buffer pixel.
Parameters
newpix The new pixel value.
bufpix The buffer pixel value.
alpha The alpha to apply to the new pixel.
Returns
The result of blending the two colors into a new color.
    {
        return alphaBlend(LCD8bpp_ABGR2222::getRedFromNativeColor(newpix),
                          LCD8bpp_ABGR2222::getGreenFromNativeColor(newpix),
                          LCD8bpp_ABGR2222::getBlueFromNativeColor(newpix), bufpix, alpha);
    }
References AbstractPainterABGR2222::alphaBlend(), LCD8bpp_ABGR2222::getBlueFromNativeColor(), LCD8bpp_ABGR2222::getGreenFromNativeColor(), and LCD8bpp_ABGR2222::getRedFromNativeColor().
Referenced by AbstractPainterABGR2222::alphaBlend(), PainterABGR2222::paint(), and PainterABGR2222Bitmap::paint().
alphaBlend() [2/2]
FORCE_INLINE_FUNCTION uint8_t alphaBlend (uint8_t R, uint8_t G, uint8_t B, uint8_t bufpix, uint8_t alpha) const inline
Mix colors from a new pixel and a buffer pixel with the given alpha applied to the new pixel, and the inverse alpha applied to the buffer pixel.
Parameters
R The red color.
G The green color.
B The blue color.
bufpix The buffer pixel value.
alpha The alpha of the R,G,B.
Returns
The result of blending the two colors into a new color.
    {
        const uint8_t ialpha = 0xFF - alpha;
        const uint8_t p_red = LCD8bpp_ABGR2222::getRedFromNativeColor(bufpix);
        const uint8_t p_green = LCD8bpp_ABGR2222::getGreenFromNativeColor(bufpix);
        const uint8_t p_blue = LCD8bpp_ABGR2222::getBlueFromNativeColor(bufpix);
        const uint8_t red = LCD::div255(R * alpha + p_red * ialpha);
        const uint8_t green = LCD::div255(G * alpha + p_green * ialpha);
        const uint8_t blue = LCD::div255(B * alpha + p_blue * ialpha);
        return LCD8bpp_ABGR2222::getNativeColorFromRGB(red, green, blue);
    }
References LCD::div255(), LCD8bpp_ABGR2222::getBlueFromNativeColor(), LCD8bpp_ABGR2222::getGreenFromNativeColor(), LCD8bpp_ABGR2222::getNativeColorFromRGB(), and LCD8bpp_ABGR2222::getRedFromNativeColor().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/AbstractPainterABGR2222.hpp