Battery Simulator Documentation: UnmappedDataFont
UnmappedDataFont
#include "UnmappedDataFont.hpp"
Public Member Functions
UnmappedDataFont (const GlyphNode *glyphs, const uint16_t *unicodes, uint16_t numGlyphs, uint16_t height, uint16_t baseline, uint8_t pixAboveTop, uint8_t pixBelowBottom, uint8_t bitsPerPixel, uint8_t byteAlignRow, uint8_t maxLeft, uint8_t maxRight, const uint8_t *const *glyphDataList, const KerningNode *kerningList, const Unicode::UnicodeChar fallbackChar, const Unicode::UnicodeChar ellipsisChar, const uint16_t *const gsubData, const FontContextualFormsTable *formsTable)
virtual const FontContextualFormsTable * getContextualFormsTable () const
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode) const
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, const uint8_t *&pixelData, uint8_t &bitsPerPixel) const
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, const uint8_t *&pixelData, uint8_t &bitsPerPixel) const=0
virtual const uint16_t * getGSUBTable () const
virtual int8_t getKerning (Unicode::UnicodeChar prevChar, const GlyphNode *glyph) const
virtual const uint8_t * getPixelData (const GlyphNode *glyph) const
Public Member Functions inherited from Font
virtual ~Font ()
virtual FORCE_INLINE_FUNCTION uint16_t getBaseline () const
virtual FORCE_INLINE_FUNCTION uint8_t getBitsPerPixel () const
virtual FORCE_INLINE_FUNCTION uint8_t getByteAlignRow () const
virtual uint16_t getCharWidth (const Unicode::UnicodeChar c) const
virtual Unicode::UnicodeChar getEllipsisChar () const
virtual Unicode::UnicodeChar getFallbackChar () const
virtual FORCE_INLINE_FUNCTION uint16_t getHeight () const
FORCE_INLINE_FUNCTION uint8_t getMaxPixelsLeft () const
FORCE_INLINE_FUNCTION uint8_t getMaxPixelsRight () const
virtual uint16_t getNumberOfLines (const Unicode::UnicodeChar *text,...) const
FORCE_INLINE_FUNCTION uint16_t getPixelsAboveTop () const
FORCE_INLINE_FUNCTION uint16_t getPixelsBelowBottom () const
virtual float getScaleFactor () const
virtual int16_t getSpacingAbove (const Unicode::UnicodeChar *text,...) const
virtual uint16_t getStringWidth (const Unicode::UnicodeChar *text,...) const
virtual uint16_t getStringWidth (TextDirection textDirection, const Unicode::UnicodeChar *text,...) const
virtual bool isVectorBasedFont () const
TOUCHGFX_DEPRECATED ("Please use getBaseline() instead.", virtual uint16_t getFontHeight() const)
TOUCHGFX_DEPRECATED ("Please use getHeight() instead.", virtual uint16_t getMaxTextHeight(const Unicode::UnicodeChar *text,...) const)
TOUCHGFX_DEPRECATED ("Please use getHeight() instead.", virtual uint16_t getMinimumTextHeight() const)
Protected Member Functions
UnmappedDataFont ()
int lookupUnicode (uint16_t unicode) const
Protected Member Functions inherited from Font
Font (uint16_t height, uint16_t baseline, uint8_t pixAboveTop, uint8_t pixBelowBottom, uint8_t bitsPerPixel, uint8_t byteAlignRow, uint8_t maxLeft, uint8_t maxRight, const Unicode::UnicodeChar fallbackChar, const Unicode::UnicodeChar ellipsisChar)
uint16_t getStringWidthLTR (TextDirection textDirection, const Unicode::UnicodeChar *text, va_list pArg) const
uint16_t getStringWidthRTL (TextDirection textDirection, const Unicode::UnicodeChar *text, va_list pArg) const
Protected Attributes
const FontContextualFormsTable * arabicTable
Contextual forms.
const void * glyphDataList
The glyphs (list of pointers)
const GlyphNode * glyphList
The list of glyphs.
const uint16_t * gsubTable
The GSUB tables.
const KerningNode * kerningData
The kerning.
uint16_t listSize
The size of the list of glyphs.
const uint16_t * unicodes
LookupTable with all unicodes in this font.
Protected Attributes inherited from Font
uint8_t bAlignRow: 1
The glyphs are saved with each row byte aligned.
uint16_t baselineHeight
The baseline.
uint8_t bPerPixel: 7
The number of bits per pixel.
Unicode::UnicodeChar ellipsisCharacter
The ellipsis character used for truncating long texts.
Unicode::UnicodeChar fallbackCharacter
The fallback character to use when no glyph exists for the wanted character.
uint16_t fontHeight
The font height in pixels.
uint8_t maxPixelsLeft
The maximum number of pixels a glyph extends to the left.
uint8_t maxPixelsRight
The maximum number of pixels a glyph extends to the right.
uint8_t pixelsAboveTop
The number of pixels above the top.
uint8_t pixelsBelowBottom
The number of pixels below the bottom.
Static Protected Attributes
static GlyphNode glyphNodeBuffer
Buffer for GlyphNodes read from unmapped flash.
Additional Inherited Members
Static Public Member Functions inherited from Font
static FORCE_INLINE_FUNCTION bool isInvisibleZeroWidth (Unicode::UnicodeChar character)
Detailed Description
An UnmappedDataFont has both glyph table and glyph data placed in a flash which does not support random access read (indirect access). A unicode table is located in a flash with random read access (direct access).
See also
Font, ConstFont
Constructor & Destructor Documentation
UnmappedDataFont() [1/2]
UnmappedDataFont (const GlyphNode * glyphs, const uint16_t * unicodes, uint16_t numGlyphs, uint16_t height, uint16_t baseline, uint8_t pixAboveTop, uint8_t pixBelowBottom, uint8_t bitsPerPixel, uint8_t byteAlignRow, uint8_t maxLeft, uint8_t maxRight, const uint8_t *const * glyphDataList, const KerningNode * kerningList, const Unicode::UnicodeChar fallbackChar, const Unicode::UnicodeChar ellipsisChar, const uint16_t *const gsubData, const FontContextualFormsTable * formsTable)
Construct the UnmappedDataFont.
Parameters
glyphs The array of glyphs known to this font (indirect).
unicodes The array of unicodes known to this font (direct).
numGlyphs The number of glyphs in list.
height The height in pixels of the highest character in this font.
baseline The height of the baseline in pixels.
pixBelowBottom The maximum number of pixels that can be drawn below the bottom in this font.
bitsPerPixel The number of bits per pixel in this font.
byteAlignRow Are glyphs encoded using A4 format
maxLeft The maximum a character extends to the left.
maxRight The maximum a character extends to the right.
glyphDataList Pointer to pointers the glyph data for the font (indirect).
kerningList pointer to the kerning data for the font (direct).
fallbackChar The fallback character for the typography in case no glyph is available.
ellipsisChar The ellipsis character used for truncating long texts.
gsubTable Pointer to GSUB table (direct).
    : Font(height, baseline, pixAboveTop, pixBelowBottom, bitsPerPixel, byteAlignRow, maxLeft, maxRight, fallbackChar, ellipsisChar),
      glyphList(glyphs),
      listSize(numGlyphs),
      unicodes(unicodeList),
      glyphDataList(glyphDataList),
      kerningData(kerningList),
      gsubTable(gsubData),
      arabicTable(formsTable)
{
}
UnmappedDataFont() [2/2]
UnmappedDataFont () inline protected
        : Font(0, 0, 0, 0, 0, 0, 0, 0, 0, 0), glyphList(0), unicodes(0), glyphDataList(0), kerningData(0), gsubTable(0)
    {
    }
Member Function Documentation
getContextualFormsTable()
virtual const FontContextualFormsTable * getContextualFormsTable () const inline virtual
Gets the contextual forms table used in arabic fonts.
Returns
The FontContextualFormsTable or null if the font has no table.
Reimplemented from Font.
    {
        return arabicTable;
    }
References UnmappedDataFont::arabicTable.
getGlyph() [1/3]
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode) const inline virtual
Gets the glyph data associated with the specified Unicode. Please note that in case of Thai letters and Arabic letters where diacritics can be placed relative to the previous character(s), please use TextProvider::getNextLigature() instead as it will create a temporary GlyphNode that will be adjusted with respect to X/Y position.
Parameters
unicode The character to look up.
Returns
A pointer to the glyph node or null if the glyph was not found.
See also
TextProvider::getNextLigature
Reimplemented from Font.
    {
        if (unicode == 0)
        {
            return 0;
        }
        const uint8_t* dummyPixelDataPointer = 0;
        uint8_t bitsPerPixelDummy = 0;
        const GlyphNode* glyph = getGlyph(unicode, dummyPixelDataPointer, bitsPerPixelDummy);
        return glyph;
    }
getGlyph() [2/3]
const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, const uint8_t *& pixelData, uint8_t & bitsPerPixel) const virtual
Gets the glyph data associated with the specified Unicode. The GlyphNode is allocated in the buffer passed to the constructor.
Please note that in case of Thai letters and Arabic letters where diacritics can be placed relative to the previous character(s), please use TextProvider::getNextLigature() instead as it will create a temporary GlyphNode that will be adjusted with respect to X/Y position.
Parameters
unicode The character to look up.
pixelData Pointer to the pixel data for the glyph if the glyph is found. This is set by this method.
[out] bitsPerPixel Reference where to place the number of bits per pixel.
Returns
A pointer to the glyph node or null if the glyph was not found.
Implements Font.
{
    int index = lookupUnicode(unicode);
    if (index != -1)
    {
        // Read glyphNode from unmapped flash
        touchgfx::FlashDataReader* const flashReader = ApplicationFontProvider::getFlashReader();
        if (flashReader)
        {
            flashReader->copyData(glyphList + index, &glyphNodeBuffer, sizeof(GlyphNode));
            pixelData = getPixelData(const_cast<const GlyphNode*>(&glyphNodeBuffer));
            bitsPerPixel = getBitsPerPixel();
            return &glyphNodeBuffer;
        }
    }
    return 0;
}
References FlashDataReader::copyData(), Font::getBitsPerPixel(), ApplicationFontProvider::getFlashReader(), UnmappedDataFont::getPixelData(), UnmappedDataFont::glyphList, UnmappedDataFont::glyphNodeBuffer, and UnmappedDataFont::lookupUnicode().
getGlyph() [3/3]
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, const uint8_t *& pixelData, uint8_t & bitsPerPixel) const virtual
Gets the glyph data associated with the specified Unicode. Please note that in case of Thai letters and Arabic letters where diacritics can be placed relative to the previous character(s), please use TextProvider::getNextLigature() instead as it will create a temporary GlyphNode that will be adjusted with respect to X/Y position.
Parameters
unicode The character to look up.
pixelData Pointer to the pixel data for the glyph if the glyph is found. This is set by this method.
[out] bitsPerPixel Reference where to place the number of bits per pixel.
Returns
A pointer to the glyph node or null if the glyph was not found.
Implements Font.
getGSUBTable()
virtual const uint16_t * getGSUBTable () const inline virtual
Gets GSUB table.
Returns
The GSUB table or null if font has GSUB no table
Reimplemented from Font.
    {
        return gsubTable;
    }
References UnmappedDataFont::gsubTable.
getKerning()
int8_t getKerning (Unicode::UnicodeChar prevChar, const GlyphNode * glyph) const virtual
Gets the kerning distance between two characters.
Parameters
prevChar The unicode value of the previous character.
glyph the glyph object for the current character.
Returns
The kerning distance between prevChar and glyph char.
Reimplemented from Font.
{
    if (!glyph || glyph->kerningTableSize == 0)
    {
        return 0;
    }
    const KerningNode* kerndata = kerningData + glyph->kerningTablePos();
    for (uint16_t i = glyph->kerningTableSize; i > 0; i--, kerndata++)
    {
        if (prevChar == kerndata->unicodePrevChar)
        {
            return kerndata->distance;
        }
        if (prevChar < kerndata->unicodePrevChar)
        {
            break;
        }
    }
    return 0;
}
References UnmappedDataFont::kerningData.
getPixelData()
const uint8_t * getPixelData (const GlyphNode * glyph) const virtual
Obtains the address to the pixel data for the specified glyph.
Parameters
glyph The glyph to get the pixels data of.
Returns
The address of the pixel data of the glyph.
{
    const uint8_t* const* table = (const uint8_t* const*)glyphDataList;
    return &(table[glyph->unicode / 2048][glyph->dataOffset]);
}
References UnmappedDataFont::glyphDataList.
Referenced by UnmappedDataFont::getGlyph().
lookupUnicode()
int lookupUnicode (uint16_t unicode) const protected
{
    int32_t min = 0;
    int32_t max = listSize - 1;
    int32_t mid = min + (unicode - unicodes[min]); // Linear up from [min].unicode
    if (mid < min)
    {
        // Unicode < unicodes[min] => not found
        return -1;
    }
    if (mid > max)
    {
        // Linear up ends too high
        mid = max - (unicodes[max] - unicode); // Linear down from [max].unicode
        if (mid > max)
        {
            // Unicode > unicodes[max] => not found
            return -1;
        }
        if (mid < min)
        {
            // Linear down ends too low, take the middle element
            mid = (min + max) / 2;
        }
    }
    while (min <= max)
    {
        if (unicode == unicodes[mid])
        {
            // Found at [mid]
            return mid;
        }
        if (unicode < unicodes[mid])
        {
            // Unicode is in lower half
            max = mid - 1;
            if (max < min)
            {
                // Range is empty => not found
                break;
            }
            // We adjusted max, try linear down from [max].unicode
            mid = max - (unicodes[max] - unicode);
            if (mid > max)
            {
                // Unicode > [max].unicode => not found
                break;
            }
            if (mid < min)
            {
                // Linear down ends too low, take the middle element
                mid = (min + max) / 2;
            }
        }
        else
        {
            // Unicode is in upper half
            min = mid + 1;
            if (min > max)
            {
                // Range is empty => not found
                break;
            }
            // We adjusted min, try linear up from [min].unicode
            mid = min + (unicode - unicodes[min]);
            if (mid < min)
            {
                // Unicode < [min].unicode => not found
                break;
            }
            if (mid > max)
            {
                // Linear up ends too high, take the middle element
                mid = (min + max) / 2;
            }
        }
    }
    return -1;
}
References UnmappedDataFont::listSize, and UnmappedDataFont::unicodes.
Referenced by UnmappedDataFont::getGlyph().
Member Data Documentation
arabicTable
const FontContextualFormsTable* arabicTable protected
Contextual forms.
Referenced by UnmappedDataFont::getContextualFormsTable().
glyphDataList
const void* glyphDataList protected
The glyphs (list of pointers)
Referenced by UnmappedDataFont::getPixelData().
glyphList
const GlyphNode* glyphList protected
The list of glyphs.
Referenced by UnmappedDataFont::getGlyph().
glyphNodeBuffer
GlyphNode glyphNodeBuffer static protected
Buffer for GlyphNodes read from unmapped flash.
Referenced by UnmappedDataFont::getGlyph().
gsubTable
const uint16_t* gsubTable protected
The GSUB tables.
Referenced by UnmappedDataFont::getGSUBTable().
kerningData
const KerningNode* kerningData protected
The kerning.
Referenced by UnmappedDataFont::getKerning().
listSize
uint16_t listSize protected
The size of the list of glyphs.
Referenced by UnmappedDataFont::lookupUnicode().
unicodes
const uint16_t* unicodes protected
LookupTable with all unicodes in this font.
Referenced by UnmappedDataFont::lookupUnicode().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/fonts/include/fonts/UnmappedDataFont.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/fonts/src/UnmappedDataFont.cpp