Battery Simulator Documentation: DMA_Interface
DMA_Interface abstract
#include "DMA.hpp"
Public Member Functions
virtual ~DMA_Interface ()
virtual void addToQueue (const BlitOp &op)
virtual void flush ()
bool getAllowed () const
virtual BlitOperations getBlitCaps ()=0
virtual DMAType getDMAType ()
bool getReserved () const
virtual void initialize ()
uint8_t isDmaQueueEmpty ()
uint8_t isDmaQueueFull ()
bool isDMARunning ()
void setAllowed (bool allowed)
void setReserved (bool reserved)
virtual void signalDMAInterrupt ()=0
virtual void start ()
Protected Member Functions
DMA_Interface (DMA_Queue &dmaQueue)
virtual void disableAlpha ()
virtual void enableAlpha (uint8_t alpha)
virtual void enableCopyWithTransparentPixels (uint8_t alpha)
virtual void execute ()
virtual void executeCompleted ()
virtual void seedExecution ()
virtual void setupDataCopy (const BlitOp &blitOp)=0
virtual void setupDataFill (const BlitOp &blitOp)=0
virtual void waitForFrameBufferSemaphore ()
Protected Attributes
volatile bool isAllowed
true if DMA transfers are currently allowed.
volatile bool isReserved
true if DMA is reserved for for HW rendering
bool isRunning
true if a DMA transfer is currently ongoing.
DMA_Queue & queue
Reference to the DMA queue.
Detailed Description
DMA_Interface provides basic functionality and structure for processing "blit" operations using DMA.
Constructor & Destructor Documentation
~DMA_Interface()
virtual ~DMA_Interface () inline virtual
Finalizes an instance of the DMA_Interface class.
    {
    }
DMA_Interface()
DMA_Interface (DMA_Queue & dmaQueue) inline protected
Constructs a DMA Interface object.
Parameters
[in] dmaQueue Reference to the queue of DMA operations.
        : queue(dmaQueue), isRunning(false), isAllowed(false)
    {
    }
Member Function Documentation
addToQueue()
virtual void addToQueue (const BlitOp & op) virtual
Inserts a BlitOp for processing. This also potentially starts the DMA controller, if not already running.
Parameters
op The operation to add.
disableAlpha()
virtual void disableAlpha () protected virtual
Configures blit-op hardware for solid operation (no alpha-blending)
enableAlpha()
virtual void enableAlpha (uint8_t alpha) protected virtual
Configures blit-op hardware for alpha-blending.
Parameters
alpha The alpha-blending value to apply.
enableCopyWithTransparentPixels()
virtual void enableCopyWithTransparentPixels (uint8_t alpha) protected virtual
Configures blit-op hardware for alpha-blending while simultaneously skipping transparent pixels.
Parameters
alpha The alpha-blending value to apply.
execute()
virtual void execute () protected virtual
Performs a queued blit-op.
Referenced by STM32DMA::signalDMAInterrupt(), and STM32DMA::start().
executeCompleted()
virtual void executeCompleted () protected virtual
To be called when blit-op has been performed.
Referenced by STM32DMA::signalDMAInterrupt().
flush()
virtual void flush () inline virtual
This function blocks until all DMA transfers in the queue have been completed.
Reimplemented in NoDMA.
    {
        waitForFrameBufferSemaphore();
    }
References DMA_Interface::waitForFrameBufferSemaphore().
getAllowed()
bool getAllowed () const inline
Gets whether a DMA operation is allowed to begin. Used in single-buffering to avoid changing the framebuffer while display is being updated.
Returns
true if DMA is allowed to start, false if not.
    {
        return isAllowed;
    }
References DMA_Interface::isAllowed.
getBlitCaps()
virtual BlitOperations getBlitCaps () pure virtual
Gets the blit capabilities of this DMA.
Returns
The blit operations supported by this DMA implementation.
Implemented in NoDMA, and STM32DMA.
Referenced by HAL::getBlitCaps().
getDMAType()
virtual DMAType getDMAType (void) inline virtual
Function for obtaining the DMA type of the concrete DMA_Interface implementation. As default, will return DMA_TYPE_GENERIC type value.
Returns
a DMAType value of the concrete DMA_Interface implementation.
Reimplemented in STM32DMA.
    {
        return DMA_TYPE_GENERIC;
    }
References touchgfx::DMA_TYPE_GENERIC.
Referenced by HAL::getDMAType().
getReserved()
bool getReserved () const inline
Gets whether a DMA operation is reserved by rendering. Used to allow/disallow other users of DMA2D whom are drawing into the framebuffer, e.g. video thread.
Returns
true if DMA is reserved by rendering, false if not.
    {
        return isReserved;
    }
References DMA_Interface::isReserved.
Referenced by HAL_JPEG_DataReadyCallback().
initialize()
virtual void initialize () inline virtual
Perform initialization. Does nothing in this base class.
Reimplemented in STM32DMA.
    {
    }
isDmaQueueEmpty()
uint8_t isDmaQueueEmpty ()
Query if the DMA queue is empty.
Returns
1 if DMA queue is empty, else 0.
isDmaQueueFull()
uint8_t isDmaQueueFull ()
Query if the DMA queue is full.
Returns
1 if DMA queue is full, else 0.
isDMARunning()
bool isDMARunning () inline
Query if the DMA is running.
Returns
true if a DMA operation is currently in progress.
    {
        return isRunning;
    }
References DMA_Interface::isRunning.
Referenced by HAL_JPEG_DataReadyCallback(), and JPEG_OutputHandler().
seedExecution()
virtual void seedExecution () protected virtual
Called when elements are added to the DMA-queue.
Note
The framebuffer must be locked before this method returns if the DMA-queue is non- empty.
setAllowed()
void setAllowed (bool allowed) inline
Sets whether or not a DMA operation is allowed to begin. Used in single-buffering to avoid changing the framebuffer while display is being updated.
Parameters
allowed true if DMA transfers are allowed.
    {
        isAllowed = allowed;
    }
References DMA_Interface::isAllowed.
setReserved()
void setReserved (bool reserved) inline
Sets whether or not a DMA operation is reserved by rendering. Used to allow/disallow other users of DMA2D whom are drawing into the framebuffer, e.g. video thread.
Parameters
reserved true if DMA is reserved by rendering.
    {
        isReserved = reserved;
    }
References DMA_Interface::isReserved.
setupDataCopy()
virtual void setupDataCopy (const BlitOp & blitOp) protected pure virtual
Configures blit-op hardware for a 2D copy as specified by blitOp.
Parameters
blitOp The operation to execute.
Implemented in NoDMA, and STM32DMA.
setupDataFill()
virtual void setupDataFill (const BlitOp & blitOp) protected pure virtual
Configures blit-op hardware for a 2D fill as specified by blitOp.
Parameters
blitOp The operation to execute.
Implemented in NoDMA, and STM32DMA.
signalDMAInterrupt()
virtual void signalDMAInterrupt () pure virtual
This function is called automatically by the framework when a DMA interrupt has been received.
This function is called automatically by the framework when a DMA interrupt has been received.
Implemented in NoDMA, and STM32DMA.
Referenced by HAL::signalDMAInterrupt().
start()
virtual void start () virtual
Signals that DMA transfers can start. If any elements are in the queue, start it.
Reimplemented in STM32DMA.
Referenced by TouchGFXGeneratedHAL::endFrame(), JPEG_OutputHandler(), and TouchGFXGeneratedHAL::unlockFrameBuffer().
waitForFrameBufferSemaphore()
virtual void waitForFrameBufferSemaphore () protected virtual
Waits until framebuffer semaphore is available (i.e. neither DMA or application is accessing the framebuffer).
Referenced by DMA_Interface::flush().
Member Data Documentation
isAllowed
volatile bool isAllowed protected
true if DMA transfers are currently allowed.
Referenced by DMA_Interface::getAllowed(), DMA_Interface::setAllowed(), STM32DMA::signalDMAInterrupt(), and STM32DMA::start().
isReserved
volatile bool isReserved protected
true if DMA is reserved for for HW rendering
Referenced by DMA_Interface::getReserved(), DMA_Interface::setReserved(), STM32DMA::signalDMAInterrupt(), and STM32DMA::start().
isRunning
bool isRunning protected
true if a DMA transfer is currently ongoing.
Referenced by STM32DMA::externalJobCompleted(), STM32DMA::externalJobExecute(), DMA_Interface::isDMARunning(), STM32DMA::signalDMAInterrupt(), and STM32DMA::start().
queue
DMA_Queue& queue protected
Reference to the DMA queue.
Referenced by STM32DMA::signalDMAInterrupt(), and STM32DMA::start().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/hal/DMA.hpp