Battery Simulator Documentation: ListLayout
ListLayout
#include "ListLayout.hpp"
Public Member Functions
ListLayout (const Direction d=SOUTH)
virtual void add (Drawable &d)
virtual Direction getDirection () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void setDirection (const Direction d)
Public Member Functions inherited from Container
Container ()
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Private Member Functions
void internalAddElement (Drawable &d)
void internalAddElementAt (Drawable &d, int16_t coord)
void internalRemoveElement (Drawable &d, int16_t coord)
Private Attributes
Direction direction
int16_t offset
Additional Inherited Members
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
This class provides a layout mechanism for arranging Drawable instances adjacent in the specified Direction. The first element in the ListLayout is positioned in the ListLayout origin (0,0). The dimensions of this class is automatically expanded to cover the area of the added Drawable instances, which may grow larger than the dimensions of the physical screen. Place the ListLayout inside e.g. a ScrollableContainer to allow all the children to be viewed.
See also
ScrollableContainer
Constructor & Destructor Documentation
ListLayout()
ListLayout (const Direction d = SOUTH) inline
Initializes a new instance of the ListLayout class.
Parameters
d (Optional) The direction to place the elements. SOUTH (Default) places the elements vertically, EAST places the elements horizontally.
See also
setDirection
        : Container(), direction(d), offset(0)
    {
        assert((d == SOUTH || d == EAST) && "Chosen direction not supported");
    }
References touchgfx::EAST, and touchgfx::SOUTH.
Member Function Documentation
add()
void add (Drawable & d) virtual
Adds a Drawable instance to the end of the list. The Drawable dimensions shall be set prior to addition. The coordinates of the Drawable will be updated to reflect the position in the ListLayout.
Parameters
[in] d The Drawable to add.
Reimplemented from Container.
{
    internalAddElement(d);
    Container::add(d);
    if (parent)
    {
        parent->childGeometryChanged();
    }
}
References Container::add(), Drawable::childGeometryChanged(), ListLayout::internalAddElement(), and Drawable::parent.
Referenced by SwipeContainer::add(), and ListLayout::insert().
getDirection()
virtual Direction getDirection () const inline virtual
Gets the direction of the ListLayout.
Returns
The current direction to grow in when added children (either SOUTH or EAST).
See also
setDirection
    {
        return direction;
    }
References ListLayout::direction.
insert()
void insert (Drawable * previous, Drawable & d) virtual
Inserts a Drawable after a specific child node. If previous child node is 0, the drawable will be inserted as the first element in the list. The first element in the list of children is the element drawn first, so this makes it possible to insert a Drawable behind all previously added children.
Parameters
[in] previous The Drawable to insert after. If null, insert as header.
[in] d The Drawable to insert.
Note
As with add, do not add the same drawable twice.
Reimplemented from Container.
{
    if (!firstChild)
    {
        // List is empty, just add the new entry
        add(d);
        return;
    }
    Container::insert(previous, d);
    AdjustElements tmp(&d, direction);
    Callback<AdjustElements, Drawable&> function(&tmp, &AdjustElements::handleInsert);
    forEachChild(&function);
    internalAddElementAt(d, tmp.insertedCoord);
    if (parent)
    {
        parent->childGeometryChanged();
    }
}
References ListLayout::add(), Drawable::childGeometryChanged(), ListLayout::direction, Container::firstChild, Container::forEachChild(), AdjustElements::handleInsert(), Container::insert(), ListLayout::internalAddElementAt(), and Drawable::parent.
internalAddElement()
void internalAddElement (Drawable & d) private
{
    internalAddElementAt(d, offset);
}
References ListLayout::internalAddElementAt().
Referenced by ListLayout::add(), and ListLayout::setDirection().
internalAddElementAt()
void internalAddElementAt (Drawable & d, int16_t coord) private
{
    switch (direction)
    {
    case SOUTH:
        if (rect.width < d.getWidth())
        {
            rect.width = d.getWidth();
        }
        rect.height += d.getHeight();
        d.setXY(0, coord);
        offset += d.getHeight();
        break;
    case EAST:
        if (rect.height < d.getHeight())
        {
            rect.height = d.getHeight();
        }
        rect.width += d.getWidth();
        d.setXY(coord, 0);
        offset += d.getWidth();
        break;
    case NORTH:
    case WEST:
        break;
    }
}
References ListLayout::direction, touchgfx::EAST, Rect::height, touchgfx::NORTH, Drawable::rect, touchgfx::SOUTH, touchgfx::WEST, and Rect::width.
Referenced by ListLayout::insert(), and ListLayout::internalAddElement().
internalRemoveElement()
void internalRemoveElement (Drawable & d, int16_t coord) private
{
    switch (direction)
    {
    case SOUTH:
        if (rect.width > coord)
        {
            rect.width = coord;
        }
        rect.height -= d.getHeight();
        d.setX(0);
        d.setY(0);
        offset -= d.getHeight();
        break;
    case EAST:
        if (rect.height > coord)
        {
            rect.height = coord;
        }
        rect.width -= d.getWidth();
        d.setX(0);
        d.setY(0);
        offset -= d.getWidth();
        break;
    case NORTH:
    case WEST:
        break;
    }
}
References ListLayout::direction, touchgfx::EAST, Rect::height, touchgfx::NORTH, Drawable::rect, touchgfx::SOUTH, touchgfx::WEST, and Rect::width.
Referenced by ListLayout::remove().
remove()
void remove (Drawable & d) virtual
Removes a Drawable. Safe to call even if drawable has not been added. Other Drawable elements in the ListLayout are repositioned and the size of the ListLayout is adjusted.
Parameters
[in] d The drawable to remove.
Reimplemented from Container.
{
    AdjustElements tmp(&d, direction);
    Callback<AdjustElements, Drawable&> function(&tmp, &AdjustElements::handleRemove);
    forEachChild(&function);
    if (tmp.newElementPassed)
    {
        internalRemoveElement(d, tmp.insertedCoord);
        Container::remove(d);
    }
    if (parent)
    {
        parent->childGeometryChanged();
    }
}
References Drawable::childGeometryChanged(), ListLayout::direction, Container::forEachChild(), AdjustElements::handleRemove(), ListLayout::internalRemoveElement(), Drawable::parent, and Container::remove().
Referenced by SwipeContainer::remove().
removeAll()
void removeAll () virtual
Removes all children in the Container by resetting their parent and sibling pointers. Please note that this is not done recursively, so any child which is itself a Container is not emptied.
Reimplemented from Container.
{
    offset = 0;
    setWidthHeight(0, 0);
    Container::removeAll();
    if (parent)
    {
        parent->childGeometryChanged();
    }
}
References Drawable::childGeometryChanged(), Drawable::parent, Container::removeAll(), and Drawable::setWidthHeight().
setDirection()
void setDirection (const Direction d) virtual
Sets the direction of the ListLayout. If elements have already been added to the ListLayout, these elements will be repositioned to adhere to the new direction.
Parameters
d The new Direction to grow in when added children (either SOUTH or EAST).
See also
getDirection
{
    assert((d == SOUTH || d == EAST) && "Chosen direction not supported");
    if (direction != d)
    {
        direction = d;
        offset = 0;
        setWidthHeight(0, 0);
        Callback<ListLayout, Drawable&> function(this, &ListLayout::internalAddElement);
        forEachChild(&function);
        if (parent)
        {
            parent->childGeometryChanged();
        }
    }
}
References Drawable::childGeometryChanged(), ListLayout::direction, touchgfx::EAST, Container::forEachChild(), ListLayout::internalAddElement(), Drawable::parent, Drawable::setWidthHeight(), and touchgfx::SOUTH.
Member Data Documentation
direction
Direction direction private
Referenced by ListLayout::getDirection(), ListLayout::insert(), ListLayout::internalAddElementAt(), ListLayout::internalRemoveElement(), ListLayout::remove(), and ListLayout::setDirection().
offset
int16_t offset private
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/ListLayout.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/ListLayout.cpp