Battery Simulator Documentation: AbstractClock
AbstractClock abstract
#include "AbstractClock.hpp"
Public Member Functions
AbstractClock ()
bool getCurrentAM () const
uint8_t getCurrentHour () const
uint8_t getCurrentHour12 () const
uint8_t getCurrentHour24 () const
uint8_t getCurrentMinute () const
uint8_t getCurrentSecond () const
virtual void setTime12Hour (uint8_t hour, uint8_t minute, uint8_t second, bool am)
virtual void setTime24Hour (uint8_t hour, uint8_t minute, uint8_t second)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual void updateClock ()=0
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
uint8_t currentHour
Local copy of the current hour.
uint8_t currentMinute
Local copy of the current minute.
uint8_t currentSecond
Local copy of the current second.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
Superclass of clock widgets. Allows the hour, minute and second of the clock to be set and read.
See also
AnalogClock, DigitalClock
Constructor & Destructor Documentation
AbstractClock()
AbstractClock ()
    : Container(),
      currentHour(0),
      currentMinute(0),
      currentSecond(0)
{
}
Member Function Documentation
getCurrentAM()
bool getCurrentAM () const
Is the current time a.m. or p.m.? True for a.m. and false for p.m.
Returns
True if a.m., false if p.m.
{
    return currentHour < 12;
}
References AbstractClock::currentHour.
Referenced by DigitalClock::updateClock().
getCurrentHour()
uint8_t getCurrentHour () const
Gets the current hour.
Returns
The current hour in range 0-23.
See also
getCurrentHour24, getCurrentHour12
{
    return currentHour;
}
References AbstractClock::currentHour.
Referenced by AnalogClock::setHourHandMinuteCorrection(), and AnalogClock::setMinuteHandSecondCorrection().
getCurrentHour12()
uint8_t getCurrentHour12 () const
Gets current hour 12, i.e. between 1 and 12.
Returns
The current hour in range 1-12.
See also
getCurrentHour24, getCurrentAM
{
    return ((currentHour + 11) % 12) + 1;
}
References AbstractClock::currentHour.
Referenced by DigitalClock::updateClock().
getCurrentHour24()
uint8_t getCurrentHour24 () const
Gets current hour 24, i.e. between 0 and 23.
Returns
The current hour in range 0-23.
{
    return currentHour;
}
References AbstractClock::currentHour.
Referenced by DigitalClock::updateClock().
getCurrentMinute()
uint8_t getCurrentMinute () const
Gets the current minute.
Returns
The current minute in range 0-59.
{
    return currentMinute;
}
References AbstractClock::currentMinute.
Referenced by AnalogClock::setHourHandMinuteCorrection(), AnalogClock::setMinuteHandSecondCorrection(), and DigitalClock::updateClock().
getCurrentSecond()
uint8_t getCurrentSecond () const
Gets the current second.
Returns
The current second in range 0-59.
{
    return currentSecond;
}
References AbstractClock::currentSecond.
Referenced by AnalogClock::setHourHandMinuteCorrection(), AnalogClock::setMinuteHandSecondCorrection(), and DigitalClock::updateClock().
setTime12Hour()
void setTime12Hour (uint8_t hour, uint8_t minute, uint8_t second, bool am) virtual
Sets the time with input format as 12H. Note that this does not affect any selected presentation formats.
Parameters
hour The hours, value should be between 1 and 12.
minute The minutes, value should be between 0 and 59.
second The seconds, value should be between 0 and 59.
am AM/PM setting. True = AM, false = PM.
Note
all values passed are saved modulo the values limit. For example minutes=62 is treated as minutes=2.
{
    setTime24Hour((hour % 12) + (am ? 0 : 12), minute, second);
}
References AbstractClock::setTime24Hour().
setTime24Hour()
void setTime24Hour (uint8_t hour, uint8_t minute, uint8_t second) virtual
Sets the time with input format as 24H. Note that this does not affect any selected presentation formats.
Parameters
hour The hours, value should be between 0 and 23.
minute The minutes, value should be between 0 and 59.
second The seconds, value should be between 0 and 59.
Note
all values passed are saved modulo the values limit. For example minutes=62 is treated as minutes=2.
{
    currentHour = hour % 24;
    currentMinute = minute % 60;
    currentSecond = second % 60;
    updateClock();
}
References AbstractClock::currentHour, AbstractClock::currentMinute, AbstractClock::currentSecond, and AbstractClock::updateClock().
Referenced by AnalogClock::initializeTime24Hour(), AnalogClock::setHourHandMinuteCorrection(), AnalogClock::setMinuteHandSecondCorrection(), and AbstractClock::setTime12Hour().
updateClock()
virtual void updateClock () protected pure virtual
Update the visual representation of the clock on the display.
Implemented in AnalogClock, and DigitalClock.
Referenced by AbstractClock::setTime24Hour().
Member Data Documentation
currentHour
uint8_t currentHour protected
Local copy of the current hour.
Referenced by AbstractClock::getCurrentAM(), AbstractClock::getCurrentHour(), AbstractClock::getCurrentHour12(), AbstractClock::getCurrentHour24(), AbstractClock::setTime24Hour(), and AnalogClock::updateClock().
currentMinute
uint8_t currentMinute protected
Local copy of the current minute.
Referenced by AbstractClock::getCurrentMinute(), AbstractClock::setTime24Hour(), and AnalogClock::updateClock().
currentSecond
uint8_t currentSecond protected
Local copy of the current second.
Referenced by AbstractClock::getCurrentSecond(), AbstractClock::setTime24Hour(), and AnalogClock::updateClock().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/clock/AbstractClock.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/clock/AbstractClock.cpp