Battery Simulator Documentation: HAL
HAL abstract
#include "HAL.hpp"
Public Types
enum FrameRefreshStrategy { REFRESH_STRATEGY_DEFAULT , REFRESH_STRATEGY_OPTIM_SINGLE_BUFFER_TFT_CTRL , REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER }
enum RenderingMethod { SOFTWARE , HARDWARE }
Public Member Functions
HAL (DMA_Interface &dmaInterface, LCD &display, TouchController &touchCtrl, uint16_t width, uint16_t height)
virtual ~HAL ()
virtual void allowDMATransfers ()
virtual void backPorchExited ()
virtual void blitCopy (const uint16_t *pSrc, const uint8_t *pClut, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool hasTransparentPixels, uint16_t dstWidth, Bitmap::BitmapFormat srcFormat, Bitmap::BitmapFormat dstFormat, bool replaceBgAlpha)
virtual void blitCopy (const uint16_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool hasTransparentPixels, bool replaceBgAlpha)
virtual void blitCopy (const uint16_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool hasTransparentPixels, uint16_t dstWidth, Bitmap::BitmapFormat srcFormat, Bitmap::BitmapFormat dstFormat, bool replaceBgAlpha)
virtual void blitCopyARGB8888 (const uint16_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool replaceBgAlpha)
virtual void blitCopyGlyph (const uint8_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, colortype color, uint8_t alpha, BlitOperations operation, bool replaceBgAlpha)
virtual void blitCopyWord (const uint16_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint16_t dstWidth)
virtual void blitFill (colortype color, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t alpha, bool replaceBgAlpha)
virtual void blitFill (colortype color, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t alpha, uint16_t dstWidth, Bitmap::BitmapFormat dstFormat, bool replaceBgAlpha)
virtual void blitFillWord (uint16_t colorValue, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t dstWidth)
virtual bool blockCopy (void *RESTRICT dest, const void *RESTRICT src, uint32_t numBytes)
virtual void configureInterrupts ()=0
virtual uint16_t configurePartialFrameBuffer (const uint16_t x, const uint16_t y, const uint16_t width, const uint16_t height)
virtual uint16_t * copyFBRegionToMemory (Rect meAbs)
virtual uint16_t * copyFBRegionToMemory (Rect meAbs, uint16_t *dst, uint32_t stride)
virtual uint16_t * copyFromTFTToClientBuffer (Rect region)
virtual void disableInterrupts ()=0
virtual void drawDrawableInDynamicBitmap (Drawable &drawable, BitmapId bitmapId)
virtual void drawDrawableInDynamicBitmap (Drawable &drawable, BitmapId bitmapId, const Rect &rect)
void enableDMAAcceleration (const bool enable)
virtual void enableInterrupts ()=0
virtual void enableLCDControllerInterrupt ()=0
void enableMCULoadCalculation (bool enabled)
virtual void flushDMA ()
virtual void flushFrameBuffer ()
virtual void flushFrameBuffer (const Rect &rect)
void frontPorchEntered ()
uint16_t * getAnimationStorage () const
LCD * getAuxiliaryLCD ()
virtual BlitOperations getBlitCaps ()
ButtonController * getButtonController () const
uint32_t getCPUCycles ()
uint16_t getDisplayHeight () const
DisplayOrientation getDisplayOrientation () const
uint16_t getDisplayWidth () const
virtual DMAType getDMAType ()
uint8_t getFingerSize () const
virtual FlashDataReader * getFlashDataReader () const
FrameBufferAllocator * getFrameBufferAllocator ()
FrameRefreshStrategy getFrameRefreshStrategy () const
Gestures * getGestures ()
uint32_t getLCDRefreshCount ()
uint8_t getMCULoadPct () const
virtual uint16_t getTFTCurrentLine ()
virtual uint16_t * getTFTFrameBuffer () const =0
int8_t getTouchSampleRate () const
virtual void initialize ()
void lockDMAToFrontPorch (bool enableLock)
virtual uint16_t * lockFrameBuffer ()
uint16_t * lockFrameBufferForRenderingMethod (RenderingMethod method)
virtual void registerEventListener (UIEventListener &listener)
void registerTaskDelayFunction (void(*delayF)(uint16_t))
virtual bool sampleKey (uint8_t &key)
virtual void setAnimationStorage (void *animationStorage)
void setAuxiliaryLCD (LCD *auxLCD)
void setButtonController (ButtonController *btnCtrl)
virtual void setDisplayOrientation (DisplayOrientation orientation)
void setDragThreshold (uint8_t value)
void setFingerSize (uint8_t size)
void setFrameBufferAllocator (FrameBufferAllocator *allocator)
virtual void setFrameBufferSize (uint16_t width, uint16_t height)
virtual void setFrameBufferStartAddresses (void *frameBuffer, void *doubleBuffer, void *animationStorage)
void setFrameRateCompensation (bool enabled)
bool setFrameRefreshStrategy (FrameRefreshStrategy s)
void setMCUActive (bool active)
void setMCUInstrumentation (MCUInstrumentation *mcuInstr)
void setRenderingMethod (RenderingMethod method)
void setTouchSampleRate (int8_t sampleRateInTicks)
void signalDMAInterrupt ()
void swapFrameBuffers ()
virtual void taskDelay (uint16_t ms)
virtual void taskEntry ()
virtual void unlockFrameBuffer ()
void vSync ()
Static Public Member Functions
static HAL * getInstance ()
static LCD & lcd ()
Static Public Attributes
static uint16_t DISPLAY_HEIGHT
The height of the LCD display in pixels.
static DisplayRotation DISPLAY_ROTATION
The rotation from display to framebuffer.
static uint16_t DISPLAY_WIDTH
The width of the LCD display in pixels.
static uint16_t FRAME_BUFFER_HEIGHT
The height of the framebuffer in pixels.
static uint16_t FRAME_BUFFER_WIDTH
The width of the framebuffer in pixels.
static bool USE_ANIMATION_STORAGE
Is animation storage enabled?
static bool USE_DOUBLE_BUFFERING
Is double buffering enabled?
Protected Member Functions
virtual bool beginFrame ()
virtual void endFrame ()
virtual void FlushCache ()
uint16_t * getClientFrameBuffer ()
virtual void InvalidateCache ()
virtual void noTouch ()
virtual void performDisplayOrientationChange ()
virtual void setTFTFrameBuffer (uint16_t *address)=0
virtual void tick ()
virtual void touch (int32_t x, int32_t y)
Protected Attributes
LCD * auxiliaryLCD
Auxiliary LCD class used to render Drawables into dynamic bitmaps.
ButtonController * buttonController
A reference to an optional ButtonController.
DMA_Interface & dma
A reference to the DMA interface.
uint8_t fingerSize
The radius of the finger in pixels.
uint16_t * frameBuffer0
Pointer to the first framebuffer.
uint16_t * frameBuffer1
Pointer to the second framebuffer.
uint16_t * frameBuffer2
Pointer to the optional third framebuffer used for animation storage.
FrameBufferAllocator * frameBufferAllocator
A reference to an optional FrameBufferAllocator.
bool frameBufferUpdatedThisFrame
True if something was drawn in the current frame.
Gestures gestures
Class for low-level interpretation of touch events.
LCD & lcdRef
A reference to the LCD.
bool lockDMAToPorch
Whether or not to lock DMA transfers with TFT porch signal.
MCUInstrumentation * mcuInstrumentation
A reference to an optional MCU instrumentation.
DisplayOrientation nativeDisplayOrientation
Contains the native display orientation. If desired orientation is different, apply rotation.
Rect partialFrameBufferRect
The region of the screen covered by the partial framebuffer.
FrameRefreshStrategy refreshStrategy
The selected display refresh strategy.
void(* taskDelayFunc)(uint16_t)
Pointer to a function that can delay GUI task for a number of milliseconds.
TouchController & touchController
A reference to the touch controller.
bool useAuxiliaryLCD
True if using another LCD than the hardware framebuffer.
Static Protected Attributes
static bool isDrawing
True if currently in the process of rendering a screen.
Private Member Functions
uint8_t getBitDepth (Bitmap::BitmapFormat format) const
uint16_t * getDstAddress (uint16_t x, uint16_t y, uint16_t *startAddress) const
uint16_t * getDstAddress (uint16_t x, uint16_t y, uint16_t *startAddress, uint16_t dstWidth, Bitmap::BitmapFormat dstFormat) const
Private Attributes
uint32_t cc_begin
bool clientDirty
bool displayOrientationChangeRequested
RenderingMethod lastRenderMethod
bool lastTouched
int32_t lastX
int32_t lastY
UIEventListener * listener
uint8_t mcuLoadPct
DisplayOrientation requestedOrientation
bool swapRequested
int8_t touchSampleRate
bool updateMCULoad
bool useDMAAcceleration
uint8_t vSyncCnt
bool vSyncCompensationEnabled
uint8_t vSyncForFrame
Static Private Attributes
static HAL * instance
Detailed Description
Hardware Abstraction Layer.
Contains functions that are specific to the hardware platform the code is running on.
Member Enumeration Documentation
FrameRefreshStrategy
enum FrameRefreshStrategy
A list of available frame refresh strategies.
See also
setFrameRefreshStrategy
Enumerator
REFRESH_STRATEGY_DEFAULT
If not explicitly set, this strategy is used.
REFRESH_STRATEGY_OPTIM_SINGLE_BUFFER_TFT_CTRL
Strategy optimized for single framebuffer on systems with TFT controller.
REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER
Strategy using less than a full framebuffer.
    {
        REFRESH_STRATEGY_DEFAULT,
        REFRESH_STRATEGY_OPTIM_SINGLE_BUFFER_TFT_CTRL,
        REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER
    };
RenderingMethod
enum RenderingMethod
A list of rendering methods.
See also
setRenderingMethod
Enumerator
SOFTWARE
Transition to this method will invalidate the D-Cache, if enabled.
HARDWARE
Transition to this method will flush the D-Cache, if enabled.
    {
        SOFTWARE,
        HARDWARE
    };
Constructor & Destructor Documentation
HAL()
HAL (DMA_Interface & dmaInterface, LCD & display, TouchController & touchCtrl, uint16_t width, uint16_t height) inline
Initializes a new instance of the HAL class.
Parameters
[in] dmaInterface Reference to the DMA interface.
[in] display Reference to the LCD.
[in] touchCtrl Reference to the touch controller.
width The width of the LCD display, in pixels.
height The height of the LCD display, in pixels.
        : dma(dmaInterface),
          lcdRef(display),
          touchController(touchCtrl),
          mcuInstrumentation(0),
          buttonController(0),
          frameBufferAllocator(0),
          gestures(),
          nativeDisplayOrientation(ORIENTATION_LANDSCAPE),
          taskDelayFunc(0),
          frameBuffer0(0),
          frameBuffer1(0),
          frameBuffer2(0),
          refreshStrategy(REFRESH_STRATEGY_DEFAULT),
          fingerSize(1),
          lockDMAToPorch(false),
          frameBufferUpdatedThisFrame(false),
          auxiliaryLCD(0),
          partialFrameBufferRect(),
          useAuxiliaryLCD(false),
          listener(0),
          lastX(0),
          lastY(0),
          touchSampleRate(1),
          mcuLoadPct(0),
          vSyncCnt(0),
          vSyncForFrame(1),
          vSyncCompensationEnabled(false),
          clientDirty(false),
          swapRequested(false),
          lastTouched(false),
          updateMCULoad(0),
          cc_begin(0),
          requestedOrientation(ORIENTATION_LANDSCAPE),
          displayOrientationChangeRequested(false),
          useDMAAcceleration(true),
          lastRenderMethod(HARDWARE)
    {
        instance = this;
        FRAME_BUFFER_WIDTH = DISPLAY_WIDTH = width;
        FRAME_BUFFER_HEIGHT = DISPLAY_HEIGHT = height;
        DISPLAY_ROTATION = rotate0;
        nativeDisplayOrientation = ((width >= height) ? ORIENTATION_LANDSCAPE : ORIENTATION_PORTRAIT);
    }
References HAL::DISPLAY_HEIGHT, HAL::DISPLAY_ROTATION, HAL::DISPLAY_WIDTH, HAL::FRAME_BUFFER_HEIGHT, HAL::FRAME_BUFFER_WIDTH, HAL::instance, HAL::nativeDisplayOrientation, touchgfx::ORIENTATION_LANDSCAPE, touchgfx::ORIENTATION_PORTRAIT, and touchgfx::rotate0.
~HAL()
virtual ~HAL () inline virtual
Finalizes an instance of the HAL class.
    {
    }
Member Function Documentation
allowDMATransfers()
virtual void allowDMATransfers () virtual
Allow the DMA to start transfers. Front Porch Entry is a good place to call this.
Referenced by HAL::frontPorchEntered().
backPorchExited()
virtual void backPorchExited () inline virtual
Has to be called from within the LCD IRQ rutine when the Back Porch Exit is reached.
Has to be called from within the LCD IRQ rutine when the Back Porch Exit is reached.
    {
        swapFrameBuffers();
        tick();
    }
References HAL::swapFrameBuffers(), and HAL::tick().
Referenced by HALSDL2::taskEntry().
beginFrame()
virtual bool beginFrame () protected virtual
Called when beginning to rendering a frame.
Returns
true if rendering can begin, false otherwise.
Reimplemented in TouchGFXGeneratedHAL, and TouchGFXHAL.
Referenced by TouchGFXGeneratedHAL::beginFrame().
blitCopy() [1/3]
virtual void blitCopy (const uint16_t * pSrc, const uint8_t * pClut, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool hasTransparentPixels, uint16_t dstWidth, Bitmap::BitmapFormat srcFormat, Bitmap::BitmapFormat dstFormat, bool replaceBgAlpha) virtual
Blits a 2D source-array to the framebuffer performing alpha-blending as specified.
Parameters
pSrc The source-array pointer (points to first value to copy)
pClut The CLUT pointer (points to CLUT header data which include the type and size of this CLUT followed by colors data)
x The destination x coordinate on the framebuffer.
y The destination y coordinate on the framebuffer.
width The width desired area of the source 2D array.
height The height of desired area of the source 2D array.
srcWidth The distance (in elements) from first value of first line, to first value of second line (the source 2D array width)
alpha The alpha value to use for blending (255 = solid, no blending)
hasTransparentPixels If true, this data copy contains transparent pixels and require hardware support for that to be enabled.
dstWidth The distance (in elements) from first value of first line, to first value of second line (the destination 2D array width)
srcFormat The source buffer color format (default is the framebuffer format)
dstFormat The destination buffer color format (default is the framebuffer format)
replaceBgAlpha Replace the background buffer per pixel alpha value with 255 = solid.
Note
Alpha=255 is assumed "solid" and shall be used if HAL does not support BLIT_OP_COPY_WITH_ALPHA.
blitCopy() [2/3]
virtual void blitCopy (const uint16_t * pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool hasTransparentPixels, bool replaceBgAlpha) virtual
Blits a 2D source-array to the framebuffer performing alpha-blending as specified using the default lcd format.
Parameters
pSrc The source-array pointer (points to first value to copy)
x The destination x coordinate on the framebuffer.
y The destination y coordinate on the framebuffer.
width The width desired area of the source 2D array.
height The height of desired area of the source 2D array.
srcWidth The distance (in elements) from first value of first line, to first value of second line (the source 2D array width)
alpha The alpha value to use for blending (255 = solid, no blending)
hasTransparentPixels If true, this data copy contains transparent pixels and require hardware support for that to be enabled.
replaceBgAlpha Replace the background buffer per pixel alpha value with 255 = solid.
Note
Alpha=255 is assumed "solid" and shall be used if HAL does not support BLIT_OP_COPY_WITH_ALPHA.
blitCopy() [3/3]
virtual void blitCopy (const uint16_t * pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool hasTransparentPixels, uint16_t dstWidth, Bitmap::BitmapFormat srcFormat, Bitmap::BitmapFormat dstFormat, bool replaceBgAlpha) virtual
Blits a 2D source-array to the framebuffer performing alpha-blending as specified.
Parameters
pSrc The source-array pointer (points to first value to copy)
x The destination x coordinate on the framebuffer.
y The destination y coordinate on the framebuffer.
width The width desired area of the source 2D array.
height The height of desired area of the source 2D array.
srcWidth The distance (in elements) from first value of first line, to first value of second line (the source 2D array width)
alpha The alpha value to use for blending (255 = solid, no blending)
hasTransparentPixels If true, this data copy contains transparent pixels and require hardware support for that to be enabled.
dstWidth The distance (in elements) from first value of first line, to first value of second line (the destination 2D array width)
srcFormat The source buffer color format (default is the framebuffer format)
dstFormat The destination buffer color format (default is the framebuffer format)
replaceBgAlpha Replace the background buffer per pixel alpha value with 255 = solid.
Note
Alpha=255 is assumed "solid" and shall be used if HAL does not support BLIT_OP_COPY_WITH_ALPHA.
blitCopyARGB8888()
virtual void blitCopyARGB8888 (const uint16_t * pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool replaceBgAlpha) virtual
Blits a 2D source-array to the framebuffer performing per-pixel alpha blending.
Parameters
pSrc The source-array pointer (points to first value to copy)
x The destination x coordinate on the framebuffer.
y The destination y coordinate on the framebuffer.
width The width desired area of the source 2D array.
height The height of desired area of the source 2D array.
srcWidth The distance (in elements) from first value of first line, to first value of second line (the source 2D array width)
alpha The alpha value to use for blending. This is applied on every pixel, in addition to the per-pixel alpha value (255 = solid, no blending)
replaceBgAlpha Replace the background buffer per pixel alpha value with 255 = solid.
blitCopyGlyph()
virtual void blitCopyGlyph (const uint8_t * pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, colortype color, uint8_t alpha, BlitOperations operation, bool replaceBgAlpha) virtual
Blits a 4bpp or 8bpp glyph - maybe use the same method and supply additional color mode arg.
Parameters
pSrc The source-array pointer (points to first value to copy)
x The destination x coordinate on the framebuffer.
y The destination y coordinate on the framebuffer.
width The width desired area of the source 2D array.
height The height of desired area of the source 2D array.
srcWidth The distance (in elements) from first value of first line, to first value of second line (the source 2D array width)
color Color of the text.
alpha The alpha value to use for blending (255 = solid, no blending)
operation The operation type to use for blit copy.
replaceBgAlpha Replace the background buffer per pixel alpha value with 255 = solid.
blitCopyWord()
virtual void blitCopyWord (const uint16_t * pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint16_t dstWidth) virtual
Blits a 2D source-array to the framebuffer using 16-bit copy without conversion. This operation can be used to perform hardware accelerated copies to the framebuffer even when the image (and framebuffer) format is not 16-bit.
All parameters (e.g. x) must correspond to their 16-bit values. I.e. the 10th bytes corresponds to x=5.
Parameters
pSrc Pointer to the source data (points to first value to copy)
x The destination x coordinate in the framebuffer with 16-bit pixels.
y The destination y coordinate in the framebuffer with 16-bit pixels.
width The width of the area to copy in 16-bit pixels.
height The height of the area to copy
srcWidth The width of the source bitmap (stride) in 16-bit pixels.
dstWidth The width of the framebuffer in 16-bit pixels.
blitFill() [1/2]
virtual void blitFill (colortype color, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t alpha, bool replaceBgAlpha) virtual
Blits a color value to the framebuffer performing alpha-blending as specified.
Parameters
color The desired fill-color.
x The destination x coordinate on the framebuffer.
y The destination y coordinate on the framebuffer.
width The width desired area of the source 2D array.
height The height of desired area of the source 2D array.
alpha The alpha value to use for blending (255 = solid, no blending)
replaceBgAlpha Replace the background buffer per pixel alpha value with 255 = solid.
Note
Alpha=255 is assumed "solid" and shall be used if HAL does not support BLIT_OP_FILL_WITH_ALPHA.
blitFill() [2/2]
virtual void blitFill (colortype color, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t alpha, uint16_t dstWidth, Bitmap::BitmapFormat dstFormat, bool replaceBgAlpha) virtual
Blits a color value to the framebuffer performing alpha-blending as specified.
Parameters
color The desired fill-color.
x The destination x coordinate on the framebuffer.
y The destination y coordinate on the framebuffer.
width The width desired area of the source 2D array.
height The height of desired area of the source 2D array.
alpha The alpha value to use for blending (255 = solid, no blending)
dstWidth The distance (in elements) from first value of first line, to first value of second line (the destination 2D array width)
dstFormat The destination buffer color format (default is the framebuffer format)
replaceBgAlpha Replace the background buffer per pixel alpha value with 255 = solid.
Note
Alpha=255 is assumed "solid" and shall be used if HAL does not support BLIT_OP_FILL_WITH_ALPHA.
blitFillWord()
virtual void blitFillWord (uint16_t colorValue, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t dstWidth) virtual
Fills a part of the framebuffer using 16-bit fill without conversion. This operation can be used to perform hardware accelerated fills in the framebuffer even when the framebuffer format is not 16-bit.
All parameters (e.g. x) must correspond to their 16-bit values. I.e. the 10th bytes corresponds to x=5.
Parameters
colorValue The 16-bit value to fill in the framebuffer.
x The destination x coordinate in the framebuffer with 16-bit pixels.
y The destination y coordinate in the framebuffer with 16-bit pixels.
width The width of the area to copy in 16-bit pixels.
height The height of the area to copy
dstWidth The width of the framebuffer in 16-bit pixels.
blockCopy()
virtual bool blockCopy (void *RESTRICT dest, const void *RESTRICT src, uint32_t numBytes) virtual
This function performs a platform-specific memcpy, if supported by the hardware.
Parameters
[out] dest Pointer to destination memory.
[in] src Pointer to source memory.
numBytes Number of bytes to copy.
Returns
true if the copy succeeded, false if copy was not performed.
Reimplemented in TouchGFXGeneratedHAL, and TouchGFXHAL.
Referenced by TouchGFXGeneratedHAL::blockCopy().
configureInterrupts()
virtual void configureInterrupts () pure virtual
Configures the interrupts relevant for TouchGFX. This primarily entails setting the interrupt priorities for the DMA and LCD interrupts.
Implemented in HALSDL2, TouchGFXGeneratedHAL, and TouchGFXHAL.
configurePartialFrameBuffer()
virtual uint16_t configurePartialFrameBuffer (const uint16_t x, const uint16_t y, const uint16_t width, const uint16_t height) virtual
Configures a partial framebuffer as current framebuffer. This method uses the assigned FrameBufferAllocator to allocate block of compatible dimensions. The height of the allocated block is returned.
Parameters
x The absolute x coordinate of the block on the screen.
y The absolute y coordinate of the block on the screen.
width The width of the block.
height The height of the block requested.
Returns
The height of the block allocated.
copyFBRegionToMemory() [1/2]
virtual uint16_t * copyFBRegionToMemory (Rect meAbs) virtual
Copies a region of the currently displayed framebuffer to memory. Used for e.g. SlideTransition and for displaying pre-rendered drawables e.g. in animations where redrawing the drawable is not necessary.
Parameters
meAbs The framebuffer region to copy.
Returns
A pointer to the memory address containing the copy of the framebuffer.
Note
Requires animation storage to be present.
copyFBRegionToMemory() [2/2]
virtual uint16_t * copyFBRegionToMemory (Rect meAbs, uint16_t * dst, uint32_t stride) virtual
Copies a region of the currently displayed framebuffer to a buffer. Used for e.g. SlideTransition and for displaying pre-rendered drawables e.g. in animations where redrawing the drawable is not necessary. The buffer can e.g. be a dynamic bitmap.
Parameters
meAbs The framebuffer region to copy.
[in,out] dst Address of the buffer to store the copy in.
stride The width of the target buffer (row length).
Returns
A pointer to the memory address containing the copy of the framebuffer.
Note
Requires animation storage to be present.
copyFromTFTToClientBuffer()
virtual uint16_t * copyFromTFTToClientBuffer (Rect region) virtual
Copies a region of the currently displayed framebuffer to memory. Used for e.g. BlockTransition and for displaying pre-rendered drawables e.g. in animations where redrawing the drawable is not necessary.
Parameters
region The displayed framebuffer region to copy.
Returns
A pointer to the memory address containing the copy of the framebuffer.
Note
Requires double framebuffer to be enabled.
disableInterrupts()
virtual void disableInterrupts () pure virtual
Disables the DMA and LCD interrupts.
Implemented in HALSDL2, TouchGFXGeneratedHAL, and TouchGFXHAL.
drawDrawableInDynamicBitmap() [1/2]
virtual void drawDrawableInDynamicBitmap (Drawable & drawable, BitmapId bitmapId) virtual
Render a Drawable and its widgets into a dynamic bitmap.
Parameters
[in,out] drawable A reference on the Drawable object to render.
bitmapId Dynamic bitmap to be used as a rendertarget.
drawDrawableInDynamicBitmap() [2/2]
virtual void drawDrawableInDynamicBitmap (Drawable & drawable, BitmapId bitmapId, const Rect & rect) virtual
Render a Drawable and its widgets into a dynamic bitmap. Only the specified Rect region is updated.
Parameters
[in,out] drawable A reference on the Drawable object to render.
bitmapId Dynamic bitmap to be used as a rendertarget.
rect Region to update.
enableDMAAcceleration()
void enableDMAAcceleration (const bool enable) inline
Sets a flag to allow use of DMA operations to speed up drawing operations.
Parameters
enable True to enable, false to disable.
See also
getBlitCaps
    {
        useDMAAcceleration = enable;
    }
References HAL::useDMAAcceleration.
enableInterrupts()
virtual void enableInterrupts () pure virtual
Enables the DMA and LCD interrupts.
Implemented in HALSDL2, TouchGFXGeneratedHAL, and TouchGFXHAL.
enableLCDControllerInterrupt()
virtual void enableLCDControllerInterrupt () pure virtual
Configure the LCD controller to fire interrupts at VSYNC. Called automatically once TouchGFX initialization has completed.
Implemented in HALSDL2, TouchGFXGeneratedHAL, and TouchGFXHAL.
enableMCULoadCalculation()
void enableMCULoadCalculation (bool enabled) inline
This method sets a flag that determines if generic HAL should calculate MCU load based on concrete MCU instrumentation.
Parameters
enabled If true, set flag to update MCU load.
    {
        updateMCULoad = enabled;
    }
References HAL::updateMCULoad.
endFrame()
virtual void endFrame () protected virtual
Called when a rendering pass is completed.
Reimplemented in TouchGFXGeneratedHAL, and TouchGFXHAL.
Referenced by TouchGFXGeneratedHAL::endFrame().
FlushCache()
virtual void FlushCache () inline protected virtual
Flush D-Cache.
Called by setRenderingMethod when changing rendering method from Software to Hardware indicating the cache should be invalidated.
Reimplemented in TouchGFXGeneratedHAL.
    {
    }
flushDMA()
virtual void flushDMA () virtual
This function blocks until the DMA queue (containing BlitOps) is empty.
flushFrameBuffer() [1/2]
virtual void flushFrameBuffer () virtual
This function is called whenever the framework has performed a complete draw.
On some platforms, a local framebuffer needs to be pushed to the display through a SPI channel or similar. Implement that functionality here. This function is called whenever the framework has performed a complete draw.
Reimplemented in HALSDL2, TouchGFXGeneratedHAL, and TouchGFXHAL.
Referenced by HALSDL2::flushFrameBuffer(), and TouchGFXGeneratedHAL::flushFrameBuffer().
flushFrameBuffer() [2/2]
virtual void flushFrameBuffer (const Rect & rect) virtual
This function is called whenever the framework has performed a partial draw.
Parameters
rect The area of the screen that has been drawn, expressed in absolute coordinates.
See also
flushFrameBuffer
Reimplemented in HALSDL2, TouchGFXGeneratedHAL, and TouchGFXHAL.
frontPorchEntered()
void frontPorchEntered () inline
Has to be called from within the LCD IRQ routine when the Front Porch Entry is reached.
    {
        allowDMATransfers();
    }
References HAL::allowDMATransfers().
Referenced by HALSDL2::taskEntry().
getAnimationStorage()
uint16_t * getAnimationStorage () const inline
Gets the optional framebuffer used for animation storage.
Returns
The address or 0 if unused.
    {
        return frameBuffer2;
    }
References HAL::frameBuffer2.
getAuxiliaryLCD()
LCD * getAuxiliaryLCD () inline
Get the auxiliary LCD class attached to the HAL instance if any.
Returns
A pointer on the axiliary LCD class attached to the HAL instance.
    {
        return auxiliaryLCD;
    }
References HAL::auxiliaryLCD.
getBitDepth()
uint8_t getBitDepth (Bitmap::BitmapFormat format) const private
getBlitCaps()
virtual BlitOperations getBlitCaps () inline virtual
Function for obtaining the blit capabilities of the concrete HAL implementation. As default, will return whatever blitcaps are reported by the associated DMA object.
DMA operations can be disabled by calling enableDMAAcceleration(bool).
Returns
a bitmask of the supported blitcaps.
See also
enableDMAAcceleration
    {
        if (useDMAAcceleration)
        {
            return dma.getBlitCaps();
        }
        return static_cast<BlitOperations>(0);
    }
References HAL::dma, DMA_Interface::getBlitCaps(), and HAL::useDMAAcceleration.
getButtonController()
ButtonController * getButtonController () const inline
Gets the associated ButtonController.
Returns
A pointer to the ButtonController, or zero if no ButtonController has been set.
    {
        return buttonController;
    }
References HAL::buttonController.
getClientFrameBuffer()
uint16_t * getClientFrameBuffer () inline protected
Gets client framebuffer.
Returns
The address of the framebuffer currently used by the framework to draw in.
    {
        if (USE_DOUBLE_BUFFERING && getTFTFrameBuffer() == frameBuffer0)
        {
            return frameBuffer1;
        }
        return frameBuffer0;
    }
References HAL::frameBuffer0, HAL::frameBuffer1, HAL::getTFTFrameBuffer(), and HAL::USE_DOUBLE_BUFFERING.
getCPUCycles()
uint32_t getCPUCycles ()
Gets the current cycle counter.
Returns
the cycle counter.
getDisplayHeight()
uint16_t getDisplayHeight () const inline
Gets display height.
Returns
The display height.
    {
        return DISPLAY_HEIGHT;
    }
References HAL::DISPLAY_HEIGHT.
getDisplayOrientation()
DisplayOrientation getDisplayOrientation () const inline
Gets the current display orientation. Will be equal to the native orientation of the display unless setDisplayOrientation has been explicitly called earlier.
Returns
The current display orientation.
    {
        if (DISPLAY_ROTATION == rotate0)
        {
            return nativeDisplayOrientation;
        }
        return (nativeDisplayOrientation == ORIENTATION_LANDSCAPE ? ORIENTATION_PORTRAIT : ORIENTATION_LANDSCAPE);
    }
References HAL::DISPLAY_ROTATION, HAL::nativeDisplayOrientation, touchgfx::ORIENTATION_LANDSCAPE, touchgfx::ORIENTATION_PORTRAIT, and touchgfx::rotate0.
Referenced by HALSDL2::loadSkin(), and HALSDL2::updateCurrentSkin().
getDisplayWidth()
uint16_t getDisplayWidth () const inline
Gets display width.
Returns
The display width.
    {
        return DISPLAY_WIDTH;
    }
References HAL::DISPLAY_WIDTH.
getDMAType()
virtual DMAType getDMAType () inline virtual
Function for obtaining the DMA type of the concrete DMA implementation. As default, will return DMA_TYPE_GENERIC type value.
Returns
a DMAType value of the concrete DMA implementation.
    {
        return dma.getDMAType();
    }
References HAL::dma, and DMA_Interface::getDMAType().
getDstAddress() [1/2]
uint16_t * getDstAddress (uint16_t x, uint16_t y, uint16_t * startAddress) const private
getDstAddress() [2/2]
uint16_t * getDstAddress (uint16_t x, uint16_t y, uint16_t * startAddress, uint16_t dstWidth, Bitmap::BitmapFormat dstFormat) const private
getFingerSize()
uint8_t getFingerSize () const inline
Gets the finger size in pixels.
Returns
The size of the finger in pixels, 1 is the default value.
    {
        return fingerSize;
    }
References HAL::fingerSize.
getFlashDataReader()
virtual FlashDataReader * getFlashDataReader () const inline virtual
Gets the flash data reader. This method must be implemented in subclasses that uses a FlashDataReader object.
Returns
the FlashDataReader.
    {
        return 0;
    }
getFrameBufferAllocator()
FrameBufferAllocator * getFrameBufferAllocator () inline
Gets the framebuffer allocator.
Returns
The framebuffer allocator.
    {
        return frameBufferAllocator;
    }
References HAL::frameBufferAllocator.
Referenced by HALSDL2::sdl_init().
getFrameRefreshStrategy()
FrameRefreshStrategy getFrameRefreshStrategy () const inline
Used internally by TouchGFX core to manage the timing and process of drawing into the framebuffer.
Returns
Current frame refresh strategy.
See also
setFrameRefreshStrategy
    {
        return refreshStrategy;
    }
References HAL::refreshStrategy.
Referenced by HALSDL2::flushFrameBuffer(), HALSDL2::sdl_init(), and HALSDL2::setTFTFrameBuffer().
getGestures()
Gestures * getGestures () inline
Get the Gesture class attached to the HAL instance.
Returns
A pointer to the Gestures object.
    {
        return &gestures;
    }
References HAL::gestures.
getInstance()
static HAL * getInstance () inline static
Gets the HAL instance.
Returns
The HAL instance.
    {
        return instance;
    }
References HAL::instance.
Referenced by FrontendApplicationBase::FrontendApplicationBase(), AbstractPainter::compatibleFramebuffer(), DMA2D_XferCpltCallback(), DirectFrameBufferVideoController< no_streams, output_format >::draw(), Container::getLastChildNear(), PainterRGB565::getRenderingMethod(), PainterRGB565Bitmap::getRenderingMethod(), PainterRGB565L8Bitmap::getRenderingMethod(), PainterRGB888::getRenderingMethod(), PainterRGB888Bitmap::getRenderingMethod(), PainterRGB888L8Bitmap::getRenderingMethod(), HAL_LTDC_LineEventCallback(), IdleTaskHook(), IdleTaskHook(), PainterBWBitmap::paint(), Canvas::render(), SDL2TouchController::sampleTouch(), CacheableContainer::setCacheBitmap(), touchgfx::simulator_enable_stdio(), touchgfx::simulator_printf(), touchgfx::transferThreadFunc(), CacheableContainer::updateCache(), and WinMain().
getLCDRefreshCount()
uint32_t getLCDRefreshCount () inline
Returns the number of VSync interrupts between the current drawing operation and the last drawing operation, i.e. the number of lost frames.
Returns
Number of VSync since previous draw.
    {
        return vSyncForFrame;
    }
References HAL::vSyncForFrame.
getMCULoadPct()
uint8_t getMCULoadPct () const inline
Gets the current MCU load.
Returns
mcuLoadPct the MCU Load in %.
    {
        return mcuLoadPct;
    }
References HAL::mcuLoadPct.
getTFTCurrentLine()
virtual uint16_t getTFTCurrentLine () inline virtual
Get the current line (Y) of the TFT controller
This function is used to obtain the progress of the TFT controller. More specifically, the line (or Y-value) currently being transferred.
Note: The value must be adjusted to account for vertical back porch before returning, such that the value is always within the range of [0; actual display height in pixels[
It is used for the REFRESH_STRATEGY_OPTIM_SINGLE_BUFFER_TFT_CTRL frame refresh strategy in order to synchronize framebuffer drawing with TFT controller progress. If this strategy is used, the concrete HAL subclass must provide an override of this function that returns correct line value. If this strategy is not used, then the getTFTCurrentLine function is never called and can be disregarded.
Returns
In this default implementation, 0xFFFF is returned to signify "not implemented".
    {
        return 0xFFFFu;
    }
Referenced by HAL::setFrameRefreshStrategy().
getTFTFrameBuffer()
virtual uint16_t * getTFTFrameBuffer () const pure virtual
Gets the framebuffer address used by the TFT controller.
Returns
The address of the framebuffer currently being displayed on the TFT.
Implemented in HALSDL2, TouchGFXGeneratedHAL, and TouchGFXHAL.
Referenced by HAL::getClientFrameBuffer().
getTouchSampleRate()
int8_t getTouchSampleRate () const inline
Gets the number of ticks between each touch screen sample.
Returns
Number of ticks between each touch screen sample.
    {
        return touchSampleRate;
    }
References HAL::touchSampleRate.
initialize()
virtual void initialize () virtual
This function initializes the HAL, DMA, TouchController, and interrupts.
See also
configureInterrupts
Reimplemented in TouchGFXGeneratedHAL, and TouchGFXHAL.
Referenced by TouchGFXGeneratedHAL::initialize().
InvalidateCache()
virtual void InvalidateCache () inline protected virtual
Invalidate D-Cache.
Called by setRenderingMethod when changing rendering method from Hardware to Software indicating the cache should be invalidated.
Reimplemented in TouchGFXGeneratedHAL.
    {
    }
lcd()
static LCD & lcd () inline static
Gets a reference to the LCD.
Returns
A reference to the LCD.
    {
        if (instance->useAuxiliaryLCD && instance->auxiliaryLCD)
        {
            return *instance->auxiliaryLCD;
        }
        return instance->lcdRef;
    }
References HAL::instance.
Referenced by FrontendApplicationBase::FrontendApplicationBase(), AbstractPainter::compatibleFramebuffer(), HALSDL2::copyScreenshotToClipboard(), Box::draw(), BoxWithBorder::draw(), ButtonWithLabel::draw(), TextArea::draw(), TextAreaWithWildcardBase::draw(), Button::draw(), ButtonWithIcon::draw(), GraphElementVerticalGapLine::draw(), GraphElementHistogram::draw(), GraphElementBoxes::draw(), GraphTitle::draw(), Image::draw(), Keyboard::draw(), PixelDataWidget::draw(), RadioButton::draw(), SnapshotWidget::draw(), TiledImage::draw(), VideoWidget::draw(), GraphElementGridBase::drawLine(), TextureMapper::drawQuad(), GraphLabelsX::drawString(), GraphLabelsY::drawString(), SnapshotWidget::makeSnapshot(), HALSDL2::recreateWindow(), Canvas::render(), CacheableContainer::setCacheBitmap(), HALSDL2::setFrameBufferSize(), HALSDL2::setTFTFrameBuffer(), setupSimulator(), and HALSDL2::taskEntry().
lockDMAToFrontPorch()
void lockDMAToFrontPorch (bool enableLock) inline
Function to set whether the DMA transfers are locked to the TFT update cycle. If locked, DMA transfer will not begin until the TFT controller has finished updating the display. If not locked, DMA transfers will begin as soon as possible. Default is true (DMA is locked with TFT).
Disabling the lock will in most cases significantly increase rendering performance. It is therefore strongly recommended to disable it. Depending on platform this may in rare cases cause rendering problems (visible tearing on display). Please see the chapter "Optimizing DMA During TFT Controller Access" for details on this setting.
Parameters
enableLock True to lock DMA transfers to the front porch signal. Conservative, default setting. False to disable, which will normally yield substantial performance improvement.
Note
This setting only has effect when using double buffering.
    {
        lockDMAToPorch = enableLock;
    }
References HAL::lockDMAToPorch.
Referenced by HALSDL2::sdl_init().
lockFrameBuffer()
virtual uint16_t * lockFrameBuffer () virtual
Waits for the framebuffer to become available for use (i.e. not used by DMA transfers). Calls the InvalidateCache virtual if previous operation was hardware based.
Returns
A pointer to the beginning of the currently used framebuffer.
Note
Function blocks until framebuffer is available. Client code MUST call unlockFrameBuffer() when framebuffer operation has completed.
lockFrameBufferForRenderingMethod()
uint16_t * lockFrameBufferForRenderingMethod (RenderingMethod method)
Locks the framebuffer and sets rendering method for correct cache management.
Parameters
method The rendering method to be used.
Returns
A pointer to the beginning of the currently used framebuffer.
noTouch()
virtual void noTouch () protected virtual
Called by the touch driver to indicate that no touch is currently detected.
performDisplayOrientationChange()
virtual void performDisplayOrientationChange () inline protected virtual
Perform the actual display orientation change.
Reimplemented in HALSDL2.
    {
        if (requestedOrientation != nativeDisplayOrientation)
        {
            if (DISPLAY_ROTATION == rotate0)
            {
                const uint16_t tmp = DISPLAY_HEIGHT;
                DISPLAY_HEIGHT = DISPLAY_WIDTH;
                DISPLAY_WIDTH = tmp;
                DISPLAY_ROTATION = rotate90;
            }
        }
        else if (DISPLAY_ROTATION != rotate0)
        {
            const uint16_t tmp = DISPLAY_HEIGHT;
            DISPLAY_HEIGHT = DISPLAY_WIDTH;
            DISPLAY_WIDTH = tmp;
            DISPLAY_ROTATION = rotate0;
        }
    }
References HAL::DISPLAY_HEIGHT, HAL::DISPLAY_ROTATION, HAL::DISPLAY_WIDTH, HAL::nativeDisplayOrientation, HAL::requestedOrientation, touchgfx::rotate0, and touchgfx::rotate90.
Referenced by HALSDL2::performDisplayOrientationChange().
registerEventListener()
virtual void registerEventListener (UIEventListener & listener) virtual
Registers an event handler implementation with the underlying event system. The actual HAL implementation decides whether or not multiple UIEventListener instances are allowed (including execution order).
Parameters
[in] listener The listener to register.
Referenced by TouchGFXGeneratedHAL::initialize().
registerTaskDelayFunction()
void registerTaskDelayFunction (void(*)(uint16_t) delayF) inline
Registers a function capable of delaying GUI task execution
In order to make use of the HAL::taskDelay function, a delay function must be registered by calling this function. Usually the delay function would be OSWrappers::taskDelay.
Parameters
[in] delayF A pointer to a function returning void with an uint16_t parameter specifying number of milliseconds to delay.
Note
The task delay capability is only used when the frame refresh strategy REFRESH_STRATEGY_OPTIM_SINGLE_BUFFER_TFT_CTRL is selected. Otherwise it is not necessary to register a delay function.
    {
        taskDelayFunc = delayF;
    }
References HAL::taskDelayFunc.
sampleKey()
virtual bool sampleKey (uint8_t & key) inline virtual
Sample external key event.
Parameters
[out] key Output parameter that will be set to the key value if a keypress was detected.
Returns
True if a keypress was detected and the "key" parameter is set to a value.
Reimplemented in HALSDL2.
    {
        (void)key; // Unused variable
        return false;
    }
References void().
setAnimationStorage()
virtual void setAnimationStorage (void * animationStorage) inline virtual
Sets animation storage address.
Parameters
[in] animationStorage If non-null, the animation storage. If null animation storage is disabled.
See also
setFrameBufferStartAddresses
    {
        frameBuffer2 = reinterpret_cast<uint16_t*>(animationStorage);
        USE_ANIMATION_STORAGE = animationStorage != 0;
    }
References HAL::frameBuffer2, and HAL::USE_ANIMATION_STORAGE.
Referenced by HAL::setFrameBufferStartAddresses().
setAuxiliaryLCD()
void setAuxiliaryLCD (LCD * auxLCD) inline
Set an auxiliary LCD class to be used for offscreen rendering.
Parameters
[in,out] auxLCD A pointer on the axiliary LCD class to use for offscreen rendering.
    {
        auxiliaryLCD = auxLCD;
    }
References HAL::auxiliaryLCD.
setButtonController()
void setButtonController (ButtonController * btnCtrl) inline
Stores a pointer to an instance of a specific implementation of a ButtonController.
Parameters
[in] btnCtrl pointer to button controller.
    {
        buttonController = btnCtrl;
    }
References HAL::buttonController.
setDisplayOrientation()
virtual void setDisplayOrientation (DisplayOrientation orientation) inline virtual
Sets the desired display orientation (landscape or portrait). If desired orientation is different from the native orientation of the display, a rotation is automatically applied. The rotation does not incur any performance cost.
Parameters
orientation The desired display orientation.
Note
A screen transition must occur before this takes effect!
    {
        requestedOrientation = orientation;
        displayOrientationChangeRequested = true;
    }
References HAL::displayOrientationChangeRequested, and HAL::requestedOrientation.
setDragThreshold()
void setDragThreshold (uint8_t value) inline
Configure the threshold for reporting drag events. A touch input movement must exceed this value in either axis in order to report a drag. Default value is 0.
Parameters
value New threshold value.
Note
Use if touch controller is not completely accurate to avoid "false" drags.
    {
        gestures.setDragThreshold(value);
    }
References HAL::gestures, and Gestures::setDragThreshold().
setFingerSize()
void setFingerSize (uint8_t size) inline
Sets the finger size in pixels. Setting the finger size to a size of more than 1 pixel will emulate a finger of width and height of 2*(fingersize-1)+1. This can be especially useful when trying to interact with small elements on a high ppi display. The finger size will influence which element is chosen as the point of interaction, when clicking, dragging, ... the display. A number of samples will be drawn from within the finger area and a best matching drawable will be chosen. The best matching algorithm will consider the size of the drawable and the distance from the touch point.
Parameters
[in] size the size of the finger.
    {
        fingerSize = size;
    }
References HAL::fingerSize.
setFrameBufferAllocator()
void setFrameBufferAllocator (FrameBufferAllocator * allocator) inline
Sets a framebuffer allocator. The framebuffer allocator is only used in partial framebuffer mode.
Parameters
[in] allocator pointer to a framebuffer allocator object.
    {
        frameBufferAllocator = allocator;
    }
References HAL::frameBufferAllocator.
setFrameBufferSize()
virtual void setFrameBufferSize (uint16_t width, uint16_t height) inline virtual
Sets framebuffer size. By default the display size and the framebuffer size are the same, but in some hardware configurations, the hardware may have a width of e.g. 832 pixels even though the display is only 800 pixels wide. First set the display width and height using touchgfx_generic_init() and the update the framebuffer size using setFrameBufferSize().
Parameters
width The width of the framebuffer.
height The height of the framebuffer.
See also
touchgfx_generic_init
Reimplemented in HALSDL2.
    {
        assert(width >= DISPLAY_WIDTH && height >= DISPLAY_HEIGHT && "Framebuffer cannot be smaller than display");
        FRAME_BUFFER_WIDTH = width;
        FRAME_BUFFER_HEIGHT = height;
    }
References HAL::DISPLAY_HEIGHT, HAL::DISPLAY_WIDTH, HAL::FRAME_BUFFER_HEIGHT, and HAL::FRAME_BUFFER_WIDTH.
Referenced by HALSDL2::setFrameBufferSize().
setFrameBufferStartAddresses()
virtual void setFrameBufferStartAddresses (void * frameBuffer, void * doubleBuffer, void * animationStorage) inline virtual
Sets framebuffer start addresses.
Sets individual framebuffer start addresses.
Parameters
[in] frameBuffer Buffer for framebuffer data, must be non-null.
[in] doubleBuffer If non-null, buffer for double buffer data. If null double buffering is disabled.
[in] animationStorage If non-null, the animation storage. If null animation storage is disabled.
See also
setAnimationStorage
    {
        assert(frameBuffer != 0 && "A framebuffer address must be set");
        frameBuffer0 = reinterpret_cast<uint16_t*>(frameBuffer);
        frameBuffer1 = reinterpret_cast<uint16_t*>(doubleBuffer);
        USE_DOUBLE_BUFFERING = doubleBuffer != 0;
        setAnimationStorage(animationStorage);
    }
References HAL::frameBuffer0, HAL::frameBuffer1, HAL::setAnimationStorage(), and HAL::USE_DOUBLE_BUFFERING.
Referenced by TouchGFXGeneratedHAL::initialize(), and HALSDL2::setFrameBufferSize().
setFrameRateCompensation()
void setFrameRateCompensation (bool enabled) inline
Enables or disables compensation for lost frames. See knowledge base article.
Parameters
enabled true to enable, false to disable.
    {
        vSyncCompensationEnabled = enabled;
    }
References HAL::vSyncCompensationEnabled.
setFrameRefreshStrategy()
bool setFrameRefreshStrategy (FrameRefreshStrategy s) inline
Set a specific strategy for handling timing and mechanism of framebuffer drawing.
By setting a different frame refresh strategy, the internals of how TouchGFX interacts with the framebuffer can be modified.
Currently there are two strategies available. This will increase over time.
REFRESH_STRATEGY_OPTIM_SINGLE_BUFFER_TFT_CTRL: this strategy is available on targets that use single buffering on a TFT controller based system. It requires an implementation of the getTFTCurrentLine() function as well as a task delay function being registered. The implementation of this strategy is that TouchGFX will carefully track the progress of the TFT controller, and draw parts of the framebuffer whenever possible. The effect is that the risk of tearing is much reduced compared to the default single buffer strategy of only drawing in porch areas. It does have a drawback of slightly increased MCU load. But in many cases employing this strategy will make it possible to avoid external RAM, by using just a single framebuffer in internal RAM and still avoid tearing.
REFRESH_STRATEGY_DEFAULT: This is a general strategy that works for all target configurations.
Recommendation: Try using REFRESH_STRATEGY_OPTIM_SINGLE_BUFFER_TFT_CTRL if you're on a TFT controller based system (ie. non-8080) and you have a desire to avoid external RAM. Otherwise stick to REFRESH_STRATEGY_DEFAULT.
Parameters
s The desired strategy to use.
Returns
true if the desired strategy will be used, false otherwise.
    {
        if (s == REFRESH_STRATEGY_DEFAULT || s == REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER)
        {
            refreshStrategy = s;
            return true;
        }
        if (s == REFRESH_STRATEGY_OPTIM_SINGLE_BUFFER_TFT_CTRL)
        {
            // Perform sanity checks. This strategy requires
            //   - task delay function
            //   - a TFT controller (+ an impl of getTFTCurrentLine())
            //   - single buffering
            if (taskDelayFunc != 0 && getTFTCurrentLine() != 0xFFFF && !USE_DOUBLE_BUFFERING)
            {
                refreshStrategy = s;
                return true;
            }
            return false;
        }
        // Unknown strategy
        return false;
    }
References HAL::getTFTCurrentLine(), HAL::REFRESH_STRATEGY_DEFAULT, HAL::REFRESH_STRATEGY_OPTIM_SINGLE_BUFFER_TFT_CTRL, HAL::REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER, HAL::refreshStrategy, HAL::taskDelayFunc, and HAL::USE_DOUBLE_BUFFERING.
setMCUActive()
void setMCUActive (bool active)
Register if MCU is active by measuring cpu cycles. If user wishes to track MCU load, this method should be called whenever the OS Idle task is scheduled in or out. This method makes calls to a concrete implementation of GPIO functionality and a concrete implementation of cpu cycles.
Parameters
active If true, MCU is registered as being active, inactive otherwise.
setMCUInstrumentation()
void setMCUInstrumentation (MCUInstrumentation * mcuInstr) inline
Stores a pointer to an instance of an MCU specific instrumentation class.
Parameters
[in] mcuInstr pointer to MCU instrumentation.
    {
        mcuInstrumentation = mcuInstr;
    }
References HAL::mcuInstrumentation.
setRenderingMethod()
void setRenderingMethod (RenderingMethod method)
Set current rendering method for cache maintenance.
This function is used to keep track of previous rendering method and will determine if cache should be flush or invalidated depending on transition state.
Parameters
method The rendering method used.
setTFTFrameBuffer()
virtual void setTFTFrameBuffer (uint16_t * address) protected pure virtual
Sets the framebuffer address used by the TFT controller.
Parameters
[in] address New framebuffer address.
Implemented in HALSDL2, TouchGFXGeneratedHAL, and TouchGFXHAL.
setTouchSampleRate()
void setTouchSampleRate (int8_t sampleRateInTicks) inline
Sets the number of ticks between each touch screen sample.
Parameters
sampleRateInTicks Sample rate. Default is 1 (every tick).
    {
        if (sampleRateInTicks > 0)
        {
            touchSampleRate = sampleRateInTicks;
        }
    }
References HAL::touchSampleRate.
signalDMAInterrupt()
void signalDMAInterrupt () inline
Notify the framework that a DMA interrupt has occurred.
    {
        dma.signalDMAInterrupt();
    }
References HAL::dma, and DMA_Interface::signalDMAInterrupt().
swapFrameBuffers()
void swapFrameBuffers ()
Swaps the two framebuffers.
Referenced by HAL::backPorchExited().
taskDelay()
virtual void taskDelay (uint16_t ms) inline virtual
Delay GUI task execution by number of milliseconds
This function requires the presence of a task delay function. If a task delay function has not been registered, it returns immediately. Otherwise it returns when number of milliseconds has passed.
Parameters
ms Number of milliseconds to wait.
See also
registerTaskDelayFunction
    {
        if (taskDelayFunc)
        {
            taskDelayFunc(ms);
        }
    }
References HAL::taskDelayFunc.
taskEntry()
virtual void taskEntry () virtual
Main event loop. Will wait for VSYNC signal, and then process next frame. Call this function from your GUI task.
Note
This function never returns!
Reimplemented in HALSDL2.
tick()
virtual void tick () protected virtual
This function is called at each timer tick, depending on platform implementation.
Referenced by HAL::backPorchExited().
touch()
virtual void touch (int32_t x, int32_t y) protected virtual
Called by the touch driver to indicate a touch.
Parameters
x The x coordinate of the touch.
y The y coordinate of the touch.
unlockFrameBuffer()
virtual void unlockFrameBuffer () virtual
Unlocks the framebuffer (MUST be called exactly once for each call to lockFrameBuffer()).
Reimplemented in TouchGFXGeneratedHAL.
vSync()
void vSync () inline
Called by the VSync interrupt.
Called by the VSync interrupt for counting of LCD refreshes.
    {
        vSyncCnt++;
    }
References HAL::vSyncCnt.
Referenced by HALSDL2::taskEntry().
Member Data Documentation
auxiliaryLCD
LCD* auxiliaryLCD protected
Auxiliary LCD class used to render Drawables into dynamic bitmaps.
Referenced by HAL::getAuxiliaryLCD(), and HAL::setAuxiliaryLCD().
buttonController
ButtonController* buttonController protected
A reference to an optional ButtonController.
Referenced by HAL::getButtonController(), and HAL::setButtonController().
cc_begin
uint32_t cc_begin private
clientDirty
bool clientDirty private
DISPLAY_HEIGHT
uint16_t DISPLAY_HEIGHT static
The height of the LCD display in pixels.
Referenced by BlockTransition::BlockTransition(), CoverTransition< templateDirection >::CoverTransition(), HAL::HAL(), ModalWindow::ModalWindow(), SlideTransition< templateDirection >::SlideTransition(), WipeTransition< templateDirection >::WipeTransition(), HALSDL2::copyScreenshotToClipboard(), HALSDL2::doRotate(), HALSDL2::flushFrameBuffer(), HAL::getDisplayHeight(), Screen::getScreenHeight(), CoverTransition< templateDirection >::handleTickEvent(), WipeTransition< templateDirection >::handleTickEvent(), HAL::performDisplayOrientationChange(), HALSDL2::recreateWindow(), HALSDL2::renderLCD_FrameBufferToMemory(), HAL::setFrameBufferSize(), and HALSDL2::taskEntry().
DISPLAY_ROTATION
DisplayRotation DISPLAY_ROTATION static
The rotation from display to framebuffer.
Referenced by HAL::HAL(), HALSDL2::doRotate(), HALSDL2::doSampleTouch(), CanvasWidget::draw(), ScalableImage::draw(), TextureMapper::draw(), AbstractPainter::framebufferToDisplay(), HAL::getDisplayOrientation(), HAL::performDisplayOrientationChange(), Canvas::transformFrameBufferToDisplay(), and AbstractPainterBitmap::updateBitmapOffsets().
DISPLAY_WIDTH
uint16_t DISPLAY_WIDTH static
The width of the LCD display in pixels.
Referenced by BlockTransition::BlockTransition(), CoverTransition< templateDirection >::CoverTransition(), HAL::HAL(), ModalWindow::ModalWindow(), SlideTransition< templateDirection >::SlideTransition(), WipeTransition< templateDirection >::WipeTransition(), HALSDL2::copyScreenshotToClipboard(), HALSDL2::doRotate(), HALSDL2::doSampleTouch(), HALSDL2::flushFrameBuffer(), HAL::getDisplayWidth(), Screen::getScreenWidth(), CoverTransition< templateDirection >::handleTickEvent(), WipeTransition< templateDirection >::handleTickEvent(), HAL::performDisplayOrientationChange(), HALSDL2::recreateWindow(), HALSDL2::renderLCD_FrameBufferToMemory(), HAL::setFrameBufferSize(), and HALSDL2::taskEntry().
displayOrientationChangeRequested
bool displayOrientationChangeRequested private
Referenced by HAL::setDisplayOrientation().
dma
DMA_Interface& dma protected
A reference to the DMA interface.
Referenced by TouchGFXGeneratedHAL::endFrame(), HAL::getBlitCaps(), HAL::getDMAType(), TouchGFXGeneratedHAL::initialize(), HAL::signalDMAInterrupt(), and TouchGFXGeneratedHAL::unlockFrameBuffer().
fingerSize
uint8_t fingerSize protected
The radius of the finger in pixels.
Referenced by HAL::getFingerSize(), and HAL::setFingerSize().
FRAME_BUFFER_HEIGHT
uint16_t FRAME_BUFFER_HEIGHT static
The height of the framebuffer in pixels.
Referenced by HAL::HAL(), HALSDL2::sdl_init(), HALSDL2::setFrameBufferSize(), and HAL::setFrameBufferSize().
FRAME_BUFFER_WIDTH
uint16_t FRAME_BUFFER_WIDTH static
The width of the framebuffer in pixels.
Referenced by HAL::HAL(), DirectFrameBufferVideoController< no_streams, output_format >::draw(), TextureMapper::drawQuad(), LCD16bpp::getFramebufferStride(), LCD16bppSerialFlash::getFramebufferStride(), LCD1bpp::getFramebufferStride(), LCD24bpp::getFramebufferStride(), LCD2bpp::getFramebufferStride(), LCD32bpp::getFramebufferStride(), LCD32bpp_XRGB8888::getFramebufferStride(), LCD4bpp::getFramebufferStride(), LCD8bpp_ABGR2222::getFramebufferStride(), LCD8bpp_ARGB2222::getFramebufferStride(), LCD8bpp_BGRA2222::getFramebufferStride(), LCD8bpp_RGBA2222::getFramebufferStride(), HALSDL2::sdl_init(), HALSDL2::setFrameBufferSize(), HAL::setFrameBufferSize(), and HALSDL2::updateTitle().
frameBuffer0
uint16_t* frameBuffer0 protected
Pointer to the first framebuffer.
Referenced by HAL::getClientFrameBuffer(), and HAL::setFrameBufferStartAddresses().
frameBuffer1
uint16_t* frameBuffer1 protected
Pointer to the second framebuffer.
Referenced by HAL::getClientFrameBuffer(), and HAL::setFrameBufferStartAddresses().
frameBuffer2
uint16_t* frameBuffer2 protected
Pointer to the optional third framebuffer used for animation storage.
Referenced by HAL::getAnimationStorage(), and HAL::setAnimationStorage().
frameBufferAllocator
FrameBufferAllocator* frameBufferAllocator protected
A reference to an optional FrameBufferAllocator.
Referenced by HALSDL2::flushFrameBuffer(), HAL::getFrameBufferAllocator(), HAL::setFrameBufferAllocator(), and HALSDL2::setTFTFrameBuffer().
frameBufferUpdatedThisFrame
bool frameBufferUpdatedThisFrame protected
True if something was drawn in the current frame.
gestures
Gestures gestures protected
Class for low-level interpretation of touch events.
Referenced by HAL::getGestures(), and HAL::setDragThreshold().
instance
HAL* instance static private
Referenced by HAL::HAL(), HAL::getInstance(), and HAL::lcd().
isDrawing
bool isDrawing static protected
True if currently in the process of rendering a screen.
lastRenderMethod
RenderingMethod lastRenderMethod private
lastTouched
bool lastTouched private
lastX
int32_t lastX private
lastY
int32_t lastY private
lcdRef
LCD& lcdRef protected
A reference to the LCD.
listener
UIEventListener* listener private
lockDMAToPorch
bool lockDMAToPorch protected
Whether or not to lock DMA transfers with TFT porch signal.
Referenced by HAL::lockDMAToFrontPorch().
mcuInstrumentation
MCUInstrumentation* mcuInstrumentation protected
A reference to an optional MCU instrumentation.
Referenced by HAL::setMCUInstrumentation().
mcuLoadPct
uint8_t mcuLoadPct private
Referenced by HAL::getMCULoadPct().
nativeDisplayOrientation
DisplayOrientation nativeDisplayOrientation protected
Contains the native display orientation. If desired orientation is different, apply rotation.
Referenced by HAL::HAL(), HAL::getDisplayOrientation(), and HAL::performDisplayOrientationChange().
partialFrameBufferRect
Rect partialFrameBufferRect protected
The region of the screen covered by the partial framebuffer.
refreshStrategy
FrameRefreshStrategy refreshStrategy protected
The selected display refresh strategy.
Referenced by HAL::getFrameRefreshStrategy(), and HAL::setFrameRefreshStrategy().
requestedOrientation
DisplayOrientation requestedOrientation private
Referenced by HAL::performDisplayOrientationChange(), and HAL::setDisplayOrientation().
swapRequested
bool swapRequested private
taskDelayFunc
void(* taskDelayFunc) (uint16_t) protected
Pointer to a function that can delay GUI task for a number of milliseconds.
Referenced by HAL::registerTaskDelayFunction(), HAL::setFrameRefreshStrategy(), and HAL::taskDelay().
touchController
TouchController& touchController protected
A reference to the touch controller.
touchSampleRate
int8_t touchSampleRate private
Referenced by HAL::getTouchSampleRate(), and HAL::setTouchSampleRate().
updateMCULoad
bool updateMCULoad private
Referenced by HAL::enableMCULoadCalculation().
USE_ANIMATION_STORAGE
bool USE_ANIMATION_STORAGE static
Is animation storage enabled?
Referenced by SlideTransition< templateDirection >::SlideTransition(), HALSDL2::sdl_init(), HAL::setAnimationStorage(), HALSDL2::setFrameBufferSize(), and SlideTransition< templateDirection >::tearDown().
USE_DOUBLE_BUFFERING
bool USE_DOUBLE_BUFFERING static
Is double buffering enabled?
Referenced by HAL::getClientFrameBuffer(), BlockTransition::handleTickEvent(), CoverTransition< templateDirection >::handleTickEvent(), WipeTransition< templateDirection >::handleTickEvent(), HALSDL2::sdl_init(), HALSDL2::setFrameBufferSize(), HAL::setFrameBufferStartAddresses(), and HAL::setFrameRefreshStrategy().
useAuxiliaryLCD
bool useAuxiliaryLCD protected
True if using another LCD than the hardware framebuffer.
useDMAAcceleration
bool useDMAAcceleration private
Referenced by HAL::enableDMAAcceleration(), and HAL::getBlitCaps().
vSyncCnt
uint8_t vSyncCnt private
Referenced by HAL::vSync().
vSyncCompensationEnabled
bool vSyncCompensationEnabled private
Referenced by HAL::setFrameRateCompensation().
vSyncForFrame
uint8_t vSyncForFrame private
Referenced by HAL::getLCDRefreshCount().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/hal/HAL.hpp