Battery Simulator Documentation: SlideMenu
SlideMenu
#include "SlideMenu.hpp"
Public Types
enum ExpandDirection { SOUTH , NORTH , EAST , WEST }
enum State { COLLAPSED , EXPANDED }
Public Member Functions
SlideMenu ()
virtual ~SlideMenu ()
virtual void add (Drawable &d)
virtual void animateToState (State newState)
virtual uint16_t getAnimationDuration () const
virtual EasingEquation getAnimationEasingEquation () const
virtual int16_t getBackgroundX () const
virtual int16_t getBackgroundY () const
virtual ExpandDirection getExpandDirection () const
virtual uint16_t getExpandedStateTimeout () const
virtual uint16_t getExpandedStateTimer () const
virtual int16_t getHiddenPixelsWhenExpanded () const
virtual State getState ()
virtual int16_t getStateChangeButtonX () const
virtual int16_t getStateChangeButtonY () const
virtual int16_t getVisiblePixelsWhenCollapsed () const
virtual void handleTickEvent ()
virtual void remove (Drawable &d)
virtual void resetExpandedStateTimer ()
virtual void setAnimationDuration (uint16_t duration)
virtual void setAnimationEasingEquation (EasingEquation animationEasingEquation)
virtual void setExpandDirection (ExpandDirection newExpandDirection)
virtual void setExpandedStateTimeout (uint16_t timeout)
virtual void setHiddenPixelsWhenExpanded (int16_t hiddenPixels)
virtual void setState (State newState)
virtual void setStateChangedAnimationEndedCallback (GenericCallback< const SlideMenu & > &callback)
virtual void setStateChangedCallback (GenericCallback< const SlideMenu & > &callback)
virtual void setup (ExpandDirection newExpandDirection, const Bitmap &backgroundBMP, const Bitmap &stateChangeButtonBMP, const Bitmap &stateChangeButtonPressedBMP)
virtual void setup (ExpandDirection newExpandDirection, const Bitmap &backgroundBMP, const Bitmap &stateChangeButtonBMP, const Bitmap &stateChangeButtonPressedBMP, int16_t backgroundX, int16_t backgroundY, int16_t stateChangeButtonX, int16_t stateChangeButtonY)
virtual void setup (ExpandDirection newExpandDirection, const Bitmap &backgroundBMP, int16_t backgroundX, int16_t backgroundY)
virtual void setVisiblePixelsWhenCollapsed (int16_t visiblePixels)
Public Member Functions inherited from Container
Container ()
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
void animationEndedHandler (const MoveAnimator< Container > &container)
virtual int16_t getCollapsedXCoordinate ()
virtual int16_t getCollapsedYCoordinate ()
virtual int16_t getExpandedXCoordinate ()
virtual int16_t getExpandedYCoordinate ()
void stateChangeButtonClickedHandler (const AbstractButton &button)
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
uint16_t animationDuration
The animation duration of the state change animation.
Callback< SlideMenu, const MoveAnimator< Container > & > animationEndedCallback
The local state changed animation ended callback.
EasingEquation animationEquation
The easing equation used for the state change animation.
Image background
The background of the SlideMenu.
State currentState
The current state of the SlideMenu.
ExpandDirection expandDirection
The expand direction of the SlideMenu.
uint16_t expandedStateTimeout
The expanded state timeout.
uint16_t expandedStateTimer
The timer that counts towards the expandedStateTimeout. If reached the SlideMenu will animate to COLLAPSED.
int16_t hiddenPixelsWhenExpanded
The number of hidden pixels when expanded.
MoveAnimator< Container > menuContainer
The container holding the actual menu items. This is the container that performs the state change animation.
Callback< SlideMenu, const AbstractButton & > onStateChangeButtonClicked
The local state changed button clicked callback.
Button stateChangeButton
The state change button that toggles the SlideMenu state.
GenericCallback< const SlideMenu & > * stateChangedAnimationEndedCallback
The public state changed animation ended callback.
GenericCallback< const SlideMenu & > * stateChangedCallback
The public state changed button clicked callback.
int16_t visiblePixelsWhenCollapsed
The number of visible pixels when collapsed.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
SlideMenu is a menu that can expand and collapse at the touch of a button. The SlideMenu can expand in any of the four directions. Menu items can be added, just like items are added to a normal container.
The relative positions of the background and state change button is configurable as is the direction in which the SlideMenu expands and collapses. How much of the SlideMenu that is visible when collapsed can also be set with the. It is, of course, important that the state change button is accessible when collapsed. The SlideMenu will collapse after a given timeout is reached. The timer can be reset, for example when the user interacts with elements in the list.
Menu elements are added normally using the add() method and are positioned relative to the SlideMenu.
Member Enumeration Documentation
ExpandDirection
enum ExpandDirection
Values that represent the expand directions.
Enumerator
SOUTH
Menu expands downwards (Towards the south)
NORTH
Menu expands upwards (Towards the north)
EAST
Menu expands to the right (Towards the east)
WEST
Menu expands to the left (Towards the west)
    {
        SOUTH,
        NORTH,
        EAST,
        WEST
    };
State
enum State
Values that represent the SlideMenu states.
Enumerator
COLLAPSED
Menu is currently collapsed.
EXPANDED
Menu is currently expanded.
    {
        COLLAPSED,
        EXPANDED
    };
Constructor & Destructor Documentation
SlideMenu()
SlideMenu ()
    : Container(),
      menuContainer(),
      stateChangeButton(),
      background(),
      onStateChangeButtonClicked(this, &SlideMenu::stateChangeButtonClickedHandler),
      animationEndedCallback(this, &SlideMenu::animationEndedHandler),
      stateChangedCallback(0),
      stateChangedAnimationEndedCallback(0),
      currentState(COLLAPSED),
      expandDirection(EAST),
      animationEquation(EasingEquations::cubicEaseInOut),
      visiblePixelsWhenCollapsed(0),
      hiddenPixelsWhenExpanded(0),
      expandedStateTimeout(200),
      expandedStateTimer(0),
      animationDuration(10)
{
    Application::getInstance()->registerTimerWidget(this);
    stateChangeButton.setAction(onStateChangeButtonClicked);
    menuContainer.setMoveAnimationEndedAction(animationEndedCallback);
    Container::add(menuContainer);
    menuContainer.add(background);
    menuContainer.add(stateChangeButton);
}
References Container::add(), SlideMenu::animationEndedCallback, SlideMenu::background, Application::getInstance(), SlideMenu::menuContainer, SlideMenu::onStateChangeButtonClicked, AbstractButton::setAction(), and SlideMenu::stateChangeButton.
~SlideMenu()
~SlideMenu () virtual
{
    Application::getInstance()->unregisterTimerWidget(this);
}
References Application::getInstance().
Member Function Documentation
add()
void add (Drawable & d) virtual
Adds a drawable to the container. Make sure the x and y coordinates of the Drawable is correct relative to the SlideMenu.
Parameters
[in] d The drawable to add.
Reimplemented from Container.
{
    menuContainer.add(d);
}
References SlideMenu::menuContainer.
animateToState()
void animateToState (State newState) virtual
Animate to the given expanded or collapsed state.
Parameters
newState The new state of the SlideMenu.
See also
setState, getState
{
    if (animationDuration == 0)
    {
        setState(newState);
    }
    else if (newState != currentState)
    {
        if (currentState == COLLAPSED)
        {
            menuContainer.startMoveAnimation(getExpandedXCoordinate(), getExpandedYCoordinate(), animationDuration, animationEquation, animationEquation);
            currentState = EXPANDED;
        }
        else
        {
            menuContainer.startMoveAnimation(getCollapsedXCoordinate(), getCollapsedYCoordinate(), animationDuration, animationEquation, animationEquation);
            currentState = COLLAPSED;
        }
        // Disable stateChangeButton while animating
        stateChangeButton.setTouchable(false);
    }
}
References SlideMenu::animationDuration, SlideMenu::animationEquation, SlideMenu::COLLAPSED, SlideMenu::currentState, SlideMenu::EXPANDED, SlideMenu::getCollapsedXCoordinate(), SlideMenu::getCollapsedYCoordinate(), SlideMenu::getExpandedXCoordinate(), SlideMenu::getExpandedYCoordinate(), SlideMenu::menuContainer, SlideMenu::setState(), Drawable::setTouchable(), and SlideMenu::stateChangeButton.
Referenced by SlideMenu::handleTickEvent(), and SlideMenu::stateChangeButtonClickedHandler().
animationEndedHandler()
void animationEndedHandler (const MoveAnimator< Container > & container) protected
Handler for the state change animation ended event.
Parameters
container The menuContainer.
{
    resetExpandedStateTimer();
    stateChangeButton.setTouchable(true);
    if ((stateChangedAnimationEndedCallback != 0) && stateChangedAnimationEndedCallback->isValid())
    {
        stateChangedAnimationEndedCallback->execute(*this);
    }
}
References SlideMenu::resetExpandedStateTimer(), Drawable::setTouchable(), SlideMenu::stateChangeButton, and SlideMenu::stateChangedAnimationEndedCallback.
getAnimationDuration()
uint16_t getAnimationDuration () const virtual
Gets the animation duration.
Returns
The animation duration.
{
    return animationDuration;
}
References SlideMenu::animationDuration.
getAnimationEasingEquation()
EasingEquation getAnimationEasingEquation () const virtual
Gets the animation easing equation.
Returns
The animation easing equation.
{
    return animationEquation;
}
References SlideMenu::animationEquation.
getBackgroundX()
int16_t getBackgroundX () const virtual
Gets the background Image x coordinate.
Returns
The background Image x coordinate.
{
    return background.getX();
}
References SlideMenu::background, and Drawable::getX().
getBackgroundY()
int16_t getBackgroundY () const virtual
Gets the background Image y coordinate.
Returns
The background Image y coordinate.
{
    return background.getY();
}
References SlideMenu::background, and Drawable::getY().
getCollapsedXCoordinate()
int16_t getCollapsedXCoordinate () protected virtual
Gets the x coordinate for the collapsed state.
Returns
The collapsed x coordinate.
{
    switch (expandDirection)
    {
    case EAST:
        return -menuContainer.getWidth() + visiblePixelsWhenCollapsed;
    case WEST:
        return getWidth() - visiblePixelsWhenCollapsed;
    case SOUTH:
    case NORTH:
        break;
    }
    return 0;
}
References SlideMenu::EAST, SlideMenu::expandDirection, Drawable::getWidth(), SlideMenu::menuContainer, SlideMenu::NORTH, SlideMenu::SOUTH, SlideMenu::visiblePixelsWhenCollapsed, and SlideMenu::WEST.
Referenced by SlideMenu::animateToState(), and SlideMenu::setState().
getCollapsedYCoordinate()
int16_t getCollapsedYCoordinate () protected virtual
Gets the y coordinate for the collapsed state.
Returns
The collapsed y coordinate.
{
    switch (expandDirection)
    {
    case SOUTH:
        return -menuContainer.getHeight() + visiblePixelsWhenCollapsed;
    case NORTH:
        return getHeight() - visiblePixelsWhenCollapsed;
    case EAST:
    case WEST:
        break;
    }
    return 0;
}
References SlideMenu::EAST, SlideMenu::expandDirection, Drawable::getHeight(), SlideMenu::menuContainer, SlideMenu::NORTH, SlideMenu::SOUTH, SlideMenu::visiblePixelsWhenCollapsed, and SlideMenu::WEST.
Referenced by SlideMenu::animateToState(), and SlideMenu::setState().
getExpandDirection()
SlideMenu::ExpandDirection getExpandDirection () const virtual
Gets the expand direction.
Returns
The expand direction.
{
    return expandDirection;
}
References SlideMenu::expandDirection.
getExpandedStateTimeout()
uint16_t getExpandedStateTimeout () const virtual
Gets expanded state timeout.
Returns
The expanded state timeout.
{
    return expandedStateTimeout;
}
References SlideMenu::expandedStateTimeout.
getExpandedStateTimer()
uint16_t getExpandedStateTimer () const virtual
Gets the expanded state timer.
Returns
The expanded state timer.
See also
resetExpandedStateTimer
{
    return expandedStateTimer;
}
References SlideMenu::expandedStateTimer.
getExpandedXCoordinate()
int16_t getExpandedXCoordinate () protected virtual
Gets the x coordinate for the expanded state.
Returns
The expanded x coordinate.
{
    switch (expandDirection)
    {
    case EAST:
        return -hiddenPixelsWhenExpanded;
    case WEST:
        return hiddenPixelsWhenExpanded;
    case SOUTH:
    case NORTH:
        break;
    }
    return 0;
}
References SlideMenu::EAST, SlideMenu::expandDirection, SlideMenu::hiddenPixelsWhenExpanded, SlideMenu::NORTH, SlideMenu::SOUTH, and SlideMenu::WEST.
Referenced by SlideMenu::animateToState(), and SlideMenu::setState().
getExpandedYCoordinate()
int16_t getExpandedYCoordinate () protected virtual
Gets the y coordinate for the expanded state.
Returns
The expanded y coordinate.
{
    switch (expandDirection)
    {
    case SOUTH:
        return -hiddenPixelsWhenExpanded;
    case NORTH:
        return hiddenPixelsWhenExpanded;
    case EAST:
    case WEST:
        break;
    }
    return 0;
}
References SlideMenu::EAST, SlideMenu::expandDirection, SlideMenu::hiddenPixelsWhenExpanded, SlideMenu::NORTH, SlideMenu::SOUTH, and SlideMenu::WEST.
Referenced by SlideMenu::animateToState(), and SlideMenu::setState().
getHiddenPixelsWhenExpanded()
int16_t getHiddenPixelsWhenExpanded () const virtual
Gets the hidden pixels when expanded.
Returns
The hidden pixels when expanded.
{
    return hiddenPixelsWhenExpanded;
}
References SlideMenu::hiddenPixelsWhenExpanded.
getState()
SlideMenu::State getState () virtual
Gets the current expanded or collapsed state.
Returns
The current state.
See also
setState, animateToState
{
    return currentState;
}
References SlideMenu::currentState.
getStateChangeButtonX()
int16_t getStateChangeButtonX () const virtual
Gets the state change button x coordinate.
Returns
The state change button x coordinate.
{
    return stateChangeButton.getX();
}
References Drawable::getX(), and SlideMenu::stateChangeButton.
getStateChangeButtonY()
int16_t getStateChangeButtonY () const virtual
Gets the state change button y coordinate.
Returns
The state change button y coordinate.
{
    return stateChangeButton.getY();
}
References Drawable::getY(), and SlideMenu::stateChangeButton.
getVisiblePixelsWhenCollapsed()
int16_t getVisiblePixelsWhenCollapsed () const virtual
Gets the visible pixels when collapsed.
Returns
The visible pixels when collapsed.
{
    return visiblePixelsWhenCollapsed;
}
References SlideMenu::visiblePixelsWhenCollapsed.
handleTickEvent()
void handleTickEvent () virtual
Called periodically by the framework if the Drawable instance has subscribed to timer ticks.
See also
Application::registerTimerWidget
Reimplemented from Drawable.
{
    if ((expandedStateTimeout != 0) && (currentState == EXPANDED) && !menuContainer.isMoveAnimationRunning())
    {
        expandedStateTimer++;
        if (expandedStateTimer > expandedStateTimeout)
        {
            animateToState(COLLAPSED);
        }
    }
}
References SlideMenu::animateToState(), SlideMenu::COLLAPSED, SlideMenu::currentState, SlideMenu::EXPANDED, SlideMenu::expandedStateTimeout, SlideMenu::expandedStateTimer, and SlideMenu::menuContainer.
remove()
void remove (Drawable & d) virtual
Removes the drawable from the container.
Parameters
[in] d The drawable to remove.
Reimplemented from Container.
{
    menuContainer.remove(d);
}
References SlideMenu::menuContainer.
resetExpandedStateTimer()
void resetExpandedStateTimer () virtual
Resets the expanded state timer. The SlideMenu will automatically animate to the COLLAPSED state after a number of ticks, as set with setExpandedStateTimeout(). This method resets this timer.
See also
getExpandedStateTimer
{
    expandedStateTimer = 0;
}
References SlideMenu::expandedStateTimer.
Referenced by SlideMenu::animationEndedHandler().
setAnimationDuration()
void setAnimationDuration (uint16_t duration) virtual
Sets the animation duration.
Parameters
duration The animation duration.
{
    animationDuration = duration;
}
References SlideMenu::animationDuration.
setAnimationEasingEquation()
void setAnimationEasingEquation (EasingEquation animationEasingEquation) virtual
Sets the animation easing equation.
Parameters
animationEasingEquation The animation easing equation.
{
    animationEquation = animationEasingEquation;
}
References SlideMenu::animationEquation.
setExpandDirection()
void setExpandDirection (ExpandDirection newExpandDirection) virtual
Sets the expand direction.
Parameters
newExpandDirection The new expand direction.
{
    expandDirection = newExpandDirection;
    setState(currentState);
}
References SlideMenu::currentState, SlideMenu::expandDirection, and SlideMenu::setState().
Referenced by SlideMenu::setup(), and SlideMenu::setup().
setExpandedStateTimeout()
void setExpandedStateTimeout (uint16_t timeout) virtual
Sets the expanded state timeout in ticks. The SlideMenu will animate to the COLLAPSED state when this number of ticks has been executed while the SlideMenu is in the EXPANDED state. The timer can be reset with the resetExpandedStateTimer method.
Parameters
timeout The timeout in ticks.
{
    expandedStateTimeout = timeout;
}
References SlideMenu::expandedStateTimeout.
setHiddenPixelsWhenExpanded()
void setHiddenPixelsWhenExpanded (int16_t hiddenPixels) virtual
Sets the amount of hidden pixels when expanded.
Parameters
hiddenPixels The hidden pixels.
{
    hiddenPixelsWhenExpanded = hiddenPixels;
    setState(currentState);
}
References SlideMenu::currentState, SlideMenu::hiddenPixelsWhenExpanded, and SlideMenu::setState().
setState()
void setState (State newState) virtual
Sets the state of the SlideMenu. No animation is performed.
Parameters
newState The new state of the SlideMenu.
See also
animateToState, getState
{
    if (newState == COLLAPSED)
    {
        menuContainer.moveTo(getCollapsedXCoordinate(), getCollapsedYCoordinate());
    }
    else
    {
        menuContainer.moveTo(getExpandedXCoordinate(), getExpandedYCoordinate());
    }
    currentState = newState;
}
References SlideMenu::COLLAPSED, SlideMenu::currentState, SlideMenu::getCollapsedXCoordinate(), SlideMenu::getCollapsedYCoordinate(), SlideMenu::getExpandedXCoordinate(), SlideMenu::getExpandedYCoordinate(), and SlideMenu::menuContainer.
Referenced by SlideMenu::animateToState(), SlideMenu::setExpandDirection(), SlideMenu::setHiddenPixelsWhenExpanded(), SlideMenu::setup(), SlideMenu::setup(), and SlideMenu::setVisiblePixelsWhenCollapsed().
setStateChangedAnimationEndedCallback()
void setStateChangedAnimationEndedCallback (GenericCallback< const SlideMenu & > & callback) virtual
Set the state change animation ended callback. This callback is called when a state change animation has ended.
Parameters
callback The callback.
{
    stateChangedAnimationEndedCallback = &callback;
}
References SlideMenu::stateChangedAnimationEndedCallback.
setStateChangedCallback()
void setStateChangedCallback (GenericCallback< const SlideMenu & > & callback) virtual
Set the state changed callback. This callback is called when the state change button is clicked.
Parameters
callback The callback.
{
    stateChangedCallback = &callback;
}
References SlideMenu::stateChangedCallback.
setup() [1/3]
void setup (ExpandDirection newExpandDirection, const Bitmap & backgroundBMP, const Bitmap & stateChangeButtonBMP, const Bitmap & stateChangeButtonPressedBMP) virtual
Setup the SlideMenu by positioning the stateChangeButton next to background image relative to the expand direction, and center it in the other dimension. The width and height of the SlideMenu will be automatically set to span both elements. Default values are: expandedStateTimeout = 200, visiblePixelsWhenCollapsed = 0, hiddenPixelsWhenExpanded = 0, animationDuration = 10, animationEquation = cubicEaseInOut.
Parameters
newExpandDirection The new expand direction.
backgroundBMP The background bitmap.
stateChangeButtonBMP The state change button bitmap.
stateChangeButtonPressedBMP The state change button pressed bitmap.
{
    int16_t backgroundX = 0;
    int16_t backgroundY = 0;
    int16_t buttonX = 0;
    int16_t buttonY = 0;
    switch (newExpandDirection)
    {
    case SOUTH:
        backgroundX = 0;
        backgroundY = 0;
        buttonX = (backgroundBMP.getWidth() - stateChangeButtonBMP.getWidth()) / 2;
        buttonY = backgroundBMP.getHeight();
        setVisiblePixelsWhenCollapsed(stateChangeButtonBMP.getHeight());
        break;
    case NORTH:
        backgroundX = 0;
        backgroundY = stateChangeButtonBMP.getHeight();
        buttonX = (backgroundBMP.getWidth() - stateChangeButtonBMP.getWidth()) / 2;
        buttonY = 0;
        setVisiblePixelsWhenCollapsed(stateChangeButtonBMP.getHeight());
        break;
    case EAST:
        backgroundX = 0;
        backgroundY = 0;
        buttonX = backgroundBMP.getWidth();
        buttonY = (backgroundBMP.getHeight() - stateChangeButtonBMP.getHeight()) / 2;
        setVisiblePixelsWhenCollapsed(stateChangeButtonBMP.getWidth());
        break;
    case WEST:
        backgroundX = stateChangeButtonBMP.getWidth();
        backgroundY = 0;
        buttonX = 0;
        buttonY = (backgroundBMP.getHeight() - stateChangeButtonBMP.getHeight()) / 2;
        setVisiblePixelsWhenCollapsed(stateChangeButtonBMP.getWidth());
        break;
    }
    setup(newExpandDirection, backgroundBMP, stateChangeButtonBMP, stateChangeButtonPressedBMP, backgroundX, backgroundY, buttonX, buttonY);
}
References SlideMenu::EAST, SlideMenu::NORTH, SlideMenu::setup(), SlideMenu::setVisiblePixelsWhenCollapsed(), SlideMenu::SOUTH, and SlideMenu::WEST.
Referenced by SlideMenu::setup().
setup() [2/3]
void setup (ExpandDirection newExpandDirection, const Bitmap & backgroundBMP, const Bitmap & stateChangeButtonBMP, const Bitmap & stateChangeButtonPressedBMP, int16_t backgroundX, int16_t backgroundY, int16_t stateChangeButtonX, int16_t stateChangeButtonY) virtual
Setup method for the SlideMenu. Positioning of the background image and the stateChangeButton is done by stating the X and Y coordinates for the elements (relative to the SlideMenu). The width and height of the SlideMenu will be automatically set to span both elements. Default values are: expandedStateTimeout = 200, visiblePixelsWhenCollapsed = 0, hiddenPixelsWhenExpanded = 0, animationDuration = 10, animationEquation = cubicEaseInOut.
Parameters
newExpandDirection The new expand direction.
backgroundBMP The background bitmap.
stateChangeButtonBMP The state change button bitmap.
stateChangeButtonPressedBMP The state change button pressed bitmap.
backgroundX The background x coordinate.
backgroundY The background y coordinate.
stateChangeButtonX The state change button x coordinate.
stateChangeButtonY The state change button y coordinate.
{
    setExpandDirection(newExpandDirection);
    background.setBitmap(backgroundBMP);
    background.setXY(backgroundX, backgroundY);
    stateChangeButton.setBitmaps(stateChangeButtonBMP, stateChangeButtonPressedBMP);
    stateChangeButton.setXY(stateChangeButtonX, stateChangeButtonY);
    Rect boundingRect;
    boundingRect.expandToFit(background.getRect());
    boundingRect.expandToFit(stateChangeButton.getRect());
    menuContainer.setWidth(boundingRect.right());
    menuContainer.setHeight(boundingRect.bottom());
    setWidthHeight(menuContainer);
    setExpandDirection(expandDirection);
    setState(currentState);
    invalidate();
}
References SlideMenu::background, SlideMenu::currentState, SlideMenu::expandDirection, Drawable::getRect(), Drawable::invalidate(), SlideMenu::menuContainer, Image::setBitmap(), Button::setBitmaps(), SlideMenu::setExpandDirection(), SlideMenu::setState(), Drawable::setWidthHeight(), Drawable::setXY(), and SlideMenu::stateChangeButton.
setup() [3/3]
void setup (ExpandDirection newExpandDirection, const Bitmap & backgroundBMP, int16_t backgroundX, int16_t backgroundY) virtual
Setup method for the SlideMenu. Positioning of the background is done by stating the X and Y coordinates for the element (relative to the SlideMenu). The width and height of the SlideMenu will be automatically set to the size of the background. Default values are: expandedStateTimeout = 200, visiblePixelsWhenCollapsed = 0, hiddenPixelsWhenExpanded = 0, animationDuration * = 10, animationEquation = cubicEaseInOut.
Parameters
newExpandDirection The new expand direction.
backgroundBMP The background bitmap.
backgroundX The background x coordinate.
backgroundY The background y coordinate.
{
    setExpandDirection(newExpandDirection);
    background.setBitmap(backgroundBMP);
    background.setXY(backgroundX, backgroundY);
    const Rect boundingRect = background.getRect();
    // boundingRect.expandToFit(background.getRect());
    menuContainer.setWidth(boundingRect.right());
    menuContainer.setHeight(boundingRect.bottom());
    setWidthHeight(menuContainer);
    setExpandDirection(expandDirection);
    setState(currentState);
    invalidate();
}
References SlideMenu::background, SlideMenu::currentState, SlideMenu::expandDirection, Drawable::getRect(), Drawable::invalidate(), SlideMenu::menuContainer, Image::setBitmap(), SlideMenu::setExpandDirection(), SlideMenu::setState(), Drawable::setWidthHeight(), and Drawable::setXY().
setVisiblePixelsWhenCollapsed()
void setVisiblePixelsWhenCollapsed (int16_t visiblePixels) virtual
Sets the amount of visible pixels when collapsed.
Parameters
visiblePixels The visible pixels.
{
    visiblePixelsWhenCollapsed = visiblePixels;
    setState(currentState);
}
References SlideMenu::currentState, SlideMenu::setState(), and SlideMenu::visiblePixelsWhenCollapsed.
Referenced by SlideMenu::setup().
stateChangeButtonClickedHandler()
void stateChangeButtonClickedHandler (const AbstractButton & button) protected
Handler for the state change button clicked event.
Parameters
button The state change button.
{
    if (currentState == COLLAPSED)
    {
        animateToState(EXPANDED);
    }
    else
    {
        animateToState(COLLAPSED);
    }
    if ((stateChangedCallback != 0) && stateChangedCallback->isValid())
    {
        stateChangedCallback->execute(*this);
    }
}
References SlideMenu::animateToState(), SlideMenu::COLLAPSED, SlideMenu::currentState, SlideMenu::EXPANDED, and SlideMenu::stateChangedCallback.
Member Data Documentation
animationDuration
uint16_t animationDuration protected
The animation duration of the state change animation.
Referenced by SlideMenu::animateToState(), SlideMenu::getAnimationDuration(), and SlideMenu::setAnimationDuration().
animationEndedCallback
Callback<SlideMenu, const MoveAnimator<Container>&> animationEndedCallback protected
The local state changed animation ended callback.
Referenced by SlideMenu::SlideMenu().
animationEquation
EasingEquation animationEquation protected
The easing equation used for the state change animation.
Referenced by SlideMenu::animateToState(), SlideMenu::getAnimationEasingEquation(), and SlideMenu::setAnimationEasingEquation().
background
Image background protected
The background of the SlideMenu.
Referenced by SlideMenu::SlideMenu(), SlideMenu::getBackgroundX(), SlideMenu::getBackgroundY(), SlideMenu::setup(), and SlideMenu::setup().
currentState
State currentState protected
The current state of the SlideMenu.
Referenced by SlideMenu::animateToState(), SlideMenu::getState(), SlideMenu::handleTickEvent(), SlideMenu::setExpandDirection(), SlideMenu::setHiddenPixelsWhenExpanded(), SlideMenu::setState(), SlideMenu::setup(), SlideMenu::setup(), SlideMenu::setVisiblePixelsWhenCollapsed(), and SlideMenu::stateChangeButtonClickedHandler().
expandDirection
ExpandDirection expandDirection protected
The expand direction of the SlideMenu.
Referenced by SlideMenu::getCollapsedXCoordinate(), SlideMenu::getCollapsedYCoordinate(), SlideMenu::getExpandDirection(), SlideMenu::getExpandedXCoordinate(), SlideMenu::getExpandedYCoordinate(), SlideMenu::setExpandDirection(), SlideMenu::setup(), and SlideMenu::setup().
expandedStateTimeout
uint16_t expandedStateTimeout protected
The expanded state timeout.
Referenced by SlideMenu::getExpandedStateTimeout(), SlideMenu::handleTickEvent(), and SlideMenu::setExpandedStateTimeout().
expandedStateTimer
uint16_t expandedStateTimer protected
The timer that counts towards the expandedStateTimeout. If reached the SlideMenu will animate to COLLAPSED.
Referenced by SlideMenu::getExpandedStateTimer(), SlideMenu::handleTickEvent(), and SlideMenu::resetExpandedStateTimer().
hiddenPixelsWhenExpanded
int16_t hiddenPixelsWhenExpanded protected
The number of hidden pixels when expanded.
Referenced by SlideMenu::getExpandedXCoordinate(), SlideMenu::getExpandedYCoordinate(), SlideMenu::getHiddenPixelsWhenExpanded(), and SlideMenu::setHiddenPixelsWhenExpanded().
menuContainer
MoveAnimator<Container> menuContainer protected
The container holding the actual menu items. This is the container that performs the state change animation.
Referenced by SlideMenu::SlideMenu(), SlideMenu::add(), SlideMenu::animateToState(), SlideMenu::getCollapsedXCoordinate(), SlideMenu::getCollapsedYCoordinate(), SlideMenu::handleTickEvent(), SlideMenu::remove(), SlideMenu::setState(), SlideMenu::setup(), and SlideMenu::setup().
onStateChangeButtonClicked
Callback<SlideMenu, const AbstractButton&> onStateChangeButtonClicked protected
The local state changed button clicked callback.
Referenced by SlideMenu::SlideMenu().
stateChangeButton
Button stateChangeButton protected
The state change button that toggles the SlideMenu state.
Referenced by SlideMenu::SlideMenu(), SlideMenu::animateToState(), SlideMenu::animationEndedHandler(), SlideMenu::getStateChangeButtonX(), SlideMenu::getStateChangeButtonY(), and SlideMenu::setup().
stateChangedAnimationEndedCallback
GenericCallback<const SlideMenu&>* stateChangedAnimationEndedCallback protected
The public state changed animation ended callback.
Referenced by SlideMenu::animationEndedHandler(), and SlideMenu::setStateChangedAnimationEndedCallback().
stateChangedCallback
GenericCallback<const SlideMenu&>* stateChangedCallback protected
The public state changed button clicked callback.
Referenced by SlideMenu::setStateChangedCallback(), and SlideMenu::stateChangeButtonClickedHandler().
visiblePixelsWhenCollapsed
int16_t visiblePixelsWhenCollapsed protected
The number of visible pixels when collapsed.
Referenced by SlideMenu::getCollapsedXCoordinate(), SlideMenu::getCollapsedYCoordinate(), SlideMenu::getVisiblePixelsWhenCollapsed(), and SlideMenu::setVisiblePixelsWhenCollapsed().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/SlideMenu.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/SlideMenu.cpp