Battery Simulator Documentation: ScrollList
ScrollList
#include "ScrollList.hpp"
Public Member Functions
ScrollList ()
int16_t getItem (int16_t drawableIndex)
int16_t getPaddingAfter () const
int16_t getPaddingBefore () const
bool getSnapping () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void setDrawables (DrawableListItemsInterface &drawableListItems, GenericCallback< DrawableListItemsInterface *, int16_t, int16_t > &updateDrawableCallback)
virtual void setDrawableSize (int16_t drawableSize, int16_t drawableMargin)
virtual void setHeight (int16_t height)
void setPadding (int16_t paddingBefore, int16_t paddingAfter)
void setSnapping (bool snap)
virtual void setWidth (int16_t width)
void setWindowSize (int16_t items)
Public Member Functions inherited from ScrollBase
ScrollBase ()
void allowHorizontalDrag (bool enable)
void allowVerticalDrag (bool enable)
virtual void animateToItem (int16_t itemIndex, int16_t animationSteps=-1)
uint16_t getAnimationSteps () const
virtual bool getCircular () const
uint16_t getDragAcceleration () const
virtual int16_t getDrawableMargin () const
virtual int16_t getDrawableSize () const
virtual bool getHorizontal () const
uint16_t getMaxSwipeItems () const
virtual int16_t getNumberOfItems () const
uint8_t getOvershootPercentage () const
uint16_t getSwipeAcceleration () const
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void initialize ()
bool isAnimating () const
virtual void itemChanged (int itemIndex)
void setAnimationEndedCallback (GenericCallback<> &callback)
void setAnimationSteps (int16_t steps)
virtual void setCircular (bool circular)
void setDragAcceleration (uint16_t acceleration)
void setEasingEquation (EasingEquation equation)
virtual void setHorizontal (bool horizontal)
void setItemPressedCallback (GenericCallback< int16_t > &callback)
void setItemSelectedCallback (GenericCallback< int16_t > &callback)
void setMaxSwipeItems (uint16_t maxItems)
virtual void setNumberOfItems (int16_t numberOfItems)
void setOvershootPercentage (uint8_t percentage)
void setSwipeAcceleration (uint16_t acceleration)
void stopAnimation ()
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual int32_t getNearestAlignedOffset (int32_t offset) const
virtual int32_t getPositionForItem (int16_t itemIndex)
virtual int32_t keepOffsetInsideLimits (int32_t newOffset, int16_t overShoot) const
Protected Member Functions inherited from ScrollBase
virtual void animateToPosition (int32_t position, int16_t steps=-1)
int getNormalizedOffset (int offset) const
virtual int32_t getOffset () const
virtual void setOffset (int32_t offset)
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
int16_t paddingAfterLastItem
The distance after last item.
bool snapping
Is snapping enabled?
int windowSize
Number of items that should always be visible.
Protected Attributes inherited from ScrollBase
GenericCallback * animationEndedCallback
The animation ended callback.
AnimationState currentAnimationState
The current animation state.
uint16_t defaultAnimationSteps
The animation steps.
int16_t distanceBeforeAlignedItem
The distance before aligned item.
uint16_t dragAcceleration
The drag acceleration x10.
bool draggableX
Is the container draggable in the horizontal direction.
bool draggableY
Is the container draggable in the vertical direction.
EasingEquation easingEquation
The easing equation used for animation.
int gestureEnd
The gesture end.
int gestureStart
The gesture start.
int gestureStep
The current gesture step.
int gestureStepsTotal
The total gesture steps.
int32_t initialSwipeOffset
The initial swipe offset.
GenericCallback * itemLockedInCallback
The item locked in callback.
GenericCallback< int16_t > * itemPressedCallback
The item pressed callback.
GenericCallback< int16_t > * itemSelectedCallback
The item selected callback.
int16_t itemSize
Size of the item (including margin)
DrawableList list
The list.
uint16_t maxSwipeItems
The maximum swipe items.
int16_t numberOfDrawables
Number of drawables.
uint8_t overshootPercentage
The overshoot percentage when dragging.
uint16_t swipeAcceleration
The swipe acceleration x10.
int16_t xClick
The x coordinate of a click.
int16_t yClick
The y coordinate of a click.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Protected Types inherited from ScrollBase
enum AnimationState { NO_ANIMATION , ANIMATING_GESTURE , ANIMATING_DRAG }
Detailed Description
A simple list of scrolling drawables. Since a long list of drawables only display a few of items at any one time, the drawables are re-used to preserve resources.
See also
DrawableList
Constructor & Destructor Documentation
ScrollList()
ScrollList ()
    : ScrollBase(),
      paddingAfterLastItem(0),
      snapping(false),
      windowSize(1)
{
}
Member Function Documentation
getItem()
int16_t getItem (int16_t drawableIndex) inline
Gets an item.
Parameters
drawableIndex Zero-based index of the drawable.
Returns
The item.
    {
        return list.getItemIndex(drawableIndex);
    }
References DrawableList::getItemIndex(), and ScrollBase::list.
getNearestAlignedOffset()
int32_t getNearestAlignedOffset (int32_t offset) const protected virtual
Gets nearest offset aligned to a multiple of itemSize.
Parameters
offset The offset.
Returns
The nearest aligned offset.
Reimplemented from ScrollBase.
{
    if (snapping)
    {
        // ScrollBase implementation will snap
        return ScrollBase::getNearestAlignedOffset(offset);
    }
    return keepOffsetInsideLimits(offset, 0);
}
References ScrollBase::getNearestAlignedOffset(), ScrollList::keepOffsetInsideLimits(), and ScrollList::snapping.
Referenced by ScrollList::handleClickEvent(), and ScrollList::setSnapping().
getPaddingAfter()
int16_t getPaddingAfter () const
Gets distance after last drawable in ScrollList.
Returns
The distance after the last drawable in the ScrollList.
See also
setPadding, getPaddingBefore
{
    return paddingAfterLastItem;
}
References ScrollList::paddingAfterLastItem.
getPaddingBefore()
int16_t getPaddingBefore () const
Gets distance before first drawable in ScrollList.
Returns
The distance before.
See also
setPadding, getPaddingAfter
{
    return distanceBeforeAlignedItem;
}
References ScrollBase::distanceBeforeAlignedItem.
getPositionForItem()
int32_t getPositionForItem (int16_t itemIndex) protected virtual
Get the position for an item. The position should ensure that the item is in view as defined by the semantics of the actual scroll class. If the item is already in view, the current offset is returned and not the offset of the given item.
Parameters
itemIndex Zero-based index of the item.
Returns
The position for item.
Implements ScrollBase.
{
    const int32_t currentOffset = getNormalizedOffset(getOffset());
    if (itemIndex < 0 || itemIndex >= list.getNumberOfItems() || itemSize == 0)
    {
        return currentOffset;
    }
    const int32_t itemOffset = -itemIndex * itemSize;
    // Get the visible size
    const int16_t widgetSize = getHorizontal() ? getWidth() : getHeight();
    const int16_t activeWidgetSize = widgetSize - (distanceBeforeAlignedItem + paddingAfterLastItem);
    if (list.getCircular())
    {
        int32_t offset = currentOffset;
        // Important this is a do-while of visibleSize < itemSize in which case we need to check at least one time
        do
        {
            const int16_t i = (-getNormalizedOffset(offset)) / itemSize; // Item index of first
            if (itemIndex == i)
            {
                return currentOffset;
            }
            offset -= itemSize;
        } while (offset >= currentOffset - (activeWidgetSize - itemSize));
        const int32_t allItemsSize = list.getNumberOfItems() * itemSize;
        // Either scroll left from the first item or right from the last item. Find out which is closest
        int32_t leftScrollDistance = itemOffset - currentOffset;
        const int32_t leftScrollDistance2 = (itemOffset + allItemsSize) - currentOffset;
        const int32_t rightItemOffset = getNormalizedOffset(currentOffset - (activeWidgetSize - itemSize));
        int32_t rightScrollDistance = rightItemOffset - itemOffset;
        const int32_t rightScrollDistance2 = rightItemOffset - (itemOffset - allItemsSize);
        if (abs(leftScrollDistance2) < abs(leftScrollDistance))
        {
            leftScrollDistance = leftScrollDistance2;
        }
        if (abs(rightScrollDistance2) < abs(rightScrollDistance))
        {
            rightScrollDistance = rightScrollDistance2;
        }
        if (abs(rightScrollDistance) < abs(leftScrollDistance))
        {
            return currentOffset - rightScrollDistance;
        }
        return currentOffset + leftScrollDistance;
    }
    if (itemOffset > currentOffset) // First item on screen is higher than the itemIndex. Scroll itemIndex to top position
    {
        return itemOffset;
    }
    const int16_t numberOfVisibleItems = activeWidgetSize / itemSize;
    int32_t itemOffsetAtEnd = itemOffset;
    if (numberOfVisibleItems > 0)
    {
        if (snapping)
        {
            itemOffsetAtEnd = itemOffset + (numberOfVisibleItems - 1) * itemSize;
        }
        else
        {
            itemOffsetAtEnd = itemOffset + activeWidgetSize - itemSize;
        }
    }
    if (itemOffsetAtEnd < currentOffset)
    {
        return itemOffsetAtEnd;
    }
    return currentOffset;
}
References touchgfx::abs(), ScrollBase::distanceBeforeAlignedItem, DrawableList::getCircular(), Drawable::getHeight(), ScrollBase::getHorizontal(), ScrollBase::getNormalizedOffset(), DrawableList::getNumberOfItems(), ScrollBase::getOffset(), Drawable::getWidth(), ScrollBase::itemSize, ScrollBase::list, ScrollList::paddingAfterLastItem, and ScrollList::snapping.
getSnapping()
bool getSnapping () const
Gets the current snap stetting.
Returns
true if snapping is set, false otherwise.
See also
setSnapping
{
    return snapping;
}
References ScrollList::snapping.
handleClickEvent()
void handleClickEvent (const ClickEvent & event) virtual
Defines the event handler interface for ClickEvents. The default implementation ignores the event. The event is only received if the Drawable is touchable and visible.
Parameters
event The ClickEvent received from the HAL.
Reimplemented from Drawable.
{
    ScrollBase::handleClickEvent(event);
    if (event.getType() == ClickEvent::PRESSED)
    {
        xClick = event.getX();
        yClick = event.getY();
        initialSwipeOffset = getOffset();
        setOffset(getNearestAlignedOffset(initialSwipeOffset));
        if (itemPressedCallback && itemPressedCallback->isValid())
        {
            const int16_t click = (getHorizontal() ? xClick : yClick);
            int32_t offset = click - getOffset();
            const int32_t listSize = getNumberOfItems() * itemSize;
            if (getCircular())
            {
                offset += listSize;
                offset %= listSize;
            }
            if (offset >= 0 && offset < listSize)
            {
                const int16_t item = offset / itemSize;
                itemPressedCallback->execute(item);
            }
        }
    }
    else if (event.getType() == ClickEvent::RELEASED)
    {
        if (currentAnimationState == NO_ANIMATION)
        {
            // For a tiny drag, start by re-aligning (no animation(!))
            setOffset(getNearestAlignedOffset(getOffset()));
            if (itemSelectedCallback && itemSelectedCallback->isValid())
            {
                const int16_t click = (getHorizontal() ? xClick : yClick);
                int32_t offset = click - getOffset();
                const int32_t listSize = getNumberOfItems() * itemSize;
                if (getCircular())
                {
                    offset += listSize;
                    offset %= listSize;
                }
                else
                {
                    offset -= distanceBeforeAlignedItem;
                }
                if (offset >= 0 && offset < listSize)
                {
                    const int16_t item = offset / itemSize;
                    itemSelectedCallback->execute(item);
                }
            }
        }
        else if (currentAnimationState == ANIMATING_DRAG)
        {
            // click + drag + release. Find best Y to scroll to
            animateToPosition(getNearestAlignedOffset(getOffset()));
        }
    }
}
References ScrollBase::animateToPosition(), ScrollBase::ANIMATING_DRAG, ScrollBase::currentAnimationState, ScrollBase::distanceBeforeAlignedItem, GenericCallback< T1, T2, T3 >::execute(), ScrollBase::getCircular(), ScrollBase::getHorizontal(), ScrollList::getNearestAlignedOffset(), ScrollBase::getNumberOfItems(), ScrollBase::getOffset(), Drawable::handleClickEvent(), ScrollBase::initialSwipeOffset, GenericCallback< T1, T2, T3 >::isValid(), ScrollBase::itemPressedCallback, ScrollBase::itemSelectedCallback, ScrollBase::itemSize, ScrollBase::NO_ANIMATION, ClickEvent::PRESSED, ClickEvent::RELEASED, ScrollBase::setOffset(), ScrollBase::xClick, and ScrollBase::yClick.
keepOffsetInsideLimits()
int32_t keepOffsetInsideLimits (int32_t newOffset, int16_t overShoot) const protected virtual
Keep offset inside limits. Return the new offset that is inside the limits of the scroll list, with the overShoot value added at both ends of the list.
Parameters
newOffset The new offset.
overShoot The over shoot.
Returns
The new offset inside the limits.
Implements ScrollBase.
{
    if (!getCircular())
    {
        newOffset = MIN(newOffset, overShoot);
        const int maxOffToTheStart = windowSize < getNumberOfItems() ? getNumberOfItems() - windowSize : 0;
        newOffset = MAX(newOffset, -(itemSize * maxOffToTheStart) - overShoot);
    }
    return newOffset;
}
References ScrollBase::getCircular(), ScrollBase::getNumberOfItems(), ScrollBase::itemSize, MAX, MIN, and ScrollList::windowSize.
Referenced by ScrollList::getNearestAlignedOffset(), and ScrollList::setWindowSize().
setDrawables()
void setDrawables (DrawableListItemsInterface & drawableListItems, GenericCallback< DrawableListItemsInterface *, int16_t, int16_t > & updateDrawableCallback) virtual
Setup a list of drawables and provide a function to call to update a given Drawable with new contents.
Parameters
[in] drawableListItems The drawables allocated.
[in] updateDrawableCallback A callback to update the contents of a specific drawable with a specific item.
See also
DrawableList::setDrawables
{
    stopAnimation();
    numberOfDrawables = drawableListItems.getNumberOfDrawables();
    list.setDrawables(drawableListItems, 0, updateDrawableCallback);
    setOffset(0);
}
References ScrollBase::list, ScrollBase::numberOfDrawables, DrawableList::setDrawables(), ScrollBase::setOffset(), and ScrollBase::stopAnimation().
setDrawableSize()
void setDrawableSize (int16_t drawableSize, int16_t drawableMargin) virtual
Sets drawables size. The drawable is is the size of each drawable in the list in the set direction of the list (this is enforced by the DrawableList class). The specified margin is added above and below each item for spacing. The entire size of an item is thus size + 2 * spacing.
For a horizontal list each element will be drawableSize high and have the same width as set using setWidth(). For a vertical list each element will be drawableSize wide and have the same height as set using setHeight().
Parameters
drawableSize The size of the drawable.
drawableMargin The margin around drawables (margin before and margin after).
See also
setWidth, setHeight, setHorizontal
Reimplemented from ScrollBase.
{
    ScrollBase::setDrawableSize(drawableSize, drawableMargin);
    setWindowSize(windowSize);
}
References ScrollBase::setDrawableSize(), ScrollList::setWindowSize(), and ScrollList::windowSize.
setHeight()
void setHeight (int16_t height) virtual
Sets the height of this drawable.
Parameters
height The new height.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Also sets the height of the children.
Reimplemented from ScrollBase.
{
    ScrollBase::setHeight(height);
    if (!getHorizontal())
    {
        setWindowSize(windowSize);
    }
}
References ScrollBase::getHorizontal(), ScrollBase::setHeight(), ScrollList::setWindowSize(), and ScrollList::windowSize.
setPadding()
void setPadding (int16_t paddingBefore, int16_t paddingAfter)
Sets distance offset before and after the "visible" drawables in the ScrollList. This allows the actual area where widgets are placed to have a little extra area where parts of drawables can be seen. For example if the ScrollList is 200, each drawable is 50 and distance before and distance after are 25, then there is room for three visible drawables inside the ScrollList. When scrolling, part of the scrolled out drawables can be seen before and after the three drawables. In this case 25/50 = 50% of a drawable can be seen before and after the three drawables in the ScrollList.
Parameters
paddingBefore The distance before the first drawable in the ScrollList.
paddingAfter The distance after the last drawable in the ScrollList.
See also
getPaddingBefore, getPaddingAfter
{
    const int32_t currentOffset = getOffset();
    distanceBeforeAlignedItem = paddingBefore;
    paddingAfterLastItem = paddingAfter;
    setOffset(currentOffset);
    list.refreshDrawables();
}
References ScrollBase::distanceBeforeAlignedItem, ScrollBase::getOffset(), ScrollBase::list, ScrollList::paddingAfterLastItem, DrawableList::refreshDrawables(), and ScrollBase::setOffset().
setSnapping()
void setSnapping (bool snap)
Set snapping. If snapping is false, the items can flow freely. If snapping is true, the items will snap into place so an item is always in the "selected" spot.
Parameters
snap true to snap.
See also
getSnapping
{
    snapping = snap;
    if (snapping)
    {
        setOffset(getNearestAlignedOffset(getOffset()));
    }
}
References ScrollList::getNearestAlignedOffset(), ScrollBase::getOffset(), ScrollBase::setOffset(), and ScrollList::snapping.
setWidth()
void setWidth (int16_t width) virtual
Sets the width of this drawable.
Parameters
width The new width.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Also sets the width of the children.
Reimplemented from ScrollBase.
{
    ScrollBase::setWidth(width);
    if (getHorizontal())
    {
        setWindowSize(windowSize);
    }
}
References ScrollBase::getHorizontal(), ScrollBase::setWidth(), ScrollList::setWindowSize(), and ScrollList::windowSize.
setWindowSize()
void setWindowSize (int16_t items)
Sets window size, i.e. the number of items that should always be visible. The default value is 1. If three items are visible on the display and window size is set to three, no part of the screen will be blank (unless the list contains less than three items and the list is not circular).
Parameters
items The number of items that should always be visible.
Note
This only applies to non-circular lists.
{
    if (itemSize > 0)
    {
        const int16_t widgetSize = getHorizontal() ? getWidth() : getHeight();
        const int16_t activeWidgetSize = widgetSize - (distanceBeforeAlignedItem + paddingAfterLastItem);
        const int16_t numberOfVisibleItems = (activeWidgetSize + itemSize / 2) / itemSize; // Round up
        items = MIN(items, numberOfVisibleItems);                                          // No more than numberOfVisibleItems
    }
    windowSize = MAX(1, items); // No less than 1
    animateToPosition(keepOffsetInsideLimits(getOffset(), 0));
}
References ScrollBase::animateToPosition(), ScrollBase::distanceBeforeAlignedItem, Drawable::getHeight(), ScrollBase::getHorizontal(), ScrollBase::getOffset(), Drawable::getWidth(), ScrollBase::itemSize, ScrollList::keepOffsetInsideLimits(), MAX, MIN, ScrollList::paddingAfterLastItem, and ScrollList::windowSize.
Referenced by ScrollList::setDrawableSize(), ScrollList::setHeight(), and ScrollList::setWidth().
Member Data Documentation
paddingAfterLastItem
int16_t paddingAfterLastItem protected
The distance after last item.
Referenced by ScrollList::getPaddingAfter(), ScrollList::getPositionForItem(), ScrollList::setPadding(), and ScrollList::setWindowSize().
snapping
bool snapping protected
Is snapping enabled?
Referenced by ScrollList::getNearestAlignedOffset(), ScrollList::getPositionForItem(), ScrollList::getSnapping(), and ScrollList::setSnapping().
windowSize
int windowSize protected
Number of items that should always be visible.
Referenced by ScrollList::keepOffsetInsideLimits(), ScrollList::setDrawableSize(), ScrollList::setHeight(), ScrollList::setWidth(), and ScrollList::setWindowSize().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/scrollers/ScrollList.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/scrollers/ScrollList.cpp