Battery Simulator Documentation: Circle
Circle
#include "Circle.hpp"
Public Member Functions
Circle ()
virtual bool drawCanvasWidget (const Rect &invalidatedArea) const
template<typename T >
void getArc (T &startAngle, T &endAngle) const
int16_t getArcEnd () const
template<typename T >
void getArcEnd (T &angle) const
int16_t getArcStart () const
template<typename T >
void getArcStart (T &angle) const
int getCapPrecision () const
template<typename T >
void getCenter (T &x, T &y) const
template<typename T >
void getLineWidth (T &width) const
virtual Rect getMinimalRect () const
Rect getMinimalRect (CWRUtil::Q5 arcStart, CWRUtil::Q5 arcEnd) const
Rect getMinimalRect (int16_t arcStart, int16_t arcEnd) const
int getPrecision () const
template<typename T >
void getRadius (T &r) const
void setArc (const int16_t startAngle, const int16_t endAngle)
template<typename T >
void setArc (const T startAngle, const T endAngle)
void setCapPrecision (const int precision)
void setCenter (const int16_t x, const int16_t y)
template<typename T >
void setCenter (const T x, const T y)
void setCircle (const int16_t x, const int16_t y, const int16_t r)
template<typename T >
void setCircle (const T x, const T y, const T r)
template<typename T >
void setLineWidth (const T width)
void setPixelCenter (int x, int y)
void setPrecision (const int precision)
template<typename T >
void setRadius (const T r)
template<typename T >
void updateArc (const T startAngle, const T endAngle)
template<typename T >
void updateArcEnd (const T endAngle)
template<typename T >
void updateArcStart (const T startAngle)
Public Member Functions inherited from CanvasWidget
CanvasWidget ()
virtual void draw (const Rect &invalidatedArea) const
virtual uint8_t getAlpha () const
const AbstractPainter * getPainter () const
virtual Rect getSolidRect () const
virtual void invalidate () const
virtual void setAlpha (uint8_t newAlpha)
void setPainter (const AbstractPainter &painter)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
void updateArc (const CWRUtil::Q5 setStartAngleQ5, const CWRUtil::Q5 setEndAngleQ5)
Private Member Functions
void calculateMinimalRect (CWRUtil::Q5 arcStart, CWRUtil::Q5 arcEnd, CWRUtil::Q5 &xMin, CWRUtil::Q5 &xMax, CWRUtil::Q5 &yMin, CWRUtil::Q5 &yMax) const
Rect getMinimalRectForUpdatedEndAngle (const CWRUtil::Q5 &endAngleQ5) const
Rect getMinimalRectForUpdatedStartAngle (const CWRUtil::Q5 &startAngleQ5) const
FORCE_INLINE_FUNCTION void lineToAngleRadius2 (Canvas &canvas, const CWRUtil::Q5 &angle, const CWRUtil::Q5 &r2) const
FORCE_INLINE_FUNCTION void lineToXYAngleRadius2 (Canvas &canvas, const CWRUtil::Q5 &x, const CWRUtil::Q5 &y, const CWRUtil::Q5 &angle, const CWRUtil::Q5 &r2) const
FORCE_INLINE_FUNCTION void moveToAngleRadius2 (Canvas &canvas, const CWRUtil::Q5 &angle, const CWRUtil::Q5 &r2) const
FORCE_INLINE_FUNCTION void updateMinMaxAngleLine (const CWRUtil::Q5 &angle, const CWRUtil::Q5 &halfLineWidth, CWRUtil::Q5 &xMin, CWRUtil::Q5 &xMax, CWRUtil::Q5 &yMin, CWRUtil::Q5 &yMax) const
FORCE_INLINE_FUNCTION void updateMinMaxAngleSolid (const CWRUtil::Q5 &angle, CWRUtil::Q5 &xMin, CWRUtil::Q5 &xMax, CWRUtil::Q5 &yMin, CWRUtil::Q5 &yMax) const
FORCE_INLINE_FUNCTION void updateMinMaxX (const CWRUtil::Q5 &xNew, CWRUtil::Q5 &xMin, CWRUtil::Q5 &xMax) const
FORCE_INLINE_FUNCTION void updateMinMaxY (const CWRUtil::Q5 &yNew, CWRUtil::Q5 &yMin, CWRUtil::Q5 &yMax) const
Private Attributes
CWRUtil::Q5 circleArcAngleEnd
CWRUtil::Q5 circleArcAngleStart
uint8_t circleArcIncrement
uint8_t circleCapArcIncrement
CWRUtil::Q5 circleCenterX
CWRUtil::Q5 circleCenterY
CWRUtil::Q5 circleLineWidth
CWRUtil::Q5 circleRadius
Additional Inherited Members
Protected Attributes inherited from CanvasWidget
uint8_t alpha
The Alpha for this CanvasWidget.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
Simple widget capable of drawing a circle, or part of a circle (an arc). The Circle can be filled or be drawn as a simple line along the circumference of the circle. Several parameters of the circle can be changed: Center, radius, line width, line cap, start angle and end angle.
Note
Since the underlying CanwasWidgetRenderer only supports straight lines, the circle is drawn using many small straight lines segments. The granularity can be adjusted to match the requirements - large circles need more line segments, small circles need fewer line segments, to look smooth and round.
All circle parameters are internally handled as CWRUtil::Q5 which means that floating point values are rounded down to a fixed number of binary digits, for example:
Circle circle;
circle.setCircle(1.1f, 1.1f, 0.9); // Will use (35/32, 35/32, 28/32) = (1.09375f, 1.09375f, 0.875f)
int x, y, r;
circle.getCenter(&x, &y); // Will return (1, 1)
circle.getRadius(&r); // Will return 0
.
Constructor & Destructor Documentation
Circle()
Circle ()
    : CanvasWidget(),
      circleCenterX(0), circleCenterY(0), circleRadius(0),
      circleArcAngleStart(CWRUtil::toQ5<int>(0)), circleArcAngleEnd(CWRUtil::toQ5<int>(360)),
      circleLineWidth(0), circleArcIncrement(5),
      circleCapArcIncrement(180)
{
    Drawable::setWidthHeight(0, 0);
}
References Drawable::setWidthHeight().
Member Function Documentation
calculateMinimalRect()
void calculateMinimalRect (CWRUtil::Q5 arcStart, CWRUtil::Q5 arcEnd, CWRUtil::Q5 & xMin, CWRUtil::Q5 & xMax, CWRUtil::Q5 & yMin, CWRUtil::Q5 & yMax) const private
{
    // Put start before end by swapping
    if (arcStart > arcEnd)
    {
        CWRUtil::Q5 const tmp = arcStart;
        arcStart = arcEnd;
        arcEnd = tmp;
    }
    CWRUtil::Q5 const _90 = CWRUtil::toQ5<int>(90);
    CWRUtil::Q5 const _360 = CWRUtil::toQ5<int>(360);
    if ((arcEnd - arcStart) >= _360)
    {
        // The entire circle has to be drawn
        arcStart = CWRUtil::toQ5<int>(0);
        arcEnd = _360;
    }
    if (circleLineWidth == 0)
    {
        // Check start angle
        updateMinMaxAngleSolid(arcStart, xMin, xMax, yMin, yMax);
        // Here we have a up to 4 approximation steps on angles divisible by 90
        CWRUtil::Q5 i;
        for (i = CWRUtil::Q5(ROUNDUP((int)(arcStart + (CWRUtil::Q5)1), (int)_90)); i <= arcEnd; i += _90)
        {
            updateMinMaxAngleSolid(i, xMin, xMax, yMin, yMax);
        }
        // Check end angle
        if ((i - _90) < arcEnd)
        {
            updateMinMaxAngleSolid(arcEnd, xMin, xMax, yMin, yMax);
        }
        updateMinMaxX(circleCenterX, xMin, xMax);
        updateMinMaxY(circleCenterY, yMin, yMax);
    }
    else
    {
        const CWRUtil::Q5 halfLineWidth = (circleLineWidth + (CWRUtil::Q5)1) / 2;
        // Check start angle
        updateMinMaxAngleLine(arcStart, halfLineWidth, xMin, xMax, yMin, yMax);
        // Here we have a up to 4 approximation steps on angles divisible by 90
        CWRUtil::Q5 i;
        for (i = CWRUtil::Q5(ROUNDUP((int)(arcStart + (CWRUtil::Q5)1), (int)_90)); i <= arcEnd; i += _90)
        {
            updateMinMaxAngleLine(i, halfLineWidth, xMin, xMax, yMin, yMax);
        }
        // Check end angle
        if ((i - _90) < arcEnd)
        {
            updateMinMaxAngleLine(arcEnd, halfLineWidth, xMin, xMax, yMin, yMax);
        }
    }
}
References Circle::circleCenterX, Circle::circleCenterY, Circle::circleLineWidth, ROUNDUP, Circle::updateMinMaxAngleLine(), Circle::updateMinMaxAngleSolid(), Circle::updateMinMaxX(), and Circle::updateMinMaxY().
Referenced by Circle::getMinimalRect().
drawCanvasWidget()
bool drawCanvasWidget (const Rect & invalidatedArea) const virtual
Draw canvas widget for the given invalidated area. Similar to draw(), but might be invoked several times with increasingly smaller areas to due to memory constraints from the underlying CanvasWidgetRenderer.
Parameters
invalidatedArea The invalidated area.
Returns
true if the widget was drawn properly, false if not.
See also
draw
Implements CanvasWidget.
{
    CWRUtil::Q5 arcStart = circleArcAngleStart;
    CWRUtil::Q5 arcEnd = circleArcAngleEnd;
    CWRUtil::Q5 const _360 = CWRUtil::toQ5<int>(360);
    // Put start before end by swapping
    if (arcStart > arcEnd)
    {
        CWRUtil::Q5 const tmp = arcStart;
        arcStart = arcEnd;
        arcEnd = tmp;
    }
    if ((arcEnd - arcStart) >= _360)
    {
        // The entire circle has to be drawn
        arcStart = CWRUtil::toQ5<int>(0);
        arcEnd = _360;
    }
    const int16_t circleCenterX16 = circleCenterX.to<int16_t>();
    const int16_t circleCenterY16 = circleCenterY.to<int16_t>();
    int32_t routside = 0;
    if (circleLineWidth != 0)
    {
        // Check if invalidated area is completely inside the circle
        const int32_t dx1 = abs((int)circleCenterX16 - invalidatedArea.x); // Find distances between each corner and circle center
        const int32_t dx2 = abs((int)circleCenterX16 - invalidatedArea.right());
        const int32_t dy1 = abs((int)circleCenterY16 - invalidatedArea.y);
        const int32_t dy2 = abs((int)circleCenterY16 - invalidatedArea.bottom());
        const int32_t dx = MAX(dx1, dx2) + 1; // Largest horz/vert distance (round up)
        const int32_t dy = MAX(dy1, dy2) + 1;
        // From https://www.mathopenref.com/polygonincircle.html
        const int32_t rmin = ((circleRadius - (circleLineWidth / 2)) * CWRUtil::cosine((circleArcIncrement + 1) / 2)).to<int>();
        // Check if invalidatedArea is completely inside circle
        if ((dx * dx) + (dy * dy) < rmin * rmin)
        {
            return true;
        }
        routside = (circleRadius + (circleLineWidth / 2)).to<int>() + 1;
    }
    else
    {
        routside = circleRadius.to<int>() + 1;
    }
    // From https://yal.cc/rectangle-circle-intersection-test/
    const int32_t invalidatedRight = invalidatedArea.right();
    const int32_t minimumX = MIN(circleCenterX16, invalidatedRight);
    const int32_t nearestX = circleCenterX16 - MAX(invalidatedArea.x, minimumX);
    const int32_t invalidatedBottom = invalidatedArea.bottom();
    const int32_t minimumY = MIN(circleCenterY16, invalidatedBottom);
    const int32_t nearestY = circleCenterY16 - MAX(invalidatedArea.y, minimumY);
    // Check if invalidatedArea is completely outside circle
    if ((nearestX * nearestX) + (nearestY * nearestY) > routside * routside)
    {
        return true;
    }
    Canvas canvas(getPainter(), getAbsoluteRect(), invalidatedArea, getAlpha());
    CWRUtil::Q5 radius = circleRadius;
    CWRUtil::Q5 lineWidth = circleLineWidth;
    if (circleLineWidth > circleRadius * 2)
    {
        lineWidth = (circleRadius + circleLineWidth / 2);
        radius = lineWidth / 2;
    }
    CWRUtil::Q5 arc = arcStart;
    CWRUtil::Q5 const circleArcIncrementQ5 = CWRUtil::toQ5<int>(circleArcIncrement);
    moveToAngleRadius2(canvas, arc, (radius * 2) + lineWidth);
    CWRUtil::Q5 nextArc = CWRUtil::Q5(ROUNDUP((int)(arc + CWRUtil::toQ5<int>(1)), (int)circleArcIncrementQ5));
    while (nextArc <= arcEnd)
    {
        arc = nextArc;
        lineToAngleRadius2(canvas, arc, (radius * 2) + lineWidth);
        nextArc += circleArcIncrementQ5;
    }
    if (arc < arcEnd)
    {
        // "arc" is not updated. It is the last arc in steps of "circleArcIncrement"
        lineToAngleRadius2(canvas, arcEnd, (radius * 2) + lineWidth);
    }
    if (lineWidth == CWRUtil::toQ5<int>(0))
    {
        // Draw a filled circle / pie / pacman
        if (arcEnd - arcStart < _360)
        {
            // Not a complete circle, line to center
            canvas.lineTo(circleCenterX, circleCenterY);
        }
    }
    else
    {
        if (canvas.wasOutlineTooComplex())
        {
            return false;
        }
        CWRUtil::Q5 const circleCapArcIncrementQ5 = CWRUtil::toQ5<int>(circleCapArcIncrement);
        CWRUtil::Q5 const _180 = CWRUtil::toQ5<int>(180);
        if (arcEnd - arcStart < _360)
        {
            // Draw the circle cap
            CWRUtil::Q5 const capX = circleCenterX + (radius * CWRUtil::sine(arcEnd));
            CWRUtil::Q5 const capY = circleCenterY - (radius * CWRUtil::cosine(arcEnd));
            for (CWRUtil::Q5 capAngle = arcEnd + circleCapArcIncrementQ5; capAngle < arcEnd + _180; capAngle += circleCapArcIncrementQ5)
            {
                lineToXYAngleRadius2(canvas, capX, capY, capAngle, lineWidth);
            }
        }
        // Not a filled circle, draw the path on the inside of the circle
        if (arc < arcEnd)
        {
            lineToAngleRadius2(canvas, arcEnd, (radius * 2) - lineWidth);
        }
        nextArc = arc;
        while (nextArc >= arcStart)
        {
            arc = nextArc;
            lineToAngleRadius2(canvas, arc, (radius * 2) - lineWidth);
            nextArc -= circleArcIncrementQ5;
        }
        if (arc > arcStart)
        {
            lineToAngleRadius2(canvas, arcStart, (radius * 2) - lineWidth);
        }
        if (arcEnd - arcStart < _360)
        {
            // Draw the circle cap
            CWRUtil::Q5 const capX = circleCenterX + (radius * CWRUtil::sine(arcStart));
            CWRUtil::Q5 const capY = circleCenterY - (radius * CWRUtil::cosine(arcStart));
            for (CWRUtil::Q5 capAngle = (arcStart - _180) + circleCapArcIncrementQ5; capAngle < arcStart; capAngle += circleCapArcIncrementQ5)
            {
                lineToXYAngleRadius2(canvas, capX, capY, capAngle, lineWidth);
            }
        }
    }
    return canvas.render();
}
References touchgfx::abs(), Circle::circleArcAngleEnd, Circle::circleArcAngleStart, Circle::circleArcIncrement, Circle::circleCapArcIncrement, Circle::circleCenterX, Circle::circleCenterY, Circle::circleLineWidth, Circle::circleRadius, CWRUtil::cosine(), Drawable::getAbsoluteRect(), CanvasWidget::getAlpha(), CanvasWidget::getPainter(), Circle::lineToAngleRadius2(), Circle::lineToXYAngleRadius2(), MAX, MIN, Circle::moveToAngleRadius2(), ROUNDUP, CWRUtil::sine(), and CWRUtil::Q5::to().
getArc()
template<typename T > void getArc (T & startAngle, T & endAngle) const inline
Gets the start and end angles in degrees for the circle arc.
Template Parameters
T Generic type parameter, either int or float.
Parameters
[out] startAngle The start angle rounded down to the precision of T.
[out] endAngle The end angle rounded down to the precision of T.
See also
setArc
Note
Angles are given in degrees, so a full circle is 360.
    {
        startAngle = circleArcAngleStart.to<T>();
        endAngle = circleArcAngleEnd.to<T>();
    }
References Circle::circleArcAngleEnd, Circle::circleArcAngleStart, and CWRUtil::Q5::to().
getArcEnd() [1/2]
int16_t getArcEnd () const inline
Gets the end angle in degrees for the arc.
Returns
The end angle for the arc rounded down to an integer.
See also
getArc, setArc
Note
Angles are given in degrees, so a full circle is 360.
    {
        return circleArcAngleEnd.to<int>();
    }
References Circle::circleArcAngleEnd, and CWRUtil::Q5::to().
getArcEnd() [2/2]
template<typename T > void getArcEnd (T & angle) const inline
Gets the end angle in degrees for the arc.
Template Parameters
T Generic type parameter, either int or float.
Parameters
[out] angle The end angle rounded down to the precision of T.
Note
Angles are given in degrees, so a full circle is 360.
    {
        angle = circleArcAngleEnd.to<T>();
    }
References Circle::circleArcAngleEnd, and CWRUtil::Q5::to().
getArcStart() [1/2]
int16_t getArcStart () const inline
Gets the start angle in degrees for the arc.
Returns
The starting angle for the arc rounded down to an integer.
See also
getArc, setArc
Note
Angles are given in degrees, so a full circle is 360.
    {
        return circleArcAngleStart.to<int>();
    }
References Circle::circleArcAngleStart, and CWRUtil::Q5::to().
Referenced by CircleProgress::getStartAngle(), and CircleProgress::setValue().
getArcStart() [2/2]
template<typename T > void getArcStart (T & angle) const inline
Gets the start angle in degrees for the arc.
Template Parameters
T Generic type parameter, either int or float.
Parameters
[out] angle The starting angle rounded down to the precision of T.
See also
getArc, setArc
Note
Angles are given in degrees, so a full circle is 360.
    {
        angle = circleArcAngleStart.to<T>();
    }
References Circle::circleArcAngleStart, and CWRUtil::Q5::to().
getCapPrecision()
int getCapPrecision () const
Gets the precision of the ends of the Circle arc.
Returns
The cap precision in degrees.
See also
getCapPrecision
{
    return circleCapArcIncrement;
}
References Circle::circleCapArcIncrement.
Referenced by CircleProgress::getCapPrecision().
getCenter()
template<typename T > void getCenter (T & x, T & y) const inline
Gets the center coordinates of the Circle.
Template Parameters
T Generic type parameter, either int or float.
Parameters
[out] x The x coordinate of the center rounded down to the precision of T.
[out] y The y coordinate of the center rounded down to the precision of T.
See also
setCenter
    {
        x = circleCenterX.to<T>();
        y = circleCenterY.to<T>();
    }
References Circle::circleCenterX, Circle::circleCenterY, and CWRUtil::Q5::to().
Referenced by CircleProgress::getCenter().
getLineWidth()
template<typename T > void getLineWidth (T & width) const inline
Gets line width.
Template Parameters
T Generic type parameter, either int or float.
Parameters
[out] width The line width rounded down to the precision of T.
See also
setLineWidth
    {
        width = circleLineWidth.to<T>();
    }
References Circle::circleLineWidth, and CWRUtil::Q5::to().
Referenced by CircleProgress::getLineWidth().
getMinimalRect() [1/3]
virtual Rect getMinimalRect () const inline virtual
Gets minimal rectangle containing the shape drawn by this widget. Default implementation returns the size of the entire widget, but this function should be overwritten in subclasses and return the minimal rectangle containing the shape. See classes such as Circle for example implementations.
Returns
The minimal rectangle containing the shape drawn.
Reimplemented from CanvasWidget.
    {
        return getMinimalRect(circleArcAngleStart, circleArcAngleEnd);
    }
References Circle::circleArcAngleEnd, Circle::circleArcAngleStart, and Circle::getMinimalRect().
Referenced by Circle::getMinimalRect(), Circle::getMinimalRect(), Circle::getMinimalRectForUpdatedEndAngle(), Circle::getMinimalRectForUpdatedStartAngle(), and Circle::updateArc().
getMinimalRect() [2/3]
Rect getMinimalRect (CWRUtil::Q5 arcStart, CWRUtil::Q5 arcEnd) const
Gets minimal rectangle containing a given circle arc using the set line width.
Parameters
arcStart The arc start.
arcEnd The arc end.
Returns
The minimal rectangle.
{
    CWRUtil::Q5 xMin = CWRUtil::toQ5<int>(getWidth());
    CWRUtil::Q5 xMax = CWRUtil::toQ5<int>(0);
    CWRUtil::Q5 yMin = CWRUtil::toQ5<int>(getHeight());
    CWRUtil::Q5 yMax = CWRUtil::toQ5<int>(0);
    calculateMinimalRect(arcStart, arcEnd, xMin, xMax, yMin, yMax);
    return Rect(xMin.to<int>() - 1, yMin.to<int>() - 1,
                (xMax.to<int>() - xMin.to<int>()) + 2, (yMax.to<int>() - yMin.to<int>()) + 2);
}
References Circle::calculateMinimalRect(), Drawable::getHeight(), and Drawable::getWidth().
getMinimalRect() [3/3]
Rect getMinimalRect (int16_t arcStart, int16_t arcEnd) const inline
Gets minimal rectangle containing a given circle arc using the set line width.
Parameters
arcStart The arc start.
arcEnd The arc end.
Returns
The minimal rectangle.
    {
        return getMinimalRect(CWRUtil::toQ5<int>(arcStart), CWRUtil::toQ5<int>(arcEnd));
    }
References Circle::getMinimalRect().
getMinimalRectForUpdatedEndAngle()
Rect getMinimalRectForUpdatedEndAngle (const CWRUtil::Q5 & endAngleQ5) const private
{
    CWRUtil::Q5 minAngle = CWRUtil::Q5(0); // Unused default value
    CWRUtil::Q5 maxAngle = CWRUtil::Q5(0); // Unused default value
    const int circleArcIncrementQ5int = (int)CWRUtil::toQ5<int>(circleArcIncrement);
    if (circleArcAngleStart < circleArcAngleEnd)
    {
        // start is smaller than end
        if (endAngleQ5 > circleArcAngleEnd)
        {
            // end moved even higher
            minAngle = CWRUtil::Q5(ROUNDDOWN((int)circleArcAngleEnd, circleArcIncrementQ5int));
            minAngle = MAX(minAngle, circleArcAngleStart);
            maxAngle = endAngleQ5;
        }
        else if (endAngleQ5 > circleArcAngleStart)
        {
            // end moved lower, but not past start
            minAngle = CWRUtil::Q5(ROUNDDOWN((int)endAngleQ5, circleArcIncrementQ5int));
            minAngle = MAX(minAngle, circleArcAngleStart); // No need to go lower than start
            maxAngle = circleArcAngleEnd;
        }
        else
        {
            // end move past start
            minAngle = endAngleQ5;
            maxAngle = circleArcAngleEnd;
        }
    }
    else
    {
        // start is higher than end
        if (endAngleQ5 < circleArcAngleEnd)
        {
            // end moved even lower
            minAngle = endAngleQ5;
            maxAngle = CWRUtil::Q5(ROUNDUP((int)circleArcAngleEnd, circleArcIncrementQ5int));
            maxAngle = MIN(maxAngle, circleArcAngleStart); // No need to go higher than start
        }
        else if (endAngleQ5 < circleArcAngleStart)
        {
            // end moved higher, but not higher than start
            minAngle = circleArcAngleEnd;
            maxAngle = CWRUtil::Q5(ROUNDUP((int)endAngleQ5, circleArcIncrementQ5int));
            maxAngle = MIN(maxAngle, circleArcAngleStart);
        }
        else
        {
            // end moved past start
            minAngle = circleArcAngleEnd;
            maxAngle = endAngleQ5;
        }
    }
    return getMinimalRect(minAngle, maxAngle);
}
References Circle::circleArcAngleEnd, Circle::circleArcAngleStart, Circle::circleArcIncrement, Circle::getMinimalRect(), MAX, MIN, ROUNDDOWN, and ROUNDUP.
Referenced by Circle::updateArc(), and Circle::updateArcEnd().
getMinimalRectForUpdatedStartAngle()
Rect getMinimalRectForUpdatedStartAngle (const CWRUtil::Q5 & startAngleQ5) const private
{
    CWRUtil::Q5 minAngle = CWRUtil::Q5(0); // Unused default value
    CWRUtil::Q5 maxAngle = CWRUtil::Q5(0); // Unused default value
    const int circleArcIncrementQ5int = (int)CWRUtil::toQ5<int>(circleArcIncrement);
    if (circleArcAngleStart < circleArcAngleEnd)
    {
        // start is smaller than end
        if (startAngleQ5 < circleArcAngleStart)
        {
            // start moved even lower
            minAngle = startAngleQ5;
            maxAngle = CWRUtil::Q5(ROUNDUP((int)circleArcAngleStart, circleArcIncrementQ5int));
            maxAngle = MIN(maxAngle, circleArcAngleEnd); // No need to go higher than end
        }
        else if (startAngleQ5 < circleArcAngleEnd)
        {
            // start moved higher, but not higher than end
            minAngle = circleArcAngleStart;
            maxAngle = CWRUtil::Q5(ROUNDUP((int)startAngleQ5, circleArcIncrementQ5int));
            maxAngle = MIN(maxAngle, circleArcAngleEnd); // No need to go higher than end
        }
        else
        {
            // start moved past end
            minAngle = circleArcAngleStart;
            maxAngle = startAngleQ5;
        }
    }
    else
    {
        // start is higher than end
        if (startAngleQ5 > circleArcAngleStart)
        {
            // start moved even higher
            minAngle = CWRUtil::Q5(ROUNDDOWN((int)circleArcAngleStart, circleArcIncrementQ5int));
            minAngle = MAX(minAngle, circleArcAngleEnd); // No need to go lower then end
            maxAngle = startAngleQ5;
        }
        else if (startAngleQ5 > circleArcAngleEnd)
        {
            // start moved lower, but not lower than end
            minAngle = CWRUtil::Q5(ROUNDDOWN((int)startAngleQ5, circleArcIncrementQ5int));
            minAngle = MAX(minAngle, circleArcAngleEnd); // No need to go lower than end
            maxAngle = circleArcAngleStart;
        }
        else
        {
            // start moved lower past end
            minAngle = startAngleQ5;
            maxAngle = circleArcAngleStart;
        }
    }
    return getMinimalRect(minAngle, maxAngle);
}
References Circle::circleArcAngleEnd, Circle::circleArcAngleStart, Circle::circleArcIncrement, Circle::getMinimalRect(), MAX, MIN, ROUNDDOWN, and ROUNDUP.
Referenced by Circle::updateArc(), and Circle::updateArcStart().
getPrecision()
int getPrecision () const
Gets the precision of the circle drawing function. The precision is the number of degrees used as step counter when drawing smaller line fragments around the circumference of the circle, the default being 5.
Returns
The precision.
See also
setPrecision
{
    return circleArcIncrement;
}
References Circle::circleArcIncrement.
getRadius()
template<typename T > void getRadius (T & r) const inline
Gets the radius of the Circle.
Template Parameters
T Generic type parameter, either int or float.
Parameters
[out] r The radius rounded down to the precision of T.
    {
        r = circleRadius.to<T>();
    }
References Circle::circleRadius, and CWRUtil::Q5::to().
Referenced by CircleProgress::getRadius().
lineToAngleRadius2()
FORCE_INLINE_FUNCTION void lineToAngleRadius2 (Canvas & canvas, const CWRUtil::Q5 & angle, const CWRUtil::Q5 & r2) const inline private
    {
        lineToXYAngleRadius2(canvas, circleCenterX, circleCenterY, angle, r2);
    }
References Circle::circleCenterX, Circle::circleCenterY, and Circle::lineToXYAngleRadius2().
Referenced by Circle::drawCanvasWidget().
lineToXYAngleRadius2()
FORCE_INLINE_FUNCTION void lineToXYAngleRadius2 (Canvas & canvas, const CWRUtil::Q5 & x, const CWRUtil::Q5 & y, const CWRUtil::Q5 & angle, const CWRUtil::Q5 & r2) const inline private
    {
        canvas.lineTo(x + ((r2 * CWRUtil::sine(angle)) / 2), y - ((r2 * CWRUtil::cosine(angle)) / 2));
    }
References CWRUtil::cosine(), and CWRUtil::sine().
Referenced by Circle::drawCanvasWidget(), and Circle::lineToAngleRadius2().
moveToAngleRadius2()
FORCE_INLINE_FUNCTION void moveToAngleRadius2 (Canvas & canvas, const CWRUtil::Q5 & angle, const CWRUtil::Q5 & r2) const inline private
    {
        canvas.moveTo(circleCenterX + ((r2 * CWRUtil::sine(angle)) / 2), circleCenterY - ((r2 * CWRUtil::cosine(angle)) / 2));
    }
References Circle::circleCenterX, Circle::circleCenterY, CWRUtil::cosine(), and CWRUtil::sine().
Referenced by Circle::drawCanvasWidget().
setArc() [1/2]
void setArc (const int16_t startAngle, const int16_t endAngle) inline
Sets the start and end angles in degrees of the Circle arc. 0 degrees is straight up (12 o'clock) and 90 degrees is to the left (3 o'clock). Any positive or negative degrees can be used to specify the part of the Circle to draw.
Parameters
startAngle The start degrees.
endAngle The end degrees.
See also
getArc, updateArcStart, updateArcEnd, updateArc
Note
The area containing the Circle is not invalidated.
Angles are given in degrees, so a full circle is 360.
    {
        setArc<int>(startAngle, endAngle);
    }
setArc() [2/2]
template<typename T > void setArc (const T startAngle, const T endAngle) inline
Sets the start and end angles in degrees of the Circle arc. 0 degrees is straight up (12 o'clock) and 90 degrees is to the left (3 o'clock). Any positive or negative degrees can be used to specify the part of the Circle to draw.
Template Parameters
T Generic type parameter, either int or float.
Parameters
startAngle The start degrees.
endAngle The end degrees.
See also
getArc, updateArcStart, updateArcEnd, updateArc
Note
The area containing the Circle is not invalidated.
Angles are given in degrees, so a full circle is 360.
    {
        circleArcAngleStart = CWRUtil::toQ5(startAngle);
        circleArcAngleEnd = CWRUtil::toQ5(endAngle);
    }
References Circle::circleArcAngleEnd, Circle::circleArcAngleStart, and CWRUtil::toQ5().
Referenced by CircleProgress::setStartEndAngle(), and Gauge::setStartEndAngle().
setCapPrecision()
void setCapPrecision (const int precision)
Sets the precision of the ends of the Circle arc. The precision is given in degrees where 180 is the default which results in a square ended arc (aka "butt cap"). 90 will draw "an arrow head" and smaller values gives a round cap. Larger values of precision results in faster rendering of the circle.
Parameters
precision The new cap precision.
Note
The circle is not invalidated.
The cap precision is not used if the circle is filled (if line width is zero) or when a full circle is drawn.
{
    if (precision < 1)
    {
        precision = 1;
    }
    if (precision > 180)
    {
        precision = 180;
    }
    circleCapArcIncrement = precision;
}
References Circle::circleCapArcIncrement.
Referenced by CircleProgress::setCapPrecision().
setCenter() [1/2]
void setCenter (const int16_t x, const int16_t y) inline
Sets the center of the Circle.
Parameters
x The x coordinate of center.
y The y coordinate of center.
See also
setRadius, setCircle, getCenter
Note
The area containing the Circle is not invalidated.
    {
        setCenter<int>(x, y);
    }
setCenter() [2/2]
template<typename T > void setCenter (const T x, const T y) inline
Sets the center of the Circle.
Template Parameters
T Generic type parameter, either int or float.
Parameters
x The x coordinate of center.
y The y coordinate of center.
See also
setRadius, setCircle, getCenter
Note
The area containing the Circle is not invalidated.
    {
        this->circleCenterX = CWRUtil::toQ5(x);
        this->circleCenterY = CWRUtil::toQ5(y);
    }
References Circle::circleCenterX, Circle::circleCenterY, and CWRUtil::toQ5().
Referenced by CircleProgress::setCenter().
setCircle() [1/2]
void setCircle (const int16_t x, const int16_t y, const int16_t r) inline
Sets the center and radius of the Circle.
Parameters
x The x coordinate of center.
y The y coordinate of center.
r The radius.
See also
setCenter, setRadius
Note
The area containing the Circle is not invalidated.
    {
        setCircle<int>(x, y, r);
    }
setCircle() [2/2]
template<typename T > void setCircle (const T x, const T y, const T r) inline
Sets the center and radius of the Circle.
Template Parameters
T Generic type parameter, either int or float.
Parameters
x The x coordinate of center.
y The y coordinate of center.
r The radius.
See also
setCenter, setRadius
Note
The area containing the Circle is not invalidated.
    {
        setCenter<T>(x, y);
        setRadius<T>(r);
    }
setLineWidth()
template<typename T > void setLineWidth (const T width) inline
Sets the line width for this Circle. If the line width is set to zero, the circle will be filled.
Template Parameters
T Generic type parameter, either int or float.
Parameters
width The width of the line measured in pixels.
Note
The area containing the Circle is not invalidated.
if the new line with is smaller than the old width, the circle should be invalidated before updating the width to ensure that the old circle is completely erased.
    {
        this->circleLineWidth = CWRUtil::toQ5(width);
        this->circleLineWidth = MAX(CWRUtil::toQ5(0), this->circleLineWidth);
    }
References Circle::circleLineWidth, MAX, and CWRUtil::toQ5().
Referenced by CircleProgress::setLineWidth().
setPixelCenter()
void setPixelCenter (int x, int y) inline
Sets the center of the circle / arc in the middle of a pixel. Normally the coordinate is between pixel number x and x+1 horizontally and between pixel y and y+1 vertically. This function will set the center in the middle of the pixel by adding 0.5 to both x and y.
Parameters
x The x coordinate of the center of the circle.
y The y coordinate of the center of the circle.
    {
        int32_t half = (int32_t)CWRUtil::toQ5(1) / 2;
        setCenter<CWRUtil::Q5>(CWRUtil::Q5((int32_t)CWRUtil::toQ5(x) + half), CWRUtil::Q5((int32_t)CWRUtil::toQ5(y) + half));
    }
References CWRUtil::toQ5().
Referenced by Gauge::setArcPosition(), and Gauge::setCenter().
setPrecision()
void setPrecision (const int precision)
Sets precision of the Circle drawing function. The number given as precision is the number of degrees used as step counter when drawing the line fragments around the circumference of the circle, five being a reasonable value. Higher values results in less nice circles but faster rendering and possibly sufficient for very small circles. Large circles might require a precision smaller than five to make the edge of the circle look nice and smooth.
Parameters
precision The precision measured in degrees.
Note
The circle is not invalidated.
{
    if (precision < 1)
    {
        precision = 1;
    }
    if (precision > 120)
    {
        precision = 120;
    }
    circleArcIncrement = precision;
}
References Circle::circleArcIncrement.
setRadius()
template<typename T > void setRadius (const T r) inline
Sets the radius of the Circle.
Template Parameters
T Generic type parameter, either int or float.
Parameters
r The radius.
See also
setCircle, setCenter, getRadius
Note
The area containing the Circle is not invalidated.
    {
        this->circleRadius = CWRUtil::toQ5(r);
        this->circleRadius = MAX(CWRUtil::toQ5(0), this->circleRadius);
    }
References Circle::circleRadius, MAX, and CWRUtil::toQ5().
Referenced by CircleProgress::setRadius().
updateArc() [1/2]
void updateArc (const CWRUtil::Q5 setStartAngleQ5, const CWRUtil::Q5 setEndAngleQ5) protected
Updates the start and end angle in degrees for this Circle arc.
Parameters
setStartAngleQ5 The new start angle in degrees.
setEndAngleQ5 The new end angle in degrees.
See also
setArc, getArc, updateArcStart, updateArcEnd
Note
The areas containing the updated Circle arcs are invalidated. As little as possible will be invalidated for best performance.
{
    CWRUtil::Q5 startAngleQ5 = setStartAngleQ5;
    CWRUtil::Q5 endAngleQ5 = setEndAngleQ5;
    if (circleArcAngleStart == startAngleQ5 && circleArcAngleEnd == endAngleQ5)
    {
        return;
    }
    // Make sure old start < end
    if (circleArcAngleStart > circleArcAngleEnd)
    {
        CWRUtil::Q5 const tmp = circleArcAngleStart;
        circleArcAngleStart = circleArcAngleEnd;
        circleArcAngleEnd = tmp;
    }
    // Make sure new start < end
    if (startAngleQ5 > endAngleQ5)
    {
        CWRUtil::Q5 const tmp = startAngleQ5;
        startAngleQ5 = endAngleQ5;
        endAngleQ5 = tmp;
    }
    // Nice constant
    const CWRUtil::Q5 _360 = CWRUtil::toQ5<int>(360);
    // Get old circle range start in [0..360[
    if (circleArcAngleStart >= _360)
    {
        const int x = (circleArcAngleStart / _360).to<int>();
        circleArcAngleStart -= _360 * x;
        circleArcAngleEnd -= _360 * x;
    }
    else if (circleArcAngleStart < 0)
    {
        const int x = 1 + ((-circleArcAngleStart) / _360).to<int>();
        circleArcAngleStart += _360 * x;
        circleArcAngleEnd += _360 * x;
    }
    // Detect full circle
    if ((circleArcAngleEnd - circleArcAngleStart) > _360)
    {
        circleArcAngleEnd = circleArcAngleStart + _360;
    }
    // Get new circle range start in [0..360[
    if (startAngleQ5 >= _360)
    {
        const int x = (startAngleQ5 / _360).to<int>();
        startAngleQ5 -= _360 * x;
        endAngleQ5 -= _360 * x;
    }
    else if (startAngleQ5 < 0)
    {
        const int x = 1 + (-startAngleQ5 / _360).to<int>();
        startAngleQ5 += _360 * x;
        endAngleQ5 += _360 * x;
    }
    // Detect full circle
    if ((endAngleQ5 - startAngleQ5) >= _360)
    {
        // Align full new circle with old start.
        // So old[90..270] -> new[0..360] becomes new[90..450] for smaller invalidated area
        startAngleQ5 = circleArcAngleStart;
        endAngleQ5 = startAngleQ5 + _360;
    }
    else if ((circleArcAngleEnd - circleArcAngleStart) >= _360)
    {
        // New circle is not full, but old is. Align old circle with new.
        // So old[0..360] -> new[90..270] becomes old[90..450] for smaller invalidated area
        circleArcAngleStart = startAngleQ5;
        circleArcAngleEnd = circleArcAngleStart + _360;
    }
    // New start is after old end. Could be overlap
    // if old[10..30]->new[350..380] becomes new[-10..20]
    if (startAngleQ5 > circleArcAngleEnd && endAngleQ5 - _360 >= circleArcAngleStart)
    {
        startAngleQ5 -= _360;
        endAngleQ5 -= _360;
    }
    // Same as above but for old instead of new
    if (circleArcAngleStart > endAngleQ5 && circleArcAngleEnd - _360 >= startAngleQ5)
    {
        circleArcAngleStart -= _360;
        circleArcAngleEnd -= _360;
    }
    Rect r;
    if (startAngleQ5 > circleArcAngleEnd || endAngleQ5 < circleArcAngleStart)
    {
        // Arcs do not overlap. Invalidate both arcs.
        r = getMinimalRect(circleArcAngleStart, circleArcAngleEnd);
        invalidateRect(r);
        r = getMinimalRect(startAngleQ5, endAngleQ5);
        invalidateRect(r);
    }
    else
    {
        // Arcs overlap. Invalidate both ends.
        if (circleArcAngleStart != startAngleQ5)
        {
            r = getMinimalRectForUpdatedStartAngle(startAngleQ5);
            invalidateRect(r);
        }
        if (circleArcAngleEnd != endAngleQ5)
        {
            r = getMinimalRectForUpdatedEndAngle(endAngleQ5);
            invalidateRect(r);
        }
    }
    circleArcAngleStart = setStartAngleQ5;
    circleArcAngleEnd = setEndAngleQ5;
}
References Circle::circleArcAngleEnd, Circle::circleArcAngleStart, Circle::getMinimalRect(), Circle::getMinimalRectForUpdatedEndAngle(), Circle::getMinimalRectForUpdatedStartAngle(), and Drawable::invalidateRect().
updateArc() [2/2]
template<typename T > void updateArc (const T startAngle, const T endAngle) inline
Updates the start and end angle in degrees for this Circle arc.
Template Parameters
T Generic type parameter, either int or float.
Parameters
startAngle The new start angle in degrees.
endAngle The new end angle in degrees.
See also
setArc, getArc, updateArcStart, updateArcEnd
Note
The areas containing the updated Circle arcs are invalidated. As little as possible will be invalidated for best performance.
Angles are given in degrees, so a full circle is 360.
    {
        updateArc(CWRUtil::toQ5(startAngle), CWRUtil::toQ5(endAngle));
    }
References CWRUtil::toQ5(), and Circle::updateArc().
Referenced by Circle::updateArc().
updateArcEnd()
template<typename T > void updateArcEnd (const T endAngle) inline
Updates the end angle in degrees for this Circle arc.
Template Parameters
T Generic type parameter, either int or float.
Parameters
endAngle The end angle in degrees.
See also
setArc, updateArcStart, updateArc
Note
The area containing the updated Circle arc is invalidated.
Angles are given in degrees, so a full circle is 360.
    {
        CWRUtil::Q5 endAngleQ5 = CWRUtil::toQ5(endAngle);
        if (circleArcAngleEnd == endAngleQ5)
        {
            return;
        }
        Rect minimalRect = getMinimalRectForUpdatedEndAngle(endAngleQ5);
        circleArcAngleEnd = endAngleQ5;
        invalidateRect(minimalRect);
    }
References Circle::circleArcAngleEnd, Circle::getMinimalRectForUpdatedEndAngle(), Drawable::invalidateRect(), and CWRUtil::toQ5().
Referenced by CircleProgress::setValue(), and Gauge::setValue().
updateArcStart()
template<typename T > void updateArcStart (const T startAngle) inline
Updates the start angle in degrees for this Circle arc.
Template Parameters
T Generic type parameter, either int or float.
Parameters
startAngle The start angle in degrees.
See also
setArc, updateArcEnd, updateArc
Note
The area containing the updated Circle arc is invalidated.
Angles are given in degrees, so a full circle is 360.
    {
        CWRUtil::Q5 startAngleQ5 = CWRUtil::toQ5(startAngle);
        if (circleArcAngleStart == startAngleQ5)
        {
            return;
        }
        Rect minimalRect = getMinimalRectForUpdatedStartAngle(startAngleQ5);
        circleArcAngleStart = startAngleQ5;
        invalidateRect(minimalRect);
    }
References Circle::circleArcAngleStart, Circle::getMinimalRectForUpdatedStartAngle(), Drawable::invalidateRect(), and CWRUtil::toQ5().
updateMinMaxAngleLine()
FORCE_INLINE_FUNCTION void updateMinMaxAngleLine (const CWRUtil::Q5 & angle, const CWRUtil::Q5 & halfLineWidth, CWRUtil::Q5 & xMin, CWRUtil::Q5 & xMax, CWRUtil::Q5 & yMin, CWRUtil::Q5 & yMax) const inline private
    {
        const CWRUtil::Q5 xNew = circleCenterX + (circleRadius * CWRUtil::sine(angle));
        updateMinMaxX(xNew - halfLineWidth, xMin, xMax);
        updateMinMaxX(xNew + halfLineWidth, xMin, xMax);
        const CWRUtil::Q5 yNew = circleCenterY - (circleRadius * CWRUtil::cosine(angle));
        updateMinMaxY(yNew - halfLineWidth, yMin, yMax);
        updateMinMaxY(yNew + halfLineWidth, yMin, yMax);
    }
References Circle::circleCenterX, Circle::circleCenterY, Circle::circleRadius, CWRUtil::cosine(), CWRUtil::sine(), Circle::updateMinMaxX(), and Circle::updateMinMaxY().
Referenced by Circle::calculateMinimalRect().
updateMinMaxAngleSolid()
FORCE_INLINE_FUNCTION void updateMinMaxAngleSolid (const CWRUtil::Q5 & angle, CWRUtil::Q5 & xMin, CWRUtil::Q5 & xMax, CWRUtil::Q5 & yMin, CWRUtil::Q5 & yMax) const inline private
    {
        updateMinMaxX(circleCenterX + (circleRadius * CWRUtil::sine(angle)), xMin, xMax);
        updateMinMaxY(circleCenterY - (circleRadius * CWRUtil::cosine(angle)), yMin, yMax);
    }
References Circle::circleCenterX, Circle::circleCenterY, Circle::circleRadius, CWRUtil::cosine(), CWRUtil::sine(), Circle::updateMinMaxX(), and Circle::updateMinMaxY().
Referenced by Circle::calculateMinimalRect().
updateMinMaxX()
FORCE_INLINE_FUNCTION void updateMinMaxX (const CWRUtil::Q5 & xNew, CWRUtil::Q5 & xMin, CWRUtil::Q5 & xMax) const inline private
    {
        if (xNew < xMin)
        {
            xMin = xNew;
        }
        if (xNew > xMax)
        {
            xMax = xNew;
        }
    }
Referenced by Circle::calculateMinimalRect(), Circle::updateMinMaxAngleLine(), and Circle::updateMinMaxAngleSolid().
updateMinMaxY()
FORCE_INLINE_FUNCTION void updateMinMaxY (const CWRUtil::Q5 & yNew, CWRUtil::Q5 & yMin, CWRUtil::Q5 & yMax) const inline private
    {
        if (yNew < yMin)
        {
            yMin = yNew;
        }
        if (yNew > yMax)
        {
            yMax = yNew;
        }
    }
Referenced by Circle::calculateMinimalRect(), Circle::updateMinMaxAngleLine(), and Circle::updateMinMaxAngleSolid().
Member Data Documentation
circleArcAngleEnd
CWRUtil::Q5 circleArcAngleEnd private
Referenced by Circle::drawCanvasWidget(), Circle::getArc(), Circle::getArcEnd(), Circle::getArcEnd(), Circle::getMinimalRect(), Circle::getMinimalRectForUpdatedEndAngle(), Circle::getMinimalRectForUpdatedStartAngle(), Circle::setArc(), Circle::updateArc(), and Circle::updateArcEnd().
circleArcAngleStart
CWRUtil::Q5 circleArcAngleStart private
Referenced by Circle::drawCanvasWidget(), Circle::getArc(), Circle::getArcStart(), Circle::getArcStart(), Circle::getMinimalRect(), Circle::getMinimalRectForUpdatedEndAngle(), Circle::getMinimalRectForUpdatedStartAngle(), Circle::setArc(), Circle::updateArc(), and Circle::updateArcStart().
circleArcIncrement
uint8_t circleArcIncrement private
Referenced by Circle::drawCanvasWidget(), Circle::getMinimalRectForUpdatedEndAngle(), Circle::getMinimalRectForUpdatedStartAngle(), Circle::getPrecision(), and Circle::setPrecision().
circleCapArcIncrement
uint8_t circleCapArcIncrement private
Referenced by Circle::drawCanvasWidget(), Circle::getCapPrecision(), and Circle::setCapPrecision().
circleCenterX
CWRUtil::Q5 circleCenterX private
Referenced by Circle::calculateMinimalRect(), Circle::drawCanvasWidget(), Circle::getCenter(), Circle::lineToAngleRadius2(), Circle::moveToAngleRadius2(), Circle::setCenter(), Circle::updateMinMaxAngleLine(), and Circle::updateMinMaxAngleSolid().
circleCenterY
CWRUtil::Q5 circleCenterY private
Referenced by Circle::calculateMinimalRect(), Circle::drawCanvasWidget(), Circle::getCenter(), Circle::lineToAngleRadius2(), Circle::moveToAngleRadius2(), Circle::setCenter(), Circle::updateMinMaxAngleLine(), and Circle::updateMinMaxAngleSolid().
circleLineWidth
CWRUtil::Q5 circleLineWidth private
Referenced by Circle::calculateMinimalRect(), Circle::drawCanvasWidget(), Circle::getLineWidth(), and Circle::setLineWidth().
circleRadius
CWRUtil::Q5 circleRadius private
Referenced by Circle::drawCanvasWidget(), Circle::getRadius(), Circle::setRadius(), Circle::updateMinMaxAngleLine(), and Circle::updateMinMaxAngleSolid().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/Circle.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/Circle.cpp