Battery Simulator Documentation: LCD1bpp
LCD1bpp
#include "LCD1bpp.hpp"
Classes
class bwRLEdata
Public Member Functions
virtual uint8_t bitDepth () const
virtual void blitCopy (const uint16_t *sourceData, const Rect &source, const Rect &blitRect, uint8_t alpha, bool hasTransparentPixels)
virtual void blitCopy (const uint8_t *sourceData, Bitmap::BitmapFormat sourceFormat, const Rect &source, const Rect &blitRect, uint8_t alpha, bool hasTransparentPixels)
virtual void copyAreaFromTFTToClientBuffer (const Rect &region)
virtual uint16_t * copyFrameBufferRegionToMemory (const Rect &visRegion, const Rect &absRegion, const BitmapId bitmapId)
virtual Rect copyFrameBufferRegionToMemory (const Rect &visRegion, const Rect &absRegion, uint8_t *dst, int16_t dstWidth, int16_t dstHeight)
virtual void drawPartialBitmap (const Bitmap &bitmap, int16_t x, int16_t y, const Rect &rect, uint8_t alpha=255, bool useOptimized=true)
void enableTextureMapperAll () const
virtual void fillBuffer (uint8_t *const destination, uint16_t pixelStride, const Rect &rect, const colortype color, const uint8_t alpha)
virtual void fillRect (const Rect &rect, colortype color, uint8_t alpha=255)
virtual Bitmap::BitmapFormat framebufferFormat () const
virtual uint16_t framebufferStride () const
Public Member Functions inherited from LCD
LCD ()
virtual ~LCD ()
uint16_t * copyFrameBufferRegionToMemory (const Rect &region, const BitmapId bitmapId=BITMAP_ANIMATION_STORAGE)
void drawString (Rect widgetArea, const Rect &invalidatedArea, const StringVisuals &stringVisuals, const Unicode::UnicodeChar *format,...)
virtual void drawTextureMapQuad (const DrawingSurface &dest, const Point3D *vertices, const TextureSurface &texture, const Rect &absoluteRect, const Rect &dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha=255, uint16_t subDivisionSize=12)
virtual void drawTextureMapTriangle (const DrawingSurface &dest, const Point3D *vertices, const TextureSurface &texture, const Rect &absoluteRect, const Rect &dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha=255, uint16_t subDivisionSize=12)
colortype getDefaultColor () const
virtual void setDefaultColor (colortype color)
void setVectorFontRenderer (VectorFontRenderer *renderer)
virtual bool supportDynamicBitmapDrawing (const Bitmap::BitmapFormat format)
Static Public Member Functions
static FORCE_INLINE_FUNCTION uint16_t getFramebufferStride ()
static FORCE_INLINE_FUNCTION uint8_t getNativeColor (colortype color)
static FORCE_INLINE_FUNCTION uint8_t getNativeColorFromRGB (uint8_t red, uint8_t green, uint8_t blue)
Static Public Member Functions inherited from LCD
static FORCE_INLINE_FUNCTION uint8_t div255 (uint16_t num)
static FORCE_INLINE_FUNCTION uint32_t div255g (uint32_t pixelxAlpha)
static FORCE_INLINE_FUNCTION uint32_t div255rb (uint32_t pixelxAlpha)
Protected Member Functions
virtual void blitCopyRLE (const uint16_t *_sourceData, const Rect &source, const Rect &blitRect, uint8_t alpha)
void copyRect (const uint8_t *srcAddress, int16_t srcStride, uint8_t srcPixelOffset, uint8_t *RESTRICT dstAddress, int16_t dstStride, uint8_t dstPixelOffset, int16_t width, int16_t height) const
virtual void drawGlyph (uint16_t *wbuf16, Rect widgetArea, int16_t x, int16_t y, uint16_t offsetX, uint16_t offsetY, const Rect &invalidatedArea, const GlyphNode *glyph, const uint8_t *glyphData, uint8_t byteAlignRow, colortype color, uint8_t bitsPerPixel, uint8_t alpha, TextRotation rotation)
virtual void drawTextureMapScanLine (const DrawingSurface &, const Gradients &, const Edge *, const Edge *, const TextureSurface &, const Rect &, const Rect &, RenderingVariant, uint8_t, uint16_t)
Protected Member Functions inherited from LCD
void drawStringLTR (const Rect &widgetArea, const Rect &invalidatedArea, const StringVisuals &visuals, const Unicode::UnicodeChar *format, va_list pArg)
void drawStringRTL (const Rect &widgetArea, const Rect &invalidatedArea, const StringVisuals &visuals, const Unicode::UnicodeChar *format, va_list pArg)
virtual DrawTextureMapScanLineBase * getTextureMapperDrawScanLine (const TextureSurface &texture, RenderingVariant renderVariant, uint8_t alpha)
Static Protected Member Functions
static void fillMemory (void *RESTRICT dst, colortype color, uint16_t bytesToFill)
static int nextLine (bool rotatedDisplay, TextRotation textRotation)
static int nextPixel (bool rotatedDisplay, TextRotation textRotation)
Static Protected Member Functions inherited from LCD
static FORCE_INLINE_FUNCTION uint8_t getAlphaFromA4 (const uint16_t *data, uint32_t offset)
static uint16_t getNumLines (TextProvider &textProvider, WideTextAction wideTextAction, TextDirection textDirection, const Font *font, int16_t width)
static int realX (const Rect &widgetArea, int16_t x, int16_t y, TextRotation rotation)
static int realY (const Rect &widgetArea, int16_t x, int16_t y, TextRotation rotation)
static void rotateRect (Rect &rect, const Rect &canvas, const TextRotation rotation)
static uint16_t stringWidth (TextProvider &textProvider, const Font &font, const int numChars, TextDirection textDirection)
Additional Inherited Members
Static Protected Attributes inherited from LCD
static colortype defaultColor
Default Color to use when displaying transparency-only elements, e.g. A4 bitmaps.
static const uint16_t newLine = 10
NewLine value.
Detailed Description
This class contains the various low-level drawing routines for drawing bitmaps, texts and rectangles on 1 bits per pixel displays.
See also
LCD
Note
All coordinates are expected to be in absolute coordinates!
Member Function Documentation
bitDepth()
virtual uint8_t bitDepth () const inline virtual
Number of bits per pixel used by the display.
Returns
The number of bits per pixel.
Implements LCD.
    {
        return 1;
    }
blitCopy() [1/2]
virtual void blitCopy (const uint16_t * sourceData, const Rect & source, const Rect & blitRect, uint8_t alpha, bool hasTransparentPixels) virtual
Blits (directly copies) a block of data to the framebuffer, performing alpha blending (and tranparency keying) as specified. Performs a software blend if HAL does not support BLIT_COPY_WITH_ALPHA and alpha != 255 (solid).
Parameters
sourceData The source array pointer (points to the beginning of the data). The sourceData must be stored in a format suitable for the selected display.
source The position and dimensions of the source. The x and y of this rect should both be 0.
blitRect A rectangle describing what region of the sourceData is to be copied to the framebuffer.
alpha The alpha value to use for blending ranging from 0=invisible to 255=solid=no blending.
hasTransparentPixels If true, this data copy contains transparent pixels and require hardware support for that to be enabled.
Implements LCD.
blitCopy() [2/2]
virtual void blitCopy (const uint8_t * sourceData, Bitmap::BitmapFormat sourceFormat, const Rect & source, const Rect & blitRect, uint8_t alpha, bool hasTransparentPixels) virtual
Blits (directly copies) a block of data to the framebuffer, performing alpha blending (and tranparency keying) as specified. Performs a software blend if HAL does not support BLIT_COPY_WITH_ALPHA and alpha < 255 (solid).
If the display does not support the specified sourceFormat, an assert will be raised.
Parameters
sourceData The source array pointer (points to the beginning of the data). The sourceData must be stored in a format suitable for the selected display.
sourceFormat The bitmap format used in the source data.
source The position and dimensions of the source. The x and y of this rect should both be 0.
blitRect A rectangle describing what region of the sourceData is to be copied to the framebuffer.
alpha The alpha value to use for blending ranging from 0=invisible to 255=solid=no blending.
hasTransparentPixels If true, this data copy contains transparent pixels and require hardware support for that to be enabled.
Implements LCD.
blitCopyRLE()
virtual void blitCopyRLE (const uint16_t * _sourceData, const Rect & source, const Rect & blitRect, uint8_t alpha) protected virtual
Blits a run-length encoded2D source-array to the framebuffer if alpha > zero.
Parameters
_sourceData The source-array pointer (points to the beginning of the data). Data stored in RLE format, where each byte indicates number of pixels with certain color, alternating between black and white. First byte represents black.
source The location and dimensions of the source.
blitRect A rectangle describing what region is to be drawn.
alpha The alpha value to use for blending (0 = invisible, otherwise solid).
copyAreaFromTFTToClientBuffer()
virtual void copyAreaFromTFTToClientBuffer (const Rect & region) virtual
Copies part of the displayed framebuffer to current framebuffer. The region given is the absolute region on screen.
Parameters
region A rectangle describing what region of the displayed framebuffer is to be copied to the framebuffer.
Note
The copy is performed only when double buffering is enabled. Otherwise the given region in current framebuffer is left untouched.
Implements LCD.
copyFrameBufferRegionToMemory() [1/2]
virtual uint16_t * copyFrameBufferRegionToMemory (const Rect & visRegion, const Rect & absRegion, const BitmapId bitmapId) virtual
Copies part of the framebuffer to the data section of a bitmap. The bitmap must be a dynamic bitmap or animation storage (BITMAP_ANIMATION_STORAGE). The two regions given are the visible region and the absolute region on screen. This is used to copy only a part of the framebuffer. This might be the case if a SnapshotWidget is placed inside a Container where parts of the SnapshowWidget is outside the area defined by the Container. The visible region must be completely inside the absolute region.
Parameters
visRegion The visible region.
absRegion The absolute region.
bitmapId Identifier for the bitmap.
Returns
Null if it fails, else a pointer to the data in the given bitmap.
See also
blitCopy, copyFrameBufferRegionToMemory(const Rect&, const Rect&, uint8_t*, int16_t, int16_t)
Note
There is only one instance of animation storage. The content of the bitmap data /animation storage outside the given region is left untouched.
Implements LCD.
copyFrameBufferRegionToMemory() [2/2]
virtual Rect copyFrameBufferRegionToMemory (const Rect & visRegion, const Rect & absRegion, uint8_t * dst, int16_t dstWidth, int16_t dstHeight) virtual
Copies part of the framebuffer to memory. The memory is assumed to have the same format as the framebuffer. The two regions given are the visible region and the absolute region on screen. This is used to copy only a part of the framebuffer. This might be the case if a SnapshotWidget is placed inside a Container where parts of the SnapshowWidget is outside the area defined by the Container. The visible region must be completely inside the absolute region.
Parameters
visRegion The visible region.
absRegion The absolute region.
[in,out] dst Destination memory in same format as the framebuffer.
dstWidth Width of the destination.
dstHeight Height of the destination.
Returns
The rect that was actually copied to the destination buffer.
See also
blitCopy, copyFrameBufferRegionToMemory(const Rect&, const Rect&, const BitmapId)
Note
There is only one instance of animation storage. The content of the bitmap data /animation storage outside the given region is left untouched.
Implements LCD.
copyRect()
void copyRect (const uint8_t * srcAddress, int16_t srcStride, uint8_t srcPixelOffset, uint8_t *RESTRICT dstAddress, int16_t dstStride, uint8_t dstPixelOffset, int16_t width, int16_t height) const protected
Copies a rectangular area from the framebuffer til a givene memory address, which is typically in the animation storage or a dynamic bitmap.
Parameters
srcAddress Source address (byte address).
srcStride Source stride (number of bytes to advance to next line).
srcPixelOffset Source pixel offset (first pixel in first source byte).
[in] dstAddress If destination address (byte address).
dstStride Destination stride (number of bytes to advance to next line).
dstPixelOffset Destination pixel offset (first pixel in destination byte).
width The width of area (in pixels).
height The height of area (in pixels).
drawGlyph()
virtual void drawGlyph (uint16_t * wbuf16, Rect widgetArea, int16_t x, int16_t y, uint16_t offsetX, uint16_t offsetY, const Rect & invalidatedArea, const GlyphNode * glyph, const uint8_t * glyphData, uint8_t byteAlignRow, colortype color, uint8_t bitsPerPixel, uint8_t alpha, TextRotation rotation) protected virtual
Private version of draw-glyph with explicit destination buffer pointer argument. For all parameters (except the buffer pointer) see the public function drawString().
Parameters
[out] wbuf16 The destination (frame) buffer to draw to.
widgetArea The canvas to draw the glyph inside.
x Horizontal offset to start drawing the glyph.
y Vertical offset to start drawing the glyph.
offsetX Horizontal offset in the glyph to start drawing from.
offsetY Vertical offset in the glyph to start drawing from.
invalidatedArea The area to draw inside.
glyph Specifications of the glyph to draw.
glyphData Data containing the actual glyph (dense format)
byteAlignRow Each row of glyph data starts in a new byte.
color The color of the glyph.
bitsPerPixel Bit depth of the glyph.
alpha The transparency of the glyph.
rotation Rotation to do before drawing the glyph.
Implements LCD.
drawPartialBitmap()
virtual void drawPartialBitmap (const Bitmap & bitmap, int16_t x, int16_t y, const Rect & rect, uint8_t alpha = 255, bool useOptimized = true) virtual
Draws all (or a part) of a bitmap. The coordinates of the corner of the bitmap is given in (x, y) and rect describes which part of the bitmap should be drawn. The bitmap can be drawn as it is or more or less transparent depending on the value of alpha. The value of alpha is independent of the transparency of the individual pixels of the given bitmap.
Parameters
bitmap The bitmap to draw.
x The absolute x coordinate to place (0, 0) of the bitmap on the screen.
y The absolute y coordinate to place (0, 0) of the bitmap on the screen.
rect A rectangle describing what region of the bitmap is to be drawn.
alpha (Optional) Optional alpha value ranging from 0=invisible to 255=solid. Default is 255 (solid).
useOptimized (Optional) if false, do not attempt to substitute (parts of) this bitmap with faster fillrects.
Implements LCD.
drawTextureMapScanLine()
virtual void drawTextureMapScanLine (const DrawingSurface & dest, const Gradients & gradients, const Edge * leftEdge, const Edge * rightEdge, const TextureSurface & texture, const Rect & absoluteRect, const Rect & dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha, uint16_t subDivisionSize) inline protected virtual
Draw scan line. Draw one horizontal line of the texture map on screen. The scan line will be drawn using perspective correct texture mapping. The appearance of the line is determined by the left and right edge and the gradients structure. The edges contain the information about the x,y,z coordinates of the left and right side respectively and also information about the u,v coordinates of the texture map used. The gradients structure contains information about how to interpolate all the values across the scan line. The data drawn should be present in the texture argument.
The scan line will be drawn using the additional arguments. The scan line will be placed and clipped using the absolute and dirty rectangles The alpha will determine how the scan line should be alpha blended. The subDivisionSize will determine the size of the piecewise affine texture mapped lines.
Parameters
dest The description of where the texture is drawn - can be used to issue a draw off screen.
gradients The gradients using in interpolation across the scan line.
leftEdge The left edge of the scan line.
rightEdge The right edge of the scan line.
texture The texture.
absoluteRect The containing rectangle in absolute coordinates.
dirtyAreaAbsolute The dirty area in absolute coordinates.
renderVariant The render variant - includes the algorithm and the pixel format.
alpha The alpha.
subDivisionSize The size of the subdivisions of the scan line. A value of 1 will give a completely perspective correct texture mapped scan line. A large value will give an affine texture mapped scan line.
Reimplemented from LCD.
    {
        assert(false && "Texture mapping not supported for 1bpp");
    }
enableTextureMapperAll()
void enableTextureMapperAll () const
Enables the texture mappers for all image formats. Currently texture mapping is not supported on 1bpp displays, so this function does not do anything. It is merely included to allow function enableTextureMapperAll() to be called on any subclass of LCD.
fillBuffer()
virtual void fillBuffer (uint8_t *const destination, uint16_t pixelStride, const Rect & rect, const colortype color, const uint8_t alpha) virtual
Draws a filled rectangle in destination memory using the specified color and opacity. The destination memory must have the same format as the display framebuffer. By default the rectangle will be drawn as a solid box. The rectangle can be drawn with transparency by specifying alpha from 0=invisible to 255=solid.
Parameters
[in] destination The start of the memory area to fill.
pixelStride The pixel stride, i.e. number of pixels in a row.
rect The rectangle to fill absolute coordinates.
color The rectangle color.
alpha The rectangle opacity, from 0=invisible to 255=solid.
Note
The pixelStride is rounded up to nearest whole bytes for displays with more than one pixel per byte (LCD1bpp, LCD2bpp and LCD4bpp)
Implements LCD.
fillMemory()
static void fillMemory (void *RESTRICT dst, colortype color, uint16_t bytesToFill) static protected
Fill memory efficiently. Try to get 32bit aligned or 16bit aligned and then copy as quickly as possible.
Parameters
[out] dst Pointer to memory to fill.
color Color to write to memory, either 0 => 0x00000000 or 1 => 0xFFFFFFFF.
bytesToFill Number of bytes to fill.
fillRect()
virtual void fillRect (const Rect & rect, colortype color, uint8_t alpha = 255) virtual
Draws a filled rectangle in the framebuffer in the specified color and opacity. By default the rectangle will be drawn as a solid box. The rectangle can be drawn with transparency by specifying alpha from 0=invisible to 255=solid.
Parameters
rect The rectangle to draw in absolute display coordinates.
color The rectangle color.
alpha (Optional) The rectangle opacity, from 0=invisible to 255=solid.
See also
fillBuffer
Implements LCD.
framebufferFormat()
virtual Bitmap::BitmapFormat framebufferFormat () const inline virtual
Framebuffer format used by the display.
Returns
A Bitmap::BitmapFormat.
Implements LCD.
    {
        return Bitmap::BW;
    }
References Bitmap::BW.
framebufferStride()
virtual uint16_t framebufferStride () const inline virtual
Framebuffer stride in bytes. The distance (in bytes) from the start of one framebuffer row, to the next.
Returns
The number of bytes in one framebuffer row.
Implements LCD.
    {
        return getFramebufferStride();
    }
References LCD1bpp::getFramebufferStride().
getFramebufferStride()
static FORCE_INLINE_FUNCTION uint16_t getFramebufferStride () inline static
Framebuffer stride in bytes. The distance (in bytes) from the start of one framebuffer row, to the next.
Returns
The number of bytes in one framebuffer row.
    {
        assert(HAL::FRAME_BUFFER_WIDTH > 0 && "HAL has not been initialized yet");
        return (HAL::FRAME_BUFFER_WIDTH + 7) / 8;
    }
References HAL::FRAME_BUFFER_WIDTH.
Referenced by LCD1bpp::framebufferStride().
getNativeColor()
static FORCE_INLINE_FUNCTION uint8_t getNativeColor (colortype color) inline static
Generates a color representation to be used on the LCD, based on 24 bit RGB values.
Parameters
color The color.
Returns
The color representation depending on LCD color format.
    {
        return getNativeColorFromRGB(Color::getRed(color), Color::getGreen(color), Color::getBlue(color));
    }
References Color::getBlue(), Color::getGreen(), LCD1bpp::getNativeColorFromRGB(), and Color::getRed().
Referenced by PainterBW::setColor().
getNativeColorFromRGB()
static FORCE_INLINE_FUNCTION uint8_t getNativeColorFromRGB (uint8_t red, uint8_t green, uint8_t blue) inline static
Generates a color representation to be used on the LCD, based on 24 bit RGB values.
Parameters
red Value of the red part (0-255).
green Value of the green part (0-255).
blue Value of the blue part (0-255).
Returns
The color representation depending on LCD color format.
    {
        // Find the GRAY value (http://en.wikipedia.org/wiki/Luma_%28video%29) rounded to nearest integer
        return (red * 54 + green * 183 + blue * 19) >> 15;
    }
Referenced by LCD1bpp::getNativeColor().
nextLine()
static int nextLine (bool rotatedDisplay, TextRotation textRotation) static protected
Find out how much to advance in the display buffer to get to the next line.
Parameters
rotatedDisplay Is the display running in portrait mode?
textRotation Rotation to perform.
Returns
How much to advance to get to the next line.
nextPixel()
static int nextPixel (bool rotatedDisplay, TextRotation textRotation) static protected
Find out how much to advance in the display buffer to get to the next pixel.
Parameters
rotatedDisplay Is the display running in portrait mode?
textRotation Rotation to perform.
Returns
How much to advance to get to the next pixel.
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/platform/driver/lcd/LCD1bpp.hpp