Battery Simulator Documentation: CachedFont
CachedFont
#include "CachedFont.hpp"
Public Member Functions
CachedFont ()
CachedFont (const struct touchgfx::BinaryFontData *data, FontId id, FontCache *_cache, const GeneratedFont *_flashFont)
virtual const FontContextualFormsTable * getContextualFormsTable () const
FontId getFontId () const
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, const uint8_t *&pixelData, uint8_t &bitsPerPixel) const
virtual const uint16_t * getGSUBTable () const
virtual int8_t getKerning (Unicode::UnicodeChar prevChar, const GlyphNode *glyph) const
virtual const uint8_t * getPixelData (const GlyphNode *glyph) const
virtual void setContextualFormsTable (const FontContextualFormsTable *table)
void setFontCache (FontCache &cache)
virtual void setGSUBTable (const uint16_t *table)
Public Member Functions inherited from GeneratedFont
GeneratedFont (const GlyphNode *glyphs, uint16_t numGlyphs, uint16_t height, uint16_t baseline, uint8_t pixAboveTop, uint8_t pixBelowBottom, uint8_t bitsPerPixel, uint8_t byteAlignRow, uint8_t maxLeft, uint8_t maxRight, const uint8_t *const *glyphDataInternalFlash, const KerningNode *kerningList, const Unicode::UnicodeChar fallbackChar, const Unicode::UnicodeChar ellipsisChar, const uint16_t *const gsubData, const FontContextualFormsTable *formsTable)
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode) const
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, const uint8_t *&pixelData, uint8_t &bitsPerPixel) const
virtual const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, const uint8_t *&pixelData, uint8_t &bitsPerPixel) const =0
Public Member Functions inherited from ConstFont
ConstFont (const GlyphNode *glyphs, uint16_t numGlyphs, uint16_t height, uint16_t baseline, uint8_t pixAboveTop, uint8_t pixBelowBottom, uint8_t bitsPerPixel, uint8_t byteAlignRow, uint8_t maxLeft, uint8_t maxRight, const Unicode::UnicodeChar fallbackChar, const Unicode::UnicodeChar ellipsisChar)
const GlyphNode * find (Unicode::UnicodeChar unicode) const
Public Member Functions inherited from Font
virtual ~Font ()
virtual FORCE_INLINE_FUNCTION uint16_t getBaseline () const
virtual FORCE_INLINE_FUNCTION uint8_t getBitsPerPixel () const
virtual FORCE_INLINE_FUNCTION uint8_t getByteAlignRow () const
virtual uint16_t getCharWidth (const Unicode::UnicodeChar c) const
virtual Unicode::UnicodeChar getEllipsisChar () const
virtual Unicode::UnicodeChar getFallbackChar () const
virtual FORCE_INLINE_FUNCTION uint16_t getHeight () const
FORCE_INLINE_FUNCTION uint8_t getMaxPixelsLeft () const
FORCE_INLINE_FUNCTION uint8_t getMaxPixelsRight () const
virtual uint16_t getNumberOfLines (const Unicode::UnicodeChar *text,...) const
FORCE_INLINE_FUNCTION uint16_t getPixelsAboveTop () const
FORCE_INLINE_FUNCTION uint16_t getPixelsBelowBottom () const
virtual float getScaleFactor () const
virtual int16_t getSpacingAbove (const Unicode::UnicodeChar *text,...) const
virtual uint16_t getStringWidth (const Unicode::UnicodeChar *text,...) const
virtual uint16_t getStringWidth (TextDirection textDirection, const Unicode::UnicodeChar *text,...) const
virtual bool isVectorBasedFont () const
TOUCHGFX_DEPRECATED ("Please use getBaseline() instead.", virtual uint16_t getFontHeight() const)
TOUCHGFX_DEPRECATED ("Please use getHeight() instead.", virtual uint16_t getMaxTextHeight(const Unicode::UnicodeChar *text,...) const)
TOUCHGFX_DEPRECATED ("Please use getHeight() instead.", virtual uint16_t getMinimumTextHeight() const)
Private Attributes
FontCache * cache
const GeneratedFont * flashFont
FontId fontId
Additional Inherited Members
Static Public Member Functions inherited from Font
static FORCE_INLINE_FUNCTION bool isInvisibleZeroWidth (Unicode::UnicodeChar character)
Protected Member Functions inherited from GeneratedFont
GeneratedFont ()
Protected Member Functions inherited from Font
Font (uint16_t height, uint16_t baseline, uint8_t pixAboveTop, uint8_t pixBelowBottom, uint8_t bitsPerPixel, uint8_t byteAlignRow, uint8_t maxLeft, uint8_t maxRight, const Unicode::UnicodeChar fallbackChar, const Unicode::UnicodeChar ellipsisChar)
uint16_t getStringWidthLTR (TextDirection textDirection, const Unicode::UnicodeChar *text, va_list pArg) const
uint16_t getStringWidthRTL (TextDirection textDirection, const Unicode::UnicodeChar *text, va_list pArg) const
Protected Attributes inherited from GeneratedFont
const FontContextualFormsTable * arabicTable
Contextual forms.
const void * glyphData
The glyphs.
const uint16_t * gsubTable
The GSUB tables.
const KerningNode * kerningData
The kerning.
Protected Attributes inherited from ConstFont
const GlyphNode * glyphList
The list of glyphs.
uint16_t listSize
The size of the list of glyphs.
Protected Attributes inherited from Font
uint8_t bAlignRow: 1
The glyphs are saved with each row byte aligned.
uint16_t baselineHeight
The baseline.
uint8_t bPerPixel: 7
The number of bits per pixel.
Unicode::UnicodeChar ellipsisCharacter
The ellipsis character used for truncating long texts.
Unicode::UnicodeChar fallbackCharacter
The fallback character to use when no glyph exists for the wanted character.
uint16_t fontHeight
The font height in pixels.
uint8_t maxPixelsLeft
The maximum number of pixels a glyph extends to the left.
uint8_t maxPixelsRight
The maximum number of pixels a glyph extends to the right.
uint8_t pixelsAboveTop
The number of pixels above the top.
uint8_t pixelsBelowBottom
The number of pixels below the bottom.
Detailed Description
Constructor & Destructor Documentation
CachedFont() [1/2]
CachedFont (const struct touchgfx::BinaryFontData * data, FontId id, FontCache * _cache, const GeneratedFont * _flashFont) inline
        : GeneratedFont(0, // GlyphNode*
                        data->numberOfGlyphs,
                        data->fontHeight,
                        data->baseline,
                        data->pixAboveTop,
                        data->pixBelowBottom,
                        data->bitsPerPixel,
                        data->byteAlignRow,
                        data->maxLeft,
                        data->maxRight,
                        0, // glyphDataPointer
                        0, // Kerning table not used for cached font
                        data->fallbackChar,
                        data->ellipsisChar,
                        0,  // lsubTablePointer
                        0), // contextualFormsPointer
          fontId(id),
          cache(_cache),
          flashFont(_flashFont)
    {
    }
CachedFont() [2/2]
CachedFont () inline
        : GeneratedFont()
    {
    }
Member Function Documentation
getContextualFormsTable()
virtual const FontContextualFormsTable * getContextualFormsTable () const inline virtual
Gets the contextual forms table used in arabic fonts.
Returns
The FontContextualFormsTable or null if the font has no table.
Reimplemented from GeneratedFont.
    {
        if (arabicTable != 0)
        {
            return arabicTable;
        }
        return flashFont->getContextualFormsTable();
    }
References GeneratedFont::arabicTable, and CachedFont::flashFont.
Referenced by FontCache::createSortedLigatures().
getFontId()
FontId getFontId () const inline
    {
        return fontId;
    }
References CachedFont::fontId.
getGlyph()
const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, const uint8_t *& pixelData, uint8_t & bitsPerPixel) const virtual
Gets the glyph data associated with the specified Unicode. Please note that in case of Thai letters and Arabic letters where diacritics can be placed relative to the previous character(s), please use TextProvider::getNextLigature() instead as it will create a temporary GlyphNode that will be adjusted with respect to X/Y position.
Parameters
unicode The character to look up.
pixelData Pointer to the pixel data for the glyph if the glyph is found. This is set by this method.
[out] bitsPerPixel Reference where to place the number of bits per pixel.
Returns
A pointer to the glyph node or null if the glyph was not found.
Reimplemented from ConstFont.
{
    // Look first in internal flash font
    const GlyphNode* n = flashFont->find(unicode);
    if ((n == 0) && (cache != 0))
    {
        // Now look in FontCache table
        n = cache->getGlyph(unicode, fontId);
    }
    // Revert to normal behaviour if still not found
    if (n == 0 && unicode != 0 && unicode != '\n')
    {
        Unicode::UnicodeChar fallbackChar = flashFont->getFallbackChar();
        n = flashFont->find(fallbackChar);
        if (n == 0)
        {
            n = cache->getGlyph(fallbackChar, fontId);
        }
    }
    if (n != 0)
    {
        pixelData = getPixelData(n);
        bitsPerPixel = getBitsPerPixel();
        return n;
    }
    return (const GlyphNode*)0;
}
References CachedFont::cache, CachedFont::flashFont, CachedFont::fontId, Font::getBitsPerPixel(), FontCache::getGlyph(), and CachedFont::getPixelData().
getGSUBTable()
virtual const uint16_t * getGSUBTable () const inline virtual
Gets GSUB table. Currently only used for Devanagari fonts.
Returns
The GSUB table or null if font has GSUB no table.
Reimplemented from GeneratedFont.
    {
        if (gsubTable != 0)
        {
            return gsubTable;
        }
        return flashFont->getGSUBTable();
    }
References CachedFont::flashFont, and GeneratedFont::gsubTable.
Referenced by FontCache::createSortedLigatures().
getKerning()
int8_t getKerning (Unicode::UnicodeChar prevChar, const GlyphNode * glyph) const virtual
Gets the kerning distance between two characters.
Parameters
prevChar The Unicode value of the previous character.
glyph the glyph object for the current character.
Returns
The kerning distance between prevChar and glyph char.
Reimplemented from GeneratedFont.
{
    // Kerning is not supported by Font Caching
    return 0;
}
getPixelData()
const uint8_t * getPixelData (const GlyphNode * glyph) const virtual
Gets the pixel date associated with this glyph.
Parameters
glyph The glyph to get the pixels data from.
Returns
Pointer to the pixel data of this glyph.
Reimplemented from GeneratedFont.
{
    // If glyph is cached, then data is present just after the GlyphNode
    if (FontCache::isCached(glyph))
    {
        const uint8_t* data = FontCache::getPixelData(glyph);
        return data;
    }
    return flashFont->getPixelData(glyph);
}
References CachedFont::flashFont, FontCache::getPixelData(), and FontCache::isCached().
Referenced by CachedFont::getGlyph().
setContextualFormsTable()
virtual void setContextualFormsTable (const FontContextualFormsTable * table) inline virtual
    {
        arabicTable = table;
    }
References GeneratedFont::arabicTable.
Referenced by FontCache::initializeCachedFont().
setFontCache()
void setFontCache (FontCache & cache)
setGSUBTable()
virtual void setGSUBTable (const uint16_t * table) inline virtual
    {
        gsubTable = table;
    }
References GeneratedFont::gsubTable.
Referenced by FontCache::initializeCachedFont().
Member Data Documentation
cache
FontCache* cache private
Referenced by CachedFont::getGlyph().
flashFont
const GeneratedFont* flashFont private
Referenced by CachedFont::getContextualFormsTable(), CachedFont::getGlyph(), CachedFont::getGSUBTable(), and CachedFont::getPixelData().
fontId
FontId fontId private
Referenced by CachedFont::getFontId(), and CachedFont::getGlyph().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/fonts/include/fonts/CachedFont.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/fonts/src/CachedFont.cpp