Battery Simulator Documentation: LCD32bpp_XRGB8888
LCD32bpp_XRGB8888
#include "LCD32bpp_XRGB8888.hpp"
Classes
class DecompressorL8_L4
class DecompressorL8_LZW9
class DecompressorL8_RLE
class DecompressorL8Base
class DrawTextureMapScanLineBase32
class TextureMapper_A4_BilinearInterpolation_GA
class TextureMapper_A4_BilinearInterpolation_NoGA
class TextureMapper_A4_NearestNeighbor_GA
class TextureMapper_A4_NearestNeighbor_NoGA
class TextureMapper_ARGB8888_NonOpaque_BilinearInterpolation_GA
class TextureMapper_ARGB8888_NonOpaque_NearestNeighbor_GA
class TextureMapper_L8_ARGB8888_NonOpaque_BilinearInterpolation_GA
class TextureMapper_L8_ARGB8888_NonOpaque_NearestNeighbor_GA
class TextureMapper_L8_RGB565_Opaque_BilinearInterpolation_GA
class TextureMapper_L8_RGB565_Opaque_BilinearInterpolation_NoGA
class TextureMapper_L8_RGB565_Opaque_NearestNeighbor_GA
class TextureMapper_L8_RGB565_Opaque_NearestNeighbor_NoGA
class TextureMapper_L8_RGB888_Opaque_BilinearInterpolation_GA
class TextureMapper_L8_RGB888_Opaque_BilinearInterpolation_NoGA
class TextureMapper_L8_RGB888_Opaque_NearestNeighbor_GA
class TextureMapper_L8_RGB888_Opaque_NearestNeighbor_NoGA
class TextureMapper_RGB565_NonOpaque_BilinearInterpolation_GA
class TextureMapper_RGB565_NonOpaque_BilinearInterpolation_NoGA
class TextureMapper_RGB565_NonOpaque_NearestNeighbor_GA
class TextureMapper_RGB565_NonOpaque_NearestNeighbor_NoGA
class TextureMapper_RGB565_Opaque_BilinearInterpolation_GA
class TextureMapper_RGB565_Opaque_BilinearInterpolation_NoGA
class TextureMapper_RGB565_Opaque_NearestNeighbor_GA
class TextureMapper_RGB565_Opaque_NearestNeighbor_NoGA
class TextureMapper_RGB888_Opaque_BilinearInterpolation_GA
class TextureMapper_RGB888_Opaque_BilinearInterpolation_NoGA
class TextureMapper_RGB888_Opaque_NearestNeighbor_GA
class TextureMapper_RGB888_Opaque_NearestNeighbor_NoGA
Public Member Functions
LCD32bpp_XRGB8888 ()
virtual uint8_t bitDepth () const
virtual void blitCopy (const uint16_t *sourceData, const Rect &source, const Rect &blitRect, uint8_t alpha, bool hasTransparentPixels)
virtual void blitCopy (const uint8_t *sourceData, Bitmap::BitmapFormat sourceFormat, const Rect &source, const Rect &blitRect, uint8_t alpha, bool hasTransparentPixels)
virtual void copyAreaFromTFTToClientBuffer (const Rect &region)
virtual uint16_t * copyFrameBufferRegionToMemory (const Rect &visRegion, const Rect &absRegion, const BitmapId bitmapId)
virtual Rect copyFrameBufferRegionToMemory (const Rect &visRegion, const Rect &absRegion, uint8_t *dst, int16_t dstWidth, int16_t dstHeight)
virtual void drawPartialBitmap (const Bitmap &bitmap, int16_t x, int16_t y, const Rect &rect, uint8_t alpha=255, bool useOptimized=true)
void enableDecompressorL8_All ()
void enableDecompressorL8_L4 ()
void enableDecompressorL8_LZW9 ()
void enableDecompressorL8_RLE ()
void enableTextureMapperA4 ()
void enableTextureMapperA4_BilinearInterpolation ()
void enableTextureMapperA4_NearestNeighbor ()
void enableTextureMapperAll ()
void enableTextureMapperARGB8888 ()
void enableTextureMapperARGB8888_BilinearInterpolation ()
void enableTextureMapperARGB8888_NearestNeighbor ()
void enableTextureMapperL8_ARGB8888 ()
void enableTextureMapperL8_ARGB8888_BilinearInterpolation ()
void enableTextureMapperL8_ARGB8888_NearestNeighbor ()
void enableTextureMapperL8_RGB565 ()
void enableTextureMapperL8_RGB565_BilinearInterpolation ()
void enableTextureMapperL8_RGB565_NearestNeighbor ()
void enableTextureMapperL8_RGB888 ()
void enableTextureMapperL8_RGB888_BilinearInterpolation ()
void enableTextureMapperL8_RGB888_NearestNeighbor ()
void enableTextureMapperRGB565 ()
void enableTextureMapperRGB565_NonOpaque_BilinearInterpolation ()
void enableTextureMapperRGB565_NonOpaque_NearestNeighbor ()
void enableTextureMapperRGB565_Opaque_BilinearInterpolation ()
void enableTextureMapperRGB565_Opaque_NearestNeighbor ()
void enableTextureMapperRGB888 ()
void enableTextureMapperRGB888_BilinearInterpolation ()
void enableTextureMapperRGB888_NearestNeighbor ()
virtual void fillBuffer (uint8_t *const destination, uint16_t pixelStride, const Rect &rect, const colortype color, const uint8_t alpha)
virtual void fillRect (const Rect &rect, colortype color, uint8_t alpha=255)
virtual Bitmap::BitmapFormat framebufferFormat () const
virtual uint16_t framebufferStride () const
virtual bool supportDynamicBitmapDrawing (const Bitmap::BitmapFormat)
Public Member Functions inherited from LCD
LCD ()
virtual ~LCD ()
uint16_t * copyFrameBufferRegionToMemory (const Rect &region, const BitmapId bitmapId=BITMAP_ANIMATION_STORAGE)
void drawString (Rect widgetArea, const Rect &invalidatedArea, const StringVisuals &stringVisuals, const Unicode::UnicodeChar *format,...)
virtual void drawTextureMapQuad (const DrawingSurface &dest, const Point3D *vertices, const TextureSurface &texture, const Rect &absoluteRect, const Rect &dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha=255, uint16_t subDivisionSize=12)
virtual void drawTextureMapTriangle (const DrawingSurface &dest, const Point3D *vertices, const TextureSurface &texture, const Rect &absoluteRect, const Rect &dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha=255, uint16_t subDivisionSize=12)
colortype getDefaultColor () const
virtual void setDefaultColor (colortype color)
void setVectorFontRenderer (VectorFontRenderer *renderer)
Static Public Member Functions
static FORCE_INLINE_FUNCTION uint32_t blendRgb565withXrgb8888 (const uint16_t fgRGB565, const uint32_t bgXRGB8888, const uint8_t fgAlpha, const uint8_t bgAlpha)
static FORCE_INLINE_FUNCTION uint32_t blendRgb888withXrgb8888 (const uint8_t *const fgRGB888, const uint32_t bgXRGB8888, const uint8_t fgAlpha, const uint8_t bgAlpha)
static FORCE_INLINE_FUNCTION uint32_t blendRGBwithXrgb8888 (const uint8_t fgR, const uint8_t fgG, const uint8_t fgB, const uint32_t bgXRGB8888, const uint8_t fgAlpha, const uint8_t bgAlpha)
static FORCE_INLINE_FUNCTION uint32_t blendXrgb888withXrgb8888 (const uint32_t fgXRGB8888, const uint32_t bgXRGB8888, const uint8_t fgAlpha, const uint8_t bgAlpha)
static FORCE_INLINE_FUNCTION uint8_t getBlueFromColor (colortype color)
static FORCE_INLINE_FUNCTION uint16_t getFramebufferStride ()
static FORCE_INLINE_FUNCTION uint32_t rgb888toXrgb8888 (const uint8_t *const rgb888)
Static Public Member Functions inherited from LCD
static FORCE_INLINE_FUNCTION uint8_t div255 (uint16_t num)
static FORCE_INLINE_FUNCTION uint32_t div255g (uint32_t pixelxAlpha)
static FORCE_INLINE_FUNCTION uint32_t div255rb (uint32_t pixelxAlpha)
Protected Member Functions
void blitCopyL8 (const uint8_t *sourceData, const uint8_t *clutData, const Rect &source, const Rect &blitRect, uint8_t alpha)
virtual void drawGlyph (uint16_t *wbuf16, Rect widgetArea, int16_t x, int16_t y, uint16_t offsetX, uint16_t offsetY, const Rect &invalidatedArea, const GlyphNode *glyph, const uint8_t *glyphData, uint8_t byteAlignRow, colortype color, uint8_t bitsPerPixel, uint8_t alpha, TextRotation rotation)
virtual DrawTextureMapScanLineBase * getTextureMapperDrawScanLine (const TextureSurface &texture, RenderingVariant renderVariant, uint8_t alpha)
Protected Member Functions inherited from LCD
void drawStringLTR (const Rect &widgetArea, const Rect &invalidatedArea, const StringVisuals &visuals, const Unicode::UnicodeChar *format, va_list pArg)
void drawStringRTL (const Rect &widgetArea, const Rect &invalidatedArea, const StringVisuals &visuals, const Unicode::UnicodeChar *format, va_list pArg)
virtual void drawTextureMapScanLine (const DrawingSurface &dest, const Gradients &gradients, const Edge *leftEdge, const Edge *rightEdge, const TextureSurface &texture, const Rect &absoluteRect, const Rect &dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha, uint16_t subDivisionSize)
Static Protected Member Functions
static void blitCopyL8_ARGB8888 (const uint8_t *sourceData, const uint8_t *clutData, const Rect &source, const Rect &blitRect, uint8_t alpha)
static void blitCopyL8_RGB565 (const uint8_t *sourceData, const uint8_t *clutData, const Rect &source, const Rect &blitRect, uint8_t alpha)
static void blitCopyL8_RGB888 (const uint8_t *sourceData, const uint8_t *clutData, const Rect &source, const Rect &blitRect, uint8_t alpha)
static void blitCopyRGB565 (const uint16_t *sourceData16, const Rect &source, const Rect &blitRect, uint8_t alpha)
static void blitCopyRGB888 (const uint16_t *sourceData16, const Rect &source, const Rect &blitRect, uint8_t alpha)
static int nextLine (bool rotatedDisplay, TextRotation textRotation)
static int nextPixel (bool rotatedDisplay, TextRotation textRotation)
Static Protected Member Functions inherited from LCD
static FORCE_INLINE_FUNCTION uint8_t getAlphaFromA4 (const uint16_t *data, uint32_t offset)
static uint16_t getNumLines (TextProvider &textProvider, WideTextAction wideTextAction, TextDirection textDirection, const Font *font, int16_t width)
static int realX (const Rect &widgetArea, int16_t x, int16_t y, TextRotation rotation)
static int realY (const Rect &widgetArea, int16_t x, int16_t y, TextRotation rotation)
static void rotateRect (Rect &rect, const Rect &canvas, const TextRotation rotation)
static uint16_t stringWidth (TextProvider &textProvider, const Font &font, const int numChars, TextDirection textDirection)
Static Private Member Functions
static FORCE_INLINE_FUNCTION uint16_t bilinearInterpolate565 (uint16_t c00, uint16_t c10, uint16_t c01, uint16_t c11, uint8_t x, uint8_t y)
static FORCE_INLINE_FUNCTION uint16_t bilinearInterpolate565 (uint16_t c00, uint16_t c10, uint8_t x)
static FORCE_INLINE_FUNCTION uint8_t bilinearInterpolate8 (uint8_t c00, uint8_t c10, uint8_t c01, uint8_t c11, uint8_t x, uint8_t y)
static FORCE_INLINE_FUNCTION uint8_t bilinearInterpolate8 (uint8_t c00, uint8_t c10, uint8_t x)
static FORCE_INLINE_FUNCTION uint32_t bilinearInterpolate888 (uint32_t c00, uint32_t c10, uint32_t c01, uint32_t c11, uint8_t x, uint8_t y)
static FORCE_INLINE_FUNCTION uint32_t bilinearInterpolate888 (uint32_t c00, uint32_t c10, uint8_t x)
static FORCE_INLINE_FUNCTION uint16_t compactRgb565 (uint32_t c)
static FORCE_INLINE_FUNCTION uint32_t div255_888 (uint32_t val, uint8_t factor)
static FORCE_INLINE_FUNCTION uint32_t div255_888_FFcheck (uint32_t val, uint8_t factor)
static FORCE_INLINE_FUNCTION uint32_t expandRgb565 (uint16_t c)
Private Attributes
DecompressorL8Base * decompressorL8_L4
DecompressorL8Base * decompressorL8_LZW9
DecompressorL8Base * decompressorL8_RLE
DrawTextureMapScanLineBase * textureMapper_A4_BilinearInterpolation_GA
DrawTextureMapScanLineBase * textureMapper_A4_BilinearInterpolation_NoGA
DrawTextureMapScanLineBase * textureMapper_A4_NearestNeighbor_GA
DrawTextureMapScanLineBase * textureMapper_A4_NearestNeighbor_NoGA
DrawTextureMapScanLineBase * textureMapper_ARGB8888_NonOpaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase * textureMapper_ARGB8888_NonOpaque_NearestNeighbor_GA
DrawTextureMapScanLineBase * textureMapper_L8_ARGB8888_NonOpaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase * textureMapper_L8_ARGB8888_NonOpaque_NearestNeighbor_GA
DrawTextureMapScanLineBase * textureMapper_L8_RGB565_Opaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase * textureMapper_L8_RGB565_Opaque_BilinearInterpolation_NoGA
DrawTextureMapScanLineBase * textureMapper_L8_RGB565_Opaque_NearestNeighbor_GA
DrawTextureMapScanLineBase * textureMapper_L8_RGB565_Opaque_NearestNeighbor_NoGA
DrawTextureMapScanLineBase * textureMapper_L8_RGB888_Opaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase * textureMapper_L8_RGB888_Opaque_BilinearInterpolation_NoGA
DrawTextureMapScanLineBase * textureMapper_L8_RGB888_Opaque_NearestNeighbor_GA
DrawTextureMapScanLineBase * textureMapper_L8_RGB888_Opaque_NearestNeighbor_NoGA
DrawTextureMapScanLineBase * textureMapper_RGB565_NonOpaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase * textureMapper_RGB565_NonOpaque_BilinearInterpolation_NoGA
DrawTextureMapScanLineBase * textureMapper_RGB565_NonOpaque_NearestNeighbor_GA
DrawTextureMapScanLineBase * textureMapper_RGB565_NonOpaque_NearestNeighbor_NoGA
DrawTextureMapScanLineBase * textureMapper_RGB565_Opaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase * textureMapper_RGB565_Opaque_BilinearInterpolation_NoGA
DrawTextureMapScanLineBase * textureMapper_RGB565_Opaque_NearestNeighbor_GA
DrawTextureMapScanLineBase * textureMapper_RGB565_Opaque_NearestNeighbor_NoGA
DrawTextureMapScanLineBase * textureMapper_RGB888_Opaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase * textureMapper_RGB888_Opaque_BilinearInterpolation_NoGA
DrawTextureMapScanLineBase * textureMapper_RGB888_Opaque_NearestNeighbor_GA
DrawTextureMapScanLineBase * textureMapper_RGB888_Opaque_NearestNeighbor_NoGA
Additional Inherited Members
Static Protected Attributes inherited from LCD
static colortype defaultColor
Default Color to use when displaying transparency-only elements, e.g. A4 bitmaps.
static const uint16_t newLine = 10
NewLine value.
Detailed Description
This class contains the various low-level drawing routines for drawing bitmaps, texts and rectangles on 16 bits per pixel displays.
See also
LCD
Note
All coordinates are expected to be in absolute coordinates!
Constructor & Destructor Documentation
LCD32bpp_XRGB8888()
LCD32bpp_XRGB8888 ()
Member Function Documentation
bilinearInterpolate565() [1/2]
static FORCE_INLINE_FUNCTION uint16_t bilinearInterpolate565 (uint16_t c00, uint16_t c10, uint16_t c01, uint16_t c11, uint8_t x, uint8_t y) inline static private
    {
        assert(x < 16 && y < 16);
        uint32_t a00 = expandRgb565(c00);
        uint32_t a10 = expandRgb565(c10);
        uint32_t a01 = expandRgb565(c01);
        uint32_t a11 = expandRgb565(c11);
        uint8_t xy = (x * y) >> 3;
        return compactRgb565((a00 * (32 - 2 * y - 2 * x + xy) + a10 * (2 * x - xy) + a01 * (2 * y - xy) + a11 * xy) >> 5);
    }
References LCD32bpp_XRGB8888::compactRgb565(), and LCD32bpp_XRGB8888::expandRgb565().
bilinearInterpolate565() [2/2]
static FORCE_INLINE_FUNCTION uint16_t bilinearInterpolate565 (uint16_t c00, uint16_t c10, uint8_t x) inline static private
    {
        assert(x < 16);
        uint32_t a00 = expandRgb565(c00);
        uint32_t a10 = expandRgb565(c10);
        return compactRgb565((a00 * (32 - 2 * x) + a10 * (2 * x)) >> 5);
    }
References LCD32bpp_XRGB8888::compactRgb565(), and LCD32bpp_XRGB8888::expandRgb565().
bilinearInterpolate8() [1/2]
static FORCE_INLINE_FUNCTION uint8_t bilinearInterpolate8 (uint8_t c00, uint8_t c10, uint8_t c01, uint8_t c11, uint8_t x, uint8_t y) inline static private
    {
        assert(x < 16 && y < 16);
        uint16_t xy11 = x * y;
        uint16_t xy10 = 16 * x - xy11;
        uint16_t xy01 = 16 * y - xy11;
        uint16_t xy00 = 256 - (xy11 + xy10 + xy01);
        return (c00 * xy00 + c10 * xy10 + c01 * xy01 + c11 * xy11) >> 8;
    }
bilinearInterpolate8() [2/2]
static FORCE_INLINE_FUNCTION uint8_t bilinearInterpolate8 (uint8_t c00, uint8_t c10, uint8_t x) inline static private
    {
        assert(x < 16);
        uint16_t xy10 = 16 * x;
        uint16_t xy00 = 256 - xy10;
        return (c00 * xy00 + c10 * xy10) >> 8;
    }
bilinearInterpolate888() [1/2]
static FORCE_INLINE_FUNCTION uint32_t bilinearInterpolate888 (uint32_t c00, uint32_t c10, uint32_t c01, uint32_t c11, uint8_t x, uint8_t y) inline static private
    {
        assert(x < 16 && y < 16);
        uint16_t xy11 = x * y;
        uint16_t xy10 = 16 * x - xy11;
        uint16_t xy01 = 16 * y - xy11;
        uint16_t xy00 = 256 - (xy11 + xy10 + xy01);
        return ((((c00 & 0xFF00FF) * xy00 + (c10 & 0xFF00FF) * xy10 + (c01 & 0xFF00FF) * xy01 + (c11 & 0xFF00FF) * xy11) >> 8) & 0xFF00FF) |
               ((((c00 & 0x00FF00) * xy00 + (c10 & 0x00FF00) * xy10 + (c01 & 0x00FF00) * xy01 + (c11 & 0x00FF00) * xy11) >> 8) & 0x00FF00);
    }
bilinearInterpolate888() [2/2]
static FORCE_INLINE_FUNCTION uint32_t bilinearInterpolate888 (uint32_t c00, uint32_t c10, uint8_t x) inline static private
    {
        assert(x < 16);
        uint16_t xy10 = 16 * x;
        uint16_t xy00 = 256 - xy10;
        return ((((c00 & 0xFF00FF) * xy00 + (c10 & 0xFF00FF) * xy10) >> 8) & 0xFF00FF) |
               ((((c00 & 0x00FF00) * xy00 + (c10 & 0x00FF00) * xy10) >> 8) & 0x00FF00);
    }
bitDepth()
virtual uint8_t bitDepth () const inline virtual
Number of bits per pixel used by the display.
Returns
The number of bits per pixel.
Implements LCD.
    {
        return 32;
    }
blendRgb565withXrgb8888()
static FORCE_INLINE_FUNCTION uint32_t blendRgb565withXrgb8888 (const uint16_t fgRGB565, const uint32_t bgXRGB8888, const uint8_t fgAlpha, const uint8_t bgAlpha) inline static
Alpha blend a 16bit RGB565 color with the 32bit color given in bgXRGB8888 using the provided fgAlpha (for fgRGB565) and bgAlpha (for bgXRGB8888). The resulting color is returned. address.
Parameters
fgRGB565 A pointer to the foreground 24bit RGB.
bgXRGB8888 The background 32bit color.
fgAlpha The foreground alpha.
bgAlpha The background alpha.
Returns
The blended value.
    {
        const uint8_t r = (fgRGB565 & 0xF800) >> 8;
        const uint8_t g = (fgRGB565 & 0x07E0) >> 3;
        const uint8_t b = fgRGB565 << 3;
        // return blendRGBwithXrgb8888(r, g, b, bgXRGB8888, fgAlpha, bgAlpha);
        return blendRGBwithXrgb8888(r | (r >> 5), g | (g >> 6), b | (b >> 5), bgXRGB8888, fgAlpha, bgAlpha);
    }
References LCD32bpp_XRGB8888::blendRGBwithXrgb8888().
Referenced by PainterXRGB8888Bitmap::paint(), and PainterXRGB8888L8Bitmap::paint().
blendRgb888withXrgb8888()
static FORCE_INLINE_FUNCTION uint32_t blendRgb888withXrgb8888 (const uint8_t *const fgRGB888, const uint32_t bgXRGB8888, const uint8_t fgAlpha, const uint8_t bgAlpha) inline static
Alpha blend a 24bit RGB888 with the 32bit color given in bgXRGB8888 using the provided fgAlpha (for fgRGB888) and bgAlpha (for bgXRGB8888). The resulting color is returned. address.
Parameters
fgRGB888 A pointer to the foreground 24bit RGB.
bgXRGB8888 The background 32bit color.
fgAlpha The foreground alpha.
bgAlpha The background alpha.
Returns
The blended value.
    {
        return blendRGBwithXrgb8888(fgRGB888[2], fgRGB888[1], fgRGB888[0], bgXRGB8888, fgAlpha, bgAlpha);
    }
References LCD32bpp_XRGB8888::blendRGBwithXrgb8888().
Referenced by LCD32bpp_XRGB8888::blendXrgb888withXrgb8888(), PainterXRGB8888Bitmap::paint(), and PainterXRGB8888L8Bitmap::paint().
blendRGBwithXrgb8888()
static FORCE_INLINE_FUNCTION uint32_t blendRGBwithXrgb8888 (const uint8_t fgR, const uint8_t fgG, const uint8_t fgB, const uint32_t bgXRGB8888, const uint8_t fgAlpha, const uint8_t bgAlpha) inline static
Alpha blend R,G,B with the 32bit color given in bgXRGB8888 using the provided fgAlpha (for R, G,B) and bgAlpha (for bgXRGB8888). The resulting color is returned. address.
Parameters
fgR The foreground blue.
fgG The foreground green.
fgB The foreground blue.
bgXRGB8888 The background 32bit color.
fgAlpha The foreground alpha.
bgAlpha The background alpha.
Returns
The blended value.
    {
        const uint8_t b = div255(fgB * fgAlpha + (bgXRGB8888 & 0xFF) * bgAlpha);
        const uint8_t g = div255(fgG * fgAlpha + ((bgXRGB8888 >> 8) & 0xFF) * bgAlpha);
        const uint8_t r = div255(fgR * fgAlpha + ((bgXRGB8888 >> 16) & 0xFF) * bgAlpha);
        return (r << 16) | (g << 8) | b;
    }
References LCD::div255().
Referenced by LCD32bpp_XRGB8888::blendRgb565withXrgb8888(), and LCD32bpp_XRGB8888::blendRgb888withXrgb8888().
blendXrgb888withXrgb8888()
static FORCE_INLINE_FUNCTION uint32_t blendXrgb888withXrgb8888 (const uint32_t fgXRGB8888, const uint32_t bgXRGB8888, const uint8_t fgAlpha, const uint8_t bgAlpha) inline static
Alpha blend two 32bit colors using the provided fgAlpha (for fgXRGB8888) and bgAlpha (for bgXRGB8888). The resulting color is returned.
Parameters
fgXRGB8888 The foreground 32bit color.
bgXRGB8888 The background 32bit color.
fgAlpha The foreground alpha.
bgAlpha The background alpha.
Returns
The blended value.
    {
        return blendRgb888withXrgb8888(reinterpret_cast<const uint8_t*>(&fgXRGB8888), bgXRGB8888, fgAlpha, bgAlpha);
    }
References LCD32bpp_XRGB8888::blendRgb888withXrgb8888().
Referenced by PainterXRGB8888L8Bitmap::paint().
blitCopy() [1/2]
virtual void blitCopy (const uint16_t * sourceData, const Rect & source, const Rect & blitRect, uint8_t alpha, bool hasTransparentPixels) virtual
Blits (directly copies) a block of data to the framebuffer, performing alpha blending (and tranparency keying) as specified. Performs a software blend if HAL does not support BLIT_COPY_WITH_ALPHA and alpha != 255 (solid).
Parameters
sourceData The source array pointer (points to the beginning of the data). The sourceData must be stored in a format suitable for the selected display.
source The position and dimensions of the source. The x and y of this rect should both be 0.
blitRect A rectangle describing what region of the sourceData is to be copied to the framebuffer.
alpha The alpha value to use for blending ranging from 0=invisible to 255=solid=no blending.
hasTransparentPixels If true, this data copy contains transparent pixels and require hardware support for that to be enabled.
Implements LCD.
blitCopy() [2/2]
virtual void blitCopy (const uint8_t * sourceData, Bitmap::BitmapFormat sourceFormat, const Rect & source, const Rect & blitRect, uint8_t alpha, bool hasTransparentPixels) virtual
Blits (directly copies) a block of data to the framebuffer, performing alpha blending (and tranparency keying) as specified. Performs a software blend if HAL does not support BLIT_COPY_WITH_ALPHA and alpha < 255 (solid).
If the display does not support the specified sourceFormat, an assert will be raised.
Parameters
sourceData The source array pointer (points to the beginning of the data). The sourceData must be stored in a format suitable for the selected display.
sourceFormat The bitmap format used in the source data.
source The position and dimensions of the source. The x and y of this rect should both be 0.
blitRect A rectangle describing what region of the sourceData is to be copied to the framebuffer.
alpha The alpha value to use for blending ranging from 0=invisible to 255=solid=no blending.
hasTransparentPixels If true, this data copy contains transparent pixels and require hardware support for that to be enabled.
Implements LCD.
blitCopyL8()
void blitCopyL8 (const uint8_t * sourceData, const uint8_t * clutData, const Rect & source, const Rect & blitRect, uint8_t alpha) protected
Blits a 2D indexed 8-bit source to the framebuffer performing alpha-blending per pixel as specified if indexed format is not supported by the DMA a software blend is performed.
Parameters
sourceData The source-indexes pointer (points to the beginning of the data). The sourceData must be stored as 8- bits indexes.
clutData The source-clut pointer (points to the beginning of the CLUT color format and size data followed by colors entries.
source The location and dimensions of the source.
blitRect A rectangle describing what region is to be drawn.
alpha The alpha value to use for blending applied to the whole image (255 = solid, no blending)
blitCopyL8_ARGB8888()
static void blitCopyL8_ARGB8888 (const uint8_t * sourceData, const uint8_t * clutData, const Rect & source, const Rect & blitRect, uint8_t alpha) static protected
Blits a 2D indexed 8-bit source to the framebuffer performing alpha-blending per pixel as specified if L8_ARGB8888 is not supported by the DMA a software blend is performed.
Parameters
sourceData The source-indexes pointer (points to the beginning of the data). The sourceData must be stored as 8- bits indexes.
clutData The source-clut pointer (points to the beginning of the CLUT color format and size data followed by colors entries stored as 32- bits (ARGB8888) format.
source The location and dimensions of the source.
blitRect A rectangle describing what region is to be drawn.
alpha The alpha value to use for blending applied to the whole image (255 = solid, no blending)
blitCopyL8_RGB565()
static void blitCopyL8_RGB565 (const uint8_t * sourceData, const uint8_t * clutData, const Rect & source, const Rect & blitRect, uint8_t alpha) static protected
Blits a 2D indexed 8-bit source to the framebuffer performing alpha-blending per pixel as specified if L8_RGB565 is not supported by the DMA a software blend is performed.
Parameters
sourceData The source-indexes pointer (points to the beginning of the data). The sourceData must be stored as 8- bits indexes.
clutData The source-clut pointer (points to the beginning of the CLUT color format and size data followed by colors entries stored as 16- bits (RGB565) format.
source The location and dimensions of the source.
blitRect A rectangle describing what region is to be drawn.
alpha The alpha value to use for blending applied to the whole image (255 = solid, no blending)
blitCopyL8_RGB888()
static void blitCopyL8_RGB888 (const uint8_t * sourceData, const uint8_t * clutData, const Rect & source, const Rect & blitRect, uint8_t alpha) static protected
Blits a 2D indexed 8-bit source to the framebuffer performing alpha-blending per pixel as specified if L8_RGB888 is not supported by the DMA a software blend is performed.
Parameters
sourceData The source-indexes pointer (points to the beginning of the data). The sourceData must be stored as 8- bits indexes.
clutData The source-clut pointer (points to the beginning of the CLUT color format and size data followed by colors entries stored as 32- bits (RGB888) format.
source The location and dimensions of the source.
blitRect A rectangle describing what region is to be drawn.
alpha The alpha value to use for blending applied to the whole image (255 = solid, no blending)
blitCopyRGB565()
static void blitCopyRGB565 (const uint16_t * sourceData16, const Rect & source, const Rect & blitRect, uint8_t alpha) static protected
Blits a 2D source-array to the framebuffer performing alpha-blending per pixel as specified. If! RGB565 is not supported by the DMA a software blend is performed.
Parameters
sourceData16 The source-array pointer (points to the beginning of the data). The sourceData must be stored as 16- bits RGB565 values.
source The location and dimensions of the source.
blitRect A rectangle describing what region is to be drawn.
alpha The alpha value to use for blending applied to the whole image (255 = solid, no blending)
blitCopyRGB888()
static void blitCopyRGB888 (const uint16_t * sourceData16, const Rect & source, const Rect & blitRect, uint8_t alpha) static protected
Blits a 2D source-array to the framebuffer performing alpha-blending per pixel as specified. If RGB888 is not supported by the DMA a software blend is performed.
Parameters
sourceData16 The source-array pointer (points to the beginning of the data). The sourceData must be stored as 24- bits RGB888 values.
source The location and dimensions of the source.
blitRect A rectangle describing what region is to be drawn.
alpha The alpha value to use for blending applied to the whole image (255 = solid, no blending)
compactRgb565()
static FORCE_INLINE_FUNCTION uint16_t compactRgb565 (uint32_t c) inline static private
    {
        return ((c >> 16) & 0x07E0) | (c & ~0x07E0);
    }
Referenced by LCD32bpp_XRGB8888::bilinearInterpolate565(), and LCD32bpp_XRGB8888::bilinearInterpolate565().
copyAreaFromTFTToClientBuffer()
virtual void copyAreaFromTFTToClientBuffer (const Rect & region) virtual
Copies part of the displayed framebuffer to current framebuffer. The region given is the absolute region on screen.
Parameters
region A rectangle describing what region of the displayed framebuffer is to be copied to the framebuffer.
Note
The copy is performed only when double buffering is enabled. Otherwise the given region in current framebuffer is left untouched.
Implements LCD.
copyFrameBufferRegionToMemory() [1/2]
virtual uint16_t * copyFrameBufferRegionToMemory (const Rect & visRegion, const Rect & absRegion, const BitmapId bitmapId) virtual
Copies part of the framebuffer to the data section of a bitmap. The bitmap must be a dynamic bitmap or animation storage (BITMAP_ANIMATION_STORAGE). The two regions given are the visible region and the absolute region on screen. This is used to copy only a part of the framebuffer. This might be the case if a SnapshotWidget is placed inside a Container where parts of the SnapshowWidget is outside the area defined by the Container. The visible region must be completely inside the absolute region.
Parameters
visRegion The visible region.
absRegion The absolute region.
bitmapId Identifier for the bitmap.
Returns
Null if it fails, else a pointer to the data in the given bitmap.
See also
blitCopy, copyFrameBufferRegionToMemory(const Rect&, const Rect&, uint8_t*, int16_t, int16_t)
Note
There is only one instance of animation storage. The content of the bitmap data /animation storage outside the given region is left untouched.
Implements LCD.
copyFrameBufferRegionToMemory() [2/2]
virtual Rect copyFrameBufferRegionToMemory (const Rect & visRegion, const Rect & absRegion, uint8_t * dst, int16_t dstWidth, int16_t dstHeight) virtual
Copies part of the framebuffer to memory. The memory is assumed to have the same format as the framebuffer. The two regions given are the visible region and the absolute region on screen. This is used to copy only a part of the framebuffer. This might be the case if a SnapshotWidget is placed inside a Container where parts of the SnapshowWidget is outside the area defined by the Container. The visible region must be completely inside the absolute region.
Parameters
visRegion The visible region.
absRegion The absolute region.
[in,out] dst Destination memory in same format as the framebuffer.
dstWidth Width of the destination.
dstHeight Height of the destination.
Returns
The rect that was actually copied to the destination buffer.
See also
blitCopy, copyFrameBufferRegionToMemory(const Rect&, const Rect&, const BitmapId)
Note
There is only one instance of animation storage. The content of the bitmap data /animation storage outside the given region is left untouched.
Implements LCD.
div255_888()
static FORCE_INLINE_FUNCTION uint32_t div255_888 (uint32_t val, uint8_t factor) inline static private
    {
        return div255rb((val & 0xFF00FF) * factor) | div255g((val & 0x00FF00) * factor);
    }
References LCD::div255g(), and LCD::div255rb().
Referenced by LCD32bpp_XRGB8888::div255_888_FFcheck().
div255_888_FFcheck()
static FORCE_INLINE_FUNCTION uint32_t div255_888_FFcheck (uint32_t val, uint8_t factor) inline static private
    {
        return factor < 0xFF ? div255_888(val, factor) : val;
    }
References LCD32bpp_XRGB8888::div255_888().
drawGlyph()
virtual void drawGlyph (uint16_t * wbuf16, Rect widgetArea, int16_t x, int16_t y, uint16_t offsetX, uint16_t offsetY, const Rect & invalidatedArea, const GlyphNode * glyph, const uint8_t * glyphData, uint8_t byteAlignRow, colortype color, uint8_t bitsPerPixel, uint8_t alpha, TextRotation rotation) protected virtual
Private version of draw-glyph with explicit destination buffer pointer argument. For all parameters (except the buffer pointer) see the public function drawString().
Parameters
[out] wbuf16 The destination (frame) buffer to draw to.
widgetArea The canvas to draw the glyph inside.
x Horizontal offset to start drawing the glyph.
y Vertical offset to start drawing the glyph.
offsetX Horizontal offset in the glyph to start drawing from.
offsetY Vertical offset in the glyph to start drawing from.
invalidatedArea The area to draw inside.
glyph Specifications of the glyph to draw.
glyphData Data containing the actual glyph (dense format)
byteAlignRow Each row of glyph data starts in a new byte.
color The color of the glyph.
bitsPerPixel Bit depth of the glyph.
alpha The transparency of the glyph.
rotation Rotation to do before drawing the glyph.
Implements LCD.
drawPartialBitmap()
virtual void drawPartialBitmap (const Bitmap & bitmap, int16_t x, int16_t y, const Rect & rect, uint8_t alpha = 255, bool useOptimized = true) virtual
Draws all (or a part) of a bitmap. The coordinates of the corner of the bitmap is given in (x, y) and rect describes which part of the bitmap should be drawn. The bitmap can be drawn as it is or more or less transparent depending on the value of alpha. The value of alpha is independent of the transparency of the individual pixels of the given bitmap.
Parameters
bitmap The bitmap to draw.
x The absolute x coordinate to place (0, 0) of the bitmap on the screen.
y The absolute y coordinate to place (0, 0) of the bitmap on the screen.
rect A rectangle describing what region of the bitmap is to be drawn.
alpha (Optional) Optional alpha value ranging from 0=invisible to 255=solid. Default is 255 (solid).
useOptimized (Optional) if false, do not attempt to substitute (parts of) this bitmap with faster fillrects.
Implements LCD.
enableDecompressorL8_All()
void enableDecompressorL8_All ()
Enables all the decompressors available for L8 images (L4, RLE and LZW9). This allows drawing L4, RLE and LZW9 compressed L8 images.
See also
enableDecompressorL8_L4, enableDecompressorL8_RLE, enableDecompressorL8_LZW9
enableDecompressorL8_L4()
void enableDecompressorL8_L4 ()
Enables the decompressor for L8 images compressed with the L4 algorithm. This allows drawing L4 compressed L8 images.
enableDecompressorL8_LZW9()
void enableDecompressorL8_LZW9 ()
Enables the decompressor for L8 images compressed with the LZW9 algorithm. This allows drawing LZW9 compressed L8 images.
enableDecompressorL8_RLE()
void enableDecompressorL8_RLE ()
Enables the decompressor for L8 images compressed with the RLE algorithm. This allows drawing RLE compressed L8 images.
enableTextureMapperA4()
void enableTextureMapperA4 ()
Enables the texture mappers for A4 image format. This allows drawing A4 images using Bilinear Interpolation and Nearest Neighbor algorithms.
See also
enableTextureMapperA4_BilinearInterpolation, enableTextureMapperA4_NearestNeighbor
enableTextureMapperA4_BilinearInterpolation()
void enableTextureMapperA4_BilinearInterpolation ()
Enables the texture mappers for A4 image format. This allows drawing A4 images using Bilinear Interpolation algorithm.
See also
enableTextureMapperA4, enableTextureMapperA4_NearestNeighbor
enableTextureMapperA4_NearestNeighbor()
void enableTextureMapperA4_NearestNeighbor ()
Enables the texture mappers for A4 image format. This allows drawing A4 images using Nearest Neighbor algorithm.
See also
enableTextureMapperA4, enableTextureMapperA4_BilinearInterpolation
enableTextureMapperAll()
void enableTextureMapperAll ()
Enables the texture mappers for all image formats. This allows drawing any image using Bilinear Interpolation and Nearest Neighbor algorithms, but might use a lot of memory for the drawing algorithms.
enableTextureMapperARGB8888()
void enableTextureMapperARGB8888 ()
Enables the texture mappers for ARGB8888 image format. This allows drawing ARGB8888 images using Bilinear Interpolation and Nearest Neighbor algorithms.
See also
enableTextureMapperARGB8888_BilinearInterpolation, enableTextureMapperARGB8888_NearestNeighbor
enableTextureMapperARGB8888_BilinearInterpolation()
void enableTextureMapperARGB8888_BilinearInterpolation ()
Enables the texture mappers for ARGB8888 image format. This allows drawing ARGB8888 images using Bilinear Interpolation algorithm.
See also
enableTextureMapperARGB8888, enableTextureMapperARGB8888_NearestNeighbor
enableTextureMapperARGB8888_NearestNeighbor()
void enableTextureMapperARGB8888_NearestNeighbor ()
Enables the texture mappers for ARGB8888 image format. This allows drawing ARGB8888 images using Nearest Neighbor algorithm.
See also
enableTextureMapperARGB8888, enableTextureMapperARGB8888_BilinearInterpolation
enableTextureMapperL8_ARGB8888()
void enableTextureMapperL8_ARGB8888 ()
Enables the texture mappers for L8_ARGB8888 image format. This allows drawing L8_ARGB8888 images using Bilinear Interpolation and Nearest Neighbor algorithms.
See also
enableTextureMapperL8_ARGB8888_BilinearInterpolation, enableTextureMapperL8_ARGB8888_NearestNeighbor
enableTextureMapperL8_ARGB8888_BilinearInterpolation()
void enableTextureMapperL8_ARGB8888_BilinearInterpolation ()
Enables the texture mappers for L8_ARGB8888 image format. This allows drawing L8_ARGB8888 images using Bilinear Interpolation algorithm.
See also
enableTextureMapperL8_ARGB8888, enableTextureMapperL8_ARGB8888_NearestNeighbor
enableTextureMapperL8_ARGB8888_NearestNeighbor()
void enableTextureMapperL8_ARGB8888_NearestNeighbor ()
Enables the texture mappers for L8_ARGB8888 image format. This allows drawing L8_ARGB8888 images using Nearest Neighbor algorithm.
See also
enableTextureMapperL8_ARGB8888, enableTextureMapperL8_ARGB8888_BilinearInterpolation
enableTextureMapperL8_RGB565()
void enableTextureMapperL8_RGB565 ()
Enables the texture mappers for L8_RGB565 image format. This allows drawing L8_RGB565 images using Bilinear Interpolation and Nearest Neighbor algorithms.
See also
enableTextureMapperL8_RGB565_BilinearInterpolation, enableTextureMapperL8_RGB565_NearestNeighbor
enableTextureMapperL8_RGB565_BilinearInterpolation()
void enableTextureMapperL8_RGB565_BilinearInterpolation ()
Enables the texture mappers for L8_RGB565 image format. This allows drawing L8_RGB565 images using Bilinear Interpolation algorithm.
See also
enableTextureMapperL8_RGB565, enableTextureMapperL8_RGB565_NearestNeighbor
enableTextureMapperL8_RGB565_NearestNeighbor()
void enableTextureMapperL8_RGB565_NearestNeighbor ()
Enables the texture mappers for L8_RGB565 image format. This allows drawing L8_RGB565 images using Nearest Neighbor algorithm.
See also
enableTextureMapperL8_RGB565, enableTextureMapperL8_RGB565_BilinearInterpolation
enableTextureMapperL8_RGB888()
void enableTextureMapperL8_RGB888 ()
Enables the texture mappers for L8_RGB888 image format. This allows drawing L8_RGB888 images using Bilinear Interpolation and Nearest Neighbor algorithms.
See also
enableTextureMapperL8_RGB888_BilinearInterpolation, enableTextureMapperL8_RGB888_NearestNeighbor
enableTextureMapperL8_RGB888_BilinearInterpolation()
void enableTextureMapperL8_RGB888_BilinearInterpolation ()
Enables the texture mappers for L8_RGB888 image format. This allows drawing L8_RGB888 images using Bilinear Interpolation algorithm.
See also
enableTextureMapperL8_RGB888, enableTextureMapperL8_RGB888_NearestNeighbor
enableTextureMapperL8_RGB888_NearestNeighbor()
void enableTextureMapperL8_RGB888_NearestNeighbor ()
Enables the texture mappers for L8_RGB888 image format. This allows drawing L8_RGB888 images using Nearest Neighbor algorithm.
See also
enableTextureMapperL8_RGB888, enableTextureMapperL8_RGB888_BilinearInterpolation
enableTextureMapperRGB565()
void enableTextureMapperRGB565 ()
Enables the texture mappers for RGB565 image format. This allows drawing RGB565 images using Bilinear Interpolation and Nearest Neighbor algorithms.
enableTextureMapperRGB565_NonOpaque_BilinearInterpolation()
void enableTextureMapperRGB565_NonOpaque_BilinearInterpolation ()
Enables the texture mappers for NonOpaque RGB565 image format. This allows drawing RGB565 images using Bilinear Interpolation algorithm.
See also
enableTextureMapperRGB565, enableTextureMapperRGB565_Opaque_BilinearInterpolation
enableTextureMapperRGB565_NonOpaque_NearestNeighbor()
void enableTextureMapperRGB565_NonOpaque_NearestNeighbor ()
Enables the texture mappers for NonOpaque RGB565 image format. This allows drawing RGB565 images using Nearest Neighbor algorithm.
See also
enableTextureMapperRGB565, enableTextureMapperRGB565_Opaque_NearestNeighbor
enableTextureMapperRGB565_Opaque_BilinearInterpolation()
void enableTextureMapperRGB565_Opaque_BilinearInterpolation ()
Enables the texture mappers for Opaque RGB565 image format. This allows drawing RGB565 images using Bilinear Interpolation algorithm.
See also
enableTextureMapperRGB565, enableTextureMapperRGB565_NonOpaque_BilinearInterpolation
enableTextureMapperRGB565_Opaque_NearestNeighbor()
void enableTextureMapperRGB565_Opaque_NearestNeighbor ()
Enables the texture mappers for Opaque RGB565 image format. This allows drawing RGB565 images using Nearest Neighbor algorithm.
See also
enableTextureMapperRGB565, enableTextureMapperRGB565_NonOpaque_NearestNeighbor
enableTextureMapperRGB888()
void enableTextureMapperRGB888 ()
Enables the texture mappers for RGB888 image format. This allows drawing RGB888 images using Bilinear Interpolation and Nearest Neighbor algorithms.
See also
enableTextureMapperRGB888_BilinearInterpolation, enableTextureMapperRGB888_NearestNeighbor
enableTextureMapperRGB888_BilinearInterpolation()
void enableTextureMapperRGB888_BilinearInterpolation ()
Enables the texture mappers for RGB888 image format. This allows drawing RGB888 images using Bilinear Interpolation algorithm.
See also
enableTextureMapperRGB888, enableTextureMapperRGB888_NearestNeighbor
enableTextureMapperRGB888_NearestNeighbor()
void enableTextureMapperRGB888_NearestNeighbor ()
Enables the texture mappers for RGB888 image format. This allows drawing RGB888 images using Nearest Neighbor algorithm.
See also
enableTextureMapperRGB888, enableTextureMapperRGB888_BilinearInterpolation
expandRgb565()
static FORCE_INLINE_FUNCTION uint32_t expandRgb565 (uint16_t c) inline static private
    {
        return ((c & 0x07E0) << 16) | (c & ~0x07E0);
    }
Referenced by LCD32bpp_XRGB8888::bilinearInterpolate565(), and LCD32bpp_XRGB8888::bilinearInterpolate565().
fillBuffer()
virtual void fillBuffer (uint8_t *const destination, uint16_t pixelStride, const Rect & rect, const colortype color, const uint8_t alpha) virtual
Draws a filled rectangle in destination memory using the specified color and opacity. The destination memory must have the same format as the display framebuffer. By default the rectangle will be drawn as a solid box. The rectangle can be drawn with transparency by specifying alpha from 0=invisible to 255=solid.
Parameters
[in] destination The start of the memory area to fill.
pixelStride The pixel stride, i.e. number of pixels in a row.
rect The rectangle to fill absolute coordinates.
color The rectangle color.
alpha The rectangle opacity, from 0=invisible to 255=solid.
Note
The pixelStride is rounded up to nearest whole bytes for displays with more than one pixel per byte (LCD1bpp, LCD2bpp and LCD4bpp)
Implements LCD.
fillRect()
virtual void fillRect (const Rect & rect, colortype color, uint8_t alpha = 255) virtual
Draws a filled rectangle in the framebuffer in the specified color and opacity. By default the rectangle will be drawn as a solid box. The rectangle can be drawn with transparency by specifying alpha from 0=invisible to 255=solid.
Parameters
rect The rectangle to draw in absolute display coordinates.
color The rectangle color.
alpha (Optional) The rectangle opacity, from 0=invisible to 255=solid.
See also
fillBuffer
Implements LCD.
framebufferFormat()
virtual Bitmap::BitmapFormat framebufferFormat () const inline virtual
Framebuffer format used by the display.
Returns
A Bitmap::BitmapFormat.
Implements LCD.
    {
        return Bitmap::ARGB8888;
    }
References Bitmap::ARGB8888.
framebufferStride()
virtual uint16_t framebufferStride () const inline virtual
Framebuffer stride in bytes. The distance (in bytes) from the start of one framebuffer row, to the next.
Returns
The number of bytes in one framebuffer row.
Implements LCD.
    {
        return getFramebufferStride();
    }
References LCD32bpp_XRGB8888::getFramebufferStride().
getBlueFromColor()
static FORCE_INLINE_FUNCTION uint8_t getBlueFromColor (colortype color) inline static
Gets blue from color.
Parameters
color The color.
Returns
The blue from color.
    {
        return color & 0xFF;
    }
getFramebufferStride()
static FORCE_INLINE_FUNCTION uint16_t getFramebufferStride () inline static
Framebuffer stride in bytes. The distance (in bytes) from the start of one framebuffer row, to the next.
Returns
The number of bytes in one framebuffer row.
    {
        assert(HAL::FRAME_BUFFER_WIDTH > 0 && "HAL has not been initialized yet");
        return HAL::FRAME_BUFFER_WIDTH * 4;
    }
References HAL::FRAME_BUFFER_WIDTH.
Referenced by LCD32bpp_XRGB8888::framebufferStride().
getTextureMapperDrawScanLine()
virtual DrawTextureMapScanLineBase * getTextureMapperDrawScanLine (const TextureSurface & texture, RenderingVariant renderVariant, uint8_t alpha) protected virtual
Gets pointer to object that can draw a scan line which allows for highly specialized and optimized implementation.
Parameters
texture The texture Surface.
renderVariant The render variant.
alpha The global alpha.
Returns
Null if it fails, else the pointer to the texture mapper draw scan line object.
Reimplemented from LCD.
nextLine()
static int nextLine (bool rotatedDisplay, TextRotation textRotation) static protected
Find out how much to advance in the display buffer to get to the next line.
Parameters
rotatedDisplay Is the display running in portrait mode?
textRotation Rotation to perform.
Returns
How much to advance to get to the next line.
nextPixel()
static int nextPixel (bool rotatedDisplay, TextRotation textRotation) static protected
Find out how much to advance in the display buffer to get to the next pixel.
Parameters
rotatedDisplay Is the display running in portrait mode?
textRotation Rotation to perform.
Returns
How much to advance to get to the next pixel.
rgb888toXrgb8888()
static FORCE_INLINE_FUNCTION uint32_t rgb888toXrgb8888 (const uint8_t *const rgb888) inline static
Copies the 24bit color (blue, green, red) to the given 32bit destination, setting alpha to zero.
Parameters
rgb888 A pointer to the three bytes.
Returns
The 24bit RGB888 converted to a 32bit color value with zero alpha.
    {
        return (rgb888[2] << 16) | (rgb888[1] << 8) | rgb888[0];
    }
Referenced by PainterXRGB8888Bitmap::paint(), and PainterXRGB8888L8Bitmap::paint().
supportDynamicBitmapDrawing()
virtual bool supportDynamicBitmapDrawing (const Bitmap::BitmapFormat format) inline virtual
Check if LCD support dynamic bitmap drawing.
Parameters
format The dynamic bitmap format.
Returns
true if dynamic bitmap drawing is supported, false otherwise.
Reimplemented from LCD.
    {
        // DynamicBitmap drawing is not supported by LCD32XRGB
        return false;
    }
Member Data Documentation
decompressorL8_L4
DecompressorL8Base* decompressorL8_L4 private
decompressorL8_LZW9
DecompressorL8Base* decompressorL8_LZW9 private
decompressorL8_RLE
DecompressorL8Base* decompressorL8_RLE private
textureMapper_A4_BilinearInterpolation_GA
DrawTextureMapScanLineBase* textureMapper_A4_BilinearInterpolation_GA private
textureMapper_A4_BilinearInterpolation_NoGA
DrawTextureMapScanLineBase* textureMapper_A4_BilinearInterpolation_NoGA private
textureMapper_A4_NearestNeighbor_GA
DrawTextureMapScanLineBase* textureMapper_A4_NearestNeighbor_GA private
textureMapper_A4_NearestNeighbor_NoGA
DrawTextureMapScanLineBase* textureMapper_A4_NearestNeighbor_NoGA private
textureMapper_ARGB8888_NonOpaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase* textureMapper_ARGB8888_NonOpaque_BilinearInterpolation_GA private
textureMapper_ARGB8888_NonOpaque_NearestNeighbor_GA
DrawTextureMapScanLineBase* textureMapper_ARGB8888_NonOpaque_NearestNeighbor_GA private
textureMapper_L8_ARGB8888_NonOpaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase* textureMapper_L8_ARGB8888_NonOpaque_BilinearInterpolation_GA private
textureMapper_L8_ARGB8888_NonOpaque_NearestNeighbor_GA
DrawTextureMapScanLineBase* textureMapper_L8_ARGB8888_NonOpaque_NearestNeighbor_GA private
textureMapper_L8_RGB565_Opaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase* textureMapper_L8_RGB565_Opaque_BilinearInterpolation_GA private
textureMapper_L8_RGB565_Opaque_BilinearInterpolation_NoGA
DrawTextureMapScanLineBase* textureMapper_L8_RGB565_Opaque_BilinearInterpolation_NoGA private
textureMapper_L8_RGB565_Opaque_NearestNeighbor_GA
DrawTextureMapScanLineBase* textureMapper_L8_RGB565_Opaque_NearestNeighbor_GA private
textureMapper_L8_RGB565_Opaque_NearestNeighbor_NoGA
DrawTextureMapScanLineBase* textureMapper_L8_RGB565_Opaque_NearestNeighbor_NoGA private
textureMapper_L8_RGB888_Opaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase* textureMapper_L8_RGB888_Opaque_BilinearInterpolation_GA private
textureMapper_L8_RGB888_Opaque_BilinearInterpolation_NoGA
DrawTextureMapScanLineBase* textureMapper_L8_RGB888_Opaque_BilinearInterpolation_NoGA private
textureMapper_L8_RGB888_Opaque_NearestNeighbor_GA
DrawTextureMapScanLineBase* textureMapper_L8_RGB888_Opaque_NearestNeighbor_GA private
textureMapper_L8_RGB888_Opaque_NearestNeighbor_NoGA
DrawTextureMapScanLineBase* textureMapper_L8_RGB888_Opaque_NearestNeighbor_NoGA private
textureMapper_RGB565_NonOpaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase* textureMapper_RGB565_NonOpaque_BilinearInterpolation_GA private
textureMapper_RGB565_NonOpaque_BilinearInterpolation_NoGA
DrawTextureMapScanLineBase* textureMapper_RGB565_NonOpaque_BilinearInterpolation_NoGA private
textureMapper_RGB565_NonOpaque_NearestNeighbor_GA
DrawTextureMapScanLineBase* textureMapper_RGB565_NonOpaque_NearestNeighbor_GA private
textureMapper_RGB565_NonOpaque_NearestNeighbor_NoGA
DrawTextureMapScanLineBase* textureMapper_RGB565_NonOpaque_NearestNeighbor_NoGA private
textureMapper_RGB565_Opaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase* textureMapper_RGB565_Opaque_BilinearInterpolation_GA private
textureMapper_RGB565_Opaque_BilinearInterpolation_NoGA
DrawTextureMapScanLineBase* textureMapper_RGB565_Opaque_BilinearInterpolation_NoGA private
textureMapper_RGB565_Opaque_NearestNeighbor_GA
DrawTextureMapScanLineBase* textureMapper_RGB565_Opaque_NearestNeighbor_GA private
textureMapper_RGB565_Opaque_NearestNeighbor_NoGA
DrawTextureMapScanLineBase* textureMapper_RGB565_Opaque_NearestNeighbor_NoGA private
textureMapper_RGB888_Opaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase* textureMapper_RGB888_Opaque_BilinearInterpolation_GA private
textureMapper_RGB888_Opaque_BilinearInterpolation_NoGA
DrawTextureMapScanLineBase* textureMapper_RGB888_Opaque_BilinearInterpolation_NoGA private
textureMapper_RGB888_Opaque_NearestNeighbor_GA
DrawTextureMapScanLineBase* textureMapper_RGB888_Opaque_NearestNeighbor_GA private
textureMapper_RGB888_Opaque_NearestNeighbor_NoGA
DrawTextureMapScanLineBase* textureMapper_RGB888_Opaque_NearestNeighbor_NoGA private
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/platform/driver/lcd/LCD32bpp_XRGB8888.hpp