Battery Simulator Documentation: ScrollWheelBase
ScrollWheelBase
#include "ScrollWheelBase.hpp"
Public Member Functions
ScrollWheelBase ()
int getSelectedItem () const
virtual int16_t getSelectedItemOffset () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual int32_t keepOffsetInsideLimits (int32_t newOffset, int16_t overShoot) const
void setAnimateToCallback (GenericCallback< int16_t > &callback)
virtual void setSelectedItemOffset (int16_t offset)
Public Member Functions inherited from ScrollBase
ScrollBase ()
void allowHorizontalDrag (bool enable)
void allowVerticalDrag (bool enable)
virtual void animateToItem (int16_t itemIndex, int16_t animationSteps=-1)
uint16_t getAnimationSteps () const
virtual bool getCircular () const
uint16_t getDragAcceleration () const
virtual int16_t getDrawableMargin () const
virtual int16_t getDrawableSize () const
virtual bool getHorizontal () const
uint16_t getMaxSwipeItems () const
virtual int16_t getNumberOfItems () const
uint8_t getOvershootPercentage () const
uint16_t getSwipeAcceleration () const
virtual void handleTickEvent ()
virtual void initialize ()
bool isAnimating () const
virtual void itemChanged (int itemIndex)
void setAnimationEndedCallback (GenericCallback<> &callback)
void setAnimationSteps (int16_t steps)
virtual void setCircular (bool circular)
void setDragAcceleration (uint16_t acceleration)
virtual void setDrawableSize (int16_t drawableSize, int16_t drawableMargin)
void setEasingEquation (EasingEquation equation)
virtual void setHeight (int16_t height)
virtual void setHorizontal (bool horizontal)
void setItemPressedCallback (GenericCallback< int16_t > &callback)
void setItemSelectedCallback (GenericCallback< int16_t > &callback)
void setMaxSwipeItems (uint16_t maxItems)
virtual void setNumberOfItems (int16_t numberOfItems)
void setOvershootPercentage (uint8_t percentage)
void setSwipeAcceleration (uint16_t acceleration)
virtual void setWidth (int16_t width)
void stopAnimation ()
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual void animateToPosition (int32_t position, int16_t steps=-1)
virtual int32_t getPositionForItem (int16_t itemIndex)
Protected Member Functions inherited from ScrollBase
virtual int32_t getNearestAlignedOffset (int32_t offset) const
int getNormalizedOffset (int offset) const
virtual int32_t getOffset () const
virtual void setOffset (int32_t offset)
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
GenericCallback< int16_t > * animateToCallback
The animate to callback.
Protected Attributes inherited from ScrollBase
GenericCallback * animationEndedCallback
The animation ended callback.
AnimationState currentAnimationState
The current animation state.
uint16_t defaultAnimationSteps
The animation steps.
int16_t distanceBeforeAlignedItem
The distance before aligned item.
uint16_t dragAcceleration
The drag acceleration x10.
bool draggableX
Is the container draggable in the horizontal direction.
bool draggableY
Is the container draggable in the vertical direction.
EasingEquation easingEquation
The easing equation used for animation.
int gestureEnd
The gesture end.
int gestureStart
The gesture start.
int gestureStep
The current gesture step.
int gestureStepsTotal
The total gesture steps.
int32_t initialSwipeOffset
The initial swipe offset.
GenericCallback * itemLockedInCallback
The item locked in callback.
GenericCallback< int16_t > * itemPressedCallback
The item pressed callback.
GenericCallback< int16_t > * itemSelectedCallback
The item selected callback.
int16_t itemSize
Size of the item (including margin)
DrawableList list
The list.
uint16_t maxSwipeItems
The maximum swipe items.
int16_t numberOfDrawables
Number of drawables.
uint8_t overshootPercentage
The overshoot percentage when dragging.
uint16_t swipeAcceleration
The swipe acceleration x10.
int16_t xClick
The x coordinate of a click.
int16_t yClick
The y coordinate of a click.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Protected Types inherited from ScrollBase
enum AnimationState { NO_ANIMATION , ANIMATING_GESTURE , ANIMATING_DRAG }
Detailed Description
A base class for a scroll wheel. A scroll wheel is very much like the digit selector on a padlock with numbers. The digits always snap into place and exactly one number is always the "selected" number. Using ScrollWheel, all elements look the same, but an underlying bitmap can help emphasize the "selected" element. The ScrollWheelWithSelectionStyle can have a completely different style on the "selected" item - the font can be larger or bold and images can change color - this can help to give a kind of 3D effect using very few resources.
See also
ScrollWheel, ScrollWheelWithSelectionStyle
Constructor & Destructor Documentation
ScrollWheelBase()
ScrollWheelBase ()
    : ScrollBase(),
      animateToCallback(0)
{
    ScrollWheelBase::setHorizontal(false);
    setTouchable(true);
}
References ScrollBase::setHorizontal(), and Drawable::setTouchable().
Member Function Documentation
animateToPosition()
void animateToPosition (int32_t position, int16_t steps = -1) protected virtual
Animate to a new position/offset using the given number of steps.
Parameters
position The new position.
steps (Optional) The steps.
Reimplemented from ScrollBase.
{
    if (itemSize == 0)
    {
        return;
    }
    if (animateToCallback && animateToCallback->isValid() && itemSize > 0)
    {
        position = getNearestAlignedOffset(position);
        const int16_t itemIndex = (-position) / itemSize;
        animateToCallback->execute(itemIndex);
    }
    ScrollBase::animateToPosition(position, steps);
}
References ScrollWheelBase::animateToCallback, ScrollBase::animateToPosition(), GenericCallback< T1, T2, T3 >::execute(), ScrollBase::getNearestAlignedOffset(), GenericCallback< T1, T2, T3 >::isValid(), and ScrollBase::itemSize.
Referenced by ScrollWheelBase::handleClickEvent(), and ScrollWheelBase::handleGestureEvent().
getPositionForItem()
int32_t getPositionForItem (int16_t itemIndex) protected virtual
Get the position for an item. The position should ensure that the item is in view as defined by the semantics of the actual scroll class. If the item is already in view, the current offset is returned and not the offset of the given item.
Parameters
itemIndex Zero-based index of the item.
Returns
The position for item.
Implements ScrollBase.
{
    int32_t newOffset = -itemIndex * itemSize;
    if (getCircular())
    {
        // Check if it is closer to scroll backwards
        const int32_t otherOffset = newOffset + getNumberOfItems() * itemSize;
        const int32_t offset = getOffset();
        if (abs(otherOffset - offset) < abs(newOffset - offset))
        {
            newOffset = otherOffset;
        }
    }
    return newOffset;
}
References touchgfx::abs(), ScrollBase::getCircular(), ScrollBase::getNumberOfItems(), ScrollBase::getOffset(), and ScrollBase::itemSize.
getSelectedItem()
int getSelectedItem () const
Gets selected item. If an animation is in progress, the item that is being scrolled to is returned, not the item that happens to be flying by at the time.
Returns
The selected item.
{
    if (itemSize == 0)
    {
        return 0;
    }
    if (currentAnimationState == ANIMATING_GESTURE)
    {
        // Scroll in progress, get the destination value
        return (-getNormalizedOffset(gestureEnd)) / itemSize;
    }
    return (-getNormalizedOffset(getOffset())) / itemSize;
}
References ScrollBase::ANIMATING_GESTURE, ScrollBase::currentAnimationState, ScrollBase::gestureEnd, ScrollBase::getNormalizedOffset(), ScrollBase::getOffset(), and ScrollBase::itemSize.
Referenced by ScrollWheelBase::handleClickEvent().
getSelectedItemOffset()
int16_t getSelectedItemOffset () const virtual
Gets offset of selected item measured in pixels relative to the start of the widget.
Returns
The selected item offset.
See also
setSelectedItemOffset
{
    return distanceBeforeAlignedItem;
}
References ScrollBase::distanceBeforeAlignedItem.
handleClickEvent()
void handleClickEvent (const ClickEvent & event) virtual
Defines the event handler interface for ClickEvents. The default implementation ignores the event. The event is only received if the Drawable is touchable and visible.
Parameters
event The ClickEvent received from the HAL.
Reimplemented from Drawable.
{
    if (itemSize == 0)
    {
        return;
    }
    const int32_t offset = getOffset();
    if (event.getType() == ClickEvent::PRESSED)
    {
        xClick = event.getX();
        yClick = event.getY();
        initialSwipeOffset = offset;
        if (itemPressedCallback && itemPressedCallback->isValid())
        {
            itemPressedCallback->execute(getSelectedItem());
        }
    }
    else if (event.getType() == ClickEvent::RELEASED)
    {
        if (currentAnimationState == NO_ANIMATION)
        {
            const int16_t click = getHorizontal() ? xClick : yClick;
            // Click => move to clicked position
            if (click < distanceBeforeAlignedItem)
            {
                animateToPosition(offset + ((distanceBeforeAlignedItem - click) / itemSize + 1) * itemSize);
            }
            else if (click > distanceBeforeAlignedItem + itemSize)
            {
                animateToPosition(offset - ((click - distanceBeforeAlignedItem) / itemSize) * itemSize);
            }
            else
            {
                animateToPosition(offset);
            }
        }
        else if (currentAnimationState == ANIMATING_DRAG)
        {
            // click + drag + release. Find best Y to scroll to
            animateToPosition(offset);
        }
        if (itemSelectedCallback && itemSelectedCallback->isValid())
        {
            itemSelectedCallback->execute(getSelectedItem());
        }
    }
}
References ScrollWheelBase::animateToPosition(), ScrollBase::ANIMATING_DRAG, ScrollBase::currentAnimationState, ScrollBase::distanceBeforeAlignedItem, GenericCallback< T1, T2, T3 >::execute(), ScrollBase::getHorizontal(), ScrollBase::getOffset(), ScrollWheelBase::getSelectedItem(), ScrollBase::initialSwipeOffset, GenericCallback< T1, T2, T3 >::isValid(), ScrollBase::itemPressedCallback, ScrollBase::itemSelectedCallback, ScrollBase::itemSize, ScrollBase::NO_ANIMATION, ClickEvent::PRESSED, ClickEvent::RELEASED, ScrollBase::xClick, and ScrollBase::yClick.
handleDragEvent()
void handleDragEvent (const DragEvent & event) virtual
Defines the event handler interface for DragEvents. The default implementation ignores the event. The event is only received if the drawable is touchable and visible.
Parameters
event The DragEvent received from the HAL.
Reimplemented from ScrollBase.
{
    currentAnimationState = ANIMATING_DRAG;
    int newOffset = getOffset() + (getHorizontal() ? event.getDeltaX() : event.getDeltaY()) * dragAcceleration / 10;
    newOffset = keepOffsetInsideLimits(newOffset, overshootPercentage);
    setOffset(newOffset);
}
References ScrollBase::ANIMATING_DRAG, ScrollBase::currentAnimationState, ScrollBase::dragAcceleration, ScrollBase::getHorizontal(), ScrollBase::getOffset(), ScrollWheelBase::keepOffsetInsideLimits(), ScrollBase::overshootPercentage, and ScrollBase::setOffset().
handleGestureEvent()
void handleGestureEvent (const GestureEvent & event) virtual
Defines the event handler interface for GestureEvents. The default implementation ignores the event. The event is only received if the Drawable is touchable and visible.
Parameters
event The GestureEvent received from the HAL.
Reimplemented from ScrollBase.
{
    if (event.getType() == (getHorizontal() ? GestureEvent::SWIPE_HORIZONTAL : GestureEvent::SWIPE_VERTICAL))
    {
        int32_t newOffset = getOffset() + event.getVelocity() * swipeAcceleration / 10;
        if (maxSwipeItems > 0)
        {
            const int32_t maxDistance = maxSwipeItems * itemSize;
            newOffset = MIN(newOffset, initialSwipeOffset + maxDistance);
            newOffset = MAX(newOffset, initialSwipeOffset - maxDistance);
        }
        animateToPosition(newOffset);
    }
}
References ScrollWheelBase::animateToPosition(), ScrollBase::getHorizontal(), ScrollBase::getOffset(), ScrollBase::initialSwipeOffset, ScrollBase::itemSize, MAX, ScrollBase::maxSwipeItems, MIN, GestureEvent::SWIPE_HORIZONTAL, GestureEvent::SWIPE_VERTICAL, and ScrollBase::swipeAcceleration.
keepOffsetInsideLimits()
int32_t keepOffsetInsideLimits (int32_t newOffset, int16_t overShoot) const virtual
Keep offset inside limits. Return the new offset that is inside the limits of the scroll list, with the overShoot value added at both ends of the list.
Parameters
newOffset The new offset.
overShoot The over shoot.
Returns
The new offset inside the limits.
Implements ScrollBase.
{
    if (!getCircular())
    {
        newOffset = MIN(newOffset, overShoot);
        const int16_t numberOfItems = getNumberOfItems();
        newOffset = MAX(newOffset, -(itemSize * (numberOfItems - 1)) - overShoot);
    }
    return newOffset;
}
References ScrollBase::getCircular(), ScrollBase::getNumberOfItems(), ScrollBase::itemSize, MAX, and MIN.
Referenced by ScrollWheelBase::handleDragEvent(), and ScrollWheelWithSelectionStyle::refreshDrawableListsLayout().
setAnimateToCallback()
void setAnimateToCallback (GenericCallback< int16_t > & callback)
Sets Callback which will be called when the ScrollWheel animates to a new item.
Parameters
[in] callback The callback.
{
    animateToCallback = &callback;
}
References ScrollWheelBase::animateToCallback.
setSelectedItemOffset()
void setSelectedItemOffset (int16_t offset) virtual
Sets selected item offset, measured in pixels, from the edge of the widget. The offset is the relative x coordinate if the ScrollWheel is horizontal, otherwise it is the relative y coordinate. If this value is zero, the selected item is placed at the very start of the widget.
Parameters
offset The offset.
See also
getSelectedItemOffset
Reimplemented in ScrollWheelWithSelectionStyle.
{
    const int32_t currentOffset = getOffset();
    distanceBeforeAlignedItem = offset;
    setOffset(currentOffset);
}
References ScrollBase::distanceBeforeAlignedItem, ScrollBase::getOffset(), and ScrollBase::setOffset().
Referenced by ScrollWheelWithSelectionStyle::setSelectedItemOffset().
Member Data Documentation
animateToCallback
GenericCallback<int16_t>* animateToCallback protected
The animate to callback.
Referenced by ScrollWheelBase::animateToPosition(), and ScrollWheelBase::setAnimateToCallback().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/scrollers/ScrollWheelBase.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/scrollers/ScrollWheelBase.cpp