Battery Simulator Documentation: OSWrappers
OSWrappers
#include "OSWrappers.hpp"
Static Public Member Functions
static void deinitialize ()
static void giveFrameBufferSemaphore ()
static void giveFrameBufferSemaphoreFromISR ()
static void initialize ()
static bool isVSyncAvailable ()
static void signalRenderingDone ()
static void signalVSync ()
static void takeFrameBufferSemaphore ()
static void taskDelay (uint16_t ms)
static void taskYield ()
static void tryTakeFrameBufferSemaphore ()
static void waitForVSync ()
Detailed Description
This class specifies OS wrappers for dealing with the framebuffer semaphore and the VSYNC signal.
Member Function Documentation
deinitialize()
void deinitialize () static
Initialize framebuffer semaphore and queue/mutex for VSYNC signal.
{
    if (s_FrameBufferLock)
    {
        SDL_DestroyMutex(s_FrameBufferLock);
        s_FrameBufferLock = NULL;
    }
}
References NULL, touchgfx::s_FrameBufferLock, and SDL_DestroyMutex().
Referenced by OSWrappers::initialize().
giveFrameBufferSemaphore()
void giveFrameBufferSemaphore () static
Release the framebuffer semaphore.
{
    assert(framebufferLocked && "Framebuffers not previously locked");
    framebufferLocked = false;
    SDL_UnlockMutex(s_FrameBufferLock);
}
References touchgfx::framebufferLocked, touchgfx::s_FrameBufferLock, and SDL_UnlockMutex().
giveFrameBufferSemaphoreFromISR()
void giveFrameBufferSemaphoreFromISR () static
Release the framebuffer semaphore in a way that is safe in interrupt context. Called from ISR.
{
}
initialize()
void initialize () static
Initialize framebuffer semaphore and queue/mutex for VSYNC signal.
{
    atexit(deinitialize);
    // Setup framebuffer lock
    s_FrameBufferLock = SDL_CreateMutex();
    framebufferLocked = false;
}
References OSWrappers::deinitialize(), touchgfx::framebufferLocked, touchgfx::s_FrameBufferLock, and SDL_CreateMutex().
isVSyncAvailable()
static bool isVSyncAvailable () static
This function checks if a VSync occurred after last rendering. The function is used in systems that cannot wait in waitForVSync (because they are also checking other event sources.
Note
signalRenderingDone is typically used together with this function.
Returns
True if VSync occurred.
signalRenderingDone()
void signalRenderingDone () static
Signal that the rendering of the frame has completed. Used by some systems to avoid using any previous vsync.
{
    // Empty implementation for CMSIS V2
}
signalVSync()
void signalVSync () static
Signal that a VSYNC has occurred. Should make the vsync queue/mutex available.
Note
This function is called from an ISR, and should (depending on OS) trigger a scheduling.
{
    if (vsync_q)
    {
        // Since this is called from an interrupt, FreeRTOS requires special handling to trigger a
        // re-scheduling. May be applicable for other OSes as well.
        portBASE_TYPE px = pdFALSE;
        xQueueSendFromISR(vsync_q, &dummy, &px);
        portEND_SWITCHING_ISR(px);
    }
}
References dummy, and vsync_q.
Referenced by HAL_LTDC_LineEventCallback().
takeFrameBufferSemaphore()
void takeFrameBufferSemaphore () static
Take the framebuffer semaphore. Blocks until semaphore is available.
{
    assert(!framebufferLocked && "Framebuffers already locked");
    framebufferLocked = true;
    SDL_LockMutex(s_FrameBufferLock);
}
References touchgfx::framebufferLocked, touchgfx::s_FrameBufferLock, and SDL_LockMutex().
taskDelay()
void taskDelay (uint16_t ms) static
A function that causes executing task to sleep for a number of milliseconds. This function is OPTIONAL. It is only used by the TouchGFX in the case of a specific frame refresh strategy (REFRESH_STRATEGY_OPTIM_SINGLE_BUFFER_TFT_CTRL). Due to backwards compatibility, in order for this function to be usable by the HAL the function must be explicitly registered: hal.registerTaskDelayFunction(&OSWrappers::taskDelay)
Parameters
ms The number of milliseconds to sleep.
See also
HAL::setFrameRefreshStrategy, HAL::registerTaskDelayFunction
{
    vTaskDelay(ms);
}
taskYield()
void taskYield () static
A function that causes the executing task to yield control to another thread. This function is used by the framework when it is necessary to wait a little before continuing (e.g. drawing).
The implementation should typically request the operating system to change to another task of similar priority. When running without an operating system, the implementation can run a very short task and return.
{
}
tryTakeFrameBufferSemaphore()
void tryTakeFrameBufferSemaphore () static
Attempt to obtain the framebuffer semaphore. If semaphore is not available, do nothing.
Note
must return immediately! This function does not care who has the taken the semaphore, it only serves to make sure that the semaphore is taken by someone.
{
}
waitForVSync()
void waitForVSync () static
This function blocks until a VSYNC occurs.
Note
This function must first clear the mutex/queue and then wait for the next one to occur.
{
}
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/hal/OSWrappers.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/platform/hal/simulator/sdl2/OSWrappers.cpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/os/OSWrappers.cpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/os/OSWrappers_cmsis.cpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/target/generated/OSWrappers.cpp