Battery Simulator Documentation: TypedText
TypedText
#include "TypedText.hpp"
Classes
struct TypedTextData
Public Member Functions
TypedText (const TypedTextId id=TYPED_TEXT_INVALID)
virtual ~TypedText ()
FORCE_INLINE_FUNCTION Alignment getAlignment () const
FORCE_INLINE_FUNCTION const Font * getFont () const
FORCE_INLINE_FUNCTION FontId getFontId () const
FORCE_INLINE_FUNCTION TypedTextId getId () const
FORCE_INLINE_FUNCTION const Unicode::UnicodeChar * getText () const
FORCE_INLINE_FUNCTION TextDirection getTextDirection () const
FORCE_INLINE_FUNCTION bool hasValidId () const
Static Public Member Functions
static void registerTexts (const Texts *t)
static void registerTypedTextDatabase (const TypedTextData *data, const Font *const *f, const uint16_t n)
Private Attributes
TypedTextId typedTextId
Static Private Attributes
static const Font *const * fonts
static uint16_t numberOfTypedTexts
static const Texts * texts
static const TypedTextData * typedTexts
Detailed Description
TypedText represents text (for characters) and typography (for font and alignment). TypedText provides methods for adjusting the text, font and alignment.
See also
TextArea
Constructor & Destructor Documentation
TypedText()
TypedText (const TypedTextId id = TYPED_TEXT_INVALID) inline
Initializes a new instance of the TypedText class.
Parameters
id (Optional) The identifier.
        : typedTextId(id)
    {
    }
~TypedText()
virtual ~TypedText () inline virtual
Finalizes an instance of the TypedText class.
    {
    }
Member Function Documentation
getAlignment()
FORCE_INLINE_FUNCTION Alignment getAlignment () const inline
Gets the alignment associated with this TypedText.
Returns
The alignment.
    {
        assert(typedTexts != 0 && "TypedText database has not been initialized.");
        assert(hasValidId() && "typedTextId larger than numberOfTypedTexts.");
        return typedTexts[typedTextId].alignment;
    }
References TypedText::hasValidId(), TypedText::typedTextId, and TypedText::typedTexts.
Referenced by ButtonWithLabel::draw(), TextAreaWithWildcardBase::draw(), GraphTitle::draw(), GraphLabelsX::drawString(), GraphLabelsY::drawString(), and TextArea::getAlignment().
getFont()
FORCE_INLINE_FUNCTION const Font * getFont () const inline
Gets the font associated with this TypedText.
Returns
The font.
    {
        assert(typedTexts != 0 && "TypedText database has not been initialized.");
        assert(hasValidId() && "typedTextId larger than numberOfTypedTexts.");
        return fonts[typedTexts[typedTextId].fontIdx];
    }
References TypedText::fonts, TypedText::hasValidId(), TypedText::typedTextId, and TypedText::typedTexts.
Referenced by TextArea::calculateBoundingArea(), TextArea::calculateTextHeight(), ButtonWithLabel::draw(), TextArea::draw(), TextAreaWithWildcardBase::draw(), GraphLabelsBase::draw(), GraphTitle::draw(), TextArea::getTextWidth(), GraphLabelsX::invalidateGraphPointAt(), and ButtonWithLabel::updateTextPosition().
getFontId()
FORCE_INLINE_FUNCTION FontId getFontId () const inline
Gets the font ID associated with this TypedText.
Returns
The font.
    {
        assert(typedTexts != 0 && "TypedText database has not been initialized.");
        assert(hasValidId() && "typedTextId larger than numberOfTypedTexts.");
        return typedTexts[typedTextId].fontIdx;
    }
References TypedText::hasValidId(), TypedText::typedTextId, and TypedText::typedTexts.
getId()
FORCE_INLINE_FUNCTION TypedTextId getId () const inline
Gets the id of the typed text.
Returns
The id.
    {
        return typedTextId;
    }
References TypedText::typedTextId.
getText()
FORCE_INLINE_FUNCTION const Unicode::UnicodeChar * getText () const inline
Gets the text associated with this TypedText.
Returns
The text.
    {
        assert(typedTexts != 0 && "TypedText database has not been initialized.");
        assert(hasValidId() && "typedTextId larger than numberOfTypedTexts.");
        return texts->getText(typedTextId);
    }
References TypedText::hasValidId(), TypedText::texts, TypedText::typedTextId, and TypedText::typedTexts.
Referenced by TextArea::calculateBoundingArea(), ButtonWithLabel::draw(), TextArea::draw(), TextAreaWithWildcardBase::draw(), GraphTitle::draw(), GraphLabelsX::drawString(), GraphLabelsY::drawString(), TextArea::getTextHeight(), TextArea::getTextWidth(), TextArea::invalidateContent(), GraphLabelsX::invalidateGraphPointAt(), and ButtonWithLabel::updateTextPosition().
getTextDirection()
FORCE_INLINE_FUNCTION TextDirection getTextDirection () const inline
Gets the text direction associated with this TypedText.
Returns
The alignment.
    {
        assert(typedTexts != 0 && "TypedText database has not been initialized.");
        assert(hasValidId() && "typedTextId larger than numberOfTypedTexts.");
        return typedTexts[typedTextId].direction;
    }
References TypedText::hasValidId(), TypedText::typedTextId, and TypedText::typedTexts.
Referenced by TextArea::calculateBoundingArea(), TextArea::calculateTextHeight(), ButtonWithLabel::draw(), TextArea::draw(), TextAreaWithWildcardBase::draw(), GraphTitle::draw(), GraphLabelsX::drawString(), GraphLabelsY::drawString(), and TextArea::getTextWidth().
hasValidId()
FORCE_INLINE_FUNCTION bool hasValidId () const inline
Has the TypedText been set to a proper value?
Returns
Is the id valid.
    {
        return typedTextId < numberOfTypedTexts;
    }
References TypedText::numberOfTypedTexts, and TypedText::typedTextId.
Referenced by TextArea::calculateBoundingArea(), TextArea::calculateTextHeight(), ButtonWithLabel::draw(), TextArea::draw(), TextAreaWithWildcardBase::draw(), GraphLabelsBase::draw(), GraphTitle::draw(), TypedText::getAlignment(), TextArea::getAlignment(), TypedText::getFont(), TypedText::getFontId(), TypedText::getText(), TypedText::getTextDirection(), TextArea::getTextHeight(), TextArea::getTextWidth(), TextArea::invalidateContent(), GraphLabelsX::invalidateGraphPointAt(), TextArea::resizeHeightToCurrentText(), TextArea::resizeHeightToCurrentTextWithRotation(), TextArea::resizeToCurrentText(), TextArea::resizeToCurrentTextWithAlignment(), and ButtonWithLabel::updateTextPosition().
registerTexts()
static void registerTexts (const Texts * t) inline static
Registers an array of texts. This function is called automatically from touchgfx_generic_init(). Should not be called under normal circumstances.
Parameters
t The array of texts.
    {
        texts = t;
    }
References TypedText::texts.
Referenced by touchgfx::touchgfx_generic_init(), and touchgfx::touchgfx_init().
registerTypedTextDatabase()
static void registerTypedTextDatabase (const TypedTextData * data, const Font *const * f, const uint16_t n) inline static
Registers an array of typed texts. All typed text instances are bound to this database. This function is called automatically when setting a new language. Use Texts::setLanguage() instead of calling this function directly.
Parameters
data A reference to the TypedTextData storage array.
f The fonts associated with the array.
n The number of typed texts in the array.
    {
        typedTexts = data;
        fonts = f;
        numberOfTypedTexts = n;
    }
References TypedText::fonts, TypedText::numberOfTypedTexts, and TypedText::typedTexts.
Referenced by Texts::setLanguage().
Member Data Documentation
fonts
const Font* const* fonts static private
Referenced by TypedText::getFont(), and TypedText::registerTypedTextDatabase().
numberOfTypedTexts
uint16_t numberOfTypedTexts static private
Referenced by TypedText::hasValidId(), and TypedText::registerTypedTextDatabase().
texts
const Texts* texts static private
Referenced by TypedText::getText(), and TypedText::registerTexts().
typedTextId
TypedTextId typedTextId private
Referenced by TypedText::getAlignment(), TypedText::getFont(), TypedText::getFontId(), TypedText::getId(), TypedText::getText(), TypedText::getTextDirection(), and TypedText::hasValidId().
typedTexts
const TypedTextData* typedTexts static private
Referenced by TypedText::getAlignment(), TypedText::getFont(), TypedText::getFontId(), TypedText::getText(), TypedText::getTextDirection(), and TypedText::registerTypedTextDatabase().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/TypedText.hpp