Battery Simulator Documentation: ScrollWheelWithSelectionStyle
ScrollWheelWithSelectionStyle
#include "ScrollWheelWithSelectionStyle.hpp"
Public Member Functions
ScrollWheelWithSelectionStyle ()
virtual int16_t getSelectedItemExtraSizeAfter () const
virtual int16_t getSelectedItemExtraSizeBefore () const
virtual int16_t getSelectedItemMarginAfter () const
virtual int16_t getSelectedItemMarginBefore () const
virtual void initialize ()
virtual void itemChanged (int itemIndex)
virtual void setCircular (bool circular)
virtual void setDrawables (DrawableListItemsInterface &drawableListItems, GenericCallback< DrawableListItemsInterface *, int16_t, int16_t > &updateDrawableCallback, DrawableListItemsInterface &centerDrawableListItems, GenericCallback< DrawableListItemsInterface *, int16_t, int16_t > &updateCenterDrawableCallback)
virtual void setDrawableSize (int16_t drawableSize, int16_t drawableMargin)
virtual void setHeight (int16_t height)
virtual void setHorizontal (bool horizontal)
virtual void setNumberOfItems (int16_t numberOfItems)
virtual void setSelectedItemExtraSize (int16_t extraSizeBefore, int16_t extraSizeAfter)
virtual void setSelectedItemMargin (int16_t marginBefore, int16_t marginAfter)
virtual void setSelectedItemOffset (int16_t offset)
virtual void setSelectedItemPosition (int16_t offset, int16_t extraSizeBefore, int16_t extraSizeAfter, int16_t marginBefore, int16_t marginAfter)
virtual void setWidth (int16_t width)
Public Member Functions inherited from ScrollWheelBase
ScrollWheelBase ()
int getSelectedItem () const
virtual int16_t getSelectedItemOffset () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual int32_t keepOffsetInsideLimits (int32_t newOffset, int16_t overShoot) const
void setAnimateToCallback (GenericCallback< int16_t > &callback)
Public Member Functions inherited from ScrollBase
ScrollBase ()
void allowHorizontalDrag (bool enable)
void allowVerticalDrag (bool enable)
virtual void animateToItem (int16_t itemIndex, int16_t animationSteps=-1)
uint16_t getAnimationSteps () const
virtual bool getCircular () const
uint16_t getDragAcceleration () const
virtual int16_t getDrawableMargin () const
virtual int16_t getDrawableSize () const
virtual bool getHorizontal () const
uint16_t getMaxSwipeItems () const
virtual int16_t getNumberOfItems () const
uint8_t getOvershootPercentage () const
uint16_t getSwipeAcceleration () const
virtual void handleTickEvent ()
bool isAnimating () const
void setAnimationEndedCallback (GenericCallback<> &callback)
void setAnimationSteps (int16_t steps)
void setDragAcceleration (uint16_t acceleration)
void setEasingEquation (EasingEquation equation)
void setItemPressedCallback (GenericCallback< int16_t > &callback)
void setItemSelectedCallback (GenericCallback< int16_t > &callback)
void setMaxSwipeItems (uint16_t maxItems)
void setOvershootPercentage (uint8_t percentage)
void setSwipeAcceleration (uint16_t acceleration)
void stopAnimation ()
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
void refreshDrawableListsLayout ()
virtual void setOffset (int32_t offset)
Protected Member Functions inherited from ScrollWheelBase
virtual void animateToPosition (int32_t position, int16_t steps=-1)
virtual int32_t getPositionForItem (int16_t itemIndex)
Protected Member Functions inherited from ScrollBase
virtual int32_t getNearestAlignedOffset (int32_t offset) const
int getNormalizedOffset (int offset) const
virtual int32_t getOffset () const
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
DrawableListItemsInterface * centerDrawables
The drawables at the center of the scroll wheel.
DrawableListItemsInterface * drawables
The drawables at the beginning and end of the scroll wheel.
int16_t drawablesInFirstList
List of drawables in firsts.
int16_t extraSizeAfterSelectedItem
The distance after selected item.
int16_t extraSizeBeforeSelectedItem
The distance before selected item.
DrawableList listAfter
The list of items after the center.
DrawableList listCenter
The center list.
int16_t marginAfterSelectedItem
The distance after selected item.
int16_t marginBeforeSelectedItem
The distance before selected item.
GenericCallback< DrawableListItemsInterface *, int16_t, int16_t > * originalUpdateCenterDrawableCallback
The original update center drawable callback.
GenericCallback< DrawableListItemsInterface *, int16_t, int16_t > * originalUpdateDrawableCallback
The original update drawable callback.
Protected Attributes inherited from ScrollWheelBase
GenericCallback< int16_t > * animateToCallback
The animate to callback.
Protected Attributes inherited from ScrollBase
GenericCallback * animationEndedCallback
The animation ended callback.
AnimationState currentAnimationState
The current animation state.
uint16_t defaultAnimationSteps
The animation steps.
int16_t distanceBeforeAlignedItem
The distance before aligned item.
uint16_t dragAcceleration
The drag acceleration x10.
bool draggableX
Is the container draggable in the horizontal direction.
bool draggableY
Is the container draggable in the vertical direction.
EasingEquation easingEquation
The easing equation used for animation.
int gestureEnd
The gesture end.
int gestureStart
The gesture start.
int gestureStep
The current gesture step.
int gestureStepsTotal
The total gesture steps.
int32_t initialSwipeOffset
The initial swipe offset.
GenericCallback * itemLockedInCallback
The item locked in callback.
GenericCallback< int16_t > * itemPressedCallback
The item pressed callback.
GenericCallback< int16_t > * itemSelectedCallback
The item selected callback.
int16_t itemSize
Size of the item (including margin)
DrawableList list
The list.
uint16_t maxSwipeItems
The maximum swipe items.
int16_t numberOfDrawables
Number of drawables.
uint8_t overshootPercentage
The overshoot percentage when dragging.
uint16_t swipeAcceleration
The swipe acceleration x10.
int16_t xClick
The x coordinate of a click.
int16_t yClick
The y coordinate of a click.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Protected Types inherited from ScrollBase
enum AnimationState { NO_ANIMATION , ANIMATING_GESTURE , ANIMATING_DRAG }
Detailed Description
A scroll wheel is very much like the digit selector on a padlock with numbers. The digits always snap into place and exactly one number is always the "selected" number. Similar to an ordinary ScrollWheel, but with a different style for the selected item which can thus be bold, have a different color or similar effect to highlight it and help create a 3D effect using very few resources.
See also
DrawableList, ScrollWheel
Constructor & Destructor Documentation
ScrollWheelWithSelectionStyle()
ScrollWheelWithSelectionStyle ()
    : ScrollWheelBase(),
      drawablesInFirstList(0),
      listCenter(),
      listAfter(),
      extraSizeBeforeSelectedItem(0),
      extraSizeAfterSelectedItem(0),
      marginBeforeSelectedItem(0),
      marginAfterSelectedItem(0),
      drawables(0),
      centerDrawables(0),
      originalUpdateDrawableCallback(0),
      originalUpdateCenterDrawableCallback(0)
{
    ScrollWheelBase::add(listAfter);
    ScrollWheelBase::add(listCenter); // Put center list at top of the first/last list.
}
References Container::add(), ScrollWheelWithSelectionStyle::listAfter, and ScrollWheelWithSelectionStyle::listCenter.
Member Function Documentation
getSelectedItemExtraSizeAfter()
int16_t getSelectedItemExtraSizeAfter () const virtual
Gets selected item extra size after.
Returns
The selected item extra size after.
See also
setSelectedItemExtraSize
{
    return extraSizeAfterSelectedItem;
}
References ScrollWheelWithSelectionStyle::extraSizeAfterSelectedItem.
getSelectedItemExtraSizeBefore()
int16_t getSelectedItemExtraSizeBefore () const virtual
Gets selected item extra size before.
Returns
The selected item extra size before.
See also
setSelectedItemExtraSize
{
    return extraSizeBeforeSelectedItem;
}
References ScrollWheelWithSelectionStyle::extraSizeBeforeSelectedItem.
getSelectedItemMarginAfter()
int16_t getSelectedItemMarginAfter () const virtual
Gets selected item margin after.
Returns
The selected item margin after.
See also
setSelectedItemMargin
{
    return marginAfterSelectedItem;
}
References ScrollWheelWithSelectionStyle::marginAfterSelectedItem.
getSelectedItemMarginBefore()
int16_t getSelectedItemMarginBefore () const virtual
Gets selected item margin before.
Returns
The selected item margin before.
See also
setSelectedItemMargin
{
    return marginBeforeSelectedItem;
}
References ScrollWheelWithSelectionStyle::marginBeforeSelectedItem.
initialize()
virtual void initialize () inline virtual
Removed all drawables and initializes the content of these items.
Reimplemented from ScrollBase.
    {
        ScrollWheelBase::initialize();
        listCenter.refreshDrawables();
        listAfter.refreshDrawables();
    }
References ScrollBase::initialize(), ScrollWheelWithSelectionStyle::listAfter, ScrollWheelWithSelectionStyle::listCenter, and DrawableList::refreshDrawables().
itemChanged()
void itemChanged (int itemIndex) virtual
Inform the scroll list that the contents of an item has changed and force all drawables with the given item index to be updated via the callback provided. This is important as a circular list with very few items might display the same item more than once and all these items should be updated.
Parameters
itemIndex Zero-based index of the changed item.
Reimplemented from ScrollBase.
{
    ScrollWheelBase::itemChanged(itemIndex);
    listCenter.itemChanged(itemIndex);
    listAfter.itemChanged(itemIndex);
}
References ScrollBase::itemChanged(), DrawableList::itemChanged(), ScrollWheelWithSelectionStyle::listAfter, and ScrollWheelWithSelectionStyle::listCenter.
refreshDrawableListsLayout()
void refreshDrawableListsLayout () protected
Refresh drawable lists layout. Ensure that the three DrawableLists are places correctly and setup properly. This is typically done after the ScrollWheelWithSelectionStyle has been resized or the size of the selected item is changed.
{
    if (drawables != 0 && centerDrawables != 0)
    {
        const int32_t currentOffset = getOffset();
        const int16_t listCenterPos = distanceBeforeAlignedItem - extraSizeBeforeSelectedItem;
        const int16_t listAfterPos = distanceBeforeAlignedItem + itemSize + (extraSizeAfterSelectedItem + marginAfterSelectedItem);
        const int16_t listBeforeSize = listCenterPos - marginBeforeSelectedItem;
        const int16_t listCenterSize = itemSize + extraSizeBeforeSelectedItem + extraSizeAfterSelectedItem;
        if (getHorizontal())
        {
            const int16_t listAfterSize = getWidth() - listAfterPos;
            list.setPosition(0, 0, listBeforeSize, getHeight());
            listCenter.setPosition(listCenterPos, 0, listCenterSize, getHeight());
            listAfter.setPosition(listAfterPos, 0, listAfterSize, getHeight());
        }
        else
        {
            const int16_t listAfterSize = getHeight() - listAfterPos;
            list.setPosition(0, 0, getWidth(), listBeforeSize);
            listCenter.setPosition(0, listCenterPos, getWidth(), listCenterSize);
            listAfter.setPosition(0, listAfterPos, getWidth(), listAfterSize);
        }
        list.setDrawables(*drawables, 0, *originalUpdateDrawableCallback);
        drawablesInFirstList = list.getNumberOfDrawables();
        listCenter.setDrawables(*centerDrawables, 0, *originalUpdateCenterDrawableCallback);
        listAfter.setDrawables(*drawables, drawablesInFirstList, *originalUpdateDrawableCallback);
        setOffset(keepOffsetInsideLimits(currentOffset, 0));
    }
}
References ScrollWheelWithSelectionStyle::centerDrawables, ScrollBase::distanceBeforeAlignedItem, ScrollWheelWithSelectionStyle::drawables, ScrollWheelWithSelectionStyle::drawablesInFirstList, ScrollWheelWithSelectionStyle::extraSizeAfterSelectedItem, ScrollWheelWithSelectionStyle::extraSizeBeforeSelectedItem, Drawable::getHeight(), ScrollBase::getHorizontal(), DrawableList::getNumberOfDrawables(), ScrollBase::getOffset(), Drawable::getWidth(), ScrollBase::itemSize, ScrollWheelBase::keepOffsetInsideLimits(), ScrollBase::list, ScrollWheelWithSelectionStyle::listAfter, ScrollWheelWithSelectionStyle::listCenter, ScrollWheelWithSelectionStyle::marginAfterSelectedItem, ScrollWheelWithSelectionStyle::marginBeforeSelectedItem, ScrollWheelWithSelectionStyle::originalUpdateCenterDrawableCallback, ScrollWheelWithSelectionStyle::originalUpdateDrawableCallback, DrawableList::setDrawables(), ScrollWheelWithSelectionStyle::setOffset(), and Drawable::setPosition().
Referenced by ScrollWheelWithSelectionStyle::setDrawables(), ScrollWheelWithSelectionStyle::setDrawableSize(), ScrollWheelWithSelectionStyle::setHeight(), ScrollWheelWithSelectionStyle::setHorizontal(), ScrollWheelWithSelectionStyle::setSelectedItemExtraSize(), ScrollWheelWithSelectionStyle::setSelectedItemMargin(), ScrollWheelWithSelectionStyle::setSelectedItemOffset(), and ScrollWheelWithSelectionStyle::setWidth().
setCircular()
void setCircular (bool circular) virtual
Sets whether the list is circular (infinite) or not. A circular list is a list where the first drawable re-appears after the last item in the list - and the last item in the list appears before the first item in the list.
Parameters
circular True if the list should be circular, false if the list should not be circular.
See also
DrawableList::setCircular, getCircular
Reimplemented from ScrollBase.
{
    ScrollWheelBase::setCircular(circular);
    listCenter.setCircular(circular);
    listAfter.setCircular(circular);
}
References ScrollWheelWithSelectionStyle::listAfter, ScrollWheelWithSelectionStyle::listCenter, DrawableList::setCircular(), and ScrollBase::setCircular().
setDrawables()
void setDrawables (DrawableListItemsInterface & drawableListItems, GenericCallback< DrawableListItemsInterface *, int16_t, int16_t > & updateDrawableCallback, DrawableListItemsInterface & centerDrawableListItems, GenericCallback< DrawableListItemsInterface *, int16_t, int16_t > & updateCenterDrawableCallback) virtual
Setups the widget. Numerous parameters control the position of the widget, the two scroll lists inside and the values in them.
Parameters
[in] drawableListItems Number of drawables in outer array.
[in] updateDrawableCallback The callback to update a drawable.
[in] centerDrawableListItems Number of drawables in center array.
[in] updateCenterDrawableCallback The callback to update a center drawable.
{
    drawables = &drawableListItems;
    centerDrawables = &centerDrawableListItems;
    currentAnimationState = NO_ANIMATION;
    originalUpdateDrawableCallback = &updateDrawableCallback;
    originalUpdateCenterDrawableCallback = &updateCenterDrawableCallback;
    refreshDrawableListsLayout();
    setOffset(0);
}
References ScrollWheelWithSelectionStyle::centerDrawables, ScrollBase::currentAnimationState, ScrollWheelWithSelectionStyle::drawables, ScrollBase::NO_ANIMATION, ScrollWheelWithSelectionStyle::originalUpdateCenterDrawableCallback, ScrollWheelWithSelectionStyle::originalUpdateDrawableCallback, ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), and ScrollWheelWithSelectionStyle::setOffset().
setDrawableSize()
void setDrawableSize (int16_t drawableSize, int16_t drawableMargin) virtual
Sets drawables size. The drawable is is the size of each drawable in the list in the set direction of the list (this is enforced by the DrawableList class). The specified margin is added above and below each item for spacing. The entire size of an item is thus size + 2 * spacing.
For a horizontal list each element will be drawableSize high and have the same width as set using setWidth(). For a vertical list each element will be drawableSize wide and have the same height as set using setHeight().
Parameters
drawableSize The size of the drawable.
drawableMargin The margin around drawables (margin before and margin after).
See also
setWidth, setHeight, setHorizontal
Reimplemented from ScrollBase.
{
    ScrollWheelBase::setDrawableSize(drawableSize, drawableMargin);
    listCenter.setDrawableSize(drawableSize, drawableMargin);
    listAfter.setDrawableSize(drawableSize, drawableMargin);
    // Resize the three lists
    setSelectedItemOffset(distanceBeforeAlignedItem);
    // Changing the drawable size alters number of required drawables, so refresh this
    refreshDrawableListsLayout();
}
References ScrollBase::distanceBeforeAlignedItem, ScrollWheelWithSelectionStyle::listAfter, ScrollWheelWithSelectionStyle::listCenter, ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), DrawableList::setDrawableSize(), ScrollBase::setDrawableSize(), and ScrollWheelWithSelectionStyle::setSelectedItemOffset().
setHeight()
void setHeight (int16_t height) virtual
Sets the height of this drawable.
Parameters
height The new height.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Also sets the height of the children.
Reimplemented from ScrollBase.
{
    ScrollWheelBase::setHeight(height);
    if (!getHorizontal())
    {
        refreshDrawableListsLayout();
    }
}
References ScrollBase::getHorizontal(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), and ScrollBase::setHeight().
setHorizontal()
void setHorizontal (bool horizontal) virtual
Sets a horizontal or vertical layout. If parameter horizontal is set true, all drawables are arranged side by side. If horizontal is set false, the drawables are arranged above and below each other (vertically).
Parameters
horizontal True to align drawables horizontal, false to align drawables vertically.
See also
DrawableList::setHorizontal, getHorizontal
Note
Default value is false, i.e. vertical layout.
Reimplemented from ScrollBase.
{
    ScrollWheelBase::setHorizontal(horizontal);
    listCenter.setHorizontal(horizontal);
    listAfter.setHorizontal(horizontal);
    refreshDrawableListsLayout();
}
References ScrollWheelWithSelectionStyle::listAfter, ScrollWheelWithSelectionStyle::listCenter, ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), DrawableList::setHorizontal(), and ScrollBase::setHorizontal().
setNumberOfItems()
void setNumberOfItems (int16_t numberOfItems) virtual
Sets number of items in the DrawableList. This forces all drawables to be updated to ensure that the content is correct. For example a date selector might switch number of days between 28, 29, 30, and 31 depending on the month. A circular list might show 27-28-29-30-31 and might need to update this to show 27-28-1-2-3.
Parameters
numberOfItems Number of items.
Note
The DrawableList is refreshed to reflect the change.
Reimplemented from ScrollBase.
{
    if (numberOfItems != getNumberOfItems())
    {
        ScrollWheelBase::setNumberOfItems(numberOfItems);
        listCenter.setNumberOfItems(numberOfItems);
        listAfter.setNumberOfItems(numberOfItems);
    }
}
References ScrollBase::getNumberOfItems(), ScrollWheelWithSelectionStyle::listAfter, ScrollWheelWithSelectionStyle::listCenter, DrawableList::setNumberOfItems(), and ScrollBase::setNumberOfItems().
setOffset()
void setOffset (int32_t offset) protected virtual
Sets display offset of first item.
Parameters
offset The offset.
Reimplemented from ScrollBase.
{
    ScrollWheelBase::setOffset(offset);
    listCenter.setOffset((distanceBeforeAlignedItem - (distanceBeforeAlignedItem - extraSizeBeforeSelectedItem)) + offset);
    listAfter.setOffset((distanceBeforeAlignedItem - (distanceBeforeAlignedItem + itemSize + extraSizeAfterSelectedItem + marginAfterSelectedItem)) + offset);
}
References ScrollBase::distanceBeforeAlignedItem, ScrollWheelWithSelectionStyle::extraSizeAfterSelectedItem, ScrollWheelWithSelectionStyle::extraSizeBeforeSelectedItem, ScrollBase::itemSize, ScrollWheelWithSelectionStyle::listAfter, ScrollWheelWithSelectionStyle::listCenter, ScrollWheelWithSelectionStyle::marginAfterSelectedItem, ScrollBase::setOffset(), and DrawableList::setOffset().
Referenced by ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), and ScrollWheelWithSelectionStyle::setDrawables().
setSelectedItemExtraSize()
void setSelectedItemExtraSize (int16_t extraSizeBefore, int16_t extraSizeAfter) virtual
Sets selected item extra size to make the size of the area for the center drawables larger.
Parameters
extraSizeBefore The extra size before.
extraSizeAfter The extra size after.
See also
setSelectedItemOffset
{
    extraSizeBeforeSelectedItem = extraSizeBefore;
    extraSizeAfterSelectedItem = extraSizeAfter;
    refreshDrawableListsLayout();
}
References ScrollWheelWithSelectionStyle::extraSizeAfterSelectedItem, ScrollWheelWithSelectionStyle::extraSizeBeforeSelectedItem, and ScrollWheelWithSelectionStyle::refreshDrawableListsLayout().
Referenced by ScrollWheelWithSelectionStyle::setSelectedItemPosition().
setSelectedItemMargin()
void setSelectedItemMargin (int16_t marginBefore, int16_t marginAfter) virtual
Sets margin around selected item. This like an invisible area added before and after the selected item (including extra size).
Parameters
marginBefore The margin before.
marginAfter The margin after.
See also
setSelectedItemOffset, setSelectedItemExtraSize
{
    marginBeforeSelectedItem = marginBefore;
    marginAfterSelectedItem = marginAfter;
    refreshDrawableListsLayout();
}
References ScrollWheelWithSelectionStyle::marginAfterSelectedItem, ScrollWheelWithSelectionStyle::marginBeforeSelectedItem, and ScrollWheelWithSelectionStyle::refreshDrawableListsLayout().
Referenced by ScrollWheelWithSelectionStyle::setSelectedItemPosition().
setSelectedItemOffset()
void setSelectedItemOffset (int16_t offset) virtual
Sets selected item offset, measured in pixels, from the edge of the widget. The offset is the relative x coordinate if the ScrollWheel is horizontal, otherwise it is the relative y coordinate. If this value is zero, the selected item is placed at the very start of the widget.
Parameters
offset The offset.
See also
getSelectedItemOffset
Reimplemented from ScrollWheelBase.
{
    ScrollWheelBase::setSelectedItemOffset(offset);
    refreshDrawableListsLayout();
}
References ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), and ScrollWheelBase::setSelectedItemOffset().
Referenced by ScrollWheelWithSelectionStyle::setDrawableSize(), and ScrollWheelWithSelectionStyle::setSelectedItemPosition().
setSelectedItemPosition()
void setSelectedItemPosition (int16_t offset, int16_t extraSizeBefore, int16_t extraSizeAfter, int16_t marginBefore, int16_t marginAfter) virtual
Sets the selected item offset. This is the distance from the beginning of the ScrollWheel measured in pixels. The distance before and after that should also be drawn using the center drawables - for example to extend area of emphasized elements - can also be specified. Further, if a gap is needed between the "normal" drawables and the center drawables - for example to give the illusion that that items disappear under a graphical element, only to appear in the center.
This is a combination of setSelectedItemOffset, setSelectedItemExtraSize and setSelectedItemMargin.
Parameters
offset The offset of the selected item.
extraSizeBefore The extra size before the selected item.
extraSizeAfter The extra size after the selected item.
marginBefore The margin before the selected item.
marginAfter The margin after the selected item.
See also
setSelectedItemOffset, setSelectedItemExtraSize, setSelectedItemMargin
{
    setSelectedItemOffset(offset);
    setSelectedItemExtraSize(extraSizeBefore, extraSizeAfter);
    setSelectedItemMargin(marginBefore, marginAfter);
}
References ScrollWheelWithSelectionStyle::setSelectedItemExtraSize(), ScrollWheelWithSelectionStyle::setSelectedItemMargin(), and ScrollWheelWithSelectionStyle::setSelectedItemOffset().
setWidth()
void setWidth (int16_t width) virtual
Sets the width of this drawable.
Parameters
width The new width.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Also sets the width of the children.
Reimplemented from ScrollBase.
{
    ScrollWheelBase::setWidth(width);
    if (getHorizontal())
    {
        refreshDrawableListsLayout();
    }
}
References ScrollBase::getHorizontal(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), and ScrollBase::setWidth().
Member Data Documentation
centerDrawables
DrawableListItemsInterface* centerDrawables protected
The drawables at the center of the scroll wheel.
Referenced by ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), and ScrollWheelWithSelectionStyle::setDrawables().
drawables
DrawableListItemsInterface* drawables protected
The drawables at the beginning and end of the scroll wheel.
Referenced by ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), and ScrollWheelWithSelectionStyle::setDrawables().
drawablesInFirstList
int16_t drawablesInFirstList protected
List of drawables in firsts.
Referenced by ScrollWheelWithSelectionStyle::refreshDrawableListsLayout().
extraSizeAfterSelectedItem
int16_t extraSizeAfterSelectedItem protected
The distance after selected item.
Referenced by ScrollWheelWithSelectionStyle::getSelectedItemExtraSizeAfter(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), ScrollWheelWithSelectionStyle::setOffset(), and ScrollWheelWithSelectionStyle::setSelectedItemExtraSize().
extraSizeBeforeSelectedItem
int16_t extraSizeBeforeSelectedItem protected
The distance before selected item.
Referenced by ScrollWheelWithSelectionStyle::getSelectedItemExtraSizeBefore(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), ScrollWheelWithSelectionStyle::setOffset(), and ScrollWheelWithSelectionStyle::setSelectedItemExtraSize().
listAfter
DrawableList listAfter protected
The list of items after the center.
Referenced by ScrollWheelWithSelectionStyle::ScrollWheelWithSelectionStyle(), ScrollWheelWithSelectionStyle::initialize(), ScrollWheelWithSelectionStyle::itemChanged(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), ScrollWheelWithSelectionStyle::setCircular(), ScrollWheelWithSelectionStyle::setDrawableSize(), ScrollWheelWithSelectionStyle::setHorizontal(), ScrollWheelWithSelectionStyle::setNumberOfItems(), and ScrollWheelWithSelectionStyle::setOffset().
listCenter
DrawableList listCenter protected
The center list.
Referenced by ScrollWheelWithSelectionStyle::ScrollWheelWithSelectionStyle(), ScrollWheelWithSelectionStyle::initialize(), ScrollWheelWithSelectionStyle::itemChanged(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), ScrollWheelWithSelectionStyle::setCircular(), ScrollWheelWithSelectionStyle::setDrawableSize(), ScrollWheelWithSelectionStyle::setHorizontal(), ScrollWheelWithSelectionStyle::setNumberOfItems(), and ScrollWheelWithSelectionStyle::setOffset().
marginAfterSelectedItem
int16_t marginAfterSelectedItem protected
The distance after selected item.
Referenced by ScrollWheelWithSelectionStyle::getSelectedItemMarginAfter(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), ScrollWheelWithSelectionStyle::setOffset(), and ScrollWheelWithSelectionStyle::setSelectedItemMargin().
marginBeforeSelectedItem
int16_t marginBeforeSelectedItem protected
The distance before selected item.
Referenced by ScrollWheelWithSelectionStyle::getSelectedItemMarginBefore(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), and ScrollWheelWithSelectionStyle::setSelectedItemMargin().
originalUpdateCenterDrawableCallback
GenericCallback<DrawableListItemsInterface*, int16_t, int16_t>* originalUpdateCenterDrawableCallback protected
The original update center drawable callback.
Referenced by ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), and ScrollWheelWithSelectionStyle::setDrawables().
originalUpdateDrawableCallback
GenericCallback<DrawableListItemsInterface*, int16_t, int16_t>* originalUpdateDrawableCallback protected
The original update drawable callback.
Referenced by ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), and ScrollWheelWithSelectionStyle::setDrawables().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/scrollers/ScrollWheelWithSelectionStyle.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/scrollers/ScrollWheelWithSelectionStyle.cpp