Battery Simulator Documentation: TouchGFXGeneratedHAL
TouchGFXGeneratedHAL
HAL implementation for TouchGFXGenerated.
#include "TouchGFXGeneratedHAL.hpp"
Public Member Functions
TouchGFXGeneratedHAL (touchgfx::DMA_Interface &dma, touchgfx::LCD &display, touchgfx::TouchController &tc, uint16_t width, uint16_t height)
Constructor.
virtual bool beginFrame ()
Called when beginning to rendering a frame.
virtual bool blockCopy (void *RESTRICT dest, const void *RESTRICT src, uint32_t numBytes)
virtual void configureInterrupts ()
Sets the DMA and LCD interrupt priorities.
virtual void disableInterrupts ()
Disables the DMA and LCD interrupts.
virtual void enableInterrupts ()
Enables the DMA and LCD interrupts.
virtual void enableLCDControllerInterrupt ()
Configure the LCD controller to fire interrupts at VSYNC.
virtual void endFrame ()
Called when a rendering pass is completed.
virtual void flushFrameBuffer ()
This function is called whenever the framework has performed a complete draw.
virtual void flushFrameBuffer (const touchgfx::Rect &rect)
This function is called whenever the framework has performed a partial draw.
virtual void initialize ()
This function is responsible for initializing the entire framework.
virtual void unlockFrameBuffer ()
Unlocks the framebuffer.
Public Member Functions inherited from HAL
HAL (DMA_Interface &dmaInterface, LCD &display, TouchController &touchCtrl, uint16_t width, uint16_t height)
virtual ~HAL ()
virtual void allowDMATransfers ()
virtual void backPorchExited ()
virtual void blitCopy (const uint16_t *pSrc, const uint8_t *pClut, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool hasTransparentPixels, uint16_t dstWidth, Bitmap::BitmapFormat srcFormat, Bitmap::BitmapFormat dstFormat, bool replaceBgAlpha)
virtual void blitCopy (const uint16_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool hasTransparentPixels, bool replaceBgAlpha)
virtual void blitCopy (const uint16_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool hasTransparentPixels, uint16_t dstWidth, Bitmap::BitmapFormat srcFormat, Bitmap::BitmapFormat dstFormat, bool replaceBgAlpha)
virtual void blitCopyARGB8888 (const uint16_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool replaceBgAlpha)
virtual void blitCopyGlyph (const uint8_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, colortype color, uint8_t alpha, BlitOperations operation, bool replaceBgAlpha)
virtual void blitCopyWord (const uint16_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint16_t dstWidth)
virtual void blitFill (colortype color, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t alpha, bool replaceBgAlpha)
virtual void blitFill (colortype color, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t alpha, uint16_t dstWidth, Bitmap::BitmapFormat dstFormat, bool replaceBgAlpha)
virtual void blitFillWord (uint16_t colorValue, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t dstWidth)
virtual uint16_t configurePartialFrameBuffer (const uint16_t x, const uint16_t y, const uint16_t width, const uint16_t height)
virtual uint16_t * copyFBRegionToMemory (Rect meAbs)
virtual uint16_t * copyFBRegionToMemory (Rect meAbs, uint16_t *dst, uint32_t stride)
virtual uint16_t * copyFromTFTToClientBuffer (Rect region)
virtual void drawDrawableInDynamicBitmap (Drawable &drawable, BitmapId bitmapId)
virtual void drawDrawableInDynamicBitmap (Drawable &drawable, BitmapId bitmapId, const Rect &rect)
void enableDMAAcceleration (const bool enable)
void enableMCULoadCalculation (bool enabled)
virtual void flushDMA ()
void frontPorchEntered ()
uint16_t * getAnimationStorage () const
LCD * getAuxiliaryLCD ()
virtual BlitOperations getBlitCaps ()
ButtonController * getButtonController () const
uint32_t getCPUCycles ()
uint16_t getDisplayHeight () const
DisplayOrientation getDisplayOrientation () const
uint16_t getDisplayWidth () const
virtual DMAType getDMAType ()
uint8_t getFingerSize () const
virtual FlashDataReader * getFlashDataReader () const
FrameBufferAllocator * getFrameBufferAllocator ()
FrameRefreshStrategy getFrameRefreshStrategy () const
Gestures * getGestures ()
uint32_t getLCDRefreshCount ()
uint8_t getMCULoadPct () const
virtual uint16_t getTFTCurrentLine ()
int8_t getTouchSampleRate () const
void lockDMAToFrontPorch (bool enableLock)
virtual uint16_t * lockFrameBuffer ()
uint16_t * lockFrameBufferForRenderingMethod (RenderingMethod method)
virtual void registerEventListener (UIEventListener &listener)
void registerTaskDelayFunction (void(*delayF)(uint16_t))
virtual bool sampleKey (uint8_t &key)
virtual void setAnimationStorage (void *animationStorage)
void setAuxiliaryLCD (LCD *auxLCD)
void setButtonController (ButtonController *btnCtrl)
virtual void setDisplayOrientation (DisplayOrientation orientation)
void setDragThreshold (uint8_t value)
void setFingerSize (uint8_t size)
void setFrameBufferAllocator (FrameBufferAllocator *allocator)
virtual void setFrameBufferSize (uint16_t width, uint16_t height)
virtual void setFrameBufferStartAddresses (void *frameBuffer, void *doubleBuffer, void *animationStorage)
void setFrameRateCompensation (bool enabled)
bool setFrameRefreshStrategy (FrameRefreshStrategy s)
void setMCUActive (bool active)
void setMCUInstrumentation (MCUInstrumentation *mcuInstr)
void setRenderingMethod (RenderingMethod method)
void setTouchSampleRate (int8_t sampleRateInTicks)
void signalDMAInterrupt ()
void swapFrameBuffers ()
virtual void taskDelay (uint16_t ms)
virtual void taskEntry ()
void vSync ()
Protected Member Functions
virtual void FlushCache ()
virtual uint16_t * getTFTFrameBuffer () const
Gets the frame buffer address used by the TFT controller.
virtual void InvalidateCache ()
virtual void setTFTFrameBuffer (uint16_t *adr)
Sets the frame buffer address used by the TFT controller.
Protected Member Functions inherited from HAL
uint16_t * getClientFrameBuffer ()
virtual void noTouch ()
virtual void performDisplayOrientationChange ()
virtual void tick ()
virtual void touch (int32_t x, int32_t y)
Additional Inherited Members
Public Types inherited from HAL
enum FrameRefreshStrategy { REFRESH_STRATEGY_DEFAULT , REFRESH_STRATEGY_OPTIM_SINGLE_BUFFER_TFT_CTRL , REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER }
enum RenderingMethod { SOFTWARE , HARDWARE }
Static Public Member Functions inherited from HAL
static HAL * getInstance ()
static LCD & lcd ()
Static Public Attributes inherited from HAL
static uint16_t DISPLAY_HEIGHT
The height of the LCD display in pixels.
static DisplayRotation DISPLAY_ROTATION
The rotation from display to framebuffer.
static uint16_t DISPLAY_WIDTH
The width of the LCD display in pixels.
static uint16_t FRAME_BUFFER_HEIGHT
The height of the framebuffer in pixels.
static uint16_t FRAME_BUFFER_WIDTH
The width of the framebuffer in pixels.
static bool USE_ANIMATION_STORAGE
Is animation storage enabled?
static bool USE_DOUBLE_BUFFERING
Is double buffering enabled?
Protected Attributes inherited from HAL
LCD * auxiliaryLCD
Auxiliary LCD class used to render Drawables into dynamic bitmaps.
ButtonController * buttonController
A reference to an optional ButtonController.
DMA_Interface & dma
A reference to the DMA interface.
uint8_t fingerSize
The radius of the finger in pixels.
uint16_t * frameBuffer0
Pointer to the first framebuffer.
uint16_t * frameBuffer1
Pointer to the second framebuffer.
uint16_t * frameBuffer2
Pointer to the optional third framebuffer used for animation storage.
FrameBufferAllocator * frameBufferAllocator
A reference to an optional FrameBufferAllocator.
bool frameBufferUpdatedThisFrame
True if something was drawn in the current frame.
Gestures gestures
Class for low-level interpretation of touch events.
LCD & lcdRef
A reference to the LCD.
bool lockDMAToPorch
Whether or not to lock DMA transfers with TFT porch signal.
MCUInstrumentation * mcuInstrumentation
A reference to an optional MCU instrumentation.
DisplayOrientation nativeDisplayOrientation
Contains the native display orientation. If desired orientation is different, apply rotation.
Rect partialFrameBufferRect
The region of the screen covered by the partial framebuffer.
FrameRefreshStrategy refreshStrategy
The selected display refresh strategy.
void(* taskDelayFunc)(uint16_t)
Pointer to a function that can delay GUI task for a number of milliseconds.
TouchController & touchController
A reference to the touch controller.
bool useAuxiliaryLCD
True if using another LCD than the hardware framebuffer.
Static Protected Attributes inherited from HAL
static bool isDrawing
True if currently in the process of rendering a screen.
Detailed Description
HAL implementation for TouchGFXGenerated.
File Name : TouchGFXGeneratedHAL.hpp
This file is generated by TouchGFX Generator 4.23.1. Please, do not edit!
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
See also
HAL
Constructor & Destructor Documentation
TouchGFXGeneratedHAL()
TouchGFXGeneratedHAL (touchgfx::DMA_Interface & dma, touchgfx::LCD & display, touchgfx::TouchController & tc, uint16_t width, uint16_t height) inline
Constructor.
   Constructor. Initializes members.
Parameters
[in,out] dma Reference to DMA interface.
[in,out] display Reference to LCD interface.
[in,out] tc Reference to Touch Controller driver.
width Width of the display.
height Height of the display.
                                                                                                                                         :
        touchgfx::HAL(dma, display, tc, width, height)
    {
    }
Member Function Documentation
beginFrame()
void beginFrame () virtual
Called when beginning to rendering a frame.
   Called when beginning to rendering a frame.
Returns
true if rendering can begin, false otherwise.
Reimplemented from HAL.
Reimplemented in TouchGFXHAL.
{
    return HAL::beginFrame();
}
References HAL::beginFrame().
Referenced by TouchGFXHAL::beginFrame().
blockCopy()
bool blockCopy (void *RESTRICT dest, const void *RESTRICT src, uint32_t numBytes) virtual
This function performs a platform-specific memcpy, if supported by the hardware.
Parameters
[out] dest Pointer to destination memory.
[in] src Pointer to source memory.
numBytes Number of bytes to copy.
Returns
true if the copy succeeded, false if copy was not performed.
Reimplemented from HAL.
Reimplemented in TouchGFXHAL.
{
    return HAL::blockCopy(dest, src, numBytes);
}
References HAL::blockCopy().
Referenced by TouchGFXHAL::blockCopy().
configureInterrupts()
void configureInterrupts () virtual
Sets the DMA and LCD interrupt priorities.
   Sets the DMA and LCD interrupt priorities.
Implements HAL.
Reimplemented in TouchGFXHAL.
{
    NVIC_SetPriority(DMA2D_IRQn, 9);
    NVIC_SetPriority(LTDC_IRQn, 9);
}
Referenced by TouchGFXHAL::configureInterrupts().
disableInterrupts()
void disableInterrupts () virtual
Disables the DMA and LCD interrupts.
   Disables the DMA and LCD interrupts.
Implements HAL.
Reimplemented in TouchGFXHAL.
{
    NVIC_DisableIRQ(DMA2D_IRQn);
    NVIC_DisableIRQ(LTDC_IRQn);
}
Referenced by TouchGFXHAL::disableInterrupts().
enableInterrupts()
void enableInterrupts () virtual
Enables the DMA and LCD interrupts.
   Enables the DMA and LCD interrupts.
Implements HAL.
Reimplemented in TouchGFXHAL.
{
    NVIC_EnableIRQ(DMA2D_IRQn);
    NVIC_EnableIRQ(LTDC_IRQn);
}
Referenced by TouchGFXHAL::enableInterrupts().
enableLCDControllerInterrupt()
void enableLCDControllerInterrupt () virtual
Configure the LCD controller to fire interrupts at VSYNC.
   Configure the LCD controller to fire interrupts at VSYNC. Called automatically
   once TouchGFX initialization has completed.
Implements HAL.
Reimplemented in TouchGFXHAL.
{
    lcd_int_active_line = (LTDC->BPCR & 0x7FF) - 1;
    lcd_int_porch_line = (LTDC->AWCR & 0x7FF) - 1;
    /* Sets the Line Interrupt position */
    LTDC->LIPCR = lcd_int_active_line;
    /* Line Interrupt Enable            */
    LTDC->IER |= LTDC_IER_LIE;
}
Referenced by TouchGFXHAL::enableLCDControllerInterrupt().
endFrame()
void endFrame () virtual
Called when a rendering pass is completed.
   Called when a rendering pass is completed.
Reimplemented from HAL.
Reimplemented in TouchGFXHAL.
{
    HAL::endFrame();
    videoController.endFrame();
    dma.start();
}
References HAL::dma, HAL::endFrame(), and DMA_Interface::start().
Referenced by TouchGFXHAL::endFrame().
FlushCache()
void FlushCache () protected virtual
Flush D-Cache.
Called by setRenderingMethod when changing rendering method from Software to Hardware indicating the cache should be invalidated.
Reimplemented from HAL.
{
    // If the framebuffer is placed in Write Through cached memory (e.g. SRAM) then
    // the DCache must be flushed prior to DMA2D accessing it. That's done
    // using the function SCB_CleanInvalidateDCache(). Remember to enable "CPU Cache" in the
    // "System Core" settings for "Cortex M7" in CubeMX in order for this function call to work.
    if (SCB->CCR & SCB_CCR_DC_Msk)
    {
        SCB_CleanInvalidateDCache();
    }
}
flushFrameBuffer() [1/2]
void flushFrameBuffer () inline virtual
This function is called whenever the framework has performed a complete draw.
This specialization is only in place to keep compilers happy. Base impl. will call the Rect version.
See also
HAL::flushFrameBuffer
Reimplemented from HAL.
Reimplemented in TouchGFXHAL.
    {
        HAL::flushFrameBuffer();
    }
Referenced by TouchGFXHAL::flushFrameBuffer(), and TouchGFXHAL::flushFrameBuffer().
flushFrameBuffer() [2/2]
void flushFrameBuffer (const touchgfx::Rect & rect) virtual
This function is called whenever the framework has performed a partial draw.
   This function is called whenever the framework has performed a partial draw.
   On the STM32F7, make sure to clean and invalidate the data cache. This is to
   ensure that LTDC sees correct data when transferring to the display.
Parameters
rect The area of the screen that has been drawn, expressed in absolute coordinates.
See also
flushFrameBuffer().
Reimplemented from HAL.
Reimplemented in TouchGFXHAL.
{
    HAL::flushFrameBuffer(rect);
}
References HAL::flushFrameBuffer().
getTFTFrameBuffer()
uint16_t * getTFTFrameBuffer () const protected virtual
Gets the frame buffer address used by the TFT controller.
   Gets the frame buffer address used by the TFT controller.
Returns
The address of the frame buffer currently being displayed on the TFT.
Implements HAL.
Reimplemented in TouchGFXHAL.
{
    return (uint16_t*)LTDC_Layer1->CFBAR;
}
Referenced by TouchGFXHAL::getTFTFrameBuffer().
initialize()
void initialize () virtual
This function is responsible for initializing the entire framework.
   This function is responsible for initializing the entire framework.
Reimplemented from HAL.
Reimplemented in TouchGFXHAL.
{
    HAL::initialize();
    registerEventListener(*(Application::getInstance()));
    setFrameBufferStartAddresses((void*)0xD0000000, (void*)0xD01C2000, (void*)0);
    /*
     * Add DMA2D to hardware decoder
     */
    mjpegdecoder1.addDMA(dma);
    /*
     * Add hardware decoder to video controller
     */
    videoController.addDecoder(mjpegdecoder1, 0);
    videoController.setRGBBuffer((uint8_t*)videoRGBBuffer, sizeof(videoRGBBuffer));
}
References HardwareMJPEGDecoder::addDMA(), HAL::dma, Application::getInstance(), HAL::initialize(), mjpegdecoder1, HAL::registerEventListener(), and HAL::setFrameBufferStartAddresses().
Referenced by TouchGFXHAL::initialize().
InvalidateCache()
void InvalidateCache () protected virtual
Invalidate D-Cache.
Called by setRenderingMethod when changing rendering method from Hardware to Software indicating the cache should be invalidated.
Reimplemented from HAL.
{
    // If the framebuffer is placed in Write Through cached memory (e.g. SRAM) then
    // the DCache must be flushed prior to DMA2D accessing it. That's done
    // using the function SCB_CleanInvalidateDCache(). Remember to enable "CPU Cache" in the
    // "System Core" settings for "Cortex M7" in CubeMX in order for this function call to work.
    if (SCB->CCR & SCB_CCR_DC_Msk)
    {
        SCB_CleanInvalidateDCache();
    }
}
setTFTFrameBuffer()
void setTFTFrameBuffer (uint16_t * adr) protected virtual
Sets the frame buffer address used by the TFT controller.
   Sets the frame buffer address used by the TFT controller.
Parameters
[in,out] adr New frame buffer address.
Implements HAL.
Reimplemented in TouchGFXHAL.
{
    LTDC_Layer1->CFBAR = (uint32_t)adr;
    /* Reload immediate */
    LTDC->SRCR = (uint32_t)LTDC_SRCR_IMR;
}
Referenced by TouchGFXHAL::setTFTFrameBuffer().
unlockFrameBuffer()
void unlockFrameBuffer () inline virtual
Unlocks the framebuffer.
This specialization is marks DMA2D as un-reserved by the framwork.
See also
HAL::unlockFrameBuffer
Reimplemented from HAL.
    {
        HAL::unlockFrameBuffer();
        dma.start();
    }
References HAL::dma, and DMA_Interface::start().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/target/generated/TouchGFXGeneratedHAL.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/target/generated/TouchGFXGeneratedHAL.cpp