Battery Simulator Documentation: ModalWindow
ModalWindow
#include "ModalWindow.hpp"
Public Member Functions
ModalWindow ()
virtual void add (Drawable &d)
virtual uint16_t getBackgroundHeight () const
virtual uint16_t getBackgroundWidth () const
virtual uint8_t getShadeAlpha () const
virtual colortype getShadeColor () const
virtual void hide ()
virtual void remove (Drawable &d)
virtual void setBackground (const BitmapId &bmpId)
virtual void setBackground (const BitmapId &bmpId, int16_t backgroundX, int16_t backgroundY)
virtual void setShadeAlpha (uint8_t alpha)
virtual void setShadeColor (colortype color)
virtual void show ()
Public Member Functions inherited from Container
Container ()
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
Box backgroundShade
The background shade.
Image windowBackground
The window background.
Container windowContainer
The window container that defines the active container area where both the windowBackground and added drawables are placed.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Detailed Description
Container for displaying a modal window and hijacking touch event and prevent them from reaching the underlying view and widgets.
The container has a background image and a surrounding box that acts as a shade on top of the rest of the screen. The background image must be set (using setBackground()) and the shade can be adjusted (using setShadeAlpha() and setShadeColor()).
The ModalWindow can either be used directly by adding widgets/containers to the ModalWindow from your view or by sub-classing it if you need a specific ModalWindow with predefined behavior across your application.
The ModalWindow should be instantiated in the view class and added as the last element (to always be on top, i.e. be modal). The ModalWindow will fill up the entire screen so it should always be placed at x=0, y=0 on the display.
To control the visibility of the ModalWindow use the show and hide methods.
Constructor & Destructor Documentation
ModalWindow()
ModalWindow ()
    : Container(),
      backgroundShade(),
      windowContainer(),
      windowBackground()
{
    ModalWindow::setWidthHeight(HAL::DISPLAY_WIDTH, HAL::DISPLAY_HEIGHT);
    const int defaultShadeAlpha = 96;
    const colortype defaultShadeColor = Color::getColorFromRGB(0x0, 0x0, 0x0);
    backgroundShade.setPosition(0, 0, getWidth(), getHeight());
    backgroundShade.setColor(defaultShadeColor);
    backgroundShade.setTouchable(true);
    ModalWindow::setShadeAlpha(defaultShadeAlpha);
    Container::add(backgroundShade);
    Container::add(windowContainer);
    windowContainer.add(windowBackground);
}
References Container::add(), ModalWindow::backgroundShade, HAL::DISPLAY_HEIGHT, HAL::DISPLAY_WIDTH, Color::getColorFromRGB(), Drawable::getHeight(), Drawable::getWidth(), Box::setColor(), Drawable::setPosition(), ModalWindow::setShadeAlpha(), Drawable::setTouchable(), Drawable::setWidthHeight(), ModalWindow::windowBackground, and ModalWindow::windowContainer.
Member Function Documentation
add()
void add (Drawable & d) virtual
Adds a Drawable instance as child to this Container. The Drawable added will be placed as the element to be drawn last, and thus appear on top of all previously added drawables in the Container.
Parameters
[in] d The Drawable to add.
Note
Never add a drawable more than once!
Reimplemented from Container.
{
    windowContainer.add(d);
}
References Container::add(), and ModalWindow::windowContainer.
getBackgroundHeight()
uint16_t getBackgroundHeight () const virtual
Gets the height of the actual window (the background images). Whereas the getHeight() method will return the height including the shade.
Returns
The height of the actual window.
{
    return windowBackground.getHeight();
}
References Drawable::getHeight(), and ModalWindow::windowBackground.
getBackgroundWidth()
uint16_t getBackgroundWidth () const virtual
Gets the width of the actual window (the background images). Whereas the getWidth() method will return the width including the shade.
Returns
The width of the actual window.
{
    return windowBackground.getWidth();
}
References Drawable::getWidth(), and ModalWindow::windowBackground.
getShadeAlpha()
uint8_t getShadeAlpha () const virtual
Gets the alpha value of the background shade.
Returns
The background shades alpha.
{
    return backgroundShade.getAlpha();
}
References ModalWindow::backgroundShade, and Box::getAlpha().
getShadeColor()
colortype getShadeColor () const virtual
Gets the color of the background shade.
Returns
The color of the background shade.
{
    return backgroundShade.getColor();
}
References ModalWindow::backgroundShade, and Box::getColor().
hide()
void hide () virtual
Make the ModalWindow invisible.
{
    invalidate();
    setVisible(false);
}
References Drawable::invalidate(), and Drawable::setVisible().
remove()
void remove (Drawable & d) virtual
Removes a Drawable from the container by removing it from the linked list of children. If the Drawable is not in the list of children, nothing happens. It is possible to remove an element from whichever Container it is a member of using:
if (d.getParent()) d.getParent()->remove(d);
The Drawable will have the parent and next sibling cleared, but is otherwise left unaltered.
Parameters
[in] d The Drawable to remove.
Note
This is safe to call even if d is not a child of this Container (in which case nothing happens).
Reimplemented from Container.
{
    windowContainer.remove(d);
}
References Container::remove(), and ModalWindow::windowContainer.
setBackground() [1/2]
void setBackground (const BitmapId & bmpId) virtual
Sets the background of the actual window. The remaining area of the screen will be covered by the shade. The background image is centered on the screen.
Parameters
bmpId Identifier for the background bitmap.
{
    windowBackground.setBitmap(Bitmap(bmpId));
    windowBackground.setXY(0, 0);
    windowContainer.setPosition((getWidth() - windowBackground.getWidth()) / 2, (getHeight() - windowBackground.getHeight()) / 2, windowBackground.getWidth(), windowBackground.getHeight());
    invalidate();
}
References Drawable::getHeight(), Drawable::getWidth(), Drawable::invalidate(), Image::setBitmap(), Drawable::setPosition(), Drawable::setXY(), ModalWindow::windowBackground, and ModalWindow::windowContainer.
Referenced by ModalWindow::setBackground().
setBackground() [2/2]
void setBackground (const BitmapId & bmpId, int16_t backgroundX, int16_t backgroundY) virtual
Sets the background of the actual window. The remaining area of the screen will be covered by the shade. The background image will be placed at the backgroundX and backgroundY coordinate.
Parameters
bmpId Identifier for the bitmap.
backgroundX The background x coordinate.
backgroundY The background y coordinate.
{
    setBackground(bmpId);
    windowContainer.setXY(backgroundX, backgroundY);
}
References ModalWindow::setBackground(), Drawable::setXY(), and ModalWindow::windowContainer.
setShadeAlpha()
void setShadeAlpha (uint8_t alpha) virtual
Sets the alpha value of the background shade. Default, if not set, is 96.
Parameters
alpha The new alpha.
{
    backgroundShade.setAlpha(alpha);
    backgroundShade.invalidate();
}
References ModalWindow::backgroundShade, Drawable::invalidate(), and Box::setAlpha().
Referenced by ModalWindow::ModalWindow().
setShadeColor()
void setShadeColor (colortype color) virtual
Sets the color of the background shade. Default is black.
Parameters
color The new color.
{
    backgroundShade.setColor(color);
    backgroundShade.invalidate();
}
References ModalWindow::backgroundShade, Drawable::invalidate(), and Box::setColor().
show()
void show () virtual
Make the ModalWindow visible.
{
    setVisible(true);
    invalidate();
}
References Drawable::invalidate(), and Drawable::setVisible().
Member Data Documentation
backgroundShade
Box backgroundShade protected
The background shade.
Referenced by ModalWindow::ModalWindow(), ModalWindow::getShadeAlpha(), ModalWindow::getShadeColor(), ModalWindow::setShadeAlpha(), and ModalWindow::setShadeColor().
windowBackground
Image windowBackground protected
The window background.
Referenced by ModalWindow::ModalWindow(), ModalWindow::getBackgroundHeight(), ModalWindow::getBackgroundWidth(), and ModalWindow::setBackground().
windowContainer
Container windowContainer protected
The window container that defines the active container area where both the windowBackground and added drawables are placed.
Referenced by ModalWindow::ModalWindow(), ModalWindow::add(), ModalWindow::remove(), ModalWindow::setBackground(), and ModalWindow::setBackground().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/ModalWindow.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/ModalWindow.cpp