Battery Simulator Documentation: AnalogClock
AnalogClock
#include "AnalogClock.hpp"
Public Member Functions
AnalogClock ()
virtual uint8_t getAlpha () const
virtual uint16_t getAnimationDuration ()
virtual bool getHourHandMinuteCorrection () const
virtual bool getMinuteHandSecondCorrection () const
virtual void initializeTime12Hour (uint8_t hour, uint8_t minute, uint8_t second, bool am)
virtual void initializeTime24Hour (uint8_t hour, uint8_t minute, uint8_t second)
virtual void invalidateContent () const
virtual void setAlpha (uint8_t newAlpha)
virtual void setAnimation (uint16_t duration=10, EasingEquation animationProgressionEquation=EasingEquations::backEaseInOut)
virtual void setBackground (const BitmapId backgroundBitmapId)
virtual void setBackground (const BitmapId backgroundBitmapId, int16_t rotationCenterX, int16_t rotationCenterY)
virtual void setHourHandMinuteCorrection (bool active)
virtual void setMinuteHandSecondCorrection (bool active)
virtual void setRotationCenter (int16_t rotationCenterX, int16_t rotationCenterY)
virtual void setupHourHand (const BitmapId hourHandBitmapId, int16_t rotationCenterX, int16_t rotationCenterY)
virtual void setupMinuteHand (const BitmapId minuteHandBitmapId, int16_t rotationCenterX, int16_t rotationCenterY)
virtual void setupSecondHand (const BitmapId secondHandBitmapId, int16_t rotationCenterX, int16_t rotationCenterY)
Public Member Functions inherited from AbstractClock
AbstractClock ()
bool getCurrentAM () const
uint8_t getCurrentHour () const
uint8_t getCurrentHour12 () const
uint8_t getCurrentHour24 () const
uint8_t getCurrentMinute () const
uint8_t getCurrentSecond () const
virtual void setTime12Hour (uint8_t hour, uint8_t minute, uint8_t second, bool am)
virtual void setTime24Hour (uint8_t hour, uint8_t minute, uint8_t second)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual bool animationEnabled () const
virtual float convertHandValueToAngle (uint8_t steps, uint8_t handValue, uint8_t secondHandValue=0) const
virtual void setupHand (TextureMapper &hand, const BitmapId bitmapId, int16_t rotationCenterX, int16_t rotationCenterY)
virtual void updateClock ()
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
uint16_t animationDuration
The duration of hand animations. If 0 animations are disabled.
EasingEquation animationEquation
The easing equation used by hand animations.
Image background
The background image of the AnalogClock.
int16_t clockRotationCenterX
The x coordinate of the rotation point of the hands.
int16_t clockRotationCenterY
The y coordinate of the rotation point of the hands.
AnimationTextureMapper hourHand
TextureMapper used for drawing the hourHand.
bool hourHandMinuteCorrectionActive
Is hour hand minute correction active.
uint8_t lastHour
The last know hour value.
uint8_t lastMinute
The last know minute value.
uint8_t lastSecond
The last know second value.
AnimationTextureMapper minuteHand
TextureMapper used for drawing the minuteHand.
bool minuteHandSecondCorrectionActive
Is minute hand second correction active.
AnimationTextureMapper secondHand
TextureMapper used for drawing the secondHand.
Protected Attributes inherited from AbstractClock
uint8_t currentHour
Local copy of the current hour.
uint8_t currentMinute
Local copy of the current minute.
uint8_t currentSecond
Local copy of the current second.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
An analog clock. Should be supplied with images for the background, hour hand, minute hand and the optional second hand. You setup the AnalogClock by specifying the rotation point of each hand as well as the global rotation point of the clock. You can customize the behavior of the AnalogClock in respect to animations and relations between the hands e.g. if the hour hand should move gradually towards the next hour as the minute hand progresses (setHourHandMinuteCorrection())
Constructor & Destructor Documentation
AnalogClock()
AnalogClock ()
    : AbstractClock(),
      background(),
      hourHand(),
      minuteHand(),
      secondHand(),
      animationEquation(EasingEquations::linearEaseNone),
      animationDuration(0),
      clockRotationCenterX(0),
      clockRotationCenterY(0),
      lastHour(0),
      lastMinute(0),
      lastSecond(0),
      hourHandMinuteCorrectionActive(false),
      minuteHandSecondCorrectionActive(false)
{
    AnalogClock::add(background);
    hourHand.updateZAngle(0.f);
    minuteHand.updateZAngle(0.f);
    secondHand.updateZAngle(0.f);
    hourHand.setVisible(false);
    minuteHand.setVisible(false);
    secondHand.setVisible(false);
}
References Container::add(), AnalogClock::background, AnalogClock::hourHand, AnalogClock::minuteHand, AnalogClock::secondHand, Drawable::setVisible(), and TextureMapper::updateZAngle().
Member Function Documentation
animationEnabled()
bool animationEnabled () const protected virtual
Is animation enabled for the hands?
Returns
true if animation is enabled.
{
    return animationDuration > 1;
}
References AnalogClock::animationDuration.
Referenced by AnalogClock::updateClock().
convertHandValueToAngle()
float convertHandValueToAngle (uint8_t steps, uint8_t handValue, uint8_t secondHandValue = 0) const protected virtual
Convert hand value to angle.
Parameters
steps Number of steps the primary hand value is divided into, i.e. 60 for minutes/seconds and 12 for hour.
handValue The actual value for the hand in question (in the range [0; steps]).
secondHandValue (Optional) If the angle should be corrected for a secondary hand its value should be specified here (in the range [0; 60]). This is the case when setHourHandMinuteCorrection(true) or setMinuteHandSecondCorrection(true) is selected.
Returns
The converted value to angle.
{
    return ((handValue / (float)steps) + (secondHandValue / (steps * 60.f))) * 2 * PI;
}
References touchgfx::PI.
Referenced by AnalogClock::updateClock().
getAlpha()
uint8_t getAlpha () const virtual
Gets the current alpha value of the widget. The alpha value is in range 255 (solid) to 0 (invisible).
Returns
The current alpha value.
See also
setAlpha
{
    return background.getAlpha();
}
References AnalogClock::background, and Image::getAlpha().
Referenced by AnalogClock::invalidateContent().
getAnimationDuration()
virtual uint16_t getAnimationDuration () inline virtual
Gets the animation duration.
Returns
The animation duration.
See also
setAnimation
    {
        return animationDuration;
    }
References AnalogClock::animationDuration.
getHourHandMinuteCorrection()
bool getHourHandMinuteCorrection () const virtual
Gets hour hand minute correction.
Returns
true if hour hand minute correction is active.
See also
setHourHandMinuteCorrection
{
    return hourHandMinuteCorrectionActive;
}
References AnalogClock::hourHandMinuteCorrectionActive.
getMinuteHandSecondCorrection()
bool getMinuteHandSecondCorrection () const virtual
Gets minute hand second correction.
Returns
true if minute hand second correction is active.
See also
setHourHandMinuteCorrection
{
    return minuteHandSecondCorrectionActive;
}
References AnalogClock::minuteHandSecondCorrectionActive.
initializeTime12Hour()
void initializeTime12Hour (uint8_t hour, uint8_t minute, uint8_t second, bool am) virtual
Sets the time with input format as 12H. No animations are performed regardless of the animation settings. This is often useful when setting up the AnalogClock where you do not want an initial animation.
Parameters
hour The hours, value should be between 1 and 12.
minute The minutes, value should be between 0 and 59.
second The seconds, value should be between 0 and 59.
am AM/PM setting. True = AM, false = PM.
See also
setTime12Hour
Note
that this does not affect any selected presentation formats.
{
    initializeTime24Hour((hour % 12) + (am ? 0 : 12), minute, second);
}
References AnalogClock::initializeTime24Hour().
initializeTime24Hour()
void initializeTime24Hour (uint8_t hour, uint8_t minute, uint8_t second) virtual
Sets the time with input format as 24H. No animations are performed regardless of the animation settings. This is often useful when setting up the AnalogClock where you do not want an initial animation.
Parameters
hour The hours, value should be between 0 and 23.
minute The minutes, value should be between 0 and 59.
second The seconds, value should be between 0 and 59.
See also
setTime24Hour
Note
that this does not affect any selected presentation formats.
{
    lastHour = 255;
    lastMinute = 255;
    lastSecond = 255;
    // Disable animation and set time
    const uint16_t tempAnimationDuration = animationDuration;
    animationDuration = 1;
    setTime24Hour(hour, minute, second);
    animationDuration = tempAnimationDuration;
}
References AnalogClock::animationDuration, AnalogClock::lastHour, AnalogClock::lastMinute, AnalogClock::lastSecond, and AbstractClock::setTime24Hour().
Referenced by AnalogClock::initializeTime12Hour().
invalidateContent()
virtual void invalidateContent () const inline virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from Drawable.
    {
        if (getAlpha() > 0)
        {
            AbstractClock::invalidateContent();
        }
    }
References AnalogClock::getAlpha(), and Drawable::invalidateContent().
setAlpha()
void setAlpha (uint8_t newAlpha) virtual
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
The alpha value is reflected in the background image
{
    background.setAlpha(newAlpha);
    hourHand.setAlpha(newAlpha);
    minuteHand.setAlpha(newAlpha);
    secondHand.setAlpha(newAlpha);
}
References AnalogClock::background, AnalogClock::hourHand, AnalogClock::minuteHand, AnalogClock::secondHand, and Image::setAlpha().
setAnimation()
void setAnimation (uint16_t duration = 10, EasingEquation animationProgressionEquation = EasingEquations::backEaseInOut) virtual
Setup the clock to use animation for hand movements.
Parameters
duration (Optional) The animation duration, default is 10.
animationProgressionEquation (Optional) The animation progression equation, default is EasingEquations::backEaseInOut.
{
    animationDuration = duration;
    animationEquation = animationProgressionEquation;
}
References AnalogClock::animationDuration, and AnalogClock::animationEquation.
setBackground() [1/2]
void setBackground (const BitmapId backgroundBitmapId) virtual
Sets the background image of the clock. The clock rotation center is automatically set to the background image center. The clock rotation center is the point that the clock hands rotates around. The size of the AnalocClock widget is set to the size of the bitmap.
Parameters
backgroundBitmapId Identifier for the background bitmap.
{
    setBackground(backgroundBitmapId, Bitmap(backgroundBitmapId).getWidth() / 2, Bitmap(backgroundBitmapId).getHeight() / 2);
}
References Drawable::getHeight(), Drawable::getWidth(), and AnalogClock::setBackground().
Referenced by AnalogClock::setBackground().
setBackground() [2/2]
void setBackground (const BitmapId backgroundBitmapId, int16_t rotationCenterX, int16_t rotationCenterY) virtual
Sets the background image of the clock and the rotation center of the clock. The clock rotation center is the point that the clock hands rotates around. The size of the AnalocClock widget is set to the size of the bitmap.
Parameters
backgroundBitmapId Identifier for the background bitmap.
rotationCenterX The rotation center x coordinate.
rotationCenterY The rotation center y coordinate.
See also
setBackground(BitmapId), setRotationCenter
{
    background.setBitmap(Bitmap(backgroundBitmapId));
    setWidthHeight(background);
    setRotationCenter(rotationCenterX, rotationCenterY);
}
References AnalogClock::background, Image::setBitmap(), AnalogClock::setRotationCenter(), and Drawable::setWidthHeight().
setHourHandMinuteCorrection()
void setHourHandMinuteCorrection (bool active) virtual
Sets whether hour hand minute correction should be active. If set to true the hour hand will be positioned between the current hour and the next depending on the minute hands position.
Parameters
active true to use hour hand correction.
See also
getHourHandMinuteCorrection
{
    hourHandMinuteCorrectionActive = active;
    setTime24Hour(getCurrentHour(), getCurrentMinute(), getCurrentSecond());
}
References AbstractClock::getCurrentHour(), AbstractClock::getCurrentMinute(), AbstractClock::getCurrentSecond(), AnalogClock::hourHandMinuteCorrectionActive, and AbstractClock::setTime24Hour().
setMinuteHandSecondCorrection()
void setMinuteHandSecondCorrection (bool active) virtual
Sets whether minute hand second correction should be active. If set to true the minute hand will be positioned between the current minute and the next depending on the second hands position.
Parameters
active true to use.
See also
setMinuteHandSecondCorrection
{
    minuteHandSecondCorrectionActive = active;
    setTime24Hour(getCurrentHour(), getCurrentMinute(), getCurrentSecond());
}
References AbstractClock::getCurrentHour(), AbstractClock::getCurrentMinute(), AbstractClock::getCurrentSecond(), AnalogClock::minuteHandSecondCorrectionActive, and AbstractClock::setTime24Hour().
setRotationCenter()
void setRotationCenter (int16_t rotationCenterX, int16_t rotationCenterY) virtual
Sets the rotation center of the clock. The clock rotation center is the point that the clock hands rotates around.
Parameters
rotationCenterX The rotation center x coordinate.
rotationCenterY The rotation center y coordinate.
{
    clockRotationCenterX = rotationCenterX;
    clockRotationCenterY = rotationCenterY;
}
References AnalogClock::clockRotationCenterX, and AnalogClock::clockRotationCenterY.
Referenced by AnalogClock::setBackground().
setupHand()
void setupHand (TextureMapper & hand, const BitmapId bitmapId, int16_t rotationCenterX, int16_t rotationCenterY) protected virtual
Sets up a given the hand.
Parameters
[in] hand Reference to the hand being setup.
bitmapId The bitmap identifier for the given hand.
rotationCenterX The hand rotation center x coordinate.
rotationCenterY The hand rotation center y coordinate.
{
    remove(hand);
    hand.setBitmap(Bitmap(bitmapId));
    hand.setWidthHeight(*this);
    hand.setXY(0, 0);
    hand.setBitmapPosition(clockRotationCenterX - rotationCenterX, clockRotationCenterY - rotationCenterY);
    hand.setCameraDistance(300.0f);
    hand.setOrigo((float)clockRotationCenterX, (float)clockRotationCenterY, hand.getCameraDistance());
    hand.setCamera(hand.getOrigoX(), hand.getOrigoY());
    hand.setRenderingAlgorithm(TextureMapper::BILINEAR_INTERPOLATION);
    add(hand);
    hand.setVisible(true);
}
References Container::add(), TextureMapper::BILINEAR_INTERPOLATION, AnalogClock::clockRotationCenterX, AnalogClock::clockRotationCenterY, and Container::remove().
Referenced by AnalogClock::setupHourHand(), AnalogClock::setupMinuteHand(), and AnalogClock::setupSecondHand().
setupHourHand()
void setupHourHand (const BitmapId hourHandBitmapId, int16_t rotationCenterX, int16_t rotationCenterY) virtual
Sets up the hour hand. The specified rotation center is the point of the hand that is to be placed on top of the clock rotation center. That is the point that the hand rotates around. The rotation point is relative to the supplied bitmap and can be placed outside of it.
Parameters
hourHandBitmapId Identifier for the hour hand bitmap.
rotationCenterX The hand rotation center x coordinate.
rotationCenterY The hand rotation center y coordinate.
Note
If no hour hand is setup it will just be omitted.
{
    setupHand(hourHand, hourHandBitmapId, rotationCenterX, rotationCenterY);
}
References AnalogClock::hourHand, and AnalogClock::setupHand().
setupMinuteHand()
void setupMinuteHand (const BitmapId minuteHandBitmapId, int16_t rotationCenterX, int16_t rotationCenterY) virtual
Sets up the minute hand. The specified rotation center is the point of the hand that is to be placed on top of the clock rotation center. That is the point that the hand rotates around. The rotation point is relative to the supplied bitmap but can be placed outside of it.
Parameters
minuteHandBitmapId Identifier for the minute hand bitmap.
rotationCenterX The hand rotation center x coordinate.
rotationCenterY The hand rotation center y coordinate.
Note
If no minute hand is setup it will just be omitted.
{
    setupHand(minuteHand, minuteHandBitmapId, rotationCenterX, rotationCenterY);
}
References AnalogClock::minuteHand, and AnalogClock::setupHand().
setupSecondHand()
void setupSecondHand (const BitmapId secondHandBitmapId, int16_t rotationCenterX, int16_t rotationCenterY) virtual
Sets up the second hand. The specified rotation center is the point of the hand that is to be placed on top of the clock rotation center. That is the point that the hand rotates around. The rotation point is relative to the supplied bitmap but can be placed outside of it.
Parameters
secondHandBitmapId Identifier for the second hand bitmap.
rotationCenterX The hand rotation center x coordinate.
rotationCenterY The hand rotation center y coordinate.
Note
If no second hand is setup it will just be omitted.
{
    setupHand(secondHand, secondHandBitmapId, rotationCenterX, rotationCenterY);
}
References AnalogClock::secondHand, and AnalogClock::setupHand().
updateClock()
void updateClock () protected virtual
Update the visual representation of the clock on the display.
Implements AbstractClock.
{
    // Make sure that animating to 0 will move from left to right
    if (lastHour != 0 && currentHour == 0)
    {
        hourHand.updateZAngle(hourHand.getZAngle() - (2 * PI));
    }
    if (lastMinute != 0 && currentMinute == 0)
    {
        minuteHand.updateZAngle(minuteHand.getZAngle() - (2 * PI));
    }
    if (lastSecond != 0 && currentSecond == 0)
    {
        secondHand.updateZAngle(secondHand.getZAngle() - (2 * PI));
    }
    float newHandAngle;
    // Move hour hand
    if (hourHand.isVisible() && ((currentHour != lastHour) || (hourHandMinuteCorrectionActive && (currentMinute != lastMinute))))
    {
        newHandAngle = convertHandValueToAngle(12, currentHour, hourHandMinuteCorrectionActive ? currentMinute : 0);
        if (animationEnabled() && !hourHand.isTextureMapperAnimationRunning())
        {
            hourHand.setupAnimation(AnimationTextureMapper::Z_ROTATION, newHandAngle, animationDuration, 0, animationEquation);
            hourHand.startAnimation();
        }
        else
        {
            if (animationEnabled())
            {
                hourHand.cancelAnimationTextureMapperAnimation();
            }
            hourHand.updateZAngle(newHandAngle);
        }
    }
    // Move minute hand
    if (minuteHand.isVisible() && ((currentMinute != lastMinute) || (minuteHandSecondCorrectionActive && (currentSecond != lastSecond))))
    {
        newHandAngle = convertHandValueToAngle(60, currentMinute, minuteHandSecondCorrectionActive ? currentSecond : 0);
        if (animationEnabled() && !minuteHand.isTextureMapperAnimationRunning())
        {
            minuteHand.setupAnimation(AnimationTextureMapper::Z_ROTATION, newHandAngle, animationDuration, 0, animationEquation);
            minuteHand.startAnimation();
        }
        else
        {
            if (animationEnabled())
            {
                minuteHand.cancelAnimationTextureMapperAnimation();
            }
            minuteHand.updateZAngle(newHandAngle);
        }
    }
    // Move second hand
    if (secondHand.isVisible() && (currentSecond != lastSecond))
    {
        newHandAngle = convertHandValueToAngle(60, currentSecond);
        if (animationEnabled() && !secondHand.isTextureMapperAnimationRunning())
        {
            secondHand.setupAnimation(AnimationTextureMapper::Z_ROTATION, newHandAngle, animationDuration, 0, animationEquation);
            secondHand.startAnimation();
        }
        else
        {
            if (animationEnabled())
            {
                secondHand.cancelAnimationTextureMapperAnimation();
            }
            secondHand.updateZAngle(newHandAngle);
        }
    }
    lastHour = currentHour;
    lastMinute = currentMinute;
    lastSecond = currentSecond;
}
References AnalogClock::animationDuration, AnalogClock::animationEnabled(), AnalogClock::animationEquation, AnimationTextureMapper::cancelAnimationTextureMapperAnimation(), AnalogClock::convertHandValueToAngle(), AbstractClock::currentHour, AbstractClock::currentMinute, AbstractClock::currentSecond, TextureMapper::getZAngle(), AnalogClock::hourHand, AnalogClock::hourHandMinuteCorrectionActive, AnimationTextureMapper::isTextureMapperAnimationRunning(), Drawable::isVisible(), AnalogClock::lastHour, AnalogClock::lastMinute, AnalogClock::lastSecond, AnalogClock::minuteHand, AnalogClock::minuteHandSecondCorrectionActive, touchgfx::PI, AnalogClock::secondHand, AnimationTextureMapper::setupAnimation(), AnimationTextureMapper::startAnimation(), TextureMapper::updateZAngle(), and AnimationTextureMapper::Z_ROTATION.
Member Data Documentation
animationDuration
uint16_t animationDuration protected
The duration of hand animations. If 0 animations are disabled.
Referenced by AnalogClock::animationEnabled(), AnalogClock::getAnimationDuration(), AnalogClock::initializeTime24Hour(), AnalogClock::setAnimation(), and AnalogClock::updateClock().
animationEquation
EasingEquation animationEquation protected
The easing equation used by hand animations.
Referenced by AnalogClock::setAnimation(), and AnalogClock::updateClock().
background
Image background protected
The background image of the AnalogClock.
Referenced by AnalogClock::AnalogClock(), AnalogClock::getAlpha(), AnalogClock::setAlpha(), and AnalogClock::setBackground().
clockRotationCenterX
int16_t clockRotationCenterX protected
The x coordinate of the rotation point of the hands.
Referenced by AnalogClock::setRotationCenter(), and AnalogClock::setupHand().
clockRotationCenterY
int16_t clockRotationCenterY protected
The y coordinate of the rotation point of the hands.
Referenced by AnalogClock::setRotationCenter(), and AnalogClock::setupHand().
hourHand
AnimationTextureMapper hourHand protected
TextureMapper used for drawing the hourHand.
Referenced by AnalogClock::AnalogClock(), AnalogClock::setAlpha(), AnalogClock::setupHourHand(), and AnalogClock::updateClock().
hourHandMinuteCorrectionActive
bool hourHandMinuteCorrectionActive protected
Is hour hand minute correction active.
Referenced by AnalogClock::getHourHandMinuteCorrection(), AnalogClock::setHourHandMinuteCorrection(), and AnalogClock::updateClock().
lastHour
uint8_t lastHour protected
The last know hour value.
Referenced by AnalogClock::initializeTime24Hour(), and AnalogClock::updateClock().
lastMinute
uint8_t lastMinute protected
The last know minute value.
Referenced by AnalogClock::initializeTime24Hour(), and AnalogClock::updateClock().
lastSecond
uint8_t lastSecond protected
The last know second value.
Referenced by AnalogClock::initializeTime24Hour(), and AnalogClock::updateClock().
minuteHand
AnimationTextureMapper minuteHand protected
TextureMapper used for drawing the minuteHand.
Referenced by AnalogClock::AnalogClock(), AnalogClock::setAlpha(), AnalogClock::setupMinuteHand(), and AnalogClock::updateClock().
minuteHandSecondCorrectionActive
bool minuteHandSecondCorrectionActive protected
Is minute hand second correction active.
Referenced by AnalogClock::getMinuteHandSecondCorrection(), AnalogClock::setMinuteHandSecondCorrection(), and AnalogClock::updateClock().
secondHand
AnimationTextureMapper secondHand protected
TextureMapper used for drawing the secondHand.
Referenced by AnalogClock::AnalogClock(), AnalogClock::setAlpha(), AnalogClock::setupSecondHand(), and AnalogClock::updateClock().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/clock/AnalogClock.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/clock/AnalogClock.cpp