Battery Simulator Documentation: PainterRGB565LinearGradient
PainterRGB565LinearGradient
#include "PainterRGB565LinearGradient.hpp"
Public Member Functions
virtual void paint (uint8_t *destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const
virtual void tearDown () const
Public Member Functions inherited from AbstractPainterLinearGradient
AbstractPainterLinearGradient ()
virtual ~AbstractPainterLinearGradient ()
void setGradientEndPoints (float startX, float startY, float endX, float endY, float width, float height, const Matrix3x3 &m)
void setGradientTexture (const uint32_t *tex, bool solid)
Public Member Functions inherited from AbstractPainter
AbstractPainter ()
virtual ~AbstractPainter ()
void framebufferToDisplay (int16_t &widgetX, int16_t &widgetY) const
virtual HAL::RenderingMethod getRenderingMethod () const
virtual bool setup (const Rect &widgetRect) const
Additional Inherited Members
Static Protected Member Functions inherited from AbstractPainter
static FORCE_INLINE_FUNCTION bool compatibleFramebuffer (Bitmap::BitmapFormat format)
Protected Attributes inherited from AbstractPainterLinearGradient
float clOffset
Vertical offset for line with first color.
float clSlope
Slope of lines with same color.
int16_t coord0
The gradient line start.
int16_t coord1
The gradient line end.
float deltaColor
Color increment when moving 1 pixel horizontally.
float horizontalDistance
Horizontal distance between pixels with the first color and the last color.
bool isHorizontal
True if the gradient is horizontal (y0 == y1).
bool isSolid
True if all the gradient colors are solid.
bool isVertical
True if the gradient is vertical (x0 == x1).
const uint32_t * texture
The gradient color texture 1 x 1024.
Protected Attributes inherited from AbstractPainter
int16_t widgetWidth
The width of the widget on screen, used by framebufferToDisplay()
Detailed Description
An abstract class for creating painter classes for drawing canvas widgets. All canvas widgets need a painter to fill the shape drawn with a CanvasWidgetRenderer. The painter must provide the color of a pixel on a given coordinate, which will the be blended into the framebuffer depending on the position of the canvas widget and the transparency of the given pixel.
Member Function Documentation
paint()
void paint (uint8_t * destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const virtual
Paints a streak of pixels (all with the same alpha) in the framebuffer. The first pixel to paint is at 'offset' relative to 'destination' (to be able to support 1bpp, 2bpp and 4bpp). The first pixel to paint is at the given 'widgetX', 'widgetY' coordinate. The number of pixels to paint is 'count' and the alpha to apply is 'alpha'.
Note that the widgetX, widgetY is relative to the widget in the framebuffer, not the display. To convert the coordinate to display widget coordinates, use framebufferToDisplay().
Parameters
[in] destination If non-null, the pointer.
offset The offset to add to the destination.
widgetX The widget x coordinate.
widgetY The widget y coordinate.
count Number of pixels.
alpha The alpha of the pixels.
See also
AbstractPainter::setup, AbstractPainter::tearDown, AbstractPainter::framebufferToDisplay
Implements AbstractPainter.
{
    uint16_t* p = reinterpret_cast<uint16_t*>(destination) + offset;
    if (isVertical)
    {
        // The whole line is the same color
        uint32_t color;
        bool noise = false;
        if (widgetY <= coord0)
        {
            color = texture[deltaColor > 0 ? 0 : 1023];
        }
        else if (widgetY >= coord1)
        {
            color = texture[deltaColor > 0 ? 1023 : 0];
        }
        else
        {
            const int32_t colorOffset = (int)((widgetY - coord0) * deltaColor);
            color = texture[deltaColor > 0 ? colorOffset : 1023 + colorOffset];
            noise = true;
        }
        const uint16_t color565 = getNativeColor(color);
        uint16_t* const p_end = p + count;
        if (isSolid && (alpha == 255))
        {
            if (noise)
            {
                const uint8_t b = color & 0xFF;
                const uint8_t g = (color >> 8) & 0xFF;
                const uint8_t r = (color >> 16) & 0xFF;
                int x = widgetX;
                while (p < p_end)
                {
                    *p++ = applyNoise(x, widgetY, r, g, b);
                    x++;
                }
            }
            else
            {
                while (p < p_end)
                {
                    *p++ = color565;
                }
            }
        }
        else
        {
            const uint8_t a = (color >> 24) & 0xFF;
            const uint8_t alphaTot = LCD::div255(a * alpha);
            const uint16_t r = (color >> 8) & RMASK;
            const uint16_t g = (color >> 5) & GMASK;
            const uint16_t b = (color >> 3) & BMASK;
            while (p < p_end)
            {
                *p = alphaBlend(r, g, b, *p, alphaTot);
                p++;
            };
        }
        return;
    }
    //vx0 is where first color line (y=clSlope*x+clOffset) intersects the horizontal line y=widgetY
    float vx0;
    if (isHorizontal)
    {
        vx0 = coord0;
    }
    else
    {
        vx0 = (widgetY - clOffset) / clSlope;
        if (deltaColor < 0.0f)
        {
            vx0 -= horizontalDistance;
        }
    }
    int x = widgetX;
    // Left of gradient
    // All pixels up to first gradient line, paint using fixed color
    if (x <= vx0) // All pixels up to first gradient line
    {
        // Starting before gradient
        const int pixels = (int)(MIN(vx0 + 1 - x, count));
        // Start in correct end of palette depending on direction
        const uint32_t colorStart = texture[deltaColor > 0 ? 0 : 1023];
        uint16_t* const p_end = p + pixels;
        if (isSolid && (alpha == 255))
        {
            const uint16_t color565 = getNativeColor(colorStart);
            while (p < p_end)
            {
                *p++ = color565;
            }
        }
        else
        {
            const uint8_t a = (colorStart >> 24) & 0xFF;
            const uint8_t alphaTot = LCD::div255(a * alpha);
            const uint16_t r = (colorStart >> 8) & RMASK;
            const uint16_t g = (colorStart >> 5) & GMASK;
            const uint16_t b = (colorStart >> 3) & BMASK;
            while (p < p_end)
            {
                *p = alphaBlend(r, g, b, *p, alphaTot);
                p++;
            };
        }
        x += pixels;
    }
    const int16_t right = widgetX + count;
    if (x < right) // More to draw
    {
        //vx1 is where y=widgetY intersects the last color line (fixed distance from vx0)
        const float vx1 = vx0 + horizontalDistance;
        if (x < vx1) // Draw gradient part until last color line
        {
            const int endx = (int)(MIN(right, vx1));
            const uint16_t* const p_end = p + (endx - x);
            // Start with first or last color depending on direction
            float colorF = deltaColor > 0 ? 0.0000f : 1023.9999f;
            colorF += (x - vx0) * deltaColor;
            if (isSolid && (alpha == 255))
            {
                while (p < p_end)
                {
                    const int colorIndex = (int)colorF;
                    const uint32_t color = texture[colorIndex];
                    const uint8_t b = color & 0xFF;
                    const uint8_t g = (color >> 8) & 0xFF;
                    const uint8_t r = (color >> 16) & 0xFF;
                    *p++ = applyNoise(colorIndex, widgetY, r, g, b);
                    colorF += deltaColor;
                }
            }
            else
            {
                while (p < p_end)
                {
                    const int colorIndex = (int)colorF;
                    const uint32_t color = texture[colorIndex];
                    const uint8_t a = color >> 24;
                    const uint8_t alphaTot = LCD::div255(a * alpha);
                    const uint16_t r = (color >> 8) & RMASK;
                    const uint16_t g = (color >> 5) & GMASK;
                    const uint16_t b = (color >> 3) & BMASK;
                    *p = alphaBlend(r, g, b, *p, alphaTot);
                    p++;
                    colorF += deltaColor;
                }
            }
            x = endx;
        }
        if (x < right) // Second fixed color part
        {
            const uint16_t* const p_end = p + (right - x);
            const uint32_t colorEnd = texture[deltaColor > 0 ? 1023 : 0];
            const uint16_t color565 = getNativeColor(colorEnd);
            if (isSolid && (alpha == 255))
            {
                while (p < p_end)
                {
                    *p++ = color565;
                }
            }
            else
            {
                const uint8_t a = (colorEnd >> 24) & 0xFF;
                const uint8_t alphaTot = LCD::div255(a * alpha);
                const uint16_t r = (colorEnd >> 8) & RMASK;
                const uint16_t g = (colorEnd >> 5) & GMASK;
                const uint16_t b = (colorEnd >> 3) & BMASK;
                while (p < p_end)
                {
                    *p = alphaBlend(r, g, b, *p, alphaTot);
                    p++;
                };
            }
        }
    }
}
References touchgfx::alphaBlend(), touchgfx::applyNoise(), touchgfx::BMASK, AbstractPainterLinearGradient::clOffset, AbstractPainterLinearGradient::clSlope, AbstractPainterLinearGradient::coord0, AbstractPainterLinearGradient::coord1, AbstractPainterLinearGradient::deltaColor, LCD::div255(), touchgfx::getNativeColor(), touchgfx::GMASK, AbstractPainterLinearGradient::horizontalDistance, AbstractPainterLinearGradient::isHorizontal, AbstractPainterLinearGradient::isSolid, AbstractPainterLinearGradient::isVertical, MIN, and touchgfx::RMASK.
tearDown()
void tearDown () const virtual
This function is called after all paint operation have finished. This allows the painter to close down dma queues etc. This happens after the last scan line segment has been drawn.
See also
AbstractPainter::paint, AbstractPainter::setup
Reimplemented from AbstractPainter.
{
}
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/PainterRGB565LinearGradient.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/PainterRGB565LinearGradient.cpp