Battery Simulator Documentation: SwipeContainer::PageIndicator
SwipeContainer::PageIndicator
Public Member Functions
PageIndicator ()
uint8_t getCurrentPage () const
uint8_t getNumberOfPages () const
void goLeft ()
void goRight ()
void setBitmaps (const Bitmap &normalPage, const Bitmap &highlightedPage)
void setCurrentPage (uint8_t page)
void setNumberOfPages (uint8_t size)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Private Attributes
uint8_t currentPage
uint8_t numberOfPages
Image selectedPage
TiledImage unselectedPages
Additional Inherited Members
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
Constructor & Destructor Documentation
PageIndicator()
PageIndicator ()
    : Container(),
      unselectedPages(),
      selectedPage(),
      numberOfPages(0),
      currentPage(0)
{
    unselectedPages.setXY(0, 0);
    selectedPage.setXY(0, 0);
    Container::add(unselectedPages);
    Container::add(selectedPage);
}
References Container::add(), SwipeContainer::PageIndicator::selectedPage, Drawable::setXY(), and SwipeContainer::PageIndicator::unselectedPages.
Member Function Documentation
getCurrentPage()
uint8_t getCurrentPage () const
{
    return currentPage;
}
Referenced by SwipeContainer::getSelectedPage().
getNumberOfPages()
uint8_t getNumberOfPages () const
{
    return numberOfPages;
}
Referenced by SwipeContainer::getNumberOfPages(), and SwipeContainer::remove().
goLeft()
void goLeft ()
{
    setCurrentPage((currentPage + numberOfPages - 1) % numberOfPages);
}
Referenced by SwipeContainer::animateRight(), and SwipeContainer::animateRightWithButton().
goRight()
void goRight ()
{
    setCurrentPage((currentPage + 1) % numberOfPages);
}
Referenced by SwipeContainer::animateLeft(), and SwipeContainer::animateLeftWithButton().
setBitmaps()
void setBitmaps (const Bitmap & normalPage, const Bitmap & highlightedPage)
{
    selectedPage.setBitmap(highlightedPage);
    unselectedPages.setBitmap(normalPage);
    if (numberOfPages > 0)
    {
        setNumberOfPages(numberOfPages);
    }
}
Referenced by SwipeContainer::setPageIndicatorBitmaps().
setCurrentPage()
void setCurrentPage (uint8_t page)
{
    if (page < numberOfPages && page != currentPage)
    {
        currentPage = page;
        const int dotWidth = Bitmap(unselectedPages.getBitmap()).getWidth();
        selectedPage.moveTo(page * dotWidth, selectedPage.getY());
    }
}
References Bitmap::getWidth().
Referenced by SwipeContainer::setSelectedPage().
setNumberOfPages()
void setNumberOfPages (uint8_t size)
{
    numberOfPages = size;
    if (unselectedPages.getBitmapId() != BITMAP_INVALID)
    {
        const int dotWidth = Bitmap(unselectedPages.getBitmap()).getWidth();
        unselectedPages.setWidth(dotWidth * size);
        // adjust size of container according to the actual bitmaps
        invalidate();
        setWidthHeight(unselectedPages);
        setCurrentPage(MIN(size, currentPage));
        invalidate();
    }
}
References touchgfx::BITMAP_INVALID, Bitmap::getWidth(), Drawable::invalidate(), MIN, and Drawable::setWidthHeight().
Referenced by SwipeContainer::add(), and SwipeContainer::remove().
Member Data Documentation
currentPage
uint8_t currentPage private
numberOfPages
uint8_t numberOfPages private
selectedPage
Image selectedPage private
Referenced by SwipeContainer::PageIndicator::PageIndicator().
unselectedPages
TiledImage unselectedPages private
Referenced by SwipeContainer::PageIndicator::PageIndicator().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/SwipeContainer.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/SwipeContainer.cpp