Battery Simulator Documentation: ButtonWithLabel
ButtonWithLabel
#include "ButtonWithLabel.hpp"
Public Member Functions
ButtonWithLabel ()
virtual void draw (const Rect &area) const
TextRotation getLabelRotation ()
const TypedText & getLabelText () const
void setLabelColor (colortype col)
void setLabelColorPressed (colortype col)
void setLabelRotation (TextRotation textRotation)
void setLabelText (TypedText t)
void updateTextPosition ()
Public Member Functions inherited from Button
Button ()
uint8_t getAlpha () const
Bitmap getCurrentlyDisplayedBitmap () const
virtual Rect getSolidRect () const
virtual void invalidateContent () const
void setAlpha (uint8_t newAlpha)
virtual void setBitmaps (const Bitmap &bitmapReleased, const Bitmap &bitmapPressed)
Public Member Functions inherited from AbstractButton
AbstractButton ()
virtual void executeAction ()
virtual bool getPressedState () const
virtual void handleClickEvent (const ClickEvent &event)
void setAction (GenericCallback< const AbstractButton & > &callback)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
colortype color
The color used for the label when the button is in the released, normal state.
colortype colorPressed
The color used for the label when the button is in the pressed state.
TextRotation rotation
The rotation used for the label.
int16_t textHeightIncludingSpacing
Total height of the label (text height + spacing).
TypedText typedText
The TypedText used for the button label.
Protected Attributes inherited from Button
uint8_t alpha
The current alpha value. 255=solid, 0=invisible.
Bitmap down
The image to display when button is pressed.
Bitmap up
The image to display when button is released (normal state).
Protected Attributes inherited from AbstractButton
GenericCallback< const AbstractButton & > * action
The callback to be executed when this AbstractButton is clicked.
bool pressed
Is the button pressed or released? True if pressed.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A Button that has a bitmap with a text on top of it. It is possible to have two different colors for the text depending on the current state of the button (released or pressed).
Typical use case could be a red button with a normal and a pressed image. Those images can be reused across several buttons. The ButtonWithLabel will then allow a text to be superimposed on top of the red button.
See also
Button
Constructor & Destructor Documentation
ButtonWithLabel()
ButtonWithLabel ()
    : Button(), typedText(), color(0), colorPressed(0), rotation(TEXT_ROTATE_0), textHeightIncludingSpacing(0)
{
}
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Reimplemented from Button.
{
    Button::draw(area);
    if (typedText.hasValidId())
    {
        const Font* fontToDraw = typedText.getFont(); // Never return 0
        const int16_t height = textHeightIncludingSpacing;
        int16_t offset;
        Rect labelRect;
        switch (rotation)
        {
        case TEXT_ROTATE_0:
            offset = (this->getHeight() - height) / 2; // Prefer round down
            labelRect = Rect(0, offset, this->getWidth(), height);
            break;
        case TEXT_ROTATE_180:
            offset = ((this->getHeight() - height) + 1) / 2; // Prefer round up
            labelRect = Rect(0, offset, this->getWidth(), height);
            break;
        case TEXT_ROTATE_90:
            offset = ((this->getWidth() - height) + 1) / 2; // Prefer round up
            labelRect = Rect(offset, 0, height, this->getHeight());
            break;
        case TEXT_ROTATE_270:
            offset = (this->getWidth() - height) / 2; // Prefer round down
            labelRect = Rect(offset, 0, height, this->getHeight());
            break;
        }
        Rect dirty = labelRect & area;
        if (!dirty.isEmpty())
        {
            dirty.x -= labelRect.x;
            dirty.y -= labelRect.y;
            translateRectToAbsolute(labelRect);
            const LCD::StringVisuals visuals(fontToDraw, pressed ? colorPressed : color, alpha, typedText.getAlignment(), 0, rotation, typedText.getTextDirection(), 0, WIDE_TEXT_NONE);
            HAL::lcd().drawString(labelRect, dirty, visuals, typedText.getText());
        }
    }
}
References Button::alpha, ButtonWithLabel::color, ButtonWithLabel::colorPressed, touchgfx::dirty, Button::draw(), TypedText::getAlignment(), TypedText::getFont(), Drawable::getHeight(), TypedText::getText(), TypedText::getTextDirection(), Drawable::getWidth(), TypedText::hasValidId(), HAL::lcd(), AbstractButton::pressed, ButtonWithLabel::rotation, touchgfx::TEXT_ROTATE_0, touchgfx::TEXT_ROTATE_180, touchgfx::TEXT_ROTATE_270, touchgfx::TEXT_ROTATE_90, ButtonWithLabel::textHeightIncludingSpacing, Drawable::translateRectToAbsolute(), ButtonWithLabel::typedText, and touchgfx::WIDE_TEXT_NONE.
getLabelRotation()
TextRotation getLabelRotation () inline
Gets the current rotation of the text on the label.
Returns
The current rotation of the text.
    {
        return rotation;
    }
References ButtonWithLabel::rotation.
getLabelText()
const TypedText & getLabelText () const inline
Gets the text used for the label.
Returns
The text used for the label.
    {
        return typedText;
    }
References ButtonWithLabel::typedText.
setLabelColor()
void setLabelColor (colortype col) inline
Sets label color for the text when the button is in the normal, released state.
Parameters
col The color with which the text label should be drawn.
See also
setLabelColorPressed
Note
If the button is currently in the normal, released state, the button should be forced to redraw itself. This is done by calling invalidate() on the ButtonWithLabel.
The user code must call invalidate() in order to update the button on the display.
    {
        color = col;
    }
setLabelColorPressed()
void setLabelColorPressed (colortype col) inline
Sets label color for the text when the button is in the pressed state.
Parameters
col The color with which the text label should be drawn when the button is pressed.
See also
setLabelColor
Note
If the button is currently in the pressed state, the button should be forced to redraw itself. This is done by calling invalidate() on the ButtonWithLabel.
The user code must call invalidate() in order to update the button on the display.
    {
        colorPressed = col;
    }
References ButtonWithLabel::colorPressed.
setLabelRotation()
void setLabelRotation (TextRotation textRotation) inline
Sets the rotation of the text on the label. The text can be rotated in steps of 90 degrees.
Parameters
textRotation The rotation of the text. Default is TEXT_ROTATE_0.
See also
TextArea::setRotation
Note
that this will not rotate the bitmap of the label, only the text.
The user code must call invalidate() in order to update the button on the display.
    {
        rotation = textRotation;
    }
References ButtonWithLabel::rotation.
setLabelText()
void setLabelText (TypedText t) inline
Sets the text to display on the button. Texts with wildcards are not supported.
Parameters
t The text to display.
Note
The user code must call invalidate() in order to update the button on the display.
    {
        typedText = t;
        updateTextPosition();
    }
References ButtonWithLabel::typedText, and ButtonWithLabel::updateTextPosition().
updateTextPosition()
void updateTextPosition () inline
Positions the label text horizontally centered. If the text changes due to a language change you may need to reposition the label text by calling this function to keep the text horizontally centered.
Note
The user code must call invalidate() in order to update the button on the display.
    {
        if (typedText.hasValidId())
        {
            const Font* f = typedText.getFont();
            const Unicode::UnicodeChar* s = typedText.getText();
            textHeightIncludingSpacing = f->getHeight() * f->getNumberOfLines(s) + f->getSpacingAbove(s);
        }
        else
        {
            textHeightIncludingSpacing = 0;
        }
    }
References TypedText::getFont(), TypedText::getText(), TypedText::hasValidId(), ButtonWithLabel::textHeightIncludingSpacing, and ButtonWithLabel::typedText.
Referenced by ButtonWithLabel::setLabelText().
Member Data Documentation
color
colortype color protected
The color used for the label when the button is in the released, normal state.
Referenced by ButtonWithLabel::draw().
colorPressed
colortype colorPressed protected
The color used for the label when the button is in the pressed state.
Referenced by ButtonWithLabel::draw(), and ButtonWithLabel::setLabelColorPressed().
rotation
TextRotation rotation protected
The rotation used for the label.
Referenced by ButtonWithLabel::draw(), ButtonWithLabel::getLabelRotation(), and ButtonWithLabel::setLabelRotation().
textHeightIncludingSpacing
int16_t textHeightIncludingSpacing protected
Total height of the label (text height + spacing).
Referenced by ButtonWithLabel::draw(), and ButtonWithLabel::updateTextPosition().
typedText
TypedText typedText protected
The TypedText used for the button label.
Referenced by ButtonWithLabel::draw(), ButtonWithLabel::getLabelText(), ButtonWithLabel::setLabelText(), and ButtonWithLabel::updateTextPosition().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/ButtonWithLabel.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/ButtonWithLabel.cpp