Battery Simulator Documentation: ScalableImage
ScalableImage
#include "ScalableImage.hpp"
Public Types
enum ScalingAlgorithm { NEAREST_NEIGHBOR , BILINEAR_INTERPOLATION }
Public Member Functions
ScalableImage (const Bitmap &bmp=Bitmap())
virtual void draw (const Rect &invalidatedArea) const
virtual ScalingAlgorithm getScalingAlgorithm ()
virtual Rect getSolidRect () const
virtual void setScalingAlgorithm (ScalingAlgorithm algorithm)
Public Member Functions inherited from Image
Image (const Bitmap &bmp=Bitmap())
uint8_t getAlpha () const
Bitmap getBitmap () const
BitmapId getBitmapId () const
virtual void invalidateContent () const
void setAlpha (uint8_t newAlpha)
virtual void setBitmap (const Bitmap &bmp)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
ScalingAlgorithm currentScalingAlgorithm
The current scaling algorithm.
Protected Attributes inherited from Image
uint8_t alpha
The Alpha for this image.
Bitmap bitmap
The Bitmap to display.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
Widget for representing a scaled version of a bitmap. Simply change the width/height of the widget to resize the image. The quality of the scaled image depends of the rendering algorithm used. The rendering algorithm can be changed dynamically. Please note that scaling images is done at runtime and may require a lot of calculations.
Note
Note that this widget does not support 1 bit per pixel color depth.
Member Enumeration Documentation
ScalingAlgorithm
enum ScalingAlgorithm
Rendering algorithm to use when scaling the bitmap. Nearest neighbor simply finds the closest pixel in the source bitmap. Bi-linear interpolation averages 4 pixels to find a much better pixel representation.
Enumerator
NEAREST_NEIGHBOR
Fast but not a very good image quality. Good for fast animations.
BILINEAR_INTERPOLATION
Slower but better image quality. Good for static representation of a scaled image.
    {
        NEAREST_NEIGHBOR,
        BILINEAR_INTERPOLATION
    };
Constructor & Destructor Documentation
ScalableImage()
ScalableImage (const Bitmap & bmp = Bitmap())
Constructs a new ScalableImage with a default alpha value of 255 (solid) and a default Bitmap (undefined) if none is specified. If a Bitmap is passed to the constructor, the width and height of this widget is set to those of the bitmap.
Parameters
bmp (Optional) The bitmap to display.
See also
setBitmap
    : Image(bmp),
      currentScalingAlgorithm(BILINEAR_INTERPOLATION)
{
}
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Reimplemented from Image.
{
    if (!alpha)
    {
        return;
    }
    uint16_t* fb = 0;
    float triangleXs[4];
    float triangleYs[4];
    float triangleZs[4];
    float triangleUs[4];
    float triangleVs[4];
    const float imageX0 = 0;
    const float imageY0 = 0;
    const float imageX1 = imageX0 + getWidth();
    const float imageY1 = imageY0;
    const float imageX2 = imageX1;
    const float imageY2 = imageY0 + getHeight();
    const float imageX3 = imageX0;
    const float imageY3 = imageY2;
    triangleZs[0] = 100.f;
    triangleZs[1] = 100.f;
    triangleZs[2] = 100.f;
    triangleZs[3] = 100.f;
    // Setup texture coordinates
    const float right = (float)(bitmap.getWidth());
    const float bottom = (float)(bitmap.getHeight());
    float textureU0 = 0.0f;
    float textureV0 = 0.0f;
    float textureU1 = right;
    float textureV1 = 0.0f;
    float textureU2 = right;
    float textureV2 = bottom;
    float textureU3 = 0.0f;
    float textureV3 = bottom;
    if (HAL::DISPLAY_ROTATION == rotate90)
    {
        textureU0 = 0.0f;
        textureV0 = right;
        textureU1 = 0.0f;
        textureV1 = 0.0f;
        textureU2 = bottom;
        textureV2 = 0.0f;
        textureU3 = bottom;
        textureV3 = right;
    }
    triangleXs[0] = imageX0;
    triangleXs[1] = imageX1;
    triangleXs[2] = imageX2;
    triangleXs[3] = imageX3;
    triangleYs[0] = imageY0;
    triangleYs[1] = imageY1;
    triangleYs[2] = imageY2;
    triangleYs[3] = imageY3;
    triangleUs[0] = textureU0;
    triangleUs[1] = textureU1;
    triangleUs[2] = textureU2;
    triangleUs[3] = textureU3;
    triangleVs[0] = textureV0;
    triangleVs[1] = textureV1;
    triangleVs[2] = textureV2;
    triangleVs[3] = textureV3;
    drawQuad(invalidatedArea, fb, triangleXs, triangleYs, triangleZs, triangleUs, triangleVs);
}
References HAL::DISPLAY_ROTATION, Drawable::getHeight(), Drawable::getWidth(), and touchgfx::rotate90.
getScalingAlgorithm()
ScalableImage::ScalingAlgorithm getScalingAlgorithm () virtual
Gets the algorithm used when rendering.
Returns
The algorithm used when rendering.
See also
ScalingAlgorithm
{
    return currentScalingAlgorithm;
}
References ScalableImage::currentScalingAlgorithm.
Referenced by ZoomAnimationImage::getScalingMode().
getSolidRect()
Rect getSolidRect () const virtual
Get (the largest possible) rectangle that is guaranteed to be solid (opaque). This information is important, as any Drawable underneath the solid area does not need to be drawn.
Returns
The solid rectangle part of the Drawable.
Note
The rectangle returned must be relative to upper left corner of the Drawable, meaning that a completely solid widget should return the full size Rect(0, 0, getWidth(), getHeight()). If no area can be guaranteed to be solid, an empty Rect must be returned. Failing to return the correct rectangle may result in errors on the display.
Reimplemented from Image.
{
    // If original image is completely solid the scaled image will also be
    // Return the unscaled solid rect limited to the widget
    // TextureMapper may not fill solid pixels in the whole widget due to antialiasing
    if (alpha == 255)
    {
        const Rect bmpSolid = bitmap.getSolidRect();
        if (bmpSolid.width == bitmap.getWidth() && bmpSolid.height == bitmap.getHeight())
        {
            const Rect widgetRect(0, 0, getWidth(), getHeight());
            return bmpSolid & widgetRect;
        }
    }
    // Return empty rect otherwise
    return Rect();
}
References Drawable::getHeight(), and Drawable::getWidth().
setScalingAlgorithm()
void setScalingAlgorithm (ScalingAlgorithm algorithm) virtual
Sets the algorithm to be used. In short, there is currently a value for fast (nearest neighbor) and a value for slow (bi-linear interpolation).
Parameters
algorithm The algorithm to use when rendering.
See also
ScalingAlgorithm
{
    currentScalingAlgorithm = algorithm;
}
References ScalableImage::currentScalingAlgorithm.
Referenced by ZoomAnimationImage::ZoomAnimationImage(), and ZoomAnimationImage::setScalingMode().
Member Data Documentation
currentScalingAlgorithm
ScalingAlgorithm currentScalingAlgorithm protected
The current scaling algorithm.
Referenced by ScalableImage::getScalingAlgorithm(), and ScalableImage::setScalingAlgorithm().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/ScalableImage.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/ScalableImage.cpp