Battery Simulator Documentation: DynamicDataGraph
DynamicDataGraph abstract
#include "AbstractDataGraph.hpp"
Public Member Functions
DynamicDataGraph (int16_t capacity, int *values)
FORCE_INLINE_FUNCTION int16_t addDataPoint (float y)
FORCE_INLINE_FUNCTION int16_t addDataPoint (int y)
int16_t addDataPointScaled (int y)
virtual int getGraphRangeXMax () const
virtual int getGraphRangeXMin () const
virtual int getScale () const
virtual float getXAxisFactorAsFloat () const
virtual int getXAxisFactorAsInt () const
virtual int getXAxisFactorScaled () const
virtual float getXAxisOffsetAsFloat () const
virtual int getXAxisOffsetAsInt () const
virtual int getXAxisOffsetScaled () const
virtual int indexToDataPointXScaled (int16_t index) const
virtual int indexToDataPointYScaled (int16_t index) const
virtual void setGraphRangeXAutoScaled (bool, int margin)
virtual void setGraphRangeYAutoScaled (bool showXaxis, int margin)
virtual void setScale (int scale, bool updateData=false)
virtual void setXAxisFactor (float factor)
virtual void setXAxisFactor (int factor)
virtual void setXAxisFactorScaled (int factor)
virtual void setXAxisOffset (float offset)
virtual void setXAxisOffset (int offset)
virtual void setXAxisOffsetScaled (int offset)
Public Member Functions inherited from AbstractDataGraph
AbstractDataGraph (int16_t capacity)
void addBottomElement (AbstractGraphDecoration &d)
void addGraphElement (AbstractGraphElement &d)
void addLeftElement (AbstractGraphDecoration &d)
void addRightElement (AbstractGraphDecoration &d)
void addTopElement (AbstractGraphDecoration &d)
virtual void clear ()
FORCE_INLINE_FUNCTION int float2scaledX (float f) const
FORCE_INLINE_FUNCTION int float2scaledY (float f) const
FORCE_INLINE_FUNCTION uint8_t getAlpha () const
FORCE_INLINE_FUNCTION int16_t getGapBeforeIndex () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaHeight () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaHeightIncludingPadding () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginBottom () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginLeft () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginRight () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginTop () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingBottom () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingLeft () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingRight () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingTop () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaWidth () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaWidthIncludingPadding () const
virtual float getGraphRangeXMaxAsFloat () const
virtual int getGraphRangeXMaxAsInt () const
virtual int getGraphRangeXMaxScaled () const
virtual float getGraphRangeXMinAsFloat () const
virtual int getGraphRangeXMinAsInt () const
virtual int getGraphRangeXMinScaled () const
virtual float getGraphRangeYMaxAsFloat () const
virtual int getGraphRangeYMaxAsInt () const
virtual int getGraphRangeYMaxScaled () const
virtual float getGraphRangeYMinAsFloat () const
virtual int getGraphRangeYMinAsInt () const
virtual int getGraphRangeYMinScaled () const
FORCE_INLINE_FUNCTION int16_t getMaxCapacity () const
virtual bool getNearestIndexForScreenX (int16_t x, int16_t &index) const
virtual bool getNearestIndexForScreenXY (int16_t x, int16_t y, int16_t &index)
FORCE_INLINE_FUNCTION int16_t getUsedCapacity () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
FORCE_INLINE_FUNCTION void indexToDataPoint (int16_t index, float &xvalue, float &yvalue) const
FORCE_INLINE_FUNCTION void indexToDataPoint (int16_t index, int &xvalue, int &yvalue) const
FORCE_INLINE_FUNCTION void indexToDataPointScaled (int16_t index, int &xvalue, int &yvalue) const
FORCE_INLINE_FUNCTION float indexToDataPointXAsFloat (int16_t index) const
FORCE_INLINE_FUNCTION int indexToDataPointXAsInt (int16_t index) const
FORCE_INLINE_FUNCTION float indexToDataPointYAsFloat (int16_t index) const
FORCE_INLINE_FUNCTION int indexToDataPointYAsInt (int16_t index) const
FORCE_INLINE_FUNCTION int16_t indexToScreenX (int16_t index) const
FORCE_INLINE_FUNCTION int16_t indexToScreenY (int16_t index) const
FORCE_INLINE_FUNCTION int int2scaledX (int i) const
FORCE_INLINE_FUNCTION int int2scaledY (int i) const
virtual void invalidateContent () const
FORCE_INLINE_FUNCTION float scaled2floatX (int i) const
FORCE_INLINE_FUNCTION float scaled2floatY (int i) const
FORCE_INLINE_FUNCTION int scaled2intX (int i) const
FORCE_INLINE_FUNCTION int scaled2intY (int i) const
virtual void setAlpha (uint8_t newAlpha)
FORCE_INLINE_FUNCTION void setClickAction (GenericCallback< const AbstractDataGraph &, const GraphClickEvent & > &callback)
FORCE_INLINE_FUNCTION void setDragAction (GenericCallback< const AbstractDataGraph &, const GraphDragEvent & > &callback)
FORCE_INLINE_FUNCTION void setGapBeforeIndex (int16_t index)
void setGraphAreaMargin (int16_t top, int16_t left, int16_t right, int16_t bottom)
void setGraphAreaPadding (int16_t top, int16_t left, int16_t right, int16_t bottom)
FORCE_INLINE_FUNCTION void setGraphRange (float xMin, float xMax, float yMin, float yMax)
FORCE_INLINE_FUNCTION void setGraphRange (float xMin, float xMax, int yMin, int yMax)
FORCE_INLINE_FUNCTION void setGraphRange (int xMin, int xMax, float yMin, float yMax)
FORCE_INLINE_FUNCTION void setGraphRange (int xMin, int xMax, int yMin, int yMax)
FORCE_INLINE_FUNCTION void setGraphRangeScaled (int xMin, int xMax, int yMin, int yMax)
virtual void setGraphRangeX (float min, float max)
virtual void setGraphRangeX (int min, int max)
virtual void setGraphRangeXAuto (bool showYaxis, float margin)
virtual void setGraphRangeXAuto (bool showYaxis=true, int margin=0)
virtual void setGraphRangeXScaled (int min, int max)
virtual void setGraphRangeY (float min, float max)
virtual void setGraphRangeY (int min, int max)
virtual void setGraphRangeYAuto (bool showXaxis, float margin)
virtual void setGraphRangeYAuto (bool showXaxis=true, int margin=0)
virtual void setGraphRangeYScaled (int min, int max)
virtual void setHeight (int16_t height)
virtual void setWidth (int16_t width)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual int16_t addValue (int value)=0
virtual void beforeAddValue ()
virtual int16_t dataIndex (int16_t screenIndex) const
virtual int getScaleX () const
virtual int getScaleY () const
virtual int32_t indexToGlobalIndex (int16_t index) const
virtual CWRUtil::Q5 indexToScreenXQ5 (int16_t index) const
virtual CWRUtil::Q5 indexToScreenYQ5 (int16_t index) const
virtual int indexToXAxis (const int valueScaled, const int) const
virtual void setScaleX (int scale, bool updateData=false)
virtual void setScaleY (int scale, bool updateData=false)
virtual bool xScreenRangeToIndexRange (int16_t xMin, int16_t xMax, int16_t &indexMin, int16_t &indexMax) const
Protected Member Functions inherited from AbstractDataGraph
void invalidateAllXAxisPoints ()
FORCE_INLINE_FUNCTION void invalidateGraphArea () const
void invalidateGraphPointAt (int16_t index)
void invalidateXAxisPointAt (int16_t index)
void updateAreasPosition ()
virtual CWRUtil::Q5 valueToScreenXQ5 (int x) const
virtual CWRUtil::Q5 valueToScreenYQ5 (int y) const
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
uint32_t dataCounter
The data counter of how many times addDataPoint() has been called.
int xAxisFactor
The axis scale (real distance between two indices)
int xAxisOffset
The x axis offset (real value of data point at index 0)
int * yValues
The values of the graph.
Protected Attributes inherited from AbstractDataGraph
uint8_t alpha
The alpha of the entire graph.
Container bottomArea
The area below the graph.
int16_t bottomPadding
The graph area bottom padding.
GenericCallback< const AbstractDataGraph &, const GraphClickEvent & > * clickAction
The callback to be executed when this Graph is clicked.
GenericCallback< const AbstractDataGraph &, const GraphDragEvent & > * dragAction
The callback to be executed when this Graph is dragged.
int16_t gapBeforeIndex
The graph is disconnected (there is a gap) before this element index.
Container graphArea
The graph area (the center area)
int graphRangeMaxX
The graph range maximum x coordinate.
int graphRangeMaxY
The graph range maximum y coordinate.
int graphRangeMinX
The graph range minimum x coordinate.
int graphRangeMinY
The graph range minimum y coordinate.
Container leftArea
The area to the left of the graph.
int16_t leftPadding
The graph area left padding.
int16_t maxCapacity
Maximum number of points in the graph.
Container rightArea
The area to the right of the graph.
int16_t rightPadding
The graph area right padding.
Container topArea
The area above the graph.
int16_t topPadding
The graph area top padding.
int16_t usedCapacity
The number of used points in the graph.
int xScale
The data scale for the x values.
int yScale
The data scale for the y values.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataGraph
static int convertToNewScale (int value, int oldScale, int newScale)
static FORCE_INLINE_FUNCTION int float2scaled (float f, int scale)
static FORCE_INLINE_FUNCTION int int2scaled (int i, int scale)
static FORCE_INLINE_FUNCTION float scaled2float (int i, int scale)
static FORCE_INLINE_FUNCTION int scaled2int (int i, int scale)
Detailed Description
Abstract helper class used to implement graphs with the same distance between the x values (i.e. x is ignored).
Constructor & Destructor Documentation
DynamicDataGraph()
DynamicDataGraph (int16_t capacity, int * values) inline
Initializes a new instance of the AbstractDataGraphWithY class.
Parameters
capacity The capacity.
[in] values Address where to store the y values of the graph.
        : AbstractDataGraph(capacity), xAxisFactor(1), xAxisOffset(0), yValues(values), dataCounter(0)
    {
        DynamicDataGraph::setGraphRangeX(0, capacity - 1);
    }
References AbstractDataGraph::setGraphRangeX().
Member Function Documentation
addDataPoint() [1/2]
FORCE_INLINE_FUNCTION int16_t addDataPoint (float y) inline
Adds a new data point to the end of the graph. The part of the graph that is changed, is automatically redrawn (invalidated).
Parameters
y The new data point.
Returns
The index of the just added value.
    {
        return addDataPointScaled(float2scaledY(y));
    }
References DynamicDataGraph::addDataPointScaled(), and AbstractDataGraph::float2scaledY().
addDataPoint() [2/2]
FORCE_INLINE_FUNCTION int16_t addDataPoint (int y) inline
Adds a new data point to the end of the graph. The part of the graph that is changed, is automatically redrawn (invalidated).
Parameters
y The new data point.
Returns
The index of the just added value.
    {
        return addDataPointScaled(int2scaledY(y));
    }
References DynamicDataGraph::addDataPointScaled(), and AbstractDataGraph::int2scaledY().
addDataPointScaled()
int16_t addDataPointScaled (int y)
Adds a new data point to the end of the graph. The part of the graph that is changed, is automatically redrawn (invalidated).
Parameters
y The new data point.
Returns
The index of the just added value.
The index of the added data point.
Note
The y value must already be scaled.
{
    beforeAddValue();
    dataCounter++;
    return addValue(y);
}
References DynamicDataGraph::addValue(), DynamicDataGraph::beforeAddValue(), and DynamicDataGraph::dataCounter.
Referenced by DynamicDataGraph::addDataPoint(), and DynamicDataGraph::addDataPoint().
addValue()
virtual int16_t addValue (int value) protected pure virtual
Adds a value to the internal data array and keeps track of when graph points, graph axis and the entire graph needs to be redrawn (invalidated).
Parameters
value The value to add to the array.
Returns
The index of the newly added value.
Implemented in GraphScrollData, GraphWrapAndClearData, and GraphWrapAndOverwriteData.
Referenced by DynamicDataGraph::addDataPointScaled().
beforeAddValue()
virtual void beforeAddValue () inline protected virtual
This function is called before a new value (data point) is added. This allows for invalidation to be calculated based on the global data counter before it is increased as a result of adding the new point.
Reimplemented in GraphScrollData, GraphWrapAndClearData, and GraphWrapAndOverwriteData.
    {
    }
Referenced by DynamicDataGraph::addDataPointScaled().
dataIndex()
virtual int16_t dataIndex (int16_t screenIndex) const inline protected virtual
Get the data index in the yValues array of the given screen index. Normally this is just the 'i' but e.g. GraphScrollData does not, for performance reasons.
Parameters
screenIndex Zero-based screen index.
Returns
The index in the yValues array.
Reimplemented in GraphScrollData.
    {
        return screenIndex;
    }
Referenced by GraphWrapAndClearData::addValue(), GraphWrapAndOverwriteData::addValue(), DynamicDataGraph::indexToDataPointYScaled(), and DynamicDataGraph::indexToScreenYQ5().
getGraphRangeXMax()
virtual int getGraphRangeXMax () const inline virtual
Gets the maximum x coordinate for the graph.
Returns
The maximum x coordinate .
    {
        return getGraphRangeXMaxScaled();
    }
References AbstractDataGraph::getGraphRangeXMaxScaled().
Referenced by GraphWrapAndOverwriteData::addValue(), GraphWrapAndOverwriteData::beforeAddValue(), and DynamicDataGraph::setGraphRangeYAutoScaled().
getGraphRangeXMin()
virtual int getGraphRangeXMin () const inline virtual
Gets the minimum x coordinate for the graph.
Returns
The minimum x coordinate .
    {
        return getGraphRangeXMinScaled();
    }
References AbstractDataGraph::getGraphRangeXMinScaled().
Referenced by GraphWrapAndOverwriteData::addValue(), GraphWrapAndOverwriteData::beforeAddValue(), and DynamicDataGraph::setGraphRangeYAutoScaled().
getScale()
virtual int getScale () const inline virtual
Gets the scaling factor previously set using setScale().
Returns
The scaling factor.
See also
setScale
    {
        return getScaleY();
    }
References DynamicDataGraph::getScaleY().
getScaleX()
virtual int getScaleX () const inline protected virtual
Gets the scaling factor previously set using setScaleX().
Returns
The scaling factor.
See also
setScaleX, setScaleY, getScaleY
Reimplemented from AbstractDataGraph.
    {
        return AbstractDataGraph::getScaleX();
    }
References AbstractDataGraph::getScaleX().
Referenced by DynamicDataGraph::setScaleX().
getScaleY()
virtual int getScaleY () const inline protected virtual
Gets the scaling factor previously set using setScaleY().
Returns
The scaling factor.
See also
setScaleY, setScaleX, getScaleX
Reimplemented from AbstractDataGraph.
    {
        return AbstractDataGraph::getScaleY();
    }
References AbstractDataGraph::getScaleY().
Referenced by DynamicDataGraph::getScale(), and DynamicDataGraph::setScaleY().
getXAxisFactorAsFloat()
virtual float getXAxisFactorAsFloat () const inline virtual
Get x coordinate axis factor value. This is the real x value increment between two data points added to the graph.
Returns
The x axis factor.
    {
        return scaled2floatX(getXAxisFactorScaled());
    }
References DynamicDataGraph::getXAxisFactorScaled(), and AbstractDataGraph::scaled2floatX().
getXAxisFactorAsInt()
virtual int getXAxisFactorAsInt () const inline virtual
Get x coordinate axis factor value. This is the real x value increment between two data points added to the graph.
Returns
The x axis factor.
    {
        return scaled2intX(getXAxisFactorScaled());
    }
References DynamicDataGraph::getXAxisFactorScaled(), and AbstractDataGraph::scaled2intX().
getXAxisFactorScaled()
virtual int getXAxisFactorScaled () const inline virtual
Get x axis factor as a scaled value.
Returns
The x axis factor (scaled).
See also
getXAxisFactorAsInt, getXAxisFactorAsFloat, setXAxisFactor
    {
        return xAxisFactor;
    }
References DynamicDataGraph::xAxisFactor.
Referenced by DynamicDataGraph::getXAxisFactorAsFloat(), and DynamicDataGraph::getXAxisFactorAsInt().
getXAxisOffsetAsFloat()
virtual float getXAxisOffsetAsFloat () const inline virtual
Get x coordinate axis offset value. This is the real x value of the first data point added to the graph (i.e. the data point at index 0).
Returns
The x axis offset.
    {
        return scaled2floatX(getXAxisOffsetScaled());
    }
References DynamicDataGraph::getXAxisOffsetScaled(), and AbstractDataGraph::scaled2floatX().
getXAxisOffsetAsInt()
virtual int getXAxisOffsetAsInt () const inline virtual
Get x coordinate axis offset value. This is the real x value of the first data point added to the graph (i.e. the data point at index 0).
Returns
The x axis offset.
    {
        return scaled2intX(getXAxisOffsetScaled());
    }
References DynamicDataGraph::getXAxisOffsetScaled(), and AbstractDataGraph::scaled2intX().
getXAxisOffsetScaled()
virtual int getXAxisOffsetScaled () const inline virtual
Get x axis offset as a scaled value.
Returns
The x axis offset (scaled).
See also
getXAxisOffsetAsInt, getXAxisOffsetAsFloat, setXAxisOffsetScaled, setXAxisOffset
    {
        return xAxisOffset;
    }
References DynamicDataGraph::xAxisOffset.
Referenced by DynamicDataGraph::getXAxisOffsetAsFloat(), and DynamicDataGraph::getXAxisOffsetAsInt().
indexToDataPointXScaled()
virtual int indexToDataPointXScaled (int16_t index) const inline virtual
Gets data point x coordinate scaled.
Parameters
index Zero-based index of the value to fetch.
Returns
The data point x coordinate scaled.
See also
indexToDataPointXAsInt, indexToDataPointXAsFloat, indexToDataPointYScaled, indexToDataPoint, indexToDataPointScaled
Implements AbstractDataGraph.
    {
        assert(index >= 0 && index < usedCapacity);
        return (indexToGlobalIndex(index) * xAxisFactor) + xAxisOffset;
    }
References DynamicDataGraph::indexToGlobalIndex(), AbstractDataGraph::usedCapacity, DynamicDataGraph::xAxisFactor, and DynamicDataGraph::xAxisOffset.
indexToDataPointYScaled()
virtual int indexToDataPointYScaled (int16_t index) const inline virtual
Gets data point y coordinate scaled.
Parameters
index Zero-based index of the value to fetch.
Returns
The data point y coordinate scaled.
See also
indexToDataPointYAsInt, indexToDataPointYAsFloat, indexToDataPointXScaled, indexToDataPoint, indexToDataPointScaled
Implements AbstractDataGraph.
    {
        assert(index >= 0 && index < usedCapacity);
        return yValues[dataIndex(index)];
    }
References DynamicDataGraph::dataIndex(), AbstractDataGraph::usedCapacity, and DynamicDataGraph::yValues.
indexToGlobalIndex()
virtual int32_t indexToGlobalIndex (int16_t index) const inline protected virtual
Convert an index to global index. The index is the index of any data point, The global index is a value that keeps growing whenever a new data point is added the the graph.
Parameters
index Zero-based index of the point.
Returns
The global index.
Reimplemented in GraphScrollData, GraphWrapAndClearData, and GraphWrapAndOverwriteData.
    {
        return (int32_t)index;
    }
Referenced by DynamicDataGraph::indexToDataPointXScaled(), and DynamicDataGraph::indexToXAxis().
indexToScreenXQ5()
virtual CWRUtil::Q5 indexToScreenXQ5 (int16_t index) const inline protected virtual
Gets screen x coordinate for a specific data point added to the graph.
Parameters
index The index of the element to get the x coordinate for.
Returns
The screen x coordinate for the specific data point.
Implements AbstractDataGraph.
    {
        return valueToScreenXQ5(int2scaledX(index));
    }
References AbstractDataGraph::int2scaledX(), and AbstractDataGraph::valueToScreenXQ5().
indexToScreenYQ5()
virtual CWRUtil::Q5 indexToScreenYQ5 (int16_t index) const inline protected virtual
Gets screen y coordinate for a specific data point added to the graph.
Parameters
index The index of the element to get the y coordinate for.
Returns
The screen x coordinate for the specific data point.
Implements AbstractDataGraph.
    {
        return valueToScreenYQ5(yValues[dataIndex(index)]);
    }
References DynamicDataGraph::dataIndex(), AbstractDataGraph::valueToScreenYQ5(), and DynamicDataGraph::yValues.
indexToXAxis()
virtual int indexToXAxis (const int valueScaled, const int labelScaled) const inline protected virtual
Convert the given valueScaled (index) to x axis value.
Parameters
valueScaled The value scaled.
labelScaled The label scaled.
Returns
The x axis value.
Implements AbstractDataGraph.
    {
        // Value is also index for these types of graphs.
        return (indexToGlobalIndex(scaled2intX(valueScaled)) * xAxisFactor) + xAxisOffset;
    }
References DynamicDataGraph::indexToGlobalIndex(), AbstractDataGraph::scaled2intX(), DynamicDataGraph::xAxisFactor, and DynamicDataGraph::xAxisOffset.
setGraphRangeXAutoScaled()
virtual void setGraphRangeXAutoScaled (bool showYaxis, int margin) inline virtual
Automatically adjust min and max x coordinate to show entire graph. It is possible to ensure that the y axis (i.e. x=0) is included in the new range. If the graph range is changed as a consequence of calling this function, the graph is automatically redrawn (invalidated).
Parameters
showYaxis (Optional) True to ensure that the y axis is visible (default is true).
margin (Optional) The margin to add above/below the max/min x value (default is no margin).
See also
setGraphRangeXAuto, setGraphRangeXAutoScaled, setGraphRangeYAuto, setGraphRangeYAutoScaled
Note
This takes the currently visible y coordinate range into account.
If data in the graph is changed, added or deleted, the graph range is not automatically recalculated. Call this function again to achieve this functionality.
The arguments are assumed scaled. This means that if the scale is 1000, a value of 1 is interpreted as 0.001 (i.e. 1/1000).
Implements AbstractDataGraph.
    {
        setGraphRangeXScaled(-scaled2intX(margin), (usedCapacity - 1) + scaled2intX(margin));
    }
References AbstractDataGraph::scaled2intX(), AbstractDataGraph::setGraphRangeXScaled(), and AbstractDataGraph::usedCapacity.
setGraphRangeYAutoScaled()
void setGraphRangeYAutoScaled (bool showXaxis, int margin) virtual
Automatic adjust min and max y coordinate to show entire graph. It is possible to ensure that the x axis (i.e. y=0) is included in the new range. If the graph range is changed, the graph is automatically redrawn (invalidated).
Parameters
showXaxis True to ensure that the x axis is visible (default is true).
margin The margin to add above/below the max/min y value (default is no margin).
Note
This takes the current visible x coordinate range into account.
Implements AbstractDataGraph.
{
    if (usedCapacity == 0)
    {
        return;
    }
    int16_t indexMin = (int16_t)getGraphRangeXMin();
    int16_t indexMax = (int16_t)getGraphRangeXMax();
    if (indexMin > indexMax)
    {
        const int tmp = indexMin;
        indexMin = indexMax;
        indexMax = tmp;
    }
    indexMin = MAX(indexMin, 0);
    indexMax = MIN(indexMax, usedCapacity);
    if (indexMin < usedCapacity && indexMax >= 0)
    {
        int yMin = showXaxis ? margin : yValues[indexMin];
        int yMax = showXaxis ? -margin : yValues[indexMin];
        for (int i = indexMin; i < indexMax; i++)
        {
            const int y = yValues[i];
            if (yMin > y)
            {
                yMin = y;
            }
            if (yMax < y)
            {
                yMax = y;
            }
        }
        yMin -= margin;
        yMax += margin;
        if (yMin != yMax)
        {
            setGraphRangeYScaled(yMin, yMax);
        }
    }
}
References DynamicDataGraph::getGraphRangeXMax(), DynamicDataGraph::getGraphRangeXMin(), MAX, MIN, AbstractDataGraph::setGraphRangeYScaled(), AbstractDataGraph::usedCapacity, and DynamicDataGraph::yValues.
setScale()
virtual void setScale (int scale, bool updateData = false) inline virtual
Sets a scaling factor to be multiplied on each added element. Since the graph only stores integer values internally, it is possible to set a scale to e.g. 1000 and make the graph work as if there are three digits of precision. The addDataPoint() will multiply the argument with the scaling factor and store this value.
By setting the scale to 1 it is possible to simply use integer values for the graph.
Parameters
scale The scaling factor.
updateData (Optional) True to update all existing y value.
See also
getScale
Note
The current xAxisFactor, xAxisOffet and xGraphRange values are updated to reflect the new scale being set.
    {
        setScaleX(scale, updateData);
        setScaleY(scale, updateData);
    }
References DynamicDataGraph::setScaleX(), and DynamicDataGraph::setScaleY().
setScaleX()
void setScaleX (int scale, bool updateData = false) protected virtual
Sets a scaling factor to be multiplied on each X value added. Since the graph only stores integer values internally, it is possible to set a scale to e.g. 1000 and make the graph work as if there are three digits of precision. The addDataPoint() will multiply the x argument with the scaling factor and store this value. Please note the addDataPointScaled, which allows adding a value that is assumed to have already been multiplied by the scaling factor. Other functions exist in a "scaled" version where the arguments are assumed to already be scaled.
By setting the scale to 1 it is possible to simply use integer values for the graph.
Parameters
scale The scaling factor.
updateData (Optional) True to update all existing x value.
See also
getScaleX, setScaleY, getScaleY
Reimplemented from AbstractDataGraph.
{
    const int oldScale = getScaleX();
    if (scale != oldScale)
    {
        setGraphRangeXScaled(convertToNewScale(graphRangeMinX, oldScale, scale), convertToNewScale(graphRangeMaxX, oldScale, scale));
        xAxisFactor = convertToNewScale(xAxisFactor, oldScale, scale);
        xAxisOffset = convertToNewScale(xAxisOffset, oldScale, scale);
        AbstractDataGraph::setScaleX(scale, updateData);
    }
}
References AbstractDataGraph::convertToNewScale(), DynamicDataGraph::getScaleX(), AbstractDataGraph::graphRangeMaxX, AbstractDataGraph::graphRangeMinX, AbstractDataGraph::setGraphRangeXScaled(), AbstractDataGraph::setScaleX(), DynamicDataGraph::xAxisFactor, and DynamicDataGraph::xAxisOffset.
Referenced by DynamicDataGraph::setScale().
setScaleY()
void setScaleY (int scale, bool updateData = false) protected virtual
Sets a scaling factor to be multiplied on each Y value added. Since the graph only stores integer values internally, it is possible to set a scale to e.g. 1000 and make the graph work as if there are three digits of precision. The addDataPoint() will multiply the y argument with the scaling factor and store this value. Please note the addDataPointScaled, which allows adding a value that is assumed to have already been multiplied by the scaling factor. Other functions exist in a "scaled" version where the arguments are assumed to already be scaled.
By setting the scale to 1 it is possible to simply use integer values for the graph.
Parameters
scale The scaling factor.
updateData (Optional) True to update all existing y value.
See also
getScaleY, setScaleX, getScaleX
Reimplemented from AbstractDataGraph.
{
    if (updateData)
    {
        const int oldScale = getScaleY();
        for (int16_t index = 0; index < usedCapacity; index++)
        {
            yValues[index] = convertToNewScale(yValues[index], oldScale, scale);
        }
    }
    AbstractDataGraph::setScaleY(scale);
}
References AbstractDataGraph::convertToNewScale(), DynamicDataGraph::getScaleY(), AbstractDataGraph::setScaleY(), AbstractDataGraph::usedCapacity, and DynamicDataGraph::yValues.
Referenced by DynamicDataGraph::setScale().
setXAxisFactor() [1/2]
virtual void setXAxisFactor (float factor) inline virtual
Set x coordinate axis factor value. This is the real x value increment between two data points added to the graph.
Parameters
factor The x axis factor.
    {
        setXAxisFactorScaled(float2scaledX(factor));
    }
References AbstractDataGraph::float2scaledX(), and DynamicDataGraph::setXAxisFactorScaled().
setXAxisFactor() [2/2]
virtual void setXAxisFactor (int factor) inline virtual
Set x coordinate axis factor value. This is the real x value increment between two data points added to the graph.
Parameters
factor The x axis factor.
    {
        setXAxisFactorScaled(int2scaledX(factor));
    }
References AbstractDataGraph::int2scaledX(), and DynamicDataGraph::setXAxisFactorScaled().
setXAxisFactorScaled()
virtual void setXAxisFactorScaled (int factor) inline virtual
Set x coordinate axis factor value using a pre-scaled value. This is the real x value increment between two data points added to the graph.
Parameters
factor The x axis factor.
See also
setXAxisFactorScaled,setXAxisFactor
    {
        xAxisFactor = factor;
    }
References DynamicDataGraph::xAxisFactor.
Referenced by DynamicDataGraph::setXAxisFactor(), and DynamicDataGraph::setXAxisFactor().
setXAxisOffset() [1/2]
virtual void setXAxisOffset (float offset) inline virtual
Set x coordinate axis offset value. This is the real x value of the first data point added to the graph (i.e. the data point at index 0).
Parameters
offset The x axis offset.
    {
        setXAxisOffsetScaled(float2scaledX(offset));
    }
References AbstractDataGraph::float2scaledX(), and DynamicDataGraph::setXAxisOffsetScaled().
setXAxisOffset() [2/2]
virtual void setXAxisOffset (int offset) inline virtual
Set x coordinate axis offset value. This is the real x value of the first data point added to the graph (i.e. the data point at index 0).
Parameters
offset The x axis offset.
    {
        setXAxisOffsetScaled(int2scaledX(offset));
    }
References AbstractDataGraph::int2scaledX(), and DynamicDataGraph::setXAxisOffsetScaled().
setXAxisOffsetScaled()
virtual void setXAxisOffsetScaled (int offset) inline virtual
Set x coordinate axis offset value with a pre-scaled offset value. This is the real x value of the first data point added to the graph (i.e. the data point at index 0).
Parameters
offset The x axis offset.
See also
setXAxisOffset
setXAxisOffset, getXAxisOffsetScaled
    {
        xAxisOffset = offset;
    }
References DynamicDataGraph::xAxisOffset.
Referenced by DynamicDataGraph::setXAxisOffset(), and DynamicDataGraph::setXAxisOffset().
xScreenRangeToIndexRange()
bool xScreenRangeToIndexRange (int16_t xMin, int16_t xMax, int16_t & indexMin, int16_t & indexMax) const protected virtual
Gets index range for screen x coordinate range taking the current graph range into account.
Parameters
xMin The low screen x coordinate.
xMax The high screen x coordinate.
[out] indexMin The low element index.
[out] indexMax The high element index.
Returns
True if the range from low index to high index is legal.
Note
For internal use.
Implements AbstractDataGraph.
{
    if (usedCapacity == 0)
    {
        indexMin = indexMax = -1;
        return false;
    }
    if (getGraphAreaWidth() <= 1)
    {
        indexMin = 0;
        indexMax = usedCapacity - 1;
        return true;
    }
    CWRUtil::Q5 xQ5Min = CWRUtil::muldivQ5(CWRUtil::toQ5(xMin - leftPadding), CWRUtil::Q5(scaled2intX(graphRangeMaxX - graphRangeMinX)), CWRUtil::Q5(getGraphAreaWidth() - 1)) + CWRUtil::toQ5(scaled2intX(graphRangeMinX));
    CWRUtil::Q5 xQ5Max = CWRUtil::muldivQ5(CWRUtil::toQ5(xMax - leftPadding), CWRUtil::Q5(scaled2intX(graphRangeMaxX - graphRangeMinX)), CWRUtil::Q5(getGraphAreaWidth() - 1)) + CWRUtil::toQ5(scaled2intX(graphRangeMinX));
    if (xQ5Min > xQ5Max)
    {
        const CWRUtil::Q5 tmp = xQ5Min;
        xQ5Min = xQ5Max;
        xQ5Max = tmp;
    }
    indexMin = xQ5Min.to<int16_t>(); // X is also index in AbstractDataGraphWithY
    indexMax = xQ5Max.ceil();
    if (indexMax < 0)
    {
        indexMin = indexMax = 0;
        return false;
    }
    if (indexMin > usedCapacity - 1)
    {
        indexMin = indexMax = usedCapacity - 1;
        return false;
    }
    indexMin = MAX(0, indexMin);
    indexMax = MIN(usedCapacity - 1, indexMax);
    return true;
}
References AbstractDataGraph::getGraphAreaWidth(), AbstractDataGraph::graphRangeMaxX, AbstractDataGraph::graphRangeMinX, AbstractDataGraph::leftPadding, MAX, MIN, CWRUtil::muldivQ5(), AbstractDataGraph::scaled2intX(), CWRUtil::toQ5(), and AbstractDataGraph::usedCapacity.
Member Data Documentation
dataCounter
uint32_t dataCounter protected
The data counter of how many times addDataPoint() has been called.
Referenced by DynamicDataGraph::addDataPointScaled(), GraphScrollData::indexToGlobalIndex(), GraphWrapAndClearData::indexToGlobalIndex(), and GraphWrapAndOverwriteData::indexToGlobalIndex().
xAxisFactor
int xAxisFactor protected
The axis scale (real distance between two indices)
Referenced by DynamicDataGraph::getXAxisFactorScaled(), DynamicDataGraph::indexToDataPointXScaled(), DynamicDataGraph::indexToXAxis(), DynamicDataGraph::setScaleX(), and DynamicDataGraph::setXAxisFactorScaled().
xAxisOffset
int xAxisOffset protected
The x axis offset (real value of data point at index 0)
Referenced by DynamicDataGraph::getXAxisOffsetScaled(), DynamicDataGraph::indexToDataPointXScaled(), DynamicDataGraph::indexToXAxis(), DynamicDataGraph::setScaleX(), and DynamicDataGraph::setXAxisOffsetScaled().
yValues
int* yValues protected
The values of the graph.
Referenced by GraphScrollData::addValue(), GraphWrapAndClearData::addValue(), GraphWrapAndOverwriteData::addValue(), DynamicDataGraph::indexToDataPointYScaled(), DynamicDataGraph::indexToScreenYQ5(), DynamicDataGraph::setGraphRangeYAutoScaled(), and DynamicDataGraph::setScaleY().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/graph/AbstractDataGraph.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph/AbstractDataGraph.cpp