Battery Simulator Documentation: MJPEGDecoder
MJPEGDecoder abstract
#include "MJPEGDecoder.hpp"
Public Types
enum AVIErrors {
AVI_NO_ERROR , AVI_NO_BUFFERS , AVI_NO_FILE , AVI_ERROR_NOT_RIFF ,
AVI_ERROR_AVI_HEADER_NOT_FOUND , AVI_ERROR_AVI_LIST_NOT_FOUND , AVI_ERROR_AVI_HDRL_NOT_FOUND , AVI_ERROR_AVI_AVIH_NOT_FOUND ,
AVI_ERROR_AVI_HEADER_TO_SHORT , AVI_ERROR_FILE_BUFFER_TO_SMALL , AVI_ERROR_MOVI_NOT_FOUND , AVI_ERROR_IDX1_NOT_FOUND ,
AVI_ERROR_FRAMENO_TO_HIGH , AVI_ERROR_EOF_REACHED , AVI_NO_ERROR , AVI_NO_BUFFERS ,
AVI_NO_FILE , AVI_ERROR_NOT_RIFF , AVI_ERROR_AVI_HEADER_NOT_FOUND , AVI_ERROR_AVI_LIST_NOT_FOUND ,
AVI_ERROR_AVI_HDRL_NOT_FOUND , AVI_ERROR_AVI_AVIH_NOT_FOUND , AVI_ERROR_AVI_HEADER_TO_SHORT , AVI_ERROR_FILE_BUFFER_TO_SMALL ,
AVI_ERROR_MOVI_NOT_FOUND , AVI_ERROR_IDX1_NOT_FOUND , AVI_ERROR_FRAMENO_TO_HIGH , AVI_ERROR_EOF_REACHED
}
enum AVIErrors {
AVI_NO_ERROR , AVI_NO_BUFFERS , AVI_NO_FILE , AVI_ERROR_NOT_RIFF ,
AVI_ERROR_AVI_HEADER_NOT_FOUND , AVI_ERROR_AVI_LIST_NOT_FOUND , AVI_ERROR_AVI_HDRL_NOT_FOUND , AVI_ERROR_AVI_AVIH_NOT_FOUND ,
AVI_ERROR_AVI_HEADER_TO_SHORT , AVI_ERROR_FILE_BUFFER_TO_SMALL , AVI_ERROR_MOVI_NOT_FOUND , AVI_ERROR_IDX1_NOT_FOUND ,
AVI_ERROR_FRAMENO_TO_HIGH , AVI_ERROR_EOF_REACHED , AVI_NO_ERROR , AVI_NO_BUFFERS ,
AVI_NO_FILE , AVI_ERROR_NOT_RIFF , AVI_ERROR_AVI_HEADER_NOT_FOUND , AVI_ERROR_AVI_LIST_NOT_FOUND ,
AVI_ERROR_AVI_HDRL_NOT_FOUND , AVI_ERROR_AVI_AVIH_NOT_FOUND , AVI_ERROR_AVI_HEADER_TO_SHORT , AVI_ERROR_FILE_BUFFER_TO_SMALL ,
AVI_ERROR_MOVI_NOT_FOUND , AVI_ERROR_IDX1_NOT_FOUND , AVI_ERROR_FRAMENO_TO_HIGH , AVI_ERROR_EOF_REACHED
}
Public Member Functions
virtual ~MJPEGDecoder ()
virtual ~MJPEGDecoder ()
virtual bool decodeFrame (const touchgfx::Rect &area, uint8_t *frameBuffer, uint32_t framebufferStride)=0
virtual bool decodeFrame (const touchgfx::Rect &area, uint8_t *frameBuffer, uint32_t framebufferStride)=0
virtual bool decodeNextFrame (uint8_t *buffer, uint16_t width, uint16_t height, uint32_t stride)=0
virtual bool decodeNextFrame (uint8_t *buffer, uint16_t width, uint16_t height, uint32_t stride)=0
virtual bool decodeThumbnail (uint32_t frameno, uint8_t *buffer, uint16_t width, uint16_t height)=0
virtual bool decodeThumbnail (uint32_t frameno, uint8_t *buffer, uint16_t width, uint16_t height)=0
virtual uint32_t getCurrentFrameNumber () const =0
virtual uint32_t getCurrentFrameNumber () const =0
virtual AVIErrors getLastError ()=0
virtual AVIErrors getLastError ()=0
virtual uint32_t getNumberOfFrames ()=0
virtual uint32_t getNumberOfFrames ()=0
virtual void getVideoInfo (touchgfx::VideoInformation *data)=0
virtual void getVideoInfo (touchgfx::VideoInformation *data)=0
virtual void gotoFrame (uint32_t frameno)=0
virtual void gotoFrame (uint32_t frameno)=0
virtual bool gotoNextFrame ()=0
virtual bool gotoNextFrame ()=0
virtual bool hasVideo ()=0
virtual bool hasVideo ()=0
virtual void setVideoData (const uint8_t *movie, const uint32_t length)=0
virtual void setVideoData (const uint8_t *movie, const uint32_t length)=0
virtual void setVideoData (touchgfx::VideoDataReader &reader)=0
virtual void setVideoData (touchgfx::VideoDataReader &reader)=0
Detailed Description
File Name : MJPEGDecoder.hpp
This file is generated by TouchGFX Generator 4.23.1. Please, do not edit!
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Member Enumeration Documentation
AVIErrors [1/2]
enum AVIErrors
Enumerator
AVI_NO_ERROR
AVI_NO_BUFFERS
AVI_NO_FILE
AVI_ERROR_NOT_RIFF
AVI_ERROR_AVI_HEADER_NOT_FOUND
AVI_ERROR_AVI_LIST_NOT_FOUND
AVI_ERROR_AVI_HDRL_NOT_FOUND
AVI_ERROR_AVI_AVIH_NOT_FOUND
AVI_ERROR_AVI_HEADER_TO_SHORT
AVI_ERROR_FILE_BUFFER_TO_SMALL
AVI_ERROR_MOVI_NOT_FOUND
AVI_ERROR_IDX1_NOT_FOUND
AVI_ERROR_FRAMENO_TO_HIGH
AVI_ERROR_EOF_REACHED
AVI_NO_ERROR
AVI_NO_BUFFERS
AVI_NO_FILE
AVI_ERROR_NOT_RIFF
AVI_ERROR_AVI_HEADER_NOT_FOUND
AVI_ERROR_AVI_LIST_NOT_FOUND
AVI_ERROR_AVI_HDRL_NOT_FOUND
AVI_ERROR_AVI_AVIH_NOT_FOUND
AVI_ERROR_AVI_HEADER_TO_SHORT
AVI_ERROR_FILE_BUFFER_TO_SMALL
AVI_ERROR_MOVI_NOT_FOUND
AVI_ERROR_IDX1_NOT_FOUND
AVI_ERROR_FRAMENO_TO_HIGH
AVI_ERROR_EOF_REACHED
    {
        AVI_NO_ERROR,
        AVI_NO_BUFFERS,
        AVI_NO_FILE,
        AVI_ERROR_NOT_RIFF,
        AVI_ERROR_AVI_HEADER_NOT_FOUND,
        AVI_ERROR_AVI_LIST_NOT_FOUND,
        AVI_ERROR_AVI_HDRL_NOT_FOUND,
        AVI_ERROR_AVI_AVIH_NOT_FOUND,
        AVI_ERROR_AVI_HEADER_TO_SHORT, //not full header provided
        AVI_ERROR_FILE_BUFFER_TO_SMALL,
        AVI_ERROR_MOVI_NOT_FOUND,
        AVI_ERROR_IDX1_NOT_FOUND,
        AVI_ERROR_FRAMENO_TO_HIGH,
        AVI_ERROR_EOF_REACHED
    };
AVIErrors [2/2]
enum AVIErrors
Enumerator
AVI_NO_ERROR
AVI_NO_BUFFERS
AVI_NO_FILE
AVI_ERROR_NOT_RIFF
AVI_ERROR_AVI_HEADER_NOT_FOUND
AVI_ERROR_AVI_LIST_NOT_FOUND
AVI_ERROR_AVI_HDRL_NOT_FOUND
AVI_ERROR_AVI_AVIH_NOT_FOUND
AVI_ERROR_AVI_HEADER_TO_SHORT
AVI_ERROR_FILE_BUFFER_TO_SMALL
AVI_ERROR_MOVI_NOT_FOUND
AVI_ERROR_IDX1_NOT_FOUND
AVI_ERROR_FRAMENO_TO_HIGH
AVI_ERROR_EOF_REACHED
AVI_NO_ERROR
AVI_NO_BUFFERS
AVI_NO_FILE
AVI_ERROR_NOT_RIFF
AVI_ERROR_AVI_HEADER_NOT_FOUND
AVI_ERROR_AVI_LIST_NOT_FOUND
AVI_ERROR_AVI_HDRL_NOT_FOUND
AVI_ERROR_AVI_AVIH_NOT_FOUND
AVI_ERROR_AVI_HEADER_TO_SHORT
AVI_ERROR_FILE_BUFFER_TO_SMALL
AVI_ERROR_MOVI_NOT_FOUND
AVI_ERROR_IDX1_NOT_FOUND
AVI_ERROR_FRAMENO_TO_HIGH
AVI_ERROR_EOF_REACHED
    {
        AVI_NO_ERROR,
        AVI_NO_BUFFERS,
        AVI_NO_FILE,
        AVI_ERROR_NOT_RIFF,
        AVI_ERROR_AVI_HEADER_NOT_FOUND,
        AVI_ERROR_AVI_LIST_NOT_FOUND,
        AVI_ERROR_AVI_HDRL_NOT_FOUND,
        AVI_ERROR_AVI_AVIH_NOT_FOUND,
        AVI_ERROR_AVI_HEADER_TO_SHORT, //not full header provided
        AVI_ERROR_FILE_BUFFER_TO_SMALL,
        AVI_ERROR_MOVI_NOT_FOUND,
        AVI_ERROR_IDX1_NOT_FOUND,
        AVI_ERROR_FRAMENO_TO_HIGH,
        AVI_ERROR_EOF_REACHED
    };
Constructor & Destructor Documentation
~MJPEGDecoder() [1/2]
virtual ~MJPEGDecoder () inline virtual
    {
    }
~MJPEGDecoder() [2/2]
virtual ~MJPEGDecoder () inline virtual
    {
    }
Member Function Documentation
decodeFrame() [1/2]
virtual bool decodeFrame (const touchgfx::Rect & area, uint8_t * frameBuffer, uint32_t framebufferStride) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::draw().
decodeFrame() [2/2]
virtual bool decodeFrame (const touchgfx::Rect & area, uint8_t * frameBuffer, uint32_t framebufferStride) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
decodeNextFrame() [1/2]
virtual bool decodeNextFrame (uint8_t * buffer, uint16_t width, uint16_t height, uint32_t stride) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
Referenced by DedicatedBufferController< no_streams, width, height, stride, output_format >::decoderTaskEntry(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::decoderTaskEntry().
decodeNextFrame() [2/2]
virtual bool decodeNextFrame (uint8_t * buffer, uint16_t width, uint16_t height, uint32_t stride) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
decodeThumbnail() [1/2]
virtual bool decodeThumbnail (uint32_t frameno, uint8_t * buffer, uint16_t width, uint16_t height) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
decodeThumbnail() [2/2]
virtual bool decodeThumbnail (uint32_t frameno, uint8_t * buffer, uint16_t width, uint16_t height) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
getCurrentFrameNumber() [1/2]
virtual uint32_t getCurrentFrameNumber () const pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
Referenced by DedicatedBufferController< no_streams, width, height, stride, output_format >::decoderTaskEntry(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::decoderTaskEntry(), DirectFrameBufferVideoController< no_streams, output_format >::setCommand(), DirectFrameBufferVideoController< no_streams, output_format >::setVideoData(), DirectFrameBufferVideoController< no_streams, output_format >::setVideoData(), and DirectFrameBufferVideoController< no_streams, output_format >::updateFrame().
getCurrentFrameNumber() [2/2]
virtual uint32_t getCurrentFrameNumber () const pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
getLastError() [1/2]
virtual AVIErrors getLastError () pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
getLastError() [2/2]
virtual AVIErrors getLastError () pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
getNumberOfFrames() [1/2]
virtual uint32_t getNumberOfFrames () pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::setCommand(), and DirectFrameBufferVideoController< no_streams, output_format >::updateFrame().
getNumberOfFrames() [2/2]
virtual uint32_t getNumberOfFrames () pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
getVideoInfo() [1/2]
virtual void getVideoInfo (touchgfx::VideoInformation * data) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::getVideoInformation(), DedicatedBufferController< no_streams, width, height, stride, output_format >::getVideoInformation(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::getVideoInformation().
getVideoInfo() [2/2]
virtual void getVideoInfo (touchgfx::VideoInformation * data) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
gotoFrame() [1/2]
virtual void gotoFrame (uint32_t frameno) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
Referenced by DedicatedBufferController< no_streams, width, height, stride, output_format >::decoderTaskEntry(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::decoderTaskEntry(), and DirectFrameBufferVideoController< no_streams, output_format >::updateFrame().
gotoFrame() [2/2]
virtual void gotoFrame (uint32_t frameno) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
gotoNextFrame() [1/2]
virtual bool gotoNextFrame () pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::setCommand(), and DirectFrameBufferVideoController< no_streams, output_format >::updateFrame().
gotoNextFrame() [2/2]
virtual bool gotoNextFrame () pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
hasVideo() [1/2]
virtual bool hasVideo () pure virtual
Check if MJPEGDecoder has a video.
Returns
Returns true if the MJPEGDecoder has a video.
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
hasVideo() [2/2]
virtual bool hasVideo () pure virtual
Check if MJPEGDecoder has a video.
Returns
Returns true if the MJPEGDecoder has a video.
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
setVideoData() [1/4]
virtual void setVideoData (const uint8_t * movie, const uint32_t length) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::setVideoData(), DedicatedBufferController< no_streams, width, height, stride, output_format >::setVideoData(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setVideoData(), DirectFrameBufferVideoController< no_streams, output_format >::setVideoData(), DedicatedBufferController< no_streams, width, height, stride, output_format >::setVideoData(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::setVideoData().
setVideoData() [2/4]
virtual void setVideoData (const uint8_t * movie, const uint32_t length) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
setVideoData() [3/4]
virtual void setVideoData (touchgfx::VideoDataReader & reader) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
setVideoData() [4/4]
virtual void setVideoData (touchgfx::VideoDataReader & reader) pure virtual
Implemented in SoftwareMJPEGDecoder, and HardwareMJPEGDecoder.
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/simulator/include/simulator/video/MJPEGDecoder.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/target/generated/MJPEGDecoder.hpp