Battery Simulator Documentation: IconButtonStyle< T >
IconButtonStyle< T >
#include "IconButtonStyle.hpp"
Public Member Functions
IconButtonStyle ()
Bitmap getCurrentlyDisplayedIcon () const
int16_t getIconX () const
int16_t getIconY () const
virtual void setIconBitmaps (const Bitmap &newIconReleased, const Bitmap &newIconPressed)
void setIconX (int16_t x)
void setIconXY (int16_t x, int16_t y)
void setIconY (int16_t y)
Protected Member Functions
virtual void handleAlphaUpdated ()
virtual void handlePressedUpdated ()
Protected Attributes
Image iconImage
The icon image.
Bitmap iconPressed
Icon to display when button is pressed.
Bitmap iconReleased
Icon to display when button is not pressed.
Detailed Description
template<class T>
class touchgfx::IconButtonStyle< T >
An icon button style. This class is supposed to be used with one of the ButtonTrigger classes to create a functional button. This class will show one of two icons depending on the state of the button (pressed or released).
To get a background behind the icon, use IconButtonStyle together with e.g. ImageButtonStyle: IconButtonStyle<ImageButtonStyle<ClickButtonTrigger> > myButton;
The IconButtonStyle will center the icon on the enclosing container (normally AbstractButtonContainer). Set the size of the button before setting the icons.
The position of the icon can be adjusted with setIconXY.
See also
AbstractButtonContainer
Constructor & Destructor Documentation
IconButtonStyle()
template<class T > IconButtonStyle () inline
        : T()
    {
        T::add(iconImage);
    }
References IconButtonStyle< T >::iconImage.
Member Function Documentation
getCurrentlyDisplayedIcon()
template<class T > Bitmap getCurrentlyDisplayedIcon () const inline
Gets currently displayed icon.
Returns
The currently displayed icon.
    {
        return (T::getPressed() ? iconPressed : iconReleased);
    }
References IconButtonStyle< T >::iconPressed, and IconButtonStyle< T >::iconReleased.
getIconX()
template<class T > int16_t getIconX () const inline
Gets icon x coordinate.
Returns
The icon x coordinate.
    {
        return iconImage.getX();
    }
References Drawable::getX(), and IconButtonStyle< T >::iconImage.
getIconY()
template<class T > int16_t getIconY () const inline
Gets icon y coordinate.
Returns
The icon y coordinate.
    {
        return iconImage.getY();
    }
References Drawable::getY(), and IconButtonStyle< T >::iconImage.
handleAlphaUpdated()
template<class T > virtual void handleAlphaUpdated () inline protected virtual
Handles what should happen when the alpha is updated.
    {
        iconImage.setAlpha(T::getAlpha());
        T::handleAlphaUpdated();
    }
References IconButtonStyle< T >::iconImage, and Image::setAlpha().
handlePressedUpdated()
template<class T > virtual void handlePressedUpdated () inline protected virtual
Handles what should happen when the pressed state is updated.
    {
        iconImage.setBitmap(T::getPressed() ? iconPressed : iconReleased);
        T::handlePressedUpdated();
    }
References IconButtonStyle< T >::iconImage, IconButtonStyle< T >::iconPressed, IconButtonStyle< T >::iconReleased, and Image::setBitmap().
Referenced by IconButtonStyle< T >::setIconBitmaps().
setIconBitmaps()
template<class T > virtual void setIconBitmaps (const Bitmap & newIconReleased, const Bitmap & newIconPressed) inline virtual
Sets icon bitmaps.
Parameters
newIconReleased The new icon released.
newIconPressed The new icon pressed.
    {
        iconReleased = newIconReleased;
        iconPressed = newIconPressed;
        iconImage.setXY((T::getWidth() / 2) - (newIconPressed.getWidth() / 2), (T::getHeight() / 2) - (newIconPressed.getHeight() / 2));
        handlePressedUpdated();
    }
References IconButtonStyle< T >::handlePressedUpdated(), IconButtonStyle< T >::iconImage, IconButtonStyle< T >::iconPressed, IconButtonStyle< T >::iconReleased, and Drawable::setXY().
setIconX()
template<class T > void setIconX (int16_t x) inline
Sets icon x coordinate.
Parameters
x The x coordinate.
    {
        iconImage.setX(x);
    }
References IconButtonStyle< T >::iconImage, and Drawable::setX().
Referenced by IconButtonStyle< T >::setIconXY().
setIconXY()
template<class T > void setIconXY (int16_t x, int16_t y) inline
Sets the position of the icon.
Parameters
x The x coordinate.
y The y coordinate.
    {
        setIconX(x);
        setIconY(y);
    }
References IconButtonStyle< T >::setIconX(), and IconButtonStyle< T >::setIconY().
setIconY()
template<class T > void setIconY (int16_t y) inline
Sets icon y coordinate.
Parameters
y The y coordinate.
    {
        iconImage.setY(y);
    }
References IconButtonStyle< T >::iconImage, and Drawable::setY().
Referenced by IconButtonStyle< T >::setIconXY().
Member Data Documentation
iconImage
template<class T > Image iconImage protected
The icon image.
Referenced by IconButtonStyle< T >::IconButtonStyle(), IconButtonStyle< T >::getIconX(), IconButtonStyle< T >::getIconY(), IconButtonStyle< T >::handleAlphaUpdated(), IconButtonStyle< T >::handlePressedUpdated(), IconButtonStyle< T >::setIconBitmaps(), IconButtonStyle< T >::setIconX(), and IconButtonStyle< T >::setIconY().
iconPressed
template<class T > Bitmap iconPressed protected
Icon to display when button is pressed.
Referenced by IconButtonStyle< T >::getCurrentlyDisplayedIcon(), IconButtonStyle< T >::handlePressedUpdated(), and IconButtonStyle< T >::setIconBitmaps().
iconReleased
template<class T > Bitmap iconReleased protected
Icon to display when button is not pressed.
Referenced by IconButtonStyle< T >::getCurrentlyDisplayedIcon(), IconButtonStyle< T >::handlePressedUpdated(), and IconButtonStyle< T >::setIconBitmaps().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/buttons/IconButtonStyle.hpp