Battery Simulator Documentation: Line
Line
#include "Line.hpp"
Public Types
enum LINE_ENDING_STYLE { BUTT_CAP_ENDING , ROUND_CAP_ENDING , SQUARE_CAP_ENDING }
Public Member Functions
Line ()
virtual bool drawCanvasWidget (const Rect &invalidatedArea) const
template<typename T >
void getEnd (T &x, T &y) const
LINE_ENDING_STYLE getLineEndingStyle () const
template<typename T >
T getLineWidth () const
template<typename T >
void getLineWidth (T &width) const
virtual Rect getMinimalRect () const
template<typename T >
void getStart (T &x, T &y) const
virtual void invalidateContent () const
void setCapPrecision (int precision)
void setEnd (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5)
template<typename T >
void setEnd (T x, T y)
template<typename T >
void setLine (T startX, T startY, T endX, T endY)
void setLineEndingStyle (LINE_ENDING_STYLE lineEnding)
void setLineWidth (CWRUtil::Q5 widthQ5)
template<typename T >
void setLineWidth (T width)
void setStart (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5)
template<typename T >
void setStart (T x, T y)
void updateEnd (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5)
template<typename T >
void updateEnd (T x, T y)
void updateLengthAndAngle (CWRUtil::Q5 length, CWRUtil::Q5 angle)
void updateLineWidth (CWRUtil::Q5 widthQ5)
template<typename T >
void updateLineWidth (T width)
void updateStart (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5)
template<typename T >
void updateStart (T x, T y)
Public Member Functions inherited from CanvasWidget
CanvasWidget ()
virtual void draw (const Rect &invalidatedArea) const
virtual uint8_t getAlpha () const
const AbstractPainter * getPainter () const
virtual Rect getSolidRect () const
virtual void invalidate () const
virtual void setAlpha (uint8_t newAlpha)
void setPainter (const AbstractPainter &painter)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Private Member Functions
Rect rectContainingPoints (const Rect &fullRect, CWRUtil::Q5 x0, CWRUtil::Q5 y0, CWRUtil::Q5 x1, CWRUtil::Q5 y1, CWRUtil::Q5 x2, CWRUtil::Q5 y2) const
void updateCachedShape ()
Private Attributes
CWRUtil::Q5 cornerXQ5 [4]
CWRUtil::Q5 cornerYQ5 [4]
CWRUtil::Q5 endXQ5
CWRUtil::Q5 endYQ5
int lineCapArcIncrement
LINE_ENDING_STYLE lineEnding
CWRUtil::Q5 lineWidthQ5
Rect minimalRect
CWRUtil::Q5 startXQ5
CWRUtil::Q5 startYQ5
Additional Inherited Members
Protected Attributes inherited from CanvasWidget
uint8_t alpha
The Alpha for this CanvasWidget.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
Simple CanvasWidget capable of drawing a line from one point to another point. The end points can be moved to new locations and the line width can be set and changed. A 10 pixel long line along the top of the screen with a width on 1 pixel has endpoints in (0, 0.5) and (10, 0.5) and line width 1. The Line class calculates the corners of the shape, which in this case would be (0, 0), (10, 0), (10, 1) and (0, 1) and tells CanvasWidgetRenderer to moveTo() the first coordinate and then lineTo() the next coordinates in order. Finally it tells CWR to render the inside of the shape using the set Painter object.
The Line class caches the four corners of the shape to speed up redrawing. In general, drawing lines involve some extra mathematics for calculating the normal vector of the line and this computation would slow down re-draws if not cached.
Note
All coordinates are internally handled as CWRUtil::Q5 which means that floating point values are rounded down to a fixed number of binary digits, for example:
Line line;
line.setStart(1.1f, 1.1f); // Will use (35/32, 35/32) = (1.09375f, 1.09375f)
int x, y;
line.getStart(&x, &y); // Will return (1, 1)
.
Member Enumeration Documentation
LINE_ENDING_STYLE
enum LINE_ENDING_STYLE
Values that represent line ending styles.
Enumerator
BUTT_CAP_ENDING
The line ending is cut 90 degrees at the end of the line.
ROUND_CAP_ENDING
The line ending is rounded as a circle with center at the end of the line.
SQUARE_CAP_ENDING
The line ending is cut 90 degrees, but extends half the width of the line.
    {
        BUTT_CAP_ENDING,
        ROUND_CAP_ENDING,
        SQUARE_CAP_ENDING
    };
Constructor & Destructor Documentation
Line()
Line ()
    : CanvasWidget(),
      startXQ5(0), startYQ5(0), endXQ5(0), endYQ5(0),
      lineWidthQ5(CWRUtil::toQ5<int>(1)),
      lineEnding(BUTT_CAP_ENDING),
      minimalRect(),
      lineCapArcIncrement(18)
{
    Drawable::setWidthHeight(0, 0);
}
References Drawable::setWidthHeight().
Member Function Documentation
drawCanvasWidget()
bool drawCanvasWidget (const Rect & invalidatedArea) const virtual
Draw canvas widget for the given invalidated area. Similar to draw(), but might be invoked several times with increasingly smaller areas to due to memory constraints from the underlying CanvasWidgetRenderer.
Parameters
invalidatedArea The invalidated area.
Returns
true if the widget was drawn properly, false if not.
See also
draw
Implements CanvasWidget.
{
    Canvas canvas(getPainter(), getAbsoluteRect(), invalidatedArea, getAlpha());
    CWRUtil::Q5 radiusQ5;
    if (lineEnding == ROUND_CAP_ENDING)
    {
        const int angleInDegrees = CWRUtil::angle(cornerXQ5[0] - startXQ5, cornerYQ5[0] - startYQ5, radiusQ5);
        canvas.moveTo(cornerXQ5[0], cornerYQ5[0]);
        canvas.lineTo(cornerXQ5[1], cornerYQ5[1]);
        for (int i = lineCapArcIncrement; i < 180; i += lineCapArcIncrement)
        {
            canvas.lineTo(endXQ5 + radiusQ5 * CWRUtil::sine(angleInDegrees - i), endYQ5 - radiusQ5 * CWRUtil::cosine(angleInDegrees - i));
        }
        canvas.lineTo(cornerXQ5[2], cornerYQ5[2]);
        canvas.lineTo(cornerXQ5[3], cornerYQ5[3]);
        for (int i = 180 - lineCapArcIncrement; i > 0; i -= lineCapArcIncrement)
        {
            canvas.lineTo(startXQ5 + radiusQ5 * CWRUtil::sine(angleInDegrees + i), startYQ5 - radiusQ5 * CWRUtil::cosine(angleInDegrees + i));
        }
    }
    else
    {
        canvas.moveTo(cornerXQ5[0], cornerYQ5[0]);
        canvas.lineTo(cornerXQ5[1], cornerYQ5[1]);
        canvas.lineTo(cornerXQ5[2], cornerYQ5[2]);
        canvas.lineTo(cornerXQ5[3], cornerYQ5[3]);
    }
    return canvas.render();
}
References CWRUtil::angle(), Line::cornerXQ5, Line::cornerYQ5, CWRUtil::cosine(), Line::endXQ5, Line::endYQ5, Drawable::getAbsoluteRect(), CanvasWidget::getAlpha(), CanvasWidget::getPainter(), Line::lineCapArcIncrement, Line::lineEnding, Line::ROUND_CAP_ENDING, CWRUtil::sine(), Line::startXQ5, and Line::startYQ5.
getEnd()
template<typename T > void getEnd (T & x, T & y) const inline
Gets the endpoint coordinates for the line.
Template Parameters
T Generic type parameter, either int or float.
Parameters
[out] x The x coordinate rounded down to the precision of T.
[out] y The y coordinate rounded down to the precision of T.
See also
setEnd, updateEnd
    {
        x = endXQ5.to<T>();
        y = endYQ5.to<T>();
    }
References Line::endXQ5, Line::endYQ5, and CWRUtil::Q5::to().
getLineEndingStyle()
Line::LINE_ENDING_STYLE getLineEndingStyle () const
Gets line ending style.
Returns
The line ending style.
See also
LINE_ENDING_STYLE, setLineEndingStyle
{
    return lineEnding;
}
References Line::lineEnding.
Referenced by LineProgress::getLineEndingStyle().
getLineWidth() [1/2]
template<typename T > T getLineWidth () const inline
Gets line width.
Template Parameters
T Generic type parameter, either int or float.
Returns
The line width rounded down to the precision of T.
See also
setLineWidth
    {
        return lineWidthQ5.to<T>();
    }
References Line::lineWidthQ5, and CWRUtil::Q5::to().
getLineWidth() [2/2]
template<typename T > void getLineWidth (T & width) const inline
Gets line width.
Template Parameters
T Generic type parameter, either int or float.
Parameters
[out] width The line width rounded down to the precision of T.
See also
setLineWidth
    {
        width = lineWidthQ5.to<T>();
    }
References Line::lineWidthQ5, and CWRUtil::Q5::to().
Referenced by LineProgress::getLineWidth().
getMinimalRect()
Rect getMinimalRect () const virtual
Gets minimal rectangle containing the shape drawn by this widget. Default implementation returns the size of the entire widget, but this function should be overwritten in subclasses and return the minimal rectangle containing the shape. See classes such as Circle for example implementations.
Returns
The minimal rectangle containing the shape drawn.
Reimplemented from CanvasWidget.
{
    return minimalRect;
}
References Line::minimalRect.
Referenced by Line::invalidateContent(), and Line::updateLineWidth().
getStart()
template<typename T > void getStart (T & x, T & y) const inline
Gets the starting point of the line as either integers or floats.
Template Parameters
T Generic type parameter, either int or float.
Parameters
[out] x The x coordinate rounded down to the precision of T.
[out] y The y coordinate rounded down to the precision of T.
See also
setStart, setLine
    {
        x = startXQ5.to<T>();
        y = startYQ5.to<T>();
    }
References Line::startXQ5, Line::startYQ5, and CWRUtil::Q5::to().
invalidateContent()
void invalidateContent () const virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from Drawable.
{
    if (alpha == 0)
    {
        return;
    }
    Rect smallRect = getMinimalRect();
    if (abs(startXQ5.to<int>() - endXQ5.to<int>()) < lineWidthQ5.to<int>() * 2 ||
        abs(startYQ5.to<int>() - endYQ5.to<int>()) < lineWidthQ5.to<int>() * 2)
    {
        invalidateRect(smallRect);
        return;
    }
    const int16_t center_x = ((startXQ5 + endXQ5) / 2).to<int16_t>();
    const int16_t center_y = ((startYQ5 + endYQ5) / 2).to<int16_t>();
    // The following should be "lineWidth/sqrt(2)" but to speed up we take the slightly larger "lineWidth/1.3333"="(lineWidth*3)/4"
    const int16_t extra_width = ((CWRUtil::Q5)(((int)(lineWidthQ5)*3 + 3) >> 2)).ceil();
#define same_sign(x, y) (((x) < 0 && (y) < 0) || ((x) > 0 && (y) > 0))
    if (smallRect.width < smallRect.height)
    {
        const int16_t left_x = center_x - extra_width;
        const int16_t right_x = center_x + extra_width;
        // "vertical" line
        if (same_sign(endXQ5 - startXQ5, endYQ5 - startYQ5))
        {
            // From top-left to bottom-right
            Rect topLeftRect(smallRect.x, smallRect.y, right_x - smallRect.x, center_y - smallRect.y);
            Rect bottomRightRect(left_x, center_y, smallRect.right() - left_x, smallRect.bottom() - center_y);
            invalidateRect(topLeftRect);
            invalidateRect(bottomRightRect);
        }
        else
        {
            // From top-right to bottom-left
            Rect topRightRect(left_x, smallRect.y, smallRect.right() - left_x, center_y - smallRect.y);
            Rect bottomLeftRect(smallRect.x, center_y, right_x - smallRect.x, smallRect.bottom() - center_y);
            invalidateRect(topRightRect);
            invalidateRect(bottomLeftRect);
        }
    }
    else
    {
        const int16_t top_y = center_y - extra_width;
        const int16_t bottom_y = center_y + extra_width;
        // "horizontal" line
        if (same_sign(endXQ5 - startXQ5, endYQ5 - startYQ5))
        {
            // From top-left to bottom-right
            Rect topLeftRect(smallRect.x, smallRect.y, center_x - smallRect.x, bottom_y - smallRect.y);
            Rect bottomRightRect(center_x, top_y, smallRect.right() - center_x, smallRect.bottom() - top_y);
            invalidateRect(topLeftRect);
            invalidateRect(bottomRightRect);
        }
        else
        {
            // From top-right to bottom-left
            Rect bottomLeftRect(smallRect.x, top_y, center_x - smallRect.x, smallRect.bottom() - top_y);
            Rect topRightRect(center_x, smallRect.y, smallRect.right() - center_x, bottom_y - smallRect.y);
            invalidateRect(bottomLeftRect);
            invalidateRect(topRightRect);
        }
    }
#undef same_sign
}
References touchgfx::abs(), Line::endXQ5, Line::endYQ5, Line::getMinimalRect(), Drawable::invalidateRect(), Line::lineWidthQ5, same_sign, Line::startXQ5, Line::startYQ5, and CWRUtil::Q5::to().
Referenced by Line::updateEnd(), and Line::updateStart().
rectContainingPoints()
touchgfx::Rect rectContainingPoints (const Rect & fullRect, CWRUtil::Q5 x0, CWRUtil::Q5 y0, CWRUtil::Q5 x1, CWRUtil::Q5 y1, CWRUtil::Q5 x2, CWRUtil::Q5 y2) const private
{
    const int16_t xMin = MIN(MIN(x0, x1), x2).floor();
    const int16_t yMin = MIN(MIN(y0, y1), y2).floor();
    const int16_t xMax = MAX(MAX(x0, x1), x2).ceil();
    const int16_t yMax = MAX(MAX(y0, y1), y2).ceil();
    Rect r(xMin, yMin, xMax - xMin, yMax - yMin);
    r &= fullRect;
    return r;
}
References MAX, and MIN.
setCapPrecision()
void setCapPrecision (int precision)
Sets a precision of the arc at the ends of the Line. This only works for ROUND_CAP_ENDING. The precision is given in degrees where 18 is the default which results in a nice half circle with 10 line segments. 90 will draw "an arrow head", 180 will look exactly like a BUTT_CAP_ENDING.
Parameters
precision The new ROUND_CAP_ENDING precision.
Note
The line is not invalidated.
This is only used if line ending is set to ROUND_CAP_ENDING.
{
    if (precision < 1)
    {
        precision = 1;
    }
    if (precision > 180)
    {
        precision = 180;
    }
    lineCapArcIncrement = precision;
}
References Line::lineCapArcIncrement.
setEnd() [1/2]
void setEnd (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5)
Sets the endpoint coordinates of the line.
Parameters
xQ5 The x coordinate of the end point in Q5 format.
yQ5 The y coordinate of the end point in Q5 format.
See also
updateEnd, getEnd
Note
The area containing the Line is not invalidated.
{
    if (endXQ5 == xQ5 && endYQ5 == yQ5)
    {
        return;
    }
    endXQ5 = xQ5;
    endYQ5 = yQ5;
    updateCachedShape();
}
References Line::endXQ5, Line::endYQ5, and Line::updateCachedShape().
setEnd() [2/2]
template<typename T > void setEnd (T x, T y) inline
Sets the endpoint coordinates of the line.
Template Parameters
T Generic type parameter, either int or float.
Parameters
x The x coordinate of the end point.
y The y coordinate of the end point.
See also
updateEnd, getEnd
Note
The area containing the Line is not invalidated.
    {
        setEnd(CWRUtil::toQ5<T>(x), CWRUtil::toQ5<T>(y));
    }
References Line::setEnd().
Referenced by Line::setEnd(), and Line::setLine().
setLine()
template<typename T > void setLine (T startX, T startY, T endX, T endY) inline
Sets the starting point and ending point of the line.
Template Parameters
T Generic type parameter, either int or float.
Parameters
startX The x coordinate of the start point.
startY The y coordinate of the start point.
endX The x coordinate of the end point.
endY The y coordinate of the end point.
See also
setStart, setEnd
Note
The area containing the Line is not invalidated.
    {
        setStart(startX, startY);
        setEnd(endX, endY);
    }
References Line::setEnd(), and Line::setStart().
setLineEndingStyle()
void setLineEndingStyle (Line::LINE_ENDING_STYLE lineEndingStyle)
Sets line ending style. The same style is applied to both ends of the line.
Parameters
lineEnding The line ending style.
See also
LINE_ENDING_STYLE, getLineEndingStyle
Note
The area containing the Line is not invalidated.
{
    lineEnding = lineEndingStyle;
    updateCachedShape();
}
References Line::lineEnding, and Line::updateCachedShape().
Referenced by LineProgress::setLineEndingStyle().
setLineWidth() [1/2]
void setLineWidth (CWRUtil::Q5 widthQ5) inline
Sets the width for this Line.
Parameters
widthQ5 The width of the line measured in pixels in Q5 format.
See also
updateLineWidth
Note
The area containing the Line is not invalidated.
    {
        if (lineWidthQ5 == widthQ5)
        {
            return;
        }
        lineWidthQ5 = widthQ5;
        updateCachedShape();
    }
References Line::lineWidthQ5, and Line::updateCachedShape().
setLineWidth() [2/2]
template<typename T > void setLineWidth (T width) inline
Sets the width for this Line.
Template Parameters
T Generic type parameter, either int or float.
Parameters
width The width of the line measured in pixels.
See also
updateLineWidth
Note
The area containing the Line is not invalidated.
    {
        setLineWidth(CWRUtil::toQ5<T>(width));
    }
References Line::setLineWidth().
Referenced by LineProgress::setLineWidth(), and Line::setLineWidth().
setStart() [1/2]
void setStart (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5)
Sets the starting point of the line.
Parameters
xQ5 The x coordinate of the start point in Q5 format.
yQ5 The y coordinate of the start point in Q5 format.
See also
updateStart, getStart, setLine, setEnd
Note
The area containing the Line is not invalidated.
{
    if (startXQ5 == xQ5 && startYQ5 == yQ5)
    {
        return;
    }
    startXQ5 = xQ5;
    startYQ5 = yQ5;
    updateCachedShape();
}
References Line::startXQ5, Line::startYQ5, and Line::updateCachedShape().
setStart() [2/2]
template<typename T > void setStart (T x, T y) inline
Sets the starting point of the line.
Template Parameters
T Generic type parameter, either int or float.
Parameters
x The x coordinate of the start point.
y The y coordinate of the start point.
See also
updateStart, getStart, setLine, setEnd
Note
The area containing the Line is not invalidated.
    {
        setStart(CWRUtil::toQ5<T>(x), CWRUtil::toQ5<T>(y));
    }
References Line::setStart().
Referenced by Line::setLine(), LineProgress::setStart(), and Line::setStart().
updateCachedShape()
void updateCachedShape () private
{
    CWRUtil::Q5 dxQ5 = endXQ5 - startXQ5;
    CWRUtil::Q5 dyQ5 = endYQ5 - startYQ5;
    CWRUtil::Q5 dQ5 = CWRUtil::toQ5<int>(0);
    // Look for horizontal, vertical or no-line
    if (dxQ5 == 0)
    {
        if (dyQ5 == 0)
        {
            cornerXQ5[0] = cornerXQ5[1] = cornerXQ5[2] = cornerXQ5[3] = startXQ5;
            cornerYQ5[0] = cornerYQ5[1] = cornerYQ5[2] = cornerYQ5[3] = startYQ5;
            return;
        }
        dQ5 = abs(dyQ5);
    }
    else if (dyQ5 == 0)
    {
        dQ5 = abs(dxQ5);
    }
    else
    {
        // We want to hit as close to the limit inside 32bits.
        // sqrt(0x7FFFFFFF / 2) = 46340, which is roughly toQ5(1448)
        static const int32_t MAXVAL = 46340;
        const int32_t common_divisor = gcd(abs((int32_t)dxQ5), abs((int32_t)dyQ5));
        // First try to scale down
        if (common_divisor != 1)
        {
            dxQ5 = CWRUtil::Q5((int32_t)dxQ5 / common_divisor);
            dyQ5 = CWRUtil::Q5((int32_t)dyQ5 / common_divisor);
        }
        // Neither dx or dy is zero, find the largest multiplier / smallest divisor to stay within limit
        if (abs((int32_t)dxQ5) <= MAXVAL || abs((int32_t)dyQ5) <= MAXVAL)
        {
            // Look for largest multiplier
            const int32_t mulx = MAXVAL / abs((int32_t)dxQ5);
            const int32_t muly = MAXVAL / abs((int32_t)dyQ5);
            const int32_t mult = MIN(mulx, muly);
            dxQ5 = CWRUtil::Q5(mult * (int32_t)dxQ5);
            dyQ5 = CWRUtil::Q5(mult * (int32_t)dyQ5);
        }
        else
        {
            // Look for smallest divisor
            const int32_t divx = abs((int32_t)dxQ5) / MAXVAL;
            const int32_t divy = abs((int32_t)dyQ5) / MAXVAL;
            const int32_t divi = MAX(divx, divy) + 1;
            dxQ5 = CWRUtil::Q5((int32_t)dxQ5 / divi);
            dyQ5 = CWRUtil::Q5((int32_t)dyQ5 / divi);
        }
        dQ5 = CWRUtil::length(dxQ5, dyQ5);
    }
    dyQ5 = CWRUtil::muldivQ5(lineWidthQ5, dyQ5, dQ5) / 2;
    dxQ5 = CWRUtil::muldivQ5(lineWidthQ5, dxQ5, dQ5) / 2;
    switch (lineEnding)
    {
    case BUTT_CAP_ENDING:
        cornerXQ5[0] = startXQ5 - dyQ5;
        cornerYQ5[0] = startYQ5 + dxQ5;
        cornerXQ5[1] = endXQ5 - dyQ5;
        cornerYQ5[1] = endYQ5 + dxQ5;
        cornerXQ5[2] = endXQ5 + dyQ5;
        cornerYQ5[2] = endYQ5 - dxQ5;
        cornerXQ5[3] = startXQ5 + dyQ5;
        cornerYQ5[3] = startYQ5 - dxQ5;
        break;
    case ROUND_CAP_ENDING:
        // Nothing cached, calculated on each draw, but extremes are same as SQUARE_CAP_ENDING, so
        // Fall Through (for calculations)
    case SQUARE_CAP_ENDING:
        cornerXQ5[0] = (startXQ5 - dyQ5) - dxQ5;
        cornerYQ5[0] = (startYQ5 + dxQ5) - dyQ5;
        cornerXQ5[1] = (endXQ5 - dyQ5) + dxQ5;
        cornerYQ5[1] = (endYQ5 + dxQ5) + dyQ5;
        cornerXQ5[2] = (endXQ5 + dyQ5) + dxQ5;
        cornerYQ5[2] = (endYQ5 - dxQ5) + dyQ5;
        cornerXQ5[3] = (startXQ5 + dyQ5) - dxQ5;
        cornerYQ5[3] = (startYQ5 - dxQ5) - dyQ5;
        break;
    }
    CWRUtil::Q5 xMinQ5 = cornerXQ5[0];
    CWRUtil::Q5 xMaxQ5 = cornerXQ5[0];
    CWRUtil::Q5 yMinQ5 = cornerYQ5[0];
    CWRUtil::Q5 yMaxQ5 = cornerYQ5[0];
    for (int i = 1; i < 4; i++)
    {
        if (cornerXQ5[i] < xMinQ5)
        {
            xMinQ5 = cornerXQ5[i];
        }
        if (cornerXQ5[i] > xMaxQ5)
        {
            xMaxQ5 = cornerXQ5[i];
        }
        if (cornerYQ5[i] < yMinQ5)
        {
            yMinQ5 = cornerYQ5[i];
        }
        if (cornerYQ5[i] > yMaxQ5)
        {
            yMaxQ5 = cornerYQ5[i];
        }
    }
    const int16_t xMin = xMinQ5.floor();
    const int16_t yMin = yMinQ5.floor();
    const int16_t xMax = xMaxQ5.ceil();
    const int16_t yMax = yMaxQ5.ceil();
    minimalRect = Rect(xMin, yMin, xMax - xMin, yMax - yMin);
    if (lineEnding == ROUND_CAP_ENDING)
    {
        cornerXQ5[0] = startXQ5 - dyQ5;
        cornerYQ5[0] = startYQ5 + dxQ5;
        cornerXQ5[1] = endXQ5 - dyQ5;
        cornerYQ5[1] = endYQ5 + dxQ5;
        cornerXQ5[2] = endXQ5 + dyQ5;
        cornerYQ5[2] = endYQ5 - dxQ5;
        cornerXQ5[3] = startXQ5 + dyQ5;
        cornerYQ5[3] = startYQ5 - dxQ5;
    }
}
References touchgfx::abs(), Line::BUTT_CAP_ENDING, Line::cornerXQ5, Line::cornerYQ5, Line::endXQ5, Line::endYQ5, touchgfx::gcd(), CWRUtil::length(), Line::lineEnding, Line::lineWidthQ5, MAX, MIN, Line::minimalRect, CWRUtil::muldivQ5(), Line::ROUND_CAP_ENDING, Line::SQUARE_CAP_ENDING, Line::startXQ5, and Line::startYQ5.
Referenced by Line::setEnd(), Line::setLineEndingStyle(), Line::setLineWidth(), Line::setStart(), Line::updateEnd(), Line::updateLineWidth(), and Line::updateStart().
updateEnd() [1/2]
void updateEnd (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5)
Update the endpoint for this Line. The rectangle that surrounds the line before and after will be invalidated.
Parameters
xQ5 The x coordinate of the end point in Q5 format.
yQ5 The y coordinate of the end point in Q5 format.
See also
setEnd, updateStart
Note
The area containing the Line is invalidated before and after the change.
{
    if (endXQ5 == xQ5 && endYQ5 == yQ5)
    {
        return;
    }
    invalidateContent();
    endXQ5 = xQ5;
    endYQ5 = yQ5;
    updateCachedShape();
    invalidateContent();
}
References Line::endXQ5, Line::endYQ5, Line::invalidateContent(), and Line::updateCachedShape().
updateEnd() [2/2]
template<typename T > void updateEnd (T x, T y) inline
Update the endpoint for this Line. The rectangle that surrounds the line before and after will be invalidated.
Template Parameters
T Generic type parameter, either int or float.
Parameters
x The x coordinate of the end point.
y The y coordinate of the end point.
See also
setEnd, updateStart
Note
The area containing the Line is invalidated before and after the change.
    {
        CWRUtil::Q5 xQ5 = CWRUtil::toQ5<T>(x);
        CWRUtil::Q5 yQ5 = CWRUtil::toQ5<T>(y);
        updateEnd(xQ5, yQ5);
    }
References Line::updateEnd().
Referenced by LineProgress::setValue(), Line::updateEnd(), and Line::updateLengthAndAngle().
updateLengthAndAngle()
void updateLengthAndAngle (CWRUtil::Q5 length, CWRUtil::Q5 angle)
Update the end point for this Line given the new length and angle in degrees. The rectangle that surrounds the line before and after will be invalidated. The starting coordinates will be fixed but the ending point will be updated. This is simply a different way to update the ending point.
Parameters
length The new length of the line in Q5 format.
angle The new angle of the line in Q5 format.
See also
updateEnd
Note
The area containing the Line is invalidated before and after the change.
Angles are given in degrees, so a full circle is 360.
{
    updateEnd(startXQ5 + length * CWRUtil::sine(angle), startYQ5 - length * CWRUtil::cosine(angle));
}
References CWRUtil::cosine(), CWRUtil::sine(), Line::startXQ5, Line::startYQ5, and Line::updateEnd().
updateLineWidth() [1/2]
void updateLineWidth (CWRUtil::Q5 widthQ5) inline
Update the width for this Line.
Update the width for this Line and invalidates the minimal rectangle surrounding the line on screen.
Parameters
widthQ5 The width of the line measured in pixels in Q5 format.
See also
setLineWidth
Note
The area containing the Line is invalidated before and after the change.
    {
        if (lineWidthQ5 == widthQ5)
        {
            return;
        }
        Rect rectBefore = getMinimalRect();
        invalidateRect(rectBefore);
        lineWidthQ5 = widthQ5;
        updateCachedShape();
        Rect rectAfter = getMinimalRect();
        invalidateRect(rectAfter);
    }
References Line::getMinimalRect(), Drawable::invalidateRect(), Line::lineWidthQ5, and Line::updateCachedShape().
updateLineWidth() [2/2]
template<typename T > void updateLineWidth (T width) inline
Update the width for this Line and invalidates the minimal rectangle surrounding the line on screen.
Template Parameters
T Generic type parameter, either int or float.
Parameters
width The width of the line measured in pixels.
See also
setLineWidth
Note
The area containing the Line is invalidated before and after the change.
    {
        updateLineWidth(CWRUtil::toQ5<T>(width));
    }
References Line::updateLineWidth().
Referenced by Line::updateLineWidth().
updateStart() [1/2]
void updateStart (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5)
Update the start point for this Line. The rectangle that surrounds the line before and after will be invalidated.
Parameters
xQ5 The x coordinate of the start point in CWRUtil::Q5 format.
yQ5 The y coordinate of the start point in CWRUtil::Q5 format.
See also
setStart, updateEnd
Note
The area containing the Line is invalidated before and after the change.
{
    if (startXQ5 == xQ5 && startYQ5 == yQ5)
    {
        return;
    }
    invalidateContent();
    startXQ5 = xQ5;
    startYQ5 = yQ5;
    updateCachedShape();
    invalidateContent();
}
References Line::invalidateContent(), Line::startXQ5, Line::startYQ5, and Line::updateCachedShape().
updateStart() [2/2]
template<typename T > void updateStart (T x, T y) inline
Update the start point for this Line. The rectangle that surrounds the line before and after will be invalidated.
Template Parameters
T Generic type parameter, either int or float.
Parameters
x The x coordinate of the start point.
y The y coordinate of the start point.
See also
setStart, updateEnd
Note
The area containing the Line is invalidated before and after the change.
    {
        updateStart(CWRUtil::toQ5<T>(x), CWRUtil::toQ5<T>(y));
    }
References Line::updateStart().
Referenced by Line::updateStart().
Member Data Documentation
cornerXQ5
CWRUtil::Q5 cornerXQ5[4] private
Referenced by Line::drawCanvasWidget(), and Line::updateCachedShape().
cornerYQ5
CWRUtil::Q5 cornerYQ5[4] private
Referenced by Line::drawCanvasWidget(), and Line::updateCachedShape().
endXQ5
CWRUtil::Q5 endXQ5 private
Referenced by Line::drawCanvasWidget(), Line::getEnd(), Line::invalidateContent(), Line::setEnd(), Line::updateCachedShape(), and Line::updateEnd().
endYQ5
CWRUtil::Q5 endYQ5 private
Referenced by Line::drawCanvasWidget(), Line::getEnd(), Line::invalidateContent(), Line::setEnd(), Line::updateCachedShape(), and Line::updateEnd().
lineCapArcIncrement
int lineCapArcIncrement private
Referenced by Line::drawCanvasWidget(), and Line::setCapPrecision().
lineEnding
LINE_ENDING_STYLE lineEnding private
Referenced by Line::drawCanvasWidget(), Line::getLineEndingStyle(), Line::setLineEndingStyle(), and Line::updateCachedShape().
lineWidthQ5
CWRUtil::Q5 lineWidthQ5 private
Referenced by Line::getLineWidth(), Line::getLineWidth(), Line::invalidateContent(), Line::setLineWidth(), Line::updateCachedShape(), and Line::updateLineWidth().
minimalRect
Rect minimalRect private
Referenced by Line::getMinimalRect(), and Line::updateCachedShape().
startXQ5
CWRUtil::Q5 startXQ5 private
Referenced by Line::drawCanvasWidget(), Line::getStart(), Line::invalidateContent(), Line::setStart(), Line::updateCachedShape(), Line::updateLengthAndAngle(), and Line::updateStart().
startYQ5
CWRUtil::Q5 startYQ5 private
Referenced by Line::drawCanvasWidget(), Line::getStart(), Line::invalidateContent(), Line::setStart(), Line::updateCachedShape(), Line::updateLengthAndAngle(), and Line::updateStart().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/Line.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/Line.cpp