Battery Simulator Documentation: GraphElementGridBase
GraphElementGridBase abstract
#include "GraphElements.hpp"
Public Member Functions
GraphElementGridBase ()
virtual void draw (const Rect &invalidatedArea) const
virtual int getCorrectlyScaledGridInterval (const AbstractDataGraph *graph) const =0
virtual int getCorrectlyScaledMajorInterval (const AbstractDataGraph *graph) const
FORCE_INLINE_FUNCTION float getIntervalAsFloat () const
FORCE_INLINE_FUNCTION int getIntervalAsInt () const
FORCE_INLINE_FUNCTION int getIntervalScaled () const
FORCE_INLINE_FUNCTION uint8_t getLineWidth () const
FORCE_INLINE_FUNCTION int getScale () const
virtual void invalidateGraphPointAt (int16_t)
FORCE_INLINE_FUNCTION void setInterval (float interval)
FORCE_INLINE_FUNCTION void setInterval (int interval)
FORCE_INLINE_FUNCTION void setIntervalScaled (int interval)
FORCE_INLINE_FUNCTION void setLineWidth (uint8_t width)
FORCE_INLINE_FUNCTION void setMajorGrid (const GraphElementGridBase &major)
FORCE_INLINE_FUNCTION void setScale (int scale)
Public Member Functions inherited from AbstractGraphElementNoCWR
AbstractGraphElementNoCWR ()
virtual bool drawCanvasWidget (const Rect &) const
virtual colortype getColor () const
virtual void setColor (colortype newColor)
Public Member Functions inherited from AbstractGraphElement
AbstractGraphElement ()
Public Member Functions inherited from CanvasWidget
CanvasWidget ()
virtual uint8_t getAlpha () const
virtual Rect getMinimalRect () const
const AbstractPainter * getPainter () const
virtual Rect getSolidRect () const
virtual void invalidate () const
virtual void setAlpha (uint8_t newAlpha)
void setPainter (const AbstractPainter &painter)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual void drawLine (const Rect &invalidatedArea, int16_t start, int16_t length, int16_t pos, int16_t width, uint8_t a) const
virtual Rect enclosingArea (const AbstractDataGraph *graph) const =0
virtual int getGraphAreaEndPos (const AbstractDataGraph *graph) const =0
virtual int getGraphAreaLength (const AbstractDataGraph *graph) const =0
virtual int getGraphAreaStart (const AbstractDataGraph *graph) const =0
virtual int getGraphAreaStartPos (const AbstractDataGraph *graph) const =0
virtual int getGraphRangeMaxScaled (const AbstractDataGraph *graph) const =0
virtual int getGraphRangeMinScaled (const AbstractDataGraph *graph) const =0
virtual Rect lineRect (int16_t start, int16_t length, int16_t pos, int16_t width) const =0
virtual CWRUtil::Q5 valueToScreenQ5 (const AbstractDataGraph *graph, int value) const =0
Protected Member Functions inherited from AbstractGraphElementNoCWR
void normalizeRect (Rect &r) const
Protected Member Functions inherited from AbstractGraphElement
FORCE_INLINE_FUNCTION int convertToGraphScaleX (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION int convertToGraphScaleY (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION AbstractDataGraph * getGraph () const
FORCE_INLINE_FUNCTION int getIndexToXAxis (const AbstractDataGraph *graph, const int valueScaled, const int labelScaled) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenXQ5 (const AbstractDataGraph *graph, int16_t index) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenYQ5 (const AbstractDataGraph *graph, int16_t index) const
bool isCenterInvisible (const AbstractDataGraph *graph, int16_t index) const
Rect rectAround (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5, CWRUtil::Q5 diameterQ5) const
Rect rectFromQ5Coordinates (CWRUtil::Q5 screenXminQ5, CWRUtil::Q5 screenYminQ5, CWRUtil::Q5 screenXmaxQ5, CWRUtil::Q5 screenYmaxQ5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 roundQ5 (CWRUtil::Q5 q5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenXQ5 (const AbstractDataGraph *graph, int x) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenYQ5 (const AbstractDataGraph *graph, int y) const
FORCE_INLINE_FUNCTION bool xScreenRangeToIndexRange (const AbstractDataGraph *graph, int16_t xMin, int16_t xMax, int16_t &indexMin, int16_t &indexMax) const
Protected Attributes
int dataScale
The scaling factor.
int gridInterval
The grid line interval.
uint8_t lineWidth
Width of the line.
const GraphElementGridBase * majorGrid
A pointer to a major grid, if any.
Protected Attributes inherited from AbstractGraphElementNoCWR
colortype color
The currently assigned color.
Protected Attributes inherited from CanvasWidget
uint8_t alpha
The Alpha for this CanvasWidget.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
GraphElementGridBase is a helper class used to implement classed to draw grid lines in the graph.
Constructor & Destructor Documentation
GraphElementGridBase()
GraphElementGridBase () inline
Default constructor.
        : dataScale(1), gridInterval(10), lineWidth(1), majorGrid(0)
    {
    }
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draws the given invalidated area. If the underlying CanvasWidgetRenderer fail to render the widget (if the widget is too complex), the invalidated area is cut into smaller slices (horizontally) which are then drawn separately. If drawing a single raster line fails, that line is considered too complex and skipped (it is left blank/transparent) and drawing continues on the next raster line.
If drawing has failed at least once, which means that the number of horizontal lines draw has been reduced, the number of successfully drawn horizontal lines is remembered for the next invocation of draw(). A future call to draw() would then start off with the reduced number of horizontal lines to prevent potentially drawing the canvas widget in vain, as happened previously in draw().
Parameters
invalidatedArea The invalidated area.
See also
drawCanvasWidget
Note
Subclasses of CanvasWidget should implement drawCanvasWidget(), not draw().
The term "too complex" means that the size of the buffer (assigned to CanvasWidgetRenderer using CanvasWidgetRenderer::setupBuffer()) is too small.
Reimplemented from CanvasWidget.
{
    const AbstractDataGraph* graph = getGraph();
    const uint8_t a = LCD::div255(getAlpha() * graph->getAlpha());
    if (lineWidth == 0 || a == 0)
    {
        return;
    }
    const Rect invalidRect = enclosingArea(graph) & invalidatedArea;
    const int minorInterval = getCorrectlyScaledGridInterval(graph);
    const int majorInterval = getCorrectlyScaledMajorInterval(graph);
    const CWRUtil::Q5 lw2Q5minor = CWRUtil::toQ5(lineWidth) / 2;
    const int16_t start = getGraphAreaStart(graph);
    const int16_t length = getGraphAreaLength(graph);
    if (minorInterval == 0 && majorInterval == 0)
    {
        const int16_t pos = (valueToScreenQ5(graph, 0) - lw2Q5minor).round();
        const int16_t graphPos = pos - getGraphAreaStartPos(graph);
        if (graphPos + lineWidth >= 0 && graphPos < getGraphAreaEndPos(graph))
        {
            drawLine(invalidRect, start, length, pos, lineWidth, a);
        }
    }
    else if (minorInterval > 0)
    {
        int rangeMin = getGraphRangeMinScaled(graph);
        int rangeMax = getGraphRangeMaxScaled(graph);
        if (abs(rangeMax - rangeMin) / minorInterval > 500)
        {
            return; // Too many grid lines
        }
        if (valueToScreenQ5(graph, rangeMin) > valueToScreenQ5(graph, rangeMax))
        {
            const int tmp = rangeMin;
            rangeMin = rangeMax;
            rangeMax = tmp;
        }
        // Now rangeMax has a higher screen coordinate than rangeMin
        const int margin = rangeMin < rangeMax ? +1 : -1;
        const int minorLo = (rangeMin / minorInterval) - margin;
        const int minorHi = (rangeMax / minorInterval) + margin;
        const int minorStep = minorLo < minorHi ? +1 : -1;
        if (majorInterval == 0)
        {
            // No major lines, simply draw all lines
            for (int minorIndex = minorLo; minorIndex != minorHi + minorStep; minorIndex += minorStep)
            {
                const int16_t pos = (valueToScreenQ5(graph, minorInterval * minorIndex) - lw2Q5minor).round();
                const int16_t graphPos = pos - getGraphAreaStartPos(graph);
                if (graphPos + lineWidth >= 0 && graphPos < getGraphAreaEndPos(graph))
                {
                    drawLine(invalidRect, start, length, pos, lineWidth, a);
                }
            }
        }
        else
        {
            const int majorLo = (rangeMin / majorInterval) - margin;
            const int majorHi = (rangeMax / majorInterval) + margin;
            const int majorStep = majorLo < majorHi ? +1 : -1;
            int majorIndex = majorLo;
            int16_t majorCoord = valueToScreenQ5(graph, majorInterval * majorIndex).round();
            int minorIndex = minorLo;
            int16_t minorCoord = valueToScreenQ5(graph, minorInterval * minorIndex).round();
            for (;;)
            {
                // Draw minor lines up to the major line
                while (minorCoord < majorCoord)
                {
                    const int16_t pos = (valueToScreenQ5(graph, minorInterval * minorIndex) - lw2Q5minor).round();
                    const int16_t graphPos = pos - getGraphAreaStartPos(graph);
                    if (graphPos + lineWidth >= 0 && graphPos < getGraphAreaEndPos(graph))
                    {
                        drawLine(invalidRect, start, length, pos, lineWidth, a);
                    }
                    minorIndex += minorStep;
                    minorCoord = valueToScreenQ5(graph, minorInterval * minorIndex).round();
                }
                // Advance minor past the major line we are about to draw
                while (minorCoord <= majorCoord)
                {
                    minorIndex += minorStep;
                    minorCoord = valueToScreenQ5(graph, minorInterval * minorIndex).round();
                }
                if (majorCoord <= minorCoord)
                {
                    majorIndex += majorStep;
                    if (majorIndex == majorHi + majorStep)
                    {
                        break;
                    }
                    majorCoord = valueToScreenQ5(graph, majorInterval * majorIndex).round();
                }
            }
        }
    }
}
References touchgfx::abs(), LCD::div255(), GraphElementGridBase::drawLine(), GraphElementGridBase::enclosingArea(), CanvasWidget::getAlpha(), GraphElementGridBase::getCorrectlyScaledGridInterval(), GraphElementGridBase::getCorrectlyScaledMajorInterval(), AbstractGraphElement::getGraph(), GraphElementGridBase::getGraphAreaEndPos(), GraphElementGridBase::getGraphAreaLength(), GraphElementGridBase::getGraphAreaStart(), GraphElementGridBase::getGraphAreaStartPos(), GraphElementGridBase::getGraphRangeMaxScaled(), GraphElementGridBase::getGraphRangeMinScaled(), GraphElementGridBase::lineWidth, CWRUtil::toQ5(), and GraphElementGridBase::valueToScreenQ5().
drawLine()
void drawLine (const Rect & invalidatedArea, int16_t start, int16_t length, int16_t pos, int16_t width, uint8_t a) const protected virtual
Draw vertical line using LCD::fillRect and handles negative dimensions properly.
Parameters
invalidatedArea The invalidated area to intersect the line with.
start The start coordinate (offset from edge).
length The length of the line.
pos The start coordinate (distance in span).
width The width of the line.
a The alpha of the line.
{
    Rect r = lineRect(start, length, pos, width);
    normalizeRect(r);
    r &= invalidatedArea;
    if (!r.isEmpty())
    {
        translateRectToAbsolute(r);
        HAL::lcd().fillRect(r, color, a);
    }
}
References HAL::lcd(), GraphElementGridBase::lineRect(), AbstractGraphElementNoCWR::normalizeRect(), and Drawable::translateRectToAbsolute().
Referenced by GraphElementGridBase::draw().
enclosingArea()
virtual Rect enclosingArea (const AbstractDataGraph * graph) const protected pure virtual
Return the enclosing area for the grid lines. Vertical lines are allowed to go a bit to the left and right, but not above or below. Vice versa for horizontal gridlines.
Parameters
graph The graph.
Returns
A Rect which the grid lines should be inside.
Implemented in GraphElementGridX, and GraphElementGridY.
Referenced by GraphElementGridBase::draw().
getCorrectlyScaledGridInterval()
virtual int getCorrectlyScaledGridInterval (const AbstractDataGraph * graph) const pure virtual
Gets correctly scaled minor interval, as the minor grid may have a scale that differs the scale of the graph and this grid line.
Parameters
graph The graph.
Returns
The correctly scaled minor interval.
Implemented in GraphElementGridX, and GraphElementGridY.
Referenced by GraphElementGridBase::draw().
getCorrectlyScaledMajorInterval()
virtual int getCorrectlyScaledMajorInterval (const AbstractDataGraph * graph) const inline virtual
Gets correctly scaled major interval, as the major grid may have a scale that differs the scale of the graph and this grid line.
Parameters
graph The graph.
Returns
The correctly scaled major interval.
    {
        return majorGrid == 0 ? 0 : majorGrid->getCorrectlyScaledGridInterval(graph);
    }
References GraphElementGridBase::majorGrid.
Referenced by GraphElementGridBase::draw().
getGraphAreaEndPos()
virtual int getGraphAreaEndPos (const AbstractDataGraph * graph) const protected pure virtual
Gets graph area end position. Horizontal offset of last vertical line or vertical offset of last horizontal line.
Parameters
graph The graph.
Returns
The graph area end position. Horizontal offset of last vertical line or vertical offset of last horizontal line.
Implemented in GraphElementGridX, and GraphElementGridY.
Referenced by GraphElementGridBase::draw().
getGraphAreaLength()
virtual int getGraphAreaLength (const AbstractDataGraph * graph) const protected pure virtual
Gets graph area length (distance from border to border).
Parameters
graph The graph.
Returns
The graph area length (distance from border to border.
Implemented in GraphElementGridX, and GraphElementGridY.
Referenced by GraphElementGridBase::draw().
getGraphAreaStart()
virtual int getGraphAreaStart (const AbstractDataGraph * graph) const protected pure virtual
Gets graph area start (distance from the border).
Parameters
graph The graph.
Returns
The graph area start (distance from the border).
Implemented in GraphElementGridX, and GraphElementGridY.
Referenced by GraphElementGridBase::draw().
getGraphAreaStartPos()
virtual int getGraphAreaStartPos (const AbstractDataGraph * graph) const protected pure virtual
Gets graph area start position. Horizontal offset of first vertical line or vertical offset of first horizontal line.
Parameters
graph The graph.
Returns
The graph area start position. Horizontal offset of first vertical line or vertical offset og first horizontal line.
Implemented in GraphElementGridX, and GraphElementGridY.
Referenced by GraphElementGridBase::draw().
getGraphRangeMaxScaled()
virtual int getGraphRangeMaxScaled (const AbstractDataGraph * graph) const protected pure virtual
Gets graph range maximum x/y scaled.
Parameters
graph The graph.
Returns
The graph range maximum scaled.
Implemented in GraphElementGridX, and GraphElementGridY.
Referenced by GraphElementGridBase::draw().
getGraphRangeMinScaled()
virtual int getGraphRangeMinScaled (const AbstractDataGraph * graph) const protected pure virtual
Gets graph range minimum x/y scaled.
Parameters
graph The graph.
Returns
The graph range minimum scaled.
Implemented in GraphElementGridX, and GraphElementGridY.
Referenced by GraphElementGridBase::draw().
getIntervalAsFloat()
FORCE_INLINE_FUNCTION float getIntervalAsFloat () const inline
Gets the interval between each grid line.
Returns
The interval between each grid line.
See also
setInterval
    {
        return AbstractDataGraph::scaled2float(getIntervalScaled(), dataScale);
    }
References GraphElementGridBase::dataScale, GraphElementGridBase::getIntervalScaled(), and AbstractDataGraph::scaled2float().
getIntervalAsInt()
FORCE_INLINE_FUNCTION int getIntervalAsInt () const inline
Gets the interval between each grid line.
Returns
The interval between each grid line.
See also
setInterval
    {
        return AbstractDataGraph::scaled2int(getIntervalScaled(), dataScale);
    }
References GraphElementGridBase::dataScale, GraphElementGridBase::getIntervalScaled(), and AbstractDataGraph::scaled2int().
getIntervalScaled()
FORCE_INLINE_FUNCTION int getIntervalScaled () const inline
Gets the interval between each grid line.
Returns
The interval between each grid line.
See also
setInterval
Note
The interval returned here is left unscaled.
    {
        return gridInterval;
    }
References GraphElementGridBase::gridInterval.
Referenced by GraphElementGridBase::getIntervalAsFloat(), and GraphElementGridBase::getIntervalAsInt().
getLineWidth()
FORCE_INLINE_FUNCTION uint8_t getLineWidth () const inline
Gets line width.
Returns
The line width.
See also
setLineWidth
    {
        return lineWidth;
    }
References GraphElementGridBase::lineWidth.
getScale()
FORCE_INLINE_FUNCTION int getScale () const inline
Gets the scaling factor set using setScale.
Returns
The scaling factor.
See also
setScale
    {
        return dataScale;
    }
References GraphElementGridBase::dataScale.
invalidateGraphPointAt()
virtual void invalidateGraphPointAt (int16_t index) inline virtual
Invalidate the point at the given index. This allows a graph element to only invalidate the minimum rectangle required for the given index. The Graph will call this function before and after changing a point to ensure that both the old and the new area are redrawn (invalidated).
Parameters
index Zero-based index of the point.
Implements AbstractGraphElement.
    {
    }
lineRect()
virtual Rect lineRect (int16_t start, int16_t length, int16_t pos, int16_t width) const protected pure virtual
Return the specific rectangle for line.
Parameters
start The start (distance from the border).
length The length (length of the line).
pos The position (horizonal offset for vertical lines, vertical offset for horizontal lines).
width The (line) width.
Returns
A Rect.
Implemented in GraphElementGridX, and GraphElementGridY.
Referenced by GraphElementGridBase::drawLine().
setInterval() [1/2]
FORCE_INLINE_FUNCTION void setInterval (float interval) inline
Sets the interval between each grid line.
Parameters
interval The interval between each grid line.
See also
getIntervalAsInt, getIntervalAsFloat, setMajorGrid
Note
If interval is 0 only the axis is shown.
    {
        setIntervalScaled(AbstractDataGraph::float2scaled(abs(interval), dataScale));
    }
References touchgfx::abs(), GraphElementGridBase::dataScale, AbstractDataGraph::float2scaled(), and GraphElementGridBase::setIntervalScaled().
setInterval() [2/2]
FORCE_INLINE_FUNCTION void setInterval (int interval) inline
Sets the interval between each grid line.
Parameters
interval The interval between each grid line.
See also
getIntervalAsInt, getIntervalAsFloat, setMajorGrid
Note
If interval is 0 only the axis is shown.
    {
        setIntervalScaled(abs(interval) * dataScale);
    }
References touchgfx::abs(), GraphElementGridBase::dataScale, and GraphElementGridBase::setIntervalScaled().
setIntervalScaled()
FORCE_INLINE_FUNCTION void setIntervalScaled (int interval) inline
Sets the interval between each grid line.
Parameters
interval The interval between each grid line.
See also
getIntervalAsInt, getIntervalAsFloat, setMajorGrid
Note
If interval is 0 only the axis is shown.
The interval set here must already be scaled.
    {
        gridInterval = abs(interval);
    }
References touchgfx::abs(), and GraphElementGridBase::gridInterval.
Referenced by GraphElementGridBase::setInterval(), and GraphElementGridBase::setInterval().
setLineWidth()
FORCE_INLINE_FUNCTION void setLineWidth (uint8_t width) inline
Sets line width of the grid lines.
Parameters
width The width of the grid lines.
See also
getLineWidth
    {
        lineWidth = width;
    }
References GraphElementGridBase::lineWidth.
setMajorGrid()
FORCE_INLINE_FUNCTION void setMajorGrid (const GraphElementGridBase & major) inline
Sets "major" grid that will be responsible for drawing major grid lines. If a grid line would be drawn at the same position as the major grid line, the grid line will not be drawn.
Parameters
major Reference to a major grid line object.
    {
        majorGrid = &major;
    }
References GraphElementGridBase::majorGrid.
setScale()
FORCE_INLINE_FUNCTION void setScale (int scale) inline
Sets a scaling factor to be multiplied on the grid interval. Any already set grid interval will be updated to the new correctly scaled value. To avoid this, use setIntervalScaled() after setting scale.
Parameters
scale The scaling factor.
See also
getScale
    {
        assert(scale != 0);
        gridInterval = AbstractDataGraph::convertToNewScale(gridInterval, dataScale, scale);
        dataScale = scale;
    }
References AbstractDataGraph::convertToNewScale(), GraphElementGridBase::dataScale, and GraphElementGridBase::gridInterval.
valueToScreenQ5()
virtual CWRUtil::Q5 valueToScreenQ5 (const AbstractDataGraph * graph, int value) const protected pure virtual
The graph value to the correct screen coordinate in Q5.
Parameters
graph The graph.
value The value.
Returns
The graph value to the correct screen coordinate in Q5.
Implemented in GraphElementGridX, and GraphElementGridY.
Referenced by GraphElementGridBase::draw().
Member Data Documentation
dataScale
int dataScale protected
The scaling factor.
Referenced by GraphElementGridX::getCorrectlyScaledGridInterval(), GraphElementGridY::getCorrectlyScaledGridInterval(), GraphElementGridBase::getIntervalAsFloat(), GraphElementGridBase::getIntervalAsInt(), GraphElementGridBase::getScale(), GraphElementGridBase::setInterval(), GraphElementGridBase::setInterval(), and GraphElementGridBase::setScale().
gridInterval
int gridInterval protected
The grid line interval.
Referenced by GraphElementGridX::getCorrectlyScaledGridInterval(), GraphElementGridY::getCorrectlyScaledGridInterval(), GraphElementGridBase::getIntervalScaled(), GraphElementGridBase::setIntervalScaled(), and GraphElementGridBase::setScale().
lineWidth
uint8_t lineWidth protected
Width of the line.
Referenced by GraphElementGridBase::draw(), GraphElementGridBase::getLineWidth(), and GraphElementGridBase::setLineWidth().
majorGrid
const GraphElementGridBase* majorGrid protected
A pointer to a major grid, if any.
Referenced by GraphElementGridBase::getCorrectlyScaledMajorInterval(), and GraphElementGridBase::setMajorGrid().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/graph/GraphElements.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph/GraphElements.cpp