Battery Simulator Documentation: VideoWidget
VideoWidget
#include "VideoWidget.hpp"
Public Member Functions
VideoWidget ()
virtual ~VideoWidget ()
void clearMovieEndedAction ()
virtual void draw (const Rect &invalidatedArea) const
uint32_t getCurrentFrameNumber () const
virtual Rect getSolidRect () const
void getVideoInformation (VideoInformation *data) const
virtual void handleTickEvent ()
bool isPlaying () const
void pause () const
void play () const
void seek (uint32_t frameNumber) const
void setFrameRate (uint32_t ui_frames, uint32_t video_frames) const
void setMovieEndedAction (GenericCallback< const VideoWidget & > &callback)
void setRepeat (bool repeat) const
void setVideoBuffer (uint8_t *const videoBuffer)
void setVideoBufferFormat (Bitmap::BitmapFormat bufferFormat, int16_t width, int16_t height)
void setVideoData (const uint8_t *movie, const uint32_t length)
void setVideoData (VideoDataReader &reader)
void showFrame (uint32_t frameNumber) const
void stop () const
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Private Member Functions
void readVideoInformation ()
Private Attributes
uint8_t * buffer
The buffer where the pixels are copied from.
int16_t bufferHeight
Height of buffer in pixels (when used)
int16_t bufferWidth
Width (stride) of buffer in pixels (when used)
Bitmap::BitmapFormat format
The pixel format for the data.
VideoController::Handle handle
The handle of this video stream.
GenericCallback< const VideoWidget & > * movieEndedAction
Pointer to the callback to be executed when the video is done.
int16_t videoHeight
Height of video in pixels.
int16_t videoWidth
Width of video in pixels.
Additional Inherited Members
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A Widget for displaying video.
The Widget interacts with a VideoController instance.
See also
VideoController
Constructor & Destructor Documentation
VideoWidget()
VideoWidget ()
Default constructor.
    : Widget(),
      movieEndedAction(0), buffer(0), format(Bitmap::RGB888),
      bufferWidth(0), bufferHeight(0), videoWidth(0), videoHeight(0)
{
    handle = VideoController::getInstance().registerVideoWidget(*this);
    Application::getInstance()->registerTimerWidget(this);
}
References Application::getInstance(), VideoController::getInstance(), and VideoWidget::handle.
~VideoWidget()
~VideoWidget () virtual
Destructor. Unregisters the Widget from the Controller.
{
    VideoController::getInstance().unregisterVideoWidget(handle);
    Application::getInstance()->unregisterTimerWidget(this);
}
References Application::getInstance(), VideoController::getInstance(), and VideoWidget::handle.
Member Function Documentation
clearMovieEndedAction()
void clearMovieEndedAction () inline
Clears the movie ended action previously set by setMovieEndedAction.
See also
setMovieEndedAction
    {
        movieEndedAction = 0;
    }
References VideoWidget::movieEndedAction.
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Implements Drawable.
{
    // Only draw the invalidated area inside the video x buffer
    Rect invVideoRect(0, 0, videoWidth, videoHeight);
    invVideoRect &= invalidatedArea;
    // Inform controller that we are drawing
    VideoController::getInstance().draw(handle, invVideoRect, *this);
    // If we have a buffer, draw that
    if (buffer != 0)
    {
        // Limit to buffer size
        invVideoRect &= Rect(0, 0, bufferWidth, bufferHeight);
        // Convert to lcd coordinates. Width is buffer stride.
        Rect absolute = getAbsoluteRect();
        absolute.width = bufferWidth;
        // Copy to LCD, always solid
        HAL::lcd().blitCopy(buffer, format, absolute, invVideoRect, 255, false);
    }
}
References VideoWidget::bufferHeight, VideoWidget::bufferWidth, Drawable::getAbsoluteRect(), VideoController::getInstance(), VideoWidget::handle, HAL::lcd(), VideoWidget::videoHeight, and VideoWidget::videoWidth.
getCurrentFrameNumber()
uint32_t getCurrentFrameNumber () const
Get the current frame number.
Returns
Returns the current frame number.
{
    return VideoController::getInstance().getCurrentFrameNumber(handle);
}
References VideoController::getInstance(), and VideoWidget::handle.
getSolidRect()
Rect getSolidRect () const virtual
Get (the largest possible) rectangle that is guaranteed to be solid (opaque). This information is important, as any Drawable underneath the solid area does not need to be drawn.
Returns
The solid rectangle part of the Drawable.
Note
The rectangle returned must be relative to upper left corner of the Drawable, meaning that a completely solid widget should return the full size Rect(0, 0, getWidth(), getHeight()). If no area can be guaranteed to be solid, an empty Rect must be returned. Failing to return the correct rectangle may result in errors on the display.
Implements Drawable.
{
    // For Dedicated or DoubleBuffered video we have a bufferWidth > 0
    // But maybe no buffer yet (only after decoding first frame)
    if (bufferWidth > 0)
    {
        // Solid inside video area if we have a buffer, otherwise transparent
        if (buffer != 0)
        {
            return Rect(0, 0, MIN(videoWidth, bufferWidth), MIN(videoHeight, bufferHeight));
        }
        return Rect();
    }
    //Direct to framebuffer, solid inside the video area
    return Rect(0, 0, videoWidth, videoHeight);
}
References VideoWidget::bufferHeight, VideoWidget::bufferWidth, MIN, VideoWidget::videoHeight, and VideoWidget::videoWidth.
getVideoInformation()
void getVideoInformation (VideoInformation * data) const
Get Video information.
Get information from the video data.
Parameters
[in,out] data Pointer to VideoInformation where information should be stored.
{
    VideoController::getInstance().getVideoInformation(handle, data);
}
References VideoController::getInstance(), and VideoWidget::handle.
handleTickEvent()
void handleTickEvent () virtual
Called periodically by the framework if the Drawable instance has subscribed to timer ticks.
See also
Application::registerTimerWidget
Reimplemented from Drawable.
{
    const bool hasMoreFrames = VideoController::getInstance().updateFrame(handle, *this);
    if (!hasMoreFrames)
    {
        // Now showing last frame
        if (movieEndedAction && movieEndedAction->isValid())
        {
            movieEndedAction->execute(*this);
        }
    }
}
References VideoController::getInstance(), VideoWidget::handle, and VideoWidget::movieEndedAction.
isPlaying()
bool isPlaying () const
Check if the video is playing (not paused or stopped).
Returns
Returns true if the video is playing.
{
    return VideoController::getInstance().getIsPlaying(handle);
}
References VideoController::getInstance(), and VideoWidget::handle.
Referenced by VideoWidget::showFrame().
pause()
void pause () const
Pause the video.
{
    VideoController::getInstance().setCommand(handle, VideoController::PAUSE, 0);
}
References VideoController::getInstance(), VideoWidget::handle, and VideoController::PAUSE.
play()
void play () const
Play the video.
{
    VideoController::getInstance().setCommand(handle, VideoController::PLAY, 0);
}
References VideoController::getInstance(), VideoWidget::handle, and VideoController::PLAY.
readVideoInformation()
void readVideoInformation () private
Reads information from the video. Sets the video width and height. Sets the framerate to speed specified in movie. Assumes 60 ui frame pr. second.
{
    // Set frame rate to movie speed (assuming 60 ui frames in a second)
    VideoInformation videoInformation;
    VideoController::getInstance().getVideoInformation(handle, &videoInformation);
    videoWidth = (int16_t)videoInformation.frame_width;
    videoHeight = (int16_t)videoInformation.frame_height;
    const uint32_t videoFramesIn1000ms = 1000 / videoInformation.ms_between_frames;
    setFrameRate(60, videoFramesIn1000ms);
}
References VideoController::getInstance(), VideoWidget::handle, VideoWidget::setFrameRate(), VideoWidget::videoHeight, and VideoWidget::videoWidth.
Referenced by VideoWidget::setVideoData(), and VideoWidget::setVideoData().
seek()
void seek (uint32_t frameNumber) const
Seek to specific frame. Frame number 1 is the first frame. The display is not updated updated unless the video is playing.
Parameters
frameNumber The frame number to seek to.
See also
showFrame
{
    VideoController::getInstance().setCommand(handle, VideoController::SEEK, frameNumber);
}
References VideoController::getInstance(), VideoWidget::handle, and VideoController::SEEK.
Referenced by VideoWidget::showFrame().
setFrameRate()
void setFrameRate (uint32_t ui_frames, uint32_t video_frames) const
Sets the frame rate of the video.
To get 20 video frames pr second on a 60 fps display use video_frames = 20 and ui_frames = 60.
Parameters
ui_frames Number of UI frames (divider)
video_frames Number of video_frames (dividend)
{
    VideoController::getInstance().setFrameRate(handle, ui_frames, video_frames);
}
References VideoController::getInstance(), and VideoWidget::handle.
Referenced by VideoWidget::readVideoInformation().
setMovieEndedAction()
void setMovieEndedAction (GenericCallback< const VideoWidget & > & callback) inline
Associates an action to be performed when the movie has ended. If the video is set to repeat, the action is also triggered when the animation starts over.
Parameters
callback The callback is executed when done. The callback is given the VideoWidget.
    {
        movieEndedAction = &callback;
    }
References VideoWidget::movieEndedAction.
setRepeat()
void setRepeat (bool repeat) const
Set repeat mode. When set the video is restarted when the end is reached.
Parameters
repeat When true, the video is repeated.
{
    VideoController::getInstance().setCommand(handle, VideoController::SET_REPEAT, repeat ? 1 : 0);
}
References VideoController::getInstance(), VideoWidget::handle, and VideoController::SET_REPEAT.
setVideoBuffer()
void setVideoBuffer (uint8_t *const videoBuffer) inline
Set video buffer data. Only used when video frames are decoded to a buffer and not directly to the framebuffer.
Parameters
[in] videoBuffer Video buffer.
    {
        buffer = videoBuffer;
    }
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::registerVideoWidget(), DedicatedBufferController< no_streams, width, height, stride, output_format >::registerVideoWidget(), DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::registerVideoWidget(), DedicatedBufferController< no_streams, width, height, stride, output_format >::updateFrame(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::updateFrame().
setVideoBufferFormat()
void setVideoBufferFormat (Bitmap::BitmapFormat bufferFormat, int16_t width, int16_t height) inline
Set video buffer format. Only used when video frames are decoded to a buffer and not directly to the framebuffer.
Parameters
bufferFormat Format of the videoBuffer (RGB565 or RGB888)
width Width of the videoBuffer in pixels
height Height of the videoBuffer in pixels
    {
        format = bufferFormat;
        bufferWidth = width;
        bufferHeight = height;
    }
References VideoWidget::bufferHeight, and VideoWidget::bufferWidth.
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::registerVideoWidget(), DedicatedBufferController< no_streams, width, height, stride, output_format >::registerVideoWidget(), and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >::registerVideoWidget().
setVideoData() [1/2]
void setVideoData (const uint8_t * movie, const uint32_t length)
Set the video data for the stream. The video is paused and set to start on the first frame.
Parameters
movie Pointer to the video data.
length Length of the vide data.
{
    VideoController::getInstance().setVideoData(handle, movie, length);
    readVideoInformation();
}
References VideoController::getInstance(), VideoWidget::handle, and VideoWidget::readVideoInformation().
setVideoData() [2/2]
void setVideoData (VideoDataReader & reader)
Set the video data for the stream. The video is paused and set to start on the first frame.
Parameters
[in,out] reader Reference to a VideoDataReader object.
{
    VideoController::getInstance().setVideoData(handle, reader);
    readVideoInformation();
}
References VideoController::getInstance(), VideoWidget::handle, and VideoWidget::readVideoInformation().
showFrame()
void showFrame (uint32_t frameNumber) const
Seek to a specific frame and update the display. Equal to seek if the video is playing.
Parameters
frameNumber The frame number to seek to.
See also
seek
{
    if (isPlaying())
    {
        seek(frameNumber);
    }
    else
    {
        VideoController::getInstance().setCommand(handle, VideoController::SHOW, frameNumber);
    }
}
References VideoController::getInstance(), VideoWidget::handle, VideoWidget::isPlaying(), VideoWidget::seek(), and VideoController::SHOW.
stop()
void stop () const
Stop the video.
{
    VideoController::getInstance().setCommand(handle, VideoController::STOP, 0);
}
References VideoController::getInstance(), VideoWidget::handle, and VideoController::STOP.
Member Data Documentation
buffer
uint8_t* buffer private
The buffer where the pixels are copied from.
bufferHeight
int16_t bufferHeight private
Height of buffer in pixels (when used)
Referenced by VideoWidget::draw(), VideoWidget::getSolidRect(), and VideoWidget::setVideoBufferFormat().
bufferWidth
int16_t bufferWidth private
Width (stride) of buffer in pixels (when used)
Referenced by VideoWidget::draw(), VideoWidget::getSolidRect(), and VideoWidget::setVideoBufferFormat().
format
Bitmap::BitmapFormat format private
The pixel format for the data.
handle
VideoController::Handle handle private
The handle of this video stream.
Referenced by VideoWidget::VideoWidget(), VideoWidget::~VideoWidget(), VideoWidget::draw(), VideoWidget::getCurrentFrameNumber(), VideoWidget::getVideoInformation(), VideoWidget::handleTickEvent(), VideoWidget::isPlaying(), VideoWidget::pause(), VideoWidget::play(), VideoWidget::readVideoInformation(), VideoWidget::seek(), VideoWidget::setFrameRate(), VideoWidget::setRepeat(), VideoWidget::setVideoData(), VideoWidget::setVideoData(), VideoWidget::showFrame(), and VideoWidget::stop().
movieEndedAction
GenericCallback<const VideoWidget&>* movieEndedAction private
Pointer to the callback to be executed when the video is done.
Referenced by VideoWidget::clearMovieEndedAction(), VideoWidget::handleTickEvent(), and VideoWidget::setMovieEndedAction().
videoHeight
int16_t videoHeight private
Height of video in pixels.
Referenced by VideoWidget::draw(), VideoWidget::getSolidRect(), and VideoWidget::readVideoInformation().
videoWidth
int16_t videoWidth private
Width of video in pixels.
Referenced by VideoWidget::draw(), VideoWidget::getSolidRect(), and VideoWidget::readVideoInformation().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/VideoWidget.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/VideoWidget.cpp