Battery Simulator Documentation: VideoController
VideoController abstract
#include "VideoController.hpp"
Public Types
enum Command {
PLAY , PAUSE , SEEK , SHOW ,
STOP , SET_REPEAT
}
typedef uint32_t Handle
Public Member Functions
virtual ~VideoController ()
virtual void draw (const Handle handle, const Rect &invalidatedArea, const VideoWidget &widget)=0
virtual uint32_t getCurrentFrameNumber (const Handle handle)=0
virtual bool getIsPlaying (const Handle handle)=0
virtual void getVideoInformation (const Handle handle, VideoInformation *data)=0
virtual Handle registerVideoWidget (VideoWidget &widget)=0
virtual void setCommand (const Handle handle, Command cmd, uint32_t param)=0
virtual void setFrameRate (const Handle handle, uint32_t ui_frames, uint32_t video_frames)=0
virtual void setVideoData (const Handle handle, const uint8_t *movie, const uint32_t length)=0
virtual void setVideoData (const Handle handle, VideoDataReader &reader)=0
virtual void setVideoFrameRateCompensation (bool allow)=0
virtual void unregisterVideoWidget (const Handle handle)=0
virtual bool updateFrame (const Handle handle, VideoWidget &widget)=0
Static Public Member Functions
static VideoController & getInstance ()
Detailed Description
The VideoController is an abstract interface for the video decoder. A concrete implementation will be generated by the TouchGFX Generator.
The VideoController can control multiple video streams in multiple VideoWidgets. These are recognized by their Handle.
Application code should only interact with the VideoWidget class.
See also
VideoWidget
Member Typedef Documentation
Handle
typedef uint32_t Handle
Type to identify a video stream.
Member Enumeration Documentation
Command
enum Command
The commands send to the Controller.
Enumerator
PLAY
Play the video.
PAUSE
Pause the playing.
SEEK
Seek to frame.
SHOW
Show a frame.
STOP
Stop the video.
SET_REPEAT
Set repeat mode.
    {
        PLAY,
        PAUSE,
        SEEK,
        SHOW,
        STOP,
        SET_REPEAT
    };
Constructor & Destructor Documentation
~VideoController()
virtual ~VideoController () inline virtual
Virtual destructor.
    {
    }
Member Function Documentation
draw()
virtual void draw (const Handle handle, const Rect & invalidatedArea, const VideoWidget & widget) pure virtual
Draw the video content.
Parameters
handle The stream handle.
invalidatedArea The area of the widget that must be redrawn.
widget Reference to the widget.
Implemented in DirectFrameBufferVideoController< no_streams, output_format >, DedicatedBufferController< no_streams, width, height, stride, output_format >, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >.
getCurrentFrameNumber()
virtual uint32_t getCurrentFrameNumber (const Handle handle) pure virtual
Get the current frame number.
Parameters
handle The stream handle.
Returns
Return the current frame number.
Implemented in DirectFrameBufferVideoController< no_streams, output_format >, DedicatedBufferController< no_streams, width, height, stride, output_format >, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >.
getInstance()
VideoController & getInstance () static
Gets the VideoController instance.
Returns
The VideoController instance.
{
    return controller;
}
References controller.
Referenced by VideoWidget::VideoWidget(), VideoWidget::~VideoWidget(), VideoWidget::draw(), VideoWidget::getCurrentFrameNumber(), VideoWidget::getVideoInformation(), VideoWidget::handleTickEvent(), VideoWidget::isPlaying(), VideoWidget::pause(), VideoWidget::play(), VideoWidget::readVideoInformation(), VideoWidget::seek(), VideoWidget::setFrameRate(), VideoWidget::setRepeat(), VideoWidget::setVideoData(), VideoWidget::setVideoData(), VideoWidget::showFrame(), and VideoWidget::stop().
getIsPlaying()
virtual bool getIsPlaying (const Handle handle) pure virtual
Check if the video stream is playing (not paused or stopped).
Parameters
handle The stream handle.
Returns
Returns true if the video is playing.
Implemented in DirectFrameBufferVideoController< no_streams, output_format >, DedicatedBufferController< no_streams, width, height, stride, output_format >, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >.
getVideoInformation()
virtual void getVideoInformation (const Handle handle, VideoInformation * data) pure virtual
Get Video information.
Get information from the video data.
Parameters
handle The stream handle.
[in,out] data Pointer to VideoInformation where information should be stored.
Implemented in DirectFrameBufferVideoController< no_streams, output_format >, DedicatedBufferController< no_streams, width, height, stride, output_format >, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >.
registerVideoWidget()
virtual Handle registerVideoWidget (VideoWidget & widget) pure virtual
Register a VideoWidget to get a Handle.
Parameters
[in,out] widget The VideoWidget.
Returns
A video stream handle.
Implemented in DirectFrameBufferVideoController< no_streams, output_format >, DedicatedBufferController< no_streams, width, height, stride, output_format >, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >.
setCommand()
virtual void setCommand (const Handle handle, Command cmd, uint32_t param) pure virtual
Pass a command from the Widget to the Controller.
Parameters
handle The stream handle.
cmd The Command.
param A parameter.
Implemented in DirectFrameBufferVideoController< no_streams, output_format >, DedicatedBufferController< no_streams, width, height, stride, output_format >, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >.
setFrameRate()
virtual void setFrameRate (const Handle handle, uint32_t ui_frames, uint32_t video_frames) pure virtual
Set the framerate for video using a qoutient of screen frames /video frames.
To get 20 video frames pr second on a 60 fps display use video_frames = 20 and ui_frames = 60.
Parameters
handle The stream handle.
ui_frames Number of UI frames (divider)
video_frames Number of video_frames (dividend)
Implemented in DirectFrameBufferVideoController< no_streams, output_format >, DedicatedBufferController< no_streams, width, height, stride, output_format >, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >.
setVideoData() [1/2]
virtual void setVideoData (const Handle handle, const uint8_t * movie, const uint32_t length) pure virtual
Set the video data for the stream.
Parameters
handle The stream handle.
movie Pointer to the video data.
length Length of the video data.
Implemented in DirectFrameBufferVideoController< no_streams, output_format >, DedicatedBufferController< no_streams, width, height, stride, output_format >, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >.
setVideoData() [2/2]
virtual void setVideoData (const Handle handle, VideoDataReader & reader) pure virtual
Set the video data for the stream.
Parameters
handle The stream handle.
[in,out] reader Reference to a VideoDataReader object.
Implemented in DirectFrameBufferVideoController< no_streams, output_format >.
setVideoFrameRateCompensation()
virtual void setVideoFrameRateCompensation (bool allow) pure virtual
Allow skipping of video frames to compensate for long decoding times.
Parameters
allow true if compensation is allowed.
Implemented in DedicatedBufferController< no_streams, width, height, stride, output_format >, DoubleBufferedVideoController< no_streams, width, height, stride, output_format >, and DirectFrameBufferVideoController< no_streams, output_format >.
unregisterVideoWidget()
virtual void unregisterVideoWidget (const Handle handle) pure virtual
Unregister a VideoWidget to release the handle.
Parameters
handle The stream handle.
Implemented in DirectFrameBufferVideoController< no_streams, output_format >, DedicatedBufferController< no_streams, width, height, stride, output_format >, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >.
updateFrame()
virtual bool updateFrame (const Handle handle, VideoWidget & widget) pure virtual
Signal that the widget can be invalidated (tickEvent).
Parameters
handle The stream handle.
[in,out] widget The Widget.
Returns
Returns true if video has more frames (i.e. false on the last frame).
Implemented in DirectFrameBufferVideoController< no_streams, output_format >, DedicatedBufferController< no_streams, width, height, stride, output_format >, and DoubleBufferedVideoController< no_streams, width, height, stride, output_format >.
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/hal/VideoController.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/simulator/src/mainBase.cpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/target/generated/TouchGFXGeneratedHAL.cpp