Battery Simulator Documentation: GraphTitle
GraphTitle
#include "GraphLabels.hpp"
Public Member Functions
GraphTitle ()
virtual void draw (const Rect &invalidatedArea) const
virtual bool drawCanvasWidget (const Rect &) const
FORCE_INLINE_FUNCTION TextRotation getTitleRotation () const
FORCE_INLINE_FUNCTION const TypedText & getTitleTypedText () const
virtual void invalidateGraphPointAt (int16_t)
FORCE_INLINE_FUNCTION void setTitleRotation (TextRotation rotation)
FORCE_INLINE_FUNCTION void setTitleTypedText (const TypedText &typedText)
Public Member Functions inherited from AbstractGraphElementNoCWR
AbstractGraphElementNoCWR ()
virtual colortype getColor () const
virtual void setColor (colortype newColor)
Public Member Functions inherited from AbstractGraphElement
AbstractGraphElement ()
Public Member Functions inherited from CanvasWidget
CanvasWidget ()
virtual uint8_t getAlpha () const
virtual Rect getMinimalRect () const
const AbstractPainter * getPainter () const
virtual Rect getSolidRect () const
virtual void invalidate () const
virtual void setAlpha (uint8_t newAlpha)
void setPainter (const AbstractPainter &painter)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Private Attributes
TextRotation titleRotation
The title rotation.
TypedText titleTypedText
The title typed text.
Additional Inherited Members
Protected Member Functions inherited from AbstractGraphElementNoCWR
void normalizeRect (Rect &r) const
Protected Member Functions inherited from AbstractGraphElement
FORCE_INLINE_FUNCTION int convertToGraphScaleX (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION int convertToGraphScaleY (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION AbstractDataGraph * getGraph () const
FORCE_INLINE_FUNCTION int getIndexToXAxis (const AbstractDataGraph *graph, const int valueScaled, const int labelScaled) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenXQ5 (const AbstractDataGraph *graph, int16_t index) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenYQ5 (const AbstractDataGraph *graph, int16_t index) const
bool isCenterInvisible (const AbstractDataGraph *graph, int16_t index) const
Rect rectAround (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5, CWRUtil::Q5 diameterQ5) const
Rect rectFromQ5Coordinates (CWRUtil::Q5 screenXminQ5, CWRUtil::Q5 screenYminQ5, CWRUtil::Q5 screenXmaxQ5, CWRUtil::Q5 screenYmaxQ5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 roundQ5 (CWRUtil::Q5 q5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenXQ5 (const AbstractDataGraph *graph, int x) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenYQ5 (const AbstractDataGraph *graph, int y) const
FORCE_INLINE_FUNCTION bool xScreenRangeToIndexRange (const AbstractDataGraph *graph, int16_t xMin, int16_t xMax, int16_t &indexMin, int16_t &indexMax) const
Protected Attributes inherited from AbstractGraphElementNoCWR
colortype color
The currently assigned color.
Protected Attributes inherited from CanvasWidget
uint8_t alpha
The Alpha for this CanvasWidget.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
The GraphTitle is just a simple text, but it is automatically moved with the graph. Also, the alpha value is combined with the alpha of the graph and so it will be faded if the graph is faded.
Constructor & Destructor Documentation
GraphTitle()
GraphTitle () inline
        : titleTypedText(TYPED_TEXT_INVALID), titleRotation(TEXT_ROTATE_0)
    {
    }
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draws the given invalidated area. If the underlying CanvasWidgetRenderer fail to render the widget (if the widget is too complex), the invalidated area is cut into smaller slices (horizontally) which are then drawn separately. If drawing a single raster line fails, that line is considered too complex and skipped (it is left blank/transparent) and drawing continues on the next raster line.
If drawing has failed at least once, which means that the number of horizontal lines draw has been reduced, the number of successfully drawn horizontal lines is remembered for the next invocation of draw(). A future call to draw() would then start off with the reduced number of horizontal lines to prevent potentially drawing the canvas widget in vain, as happened previously in draw().
Parameters
invalidatedArea The invalidated area.
See also
drawCanvasWidget
Note
Subclasses of CanvasWidget should implement drawCanvasWidget(), not draw().
The term "too complex" means that the size of the buffer (assigned to CanvasWidgetRenderer using CanvasWidgetRenderer::setupBuffer()) is too small.
Reimplemented from CanvasWidget.
{
    if (!titleTypedText.hasValidId())
    {
        return;
    }
    const Font* fontToDraw = titleTypedText.getFont();
    if (!fontToDraw)
    {
        return;
    }
    const uint8_t a = LCD::div255(getAlpha() * getGraph()->getAlpha());
    if (a == 0)
    {
        return;
    }
    const uint16_t lineHeight = fontToDraw->getHeight() * fontToDraw->getNumberOfLines(titleTypedText.getText());
    Rect labelRect(rect);
    // Adjust to make label centered
    if (titleRotation == TEXT_ROTATE_0 || titleRotation == TEXT_ROTATE_180)
    {
        labelRect.y += (labelRect.height - lineHeight) / 2;
        labelRect.height = lineHeight;
    }
    else
    {
        labelRect.x += (labelRect.width - lineHeight) / 2;
        labelRect.width = lineHeight;
    }
    Rect dirty = labelRect & invalidatedArea;
    if (!dirty.isEmpty())
    {
        dirty.x -= labelRect.x;
        dirty.y -= labelRect.y;
        translateRectToAbsolute(labelRect);
        const LCD::StringVisuals visuals(fontToDraw, getColor(), a, titleTypedText.getAlignment(), 0, titleRotation, titleTypedText.getTextDirection(), 0, WIDE_TEXT_NONE);
        HAL::lcd().drawString(labelRect, dirty, visuals, titleTypedText.getText(), 0, 0);
    }
}
References touchgfx::dirty, LCD::div255(), TypedText::getAlignment(), CanvasWidget::getAlpha(), AbstractGraphElementNoCWR::getColor(), TypedText::getFont(), AbstractGraphElement::getGraph(), TypedText::getText(), TypedText::getTextDirection(), TypedText::hasValidId(), HAL::lcd(), Drawable::rect, touchgfx::TEXT_ROTATE_0, touchgfx::TEXT_ROTATE_180, GraphTitle::titleRotation, GraphTitle::titleTypedText, Drawable::translateRectToAbsolute(), and touchgfx::WIDE_TEXT_NONE.
drawCanvasWidget()
virtual bool drawCanvasWidget (const Rect & invalidatedArea) const inline virtual
Draw canvas widget for the given invalidated area. Similar to draw(), but might be invoked several times with increasingly smaller areas to due to memory constraints from the underlying CanvasWidgetRenderer.
Parameters
invalidatedArea The invalidated area.
Returns
true if the widget was drawn properly, false if not.
See also
draw
Reimplemented from AbstractGraphElementNoCWR.
    {
        return true;
    }
getTitleRotation()
FORCE_INLINE_FUNCTION TextRotation getTitleRotation () const inline
Gets title rotation.
Returns
The title rotation.
See also
setTitleRotation
    {
        return titleRotation;
    }
References GraphTitle::titleRotation.
getTitleTypedText()
FORCE_INLINE_FUNCTION const TypedText & getTitleTypedText () const inline
Gets title typed text.
Returns
The title typed text.
See also
setTitleTypedText
    {
        return titleTypedText;
    }
References GraphTitle::titleTypedText.
invalidateGraphPointAt()
virtual void invalidateGraphPointAt (int16_t index) inline virtual
Invalidate the point at the given index. This allows a graph element to only invalidate the minimum rectangle required for the given index. The Graph will call this function before and after changing a point to ensure that both the old and the new area are redrawn (invalidated).
Parameters
index Zero-based index of the point.
Implements AbstractGraphElement.
    {
    }
setTitleRotation()
FORCE_INLINE_FUNCTION void setTitleRotation (TextRotation rotation) inline
Sets TextRotation of the title.
Parameters
rotation The rotation.
See also
setTitleTypedText, getTitleRotation
    {
        titleRotation = rotation;
    }
References GraphTitle::titleRotation.
setTitleTypedText()
FORCE_INLINE_FUNCTION void setTitleTypedText (const TypedText & typedText) inline
Sets TypedText to use as a title. It can be any static text which is just added as a title.
Parameters
typedText The typed text.
See also
getTitleTypedText
    {
        titleTypedText = typedText;
    }
References GraphTitle::titleTypedText.
Member Data Documentation
titleRotation
TextRotation titleRotation private
The title rotation.
Referenced by GraphTitle::draw(), GraphTitle::getTitleRotation(), and GraphTitle::setTitleRotation().
titleTypedText
TypedText titleTypedText private
The title typed text.
Referenced by GraphTitle::draw(), GraphTitle::getTitleTypedText(), and GraphTitle::setTitleTypedText().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/graph/GraphLabels.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph/GraphLabels.cpp