Battery Simulator Documentation: Screen1ViewBase
Screen1ViewBase
#include "Screen1ViewBase.hpp"
Public Member Functions
Screen1ViewBase ()
virtual ~Screen1ViewBase ()
virtual void setupScreen ()
Public Member Functions inherited from View< Screen1Presenter >
View ()
void bind (Screen1Presenter &newPresenter)
Public Member Functions inherited from Screen
Screen ()
virtual ~Screen ()
virtual void afterTransition ()
void bindTransition (Transition &trans)
void draw ()
virtual void draw (Rect &rect)
Container & getRootContainer ()
int16_t getScreenHeight () const
int16_t getScreenWidth () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleKeyEvent (uint8_t key)
virtual void handleTickEvent ()
void JSMOC (const Rect &invalidatedArea, Drawable *widgetToDraw)
void startSMOC (const Rect &invalidatedArea)
virtual void tearDownScreen ()
bool usingSMOC () const
Protected Member Functions
FrontendApplication & application ()
Protected Member Functions inherited from Screen
void add (Drawable &d)
void insert (Drawable *previous, Drawable &d)
void invalidate () const
void invalidateRect (Rect &invalidatedArea) const
void remove (Drawable &d)
void useSMOCDrawing (bool enabled)
Protected Attributes
touchgfx::Box __background
touchgfx::AnimatedImage animatedImage1
touchgfx::Image image1
touchgfx::Image image2
touchgfx::ImageProgress imageProgress1
Protected Attributes inherited from View< Screen1Presenter >
Screen1Presenter * presenter
Pointer to the Presenter associated with this view.
Protected Attributes inherited from Screen
Container container
The container contains the contents of the screen.
Drawable * focus
The drawable currently in focus (set when DOWN_PRESSED is received).
Detailed Description
Constructor & Destructor Documentation
Screen1ViewBase()
Screen1ViewBase ()
{
    __background.setPosition(0, 0, 1024, 600);
    __background.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    add(__background);
    image1.setXY(0, 0);
    image1.setBitmap(touchgfx::Bitmap(BITMAP_PXFUEL_ID));
    add(image1);
    animatedImage1.setXY(248, 520);
    animatedImage1.setBitmaps(BITMAP_C7BB67AD_72CB_469F_AAB8_1D20CB9D21DF_0_ID, BITMAP_C7BB67AD_72CB_469F_AAB8_1D20CB9D21DF_5_ID);
    animatedImage1.setUpdateTicksInterval(9);
    animatedImage1.setAlpha(0);
    add(animatedImage1);
    image2.setXY(0, 0);
    image2.setBitmap(touchgfx::Bitmap(BITMAP_LOGO_400PX_ID));
    add(image2);
    imageProgress1.setXY(362, 575);
    imageProgress1.setProgressIndicatorPosition(0, 0, 300, 10);
    imageProgress1.setRange(0, 100);
    imageProgress1.setDirection(touchgfx::AbstractDirectionProgress::RIGHT);
    imageProgress1.setBackground(touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_IMAGEPROGRESS_PLAIN_NORMAL_MEDIUM_ID));
    imageProgress1.setBitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_IMAGEPROGRESS_PLAIN_NORMAL_MEDIUM_ACTION_ID);
    imageProgress1.setValue(60);
    imageProgress1.setAnchorAtZero(true);
    add(imageProgress1);
}
References __background, Screen::add(), animatedImage1, BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_IMAGEPROGRESS_PLAIN_NORMAL_MEDIUM_ACTION_ID, BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_IMAGEPROGRESS_PLAIN_NORMAL_MEDIUM_ID, BITMAP_C7BB67AD_72CB_469F_AAB8_1D20CB9D21DF_0_ID, BITMAP_C7BB67AD_72CB_469F_AAB8_1D20CB9D21DF_5_ID, BITMAP_LOGO_400PX_ID, BITMAP_PXFUEL_ID, Color::getColorFromRGB(), image1, image2, imageProgress1, AbstractDirectionProgress::RIGHT, Image::setAlpha(), ImageProgress::setAnchorAtZero(), AbstractProgressIndicator::setBackground(), ImageProgress::setBitmap(), Image::setBitmap(), AnimatedImage::setBitmaps(), Box::setColor(), AbstractDirectionProgress::setDirection(), Drawable::setPosition(), ImageProgress::setProgressIndicatorPosition(), AbstractProgressIndicator::setRange(), AnimatedImage::setUpdateTicksInterval(), ImageProgress::setValue(), and Drawable::setXY().
~Screen1ViewBase()
~Screen1ViewBase () virtual
{
}
Member Function Documentation
application()
FrontendApplication & application () inline protected
{
        return *static_cast<FrontendApplication*>(touchgfx::Application::getInstance());
    }
References Application::getInstance().
setupScreen()
void setupScreen () virtual
Called by Application::switchScreen() when this screen is going to be displayed. Base version does nothing, but place any screen specific initialization code in an overridden version.
See also
Application::switchScreen
Reimplemented from Screen.
Reimplemented in Screen1View.
{
}
Referenced by Screen1View::setupScreen().
Member Data Documentation
__background
touchgfx::Box __background protected
Referenced by Screen1ViewBase().
animatedImage1
touchgfx::AnimatedImage animatedImage1 protected
Referenced by Screen1ViewBase(), and Screen1View::SetState().
image1
touchgfx::Image image1 protected
Referenced by Screen1ViewBase().
image2
touchgfx::Image image2 protected
Referenced by Screen1ViewBase().
imageProgress1
touchgfx::ImageProgress imageProgress1 protected
Referenced by Screen1ViewBase(), and Screen1View::SetLevel().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/gui_generated/include/gui_generated/screen1_screen/Screen1ViewBase.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/gui_generated/src/screen1_screen/Screen1ViewBase.cpp