Battery Simulator Documentation: Canvas
Canvas
#include "Canvas.hpp"
Public Member Functions
Canvas (const AbstractPainter *const painter, const Rect &canvasAreaAbs, const Rect &invalidatedAreaRel, uint8_t globalAlpha)
virtual ~Canvas ()
bool close ()
void cubicBezierTo (float x0, float y0, float x1, float y1, float x2, float y2, float x, float y)
Rasterizer::FillingRule getFillingRule () const
virtual void lineTo (CWRUtil::Q5 x, CWRUtil::Q5 y)
template<typename T >
void lineTo (T x, T y)
void moveTo (CWRUtil::Q5 x, CWRUtil::Q5 y)
template<typename T >
void moveTo (T x, T y)
void quadraticBezierTo (float x0, float y0, const float x1, const float y1, const float x, const float y)
bool render (uint8_t customAlpha=255)
void setFillingRule (Rasterizer::FillingRule rule)
FORCE_INLINE_FUNCTION bool wasOutlineTooComplex ()
Private Types
enum { POINT_IS_ABOVE = 1 << 0 , POINT_IS_BELOW = 1 << 1 , POINT_IS_LEFT = 1 << 2 , POINT_IS_RIGHT = 1 << 3 }
Private Member Functions
FORCE_INLINE_FUNCTION uint8_t isOutside (const CWRUtil::Q5 &x, const CWRUtil::Q5 &y, const CWRUtil::Q5 &width, const CWRUtil::Q5 &height) const
void recursiveCubicBezier (const float x1, const float y1, const float x2, const float y2, const float x3, const float y3, const float x4, const float y4, const unsigned level)
void recursiveQuadraticBezier (const float x1, const float y1, const float x2, const float y2, const float x3, const float y3, const unsigned level)
void transformFrameBufferToDisplay (CWRUtil::Q5 &x, CWRUtil::Q5 &y) const
Private Attributes
uint8_t canvasAlpha
int16_t canvasAreaWidth
const AbstractPainter *const canvasPainter
Rect dirtyAreaAbsolute
CWRUtil::Q5 initialMoveToX
CWRUtil::Q5 initialMoveToY
CWRUtil::Q5 invalidatedAreaHeight
CWRUtil::Q5 invalidatedAreaWidth
CWRUtil::Q5 invalidatedAreaX
CWRUtil::Q5 invalidatedAreaY
bool isPenDown
uint8_t penDownOutside
uint8_t previousOutside
CWRUtil::Q5 previousX
CWRUtil::Q5 previousY
Rasterizer rasterizer
bool wasPenDown
Detailed Description
Class for easy rendering using CanvasWidgetRenderer.
The Canvas class will make implementation of a new CanvasWidget very easy. The few simple primitives allows moving a "pen" and drawing the outline of a shape which can then be rendered.
The Canvas class has been optimized to eliminate drawing unnecessary lines outside the currently invalidated rectangle.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
POINT_IS_ABOVE
POINT_IS_BELOW
POINT_IS_LEFT
POINT_IS_RIGHT
    {
        POINT_IS_ABOVE = 1 << 0,
        POINT_IS_BELOW = 1 << 1,
        POINT_IS_LEFT = 1 << 2,
        POINT_IS_RIGHT = 1 << 3
    };
Constructor & Destructor Documentation
Canvas()
Canvas (const AbstractPainter *const painter, const Rect & canvasAreaAbs, const Rect & invalidatedAreaRel, uint8_t globalAlpha)
Canvas Constructor. Locks the framebuffer and prepares for drawing only in the allowed area which has been invalidated. The color depth of the LCD is taken into account.
Parameters
painter The painter used for drawing in the canvas.
canvasAreaAbs The canvas dimensions in absolute coordinates.
invalidatedAreaRel The area which should be updated in relative coordinates to the canvas area.
globalAlpha The alpha value to use when drawing in the canvas.
Note
Locks the framebuffer.
    : canvasPainter(painter),
      canvasAreaWidth(canvasAreaAbs.width),
      canvasAlpha(globalAlpha),
      rasterizer(),
      invalidatedAreaX(0),
      invalidatedAreaY(0),
      invalidatedAreaWidth(0),
      invalidatedAreaHeight(0),
      isPenDown(false),
      wasPenDown(false),
      previousX(0),
      previousY(0),
      previousOutside(0),
      penDownOutside(0),
      initialMoveToX(0),
      initialMoveToY(0)
{
    assert(CanvasWidgetRenderer::hasBuffer() && "No buffer allocated for CanvasWidgetRenderer drawing");
    assert(Rasterizer::POLY_BASE_SHIFT == 5 && "CanvasWidget assumes Q5 but Rasterizer uses a different setting");
    Rect dirtyArea = invalidatedAreaRel;
    dirtyAreaAbsolute = Rect(canvasAreaAbs.x + invalidatedAreaRel.x,
                             canvasAreaAbs.y + invalidatedAreaRel.y,
                             invalidatedAreaRel.width,
                             invalidatedAreaRel.height);
    // Transform rects to match framebuffer coordinates
    // This is needed if the display is rotated compared to the framebuffer
    DisplayTransformation::transformDisplayToFrameBuffer(dirtyArea, canvasAreaAbs);
    DisplayTransformation::transformDisplayToFrameBuffer(dirtyAreaAbsolute);
    // Re-size buffers for optimum memory buffer layout.
    rasterizer.reset(dirtyArea.x, dirtyArea.y);
    invalidatedAreaX = CWRUtil::toQ5<int>(dirtyArea.x);
    invalidatedAreaY = CWRUtil::toQ5<int>(dirtyArea.y);
    invalidatedAreaWidth = CWRUtil::toQ5<int>(dirtyArea.width);
    invalidatedAreaHeight = CWRUtil::toQ5<int>(dirtyArea.height);
    rasterizer.setMaxRender(dirtyAreaAbsolute.width, dirtyAreaAbsolute.height);
}
References Canvas::dirtyAreaAbsolute, CanvasWidgetRenderer::hasBuffer(), Rect::height, Canvas::invalidatedAreaHeight, Canvas::invalidatedAreaWidth, Canvas::invalidatedAreaX, Canvas::invalidatedAreaY, Canvas::rasterizer, DisplayTransformation::transformDisplayToFrameBuffer(), and Rect::width.
~Canvas()
virtual ~Canvas () inline virtual
Finalizes an instance of the Canvas class.
Note
Unlocks the framebuffer.
    {
    }
Member Function Documentation
close()
bool close ()
Closes the current shape so that the inside can be filled using a Painter.
Returns
True if there is enough memory to calculate the shape outline, false if there is too little memory.
{
    if (isPenDown)
    {
        if (previousOutside & penDownOutside)
        {
            // We are outside on the same side as we started. No need
            // to close the path, CWR will do this for us.
            //   lineTo(penDownX, penDownY);
        }
        else
        {
            if (previousOutside)
            {
                rasterizer.lineTo(previousX, previousY);
            }
            rasterizer.lineTo(initialMoveToX, initialMoveToY);
        }
    }
    isPenDown = false;
    return !rasterizer.wasOutlineTooComplex();
}
References Canvas::initialMoveToX, Canvas::initialMoveToY, Canvas::isPenDown, Canvas::penDownOutside, Canvas::previousOutside, Canvas::previousX, Canvas::previousY, and Canvas::rasterizer.
Referenced by Canvas::moveTo(), and Canvas::render().
cubicBezierTo()
void cubicBezierTo (float x0, float y0, float x1, float y1, float x2, float y2, float x, float y) inline
Draw a Cubic Bezier curve via x1,y1 and x2,y2 to x3,y3.
Parameters
x0 The start x coordinate.
y0 The start y coordinate.
x1 The first 'via' x coordinate.
y1 The first 'via' y coordinate.
x2 The second 'via' x coordinate.
y2 The second 'via' y coordinate.
x The end x coordinate.
y The end y coordinate.
    {
        recursiveCubicBezier(x0, y0, x1, y1, x2, y2, x, y, 0);
        lineTo(CWRUtil::toQ5<float>(x), CWRUtil::toQ5<float>(y));
    }
References Canvas::lineTo(), and Canvas::recursiveCubicBezier().
Referenced by CWRVectorRenderer::StrokeCanvas::strokeBezierCubic().
getFillingRule()
Rasterizer::FillingRule getFillingRule () const inline
Gets the filling rule being used when rendering the outline.
Returns
The filling rule.
See also
setFillingRule
    {
        return rasterizer.getFillingRule();
    }
References Canvas::rasterizer.
isOutside()
FORCE_INLINE_FUNCTION uint8_t isOutside (const CWRUtil::Q5 & x, const CWRUtil::Q5 & y, const CWRUtil::Q5 & width, const CWRUtil::Q5 & height) const inline private
    {
        return ((y < 0) ? (POINT_IS_ABOVE) : (y >= height ? POINT_IS_BELOW : 0)) |
               ((x < 0) ? (POINT_IS_LEFT) : (x >= width ? POINT_IS_RIGHT : 0));
    }
References Canvas::POINT_IS_ABOVE, Canvas::POINT_IS_BELOW, Canvas::POINT_IS_LEFT, and Canvas::POINT_IS_RIGHT.
Referenced by Canvas::lineTo(), and Canvas::moveTo().
lineTo() [1/2]
void lineTo (CWRUtil::Q5 x, CWRUtil::Q5 y) virtual
Draw line from the current (x, y) to the new (x, y) as part of the shape being drawn. As for moveTo, lineTo commands completely outside the drawing are are discarded.
Parameters
x The x coordinate for the pen position in CWRUtil::Q5 format.
y The y coordinate for the pen position in CWRUtil::Q5 format.
See also
CWRUtil::Q5, moveTo
Reimplemented in CWRVectorRenderer::StrokeCanvas.
{
    transformFrameBufferToDisplay(x, y);
    x -= invalidatedAreaX;
    y -= invalidatedAreaY;
    uint8_t outside = isOutside(x, y, invalidatedAreaWidth, invalidatedAreaHeight);
    if (!previousOutside)
    {
        rasterizer.lineTo(x, y);
    }
    else
    {
        if (!outside || !(previousOutside & outside))
        {
            // x,y is inside, or on another side compared to previous
            if (!isPenDown)
            {
                penDownOutside = previousOutside;
                rasterizer.moveTo(previousX, previousY);
                isPenDown = true;
                wasPenDown = true;
            }
            else
            {
                rasterizer.lineTo(previousX, previousY);
            }
            rasterizer.lineTo(x, y);
        }
        else
        {
            // Restrict "outside" to the same side as previous point.
            outside &= previousOutside;
        }
    }
    previousX = x;
    previousY = y;
    previousOutside = outside;
}
References Canvas::invalidatedAreaHeight, Canvas::invalidatedAreaWidth, Canvas::invalidatedAreaX, Canvas::invalidatedAreaY, Canvas::isOutside(), Canvas::isPenDown, Canvas::penDownOutside, Canvas::previousOutside, Canvas::previousX, Canvas::previousY, Canvas::rasterizer, Canvas::transformFrameBufferToDisplay(), and Canvas::wasPenDown.
Referenced by Canvas::cubicBezierTo(), Canvas::lineTo(), CWRVectorRenderer::StrokeCanvas::lineToWithTransform(), Canvas::quadraticBezierTo(), Canvas::recursiveCubicBezier(), and Canvas::recursiveQuadraticBezier().
lineTo() [2/2]
template<typename T > void lineTo (T x, T y) inline
Draw line from the current (x, y) to the new (x, y) as part of the shape being drawn. As for moveTo, lineTo commands completely outside the drawing are are discarded.
Template Parameters
T either int or float.
Parameters
x The x coordinate for the pen position.
y The y coordinate for the pen position.
    {
        lineTo(CWRUtil::toQ5<T>(x), CWRUtil::toQ5<T>(y));
    }
References Canvas::lineTo().
moveTo() [1/2]
void moveTo (CWRUtil::Q5 x, CWRUtil::Q5 y)
Move the current pen position to (x, y). If the pen is outside the drawing area, nothing is done, but the coordinates are saved in case the next operation is lineTo a coordinate which is inside (or on the opposite side of) the drawing area.
Parameters
x The x coordinate for the pen position in CWRUtil::Q5 format.
y The y coordinate for the pen position in CWRUtil::Q5 format.
{
    if (isPenDown)
    {
        if (!close())
        {
            return;
        }
    }
    transformFrameBufferToDisplay(x, y);
    x -= invalidatedAreaX;
    y -= invalidatedAreaY;
    const uint8_t outside = isOutside(x, y, invalidatedAreaWidth, invalidatedAreaHeight);
    if (outside)
    {
        isPenDown = false;
    }
    else
    {
        penDownOutside = outside;
        rasterizer.moveTo(x, y);
        isPenDown = true;
        wasPenDown = true;
    }
    initialMoveToX = x;
    initialMoveToY = y;
    previousX = x;
    previousY = y;
    previousOutside = outside;
}
References Canvas::close(), Canvas::initialMoveToX, Canvas::initialMoveToY, Canvas::invalidatedAreaHeight, Canvas::invalidatedAreaWidth, Canvas::invalidatedAreaX, Canvas::invalidatedAreaY, Canvas::isOutside(), Canvas::isPenDown, Canvas::penDownOutside, Canvas::previousOutside, Canvas::previousX, Canvas::previousY, Canvas::rasterizer, Canvas::transformFrameBufferToDisplay(), and Canvas::wasPenDown.
Referenced by Canvas::moveTo(), and CWRVectorRenderer::StrokeCanvas::moveToWithTransform().
moveTo() [2/2]
template<typename T > void moveTo (T x, T y) inline
Move the current pen position to (x, y). If the pen is outside (above or below) the drawing area, nothing is done, but the coordinates are saved in case the next operation is lineTo a coordinate which is inside (or on the opposite side of) the drawing area.
Template Parameters
T Either int or float.
Parameters
x The x coordinate for the pen position.
y The y coordinate for the pen position.
    {
        moveTo(CWRUtil::toQ5<T>(x), CWRUtil::toQ5<T>(y));
    }
References Canvas::moveTo().
quadraticBezierTo()
void quadraticBezierTo (float x0, float y0, const float x1, const float y1, const float x, const float y) inline
Draw a Quadratic Bezier curve via x1,y1 to x2,y2.
Parameters
x0 The start x coordinate.
y0 The start y coordinate.
x1 The 'via' x coordinate.
y1 The 'via' y coordinate.
x The end x coordinate.
y The end y coordinate.
    {
        recursiveQuadraticBezier(x0, y0, x1, y1, x, y, 0);
        lineTo(CWRUtil::toQ5<float>(x), CWRUtil::toQ5<float>(y));
    }
References Canvas::lineTo(), and Canvas::recursiveQuadraticBezier().
Referenced by CWRVectorRenderer::StrokeCanvas::strokeBezierQuad().
recursiveCubicBezier()
void recursiveCubicBezier (const float x1, const float y1, const float x2, const float y2, const float x3, const float y3, const float x4, const float y4, const unsigned level) private
{
    if (level > curve_recursion_limit)
    {
        return;
    }
    // Calculate all the mid-points of the line segments
    //----------------------
    const float x12 = (x1 + x2) / 2;
    const float y12 = (y1 + y2) / 2;
    const float x23 = (x2 + x3) / 2;
    const float y23 = (y2 + y3) / 2;
    const float x34 = (x3 + x4) / 2;
    const float y34 = (y3 + y4) / 2;
    const float x123 = (x12 + x23) / 2;
    const float y123 = (y12 + y23) / 2;
    const float x234 = (x23 + x34) / 2;
    const float y234 = (y23 + y34) / 2;
    const float x1234 = (x123 + x234) / 2;
    const float y1234 = (y123 + y234) / 2;
    if (level > 0) // Enforce subdivision first time
    {
        // Try to approximate the full cubic curve by a single straight line
        //------------------
        float dx = x4 - x1;
        float dy = y4 - y1;
        const float d2 = abs(((x2 - x4) * dy - (y2 - y4) * dx));
        const float d3 = abs(((x3 - x4) * dy - (y3 - y4) * dx));
        float da1, da2;
        if (d2 > curve_collinearity_epsilon && d3 > curve_collinearity_epsilon)
        {
            // Regular care
            //-----------------
            if ((d2 + d3) * (d2 + d3) <= m_distance_tolerance * (dx * dx + dy * dy))
            {
                // If the curvature doesn't exceed the distance_tolerance value
                // we tend to finish subdivisions.
                //----------------------
                // FGC: lint does not like this
                // if (m_angle_tolerance < curve_angle_tolerance_epsilon)
                // {
                //     lineTo(x1234, y1234);
                //     return;
                // }
                // Angle & Cusp Condition
                //----------------------
                const float a23 = atan2f(y3 - y2, x3 - x2);
                da1 = abs(a23 - atan2f(y2 - y1, x2 - x1));
                da2 = abs(atan2f(y4 - y3, x4 - x3) - a23);
                if (da1 >= PI)
                {
                    da1 = 2 * PI - da1;
                }
                if (da2 >= PI)
                {
                    da2 = 2 * PI - da2;
                }
                if (da1 + da2 < m_angle_tolerance)
                {
                    // Finally we can stop the recursion
                    //----------------------
                    lineTo(x1234, y1234);
                    return;
                }
                // FGC: lint does not like this
                // if (m_cusp_limit != 0.0f)
                // {
                //     if (da1 > m_cusp_limit)
                //     {
                //         lineTo(x2, y2);
                //         return;
                //     }
                //     if (da2 > m_cusp_limit)
                //     {
                //         lineTo(x3, y3);
                //         return;
                //     }
                // }
            }
        }
        else
        {
            if (d2 > curve_collinearity_epsilon)
            {
                // p1,p3,p4 are collinear, p2 is considerable
                //----------------------
                if (d2 * d2 <= m_distance_tolerance * (dx * dx + dy * dy))
                {
                    // FGC: lint does not like this
                    // if (m_angle_tolerance < curve_angle_tolerance_epsilon)
                    // {
                    //     lineTo(x1234, y1234);
                    //     return;
                    // }
                    // Angle Condition
                    //----------------------
                    da1 = abs(atan2f(y3 - y2, x3 - x2) - atan2f(y2 - y1, x2 - x1));
                    if (da1 >= PI)
                    {
                        da1 = 2 * PI - da1;
                    }
                    if (da1 < m_angle_tolerance)
                    {
                        lineTo(x2, y2);
                        lineTo(x3, y3);
                        return;
                    }
                    // FGC: lint does not like this
                    // if (m_cusp_limit != 0.0f)
                    // {
                    //     if (da1 > m_cusp_limit)
                    //     {
                    //         lineTo(x2, y2);
                    //         return;
                    //     }
                    // }
                }
            }
            else if (d3 > curve_collinearity_epsilon)
            {
                // p1,p2,p4 are collinear, p3 is considerable
                //----------------------
                if (d3 * d3 <= m_distance_tolerance * (dx * dx + dy * dy))
                {
                    // FGC: lint does not like this
                    // if (m_angle_tolerance < curve_angle_tolerance_epsilon)
                    // {
                    //     lineTo(x1234, y1234);
                    //     return;
                    // }
                    // Angle Condition
                    //----------------------
                    da1 = abs(atan2f(y4 - y3, x4 - x3) - atan2f(y3 - y2, x3 - x2));
                    if (da1 >= PI)
                    {
                        da1 = 2 * PI - da1;
                    }
                    if (da1 < m_angle_tolerance)
                    {
                        lineTo(x2, y2);
                        lineTo(x3, y3);
                        return;
                    }
                    // FGC: lint does not like this
                    // if (m_cusp_limit != 0.0f)
                    // {
                    //     if (da1 > m_cusp_limit)
                    //     {
                    //         lineTo(x3, y3);
                    //         return;
                    //     }
                    // }
                }
            }
            else
            {
                // Collinear case
                //-----------------
                dx = x1234 - (x1 + x4) / 2;
                dy = y1234 - (y1 + y4) / 2;
                if (dx * dx + dy * dy <= m_distance_tolerance)
                {
                    lineTo(x1234, y1234);
                    return;
                }
            }
        }
    }
    // Continue subdivision
    //----------------------
    recursiveCubicBezier(x1, y1, x12, y12, x123, y123, x1234, y1234, level + 1);
    recursiveCubicBezier(x1234, y1234, x234, y234, x34, y34, x4, y4, level + 1);
}
References touchgfx::abs(), curve_collinearity_epsilon, curve_recursion_limit, Canvas::lineTo(), m_angle_tolerance, m_distance_tolerance, touchgfx::PI, and Canvas::recursiveCubicBezier().
Referenced by Canvas::cubicBezierTo(), and Canvas::recursiveCubicBezier().
recursiveQuadraticBezier()
void recursiveQuadraticBezier (const float x1, const float y1, const float x2, const float y2, const float x3, const float y3, const unsigned level) private
{
    if (level > curve_recursion_limit)
    {
        return;
    }
    // Calculate all the mid-points of the line segments
    //----------------------
    const float x12 = (x1 + x2) / 2;
    const float y12 = (y1 + y2) / 2;
    const float x23 = (x2 + x3) / 2;
    const float y23 = (y2 + y3) / 2;
    const float x123 = (x12 + x23) / 2;
    const float y123 = (y12 + y23) / 2;
    float dx = x3 - x1;
    float dy = y3 - y1;
    const float d = abs(((x2 - x3) * dy - (y2 - y3) * dx));
    if (d > curve_collinearity_epsilon)
    {
        // Regular care
        //-----------------
        if (d * d <= m_distance_tolerance * (dx * dx + dy * dy))
        {
            // If the curvature doesn't exceed the distance_tolerance value
            // we tend to finish subdivisions.
            //----------------------
            // FGC: lint does not like this
            // if (m_angle_tolerance < curve_angle_tolerance_epsilon)
            // {
            //     lineTo(x123, y123);
            //     return;
            // }
            // Angle & Cusp Condition
            //----------------------
            float da = abs(atan2f(y3 - y2, x3 - x2) - atan2f(y2 - y1, x2 - x1));
            if (da >= PI)
            {
                da = 2 * PI - da;
            }
            if (da < m_angle_tolerance)
            {
                // Finally we can stop the recursion
                //----------------------
                lineTo(x123, y123);
                return;
            }
        }
    }
    else
    {
        // Collinear case
        //-----------------
        dx = x123 - (x1 + x3) / 2;
        dy = y123 - (y1 + y3) / 2;
        if (dx * dx + dy * dy <= m_distance_tolerance)
        {
            lineTo(x123, y123);
            return;
        }
    }
    // Continue subdivision
    //----------------------
    recursiveQuadraticBezier(x1, y1, x12, y12, x123, y123, level + 1);
    recursiveQuadraticBezier(x123, y123, x23, y23, x3, y3, level + 1);
}
References touchgfx::abs(), curve_collinearity_epsilon, curve_recursion_limit, Canvas::lineTo(), m_angle_tolerance, m_distance_tolerance, touchgfx::PI, and Canvas::recursiveQuadraticBezier().
Referenced by Canvas::quadraticBezierTo(), and Canvas::recursiveQuadraticBezier().
render()
bool render (uint8_t customAlpha = 255)
Render the graphical shape drawn using moveTo() and lineTo() with the given Painter. The shape is automatically closed, i.e. a lineTo() is automatically inserted connecting the current pen position with the initial pen position given in the first moveTo() command.
Parameters
customAlpha (Optional) Alpha to apply to the entire canvas. Useful if the canvas is part of a more complex container setup that needs to be faded. Default is solid.
Returns
true if the widget was rendered, false if insufficient memory was available to render the widget.
{
    const uint8_t alpha = LCD::div255(canvasAlpha * customAlpha);
    if (alpha == 0 || !wasPenDown)
    {
        return true; // Nothing. Done
    }
    // If the invalidated rect is too wide compared to the allocated buffer for CWR,
    // redrawing will not help. The CanvasWidget needs to know about this situation
    // and maybe try to divide the area vertically instead, but this has not been
    // implemented. And probably should not.
    if (!close())
    {
        return false;
    }
    // Create the rendering buffer
    uint8_t* RESTRICT framebuffer = reinterpret_cast<uint8_t*>(HAL::getInstance()->lockFrameBufferForRenderingMethod(canvasPainter->getRenderingMethod()));
    const int stride = HAL::lcd().framebufferStride();
    uint8_t xAdjust = 0;
    switch (HAL::lcd().framebufferFormat())
    {
    case Bitmap::BW:
        framebuffer += (dirtyAreaAbsolute.x / 8) + dirtyAreaAbsolute.y * stride;
        xAdjust = dirtyAreaAbsolute.x % 8;
        break;
    case Bitmap::GRAY2:
        framebuffer += (dirtyAreaAbsolute.x / 4) + dirtyAreaAbsolute.y * stride;
        xAdjust = dirtyAreaAbsolute.x % 4;
        break;
    case Bitmap::GRAY4:
        framebuffer += (dirtyAreaAbsolute.x / 2) + dirtyAreaAbsolute.y * stride;
        xAdjust = dirtyAreaAbsolute.x % 2;
        break;
    case Bitmap::RGB565:
        framebuffer += dirtyAreaAbsolute.x * 2 + dirtyAreaAbsolute.y * stride;
        break;
    case Bitmap::RGB888:
        framebuffer += dirtyAreaAbsolute.x * 3 + dirtyAreaAbsolute.y * stride;
        break;
    case Bitmap::RGBA2222:
    case Bitmap::BGRA2222:
    case Bitmap::ARGB2222:
    case Bitmap::ABGR2222:
    case Bitmap::L8:
        framebuffer += dirtyAreaAbsolute.x + dirtyAreaAbsolute.y * stride;
        break;
    case Bitmap::ARGB8888:
        framebuffer += dirtyAreaAbsolute.x * 4 + dirtyAreaAbsolute.y * stride;
        break;
    case Bitmap::BW_RLE:
    case Bitmap::A4:
    case Bitmap::CUSTOM:
        assert(false && "Unsupported bit depth");
    }
    const bool result = rasterizer.render(canvasPainter, framebuffer, stride, xAdjust, alpha);
    canvasPainter->tearDown();
    HAL::getInstance()->unlockFrameBuffer();
    return result;
}
References Bitmap::A4, Bitmap::ABGR2222, Bitmap::ARGB2222, Bitmap::ARGB8888, Bitmap::BGRA2222, Bitmap::BW, Bitmap::BW_RLE, Canvas::canvasAlpha, Canvas::canvasPainter, Canvas::close(), Bitmap::CUSTOM, Canvas::dirtyAreaAbsolute, LCD::div255(), HAL::getInstance(), Bitmap::GRAY2, Bitmap::GRAY4, Bitmap::L8, HAL::lcd(), Canvas::rasterizer, RESTRICT, Bitmap::RGB565, Bitmap::RGB888, Bitmap::RGBA2222, Canvas::wasPenDown, Rect::x, and Rect::y.
Referenced by CWRVectorRenderer::StrokeCanvas::strokeRender().
setFillingRule()
void setFillingRule (Rasterizer::FillingRule rule) inline
Sets the filling rule to be used when rendering the outline.
Parameters
rule The filling rule.
See also
getFillingRule
    {
        rasterizer.setFillingRule(rule);
    }
References Canvas::rasterizer.
Referenced by CWRVectorRenderer::StrokeCanvas::StrokeCanvas().
transformFrameBufferToDisplay()
void transformFrameBufferToDisplay (CWRUtil::Q5 & x, CWRUtil::Q5 & y) const private
{
    if (HAL::DISPLAY_ROTATION == rotate90)
    {
        CWRUtil::Q5 const tmpY = y;
        y = CWRUtil::toQ5<int>(canvasAreaWidth) - x;
        x = tmpY;
    }
}
References Canvas::canvasAreaWidth, HAL::DISPLAY_ROTATION, and touchgfx::rotate90.
Referenced by Canvas::lineTo(), and Canvas::moveTo().
wasOutlineTooComplex()
FORCE_INLINE_FUNCTION bool wasOutlineTooComplex () inline
Determines if we the outline was too complex to draw completely.
Returns
True if it was too complex, false if not.
    {
        return rasterizer.wasOutlineTooComplex();
    }
References Canvas::rasterizer.
Member Data Documentation
canvasAlpha
uint8_t canvasAlpha private
Referenced by Canvas::render().
canvasAreaWidth
int16_t canvasAreaWidth private
Referenced by Canvas::transformFrameBufferToDisplay().
canvasPainter
const AbstractPainter* const canvasPainter private
Referenced by Canvas::render().
dirtyAreaAbsolute
Rect dirtyAreaAbsolute private
Referenced by Canvas::Canvas(), and Canvas::render().
initialMoveToX
CWRUtil::Q5 initialMoveToX private
Referenced by Canvas::close(), and Canvas::moveTo().
initialMoveToY
CWRUtil::Q5 initialMoveToY private
Referenced by Canvas::close(), and Canvas::moveTo().
invalidatedAreaHeight
CWRUtil::Q5 invalidatedAreaHeight private
Referenced by Canvas::Canvas(), Canvas::lineTo(), and Canvas::moveTo().
invalidatedAreaWidth
CWRUtil::Q5 invalidatedAreaWidth private
Referenced by Canvas::Canvas(), Canvas::lineTo(), and Canvas::moveTo().
invalidatedAreaX
CWRUtil::Q5 invalidatedAreaX private
Referenced by Canvas::Canvas(), Canvas::lineTo(), and Canvas::moveTo().
invalidatedAreaY
CWRUtil::Q5 invalidatedAreaY private
Referenced by Canvas::Canvas(), Canvas::lineTo(), and Canvas::moveTo().
isPenDown
bool isPenDown private
Referenced by Canvas::close(), Canvas::lineTo(), and Canvas::moveTo().
penDownOutside
uint8_t penDownOutside private
Referenced by Canvas::close(), Canvas::lineTo(), and Canvas::moveTo().
previousOutside
uint8_t previousOutside private
Referenced by Canvas::close(), Canvas::lineTo(), and Canvas::moveTo().
previousX
CWRUtil::Q5 previousX private
Referenced by Canvas::close(), Canvas::lineTo(), and Canvas::moveTo().
previousY
CWRUtil::Q5 previousY private
Referenced by Canvas::close(), Canvas::lineTo(), and Canvas::moveTo().
rasterizer
Rasterizer rasterizer private
Referenced by Canvas::Canvas(), Canvas::close(), Canvas::getFillingRule(), Canvas::lineTo(), Canvas::moveTo(), Canvas::render(), Canvas::setFillingRule(), and Canvas::wasOutlineTooComplex().
wasPenDown
bool wasPenDown private
Referenced by Canvas::lineTo(), Canvas::moveTo(), and Canvas::render().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/Canvas.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/Canvas.cpp