Battery Simulator Documentation: Color
Color
#include "Color.hpp"
Static Public Member Functions
static FORCE_INLINE_FUNCTION uint8_t getBlue (colortype color)
static FORCE_INLINE_FUNCTION uint8_t getBlueFromRGB565 (uint16_t color)
static FORCE_INLINE_FUNCTION colortype getColorFromHSL (uint8_t hue, uint8_t saturation, uint8_t luminance)
static FORCE_INLINE_FUNCTION colortype getColorFromHSV (uint8_t hue, uint8_t saturation, uint8_t value)
static FORCE_INLINE_FUNCTION colortype getColorFromRGB (uint8_t red, uint8_t green, uint8_t blue)
static FORCE_INLINE_FUNCTION uint8_t getGreen (colortype color)
static FORCE_INLINE_FUNCTION uint8_t getGreenFromRGB565 (uint16_t color)
static FORCE_INLINE_FUNCTION void getHSLFromColor (colortype color, uint8_t &hue, uint8_t &saturation, uint8_t &luminance)
static FORCE_INLINE_FUNCTION void getHSLFromHSV (uint8_t hsv_hue, uint8_t hsv_saturation, uint8_t hsv_value, uint8_t &hsl_hue, uint8_t &hsl_saturation, uint8_t &hsl_luminance)
static FORCE_INLINE_FUNCTION void getHSLFromRGB (uint8_t red, uint8_t green, uint8_t blue, uint8_t &hue, uint8_t &saturation, uint8_t &luminance)
static FORCE_INLINE_FUNCTION void getHSVFromColor (colortype color, uint8_t &hue, uint8_t &saturation, uint8_t &value)
static FORCE_INLINE_FUNCTION void getHSVFromHSL (uint8_t hsl_hue, uint8_t hsl_saturation, uint8_t hsl_luminance, uint8_t &hsv_hue, uint8_t &hsv_saturation, uint8_t &hsv_value)
static void getHSVFromRGB (uint8_t red, uint8_t green, uint8_t blue, uint8_t &hue, uint8_t &saturation, uint8_t &value)
static FORCE_INLINE_FUNCTION uint8_t getRed (colortype color)
static FORCE_INLINE_FUNCTION uint8_t getRedFromRGB565 (uint16_t color)
static FORCE_INLINE_FUNCTION void getRGBFromColor (colortype color, uint8_t &red, uint8_t &green, uint8_t &blue)
static FORCE_INLINE_FUNCTION void getRGBFromHSL (uint8_t hue, uint8_t saturation, uint8_t luminance, uint8_t &red, uint8_t &green, uint8_t &blue)
static void getRGBFromHSV (uint8_t hue, uint8_t saturation, uint8_t value, uint8_t &red, uint8_t &green, uint8_t &blue)
static FORCE_INLINE_FUNCTION uint32_t rgb565toXrgb8888 (uint16_t rgb565)
Detailed Description
Contains functionality for color conversion.
Member Function Documentation
getBlue()
static FORCE_INLINE_FUNCTION uint8_t getBlue (colortype color) inline static
Gets the blue color part of a color.
Parameters
color The color value.
Returns
The blue part of the color (0 to 255).
    {
        return color;
    }
Referenced by Color::getHSLFromColor(), Color::getHSVFromColor(), LCD1bpp::getNativeColor(), LCD2bpp::getNativeColor(), LCD4bpp::getNativeColor(), Color::getRGBFromColor(), touchgfx::paint::argb8888::lineFromColor(), touchgfx::paint::rgb888::lineFromColor(), PainterABGR2222::setColor(), PainterARGB2222::setColor(), PainterARGB8888::setColor(), PainterBGRA2222::setColor(), PainterRGB888::setColor(), PainterRGBA2222::setColor(), and PainterXRGB8888::setColor().
getBlueFromRGB565()
static FORCE_INLINE_FUNCTION uint8_t getBlueFromRGB565 (uint16_t color) inline static
Gets the blue color part of a 16bpp color also known as RGB565. The blue part (5 bits) is extracted and scaled to the full 0-255 byte range.
Parameters
color The color value in RGB565.
Returns
The blue part of the color (0 to 255).
    {
        const uint8_t blue = color << 3;
        return blue | (blue >> 5);
    }
Referenced by LCD32bpp::alphaBlend565(), LCD32bpp::alphaBlend565_premul(), touchgfx::paint::rgb565::lineFromL8RGB888(), touchgfx::paint::argb8888::lineFromRGB565(), PainterARGB8888L8Bitmap::paint(), Color::rgb565toXrgb8888(), and HALSDL2::scaleTo24bpp().
getColorFromHSL()
static FORCE_INLINE_FUNCTION colortype getColorFromHSL (uint8_t hue, uint8_t saturation, uint8_t luminance) inline static
Convert a given color from HSV (Hue, Saturation, Value) to colortype.
Parameters
hue The input Hue (0 to 255).
saturation The input Saturation (0 to 255).
luminance The input Value (0 to 255).
Returns
The colortype color.
Note
The conversion is an approximation.
    {
        uint8_t red, green, blue;
        getRGBFromHSL(hue, saturation, luminance, red, green, blue);
        return getColorFromRGB(red, green, blue);
    }
References Color::getColorFromRGB(), and Color::getRGBFromHSL().
getColorFromHSV()
static FORCE_INLINE_FUNCTION colortype getColorFromHSV (uint8_t hue, uint8_t saturation, uint8_t value) inline static
Convert a given color from HSV (Hue, Saturation, Value) to colortype.
Parameters
hue The input Hue (0 to 255).
saturation The input Saturation (0 to 255).
value The input Value (0 to 255).
Returns
The colortype color.
Note
The conversion is an approximation.
    {
        uint8_t red, green, blue;
        getRGBFromHSV(hue, saturation, value, red, green, blue);
        return getColorFromRGB(red, green, blue);
    }
References Color::getColorFromRGB(), and Color::getRGBFromHSV().
getColorFromRGB()
static FORCE_INLINE_FUNCTION colortype getColorFromRGB (uint8_t red, uint8_t green, uint8_t blue) inline static
Generates a color representation to be used on the LCD, based on 24 bit RGB values. The embedded alpha value is set to 255.
Parameters
red Value of the red part (0 to 255).
green Value of the green part (0 to 255).
blue Value of the blue part (0 to 255).
Returns
The color representation depending on LCD color format.
    {
        return 0xFF000000 | (red << 16) | (green << 8) | (blue);
    }
Referenced by Keyboard::Keyboard(), ModalWindow::ModalWindow(), Screen1ViewBase::Screen1ViewBase(), Color::getColorFromHSL(), and Color::getColorFromHSV().
getGreen()
static FORCE_INLINE_FUNCTION uint8_t getGreen (colortype color) inline static
Gets the green color part of a color.
Parameters
color The color value.
Returns
The green part of the color (0 to 255).
    {
        return color >> 8;
    }
Referenced by Color::getHSLFromColor(), Color::getHSVFromColor(), LCD1bpp::getNativeColor(), LCD2bpp::getNativeColor(), LCD4bpp::getNativeColor(), Color::getRGBFromColor(), touchgfx::paint::argb8888::lineFromColor(), touchgfx::paint::rgb888::lineFromColor(), PainterABGR2222::setColor(), PainterARGB2222::setColor(), PainterARGB8888::setColor(), PainterBGRA2222::setColor(), PainterRGB888::setColor(), PainterRGBA2222::setColor(), and PainterXRGB8888::setColor().
getGreenFromRGB565()
static FORCE_INLINE_FUNCTION uint8_t getGreenFromRGB565 (uint16_t color) inline static
Gets the green color part of a 16bpp color also known as RGB565. The green part (6 bits) is extracted and scaled to the full 0-255 byte range.
Parameters
color The color value in RGB565.
Returns
The green part of the color (0 to 255).
    {
        const uint8_t green = (color >> 3) & 0xFC;
        return green | (green >> 6);
    }
Referenced by LCD32bpp::alphaBlend565(), LCD32bpp::alphaBlend565_premul(), touchgfx::paint::rgb565::lineFromL8RGB888(), touchgfx::paint::argb8888::lineFromRGB565(), PainterARGB8888L8Bitmap::paint(), Color::rgb565toXrgb8888(), and HALSDL2::scaleTo24bpp().
getHSLFromColor()
static FORCE_INLINE_FUNCTION void getHSLFromColor (colortype color, uint8_t & hue, uint8_t & saturation, uint8_t & luminance) inline static
Convert a given colortype color to HSV (Hue, Saturation, Value).
Parameters
color The input color.
[out] hue The output Hue (0 to 255).
[out] saturation The output Saturation (0 to 255).
[out] luminance The output Value (0 to 255).
Note
The conversion is an approximation.
    {
        getHSLFromRGB(getRed(color), getGreen(color), getBlue(color), hue, saturation, luminance);
    }
References Color::getBlue(), Color::getGreen(), Color::getHSLFromRGB(), and Color::getRed().
getHSLFromHSV()
static FORCE_INLINE_FUNCTION void getHSLFromHSV (uint8_t hsv_hue, uint8_t hsv_saturation, uint8_t hsv_value, uint8_t & hsl_hue, uint8_t & hsl_saturation, uint8_t & hsl_luminance) inline static
Convert HSV (Hue, Saturation, Value) to HSL (Hue, Saturation, Luminance).
Parameters
hsv_hue The input HSV hue (0 to 255).
hsv_saturation The input HSV saturation (0 to 255).
hsv_value The input HSV value (0 to 255).
[out] hsl_hue The output HSL hue (0 to 255).
[out] hsl_saturation The output HSL saturation (0 to 255).
[out] hsl_luminance The output HSL luminance (0 to 255).
    {
        hsl_hue = hsv_hue;
        uint16_t luminance2 = (hsv_value * (510 - hsv_saturation)) / 255;
        hsl_luminance = luminance2 >> 1;
        hsl_saturation = (hsl_luminance == 0 || hsl_luminance == 255) ? 0 : (uint8_t)(((hsv_value * 2 - luminance2) * 255) / MIN(luminance2, 510 - luminance2));
    }
References MIN.
Referenced by Color::getHSLFromRGB().
getHSLFromRGB()
static FORCE_INLINE_FUNCTION void getHSLFromRGB (uint8_t red, uint8_t green, uint8_t blue, uint8_t & hue, uint8_t & saturation, uint8_t & luminance) inline static
Convert a given color from RGB (Red, Green, Blue) to HSV (Hue, Saturation, Value).
Parameters
red The input Red (0 to 255).
green The input Green (0 to 255).
blue The input Blue (0 to 255).
[out] hue The output Hue (0 to 255).
[out] saturation The output Saturation (0 to 255).
[out] luminance The output Value (0 to 255).
Note
The conversion is an approximation.
    {
        uint8_t hsv_hue, hsv_saturation, hsv_value;
        getHSVFromRGB(red, green, blue, hsv_hue, hsv_saturation, hsv_value);
        getHSLFromHSV(hsv_hue, hsv_saturation, hsv_value, hue, saturation, luminance);
    }
References Color::getHSLFromHSV(), and Color::getHSVFromRGB().
Referenced by Color::getHSLFromColor().
getHSVFromColor()
static FORCE_INLINE_FUNCTION void getHSVFromColor (colortype color, uint8_t & hue, uint8_t & saturation, uint8_t & value) inline static
Convert a given colortype color to HSV (Hue, Saturation, Value).
Parameters
color The input color.
[out] hue The output Hue (0 to 255).
[out] saturation The output Saturation (0 to 255).
[out] value The output Value (0 to 255).
Note
The conversion is an approximation.
    {
        getHSVFromRGB(getRed(color), getGreen(color), getBlue(color), hue, saturation, value);
    }
References Color::getBlue(), Color::getGreen(), Color::getHSVFromRGB(), and Color::getRed().
getHSVFromHSL()
static FORCE_INLINE_FUNCTION void getHSVFromHSL (uint8_t hsl_hue, uint8_t hsl_saturation, uint8_t hsl_luminance, uint8_t & hsv_hue, uint8_t & hsv_saturation, uint8_t & hsv_value) inline static
Convert HSL (Hue, Saturation, Luminance) to HSV (Hue, Saturation, Value).
Parameters
hsl_hue The input HSL hue (0 to 255).
hsl_saturation The input HSL saturation (0 to 255).
hsl_luminance The input HSL luminance (0 to 255).
[out] hsv_hue The output HSV hue (0 to 255).
[out] hsv_saturation The output HSV saturation (0 to 255).
[out] hsv_value The output HSV value (0 to 255).
    {
        hsv_hue = hsl_hue;
        hsv_value = hsl_luminance + LCD::div255(hsl_saturation * MIN(hsl_luminance, 255 - hsl_luminance));
        hsv_saturation = hsv_value == 0 ? 0 : 510 - ((hsl_luminance * 510) / hsv_value);
    }
References LCD::div255(), and MIN.
Referenced by Color::getRGBFromHSL().
getHSVFromRGB()
static void getHSVFromRGB (uint8_t red, uint8_t green, uint8_t blue, uint8_t & hue, uint8_t & saturation, uint8_t & value) inline static
Convert a given color from RGB (Red, Green, Blue) to HSV (Hue, Saturation, Value).
Parameters
red The input Red (0 to 255).
green The input Green (0 to 255).
blue The input Blue (0 to 255).
[out] hue The output Hue (0 to 255).
[out] saturation The output Saturation (0 to 255).
[out] value The output Value (0 to 255).
Note
The conversion is an approximation.
    {
        const uint8_t rgbMin = MIN(MIN(red, green), blue);
        const uint8_t rgbMax = MAX(MAX(red, green), blue);
        const uint8_t rgbRange = rgbMax - rgbMin;
        value = rgbMax;
        if (value == 0)
        {
            hue = 0;
            saturation = 0;
            return;
        }
        saturation = 255 * rgbRange / value;
        if (saturation == 0)
        {
            hue = 0;
        }
        else if (rgbMax == red)
        {
            if (green < blue)
            {
                hue = 0 + (42 * (green - blue) + rgbRange / 2) / rgbRange; // [0-42; 0] = [214; 0]
            }
            else
            {
                hue = 0 + (43 * (green - blue) + rgbRange / 2) / rgbRange; // [0; 0+43] = [0; 43]
            }
        }
        else if (rgbMax == green)
        {
            if (blue < red)
            {
                hue = 86 + (43 * (blue - red) + rgbRange / 2) / rgbRange; // [86-43; 86] = [43; 86]
            }
            else
            {
                hue = 86 + (42 * (blue - red) + rgbRange / 2) / rgbRange; // [86; 86+42] = [86; 128]
            }
        }
        else
        {
            hue = 171 + (43 * (red - green) + rgbRange / 2) / rgbRange; // [171-43; 171+43] = [128; 214]
        }
    }
References MAX, and MIN.
Referenced by Color::getHSLFromRGB(), and Color::getHSVFromColor().
getRed()
static FORCE_INLINE_FUNCTION uint8_t getRed (colortype color) inline static
Gets the red color part of a color.
Parameters
color The color value.
Returns
The red part of the color (0 to 255).
    {
        return color >> 16;
    }
Referenced by Color::getHSLFromColor(), Color::getHSVFromColor(), LCD1bpp::getNativeColor(), LCD2bpp::getNativeColor(), LCD4bpp::getNativeColor(), Color::getRGBFromColor(), touchgfx::paint::argb8888::lineFromColor(), touchgfx::paint::rgb888::lineFromColor(), PainterABGR2222::setColor(), PainterARGB2222::setColor(), PainterARGB8888::setColor(), PainterBGRA2222::setColor(), PainterRGB888::setColor(), PainterRGBA2222::setColor(), and PainterXRGB8888::setColor().
getRedFromRGB565()
static FORCE_INLINE_FUNCTION uint8_t getRedFromRGB565 (uint16_t color) inline static
Gets the red color part of a 16bpp color also known as RGB565. The red part (5 bits) is extracted and scaled to the full 0-255 byte range.
Parameters
color The color value in RGB565.
Returns
The red part of the color (0 to 255).
    {
        const uint8_t red = (color >> 8) & 0xF8;
        return red | (red >> 5);
    }
Referenced by LCD32bpp::alphaBlend565(), LCD32bpp::alphaBlend565_premul(), touchgfx::paint::rgb565::lineFromL8RGB888(), touchgfx::paint::argb8888::lineFromRGB565(), PainterARGB8888L8Bitmap::paint(), Color::rgb565toXrgb8888(), and HALSDL2::scaleTo24bpp().
getRGBFromColor()
static FORCE_INLINE_FUNCTION void getRGBFromColor (colortype color, uint8_t & red, uint8_t & green, uint8_t & blue) inline static
Split a given colortype color to its RGB (Red, Green, Blue) components.
Parameters
color The input color.
[out] red The output Red (0 to 255).
[out] green The output Green (0 to 255).
[out] blue The output Blue (0 to 255).
    {
        red = getRed(color);
        green = getGreen(color);
        blue = getBlue(color);
    }
References Color::getBlue(), Color::getGreen(), and Color::getRed().
getRGBFromHSL()
static FORCE_INLINE_FUNCTION void getRGBFromHSL (uint8_t hue, uint8_t saturation, uint8_t luminance, uint8_t & red, uint8_t & green, uint8_t & blue) inline static
Convert a given color from HSV (Hue, Saturation, Value) to RGB (Red, Green, Blue).
Parameters
hue The input Hue (0 to 255).
saturation The input Saturation (0 to 255).
luminance The input Value (0 to 255).
[out] red The output Red (0 to 255).
[out] green The output Green (0 to 255).
[out] blue The output Blue (0 to 255).
Note
The conversion is an approximation.
    {
        uint8_t hsv_hue, hsv_saturation, hsv_value;
        getHSVFromHSL(hue, saturation, luminance, hsv_hue, hsv_saturation, hsv_value);
        getRGBFromHSV(hsv_hue, hsv_saturation, hsv_value, red, green, blue);
    }
References Color::getHSVFromHSL(), and Color::getRGBFromHSV().
Referenced by Color::getColorFromHSL().
getRGBFromHSV()
static void getRGBFromHSV (uint8_t hue, uint8_t saturation, uint8_t value, uint8_t & red, uint8_t & green, uint8_t & blue) inline static
Convert a given color from HSV (Hue, Saturation, Value) to RGB (Red, Green, Blue).
Parameters
hue The input Hue (0 to 255).
saturation The input Saturation (0 to 255).
value The input Value (0 to 255).
[out] red The output Red (0 to 255).
[out] green The output Green (0 to 255).
[out] blue The output Blue (0 to 255).
Note
The conversion is an approximation.
    {
        if (saturation == 0)
        {
            red = green = blue = value;
            return;
        }
        const uint8_t region = (hue * 6) >> 8;
        const int next_region_start = ((((region + 1) << 8) + 5) / 6); // Can go up to 256, uint8_t not enough
        const uint8_t region_size = next_region_start - (((region << 8) + 5) / 6);
        const uint8_t remainder = 255 - (next_region_start - hue) * 255 / region_size;
        const uint8_t p = LCD::div255(value * (255 - saturation));
        const uint8_t q = LCD::div255(value * (255 - LCD::div255(saturation * remainder)));
        const uint8_t t = LCD::div255(value * (255 - LCD::div255(saturation * (255 - remainder))));
        switch (region)
        {
        case 0:
            red = value;
            green = t;
            blue = p;
            break;
        case 1:
            red = q;
            green = value;
            blue = p;
            break;
        case 2:
            red = p;
            green = value;
            blue = t;
            break;
        case 3:
            red = p;
            green = q;
            blue = value;
            break;
        case 4:
            red = t;
            green = p;
            blue = value;
            break;
        default:
            red = value;
            green = p;
            blue = q;
            break;
        }
    }
References LCD::div255().
Referenced by Color::getColorFromHSV(), and Color::getRGBFromHSL().
rgb565toXrgb8888()
static FORCE_INLINE_FUNCTION uint32_t rgb565toXrgb8888 (uint16_t rgb565) inline static
Convert 16bit RGB565 color to 32bit ARGB8888 color by expanding the 5,6,5 colors to full 8,8, 8 colors. The alpha value is set to zero.
Parameters
rgb565 The 16bit RGB565 color.
Returns
The 32bit color value.
See also
getRedFromRGB565, getGreenFromRGB565, getBlueFromRGB565
    {
        return (getRedFromRGB565(rgb565) << 16) | (getGreenFromRGB565(rgb565) << 8) | getBlueFromRGB565(rgb565);
    }
References Color::getBlueFromRGB565(), Color::getGreenFromRGB565(), and Color::getRedFromRGB565().
Referenced by PainterXRGB8888Bitmap::paint(), and PainterXRGB8888L8Bitmap::paint().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/Color.hpp