Battery Simulator Documentation: PainterXRGB8888Bitmap
PainterXRGB8888Bitmap
#include "PainterXRGB8888Bitmap.hpp"
Public Member Functions
PainterXRGB8888Bitmap (const Bitmap &bmp=Bitmap(BITMAP_INVALID))
virtual void paint (uint8_t *destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const
virtual void setBitmap (const Bitmap &bmp)
virtual bool setup (const Rect &widgetRect) const
Public Member Functions inherited from AbstractPainterARGB8888
AbstractPainterARGB8888 ()
Public Member Functions inherited from AbstractPainter
AbstractPainter ()
virtual ~AbstractPainter ()
void framebufferToDisplay (int16_t &widgetX, int16_t &widgetY) const
virtual HAL::RenderingMethod getRenderingMethod () const
virtual void tearDown () const
Public Member Functions inherited from AbstractPainterBitmap
AbstractPainterBitmap (const Bitmap &bmp=Bitmap(BITMAP_INVALID))
virtual ~AbstractPainterBitmap ()
Bitmap getBitmap () const
void getOffset (int16_t &x, int16_t &y)
bool getTiled () const
virtual void setOffset (int16_t x, int16_t y)
virtual void setTiled (bool tiled)
Additional Inherited Members
Protected Member Functions inherited from AbstractPainterBitmap
bool adjustBitmapXY (int16_t &bitmapX, int16_t &bitmapY, int16_t &offset, int16_t &count) const
void updateBitmapOffsets (int16_t widgetWidth) const
Static Protected Member Functions inherited from AbstractPainter
static FORCE_INLINE_FUNCTION bool compatibleFramebuffer (Bitmap::BitmapFormat format)
Protected Attributes inherited from AbstractPainter
int16_t widgetWidth
The width of the widget on screen, used by framebufferToDisplay()
Protected Attributes inherited from AbstractPainterBitmap
Bitmap bitmap
The bitmap to be used when painting.
const uint8_t * bitmapData
Pointer to the bitmap data.
Bitmap::BitmapFormat bitmapFormat
Copy of the bitmap format (for speed reasons)
Rect bitmapRect
Bitmap rectangle translated to framebuffer coordinates.
bool isTiled
True if bitmap should be tiled, false if not.
int16_t xOffset
The x offset of the bitmap.
int16_t yOffset
The y offset of the bitmap.
Detailed Description
PainterXRGB8888Bitmap will take the color for a given point in the shape from a bitmap. Please be aware, the the bitmap is used by the CanvasWidgetRenderer (not Shape), so any rotation you might specify for a Canvas Widget (e.g. Shape) is not applied to the bitmap as CWR is not aware of this rotation.
See also
AbstractPainter
Constructor & Destructor Documentation
PainterXRGB8888Bitmap()
PainterXRGB8888Bitmap (const Bitmap & bmp = Bitmap(BITMAP_INVALID)) inline
Constructor.
Parameters
bmp (Optional) The bitmap to use in the painter.
        : AbstractPainterARGB8888(), AbstractPainterBitmap(bmp)
    {
    }
Member Function Documentation
paint()
void paint (uint8_t * destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const virtual
Paints a streak of pixels (all with the same alpha) in the framebuffer. The first pixel to paint is at 'offset' relative to 'destination' (to be able to support 1bpp, 2bpp and 4bpp). The first pixel to paint is at the given 'widgetX', 'widgetY' coordinate. The number of pixels to paint is 'count' and the alpha to apply is 'alpha'.
Note that the widgetX, widgetY is relative to the widget in the framebuffer, not the display. To convert the coordinate to display widget coordinates, use framebufferToDisplay().
Parameters
[in] destination If non-null, the pointer.
offset The offset to add to the destination.
widgetX The widget x coordinate.
widgetY The widget y coordinate.
count Number of pixels.
alpha The alpha of the pixels.
See also
AbstractPainter::setup, AbstractPainter::tearDown, AbstractPainter::framebufferToDisplay
Implements AbstractPainter.
{
    if (!adjustBitmapXY(widgetX, widgetY, offset, count))
    {
        return;
    }
    uint32_t* RESTRICT framebuffer = reinterpret_cast<uint32_t*>(destination) + offset;
    const uint32_t* const lineEnd = framebuffer + count;
    const int32_t rowSkip = widgetY * bitmapRect.width;
    int16_t bitmapAvailable = bitmapRect.width - widgetX;
    if (bitmapFormat == Bitmap::ARGB8888)
    {
        const uint32_t* const bitmapLineStart = reinterpret_cast<const uint32_t*>(bitmapData) + rowSkip;
        const uint32_t* bitmapPointer = bitmapLineStart + widgetX;
        do
        {
            const int16_t length = MIN(bitmapAvailable, count);
            const uint32_t* const chunkend = framebuffer + length;
            count -= length;
            do
            {
                const uint8_t srcAlpha = (*bitmapPointer) >> 24;
                const uint8_t a = LCD::div255(alpha * srcAlpha);
                if (a == 0xFF)
                {
                    *framebuffer = *bitmapPointer;
                }
                else
                {
                    *framebuffer = LCD32bpp_XRGB8888::blendRgb888withXrgb8888(reinterpret_cast<const uint8_t*>(bitmapPointer), *framebuffer, a, 0xFF - a);
                }
                bitmapPointer++;
            } while (++framebuffer < chunkend);
            bitmapPointer = bitmapLineStart;
            bitmapAvailable = bitmapRect.width;
        } while (framebuffer < lineEnd);
    }
    else if (bitmapFormat == Bitmap::RGB888)
    {
        const uint8_t* const bitmapLineStart = reinterpret_cast<const uint8_t*>(bitmapData) + rowSkip * 3;
        const uint8_t* bitmapPointer = bitmapLineStart + widgetX * 3;
        do
        {
            const int16_t length = MIN(bitmapAvailable, count);
            const uint32_t* const chunkend = framebuffer + length;
            count -= length;
            if (alpha == 0xFF)
            {
                do
                {
                    *framebuffer = LCD32bpp_XRGB8888::rgb888toXrgb8888(bitmapPointer);
                    bitmapPointer += 3;
                } while (++framebuffer < chunkend);
            }
            else
            {
                do
                {
                    *framebuffer = LCD32bpp_XRGB8888::blendRgb888withXrgb8888(bitmapPointer, *framebuffer, alpha, 0xFF - alpha);
                    bitmapPointer += 3;
                } while (++framebuffer < chunkend);
            }
            bitmapPointer = bitmapLineStart;
            bitmapAvailable = bitmapRect.width;
        } while (framebuffer < lineEnd);
    }
    else // if (bitmapFormat == Bitmap::RGB565)
    {
        const uint16_t* const bitmapLineStart = reinterpret_cast<const uint16_t*>(bitmapData) + (widgetY * bitmapRect.width);
        const uint16_t* bitmapPointer = bitmapLineStart + widgetX;
        do
        {
            const int16_t length = MIN(bitmapAvailable, count);
            const uint32_t* const chunkend = framebuffer + length;
            count -= length;
            if (alpha == 0xFF)
            {
                do
                {
                    *framebuffer = Color::rgb565toXrgb8888(*bitmapPointer++);
                } while (++framebuffer < chunkend);
            }
            else
            {
                do
                {
                    *framebuffer = LCD32bpp_XRGB8888::blendRgb565withXrgb8888(*bitmapPointer++, *framebuffer, alpha, 0xFF - alpha);
                } while (++framebuffer < chunkend);
            }
            bitmapPointer = bitmapLineStart;
            bitmapAvailable = bitmapRect.width;
        } while (framebuffer < lineEnd);
    }
}
References AbstractPainterBitmap::adjustBitmapXY(), Bitmap::ARGB8888, AbstractPainterBitmap::bitmapData, AbstractPainterBitmap::bitmapFormat, AbstractPainterBitmap::bitmapRect, LCD32bpp_XRGB8888::blendRgb565withXrgb8888(), LCD32bpp_XRGB8888::blendRgb888withXrgb8888(), LCD::div255(), MIN, RESTRICT, Color::rgb565toXrgb8888(), Bitmap::RGB888, LCD32bpp_XRGB8888::rgb888toXrgb8888(), and Rect::width.
setBitmap()
void setBitmap (const Bitmap & bmp) virtual
Sets a bitmap to be used when drawing the CanvasWidget.
Parameters
bmp The bitmap.
Reimplemented from AbstractPainterBitmap.
{
    AbstractPainterBitmap::setBitmap(bmp);
    assert((bitmap.getId() == BITMAP_INVALID || bitmapFormat == Bitmap::RGB565 || bitmapFormat == Bitmap::RGB888 || bitmapFormat == Bitmap::ARGB8888) && !bitmap.getExtraData() && "PainterXRGB8888Bitmap only works with RGB565 (without alpha), RGB888 and ARGB8888 bitmaps");
    assert(bitmap.getId() == BITMAP_INVALID || bitmapData);
}
References Bitmap::ARGB8888, touchgfx::BITMAP_INVALID, AbstractPainterBitmap::bitmapData, AbstractPainterBitmap::bitmapFormat, Bitmap::RGB565, Bitmap::RGB888, and AbstractPainterBitmap::setBitmap().
setup()
virtual bool setup (const Rect & widgetRect) const inline virtual
This function is called before any actual paint operation is started. This allows the painter to initialize variables and optional dma queues. This happens before the first scan line segment is being drawn. If the painter is unable to draw, e.g. no bitmap assigned to a bitmap painter, 'false' should be returned.
Parameters
widgetRect The widget rectangle.
Returns
True if the painter is ready to paint, false otherwise.
See also
AbstractPainter::paint, AbstractPainter::tearDown
Reimplemented from AbstractPainter.
    {
        if (!AbstractPainterARGB8888::setup(widgetRect))
        {
            return false;
        }
        updateBitmapOffsets(widgetWidth);
        return bitmap.getId() != BITMAP_INVALID;
    }
References touchgfx::BITMAP_INVALID, AbstractPainter::setup(), AbstractPainterBitmap::updateBitmapOffsets(), and AbstractPainter::widgetWidth.
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/PainterXRGB8888Bitmap.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/PainterXRGB8888Bitmap.cpp