Battery Simulator Documentation: AnimatedImage
AnimatedImage
#include "AnimatedImage.hpp"
Public Member Functions
AnimatedImage (const BitmapId &start, const BitmapId &end, const uint8_t &updateInterval=1)
AnimatedImage (const uint8_t &updateInterval=1)
virtual void handleTickEvent ()
bool isAnimatedImageRunning () const
bool isReverse ()
virtual void pauseAnimation ()
virtual void setBitmap (const Bitmap &bmp)
virtual void setBitmapEnd (const Bitmap &bmp)
void setBitmaps (BitmapId start, BitmapId end)
void setDoneAction (GenericCallback< const AnimatedImage & > &callback)
void setUpdateTicksInterval (uint8_t updateInterval)
virtual void startAnimation (const bool rev, const bool reset=false, const bool loop=false)
virtual void stopAnimation ()
Public Member Functions inherited from Image
Image (const Bitmap &bmp=Bitmap())
virtual void draw (const Rect &invalidatedArea) const
uint8_t getAlpha () const
Bitmap getBitmap () const
BitmapId getBitmapId () const
virtual Rect getSolidRect () const
virtual void invalidateContent () const
void setAlpha (uint8_t newAlpha)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
GenericCallback< const AnimatedImage & > * animationDoneAction
Pointer to the callback to be executed when animation is done.
BitmapId endId
Id of last bitmap in animation.
bool loopAnimation
If true, continuously loop animation.
bool reverse
If true, run in reverse direction (last to first).
bool running
If true, animation is running.
BitmapId startId
Id of first bitmap in animation.
uint8_t ticksSinceUpdate
Number of ticks since last animation update.
uint8_t updateTicksInterval
Number of ticks between each animation update (image change).
Protected Attributes inherited from Image
uint8_t alpha
The Alpha for this image.
Bitmap bitmap
The Bitmap to display.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A widget capable of basic animation using a range of bitmaps. The AnimatedImage is capable of running the animation from start to end or, in reverse order, end to start. It is capable of doing a single animation or looping the animation until stopped or paused.
Constructor & Destructor Documentation
AnimatedImage() [1/2]
AnimatedImage (const BitmapId & start, const BitmapId & end, const uint8_t & updateInterval = 1) inline
Constructs an AnimatedImage. The start and the end specifies the range of bitmaps to be used for animation. The update interval defines how often the animation should be updated. The animation will iterate over the bitmaps that lies between the IDs of start and end, both included.
Parameters
start Defines the start of the range of images in the animation.
end Defines the end of the range of images in the animation.
updateInterval (Optional) Defines the number of ticks between each animation step. Higher value results in a slower animation. Default is to update the image on every tick.
        : Image(Bitmap(start)),
          animationDoneAction(0),
          startId(start),
          endId(end),
          updateTicksInterval(updateInterval),
          ticksSinceUpdate(0),
          reverse(false),
          loopAnimation(false),
          running(false)
    {
    }
AnimatedImage() [2/2]
AnimatedImage (const uint8_t & updateInterval = 1) inline
Constructs an AnimatedImage without initializing bitmaps.
Parameters
updateInterval (Optional) Defines the number of ticks between each animation step. Higher value results in a slower animation.
Note
The bitmaps to display must be configured through set setBitmaps function before this widget displays anything.
        : animationDoneAction(0),
          startId(BITMAP_INVALID),
          endId(BITMAP_INVALID),
          updateTicksInterval(updateInterval),
          ticksSinceUpdate(0),
          reverse(false),
          loopAnimation(false),
          running(false)
    {
    }
Member Function Documentation
handleTickEvent()
void handleTickEvent () virtual
Called periodically by the framework if the Drawable instance has subscribed to timer ticks.
See also
Application::registerTimerWidget
Reimplemented from Drawable.
{
    if (!running)
    {
        return;
    }
    ++ticksSinceUpdate;
    if (ticksSinceUpdate != updateTicksInterval)
    {
        return;
    }
    ticksSinceUpdate = 0;
    BitmapId currentId = getBitmap();
    if (((currentId == endId) && !reverse) || ((currentId == startId) && reverse))
    {
        if (!loopAnimation)
        {
            Application::getInstance()->unregisterTimerWidget(this);
            running = false;
        }
        if (animationDoneAction && animationDoneAction->isValid())
        {
            animationDoneAction->execute(*this);
        }
        if (running && loopAnimation)
        {
            if (reverse)
            {
                Image::setBitmap(Bitmap(endId));
            }
            else
            {
                Image::setBitmap(Bitmap(startId));
            }
            invalidate();
        }
    }
    else
    {
        if (reverse)
        {
            --currentId;
        }
        else
        {
            ++currentId;
        }
        Image::setBitmap(Bitmap(currentId));
        invalidate();
    }
}
References AnimatedImage::animationDoneAction, AnimatedImage::endId, Image::getBitmap(), Application::getInstance(), Drawable::invalidate(), AnimatedImage::loopAnimation, AnimatedImage::reverse, AnimatedImage::running, Image::setBitmap(), AnimatedImage::startId, AnimatedImage::ticksSinceUpdate, and AnimatedImage::updateTicksInterval.
isAnimatedImageRunning()
bool isAnimatedImageRunning () const inline
Gets the running state of the AnimatedImage.
Returns
true if the animation is currently running, false otherwise.
    {
        return running;
    }
References AnimatedImage::running.
Referenced by Screen1View::SetState().
isReverse()
bool isReverse () inline
Query if this object is running in reverse.
Returns
true if the animation is performed in reverse order.
    {
        return reverse;
    }
References AnimatedImage::reverse.
pauseAnimation()
void pauseAnimation () virtual
Toggles the running state of an animation. Pauses the animation if the animation is running. Continues the animation if previously paused.
See also
stopAnimation
{
    if (running)
    {
        Application::getInstance()->unregisterTimerWidget(this);
        running = false;
    }
    else
    {
        Application::getInstance()->registerTimerWidget(this);
        running = true;
    }
}
References Application::getInstance(), and AnimatedImage::running.
setBitmap()
void setBitmap (const Bitmap & bmp) virtual
Sets the bitmap for this Image and updates the width and height of this widget to match those of the Bitmap.
Parameters
bmp The bitmap instance.
Note
The user code must call invalidate() in order to update the image on the display.
See also
setBitmaps, setBitmapEnd
Note
This only sets the start image.
Reimplemented from Image.
{
    startId = bmp.getId();
    Image::setBitmap(bmp);
}
References Image::setBitmap(), and AnimatedImage::startId.
Referenced by AnimatedImage::setBitmaps().
setBitmapEnd()
void setBitmapEnd (const Bitmap & bmp) virtual
Sets the end bitmap for this AnimatedImage sequence.
Parameters
bmp The bitmap.
See also
setBitmaps, setBitmap
{
    endId = bmp.getId();
}
References AnimatedImage::endId.
Referenced by AnimatedImage::setBitmaps().
setBitmaps()
void setBitmaps (BitmapId start, BitmapId end)
Sets the bitmaps that are used by the animation.
The animation will iterate over the bitmaps that lies between the IDs of start and end, both inclusive.
Parameters
start Defines the start of the range of images in the animation.
end Defines the end of the range of images in the animation.
See also
setBitmap, setBitmapEnd
{
    setBitmap(start);
    setBitmapEnd(end);
}
References AnimatedImage::setBitmap(), and AnimatedImage::setBitmapEnd().
Referenced by Screen1ViewBase::Screen1ViewBase(), and AnimatedImageButtonStyle< T >::setBitmaps().
setDoneAction()
void setDoneAction (GenericCallback< const AnimatedImage & > & callback) inline
Associates an action to be performed when the animation of the AnimatedImage is done. If the animation is set to loop at the end, the action is also triggered when the animation starts over.
Parameters
callback The callback is executed when done. The callback is given the animated image.
    {
        animationDoneAction = &callback;
    }
References AnimatedImage::animationDoneAction.
setUpdateTicksInterval()
void setUpdateTicksInterval (uint8_t updateInterval)
Sets the update interval. The value specifies the number of ticks between each step of the animation. The default update interval for animated images is 1, which means results in the fastest possible animation.
Parameters
updateInterval Defines the number of ticks between each animation step. Higher value results in a slower animation.
{
    updateTicksInterval = updateInterval;
    ticksSinceUpdate = 0;
}
References AnimatedImage::ticksSinceUpdate, and AnimatedImage::updateTicksInterval.
Referenced by Screen1ViewBase::Screen1ViewBase(), and AnimatedImageButtonStyle< T >::setUpdateTicksInterval().
startAnimation()
void startAnimation (const bool rev, const bool reset = false, const bool loop = false) virtual
Starts the animation with the given parameters for animation direction, normal or reverse, whether to restart the animation and finally if the animation should loop automatically upon completion.
Parameters
rev Defines if the animation should be performed in reverse order.
reset (Optional) Defines if the animation should reset and start from the first (or last if reverse order) bitmap.
loop (Optional) Defines if the animation should loop or do a single animation.
{
    if ((startId != BITMAP_INVALID) && (endId != BITMAP_INVALID))
    {
        reverse = rev;
        loopAnimation = loop;
        if (reverse && reset)
        {
            Image::setBitmap(Bitmap(endId));
            invalidate();
        }
        else if (!reverse && reset)
        {
            Image::setBitmap(Bitmap(startId));
            invalidate();
        }
        Application::getInstance()->registerTimerWidget(this);
        running = true;
    }
}
References touchgfx::BITMAP_INVALID, AnimatedImage::endId, Application::getInstance(), Drawable::invalidate(), AnimatedImage::loopAnimation, AnimatedImage::reverse, AnimatedImage::running, Image::setBitmap(), and AnimatedImage::startId.
Referenced by AnimatedImageButtonStyle< T >::handlePressedUpdated(), and Screen1View::SetState().
stopAnimation()
void stopAnimation () virtual
Stops and resets the animation. If the animation should not reset to the first image in the animation sequence, use pauseAnimation().
See also
startAnimation, pauseAnimation
{
    if (running)
    {
        Application::getInstance()->unregisterTimerWidget(this);
        running = false;
    }
    if (reverse)
    {
        Image::setBitmap(Bitmap(endId));
    }
    else
    {
        Image::setBitmap(Bitmap(startId));
    }
    invalidate();
}
References AnimatedImage::endId, Application::getInstance(), Drawable::invalidate(), AnimatedImage::reverse, AnimatedImage::running, Image::setBitmap(), and AnimatedImage::startId.
Referenced by Screen1View::SetState().
Member Data Documentation
animationDoneAction
GenericCallback<const AnimatedImage&>* animationDoneAction protected
Pointer to the callback to be executed when animation is done.
Referenced by AnimatedImage::handleTickEvent(), and AnimatedImage::setDoneAction().
endId
BitmapId endId protected
Id of last bitmap in animation.
Referenced by AnimatedImage::handleTickEvent(), AnimatedImage::setBitmapEnd(), AnimatedImage::startAnimation(), and AnimatedImage::stopAnimation().
loopAnimation
bool loopAnimation protected
If true, continuously loop animation.
Referenced by AnimatedImage::handleTickEvent(), and AnimatedImage::startAnimation().
reverse
bool reverse protected
If true, run in reverse direction (last to first).
Referenced by AnimatedImage::handleTickEvent(), AnimatedImage::isReverse(), AnimatedImage::startAnimation(), and AnimatedImage::stopAnimation().
running
bool running protected
If true, animation is running.
Referenced by AnimatedImage::handleTickEvent(), AnimatedImage::isAnimatedImageRunning(), AnimatedImage::pauseAnimation(), AnimatedImage::startAnimation(), and AnimatedImage::stopAnimation().
startId
BitmapId startId protected
Id of first bitmap in animation.
Referenced by AnimatedImage::handleTickEvent(), AnimatedImage::setBitmap(), AnimatedImage::startAnimation(), and AnimatedImage::stopAnimation().
ticksSinceUpdate
uint8_t ticksSinceUpdate protected
Number of ticks since last animation update.
Referenced by AnimatedImage::handleTickEvent(), and AnimatedImage::setUpdateTicksInterval().
updateTicksInterval
uint8_t updateTicksInterval protected
Number of ticks between each animation update (image change).
Referenced by AnimatedImage::handleTickEvent(), and AnimatedImage::setUpdateTicksInterval().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/AnimatedImage.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/AnimatedImage.cpp