Battery Simulator Documentation: AnimatedImageButtonStyle< T >
AnimatedImageButtonStyle< T >
#include "AnimatedImageButtonStyle.hpp"
Public Member Functions
AnimatedImageButtonStyle ()
void setBitmaps (const Bitmap &bitmapStart, const Bitmap &bitmapEnd)
void setBitmapXY (uint16_t x, uint16_t y)
void setUpdateTicksInterval (uint8_t updateInterval)
Protected Member Functions
virtual void handleAlphaUpdated ()
virtual void handlePressedUpdated ()
Protected Attributes
AnimatedImage buttonAnimatedImage
The button animated image.
Detailed Description
template<class T>
class touchgfx::AnimatedImageButtonStyle< T >
An animated image button style. An animated image button style. This class is supposed to be used with one of the ButtonTrigger classes to create a functional button. This class will show the first or last image of an animated image depending on the state of the button (pressed or released). When the state changes the button will show the sequence of images in forward or reversed order.
The AnimatedImageButtonStyle will set the size of the enclosing container (normally AbstractButtonContainer) to the size of the first Bitmap. This can be overridden by calling setWidth/setHeight after setting the bitmaps.
The position of the bitmap can be adjusted with setBitmapXY (default is upper left corner).
Template Parameters
T Generic type parameter. Typically a AbstractButtonContainer subclass.
See also
AbstractButtonContainer
Constructor & Destructor Documentation
AnimatedImageButtonStyle()
template<class T > AnimatedImageButtonStyle () inline
        : T(), buttonAnimatedImage()
    {
        buttonAnimatedImage.setXY(0, 0);
        T::add(buttonAnimatedImage);
    }
References AnimatedImageButtonStyle< T >::buttonAnimatedImage, and Drawable::setXY().
Member Function Documentation
handleAlphaUpdated()
template<class T > virtual void handleAlphaUpdated () inline protected virtual
Handles what should happen when the alpha is updated.
    {
        buttonAnimatedImage.setAlpha(T::getAlpha());
        T::handleAlphaUpdated();
    }
References AnimatedImageButtonStyle< T >::buttonAnimatedImage, and Image::setAlpha().
handlePressedUpdated()
template<class T > virtual void handlePressedUpdated () inline protected virtual
Handles what should happen when the pressed state is updated.
    {
        buttonAnimatedImage.startAnimation(AbstractButtonContainer::pressed, true, false);
        T::handlePressedUpdated();
    }
References AnimatedImageButtonStyle< T >::buttonAnimatedImage, AbstractButtonContainer::pressed, and AnimatedImage::startAnimation().
Referenced by AnimatedImageButtonStyle< T >::setBitmaps().
setBitmaps()
template<class T > void setBitmaps (const Bitmap & bitmapStart, const Bitmap & bitmapEnd) inline
Sets the bitmaps.
Parameters
bitmapStart The bitmap start.
bitmapEnd The bitmap end.
    {
        buttonAnimatedImage.setBitmaps(bitmapStart.getId(), bitmapEnd.getId());
        AbstractButtonContainer::setWidthHeight(bitmapStart);
        handlePressedUpdated();
    }
References AnimatedImageButtonStyle< T >::buttonAnimatedImage, AnimatedImageButtonStyle< T >::handlePressedUpdated(), AnimatedImage::setBitmaps(), and Drawable::setWidthHeight().
setBitmapXY()
template<class T > void setBitmapXY (uint16_t x, uint16_t y) inline
Sets bitmap x and y.
Parameters
x An uint16_t to process.
y An uint16_t to process.
    {
        buttonAnimatedImage.setXY(x, y);
    }
References AnimatedImageButtonStyle< T >::buttonAnimatedImage, and Drawable::setXY().
setUpdateTicksInterval()
template<class T > void setUpdateTicksInterval (uint8_t updateInterval) inline
Sets update ticks interval.
Parameters
updateInterval The update interval.
    {
        buttonAnimatedImage.setUpdateTicksInterval(updateInterval);
    }
References AnimatedImageButtonStyle< T >::buttonAnimatedImage, and AnimatedImage::setUpdateTicksInterval().
Member Data Documentation
buttonAnimatedImage
template<class T > AnimatedImage buttonAnimatedImage protected
The button animated image.
Referenced by AnimatedImageButtonStyle< T >::AnimatedImageButtonStyle(), AnimatedImageButtonStyle< T >::handleAlphaUpdated(), AnimatedImageButtonStyle< T >::handlePressedUpdated(), AnimatedImageButtonStyle< T >::setBitmaps(), AnimatedImageButtonStyle< T >::setBitmapXY(), and AnimatedImageButtonStyle< T >::setUpdateTicksInterval().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/buttons/AnimatedImageButtonStyle.hpp