Battery Simulator Documentation: CWRUtil::Q5
CWRUtil::Q5
#include "CWRUtil.hpp"
Public Member Functions
Q5 ()
Q5 (const Q10 q10)
Q5 (int i)
int ceil () const
int floor () const
operator int () const
Q5 operator% (const Q5 q5) const
Q5 & operator%= (const Q5 q5)
Q5 operator* (const int i) const
Q5 operator* (const Q15 &q15) const
Q10 operator* (const Q5 &q5) const
Q5 operator+ (const Q5 &q5) const
Q5 & operator+= (const Q5 &q5)
Q5 operator- () const
Q5 operator- (const Q5 &q5) const
Q5 & operator-= (const Q5 &q5)
Q5 operator/ (const int i) const
Q5 operator/ (const Q5 q5) const
int round () const
template<typename T >
T to () const
Private Attributes
int32_t v
Detailed Description
Defines a "floating point number" with 5 bits reserved for the fractional part of the decimal number. Q5 implements some simple arithmetic operations, most yielding a Q5 number and some yielding a Q10 number as a result. Other operations also work with Q15 numbers.
See also
Q10, Q15
Constructor & Destructor Documentation
Q5() [1/3]
Q5 () inline
Initializes a new instance of the Q5 class.
            : v(0)
        {
        }
Referenced by CWRUtil::Q5::operator%(), CWRUtil::Q5::operator*(), CWRUtil::Q5::operator*(), CWRUtil::Q5::operator+(), CWRUtil::Q5::operator-(), CWRUtil::Q5::operator-(), CWRUtil::Q5::operator/(), CWRUtil::Q5::operator/(), and CWRUtil::Q5::round().
Q5() [2/3]
Q5 (int i) inline explicit
Constructor from integer. No conversion is done - the integer is assumed to already be in Q5 format.
Parameters
i Integer pre-formattet in Q5 format.
            : v(i)
        {
        }
Q5() [3/3]
Q5 (const Q10 q10) inline
Constructor from Q10. The Q10 is shifted down to convert it to Q5, thus the value is rounded down in the conversion.
Parameters
q10 The Q10 value to convert to a Q5 value.
See also
Q10
            : v((int)q10 / Rasterizer::POLY_BASE_SIZE)
        {
        }
Member Function Documentation
ceil()
int ceil () const inline
Convert the Q5 value to an integer by removing the 5 bits used for the fraction. The number is rounded up to the nearest integer.
Returns
The first integer value higher than (or equal to) the Q5 value.
See also
floor
        {
            return v < 0 ? to<int>() : (v + (Rasterizer::POLY_BASE_SIZE - 1)) / Rasterizer::POLY_BASE_SIZE;
        }
Referenced by GraphElementBoxes::draw(), GraphElementLine::drawCanvasWidget(), GraphElementDots::drawCanvasWidget(), and GraphElementDiamonds::drawCanvasWidget().
floor()
int floor () const inline
Convert the Q5 value to an integer by removing the 5 bits used for the fraction. The number is rounded down to the nearest integer.
Returns
The first integer value higher than (or equal to) the Q5 value.
See also
ceil
        {
            return to<int>();
        }
operator int()
operator int () const inline
Gets the Q5 as an integer without conversion.
Returns
The unconverted Q5 value.
        {
            return v;
        }
References CWRUtil::Q5::v.
operator%()
Q5 operator% (const Q5 q5) const inline
Modulus operator.
Parameters
q5 The Q5 to modulus this by.
Returns
The result of the operation.
        {
            return Q5(v % q5.v);
        }
References CWRUtil::Q5::Q5().
operator%=()
Q5 & operator%= (const Q5 q5) inline
Modulus operator.
Parameters
q5 The Q5 to modulus this by.
Returns
The result of the operation.
        {
            v %= q5.v;
            return *this;
        }
operator*() [1/3]
Q5 operator* (const int i) const inline
Multiplication operator.
Parameters
i The integer to multiply this with.
Returns
The result of the operation.
        {
            return Q5(v * i);
        }
References CWRUtil::Q5::Q5().
operator*() [2/3]
Q5 operator* (const Q15 & q15) const inline
Multiplication operator. Often used in relation with sine and cosine calculation which are pre-calculated as Q15. As the result is needed as a Q5, this operator multiplies with the given Q15 and converts the result to a Q5.
Parameters
q15 The Q15 to multiply this with.
Returns
The result of the operation.
See also
Q15
        {
            int32_t remainder;
            return Q5(muldiv(v, (int)q15, Rasterizer::POLY_BASE_SIZE * Rasterizer::POLY_BASE_SIZE * Rasterizer::POLY_BASE_SIZE, remainder));
        }
References CWRUtil::Q5::Q5(), and touchgfx::muldiv().
operator*() [3/3]
Q10 operator* (const Q5 & q5) const inline
Multiplication operator. The result is a Q10, not a Q5, for increased precision.
Parameters
q5 The Q5 to multiply this with.
Returns
The result of the operation.
See also
Q10
        {
            return Q10(v * q5.v);
        }
operator+()
Q5 operator+ (const Q5 & q5) const inline
Addition operator.
Parameters
q5 The Q5 to add to this.
Returns
The result of the operation.
        {
            return Q5(v + q5.v);
        }
References CWRUtil::Q5::Q5().
operator+=()
Q5 & operator+= (const Q5 & q5) inline
Addition operator.
Parameters
q5 The Q5 to add to this.
Returns
The result of the operation.
        {
            v += q5.v;
            return *this;
        }
operator-() [1/2]
Q5 operator- () const inline
Negation operator.
Returns
The negative value of this.
        {
            return Q5(-v);
        }
References CWRUtil::Q5::Q5().
operator-() [2/2]
Q5 operator- (const Q5 & q5) const inline
Subtraction operator.
Parameters
q5 The Q5 to subtract from this.
Returns
The result of the operation.
        {
            return Q5(v - q5.v);
        }
References CWRUtil::Q5::Q5().
operator-=()
Q5 & operator-= (const Q5 & q5) inline
Subtraction operator.
Parameters
q5 The Q5 to subtract from this.
Returns
The result of the operation.
        {
            v -= q5.v;
            return *this;
        }
operator/() [1/2]
Q5 operator/ (const int i) const inline
Division operator.
Parameters
i The integer to divide this by.
Returns
The result of the operation.
        {
            return Q5(v / i);
        }
References CWRUtil::Q5::Q5().
operator/() [2/2]
Q5 operator/ (const Q5 q5) const inline
Division operator. Internally this Q5 is converted to Q10 before the division to increased precision.
Parameters
q5 The Q5 to divide this by.
Returns
The result of the operation.
See also
Q10
        {
            return Q5(v * Rasterizer::POLY_BASE_SIZE / q5.v);
        }
References CWRUtil::Q5::Q5().
round()
int round () const inline
Round the Q5 value to the nearest integer value.
Returns
The integer closest to the Q5 value.
        {
            return v < 0 ? Q5((v + 1) - toQ5(1).v / 2).to<int>() : Q5(v + toQ5(1).v / 2).to<int>();
        }
References CWRUtil::Q5::Q5(), and CWRUtil::toQ5().
Referenced by GraphElementVerticalGapLine::draw(), GraphElementHistogram::draw(), GraphLabelsX::drawString(), GraphLabelsY::drawString(), GraphElementVerticalGapLine::invalidateIndex(), and AbstractGraphElement::isCenterInvisible().
to()
template<typename T > T to () const inline
Convert the Q5 value to an integer by removing the 5 bits used for the fraction, or to a floating point value by dividing by 32, depending on the type specified as T.
Template Parameters
T Either int or float.
Returns
Q5 value as a type T.
Note
Using "to<int16_t>()" result in loss of precision. Use "(int16_t)to<int>()" instead.
        {
            return (T)((T)v / (T)Rasterizer::POLY_BASE_SIZE);
        }
Referenced by Circle::drawCanvasWidget(), AbstractShape::getAngle(), AbstractShape::getAngle(), Circle::getArc(), Circle::getArcEnd(), Circle::getArcEnd(), Circle::getArcStart(), Circle::getArcStart(), Circle::getCenter(), LineProgress::getEnd(), Line::getEnd(), Line::getLineWidth(), Circle::getLineWidth(), Line::getLineWidth(), AbstractShape::getOrigin(), Circle::getRadius(), LineProgress::getStart(), Line::getStart(), Line::invalidateContent(), CWRUtil::sine(), and AbstractShape::updateAbstractShapeCache().
Member Data Documentation
v
int32_t v private
Referenced by CWRUtil::Q5::operator int().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/CWRUtil.hpp