Battery Simulator Documentation: LCD
LCD abstract
#include "LCD.hpp"
Classes
class DrawStringInternalStruct
class DrawTextureMapScanLineBase
struct StringVisuals
class WideTextInternalStruct
Public Member Functions
LCD ()
virtual ~LCD ()
virtual uint8_t bitDepth () const =0
virtual void blitCopy (const uint16_t *sourceData, const Rect &source, const Rect &blitRect, uint8_t alpha, bool hasTransparentPixels)=0
virtual void blitCopy (const uint8_t *sourceData, Bitmap::BitmapFormat sourceFormat, const Rect &source, const Rect &blitRect, uint8_t alpha, bool hasTransparentPixels)=0
virtual void copyAreaFromTFTToClientBuffer (const Rect &region)=0
uint16_t * copyFrameBufferRegionToMemory (const Rect &region, const BitmapId bitmapId=BITMAP_ANIMATION_STORAGE)
virtual uint16_t * copyFrameBufferRegionToMemory (const Rect &visRegion, const Rect &absRegion, const BitmapId bitmapId)=0
virtual Rect copyFrameBufferRegionToMemory (const Rect &visRegion, const Rect &absRegion, uint8_t *dst, int16_t dstWidth, int16_t dstHeight)=0
virtual void drawPartialBitmap (const Bitmap &bitmap, int16_t x, int16_t y, const Rect &rect, uint8_t alpha=255, bool useOptimized=true)=0
void drawString (Rect widgetArea, const Rect &invalidatedArea, const StringVisuals &stringVisuals, const Unicode::UnicodeChar *format,...)
virtual void drawTextureMapQuad (const DrawingSurface &dest, const Point3D *vertices, const TextureSurface &texture, const Rect &absoluteRect, const Rect &dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha=255, uint16_t subDivisionSize=12)
virtual void drawTextureMapTriangle (const DrawingSurface &dest, const Point3D *vertices, const TextureSurface &texture, const Rect &absoluteRect, const Rect &dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha=255, uint16_t subDivisionSize=12)
virtual void fillBuffer (uint8_t *const destination, uint16_t pixelStride, const Rect &rect, const colortype color, const uint8_t alpha)=0
virtual void fillRect (const Rect &rect, colortype color, uint8_t alpha=255)=0
virtual Bitmap::BitmapFormat framebufferFormat () const =0
virtual uint16_t framebufferStride () const =0
colortype getDefaultColor () const
virtual void setDefaultColor (colortype color)
void setVectorFontRenderer (VectorFontRenderer *renderer)
virtual bool supportDynamicBitmapDrawing (const Bitmap::BitmapFormat format)
Static Public Member Functions
static FORCE_INLINE_FUNCTION uint8_t div255 (uint16_t num)
static FORCE_INLINE_FUNCTION uint32_t div255g (uint32_t pixelxAlpha)
static FORCE_INLINE_FUNCTION uint32_t div255rb (uint32_t pixelxAlpha)
Protected Member Functions
virtual void drawGlyph (uint16_t *wbuf16, Rect widgetArea, int16_t x, int16_t y, uint16_t offsetX, uint16_t offsetY, const Rect &invalidatedArea, const GlyphNode *glyph, const uint8_t *glyphData, uint8_t byteAlignRow, colortype color, uint8_t bitsPerPixel, uint8_t alpha, TextRotation rotation)=0
void drawStringLTR (const Rect &widgetArea, const Rect &invalidatedArea, const StringVisuals &visuals, const Unicode::UnicodeChar *format, va_list pArg)
void drawStringRTL (const Rect &widgetArea, const Rect &invalidatedArea, const StringVisuals &visuals, const Unicode::UnicodeChar *format, va_list pArg)
virtual void drawTextureMapScanLine (const DrawingSurface &dest, const Gradients &gradients, const Edge *leftEdge, const Edge *rightEdge, const TextureSurface &texture, const Rect &absoluteRect, const Rect &dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha, uint16_t subDivisionSize)
virtual DrawTextureMapScanLineBase * getTextureMapperDrawScanLine (const TextureSurface &texture, RenderingVariant renderVariant, uint8_t alpha)
Static Protected Member Functions
static FORCE_INLINE_FUNCTION uint8_t getAlphaFromA4 (const uint16_t *data, uint32_t offset)
static uint16_t getNumLines (TextProvider &textProvider, WideTextAction wideTextAction, TextDirection textDirection, const Font *font, int16_t width)
static int realX (const Rect &widgetArea, int16_t x, int16_t y, TextRotation rotation)
static int realY (const Rect &widgetArea, int16_t x, int16_t y, TextRotation rotation)
static void rotateRect (Rect &rect, const Rect &canvas, const TextRotation rotation)
static uint16_t stringWidth (TextProvider &textProvider, const Font &font, const int numChars, TextDirection textDirection)
Static Protected Attributes
static colortype defaultColor
Default Color to use when displaying transparency-only elements, e.g. A4 bitmaps.
static const uint16_t newLine = 10
NewLine value.
Private Member Functions
bool drawStringInternal (uint16_t *frameBuffer, const Rect *widgetArea, int16_t widgetRectY, int16_t offset, const Rect &invalidatedArea, const StringVisuals *stringVisuals, const TextDirection textDirection, TextProvider &textProvider, const int numChars, bool useEllipsis)
void drawStringRTLInternal (int16_t &offset, const Font *font, const TextDirection textDirection, TextProvider &drawTextProvider, const int numChars, const uint16_t widthOfNumChars, const DrawStringInternalStruct *data)
void drawStringRTLLine (int16_t &offset, const Font *font, TextDirection textDirection, TextProvider &textProvider, const int numChars, const bool useEllipsis, const DrawStringInternalStruct *data)
Private Attributes
DrawTextureMapScanLineBase * textureMapperClass
Used during faster TextureMapper rendering.
VectorFontRenderer * vectorFontRenderer
Detailed Description
This class contains the various low-level drawing routines for drawing bitmaps, texts and rectangles/boxes. Normally, these draw operations are called from widgets, which also keep track of logical states such as visibility etc.
The LCD class cannot be instantiated, instead use one of the subclasses which implements the LCD drawing operations for a specific display configuration.
Note
All coordinates sent to functions in the LCD class are expected to be in absolute coordinates, i.e. (0, 0) is upper left corner of the display.
Constructor & Destructor Documentation
LCD()
LCD () inline
Initializes a new instance of the LCD class.
        : textureMapperClass(0), vectorFontRenderer(0)
    {
    }
~LCD()
virtual ~LCD () inline virtual
Finalizes an instance of the LCD class.
    {
    }
Member Function Documentation
bitDepth()
virtual uint8_t bitDepth () const pure virtual
Number of bits per pixel used by the display.
Returns
The number of bits per pixel.
Implemented in LCD16bpp, LCD16bppSerialFlash, LCD1bpp, LCD24bpp, LCD2bpp, LCD32bpp, LCD32bpp_XRGB8888, LCD4bpp, LCD8bpp_ABGR2222, LCD8bpp_ARGB2222, LCD8bpp_BGRA2222, and LCD8bpp_RGBA2222.
blitCopy() [1/2]
virtual void blitCopy (const uint16_t * sourceData, const Rect & source, const Rect & blitRect, uint8_t alpha, bool hasTransparentPixels) pure virtual
Blits (directly copies) a block of data to the framebuffer, performing alpha blending (and tranparency keying) as specified. Performs a software blend if HAL does not support BLIT_COPY_WITH_ALPHA and alpha != 255 (solid).
Parameters
sourceData The source array pointer (points to the beginning of the data). The sourceData must be stored in a format suitable for the selected display.
source The position and dimensions of the source. The x and y of this rect should both be 0.
blitRect A rectangle describing what region of the sourceData is to be copied to the framebuffer.
alpha The alpha value to use for blending ranging from 0=invisible to 255=solid=no blending.
hasTransparentPixels If true, this data copy contains transparent pixels and require hardware support for that to be enabled.
Implemented in LCD16bpp, LCD16bppSerialFlash, LCD1bpp, LCD24bpp, LCD2bpp, LCD32bpp, LCD32bpp_XRGB8888, LCD4bpp, LCD8bpp_ABGR2222, LCD8bpp_ARGB2222, LCD8bpp_BGRA2222, and LCD8bpp_RGBA2222.
blitCopy() [2/2]
virtual void blitCopy (const uint8_t * sourceData, Bitmap::BitmapFormat sourceFormat, const Rect & source, const Rect & blitRect, uint8_t alpha, bool hasTransparentPixels) pure virtual
Blits (directly copies) a block of data to the framebuffer, performing alpha blending (and tranparency keying) as specified. Performs a software blend if HAL does not support BLIT_COPY_WITH_ALPHA and alpha < 255 (solid).
If the display does not support the specified sourceFormat, an assert will be raised.
Parameters
sourceData The source array pointer (points to the beginning of the data). The sourceData must be stored in a format suitable for the selected display.
sourceFormat The bitmap format used in the source data.
source The position and dimensions of the source. The x and y of this rect should both be 0.
blitRect A rectangle describing what region of the sourceData is to be copied to the framebuffer.
alpha The alpha value to use for blending ranging from 0=invisible to 255=solid=no blending.
hasTransparentPixels If true, this data copy contains transparent pixels and require hardware support for that to be enabled.
Implemented in LCD16bpp, LCD16bppSerialFlash, LCD1bpp, LCD24bpp, LCD2bpp, LCD32bpp, LCD32bpp_XRGB8888, LCD4bpp, LCD8bpp_ABGR2222, LCD8bpp_ARGB2222, LCD8bpp_BGRA2222, and LCD8bpp_RGBA2222.
copyAreaFromTFTToClientBuffer()
virtual void copyAreaFromTFTToClientBuffer (const Rect & region) pure virtual
Copies part of the displayed framebuffer to current framebuffer. The region given is the absolute region on screen.
Parameters
region A rectangle describing what region of the displayed framebuffer is to be copied to the framebuffer.
Note
The copy is performed only when double buffering is enabled. Otherwise the given region in current framebuffer is left untouched.
Implemented in LCD16bpp, LCD16bppSerialFlash, LCD1bpp, LCD24bpp, LCD2bpp, LCD32bpp, LCD32bpp_XRGB8888, LCD4bpp, LCD8bpp_ABGR2222, LCD8bpp_ARGB2222, LCD8bpp_BGRA2222, and LCD8bpp_RGBA2222.
copyFrameBufferRegionToMemory() [1/3]
uint16_t * copyFrameBufferRegionToMemory (const Rect & region, const BitmapId bitmapId = BITMAP_ANIMATION_STORAGE) inline
Copies part of the framebuffer to the data section of a bitmap. The bitmap must be a dynamic bitmap or animation storage (BITMAP_ANIMATION_STORAGE). Only the part specified with by parameter region is copied.
If region has negative x/y coordinates of if width/height exceeds those of the given bitmap, only the visible and legal part of the framebuffer is copied. The rest of the bitmap image is left untouched.
Parameters
region The part of the framebuffer to copy.
bitmapId (Optional) The bitmap to store the data in. Default is to use Animation Storage.
Returns
A pointer to the copy.
See also
blitCopy
Note
There is only one instance of animation storage. The content of the bitmap data (or animation storage) outside the given region is left untouched.
    {
        return copyFrameBufferRegionToMemory(region, region, bitmapId);
    }
References LCD::copyFrameBufferRegionToMemory().
Referenced by LCD::copyFrameBufferRegionToMemory().
copyFrameBufferRegionToMemory() [2/3]
virtual uint16_t * copyFrameBufferRegionToMemory (const Rect & visRegion, const Rect & absRegion, const BitmapId bitmapId) pure virtual
Copies part of the framebuffer to the data section of a bitmap. The bitmap must be a dynamic bitmap or animation storage (BITMAP_ANIMATION_STORAGE). The two regions given are the visible region and the absolute region on screen. This is used to copy only a part of the framebuffer. This might be the case if a SnapshotWidget is placed inside a Container where parts of the SnapshowWidget is outside the area defined by the Container. The visible region must be completely inside the absolute region.
Parameters
visRegion The visible region.
absRegion The absolute region.
bitmapId Identifier for the bitmap.
Returns
Null if it fails, else a pointer to the data in the given bitmap.
See also
blitCopy, copyFrameBufferRegionToMemory(const Rect&, const Rect&, uint8_t*, int16_t, int16_t)
Note
There is only one instance of animation storage. The content of the bitmap data /animation storage outside the given region is left untouched.
Implemented in LCD16bpp, LCD16bppSerialFlash, LCD1bpp, LCD24bpp, LCD2bpp, LCD32bpp, LCD32bpp_XRGB8888, LCD4bpp, LCD8bpp_ABGR2222, LCD8bpp_ARGB2222, LCD8bpp_BGRA2222, and LCD8bpp_RGBA2222.
copyFrameBufferRegionToMemory() [3/3]
virtual Rect copyFrameBufferRegionToMemory (const Rect & visRegion, const Rect & absRegion, uint8_t * dst, int16_t dstWidth, int16_t dstHeight) pure virtual
Copies part of the framebuffer to memory. The memory is assumed to have the same format as the framebuffer. The two regions given are the visible region and the absolute region on screen. This is used to copy only a part of the framebuffer. This might be the case if a SnapshotWidget is placed inside a Container where parts of the SnapshowWidget is outside the area defined by the Container. The visible region must be completely inside the absolute region.
Parameters
visRegion The visible region.
absRegion The absolute region.
[in,out] dst Destination memory in same format as the framebuffer.
dstWidth Width of the destination.
dstHeight Height of the destination.
Returns
The rect that was actually copied to the destination buffer.
See also
blitCopy, copyFrameBufferRegionToMemory(const Rect&, const Rect&, const BitmapId)
Note
There is only one instance of animation storage. The content of the bitmap data /animation storage outside the given region is left untouched.
Implemented in LCD16bpp, LCD16bppSerialFlash, LCD1bpp, LCD24bpp, LCD2bpp, LCD32bpp, LCD32bpp_XRGB8888, LCD4bpp, LCD8bpp_ABGR2222, LCD8bpp_ARGB2222, LCD8bpp_BGRA2222, and LCD8bpp_RGBA2222.
div255()
static FORCE_INLINE_FUNCTION uint8_t div255 (uint16_t num) inline static
Approximates an integer division of a 16bit value by 255. Divides numerator num (e.g. the sum resulting from an alpha-blending operation) by 255.
Parameters
[in] num The numerator to divide by 255.
Returns
The result of a division by 255.
    {
        return (num + 1 + (num >> 8)) >> 8;
    }
Referenced by LCD8bpp_ABGR2222::alphaBlend(), LCD8bpp_ARGB2222::alphaBlend(), LCD8bpp_BGRA2222::alphaBlend(), LCD8bpp_RGBA2222::alphaBlend(), AbstractPainterABGR2222::alphaBlend(), AbstractPainterARGB2222::alphaBlend(), AbstractPainterBGRA2222::alphaBlend(), AbstractPainterRGBA2222::alphaBlend(), LCD32bpp::alphaBlend888(), LCD32bpp::alphaBlend888_premul(), LCD32bpp_XRGB8888::blendRGBwithXrgb8888(), LCD2bpp::div255_2(), LCD4bpp::div255_4(), GraphElementGridBase::draw(), GraphElementVerticalGapLine::draw(), GraphElementHistogram::draw(), GraphElementBoxes::draw(), GraphLabelsBase::draw(), GraphTitle::draw(), CWRVectorRenderer::drawFill(), CWRVectorRenderer::drawStroke(), Color::getHSVFromHSL(), Color::getRGBFromHSV(), GraphLabelsX::invalidateGraphPointAt(), touchgfx::paint::rgb565::lineFromARGB8888(), touchgfx::paint::argb8888::lineFromARGB8888(), touchgfx::paint::rgb888::lineFromARGB8888(), touchgfx::paint::argb8888::lineFromColor(), touchgfx::paint::rgb888::lineFromColor(), touchgfx::paint::rgb565::lineFromL8ARGB8888(), touchgfx::paint::argb8888::lineFromL8ARGB8888(), touchgfx::paint::rgb888::lineFromL8ARGB8888(), touchgfx::paint::rgb565::lineFromL8RGB888(), touchgfx::paint::argb8888::lineFromL8RGB888(), touchgfx::paint::rgb888::lineFromL8RGB888(), touchgfx::paint::argb8888::lineFromRGB565(), touchgfx::paint::argb8888::lineFromRGB888(), touchgfx::paint::rgb888::lineFromRGB888(), PainterABGR2222Bitmap::paint(), PainterARGB2222Bitmap::paint(), PainterARGB8888L8Bitmap::paint(), PainterARGB8888LinearGradient::paint(), PainterBGRA2222Bitmap::paint(), PainterGRAY2::paint(), PainterGRAY2Bitmap::paint(), PainterGRAY4::paint(), PainterGRAY4Bitmap::paint(), PainterRGB565Bitmap::paint(), PainterRGB565LinearGradient::paint(), PainterRGB888LinearGradient::paint(), PainterRGBA2222Bitmap::paint(), PainterXRGB8888::paint(), PainterXRGB8888Bitmap::paint(), PainterXRGB8888L8Bitmap::paint(), and Canvas::render().
div255g()
static FORCE_INLINE_FUNCTION uint32_t div255g (uint32_t pixelxAlpha) inline static
Divides the green component of pixelxAlpha by 255.
Parameters
[in] pixelxAlpha The green component of a 32bit ARGB pixel multiplied by an alpha factor.
Returns
pixelxAlpha with its green component divided by 255.
    {
        return ((pixelxAlpha + 0x100 + (pixelxAlpha >> 8)) >> 8) & 0x00FF00;
    }
Referenced by LCD16bpp::div255_888(), LCD16bppSerialFlash::div255_888(), LCD24bpp::div255_888(), LCD32bpp::div255_888(), LCD32bpp_XRGB8888::div255_888(), LCD8bpp_ABGR2222::div255_888(), LCD8bpp_ARGB2222::div255_888(), LCD8bpp_BGRA2222::div255_888(), and LCD8bpp_RGBA2222::div255_888().
div255rb()
static FORCE_INLINE_FUNCTION uint32_t div255rb (uint32_t pixelxAlpha) inline static
Divides the red and blue components of pixelxAlpha by 255.
Parameters
[in] pixelxAlpha The red and blue components of a 32bit ARGB pixel multiplied by an alpha factor.
Returns
pixelxAlpha with its red and blue components divided by 255.
    {
        return ((pixelxAlpha + 0x10001 + ((pixelxAlpha >> 8) & 0xFF00FF)) >> 8) & 0xFF00FF;
    }
Referenced by LCD16bpp::div255_888(), LCD16bppSerialFlash::div255_888(), LCD24bpp::div255_888(), LCD32bpp::div255_888(), LCD32bpp_XRGB8888::div255_888(), LCD8bpp_ABGR2222::div255_888(), LCD8bpp_ARGB2222::div255_888(), LCD8bpp_BGRA2222::div255_888(), and LCD8bpp_RGBA2222::div255_888().
drawGlyph()
virtual void drawGlyph (uint16_t * wbuf16, Rect widgetArea, int16_t x, int16_t y, uint16_t offsetX, uint16_t offsetY, const Rect & invalidatedArea, const GlyphNode * glyph, const uint8_t * glyphData, uint8_t byteAlignRow, colortype color, uint8_t bitsPerPixel, uint8_t alpha, TextRotation rotation) protected pure virtual
Private version of draw-glyph with explicit destination buffer pointer argument. For all parameters (except the buffer pointer) see the public function drawString().
Parameters
[out] wbuf16 The destination (frame) buffer to draw to.
widgetArea The canvas to draw the glyph inside.
x Horizontal offset to start drawing the glyph.
y Vertical offset to start drawing the glyph.
offsetX Horizontal offset in the glyph to start drawing from.
offsetY Vertical offset in the glyph to start drawing from.
invalidatedArea The area to draw inside.
glyph Specifications of the glyph to draw.
glyphData Data containing the actual glyph (dense format)
byteAlignRow Each row of glyph data starts in a new byte.
color The color of the glyph.
bitsPerPixel Bit depth of the glyph.
alpha The transparency of the glyph.
rotation Rotation to do before drawing the glyph.
Implemented in LCD16bpp, LCD16bppSerialFlash, LCD1bpp, LCD24bpp, LCD2bpp, LCD32bpp, LCD32bpp_XRGB8888, LCD4bpp, LCD8bpp_ABGR2222, LCD8bpp_ARGB2222, LCD8bpp_BGRA2222, and LCD8bpp_RGBA2222.
drawPartialBitmap()
virtual void drawPartialBitmap (const Bitmap & bitmap, int16_t x, int16_t y, const Rect & rect, uint8_t alpha = 255, bool useOptimized = true) pure virtual
Draws all (or a part) of a bitmap. The coordinates of the corner of the bitmap is given in (x, y) and rect describes which part of the bitmap should be drawn. The bitmap can be drawn as it is or more or less transparent depending on the value of alpha. The value of alpha is independent of the transparency of the individual pixels of the given bitmap.
Parameters
bitmap The bitmap to draw.
x The absolute x coordinate to place (0, 0) of the bitmap on the screen.
y The absolute y coordinate to place (0, 0) of the bitmap on the screen.
rect A rectangle describing what region of the bitmap is to be drawn.
alpha (Optional) Optional alpha value ranging from 0=invisible to 255=solid. Default is 255 (solid).
useOptimized (Optional) if false, do not attempt to substitute (parts of) this bitmap with faster fillrects.
Implemented in LCD16bpp, LCD16bppSerialFlash, LCD1bpp, LCD24bpp, LCD2bpp, LCD32bpp, LCD32bpp_XRGB8888, LCD4bpp, LCD8bpp_ABGR2222, LCD8bpp_ARGB2222, LCD8bpp_BGRA2222, and LCD8bpp_RGBA2222.
drawString()
void drawString (touchgfx::Rect widgetArea, const Rect & invalidatedArea, const StringVisuals & stringVisuals, const Unicode::UnicodeChar * format, ...)
Draws the specified Unicode string. Breaks line on newline.
Parameters
widgetArea The area covered by the drawing widget in absolute coordinates.
invalidatedArea The (sub)region of the widget area to draw, expressed relative to the widget area. If the widgetArea is x=10, y=10, width=20, height=20 and invalidatedArea is x=5, y=5, width=6, height=6 the widgetArea drawn on the LCD is x=15, y=15, width=6, height=6.
stringVisuals The string visuals (font, alignment, line space, color) with which to draw this string.
format A pointer to a null-terminated text string with optional additional wildcard arguments.
... Variable arguments providing additional information.
{
    va_list pArg;
    va_start(pArg, format);
    drawStringLTR(widgetArea, invalidatedArea, stringVisuals, format, pArg);
    va_end(pArg);
}
drawStringInternal()
bool drawStringInternal (uint16_t * frameBuffer, const Rect * widgetArea, int16_t widgetRectY, int16_t offset, const Rect & invalidatedArea, const StringVisuals * stringVisuals, const TextDirection textDirection, TextProvider & textProvider, const int numChars, bool useEllipsis) private
drawStringLTR()
void drawStringLTR (const Rect & widgetArea, const Rect & invalidatedArea, const StringVisuals & visuals, const Unicode::UnicodeChar * format, va_list pArg) protected
Draws the specified Unicode string. Breaks line on newline. The string is assumed to contain only Latin characters written left-to-right.
Parameters
widgetArea The area covered by the drawing widget in absolute coordinates.
invalidatedArea The (sub)region of the widget area to draw, expressed relative to the widget area. If the widgetArea is x=10, y=10, width=20, height=20 and invalidatedArea is x=5, y=5, width=6, height=6 the widgetArea drawn on the LCD is x=15, y=15, width=6, height=6.
[in] visuals The string visuals (font, alignment, line space, color) with which to draw this string.
format A pointer to a null-terminated text string with optional additional wildcard arguments.
pArg Variable arguments providing additional information.
See also
drawString
drawStringRTL()
void drawStringRTL (const Rect & widgetArea, const Rect & invalidatedArea, const StringVisuals & visuals, const Unicode::UnicodeChar * format, va_list pArg) protected
Draws the specified Unicode string. Breaks line on newline. The string can be either right-to-left or left-to-right and may contain sequences of Arabic / Hebrew and Latin characters.
Parameters
widgetArea The area covered by the drawing widget in absolute coordinates.
invalidatedArea The (sub)region of the widget area to draw, expressed relative to the widget area. If the widgetArea is x=10, y=10, width=20, height=20 and invalidatedArea is x=5, y=5, width=6, height=6 the widgetArea drawn on the LCD is x=15, y=15, width=6, height=6.
[in] visuals The string visuals (font, alignment, line space, color) with which to draw this string.
format A pointer to a null-terminated text string with optional additional wildcard arguments.
pArg Variable arguments providing additional information.
See also
drawString
drawStringRTLInternal()
void drawStringRTLInternal (int16_t & offset, const Font * font, const TextDirection textDirection, TextProvider & drawTextProvider, const int numChars, const uint16_t widthOfNumChars, const DrawStringInternalStruct * data) private
drawStringRTLLine()
void drawStringRTLLine (int16_t & offset, const Font * font, TextDirection textDirection, TextProvider & textProvider, const int numChars, const bool useEllipsis, const DrawStringInternalStruct * data) private
drawTextureMapQuad()
virtual void drawTextureMapQuad (const DrawingSurface & dest, const Point3D * vertices, const TextureSurface & texture, const Rect & absoluteRect, const Rect & dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha = 255, uint16_t subDivisionSize = 12) virtual
Texture map quad. Draw a perspective correct texture mapped quad. The vertices describes the surface, the x,y,z coordinates and the u,v coordinates of the texture. The texture contains the image data to be drawn The quad line will be placed and clipped using the absolute and dirty rectangles The alpha will determine how the quad should be alpha blended. The subDivisionSize will determine the size of the piecewise affine texture mapped portions of the quad.
Parameters
dest The description of where the texture is drawn - can be used to issue a draw off screen.
vertices The vertices of the quad.
texture The texture.
absoluteRect The containing rectangle in absolute coordinates.
dirtyAreaAbsolute The dirty area in absolute coordinates.
renderVariant The render variant - includes the algorithm and the pixel format.
alpha (Optional) the alpha. Default is 255 (solid).
subDivisionSize (Optional) the size of the subdivisions of the scan line. Default is 12.
drawTextureMapScanLine()
virtual void drawTextureMapScanLine (const DrawingSurface & dest, const Gradients & gradients, const Edge * leftEdge, const Edge * rightEdge, const TextureSurface & texture, const Rect & absoluteRect, const Rect & dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha, uint16_t subDivisionSize) protected virtual
Draw scan line. Draw one horizontal line of the texture map on screen. The scan line will be drawn using perspective correct texture mapping. The appearance of the line is determined by the left and right edge and the gradients structure. The edges contain the information about the x,y,z coordinates of the left and right side respectively and also information about the u,v coordinates of the texture map used. The gradients structure contains information about how to interpolate all the values across the scan line. The data drawn should be present in the texture argument.
The scan line will be drawn using the additional arguments. The scan line will be placed and clipped using the absolute and dirty rectangles The alpha will determine how the scan line should be alpha blended. The subDivisionSize will determine the size of the piecewise affine texture mapped lines.
Parameters
dest The description of where the texture is drawn - can be used to issue a draw off screen.
gradients The gradients using in interpolation across the scan line.
leftEdge The left edge of the scan line.
rightEdge The right edge of the scan line.
texture The texture.
absoluteRect The containing rectangle in absolute coordinates.
dirtyAreaAbsolute The dirty area in absolute coordinates.
renderVariant The render variant - includes the algorithm and the pixel format.
alpha The alpha.
subDivisionSize The size of the subdivisions of the scan line. A value of 1 will give a completely perspective correct texture mapped scan line. A large value will give an affine texture mapped scan line.
Reimplemented in LCD1bpp.
drawTextureMapTriangle()
virtual void drawTextureMapTriangle (const DrawingSurface & dest, const Point3D * vertices, const TextureSurface & texture, const Rect & absoluteRect, const Rect & dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha = 255, uint16_t subDivisionSize = 12) virtual
Texture map triangle. Draw a perspective correct texture mapped triangle. The vertices describes the surface, the x,y,z coordinates and the u,v coordinates of the texture. The texture contains the image data to be drawn The triangle line will be placed and clipped using the absolute and dirty rectangles The alpha will determine how the triangle should be alpha blended. The subDivisionSize will determine the size of the piecewise affine texture mapped portions of the triangle.
Parameters
dest The description of where the texture is drawn - can be used to issue a draw off screen.
vertices The vertices of the triangle.
texture The texture.
absoluteRect The containing rectangle in absolute coordinates.
dirtyAreaAbsolute The dirty area in absolute coordinates.
renderVariant The render variant - includes the algorithm and the pixel format.
alpha (Optional) the alpha. Default is 255 (solid).
subDivisionSize (Optional) the size of the subdivisions of the scan line. Default is 12.
fillBuffer()
virtual void fillBuffer (uint8_t *const destination, uint16_t pixelStride, const Rect & rect, const colortype color, const uint8_t alpha) pure virtual
Draws a filled rectangle in destination memory using the specified color and opacity. The destination memory must have the same format as the display framebuffer. By default the rectangle will be drawn as a solid box. The rectangle can be drawn with transparency by specifying alpha from 0=invisible to 255=solid.
Parameters
[in] destination The start of the memory area to fill.
pixelStride The pixel stride, i.e. number of pixels in a row.
rect The rectangle to fill absolute coordinates.
color The rectangle color.
alpha The rectangle opacity, from 0=invisible to 255=solid.
Note
The pixelStride is rounded up to nearest whole bytes for displays with more than one pixel per byte (LCD1bpp, LCD2bpp and LCD4bpp)
Implemented in LCD16bpp, LCD16bppSerialFlash, LCD1bpp, LCD24bpp, LCD2bpp, LCD32bpp, LCD32bpp_XRGB8888, LCD4bpp, LCD8bpp_ABGR2222, LCD8bpp_ARGB2222, LCD8bpp_BGRA2222, and LCD8bpp_RGBA2222.
fillRect()
virtual void fillRect (const Rect & rect, colortype color, uint8_t alpha = 255) pure virtual
Draws a filled rectangle in the framebuffer in the specified color and opacity. By default the rectangle will be drawn as a solid box. The rectangle can be drawn with transparency by specifying alpha from 0=invisible to 255=solid.
Parameters
rect The rectangle to draw in absolute display coordinates.
color The rectangle color.
alpha (Optional) The rectangle opacity, from 0=invisible to 255=solid.
See also
fillBuffer
Implemented in LCD16bpp, LCD16bppSerialFlash, LCD1bpp, LCD24bpp, LCD2bpp, LCD32bpp, LCD32bpp_XRGB8888, LCD4bpp, LCD8bpp_ABGR2222, LCD8bpp_ARGB2222, LCD8bpp_BGRA2222, and LCD8bpp_RGBA2222.
framebufferFormat()
virtual Bitmap::BitmapFormat framebufferFormat () const pure virtual
Framebuffer format used by the display.
Returns
A Bitmap::BitmapFormat.
Implemented in LCD16bpp, LCD16bppSerialFlash, LCD1bpp, LCD24bpp, LCD2bpp, LCD32bpp, LCD32bpp_XRGB8888, LCD4bpp, LCD8bpp_ABGR2222, LCD8bpp_ARGB2222, LCD8bpp_BGRA2222, and LCD8bpp_RGBA2222.
Referenced by LCD::supportDynamicBitmapDrawing().
framebufferStride()
virtual uint16_t framebufferStride () const pure virtual
Framebuffer stride in bytes. The distance (in bytes) from the start of one framebuffer row, to the next.
Returns
The number of bytes in one framebuffer row.
Implemented in LCD16bpp, LCD16bppSerialFlash, LCD1bpp, LCD24bpp, LCD2bpp, LCD32bpp, LCD32bpp_XRGB8888, LCD4bpp, LCD8bpp_ABGR2222, LCD8bpp_ARGB2222, LCD8bpp_BGRA2222, and LCD8bpp_RGBA2222.
getAlphaFromA4()
static FORCE_INLINE_FUNCTION uint8_t getAlphaFromA4 (const uint16_t * data, uint32_t offset) inline static protected
Gets alpha from A4 image at given offset. The value is scaled up from range 0-15 to 0- 255.
Parameters
data A pointer to the start of the A4 data.
offset The offset into the A4 image.
Returns
The alpha from A4 (0-255).
    {
        uint8_t byte = reinterpret_cast<const uint8_t*>(data)[offset / 2];
        return ((offset & 1) == 0 ? byte & 0xF : byte >> 4) * 0x11;
    }
getDefaultColor()
colortype getDefaultColor () const inline
Gets default color previously set using setDefaultColor.
Returns
The default color.
See also
setDefaultColor
    {
        return defaultColor;
    }
References LCD::defaultColor.
getNumLines()
static uint16_t getNumLines (TextProvider & textProvider, WideTextAction wideTextAction, TextDirection textDirection, const Font * font, int16_t width) static protected
Gets number of lines for a given text taking word wrap into consideration. The font and width are required to find the number of lines in case word wrap is true.
Parameters
[in] textProvider The text provider.
wideTextAction The wide text action in case lines are longer than the width of the text area.
textDirection The text direction (LTR or RTL).
font The font.
width The width.
Returns
The number lines.
Referenced by TextArea::calculateTextHeight().
getTextureMapperDrawScanLine()
virtual DrawTextureMapScanLineBase * getTextureMapperDrawScanLine (const TextureSurface & texture, RenderingVariant renderVariant, uint8_t alpha) protected virtual
Gets pointer to object that can draw a scan line which allows for highly specialized and optimized implementation.
Parameters
texture The texture Surface.
renderVariant The render variant.
alpha The global alpha.
Returns
Null if it fails, else the pointer to the texture mapper draw scan line object.
Reimplemented in LCD16bpp, LCD16bppSerialFlash, LCD24bpp, LCD2bpp, LCD32bpp, LCD32bpp_XRGB8888, LCD4bpp, LCD8bpp_ABGR2222, LCD8bpp_ARGB2222, LCD8bpp_BGRA2222, and LCD8bpp_RGBA2222.
realX()
static int realX (const Rect & widgetArea, int16_t x, int16_t y, TextRotation rotation) static protected
Find the real, absolute x coordinate of a point inside a widget with regards to rotation.
Parameters
[in] widgetArea The widget containing the point.
x The x coordinate.
y The y coordinate.
rotation Rotation to perform.
Returns
The absolute x coordinate after applying appropriate rotation.
realY()
static int realY (const Rect & widgetArea, int16_t x, int16_t y, TextRotation rotation) static protected
Find the real, absolute y coordinate of a point inside a widget with regards to rotation.
Parameters
[in] widgetArea The widget containing the point.
x The x coordinate.
y The y coordinate.
rotation Rotation to perform.
Returns
The absolute y coordinate after applying appropriate rotation.
rotateRect()
static void rotateRect (Rect & rect, const Rect & canvas, const TextRotation rotation) static protected
Rotate a rectangle inside another rectangle.
Parameters
[in,out] rect The rectangle to rotate.
canvas The rectangle containing the rect to rotate.
rotation Rotation to perform on rect.
setDefaultColor()
virtual void setDefaultColor (colortype color) inline virtual
Sets default color as used by alpha level only bitmap formats, e.g. A4. The default color, if no color is set, is black.
Parameters
color The color.
See also
getDefaultColor
Reimplemented in LCD4bpp.
    {
        defaultColor = color;
    }
References LCD::defaultColor.
Referenced by LCD4bpp::setDefaultColor().
setVectorFontRenderer()
void setVectorFontRenderer (VectorFontRenderer * renderer) inline
Set the vector font renderer
Parameters
renderer The renderer to be used by LCD when dealing with vector fonts.
    {
        vectorFontRenderer = renderer;
    }
References LCD::vectorFontRenderer.
stringWidth()
static uint16_t stringWidth (TextProvider & textProvider, const Font & font, const int numChars, TextDirection textDirection) static protected
Find string width of the given number of ligatures read from the given TextProvider. After the introduction of Arabic, Thai, Hindi and other languages, ligatures are counted instead of characters. For Latin languages, number of characters equal number of ligatures.
Parameters
[in] textProvider The text provider.
font The font.
numChars Number of characters (ligatures).
textDirection The text direction.
Returns
An int16_t.
Referenced by TextArea::calculateBoundingArea().
supportDynamicBitmapDrawing()
virtual bool supportDynamicBitmapDrawing (const Bitmap::BitmapFormat format) inline virtual
Check if LCD support dynamic bitmap drawing.
Parameters
format The dynamic bitmap format.
Returns
true if dynamic bitmap drawing is supported, false otherwise.
Reimplemented in LCD32bpp_XRGB8888.
    {
        // return true if bitmap format matches framebuffer format
        return (format == framebufferFormat());
    }
References LCD::framebufferFormat().
Member Data Documentation
defaultColor
colortype defaultColor static protected
Default Color to use when displaying transparency-only elements, e.g. A4 bitmaps.
Referenced by LCD::getDefaultColor(), and LCD::setDefaultColor().
newLine
const uint16_t newLine = 10 static protected
NewLine value.
textureMapperClass
DrawTextureMapScanLineBase* textureMapperClass private
Used during faster TextureMapper rendering.
vectorFontRenderer
VectorFontRenderer* vectorFontRenderer private
Referenced by LCD::setVectorFontRenderer().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/lcd/LCD.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/texts/src/Texts.cpp