Battery Simulator Documentation: RepeatButton
RepeatButton
#include "RepeatButton.hpp"
Public Member Functions
RepeatButton ()
virtual int getDelay ()
virtual int getInterval ()
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleTickEvent ()
virtual void setDelay (int delay)
virtual void setInterval (int interval)
Public Member Functions inherited from Button
Button ()
virtual void draw (const Rect &invalidatedArea) const
uint8_t getAlpha () const
Bitmap getCurrentlyDisplayedBitmap () const
virtual Rect getSolidRect () const
virtual void invalidateContent () const
void setAlpha (uint8_t newAlpha)
virtual void setBitmaps (const Bitmap &bitmapReleased, const Bitmap &bitmapPressed)
Public Member Functions inherited from AbstractButton
AbstractButton ()
virtual void executeAction ()
virtual bool getPressedState () const
void setAction (GenericCallback< const AbstractButton & > &callback)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Private Attributes
int16_t ticks
int16_t ticksBeforeContinuous
int16_t ticksDelay
int16_t ticksInterval
Additional Inherited Members
Protected Attributes inherited from Button
uint8_t alpha
The current alpha value. 255=solid, 0=invisible.
Bitmap down
The image to display when button is pressed.
Bitmap up
The image to display when button is released (normal state).
Protected Attributes inherited from AbstractButton
GenericCallback< const AbstractButton & > * action
The callback to be executed when this AbstractButton is clicked.
bool pressed
Is the button pressed or released? True if pressed.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A RepeatButton is similar to a regular Button, but it will 'repeat' if pressed for a long period of time. The RepeatButton differs from a regular Button with regards to activation. A Button is activated when the button is released, whereas a RepeatButton is activated immediately when pressed and then at regular intervals. A RepeatButton does not activate when released.
As for other well-known repeat buttons, the interval from the first activation until the second activation as well as the subsequent interval between activations can be set for the RepeatButton.
The default values for initial delay is 10 ticks, and the default value for the following delays between button activations is 5 ticks.
Constructor & Destructor Documentation
RepeatButton()
RepeatButton ()
    : Button(), ticksDelay(30), ticksInterval(15), ticks(0), ticksBeforeContinuous(0)
{
}
Member Function Documentation
getDelay()
int getDelay () virtual
Gets the delay in ticks from first button activation until next activation.
Returns
The delay, measured in ticks, between first activation and second activation.
See also
setDelay
{
    return ticksDelay;
}
References RepeatButton::ticksDelay.
getInterval()
int getInterval () virtual
The interval between repeated activations, measured in ticks. This is the number of ticks between the an activation beyond the first and the following activation.
Returns
The interval between repeated activations, measured in ticks.
See also
setInterval
{
    return ticksInterval;
}
References RepeatButton::ticksInterval.
handleClickEvent()
void handleClickEvent (const ClickEvent & event) virtual
Updates the current state of the button. The state can be either pressed or released, and if the new state is different from the current state, the button is also invalidated to force a redraw.
If the button state is changed from ClickEvent::PRESSED to ClickEvent::RELEASED, the associated action (if any) is also executed.
Parameters
event Information about the click.
Reimplemented from AbstractButton.
{
    pressed = false; // To prevent AbstractButton from calling action->execute().
    invalidate();    // Force redraw after forced state change
    Button::handleClickEvent(event);
    if (event.getType() == ClickEvent::PRESSED)
    {
        executeAction();
        ticks = 0;
        ticksBeforeContinuous = ticksDelay;
        Application::getInstance()->registerTimerWidget(this);
    }
    else
    {
        Application::getInstance()->unregisterTimerWidget(this);
    }
}
References AbstractButton::executeAction(), Application::getInstance(), Drawable::handleClickEvent(), Drawable::invalidate(), ClickEvent::PRESSED, AbstractButton::pressed, RepeatButton::ticks, RepeatButton::ticksBeforeContinuous, and RepeatButton::ticksDelay.
handleTickEvent()
void handleTickEvent () virtual
Called periodically by the framework if the Drawable instance has subscribed to timer ticks.
See also
Application::registerTimerWidget
Reimplemented from Drawable.
{
    Button::handleTickEvent();
    if (!pressed)
    {
        return;
    }
    if (ticks == ticksBeforeContinuous)
    {
        executeAction();
        ticks = 0;
        ticksBeforeContinuous = ticksInterval;
    }
    else
    {
        ticks++;
    }
}
References AbstractButton::executeAction(), Drawable::handleTickEvent(), AbstractButton::pressed, RepeatButton::ticks, RepeatButton::ticksBeforeContinuous, and RepeatButton::ticksInterval.
setDelay()
void setDelay (int delay) virtual
Sets the delay (in number of ticks) from the first button activation until the next time it will be automatically activated.
Parameters
delay The delay, measured in ticks, between first activation and second activation.
See also
setInterval, getDelay
{
    ticksDelay = delay;
}
References RepeatButton::ticksDelay.
setInterval()
void setInterval (int interval) virtual
Sets the interval in number of ticks between each each activation of the pressed button after the second activation.
Parameters
interval The interval between repeated activations, measured in ticks.
See also
setDelay, getInterval
{
    ticksInterval = interval;
}
References RepeatButton::ticksInterval.
Member Data Documentation
ticks
int16_t ticks private
Referenced by RepeatButton::handleClickEvent(), and RepeatButton::handleTickEvent().
ticksBeforeContinuous
int16_t ticksBeforeContinuous private
Referenced by RepeatButton::handleClickEvent(), and RepeatButton::handleTickEvent().
ticksDelay
int16_t ticksDelay private
Referenced by RepeatButton::getDelay(), RepeatButton::handleClickEvent(), and RepeatButton::setDelay().
ticksInterval
int16_t ticksInterval private
Referenced by RepeatButton::getInterval(), RepeatButton::handleTickEvent(), and RepeatButton::setInterval().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/RepeatButton.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/RepeatButton.cpp