Battery Simulator Documentation: RadioButton
RadioButton
#include "RadioButton.hpp"
Public Member Functions
RadioButton ()
virtual void draw (const Rect &invalidatedArea) const
void executeDeselectedAction ()
uint8_t getAlpha () const
Bitmap getCurrentlyDisplayedBitmap () const
bool getDeselectionEnabled () const
bool getSelected () const
virtual Rect getSolidRect () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void invalidateContent () const
void setAlpha (uint8_t newAlpha)
virtual void setBitmaps (const Bitmap &bmpUnselected, const Bitmap &bmpUnselectedPressed, const Bitmap &bmpSelected, const Bitmap &bmpSelectedPressed)
void setDeselectedAction (GenericCallback< const AbstractButton & > &callback)
void setDeselectionEnabled (bool state)
void setSelected (bool newSelected)
Public Member Functions inherited from AbstractButton
AbstractButton ()
virtual void executeAction ()
virtual bool getPressedState () const
void setAction (GenericCallback< const AbstractButton & > &callback)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
uint8_t alpha
The current alpha value. 255=solid, 0=invisible.
Bitmap bitmapSelected
The image to display when radio button selected and released.
Bitmap bitmapSelectedPressed
The image to display when radio button selected and pressed.
Bitmap bitmapUnselected
The image to display when radio button unselected and released.
Bitmap bitmapUnselectedPressed
The image to display when radio button unselected and pressed.
GenericCallback< const AbstractButton & > * deselectedAction
The callback to be executed when this AbstractButton is deselected.
bool deselectionEnabled
Is it possible to deselect by pressing a selected RadioButton.
bool selected
The current selected state.
Protected Attributes inherited from AbstractButton
GenericCallback< const AbstractButton & > * action
The callback to be executed when this AbstractButton is clicked.
bool pressed
Is the button pressed or released? True if pressed.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
Radio button with two states. A RadioButton is a button that changes appearance (state) when it has been pushed. Pushing the RadioButton again will return the to original state.
To make managing radio buttons much easier, they can be added to a RadioButtonGroup which then automates deselecting radio buttons when a new radio button is pressed.
See also
RadioButtonGroup
Constructor & Destructor Documentation
RadioButton()
RadioButton () inline
        : AbstractButton(), bitmapUnselected(), bitmapUnselectedPressed(), bitmapSelected(), bitmapSelectedPressed(), alpha(255), selected(false), deselectionEnabled(false), deselectedAction(0)
    {
    }
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Implements Drawable.
{
    const Bitmap bitmap = getCurrentlyDisplayedBitmap();
    if (bitmap.getId() != BITMAP_INVALID)
    {
        Rect meAbs;
        translateRectToAbsolute(meAbs); // To find our x and y coords in absolute.
        // Calculate intersection between bitmap rect and invalidated area.
        const Rect dirtyBitmapArea = bitmap.getRect() & invalidatedArea;
        if (!dirtyBitmapArea.isEmpty())
        {
            HAL::lcd().drawPartialBitmap(bitmap, meAbs.x, meAbs.y, dirtyBitmapArea, alpha);
        }
    }
}
References touchgfx::BITMAP_INVALID, RadioButton::getCurrentlyDisplayedBitmap(), HAL::lcd(), and Drawable::translateRectToAbsolute().
executeDeselectedAction()
void executeDeselectedAction () inline
Executes the previously set action.
See also
setDeselectedAction
    {
        if (deselectedAction && deselectedAction->isValid())
        {
            deselectedAction->execute(*this);
        }
    }
References RadioButton::deselectedAction.
Referenced by RadioButton::setSelected().
getAlpha()
uint8_t getAlpha () const inline
Gets the current alpha value, as previously set using setAlpha. The default alpha value (if the alpha value has not been changed using setAlpha) is 255=solid.
Returns
The current alpha value ranging from 255=solid to 0=invisible.
See also
setAlpha
    {
        return alpha;
    }
References RadioButton::alpha.
getCurrentlyDisplayedBitmap()
Bitmap getCurrentlyDisplayedBitmap () const inline
Gets currently displayed bitmap. This depends on whether the RadioButton is currently selected or not and whether it is being pressed or not, i.e. it depends on the radio button's pressed and selected state.
Returns
The bitmap currently displayed.
    {
        return (selected ? (AbstractButton::pressed ? bitmapSelectedPressed : bitmapSelected) : (AbstractButton::pressed ? bitmapUnselectedPressed : bitmapUnselected));
    }
References RadioButton::bitmapSelected, RadioButton::bitmapSelectedPressed, RadioButton::bitmapUnselected, RadioButton::bitmapUnselectedPressed, AbstractButton::pressed, and RadioButton::selected.
Referenced by RadioButton::draw(), and RadioButton::getSolidRect().
getDeselectionEnabled()
bool getDeselectionEnabled () const inline
Gets the current deselectionEnabled state.
Returns
The current deselectionEnabled state.
See also
setDeselectionEnabled
    {
        return deselectionEnabled;
    }
References RadioButton::deselectionEnabled.
Referenced by RadioButtonGroup< CAPACITY >::getDeselectionEnabled().
getSelected()
bool getSelected () const inline
Gets the current selected state.
Returns
The current selected state.
    {
        return selected;
    }
References RadioButton::selected.
Referenced by RadioButton::handleClickEvent().
getSolidRect()
Rect getSolidRect () const virtual
Get (the largest possible) rectangle that is guaranteed to be solid (opaque). This information is important, as any Drawable underneath the solid area does not need to be drawn.
Returns
The solid rectangle part of the Drawable.
Note
The rectangle returned must be relative to upper left corner of the Drawable, meaning that a completely solid widget should return the full size Rect(0, 0, getWidth(), getHeight()). If no area can be guaranteed to be solid, an empty Rect must be returned. Failing to return the correct rectangle may result in errors on the display.
Implements Drawable.
{
    if (alpha < 255)
    {
        return Rect();
    }
    return getCurrentlyDisplayedBitmap().getSolidRect();
}
References RadioButton::getCurrentlyDisplayedBitmap(), and Bitmap::getSolidRect().
handleClickEvent()
void handleClickEvent (const ClickEvent & event) virtual
Updates the current state of the button. The state can be either pressed or released, and if the new state is different from the current state, the button is also invalidated to force a redraw.
If the button state is changed from ClickEvent::PRESSED to ClickEvent::RELEASED, the associated action (if any) is also executed.
Parameters
event Information about the click.
Reimplemented from AbstractButton.
{
    const bool wasPressed = pressed;
    pressed = (event.getType() == ClickEvent::PRESSED);
    if ((pressed && !wasPressed) || (!pressed && wasPressed))
    {
        invalidate();
    }
    if (wasPressed && (event.getType() == ClickEvent::RELEASED))
    {
        if (deselectionEnabled)
        {
            setSelected(!getSelected());
        }
        else if (!getSelected())
        {
            setSelected(true);
        }
    }
}
References RadioButton::deselectionEnabled, RadioButton::getSelected(), Drawable::invalidate(), ClickEvent::PRESSED, AbstractButton::pressed, ClickEvent::RELEASED, and RadioButton::setSelected().
invalidateContent()
virtual void invalidateContent () const inline virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from Drawable.
    {
        if (alpha > 0)
        {
            AbstractButton::invalidateContent();
        }
    }
References Drawable::invalidateContent().
setAlpha()
void setAlpha (uint8_t newAlpha) inline
Sets the alpha channel for the RadioButton, i.e. all the images used. The default alpha value on a RadioButton is 255.
Parameters
newAlpha The alpha value ranging from 255=solid to 0=invisible.
See also
getAlpha
    {
        alpha = newAlpha;
    }
setBitmaps()
void setBitmaps (const Bitmap & bmpUnselected, const Bitmap & bmpUnselectedPressed, const Bitmap & bmpSelected, const Bitmap & bmpSelectedPressed) virtual
Sets the four bitmaps used by this button. The first two bitmaps must show the unselected Button when it is released and pressed. The last two bitmaps must show the selected Button when it is released and pressed.
Parameters
bmpUnselected Bitmap to use when button is unselected and released.
bmpUnselectedPressed Bitmap to use when button is unselected and pressed.
bmpSelected Bitmap to use when button is selected and released.
bmpSelectedPressed Bitmap to use when button is selected and pressed.
Note
It is not uncommon to have the same bitmap for released (normal) and pressed state.
{
    bitmapUnselected = bmpUnselected;
    bitmapUnselectedPressed = bmpUnselectedPressed;
    bitmapSelected = bmpSelected;
    bitmapSelectedPressed = bmpSelectedPressed;
    RadioButton::setWidthHeight(bitmapUnselected);
}
References RadioButton::bitmapSelected, RadioButton::bitmapSelectedPressed, RadioButton::bitmapUnselected, RadioButton::bitmapUnselectedPressed, and Drawable::setWidthHeight().
setDeselectedAction()
void setDeselectedAction (GenericCallback< const AbstractButton & > & callback) inline
Associates an action to be performed when the RadioButton is deselected.
Parameters
callback The callback to be executed. The callback will be given a reference to the AbstractButton.
Note
The action performed when the RadioButton is selected, is set using setAction().
    {
        deselectedAction = &callback;
    }
References RadioButton::deselectedAction.
setDeselectionEnabled()
void setDeselectionEnabled (bool state) inline
Sets whether or not it is possible to deselect the RadioButton by clicking it. By default it is not possible to deselect a RadioButton. The meaning of this is most clear when the RadioButton is used in a RadioButtonGroup where exactly one RadioButton should always be selected. Pressing the currently selected RadioButton should not deselect it, but rather select it again. This makes the button "sticky", i.e. a button can only be deselected by selecting another RadioButton in the same RadioButtonGroup.
Parameters
state true if it should be possible to deselect by click. Default is false.
See also
getDeselectionEnabled
    {
        deselectionEnabled = state;
    }
References RadioButton::deselectionEnabled, and state.
Referenced by RadioButtonGroup< CAPACITY >::setDeselectionEnabled().
setSelected()
void setSelected (bool newSelected)
Sets the radio buttons selected state. Note that the associated action is also performed.
Parameters
newSelected The new selected state.
See also
setAction, setDeselectedAction, RadioButtonGroup
Note
If the RadioButton is part of a RadioButtonGroup, setting the selected state of individual RadioButtons is not recommended.
{
    const bool wasSelected = selected;
    selected = newSelected;
    if (wasSelected && !newSelected)
    {
        executeDeselectedAction();
    }
    if (!wasSelected && newSelected)
    {
        executeAction();
    }
    invalidate();
}
References AbstractButton::executeAction(), RadioButton::executeDeselectedAction(), Drawable::invalidate(), and RadioButton::selected.
Referenced by RadioButton::handleClickEvent(), and RadioButtonGroup< CAPACITY >::radioButtonClickedHandler().
Member Data Documentation
alpha
uint8_t alpha protected
The current alpha value. 255=solid, 0=invisible.
Referenced by RadioButton::getAlpha().
bitmapSelected
Bitmap bitmapSelected protected
The image to display when radio button selected and released.
Referenced by RadioButton::getCurrentlyDisplayedBitmap(), and RadioButton::setBitmaps().
bitmapSelectedPressed
Bitmap bitmapSelectedPressed protected
The image to display when radio button selected and pressed.
Referenced by RadioButton::getCurrentlyDisplayedBitmap(), and RadioButton::setBitmaps().
bitmapUnselected
Bitmap bitmapUnselected protected
The image to display when radio button unselected and released.
Referenced by RadioButton::getCurrentlyDisplayedBitmap(), and RadioButton::setBitmaps().
bitmapUnselectedPressed
Bitmap bitmapUnselectedPressed protected
The image to display when radio button unselected and pressed.
Referenced by RadioButton::getCurrentlyDisplayedBitmap(), and RadioButton::setBitmaps().
deselectedAction
GenericCallback<const AbstractButton&>* deselectedAction protected
The callback to be executed when this AbstractButton is deselected.
Referenced by RadioButton::executeDeselectedAction(), and RadioButton::setDeselectedAction().
deselectionEnabled
bool deselectionEnabled protected
Is it possible to deselect by pressing a selected RadioButton.
Referenced by RadioButton::getDeselectionEnabled(), RadioButton::handleClickEvent(), and RadioButton::setDeselectionEnabled().
selected
bool selected protected
The current selected state.
Referenced by RadioButton::getCurrentlyDisplayedBitmap(), RadioButton::getSelected(), and RadioButton::setSelected().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/RadioButton.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/RadioButton.cpp