Battery Simulator Documentation: TextArea::BoundingArea
TextArea::BoundingArea
#include "TextArea.hpp"
Public Member Functions
BoundingArea ()
BoundingArea (const Rect &boundingRect, const Unicode::UnicodeChar *containedText)
Rect getRect () const
bool isValid (const Unicode::UnicodeChar *currentText) const
Private Attributes
Rect rect
const Unicode::UnicodeChar * text
Detailed Description
Structure for the relationship between a bounding rectangle and the contained text.
Constructor & Destructor Documentation
BoundingArea() [1/2]
BoundingArea (const Rect & boundingRect, const Unicode::UnicodeChar * containedText) inline
Initializes a new instance of the BoundingArea class.
Parameters
boundingRect The bounding rectangle of this text area.
containedText A pointer to the text contained in the bounding rectangle.
            : rect(boundingRect), text(containedText)
        {
        }
BoundingArea() [2/2]
BoundingArea () inline
Initializes a new instance of the BoundingArea class which is invalid by default.
            : rect(Rect(0, 0, -1, -1)), // Negative width and height means invalid rectangle
              text(0)
        {
        }
Member Function Documentation
getRect()
Rect getRect () const inline
Gets bounding rectangle.
Returns
The bounding rectangle.
        {
            return rect;
        }
References TextArea::BoundingArea::rect.
Referenced by TextArea::draw(), and TextArea::invalidateContent().
isValid()
bool isValid (const Unicode::UnicodeChar * currentText) const inline
Query if the bounding area is valid.
Parameters
currentText A pointer to the current text of this text area.
Returns
True if valid otherwise false.
        {
            return (rect.height >= 0 && rect.width >= 0 && text == currentText);
        }
References Rect::height, TextArea::BoundingArea::rect, TextArea::BoundingArea::text, and Rect::width.
Referenced by TextArea::draw(), and TextArea::invalidateContent().
Member Data Documentation
rect
Rect rect private
Referenced by TextArea::BoundingArea::getRect(), and TextArea::BoundingArea::isValid().
text
const Unicode::UnicodeChar* text private
Referenced by TextArea::BoundingArea::isValid().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/TextArea.hpp