Battery Simulator Documentation: GraphWrapAndOverwriteData
GraphWrapAndOverwriteData
#include "GraphWrapAndOverwrite.hpp"
Public Member Functions
GraphWrapAndOverwriteData (int16_t capacity, int *values)
virtual void clear ()
virtual int32_t indexToGlobalIndex (int16_t index) const
Public Member Functions inherited from DynamicDataGraph
DynamicDataGraph (int16_t capacity, int *values)
FORCE_INLINE_FUNCTION int16_t addDataPoint (float y)
FORCE_INLINE_FUNCTION int16_t addDataPoint (int y)
int16_t addDataPointScaled (int y)
virtual int getGraphRangeXMax () const
virtual int getGraphRangeXMin () const
virtual int getScale () const
virtual float getXAxisFactorAsFloat () const
virtual int getXAxisFactorAsInt () const
virtual int getXAxisFactorScaled () const
virtual float getXAxisOffsetAsFloat () const
virtual int getXAxisOffsetAsInt () const
virtual int getXAxisOffsetScaled () const
virtual int indexToDataPointXScaled (int16_t index) const
virtual int indexToDataPointYScaled (int16_t index) const
virtual void setGraphRangeXAutoScaled (bool, int margin)
virtual void setGraphRangeYAutoScaled (bool showXaxis, int margin)
virtual void setScale (int scale, bool updateData=false)
virtual void setXAxisFactor (float factor)
virtual void setXAxisFactor (int factor)
virtual void setXAxisFactorScaled (int factor)
virtual void setXAxisOffset (float offset)
virtual void setXAxisOffset (int offset)
virtual void setXAxisOffsetScaled (int offset)
Public Member Functions inherited from AbstractDataGraph
AbstractDataGraph (int16_t capacity)
void addBottomElement (AbstractGraphDecoration &d)
void addGraphElement (AbstractGraphElement &d)
void addLeftElement (AbstractGraphDecoration &d)
void addRightElement (AbstractGraphDecoration &d)
void addTopElement (AbstractGraphDecoration &d)
FORCE_INLINE_FUNCTION int float2scaledX (float f) const
FORCE_INLINE_FUNCTION int float2scaledY (float f) const
FORCE_INLINE_FUNCTION uint8_t getAlpha () const
FORCE_INLINE_FUNCTION int16_t getGapBeforeIndex () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaHeight () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaHeightIncludingPadding () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginBottom () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginLeft () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginRight () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginTop () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingBottom () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingLeft () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingRight () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingTop () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaWidth () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaWidthIncludingPadding () const
virtual float getGraphRangeXMaxAsFloat () const
virtual int getGraphRangeXMaxAsInt () const
virtual int getGraphRangeXMaxScaled () const
virtual float getGraphRangeXMinAsFloat () const
virtual int getGraphRangeXMinAsInt () const
virtual int getGraphRangeXMinScaled () const
virtual float getGraphRangeYMaxAsFloat () const
virtual int getGraphRangeYMaxAsInt () const
virtual int getGraphRangeYMaxScaled () const
virtual float getGraphRangeYMinAsFloat () const
virtual int getGraphRangeYMinAsInt () const
virtual int getGraphRangeYMinScaled () const
FORCE_INLINE_FUNCTION int16_t getMaxCapacity () const
virtual bool getNearestIndexForScreenX (int16_t x, int16_t &index) const
virtual bool getNearestIndexForScreenXY (int16_t x, int16_t y, int16_t &index)
FORCE_INLINE_FUNCTION int16_t getUsedCapacity () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
FORCE_INLINE_FUNCTION void indexToDataPoint (int16_t index, float &xvalue, float &yvalue) const
FORCE_INLINE_FUNCTION void indexToDataPoint (int16_t index, int &xvalue, int &yvalue) const
FORCE_INLINE_FUNCTION void indexToDataPointScaled (int16_t index, int &xvalue, int &yvalue) const
FORCE_INLINE_FUNCTION float indexToDataPointXAsFloat (int16_t index) const
FORCE_INLINE_FUNCTION int indexToDataPointXAsInt (int16_t index) const
FORCE_INLINE_FUNCTION float indexToDataPointYAsFloat (int16_t index) const
FORCE_INLINE_FUNCTION int indexToDataPointYAsInt (int16_t index) const
FORCE_INLINE_FUNCTION int16_t indexToScreenX (int16_t index) const
FORCE_INLINE_FUNCTION int16_t indexToScreenY (int16_t index) const
FORCE_INLINE_FUNCTION int int2scaledX (int i) const
FORCE_INLINE_FUNCTION int int2scaledY (int i) const
virtual void invalidateContent () const
FORCE_INLINE_FUNCTION float scaled2floatX (int i) const
FORCE_INLINE_FUNCTION float scaled2floatY (int i) const
FORCE_INLINE_FUNCTION int scaled2intX (int i) const
FORCE_INLINE_FUNCTION int scaled2intY (int i) const
virtual void setAlpha (uint8_t newAlpha)
FORCE_INLINE_FUNCTION void setClickAction (GenericCallback< const AbstractDataGraph &, const GraphClickEvent & > &callback)
FORCE_INLINE_FUNCTION void setDragAction (GenericCallback< const AbstractDataGraph &, const GraphDragEvent & > &callback)
FORCE_INLINE_FUNCTION void setGapBeforeIndex (int16_t index)
void setGraphAreaMargin (int16_t top, int16_t left, int16_t right, int16_t bottom)
void setGraphAreaPadding (int16_t top, int16_t left, int16_t right, int16_t bottom)
FORCE_INLINE_FUNCTION void setGraphRange (float xMin, float xMax, float yMin, float yMax)
FORCE_INLINE_FUNCTION void setGraphRange (float xMin, float xMax, int yMin, int yMax)
FORCE_INLINE_FUNCTION void setGraphRange (int xMin, int xMax, float yMin, float yMax)
FORCE_INLINE_FUNCTION void setGraphRange (int xMin, int xMax, int yMin, int yMax)
FORCE_INLINE_FUNCTION void setGraphRangeScaled (int xMin, int xMax, int yMin, int yMax)
virtual void setGraphRangeX (float min, float max)
virtual void setGraphRangeX (int min, int max)
virtual void setGraphRangeXAuto (bool showYaxis, float margin)
virtual void setGraphRangeXAuto (bool showYaxis=true, int margin=0)
virtual void setGraphRangeXScaled (int min, int max)
virtual void setGraphRangeY (float min, float max)
virtual void setGraphRangeY (int min, int max)
virtual void setGraphRangeYAuto (bool showXaxis, float margin)
virtual void setGraphRangeYAuto (bool showXaxis=true, int margin=0)
virtual void setGraphRangeYScaled (int min, int max)
virtual void setHeight (int16_t height)
virtual void setWidth (int16_t width)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual int16_t addValue (int value)
virtual void beforeAddValue ()
Protected Member Functions inherited from DynamicDataGraph
virtual int16_t dataIndex (int16_t screenIndex) const
virtual int getScaleX () const
virtual int getScaleY () const
virtual CWRUtil::Q5 indexToScreenXQ5 (int16_t index) const
virtual CWRUtil::Q5 indexToScreenYQ5 (int16_t index) const
virtual int indexToXAxis (const int valueScaled, const int) const
virtual void setScaleX (int scale, bool updateData=false)
virtual void setScaleY (int scale, bool updateData=false)
virtual bool xScreenRangeToIndexRange (int16_t xMin, int16_t xMax, int16_t &indexMin, int16_t &indexMax) const
Protected Member Functions inherited from AbstractDataGraph
void invalidateAllXAxisPoints ()
FORCE_INLINE_FUNCTION void invalidateGraphArea () const
void invalidateGraphPointAt (int16_t index)
void invalidateXAxisPointAt (int16_t index)
void updateAreasPosition ()
virtual CWRUtil::Q5 valueToScreenXQ5 (int x) const
virtual CWRUtil::Q5 valueToScreenYQ5 (int y) const
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
int16_t current
The current index (used to keep track of where to insert new data point in value array)
Protected Attributes inherited from DynamicDataGraph
uint32_t dataCounter
The data counter of how many times addDataPoint() has been called.
int xAxisFactor
The axis scale (real distance between two indices)
int xAxisOffset
The x axis offset (real value of data point at index 0)
int * yValues
The values of the graph.
Protected Attributes inherited from AbstractDataGraph
uint8_t alpha
The alpha of the entire graph.
Container bottomArea
The area below the graph.
int16_t bottomPadding
The graph area bottom padding.
GenericCallback< const AbstractDataGraph &, const GraphClickEvent & > * clickAction
The callback to be executed when this Graph is clicked.
GenericCallback< const AbstractDataGraph &, const GraphDragEvent & > * dragAction
The callback to be executed when this Graph is dragged.
int16_t gapBeforeIndex
The graph is disconnected (there is a gap) before this element index.
Container graphArea
The graph area (the center area)
int graphRangeMaxX
The graph range maximum x coordinate.
int graphRangeMaxY
The graph range maximum y coordinate.
int graphRangeMinX
The graph range minimum x coordinate.
int graphRangeMinY
The graph range minimum y coordinate.
Container leftArea
The area to the left of the graph.
int16_t leftPadding
The graph area left padding.
int16_t maxCapacity
Maximum number of points in the graph.
Container rightArea
The area to the right of the graph.
int16_t rightPadding
The graph area right padding.
Container topArea
The area above the graph.
int16_t topPadding
The graph area top padding.
int16_t usedCapacity
The number of used points in the graph.
int xScale
The data scale for the x values.
int yScale
The data scale for the y values.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataGraph
static int convertToNewScale (int value, int oldScale, int newScale)
static FORCE_INLINE_FUNCTION int float2scaled (float f, int scale)
static FORCE_INLINE_FUNCTION int int2scaled (int i, int scale)
static FORCE_INLINE_FUNCTION float scaled2float (int i, int scale)
static FORCE_INLINE_FUNCTION int scaled2int (int i, int scale)
Detailed Description
A continuous data graph which will fill the graph with elements, and overwrite the first elements with new values after the graph has filled. There will be a gap between the newly inserted element and the element after. This similar behavior to a heart beat monitor.
Constructor & Destructor Documentation
GraphWrapAndOverwriteData()
GraphWrapAndOverwriteData (int16_t capacity, int * values) inline
Initializes a new instance of the GraphWrapAndOverwriteData class.
Parameters
capacity The capacity.
[in] values Pointer to memory with room for capacity elements of type T.
        : DynamicDataGraph(capacity, values), current(0)
    {
    }
Member Function Documentation
addValue()
int16_t addValue (int value) protected virtual
Adds a value to the internal data array and keeps track of when graph points, graph axis and the entire graph needs to be redrawn (invalidated).
Parameters
value The value to add to the array.
Returns
The index of the newly added value.
Implements DynamicDataGraph.
{
    const int16_t index = current++;
    current %= maxCapacity;
    if (index == usedCapacity)
    {
        usedCapacity++;
    }
    yValues[dataIndex(index)] = value;
    setGapBeforeIndex(index + 1);
    invalidateGraphPointAt(index);
    if (usedCapacity >= maxCapacity)
    {
        invalidateXAxisPointAt(index);
    }
    if (index == 0 && usedCapacity >= maxCapacity)
    {
        const int xMin = getGraphRangeXMin();
        const int xMax = getGraphRangeXMax();
        for (int i = xMin; i < 0; i++)
        {
            invalidateXAxisPointAt(i);
        }
        for (int i = maxCapacity; i <= xMax; i++)
        {
            invalidateXAxisPointAt(i);
        }
    }
    return index;
}
References GraphWrapAndOverwriteData::current, DynamicDataGraph::dataIndex(), DynamicDataGraph::getGraphRangeXMax(), DynamicDataGraph::getGraphRangeXMin(), AbstractDataGraph::invalidateGraphPointAt(), AbstractDataGraph::invalidateXAxisPointAt(), AbstractDataGraph::maxCapacity, AbstractDataGraph::setGapBeforeIndex(), AbstractDataGraph::usedCapacity, and DynamicDataGraph::yValues.
beforeAddValue()
void beforeAddValue () protected virtual
This function is called before a new value (data point) is added. This allows for invalidation to be calculated based on the global data counter before it is increased as a result of adding the new point.
Reimplemented from DynamicDataGraph.
{
    if (current == 0 && usedCapacity >= maxCapacity)
    {
        const int xMin = getGraphRangeXMin();
        const int xMax = getGraphRangeXMax();
        for (int i = xMin; i < 0; i++)
        {
            invalidateXAxisPointAt(i);
        }
        for (int i = maxCapacity; i <= xMax; i++)
        {
            invalidateXAxisPointAt(i);
        }
    }
    if (usedCapacity >= maxCapacity)
    {
        invalidateGraphPointAt(current);
        invalidateXAxisPointAt(current);
    }
}
References GraphWrapAndOverwriteData::current, DynamicDataGraph::getGraphRangeXMax(), DynamicDataGraph::getGraphRangeXMin(), AbstractDataGraph::invalidateGraphPointAt(), AbstractDataGraph::invalidateXAxisPointAt(), AbstractDataGraph::maxCapacity, and AbstractDataGraph::usedCapacity.
clear()
void clear () virtual
Clears the graph to its blank/initial state. The graph is invalidated so that the empty graph will be drawn after a call to clear.
Reimplemented from AbstractDataGraph.
{
    DynamicDataGraph::clear();
    current = 0;
}
References AbstractDataGraph::clear(), and GraphWrapAndOverwriteData::current.
indexToGlobalIndex()
int32_t indexToGlobalIndex (int16_t index) const virtual
Convert an index to global index. The index is the index of any data point, The global index is a value that keeps growing whenever a new data point is added the the graph.
Parameters
index Zero-based index of the point.
Returns
The global index.
Reimplemented from DynamicDataGraph.
{
    if (this->usedCapacity < this->maxCapacity)
    {
        return index;
    }
    const int16_t gapIndex = this->getGapBeforeIndex();
    if (index < gapIndex)
    {
        return (this->dataCounter - gapIndex) + index;
    }
    return ((this->dataCounter - gapIndex) - this->maxCapacity) + index;
}
References DynamicDataGraph::dataCounter, AbstractDataGraph::getGapBeforeIndex(), and AbstractDataGraph::maxCapacity.
Member Data Documentation
current
int16_t current protected
The current index (used to keep track of where to insert new data point in value array)
Referenced by GraphWrapAndOverwriteData::addValue(), GraphWrapAndOverwriteData::beforeAddValue(), and GraphWrapAndOverwriteData::clear().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/graph/GraphWrapAndOverwrite.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph/GraphWrapAndOverwrite.cpp