Battery Simulator Documentation: SVGImage
SVGImage
#include "SVGImage.hpp"
Public Member Functions
SVGImage ()
virtual void draw (const Rect &invalidatedArea) const
float getImageHeight () const
float getImagePositionX () const
float getImagePositionY () const
float getImageWidth () const
float getRotation () const
float getRotationCenterX () const
float getRotationCenterY () const
float getScaleX () const
float getScaleY () const
virtual Rect getSolidRect () const
virtual void invalidateContent () const
void reset ()
void resizeToCurrentSVG ()
void setImagePosition (float imageX, float imageY)
void setRotation (float angle)
void setRotationCenter (float centerX, float centerY)
void setScale (float scale)
void setScale (float xScale, float yScale)
void setScaleX (float scale)
void setScaleY (float scale)
virtual void setSVG (uint16_t id)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
Matrix3x3 getTransformationMatrix () const
Protected Attributes
float imagePositionX
The SVG image position x coordinate.
float imagePositionY
The SVG image position y coordinate.
float rotation
The rotation.
float rotationCenterX
The rotation center x coordinate.
float rotationCenterY
The rotation center y coordinate.
float scaleX
The scale for width.
float scaleY
The scale for height.
uint16_t svgId
The SVG to display.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
Simple widget capable of showing a SVG image on the display.
See also
Image
Constructor & Destructor Documentation
SVGImage()
SVGImage () inline
Constructs a new Image with a default SVG (undefined) if none is specified.
See also
setSVG
        : Widget(), svgId(SVG_INVALID),
          scaleX(1.0f), scaleY(1.0f), rotation(0.0f), rotationCenterX(0.0f), rotationCenterY(0.0f),
          imagePositionX(0.0f), imagePositionY(0.0f)
    {
    }
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Implements Drawable.
{
    if (svgId == SVG_INVALID)
    {
        return;
    }
    const VGObject* const table = SVGDatabase::getInstance();
    const VGObject& image = table[svgId];
    VectorRenderer* renderer = VectorRenderer::getInstance();
    assert(renderer && "No VectorRenderer instance found!");
    renderer->setup(getAbsoluteRect(), invalidatedArea);
    const Matrix3x3 matrix = getTransformationMatrix();
    for (const VGShape* shape = image.shape; shape != 0; shape = shape->next)
    {
        Matrix3x3 shapeMatrix;
        shapeMatrix.setAffineTransformation(shape->transformation);
        shapeMatrix = matrix.multiply(shapeMatrix);
        // Skip entire shape if bounding box does not cover invalidatedArea
        // Find bounding box including stroke width
        const float strokeWidthHalf = shape->strokeWidth / 2.0f;
        const float bb_xMin = shape->boundingbox[0] - strokeWidthHalf;
        const float bb_yMin = shape->boundingbox[1] - strokeWidthHalf;
        const float bb_xMax = shape->boundingbox[2] + strokeWidthHalf;
        const float bb_yMax = shape->boundingbox[3] + strokeWidthHalf;
        // Transform bounding box corners
        const Matrix3x3::Point p1 = shapeMatrix.affineTransform(bb_xMin, bb_yMin);
        const Matrix3x3::Point p2 = shapeMatrix.affineTransform(bb_xMin, bb_yMax);
        const Matrix3x3::Point p3 = shapeMatrix.affineTransform(bb_xMax, bb_yMin);
        const Matrix3x3::Point p4 = shapeMatrix.affineTransform(bb_xMax, bb_yMax);
        // Find limits of transformed box
        const int16_t x_min = static_cast<int16_t>(floorf(MIN(MIN(p1.x, p2.x), MIN(p3.x, p4.x))));
        const int16_t x_max = static_cast<int16_t>(ceilf(MAX(MAX(p1.x, p2.x), MAX(p3.x, p4.x))));
        const int16_t y_min = static_cast<int16_t>(floorf(MIN(MIN(p1.y, p2.y), MIN(p3.y, p4.y))));
        const int16_t y_max = static_cast<int16_t>(ceilf(MAX(MAX(p1.y, p2.y), MAX(p3.y, p4.y))));
        const Rect shapeBox(x_min, y_min, (x_max - x_min) + 1, (y_max - y_min) + 1);
        if (shapeBox.intersect(invalidatedArea))
        {
            renderer->setTransformationMatrix(shapeMatrix);
            // First fill
            if (shape->fillMode != VG_NONE)
            {
                // Set drawing mode and color for this shape
                renderer->setMode((shape->drawingMode == VG_FILL_EVEN_ODD) ? VectorRenderer::FILL_EVEN_ODD : VectorRenderer::FILL_NON_ZERO);
                renderer->setAlpha(shape->fillAlpha);
                // Set the fill color
                switch (shape->fillMode)
                {
                case VG_NONE:
                    break; // Guarded above
                case VG_FIXED_COLOR:
                    {
                        const VGFixedColor* color = reinterpret_cast<const VGFixedColor*>(shape->fillPaint);
                        renderer->setColor(color->argb);
                        break;
                    }
                case VG_LINEAR_GRADIENT:
                    {
                        //Set shape box size on linear (and radial) gradient
                        const float width = shape->boundingbox[2] - shape->boundingbox[0];
                        const float height = shape->boundingbox[3] - shape->boundingbox[1];
                        const VGLinearGradient* linear = reinterpret_cast<const VGLinearGradient*>(shape->fillPaint);
                        renderer->setLinearGradient(linear->x0, linear->y0, linear->x1, linear->y1,
                                                    linear->stops, linear->stopPositions, linear->colors,
                                                    width, height,
                                                    linear->isSolid, linear->palette);
                        break;
                    }
                }
                // Draw this Shape
                renderer->drawPath(shape->commands, shape->numCommands, shape->points, shape->numPoints, shape->boundingbox);
            }
            // Then stroke
            if (shape->strokeMode != VG_NONE)
            {
                // Stroking is nonzero
                renderer->setMode(VectorRenderer::STROKE);
                renderer->setStrokeWidth(shape->strokeWidth);
                renderer->setStrokeLineCap(shape->strokeLineCap);
                renderer->setStrokeLineJoin(shape->strokeLineJoin);
                renderer->setStrokeMiterLimit(shape->strokeMiterLimit);
                renderer->setAlpha(shape->strokeAlpha);
                // Set the fill color
                switch (shape->strokeMode)
                {
                case VG_NONE:
                    break; // Guarded above
                case VG_FIXED_COLOR:
                    {
                        const VGFixedColor* color = reinterpret_cast<const VGFixedColor*>(shape->strokePaint);
                        renderer->setColor(color->argb);
                        break;
                    }
                case VG_LINEAR_GRADIENT:
                    {
                        //Set shape box size on linear (and radial) gradient
                        const float width = shape->boundingbox[2] - shape->boundingbox[0] + shape->strokeWidth;
                        const float height = shape->boundingbox[3] - shape->boundingbox[1] + shape->strokeWidth;
                        const VGLinearGradient* linear = reinterpret_cast<const VGLinearGradient*>(shape->strokePaint);
                        renderer->setLinearGradient(linear->x0, linear->y0, linear->x1, linear->y1,
                                                    linear->stops, linear->stopPositions, linear->colors,
                                                    width, height,
                                                    linear->isSolid, linear->palette);
                        break;
                    }
                }
                // Draw this Shape
                const float boundingbox[4] = { shape->boundingbox[0] - strokeWidthHalf, shape->boundingbox[1] - strokeWidthHalf,
                                               shape->boundingbox[2] + strokeWidthHalf, shape->boundingbox[3] + strokeWidthHalf };
                renderer->drawPath(shape->commands, shape->numCommands, shape->points, shape->numPoints, boundingbox);
            }
        }
    }
    // Finalize rendering
    renderer->tearDown();
}
References VectorRenderer::drawPath(), VectorRenderer::FILL_EVEN_ODD, VectorRenderer::FILL_NON_ZERO, Drawable::getAbsoluteRect(), VectorRenderer::getInstance(), SVGDatabase::getInstance(), SVGImage::getTransformationMatrix(), MAX, MIN, VectorRenderer::setAlpha(), VectorRenderer::setColor(), VectorRenderer::setLinearGradient(), VectorRenderer::setMode(), VectorRenderer::setStrokeLineCap(), VectorRenderer::setStrokeLineJoin(), VectorRenderer::setStrokeMiterLimit(), VectorRenderer::setStrokeWidth(), VectorRenderer::setTransformationMatrix(), VectorRenderer::setup(), VectorRenderer::STROKE, touchgfx::SVG_INVALID, SVGImage::svgId, VectorRenderer::tearDown(), touchgfx::VG_FILL_EVEN_ODD, touchgfx::VG_FIXED_COLOR, touchgfx::VG_LINEAR_GRADIENT, and touchgfx::VG_NONE.
getImageHeight()
float getImageHeight () const
Gets SVG height as given in the SVG image file. This is the width before applying any rotation and scaling.
Returns
The SVG height.
{
    if (svgId == SVG_INVALID)
    {
        return 0.0f;
    }
    const VGObject* const table = SVGDatabase::getInstance();
    const VGObject& image = table[svgId];
    return image.imageHeight;
}
References SVGDatabase::getInstance(), VGObject::imageHeight, touchgfx::SVG_INVALID, and SVGImage::svgId.
getImagePositionX()
float getImagePositionX () const inline
Gets image position x coordinate.
Returns
The image position x coordinate.
See also
setImagePosition
    {
        return imagePositionX;
    }
References SVGImage::imagePositionX.
getImagePositionY()
float getImagePositionY () const inline
Gets image position y coordinate.
Returns
The image position y coordinate.
See also
setImagePosition
    {
        return imagePositionY;
    }
References SVGImage::imagePositionY.
getImageWidth()
float getImageWidth () const
Gets SVG width as given in the SVG image file. This is the width before applying any rotation and scaling.
Returns
The SVG width.
{
    if (svgId == SVG_INVALID)
    {
        return 0.0f;
    }
    const VGObject* const table = SVGDatabase::getInstance();
    const VGObject& image = table[svgId];
    return image.imageWidth;
}
References SVGDatabase::getInstance(), VGObject::imageWidth, touchgfx::SVG_INVALID, and SVGImage::svgId.
getRotation()
float getRotation () const inline
Gets SVG rotation.
Returns
The SVG rotation.
See also
setRotation
    {
        return rotation;
    }
References SVGImage::rotation.
getRotationCenterX()
float getRotationCenterX () const inline
Gets rotation center x coordinate.
Returns
The rotation center x coordinate.
    {
        return rotationCenterX;
    }
References SVGImage::rotationCenterX.
getRotationCenterY()
float getRotationCenterY () const inline
Gets rotation center y coordinate.
Returns
The rotation center y coordinate.
    {
        return rotationCenterY;
    }
References SVGImage::rotationCenterY.
getScaleX()
float getScaleX () const inline
Gets SVG scale for width.
Returns
The SVG scale for width.
See also
setScale, setScaleX
    {
        return scaleX;
    }
References SVGImage::scaleX.
getScaleY()
float getScaleY () const inline
Gets SVG height scale.
Returns
The SVG scale for height.
See also
setScale, setScaleY
    {
        return scaleY;
    }
References SVGImage::scaleY.
getSolidRect()
virtual Rect getSolidRect () const inline virtual
Get (the largest possible) rectangle that is guaranteed to be solid (opaque). This information is important, as any Drawable underneath the solid area does not need to be drawn.
Returns
The solid rectangle part of the Drawable.
Note
The rectangle returned must be relative to upper left corner of the Drawable, meaning that a completely solid widget should return the full size Rect(0, 0, getWidth(), getHeight()). If no area can be guaranteed to be solid, an empty Rect must be returned. Failing to return the correct rectangle may result in errors on the display.
Implements Drawable.
    {
        return Rect();
    }
getTransformationMatrix()
touchgfx::Matrix3x3 getTransformationMatrix () const protected
Calculate the transformation matrix used when drawing the SVG.
Returns
The transformation matrix.
{
    Matrix3x3 matrix; // Implicit reset to identity matrix
    if (svgId != SVG_INVALID)
    {
        matrix.scale(scaleX, scaleY);
        matrix.translate(imagePositionX - rotationCenterX, imagePositionY - rotationCenterY);
        matrix.rotate(rotation);
        matrix.translate(rotationCenterX, rotationCenterY);
    }
    return matrix;
}
References SVGImage::imagePositionX, SVGImage::imagePositionY, SVGImage::rotation, SVGImage::rotationCenterX, SVGImage::rotationCenterY, Matrix3x3::scale(), SVGImage::scaleX, SVGImage::scaleY, touchgfx::SVG_INVALID, and SVGImage::svgId.
Referenced by SVGImage::draw(), SVGImage::invalidateContent(), and SVGImage::resizeToCurrentSVG().
invalidateContent()
void invalidateContent () const virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from Drawable.
{
    if (!visible || svgId == SVG_INVALID)
    {
        return;
    }
    const VGObject* const table = SVGDatabase::getInstance();
    const VGObject& image = table[svgId];
    const Matrix3x3 matrix = getTransformationMatrix();
    // Transform bounding box corners
    const Matrix3x3::Point p1 = matrix.affineTransform(image.x, image.y);
    const Matrix3x3::Point p2 = matrix.affineTransform(image.x, image.y + image.height);
    const Matrix3x3::Point p3 = matrix.affineTransform(image.x + image.width, image.y);
    const Matrix3x3::Point p4 = matrix.affineTransform(image.x + image.width, image.y + image.height);
    // Find limits of transformed box
    const int16_t x_min = static_cast<int16_t>(floorf(MIN(MIN(p1.x, p2.x), MIN(p3.x, p4.x))));
    const int16_t x_max = static_cast<int16_t>(ceilf(MAX(MAX(p1.x, p2.x), MAX(p3.x, p4.x))));
    const int16_t y_min = static_cast<int16_t>(floorf(MIN(MIN(p1.y, p2.y), MIN(p3.y, p4.y))));
    const int16_t y_max = static_cast<int16_t>(ceilf(MAX(MAX(p1.y, p2.y), MAX(p3.y, p4.y))));
    Rect r(x_min, y_min, (x_max - x_min) + 1, (y_max - y_min) + 1);
    invalidateRect(r);
}
References SVGDatabase::getInstance(), SVGImage::getTransformationMatrix(), Drawable::invalidateRect(), MAX, MIN, touchgfx::SVG_INVALID, SVGImage::svgId, and Drawable::visible.
reset()
void reset ()
Resets all adjustments made to the svg proportions.
{
    scaleX = 1.0f;
    scaleY = 1.0f;
    rotation = 0.0f;
    rotationCenterX = 0.0f;
    rotationCenterY = 0.0f;
    imagePositionX = 0.0f;
    imagePositionY = 0.0f;
}
References SVGImage::imagePositionX, SVGImage::imagePositionY, SVGImage::rotation, SVGImage::rotationCenterX, SVGImage::rotationCenterY, SVGImage::scaleX, and SVGImage::scaleY.
Referenced by SVGImage::setSVG().
resizeToCurrentSVG()
void resizeToCurrentSVG ()
Resize the Widget to match the size of the SVG drawing.
{
    if (svgId == SVG_INVALID)
    {
        return;
    }
    const VGObject* const table = SVGDatabase::getInstance();
    const VGObject& image = table[svgId];
    const Matrix3x3 matrix = getTransformationMatrix();
    // Transform bounding box corners
    const Matrix3x3::Point p1 = matrix.affineTransform(0.0f, 0.0f);
    const Matrix3x3::Point p2 = matrix.affineTransform(0.0f, image.imageHeight);
    const Matrix3x3::Point p3 = matrix.affineTransform(image.imageWidth, 0.0f);
    const Matrix3x3::Point p4 = matrix.affineTransform(image.imageWidth, image.imageHeight);
    // Find limits of transformed box
    const float x_max = MAX(MAX(p1.x, p2.x), MAX(p3.x, p4.x));
    const float y_max = MAX(MAX(p1.y, p2.y), MAX(p3.y, p4.y));
    setWidthHeight(static_cast<int16_t>(ceilf(x_max)), static_cast<int16_t>(ceilf(y_max)));
}
References SVGDatabase::getInstance(), SVGImage::getTransformationMatrix(), MAX, Drawable::setWidthHeight(), touchgfx::SVG_INVALID, and SVGImage::svgId.
Referenced by SVGImage::setSVG().
setImagePosition()
void setImagePosition (float imageX, float imageY) inline
Sets image position. This is used to move the SVG on the screen. Negative values move the SVG to the left and up.
Parameters
imageX The image x coordinate.
imageY The image y coordinate.
See also
getImagePositionX, getImagePositionY
    {
        imagePositionX = imageX;
        imagePositionY = imageY;
    }
References SVGImage::imagePositionX, and SVGImage::imagePositionY.
setRotation()
void setRotation (float angle) inline
Sets SVG rotation. The rotation is done around the position set in the previously set rotation center.
Parameters
angle The rotation angle.
See also
setRotationCenter, getRotation
    {
        rotation = angle;
    }
References SVGImage::rotation.
setRotationCenter()
void setRotationCenter (float centerX, float centerY) inline
Sets SVG rotation center. The position is relative to the topleft corner of the SVGImage widget, not relative to the SVG. The center is the position before applying any scaling.
Parameters
centerX The center x coordinate.
centerY The center y coordinate.
See also
getRotationCenterX, getRotationCenterY, setImagePosition
    {
        rotationCenterX = centerX;
        rotationCenterY = centerY;
    }
References Drawable::centerX(), Drawable::centerY(), SVGImage::rotationCenterX, and SVGImage::rotationCenterY.
setScale() [1/2]
void setScale (float scale) inline
Sets SVG scale for both width and height.
Parameters
scale The scale to apply to width and height.
    {
        setScale(scale, scale);
    }
References SVGImage::setScale().
Referenced by SVGImage::setScale().
setScale() [2/2]
void setScale (float xScale, float yScale) inline
Sets SVG scale for width and for height.
Parameters
xScale The scale for width.
yScale The scale for height.
See also
setScale(float), getScaleX, getScaleY
    {
        setScaleX(xScale);
        setScaleY(yScale);
    }
References SVGImage::setScaleX(), and SVGImage::setScaleY().
setScaleX()
void setScaleX (float scale) inline
Sets SVG scale for width.
Parameters
scale The scale for width.
See also
setScale(float), setScale(float,float), getScaleX
    {
        scaleX = scale;
    }
References SVGImage::scaleX.
Referenced by SVGImage::setScale().
setScaleY()
void setScaleY (float scale) inline
Sets SVG height scale.
Parameters
scale The scale for height.
See also
setScale(float), setScale(float,float), getScaleY
    {
        scaleY = scale;
    }
References SVGImage::scaleY.
Referenced by SVGImage::setScale().
setSVG()
void setSVG (uint16_t id) virtual
Sets the SVG for this SVGImage and updates the width and height of this widget (if the widget has not already been assigned a width and height) to match those of the SVG drawing. See the file generated/images/include/images/SVGDatabase.hpp.
Parameters
id The SVG ID.
See also
resizeToCurrentSVG
Note
The image is not resized and invalidated after setting the id.
{
    if (id >= SVGDatabase::getInstanceSize())
    {
        svgId = SVG_INVALID;
        return;
    }
    svgId = id;
    reset();
    // If the widget is empty, resize it to the size of the SVG
    if (rect.isEmpty())
    {
        resizeToCurrentSVG();
    }
}
References SVGDatabase::getInstanceSize(), Rect::isEmpty(), Drawable::rect, SVGImage::reset(), SVGImage::resizeToCurrentSVG(), touchgfx::SVG_INVALID, and SVGImage::svgId.
Member Data Documentation
imagePositionX
float imagePositionX protected
The SVG image position x coordinate.
Referenced by SVGImage::getImagePositionX(), SVGImage::getTransformationMatrix(), SVGImage::reset(), and SVGImage::setImagePosition().
imagePositionY
float imagePositionY protected
The SVG image position y coordinate.
Referenced by SVGImage::getImagePositionY(), SVGImage::getTransformationMatrix(), SVGImage::reset(), and SVGImage::setImagePosition().
rotation
float rotation protected
The rotation.
Referenced by SVGImage::getRotation(), SVGImage::getTransformationMatrix(), SVGImage::reset(), and SVGImage::setRotation().
rotationCenterX
float rotationCenterX protected
The rotation center x coordinate.
Referenced by SVGImage::getRotationCenterX(), SVGImage::getTransformationMatrix(), SVGImage::reset(), and SVGImage::setRotationCenter().
rotationCenterY
float rotationCenterY protected
The rotation center y coordinate.
Referenced by SVGImage::getRotationCenterY(), SVGImage::getTransformationMatrix(), SVGImage::reset(), and SVGImage::setRotationCenter().
scaleX
float scaleX protected
The scale for width.
Referenced by SVGImage::getScaleX(), SVGImage::getTransformationMatrix(), SVGImage::reset(), and SVGImage::setScaleX().
scaleY
float scaleY protected
The scale for height.
Referenced by SVGImage::getScaleY(), SVGImage::getTransformationMatrix(), SVGImage::reset(), and SVGImage::setScaleY().
svgId
uint16_t svgId protected
The SVG to display.
Referenced by SVGImage::draw(), SVGImage::getImageHeight(), SVGImage::getImageWidth(), SVGImage::getTransformationMatrix(), SVGImage::invalidateContent(), SVGImage::resizeToCurrentSVG(), and SVGImage::setSVG().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/SVGImage.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/SVGImage.cpp