Battery Simulator Documentation: AbstractDataGraph
AbstractDataGraph abstract
#include "AbstractDataGraph.hpp"
Classes
class GraphClickEvent
class GraphDragEvent
Public Member Functions
AbstractDataGraph (int16_t capacity)
void addBottomElement (AbstractGraphDecoration &d)
void addGraphElement (AbstractGraphElement &d)
void addLeftElement (AbstractGraphDecoration &d)
void addRightElement (AbstractGraphDecoration &d)
void addTopElement (AbstractGraphDecoration &d)
virtual void clear ()
FORCE_INLINE_FUNCTION int float2scaledX (float f) const
FORCE_INLINE_FUNCTION int float2scaledY (float f) const
FORCE_INLINE_FUNCTION uint8_t getAlpha () const
FORCE_INLINE_FUNCTION int16_t getGapBeforeIndex () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaHeight () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaHeightIncludingPadding () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginBottom () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginLeft () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginRight () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginTop () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingBottom () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingLeft () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingRight () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingTop () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaWidth () const
FORCE_INLINE_FUNCTION int16_t getGraphAreaWidthIncludingPadding () const
virtual float getGraphRangeXMaxAsFloat () const
virtual int getGraphRangeXMaxAsInt () const
virtual int getGraphRangeXMaxScaled () const
virtual float getGraphRangeXMinAsFloat () const
virtual int getGraphRangeXMinAsInt () const
virtual int getGraphRangeXMinScaled () const
virtual float getGraphRangeYMaxAsFloat () const
virtual int getGraphRangeYMaxAsInt () const
virtual int getGraphRangeYMaxScaled () const
virtual float getGraphRangeYMinAsFloat () const
virtual int getGraphRangeYMinAsInt () const
virtual int getGraphRangeYMinScaled () const
FORCE_INLINE_FUNCTION int16_t getMaxCapacity () const
virtual bool getNearestIndexForScreenX (int16_t x, int16_t &index) const
virtual bool getNearestIndexForScreenXY (int16_t x, int16_t y, int16_t &index)
virtual int getScaleX () const
virtual int getScaleY () const
FORCE_INLINE_FUNCTION int16_t getUsedCapacity () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
FORCE_INLINE_FUNCTION void indexToDataPoint (int16_t index, float &xvalue, float &yvalue) const
FORCE_INLINE_FUNCTION void indexToDataPoint (int16_t index, int &xvalue, int &yvalue) const
FORCE_INLINE_FUNCTION void indexToDataPointScaled (int16_t index, int &xvalue, int &yvalue) const
FORCE_INLINE_FUNCTION float indexToDataPointXAsFloat (int16_t index) const
FORCE_INLINE_FUNCTION int indexToDataPointXAsInt (int16_t index) const
virtual int indexToDataPointXScaled (int16_t index) const =0
FORCE_INLINE_FUNCTION float indexToDataPointYAsFloat (int16_t index) const
FORCE_INLINE_FUNCTION int indexToDataPointYAsInt (int16_t index) const
virtual int indexToDataPointYScaled (int16_t index) const =0
FORCE_INLINE_FUNCTION int16_t indexToScreenX (int16_t index) const
FORCE_INLINE_FUNCTION int16_t indexToScreenY (int16_t index) const
FORCE_INLINE_FUNCTION int int2scaledX (int i) const
FORCE_INLINE_FUNCTION int int2scaledY (int i) const
virtual void invalidateContent () const
FORCE_INLINE_FUNCTION float scaled2floatX (int i) const
FORCE_INLINE_FUNCTION float scaled2floatY (int i) const
FORCE_INLINE_FUNCTION int scaled2intX (int i) const
FORCE_INLINE_FUNCTION int scaled2intY (int i) const
virtual void setAlpha (uint8_t newAlpha)
FORCE_INLINE_FUNCTION void setClickAction (GenericCallback< const AbstractDataGraph &, const GraphClickEvent & > &callback)
FORCE_INLINE_FUNCTION void setDragAction (GenericCallback< const AbstractDataGraph &, const GraphDragEvent & > &callback)
FORCE_INLINE_FUNCTION void setGapBeforeIndex (int16_t index)
void setGraphAreaMargin (int16_t top, int16_t left, int16_t right, int16_t bottom)
void setGraphAreaPadding (int16_t top, int16_t left, int16_t right, int16_t bottom)
FORCE_INLINE_FUNCTION void setGraphRange (float xMin, float xMax, float yMin, float yMax)
FORCE_INLINE_FUNCTION void setGraphRange (float xMin, float xMax, int yMin, int yMax)
FORCE_INLINE_FUNCTION void setGraphRange (int xMin, int xMax, float yMin, float yMax)
FORCE_INLINE_FUNCTION void setGraphRange (int xMin, int xMax, int yMin, int yMax)
FORCE_INLINE_FUNCTION void setGraphRangeScaled (int xMin, int xMax, int yMin, int yMax)
virtual void setGraphRangeX (float min, float max)
virtual void setGraphRangeX (int min, int max)
virtual void setGraphRangeXAuto (bool showYaxis, float margin)
virtual void setGraphRangeXAuto (bool showYaxis=true, int margin=0)
virtual void setGraphRangeXAutoScaled (bool showYaxis, int margin)=0
virtual void setGraphRangeXScaled (int min, int max)
virtual void setGraphRangeY (float min, float max)
virtual void setGraphRangeY (int min, int max)
virtual void setGraphRangeYAuto (bool showXaxis, float margin)
virtual void setGraphRangeYAuto (bool showXaxis=true, int margin=0)
virtual void setGraphRangeYAutoScaled (bool showXaxis, int margin)=0
virtual void setGraphRangeYScaled (int min, int max)
virtual void setHeight (int16_t height)
virtual void setScaleX (int scale, bool updateData=false)
virtual void setScaleY (int scale, bool updateData=false)
virtual void setWidth (int16_t width)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Static Public Member Functions
static int convertToNewScale (int value, int oldScale, int newScale)
static FORCE_INLINE_FUNCTION int float2scaled (float f, int scale)
static FORCE_INLINE_FUNCTION int int2scaled (int i, int scale)
static FORCE_INLINE_FUNCTION float scaled2float (int i, int scale)
static FORCE_INLINE_FUNCTION int scaled2int (int i, int scale)
Protected Member Functions
virtual CWRUtil::Q5 indexToScreenXQ5 (int16_t index) const =0
virtual CWRUtil::Q5 indexToScreenYQ5 (int16_t index) const =0
virtual int indexToXAxis (const int valueScaled, const int labelScaled) const =0
void invalidateAllXAxisPoints ()
FORCE_INLINE_FUNCTION void invalidateGraphArea () const
void invalidateGraphPointAt (int16_t index)
void invalidateXAxisPointAt (int16_t index)
void updateAreasPosition ()
virtual CWRUtil::Q5 valueToScreenXQ5 (int x) const
virtual CWRUtil::Q5 valueToScreenYQ5 (int y) const
virtual bool xScreenRangeToIndexRange (int16_t xMin, int16_t xMax, int16_t &indexMin, int16_t &indexMax) const =0
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
uint8_t alpha
The alpha of the entire graph.
Container bottomArea
The area below the graph.
int16_t bottomPadding
The graph area bottom padding.
GenericCallback< const AbstractDataGraph &, const GraphClickEvent & > * clickAction
The callback to be executed when this Graph is clicked.
GenericCallback< const AbstractDataGraph &, const GraphDragEvent & > * dragAction
The callback to be executed when this Graph is dragged.
int16_t gapBeforeIndex
The graph is disconnected (there is a gap) before this element index.
Container graphArea
The graph area (the center area)
int graphRangeMaxX
The graph range maximum x coordinate.
int graphRangeMaxY
The graph range maximum y coordinate.
int graphRangeMinX
The graph range minimum x coordinate.
int graphRangeMinY
The graph range minimum y coordinate.
Container leftArea
The area to the left of the graph.
int16_t leftPadding
The graph area left padding.
int16_t maxCapacity
Maximum number of points in the graph.
Container rightArea
The area to the right of the graph.
int16_t rightPadding
The graph area right padding.
Container topArea
The area above the graph.
int16_t topPadding
The graph area top padding.
int16_t usedCapacity
The number of used points in the graph.
int xScale
The data scale for the x values.
int yScale
The data scale for the y values.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
An abstract data graph. This class is the base for other graphs. For specific graphs, please refer to those implementation, e.g. GraphScroll, GraphWrapAndClear, GraphWrapAndOverwrite and StaticGraph.
Constructor & Destructor Documentation
AbstractDataGraph()
AbstractDataGraph (int16_t capacity)
Initializes a new instance of the AbstractDataGraph class.
Parameters
capacity The capacity, i.e. the number of points in the graph.
    : Container(),
      alpha(255), xScale(1), yScale(1),
      graphArea(), leftArea(), rightArea(), topArea(), bottomArea(),
      topPadding(0), leftPadding(0), rightPadding(0), bottomPadding(0),
      maxCapacity(capacity), usedCapacity(0), gapBeforeIndex(0), clickAction(0), dragAction(0),
      graphRangeMinX(0), graphRangeMaxX(0), graphRangeMinY(0), graphRangeMaxY(0)
{
    assert(capacity > 0);
    AbstractDataGraph::add(graphArea);
    AbstractDataGraph::add(topArea);
    AbstractDataGraph::add(leftArea);
    AbstractDataGraph::add(rightArea);
    AbstractDataGraph::add(bottomArea);
    // Place all areas properly:
    setGraphAreaMargin(0, 0, 0, 0);
    setTouchable(true);
}
References Container::add(), AbstractDataGraph::bottomArea, AbstractDataGraph::graphArea, AbstractDataGraph::leftArea, AbstractDataGraph::rightArea, AbstractDataGraph::setGraphAreaMargin(), Drawable::setTouchable(), and AbstractDataGraph::topArea.
Member Function Documentation
addBottomElement()
void addBottomElement (AbstractGraphDecoration & d)
Adds an element to be shown in the area below the graph. Labels and titles can be added here.
Parameters
[in] d an AbstractGraphElement to add.
See also
GraphLabelsX, GraphTitle
{
    bottomArea.add(d);
    d.setPosition(0, 0, bottomArea.getWidth(), bottomArea.getHeight());
}
References Container::add(), AbstractDataGraph::bottomArea, Drawable::getHeight(), and Drawable::getWidth().
addGraphElement()
void addGraphElement (AbstractGraphElement & d)
Adds a graph element which will display the graph. Several graph elements can be added. Examples of graph elements are lines, dots, histograms as well as horizontal and vertical grid lines.
Parameters
[in] d an AbstractGraphElement to add.
See also
GraphElementGridX, GraphElementGridY, GraphElementArea, GraphElementBoxes, GraphElementDiamonds, GraphElementDots, GraphElementHistogram, GraphElementLine,
{
    graphArea.add(d);
    d.setPosition(0, 0, graphArea.getWidth(), graphArea.getHeight());
}
References Container::add(), Drawable::getHeight(), Drawable::getWidth(), and AbstractDataGraph::graphArea.
addLeftElement()
void addLeftElement (AbstractGraphDecoration & d)
Adds an element to be shown in the area to the left of the graph. Labels and titles can be added here.
Parameters
[in] d an AbstractGraphElement to add.
See also
GraphLabelsY, GraphTitle
{
    leftArea.add(d);
    d.setPosition(0, 0, leftArea.getWidth(), leftArea.getHeight());
}
References Container::add(), Drawable::getHeight(), Drawable::getWidth(), and AbstractDataGraph::leftArea.
addRightElement()
void addRightElement (AbstractGraphDecoration & d)
Adds an element to be shown in the area to the right of the graph. Labels and titles can be added here.
Parameters
[in] d an AbstractGraphElement to add.
See also
GraphLabelsY, GraphTitle
{
    rightArea.add(d);
    d.setPosition(0, 0, rightArea.getWidth(), rightArea.getHeight());
}
References Container::add(), Drawable::getHeight(), Drawable::getWidth(), and AbstractDataGraph::rightArea.
addTopElement()
void addTopElement (AbstractGraphDecoration & d)
Adds an element to be shown in the area above the graph. Labels and titles can be added here.
Parameters
[in] d an AbstractGraphElement to add.
See also
GraphLabelsX, GraphTitle
{
    topArea.add(d);
    d.setPosition(0, 0, topArea.getWidth(), topArea.getHeight());
}
References Container::add(), Drawable::getHeight(), Drawable::getWidth(), and AbstractDataGraph::topArea.
clear()
void clear () virtual
Clears the graph to its blank/initial state. The graph is invalidated so that the empty graph will be drawn after a call to clear.
Reimplemented in GraphScrollData, GraphWrapAndClearData, and GraphWrapAndOverwriteData.
{
    usedCapacity = 0;
    invalidateGraphArea();
}
References AbstractDataGraph::invalidateGraphArea(), and AbstractDataGraph::usedCapacity.
Referenced by GraphScrollData::clear(), GraphWrapAndClearData::clear(), and GraphWrapAndOverwriteData::clear().
convertToNewScale()
int convertToNewScale (int value, int oldScale, int newScale) static
Converts a value from one scale to another scale. This would convert eg. 21 in scale 10 to 210 in scale 100 or to 2 in scale 1.
Parameters
value The value to convert to another scale.
oldScale The old (current) scale of the value.
newScale The new scale that the value should be converted to.
Returns
The given data converted to a new scale.
{
    if (oldScale == newScale)
    {
        return value;
    }
    return muldiv(value, newScale, oldScale);
}
References touchgfx::muldiv().
Referenced by AbstractGraphElement::convertToGraphScaleX(), AbstractGraphElement::convertToGraphScaleY(), GraphElementGridBase::setScale(), GraphElementArea::setScale(), GraphElementHistogram::setScale(), GraphLabelsBase::setScale(), DynamicDataGraph::setScaleX(), StaticDataGraph::setScaleX(), DynamicDataGraph::setScaleY(), and StaticDataGraph::setScaleY().
float2scaled()
static FORCE_INLINE_FUNCTION int float2scaled (float f, int scale) inline static
Multiply a floating point value with a constant and round the result.
Parameters
f the value to scale.
scale The scale.
Returns
The product of the two numbers, rounded to nearest integer value.
    {
        const float fs = f * (float)scale;
        if (fs >= 0)
        {
            return (int)(fs + 0.5f);
        }
        return ((int)fs - 1) + (int)(1.5f + (fs - (float)(int)fs));
    }
Referenced by AbstractDataGraph::float2scaledX(), AbstractDataGraph::float2scaledY(), GraphElementArea::setBaseline(), GraphElementHistogram::setBaseline(), GraphElementGridBase::setInterval(), and GraphLabelsBase::setInterval().
float2scaledX()
FORCE_INLINE_FUNCTION int float2scaledX (float f) const inline
Same as float2scaled(float, int) using the graph's x scale.
Parameters
f The floating point value to scale.
Returns
The scaled value.
Note
For internal use.
    {
        return float2scaled(f, xScale);
    }
References AbstractDataGraph::float2scaled(), and AbstractDataGraph::xScale.
Referenced by StaticDataGraph::addDataPoint(), StaticDataGraph::deleteDataPoint(), AbstractDataGraph::setGraphRangeX(), AbstractDataGraph::setGraphRangeXAuto(), DynamicDataGraph::setXAxisFactor(), and DynamicDataGraph::setXAxisOffset().
float2scaledY()
FORCE_INLINE_FUNCTION int float2scaledY (float f) const inline
Same as float2scaled(float, int) using the graph's y scale.
Parameters
f The floating point value to scale.
Returns
The scaled value.
Note
For internal use.
    {
        return float2scaled(f, yScale);
    }
References AbstractDataGraph::float2scaled(), and AbstractDataGraph::yScale.
Referenced by StaticDataGraph::addDataPoint(), DynamicDataGraph::addDataPoint(), AbstractDataGraph::setGraphRangeY(), and AbstractDataGraph::setGraphRangeYAuto().
getAlpha()
FORCE_INLINE_FUNCTION uint8_t getAlpha () const inline
Gets the current alpha value of the widget. The alpha value is in range 255 (solid) to 0 (invisible).
Returns
The current alpha value.
See also
setAlpha
    {
        return alpha;
    }
References AbstractDataGraph::alpha.
getGapBeforeIndex()
FORCE_INLINE_FUNCTION int16_t getGapBeforeIndex () const inline
Gets gap before index as set using setGapBeforeIndex().
Returns
The gap before index.
See also
setGapBeforeIndex
    {
        return gapBeforeIndex;
    }
References AbstractDataGraph::gapBeforeIndex.
Referenced by GraphWrapAndOverwriteData::indexToGlobalIndex().
getGraphAreaHeight()
FORCE_INLINE_FUNCTION int16_t getGraphAreaHeight () const inline
Gets graph area height. This is the height of the actual graph area and is the same as the height of the graph widget minus margin and padding.
Returns
The graph area height.
See also
setGraphAreaMargin, setGraphAreaPadding
    {
        return graphArea.getHeight() - (topPadding + bottomPadding);
    }
References AbstractDataGraph::bottomPadding, Drawable::getHeight(), AbstractDataGraph::graphArea, and AbstractDataGraph::topPadding.
Referenced by AbstractDataGraph::valueToScreenYQ5().
getGraphAreaHeightIncludingPadding()
FORCE_INLINE_FUNCTION int16_t getGraphAreaHeightIncludingPadding () const inline
Gets graph area height including padding (but not margin). This is the height of the actual graph area and is the same as the height of the graph widget minus margin.
Returns
The graph area height including graph padding.
See also
setGraphAreaMargin
    {
        return graphArea.getHeight();
    }
References Drawable::getHeight(), and AbstractDataGraph::graphArea.
getGraphAreaMarginBottom()
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginBottom () const inline
Gets graph margin bottom.
Returns
The graph margin bottom.
See also
setGraphAreaMargin
    {
        return bottomArea.getHeight();
    }
References AbstractDataGraph::bottomArea, and Drawable::getHeight().
getGraphAreaMarginLeft()
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginLeft () const inline
Gets graph margin left.
Returns
The graph margin left.
See also
setGraphAreaMargin
    {
        return leftArea.getWidth();
    }
References Drawable::getWidth(), and AbstractDataGraph::leftArea.
getGraphAreaMarginRight()
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginRight () const inline
Gets graph margin right.
Returns
The graph margin right.
See also
setGraphAreaMargin
    {
        return rightArea.getWidth();
    }
References Drawable::getWidth(), and AbstractDataGraph::rightArea.
getGraphAreaMarginTop()
FORCE_INLINE_FUNCTION int16_t getGraphAreaMarginTop () const inline
Gets graph margin top.
Returns
The graph margin top.
See also
setGraphAreaMargin
    {
        return topArea.getHeight();
    }
References Drawable::getHeight(), and AbstractDataGraph::topArea.
getGraphAreaPaddingBottom()
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingBottom () const inline
Gets graph area padding bottom.
Returns
The graph area padding bottom.
See also
setGraphAreaPadding
    {
        return bottomPadding;
    }
References AbstractDataGraph::bottomPadding.
getGraphAreaPaddingLeft()
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingLeft () const inline
Gets graph area padding left.
Returns
The graph area padding left.
See also
setGraphAreaPadding
    {
        return leftPadding;
    }
References AbstractDataGraph::leftPadding.
getGraphAreaPaddingRight()
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingRight () const inline
Gets graph area padding right.
Returns
The graph area padding right.
See also
setGraphAreaPadding
    {
        return rightPadding;
    }
References AbstractDataGraph::rightPadding.
getGraphAreaPaddingTop()
FORCE_INLINE_FUNCTION int16_t getGraphAreaPaddingTop () const inline
Gets graph area padding top.
Returns
The graph area padding top.
See also
setGraphAreaPadding
    {
        return topPadding;
    }
References AbstractDataGraph::topPadding.
getGraphAreaWidth()
FORCE_INLINE_FUNCTION int16_t getGraphAreaWidth () const inline
Gets graph area width. This is the width of the actual graph area and is the same as the width of the graph widget minus margin and padding.
Returns
The graph area width.
See also
setGraphAreaMargin, setGraphAreaPadding
    {
        return graphArea.getWidth() - (leftPadding + rightPadding);
    }
References Drawable::getWidth(), AbstractDataGraph::graphArea, AbstractDataGraph::leftPadding, and AbstractDataGraph::rightPadding.
Referenced by AbstractDataGraph::valueToScreenXQ5(), DynamicDataGraph::xScreenRangeToIndexRange(), and StaticDataGraph::xScreenRangeToIndexRange().
getGraphAreaWidthIncludingPadding()
FORCE_INLINE_FUNCTION int16_t getGraphAreaWidthIncludingPadding () const inline
Gets graph area width including padding (but not margin). This is the width of the actual graph area and is the same as the width of the graph widget minus margin.
Returns
The graph width including graph padding.
See also
setGraphAreaPadding
    {
        return graphArea.getWidth();
    }
References Drawable::getWidth(), and AbstractDataGraph::graphArea.
getGraphRangeXMaxAsFloat()
virtual float getGraphRangeXMaxAsFloat () const inline virtual
Gets maximum x value for the graph.
Returns
The maximum x value.
    {
        return scaled2floatX(graphRangeMaxX);
    }
References AbstractDataGraph::graphRangeMaxX, and AbstractDataGraph::scaled2floatX().
getGraphRangeXMaxAsInt()
virtual int getGraphRangeXMaxAsInt () const inline virtual
Gets maximum x value for the graph.
Returns
The maximum x value.
    {
        return scaled2intX(graphRangeMaxX);
    }
References AbstractDataGraph::graphRangeMaxX, and AbstractDataGraph::scaled2intX().
getGraphRangeXMaxScaled()
virtual int getGraphRangeXMaxScaled () const inline virtual
Gets maximum x value for the graph.
Returns
The maximum x value.
The graph range x coordinate maximum scaled.
See also
AbstractDataGraph::getGraphRangeXMaxAsInt, AbstractDataGraph::getGraphRangeXMaxAsFloat
Note
The returned value is left scaled.
    {
        return graphRangeMaxX;
    }
References AbstractDataGraph::graphRangeMaxX.
Referenced by DynamicDataGraph::getGraphRangeXMax(), and StaticDataGraph::setGraphRangeYAutoScaled().
getGraphRangeXMinAsFloat()
virtual float getGraphRangeXMinAsFloat () const inline virtual
Gets minimum x value for the graph.
Returns
The minimum x value.
    {
        return scaled2floatX(graphRangeMinX);
    }
References AbstractDataGraph::graphRangeMinX, and AbstractDataGraph::scaled2floatX().
getGraphRangeXMinAsInt()
virtual int getGraphRangeXMinAsInt () const inline virtual
Gets minimum x value for the graph.
Returns
The minimum x value.
    {
        return scaled2intX(graphRangeMinX);
    }
References AbstractDataGraph::graphRangeMinX, and AbstractDataGraph::scaled2intX().
getGraphRangeXMinScaled()
virtual int getGraphRangeXMinScaled () const inline virtual
Gets minimum x value for the graph.
Returns
The minimum x value.
The graph range x coordinate minimum scaled.
See also
AbstractDataGraph::getGraphRangeXMinAsInt, AbstractDataGraph::getGraphRangeXMinAsFloat
Note
The returned value is left scaled.
    {
        return graphRangeMinX;
    }
References AbstractDataGraph::graphRangeMinX.
Referenced by DynamicDataGraph::getGraphRangeXMin(), and StaticDataGraph::setGraphRangeYAutoScaled().
getGraphRangeYMaxAsFloat()
virtual float getGraphRangeYMaxAsFloat () const inline virtual
Gets maximum y value for the graph.
Returns
The maximum y value.
    {
        return scaled2floatY(graphRangeMaxY);
    }
References AbstractDataGraph::graphRangeMaxY, and AbstractDataGraph::scaled2floatY().
getGraphRangeYMaxAsInt()
virtual int getGraphRangeYMaxAsInt () const inline virtual
Gets maximum y value for the graph.
Returns
The maximum y value.
    {
        return scaled2intY(graphRangeMaxY);
    }
References AbstractDataGraph::graphRangeMaxY, and AbstractDataGraph::scaled2intY().
getGraphRangeYMaxScaled()
virtual int getGraphRangeYMaxScaled () const inline virtual
Gets maximum y value for the graph.
Returns
The maximum y value.
See also
AbstractDataGraph::getGraphRangeYMaxAsInt, AbstractDataGraph::getGraphRangeYMaxAsFloat
Note
The returned value is left scaled.
    {
        return graphRangeMaxY;
    }
References AbstractDataGraph::graphRangeMaxY.
getGraphRangeYMinAsFloat()
virtual float getGraphRangeYMinAsFloat () const inline virtual
Gets minimum y value for the graph.
Returns
The minimum y value.
    {
        return scaled2floatY(graphRangeMinY);
    }
References AbstractDataGraph::graphRangeMinY, and AbstractDataGraph::scaled2floatY().
getGraphRangeYMinAsInt()
virtual int getGraphRangeYMinAsInt () const inline virtual
Gets minimum y value for the graph.
Returns
The minimum y value.
    {
        return scaled2intY(graphRangeMinY);
    }
References AbstractDataGraph::graphRangeMinY, and AbstractDataGraph::scaled2intY().
getGraphRangeYMinScaled()
virtual int getGraphRangeYMinScaled () const inline virtual
Gets minimum y value for the graph.
Returns
The minimum y value.
See also
AbstractDataGraph::getGraphRangeYMinAsInt, AbstractDataGraph::getGraphRangeYMinAsFloat
Note
The returned value is left scaled.
    {
        return graphRangeMinY;
    }
References AbstractDataGraph::graphRangeMinY.
getMaxCapacity()
FORCE_INLINE_FUNCTION int16_t getMaxCapacity () const inline
Gets the capacity (max number of points) of the graph.
Returns
The capacity.
    {
        return maxCapacity;
    }
References AbstractDataGraph::maxCapacity.
getNearestIndexForScreenX()
bool getNearestIndexForScreenX (int16_t x, int16_t & index) const virtual
Gets graph index nearest to the given screen x value. The index of the graph point closest to the given x coordinate is handed back.
Parameters
x The x value.
[out] index Zero-based index of the.
Returns
True if it succeeds, false if it fails.
See also
getNearestIndexForScreenXY
{
    index = 0;
    if (usedCapacity == 0)
    {
        return false;
    }
    uint32_t bestDist = abs(indexToScreenX(index) - x);
    for (int16_t ix = 1; ix < usedCapacity; ix++)
    {
        const uint32_t dist = abs(indexToScreenX(ix) - x);
        if (dist < bestDist)
        {
            index = ix;
            bestDist = dist;
        }
    }
    return true;
}
References touchgfx::abs(), AbstractDataGraph::indexToScreenX(), and AbstractDataGraph::usedCapacity.
Referenced by AbstractDataGraph::handleClickEvent(), and AbstractDataGraph::handleDragEvent().
getNearestIndexForScreenXY()
bool getNearestIndexForScreenXY (int16_t x, int16_t y, int16_t & index) virtual
Gets graph index nearest to the given screen position. The distance to each point on the graph is measured and the index of the point closest to the given position handed back.
Parameters
x The x value.
y The y value.
[out] index Zero-based index of the point closest to the given position.
Returns
True if it succeeds, false if it fails.
See also
getNearestIndexForScreenX
{
    if (usedCapacity == 0)
    {
        return false;
    }
    uint32_t bestDist = 0xFFFFFFFF;
    for (int16_t ix = 0; ix < usedCapacity; ix++)
    {
        const int16_t xDist = indexToScreenX(ix) - x;
        const int16_t yDist = indexToScreenY(ix) - y;
        const uint32_t dist = xDist * xDist + yDist * yDist;
        if (dist < bestDist)
        {
            index = ix;
            bestDist = dist;
        }
    }
    return true;
}
References AbstractDataGraph::indexToScreenX(), AbstractDataGraph::indexToScreenY(), and AbstractDataGraph::usedCapacity.
getScaleX()
virtual int getScaleX () const inline virtual
Gets the scaling factor previously set using setScaleX().
Returns
The scaling factor.
See also
setScaleX, setScaleY, getScaleY
Reimplemented in DynamicDataGraph.
    {
        return xScale;
    }
References AbstractDataGraph::xScale.
Referenced by DynamicDataGraph::getScaleX(), and StaticDataGraph::setScaleX().
getScaleY()
virtual int getScaleY () const inline virtual
Gets the scaling factor previously set using setScaleY().
Returns
The scaling factor.
See also
setScaleY, setScaleX, getScaleX
Reimplemented in DynamicDataGraph.
    {
        return yScale;
    }
References AbstractDataGraph::yScale.
Referenced by DynamicDataGraph::getScaleY(), and StaticDataGraph::setScaleY().
getUsedCapacity()
FORCE_INLINE_FUNCTION int16_t getUsedCapacity () const inline
Gets the number of point used by the graph.
Returns
The number of point used by the graph.
    {
        return usedCapacity;
    }
References AbstractDataGraph::usedCapacity.
handleClickEvent()
void handleClickEvent (const ClickEvent & event) virtual
Defines the event handler interface for ClickEvents. The default implementation ignores the event. The event is only received if the Drawable is touchable and visible.
Parameters
event The ClickEvent received from the HAL.
Reimplemented from Drawable.
{
    if (event.getType() == ClickEvent::CANCEL)
    {
        return;
    }
    const int16_t x = event.getX() - graphArea.getX();
    int16_t index;
    if (getNearestIndexForScreenX(x, index))
    {
        if (event.getType() == ClickEvent::PRESSED || event.getType() == ClickEvent::RELEASED)
        {
            if (clickAction && clickAction->isValid())
            {
                const GraphClickEvent graphClickEvent(index, event);
                clickAction->execute(*this, graphClickEvent);
            }
        }
    }
}
References ClickEvent::CANCEL, AbstractDataGraph::clickAction, AbstractDataGraph::getNearestIndexForScreenX(), Drawable::getX(), AbstractDataGraph::graphArea, ClickEvent::PRESSED, and ClickEvent::RELEASED.
handleDragEvent()
void handleDragEvent (const DragEvent & event) virtual
Defines the event handler interface for DragEvents. The default implementation ignores the event. The event is only received if the drawable is touchable and visible.
Parameters
event The DragEvent received from the HAL.
Reimplemented from Drawable.
{
    const int16_t x = event.getNewX() - graphArea.getX();
    int16_t index;
    if (getNearestIndexForScreenX(x, index))
    {
        if (event.getType() == DragEvent::DRAGGED)
        {
            if (dragAction && dragAction->isValid())
            {
                const GraphDragEvent graphDragEvent(index, event);
                dragAction->execute(*this, graphDragEvent);
            }
        }
    }
}
References AbstractDataGraph::dragAction, DragEvent::DRAGGED, AbstractDataGraph::getNearestIndexForScreenX(), Drawable::getX(), and AbstractDataGraph::graphArea.
indexToDataPoint() [1/2]
FORCE_INLINE_FUNCTION void indexToDataPoint (int16_t index, float & xvalue, float & yvalue) const inline
Gets data point as floating point values.
Parameters
index Zero-based index of the values to fetch.
[out] xvalue The x value.
[out] yvalue The y value.
See also
indexToDataPointXAsFloat, indexToDataPointYAsFloat, indexToDataPointScaled
    {
        xvalue = indexToDataPointXAsFloat(index);
        yvalue = indexToDataPointYAsFloat(index);
    }
References AbstractDataGraph::indexToDataPointXAsFloat(), and AbstractDataGraph::indexToDataPointYAsFloat().
indexToDataPoint() [2/2]
FORCE_INLINE_FUNCTION void indexToDataPoint (int16_t index, int & xvalue, int & yvalue) const inline
Gets data point as integer values.
Parameters
index Zero-based index of the values to fetch.
[out] xvalue The x value.
[out] yvalue The y value.
See also
indexToDataPointXAsInt, indexToDataPointYAsInt, indexToDataPointScaled
    {
        xvalue = indexToDataPointXAsInt(index);
        yvalue = indexToDataPointYAsInt(index);
    }
References AbstractDataGraph::indexToDataPointXAsInt(), and AbstractDataGraph::indexToDataPointYAsInt().
indexToDataPointScaled()
FORCE_INLINE_FUNCTION void indexToDataPointScaled (int16_t index, int & xvalue, int & yvalue) const inline
Gets data point as raw (scaled) values.
Parameters
index Zero-based index of the values to fetch.
[out] xvalue The x value.
[out] yvalue The y value.
    {
        xvalue = indexToDataPointXScaled(index);
        yvalue = indexToDataPointYScaled(index);
    }
References AbstractDataGraph::indexToDataPointXScaled(), and AbstractDataGraph::indexToDataPointYScaled().
indexToDataPointXAsFloat()
FORCE_INLINE_FUNCTION float indexToDataPointXAsFloat (int16_t index) const inline
Gets data point x coordinate as float.
Parameters
index Zero-based index of the value to fetch.
Returns
The data point x coordinate as float.
See also
indexToDataPointXAsInt, indexToDataPointXScaled, indexToDataPointYAsFloat, indexToDataPoint
    {
        return scaled2floatX(indexToDataPointXScaled(index));
    }
References AbstractDataGraph::indexToDataPointXScaled(), and AbstractDataGraph::scaled2floatX().
Referenced by AbstractDataGraph::indexToDataPoint().
indexToDataPointXAsInt()
FORCE_INLINE_FUNCTION int indexToDataPointXAsInt (int16_t index) const inline
Gets data point x coordinate as int.
Parameters
index Zero-based index of the value to fetch.
Returns
The data point x coordinate as int.
See also
indexToDataPointXAsFloat, indexToDataPointXScaled, indexToDataPointYAsInt, indexToDataPoint
    {
        return scaled2intX(indexToDataPointXScaled(index));
    }
References AbstractDataGraph::indexToDataPointXScaled(), and AbstractDataGraph::scaled2intX().
Referenced by AbstractDataGraph::indexToDataPoint().
indexToDataPointXScaled()
virtual int indexToDataPointXScaled (int16_t index) const pure virtual
Gets data point x coordinate scaled.
Parameters
index Zero-based index of the value to fetch.
Returns
The data point x coordinate scaled.
See also
indexToDataPointXAsInt, indexToDataPointXAsFloat, indexToDataPointYScaled, indexToDataPoint, indexToDataPointScaled
Implemented in DynamicDataGraph, and StaticDataGraph.
Referenced by AbstractDataGraph::indexToDataPointScaled(), AbstractDataGraph::indexToDataPointXAsFloat(), and AbstractDataGraph::indexToDataPointXAsInt().
indexToDataPointYAsFloat()
FORCE_INLINE_FUNCTION float indexToDataPointYAsFloat (int16_t index) const inline
Gets data point y coordinate as float.
Parameters
index Zero-based index of the value to fetch.
Returns
The data point y coordinate as float.
See also
indexToDataPointYAsInt, indexToDataPointYScaled, indexToDataPointXAsFloat, indexToDataPoint
    {
        return scaled2floatY(indexToDataPointYScaled(index));
    }
References AbstractDataGraph::indexToDataPointYScaled(), and AbstractDataGraph::scaled2floatY().
Referenced by AbstractDataGraph::indexToDataPoint().
indexToDataPointYAsInt()
FORCE_INLINE_FUNCTION int indexToDataPointYAsInt (int16_t index) const inline
Gets data point y coordinate as int.
Parameters
index Zero-based index of the value to fetch.
Returns
The data point y coordinate as int.
See also
indexToDataPointYAsFloat, indexToDataPointYScaled, indexToDataPointXAsInt, indexToDataPoint
    {
        return scaled2intY(indexToDataPointYScaled(index));
    }
References AbstractDataGraph::indexToDataPointYScaled(), and AbstractDataGraph::scaled2intY().
Referenced by AbstractDataGraph::indexToDataPoint().
indexToDataPointYScaled()
virtual int indexToDataPointYScaled (int16_t index) const pure virtual
Gets data point y coordinate scaled.
Parameters
index Zero-based index of the value to fetch.
Returns
The data point y coordinate scaled.
See also
indexToDataPointYAsInt, indexToDataPointYAsFloat, indexToDataPointXScaled, indexToDataPoint, indexToDataPointScaled
Implemented in DynamicDataGraph, and StaticDataGraph.
Referenced by AbstractDataGraph::indexToDataPointScaled(), AbstractDataGraph::indexToDataPointYAsFloat(), and AbstractDataGraph::indexToDataPointYAsInt().
indexToScreenX()
FORCE_INLINE_FUNCTION int16_t indexToScreenX (int16_t index) const inline
Get the screen x coordinate for the given graph point index.
Parameters
index Zero-based index of the point.
Returns
The screen x value.
    {
        return indexToScreenXQ5(index).round();
    }
References AbstractDataGraph::indexToScreenXQ5().
Referenced by AbstractDataGraph::getNearestIndexForScreenX(), and AbstractDataGraph::getNearestIndexForScreenXY().
indexToScreenXQ5()
virtual CWRUtil::Q5 indexToScreenXQ5 (int16_t index) const protected pure virtual
Gets screen x coordinate for a specific data point added to the graph.
Parameters
index The index of the element to get the x coordinate for.
Returns
The screen x coordinate for the specific data point.
Implemented in DynamicDataGraph, and StaticDataGraph.
Referenced by AbstractDataGraph::indexToScreenX().
indexToScreenY()
FORCE_INLINE_FUNCTION int16_t indexToScreenY (int16_t index) const inline
Get the screen y coordinate for the given graph point index.
Parameters
index Zero-based index of the point.
Returns
The screen x value.
    {
        return indexToScreenYQ5(index).round();
    }
References AbstractDataGraph::indexToScreenYQ5().
Referenced by AbstractDataGraph::getNearestIndexForScreenXY().
indexToScreenYQ5()
virtual CWRUtil::Q5 indexToScreenYQ5 (int16_t index) const protected pure virtual
Gets screen y coordinate for a specific data point added to the graph.
Parameters
index The index of the element to get the y coordinate for.
Returns
The screen x coordinate for the specific data point.
Implemented in DynamicDataGraph, and StaticDataGraph.
Referenced by AbstractDataGraph::indexToScreenY().
indexToXAxis()
virtual int indexToXAxis (const int valueScaled, const int labelScaled) const protected pure virtual
Convert the given valueScaled (index) to x axis value.
Parameters
valueScaled The value scaled.
labelScaled The label scaled.
Returns
The x axis value.
Implemented in DynamicDataGraph, and StaticDataGraph.
int2scaled()
static FORCE_INLINE_FUNCTION int int2scaled (int i, int scale) inline static
Multiply an integer value with a constant.
Parameters
i the value to scale.
scale The scale.
Returns
The product of the two numbers.
    {
        return i * scale;
    }
Referenced by AbstractDataGraph::int2scaledX(), AbstractDataGraph::int2scaledY(), and GraphLabelsBase::setInterval().
int2scaledX()
FORCE_INLINE_FUNCTION int int2scaledX (int i) const inline
Same as int2scaled(int, int) using the graph's x scale.
Parameters
i The integer value to scale.
Returns
The scaled integer.
Note
For internal use.
    {
        return int2scaled(i, xScale);
    }
References AbstractDataGraph::int2scaled(), and AbstractDataGraph::xScale.
Referenced by StaticDataGraph::addDataPoint(), StaticDataGraph::deleteDataPoint(), DynamicDataGraph::indexToScreenXQ5(), AbstractDataGraph::setGraphRangeX(), AbstractDataGraph::setGraphRangeXAuto(), DynamicDataGraph::setXAxisFactor(), and DynamicDataGraph::setXAxisOffset().
int2scaledY()
FORCE_INLINE_FUNCTION int int2scaledY (int i) const inline
Same as int2scaled(int, int) using the graph's y scale.
Parameters
i The integer value to scale.
Returns
The scaled integer.
Note
For internal use.
    {
        return int2scaled(i, yScale);
    }
References AbstractDataGraph::int2scaled(), and AbstractDataGraph::yScale.
Referenced by StaticDataGraph::addDataPoint(), DynamicDataGraph::addDataPoint(), AbstractDataGraph::setGraphRangeY(), and AbstractDataGraph::setGraphRangeYAuto().
invalidateAllXAxisPoints()
void invalidateAllXAxisPoints () protected
Invalidate all x axis points. Similar to invalidateXAxisPointAt, this function will iterate all visible x values and invalidate them in turn.
See also
invalidateXAxisPointAt
{
    for (int index = 0; index <= usedCapacity; index++)
    {
        invalidateXAxisPointAt(index);
    }
    topArea.invalidate();
    bottomArea.invalidate();
}
References AbstractDataGraph::bottomArea, Drawable::invalidate(), AbstractDataGraph::invalidateXAxisPointAt(), AbstractDataGraph::topArea, and AbstractDataGraph::usedCapacity.
Referenced by GraphScrollData::addValue(), GraphWrapAndClearData::addValue(), GraphScrollData::beforeAddValue(), and GraphWrapAndClearData::clear().
invalidateContent()
virtual void invalidateContent () const inline virtual
Invalidate content.
Reimplemented from Drawable.
    {
        if (alpha > 0)
        {
            Container::invalidateContent();
        }
    }
References Drawable::invalidateContent().
invalidateGraphArea()
FORCE_INLINE_FUNCTION void invalidateGraphArea () const inline protected
Invalidate entire graph area (the center of the graph). This is often useful when a graph is cleared or the X or Y range is changed.
    {
        graphArea.invalidate();
    }
References AbstractDataGraph::graphArea, and Drawable::invalidate().
Referenced by GraphScrollData::addValue(), and AbstractDataGraph::clear().
invalidateGraphPointAt()
void invalidateGraphPointAt (int16_t index) protected
Invalidate point at a given index. This will call the function invalidateGraphPointAt() on every element added to the graphArea which in turn is responsible for invalidating the part of the screen occupied by its element.
Parameters
index Zero-based index of the element to invalidate.
{
    if (index < usedCapacity)
    {
        AbstractGraphElement* d = (AbstractGraphElement*)graphArea.getFirstChild();
        while (d)
        {
            d->invalidateGraphPointAt(index);
            d = (AbstractGraphElement*)d->getNextSibling();
        }
    }
}
References Container::getFirstChild(), AbstractDataGraph::graphArea, and AbstractDataGraph::usedCapacity.
Referenced by GraphScrollData::addValue(), GraphWrapAndClearData::addValue(), GraphWrapAndOverwriteData::addValue(), GraphData::addValue(), GraphWrapAndOverwriteData::beforeAddValue(), and StaticDataGraph::deleteIndex().
invalidateXAxisPointAt()
void invalidateXAxisPointAt (int16_t index) protected
Invalidate x axis point at the given index. Since the y axis is often static, the x axis can change, and all labels need to be updated without redrawing the entire graph.
Parameters
index The x index to invalidate.
See also
invalidateAllXAxisPoints
{
    AbstractGraphElement* d = (AbstractGraphElement*)topArea.getFirstChild();
    while (d)
    {
        d->invalidateGraphPointAt(index);
        d = (AbstractGraphElement*)d->getNextSibling();
    }
    d = (AbstractGraphElement*)bottomArea.getFirstChild();
    while (d)
    {
        d->invalidateGraphPointAt(index);
        d = (AbstractGraphElement*)d->getNextSibling();
    }
}
References AbstractDataGraph::bottomArea, Container::getFirstChild(), and AbstractDataGraph::topArea.
Referenced by GraphWrapAndOverwriteData::addValue(), GraphWrapAndOverwriteData::beforeAddValue(), and AbstractDataGraph::invalidateAllXAxisPoints().
scaled2float()
static FORCE_INLINE_FUNCTION float scaled2float (int i, int scale) inline static
Divide a floating point number with a constant.
Parameters
i The number to divide.
scale The divisor (scale).
Returns
The number divided by the scale.
    {
        return (float)i / (float)scale;
    }
Referenced by GraphElementArea::getBaselineAsFloat(), GraphElementHistogram::getBaselineAsFloat(), GraphElementGridBase::getIntervalAsFloat(), GraphLabelsBase::getIntervalAsFloat(), AbstractDataGraph::scaled2floatX(), and AbstractDataGraph::scaled2floatY().
scaled2floatX()
FORCE_INLINE_FUNCTION float scaled2floatX (int i) const inline
Same as scaled2float(int, int) using the graph's x scale.
Parameters
i The scaled value to convert to a floating point value.
Returns
The unscaled value.
Note
For internal use.
    {
        return scaled2float(i, xScale);
    }
References AbstractDataGraph::scaled2float(), and AbstractDataGraph::xScale.
Referenced by AbstractDataGraph::getGraphRangeXMaxAsFloat(), AbstractDataGraph::getGraphRangeXMinAsFloat(), DynamicDataGraph::getXAxisFactorAsFloat(), DynamicDataGraph::getXAxisOffsetAsFloat(), and AbstractDataGraph::indexToDataPointXAsFloat().
scaled2floatY()
FORCE_INLINE_FUNCTION float scaled2floatY (int i) const inline
Same as scaled2float(int, int) using the graph's y scale.
Parameters
i The scaled value to convert to a floating point value.
Returns
The unscaled value.
Note
For internal use.
    {
        return scaled2float(i, yScale);
    }
References AbstractDataGraph::scaled2float(), and AbstractDataGraph::yScale.
Referenced by AbstractDataGraph::getGraphRangeYMaxAsFloat(), AbstractDataGraph::getGraphRangeYMinAsFloat(), and AbstractDataGraph::indexToDataPointYAsFloat().
scaled2int()
static FORCE_INLINE_FUNCTION int scaled2int (int i, int scale) inline static
Divide an integer with a constant and round the result.
Parameters
i The number to divide.
scale The divisor (scale).
Returns
The number divided by the scale, rounded to nearest integer.
    {
        if (i >= 0)
        {
            return ((i * 2 + scale) / scale) / 2;
        }
        return -(((-i * 2 + scale - 1) / scale) / 2);
    }
Referenced by GraphElementArea::getBaselineAsInt(), GraphElementHistogram::getBaselineAsInt(), GraphElementGridBase::getIntervalAsInt(), GraphLabelsBase::getIntervalAsInt(), AbstractDataGraph::scaled2intX(), and AbstractDataGraph::scaled2intY().
scaled2intX()
FORCE_INLINE_FUNCTION int scaled2intX (int i) const inline
Same as scaled2int(int, int) using the graph's x scale.
Parameters
i The scaled value to convert to an integer.
Returns
The unscaled value.
Note
For internal use.
    {
        return scaled2int(i, xScale);
    }
References AbstractDataGraph::scaled2int(), and AbstractDataGraph::xScale.
Referenced by AbstractDataGraph::getGraphRangeXMaxAsInt(), AbstractDataGraph::getGraphRangeXMinAsInt(), DynamicDataGraph::getXAxisFactorAsInt(), DynamicDataGraph::getXAxisOffsetAsInt(), AbstractDataGraph::indexToDataPointXAsInt(), DynamicDataGraph::indexToXAxis(), DynamicDataGraph::setGraphRangeXAutoScaled(), and DynamicDataGraph::xScreenRangeToIndexRange().
scaled2intY()
FORCE_INLINE_FUNCTION int scaled2intY (int i) const inline
Same as scaled2int(int, int) using the graph's y scale.
Parameters
i The scaled value to convert to an integer.
Returns
The unscaled value.
Note
For internal use.
    {
        return scaled2int(i, yScale);
    }
References AbstractDataGraph::scaled2int(), and AbstractDataGraph::yScale.
Referenced by AbstractDataGraph::getGraphRangeYMaxAsInt(), AbstractDataGraph::getGraphRangeYMinAsInt(), and AbstractDataGraph::indexToDataPointYAsInt().
setAlpha()
virtual void setAlpha (uint8_t newAlpha) inline virtual
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
All graph elements have to take this alpha into consideration.
    {
        alpha = newAlpha;
    }
setClickAction()
FORCE_INLINE_FUNCTION void setClickAction (GenericCallback< const AbstractDataGraph &, const GraphClickEvent & > & callback) inline
Sets an action to be executed when the graph is clicked.
Parameters
callback The callback.
See also
GraphClickEvent
    {
        clickAction = &callback;
    }
References AbstractDataGraph::clickAction.
setDragAction()
FORCE_INLINE_FUNCTION void setDragAction (GenericCallback< const AbstractDataGraph &, const GraphDragEvent & > & callback) inline
Sets an action to be executed when the graph is dragged.
Parameters
callback The callback.
See also
GraphDragEvent
    {
        dragAction = &callback;
    }
References AbstractDataGraph::dragAction.
setGapBeforeIndex()
FORCE_INLINE_FUNCTION void setGapBeforeIndex (int16_t index) inline
Makes gap before the specified index. This can be used to split a graph in two, but for some graph types, e.g. histograms, this has no effect. Only one gap can be specified at a time. Specifying a new gap automatically removes the previous gap.
Parameters
index Zero-based index where the gap should be placed.
    {
        gapBeforeIndex = index;
    }
References AbstractDataGraph::gapBeforeIndex.
Referenced by GraphWrapAndOverwriteData::addValue().
setGraphAreaMargin()
void setGraphAreaMargin (int16_t top, int16_t left, int16_t right, int16_t bottom)
Sets graph position inside the widget by reserving a margin around the graph. These areas to the left, the right, above and below are used for drawing optional axis and titles.
Parameters
top The top margin in pixels.
left The left margin in pixels.
right The right margin in pixels.
bottom The bottom margin in pixels.
See also
GraphLabelsX, GraphLabelsY, GraphTitle, getGraphAreaMarginTop, getGraphAreaMarginLeft, getGraphAreaMarginRight, getGraphAreaMarginBottom, setGraphAreaPadding
Note
The graph is automatically invalidated when the graph margins are changed.
{
    graphArea.setPosition(left, top, getWidth() - (left + right), getHeight() - (top + bottom));
    topArea.setPosition(0, 0, getWidth(), top);
    leftArea.setPosition(0, 0, left, getHeight());
    rightArea.setPosition(getWidth() - right, 0, right, getHeight());
    bottomArea.setPosition(0, getHeight() - bottom, getWidth(), bottom);
    updateAreasPosition();
}
References AbstractDataGraph::bottomArea, Drawable::getHeight(), Drawable::getWidth(), AbstractDataGraph::graphArea, AbstractDataGraph::leftArea, AbstractDataGraph::rightArea, Drawable::setPosition(), AbstractDataGraph::topArea, and AbstractDataGraph::updateAreasPosition().
Referenced by AbstractDataGraph::AbstractDataGraph().
setGraphAreaPadding()
void setGraphAreaPadding (int16_t top, int16_t left, int16_t right, int16_t bottom)
Adds padding around the graph that will not be drawn in (apart from dots, boxes, lines etc. that extend around the actual data point). The set padding will also work to make a gap between the graph and any labels that might have been added to the graph. To reserve an area that the graph will not be drawn in, use setGraphAreaMargin.
Parameters
top The top padding in pixels.
left The left padding in pixels.
right The right padding in pixels.
bottom The bottom padding in pixels.
See also
setGraphAreaMargin, getGraphAreaPaddingTop, getGraphAreaPaddingLeft, getGraphAreaPaddingRight, getGraphAreaPaddingBottom
Note
The graph is automatically invalidated when the margins are set.
{
    topPadding = top;
    leftPadding = left;
    rightPadding = right;
    bottomPadding = bottom;
}
References AbstractDataGraph::bottomPadding, AbstractDataGraph::leftPadding, AbstractDataGraph::rightPadding, and AbstractDataGraph::topPadding.
setGraphRange() [1/4]
FORCE_INLINE_FUNCTION void setGraphRange (float xMin, float xMax, float yMin, float yMax) inline
Sets minimum and maximum x and y coordinate ranges for the graph. This can be used to zoom in or out and only show parts of the graph. The range given is scaled.
Parameters
xMin The minimum x value.
xMax The maximum x value.
yMin The minimum y value.
yMax The maximum y value.
See also
setScaleX, setScaleY, setGraphRangeX, setGraphRangeY, setGraphRangeXAuto, setGraphRangeYAuto, setGraphRangeScaled
    {
        setGraphRangeX(xMin, xMax);
        setGraphRangeY(yMin, yMax);
    }
References AbstractDataGraph::setGraphRangeX(), and AbstractDataGraph::setGraphRangeY().
setGraphRange() [2/4]
FORCE_INLINE_FUNCTION void setGraphRange (float xMin, float xMax, int yMin, int yMax) inline
Sets minimum and maximum x and y coordinate ranges for the graph. This can be used to zoom in or out and only show parts of the graph. The range given is scaled.
Parameters
xMin The minimum x value.
xMax The maximum x value.
yMin The minimum y value.
yMax The maximum y value.
See also
setScaleX, setScaleY, setGraphRangeX, setGraphRangeY, setGraphRangeXAuto, setGraphRangeYAuto, setGraphRangeScaled
    {
        setGraphRangeX(xMin, xMax);
        setGraphRangeY(yMin, yMax);
    }
References AbstractDataGraph::setGraphRangeX(), and AbstractDataGraph::setGraphRangeY().
setGraphRange() [3/4]
FORCE_INLINE_FUNCTION void setGraphRange (int xMin, int xMax, float yMin, float yMax) inline
Sets minimum and maximum x and y coordinate ranges for the graph. This can be used to zoom in or out and only show parts of the graph. The range given is scaled.
Parameters
xMin The minimum x value.
xMax The maximum x value.
yMin The minimum y value.
yMax The maximum y value.
See also
setScaleX, setScaleY, setGraphRangeX, setGraphRangeY, setGraphRangeXAuto, setGraphRangeYAuto, setGraphRangeScaled
    {
        setGraphRangeX(xMin, xMax);
        setGraphRangeY(yMin, yMax);
    }
References AbstractDataGraph::setGraphRangeX(), and AbstractDataGraph::setGraphRangeY().
setGraphRange() [4/4]
FORCE_INLINE_FUNCTION void setGraphRange (int xMin, int xMax, int yMin, int yMax) inline
Sets minimum and maximum x and y coordinate ranges for the graph. This can be used to zoom in or out and only show parts of the graph. The range given is scaled.
Parameters
xMin The minimum x value.
xMax The maximum x value.
yMin The minimum y value.
yMax The maximum y value.
See also
setScaleX, setScaleY, setGraphRangeX, setGraphRangeY, setGraphRangeXAuto, setGraphRangeYAuto, setGraphRangeScaled
    {
        setGraphRangeX(xMin, xMax);
        setGraphRangeY(yMin, yMax);
    }
References AbstractDataGraph::setGraphRangeX(), and AbstractDataGraph::setGraphRangeY().
setGraphRangeScaled()
FORCE_INLINE_FUNCTION void setGraphRangeScaled (int xMin, int xMax, int yMin, int yMax) inline
Same as setGraphRange(int, int, int, int) except the passed arguments are assumed scaled. This means that if the scale is 1000, a value of 1 is interpreted as 0.001 (i.e. 1/1000).
Parameters
xMin The minimum x value.
xMax The maximum x value.
yMin The minimum y value.
yMax The maximum y value.
See also
setGraphRange
    {
        setGraphRangeXScaled(xMin, xMax);
        setGraphRangeYScaled(yMin, yMax);
    }
References AbstractDataGraph::setGraphRangeXScaled(), and AbstractDataGraph::setGraphRangeYScaled().
setGraphRangeX() [1/2]
virtual void setGraphRangeX (float min, float max) inline virtual
Sets minimum and maximum x coordinates for the graph. This can be used to zoom in or out and only show parts of the graph.
Parameters
min The minimum x value.
max The maximum x value.
Note
The graph as well as the area above and below are automatically redrawn (invalidated).
    {
        setGraphRangeXScaled(float2scaledX(min), float2scaledX(max));
    }
References AbstractDataGraph::float2scaledX(), and AbstractDataGraph::setGraphRangeXScaled().
setGraphRangeX() [2/2]
virtual void setGraphRangeX (int min, int max) inline virtual
Sets minimum and maximum x coordinates for the graph. This can be used to zoom in or out and only show parts of the graph.
Parameters
min The minimum x value.
max The maximum x value.
Note
The graph as well as the area above and below are automatically redrawn (invalidated).
    {
        setGraphRangeXScaled(int2scaledX(min), int2scaledX(max));
    }
References AbstractDataGraph::int2scaledX(), and AbstractDataGraph::setGraphRangeXScaled().
Referenced by DynamicDataGraph::DynamicDataGraph(), StaticDataGraph::StaticDataGraph(), AbstractDataGraph::setGraphRange(), AbstractDataGraph::setGraphRange(), AbstractDataGraph::setGraphRange(), and AbstractDataGraph::setGraphRange().
setGraphRangeXAuto() [1/2]
virtual void setGraphRangeXAuto (bool showYaxis, float margin) inline virtual
Automatically adjust min and max x coordinate to show entire graph. It is possible to ensure that the y axis (i.e. x=0) is included in the new range. If the graph range is changed as a consequence of calling this function, the graph is automatically redrawn (invalidated).
Parameters
showYaxis (Optional) True to ensure that the y axis is visible (default is true).
margin (Optional) The margin to add above/below the max/min x value (default is no margin).
See also
setGraphRangeXAuto, setGraphRangeXAutoScaled, setGraphRangeYAuto, setGraphRangeYAutoScaled
Note
This takes the currently visible y coordinate range into account.
If data in the graph is changed, added or deleted, the graph range is not automatically recalculated. Call this function again to achieve this functionality.
    {
        setGraphRangeXAutoScaled(showYaxis, float2scaledX(margin));
    }
References AbstractDataGraph::float2scaledX(), and AbstractDataGraph::setGraphRangeXAutoScaled().
setGraphRangeXAuto() [2/2]
virtual void setGraphRangeXAuto (bool showYaxis = true, int margin = 0) inline virtual
Automatically adjust min and max x coordinate to show entire graph. It is possible to ensure that the y axis (i.e. x=0) is included in the new range. If the graph range is changed as a consequence of calling this function, the graph is automatically redrawn (invalidated).
Parameters
showYaxis (Optional) True to ensure that the y axis is visible (default is true).
margin (Optional) The margin to add above/below the max/min x value (default is no margin).
See also
setGraphRangeXAuto, setGraphRangeXAutoScaled, setGraphRangeYAuto, setGraphRangeYAutoScaled
Note
This takes the currently visible y coordinate range into account.
If data in the graph is changed, added or deleted, the graph range is not automatically recalculated. Call this function again to achieve this functionality.
    {
        setGraphRangeXAutoScaled(showYaxis, int2scaledX(margin));
    }
References AbstractDataGraph::int2scaledX(), and AbstractDataGraph::setGraphRangeXAutoScaled().
setGraphRangeXAutoScaled()
virtual void setGraphRangeXAutoScaled (bool showYaxis, int margin) pure virtual
Automatically adjust min and max x coordinate to show entire graph. It is possible to ensure that the y axis (i.e. x=0) is included in the new range. If the graph range is changed as a consequence of calling this function, the graph is automatically redrawn (invalidated).
Parameters
showYaxis (Optional) True to ensure that the y axis is visible (default is true).
margin (Optional) The margin to add above/below the max/min x value (default is no margin).
See also
setGraphRangeXAuto, setGraphRangeXAutoScaled, setGraphRangeYAuto, setGraphRangeYAutoScaled
Note
This takes the currently visible y coordinate range into account.
If data in the graph is changed, added or deleted, the graph range is not automatically recalculated. Call this function again to achieve this functionality.
The arguments are assumed scaled. This means that if the scale is 1000, a value of 1 is interpreted as 0.001 (i.e. 1/1000).
Implemented in StaticDataGraph, and DynamicDataGraph.
Referenced by AbstractDataGraph::setGraphRangeXAuto(), and AbstractDataGraph::setGraphRangeXAuto().
setGraphRangeXScaled()
void setGraphRangeXScaled (int min, int max) virtual
Sets minimum and maximum x coordinates for the graph. This can be used to zoom in or out and only show parts of the graph.
Parameters
min The minimum x value.
max The maximum x value.
Note
The graph as well as the area above and below are automatically redrawn (invalidated).
See also
setGraphRangeX
Note
The arguments are assumed scaled. This means that if the scale is 1000, a value of 1 is interpreted as 0.001 (i.e. 1/1000).
{
    assert(min != max);
    if (max < min)
    {
        const int tmp = min;
        min = max;
        max = tmp;
    }
    if (min != graphRangeMinX || max != graphRangeMaxX)
    {
        graphRangeMinX = min;
        graphRangeMaxX = max;
        topArea.invalidate();
        graphArea.invalidate();
        bottomArea.invalidate();
    }
}
References AbstractDataGraph::bottomArea, AbstractDataGraph::graphArea, AbstractDataGraph::graphRangeMaxX, AbstractDataGraph::graphRangeMinX, Drawable::invalidate(), and AbstractDataGraph::topArea.
Referenced by AbstractDataGraph::setGraphRangeScaled(), AbstractDataGraph::setGraphRangeX(), AbstractDataGraph::setGraphRangeX(), StaticDataGraph::setGraphRangeXAutoScaled(), DynamicDataGraph::setGraphRangeXAutoScaled(), and DynamicDataGraph::setScaleX().
setGraphRangeY() [1/2]
virtual void setGraphRangeY (float min, float max) inline virtual
Sets minimum and maximum y coordinates for the graph. This can be used to zoom in or out and only show parts of the graph.
Parameters
min The minimum y value.
max The maximum y value.
Note
The graph as well as the area to the left and to the right of the graph are automatically redrawn (invalidated)
    {
        setGraphRangeYScaled(float2scaledY(min), float2scaledY(max));
    }
References AbstractDataGraph::float2scaledY(), and AbstractDataGraph::setGraphRangeYScaled().
setGraphRangeY() [2/2]
virtual void setGraphRangeY (int min, int max) inline virtual
Sets minimum and maximum y coordinates for the graph. This can be used to zoom in or out and only show parts of the graph.
Parameters
min The minimum y value.
max The maximum y value.
Note
The graph as well as the area to the left and to the right of the graph are automatically redrawn (invalidated)
    {
        setGraphRangeYScaled(int2scaledY(min), int2scaledY(max));
    }
References AbstractDataGraph::int2scaledY(), and AbstractDataGraph::setGraphRangeYScaled().
Referenced by AbstractDataGraph::setGraphRange(), AbstractDataGraph::setGraphRange(), AbstractDataGraph::setGraphRange(), and AbstractDataGraph::setGraphRange().
setGraphRangeYAuto() [1/2]
virtual void setGraphRangeYAuto (bool showXaxis, float margin) inline virtual
Automatic adjust min and max y coordinate to show entire graph. It is possible to ensure that the x axis (i.e. y=0) is included in the new range. If the graph range is changed, the graph is automatically redrawn (invalidated).
Parameters
showXaxis True to ensure that the x axis is visible (default is true).
margin The margin to add above/below the max/min y value (default is no margin).
Note
This takes the current visible x coordinate range into account.
    {
        setGraphRangeYAutoScaled(showXaxis, float2scaledY(margin));
    }
References AbstractDataGraph::float2scaledY(), and AbstractDataGraph::setGraphRangeYAutoScaled().
setGraphRangeYAuto() [2/2]
virtual void setGraphRangeYAuto (bool showXaxis = true, int margin = 0) inline virtual
Automatic adjust min and max y coordinate to show entire graph. It is possible to ensure that the x axis (i.e. y=0) is included in the new range. If the graph range is changed, the graph is automatically redrawn (invalidated).
Parameters
showXaxis True to ensure that the x axis is visible (default is true).
margin The margin to add above/below the max/min y value (default is no margin).
Note
This takes the current visible x coordinate range into account.
    {
        setGraphRangeYAutoScaled(showXaxis, int2scaledY(margin));
    }
References AbstractDataGraph::int2scaledY(), and AbstractDataGraph::setGraphRangeYAutoScaled().
setGraphRangeYAutoScaled()
virtual void setGraphRangeYAutoScaled (bool showXaxis, int margin) pure virtual
Automatic adjust min and max y coordinate to show entire graph. It is possible to ensure that the x axis (i.e. y=0) is included in the new range. If the graph range is changed, the graph is automatically redrawn (invalidated).
Parameters
showXaxis True to ensure that the x axis is visible (default is true).
margin The margin to add above/below the max/min y value (default is no margin).
Note
This takes the current visible x coordinate range into account.
Implemented in DynamicDataGraph, and StaticDataGraph.
Referenced by AbstractDataGraph::setGraphRangeYAuto(), and AbstractDataGraph::setGraphRangeYAuto().
setGraphRangeYScaled()
void setGraphRangeYScaled (int min, int max) virtual
Same as setGraphRangeY(int, int) except the passed arguments are assumed scaled.
Parameters
min The minimum y value.
max The maximum y value.
See also
setGraphRangeY
{
    assert(min != max);
    if (max < min)
    {
        const int tmp = min;
        min = max;
        max = tmp;
    }
    if (min != graphRangeMinY || max != graphRangeMaxY)
    {
        graphRangeMinY = min;
        graphRangeMaxY = max;
        leftArea.invalidate();
        graphArea.invalidate();
        rightArea.invalidate();
    }
}
References AbstractDataGraph::graphArea, AbstractDataGraph::graphRangeMaxY, AbstractDataGraph::graphRangeMinY, Drawable::invalidate(), AbstractDataGraph::leftArea, and AbstractDataGraph::rightArea.
Referenced by AbstractDataGraph::setGraphRangeScaled(), AbstractDataGraph::setGraphRangeY(), AbstractDataGraph::setGraphRangeY(), DynamicDataGraph::setGraphRangeYAutoScaled(), and StaticDataGraph::setGraphRangeYAutoScaled().
setHeight()
void setHeight (int16_t height) virtual
Sets the height of this drawable.
Parameters
height The new height.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Reimplemented from Drawable.
{
    leftArea.setHeight(height);
    rightArea.setHeight(height);
    bottomArea.setY(height - bottomArea.getHeight());
    graphArea.setHeight(height - (topArea.getHeight() + bottomArea.getHeight()));
    Container::setHeight(height);
    updateAreasPosition();
}
References AbstractDataGraph::bottomArea, Drawable::getHeight(), AbstractDataGraph::graphArea, AbstractDataGraph::leftArea, AbstractDataGraph::rightArea, Drawable::setHeight(), Drawable::setY(), AbstractDataGraph::topArea, and AbstractDataGraph::updateAreasPosition().
setScaleX()
virtual void setScaleX (int scale, bool updateData = false) inline virtual
Sets a scaling factor to be multiplied on each X value added. Since the graph only stores integer values internally, it is possible to set a scale to e.g. 1000 and make the graph work as if there are three digits of precision. The addDataPoint() will multiply the x argument with the scaling factor and store this value. Please note the addDataPointScaled, which allows adding a value that is assumed to have already been multiplied by the scaling factor. Other functions exist in a "scaled" version where the arguments are assumed to already be scaled.
By setting the scale to 1 it is possible to simply use integer values for the graph.
Parameters
scale The scaling factor.
updateData (Optional) True to update all existing x value.
See also
getScaleX, setScaleY, getScaleY
Reimplemented in DynamicDataGraph, and StaticDataGraph.
    {
        (void)updateData; // Unused variable
        assert(scale != 0);
        xScale = scale;
    }
References void(), and AbstractDataGraph::xScale.
Referenced by DynamicDataGraph::setScaleX(), and StaticDataGraph::setScaleX().
setScaleY()
virtual void setScaleY (int scale, bool updateData = false) inline virtual
Sets a scaling factor to be multiplied on each Y value added. Since the graph only stores integer values internally, it is possible to set a scale to e.g. 1000 and make the graph work as if there are three digits of precision. The addDataPoint() will multiply the y argument with the scaling factor and store this value. Please note the addDataPointScaled, which allows adding a value that is assumed to have already been multiplied by the scaling factor. Other functions exist in a "scaled" version where the arguments are assumed to already be scaled.
By setting the scale to 1 it is possible to simply use integer values for the graph.
Parameters
scale The scaling factor.
updateData (Optional) True to update all existing y value.
See also
getScaleY, setScaleX, getScaleX
Reimplemented in DynamicDataGraph, and StaticDataGraph.
    {
        (void)updateData; // Unused variable
        assert(scale != 0);
        yScale = scale;
    }
References void(), and AbstractDataGraph::yScale.
Referenced by DynamicDataGraph::setScaleY(), and StaticDataGraph::setScaleY().
setWidth()
void setWidth (int16_t width) virtual
Sets the width of this drawable.
Parameters
width The new width.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Reimplemented from Drawable.
{
    topArea.setWidth(width);
    bottomArea.setWidth(width);
    rightArea.setX(width - rightArea.getWidth());
    graphArea.setWidth(width - (leftArea.getWidth() + rightArea.getWidth()));
    Container::setWidth(width);
    updateAreasPosition();
}
References AbstractDataGraph::bottomArea, Drawable::getWidth(), AbstractDataGraph::graphArea, AbstractDataGraph::leftArea, AbstractDataGraph::rightArea, Drawable::setWidth(), Drawable::setX(), AbstractDataGraph::topArea, and AbstractDataGraph::updateAreasPosition().
updateAreasPosition()
void updateAreasPosition () protected
Updates the position of all elements in all area after a change in size of the graph area and/or label padding.
Note
The entire graph area is invalidated.
{
    Drawable* d = graphArea.getFirstChild();
    while (d)
    {
        d->setPosition(0, 0, graphArea.getWidth(), graphArea.getHeight());
        d = d->getNextSibling();
    }
    d = topArea.getFirstChild();
    while (d)
    {
        d->setPosition(0, 0, topArea.getWidth(), topArea.getHeight());
        d = d->getNextSibling();
    }
    d = leftArea.getFirstChild();
    while (d)
    {
        d->setPosition(0, 0, leftArea.getWidth(), leftArea.getHeight());
        d = d->getNextSibling();
    }
    d = rightArea.getFirstChild();
    while (d)
    {
        d->setPosition(0, 0, rightArea.getWidth(), rightArea.getHeight());
        d = d->getNextSibling();
    }
    d = bottomArea.getFirstChild();
    while (d)
    {
        d->setPosition(0, 0, bottomArea.getWidth(), bottomArea.getHeight());
        d = d->getNextSibling();
    }
    invalidate();
}
References AbstractDataGraph::bottomArea, Container::getFirstChild(), Drawable::getHeight(), Drawable::getWidth(), AbstractDataGraph::graphArea, Drawable::invalidate(), AbstractDataGraph::leftArea, AbstractDataGraph::rightArea, and AbstractDataGraph::topArea.
Referenced by AbstractDataGraph::setGraphAreaMargin(), AbstractDataGraph::setHeight(), and AbstractDataGraph::setWidth().
valueToScreenXQ5()
virtual CWRUtil::Q5 valueToScreenXQ5 (int x) const inline protected virtual
Gets screen x coordinate for an absolute value.
Parameters
x The x value.
Returns
The screen x coordinate for the given value.
    {
        return CWRUtil::muldiv_toQ5(x - graphRangeMinX, getGraphAreaWidth() - 1, graphRangeMaxX - graphRangeMinX) + CWRUtil::toQ5(leftPadding);
    }
References AbstractDataGraph::getGraphAreaWidth(), AbstractDataGraph::graphRangeMaxX, AbstractDataGraph::graphRangeMinX, AbstractDataGraph::leftPadding, CWRUtil::muldiv_toQ5(), and CWRUtil::toQ5().
Referenced by DynamicDataGraph::indexToScreenXQ5(), and StaticDataGraph::indexToScreenXQ5().
valueToScreenYQ5()
virtual CWRUtil::Q5 valueToScreenYQ5 (int y) const inline protected virtual
Gets screen y coordinate for an absolute value.
Parameters
y The y value.
Returns
The screen y coordinate for the given value.
    {
        const int16_t graphAreaHeight = getGraphAreaHeight();
        return CWRUtil::toQ5(graphAreaHeight + topPadding - 1) - CWRUtil::muldiv_toQ5(y - graphRangeMinY, graphAreaHeight - 1, graphRangeMaxY - graphRangeMinY);
    }
References AbstractDataGraph::getGraphAreaHeight(), AbstractDataGraph::graphRangeMaxY, AbstractDataGraph::graphRangeMinY, CWRUtil::muldiv_toQ5(), AbstractDataGraph::topPadding, and CWRUtil::toQ5().
Referenced by DynamicDataGraph::indexToScreenYQ5(), and StaticDataGraph::indexToScreenYQ5().
xScreenRangeToIndexRange()
virtual bool xScreenRangeToIndexRange (int16_t xMin, int16_t xMax, int16_t & indexMin, int16_t & indexMax) const protected pure virtual
Gets index range for screen x coordinate range taking the current graph range into account.
Parameters
xMin The low screen x coordinate.
xMax The high screen x coordinate.
[out] indexMin The low element index.
[out] indexMax The high element index.
Returns
True if the range from low index to high index is legal.
Note
For internal use.
Implemented in DynamicDataGraph, and StaticDataGraph.
Member Data Documentation
alpha
uint8_t alpha protected
The alpha of the entire graph.
Referenced by AbstractDataGraph::getAlpha().
bottomArea
Container bottomArea protected
The area below the graph.
Referenced by AbstractDataGraph::AbstractDataGraph(), AbstractDataGraph::addBottomElement(), AbstractDataGraph::getGraphAreaMarginBottom(), AbstractDataGraph::invalidateAllXAxisPoints(), AbstractDataGraph::invalidateXAxisPointAt(), AbstractDataGraph::setGraphAreaMargin(), AbstractDataGraph::setGraphRangeXScaled(), AbstractDataGraph::setHeight(), AbstractDataGraph::setWidth(), and AbstractDataGraph::updateAreasPosition().
bottomPadding
int16_t bottomPadding protected
The graph area bottom padding.
Referenced by AbstractDataGraph::getGraphAreaHeight(), AbstractDataGraph::getGraphAreaPaddingBottom(), and AbstractDataGraph::setGraphAreaPadding().
clickAction
GenericCallback<const AbstractDataGraph&, const GraphClickEvent&>* clickAction protected
The callback to be executed when this Graph is clicked.
Referenced by AbstractDataGraph::handleClickEvent(), and AbstractDataGraph::setClickAction().
dragAction
GenericCallback<const AbstractDataGraph&, const GraphDragEvent&>* dragAction protected
The callback to be executed when this Graph is dragged.
Referenced by AbstractDataGraph::handleDragEvent(), and AbstractDataGraph::setDragAction().
gapBeforeIndex
int16_t gapBeforeIndex protected
The graph is disconnected (there is a gap) before this element index.
Referenced by AbstractDataGraph::getGapBeforeIndex(), and AbstractDataGraph::setGapBeforeIndex().
graphArea
Container graphArea protected
The graph area (the center area)
Referenced by AbstractDataGraph::AbstractDataGraph(), AbstractDataGraph::addGraphElement(), AbstractDataGraph::getGraphAreaHeight(), AbstractDataGraph::getGraphAreaHeightIncludingPadding(), AbstractDataGraph::getGraphAreaWidth(), AbstractDataGraph::getGraphAreaWidthIncludingPadding(), AbstractDataGraph::handleClickEvent(), AbstractDataGraph::handleDragEvent(), AbstractDataGraph::invalidateGraphArea(), AbstractDataGraph::invalidateGraphPointAt(), AbstractDataGraph::setGraphAreaMargin(), AbstractDataGraph::setGraphRangeXScaled(), AbstractDataGraph::setGraphRangeYScaled(), AbstractDataGraph::setHeight(), AbstractDataGraph::setWidth(), and AbstractDataGraph::updateAreasPosition().
graphRangeMaxX
int graphRangeMaxX protected
The graph range maximum x coordinate.
Referenced by AbstractDataGraph::getGraphRangeXMaxAsFloat(), AbstractDataGraph::getGraphRangeXMaxAsInt(), AbstractDataGraph::getGraphRangeXMaxScaled(), AbstractDataGraph::setGraphRangeXScaled(), DynamicDataGraph::setScaleX(), AbstractDataGraph::valueToScreenXQ5(), DynamicDataGraph::xScreenRangeToIndexRange(), and StaticDataGraph::xScreenRangeToIndexRange().
graphRangeMaxY
int graphRangeMaxY protected
The graph range maximum y coordinate.
Referenced by AbstractDataGraph::getGraphRangeYMaxAsFloat(), AbstractDataGraph::getGraphRangeYMaxAsInt(), AbstractDataGraph::getGraphRangeYMaxScaled(), AbstractDataGraph::setGraphRangeYScaled(), and AbstractDataGraph::valueToScreenYQ5().
graphRangeMinX
int graphRangeMinX protected
The graph range minimum x coordinate.
Referenced by AbstractDataGraph::getGraphRangeXMinAsFloat(), AbstractDataGraph::getGraphRangeXMinAsInt(), AbstractDataGraph::getGraphRangeXMinScaled(), AbstractDataGraph::setGraphRangeXScaled(), DynamicDataGraph::setScaleX(), AbstractDataGraph::valueToScreenXQ5(), DynamicDataGraph::xScreenRangeToIndexRange(), and StaticDataGraph::xScreenRangeToIndexRange().
graphRangeMinY
int graphRangeMinY protected
The graph range minimum y coordinate.
Referenced by AbstractDataGraph::getGraphRangeYMinAsFloat(), AbstractDataGraph::getGraphRangeYMinAsInt(), AbstractDataGraph::getGraphRangeYMinScaled(), AbstractDataGraph::setGraphRangeYScaled(), and AbstractDataGraph::valueToScreenYQ5().
leftArea
Container leftArea protected
The area to the left of the graph.
Referenced by AbstractDataGraph::AbstractDataGraph(), AbstractDataGraph::addLeftElement(), AbstractDataGraph::getGraphAreaMarginLeft(), AbstractDataGraph::setGraphAreaMargin(), AbstractDataGraph::setGraphRangeYScaled(), AbstractDataGraph::setHeight(), AbstractDataGraph::setWidth(), and AbstractDataGraph::updateAreasPosition().
leftPadding
int16_t leftPadding protected
The graph area left padding.
Referenced by AbstractDataGraph::getGraphAreaPaddingLeft(), AbstractDataGraph::getGraphAreaWidth(), AbstractDataGraph::setGraphAreaPadding(), AbstractDataGraph::valueToScreenXQ5(), DynamicDataGraph::xScreenRangeToIndexRange(), and StaticDataGraph::xScreenRangeToIndexRange().
maxCapacity
int16_t maxCapacity protected
Maximum number of points in the graph.
Referenced by GraphScrollData::addValue(), GraphWrapAndOverwriteData::addValue(), GraphData::addValue(), GraphScrollData::beforeAddValue(), GraphWrapAndClearData::beforeAddValue(), GraphWrapAndOverwriteData::beforeAddValue(), GraphScrollData::dataIndex(), AbstractDataGraph::getMaxCapacity(), GraphScrollData::indexToGlobalIndex(), and GraphWrapAndOverwriteData::indexToGlobalIndex().
rightArea
Container rightArea protected
The area to the right of the graph.
Referenced by AbstractDataGraph::AbstractDataGraph(), AbstractDataGraph::addRightElement(), AbstractDataGraph::getGraphAreaMarginRight(), AbstractDataGraph::setGraphAreaMargin(), AbstractDataGraph::setGraphRangeYScaled(), AbstractDataGraph::setHeight(), AbstractDataGraph::setWidth(), and AbstractDataGraph::updateAreasPosition().
rightPadding
int16_t rightPadding protected
The graph area right padding.
Referenced by AbstractDataGraph::getGraphAreaPaddingRight(), AbstractDataGraph::getGraphAreaWidth(), and AbstractDataGraph::setGraphAreaPadding().
topArea
Container topArea protected
The area above the graph.
Referenced by AbstractDataGraph::AbstractDataGraph(), AbstractDataGraph::addTopElement(), AbstractDataGraph::getGraphAreaMarginTop(), AbstractDataGraph::invalidateAllXAxisPoints(), AbstractDataGraph::invalidateXAxisPointAt(), AbstractDataGraph::setGraphAreaMargin(), AbstractDataGraph::setGraphRangeXScaled(), AbstractDataGraph::setHeight(), AbstractDataGraph::setWidth(), and AbstractDataGraph::updateAreasPosition().
topPadding
int16_t topPadding protected
The graph area top padding.
Referenced by AbstractDataGraph::getGraphAreaHeight(), AbstractDataGraph::getGraphAreaPaddingTop(), AbstractDataGraph::setGraphAreaPadding(), and AbstractDataGraph::valueToScreenYQ5().
usedCapacity
int16_t usedCapacity protected
The number of used points in the graph.
Referenced by GraphScrollData::addValue(), GraphWrapAndClearData::addValue(), GraphWrapAndOverwriteData::addValue(), GraphData::addValue(), GraphScrollData::beforeAddValue(), GraphWrapAndClearData::beforeAddValue(), GraphWrapAndOverwriteData::beforeAddValue(), AbstractDataGraph::clear(), GraphScrollData::dataIndex(), StaticDataGraph::deleteIndex(), StaticDataGraph::deleteValue(), AbstractDataGraph::getNearestIndexForScreenX(), AbstractDataGraph::getNearestIndexForScreenXY(), AbstractDataGraph::getUsedCapacity(), DynamicDataGraph::indexToDataPointXScaled(), StaticDataGraph::indexToDataPointXScaled(), DynamicDataGraph::indexToDataPointYScaled(), StaticDataGraph::indexToDataPointYScaled(), GraphScrollData::indexToGlobalIndex(), GraphWrapAndClearData::indexToGlobalIndex(), AbstractDataGraph::invalidateAllXAxisPoints(), AbstractDataGraph::invalidateGraphPointAt(), StaticDataGraph::setGraphRangeXAutoScaled(), DynamicDataGraph::setGraphRangeXAutoScaled(), DynamicDataGraph::setGraphRangeYAutoScaled(), StaticDataGraph::setGraphRangeYAutoScaled(), StaticDataGraph::setScaleX(), DynamicDataGraph::setScaleY(), StaticDataGraph::setScaleY(), DynamicDataGraph::xScreenRangeToIndexRange(), and StaticDataGraph::xScreenRangeToIndexRange().
xScale
int xScale protected
The data scale for the x values.
Referenced by AbstractDataGraph::float2scaledX(), AbstractDataGraph::getScaleX(), AbstractDataGraph::int2scaledX(), AbstractDataGraph::scaled2floatX(), AbstractDataGraph::scaled2intX(), and AbstractDataGraph::setScaleX().
yScale
int yScale protected
The data scale for the y values.
Referenced by AbstractDataGraph::float2scaledY(), AbstractDataGraph::getScaleY(), AbstractDataGraph::int2scaledY(), AbstractDataGraph::scaled2floatY(), AbstractDataGraph::scaled2intY(), and AbstractDataGraph::setScaleY().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/graph/AbstractDataGraph.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph/AbstractDataGraph.cpp