Battery Simulator Documentation: PainterBGRA2222
PainterBGRA2222
#include "PainterBGRA2222.hpp"
Public Member Functions
PainterBGRA2222 (colortype color=0)
virtual void paint (uint8_t *destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const
virtual void setColor (colortype color)
Public Member Functions inherited from AbstractPainterBGRA2222
AbstractPainterBGRA2222 ()
FORCE_INLINE_FUNCTION uint8_t alphaBlend (uint8_t newpix, uint8_t bufpix, uint8_t alpha) const
FORCE_INLINE_FUNCTION uint8_t alphaBlend (uint8_t R, uint8_t G, uint8_t B, uint8_t bufpix, uint8_t alpha) const
Public Member Functions inherited from AbstractPainter
AbstractPainter ()
virtual ~AbstractPainter ()
void framebufferToDisplay (int16_t &widgetX, int16_t &widgetY) const
virtual HAL::RenderingMethod getRenderingMethod () const
virtual bool setup (const Rect &widgetRect) const
virtual void tearDown () const
Public Member Functions inherited from AbstractPainterColor
AbstractPainterColor (colortype color=0)
virtual ~AbstractPainterColor ()
colortype getColor () const
Protected Attributes
uint8_t color8
Pre-calculated native color.
uint8_t painterBlue
The blue part of the color, used when alpha blending.
uint8_t painterGreen
The green part of the color, used when alpha blending.
uint8_t painterRed
The red part of the color, used when alpha blending.
Protected Attributes inherited from AbstractPainter
int16_t widgetWidth
The width of the widget on screen, used by framebufferToDisplay()
Protected Attributes inherited from AbstractPainterColor
colortype painterColor
The color.
Additional Inherited Members
Static Protected Member Functions inherited from AbstractPainter
static FORCE_INLINE_FUNCTION bool compatibleFramebuffer (Bitmap::BitmapFormat format)
Detailed Description
The PainterBGRA2222 class allows a shape to be filled with a given color value. This allows anti-aliased elements to be drawn.
See also
AbstractPainter
Constructor & Destructor Documentation
PainterBGRA2222()
PainterBGRA2222 (colortype color = 0) inline
Initializes a new instance of the PainterBGRA2222 class.
Parameters
color (Optional) the color, default is black.
        : AbstractPainterBGRA2222(), AbstractPainterColor(color)
    {
    }
Member Function Documentation
paint()
void paint (uint8_t * destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const virtual
Paints a streak of pixels (all with the same alpha) in the framebuffer. The first pixel to paint is at 'offset' relative to 'destination' (to be able to support 1bpp, 2bpp and 4bpp). The first pixel to paint is at the given 'widgetX', 'widgetY' coordinate. The number of pixels to paint is 'count' and the alpha to apply is 'alpha'.
Note that the widgetX, widgetY is relative to the widget in the framebuffer, not the display. To convert the coordinate to display widget coordinates, use framebufferToDisplay().
Parameters
[in] destination If non-null, the pointer.
offset The offset to add to the destination.
widgetX The widget x coordinate.
widgetY The widget y coordinate.
count Number of pixels.
alpha The alpha of the pixels.
See also
AbstractPainter::setup, AbstractPainter::tearDown, AbstractPainter::framebufferToDisplay
Implements AbstractPainter.
{
    uint8_t* RESTRICT framebuffer = destination + offset;
    const uint8_t* const lineEnd = framebuffer + count;
    if (alpha == 0xFF)
    {
        do
        {
            *framebuffer = color8;
        } while (++framebuffer < lineEnd);
    }
    else
    {
        do
        {
            *framebuffer = alphaBlend(painterRed, painterGreen, painterBlue, *framebuffer, alpha);
        } while (++framebuffer < lineEnd);
    }
}
References AbstractPainterBGRA2222::alphaBlend(), PainterBGRA2222::color8, PainterBGRA2222::painterBlue, PainterBGRA2222::painterGreen, PainterBGRA2222::painterRed, and RESTRICT.
setColor()
virtual void setColor (colortype color) inline virtual
Sets color to use when drawing the CanvasWidget.
Parameters
color The color.
Reimplemented from AbstractPainterColor.
    {
        AbstractPainterColor::setColor(color);
        painterRed = Color::getRed(color);
        painterGreen = Color::getGreen(color);
        painterBlue = Color::getBlue(color);
        color8 = LCD8bpp_BGRA2222::getNativeColor(painterColor);
    }
References PainterBGRA2222::color8, Color::getBlue(), Color::getGreen(), LCD8bpp_BGRA2222::getNativeColor(), Color::getRed(), PainterBGRA2222::painterBlue, AbstractPainterColor::painterColor, PainterBGRA2222::painterGreen, PainterBGRA2222::painterRed, and AbstractPainterColor::setColor().
Member Data Documentation
color8
uint8_t color8 protected
Pre-calculated native color.
Referenced by PainterBGRA2222::paint(), and PainterBGRA2222::setColor().
painterBlue
uint8_t painterBlue protected
The blue part of the color, used when alpha blending.
Referenced by PainterBGRA2222::paint(), and PainterBGRA2222::setColor().
painterGreen
uint8_t painterGreen protected
The green part of the color, used when alpha blending.
Referenced by PainterBGRA2222::paint(), and PainterBGRA2222::setColor().
painterRed
uint8_t painterRed protected
The red part of the color, used when alpha blending.
Referenced by PainterBGRA2222::paint(), and PainterBGRA2222::setColor().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/PainterBGRA2222.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/PainterBGRA2222.cpp