Battery Simulator Documentation: TiledImage
TiledImage
#include "TiledImage.hpp"
Public Member Functions
TiledImage (const Bitmap &bmp=Bitmap())
virtual void draw (const Rect &invalidatedArea) const
virtual void getOffset (int16_t &x, int16_t &y)
virtual Rect getSolidRect () const
virtual int16_t getXOffset ()
virtual int16_t getYOffset ()
virtual void setBitmap (const Bitmap &bmp)
virtual void setOffset (int16_t x, int16_t y)
virtual void setXOffset (int16_t x)
virtual void setYOffset (int16_t y)
Public Member Functions inherited from Image
Image (const Bitmap &bmp=Bitmap())
uint8_t getAlpha () const
Bitmap getBitmap () const
BitmapId getBitmapId () const
virtual void invalidateContent () const
void setAlpha (uint8_t newAlpha)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
int16_t xOffset
The X offset into the bitmap to start drawing in range 0..bitmap.width-1.
int16_t yOffset
The Y offset into the bitmap to start drawing in range 0..bitmap.height-1.
Protected Attributes inherited from Image
uint8_t alpha
The Alpha for this image.
Bitmap bitmap
The Bitmap to display.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
Simple widget capable of showing a bitmap tiled indefinitely horizontally and vertically. This means that when the TiledImage Widget is larger than the provided Bitmap, the Bitmap is repeated over and over horizontally and vertically. The bitmap can be alpha- blended with the background and have areas of transparency.
Constructor & Destructor Documentation
TiledImage()
TiledImage (const Bitmap & bmp = Bitmap()) inline
Constructs a new TiledImage with a default alpha value of 255 (solid) and a default Bitmap (undefined) if none is specified. If a Bitmap is passed to the constructor, the width and height of this widget is set to those of the bitmap.
Parameters
bmp (Optional) The bitmap to display.
See also
setBitmap
        : Image(bmp), xOffset(0), yOffset(0)
    {
    }
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Reimplemented from Image.
{
    const int16_t bitmapWidth = bitmap.getWidth();
    const int16_t bitmapHeight = bitmap.getHeight();
    if (bitmapWidth == 0 || bitmapHeight == 0)
    {
        return;
    }
    Rect meAbs;
    translateRectToAbsolute(meAbs);
    const int16_t minX = ((invalidatedArea.x + xOffset) / bitmapWidth) * bitmapWidth - xOffset;
    const int16_t maxX = (((invalidatedArea.right() + xOffset) - 1) / bitmapWidth) * bitmapWidth;
    const int16_t minY = ((invalidatedArea.y + yOffset) / bitmapHeight) * bitmapHeight - yOffset;
    const int16_t maxY = (((invalidatedArea.bottom() + yOffset) - 1) / bitmapHeight) * bitmapHeight;
    for (int16_t x = minX; x <= maxX; x += bitmapWidth)
    {
        for (int16_t y = minY; y <= maxY; y += bitmapHeight)
        {
            Rect dirty = Rect(x, y, bitmapWidth, bitmapHeight) & invalidatedArea;
            dirty.x -= x;
            dirty.y -= y;
            HAL::lcd().drawPartialBitmap(bitmap, meAbs.x + x, meAbs.y + y, dirty, alpha);
        }
    }
}
References touchgfx::dirty, HAL::lcd(), Drawable::translateRectToAbsolute(), TiledImage::xOffset, and TiledImage::yOffset.
getOffset()
void getOffset (int16_t & x, int16_t & y) virtual
Gets the offset into the bitmap where the tile drawing should start. Please note that the offsets set using setOffset have been normalized so that x is in the range 0 to bitmap width - 1, and y is in the range 0 to bitmap height - 1.
Parameters
[out] x The x offset.
[out] y The y offset.
See also
getXOffset, getYOffset
{
    x = getXOffset();
    y = getYOffset();
}
References TiledImage::getXOffset(), and TiledImage::getYOffset().
getSolidRect()
Rect getSolidRect () const virtual
Get (the largest possible) rectangle that is guaranteed to be solid (opaque). This information is important, as any Drawable underneath the solid area does not need to be drawn.
Returns
The solid rectangle part of the Drawable.
Note
The rectangle returned must be relative to upper left corner of the Drawable, meaning that a completely solid widget should return the full size Rect(0, 0, getWidth(), getHeight()). If no area can be guaranteed to be solid, an empty Rect must be returned. Failing to return the correct rectangle may result in errors on the display.
Reimplemented from Image.
{
    if (alpha < 255)
    {
        return Rect();
    }
    Rect solidRect = bitmap.getSolidRect();
    if (solidRect.width == bitmap.getWidth())
    {
        solidRect.width = getWidth();
    }
    else
    {
        solidRect.x -= xOffset;
        Rect solidRect2 = solidRect;
        solidRect2.x += bitmap.getWidth();
        if (solidRect.x < 0)
        {
            const int16_t right = solidRect.right();
            solidRect.width = MAX(right, 0);
            solidRect.x = 0;
        }
        if (solidRect2.right() > getWidth())
        {
            solidRect2.width = solidRect2.right() - getWidth();
        }
        if (solidRect2.width > solidRect.width)
        {
            solidRect = solidRect2;
        }
    }
    if (solidRect.height == bitmap.getHeight())
    {
        solidRect.height = getHeight();
    }
    else
    {
        solidRect.y -= yOffset;
        Rect solidRect2 = solidRect;
        solidRect2.y += bitmap.getHeight();
        if (solidRect.y < 0)
        {
            const int16_t bottom = solidRect.bottom();
            solidRect.height = MAX(bottom, 0);
            solidRect.y = 0;
        }
        if (solidRect2.bottom() > getHeight())
        {
            solidRect2.height = solidRect2.bottom() - getHeight();
        }
        if (solidRect2.height > solidRect.height)
        {
            solidRect = solidRect2;
        }
    }
    return solidRect;
}
References Drawable::getHeight(), Drawable::getWidth(), MAX, TiledImage::xOffset, and TiledImage::yOffset.
getXOffset()
int16_t getXOffset () virtual
Get x offset. This is the value set using setXOffset() (or setOffset()) normalized to be in the range 0 to bitmap width - 1.
Returns
The x offset.
See also
getYOffset, getOffset
{
    return xOffset;
}
References TiledImage::xOffset.
Referenced by TiledImage::getOffset().
getYOffset()
int16_t getYOffset () virtual
Get y coordinate offset. This is the value set using setYOffset() (or setOffset()) normalized to be in the range 0 to bitmap height - 1.
Returns
The y offset.
See also
getXOffset, getOffset
{
    return yOffset;
}
References TiledImage::yOffset.
Referenced by TiledImage::getOffset().
setBitmap()
void setBitmap (const Bitmap & bmp) virtual
Sets the bitmap for this Image and updates the width and height of this widget to match those of the Bitmap.
Parameters
bmp The bitmap instance.
Note
The user code must call invalidate() in order to update the image on the display.
Reimplemented from Image.
{
    Image::setBitmap(bmp);
    // Make sure the xOffset and yOffset are correct (in range)
    setOffset(xOffset, yOffset);
}
References Image::setBitmap(), TiledImage::setOffset(), TiledImage::xOffset, and TiledImage::yOffset.
Referenced by TiledImageButtonStyle< T >::handlePressedUpdated().
setOffset()
void setOffset (int16_t x, int16_t y) virtual
Sets an offset into the bitmap where the tile drawing should start. By default the first image is aligned along the top and left, i.e. offset at (0, 0).
Parameters
x The x coordinate offset.
y The y coordinate offset.
See also
setXOffset, setYOffset
{
    setXOffset(x);
    setYOffset(y);
}
References TiledImage::setXOffset(), and TiledImage::setYOffset().
Referenced by TiledImage::setBitmap(), and TiledImageButtonStyle< T >::setTileOffset().
setXOffset()
void setXOffset (int16_t x) virtual
Sets x offset into the bitmap where the tile drawing should start. Setting the x offset to 1 will push all images one pixel to the left.
Parameters
x The x offset.
See also
setYOffset, setOffset
{
    xOffset = x;
    if (bitmap.getWidth() != 0)
    {
        xOffset %= bitmap.getWidth();
        if (xOffset < 0)
        {
            xOffset += bitmap.getWidth();
        }
    }
}
References TiledImage::xOffset.
Referenced by TiledImage::setOffset().
setYOffset()
void setYOffset (int16_t y) virtual
Sets y offset into the bitmap where the tile drawing should start. Setting the y offset to 1 will push all images one pixel up.
Parameters
y The y offset.
See also
setXOffset, setOffset
{
    yOffset = y;
    if (bitmap.getHeight() != 0)
    {
        yOffset %= bitmap.getHeight();
        if (yOffset < 0)
        {
            yOffset += bitmap.getHeight();
        }
    }
}
References TiledImage::yOffset.
Referenced by TiledImage::setOffset().
Member Data Documentation
xOffset
int16_t xOffset protected
The X offset into the bitmap to start drawing in range 0..bitmap.width-1.
Referenced by TiledImage::draw(), TiledImage::getSolidRect(), TiledImage::getXOffset(), TiledImage::setBitmap(), and TiledImage::setXOffset().
yOffset
int16_t yOffset protected
The Y offset into the bitmap to start drawing in range 0..bitmap.height-1.
Referenced by TiledImage::draw(), TiledImage::getSolidRect(), TiledImage::getYOffset(), TiledImage::setBitmap(), and TiledImage::setYOffset().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/TiledImage.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/TiledImage.cpp