Battery Simulator Documentation: DrawableList
DrawableList
#include "DrawableList.hpp"
Public Member Functions
DrawableList ()
virtual bool getCircular () const
int16_t getDrawableIndex (int16_t itemIndex, int16_t prevDrawableIndex=-1) const
int16_t getDrawableIndices (int16_t itemIndex, int16_t *drawableIndexArray, int16_t arraySize) const
virtual int16_t getDrawableMargin () const
virtual int16_t getDrawableSize () const
virtual bool getHorizontal () const
int16_t getItemIndex (int16_t drawableIndex) const
virtual int16_t getItemSize () const
int16_t getNumberOfDrawables () const
int16_t getNumberOfItems () const
int32_t getOffset () const
int16_t getRequiredNumberOfDrawables () const
void itemChanged (int16_t itemIndex)
void refreshDrawables ()
virtual void setCircular (bool circular)
virtual void setDrawables (DrawableListItemsInterface &drawableListItems, int16_t drawableItemIndexOffset, GenericCallback< DrawableListItemsInterface *, int16_t, int16_t > &updateDrawableCallback)
void setDrawableSize (int16_t drawableSize, int16_t drawableMargin)
virtual void setHeight (int16_t height)
virtual void setHorizontal (bool horizontal)
void setNumberOfItems (int16_t numberOfItems)
void setOffset (int32_t ofs)
virtual void setWidth (int16_t width)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Private Attributes
DrawableListItemsInterface * drawableItems
The drawable items.
bool drawablesInitialized
True if all drawables initialized.
int16_t firstDrawable
The first visible drawable.
int16_t firstDrawableIndex
The offset when accessing DrawableListItems.
int16_t firstItem
The first visible item.
bool isCircular
True if list is circular, false if not.
bool isHorizontal
True if list is horizontal, false if not.
int16_t itemMargin
The margin around each item (included in itemSize)
int16_t itemSize
Size of each item (including margin)
int16_t numDrawables
Number of drawables.
int16_t numItems
Number of items.
int32_t offset
The offset of item 0.
GenericCallback< DrawableListItemsInterface *, int16_t, int16_t > * updateDrawable
The update drawable callback.
Additional Inherited Members
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A container able to display many items using only a few drawables. This is done by only having drawables for visible items, and populating these drawables with new content when each of these become visible.
This means that all drawables must have an identical structure in some way, for example an Image or a Container with a button and a text.
Constructor & Destructor Documentation
DrawableList()
DrawableList ()
    : Container(),
      isHorizontal(false),
      isCircular(false),
      offset(0),
      itemSize(0),
      itemMargin(0),
      numItems(0),
      numDrawables(0),
      firstItem(0),
      firstDrawable(0),
      drawablesInitialized(false),
      firstDrawableIndex(0),
      drawableItems(0),
      updateDrawable(0)
{
}
Member Function Documentation
getCircular()
bool getCircular () const virtual
Gets the circular setting, previously set using setCircular().
Returns
True if the list is circular (infinite), false if the list is not circular (finite).
See also
ScrollBase::getCircular, setCircular
{
    return isCircular;
}
References DrawableList::isCircular.
Referenced by ScrollBase::getCircular(), and ScrollList::getPositionForItem().
getDrawableIndex()
int16_t getDrawableIndex (int16_t itemIndex, int16_t prevDrawableIndex = -1) const
Gets the drawable index of an item. If the number of items is smaller than the number of drawables and the DrawableList is circular, the same item can be in more than one drawable. In that case, calling this function again with the previously returned index as second parameter, the index of the next drawable containing the item will be returned.
Parameters
itemIndex Index of the item.
prevDrawableIndex (Optional) Index of the previous drawable. If given, search starts after this index.
Returns
The first drawable index with the given item. Returns -1 if the item is not in a drawable.
See also
getDrawableIndices
{
    if (prevDrawableIndex < -1 || prevDrawableIndex >= numDrawables || numDrawables == 0 || numItems == 0)
    {
        return -1;
    }
    if (prevDrawableIndex >= 0)
    {
        prevDrawableIndex = ((prevDrawableIndex - firstDrawable) + numDrawables) % numDrawables;
    }
    for (int16_t i = prevDrawableIndex + 1; i < numDrawables; i++)
    {
        int16_t currentItemIndex = firstItem + i;
        if (isCircular)
        {
            currentItemIndex %= numItems;
        }
        if (itemIndex == currentItemIndex)
        {
            const int16_t drawableIndex = (firstDrawable + i) % numDrawables;
            return drawableIndex;
        }
    }
    return -1;
}
References DrawableList::firstDrawable, DrawableList::firstItem, DrawableList::isCircular, DrawableList::numDrawables, and DrawableList::numItems.
Referenced by DrawableList::getDrawableIndices(), and DrawableList::itemChanged().
getDrawableIndices()
int16_t getDrawableIndices (int16_t itemIndex, int16_t * drawableIndexArray, int16_t arraySize) const
Gets drawable indices. Useful when the number of items is smaller than the number of drawables as the same item might be in more than one drawable on the screen (if the DrawableList is circular). The passed array will be filled with the drawable indices and the number of indices found is returned.
Parameters
itemIndex Zero-based index of the item.
[out] drawableIndexArray Array where the drawable indices are stored.
arraySize Size of drawable array.
Returns
The number of drawable indices found.
See also
getItemIndex, setCircular, getDrawableIndex
{
    int16_t numFound = 0;
    int16_t drawableIndex = -1;
    while ((drawableIndex = getDrawableIndex(itemIndex, drawableIndex)) >= 0)
    {
        if (numFound < arraySize)
        {
            drawableIndexArray[numFound] = drawableIndex;
            numFound++;
        }
    }
    return numFound;
}
References DrawableList::getDrawableIndex().
getDrawableMargin()
int16_t getDrawableMargin () const virtual
Gets drawable margin.
Gets drawable margin as set by setDrawables.
Returns
The drawable margin.
{
    return itemMargin;
}
References DrawableList::itemMargin.
Referenced by ScrollBase::getDrawableMargin().
getDrawableSize()
int16_t getDrawableSize () const virtual
Gets drawable size as set by setDrawables.
Returns
The drawable size.
See also
setDrawables
{
    return itemSize - 2 * itemMargin;
}
References DrawableList::itemMargin, and DrawableList::itemSize.
Referenced by ScrollBase::getDrawableSize().
getHorizontal()
bool getHorizontal () const virtual
Gets the orientation of the drawables, previously set using setHorizontal().
Returns
True if it horizontal, false if it is vertical.
See also
ScrollBase::getHorizontal, setHorizontal
{
    return isHorizontal;
}
References DrawableList::isHorizontal.
Referenced by ScrollBase::getHorizontal().
getItemIndex()
int16_t getItemIndex (int16_t drawableIndex) const
Gets item stored in a given Drawable.
Parameters
drawableIndex Zero-based index of the drawable.
Returns
The item index.
{
    if (drawableIndex < 0 || drawableIndex >= numDrawables || numDrawables == 0 || numItems == 0)
    {
        return -1;
    }
    int16_t itemNumber = ((drawableIndex + numDrawables - firstDrawable) % numDrawables) + firstItem;
    if (isCircular)
    {
        itemNumber %= numItems;
    }
    if (itemNumber < 0 || itemNumber >= numItems)
    {
        return -1;
    }
    return itemNumber;
}
References DrawableList::firstDrawable, DrawableList::firstItem, DrawableList::isCircular, DrawableList::numDrawables, and DrawableList::numItems.
Referenced by ScrollList::getItem().
getItemSize()
int16_t getItemSize () const virtual
Gets size of each item. This equals the drawable size plus the drawable margin as set in setDrawables(). Equals getDrawableSize() + 2 * getDrawableMargin().
Returns
The item size.
See also
setDrawables, setDrawableSize, getDrawableMargin
Note
Not the same as getDrawableSize().
{
    return itemSize;
}
References DrawableList::itemSize.
getNumberOfDrawables()
int16_t getNumberOfDrawables () const
Gets number of drawables based on the size of each item and the size of the widget.
Returns
The number of drawables.
See also
setDrawables
{
    return numDrawables;
}
References DrawableList::numDrawables.
Referenced by ScrollWheelWithSelectionStyle::refreshDrawableListsLayout().
getNumberOfItems()
int16_t getNumberOfItems () const
Gets number of items in the DrawableList, as previously set using setNumberOfItems().
Returns
The number of items.
See also
setNumberOfItems
{
    return numItems;
}
References DrawableList::numItems.
Referenced by ScrollBase::getNumberOfItems(), and ScrollList::getPositionForItem().
getOffset()
int32_t getOffset () const
Gets offset, as previously set using setOffset().
Returns
The virtual offset.
See also
setOffset
{
    return offset;
}
References DrawableList::offset.
Referenced by ScrollBase::getOffset().
getRequiredNumberOfDrawables()
int16_t getRequiredNumberOfDrawables () const
Gets required number of drawables. After setting up the DrawableList it is possible to request how many drawables are needed to ensure that the list can always be drawn properly. If the DrawableList has been setup with fewer Drawables than the required number of drawables, part of the lower part of the DrawableList will look wrong.
The number of required drawables depend on the size of the widget and the size of the drawables and the margin around drawables. If there are fewer drawables than required, the widget will not display correctly. If there are more drawables than required, some will be left unused.
Returns
The required number of drawables.
See also
setDrawables
{
    if (drawableItems == 0 || itemSize <= 0)
    {
        return 0;
    }
    // Calculate number of required drawables. Worst case is one pixel visible of drawable at top and rest stacked tightly
    int16_t requiredDrawables = 1 + (((isHorizontal ? getWidth() : getHeight()) - 1) + (itemSize - 1)) / itemSize;
    if (!isCircular)
    {
        // We never require more drawables than the number of elements on non-circular list.
        if (requiredDrawables > numItems)
        {
            requiredDrawables = numItems;
        }
    }
    const int16_t numberOfDrawables = drawableItems->getNumberOfDrawables();
    return MIN((numberOfDrawables - firstDrawableIndex), requiredDrawables);
}
References DrawableList::drawableItems, DrawableList::firstDrawableIndex, Drawable::getHeight(), DrawableListItemsInterface::getNumberOfDrawables(), Drawable::getWidth(), DrawableList::isCircular, DrawableList::isHorizontal, DrawableList::itemSize, MIN, and DrawableList::numItems.
Referenced by DrawableList::refreshDrawables().
itemChanged()
void itemChanged (int16_t itemIndex)
Item changed.
Item changed and drawables containing this item must be updated. This function can be called when an item has changed and needs to be updated on screen. If the given item is displayed on screen, possible more than once for cyclic lists, each drawable is request to refresh its content to reflect the new value.
Parameters
itemIndex Zero-based index of the item.
{
    if (updateDrawable && updateDrawable->isValid())
    {
        int16_t drawableIndex = -1;
        while ((drawableIndex = getDrawableIndex(itemIndex, drawableIndex)) != -1)
        {
            updateDrawable->execute(drawableItems, drawableIndex + firstDrawableIndex, itemIndex);
        }
    }
}
References DrawableList::drawableItems, DrawableList::firstDrawableIndex, DrawableList::getDrawableIndex(), and DrawableList::updateDrawable.
Referenced by ScrollBase::itemChanged(), and ScrollWheelWithSelectionStyle::itemChanged().
refreshDrawables()
void refreshDrawables ()
Refresh drawables. Useful to call if the number or items, their size or other properties have changed.
{
    if (drawableItems == 0)
    {
        numDrawables = 0;
        return;
    }
    numDrawables = getRequiredNumberOfDrawables();
    // Remove everything
    Container::removeAll();
    // Add the itemDrawables
    const int16_t w = isHorizontal ? itemSize - 2 * itemMargin : getWidth();
    const int16_t h = isHorizontal ? getHeight() : itemSize - 2 * itemMargin;
    for (int drawableIndex = 0; drawableIndex < numDrawables; drawableIndex++)
    {
        Drawable* drawable = drawableItems->getDrawable(drawableIndex + firstDrawableIndex);
        // Resize the drawables, X/Y ignored for now.
        drawable->setPosition(0, 0, w, h);
        // Add each drawable for later positioning
        if (drawable->getParent() != 0)
        {
            // Remove drawable from the current parent
            static_cast<Container*>(drawable->getParent())->remove(*drawable);
        }
        Container::add(*drawable);
    }
    drawablesInitialized = false;
    firstItem = 0;
    firstDrawable = 0;
    setOffset(offset);
}
References Container::add(), DrawableList::drawableItems, DrawableList::drawablesInitialized, DrawableList::firstDrawable, DrawableList::firstDrawableIndex, DrawableList::firstItem, DrawableListItemsInterface::getDrawable(), Drawable::getHeight(), DrawableList::getRequiredNumberOfDrawables(), Drawable::getWidth(), DrawableList::isHorizontal, DrawableList::itemMargin, DrawableList::itemSize, DrawableList::numDrawables, Container::remove(), Container::removeAll(), and DrawableList::setOffset().
Referenced by ScrollBase::initialize(), ScrollWheelWithSelectionStyle::initialize(), DrawableList::setCircular(), DrawableList::setDrawables(), DrawableList::setHeight(), DrawableList::setHorizontal(), DrawableList::setNumberOfItems(), ScrollList::setPadding(), and DrawableList::setWidth().
setCircular()
void setCircular (bool circular) virtual
Sets whether the list is circular (infinite) or not. A circular list is a list where the first drawable re-appears after the last item in the list - and the last item in the list appears before the first item in the list.
Parameters
circular True if the list should be circular, false if the list should not be circular.
See also
ScrollBase::setCircular, getCircular
{
    if ((circular && !isCircular) || (!circular && isCircular))
    {
        isCircular = circular;
        refreshDrawables();
    }
}
References DrawableList::isCircular, and DrawableList::refreshDrawables().
Referenced by ScrollBase::ScrollBase(), ScrollBase::setCircular(), and ScrollWheelWithSelectionStyle::setCircular().
setDrawables()
void setDrawables (DrawableListItemsInterface & drawableListItems, int16_t drawableItemIndexOffset, GenericCallback< DrawableListItemsInterface *, int16_t, int16_t > & updateDrawableCallback) virtual
Sets the drawables parameters. These parameters are
The access class to the array of drawables
The offset in the drawableListItems array to start using drawable and
Callback to update the contents of a drawable.
Parameters
[in] drawableListItems Number of drawables allocated.
[in] drawableItemIndexOffset The offset of the drawable item.
[in] updateDrawableCallback A callback to update the contents of a drawable.
See also
getRequiredNumberOfDrawables
{
    drawableItems = &drawableListItems;
    firstDrawableIndex = drawableItemIndexOffset;
    updateDrawable = &updateDrawableCallback;
    refreshDrawables();
}
References DrawableList::drawableItems, DrawableList::firstDrawableIndex, DrawableList::refreshDrawables(), and DrawableList::updateDrawable.
Referenced by ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), ScrollList::setDrawables(), and ScrollWheel::setDrawables().
setDrawableSize()
void setDrawableSize (int16_t drawableSize, int16_t drawableMargin)
Sets drawables size. The drawable is is the size of each drawable in the list in the set direction of the list (this is enforced by the DrawableList class). The specified margin is added above and below each item for spacing. The entire size of an item is thus size + 2 * spacing.
For a horizontal list each element will be drawableSize high and have the same width as set using setWidth(). For a vertical list each element will be drawableSize wide and have the same height as set using setHeight().
Parameters
drawableSize The size of the drawable.
drawableMargin The margin around drawables (margin before and margin after).
See also
setWidth, setHeight, setHorizontal
{
    itemSize = drawableSize + 2 * drawableMargin;
    itemMargin = drawableMargin;
}
References DrawableList::itemMargin, and DrawableList::itemSize.
Referenced by ScrollBase::setDrawableSize(), and ScrollWheelWithSelectionStyle::setDrawableSize().
setHeight()
void setHeight (int16_t height) virtual
Sets the height of this drawable.
Parameters
height The new height.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
If the list is horizontal, the height is also propagated to all drawables in the list.
Reimplemented from Drawable.
{
    Container::setHeight(height);
    refreshDrawables();
}
References DrawableList::refreshDrawables(), and Drawable::setHeight().
Referenced by ScrollBase::setHeight().
setHorizontal()
void setHorizontal (bool horizontal) virtual
Sets a horizontal or vertical layout. If parameter horizontal is set true, all drawables are arranged side by side. If horizontal is set false, the drawables are arranged above and below each other (vertically).
Parameters
horizontal True to align drawables horizontal, false to align drawables vertically.
See also
ScrollBase::setHorizontal, getHorizontal
Note
Default value is false, i.e. vertical layout.
{
    if ((horizontal && !isHorizontal) || (!horizontal && isHorizontal))
    {
        isHorizontal = horizontal;
        refreshDrawables();
    }
}
References DrawableList::isHorizontal, and DrawableList::refreshDrawables().
Referenced by ScrollBase::ScrollBase(), ScrollBase::setHorizontal(), and ScrollWheelWithSelectionStyle::setHorizontal().
setNumberOfItems()
void setNumberOfItems (int16_t numberOfItems)
Sets number of items in the list. This forces all drawables to be updated to ensure that the content is correct.
Parameters
numberOfItems Number of items.
Note
The DrawableList is refreshed to reflect the change.
{
    numItems = numberOfItems;
    refreshDrawables();
}
References DrawableList::numItems, and DrawableList::refreshDrawables().
Referenced by ScrollBase::setNumberOfItems(), and ScrollWheelWithSelectionStyle::setNumberOfItems().
setOffset()
void setOffset (int32_t ofs)
Sets virtual coordinate. Does not move to the given coordinate, but places the drawables and fill correct content into the drawables to give the impression that everything has been scrolled to the given coordinate.
Setting a value of 0 means that item 0 is at the start of the DrawableList. Setting a value of "-getItemSize()" places item 0 outside the start of the DrawableList and item 1 at the start of it.
Items that are completely outside of view, will be updated with new content using the provided callback from setDrawables(). Care is taken to not fill drawables more than strictly required.
Parameters
ofs The virtual coordinate.
See also
getOffset, setDrawables
{
    offset = ofs;
    if (numDrawables == 0 || numItems == 0 || itemSize == 0)
    {
        return;
    }
    if (!updateDrawable || !updateDrawable->isValid())
    {
        return;
    }
    // ofs is the offset of item[0]
    // 0 => item[0] is perfectly selected, -itemSize => item[1] is perfectly selected, itemSize => item[N-1] is perfectly selected etc.
    int16_t newFirstItem = 0;
    if (ofs > 0)
    {
        const int numberOfItems = ofs / itemSize + 1;
        newFirstItem -= numberOfItems;
        ofs -= numberOfItems * itemSize;
    }
    if (ofs <= -itemSize)
    {
        const int numberOfItems = ofs / itemSize;
        newFirstItem -= numberOfItems;
        ofs -= numberOfItems * itemSize;
    }
    if (isCircular)
    {
        // Make sure that firstIndex is "in range"
        newFirstItem %= numItems;
        if (newFirstItem < 0)
        {
            newFirstItem += numItems;
        }
    }
    else
    {
        if (newFirstItem < 0)
        {
            ofs -= newFirstItem * itemSize;
            newFirstItem = 0;
        }
        else if (newFirstItem + numDrawables > numItems)
        {
            const int x = numItems - (newFirstItem + numDrawables);
            ofs += x * itemSize;
            newFirstItem += x;
        }
    }
    int drawableDelta = 0;
    if (drawablesInitialized && firstItem != newFirstItem)
    {
        drawableDelta = numDrawables;
        for (int i = 1; i < numDrawables; i++)
        {
            int fi = (firstItem + i);
            int nfi = (newFirstItem + i);
            if (isCircular)
            {
                fi %= numItems;
                nfi %= numItems;
            }
            if (fi == newFirstItem)
            {
                drawableDelta = -i;
                break;
            }
            if (nfi == firstItem)
            {
                drawableDelta = i;
                break;
            }
        }
    }
    firstDrawable = ((firstDrawable - drawableDelta) + numDrawables) % numDrawables;
    firstItem = newFirstItem;
    for (int i = 0; i < numDrawables; i++)
    {
        const int drawableIndex = (firstDrawable + i) % numDrawables;
        Drawable* drawable = drawableItems->getDrawable(drawableIndex + firstDrawableIndex);
        if (isHorizontal)
        {
            drawable->moveTo(ofs + i * itemSize + itemMargin, 0);
        }
        else
        {
            drawable->moveTo(0, ofs + i * itemSize + itemMargin);
        }
        int itemIndex = i + firstItem;
        if (isCircular)
        {
            itemIndex %= numItems;
        }
        else
        {
            if (itemIndex < 0 || itemIndex >= numItems)
            {
                itemIndex = -1;
            }
        }
        if (itemIndex < 0)
        {
            drawable->setVisible(false);
        }
        else
        {
            drawable->setVisible(true);
            // Only fill if first time or outside old range
            if (!drawablesInitialized || (i < drawableDelta || i >= numDrawables + drawableDelta))
            {
                if (updateDrawable->isValid())
                {
                    updateDrawable->execute(drawableItems, drawableIndex + firstDrawableIndex, itemIndex);
                    drawable->invalidateContent();
                }
            }
        }
    }
    drawablesInitialized = true;
}
References DrawableList::drawableItems, DrawableList::drawablesInitialized, DrawableList::firstDrawable, DrawableList::firstDrawableIndex, DrawableList::firstItem, DrawableListItemsInterface::getDrawable(), DrawableList::isCircular, DrawableList::isHorizontal, DrawableList::itemMargin, DrawableList::itemSize, DrawableList::numDrawables, DrawableList::numItems, and DrawableList::updateDrawable.
Referenced by DrawableList::refreshDrawables(), ScrollBase::setOffset(), and ScrollWheelWithSelectionStyle::setOffset().
setWidth()
void setWidth (int16_t width) virtual
Sets the width of this drawable.
Parameters
width The new width.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
If the list is vertical, the width is also propagated to all drawables in the list.
Reimplemented from Drawable.
{
    Container::setWidth(width);
    refreshDrawables();
}
References DrawableList::refreshDrawables(), and Drawable::setWidth().
Referenced by ScrollBase::setWidth().
Member Data Documentation
drawableItems
DrawableListItemsInterface* drawableItems private
The drawable items.
Referenced by DrawableList::getRequiredNumberOfDrawables(), DrawableList::itemChanged(), DrawableList::refreshDrawables(), DrawableList::setDrawables(), and DrawableList::setOffset().
drawablesInitialized
bool drawablesInitialized private
True if all drawables initialized.
Referenced by DrawableList::refreshDrawables(), and DrawableList::setOffset().
firstDrawable
int16_t firstDrawable private
The first visible drawable.
Referenced by DrawableList::getDrawableIndex(), DrawableList::getItemIndex(), DrawableList::refreshDrawables(), and DrawableList::setOffset().
firstDrawableIndex
int16_t firstDrawableIndex private
The offset when accessing DrawableListItems.
Referenced by DrawableList::getRequiredNumberOfDrawables(), DrawableList::itemChanged(), DrawableList::refreshDrawables(), DrawableList::setDrawables(), and DrawableList::setOffset().
firstItem
int16_t firstItem private
The first visible item.
Referenced by DrawableList::getDrawableIndex(), DrawableList::getItemIndex(), DrawableList::refreshDrawables(), and DrawableList::setOffset().
isCircular
bool isCircular private
True if list is circular, false if not.
Referenced by DrawableList::getCircular(), DrawableList::getDrawableIndex(), DrawableList::getItemIndex(), DrawableList::getRequiredNumberOfDrawables(), DrawableList::setCircular(), and DrawableList::setOffset().
isHorizontal
bool isHorizontal private
True if list is horizontal, false if not.
Referenced by DrawableList::getHorizontal(), DrawableList::getRequiredNumberOfDrawables(), DrawableList::refreshDrawables(), DrawableList::setHorizontal(), and DrawableList::setOffset().
itemMargin
int16_t itemMargin private
The margin around each item (included in itemSize)
Referenced by DrawableList::getDrawableMargin(), DrawableList::getDrawableSize(), DrawableList::refreshDrawables(), DrawableList::setDrawableSize(), and DrawableList::setOffset().
itemSize
int16_t itemSize private
Size of each item (including margin)
Referenced by DrawableList::getDrawableSize(), DrawableList::getItemSize(), DrawableList::getRequiredNumberOfDrawables(), DrawableList::refreshDrawables(), DrawableList::setDrawableSize(), and DrawableList::setOffset().
numDrawables
int16_t numDrawables private
Number of drawables.
Referenced by DrawableList::getDrawableIndex(), DrawableList::getItemIndex(), DrawableList::getNumberOfDrawables(), DrawableList::refreshDrawables(), and DrawableList::setOffset().
numItems
int16_t numItems private
Number of items.
Referenced by DrawableList::getDrawableIndex(), DrawableList::getItemIndex(), DrawableList::getNumberOfItems(), DrawableList::getRequiredNumberOfDrawables(), DrawableList::setNumberOfItems(), and DrawableList::setOffset().
offset
int32_t offset private
The offset of item 0.
Referenced by DrawableList::getOffset().
updateDrawable
GenericCallback<DrawableListItemsInterface*, int16_t, int16_t>* updateDrawable private
The update drawable callback.
Referenced by DrawableList::itemChanged(), DrawableList::setDrawables(), and DrawableList::setOffset().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/scrollers/DrawableList.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/scrollers/DrawableList.cpp