Battery Simulator Documentation: AdjustElements
AdjustElements
Public Member Functions
AdjustElements (Drawable *d=0, Direction dir=SOUTH)
void handleInsert (Drawable &d)
void handleRemove (Drawable &d)
Private Attributes
Direction direction
int16_t insertedCoord
Drawable * newElement
bool newElementPassed
Detailed Description
Constructor & Destructor Documentation
AdjustElements()
AdjustElements (Drawable * d = 0, Direction dir = SOUTH) inline
        : insertedCoord(0),
          newElementPassed(false),
          newElement(d),
          direction(dir)
    {
    }
Member Function Documentation
handleInsert()
void handleInsert (Drawable & d) inline
    {
        if (!newElementPassed)
        {
            if (newElement == &d)
            {
                newElementPassed = true;
            }
            else
            {
                if (direction == SOUTH)
                {
                    insertedCoord = d.getY() + d.getHeight();
                }
                else if (direction == EAST)
                {
                    insertedCoord = d.getX() + d.getWidth();
                }
            }
        }
        else
        {
            if (direction == SOUTH)
            {
                d.setY(d.getY() + newElement->getHeight());
            }
            else if (direction == EAST)
            {
                d.setX(d.getX() + newElement->getWidth());
            }
        }
    }
References AdjustElements::direction, touchgfx::EAST, Drawable::getHeight(), Drawable::getWidth(), AdjustElements::insertedCoord, AdjustElements::newElement, AdjustElements::newElementPassed, and touchgfx::SOUTH.
Referenced by ListLayout::insert().
handleRemove()
void handleRemove (Drawable & d) inline
    {
        if (!newElementPassed)
        {
            if (newElement == &d)
            {
                newElementPassed = true;
            }
        }
        else
        {
            if (direction == SOUTH)
            {
                d.setY(d.getY() - newElement->getHeight());
            }
            else if (direction == EAST)
            {
                d.setX(d.getX() - newElement->getWidth());
            }
        }
        if (newElement != &d)
        {
            if (direction == SOUTH)
            {
                if (d.getWidth() > insertedCoord)
                {
                    insertedCoord = d.getWidth();
                }
            }
            else if (direction == EAST)
            {
                if (d.getHeight() > insertedCoord)
                {
                    insertedCoord = d.getHeight();
                }
            }
        }
    }
References AdjustElements::direction, touchgfx::EAST, Drawable::getHeight(), Drawable::getWidth(), AdjustElements::insertedCoord, AdjustElements::newElement, AdjustElements::newElementPassed, and touchgfx::SOUTH.
Referenced by ListLayout::remove().
Member Data Documentation
direction
Direction direction private
Referenced by AdjustElements::handleInsert(), and AdjustElements::handleRemove().
insertedCoord
int16_t insertedCoord private
Referenced by AdjustElements::handleInsert(), and AdjustElements::handleRemove().
newElement
Drawable* newElement private
Referenced by AdjustElements::handleInsert(), and AdjustElements::handleRemove().
newElementPassed
bool newElementPassed private
Referenced by AdjustElements::handleInsert(), and AdjustElements::handleRemove().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/ListLayout.cpp