Battery Simulator Documentation: ImageButtonStyle< T >
ImageButtonStyle< T >
#include "ImageButtonStyle.hpp"
Public Member Functions
ImageButtonStyle ()
Bitmap getCurrentlyDisplayedBitmap () const
virtual void setBitmaps (const Bitmap &bmpReleased, const Bitmap &bmpPressed)
void setBitmapXY (uint16_t x, uint16_t y)
Protected Member Functions
virtual void handleAlphaUpdated ()
virtual void handlePressedUpdated ()
Protected Attributes
Image buttonImage
The button image.
Bitmap down
The image to display when button is pressed.
Bitmap up
The image to display when button is released.
Detailed Description
template<class T>
class touchgfx::ImageButtonStyle< T >
An image button style. This class is supposed to be used with one of the ButtonTrigger classes to create a functional button. This class will show one of two images depending on the state of the button (pressed or released).
The ImageButtonStyle will set the size of the enclosing container (normally AbstractButtonContainer) to the size of the pressed Bitmap. This can be overridden by calling setWidth/setHeight after setting the bitmaps.
The position of the bitmap can be adjusted with setBitmapXY (default is upper left corner).
Template Parameters
T Generic type parameter. Typically a AbstractButtonContainer subclass.
See also
AbstractButtonContainer
Constructor & Destructor Documentation
ImageButtonStyle()
template<class T > ImageButtonStyle () inline
        : T(), up(), down()
    {
        buttonImage.setXY(0, 0);
        T::add(buttonImage);
    }
References ImageButtonStyle< T >::buttonImage, and Drawable::setXY().
Member Function Documentation
getCurrentlyDisplayedBitmap()
template<class T > Bitmap getCurrentlyDisplayedBitmap () const inline
Gets currently displayed bitmap.
Returns
The currently displayed bitmap.
    {
        return (AbstractButtonContainer::pressed ? down : up);
    }
References ImageButtonStyle< T >::down, AbstractButtonContainer::pressed, and ImageButtonStyle< T >::up.
handleAlphaUpdated()
template<class T > virtual void handleAlphaUpdated () inline protected virtual
Handles what should happen when the alpha is updated.
    {
        buttonImage.setAlpha(T::getAlpha());
        T::handleAlphaUpdated();
    }
References ImageButtonStyle< T >::buttonImage, and Image::setAlpha().
handlePressedUpdated()
template<class T > virtual void handlePressedUpdated () inline protected virtual
Handles what should happen when the pressed state is updated.
    {
        buttonImage.setBitmap(T::getPressed() ? down : up);
        T::handlePressedUpdated();
    }
References ImageButtonStyle< T >::buttonImage, ImageButtonStyle< T >::down, Image::setBitmap(), and ImageButtonStyle< T >::up.
Referenced by ImageButtonStyle< T >::setBitmaps().
setBitmaps()
template<class T > virtual void setBitmaps (const Bitmap & bmpReleased, const Bitmap & bmpPressed) inline virtual
Sets the bitmaps.
Parameters
bmpReleased The bitmap released.
bmpPressed The bitmap pressed.
    {
        up = bmpReleased;
        down = bmpPressed;
        ImageButtonStyle::setWidthHeight(down);
        handlePressedUpdated();
    }
References ImageButtonStyle< T >::down, ImageButtonStyle< T >::handlePressedUpdated(), and ImageButtonStyle< T >::up.
setBitmapXY()
template<class T > void setBitmapXY (uint16_t x, uint16_t y) inline
Sets bitmap x and y.
Parameters
x An uint16_t to process.
y An uint16_t to process.
    {
        buttonImage.setXY(x, y);
    }
References ImageButtonStyle< T >::buttonImage, and Drawable::setXY().
Member Data Documentation
buttonImage
template<class T > Image buttonImage protected
The button image.
Referenced by ImageButtonStyle< T >::ImageButtonStyle(), ImageButtonStyle< T >::handleAlphaUpdated(), ImageButtonStyle< T >::handlePressedUpdated(), and ImageButtonStyle< T >::setBitmapXY().
down
template<class T > Bitmap down protected
The image to display when button is pressed.
Referenced by ImageButtonStyle< T >::getCurrentlyDisplayedBitmap(), ImageButtonStyle< T >::handlePressedUpdated(), and ImageButtonStyle< T >::setBitmaps().
up
template<class T > Bitmap up protected
The image to display when button is released.
Referenced by ImageButtonStyle< T >::getCurrentlyDisplayedBitmap(), ImageButtonStyle< T >::handlePressedUpdated(), and ImageButtonStyle< T >::setBitmaps().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/buttons/ImageButtonStyle.hpp