Battery Simulator Documentation: DisplayTransformation
DisplayTransformation
#include "DisplayTransformation.hpp"
Static Public Member Functions
static void transformDisplayToFrameBuffer (float &x, float &y)
static void transformDisplayToFrameBuffer (float &x, float &y, const Rect &in)
static void transformDisplayToFrameBuffer (int16_t &x, int16_t &y)
static void transformDisplayToFrameBuffer (int16_t &x, int16_t &y, const Rect &in)
static void transformDisplayToFrameBuffer (Rect &r)
static void transformDisplayToFrameBuffer (Rect &r, const Rect &in)
static void transformFrameBufferToDisplay (int16_t &x, int16_t &y)
static void transformFrameBufferToDisplay (Rect &r)
Detailed Description
Defines transformations from display space to framebuffer space. The display might be (considered) in portrait mode from 0,0 to 272,480, while the actual framebuffer is from 0,0 to 480,272. This class handles the transformations.
Member Function Documentation
transformDisplayToFrameBuffer() [1/6]
static void transformDisplayToFrameBuffer (float & x, float & y) static
Transform x,y from display to framebuffer coordinates.
Parameters
[in,out] x the x part to translate.
[in,out] y the y part to translate.
transformDisplayToFrameBuffer() [2/6]
static void transformDisplayToFrameBuffer (float & x, float & y, const Rect & in) static
Transform x,y from coordinates relative to the in rect to framebuffer coordinates.
Transform x,y from coordinates relative to the in rect to framebuffer coordinates.
Parameters
[in,out] x the x part to translate.
[in,out] y the y part to translate.
in the rectangle defining the coordinate space.
transformDisplayToFrameBuffer() [3/6]
static void transformDisplayToFrameBuffer (int16_t & x, int16_t & y) static
Transform x,y from display to framebuffer coordinates.
Parameters
[in,out] x the x part to translate.
[in,out] y the y part to translate.
Referenced by Canvas::Canvas(), TextureMapper::drawQuad(), AbstractPainterBitmap::setBitmap(), and HALSDL2::updateTitle().
transformDisplayToFrameBuffer() [4/6]
static void transformDisplayToFrameBuffer (int16_t & x, int16_t & y, const Rect & in) static
Transform x,y from coordinates relative to the in rect to framebuffer coordinates.
Transform x,y from coordinates relative to the in rect to framebuffer coordinates.
Parameters
[in,out] x the x part to translate.
[in,out] y the y part to translate.
in the rectangle defining the coordinate space.
transformDisplayToFrameBuffer() [5/6]
static void transformDisplayToFrameBuffer (Rect & r) static
Transform rectangle from display to framebuffer coordinates.
Parameters
[in,out] r the rectangle to translate.
transformDisplayToFrameBuffer() [6/6]
static void transformDisplayToFrameBuffer (Rect & r, const Rect & in) static
Transform rectangle r from coordinates relative to the in rect to framebuffer coordinates.
Transform rectangle r from coordinates relative to the in rect to framebuffer coordinates.
Parameters
[in,out] r the rectangle to translate.
in the rectangle defining the coordinate space.
transformFrameBufferToDisplay() [1/2]
static void transformFrameBufferToDisplay (int16_t & x, int16_t & y) static
Transform x,y from framebuffer to display coordinates.
Parameters
[in,out] x the x part to translate.
[in,out] y the y part to translate.
transformFrameBufferToDisplay() [2/2]
static void transformFrameBufferToDisplay (Rect & r) static
Transform rectangle from framebuffer to display coordinates.
Parameters
[in,out] r the rectangle to translate.
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/transforms/DisplayTransformation.hpp