Battery Simulator Documentation: GraphElementArea
GraphElementArea
#include "GraphElements.hpp"
Public Member Functions
GraphElementArea ()
virtual bool drawCanvasWidget (const Rect &invalidatedArea) const
FORCE_INLINE_FUNCTION float getBaselineAsFloat () const
FORCE_INLINE_FUNCTION int getBaselineAsInt () const
FORCE_INLINE_FUNCTION int getBaselineScaled () const
FORCE_INLINE_FUNCTION int getScale () const
virtual void invalidateGraphPointAt (int16_t index)
FORCE_INLINE_FUNCTION void setBaseline (float baseline)
FORCE_INLINE_FUNCTION void setBaseline (int baseline)
FORCE_INLINE_FUNCTION void setBaselineScaled (int baseline)
FORCE_INLINE_FUNCTION void setScale (int scale)
Public Member Functions inherited from AbstractGraphElement
AbstractGraphElement ()
Public Member Functions inherited from CanvasWidget
CanvasWidget ()
virtual void draw (const Rect &invalidatedArea) const
virtual uint8_t getAlpha () const
virtual Rect getMinimalRect () const
const AbstractPainter * getPainter () const
virtual Rect getSolidRect () const
virtual void invalidate () const
virtual void setAlpha (uint8_t newAlpha)
void setPainter (const AbstractPainter &painter)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
int dataScale
The scaling factor.
int yBaseline
The base value.
Protected Attributes inherited from CanvasWidget
uint8_t alpha
The Alpha for this CanvasWidget.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Protected Member Functions inherited from AbstractGraphElement
FORCE_INLINE_FUNCTION int convertToGraphScaleX (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION int convertToGraphScaleY (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION AbstractDataGraph * getGraph () const
FORCE_INLINE_FUNCTION int getIndexToXAxis (const AbstractDataGraph *graph, const int valueScaled, const int labelScaled) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenXQ5 (const AbstractDataGraph *graph, int16_t index) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenYQ5 (const AbstractDataGraph *graph, int16_t index) const
bool isCenterInvisible (const AbstractDataGraph *graph, int16_t index) const
Rect rectAround (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5, CWRUtil::Q5 diameterQ5) const
Rect rectFromQ5Coordinates (CWRUtil::Q5 screenXminQ5, CWRUtil::Q5 screenYminQ5, CWRUtil::Q5 screenXmaxQ5, CWRUtil::Q5 screenYmaxQ5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 roundQ5 (CWRUtil::Q5 q5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenXQ5 (const AbstractDataGraph *graph, int x) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenYQ5 (const AbstractDataGraph *graph, int y) const
FORCE_INLINE_FUNCTION bool xScreenRangeToIndexRange (const AbstractDataGraph *graph, int16_t xMin, int16_t xMax, int16_t &indexMin, int16_t &indexMax) const
Detailed Description
GraphElementArea will fill the area below the line connecting the data points in the graph.
Note
The Area is drawn using Canvas Widget Renderer which is slower but produces much nicer graphics.
Constructor & Destructor Documentation
GraphElementArea()
GraphElementArea () inline
        : dataScale(1), yBaseline(0)
    {
    }
Member Function Documentation
drawCanvasWidget()
bool drawCanvasWidget (const Rect & invalidatedArea) const virtual
Draw canvas widget for the given invalidated area. Similar to draw(), but might be invoked several times with increasingly smaller areas to due to memory constraints from the underlying CanvasWidgetRenderer.
Parameters
invalidatedArea The invalidated area.
Returns
true if the widget was drawn properly, false if not.
See also
draw
Implements CanvasWidget.
{
    const AbstractDataGraph* graph = getGraph();
    if (graph->getUsedCapacity() <= 1)
    {
        return true; // Nothing to draw, everything is fine!
    }
    int16_t indexMin;
    int16_t indexMax;
    if (!xScreenRangeToIndexRange(graph, invalidatedArea.x, invalidatedArea.right(), indexMin, indexMax))
    {
        return true; // Nothing to draw, everything is fine!
    }
    const int16_t gapIndex = graph->getGapBeforeIndex();
    const int baseline = convertToGraphScaleY(graph, yBaseline, dataScale);
    const CWRUtil::Q5 screenYbaseQ5 = roundQ5(valueToScreenYQ5(graph, baseline));
    CWRUtil::Q5 screenXQ5;
    if (indexMin + 1 == gapIndex)
    {
        if (indexMin > 0)
        {
            indexMin--; // Draw the last line segment before the gap
        }
        else
        {
            indexMin++; // Do not draw a 1 segment line (a "dot")
        }
    }
    const Rect invalidRect = Rect(graph->getGraphAreaPaddingLeft(), graph->getGraphAreaPaddingTop(), graph->getGraphAreaWidth(), graph->getGraphAreaHeight()) & invalidatedArea;
    Canvas canvas(getPainter(), getAbsoluteRect(), invalidRect, getAlpha());
    canvas.moveTo(roundQ5(indexToScreenXQ5(graph, indexMin)), screenYbaseQ5);
    for (int16_t index = indexMin; index <= indexMax; index++)
    {
        if (index == gapIndex)
        {
            canvas.lineTo(screenXQ5, screenYbaseQ5);
            screenXQ5 = roundQ5(indexToScreenXQ5(graph, index));
            canvas.lineTo(screenXQ5, screenYbaseQ5);
        }
        else
        {
            screenXQ5 = roundQ5(indexToScreenXQ5(graph, index));
        }
        canvas.lineTo(screenXQ5, roundQ5(indexToScreenYQ5(graph, index)));
    }
    canvas.lineTo(screenXQ5, screenYbaseQ5);
    return canvas.render(graph->getAlpha());
}
References AbstractGraphElement::convertToGraphScaleY(), GraphElementArea::dataScale, Drawable::getAbsoluteRect(), CanvasWidget::getAlpha(), AbstractGraphElement::getGraph(), CanvasWidget::getPainter(), AbstractGraphElement::indexToScreenXQ5(), AbstractGraphElement::indexToScreenYQ5(), AbstractGraphElement::roundQ5(), AbstractGraphElement::valueToScreenYQ5(), AbstractGraphElement::xScreenRangeToIndexRange(), and GraphElementArea::yBaseline.
getBaselineAsFloat()
FORCE_INLINE_FUNCTION float getBaselineAsFloat () const inline
Gets the base previously set using setBase.
Returns
The base value.
See also
setBaseline
    {
        return AbstractDataGraph::scaled2float(getBaselineScaled(), dataScale);
    }
References GraphElementArea::dataScale, GraphElementArea::getBaselineScaled(), and AbstractDataGraph::scaled2float().
getBaselineAsInt()
FORCE_INLINE_FUNCTION int getBaselineAsInt () const inline
Gets the base previously set using setBase.
Returns
The base value.
See also
setBaseline
    {
        return AbstractDataGraph::scaled2int(getBaselineScaled(), dataScale);
    }
References GraphElementArea::dataScale, GraphElementArea::getBaselineScaled(), and AbstractDataGraph::scaled2int().
getBaselineScaled()
FORCE_INLINE_FUNCTION int getBaselineScaled () const inline
Gets the base previously set using setBase.
Returns
The base value.
See also
setBaseline
Note
The baseline returned here is left unscaled.
    {
        return yBaseline;
    }
References GraphElementArea::yBaseline.
Referenced by GraphElementArea::getBaselineAsFloat(), and GraphElementArea::getBaselineAsInt().
getScale()
FORCE_INLINE_FUNCTION int getScale () const inline
Gets the scaling factor set using setScale.
Returns
The scaling factor.
See also
setScale
    {
        return dataScale;
    }
References GraphElementArea::dataScale.
invalidateGraphPointAt()
void invalidateGraphPointAt (int16_t index) virtual
Invalidate the point at the given index. This allows a graph element to only invalidate the minimum rectangle required for the given index. The Graph will call this function before and after changing a point to ensure that both the old and the new area are redrawn (invalidated).
Parameters
index Zero-based index of the point.
Implements AbstractGraphElement.
{
    const AbstractDataGraph* graph = getGraph();
    const int baseline = convertToGraphScaleY(graph, yBaseline, dataScale);
    const CWRUtil::Q5 screenYbaseQ5 = roundQ5(valueToScreenYQ5(graph, baseline));
    CWRUtil::Q5 screenXminQ5 = indexToScreenXQ5(graph, index);
    CWRUtil::Q5 screenXmaxQ5 = screenXminQ5;
    CWRUtil::Q5 screenYminQ5 = indexToScreenYQ5(graph, index);
    CWRUtil::Q5 screenYmaxQ5 = screenYminQ5;
    if (index > 0)
    {
        screenXminQ5 = indexToScreenXQ5(graph, index - 1);
        const CWRUtil::Q5 screenYnewQ5 = indexToScreenYQ5(graph, index - 1);
        screenYminQ5 = MIN(screenYminQ5, screenYnewQ5);
        screenYmaxQ5 = MAX(screenYmaxQ5, screenYnewQ5);
    }
    if (index < graph->getUsedCapacity() - 1)
    {
        screenXmaxQ5 = indexToScreenXQ5(graph, index + 1);
        const CWRUtil::Q5 screenYnewQ5 = indexToScreenYQ5(graph, index + 1);
        screenYminQ5 = MIN(screenYminQ5, screenYnewQ5);
        screenYmaxQ5 = MAX(screenYmaxQ5, screenYnewQ5);
    }
    screenYminQ5 = MIN(screenYminQ5, screenYbaseQ5);
    screenYmaxQ5 = MAX(screenYmaxQ5, screenYbaseQ5);
    Rect dirty(rectFromQ5Coordinates(screenXminQ5, screenYminQ5, screenXmaxQ5, screenYmaxQ5));
    dirty &= Rect(0, graph->getGraphAreaPaddingTop(), graph->getGraphAreaWidthIncludingPadding(), graph->getGraphAreaHeight());
    invalidateRect(dirty);
}
References AbstractGraphElement::convertToGraphScaleY(), GraphElementArea::dataScale, touchgfx::dirty, AbstractGraphElement::getGraph(), AbstractGraphElement::indexToScreenXQ5(), AbstractGraphElement::indexToScreenYQ5(), Drawable::invalidateRect(), MAX, MIN, AbstractGraphElement::rectFromQ5Coordinates(), AbstractGraphElement::roundQ5(), AbstractGraphElement::valueToScreenYQ5(), and GraphElementArea::yBaseline.
setBaseline() [1/2]
FORCE_INLINE_FUNCTION void setBaseline (float baseline) inline
Sets the base of the area drawn. Normally, the base is 0 which means that the area is drawn below positive y values and above negative y values. Setting the base to a very high number will cause the area above the graph to be drawn. Setting the base to a very low number will cause the area below the graph to be drawn (even for negative numbers, which are higher than the base value).
Parameters
baseline The baseline value.
See also
getBaselineAsInt, getBaselineAsFloat
    {
        setBaselineScaled(AbstractDataGraph::float2scaled(baseline, dataScale));
    }
References GraphElementArea::dataScale, AbstractDataGraph::float2scaled(), and GraphElementArea::setBaselineScaled().
setBaseline() [2/2]
FORCE_INLINE_FUNCTION void setBaseline (int baseline) inline
Sets the base of the area drawn. Normally, the base is 0 which means that the area is drawn below positive y values and above negative y values. Setting the base to a very high number will cause the area above the graph to be drawn. Setting the base to a very low number will cause the area below the graph to be drawn (even for negative numbers, which are higher than the base value).
Parameters
baseline The baseline value.
See also
getBaselineAsInt, getBaselineAsFloat
    {
        setBaselineScaled(baseline * dataScale);
    }
References GraphElementArea::dataScale, and GraphElementArea::setBaselineScaled().
setBaselineScaled()
FORCE_INLINE_FUNCTION void setBaselineScaled (int baseline) inline
Sets the base of the area drawn. Normally, the base is 0 which means that the area is drawn below positive y values and above negative y values. Setting the base to a very high number will cause the area above the graph to be drawn. Setting the base to a very low number will cause the area below the graph to be drawn (even for negative numbers, which are higher than the base value).
Parameters
baseline The baseline value.
See also
getBaselineAsInt, getBaselineAsFloat
Note
The baseline set here must already be scaled.
    {
        yBaseline = baseline;
    }
References GraphElementArea::yBaseline.
Referenced by GraphElementArea::setBaseline(), and GraphElementArea::setBaseline().
setScale()
FORCE_INLINE_FUNCTION void setScale (int scale) inline
Sets a scaling factor to be multiplied on the baseline. Any already set baseline will be updated to the new correctly scaled value. To avoid this, use setBaselineScaled() after setting scale.
Parameters
scale The scaling factor.
See also
getScale
    {
        assert(scale != 0);
        yBaseline = AbstractDataGraph::convertToNewScale(yBaseline, dataScale, scale);
        dataScale = scale;
    }
References AbstractDataGraph::convertToNewScale(), GraphElementArea::dataScale, and GraphElementArea::yBaseline.
Member Data Documentation
dataScale
int dataScale protected
The scaling factor.
Referenced by GraphElementArea::drawCanvasWidget(), GraphElementArea::getBaselineAsFloat(), GraphElementArea::getBaselineAsInt(), GraphElementArea::getScale(), GraphElementArea::invalidateGraphPointAt(), GraphElementArea::setBaseline(), GraphElementArea::setBaseline(), and GraphElementArea::setScale().
yBaseline
int yBaseline protected
The base value.
Referenced by GraphElementArea::drawCanvasWidget(), GraphElementArea::getBaselineScaled(), GraphElementArea::invalidateGraphPointAt(), GraphElementArea::setBaselineScaled(), and GraphElementArea::setScale().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/graph/GraphElements.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph/GraphElements.cpp