Battery Simulator Documentation: AbstractButtonContainer
AbstractButtonContainer
#include "AbstractButtonContainer.hpp"
Public Member Functions
AbstractButtonContainer ()
virtual void executeAction ()
uint8_t getAlpha () const
bool getPressed () const
void setAction (GenericCallback< const AbstractButtonContainer & > &callback)
void setAlpha (uint8_t newAlpha)
void setPressed (bool isPressed)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual void handleAlphaUpdated ()
virtual void handlePressedUpdated ()
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
GenericCallback< const AbstractButtonContainer & > * action
The action to be executed.
uint8_t alpha
The current alpha value. 255 denotes solid, 0 denotes completely invisible.
bool pressed
True if pressed.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
An abstract button container. The AbstractButtonContainer defines pressed/not pressed state, the alpha value, and the action Callback of a button. AbstractButtonContainer is used as superclass for classes defining a specific button behavior.
See also
ClickButtonTrigger, RepeatButtonTrigger, ToggleButtonTrigger, TouchButtonTrigger
Constructor & Destructor Documentation
AbstractButtonContainer()
AbstractButtonContainer () inline
        : pressed(false), alpha(255), action(0)
    {
        setTouchable(true);
    }
References Drawable::setTouchable().
Member Function Documentation
executeAction()
virtual void executeAction () inline virtual
Executes the previously set action.
See also
setAction
    {
        if (action && action->isValid())
        {
            action->execute(*this);
        }
    }
References AbstractButtonContainer::action.
Referenced by ClickButtonTrigger::handleClickEvent(), RepeatButtonTrigger::handleClickEvent(), ToggleButtonTrigger::handleClickEvent(), TouchButtonTrigger::handleClickEvent(), and RepeatButtonTrigger::handleTickEvent().
getAlpha()
uint8_t getAlpha () const inline
Gets the current alpha value of the widget. The alpha value is in range 255 (solid) to 0 (invisible).
Returns
The current alpha value.
See also
setAlpha
    {
        return alpha;
    }
References AbstractButtonContainer::alpha.
getPressed()
bool getPressed () const inline
Gets the pressed state.
Returns
True if it succeeds, false if it fails.
See also
setPressed
    {
        return pressed;
    }
References AbstractButtonContainer::pressed.
Referenced by ClickButtonTrigger::handleClickEvent(), RepeatButtonTrigger::handleClickEvent(), ToggleButtonTrigger::handleClickEvent(), and TouchButtonTrigger::handleClickEvent().
handleAlphaUpdated()
virtual void handleAlphaUpdated () inline protected virtual
Handles what should happen when the alpha is updated.
    {
    }
Referenced by AbstractButtonContainer::setAlpha().
handlePressedUpdated()
virtual void handlePressedUpdated () inline protected virtual
Handles what should happen when the pressed state is updated.
    {
    }
Referenced by AbstractButtonContainer::setPressed().
setAction()
void setAction (GenericCallback< const AbstractButtonContainer & > & callback) inline
Sets an action callback to be executed by the subclass of AbstractContainerButton.
Parameters
callback The callback.
See also
executeAction
    {
        action = &callback;
    }
References AbstractButtonContainer::action.
setAlpha()
void setAlpha (uint8_t newAlpha) inline
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
    {
        alpha = newAlpha;
        handleAlphaUpdated();
    }
References AbstractButtonContainer::handleAlphaUpdated().
setPressed()
void setPressed (bool isPressed) inline
Sets the pressed state to the given state. A subclass of AbstractButtonContainer should implement handlePressedUpdate() to handle the new pressed state.
Parameters
isPressed True if is pressed, false if not.
See also
getPressed, handlePressedUpdated
    {
        pressed = isPressed;
        handlePressedUpdated();
    }
References AbstractButtonContainer::handlePressedUpdated(), and AbstractButtonContainer::pressed.
Referenced by ToggleButtonTrigger::forceState(), ClickButtonTrigger::handleClickEvent(), RepeatButtonTrigger::handleClickEvent(), ToggleButtonTrigger::handleClickEvent(), and TouchButtonTrigger::handleClickEvent().
Member Data Documentation
action
GenericCallback<const AbstractButtonContainer&>* action protected
The action to be executed.
Referenced by AbstractButtonContainer::executeAction(), and AbstractButtonContainer::setAction().
alpha
uint8_t alpha protected
The current alpha value. 255 denotes solid, 0 denotes completely invisible.
Referenced by AbstractButtonContainer::getAlpha().
pressed
bool pressed protected
True if pressed.
Referenced by ImageButtonStyle< T >::getCurrentlyDisplayedBitmap(), AbstractButtonContainer::getPressed(), AnimatedImageButtonStyle< T >::handlePressedUpdated(), RepeatButtonTrigger::handleTickEvent(), and AbstractButtonContainer::setPressed().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/buttons/AbstractButtonContainer.hpp