Battery Simulator Documentation: Screen
Screen
#include "Screen.hpp"
Public Member Functions
Screen ()
virtual ~Screen ()
virtual void afterTransition ()
void bindTransition (Transition &trans)
void draw ()
virtual void draw (Rect &rect)
Container & getRootContainer ()
int16_t getScreenHeight () const
int16_t getScreenWidth () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleKeyEvent (uint8_t key)
virtual void handleTickEvent ()
void JSMOC (const Rect &invalidatedArea, Drawable *widgetToDraw)
virtual void setupScreen ()
void startSMOC (const Rect &invalidatedArea)
virtual void tearDownScreen ()
bool usingSMOC () const
Protected Member Functions
void add (Drawable &d)
void insert (Drawable *previous, Drawable &d)
void invalidate () const
void invalidateRect (Rect &invalidatedArea) const
void remove (Drawable &d)
void useSMOCDrawing (bool enabled)
Protected Attributes
Container container
The container contains the contents of the screen.
Drawable * focus
The drawable currently in focus (set when DOWN_PRESSED is received).
Private Attributes
int16_t fingerAdjustmentX
int16_t fingerAdjustmentY
bool useSMOC
Detailed Description
A Screen represents a full-screen drawable area. Applications create specific screens by subclassing this class. Each Screen has a root container to which drawables are added. The Screen makes sure to delegate draw requests and various events to the appropriate drawables in correct order.
Constructor & Destructor Documentation
Screen()
Screen ()
Initializes a new instance of the Screen class.
~Screen()
virtual ~Screen () inline virtual
Finalizes an instance of the Screen class.
    {
    }
Member Function Documentation
add()
void add (Drawable & d) inline protected
Add a drawable to the content container.
Parameters
[in] d The Drawable to add.
Note
Must not be called with a Drawable that was already added to the screen. If in doubt, call remove() first.
    {
        container.add(d);
    }
References Container::add(), and Screen::container.
Referenced by Screen1ViewBase::Screen1ViewBase().
afterTransition()
virtual void afterTransition () inline virtual
Called by Application::handleTickEvent() when the transition to the screen is done. Base version does nothing, but override to do screen specific initialization code that has to be done after the transition to the screen.
See also
Application::handleTickEvent
    {
    }
bindTransition()
void bindTransition (Transition & trans)
Enables the transition to access the containers.
Parameters
[in] trans The transition to bind.
draw() [1/2]
void draw ()
Tells the screen to draw its entire area.
Note
The more specific draw(Rect&) version is preferred when possible.
draw() [2/2]
virtual void draw (Rect & rect) virtual
Tell the screen to draw the specified area. Will traverse the drawables tree from in z-order and delegate draw to them.
Parameters
[in] rect The area in absolute coordinates.
Note
The given rect must be in absolute coordinates.
getRootContainer()
Container & getRootContainer () inline
Obtain a reference to the root container of this screen.
Returns
The root container.
    {
        return container;
    }
References Screen::container.
getScreenHeight()
int16_t getScreenHeight () const inline
Gets height of the current screen. In most cases, this is the same as HAL::DISPLAY_HEIGHT.
Returns
The screen height.
    {
        return HAL::DISPLAY_HEIGHT;
    }
References HAL::DISPLAY_HEIGHT.
getScreenWidth()
int16_t getScreenWidth () const inline
Gets width of the current screen. In most cases, this is the same as HAL::DISPLAY_WIDTH.
Returns
The screen width.
    {
        return HAL::DISPLAY_WIDTH;
    }
References HAL::DISPLAY_WIDTH.
handleClickEvent()
virtual void handleClickEvent (const ClickEvent & event) virtual
Traverse the drawables in reverse z-order and notify them of a click event.
Parameters
event The event to handle.
handleDragEvent()
virtual void handleDragEvent (const DragEvent & event) virtual
Traverse the drawables in reverse z-order and notify them of a drag event.
Parameters
event The event to handle.
handleGestureEvent()
virtual void handleGestureEvent (const GestureEvent & event) virtual
Handle gestures. Traverses drawables in reverse-z and notifies them of the gesture.
Parameters
event The event to handle.
handleKeyEvent()
virtual void handleKeyEvent (uint8_t key) inline virtual
Called by the Application on the reception of a "key", the meaning of which is platform/application specific. Default implementation does nothing.
Parameters
key The key to handle.
    {
        (void)key; // Unused variable
    }
References void().
handleTickEvent()
virtual void handleTickEvent () inline virtual
Called by the Application on the current screen with a frequency of Application::TICK_INTERVAL_MS.
    {
    }
insert()
void insert (Drawable * previous, Drawable & d) inline protected
Inserts a Drawable after a specific child node. See Container::insert.
Parameters
[in] previous The Drawable to insert after. If null, insert as header.
[in] d The Drawable to insert.
See also
Container::insert
Note
As with add, do not add the same drawable twice.
    {
        container.insert(previous, d);
    }
References Screen::container, and Container::insert().
invalidate()
void invalidate () const inline protected
Tell the framework that this entire Screen needs to be redrawn.
See also
Container::invalidate
    {
        container.invalidate();
    }
References Screen::container, and Drawable::invalidate().
invalidateRect()
void invalidateRect (Rect & invalidatedArea) const inline protected
Request that a region of this root container on the screen is redrawn. See Container::invalidateRect.
To invalidate the entire Screen, use invalidate()
Parameters
[in] invalidatedArea The area of this drawable to redraw expressed in coordinates relative to the root container.
See also
Container::invalidateRect
Note
The invalidatedArea position is relative to the root container, which is usually the same as the Screen coordinates.
    {
        container.invalidateRect(invalidatedArea);
    }
References Screen::container, and Drawable::invalidateRect().
JSMOC()
void JSMOC (const Rect & invalidatedArea, Drawable * widgetToDraw)
Recursive JSMOC function. This is the actual occlusion culling implementation.
Parameters
[in] invalidatedArea The area to redraw, expressed in absolute coordinates.
[in] widgetToDraw Widget currently being drawn.
Note
JSMOC is an abbreviation of Jesper, Søren & Martin's Occlusion Culling.
remove()
void remove (Drawable & d) inline protected
Removes a drawable from the content container. Safe to call even if the drawable was never added (in which case nothing happens).
Parameters
[in] d The Drawable to remove.
    {
        container.remove(d);
    }
References Screen::container, and Container::remove().
setupScreen()
virtual void setupScreen () inline virtual
Called by Application::switchScreen() when this screen is going to be displayed. Base version does nothing, but place any screen specific initialization code in an overridden version.
See also
Application::switchScreen
Reimplemented in Screen1ViewBase, and Screen1View.
    {
    }
startSMOC()
void startSMOC (const Rect & invalidatedArea)
Starts a JSMOC run, analyzing what parts of what widgets should be redrawn.
Parameters
[in] invalidatedArea The area to redraw, expressed in absolute coordinates.
Note
SMOC is an abbreviation of Søren & Martin's Occlusion Culling.
tearDownScreen()
virtual void tearDownScreen () inline virtual
Called by Application::switchScreen() when this screen will no longer be displayed. Base version does nothing, but place any screen specific cleanup code in an overridden version.
See also
Application::switchScreen
Reimplemented in Screen1View.
    {
    }
Referenced by Screen1View::tearDownScreen().
useSMOCDrawing()
void useSMOCDrawing (bool enabled) protected
Determines whether to use JSMOC or painter's algorithm for drawing.
Parameters
enabled true if JSMOC should be enabled, false if disabled (meaning painter's algorithm is employed instead).
usingSMOC()
bool usingSMOC () const inline
Determines if using JSMOC.
Returns
true if this screen uses the JSMOC drawing algorithm.
    {
        return useSMOC;
    }
References Screen::useSMOC.
Member Data Documentation
container
Container container protected
The container contains the contents of the screen.
Referenced by Screen::add(), Screen::getRootContainer(), Screen::insert(), Screen::invalidate(), Screen::invalidateRect(), and Screen::remove().
fingerAdjustmentX
int16_t fingerAdjustmentX private
fingerAdjustmentY
int16_t fingerAdjustmentY private
focus
Drawable* focus protected
The drawable currently in focus (set when DOWN_PRESSED is received).
useSMOC
bool useSMOC private
Referenced by Screen::usingSMOC().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/Screen.hpp