Battery Simulator Documentation: Container
Container
#include "Container.hpp"
Public Member Functions
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A Container is a Drawable that can have child nodes. The z-order of children is determined by the order in which Drawables are added to the container - the Drawable added last will be front-most on the screen.
This class overrides a few functions in Drawable in order to traverse child nodes.
Note that containers act as view ports - that is, only the parts of children that intersect with the geometry of the container will be visible (e.g. setting a container's width to 0 will render all children invisible).
See also
Drawable
Constructor & Destructor Documentation
Container()
Container () inline
        : Drawable(),
          firstChild(0)
    {
    }
Member Function Documentation
add()
void add (Drawable & d) virtual
Adds a Drawable instance as child to this Container. The Drawable added will be placed as the element to be drawn last, and thus appear on top of all previously added drawables in the Container.
Parameters
[in] d The Drawable to add.
Note
Never add a drawable more than once!
Reimplemented in ListLayout, ModalWindow, ScrollableContainer, SlideMenu, and SwipeContainer.
{
    assert(&d != this && "Cannot add Drawable to self");
    assert(d.parent == 0 && "Cannot add Drawable multiple times");
    // Initialize d to have this as parent and no sibling.
    d.parent = this;
    d.nextSibling = 0;
    // Check if d is the first child to be added (container is empty)
    if (!firstChild)
    {
        firstChild = &d;
    }
    else
    {
        Drawable* head = firstChild;
        // Skip to end of currently added children
        while (head->nextSibling)
        {
            assert(head != &d && "Cannot add Drawable multiple times");
            head = head->nextSibling;
        }
        assert(head != &d && "Cannot add Drawable multiple times");
        // Make last child now point to d.
        head->nextSibling = &d;
    }
}
References Container::firstChild, and Drawable::nextSibling.
Referenced by AbstractDataGraph::AbstractDataGraph(), AbstractProgressIndicator::AbstractProgressIndicator(), AnalogClock::AnalogClock(), BoxProgress::BoxProgress(), CircleProgress::CircleProgress(), DigitalClock::DigitalClock(), Gauge::Gauge(), ImageProgress::ImageProgress(), Keyboard::Keyboard(), LineProgress::LineProgress(), ModalWindow::ModalWindow(), SwipeContainer::PageIndicator::PageIndicator(), ScrollBase::ScrollBase(), ScrollWheelWithSelectionStyle::ScrollWheelWithSelectionStyle(), SlideMenu::SlideMenu(), Slider::Slider(), SwipeContainer::SwipeContainer(), TextProgress::TextProgress(), ZoomAnimationImage::ZoomAnimationImage(), ListLayout::add(), ModalWindow::add(), ScrollableContainer::add(), Screen::add(), AbstractDataGraph::addBottomElement(), AbstractDataGraph::addGraphElement(), AbstractDataGraph::addLeftElement(), AbstractDataGraph::addRightElement(), AbstractDataGraph::addTopElement(), CoverTransition< templateDirection >::init(), SlideTransition< templateDirection >::init(), WipeTransition< templateDirection >::init(), Container::insert(), Gauge::putArcOnTop(), DrawableList::refreshDrawables(), and AnalogClock::setupHand().
contains()
bool contains (const Drawable & d) virtual
Query if a given Drawable has been added directly to this Container. The search is not done recursively.
Parameters
d The Drawable to look for.
Returns
True if the specified Drawable instance is direct child of this container, false otherwise.
{
    bool found = false;
    Drawable* head = firstChild;
    while (head && !found)
    {
        found = (head == &d);
        head = head->nextSibling;
    }
    return found;
}
References Container::firstChild, and Drawable::nextSibling.
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Implements Drawable.
Reimplemented in Keyboard.
{
    // The draw function of Container is not normally used. Containers do not per default
    // appear in the draw chain, since they are normally invisible themselves. However,
    // if someone decides to call draw on a container, at least do something useful (draw children).
    if (!isVisible() || !firstChild)
    {
        // Nothing to draw
        return;
    }
    const Rect tmp = invalidatedArea;
    Drawable* d = firstChild;
    while (d)
    {
        if (d->isVisible())
        {
            Rect drawableRegion = tmp & d->getRect();
            if (!drawableRegion.isEmpty())
            {
                // This child has a non-empty intersection with the invalidated area.
                // Convert region to the Drawable's coordinate system and draw.
                drawableRegion.x -= d->getX();
                drawableRegion.y -= d->getY();
                d->draw(drawableRegion);
            }
        }
        d = d->nextSibling;
    }
}
References Container::firstChild, and Drawable::isVisible().
forEachChild()
void forEachChild (GenericCallback< Drawable & > * function) virtual
Executes the specified callback function for each child in the Container. The callback to execute must have the following prototype: void T::func(Drawable&)
Parameters
[in] function The function to be executed for each child.
{
    Drawable* d = firstChild;
    while (d)
    {
        function->execute(*d);
        d = d->nextSibling;
    }
}
References Container::firstChild.
Referenced by ListLayout::insert(), ListLayout::remove(), and ListLayout::setDirection().
getContainedArea()
Rect getContainedArea () const protected virtual
Gets a rectangle describing the total area covered by the children of this container.
Returns
Rectangle covering all children.
Reimplemented in ScrollableContainer.
{
    Drawable* d = firstChild;
    Rect contained;
    while (d)
    {
        contained.expandToFit(d->getRect());
        d = d->nextSibling;
    }
    return contained;
}
References Container::firstChild.
getFirstChild()
virtual Drawable * getFirstChild () inline virtual
Obtain a pointer to the first child of this container. The first child is the Drawable drawn first, and therefore the Drawable behind all other children of this Container. Useful if you want to manually iterate the children added to this container.
Returns
Pointer to the first drawable added to this container. If nothing has been added return zero.
See also
getNextSibling
Reimplemented from Drawable.
    {
        return firstChild;
    }
References Container::firstChild.
Referenced by CoverTransition< templateDirection >::handleTickEvent(), SlideTransition< templateDirection >::handleTickEvent(), CoverTransition< templateDirection >::init(), SlideTransition< templateDirection >::init(), AbstractDataGraph::invalidateGraphPointAt(), AbstractDataGraph::invalidateXAxisPointAt(), SwipeContainer::remove(), and AbstractDataGraph::updateAreasPosition().
getLastChild()
void getLastChild (int16_t x, int16_t y, Drawable ** last) virtual
Gets the last child in the list of children in this Container. If this Container is touchable (isTouchable()), it will be passed back as the result. Otherwise all visible children are traversed recursively to find the Drawable that intersects with the given coordinate.
Parameters
x The x coordinate of the intersection.
y The y coordinate of the intersection.
[out] last out parameter in which the result is placed.
See also
isVisible, isTouchable, getLastChildNear
Implements Drawable.
Reimplemented in ScrollableContainer.
{
    // This function is used to obtain the drawable that should receive a click/drag/gesture event.
    // Find the last child (ie. the last child that was added, ie. the "front-most" drawable) covering
    // the specified coords.
    if (isTouchable())
    {
        // If the container itself is touchable, result so far is "this". Might be overridden by a child.
        *last = this;
    }
    Drawable* d = firstChild;
    while (d)
    {
        // Iterate over children.
        if (d->isVisible() && d->getRect().intersect(x, y))
        {
            const int16_t xadj = x - d->getX();
            const int16_t yadj = y - d->getY();
            d->getLastChild(xadj, yadj, last);
        }
        d = d->nextSibling;
    }
}
References Container::firstChild, and Drawable::isTouchable().
Referenced by ScrollableContainer::getLastChild(), Container::getLastChildNear(), and ScrollableContainer::handleDragEvent().
getLastChildNear()
void getLastChildNear (int16_t x, int16_t y, Drawable ** last, int16_t * fingerAdjustmentX, int16_t * fingerAdjustmentY) virtual
Works similar to getLastChild() but also considers the current set finger size in HAL.
Parameters
x The x coordinate of the intersection.
y The y coordinate of the intersection.
[out] last out parameter in which the result is placed.
[out] fingerAdjustmentX out parameter in which the finger adjustment x is placed.
[out] fingerAdjustmentY out parameter in which the finger adjustment y is placed.
See also
getLastChild, HAL::setFingerSize
{
    const int fingerSize = HAL::getInstance()->getFingerSize();
    *fingerAdjustmentX = 0;
    *fingerAdjustmentY = 0;
    *last = 0;
    Container::getLastChild(x, y, last);
    const int fingerSizeDistance = 3; // Up to this number is not multi-sampled
    if (fingerSize > fingerSizeDistance)
    {
        const Rect meAbsRect = getAbsoluteRect();
        uint32_t bestDistance = 0xFFFFFFFF;
        Drawable* previous = 0; // Speed up calculations if we hit the same drawable on next sample
        if (*last)
        {
            // Touched a drawable, but perhaps there is a better alternative
            previous = *last;
            const Rect absRect = (*last)->getAbsoluteRect();
            const int dx = (x + meAbsRect.x) - (absRect.x + (absRect.width / 2));
            const int dy = (y + meAbsRect.y) - (absRect.y + (absRect.height / 2));
            bestDistance = dx * dx + dy * dy;
        }
        const int samplePoints[2][4][2] = { { { 0, -1 }, { -1, 0 }, { 1, 0 }, { 0, 1 } },     // above, left, right, below
                                            { { -1, -1 }, { 1, -1 }, { -1, 1 }, { 1, 1 } } }; // up-left, up-right, down-left and down-right
        const int maxRings = 3;
        const int numRings = MIN(maxRings, (fingerSize - 1) / fingerSizeDistance);
        for (int ring = 0; ring < numRings; ring++)
        {
            // For each 'ring' "distance" increases up to "fingerSize":
            const int distance = fingerSize * (ring + 1) / numRings;
            for (int sampleIndex = 0; sampleIndex < 4; sampleIndex++)
            {
                const int* xy = samplePoints[ring % 2][sampleIndex];
                const int16_t deltaX = xy[0] * distance;
                const int16_t deltaY = xy[1] * distance;
                if (rect.intersect(x + deltaX, y + deltaY))
                {
                    Drawable* drawable = 0;
                    Container::getLastChild(x + deltaX, y + deltaY, &drawable);
                    if (drawable && drawable != previous)
                    {
                        previous = drawable;
                        const Rect absRect = drawable->getAbsoluteRect();
                        // Find distance to center of drawable
                        const int dx = (x + meAbsRect.x) - (absRect.x + (absRect.width / 2));
                        const int dy = (y + meAbsRect.y) - (absRect.y + (absRect.height / 2));
                        const uint32_t dist = dx * dx + dy * dy;
                        // Check if this drawable center is closer than the previous
                        if (dist < bestDistance)
{
                            bestDistance = dist;
                            *last = drawable;
                            *fingerAdjustmentX = deltaX;
                            *fingerAdjustmentY = deltaY;
                        }
                    }
                }
            }
        }
    }
}
References Drawable::getAbsoluteRect(), HAL::getInstance(), Container::getLastChild(), Rect::intersect(), MIN, and Drawable::rect.
Referenced by ScrollableContainer::handleClickEvent().
getSolidRect()
Rect getSolidRect () const virtual
Get (the largest possible) rectangle that is guaranteed to be solid (opaque). This information is important, as any Drawable underneath the solid area does not need to be drawn.
Returns
The solid rectangle part of the Drawable.
Note
The rectangle returned must be relative to upper left corner of the Drawable, meaning that a completely solid widget should return the full size Rect(0, 0, getWidth(), getHeight()). If no area can be guaranteed to be solid, an empty Rect must be returned. Failing to return the correct rectangle may result in errors on the display.
Implements Drawable.
{
    return Rect();
}
insert()
void insert (Drawable * previous, Drawable & d) virtual
Inserts a Drawable after a specific child node. If previous child node is 0, the drawable will be inserted as the first element in the list. The first element in the list of children is the element drawn first, so this makes it possible to insert a Drawable behind all previously added children.
Parameters
[in] previous The Drawable to insert after. If null, insert as header.
[in] d The Drawable to insert.
Note
As with add, do not add the same drawable twice.
Reimplemented in ListLayout.
{
    if (!firstChild)
    {
        // Insert as only element
        add(d);
        return;
    }
    else if (!previous)
    {
        // Insert as head element
        d.nextSibling = firstChild;
        firstChild = &d;
        d.parent = this;
    }
    else
    {
        Drawable* tmp = firstChild;
        while (tmp)
        {
            if (tmp == previous)
            {
                d.nextSibling = tmp->nextSibling;
                tmp->nextSibling = &d;
                d.parent = this;
                return;
            }
            tmp = tmp->nextSibling;
        }
    }
}
References Container::add(), and Container::firstChild.
Referenced by ListLayout::insert(), and Screen::insert().
moveChildrenRelative()
void moveChildrenRelative (int16_t deltaX, int16_t deltaY) protected virtual
Calls moveRelative on all children.
Parameters
deltaX Horizontal displacement.
deltaY Vertical displacement.
Reimplemented in ScrollableContainer.
{
    Drawable* d = firstChild;
    while (d)
    {
        d->moveRelative(deltaX, deltaY);
        d = d->nextSibling;
    }
}
References Container::firstChild.
remove()
void remove (Drawable & d) virtual
Removes a Drawable from the container by removing it from the linked list of children. If the Drawable is not in the list of children, nothing happens. It is possible to remove an element from whichever Container it is a member of using:
if (d.getParent()) d.getParent()->remove(d);
The Drawable will have the parent and next sibling cleared, but is otherwise left unaltered.
Parameters
[in] d The Drawable to remove.
Note
This is safe to call even if d is not a child of this Container (in which case nothing happens).
Reimplemented in ListLayout, ModalWindow, SlideMenu, and SwipeContainer.
{
    if (!firstChild)
    {
        // No children
        return;
    }
    if (&d == firstChild)
    {
        // d is first child.
        d.parent = 0;
        if (!d.nextSibling)
        {
            // d was only child, so now this container is empty
            firstChild = 0;
        }
        else
        {
            firstChild = d.nextSibling;
            d.nextSibling = 0;
        }
        return;
    }
    Drawable* tmp = firstChild;
    while (tmp)
    {
        if (tmp->nextSibling == &d)
        {
            tmp->nextSibling = d.nextSibling;
            d.parent = 0;
            d.nextSibling = 0;
            return;
        }
        else
        {
            tmp = tmp->nextSibling;
        }
    }
}
References Container::firstChild.
Referenced by Gauge::Gauge(), ScrollableContainer::add(), Gauge::putArcOnTop(), DrawableList::refreshDrawables(), ListLayout::remove(), ModalWindow::remove(), Screen::remove(), AnalogClock::setupHand(), CoverTransition< templateDirection >::tearDown(), SlideTransition< templateDirection >::tearDown(), and WipeTransition< templateDirection >::tearDown().
removeAll()
void removeAll () virtual
Removes all children in the Container by resetting their parent and sibling pointers. Please note that this is not done recursively, so any child which is itself a Container is not emptied.
Reimplemented in ListLayout.
{
    while (firstChild)
    {
        Drawable* d = firstChild;
        firstChild = firstChild->nextSibling;
        d->parent = 0;
        d->nextSibling = 0;
    }
}
References Container::firstChild, and Drawable::nextSibling.
Referenced by DrawableList::refreshDrawables(), and ListLayout::removeAll().
unlink()
void unlink () virtual
Removes all children by unlinking the first child. The parent and sibling pointers of the children are not reset.
See also
getFirstChild
{
    firstChild = 0;
}
References Container::firstChild.
Member Data Documentation
firstChild
Drawable* firstChild protected
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Referenced by Container::add(), Container::contains(), Container::draw(), Container::forEachChild(), ScrollableContainer::getChildrenContainedArea(), Container::getContainedArea(), Container::getFirstChild(), Container::getLastChild(), Container::insert(), ListLayout::insert(), Container::moveChildrenRelative(), ScrollableContainer::moveChildrenRelative(), Container::remove(), Container::removeAll(), and Container::unlink().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/Container.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/Container.cpp