Battery Simulator Documentation: HALSDL2
HALSDL2
#include "HALSDL2.hpp"
Classes
class SkinInfo
Public Member Functions
HALSDL2 (DMA_Interface &dma, LCD &lcd, TouchController &touchCtrl, uint16_t width, uint16_t height)
virtual void copyScreenshotToClipboard ()
bool doSampleTouch (int32_t &x, int32_t &y) const
virtual void flushFrameBuffer ()
virtual void flushFrameBuffer (const Rect &rect)
bool getConsoleVisible () const
FILE * getPrintFile () const
bool getWindowVisible () const
void loadSkin (DisplayOrientation orientation, int x, int y)
char * localFileName (char *buffer, size_t buffer_size, const char *filename)
bool printToFile (const char *filename)
virtual bool sampleKey (uint8_t &key)
virtual void saveNextScreenshots (int n)
void saveScreenshot ()
virtual void saveScreenshot (char *folder, char *filename)
virtual bool sdl_init (int argcount, char **args)
void setConsoleVisible (bool visible, bool redrawWindow=true)
virtual void setFlashInvalidatedAreas (bool flash=true)
virtual void setFrameBufferSize (uint16_t width, uint16_t height)
void setVsyncInterval (float ms)
void setWindowVisible (bool visible, bool redrawWindow=true)
virtual void taskEntry ()
Public Member Functions inherited from HAL
HAL (DMA_Interface &dmaInterface, LCD &display, TouchController &touchCtrl, uint16_t width, uint16_t height)
virtual ~HAL ()
virtual void allowDMATransfers ()
virtual void backPorchExited ()
virtual void blitCopy (const uint16_t *pSrc, const uint8_t *pClut, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool hasTransparentPixels, uint16_t dstWidth, Bitmap::BitmapFormat srcFormat, Bitmap::BitmapFormat dstFormat, bool replaceBgAlpha)
virtual void blitCopy (const uint16_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool hasTransparentPixels, bool replaceBgAlpha)
virtual void blitCopy (const uint16_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool hasTransparentPixels, uint16_t dstWidth, Bitmap::BitmapFormat srcFormat, Bitmap::BitmapFormat dstFormat, bool replaceBgAlpha)
virtual void blitCopyARGB8888 (const uint16_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint8_t alpha, bool replaceBgAlpha)
virtual void blitCopyGlyph (const uint8_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, colortype color, uint8_t alpha, BlitOperations operation, bool replaceBgAlpha)
virtual void blitCopyWord (const uint16_t *pSrc, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t srcWidth, uint16_t dstWidth)
virtual void blitFill (colortype color, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t alpha, bool replaceBgAlpha)
virtual void blitFill (colortype color, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t alpha, uint16_t dstWidth, Bitmap::BitmapFormat dstFormat, bool replaceBgAlpha)
virtual void blitFillWord (uint16_t colorValue, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t dstWidth)
virtual bool blockCopy (void *RESTRICT dest, const void *RESTRICT src, uint32_t numBytes)
virtual uint16_t configurePartialFrameBuffer (const uint16_t x, const uint16_t y, const uint16_t width, const uint16_t height)
virtual uint16_t * copyFBRegionToMemory (Rect meAbs)
virtual uint16_t * copyFBRegionToMemory (Rect meAbs, uint16_t *dst, uint32_t stride)
virtual uint16_t * copyFromTFTToClientBuffer (Rect region)
virtual void drawDrawableInDynamicBitmap (Drawable &drawable, BitmapId bitmapId)
virtual void drawDrawableInDynamicBitmap (Drawable &drawable, BitmapId bitmapId, const Rect &rect)
void enableDMAAcceleration (const bool enable)
void enableMCULoadCalculation (bool enabled)
virtual void flushDMA ()
void frontPorchEntered ()
uint16_t * getAnimationStorage () const
LCD * getAuxiliaryLCD ()
virtual BlitOperations getBlitCaps ()
ButtonController * getButtonController () const
uint32_t getCPUCycles ()
uint16_t getDisplayHeight () const
DisplayOrientation getDisplayOrientation () const
uint16_t getDisplayWidth () const
virtual DMAType getDMAType ()
uint8_t getFingerSize () const
virtual FlashDataReader * getFlashDataReader () const
FrameBufferAllocator * getFrameBufferAllocator ()
FrameRefreshStrategy getFrameRefreshStrategy () const
Gestures * getGestures ()
uint32_t getLCDRefreshCount ()
uint8_t getMCULoadPct () const
virtual uint16_t getTFTCurrentLine ()
int8_t getTouchSampleRate () const
virtual void initialize ()
void lockDMAToFrontPorch (bool enableLock)
virtual uint16_t * lockFrameBuffer ()
uint16_t * lockFrameBufferForRenderingMethod (RenderingMethod method)
virtual void registerEventListener (UIEventListener &listener)
void registerTaskDelayFunction (void(*delayF)(uint16_t))
virtual void setAnimationStorage (void *animationStorage)
void setAuxiliaryLCD (LCD *auxLCD)
void setButtonController (ButtonController *btnCtrl)
virtual void setDisplayOrientation (DisplayOrientation orientation)
void setDragThreshold (uint8_t value)
void setFingerSize (uint8_t size)
void setFrameBufferAllocator (FrameBufferAllocator *allocator)
virtual void setFrameBufferStartAddresses (void *frameBuffer, void *doubleBuffer, void *animationStorage)
void setFrameRateCompensation (bool enabled)
bool setFrameRefreshStrategy (FrameRefreshStrategy s)
void setMCUActive (bool active)
void setMCUInstrumentation (MCUInstrumentation *mcuInstr)
void setRenderingMethod (RenderingMethod method)
void setTouchSampleRate (int8_t sampleRateInTicks)
void signalDMAInterrupt ()
void swapFrameBuffers ()
virtual void taskDelay (uint16_t ms)
virtual void unlockFrameBuffer ()
void vSync ()
Static Public Member Functions
static uint8_t * doRotate (uint8_t *src)
static char ** getArgv (int *argc)
static const char * getWindowTitle ()
static bool isSingleStepping ()
static uint8_t * scaleTo24bpp (uint16_t *src, Bitmap::BitmapFormat format)
static void setSingleStepping (bool singleStepping=true)
static void setWindowTitle (const char *title)
static void singleStep (uint16_t steps=1)
static void stopApplication ()
Static Public Member Functions inherited from HAL
static HAL * getInstance ()
static LCD & lcd ()
Protected Member Functions
virtual void configureInterrupts ()
virtual void configureLCDInterrupt ()
virtual void disableInterrupts ()
virtual void enableInterrupts ()
virtual void enableLCDControllerInterrupt ()
virtual uint16_t * getTFTFrameBuffer () const
void performDisplayOrientationChange ()
virtual void renderLCD_FrameBufferToMemory (const Rect &_rectToUpdate, uint8_t *frameBuffer)
void setTFTFrameBuffer (uint16_t *addr)
Protected Member Functions inherited from HAL
virtual bool beginFrame ()
virtual void endFrame ()
virtual void FlushCache ()
uint16_t * getClientFrameBuffer ()
virtual void InvalidateCache ()
virtual void noTouch ()
virtual void tick ()
virtual void touch (int32_t x, int32_t y)
Private Member Functions
void alphaChannelCheck (SDL_Surface *surface, bool &isOpaque, bool &hasSemiTransparency)
int getCurrentSkinX () const
int getCurrentSkinY () const
bool popTouch () const
void pushTouch (bool down) const
void recreateWindow (bool updateContent=true)
void updateCurrentSkin ()
Static Private Member Functions
static void updateTitle ()
Private Attributes
SkinInfo * currentSkin
bool isConsoleVisible
bool isSkinActive
bool isWindowBorderless
bool isWindowVisible
SkinInfo landscapeSkin
float msBetweenTicks
float msPassed
SkinInfo portraitSkin
FILE * printFile
char programPath [300]
bool windowDrag
int windowDragX
int windowDragY
Static Private Attributes
static bool _lastTouch = false
static int _numTouches = 0
static bool _touches [5] = { false, false, false, false, false }
static int32_t _x = 0
static int32_t _xMouse = 0
static int32_t _y = 0
static int32_t _yMouse = 0
static const char * customTitle = 0
static bool debugInfoEnabled = false
static bool flashInvalidatedRect = false
static uint16_t icon []
static int initialMouseX
static int initialMouseY
static int initialWindowX
static int initialWindowY
static bool isWindowBeingDragged = false
static uint8_t keyPressed = 0
static bool singleSteppingEnabled = false
static uint16_t singleSteppingSteps = 0
Additional Inherited Members
Public Types inherited from HAL
enum FrameRefreshStrategy { REFRESH_STRATEGY_DEFAULT , REFRESH_STRATEGY_OPTIM_SINGLE_BUFFER_TFT_CTRL , REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER }
enum RenderingMethod { SOFTWARE , HARDWARE }
Static Public Attributes inherited from HAL
static uint16_t DISPLAY_HEIGHT
The height of the LCD display in pixels.
static DisplayRotation DISPLAY_ROTATION
The rotation from display to framebuffer.
static uint16_t DISPLAY_WIDTH
The width of the LCD display in pixels.
static uint16_t FRAME_BUFFER_HEIGHT
The height of the framebuffer in pixels.
static uint16_t FRAME_BUFFER_WIDTH
The width of the framebuffer in pixels.
static bool USE_ANIMATION_STORAGE
Is animation storage enabled?
static bool USE_DOUBLE_BUFFERING
Is double buffering enabled?
Protected Attributes inherited from HAL
LCD * auxiliaryLCD
Auxiliary LCD class used to render Drawables into dynamic bitmaps.
ButtonController * buttonController
A reference to an optional ButtonController.
DMA_Interface & dma
A reference to the DMA interface.
uint8_t fingerSize
The radius of the finger in pixels.
uint16_t * frameBuffer0
Pointer to the first framebuffer.
uint16_t * frameBuffer1
Pointer to the second framebuffer.
uint16_t * frameBuffer2
Pointer to the optional third framebuffer used for animation storage.
FrameBufferAllocator * frameBufferAllocator
A reference to an optional FrameBufferAllocator.
bool frameBufferUpdatedThisFrame
True if something was drawn in the current frame.
Gestures gestures
Class for low-level interpretation of touch events.
LCD & lcdRef
A reference to the LCD.
bool lockDMAToPorch
Whether or not to lock DMA transfers with TFT porch signal.
MCUInstrumentation * mcuInstrumentation
A reference to an optional MCU instrumentation.
DisplayOrientation nativeDisplayOrientation
Contains the native display orientation. If desired orientation is different, apply rotation.
Rect partialFrameBufferRect
The region of the screen covered by the partial framebuffer.
FrameRefreshStrategy refreshStrategy
The selected display refresh strategy.
void(* taskDelayFunc)(uint16_t)
Pointer to a function that can delay GUI task for a number of milliseconds.
TouchController & touchController
A reference to the touch controller.
bool useAuxiliaryLCD
True if using another LCD than the hardware framebuffer.
Static Protected Attributes inherited from HAL
static bool isDrawing
True if currently in the process of rendering a screen.
Detailed Description
HAL implementation for the TouchGFX simulator. This particular simulator HAL implementation uses SDL2 to show the content of the framebuffer in a window.
See also
HAL
Constructor & Destructor Documentation
HALSDL2()
HALSDL2 (DMA_Interface & dma, LCD & lcd, TouchController & touchCtrl, uint16_t width, uint16_t height) inline
Initializes a new instance of the HALSDL2 class.
Parameters
[in] dma Reference to DMA interface.
[in] lcd Reference to the LCD.
[in] touchCtrl Reference to Touch Controller driver.
width Width of the display.
height Height of the display.
        : HAL(dma, lcd, touchCtrl, width, height),
          portraitSkin(),
          landscapeSkin(),
          currentSkin(0),
          isSkinActive(true),
          isWindowBorderless(false),
          isWindowVisible(true),
          isConsoleVisible(true),
          printFile(0),
          windowDrag(false)
    {
        setVsyncInterval(30.f); // Simulate 20Hz per default for backward compatibility
        updateCurrentSkin();
    }
References HALSDL2::setVsyncInterval(), and HALSDL2::updateCurrentSkin().
Member Function Documentation
alphaChannelCheck()
void alphaChannelCheck (SDL_Surface * surface, bool & isOpaque, bool & hasSemiTransparency) private
{
    isOpaque = true;
    hasSemiTransparency = false;
    if (surface->format->BitsPerPixel < 32 || surface->format->BytesPerPixel < 4)
    {
        return;
    }
    uint32_t alpha = surface->format->Amask;
    uint8_t* data = (uint8_t*)surface->pixels;
    for (int y = 0; y < surface->h; y++)
    {
        for (int x = 0; x < surface->w; x++)
        {
            uint32_t a = alpha & *(uint32_t*)(data + y * surface->pitch + x * 4);
            if (a == 0)
            {
                isOpaque = false;
                if (hasSemiTransparency)
                {
                    return;
                }
            }
            else if (a < alpha)
            {
                hasSemiTransparency = true;
                if (!isOpaque)
                {
                    return;
                }
            }
        }
    }
    return;
}
References SDL_PixelFormat::Amask, SDL_PixelFormat::BitsPerPixel, SDL_PixelFormat::BytesPerPixel, SDL_Surface::format, SDL_Surface::h, SDL_Surface::pitch, SDL_Surface::pixels, and SDL_Surface::w.
Referenced by HALSDL2::loadSkin().
configureInterrupts()
virtual void configureInterrupts () inline protected virtual
Configures the interrupts relevant for TouchGFX. This primarily entails setting the interrupt priorities for the DMA and LCD interrupts.
Implements HAL.
    {
    }
configureLCDInterrupt()
virtual void configureLCDInterrupt () inline protected virtual
Configures LCD interrupt.
    {
    }
copyScreenshotToClipboard()
void copyScreenshotToClipboard () virtual
Copies the screenshot to clipboard.
{
#ifdef __linux__
    touchgfx_printf("Copying to clipboard has not been implemented for Linux\n");
#else
    if (!OpenClipboard(NULL))
    {
        touchgfx_printf("Unable to OpenClipboard\n");
        return;
    }
    if (!EmptyClipboard())
    {
        touchgfx_printf("Unable to EmptyClipboard\n");
        return;
    }
    uint8_t* buffer24 = doRotate(scaleTo24bpp(getTFTFrameBuffer(), lcd().framebufferFormat()));
    DWORD size_pixels = DISPLAY_WIDTH * DISPLAY_HEIGHT * 3;
    HGLOBAL hMem = GlobalAlloc(GHND, sizeof(BITMAPV5HEADER) + size_pixels);
    if (!hMem)
    {
        touchgfx_printf("Error allocating memory for bitmap data");
        return;
    }
    BITMAPV5HEADER* hdr = (BITMAPV5HEADER*)GlobalLock(hMem);
    if (!hdr)
    {
        touchgfx_printf("Error locking memory for bitmap data");
        GlobalFree(hMem);
        return;
    }
    memset(hdr, 0, sizeof(BITMAPV5HEADER));
    hdr->bV5Size = sizeof(BITMAPV5HEADER);
    hdr->bV5Width = DISPLAY_WIDTH;
    hdr->bV5Height = -DISPLAY_HEIGHT;
    hdr->bV5Planes = 1;
    hdr->bV5BitCount = 24;
    hdr->bV5Compression = BI_RGB;
    hdr->bV5SizeImage = size_pixels;
    hdr->bV5Intent = LCS_GM_GRAPHICS;
    hdr->bV5CSType = 0x57696E20;
    CopyMemory(hdr + 1, buffer24, size_pixels);
    GlobalUnlock(hMem);
    if (!SetClipboardData(CF_DIBV5, hMem))
    {
        touchgfx_printf("Unable to SetClipboardData\n");
    }
    CloseClipboard();
#endif
}
References HAL::DISPLAY_HEIGHT, HAL::DISPLAY_WIDTH, HALSDL2::doRotate(), HALSDL2::getTFTFrameBuffer(), HAL::lcd(), touchgfx::memset(), NULL, HALSDL2::scaleTo24bpp(), and touchgfx_printf.
Referenced by HALSDL2::taskEntry().
disableInterrupts()
virtual void disableInterrupts () inline protected virtual
Disables the DMA and LCD interrupts.
Implements HAL.
    {
    }
doRotate()
uint8_t * doRotate (uint8_t * src) static
Rotates a framebuffer if the display is rotated.
Parameters
[in] src The framebuffer.
Returns
Null if it fails, else a pointer to an uint8_t.
{
    if (DISPLAY_ROTATION == rotate0 && DISPLAY_WIDTH == HALSDL2__FRAME_BUFFER_WIDTH)
    {
        // Height does not need to be exactly the same
        return src;
    }
    if (!tft_display24_allocated)
    {
        tft_display24 = new uint8_t[DISPLAY_WIDTH * DISPLAY_HEIGHT * 3]; // 24bpp, hence *3
        tft_display24_allocated = true;
    }
    switch (DISPLAY_ROTATION)
    {
    case rotate0:
        for (int16_t y = 0; y < DISPLAY_HEIGHT; y++)
        {
            for (int16_t x = 0; x < DISPLAY_WIDTH; x++)
            {
                for (int i = 0; i < 3; i++)
                {
                    tft_display24[(x + y * DISPLAY_WIDTH) * 3 + i] = src[(x + y * HALSDL2__FRAME_BUFFER_WIDTH) * 3 + i];
                }
            }
        }
        return tft_display24;
    case rotate90:
        for (int16_t dstY = 0; dstY < DISPLAY_HEIGHT; dstY++)
        {
            const int16_t srcX = dstY;
            for (int16_t dstX = 0; dstX < DISPLAY_WIDTH; dstX++)
            {
                const int16_t srcY = (DISPLAY_WIDTH - 1) - dstX;
                for (int i = 0; i < 3; i++)
                {
                    tft_display24[(dstX + dstY * DISPLAY_WIDTH) * 3 + i] = src[(srcX + srcY * HALSDL2__FRAME_BUFFER_WIDTH) * 3 + i];
                }
            }
        }
        return tft_display24;
    }
    return 0;
}
References HAL::DISPLAY_HEIGHT, HAL::DISPLAY_ROTATION, HAL::DISPLAY_WIDTH, touchgfx::HALSDL2__FRAME_BUFFER_WIDTH, touchgfx::rotate0, touchgfx::rotate90, touchgfx::tft_display24, and touchgfx::tft_display24_allocated.
Referenced by HALSDL2::copyScreenshotToClipboard(), HALSDL2::recreateWindow(), HALSDL2::setTFTFrameBuffer(), and HALSDL2::taskEntry().
doSampleTouch()
bool doSampleTouch (int32_t & x, int32_t & y) const
Samples the position of the mouse cursor.
Parameters
[out] x The x coordinate.
[out] y The y coordinate.
Returns
True if touch detected, false otherwise.
{
    x = _x - getCurrentSkinX();
    y = _y - getCurrentSkinY();
    if (DISPLAY_ROTATION == rotate90)
    {
        int32_t tmp = x;
        x = y;
        y = DISPLAY_WIDTH - tmp;
    }
    return popTouch();
}
References HALSDL2::_x, HALSDL2::_y, HAL::DISPLAY_ROTATION, HAL::DISPLAY_WIDTH, HALSDL2::getCurrentSkinX(), HALSDL2::getCurrentSkinY(), HALSDL2::popTouch(), and touchgfx::rotate90.
enableInterrupts()
virtual void enableInterrupts () inline protected virtual
Enables the DMA and LCD interrupts.
Implements HAL.
    {
    }
enableLCDControllerInterrupt()
virtual void enableLCDControllerInterrupt () inline protected virtual
Enables the LCD interrupt.
Implements HAL.
    {
    }
flushFrameBuffer() [1/2]
void flushFrameBuffer () virtual
This function is called whenever the framework has performed a complete draw.
On some platforms, a local framebuffer needs to be pushed to the display through a SPI channel or similar. Implement that functionality here. This function is called whenever the framework has performed a complete draw.
Reimplemented from HAL.
{
    Rect display(0, 0, DISPLAY_WIDTH, DISPLAY_HEIGHT);
    flushFrameBuffer(display);
}
References display, HAL::DISPLAY_HEIGHT, HAL::DISPLAY_WIDTH, and HALSDL2::flushFrameBuffer().
Referenced by HALSDL2::flushFrameBuffer().
flushFrameBuffer() [2/2]
void flushFrameBuffer (const Rect & rect) virtual
This function is called whenever the framework has performed a partial draw.
Parameters
rect The area of the screen that has been drawn, expressed in absolute coordinates.
Reimplemented from HAL.
{
    if (flashInvalidatedRect)
    {
        SDL_Rect flashRect;
        flashRect.x = rect.x + getCurrentSkinX();
        flashRect.y = rect.y + getCurrentSkinY();
        flashRect.w = rect.width;
        flashRect.h = rect.height;
        SDL_SetRenderDrawBlendMode(simulatorRenderer, SDL_BLENDMODE_BLEND);
        SDL_SetRenderDrawColor(simulatorRenderer, 0, 0, 0, 127);
        SDL_RenderFillRect(simulatorRenderer, &flashRect);
        SDL_RenderPresent(simulatorRenderer);
        SDL_SetRenderDrawBlendMode(simulatorRenderer, SDL_BLENDMODE_BLEND);
        SDL_SetRenderDrawColor(simulatorRenderer, 255, 255, 255, 127);
        SDL_RenderFillRect(simulatorRenderer, &flashRect);
        SDL_RenderPresent(simulatorRenderer);
    }
    if (getFrameRefreshStrategy() != REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER)
    {
        dirty.expandToFit(rect);
    }
    else
    {
        frameBufferAllocator->markBlockReadyForTransfer();
        // For testing during transfers.
        // renderLCD_FrameBufferToMemory(dirty, doRotate(scaleTo24bpp(tft, lcd().framebufferFormat())));
    }
    HAL::flushFrameBuffer(rect);
}
References touchgfx::dirty, HALSDL2::flashInvalidatedRect, HAL::flushFrameBuffer(), HAL::frameBufferAllocator, HALSDL2::getCurrentSkinX(), HALSDL2::getCurrentSkinY(), HAL::getFrameRefreshStrategy(), Rect::height, FrameBufferAllocator::markBlockReadyForTransfer(), HAL::REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER, SDL_BLENDMODE_BLEND, SDL_RenderFillRect(), SDL_RenderPresent(), SDL_SetRenderDrawBlendMode(), SDL_SetRenderDrawColor(), touchgfx::simulatorRenderer, Rect::width, Rect::x, and Rect::y.
getArgv()
char ** getArgv (int * argc) static
Gets the argc and argv for a Windows program.
Parameters
[in,out] argc Pointer to where to store number of arguments.
Returns
The argv list of arguments.
{
    LPWSTR cmdline = GetCommandLineW();
    LPWSTR* argvw = CommandLineToArgvW(cmdline, argc);
    char** argv = new char*[*argc];
    for (int i = 0; i < *argc; i++)
    {
        char buffer[1000];
        size_t numChars = wcslen(argvw[0]) + 1;
        wcstombs_s(&numChars, buffer, sizeof(buffer), argvw[i], numChars);
        argv[i] = new char[numChars + 1];
        memcpy_s(argv[i], numChars, buffer, numChars);
        argv[i][numChars] = '\0';
    }
    return argv;
}
Referenced by WinMain().
getConsoleVisible()
bool getConsoleVisible () const inline
Is console window visible?
Returns
True if it is visible, false if it is hidden.
See also
setConsoleVisible, getWindowVisible
    {
        return isConsoleVisible;
    }
References HALSDL2::isConsoleVisible.
getCurrentSkinX()
int getCurrentSkinX () const private
{
    return (isSkinActive && currentSkin != 0 && currentSkin->surface != 0) ? currentSkin->offsetX : 0;
}
References HALSDL2::currentSkin, HALSDL2::isSkinActive, HALSDL2::SkinInfo::offsetX, and HALSDL2::SkinInfo::surface.
Referenced by HALSDL2::doSampleTouch(), HALSDL2::flushFrameBuffer(), and HALSDL2::renderLCD_FrameBufferToMemory().
getCurrentSkinY()
int getCurrentSkinY () const private
{
    return (isSkinActive && currentSkin != 0 && currentSkin->surface != 0) ? currentSkin->offsetY : 0;
}
References HALSDL2::currentSkin, HALSDL2::isSkinActive, HALSDL2::SkinInfo::offsetY, and HALSDL2::SkinInfo::surface.
Referenced by HALSDL2::doSampleTouch(), HALSDL2::flushFrameBuffer(), and HALSDL2::renderLCD_FrameBufferToMemory().
getPrintFile()
FILE * getPrintFile () const inline
Get file handle to output file (if set).
Returns
A file handle to the file where output is copied to.
See also
printToFile
    {
        return printFile;
    }
References HALSDL2::printFile.
getTFTFrameBuffer()
uint16_t * getTFTFrameBuffer () const protected virtual
Gets TFT framebuffer.
Returns
null if it fails, else the TFT framebuffer.
Implements HAL.
{
    return tft;
}
References touchgfx::tft.
Referenced by HALSDL2::copyScreenshotToClipboard(), HALSDL2::recreateWindow(), and HALSDL2::taskEntry().
getWindowTitle()
const char * getWindowTitle () static
Gets window title.
Returns
null "TouchGFX simulator" unless set to something else using setWindowTitle().
See also
setWindowTitle
{
    if (customTitle != 0)
    {
        return customTitle;
    }
    static char title[100];
    sprintf_s(title, 100, "TouchGFX simulator v%d.%d.%d", TOUCHGFX_VERSION_MAJOR, TOUCHGFX_VERSION_MINOR, TOUCHGFX_VERSION_PATCH);
    return title;
}
References HALSDL2::customTitle, TOUCHGFX_VERSION_MAJOR, TOUCHGFX_VERSION_MINOR, and TOUCHGFX_VERSION_PATCH.
Referenced by HALSDL2::recreateWindow(), and HALSDL2::updateTitle().
getWindowVisible()
bool getWindowVisible () const inline
Is the window visible?
Returns
True if it is visible, false if it is hidden.
See also
setWindowVisible, getConsoleVisible
    {
        return isWindowVisible;
    }
References HALSDL2::isWindowVisible.
Referenced by HALSDL2::sdl_init().
isSingleStepping()
bool isSingleStepping () static
Is single stepping.
Returns
True if single stepping, false if not.
See also
setSingleStepping
{
    return singleSteppingEnabled;
}
References HALSDL2::singleSteppingEnabled.
Referenced by HALSDL2::updateTitle().
loadSkin()
void loadSkin (DisplayOrientation orientation, int x, int y)
Loads a skin for a given display orientation that will be rendered in the simulator window with the the TouchGFX framebuffer placed inside the bitmap at the given coordinates. Different bitmaps can be loaded in landscape and portrait mode. If the provided bitmap cannot be loaded, the TouchGFX framebuffer will be displayed as normal. If the png files contain areas with alpha < 255, this will be used to create a shaped window.
Parameters
orientation The orientation.
x The x coordinate.
y The y coordinate.
Note
The skins must be named "portrait.png" and "landscape.png" and placed inside the "simulator/" folder. The build process of the simulator will automatically copy the skins to the folder where the executable simulator is generated.
When as skin is set, the entire framebuffer is rendered through SDL whenever there is a change. Without a skin, only the areas with changes is rendered through SDL.
{
    char path[320];
    assert(sdl_initialized && "Please call sdl_init() before loading a skin");
    SkinInfo* skin;
    const char* skinname;
    if (orientation == ORIENTATION_PORTRAIT)
    {
        skin = &portraitSkin;
        skinname = "portrait.png";
    }
    else
    {
        skin = &landscapeSkin;
        skinname = "landscape.png";
    }
    skin->offsetX = 0;
    skin->offsetY = 0;
    skin->surface = IMG_Load(localFileName(path, 320, skinname));
    if (skin->surface == 0)
    {
        touchgfx_printf("Unable to load skin image from %s\n", path);
    }
    else
    {
        skin->offsetX = x;
        skin->offsetY = y;
        alphaChannelCheck(skin->surface, skin->isOpaque, skin->hasSemiTransparency);
    }
    if (getDisplayOrientation() == orientation)
    {
        updateCurrentSkin();
        recreateWindow(false);
    }
}
References HALSDL2::alphaChannelCheck(), HAL::getDisplayOrientation(), IMG_Load(), HALSDL2::landscapeSkin, HALSDL2::localFileName(), touchgfx::ORIENTATION_PORTRAIT, HALSDL2::portraitSkin, HALSDL2::recreateWindow(), touchgfx::sdl_initialized, touchgfx_printf, and HALSDL2::updateCurrentSkin().
localFileName()
char * localFileName (char * buffer, size_t buffer_size, const char * filename)
Generate name of file placed next to the simulator.
Parameters
[in] buffer If the buffer to fill with the local filename. Must be at least 300+length of filename parameter.
buffer_size The size of the buffer in bytes.
[in] filename The filename relative to the simulator executable.
Returns
The filled buffer.
{
    sprintf_s(buffer, buffer_size, "%s%s", programPath, filename);
    return buffer;
}
References filename, and HALSDL2::programPath.
Referenced by HALSDL2::loadSkin().
performDisplayOrientationChange()
void performDisplayOrientationChange () protected virtual
Perform the actual display orientation change.
Reimplemented from HAL.
{
    HAL::performDisplayOrientationChange();
    updateCurrentSkin();
    recreateWindow(false);
}
References HAL::performDisplayOrientationChange(), HALSDL2::recreateWindow(), and HALSDL2::updateCurrentSkin().
popTouch()
bool popTouch () const private
{
    if (_numTouches < 1)
    {
        // Keep returning the same state
        return _lastTouch;
    }
    // Get first item in queue
    _lastTouch = _touches[0];
    // Move items in queue
    for (int i = 0; i < 4; i++)
    {
        _touches[i] = _touches[i + 1];
    }
    _numTouches--;
    return _lastTouch;
}
References HALSDL2::_lastTouch, HALSDL2::_numTouches, and HALSDL2::_touches.
Referenced by HALSDL2::doSampleTouch().
printToFile()
bool printToFile (const char * filename)
Also write touchgfx_printf() to a file. The file will be generated (no appended to).
Parameters
filename The name of the file to write to (or null to stop writing to a file).
Returns
True if the operation succeeds, false otherwise.
{
    if (printFile)
    {
        fclose(printFile);
        printFile = 0;
    }
    if (filename)
    {
#ifdef __GNUC_
        printFile = fopen(filename, "w");
        return printFile != 0;
#else
        return fopen_s(&printFile, filename, "w") == 0;
#endif
    }
    return true;
}
References filename, and HALSDL2::printFile.
pushTouch()
void pushTouch (bool down) const private
{
    if (_numTouches == 0)
    {
        // Save touch
        _touches[_numTouches++] = down;
    }
    else if ((_numTouches < 4) && (_touches[_numTouches - 1] ^ down))
    {
        // Only save touch if is different from the last one recorded
        _touches[_numTouches++] = down;
    }
}
References HALSDL2::_numTouches, and HALSDL2::_touches.
Referenced by HALSDL2::taskEntry().
recreateWindow()
void recreateWindow (bool updateContent = true) private
{
#if defined(WIN32) || defined(_WIN32)
    mainThreadHandle = GetCurrentThreadId();
#endif
    int windowX = SDL_WINDOWPOS_UNDEFINED;
    int windowY = SDL_WINDOWPOS_UNDEFINED;
    if (simulatorWindow != NULL)
    {
        // Save previous coordinates
        SDL_GetWindowPosition(simulatorWindow, &windowX, &windowY);
        SDL_DestroyRenderer(simulatorRenderer);
        SDL_DestroyWindow(simulatorWindow);
    }
    int width = DISPLAY_WIDTH;
    int height = DISPLAY_HEIGHT;
    if (isSkinActive && currentSkin != 0)
    {
        width = currentSkin->surface->w;
        height = currentSkin->surface->h;
    }
    if (isSkinActive && currentSkin != 0)
    {
        simulatorWindow = SDL_CreateShapedWindow(getWindowTitle(), windowX, windowY, width, height, SDL_WINDOW_BORDERLESS | (isWindowVisible ? 0 : SDL_WINDOW_HIDDEN));
        SDL_WindowShapeMode mode;
        mode.mode = ShapeModeBinarizeAlpha;
        mode.parameters.binarizationCutoff = 255;
        SDL_SetWindowShape(simulatorWindow, currentSkin->surface, &mode);
        SDL_SetWindowSize(simulatorWindow, width, height);
        SDL_SetWindowPosition(simulatorWindow, windowX, windowY);
    }
    else
    {
        simulatorWindow = SDL_CreateWindow(getWindowTitle(), windowX, windowY, width, height, (isWindowBorderless ? SDL_WINDOW_BORDERLESS : 0) | (isWindowVisible ? 0 : SDL_WINDOW_HIDDEN));
    }
    simulatorRenderer = SDL_CreateRenderer(simulatorWindow, -1, 0);
    SDL_SetRenderDrawBlendMode(simulatorRenderer, SDL_BLENDMODE_ADD);
    if (updateContent)
    {
        Rect display(0, 0, DISPLAY_WIDTH, DISPLAY_HEIGHT);
        renderLCD_FrameBufferToMemory(display, doRotate(scaleTo24bpp(getTFTFrameBuffer(), lcd().framebufferFormat())));
    }
    updateTitle();
    // Re-add window icon in case
    SDL_Surface* iconSurface = SDL_CreateRGBSurfaceFrom(icon, 32, 32, 16, 32 * 2, 0xf800, 0x07e0, 0x001f, 0x0000);
    SDL_SetWindowIcon(simulatorWindow, iconSurface);
    SDL_FreeSurface(iconSurface);
}
References HALSDL2::currentSkin, display, HAL::DISPLAY_HEIGHT, HAL::DISPLAY_WIDTH, HALSDL2::doRotate(), HALSDL2::getTFTFrameBuffer(), HALSDL2::getWindowTitle(), SDL_Surface::h, HALSDL2::icon, HALSDL2::isSkinActive, HALSDL2::isWindowBorderless, HALSDL2::isWindowVisible, HAL::lcd(), SDL_WindowShapeMode::mode, NULL, HALSDL2::renderLCD_FrameBufferToMemory(), HALSDL2::scaleTo24bpp(), SDL_BLENDMODE_ADD, SDL_CreateRenderer(), SDL_CreateRGBSurfaceFrom(), SDL_CreateShapedWindow(), SDL_CreateWindow(), SDL_DestroyRenderer(), SDL_DestroyWindow(), SDL_FreeSurface(), SDL_GetWindowPosition(), SDL_SetRenderDrawBlendMode(), SDL_SetWindowIcon(), SDL_SetWindowPosition(), SDL_SetWindowShape(), SDL_SetWindowSize(), SDL_WINDOW_BORDERLESS, SDL_WINDOW_HIDDEN, SDL_WINDOWPOS_UNDEFINED, ShapeModeBinarizeAlpha, touchgfx::simulatorRenderer, touchgfx::simulatorWindow, HALSDL2::SkinInfo::surface, HALSDL2::updateTitle(), and SDL_Surface::w.
Referenced by HALSDL2::loadSkin(), HALSDL2::performDisplayOrientationChange(), HALSDL2::sdl_init(), HALSDL2::setConsoleVisible(), HALSDL2::setWindowVisible(), and HALSDL2::taskEntry().
renderLCD_FrameBufferToMemory()
void renderLCD_FrameBufferToMemory (const Rect & _rectToUpdate, uint8_t * frameBuffer) protected virtual
Update framebuffer using an SDL Surface.
Parameters
_rectToUpdate Area to update.
[in] frameBuffer Target framebuffer.
{
    Rect rectToUpdate = _rectToUpdate;
    if (isSkinActive && currentSkin != 0 && (currentSkin->isOpaque || currentSkin->hasSemiTransparency))
    {
        // Opaque skin must be drawn before the framebuffer
        SDL_Texture* currentSkinTexture = SDL_CreateTextureFromSurface(simulatorRenderer, currentSkin->surface);
        SDL_RenderClear(simulatorRenderer);
        SDL_RenderCopy(simulatorRenderer, currentSkinTexture, NULL, NULL);
        // The skin will overwrite everything, so expand the rect to the entire framebuffer
        rectToUpdate.x = 0;
        rectToUpdate.y = 0;
        rectToUpdate.width = DISPLAY_WIDTH;
        rectToUpdate.height = DISPLAY_HEIGHT;
        SDL_DestroyTexture(currentSkinTexture);
    }
    if (flashInvalidatedRect)
    {
        SDL_Delay(1);
    }
    // Now draw the requested area
    SDL_Surface* framebufferSurface = SDL_CreateRGBSurfaceFrom((void*)frameBuffer, DISPLAY_WIDTH, DISPLAY_HEIGHT, 24, 3 * DISPLAY_WIDTH, 0, 0, 0, 0);
    SDL_Texture* framebufferTexture = SDL_CreateTextureFromSurface(simulatorRenderer, framebufferSurface);
    SDL_Rect srcRect;
    srcRect.x = rectToUpdate.x;
    srcRect.y = rectToUpdate.y;
    srcRect.h = rectToUpdate.height;
    srcRect.w = rectToUpdate.width;
    SDL_Rect dstRect = srcRect;
    dstRect.x = rectToUpdate.x + getCurrentSkinX();
    dstRect.y = rectToUpdate.y + getCurrentSkinY();
    SDL_RenderCopy(simulatorRenderer, framebufferTexture, &srcRect, &dstRect);
    if (isSkinActive && currentSkin != 0 && !(currentSkin->isOpaque || currentSkin->hasSemiTransparency))
    {
        // Non-opaque skin must be drawn last
        SDL_Texture* currentSkinTexture = SDL_CreateTextureFromSurface(simulatorRenderer, currentSkin->surface);
        SDL_RenderCopy(simulatorRenderer, currentSkinTexture, NULL, NULL);
        SDL_DestroyTexture(currentSkinTexture);
    }
    SDL_RenderPresent(simulatorRenderer);
    SDL_DestroyTexture(framebufferTexture);
    SDL_FreeSurface(framebufferSurface);
}
References HALSDL2::currentSkin, HAL::DISPLAY_HEIGHT, HAL::DISPLAY_WIDTH, HALSDL2::flashInvalidatedRect, HALSDL2::getCurrentSkinX(), HALSDL2::getCurrentSkinY(), HALSDL2::SkinInfo::hasSemiTransparency, HALSDL2::SkinInfo::isOpaque, HALSDL2::isSkinActive, NULL, SDL_CreateRGBSurfaceFrom(), SDL_CreateTextureFromSurface(), SDL_Delay(), SDL_DestroyTexture(), SDL_FreeSurface(), SDL_RenderClear(), SDL_RenderCopy(), SDL_RenderPresent(), touchgfx::simulatorRenderer, and HALSDL2::SkinInfo::surface.
Referenced by HALSDL2::recreateWindow(), HALSDL2::setTFTFrameBuffer(), and HALSDL2::taskEntry().
sampleKey()
bool sampleKey (uint8_t & key) virtual
Sample key event from keyboard.
Parameters
[out] key Output parameter that will be set to the key value if a key press was detected.
Returns
True if a key press was detected and the "key" parameter is set to a value.
Reimplemented from HAL.
{
    if (keyPressed)
    {
        key = keyPressed;
        keyPressed = 0;
        return true;
    }
    return false;
}
References HALSDL2::keyPressed.
saveNextScreenshots()
void saveNextScreenshots (int n) virtual
Copy the next N screenshots to disk. On each screen update, the new screen is saved to disk.
Parameters
n Number of screenshots to save. These are added to any ongoing amount of screenshots in queue.
{
    screenshotcount += n;
}
References touchgfx::screenshotcount.
Referenced by HALSDL2::taskEntry().
saveScreenshot() [1/2]
void saveScreenshot ()
Saves a screenshot to the default folder and default filename.
{
    static char lastBaseName[20] = { 0 };
    static int counter = 0;
    // current date/time based on current system
    time_t t = time(0);
    tm localt;
    localtime_s(&localt, &t);
    char baseName[20]; // "img_YYYYMMDD_HHMMSS" is 19 long
    sprintf_s(baseName, 20, "img_%04d%02d%02d_%02d%02d%02d",
              1900 + localt.tm_year, localt.tm_mon + 1, localt.tm_mday,
              localt.tm_hour, localt.tm_min, localt.tm_sec);
    char fileName[100];
    if (strncmp(baseName, lastBaseName, sizeof(baseName)) == 0)
    {
        // Same as previous time stamp. Add counter.
        counter++;
        sprintf_s(fileName, sizeof(fileName), "%s_%d.bmp", baseName, counter);
    }
    else
    {
        // New time stamp. Save it and clear counter.
        strncpy_s(lastBaseName, sizeof(lastBaseName), baseName, sizeof(baseName));
        counter = 0;
        sprintf_s(fileName, sizeof(fileName), "%s.bmp", baseName);
    }
    saveScreenshot(0, fileName);
}
References HALSDL2::saveScreenshot().
Referenced by HALSDL2::saveScreenshot(), and HALSDL2::taskEntry().
saveScreenshot() [2/2]
void saveScreenshot (char * folder, char * filename) virtual
Saves a screenshot.
Parameters
[in] folder Folder name to place the screenshot in.
[in] filename Filename to save the screenshot to.
{
    const char* dir = "screenshots";
#if defined(WIN32) || defined(_WIN32)
    CreateDirectory(dir, 0);
#elif defined(__GNUC__)
    mkdir(dir, S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH);
#endif
    char fullPathAndName[500];
    if (folder)
    {
        sprintf_s(fullPathAndName, sizeof(fullPathAndName), "%s/%s", dir, folder);
#if defined(WIN32) || defined(_WIN32)
        CreateDirectory(fullPathAndName, 0);
#elif defined(__GNUC__)
        mkdir(fullPathAndName, S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH);
#endif
        sprintf_s(fullPathAndName, sizeof(fullPathAndName), "%s/%s/%s", dir, folder, filename);
    }
    else
    {
        sprintf_s(fullPathAndName, sizeof(fullPathAndName), "%s/%s", dir, filename);
    }
    int width;
    int height;
    if (SDL_GetRendererOutputSize(simulatorRenderer, &width, &height) == 0)
    {
        // Create an empty surface that will be used to create the screenshot bmp file
        SDL_Surface* windowSurface = SDL_CreateRGBSurface(0, width, height, 32, 0x00ff0000, 0x0000ff00, 0x000000ff, 0xff000000);
        if (windowSurface != 0)
        {
            // Read the pixels from the current render target and save them onto the surface
            SDL_RenderReadPixels(simulatorRenderer, NULL, SDL_GetWindowPixelFormat(simulatorWindow), windowSurface->pixels, windowSurface->pitch);
            // Create the bmp screenshot file
            SDL_SaveBMP(windowSurface, fullPathAndName);
            // Destroy the screenshot surface
            SDL_FreeSurface(windowSurface);
        }
    }
}
References dir, filename, NULL, SDL_CreateRGBSurface(), SDL_FreeSurface(), SDL_GetRendererOutputSize(), SDL_GetWindowPixelFormat(), SDL_RenderReadPixels(), SDL_SaveBMP, touchgfx::simulatorRenderer, and touchgfx::simulatorWindow.
scaleTo24bpp()
uint8_t * scaleTo24bpp (uint16_t * src, Bitmap::BitmapFormat format) static
Scale framebuffer to 24bpp. The format of the framebuffer (src) is given in parameter format. The result is placed in the pre-allocated memory pointed to by parameter dst. If the framebuffer is in format Bitmap::RGB888, parameter dst is not used and the parameter src is simply returned.
Parameters
[in] src The framebuffer.
format Describes the format of the framebuffer (lcd().framebufferFormat()).
Returns
Null if it fails, else a pointer to an uint8_t.
{
    if (format == Bitmap::RGB888)
    {
        if (tft_framebuffer24_allocated)
        {
            delete[] tft_framebuffer24;
            tft_framebuffer24_allocated = false;
        }
        tft_framebuffer24 = reinterpret_cast<uint8_t*>(src);
        return tft_framebuffer24;
    }
    if (!tft_framebuffer24_allocated)
    {
        tft_framebuffer24 = new uint8_t[HALSDL2__FRAME_BUFFER_WIDTH * HALSDL2__FRAME_BUFFER_HEIGHT * 3];
        tft_framebuffer24_allocated = true;
    }
    uint8_t* buffer = reinterpret_cast<uint8_t*>(src);
    uint8_t* dst = tft_framebuffer24;
    switch (format)
    {
    case Bitmap::BW:
        for (int srcY = 0; srcY < HALSDL2__FRAME_BUFFER_HEIGHT; srcY++)
        {
            for (int srcXbyte = 0; srcXbyte < HALSDL2__FRAME_BUFFER_WIDTH / 8; srcXbyte++)
            {
                uint8_t bufbyte = *buffer++;
                for (int srcXpixel = 0; srcXpixel < 8; srcXpixel++)
                {
                    uint8_t pixel = ((bufbyte << srcXpixel) & 0xFF) >> 7;
                    uint8_t pixelByte = pixel * 0xFF;
                    *dst++ = pixelByte;
                    *dst++ = pixelByte;
                    *dst++ = pixelByte;
                }
            }
            // Check if there is a partial byte left
            if (HALSDL2__FRAME_BUFFER_WIDTH % 8 != 0)
            {
                uint8_t bufbyte = *buffer++;
                for (int srcXpixel = 0; srcXpixel < HALSDL2__FRAME_BUFFER_WIDTH % 8; srcXpixel++)
                {
                    uint8_t pixel = ((bufbyte << srcXpixel) & 0xFF) >> 7;
                    uint8_t pixelByte = pixel * 0xFF;
                    *dst++ = pixelByte;
                    *dst++ = pixelByte;
                    *dst++ = pixelByte;
                }
            }
        }
        break;
    case Bitmap::GRAY2:
        for (int srcY = 0; srcY < HALSDL2__FRAME_BUFFER_HEIGHT; srcY++)
        {
            for (int srcXbyte = 0; srcXbyte < (HALSDL2__FRAME_BUFFER_WIDTH * 2) / 8; srcXbyte++)
            {
                uint8_t bufbyte = *buffer++;
                for (int srcXpixel = 0; srcXpixel < 4; srcXpixel++)
                {
                    uint8_t pixel = bufbyte & 3;
                    bufbyte >>= 2;
                    uint8_t pixelByte = pixel * 0x55;
                    *dst++ = pixelByte;
                    *dst++ = pixelByte;
                    *dst++ = pixelByte;
                }
            }
            // Check if there is a partial byte left
            if ((HALSDL2__FRAME_BUFFER_WIDTH * 2) % 8 != 0)
            {
                uint8_t bufbyte = *buffer++;
                for (int srcXpixel = 0; srcXpixel < ((HALSDL2__FRAME_BUFFER_WIDTH * 2) % 8) / 2; srcXpixel++)
                {
                    uint8_t pixel = bufbyte & 3;
                    bufbyte >>= 2;
                    uint8_t pixelByte = pixel * 0x55;
                    *dst++ = pixelByte;
                    *dst++ = pixelByte;
                    *dst++ = pixelByte;
                }
            }
        }
        break;
    case Bitmap::GRAY4:
        for (int srcY = 0; srcY < HALSDL2__FRAME_BUFFER_HEIGHT; srcY++)
        {
            for (int srcXbyte = 0; srcXbyte < (HALSDL2__FRAME_BUFFER_WIDTH * 4) / 8; srcXbyte++)
            {
                uint8_t bufbyte = *buffer++;
                for (int srcXpixel = 0; srcXpixel < 2; srcXpixel++)
                {
                    uint8_t pixel = bufbyte & 0xF;
                    bufbyte >>= 4;
                    uint8_t pixelByte = pixel * 0x11;
                    *dst++ = pixelByte;
                    *dst++ = pixelByte;
                    *dst++ = pixelByte;
                }
            }
            // Check if there is a partial byte left
            if ((HALSDL2__FRAME_BUFFER_WIDTH * 4) % 8 != 0)
            {
                uint8_t bufbyte = *buffer++;
                for (int srcXpixel = 0; srcXpixel < ((HALSDL2__FRAME_BUFFER_WIDTH * 4) % 8) / 4; srcXpixel++)
                {
                    uint8_t pixel = bufbyte & 0xF;
                    bufbyte >>= 4;
                    uint8_t pixelByte = pixel * 0x11;
                    *dst++ = pixelByte;
                    *dst++ = pixelByte;
                    *dst++ = pixelByte;
                }
            }
        }
        break;
    case Bitmap::ARGB2222:
        for (int srcY = 0; srcY < HALSDL2__FRAME_BUFFER_HEIGHT; srcY++)
        {
            for (int srcX = 0; srcX < HALSDL2__FRAME_BUFFER_WIDTH; srcX++)
            {
                uint16_t bufword = *buffer++;
                uint8_t r = (bufword >> 4) & 0x3;
                uint8_t g = (bufword >> 2) & 0x3;
                uint8_t b = bufword & 0x3;
                *dst++ = b * 0x55;
                *dst++ = g * 0x55;
                *dst++ = r * 0x55;
            }
        }
        break;
    case Bitmap::ABGR2222:
        for (int srcY = 0; srcY < HALSDL2__FRAME_BUFFER_HEIGHT; srcY++)
        {
            for (int srcX = 0; srcX < HALSDL2__FRAME_BUFFER_WIDTH; srcX++)
            {
                uint16_t bufword = *buffer++;
                uint8_t r = bufword & 0x3;
                uint8_t g = (bufword >> 2) & 0x3;
                uint8_t b = (bufword >> 4) & 0x3;
                *dst++ = b * 0x55;
                *dst++ = g * 0x55;
                *dst++ = r * 0x55;
            }
        }
        break;
    case Bitmap::RGBA2222:
        for (int srcY = 0; srcY < HALSDL2__FRAME_BUFFER_HEIGHT; srcY++)
        {
            for (int srcX = 0; srcX < HALSDL2__FRAME_BUFFER_WIDTH; srcX++)
            {
                uint16_t bufword = *buffer++;
                uint8_t r = (bufword >> 6) & 0x3;
                uint8_t g = (bufword >> 4) & 0x3;
                uint8_t b = (bufword >> 2) & 0x3;
                *dst++ = b * 0x55;
                *dst++ = g * 0x55;
                *dst++ = r * 0x55;
            }
        }
        break;
    case Bitmap::BGRA2222:
        for (int srcY = 0; srcY < HALSDL2__FRAME_BUFFER_HEIGHT; srcY++)
        {
            for (int srcX = 0; srcX < HALSDL2__FRAME_BUFFER_WIDTH; srcX++)
            {
                uint16_t bufword = *buffer++;
                uint8_t r = (bufword >> 2) & 0x3;
                uint8_t g = (bufword >> 4) & 0x3;
                uint8_t b = (bufword >> 6) & 0x3;
                *dst++ = b * 0x55;
                *dst++ = g * 0x55;
                *dst++ = r * 0x55;
            }
        }
        break;
    case Bitmap::RGB565:
        for (int srcY = 0; srcY < HALSDL2__FRAME_BUFFER_HEIGHT; srcY++)
        {
            for (int srcX = 0; srcX < HALSDL2__FRAME_BUFFER_WIDTH; srcX++)
            {
                uint16_t bufword = *src++;
                *dst++ = Color::getBlueFromRGB565(bufword);
                *dst++ = Color::getGreenFromRGB565(bufword);
                *dst++ = Color::getRedFromRGB565(bufword);
            }
        }
        break;
    case Bitmap::ARGB8888:
        {
            uint32_t* src32 = reinterpret_cast<uint32_t*>(src);
            for (int srcY = 0; srcY < HALSDL2__FRAME_BUFFER_HEIGHT; srcY++)
            {
                for (int srcX = 0; srcX < HALSDL2__FRAME_BUFFER_WIDTH; srcX++)
                {
                    uint32_t pixel = *src32++;
                    uint8_t b = pixel & 0xFF;
                    uint8_t g = (pixel >> 8) & 0xFF;
                    uint8_t r = (pixel >> 16) & 0xFF;
                    *dst++ = b;
                    *dst++ = g;
                    *dst++ = r;
                }
            }
        }
        break;
    case Bitmap::BW_RLE:
    case Bitmap::RGB888:
    case Bitmap::L8:
    default:
        assert(0 && "unsupported screen depth");
        break;
    }
    return tft_framebuffer24;
}
References Bitmap::ABGR2222, Bitmap::ARGB2222, Bitmap::ARGB8888, Bitmap::BGRA2222, Bitmap::BW, Bitmap::BW_RLE, Color::getBlueFromRGB565(), Color::getGreenFromRGB565(), Color::getRedFromRGB565(), Bitmap::GRAY2, Bitmap::GRAY4, touchgfx::HALSDL2__FRAME_BUFFER_HEIGHT, touchgfx::HALSDL2__FRAME_BUFFER_WIDTH, Bitmap::L8, Bitmap::RGB565, Bitmap::RGB888, Bitmap::RGBA2222, touchgfx::tft_framebuffer24, and touchgfx::tft_framebuffer24_allocated.
Referenced by HALSDL2::copyScreenshotToClipboard(), HALSDL2::recreateWindow(), HALSDL2::setTFTFrameBuffer(), and HALSDL2::taskEntry().
sdl_init()
bool sdl_init (int argcount, char ** args) virtual
Initializes SDL.
Parameters
argcount Number of arguments.
[in] args Arguments.
Returns
True if init went well, false otherwise.
{
    if (sdl_initialized)
    {
        touchgfx_printf("SDL already initialized\n");
        return false;
    }
#if defined(SIMULATOR) && !defined(__linux__)
    if (getWindowVisible())
    {
        // Create window and hide it ASAP to prevent problems with files being closed when stdio is redirected to the new console
        touchgfx_enable_stdio();        // This will create a console window
        HWND hwnd = GetConsoleWindow(); // Get a handle to the console window
        if (hwnd)                       // If the console exists, quickly hide it
        {
            ShowWindow(hwnd, SW_HIDE);
        }
    }
#endif
    strncpy_s(programPath, sizeof(programPath), args[0], strlen(args[0]));
    char* filenamePos = strrchr(programPath, '/');
    if (!filenamePos)
    {
        filenamePos = strrchr(programPath, '\\');
    }
    if (filenamePos)
    {
        filenamePos++; // Skip path separator
    }
    else
    {
        filenamePos = programPath;
    }
    *filenamePos = '\0';
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER) < 0)
    {
        touchgfx_printf("Unable to init SDL: %s\n", SDL_GetError());
        return false;
    }
    // setFrameBufferSize will respect these, not set them. These can be overwritten in main()
    USE_ANIMATION_STORAGE = true;
    USE_DOUBLE_BUFFERING = true;
    setFrameBufferSize(FRAME_BUFFER_WIDTH, FRAME_BUFFER_HEIGHT);
    recreateWindow(false);
    if (simulatorWindow == NULL)
    {
        touchgfx_printf("Unable to set video mode: %s\n", SDL_GetError());
        return false;
    }
    sdl_initialized = true;
    atexit(sdlCleanup2);
    SDL_Surface* iconSurface = SDL_CreateRGBSurfaceFrom(icon, 32, 32, 16, 32 * 2, 0xf800, 0x07e0, 0x001f, 0x0000);
    SDL_SetWindowIcon(simulatorWindow, iconSurface);
    SDL_FreeSurface(iconSurface);
    lockDMAToFrontPorch(false);
    if (getFrameRefreshStrategy() == REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER)
    {
        assert(getFrameBufferAllocator() && "Framebuffer allocator must be provided when using REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER");
        sem_transfer_ready = SDL_CreateSemaphore(0);
        sem_transfer_done = SDL_CreateSemaphore(0);
        SDL_Thread* transfer_thread = SDL_CreateThread(transferThreadFunc, "FB TransferThread", (void*)NULL);
        assert(transfer_thread);
    }
    return true;
}
References HAL::FRAME_BUFFER_HEIGHT, HAL::FRAME_BUFFER_WIDTH, HAL::getFrameBufferAllocator(), HAL::getFrameRefreshStrategy(), HALSDL2::getWindowVisible(), HALSDL2::icon, HAL::lockDMAToFrontPorch(), NULL, HALSDL2::programPath, HALSDL2::recreateWindow(), HAL::REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER, SDL_CreateRGBSurfaceFrom(), SDL_CreateSemaphore(), SDL_CreateThread(), SDL_FreeSurface(), SDL_GetError(), SDL_Init(), SDL_INIT_TIMER, SDL_INIT_VIDEO, touchgfx::sdl_initialized, SDL_SetWindowIcon(), touchgfx::sdlCleanup2(), touchgfx::sem_transfer_done, touchgfx::sem_transfer_ready, HALSDL2::setFrameBufferSize(), touchgfx::simulatorWindow, touchgfx_enable_stdio, touchgfx_printf, touchgfx::transferThreadFunc(), HAL::USE_ANIMATION_STORAGE, and HAL::USE_DOUBLE_BUFFERING.
setConsoleVisible()
void setConsoleVisible (bool visible, bool redrawWindow = true) inline
Change visibility of console window (hidden vs. shown).
Parameters
visible Should the window be visible?
redrawWindow (Optional) Should the window be redrawn? Default is true.
See also
setWindowVisible, getConsoleVisible
    {
        isConsoleVisible = visible;
        if (redrawWindow)
        {
            recreateWindow();
            touchgfx::simulator_enable_stdio();
        }
    }
References HALSDL2::isConsoleVisible, HALSDL2::recreateWindow(), and touchgfx::simulator_enable_stdio().
setFlashInvalidatedAreas()
void setFlashInvalidatedAreas (bool flash = true) virtual
Flash invalidated areas on/off. The area that needs to be redrawn is flashed in grey to help identify performance bottle necks.
Parameters
flash (Optional) True to flash the screen when updating.
{
    flashInvalidatedRect = flash;
    updateTitle();
}
References HALSDL2::flashInvalidatedRect, and HALSDL2::updateTitle().
Referenced by HALSDL2::taskEntry().
setFrameBufferSize()
void setFrameBufferSize (uint16_t width, uint16_t height) virtual
Sets framebuffer size. By default the display size and the framebuffer size are the same, but in some hardware configurations, the hardware may have a width of e.g. 832 pixels even though the display is only 800 pixels wide. First set the display width and height using touchgfx_generic_init() and the update the framebuffer size using setFrameBufferSize().
Parameters
width The width of the framebuffer.
height The height of the framebuffer.
See also
touchgfx_generic_init
Reimplemented from HAL.
{
    HAL::setFrameBufferSize(width, height);
    // Get a copy of the dimension of the complete framebuffer as the dimensions get overwritten when using Partial Framebuffer
    HALSDL2__FRAME_BUFFER_WIDTH = FRAME_BUFFER_WIDTH;
    HALSDL2__FRAME_BUFFER_HEIGHT = FRAME_BUFFER_HEIGHT;
    if (single_buf)
    {
        delete[] single_buf;
    }
    if (double_buf)
    {
        delete[] double_buf;
    }
    if (anim_store)
    {
        delete[] anim_store;
    }
    // Allocate framebuffers
    const uint32_t bufferSizeInWords = (lcd().framebufferStride() * FRAME_BUFFER_HEIGHT + 1) / 2;
    single_buf = new uint16_t[bufferSizeInWords];
    double_buf = new uint16_t[bufferSizeInWords];
    anim_store = new uint16_t[bufferSizeInWords];
    const bool use_animation_storage = USE_ANIMATION_STORAGE;
    const bool use_double_buffering = USE_DOUBLE_BUFFERING;
    setFrameBufferStartAddresses(single_buf, double_buf, anim_store);
    USE_ANIMATION_STORAGE = use_animation_storage;
    USE_DOUBLE_BUFFERING = use_double_buffering;
    tft = single_buf; // Start off using single buffer for tft
}
References touchgfx::anim_store, touchgfx::double_buf, HAL::FRAME_BUFFER_HEIGHT, HAL::FRAME_BUFFER_WIDTH, touchgfx::HALSDL2__FRAME_BUFFER_HEIGHT, touchgfx::HALSDL2__FRAME_BUFFER_WIDTH, HAL::lcd(), HAL::setFrameBufferSize(), HAL::setFrameBufferStartAddresses(), touchgfx::single_buf, touchgfx::tft, HAL::USE_ANIMATION_STORAGE, and HAL::USE_DOUBLE_BUFFERING.
Referenced by HALSDL2::sdl_init().
setSingleStepping()
void setSingleStepping (bool singleStepping = true) static
Single stepping enable/disable. When single stepping is enabled, F10 will execute one tick and F9 will disable single stepping.
Parameters
singleStepping (Optional) True to pause the simulation and start single stepping.
See also
isSingleStepping
{
    singleSteppingEnabled = singleStepping;
    singleSteppingSteps = 0;
    updateTitle();
}
References HALSDL2::singleSteppingEnabled, HALSDL2::singleSteppingSteps, and HALSDL2::updateTitle().
Referenced by HALSDL2::taskEntry().
setTFTFrameBuffer()
void setTFTFrameBuffer (uint16_t * addr) protected virtual
Sets TFT framebuffer.
Parameters
[in] addr The address of the TFT framebuffer.
Implements HAL.
{
    if (getFrameRefreshStrategy() != REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER)
    {
        // Save current framebuffer address
        tft = adr;
        renderLCD_FrameBufferToMemory(dirty, doRotate(scaleTo24bpp(adr, lcd().framebufferFormat())));
    }
    else
    {
        // Wait for transfers to complete
        while (frameBufferAllocator->hasBlockReadyForTransfer())
        {
            FrameBufferAllocatorWaitOnTransfer();
        }
        // Always use the original tft buffer as screen memory GRAM
        renderLCD_FrameBufferToMemory(dirty, doRotate(scaleTo24bpp(tft, lcd().framebufferFormat())));
    }
    dirty = Rect();
}
References touchgfx::dirty, HALSDL2::doRotate(), HAL::frameBufferAllocator, touchgfx::FrameBufferAllocatorWaitOnTransfer(), HAL::getFrameRefreshStrategy(), FrameBufferAllocator::hasBlockReadyForTransfer(), HAL::lcd(), HAL::REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER, HALSDL2::renderLCD_FrameBufferToMemory(), HALSDL2::scaleTo24bpp(), and touchgfx::tft.
setVsyncInterval()
void setVsyncInterval (float ms)
Sets vsync interval for simulating same tick speed as the real hardware. Due to limitations in the granularity of SDL, the generated ticks in the simulator might not occur at the exact time, but accumulated over several ticks, the precision is very good.
Parameters
ms The milliseconds between ticks.
Note
That you can also use HAL::setFrameRateCompensation() in the simulator. The effect of this can easily be demonstrated by dragging the console output window of the simulator (when running from Visual Studio) as this will pause the SDL and generate a lot of ticks when the console window is released. Beware that since the missed vsyncs are accumulated in an 8 bit counter, only up to 255 ticks may be missed, so at VsyncInterval = 16.6667, dragging the windows for more than 255 * 16.6667ms = 4250ms = 4.25s will not generate all the ticks that were actually missed. This situation is, however, not very realistic, as normally just a couple of vsyncs are skipped.
{
    msBetweenTicks = ms;
    msPassed = 0.0f;
}
References HALSDL2::msBetweenTicks, and HALSDL2::msPassed.
Referenced by HALSDL2::HALSDL2().
setWindowTitle()
void setWindowTitle (const char * title) static
Sets window title.
Sets window title of the TouchGFX simulator.
Parameters
title The title, if null the original "TouchGFX simulator" will be used.
See also
getWindowTitle
{
    customTitle = title;
}
References HALSDL2::customTitle.
setWindowVisible()
void setWindowVisible (bool visible, bool redrawWindow = true) inline
Change visibility of window (hidden vs. shown) as well as (due to backward compatibility) the visibility of the console window.
Parameters
visible Should the window be visible?
redrawWindow (Optional) Should the window be redrawn? Default is true.
See also
getWindowVisible, setConsoleVisible
    {
        isWindowVisible = visible;
        isConsoleVisible = visible;
        if (redrawWindow)
        {
            recreateWindow();
            simulator_enable_stdio();
        }
    }
References HALSDL2::isConsoleVisible, HALSDL2::isWindowVisible, HALSDL2::recreateWindow(), and touchgfx::simulator_enable_stdio().
singleStep()
void singleStep (uint16_t steps = 1) static
Single step a number of steps. Only works if single stepping is already enabled.
Parameters
steps (Optional) The steps Default is 1 step.
See also
setSingleStepping, isSingleStepping
{
    if (singleSteppingEnabled)
    {
        singleSteppingSteps += steps;
    }
}
References HALSDL2::singleSteppingEnabled, and HALSDL2::singleSteppingSteps.
stopApplication()
void stopApplication () static
Terminate the application as quickly as possible
{
    isAlive = false;
}
References touchgfx::isAlive.
taskEntry()
void taskEntry () virtual
Main event loop. Will wait for VSYNC signal, and then process next frame. Call this function from your GUI task.
Note
This function never returns!
Reimplemented from HAL.
{
    uint32_t lastTick = SDL_GetTicks();
    while (isAlive)
    {
        SDL_Event event;
        if (SDL_PollEvent(&event) == 1)
        {
            switch (event.type)
            {
            case SDL_MOUSEMOTION:
                _xMouse = event.motion.x;
                _yMouse = event.motion.y;
                if (debugInfoEnabled)
                {
                    updateTitle();
                }
                if ((event.motion.state & SDL_BUTTON(SDL_BUTTON_LEFT)) != 0)
                {
                    _x = _xMouse;
                    _y = _yMouse;
                    pushTouch(true);
                }
                if (isWindowBeingDragged)
                {
                    int newMouseX;
                    int newMouseY;
                    SDL_GetGlobalMouseState(&newMouseX, &newMouseY);
                    SDL_SetWindowPosition(simulatorWindow, initialWindowX + (newMouseX - initialMouseX), initialWindowY + (newMouseY - initialMouseY));
                }
                break;
            case SDL_MOUSEBUTTONDOWN:
                SDL_CaptureMouse(SDL_TRUE);
                if (event.button.button == SDL_BUTTON_LEFT)
                {
                    _x = event.motion.x;
                    _y = event.motion.y;
                    pushTouch(true);
                }
                isWindowBeingDragged = (event.button.button == SDL_BUTTON_RIGHT);
                if (isWindowBeingDragged)
                {
                    SDL_GetWindowPosition(simulatorWindow, &initialWindowX, &initialWindowY);
                    SDL_GetGlobalMouseState(&initialMouseX, &initialMouseY);
                }
                break;
            case SDL_MOUSEBUTTONUP:
                SDL_CaptureMouse(SDL_FALSE);
                if (event.button.button == SDL_BUTTON_LEFT)
                {
                    pushTouch(false);
                }
                if (isWindowBeingDragged)
                {
                    int newMouseX;
                    int newMouseY;
                    SDL_GetGlobalMouseState(&newMouseX, &newMouseY);
                    SDL_SetWindowPosition(simulatorWindow, initialWindowX + (newMouseX - initialMouseX), initialWindowY + (newMouseY - initialMouseY));
                    isWindowBeingDragged = false;
                }
                break;
            case SDL_TEXTINPUT:
                if (strlen(event.text.text) == 1)
                {
                    keyPressed = (uint8_t)(event.text.text[0]);
                }
                break;
            case SDL_KEYUP:
                if (event.key.keysym.sym == SDLK_F1)
                {
                    debugInfoEnabled = !debugInfoEnabled;
                    updateTitle();
                }
                else if (event.key.keysym.sym == SDLK_F2)
                {
                    setFlashInvalidatedAreas(!flashInvalidatedRect);
                }
                else if (event.key.keysym.sym == SDLK_F3)
                {
                    if (event.key.keysym.mod & KMOD_CTRL)
                    {
                        // Repeat
                        saveNextScreenshots(50);
                    }
                    else if (event.key.keysym.mod & KMOD_SHIFT)
                    {
                        // clipboard
                        copyScreenshotToClipboard();
                    }
                    else if (event.key.keysym.mod & KMOD_ALT)
                    {
                        // Do nothing
                    }
                    else if (event.key.keysym.mod & KMOD_GUI)
                    {
                        // Do nothing
                    }
                    else
                    {
                        // No modifiers
                        saveScreenshot();
                    }
                }
                else if (event.key.keysym.sym == SDLK_F4)
                {
                    if (currentSkin != 0 && currentSkin->surface)
                    {
                        isSkinActive = !isSkinActive;
                    }
                    else
                    {
                        isWindowBorderless = !isWindowBorderless;
                    }
                    recreateWindow();
                }
                else if (event.key.keysym.sym == SDLK_ESCAPE)
                {
                    isAlive = false;
                }
                else if (event.key.keysym.sym == SDLK_F5)
                {
                    Application::getInstance()->changeToStartScreen();
                    // If stopped in single stepping, perform one step
                    if (singleSteppingEnabled && singleSteppingSteps == 0)
                    {
                        singleSteppingSteps++;
                    }
                }
                else if (event.key.keysym.sym == SDLK_F9)
                {
                    setSingleStepping(!singleSteppingEnabled);
                }
                else if (event.key.keysym.sym == SDLK_F10)
                {
                    if (singleSteppingEnabled)
                    {
                        singleSteppingSteps++;
                    }
                }
                break;
            case SDL_QUIT:
                isAlive = false;
                break;
            case SDL_WINDOWEVENT:
                switch (event.window.event)
                {
                case SDL_WINDOWEVENT_EXPOSED:
                    // Window has been exposed and should be redrawn
                    if (simulatorWindow != NULL)
                    {
                        Rect display(0, 0, DISPLAY_WIDTH, DISPLAY_HEIGHT);
                        renderLCD_FrameBufferToMemory(display, doRotate(scaleTo24bpp(getTFTFrameBuffer(), lcd().framebufferFormat())));
                    }
                    break;
                case SDL_WINDOWEVENT_CLOSE:
                    // The window manager requests that the window be closed
                    isAlive = false;
                    break;
                }
                break;
            default:
                break;
            }
        }
        else // No SDL event waiting
        {
            uint32_t thisTick = SDL_GetTicks();
            int msSinceLastTick = thisTick - lastTick;
            lastTick = thisTick;
            msPassed += msSinceLastTick;
            if (msPassed >= msBetweenTicks)
            {
                if (singleSteppingEnabled && singleSteppingSteps == 0)
                {
                    // Eat up extra ms when waiting for next step
                    while (msPassed >= msBetweenTicks)
                    {
                        msPassed -= msBetweenTicks;
                    }
                }
                else
                {
                    while (msPassed >= msBetweenTicks)
                    {
                        msPassed -= msBetweenTicks;
                        vSync();
                    }
                    backPorchExited();
                    frontPorchEntered();
                    if (screenshotcount > 0)
                    {
                        screenshotcount--;
                        saveScreenshot();
                    }
                }
                if (singleSteppingEnabled && singleSteppingSteps > 0)
                {
                    singleSteppingSteps--;
                }
            }
            else
            {
                // Sleep until we have the next tick
                uint32_t delay = (uint32_t)(msBetweenTicks - msPassed);
                // Due to rounding, delay might be zero.
                SDL_Delay(delay == 0 ? 1 : delay);
            }
        }
    }
}
References HALSDL2::_x, HALSDL2::_xMouse, HALSDL2::_y, HALSDL2::_yMouse, HAL::backPorchExited(), HALSDL2::copyScreenshotToClipboard(), HALSDL2::currentSkin, HALSDL2::debugInfoEnabled, display, HAL::DISPLAY_HEIGHT, HAL::DISPLAY_WIDTH, HALSDL2::doRotate(), HALSDL2::flashInvalidatedRect, HAL::frontPorchEntered(), Application::getInstance(), HALSDL2::getTFTFrameBuffer(), HALSDL2::initialMouseX, HALSDL2::initialMouseY, HALSDL2::initialWindowX, HALSDL2::initialWindowY, touchgfx::isAlive, HALSDL2::isSkinActive, HALSDL2::isWindowBeingDragged, HALSDL2::isWindowBorderless, HALSDL2::keyPressed, KMOD_ALT, KMOD_CTRL, KMOD_GUI, KMOD_SHIFT, HAL::lcd(), HALSDL2::msBetweenTicks, HALSDL2::msPassed, NULL, HALSDL2::pushTouch(), HALSDL2::recreateWindow(), HALSDL2::renderLCD_FrameBufferToMemory(), HALSDL2::saveNextScreenshots(), HALSDL2::saveScreenshot(), HALSDL2::scaleTo24bpp(), touchgfx::screenshotcount, SDL_BUTTON, SDL_BUTTON_LEFT, SDL_BUTTON_RIGHT, SDL_CaptureMouse(), SDL_Delay(), SDL_FALSE, SDL_GetGlobalMouseState(), SDL_GetTicks(), SDL_GetWindowPosition(), SDL_KEYUP, SDL_MOUSEBUTTONDOWN, SDL_MOUSEBUTTONUP, SDL_MOUSEMOTION, SDL_PollEvent(), SDL_QUIT, SDL_SetWindowPosition(), SDL_TEXTINPUT, SDL_TRUE, SDL_WINDOWEVENT, SDL_WINDOWEVENT_CLOSE, SDL_WINDOWEVENT_EXPOSED, SDLK_ESCAPE, SDLK_F1, SDLK_F10, SDLK_F2, SDLK_F3, SDLK_F4, SDLK_F5, SDLK_F9, HALSDL2::setFlashInvalidatedAreas(), HALSDL2::setSingleStepping(), touchgfx::simulatorWindow, HALSDL2::singleSteppingEnabled, HALSDL2::singleSteppingSteps, HALSDL2::SkinInfo::surface, HALSDL2::updateTitle(), and HAL::vSync().
updateCurrentSkin()
void updateCurrentSkin () private
{
    currentSkin = 0;
    if (getDisplayOrientation() == ORIENTATION_PORTRAIT)
    {
        if (portraitSkin.surface != 0)
        {
            currentSkin = &portraitSkin;
        }
    }
    else
    {
        if (landscapeSkin.surface != 0)
        {
            currentSkin = &landscapeSkin;
        }
    }
}
References HALSDL2::currentSkin, HAL::getDisplayOrientation(), HALSDL2::landscapeSkin, touchgfx::ORIENTATION_PORTRAIT, HALSDL2::portraitSkin, and HALSDL2::SkinInfo::surface.
Referenced by HALSDL2::HALSDL2(), HALSDL2::loadSkin(), and HALSDL2::performDisplayOrientationChange().
updateTitle()
void updateTitle () static private
{
    char title[500];
    int length = sprintf_s(title, 500, "%s", getWindowTitle());
    if (debugInfoEnabled)
    {
        length += sprintf_s(title + length, 500 - length, " @%d,%d", _xMouse, _yMouse);
        if (tft_framebuffer24 != 0)
        {
            // Convert display coordinates to framebuffer coordinates
            int16_t fb_x = _xMouse;
            int16_t fb_y = _yMouse;
            DisplayTransformation::transformDisplayToFrameBuffer(fb_x, fb_y);
            const uint8_t* const pixel_ptr = tft_framebuffer24 + 3 * (fb_x + fb_y * FRAME_BUFFER_WIDTH);
            length += sprintf_s(title + length, 500 - length, "=%02X.%02X.%02X", pixel_ptr[2], pixel_ptr[1], pixel_ptr[0]);
        }
    }
    if (flashInvalidatedRect)
    {
        length += sprintf_s(title + length, 500 - length, " (flash)");
    }
    if (isSingleStepping())
    {
        length += sprintf_s(title + length, 500 - length, " (step)");
    }
    SDL_SetWindowTitle(simulatorWindow, title);
}
References HALSDL2::_xMouse, HALSDL2::_yMouse, HALSDL2::debugInfoEnabled, HALSDL2::flashInvalidatedRect, HAL::FRAME_BUFFER_WIDTH, HALSDL2::getWindowTitle(), HALSDL2::isSingleStepping(), SDL_SetWindowTitle(), touchgfx::simulatorWindow, touchgfx::tft_framebuffer24, and DisplayTransformation::transformDisplayToFrameBuffer().
Referenced by HALSDL2::recreateWindow(), HALSDL2::setFlashInvalidatedAreas(), HALSDL2::setSingleStepping(), and HALSDL2::taskEntry().
Member Data Documentation
_lastTouch
bool _lastTouch = false static private
Referenced by HALSDL2::popTouch().
_numTouches
int _numTouches = 0 static private
Referenced by HALSDL2::popTouch(), and HALSDL2::pushTouch().
_touches
bool _touches = { false, false, false, false, false } static private
Referenced by HALSDL2::popTouch(), and HALSDL2::pushTouch().
_x
int32_t _x = 0 static private
Referenced by HALSDL2::doSampleTouch(), and HALSDL2::taskEntry().
_xMouse
int32_t _xMouse = 0 static private
Referenced by HALSDL2::taskEntry(), and HALSDL2::updateTitle().
_y
int32_t _y = 0 static private
Referenced by HALSDL2::doSampleTouch(), and HALSDL2::taskEntry().
_yMouse
int32_t _yMouse = 0 static private
Referenced by HALSDL2::taskEntry(), and HALSDL2::updateTitle().
currentSkin
SkinInfo* currentSkin private
Referenced by HALSDL2::getCurrentSkinX(), HALSDL2::getCurrentSkinY(), HALSDL2::recreateWindow(), HALSDL2::renderLCD_FrameBufferToMemory(), HALSDL2::taskEntry(), and HALSDL2::updateCurrentSkin().
customTitle
const char * customTitle = 0 static private
Referenced by HALSDL2::getWindowTitle(), and HALSDL2::setWindowTitle().
debugInfoEnabled
bool debugInfoEnabled = false static private
Referenced by HALSDL2::taskEntry(), and HALSDL2::updateTitle().
flashInvalidatedRect
bool flashInvalidatedRect = false static private
Referenced by HALSDL2::flushFrameBuffer(), HALSDL2::renderLCD_FrameBufferToMemory(), HALSDL2::setFlashInvalidatedAreas(), HALSDL2::taskEntry(), and HALSDL2::updateTitle().
icon
uint16_t icon static private
Referenced by HALSDL2::recreateWindow(), and HALSDL2::sdl_init().
initialMouseX
int initialMouseX static private
Referenced by HALSDL2::taskEntry().
initialMouseY
int initialMouseY static private
Referenced by HALSDL2::taskEntry().
initialWindowX
int initialWindowX static private
Referenced by HALSDL2::taskEntry().
initialWindowY
int initialWindowY static private
Referenced by HALSDL2::taskEntry().
isConsoleVisible
bool isConsoleVisible private
Referenced by HALSDL2::getConsoleVisible(), HALSDL2::setConsoleVisible(), and HALSDL2::setWindowVisible().
isSkinActive
bool isSkinActive private
Referenced by HALSDL2::getCurrentSkinX(), HALSDL2::getCurrentSkinY(), HALSDL2::recreateWindow(), HALSDL2::renderLCD_FrameBufferToMemory(), and HALSDL2::taskEntry().
isWindowBeingDragged
bool isWindowBeingDragged = false static private
Referenced by HALSDL2::taskEntry().
isWindowBorderless
bool isWindowBorderless private
Referenced by HALSDL2::recreateWindow(), and HALSDL2::taskEntry().
isWindowVisible
bool isWindowVisible private
Referenced by HALSDL2::getWindowVisible(), HALSDL2::recreateWindow(), and HALSDL2::setWindowVisible().
keyPressed
uint8_t keyPressed = 0 static private
Referenced by HALSDL2::sampleKey(), and HALSDL2::taskEntry().
landscapeSkin
SkinInfo landscapeSkin private
Referenced by HALSDL2::loadSkin(), and HALSDL2::updateCurrentSkin().
msBetweenTicks
float msBetweenTicks private
Referenced by HALSDL2::setVsyncInterval(), and HALSDL2::taskEntry().
msPassed
float msPassed private
Referenced by HALSDL2::setVsyncInterval(), and HALSDL2::taskEntry().
portraitSkin
SkinInfo portraitSkin private
Referenced by HALSDL2::loadSkin(), and HALSDL2::updateCurrentSkin().
printFile
FILE* printFile private
Referenced by HALSDL2::getPrintFile(), and HALSDL2::printToFile().
programPath
char programPath[300] private
Referenced by HALSDL2::localFileName(), and HALSDL2::sdl_init().
singleSteppingEnabled
bool singleSteppingEnabled = false static private
Referenced by HALSDL2::isSingleStepping(), HALSDL2::setSingleStepping(), HALSDL2::singleStep(), and HALSDL2::taskEntry().
singleSteppingSteps
uint16_t singleSteppingSteps = 0 static private
Referenced by HALSDL2::setSingleStepping(), HALSDL2::singleStep(), and HALSDL2::taskEntry().
windowDrag
bool windowDrag private
windowDragX
int windowDragX private
windowDragY
int windowDragY private
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/platform/hal/simulator/sdl2/HALSDL2.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/platform/hal/simulator/sdl2/HALSDL2.cpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/platform/hal/simulator/sdl2/HALSDL2_icon.cpp