Battery Simulator Documentation: STM32DMA
STM32DMA
This class specializes DMA_Interface for the STM32 processors.
#include "STM32DMA.hpp"
Public Member Functions
STM32DMA ()
Default constructor.
virtual ~STM32DMA ()
Destructor.
virtual touchgfx::BlitOperations getBlitCaps ()
Gets the blit capabilities.
virtual touchgfx::DMAType getDMAType (void)
virtual void initialize ()
Perform hardware specific initialization.
virtual void signalDMAInterrupt ()
Raises a DMA interrupt signal.
virtual void start ()
Public Member Functions inherited from DMA_Interface
virtual ~DMA_Interface ()
virtual void addToQueue (const BlitOp &op)
virtual void flush ()
bool getAllowed () const
bool getReserved () const
uint8_t isDmaQueueEmpty ()
uint8_t isDmaQueueFull ()
bool isDMARunning ()
void setAllowed (bool allowed)
void setReserved (bool reserved)
Protected Member Functions
void externalJobCompleted ()
Handle DMA2D when an external job has been executed.
void externalJobExecute ()
Executes an external DMA2D job.
virtual void setupDataCopy (const touchgfx::BlitOp &blitOp)
Configures the DMA for copying data to the frame buffer.
virtual void setupDataFill (const touchgfx::BlitOp &blitOp)
Configures the DMA for "filling" the frame-buffer with a single color.
Protected Member Functions inherited from DMA_Interface
DMA_Interface (DMA_Queue &dmaQueue)
virtual void disableAlpha ()
virtual void enableAlpha (uint8_t alpha)
virtual void enableCopyWithTransparentPixels (uint8_t alpha)
virtual void execute ()
virtual void executeCompleted ()
virtual void seedExecution ()
virtual void waitForFrameBufferSemaphore ()
Private Types
typedef touchgfx::DMA_Interface Base
Defines an alias representing the base.
Private Member Functions
uint32_t getChromARTInputFormat (touchgfx::Bitmap::BitmapFormat format)
uint32_t getChromARTOutputFormat (touchgfx::Bitmap::BitmapFormat format)
Private Attributes
touchgfx::LockFreeDMA_Queue dma_queue
MUTEX_TYPE mutexIsRunning
touchgfx::BlitOp queue_storage [96]
bool started_by_external_job
Additional Inherited Members
Protected Attributes inherited from DMA_Interface
volatile bool isAllowed
true if DMA transfers are currently allowed.
volatile bool isReserved
true if DMA is reserved for for HW rendering
bool isRunning
true if a DMA transfer is currently ongoing.
DMA_Queue & queue
Reference to the DMA queue.
Detailed Description
This class specializes DMA_Interface for the STM32 processors.
See also
touchgfx::DMA_Interface
Member Typedef Documentation
Base
touchgfx::DMA_Interface Base private
Defines an alias representing the base.
Defines an alias representing the base.
Constructor & Destructor Documentation
STM32DMA()
STM32DMA ()
Default constructor.
   Default constructor.
    : DMA_Interface(dma_queue), dma_queue(queue_storage, sizeof(queue_storage) / sizeof(queue_storage[0])), started_by_external_job(false), mutexIsRunning(0)
{
    mutexIsRunning = MUTEX_CREATE();
}
References MUTEX_CREATE, and mutexIsRunning.
~STM32DMA()
~STM32DMA () virtual
Destructor.
   Destructor.
{
    /* Disable DMA2D global Interrupt */
    NVIC_DisableIRQ(DMA2D_IRQn);
}
Member Function Documentation
externalJobCompleted()
void externalJobCompleted () inline protected
Handle DMA2D when an external job has been executed.
Parameters
None
    {
        if (isRunning)
        {
            isRunning = false;
            DMA2D_ExternalJobCompleted(Jpeg_OUT_BufferTab[JPEG_OUT_Read_BufferIndex]);
        }
    }
References DMA2D_ExternalJobCompleted(), DMA_Interface::isRunning, Jpeg_OUT_BufferTab, and JPEG_OUT_Read_BufferIndex.
Referenced by signalDMAInterrupt().
externalJobExecute()
void externalJobExecute () inline protected
Executes an external DMA2D job.
Parameters
None
    {
        isRunning = true;
        DMA2D_CopyBuffer(Jpeg_OUT_BufferTab[JPEG_OUT_Read_BufferIndex]);
    }
References DMA2D_CopyBuffer(), DMA_Interface::isRunning, Jpeg_OUT_BufferTab, and JPEG_OUT_Read_BufferIndex.
Referenced by signalDMAInterrupt(), and start().
getBlitCaps()
touchgfx::BlitOperations getBlitCaps () virtual
Gets the blit capabilities.
   Gets the blit capabilities.
   This DMA supports a range of blit caps: BLIT_OP_COPY, BLIT_OP_COPY_ARGB8888,
   BLIT_OP_COPY_ARGB8888_WITH_ALPHA, BLIT_OP_COPY_A4, BLIT_OP_COPY_A8.
Returns
Currently supported blitcaps.
Implements DMA_Interface.
{
    return static_cast<BlitOperations>(BLIT_OP_FILL
                                       | BLIT_OP_FILL_WITH_ALPHA
                                       | BLIT_OP_COPY
                                       | BLIT_OP_COPY_L8
                                       | BLIT_OP_COPY_WITH_ALPHA
                                       | BLIT_OP_COPY_ARGB8888
                                       | BLIT_OP_COPY_ARGB8888_WITH_ALPHA
                                       | BLIT_OP_COPY_A4
                                       | BLIT_OP_COPY_A8);
}
References touchgfx::BLIT_OP_COPY, touchgfx::BLIT_OP_COPY_A4, touchgfx::BLIT_OP_COPY_A8, touchgfx::BLIT_OP_COPY_ARGB8888, touchgfx::BLIT_OP_COPY_ARGB8888_WITH_ALPHA, touchgfx::BLIT_OP_COPY_L8, touchgfx::BLIT_OP_COPY_WITH_ALPHA, touchgfx::BLIT_OP_FILL, and touchgfx::BLIT_OP_FILL_WITH_ALPHA.
getChromARTInputFormat()
uint32_t getChromARTInputFormat (touchgfx::Bitmap::BitmapFormat format) inline private
{
    // Default color mode set to ARGB8888
    uint32_t dma2dColorMode = DMA2D_INPUT_ARGB8888;
    switch (format)
    {
    case Bitmap::ARGB8888: /* DMA2D input mode set to 32bit ARGB */
        dma2dColorMode = DMA2D_INPUT_ARGB8888;
        break;
    case Bitmap::RGB888: /* DMA2D input mode set to 24bit RGB */
        dma2dColorMode = DMA2D_INPUT_RGB888;
        break;
    case Bitmap::RGB565: /* DMA2D input mode set to 16bit RGB */
        dma2dColorMode = DMA2D_INPUT_RGB565;
        break;
    case Bitmap::ARGB2222: /* Fall through */
    case Bitmap::ABGR2222: /* Fall through */
    case Bitmap::RGBA2222: /* Fall through */
    case Bitmap::BGRA2222: /* Fall through */
    case Bitmap::L8:       /* DMA2D input mode set to 8bit Color Look up table*/
        dma2dColorMode = DMA2D_INPUT_L8;
        break;
    case Bitmap::BW:     /* Fall through */
    case Bitmap::BW_RLE: /* Fall through */
    case Bitmap::GRAY4:  /* Fall through */
    case Bitmap::GRAY2:  /* Fall through */
    default:             /* Unsupported input format for DMA2D */
        assert(0 && "Unsupported Format!");
        break;
    }
    return dma2dColorMode;
}
References Bitmap::ABGR2222, Bitmap::ARGB2222, Bitmap::ARGB8888, Bitmap::BGRA2222, Bitmap::BW, Bitmap::BW_RLE, Bitmap::GRAY2, Bitmap::GRAY4, Bitmap::L8, Bitmap::RGB565, Bitmap::RGB888, and Bitmap::RGBA2222.
Referenced by setupDataCopy().
getChromARTOutputFormat()
uint32_t getChromARTOutputFormat (touchgfx::Bitmap::BitmapFormat format) inline private
{
    // Default color mode set to ARGB8888
    uint32_t dma2dColorMode = DMA2D_OUTPUT_ARGB8888;
    switch (format)
    {
    case Bitmap::ARGB8888: /* DMA2D output mode set to 32bit ARGB */
        dma2dColorMode = DMA2D_OUTPUT_ARGB8888;
        break;
    case Bitmap::RGB888:   /* Fall through */
    case Bitmap::ARGB2222: /* Fall through */
    case Bitmap::ABGR2222: /* Fall through */
    case Bitmap::RGBA2222: /* Fall through */
    case Bitmap::BGRA2222: /* DMA2D output mode set to 24bit RGB */
        dma2dColorMode = DMA2D_OUTPUT_RGB888;
        break;
    case Bitmap::RGB565: /* DMA2D output mode set to 16bit RGB */
        dma2dColorMode = DMA2D_OUTPUT_RGB565;
        break;
    case Bitmap::L8:     /* Fall through */
    case Bitmap::BW:     /* Fall through */
    case Bitmap::BW_RLE: /* Fall through */
    case Bitmap::GRAY4:  /* Fall through */
    case Bitmap::GRAY2:  /* Fall through */
    default:             /* Unsupported output format for DMA2D */
        assert(0 && "Unsupported Format!");
        break;
    }
    return dma2dColorMode;
}
References Bitmap::ABGR2222, Bitmap::ARGB2222, Bitmap::ARGB8888, Bitmap::BGRA2222, Bitmap::BW, Bitmap::BW_RLE, Bitmap::GRAY2, Bitmap::GRAY4, Bitmap::L8, Bitmap::RGB565, Bitmap::RGB888, and Bitmap::RGBA2222.
Referenced by setupDataCopy(), and setupDataFill().
getDMAType()
virtual touchgfx::DMAType getDMAType (void) inline virtual
Function for obtaining the DMA type of the concrete DMA_Interface implementation. As default, will return DMA_TYPE_GENERIC type value.
Returns
a DMAType value of the concrete DMA_Interface implementation.
Reimplemented from DMA_Interface.
    {
        return touchgfx::DMA_TYPE_CHROMART;
    }
References touchgfx::DMA_TYPE_CHROMART.
initialize()
void initialize () virtual
Perform hardware specific initialization.
   Perform hardware specific initialization.
Reimplemented from DMA_Interface.
{
    /* Ensure DMA2D Clock is enabled */
    __HAL_RCC_DMA2D_CLK_ENABLE();
    __HAL_RCC_DMA2D_FORCE_RESET();
    __HAL_RCC_DMA2D_RELEASE_RESET();
    /* Add transfer complete callback function */
    hdma2d.XferCpltCallback = DMA2D_XferCpltCallback;
    /* Enable DMA2D global Interrupt */
    NVIC_EnableIRQ(DMA2D_IRQn);
}
References DMA2D_XferCpltCallback(), and hdma2d.
setupDataCopy()
void setupDataCopy (const touchgfx::BlitOp & blitOp) protected virtual
Configures the DMA for copying data to the frame buffer.
   Configures the DMA for copying data to the frame buffer.
Parameters
blitOp Details on the copy to perform.
Implements DMA_Interface.
{
    uint32_t dma2dForegroundColorMode = getChromARTInputFormat(static_cast<Bitmap::BitmapFormat>(blitOp.srcFormat));
    uint32_t dma2dBackgroundColorMode = getChromARTInputFormat(static_cast<Bitmap::BitmapFormat>(blitOp.dstFormat));
    uint32_t dma2dOutputColorMode = getChromARTOutputFormat(static_cast<Bitmap::BitmapFormat>(blitOp.dstFormat));
    /* DMA2D OOR register configuration */
    WRITE_REG(DMA2D->OOR, blitOp.dstLoopStride - blitOp.nSteps);
    /* DMA2D BGOR register configuration */
    WRITE_REG(DMA2D->BGOR, blitOp.dstLoopStride - blitOp.nSteps);
    /* DMA2D FGOR register configuration */
    WRITE_REG(DMA2D->FGOR, blitOp.srcLoopStride - blitOp.nSteps);
    /* DMA2D OPFCCR register configuration */
    WRITE_REG(DMA2D->OPFCCR, dma2dOutputColorMode);
    /* Configure DMA2D data size */
    WRITE_REG(DMA2D->NLR, (blitOp.nLoops | (blitOp.nSteps << DMA2D_NLR_PL_Pos)));
    /* Configure DMA2D destination address */
    WRITE_REG(DMA2D->OMAR, reinterpret_cast<uint32_t>(blitOp.pDst));
    /* Configure DMA2D source address */
    WRITE_REG(DMA2D->FGMAR, reinterpret_cast<uint32_t>(blitOp.pSrc));
    switch (blitOp.operation)
    {
    case BLIT_OP_COPY_A4:
        /* Set DMA2D color mode and alpha mode */
        WRITE_REG(DMA2D->FGPFCCR, DMA2D_INPUT_A4 | (DMA2D_COMBINE_ALPHA << DMA2D_FGPFCCR_AM_Pos) | (blitOp.alpha << 24));
        /* set DMA2D foreground color */
        WRITE_REG(DMA2D->FGCOLR, blitOp.color);
        /* Write DMA2D BGPFCCR register */
        WRITE_REG(DMA2D->BGPFCCR, dma2dBackgroundColorMode | (DMA2D_NO_MODIF_ALPHA << DMA2D_BGPFCCR_AM_Pos));
        /* Configure DMA2D Stream source2 address */
        WRITE_REG(DMA2D->BGMAR, reinterpret_cast<uint32_t>(blitOp.pDst));
        /* Set DMA2D mode */
        WRITE_REG(DMA2D->CR, DMA2D_M2M_BLEND | DMA2D_IT_TC | DMA2D_CR_START);
        break;
    case BLIT_OP_COPY_A8:
        /* Set DMA2D color mode and alpha mode */
        WRITE_REG(DMA2D->FGPFCCR, DMA2D_INPUT_A8 | (DMA2D_COMBINE_ALPHA << DMA2D_FGPFCCR_AM_Pos) | (blitOp.alpha << 24));
        /* set DMA2D foreground color */
        WRITE_REG(DMA2D->FGCOLR, blitOp.color);
        /* Write DMA2D BGPFCCR register */
        WRITE_REG(DMA2D->BGPFCCR, dma2dBackgroundColorMode | (DMA2D_NO_MODIF_ALPHA << DMA2D_BGPFCCR_AM_Pos));
        /* Configure DMA2D Stream source2 address */
        WRITE_REG(DMA2D->BGMAR, reinterpret_cast<uint32_t>(blitOp.pDst));
        /* Set DMA2D mode */
        WRITE_REG(DMA2D->CR, DMA2D_M2M_BLEND | DMA2D_IT_TC | DMA2D_CR_START);
        break;
    case BLIT_OP_COPY_L8:
        {
            const clutData_t* const palette = reinterpret_cast<const clutData_t*>(blitOp.pClut);
            bool blend = true;
            /* Set DMA2D color mode and alpha mode */
            WRITE_REG(DMA2D->FGPFCCR, dma2dForegroundColorMode | (DMA2D_COMBINE_ALPHA << DMA2D_FGPFCCR_AM_Pos) | (blitOp.alpha << 24));
            /* Write DMA2D BGPFCCR register */
            WRITE_REG(DMA2D->BGPFCCR, dma2dBackgroundColorMode | (DMA2D_NO_MODIF_ALPHA << DMA2D_BGPFCCR_AM_Pos));
            /* Configure DMA2D Stream source2 address */
            WRITE_REG(DMA2D->BGMAR, reinterpret_cast<uint32_t>(blitOp.pDst));
            /* Write foreground CLUT memory address */
            WRITE_REG(DMA2D->FGCMAR, reinterpret_cast<uint32_t>(&palette->data));
            switch ((Bitmap::ClutFormat)palette->format)
            {
            case Bitmap::CLUT_FORMAT_L8_ARGB8888:
                /* Write foreground CLUT size and CLUT color mode */
                MODIFY_REG(DMA2D->FGPFCCR, (DMA2D_FGPFCCR_CS | DMA2D_FGPFCCR_CCM), (((palette->size - 1) << DMA2D_FGPFCCR_CS_Pos) | (DMA2D_CCM_ARGB8888 << DMA2D_FGPFCCR_CCM_Pos)));
                break;
            case Bitmap::CLUT_FORMAT_L8_RGB888:
                if (blitOp.alpha == 255)
                {
                    blend = false;
                }
                MODIFY_REG(DMA2D->FGPFCCR, (DMA2D_FGPFCCR_CS | DMA2D_FGPFCCR_CCM), (((palette->size - 1) << DMA2D_FGPFCCR_CS_Pos) | (DMA2D_CCM_RGB888 << DMA2D_FGPFCCR_CCM_Pos)));
                break;
            case Bitmap::CLUT_FORMAT_L8_RGB565:
            default:
                assert(0 && "Unsupported format");
                break;
            }
            /* Enable the CLUT loading for the foreground */
            SET_BIT(DMA2D->FGPFCCR, DMA2D_FGPFCCR_START);
            while ((READ_REG(DMA2D->FGPFCCR) & DMA2D_FGPFCCR_START) != 0U)
            {
            }
            DMA2D->IFCR = (DMA2D_FLAG_CTC);
            /* Set DMA2D mode */
            if (blend)
            {
                WRITE_REG(DMA2D->CR, DMA2D_M2M_BLEND | DMA2D_IT_TC | DMA2D_CR_START);
            }
            else
            {
                WRITE_REG(DMA2D->CR, DMA2D_M2M_PFC | DMA2D_IT_TC | DMA2D_CR_START);
            }
        }
        break;
    case BLIT_OP_COPY_WITH_ALPHA:
        /* Set DMA2D color mode and alpha mode */
        WRITE_REG(DMA2D->FGPFCCR, dma2dForegroundColorMode | (DMA2D_COMBINE_ALPHA << DMA2D_FGPFCCR_AM_Pos) | (blitOp.alpha << 24));
        /* Write DMA2D BGPFCCR register */
        WRITE_REG(DMA2D->BGPFCCR, dma2dBackgroundColorMode | (DMA2D_NO_MODIF_ALPHA << DMA2D_BGPFCCR_AM_Pos));
        /* Configure DMA2D Stream source2 address */
        WRITE_REG(DMA2D->BGMAR, reinterpret_cast<uint32_t>(blitOp.pDst));
        /* Set DMA2D mode */
        WRITE_REG(DMA2D->CR, DMA2D_M2M_BLEND | DMA2D_IT_TC | DMA2D_CR_START);
        break;
    case BLIT_OP_COPY_ARGB8888:
    case BLIT_OP_COPY_ARGB8888_WITH_ALPHA:
        /* Set DMA2D color mode and alpha mode */
        WRITE_REG(DMA2D->FGPFCCR, dma2dForegroundColorMode | (DMA2D_COMBINE_ALPHA << DMA2D_FGPFCCR_AM_Pos) | (blitOp.alpha << 24));
        /* Write DMA2D BGPFCCR register */
        WRITE_REG(DMA2D->BGPFCCR, dma2dBackgroundColorMode | (DMA2D_NO_MODIF_ALPHA << DMA2D_BGPFCCR_AM_Pos));
        /* Configure DMA2D Stream source2 address */
        WRITE_REG(DMA2D->BGMAR, reinterpret_cast<uint32_t>(blitOp.pDst));
        /* Set DMA2D mode */
        WRITE_REG(DMA2D->CR, DMA2D_M2M_BLEND | DMA2D_IT_TC | DMA2D_CR_START);
        break;
    default: /* BLIT_OP_COPY */
        /* Set DMA2D color mode and alpha mode */
        WRITE_REG(DMA2D->FGPFCCR, dma2dForegroundColorMode | (DMA2D_COMBINE_ALPHA << DMA2D_FGPFCCR_AM_Pos) | (blitOp.alpha << 24));
        /* Perform pixel-format-conversion (PFC) If Bitmap format is not same format as framebuffer format */
        if (blitOp.srcFormat != blitOp.dstFormat)
        {
            /* Start DMA2D : PFC Mode */
            WRITE_REG(DMA2D->CR, DMA2D_M2M_PFC | DMA2D_IT_TC | DMA2D_CR_START);
        }
        else
        {
            /* Start DMA2D : M2M Mode */
            WRITE_REG(DMA2D->CR, DMA2D_M2M | DMA2D_IT_TC | DMA2D_CR_START);
        }
        break;
    }
}
References touchgfx::BLIT_OP_COPY_A4, touchgfx::BLIT_OP_COPY_A8, touchgfx::BLIT_OP_COPY_ARGB8888, touchgfx::BLIT_OP_COPY_ARGB8888_WITH_ALPHA, touchgfx::BLIT_OP_COPY_L8, touchgfx::BLIT_OP_COPY_WITH_ALPHA, Bitmap::CLUT_FORMAT_L8_ARGB8888, Bitmap::CLUT_FORMAT_L8_RGB565, Bitmap::CLUT_FORMAT_L8_RGB888, clutData_t::data, clutData_t::format, getChromARTInputFormat(), getChromARTOutputFormat(), and clutData_t::size.
setupDataFill()
void setupDataFill (const touchgfx::BlitOp & blitOp) protected virtual
Configures the DMA for "filling" the frame-buffer with a single color.
   Configures the DMA for "filling" the frame-buffer with a single color.
Parameters
blitOp Details on the "fill" to perform.
Implements DMA_Interface.
{
    uint32_t dma2dOutputColorMode = getChromARTOutputFormat(static_cast<Bitmap::BitmapFormat>(blitOp.dstFormat));
    /* DMA2D OPFCCR register configuration */
    WRITE_REG(DMA2D->OPFCCR, dma2dOutputColorMode);
    /* Configure DMA2D data size */
    WRITE_REG(DMA2D->NLR, (blitOp.nLoops | (blitOp.nSteps << DMA2D_NLR_PL_Pos)));
    /* Configure DMA2D destination address */
    WRITE_REG(DMA2D->OMAR, reinterpret_cast<uint32_t>(blitOp.pDst));
    /* DMA2D OOR register configuration */
    WRITE_REG(DMA2D->OOR, blitOp.dstLoopStride - blitOp.nSteps);
    if (blitOp.operation == BLIT_OP_FILL_WITH_ALPHA)
    {
        /* DMA2D BGOR register configuration */
        WRITE_REG(DMA2D->BGOR, blitOp.dstLoopStride - blitOp.nSteps);
        /* DMA2D FGOR register configuration */
        WRITE_REG(DMA2D->FGOR, blitOp.dstLoopStride - blitOp.nSteps);
        /* Write DMA2D BGPFCCR register */
        WRITE_REG(DMA2D->BGPFCCR, dma2dOutputColorMode | (DMA2D_NO_MODIF_ALPHA << DMA2D_BGPFCCR_AM_Pos));
        /* Write DMA2D FGPFCCR register */
        WRITE_REG(DMA2D->FGPFCCR, DMA2D_INPUT_A8 | (DMA2D_REPLACE_ALPHA << DMA2D_FGPFCCR_AM_Pos) | ((blitOp.alpha << 24) & DMA2D_FGPFCCR_ALPHA));
        /* DMA2D FGCOLR register configuration */
        WRITE_REG(DMA2D->FGCOLR, blitOp.color);
        /* Configure DMA2D Stream source2 address */
        WRITE_REG(DMA2D->BGMAR, reinterpret_cast<uint32_t>(blitOp.pDst));
        /* Configure DMA2D source address */
        WRITE_REG(DMA2D->FGMAR, reinterpret_cast<uint32_t>(blitOp.pDst));
        /* Enable the Peripheral and Enable the transfer complete interrupt */
        WRITE_REG(DMA2D->CR, (DMA2D_IT_TC | DMA2D_CR_START | DMA2D_M2M_BLEND));
    }
    else
    {
        /* Write DMA2D FGPFCCR register */
        WRITE_REG(DMA2D->FGPFCCR, dma2dOutputColorMode | (DMA2D_NO_MODIF_ALPHA << DMA2D_FGPFCCR_AM_Pos));
        /* DMA2D FGOR register configuration */
        WRITE_REG(DMA2D->FGOR, 0);
        /* Set color */
        WRITE_REG(DMA2D->OCOLR, blitOp.color);
        /* Enable the Peripheral and Enable the transfer complete interrupt */
        WRITE_REG(DMA2D->CR, (DMA2D_IT_TC | DMA2D_CR_START | DMA2D_R2M));
    }
}
References touchgfx::BLIT_OP_FILL_WITH_ALPHA, and getChromARTOutputFormat().
signalDMAInterrupt()
void signalDMAInterrupt () inline virtual
Raises a DMA interrupt signal.
   Raises a DMA interrupt signal.
Implements DMA_Interface.
    {
        if (!started_by_external_job)
        {
            executeCompleted();
            /* Start new external job if next buffer is full */
            if (Jpeg_OUT_BufferTab[JPEG_OUT_Read_BufferIndex].State == JPEG_BUFFER_FULL && !DMA2D_CopyBufferEnd && !isRunning && !isReserved)
            {
                started_by_external_job = true;
                externalJobExecute();
            }
        }
        else
        {
            externalJobCompleted();
            /* Prioritize BlitOps if there are any pending */
            if (!queue.isEmpty() && isAllowed)
            {
                started_by_external_job = false;
                execute();
            }
        }
    }
References DMA2D_CopyBufferEnd, DMA_Interface::execute(), DMA_Interface::executeCompleted(), externalJobCompleted(), externalJobExecute(), DMA_Interface::isAllowed, DMA_Queue::isEmpty(), DMA_Interface::isReserved, DMA_Interface::isRunning, JPEG_BUFFER_FULL, Jpeg_OUT_BufferTab, JPEG_OUT_Read_BufferIndex, DMA_Interface::queue, and started_by_external_job.
start()
virtual void start () inline virtual
Signals that DMA transfers can start. If any elements are in the queue, start it.
Reimplemented from DMA_Interface.
    {
        MUTEX_LOCK(mutexIsRunning);
        if (!queue.isEmpty() && isAllowed && !isRunning)
        {
            started_by_external_job = false;
            execute();
        }
        else if ((Jpeg_OUT_BufferTab[JPEG_OUT_Read_BufferIndex].State == JPEG_BUFFER_FULL) && !isRunning && !isReserved)
        {
            started_by_external_job = true;
            externalJobExecute();
        }
        MUTEX_UNLOCK(mutexIsRunning);
    }
References DMA_Interface::execute(), externalJobExecute(), DMA_Interface::isAllowed, DMA_Queue::isEmpty(), DMA_Interface::isReserved, DMA_Interface::isRunning, JPEG_BUFFER_FULL, Jpeg_OUT_BufferTab, JPEG_OUT_Read_BufferIndex, MUTEX_LOCK, MUTEX_UNLOCK, mutexIsRunning, DMA_Interface::queue, and started_by_external_job.
Member Data Documentation
dma_queue
touchgfx::LockFreeDMA_Queue dma_queue private
mutexIsRunning
MUTEX_TYPE mutexIsRunning private
Referenced by STM32DMA(), and start().
queue_storage
touchgfx::BlitOp queue_storage[96] private
started_by_external_job
bool started_by_external_job private
Referenced by signalDMAInterrupt(), and start().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/target/generated/STM32DMA.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/target/generated/STM32DMA.cpp