Battery Simulator Documentation: PainterRGB565Bitmap
PainterRGB565Bitmap
#include "PainterRGB565Bitmap.hpp"
Public Member Functions
PainterRGB565Bitmap (const Bitmap &bmp=Bitmap(BITMAP_INVALID))
virtual HAL::RenderingMethod getRenderingMethod () const
virtual void paint (uint8_t *destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const
virtual void setBitmap (const Bitmap &bmp)
virtual bool setup (const Rect &widgetRect) const
virtual void tearDown () const
Public Member Functions inherited from AbstractPainterRGB565
AbstractPainterRGB565 ()
FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t newpix, uint16_t bufpix, uint8_t alpha) const
FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t R, uint16_t G, uint16_t B, uint16_t bufpix, uint8_t alpha) const
Public Member Functions inherited from AbstractPainter
AbstractPainter ()
virtual ~AbstractPainter ()
void framebufferToDisplay (int16_t &widgetX, int16_t &widgetY) const
Public Member Functions inherited from AbstractPainterBitmap
AbstractPainterBitmap (const Bitmap &bmp=Bitmap(BITMAP_INVALID))
virtual ~AbstractPainterBitmap ()
Bitmap getBitmap () const
void getOffset (int16_t &x, int16_t &y)
bool getTiled () const
virtual void setOffset (int16_t x, int16_t y)
virtual void setTiled (bool tiled)
Protected Attributes
const uint8_t * bitmapExtraData
Pointer to the bitmap extra data.
Protected Attributes inherited from AbstractPainter
int16_t widgetWidth
The width of the widget on screen, used by framebufferToDisplay()
Protected Attributes inherited from AbstractPainterBitmap
Bitmap bitmap
The bitmap to be used when painting.
const uint8_t * bitmapData
Pointer to the bitmap data.
Bitmap::BitmapFormat bitmapFormat
Copy of the bitmap format (for speed reasons)
Rect bitmapRect
Bitmap rectangle translated to framebuffer coordinates.
bool isTiled
True if bitmap should be tiled, false if not.
int16_t xOffset
The x offset of the bitmap.
int16_t yOffset
The y offset of the bitmap.
Additional Inherited Members
Static Public Attributes inherited from AbstractPainterRGB565
static const uint16_t BMASK = 0x001F
Mask for blue (0000000000011111)
static const uint16_t GMASK = 0x07E0
Mask for green (0000011111100000)
static const uint16_t RMASK = 0xF800
Mask for red (1111100000000000)
Protected Member Functions inherited from AbstractPainterBitmap
bool adjustBitmapXY (int16_t &bitmapX, int16_t &bitmapY, int16_t &offset, int16_t &count) const
void updateBitmapOffsets (int16_t widgetWidth) const
Static Protected Member Functions inherited from AbstractPainter
static FORCE_INLINE_FUNCTION bool compatibleFramebuffer (Bitmap::BitmapFormat format)
Detailed Description
PainterRGB565Bitmap will take the color for a given point in the shape from a bitmap. Please be aware, the the bitmap is used by the CanvasWidgetRenderer (not Shape), so any rotation you might specify for a Canvas Widget (e.g. Shape) is not applied to the bitmap as CWR is not aware of this rotation.
See also
AbstractPainter
Constructor & Destructor Documentation
PainterRGB565Bitmap()
PainterRGB565Bitmap (const Bitmap & bmp = Bitmap(BITMAP_INVALID)) inline
Constructor.
Parameters
bmp (Optional) The bitmap to use in the painter.
        : AbstractPainterRGB565(), AbstractPainterBitmap(bmp)
    {
    }
Member Function Documentation
getRenderingMethod()
virtual HAL::RenderingMethod getRenderingMethod () const inline virtual
Return the applicable rendering method of the painter. HARDWARE if the painter uses hardware based drawing, SOFTWARE otherwise. Relevant on platforms using DCACHE.
Returns
HARDWARE if painter uses hardware based drawing, SOFTWARE otherwise.
Reimplemented from AbstractPainter.
    {
        return HAL::getInstance()->getDMAType() == DMA_TYPE_CHROMART ? HAL::HARDWARE : HAL::SOFTWARE;
    }
References touchgfx::DMA_TYPE_CHROMART, HAL::getInstance(), HAL::HARDWARE, and HAL::SOFTWARE.
paint()
void paint (uint8_t * destination, int16_t offset, int16_t widgetX, int16_t widgetY, int16_t count, uint8_t alpha) const virtual
Paints a streak of pixels (all with the same alpha) in the framebuffer. The first pixel to paint is at 'offset' relative to 'destination' (to be able to support 1bpp, 2bpp and 4bpp). The first pixel to paint is at the given 'widgetX', 'widgetY' coordinate. The number of pixels to paint is 'count' and the alpha to apply is 'alpha'.
Note that the widgetX, widgetY is relative to the widget in the framebuffer, not the display. To convert the coordinate to display widget coordinates, use framebufferToDisplay().
Parameters
[in] destination If non-null, the pointer.
offset The offset to add to the destination.
widgetX The widget x coordinate.
widgetY The widget y coordinate.
count Number of pixels.
alpha The alpha of the pixels.
See also
AbstractPainter::setup, AbstractPainter::tearDown, AbstractPainter::framebufferToDisplay
Implements AbstractPainter.
{
    if (!adjustBitmapXY(widgetX, widgetY, offset, count))
    {
        return;
    }
    uint16_t* RESTRICT framebuffer = reinterpret_cast<uint16_t*>(destination) + offset;
    const uint16_t* const lineEnd = framebuffer + count;
    const int32_t rowSkip = widgetY * bitmapRect.width;
    int16_t bitmapAvailable = bitmapRect.width - widgetX;
    if (bitmapFormat == Bitmap::RGB565)
    {
        const uint16_t* const bitmapLineStart = reinterpret_cast<const uint16_t*>(bitmapData) + rowSkip;
        const uint16_t* bitmapPointer = bitmapLineStart + widgetX;
        if (bitmapExtraData)
        {
            const uint8_t* const alpha_linestart = bitmapExtraData + rowSkip;
            const uint8_t* alphaPointer = alpha_linestart + widgetX;
            do
            {
                const int16_t length = MIN(bitmapAvailable, count);
                const uint16_t* const chunkend = framebuffer + length;
                count -= length;
                do
                {
                    const uint8_t a = LCD::div255(alpha * (*alphaPointer++));
                    if (a == 0xFF)
                    {
                        *framebuffer = *bitmapPointer;
                    }
                    else if (a)
                    {
                        *framebuffer = alphaBlend(*bitmapPointer, *framebuffer, a);
                    }
                    bitmapPointer++;
                } while (++framebuffer < chunkend);
                bitmapPointer = bitmapLineStart;
                alphaPointer = alpha_linestart;
                bitmapAvailable = bitmapRect.width;
            } while (framebuffer < lineEnd);
        }
        else
        {
            do
            {
                const int16_t length = MIN(bitmapAvailable, count);
                count -= length;
                // Call external (DMA) painter function
                paint::rgb565::lineFromRGB565(framebuffer, bitmapPointer, length, alpha);
                framebuffer += length;
                bitmapPointer = bitmapLineStart;
                bitmapAvailable = bitmapRect.width;
            } while (framebuffer < lineEnd);
        }
    }
    else // if (bitmapFormat == Bitmap::ARGB8888)
    {
        const uint32_t* const bitmapLineStart = reinterpret_cast<const uint32_t*>(bitmapData) + rowSkip;
        const uint32_t* bitmapPointer = bitmapLineStart + widgetX;
        do
        {
            const int16_t length = MIN(bitmapAvailable, count);
            count -= length;
            //Call external (DMA) painter function
            paint::rgb565::lineFromARGB8888(framebuffer, bitmapPointer, length, alpha);
            framebuffer += length;
            bitmapPointer = bitmapLineStart;
            bitmapAvailable = bitmapRect.width;
        } while (framebuffer < lineEnd);
    }
}
References AbstractPainterBitmap::adjustBitmapXY(), AbstractPainterRGB565::alphaBlend(), AbstractPainterBitmap::bitmapData, PainterRGB565Bitmap::bitmapExtraData, AbstractPainterBitmap::bitmapFormat, AbstractPainterBitmap::bitmapRect, LCD::div255(), touchgfx::paint::rgb565::lineFromARGB8888(), touchgfx::paint::rgb565::lineFromRGB565(), MIN, RESTRICT, Bitmap::RGB565, and Rect::width.
setBitmap()
void setBitmap (const Bitmap & bmp) virtual
Sets a bitmap to be used when drawing the CanvasWidget.
Parameters
bmp The bitmap.
Reimplemented from AbstractPainterBitmap.
{
    AbstractPainterBitmap::setBitmap(bmp);
    assert((bitmap.getId() == BITMAP_INVALID || bitmapFormat == Bitmap::RGB565 || bitmapFormat == Bitmap::ARGB8888) && "PainterRGB565Bitmap only works with RGB565 and ARGB8888 bitmaps");
    assert(bitmap.getId() == BITMAP_INVALID || bitmapData);
    bitmapExtraData = bitmap.getExtraData();
}
References Bitmap::ARGB8888, touchgfx::BITMAP_INVALID, AbstractPainterBitmap::bitmapData, PainterRGB565Bitmap::bitmapExtraData, AbstractPainterBitmap::bitmapFormat, Bitmap::RGB565, and AbstractPainterBitmap::setBitmap().
setup()
virtual bool setup (const Rect & widgetRect) const inline virtual
This function is called before any actual paint operation is started. This allows the painter to initialize variables and optional dma queues. This happens before the first scan line segment is being drawn. If the painter is unable to draw, e.g. no bitmap assigned to a bitmap painter, 'false' should be returned.
Parameters
widgetRect The widget rectangle.
Returns
True if the painter is ready to paint, false otherwise.
See also
AbstractPainter::paint, AbstractPainter::tearDown
Reimplemented from AbstractPainter.
    {
        if (!AbstractPainterRGB565::setup(widgetRect))
        {
            return false;
        }
        updateBitmapOffsets(widgetWidth);
        return bitmap.getId() != BITMAP_INVALID;
    }
References touchgfx::BITMAP_INVALID, AbstractPainter::setup(), AbstractPainterBitmap::updateBitmapOffsets(), and AbstractPainter::widgetWidth.
tearDown()
void tearDown () const virtual
This function is called after all paint operation have finished. This allows the painter to close down dma queues etc. This happens after the last scan line segment has been drawn.
See also
AbstractPainter::paint, AbstractPainter::setup
Reimplemented from AbstractPainter.
{
    paint::tearDown();
}
References touchgfx::paint::tearDown().
Member Data Documentation
bitmapExtraData
const uint8_t* bitmapExtraData protected
Pointer to the bitmap extra data.
Referenced by PainterRGB565Bitmap::paint(), and PainterRGB565Bitmap::setBitmap().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/PainterRGB565Bitmap.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas/PainterRGB565Bitmap.cpp