Battery Simulator Documentation: Screen1View
Screen1View
#include "Screen1View.hpp"
Public Member Functions
Screen1View ()
virtual ~Screen1View ()
virtual void SetLevel (int level)
Function implementing of SetLevel.
virtual void SetState (bool state)
Function implementing of SetState.
virtual void setupScreen ()
virtual void tearDownScreen ()
Public Member Functions inherited from Screen1ViewBase
Screen1ViewBase ()
virtual ~Screen1ViewBase ()
Public Member Functions inherited from View< Screen1Presenter >
View ()
void bind (Screen1Presenter &newPresenter)
Public Member Functions inherited from Screen
Screen ()
virtual ~Screen ()
virtual void afterTransition ()
void bindTransition (Transition &trans)
void draw ()
virtual void draw (Rect &rect)
Container & getRootContainer ()
int16_t getScreenHeight () const
int16_t getScreenWidth () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleKeyEvent (uint8_t key)
virtual void handleTickEvent ()
void JSMOC (const Rect &invalidatedArea, Drawable *widgetToDraw)
void startSMOC (const Rect &invalidatedArea)
bool usingSMOC () const
Additional Inherited Members
Protected Member Functions inherited from Screen1ViewBase
FrontendApplication & application ()
Protected Member Functions inherited from Screen
void add (Drawable &d)
void insert (Drawable *previous, Drawable &d)
void invalidate () const
void invalidateRect (Rect &invalidatedArea) const
void remove (Drawable &d)
void useSMOCDrawing (bool enabled)
Protected Attributes inherited from Screen1ViewBase
touchgfx::Box __background
touchgfx::AnimatedImage animatedImage1
touchgfx::Image image1
touchgfx::Image image2
touchgfx::ImageProgress imageProgress1
Protected Attributes inherited from View< Screen1Presenter >
Screen1Presenter * presenter
Pointer to the Presenter associated with this view.
Protected Attributes inherited from Screen
Container container
The container contains the contents of the screen.
Drawable * focus
The drawable currently in focus (set when DOWN_PRESSED is received).
Detailed Description
Constructor & Destructor Documentation
Screen1View()
Screen1View ()
File Name : Screen1View.cpp Description : Code for Screen1View applications
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
{
}
~Screen1View()
virtual ~Screen1View () inline virtual
{}
Member Function Documentation
SetLevel()
void SetLevel (int level) virtual
Function implementing of SetLevel.
Parameters
argument percentage of the battery.
Return values
None
{
    /* Set the battery level*/
    imageProgress1.setValue(level);
    imageProgress1.invalidate();
}
References Screen1ViewBase::imageProgress1, Drawable::invalidate(), and ImageProgress::setValue().
Referenced by Screen1Presenter::SetLevel().
SetState()
void SetState (bool state) virtual
Function implementing of SetState.
Parameters
argument bool for state
Return values
None
{
    /* If animation is not running*/
    if(!animatedImage1.isAnimatedImageRunning())
    {
        /* If state is charging*/
        if(state==true)
        {
            /* Show the charging animation*/
            animatedImage1.setAlpha(255);
            animatedImage1.startAnimation(false, false, true);
            animatedImage1.invalidate();
        }
    }
    /* If animation is running*/
    if(animatedImage1.isAnimatedImageRunning())
    {
        /* If the battery is discharging*/
        if(state==false)
        {
            /* Stop the animation*/
            animatedImage1.setAlpha(0);
            animatedImage1.stopAnimation();
            animatedImage1.invalidate();
        }
    }
}
References Screen1ViewBase::animatedImage1, Drawable::invalidate(), AnimatedImage::isAnimatedImageRunning(), Image::setAlpha(), AnimatedImage::startAnimation(), state, and AnimatedImage::stopAnimation().
Referenced by Screen1Presenter::SetState().
setupScreen()
void setupScreen () virtual
Called by Application::switchScreen() when this screen is going to be displayed. Base version does nothing, but place any screen specific initialization code in an overridden version.
See also
Application::switchScreen
Reimplemented from Screen1ViewBase.
{
    Screen1ViewBase::setupScreen();
}
References Screen1ViewBase::setupScreen().
tearDownScreen()
void tearDownScreen () virtual
Called by Application::switchScreen() when this screen will no longer be displayed. Base version does nothing, but place any screen specific cleanup code in an overridden version.
See also
Application::switchScreen
Reimplemented from Screen.
{
    Screen1ViewBase::tearDownScreen();
}
References Screen::tearDownScreen().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/gui/include/gui/screen1_screen/Screen1View.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/gui/src/screen1_screen/Screen1View.cpp