Battery Simulator Documentation: Image
Image
#include "Image.hpp"
Public Member Functions
Image (const Bitmap &bmp=Bitmap())
virtual void draw (const Rect &invalidatedArea) const
uint8_t getAlpha () const
Bitmap getBitmap () const
BitmapId getBitmapId () const
virtual Rect getSolidRect () const
virtual void invalidateContent () const
void setAlpha (uint8_t newAlpha)
virtual void setBitmap (const Bitmap &bmp)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
uint8_t alpha
The Alpha for this image.
Bitmap bitmap
The Bitmap to display.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
Simple widget capable of showing a bitmap on the display. The bitmap can be alpha-blended with the background (or whichever other Drawable might be "underneath" the Image). The bitmap can and have areas of varying opacity.
The conversion from image.bmp or image.png to a bitmap that can be used in TouchGFX is handled by the Image Converter as part of compiling the project. Each image is assigned a unique BITMAP identifier which.
See also
Bitmap
Constructor & Destructor Documentation
Image()
Image (const Bitmap & bmp = Bitmap()) inline
Constructs a new Image with a default alpha value of 255 (solid) and a default Bitmap (undefined) if none is specified. If a Bitmap is passed to the constructor, the width and height of this widget is set to those of the bitmap.
Parameters
bmp (Optional) The bitmap to display.
See also
setBitmap
        : Widget(), bitmap(bmp), alpha(255)
    {
        Image::setBitmap(bmp);
    }
References Image::setBitmap().
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Implements Drawable.
Reimplemented in ScalableImage, TextureMapper, and TiledImage.
{
    Rect meAbs;
    translateRectToAbsolute(meAbs); // To find our x and y coords in absolute.
    // Calculate intersection between bitmap rect and invalidated area.
    const Rect dirtyBitmapArea = bitmap.getRect() & invalidatedArea;
    if (!dirtyBitmapArea.isEmpty())
    {
        HAL::lcd().drawPartialBitmap(bitmap, meAbs.x, meAbs.y, dirtyBitmapArea, alpha);
    }
}
References HAL::lcd(), and Drawable::translateRectToAbsolute().
getAlpha()
uint8_t getAlpha () const inline
Gets the current alpha value of the widget. The alpha value is in range 255 (solid) to 0 (invisible).
Returns
The current alpha value.
See also
setAlpha
    {
        return alpha;
    }
References Image::alpha.
Referenced by AnalogClock::getAlpha(), and AbstractProgressIndicator::getAlpha().
getBitmap()
Bitmap getBitmap () const inline
Gets the Bitmap currently assigned to the Image widget.
Returns
The current Bitmap of the widget.
    {
        return bitmap;
    }
References Image::bitmap.
Referenced by AnimatedImage::handleTickEvent().
getBitmapId()
BitmapId getBitmapId () const inline
Gets the BitmapId currently assigned to the Image widget.
Returns
The current BitmapId of the widget.
    {
        return bitmap.getId();
    }
getSolidRect()
Rect getSolidRect () const virtual
Get (the largest possible) rectangle that is guaranteed to be solid (opaque). This information is important, as any Drawable underneath the solid area does not need to be drawn.
Returns
The solid rectangle part of the Drawable.
Note
The rectangle returned must be relative to upper left corner of the Drawable, meaning that a completely solid widget should return the full size Rect(0, 0, getWidth(), getHeight()). If no area can be guaranteed to be solid, an empty Rect must be returned. Failing to return the correct rectangle may result in errors on the display.
Implements Drawable.
Reimplemented in ScalableImage, TextureMapper, and TiledImage.
{
    // If alpha is less than solid, we have an empty solid rect.
    if (alpha < 255)
    {
        return Rect();
    }
    // Return solid rect from bitmap (precalculated).
    return bitmap.getSolidRect();
}
invalidateContent()
virtual void invalidateContent () const inline virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from Drawable.
Reimplemented in TextureMapper.
    {
        if (alpha > 0)
        {
            Widget::invalidateContent();
        }
    }
References Drawable::invalidateContent().
setAlpha()
void setAlpha (uint8_t newAlpha) inline
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
    {
        alpha = newAlpha;
    }
Referenced by Screen1ViewBase::Screen1ViewBase(), AnimatedImageButtonStyle< T >::handleAlphaUpdated(), IconButtonStyle< T >::handleAlphaUpdated(), ImageButtonStyle< T >::handleAlphaUpdated(), TiledImageButtonStyle< T >::handleAlphaUpdated(), AnalogClock::setAlpha(), AbstractProgressIndicator::setAlpha(), ZoomAnimationImage::setAlpha(), Gauge::setAlpha(), and Screen1View::SetState().
setBitmap()
void setBitmap (const Bitmap & bmp) virtual
Sets the bitmap for this Image and updates the width and height of this widget to match those of the Bitmap.
Parameters
bmp The bitmap instance.
Note
The user code must call invalidate() in order to update the image on the display.
Reimplemented in AnimatedImage, TextureMapper, and TiledImage.
{
    bitmap = bmp;
    // When setting bitmap, adjust size of this widget to match.
    setWidthHeight(bmp);
}
References Drawable::setWidthHeight().
Referenced by Image::Image(), Screen1ViewBase::Screen1ViewBase(), Keyboard::handleClickEvent(), IconButtonStyle< T >::handlePressedUpdated(), ImageButtonStyle< T >::handlePressedUpdated(), AnimatedImage::handleTickEvent(), AbstractProgressIndicator::setBackground(), ModalWindow::setBackground(), AnalogClock::setBackground(), AnimatedImage::setBitmap(), TextureMapper::setBitmap(), TiledImage::setBitmap(), Slider::setBitmaps(), ZoomAnimationImage::setBitmaps(), SlideMenu::setup(), SlideMenu::setup(), AnimatedImage::startAnimation(), and AnimatedImage::stopAnimation().
Member Data Documentation
alpha
uint8_t alpha protected
The Alpha for this image.
Referenced by Image::getAlpha().
bitmap
Bitmap bitmap protected
The Bitmap to display.
Referenced by Image::getBitmap().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/Image.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/Image.cpp