Battery Simulator Documentation: Model
Model
#include "Model.hpp"
Public Member Functions
Model ()
Function implementing of ModelListener.
void bind (ModelListener *listener)
void tick ()
Function implementing of Tick.
Protected Attributes
unsigned int BatteryLevel
bool BatteryState
ModelListener * modelListener
Detailed Description
Constructor & Destructor Documentation
Model()
Model ()
Function implementing of ModelListener.
Parameters
argument Not used
Return values
None
             : modelListener(0)
{
}
Member Function Documentation
bind()
void bind (ModelListener * listener) inline
    {
        modelListener = listener;
    }
References modelListener.
tick()
void tick ()
Function implementing of Tick.
Parameters
argument Not used
Return values
None
{
    /* Check if there is new data in the queue*/
    if(osMessageQueueGetCount(BatteryStateQueueHandle)>0)
    {
        /* Get the new data in the queue, store in their respective variable and send the new data to the model listener
         * The variables have been defined in Model.hpp
         * The functions have been defined in /ModelListener.hpp
         * */
        if(osMessageQueueGet(BatteryStateQueueHandle, &BatteryState, 0, 0)==osOK)
        {
            /* Push the new Data to SetState*/
            modelListener->SetState(BatteryState);
        }
    }
    /* Check if there is new data in the queue*/
    if(osMessageQueueGetCount(BatteryLevelQueueHandle)>0)
    {
        if(osMessageQueueGet(BatteryLevelQueueHandle, &BatteryLevel, 0, 0)==osOK)
        {
            /* Push the new Data to SetLevel*/
            modelListener->SetLevel(BatteryLevel);
        }
    }
}
References BatteryLevel, BatteryLevelQueueHandle, BatteryState, BatteryStateQueueHandle, modelListener, ModelListener::SetLevel(), and ModelListener::SetState().
Referenced by FrontendApplication::handleTickEvent().
Member Data Documentation
BatteryLevel
unsigned int BatteryLevel protected
Referenced by tick().
BatteryState
bool BatteryState protected
Referenced by tick().
modelListener
ModelListener* modelListener protected
Referenced by bind(), and tick().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/gui/include/gui/model/Model.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/gui/src/model/Model.cpp