Battery Simulator Documentation: GraphLabelsX
GraphLabelsX
#include "GraphLabels.hpp"
Public Member Functions
virtual int getCorrectlyScaledLabelInterval (const AbstractDataGraph *graph) const
virtual void invalidateGraphPointAt (int16_t index)
Public Member Functions inherited from GraphLabelsBase
GraphLabelsBase ()
virtual void draw (const Rect &invalidatedArea) const
virtual int getCorrectlyScaledMajorInterval (const AbstractDataGraph *graph) const
FORCE_INLINE_FUNCTION float getIntervalAsFloat () const
FORCE_INLINE_FUNCTION int getIntervalAsInt () const
FORCE_INLINE_FUNCTION int getIntervalScaled () const
FORCE_INLINE_FUNCTION Unicode::UnicodeChar getLabelDecimalPoint () const
FORCE_INLINE_FUNCTION uint16_t getLabelDecimals () const
FORCE_INLINE_FUNCTION TextRotation getLabelRotation () const
FORCE_INLINE_FUNCTION const TypedText & getLabelTypedText () const
FORCE_INLINE_FUNCTION int getScale () const
FORCE_INLINE_FUNCTION void setInterval (float interval)
FORCE_INLINE_FUNCTION void setInterval (int interval)
FORCE_INLINE_FUNCTION void setIntervalScaled (int interval)
FORCE_INLINE_FUNCTION void setLabelDecimalPoint (Unicode::UnicodeChar decimalPoint)
FORCE_INLINE_FUNCTION void setLabelDecimals (uint16_t decimals)
FORCE_INLINE_FUNCTION void setLabelRotation (TextRotation rotation)
FORCE_INLINE_FUNCTION void setLabelTypedText (const TypedText &typedText)
FORCE_INLINE_FUNCTION void setMajorLabel (const GraphLabelsBase &major)
FORCE_INLINE_FUNCTION void setScale (int scale)
Public Member Functions inherited from AbstractGraphElementNoCWR
AbstractGraphElementNoCWR ()
virtual bool drawCanvasWidget (const Rect &) const
virtual colortype getColor () const
virtual void setColor (colortype newColor)
Public Member Functions inherited from AbstractGraphElement
AbstractGraphElement ()
Public Member Functions inherited from CanvasWidget
CanvasWidget ()
virtual uint8_t getAlpha () const
virtual Rect getMinimalRect () const
const AbstractPainter * getPainter () const
virtual Rect getSolidRect () const
virtual void invalidate () const
virtual void setAlpha (uint8_t newAlpha)
void setPainter (const AbstractPainter &painter)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
void drawIndexRange (const Rect &invalidatedArea, const Font *fontToDraw, const AbstractDataGraph *graph, const int rangeMin, const int rangeMax, const int minorInterval, const int majorInterval, const uint8_t a) const
virtual void drawString (const Rect &invalidatedArea, const Font *fontToDraw, const AbstractDataGraph *graph, const int valueScaled, const int labelScaled, const uint8_t a) const
virtual int getGraphRangeMaxScaled (const AbstractDataGraph *graph) const
virtual int getGraphRangeMinScaled (const AbstractDataGraph *graph) const
Protected Member Functions inherited from GraphLabelsBase
void formatLabel (Unicode::UnicodeChar *buffer, int16_t bufferSize, int label, int decimals, Unicode::UnicodeChar decimalPoint, int scale) const
Protected Member Functions inherited from AbstractGraphElementNoCWR
void normalizeRect (Rect &r) const
Protected Member Functions inherited from AbstractGraphElement
FORCE_INLINE_FUNCTION int convertToGraphScaleX (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION int convertToGraphScaleY (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION AbstractDataGraph * getGraph () const
FORCE_INLINE_FUNCTION int getIndexToXAxis (const AbstractDataGraph *graph, const int valueScaled, const int labelScaled) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenXQ5 (const AbstractDataGraph *graph, int16_t index) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenYQ5 (const AbstractDataGraph *graph, int16_t index) const
bool isCenterInvisible (const AbstractDataGraph *graph, int16_t index) const
Rect rectAround (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5, CWRUtil::Q5 diameterQ5) const
Rect rectFromQ5Coordinates (CWRUtil::Q5 screenXminQ5, CWRUtil::Q5 screenYminQ5, CWRUtil::Q5 screenXmaxQ5, CWRUtil::Q5 screenYmaxQ5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 roundQ5 (CWRUtil::Q5 q5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenXQ5 (const AbstractDataGraph *graph, int x) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenYQ5 (const AbstractDataGraph *graph, int y) const
FORCE_INLINE_FUNCTION bool xScreenRangeToIndexRange (const AbstractDataGraph *graph, int16_t xMin, int16_t xMax, int16_t &indexMin, int16_t &indexMax) const
Additional Inherited Members
Protected Attributes inherited from GraphLabelsBase
int dataScale
The scaling factor.
Unicode::UnicodeChar labelDecimalPoint
The label decimal point character.
uint16_t labelDecimals
The number of decimals on the label.
int labelInterval
The interval between each label.
TextRotation labelRotation
The TextRotation to use for the label.
TypedText labelTypedText
The TypedText to use for the label.
const GraphLabelsBase * majorLabel
A pointer to a major label, if any.
Protected Attributes inherited from AbstractGraphElementNoCWR
colortype color
The currently assigned color.
Protected Attributes inherited from CanvasWidget
uint8_t alpha
The Alpha for this CanvasWidget.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
GraphLabelsX will draw labels along the X axis at given intervals. By combining two GraphLabelsX it is possible to have different appearance for major and minor y offsets.
Member Function Documentation
drawIndexRange()
void drawIndexRange (const Rect & invalidatedArea, const Font * fontToDraw, const AbstractDataGraph * graph, const int rangeMin, const int rangeMax, const int minorInterval, const int majorInterval, const uint8_t a) const protected virtual
Draw labels for all indexes in the given range. This is used where there is a gap in the graph and the labels have to be drawn using different x scales.
Parameters
[in] invalidatedArea The canvas.
fontToDraw The font to draw.
graph The graph.
rangeMin The minimum index.
rangeMax The maximum index.
minorInterval The minor interval.
majorInterval The major interval.
a The alpha of the strings.
Reimplemented from GraphLabelsBase.
{
    const int16_t gapIndex = graph->getGapBeforeIndex();
    if (gapIndex <= 0 || gapIndex <= rangeMin || gapIndex > rangeMax)
    {
        GraphLabelsBase::drawIndexRange(invalidatedArea, fontToDraw, graph, rangeMin, rangeMax, minorInterval, majorInterval, a);
    }
    else
    {
        GraphLabelsBase::drawIndexRange(invalidatedArea, fontToDraw, graph, rangeMin, (int)gapIndex - 1, minorInterval, majorInterval, a);
        GraphLabelsBase::drawIndexRange(invalidatedArea, fontToDraw, graph, (int)gapIndex, rangeMax, minorInterval, majorInterval, a);
    }
}
References GraphLabelsBase::drawIndexRange().
drawString()
void drawString (const Rect & invalidatedArea, const Font * fontToDraw, const AbstractDataGraph * graph, const int valueScaled, const int labelScaled, const uint8_t a) const protected virtual
Draw string.
Parameters
invalidatedArea The invalidated area.
fontToDraw The font to draw.
graph The graph.
valueScaled The value scaled.
labelScaled The label scaled.
a The alpha of the string.
Implements GraphLabelsBase.
{
    const int16_t labelX = valueToScreenXQ5(graph, valueScaled).round() - graph->getGraphAreaPaddingLeft();
    if (labelX < 0 || labelX >= graph->getGraphAreaWidth())
    {
        return;
    }
    Unicode::UnicodeChar wildcard[20];
    formatLabel(wildcard, 20, getIndexToXAxis(graph, valueScaled, labelScaled), labelDecimals, labelDecimalPoint, graph->getScaleX());
    // Adjust to make label centered
    int16_t labelWidth;
    const Unicode::UnicodeChar* text = labelTypedText.getText();
    if (labelRotation == TEXT_ROTATE_0 || labelRotation == TEXT_ROTATE_180)
    {
        labelWidth = fontToDraw->getStringWidth(text, wildcard);
    }
    else
    {
        labelWidth = fontToDraw->getHeight() * fontToDraw->getNumberOfLines(text, wildcard) + fontToDraw->getSpacingAbove(text, wildcard);
    }
    const int16_t offset = (labelRotation == TEXT_ROTATE_0 || labelRotation == TEXT_ROTATE_90) ? (labelWidth / 2) : ((labelWidth + 1) / 2);
    Rect labelRect((graph->getGraphAreaMarginLeft() + valueToScreenXQ5(graph, valueScaled).round()) - offset, 0, labelWidth, getHeight());
    Rect dirty = labelRect & invalidatedArea;
    if (!dirty.isEmpty())
    {
        dirty.x -= labelRect.x;
        dirty.y -= labelRect.y;
        translateRectToAbsolute(labelRect);
        const LCD::StringVisuals visuals(fontToDraw, color, a, labelTypedText.getAlignment(), 0, labelRotation, labelTypedText.getTextDirection(), 0, WIDE_TEXT_NONE);
        HAL::lcd().drawString(labelRect, dirty, visuals, text, wildcard, 0);
    }
}
References touchgfx::dirty, GraphLabelsBase::formatLabel(), TypedText::getAlignment(), Drawable::getHeight(), AbstractGraphElement::getIndexToXAxis(), TypedText::getText(), TypedText::getTextDirection(), GraphLabelsBase::labelDecimalPoint, GraphLabelsBase::labelDecimals, GraphLabelsBase::labelRotation, GraphLabelsBase::labelTypedText, HAL::lcd(), CWRUtil::Q5::round(), touchgfx::TEXT_ROTATE_0, touchgfx::TEXT_ROTATE_180, touchgfx::TEXT_ROTATE_90, Drawable::translateRectToAbsolute(), AbstractGraphElement::valueToScreenXQ5(), and touchgfx::WIDE_TEXT_NONE.
getCorrectlyScaledLabelInterval()
virtual int getCorrectlyScaledLabelInterval (const AbstractDataGraph * graph) const inline virtual
Gets correctly scaled minor interval, as the minor label may have a scale that differs the scale of the graph and this label.
Parameters
graph The graph.
Returns
The correctly scaled minor interval.
Implements GraphLabelsBase.
    {
        return convertToGraphScaleX(graph, labelInterval, dataScale);
    }
References AbstractGraphElement::convertToGraphScaleX(), GraphLabelsBase::dataScale, and GraphLabelsBase::labelInterval.
Referenced by GraphLabelsX::invalidateGraphPointAt().
getGraphRangeMaxScaled()
virtual int getGraphRangeMaxScaled (const AbstractDataGraph * graph) const inline protected virtual
Gets graph range maximum scaled.
Parameters
graph The graph.
Returns
The graph range maximum scaled.
Implements GraphLabelsBase.
    {
        return graph->getGraphRangeXMaxScaled();
    }
getGraphRangeMinScaled()
virtual int getGraphRangeMinScaled (const AbstractDataGraph * graph) const inline protected virtual
Gets graph range minimum scaled.
Parameters
graph The graph.
Returns
The graph range minimum scaled.
Implements GraphLabelsBase.
    {
        return graph->getGraphRangeXMinScaled();
    }
invalidateGraphPointAt()
void invalidateGraphPointAt (int16_t index) virtual
Invalidate the point at the given index. This allows a graph element to only invalidate the minimum rectangle required for the given index. The Graph will call this function before and after changing a point to ensure that both the old and the new area are redrawn (invalidated).
Parameters
index Zero-based index of the point.
Reimplemented from GraphLabelsBase.
{
    if (!labelTypedText.hasValidId())
    {
        return;
    }
    const Font* fontToDraw = labelTypedText.getFont();
    if (!fontToDraw)
    {
        return;
    }
    const AbstractDataGraph* graph = getGraph();
    const uint8_t a = LCD::div255(getAlpha() * graph->getAlpha());
    if (a == 0)
    {
        return;
    }
    const int scaledIndex = graph->int2scaledX(index);
    const int minorInterval = getCorrectlyScaledLabelInterval(graph);
    const int majorInterval = getCorrectlyScaledMajorInterval(graph);
    const bool isOnMinor = (minorInterval > 0 && scaledIndex == minorInterval * (int)(scaledIndex / minorInterval));
    const bool isOnMajor = (majorInterval > 0 && scaledIndex == majorInterval * (int)(scaledIndex / majorInterval));
    if ((majorInterval == 0 && minorInterval == 0 && scaledIndex == 0) || (isOnMinor && !isOnMajor))
    {
        Unicode::UnicodeChar wildcard[20];
        const int labelScaled = (minorInterval == 0) ? 0 : (scaledIndex / minorInterval) * labelInterval;
        formatLabel(wildcard, 20, getIndexToXAxis(graph, scaledIndex, labelScaled), labelDecimals, labelDecimalPoint, dataScale);
        // Adjust to make label centered
        int16_t labelWidth;
        const Unicode::UnicodeChar* text = labelTypedText.getText();
        if (labelRotation == TEXT_ROTATE_0 || labelRotation == TEXT_ROTATE_180)
        {
            labelWidth = fontToDraw->getStringWidth(text, wildcard);
        }
        else
        {
            // Get full height for all lines, except the last line for which we "replace" the part under
            // the baseline with the 'spacing above'.
            labelWidth = fontToDraw->getHeight() * fontToDraw->getNumberOfLines(text, wildcard) + fontToDraw->getSpacingAbove(text, wildcard);
        }
        const int16_t offset = (labelRotation == TEXT_ROTATE_0 || labelRotation == TEXT_ROTATE_90) ? (labelWidth / 2) : ((labelWidth + 1) / 2);
        Rect dirty((graph->getGraphAreaMarginLeft() + valueToScreenXQ5(graph, scaledIndex).round()) - offset, 0, labelWidth, getHeight());
        invalidateRect(dirty);
    }
}
References GraphLabelsBase::dataScale, touchgfx::dirty, LCD::div255(), GraphLabelsBase::formatLabel(), CanvasWidget::getAlpha(), GraphLabelsX::getCorrectlyScaledLabelInterval(), GraphLabelsBase::getCorrectlyScaledMajorInterval(), TypedText::getFont(), AbstractGraphElement::getGraph(), Drawable::getHeight(), AbstractGraphElement::getIndexToXAxis(), TypedText::getText(), TypedText::hasValidId(), Drawable::invalidateRect(), GraphLabelsBase::labelDecimalPoint, GraphLabelsBase::labelDecimals, GraphLabelsBase::labelInterval, GraphLabelsBase::labelRotation, GraphLabelsBase::labelTypedText, touchgfx::TEXT_ROTATE_0, touchgfx::TEXT_ROTATE_180, touchgfx::TEXT_ROTATE_90, and AbstractGraphElement::valueToScreenXQ5().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/graph/GraphLabels.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph/GraphLabels.cpp