Battery Simulator Documentation: DigitalClock
DigitalClock
#include "DigitalClock.hpp"
Public Types
enum DisplayMode { DISPLAY_12_HOUR_NO_SECONDS , DISPLAY_24_HOUR_NO_SECONDS , DISPLAY_12_HOUR , DISPLAY_24_HOUR }
Public Member Functions
DigitalClock ()
void displayLeadingZeroForHourIndicator (bool displayLeadingZero)
virtual uint8_t getAlpha () const
virtual colortype getColor () const
virtual DisplayMode getDisplayMode () const
virtual uint16_t getTextWidth () const
virtual void invalidateContent () const
virtual void setAlpha (uint8_t newAlpha)
virtual void setBaselineY (int16_t baselineY)
virtual void setColor (colortype color)
virtual void setDisplayMode (DisplayMode dm)
virtual void setHeight (int16_t height)
virtual void setTypedText (TypedText typedText)
virtual void setWidth (int16_t width)
Public Member Functions inherited from AbstractClock
AbstractClock ()
bool getCurrentAM () const
uint8_t getCurrentHour () const
uint8_t getCurrentHour12 () const
uint8_t getCurrentHour24 () const
uint8_t getCurrentMinute () const
uint8_t getCurrentSecond () const
virtual void setTime12Hour (uint8_t hour, uint8_t minute, uint8_t second, bool am)
virtual void setTime24Hour (uint8_t hour, uint8_t minute, uint8_t second)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual void updateClock ()
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
Unicode::UnicodeChar buffer [BUFFER_SIZE]
Wild card buffer for the clock text.
DisplayMode displayMode
The current display mode.
TextAreaWithOneWildcard text
The clock text.
bool useLeadingZeroForHourIndicator
Print a leading zero if the hour is less than 10.
Protected Attributes inherited from AbstractClock
uint8_t currentHour
Local copy of the current hour.
uint8_t currentMinute
Local copy of the current minute.
uint8_t currentSecond
Local copy of the current second.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Static Protected Attributes
static const int BUFFER_SIZE = 12
Buffer size of the wild card, worst case is "12:59:59 AM" (12 chars)
Detailed Description
A digital clock. Can be set in either 12 or 24 hour mode. Seconds are optional. Width and height must be set manually to match the typography and alignment specified in the text database. The Digital Clock requires a typedText with one wildcard and uses the following characters (not including quotes) "AMP :0123456789" These must be present in the text database with the same typography as the wildcard text. Leading zero for the hour indicator can be enabled/disable by the displayLeadingZeroForHourIndicator method.
Member Enumeration Documentation
DisplayMode
enum DisplayMode
Values that represent different display modes.
Enumerator
DISPLAY_12_HOUR_NO_SECONDS
12 Hour clock. Seconds are not displayed
DISPLAY_24_HOUR_NO_SECONDS
24 Hour clock. Seconds are not displayed
DISPLAY_12_HOUR
12 Hour clock. Seconds are displayed
DISPLAY_24_HOUR
24 Hour clock. Seconds are displayed
    {
        DISPLAY_12_HOUR_NO_SECONDS,
        DISPLAY_24_HOUR_NO_SECONDS,
        DISPLAY_12_HOUR,
        DISPLAY_24_HOUR
    };
Constructor & Destructor Documentation
DigitalClock()
DigitalClock ()
    : AbstractClock(),
      displayMode(DISPLAY_24_HOUR),
      useLeadingZeroForHourIndicator(false),
      text()
{
    buffer[0] = '\0';
    text.setXY(0, 0);
    text.setWildcard(buffer);
    AbstractClock::add(text);
}
References Container::add(), TextAreaWithOneWildcard::setWildcard(), Drawable::setXY(), and DigitalClock::text.
Member Function Documentation
displayLeadingZeroForHourIndicator()
void displayLeadingZeroForHourIndicator (bool displayLeadingZero)
Sets whether to display a leading zero for the hour indicator or not, when the hour value only has one digit. For example 8 can be displayed as "8:" (displayLeadingZero=false) or "08:" (displayLeadingZero=true).
Default value for this setting is false.
Parameters
displayLeadingZero true = show leading zero. false = do not show leading zero.
Note
This does not affect the display of minutes or seconds.
{
    useLeadingZeroForHourIndicator = displayLeadingZero;
}
References DigitalClock::useLeadingZeroForHourIndicator.
getAlpha()
uint8_t getAlpha () const virtual
Gets the current alpha value of the widget. The alpha value is in range 255 (solid) to 0 (invisible).
Returns
The current alpha value.
See also
setAlpha
{
    return text.getAlpha();
}
References TextArea::getAlpha(), and DigitalClock::text.
Referenced by DigitalClock::invalidateContent().
getColor()
colortype getColor () const virtual
Gets the color of the text.
Returns
The color.
{
    return text.getColor();
}
References TextArea::getColor(), and DigitalClock::text.
getDisplayMode()
virtual DisplayMode getDisplayMode () const inline virtual
Gets the current display mode.
Returns
The display mode.
See also
DisplayMode, setDisplayMode
    {
        return displayMode;
    }
References DigitalClock::displayMode.
getTextWidth()
virtual uint16_t getTextWidth () const inline virtual
Gets text width of the currently displayed DigitalClock.
Returns
The text width of the currently displayed DigitalClock.
    {
        return text.getTextWidth();
    }
References TextArea::getTextWidth(), and DigitalClock::text.
invalidateContent()
virtual void invalidateContent () const inline virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from Drawable.
    {
        if (getAlpha() > 0)
        {
            AbstractClock::invalidateContent();
        }
    }
References DigitalClock::getAlpha(), and Drawable::invalidateContent().
setAlpha()
void setAlpha (uint8_t newAlpha) virtual
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
{
    text.setAlpha(newAlpha);
}
References TextArea::setAlpha(), and DigitalClock::text.
setBaselineY()
void setBaselineY (int16_t baselineY) virtual
Adjusts the DigitalClock y coordinate so the text will have its baseline at the specified value. The placements is relative to the specified TypedText so if the TypedText is changed, you have to set the baseline again.
Parameters
baselineY The y coordinate of the baseline of the text.
Note
that setTypedText must be called prior to setting the baseline.
{
    if (text.getTypedText().hasValidId())
    {
        moveTo(getX(), baselineY - text.getTypedText().getFont()->getBaseline());
    }
}
References TextArea::getTypedText(), Drawable::getX(), Drawable::moveTo(), and DigitalClock::text.
setColor()
void setColor (colortype color) virtual
Sets the color of the text.
Parameters
color The new text color.
Note
Automatically invalidates the DigitalClock.
{
    // Do invlidateContent only once since the size does not change
    text.setColor(color);
    text.invalidateContent();
}
References TextAreaWithWildcardBase::invalidateContent(), TextArea::setColor(), and DigitalClock::text.
setDisplayMode()
virtual void setDisplayMode (DisplayMode dm) inline virtual
Sets the display mode to 12/24 hour clock with or without seconds.
Parameters
dm The new display mode.
See also
DisplayMode, getDisplayMode
    {
        displayMode = dm;
    }
References DigitalClock::displayMode.
setHeight()
void setHeight (int16_t height) virtual
Sets the height of this drawable.
Parameters
height The new height.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Reimplemented from Drawable.
{
    AbstractClock::setHeight(height);
    text.setHeight(height);
}
References Drawable::setHeight(), TextArea::setHeight(), and DigitalClock::text.
setTypedText()
void setTypedText (TypedText typedText) virtual
Sets the typed text of the DigitalClock. Expects a TypedText with one wildcard and that the following characters are defined for the typography of the TypedText:
12 hour clock: "AMP :0123456789"
24 hour clock: ":0123456789"
Parameters
typedText Describes the typed text to use.
Note
Automatically invalidates the DigitalClock.
{
    // Do invalidateContent before and after in case the size of the text changes
    text.invalidateContent();
    text.setTypedText(typedText);
    text.invalidateContent();
}
References TextAreaWithWildcardBase::invalidateContent(), TextArea::setTypedText(), and DigitalClock::text.
setWidth()
void setWidth (int16_t width) virtual
Sets the width of this drawable.
Parameters
width The new width.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Reimplemented from Drawable.
{
    AbstractClock::setWidth(width);
    text.setWidth(width);
}
References Drawable::setWidth(), TextArea::setWidth(), and DigitalClock::text.
updateClock()
void updateClock () protected virtual
Update the visual representation of the clock on the display.
Implements AbstractClock.
{
    text.invalidateContent();
    if (displayMode == DISPLAY_12_HOUR_NO_SECONDS)
    {
        const char* format = useLeadingZeroForHourIndicator ? "%02d:%02d %cM" : "%d:%02d %cM";
        Unicode::snprintf(buffer, BUFFER_SIZE, format, getCurrentHour12(), getCurrentMinute(), getCurrentAM() ? 'A' : 'P');
    }
    else if (displayMode == DISPLAY_24_HOUR_NO_SECONDS)
    {
        const char* format = useLeadingZeroForHourIndicator ? "%02d:%02d" : "%d:%02d";
        Unicode::snprintf(buffer, BUFFER_SIZE, format, getCurrentHour24(), getCurrentMinute());
    }
    else if (displayMode == DISPLAY_12_HOUR)
    {
        const char* format = useLeadingZeroForHourIndicator ? "%02d:%02d:%02d %cM" : "%d:%02d:%02d %cM";
        Unicode::snprintf(buffer, BUFFER_SIZE, format, getCurrentHour12(), getCurrentMinute(), getCurrentSecond(), getCurrentAM() ? 'A' : 'P');
    }
    else if (displayMode == DISPLAY_24_HOUR)
    {
        const char* format = useLeadingZeroForHourIndicator ? "%02d:%02d:%02d" : "%d:%02d:%02d";
        Unicode::snprintf(buffer, BUFFER_SIZE, format, getCurrentHour24(), getCurrentMinute(), getCurrentSecond());
    }
    text.invalidateContent();
}
References DigitalClock::BUFFER_SIZE, DigitalClock::DISPLAY_12_HOUR, DigitalClock::DISPLAY_12_HOUR_NO_SECONDS, DigitalClock::DISPLAY_24_HOUR, DigitalClock::DISPLAY_24_HOUR_NO_SECONDS, DigitalClock::displayMode, AbstractClock::getCurrentAM(), AbstractClock::getCurrentHour12(), AbstractClock::getCurrentHour24(), AbstractClock::getCurrentMinute(), AbstractClock::getCurrentSecond(), TextAreaWithWildcardBase::invalidateContent(), Unicode::snprintf(), DigitalClock::text, and DigitalClock::useLeadingZeroForHourIndicator.
Member Data Documentation
buffer
Unicode::UnicodeChar buffer[BUFFER_SIZE] protected
Wild card buffer for the clock text.
BUFFER_SIZE
const int BUFFER_SIZE = 12 static protected
Buffer size of the wild card, worst case is "12:59:59 AM" (12 chars)
Referenced by DigitalClock::updateClock().
displayMode
DisplayMode displayMode protected
The current display mode.
Referenced by DigitalClock::getDisplayMode(), DigitalClock::setDisplayMode(), and DigitalClock::updateClock().
text
TextAreaWithOneWildcard text protected
The clock text.
Referenced by DigitalClock::DigitalClock(), DigitalClock::getAlpha(), DigitalClock::getColor(), DigitalClock::getTextWidth(), DigitalClock::setAlpha(), DigitalClock::setBaselineY(), DigitalClock::setColor(), DigitalClock::setHeight(), DigitalClock::setTypedText(), DigitalClock::setWidth(), and DigitalClock::updateClock().
useLeadingZeroForHourIndicator
bool useLeadingZeroForHourIndicator protected
Print a leading zero if the hour is less than 10.
Referenced by DigitalClock::displayLeadingZeroForHourIndicator(), and DigitalClock::updateClock().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/clock/DigitalClock.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/clock/DigitalClock.cpp