Battery Simulator Documentation: Gauge
Gauge
#include "Gauge.hpp"
Public Member Functions
Gauge ()
Circle & getArc ()
virtual void getCenter (int &x, int &y) const
virtual int getEndAngle () const
virtual int getStartAngle () const
virtual void invalidateContent () const
void putArcOnTop (bool arcOnTop=true)
virtual void setAlpha (uint8_t newAlpha)
void setArcPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setArcVisible (bool show=true)
void setBackgroundOffset (int16_t offsetX, int16_t offsetY)
virtual void setCenter (int x, int y)
virtual void setHeight (int16_t height)
void setMovingNeedleRenderingAlgorithm (TextureMapper::RenderingAlgorithm algorithm)
void setNeedle (const BitmapId bitmapId, int16_t rotationCenterX, int16_t rotationCenterY)
virtual void setStartEndAngle (int startAngle, int endAngle)
void setSteadyNeedleRenderingAlgorithm (TextureMapper::RenderingAlgorithm algorithm)
virtual void setValue (int value)
virtual void setWidth (int16_t width)
Public Member Functions inherited from AbstractProgressIndicator
AbstractProgressIndicator ()
virtual uint8_t getAlpha () const
virtual uint16_t getProgress (uint16_t range=100) const
virtual int16_t getProgressIndicatorHeight () const
virtual int16_t getProgressIndicatorWidth () const
virtual int16_t getProgressIndicatorX () const
virtual int16_t getProgressIndicatorY () const
virtual void getRange (int &min, int &max) const
virtual void getRange (int &min, int &max, uint16_t &steps) const
virtual void getRange (int &min, int &max, uint16_t &steps, uint16_t &minStep) const
virtual int getValue () const
virtual void handleTickEvent ()
virtual void setBackground (const Bitmap &bitmapBackground)
virtual void setEasingEquation (EasingEquation easingEquation)
virtual void setRange (int min, int max, uint16_t steps=0, uint16_t minStep=0)
void setValueSetAction (GenericCallback< const AbstractProgressIndicator & > &callback)
void setValueUpdatedAction (GenericCallback< const AbstractProgressIndicator & > &callback)
virtual void updateValue (int value, uint16_t duration)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual void setProgressIndicatorPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setupNeedleTextureMapper ()
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
TextureMapper::RenderingAlgorithm algorithmMoving
The algorithm used when the needle is moving.
TextureMapper::RenderingAlgorithm algorithmSteady
The algorithm used when the needle is steady.
Circle arc
The arc.
int16_t gaugeCenterX
The x coordinate of the rotation point of the hands.
int16_t gaugeCenterY
The y coordinate of the rotation point of the hands.
TextureMapper needle
The textureMapper.
int16_t needleCenterX
The x coordinate of the rotation point of the hands.
int16_t needleCenterY
The y coordinate of the rotation point of the hands.
int needleEndAngle
The end angle in degrees.
int needleStartAngle
The start angle in degrees.
Protected Attributes inherited from AbstractProgressIndicator
int animationDuration
Duration of the animation.
int animationEndValue
The animation end value.
bool animationRunning
Is the animation running.
int animationStartValue
The animation start value.
int animationStep
The current animation step.
Image background
The background image.
int currentValue
The current value.
EasingEquation equation
The equation used in updateValue()
Container progressIndicatorContainer
The container that holds the actual progress indicator.
int rangeMax
The range maximum.
int rangeMin
The range minimum.
uint16_t rangeSteps
The range steps.
uint16_t rangeStepsMin
The range steps minimum.
GenericCallback< const AbstractProgressIndicator & > * valueSetCallback
New value assigned Callback.
GenericCallback< const AbstractProgressIndicator & > * valueUpdatedCallback
Animation ended Callback.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A gauge is a graphical element that shows a needle on a dial, often a speedometer or similar. Much like a progress indicator, the minimum and maximum value of the Gauge, as well as steps can be set. For more information on this, consult the documentation on ProgressIndicators.
A Gauge has a needle and optionally an arc that follows the needle.
Constructor & Destructor Documentation
Gauge()
Gauge ()
Initializes a new instance of the Gauge class.
    : AbstractProgressIndicator(),
      needle(),
      algorithmMoving(TextureMapper::BILINEAR_INTERPOLATION),
      algorithmSteady(TextureMapper::BILINEAR_INTERPOLATION),
      needleStartAngle(0),
      needleEndAngle(0),
      gaugeCenterX(0),
      gaugeCenterY(0),
      needleCenterX(0),
      needleCenterY(0),
      arc()
{
    Gauge::remove(progressIndicatorContainer);
    Gauge::add(arc);
    Gauge::add(needle);
    arc.setVisible(false);
}
References Container::add(), Gauge::arc, Gauge::needle, AbstractProgressIndicator::progressIndicatorContainer, Container::remove(), and Drawable::setVisible().
Member Function Documentation
getArc()
Circle & getArc ()
Gets a reference to the arc (Circle). This allows for setting radius, line width, painter, etc. on the arc (Circle).
Returns
The arc (Circle).
{
    return arc; //lint !e1536
}
References Gauge::arc.
getCenter()
virtual void getCenter (int & x, int & y) const inline virtual
Gets the texture mapper center coordinates.
Parameters
[out] x The x coordinate of the center of the texture mapper.
[out] y The y coordinate of the center of the texture mapper.
See also
setCenter
    {
        x = gaugeCenterX;
        y = gaugeCenterY;
    }
References Gauge::gaugeCenterX, and Gauge::gaugeCenterY.
getEndAngle()
int getEndAngle () const virtual
Gets end angle in degrees. Beware that the value returned is not related to the current progress of the texture mapper but rather the end point of the Gauge when it is at max value.
Returns
The end angle.
See also
setStartEndAngle
Note
Angles are given in degrees, so a full circle is 360.
{
    return needleEndAngle;
}
References Gauge::needleEndAngle.
getStartAngle()
int getStartAngle () const virtual
Gets start angle in degrees for the needle (and arc).
Returns
The start angle.
See also
setStartEndAngle, getEndAngle
Note
Angles are given in degrees, so a full circle is 360.
{
    return needleStartAngle;
}
References Gauge::needleStartAngle.
invalidateContent()
virtual void invalidateContent () const inline virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from AbstractProgressIndicator.
    {
        if (getAlpha() > 0)
        {
            AbstractProgressIndicator::invalidateContent();
        }
    }
References AbstractProgressIndicator::getAlpha(), and AbstractProgressIndicator::invalidateContent().
putArcOnTop()
void putArcOnTop (bool arcOnTop = true)
Shows the arc on top of the needle. By default the needle is drawn on top of the arc.
Parameters
arcOnTop (Optional) True to put the arc on top of the needle (default), false to put the needle on top of the arc.
{
    if (onTop)
    {
        remove(arc);
        add(arc);
    }
    else
    {
        remove(needle);
        add(needle);
    }
}
References Container::add(), Gauge::arc, Gauge::needle, and Container::remove().
setAlpha()
void setAlpha (uint8_t newAlpha) virtual
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
Reimplemented from AbstractProgressIndicator.
{
    AbstractProgressIndicator::setAlpha(newAlpha);
    needle.setAlpha(newAlpha);
    arc.setAlpha(newAlpha);
}
References Gauge::arc, Gauge::needle, AbstractProgressIndicator::setAlpha(), CanvasWidget::setAlpha(), and Image::setAlpha().
setArcPosition()
void setArcPosition (int16_t x, int16_t y, int16_t width, int16_t height)
Sets arc position inside the Gauge. This is especially useful if the arc is using a bitmap painter. If the center has previously been set, the arc center will be updated to be at the same offset relative to the top left corner of the Gauge.
Parameters
x The x coordinate.
y The y coordinate.
width The width.
height The height.
See also
setCenter, getArc
{
    arc.setPosition(x, y, width, height);
    arc.setPixelCenter(gaugeCenterX - x, gaugeCenterY - y);
}
References Gauge::arc, Gauge::gaugeCenterX, Gauge::gaugeCenterY, Circle::setPixelCenter(), and Drawable::setPosition().
setArcVisible()
void setArcVisible (bool show = true)
Allow the arc to be shown or hidden.
Parameters
show (Optional) True to show, false to hide. Default is to show the arc.
{
    arc.setVisible(show);
}
References Gauge::arc, and Drawable::setVisible().
setBackgroundOffset()
void setBackgroundOffset (int16_t offsetX, int16_t offsetY)
Sets background offset inside the Gauge. If the dial is smaller than the size needed for the Gauge to show the needle, the background image can be moved inside the Gauge.
Parameters
offsetX The offset x coordinate.
offsetY The offset y coordinate.
See also
setBackground
{
    background.setXY(offsetX, offsetY);
}
References AbstractProgressIndicator::background, and Drawable::setXY().
setCenter()
void setCenter (int x, int y) virtual
Sets the center of the texture mapper and the arc inside the Gauge.
Parameters
x The x coordinate of the center of the texture mapper.
y The y coordinate of the center of the texture mapper.
See also
getCenter
{
    gaugeCenterX = x;
    gaugeCenterY = y;
    setupNeedleTextureMapper();
    arc.setPixelCenter(x - arc.getX(), y - arc.getY());
}
References Gauge::arc, Gauge::gaugeCenterX, Gauge::gaugeCenterY, Drawable::getX(), Drawable::getY(), Circle::setPixelCenter(), and Gauge::setupNeedleTextureMapper().
setHeight()
void setHeight (int16_t height) virtual
Sets the height of this drawable.
Parameters
height The new height.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Reimplemented from Drawable.
{
    AbstractProgressIndicator::setHeight(height);
    needle.setHeight(height);
    arc.setHeight(height);
}
References Gauge::arc, Gauge::needle, and Drawable::setHeight().
setMovingNeedleRenderingAlgorithm()
void setMovingNeedleRenderingAlgorithm (TextureMapper::RenderingAlgorithm algorithm)
Sets rendering algorithm used when the needle is moving during an animation. For better performance, this can be set to TextureMapper::NEAREST_NEIGHBOR. For nicer graphics, it should be set to TextureMapper::BILINEAR_INTERPOLATION (this is the default behavior).
Parameters
algorithm The algorithm.
See also
updateValue, setSteadyNeedleRenderingAlgorithm
{
    algorithmMoving = algorithm;
}
References Gauge::algorithmMoving.
setNeedle()
void setNeedle (const BitmapId bitmapId, int16_t rotationCenterX, int16_t rotationCenterY)
Sets a bitmap for the needle and the rotation point in the needle bitmap.
Parameters
bitmapId Identifier for the bitmap.
rotationCenterX The rotation center x coordinate.
rotationCenterY The rotation center y coordinate.
{
    needle.setBitmap(Bitmap(bitmapId));
    needleCenterX = rotationCenterX;
    needleCenterY = rotationCenterY;
    setupNeedleTextureMapper();
}
References Gauge::needle, Gauge::needleCenterX, Gauge::needleCenterY, TextureMapper::setBitmap(), and Gauge::setupNeedleTextureMapper().
setProgressIndicatorPosition()
void setProgressIndicatorPosition (int16_t x, int16_t y, int16_t width, int16_t height) protected virtual
This function has no effect on a Gauge.
Parameters
x unused
y unused
width unused
height unused
Reimplemented from AbstractProgressIndicator.
{
}
setStartEndAngle()
void setStartEndAngle (int startAngle, int endAngle) virtual
Sets start and end angle in degrees for the needle and arc. By swapping end and start angles, these can progress backwards.
Parameters
startAngle The start angle.
endAngle The end angle.
Note
Angles are given in degrees, so a full circle is 360.
{
    assert(startAngle != endAngle);
    needleStartAngle = startAngle;
    needleEndAngle = endAngle;
    arc.setArc(startAngle, endAngle);
    Gauge::setValue(Gauge::getValue());
}
References Gauge::arc, AbstractProgressIndicator::getValue(), Gauge::needleEndAngle, Gauge::needleStartAngle, Circle::setArc(), and Gauge::setValue().
setSteadyNeedleRenderingAlgorithm()
void setSteadyNeedleRenderingAlgorithm (TextureMapper::RenderingAlgorithm algorithm)
Sets rendering algorithm used when the needle is steady (after an animation). For better performance, this can be set to TextureMapper::NEAREST_NEIGHBOR. For nicer graphics, it should be set to TextureMapper::BILINEAR_INTERPOLATION (this is the default behavior).
Parameters
algorithm The algorithm.
See also
updateValue, setMovingNeedleRenderingAlgorithm
{
    algorithmSteady = algorithm;
}
References Gauge::algorithmSteady.
setupNeedleTextureMapper()
void setupNeedleTextureMapper () protected
Sets up the needle texture mapper.
{
    needle.setWidthHeight(*this);
    needle.setXY(0, 0);
    needle.setBitmapPosition(gaugeCenterX - needleCenterX, gaugeCenterY - needleCenterY);
    needle.setCameraDistance(300.0f);
    needle.setOrigo((float)gaugeCenterX, (float)gaugeCenterY, needle.getCameraDistance());
    needle.setCamera(needle.getOrigoX(), needle.getOrigoY());
    needle.setRenderingAlgorithm(TextureMapper::BILINEAR_INTERPOLATION);
}
References TextureMapper::BILINEAR_INTERPOLATION, Gauge::gaugeCenterX, Gauge::gaugeCenterY, TextureMapper::getCameraDistance(), TextureMapper::getOrigoX(), TextureMapper::getOrigoY(), Gauge::needle, Gauge::needleCenterX, Gauge::needleCenterY, TextureMapper::setBitmapPosition(), TextureMapper::setCamera(), TextureMapper::setCameraDistance(), TextureMapper::setOrigo(), TextureMapper::setRenderingAlgorithm(), Drawable::setWidthHeight(), and Drawable::setXY().
Referenced by Gauge::setCenter(), and Gauge::setNeedle().
setValue()
void setValue (int value) virtual
Sets the current value in the range (min..max) set by setRange(). Values lower than min are mapped to min, values higher than max are mapped to max. If a callback function has been set using setValueSetAction, that callback will be called (unless the new value is the same as the current value).
Parameters
value The value.
See also
getValue, updateValue, setValueSetAction
Note
if value is equal to the current value, nothing happens, and the callback will not be called.
Reimplemented from AbstractProgressIndicator.
{
    AbstractProgressIndicator::setValue(value);
    if (animationStep >= animationDuration)
    {
        needle.setRenderingAlgorithm(algorithmSteady);
    }
    else
    {
        needle.setRenderingAlgorithm(algorithmMoving);
    }
    const uint16_t progress = AbstractProgressIndicator::getProgress(abs(needleEndAngle - needleStartAngle));
    if (needleEndAngle < needleStartAngle)
    {
        needle.updateZAngle(((float)(needleStartAngle - progress) / 180.0f) * PI);
        arc.updateArcEnd(needleStartAngle - progress);
    }
    else
    {
        needle.updateZAngle(((float)(needleStartAngle + progress) / 180.0f) * PI);
        arc.updateArcEnd(needleStartAngle + progress);
    }
}
References touchgfx::abs(), Gauge::algorithmMoving, Gauge::algorithmSteady, AbstractProgressIndicator::animationDuration, AbstractProgressIndicator::animationStep, Gauge::arc, AbstractProgressIndicator::getProgress(), Gauge::needle, Gauge::needleEndAngle, Gauge::needleStartAngle, touchgfx::PI, progress, TextureMapper::setRenderingAlgorithm(), AbstractProgressIndicator::setValue(), Circle::updateArcEnd(), and TextureMapper::updateZAngle().
Referenced by Gauge::setStartEndAngle().
setWidth()
void setWidth (int16_t width) virtual
Sets the width of this drawable.
Parameters
width The new width.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Reimplemented from Drawable.
{
    AbstractProgressIndicator::setWidth(width);
    needle.setWidth(width);
    arc.setWidth(width);
}
References Gauge::arc, Gauge::needle, and Drawable::setWidth().
Member Data Documentation
algorithmMoving
TextureMapper::RenderingAlgorithm algorithmMoving protected
The algorithm used when the needle is moving.
Referenced by Gauge::setMovingNeedleRenderingAlgorithm(), and Gauge::setValue().
algorithmSteady
TextureMapper::RenderingAlgorithm algorithmSteady protected
The algorithm used when the needle is steady.
Referenced by Gauge::setSteadyNeedleRenderingAlgorithm(), and Gauge::setValue().
arc
Circle arc protected
The arc.
Referenced by Gauge::Gauge(), Gauge::getArc(), Gauge::putArcOnTop(), Gauge::setAlpha(), Gauge::setArcPosition(), Gauge::setArcVisible(), Gauge::setCenter(), Gauge::setHeight(), Gauge::setStartEndAngle(), Gauge::setValue(), and Gauge::setWidth().
gaugeCenterX
int16_t gaugeCenterX protected
The x coordinate of the rotation point of the hands.
Referenced by Gauge::getCenter(), Gauge::setArcPosition(), Gauge::setCenter(), and Gauge::setupNeedleTextureMapper().
gaugeCenterY
int16_t gaugeCenterY protected
The y coordinate of the rotation point of the hands.
Referenced by Gauge::getCenter(), Gauge::setArcPosition(), Gauge::setCenter(), and Gauge::setupNeedleTextureMapper().
needle
TextureMapper needle protected
The textureMapper.
Referenced by Gauge::Gauge(), Gauge::putArcOnTop(), Gauge::setAlpha(), Gauge::setHeight(), Gauge::setNeedle(), Gauge::setupNeedleTextureMapper(), Gauge::setValue(), and Gauge::setWidth().
needleCenterX
int16_t needleCenterX protected
The x coordinate of the rotation point of the hands.
Referenced by Gauge::setNeedle(), and Gauge::setupNeedleTextureMapper().
needleCenterY
int16_t needleCenterY protected
The y coordinate of the rotation point of the hands.
Referenced by Gauge::setNeedle(), and Gauge::setupNeedleTextureMapper().
needleEndAngle
int needleEndAngle protected
The end angle in degrees.
Referenced by Gauge::getEndAngle(), Gauge::setStartEndAngle(), and Gauge::setValue().
needleStartAngle
int needleStartAngle protected
The start angle in degrees.
Referenced by Gauge::getStartAngle(), Gauge::setStartEndAngle(), and Gauge::setValue().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/Gauge.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/Gauge.cpp