Battery Simulator Documentation: BoxProgress
BoxProgress
#include "BoxProgress.hpp"
Public Member Functions
BoxProgress ()
virtual colortype getColor () const
virtual void setAlpha (uint8_t newAlpha)
virtual void setColor (colortype color)
virtual void setProgressIndicatorPosition (int16_t x, int16_t y, int16_t width, int16_t height)
virtual void setValue (int value)
Public Member Functions inherited from AbstractDirectionProgress
AbstractDirectionProgress ()
virtual DirectionType getDirection () const
virtual void setDirection (DirectionType direction)
Public Member Functions inherited from AbstractProgressIndicator
AbstractProgressIndicator ()
virtual uint8_t getAlpha () const
virtual uint16_t getProgress (uint16_t range=100) const
virtual int16_t getProgressIndicatorHeight () const
virtual int16_t getProgressIndicatorWidth () const
virtual int16_t getProgressIndicatorX () const
virtual int16_t getProgressIndicatorY () const
virtual void getRange (int &min, int &max) const
virtual void getRange (int &min, int &max, uint16_t &steps) const
virtual void getRange (int &min, int &max, uint16_t &steps, uint16_t &minStep) const
virtual int getValue () const
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void setBackground (const Bitmap &bitmapBackground)
virtual void setEasingEquation (EasingEquation easingEquation)
virtual void setRange (int min, int max, uint16_t steps=0, uint16_t minStep=0)
void setValueSetAction (GenericCallback< const AbstractProgressIndicator & > &callback)
void setValueUpdatedAction (GenericCallback< const AbstractProgressIndicator & > &callback)
virtual void updateValue (int value, uint16_t duration)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
Box box
The box.
Protected Attributes inherited from AbstractDirectionProgress
DirectionType progressDirection
The progress direction.
Protected Attributes inherited from AbstractProgressIndicator
int animationDuration
Duration of the animation.
int animationEndValue
The animation end value.
bool animationRunning
Is the animation running.
int animationStartValue
The animation start value.
int animationStep
The current animation step.
Image background
The background image.
int currentValue
The current value.
EasingEquation equation
The equation used in updateValue()
Container progressIndicatorContainer
The container that holds the actual progress indicator.
int rangeMax
The range maximum.
int rangeMin
The range minimum.
uint16_t rangeSteps
The range steps.
uint16_t rangeStepsMin
The range steps minimum.
GenericCallback< const AbstractProgressIndicator & > * valueSetCallback
New value assigned Callback.
GenericCallback< const AbstractProgressIndicator & > * valueUpdatedCallback
Animation ended Callback.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Public Types inherited from AbstractDirectionProgress
enum DirectionType { RIGHT , LEFT , DOWN , UP }
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Detailed Description
A BoxProgress which shows the current progress using a simple Box. It is possible to set the color and the alpha of the box. It is also possible to control in what direction the box will progress (up, down, to the left or to the right).
Constructor & Destructor Documentation
BoxProgress()
BoxProgress ()
    : AbstractDirectionProgress(), box()
{
    progressIndicatorContainer.add(box);
}
References Container::add(), BoxProgress::box, and AbstractProgressIndicator::progressIndicatorContainer.
Member Function Documentation
getColor()
colortype getColor () const virtual
Gets the color of the Box.
Returns
The color.
See also
setColor
{
    return box.getColor();
}
References BoxProgress::box, and Box::getColor().
setAlpha()
void setAlpha (uint8_t newAlpha) virtual
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
Reimplemented from AbstractProgressIndicator.
{
    AbstractDirectionProgress::setAlpha(newAlpha);
    box.setAlpha(newAlpha);
}
References BoxProgress::box, AbstractProgressIndicator::setAlpha(), and Box::setAlpha().
setColor()
void setColor (colortype color) virtual
Sets the color of the Box.
Parameters
color The color.
See also
getColor
{
    box.setColor(color);
}
References BoxProgress::box, and Box::setColor().
setProgressIndicatorPosition()
void setProgressIndicatorPosition (int16_t x, int16_t y, int16_t width, int16_t height) virtual
Sets the position and dimensions of the actual progress indicator relative to the background image.
Parameters
x The x coordinate.
y The y coordinate.
width The width of the box progress indicator.
height The height of the box progress indicator.
See also
getProgressIndicatorX, getProgressIndicatorY, getProgressIndicatorWidth, getProgressIndicatorHeight
Reimplemented from AbstractProgressIndicator.
{
    box.setPosition(0, 0, width, height);
    AbstractDirectionProgress::setProgressIndicatorPosition(x, y, width, height);
}
References BoxProgress::box, Drawable::setPosition(), and AbstractProgressIndicator::setProgressIndicatorPosition().
setValue()
void setValue (int value) virtual
Sets the current value in the range (min..max) set by setRange(). Values lower than min are mapped to min, values higher than max are mapped to max. If a callback function has been set using setValueSetAction, that callback will be called (unless the new value is the same as the current value).
Parameters
value The value.
See also
getValue, updateValue, setValueSetAction
Note
if value is equal to the current value, nothing happens, and the callback will not be called.
Reimplemented from AbstractProgressIndicator.
{
    AbstractDirectionProgress::setValue(value);
    int16_t progress = 0;
    switch (progressDirection)
    {
    case RIGHT:
    case LEFT:
        progress = AbstractDirectionProgress::getProgress(progressIndicatorContainer.getWidth());
        break;
    case DOWN:
    case UP:
        progress = AbstractDirectionProgress::getProgress(progressIndicatorContainer.getHeight());
        break;
    }
    switch (progressDirection)
    {
    case RIGHT:
        {
            const int16_t oldWidth = box.getWidth();
            box.setPosition(0, 0, progress, progressIndicatorContainer.getHeight());
            const int16_t newWidth = box.getWidth();
            Rect r(MIN(oldWidth, newWidth), 0, abs(oldWidth - newWidth), box.getHeight());
            progressIndicatorContainer.invalidateRect(r);
            break;
        }
    case LEFT:
        {
            const int16_t oldX = box.getX();
            box.setPosition(getWidth() - progress, 0, progress, progressIndicatorContainer.getHeight());
            const int16_t newX = box.getX();
            Rect r(MIN(oldX, newX), 0, abs(oldX - newX), box.getHeight());
            progressIndicatorContainer.invalidateRect(r);
            break;
        }
    case DOWN:
        {
            const int16_t oldHeight = box.getHeight();
            box.setPosition(0, 0, progressIndicatorContainer.getWidth(), progress);
            const int16_t newHeight = box.getHeight();
            Rect r(0, MIN(oldHeight, newHeight), box.getWidth(), abs(oldHeight - newHeight));
            progressIndicatorContainer.invalidateRect(r);
            break;
        }
    case UP:
        {
            const int16_t oldY = box.getY();
            box.setPosition(0, progressIndicatorContainer.getHeight() - progress, progressIndicatorContainer.getWidth(), progress);
            const int16_t newY = box.getY();
            Rect r(0, MIN(oldY, newY), box.getWidth(), abs(oldY - newY));
            progressIndicatorContainer.invalidateRect(r);
            break;
        }
    }
}
References touchgfx::abs(), BoxProgress::box, AbstractDirectionProgress::DOWN, Drawable::getHeight(), AbstractProgressIndicator::getProgress(), Drawable::getWidth(), Drawable::getX(), Drawable::getY(), Drawable::invalidateRect(), AbstractDirectionProgress::LEFT, MIN, progress, AbstractDirectionProgress::progressDirection, AbstractProgressIndicator::progressIndicatorContainer, AbstractDirectionProgress::RIGHT, Drawable::setPosition(), AbstractProgressIndicator::setValue(), and AbstractDirectionProgress::UP.
Member Data Documentation
box
Box box protected
The box.
Referenced by BoxProgress::BoxProgress(), BoxProgress::getColor(), BoxProgress::setAlpha(), BoxProgress::setColor(), BoxProgress::setProgressIndicatorPosition(), and BoxProgress::setValue().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/progress_indicators/BoxProgress.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/progress_indicators/BoxProgress.cpp