Battery Simulator Documentation: TextureMapper
TextureMapper
#include "TextureMapper.hpp"
Public Types
enum RenderingAlgorithm { NEAREST_NEIGHBOR , BILINEAR_INTERPOLATION }
Public Member Functions
TextureMapper (const Bitmap &bmp=Bitmap())
virtual void draw (const Rect &invalidatedArea) const
virtual float getBitmapPositionX () const
virtual float getBitmapPositionY () const
virtual float getCameraDistance () const
virtual float getCameraX () const
virtual float getCameraY () const
virtual float getOrigoX () const
virtual float getOrigoY () const
virtual float getOrigoZ () const
virtual RenderingAlgorithm getRenderingAlgorithm () const
virtual float getScale () const
virtual Rect getSolidRect () const
virtual float getX0 () const
virtual float getX1 () const
virtual float getX2 () const
virtual float getX3 () const
virtual float getXAngle () const
virtual float getY0 () const
virtual float getY1 () const
virtual float getY2 () const
virtual float getY3 () const
virtual float getYAngle () const
virtual float getZ0 () const
virtual float getZ1 () const
virtual float getZ2 () const
virtual float getZ3 () const
virtual float getZAngle () const
virtual void invalidateContent () const
virtual void setAngles (float newXAngle, float newYAngle, float newZAngle)
virtual void setBitmap (const Bitmap &bmp)
virtual void setBitmapPosition (float x, float y)
virtual void setBitmapPosition (int x, int y)
virtual void setCamera (float x, float y)
virtual void setCameraDistance (float d)
virtual void setOrigo (float x, float y)
virtual void setOrigo (float x, float y, float z)
virtual void setRenderingAlgorithm (RenderingAlgorithm algorithm)
virtual void setScale (float newScale)
virtual void setXAngle (float newXAngle)
virtual void setYAngle (float newYAngle)
virtual void setZAngle (float newZAngle)
TOUCHGFX_DEPRECATED ("Please use invalidateContent() instead.", void invalidateBoundingRect() const)
virtual void updateAngles (float newXAngle, float newYAngle, float newZAngle)
virtual void updateScale (float newScale)
virtual void updateXAngle (float newXAngle)
virtual void updateYAngle (float newYAngle)
virtual void updateZAngle (float newZAngle)
Public Member Functions inherited from Image
Image (const Bitmap &bmp=Bitmap())
uint8_t getAlpha () const
Bitmap getBitmap () const
BitmapId getBitmapId () const
void setAlpha (uint8_t newAlpha)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
void applyTransformation ()
void drawQuad (const Rect &invalidatedArea, uint16_t *fb, const float *triangleXs, const float *triangleYs, const float *triangleZs, const float *triangleUs, const float *triangleVs) const
Rect getBoundingRect () const
RenderingVariant lookupRenderVariant () const
Protected Attributes
float cameraDistance
The camera distance.
RenderingAlgorithm currentRenderingAlgorithm
The current rendering algorithm.
float imageX0
The coordinate for the image points.
float imageX1
The coordinate for the image points.
float imageX2
The coordinate for the image points.
float imageX3
The coordinate for the image points.
float imageY0
The coordinate for the image points.
float imageY1
The coordinate for the image points.
float imageY2
The coordinate for the image points.
float imageY3
The coordinate for the image points.
float imageZ0
The coordinate for the image points.
float imageZ1
The coordinate for the image points.
float imageZ2
The coordinate for the image points.
float imageZ3
The coordinate for the image points.
float scale
The scale.
uint16_t subDivisionSize
The size of the affine sub divisions.
float xAngle
The angle x in radians.
float xBitmapPosition
The bitmap position x.
float xCamera
The camera x coordinate.
float xOrigo
The origo x coordinate.
float yAngle
The angle y in radians.
float yBitmapPosition
The bitmap position y.
float yCamera
The camera y coordinate.
float yOrigo
The origo y coordinate.
float zAngle
The angle z in radians.
float zOrigo
The origo z coordinate.
Protected Attributes inherited from Image
uint8_t alpha
The Alpha for this image.
Bitmap bitmap
The Bitmap to display.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Static Protected Attributes
static const int MINIMAL_CAMERA_DISTANCE = 1
The minimal camera distance.
Detailed Description
The TextureMapper widget displays a transformed image. It can be used to generate effects where an image should be rotated in two or three dimensions.
The image can be freely scaled and rotated in three dimensions. The scaling and rotation is done around the adjustable origin. A virtual camera is applied to the rendered image yielding a perspective impression. The amount of perspective impression can be adjusted. The transformed image is clipped according to the dimensions of the TextureMapper widget. In order to make the image fully visible the TextureMapper should be large enough to accommodate the transformed image, which may be larger than the raw image.
See also
Widget
Note
The drawing of this widget is not trivial and typically has a significant performance penalty. The number of pixels drawn, the presence of global alpha or per pixel alpha inflicts the computation and should be considered.
This widget does not support 1 bit per pixel color depth.
Member Enumeration Documentation
RenderingAlgorithm
enum RenderingAlgorithm
Rendering algorithm to use when scaling the bitmap. Nearest neighbor simply finds the closest pixel in the source bitmap. Bilinear interpolation averages 4 pixels to find a much better pixel representation, and is therefore slower than the Nearest neighbor algorithm.
Enumerator
NEAREST_NEIGHBOR
Fast but not a very good image quality. Good for fast animations.
BILINEAR_INTERPOLATION
Slower but better image quality. Good for static representation of a scaled image.
    {
        NEAREST_NEIGHBOR,
        BILINEAR_INTERPOLATION
    };
Constructor & Destructor Documentation
TextureMapper()
TextureMapper (const Bitmap & bmp = Bitmap())
Constructs a new TextureMapper with a default alpha value of 255 (solid) and a default Bitmap (undefined) if none is specified. If a Bitmap is passed to the constructor, the width and height of this widget is set to those of the bitmap.
Parameters
bmp (Optional) The bitmap to display.
See also
setBitmap
    : Image(bmp),
      currentRenderingAlgorithm(NEAREST_NEIGHBOR),
      xBitmapPosition(0.0f),
      yBitmapPosition(0.0f),
      xAngle(0.0f),
      yAngle(0.0f),
      zAngle(0.0f),
      scale(1.0f),
      xOrigo(0.0f),
      yOrigo(0.0f),
      zOrigo(1000.0f),
      xCamera(0.0f),
      yCamera(0.0f),
      cameraDistance(1000.0f),
      imageX0(0.0f),
      imageY0(0.0f),
      imageZ0(1.0f),
      imageX1(0.0f),
      imageY1(0.0f),
      imageZ1(1.0f),
      imageX2(0.0f),
      imageY2(0.0f),
      imageZ2(1.0f),
      imageX3(0.0f),
      imageY3(0.0f),
      imageZ3(1.0f),
      subDivisionSize(12)
{
}
Member Function Documentation
applyTransformation()
void applyTransformation () protected
Transform the bitmap using the supplied origo, scale, rotation and camera. This method is called by all the methods that manipulate origo, scale, rotation and camera.
{
    const uint8_t n = 4;
    const int imgWidth = Bitmap(bitmap).getWidth() + 1;
    const int imgHeight = Bitmap(bitmap).getHeight() + 1;
    const Point4 vertices[n] = {
        Point4(xBitmapPosition - 1, yBitmapPosition - 1, cameraDistance),
        Point4((xBitmapPosition - 1) + imgWidth, yBitmapPosition - 1, cameraDistance),
        Point4((xBitmapPosition - 1) + imgWidth, (yBitmapPosition - 1) + imgHeight, cameraDistance),
        Point4(xBitmapPosition - 1, (yBitmapPosition - 1) + imgHeight, cameraDistance),
    };
    Point4 transformed[n];
    const Vector4 tm_center(xOrigo, yOrigo, zOrigo);
    Matrix4x4 translateToCenter;
    translateToCenter.concatenateXTranslation(-tm_center.getX()).concatenateYTranslation(-tm_center.getY()).concatenateZTranslation(-tm_center.getZ());
    Matrix4x4 rotateAroundCenter;
    rotateAroundCenter.concatenateXRotation(xAngle).concatenateYRotation(yAngle).concatenateZRotation(zAngle);
    Matrix4x4 scaleAroundCenter;
    scaleAroundCenter.concatenateXScale(scale).concatenateYScale(scale).concatenateZScale(scale);
    Matrix4x4 translateFromCenter;
    translateFromCenter.concatenateXTranslation(tm_center.getX()).concatenateYTranslation(tm_center.getY()).concatenateZTranslation(tm_center.getZ());
    Matrix4x4 transform = translateFromCenter * scaleAroundCenter * rotateAroundCenter * translateToCenter;
    Matrix4x4 translateToCamera;
    translateToCamera.concatenateXTranslation(-xCamera);
    translateToCamera.concatenateYTranslation(-yCamera);
    Matrix4x4 perspectiveProject;
    perspectiveProject.setViewDistance(cameraDistance);
    Matrix4x4 translateFromCamera;
    translateFromCamera.concatenateXTranslation(xCamera).concatenateYTranslation(yCamera);
    transform = translateFromCamera * perspectiveProject * translateToCamera * transform;
    for (int i = 0; i < n; i++)
    {
        transformed[i] = transform * vertices[i];
    }
    imageX0 = ((float)transformed[0].getX() * cameraDistance / (float)transformed[0].getZ());
    imageY0 = ((float)transformed[0].getY() * cameraDistance / (float)transformed[0].getZ());
    imageZ0 = ((float)transformed[0].getZ());
    imageX1 = ((float)transformed[1].getX() * cameraDistance / (float)transformed[1].getZ());
    imageY1 = ((float)transformed[1].getY() * cameraDistance / (float)transformed[1].getZ());
    imageZ1 = ((float)transformed[1].getZ());
    imageX2 = ((float)transformed[2].getX() * cameraDistance / (float)transformed[2].getZ());
    imageY2 = ((float)transformed[2].getY() * cameraDistance / (float)transformed[2].getZ());
    imageZ2 = ((float)transformed[2].getZ());
    imageX3 = ((float)transformed[3].getX() * cameraDistance / (float)transformed[3].getZ());
    imageY3 = ((float)transformed[3].getY() * cameraDistance / (float)transformed[3].getZ());
    imageZ3 = ((float)transformed[3].getZ());
}
References TextureMapper::cameraDistance, Bitmap::getHeight(), Bitmap::getWidth(), Drawable::getX(), Drawable::getY(), TextureMapper::imageX0, TextureMapper::imageX1, TextureMapper::imageX2, TextureMapper::imageX3, TextureMapper::imageY0, TextureMapper::imageY1, TextureMapper::imageY2, TextureMapper::imageY3, TextureMapper::imageZ0, TextureMapper::imageZ1, TextureMapper::imageZ2, TextureMapper::imageZ3, TextureMapper::xAngle, TextureMapper::xBitmapPosition, TextureMapper::xCamera, TextureMapper::xOrigo, TextureMapper::yAngle, TextureMapper::yBitmapPosition, TextureMapper::yCamera, TextureMapper::yOrigo, TextureMapper::zAngle, and TextureMapper::zOrigo.
Referenced by TextureMapper::setAngles(), TextureMapper::setBitmap(), TextureMapper::setBitmapPosition(), TextureMapper::setCamera(), TextureMapper::setCameraDistance(), TextureMapper::setOrigo(), TextureMapper::setOrigo(), and TextureMapper::setScale().
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Reimplemented from Image.
{
    if (!alpha)
    {
        return;
    }
    uint16_t* fb = 0;
    // Setup texture coordinates
    const float right = (float)(bitmap.getWidth());
    const float bottom = (float)(bitmap.getHeight());
    float textureU0 = -1.0f;
    float textureV0 = -1.0f;
    float textureU1 = right;
    float textureV1 = -1.0f;
    float textureU2 = right;
    float textureV2 = bottom;
    float textureU3 = -1.0f;
    float textureV3 = bottom;
    if (HAL::DISPLAY_ROTATION == rotate90)
    {
        textureU0 = -1.0f;
        textureV0 = right;
        textureU1 = -1.0f;
        textureV1 = -1.0f;
        textureU2 = bottom;
        textureV2 = -1.0f;
        textureU3 = bottom;
        textureV3 = right;
    }
    float triangleXs[4];
    float triangleYs[4];
    float triangleZs[4];
    float triangleUs[4];
    float triangleVs[4];
    // Determine winding order
    Vector4 zeroToOne(imageX1 - imageX0, imageY1 - imageY0, imageZ1 - imageZ0);
    const Vector4 zeroToTwo(imageX2 - imageX0, imageY2 - imageY0, imageZ2 - imageZ0);
    const Vector4 normal = zeroToOne.crossProduct(zeroToTwo);
    if (normal.getZ() > 0)
    {
        triangleXs[0] = imageX0;
        triangleXs[1] = imageX1;
        triangleXs[2] = imageX2;
        triangleXs[3] = imageX3;
        triangleYs[0] = imageY0;
        triangleYs[1] = imageY1;
        triangleYs[2] = imageY2;
        triangleYs[3] = imageY3;
        triangleZs[0] = imageZ0;
        triangleZs[1] = imageZ1;
        triangleZs[2] = imageZ2;
        triangleZs[3] = imageZ3;
        triangleUs[0] = textureU0;
        triangleUs[1] = textureU1;
        triangleUs[2] = textureU2;
        triangleUs[3] = textureU3;
        triangleVs[0] = textureV0;
        triangleVs[1] = textureV1;
        triangleVs[2] = textureV2;
        triangleVs[3] = textureV3;
    }
    else
    {
        // invert due to the triangles winding order (showing backface of the triangle)
        triangleXs[1] = imageX0;
        triangleXs[0] = imageX1;
        triangleXs[2] = imageX3;
        triangleXs[3] = imageX2;
        triangleYs[1] = imageY0;
        triangleYs[0] = imageY1;
        triangleYs[2] = imageY3;
        triangleYs[3] = imageY2;
        triangleZs[1] = imageZ0;
        triangleZs[0] = imageZ1;
        triangleZs[2] = imageZ3;
        triangleZs[3] = imageZ2;
        triangleUs[1] = textureU0;
        triangleUs[0] = textureU1;
        triangleUs[2] = textureU3;
        triangleUs[3] = textureU2;
        triangleVs[1] = textureV0;
        triangleVs[0] = textureV1;
        triangleVs[2] = textureV3;
        triangleVs[3] = textureV2;
    }
    drawQuad(invalidatedArea, fb, triangleXs, triangleYs, triangleZs, triangleUs, triangleVs);
}
References HAL::DISPLAY_ROTATION, TextureMapper::drawQuad(), TextureMapper::imageX0, TextureMapper::imageX1, TextureMapper::imageX2, TextureMapper::imageX3, TextureMapper::imageY0, TextureMapper::imageY1, TextureMapper::imageY2, TextureMapper::imageY3, TextureMapper::imageZ0, TextureMapper::imageZ1, TextureMapper::imageZ2, TextureMapper::imageZ3, and touchgfx::rotate90.
drawQuad()
void drawQuad (const Rect & invalidatedArea, uint16_t * fb, const float * triangleXs, const float * triangleYs, const float * triangleZs, const float * triangleUs, const float * triangleVs) const protected
The TextureMapper will draw the transformed bitmap by drawing one transformed quad. The quad is drawn from the points 0,1,2,3 using the x,y,z values from each point along with the u,v coordinates in the bitmap associated with each point.
Parameters
invalidatedArea The invalidated area.
[in] fb The framebuffer.
triangleXs The triangle xs.
triangleYs The triangle ys.
triangleZs The triangle zs.
triangleUs The triangle us.
triangleVs The triangle vs.
{
    // Area to redraw. Relative to the TextureMapper.
    Rect dirtyArea = Rect(0, 0, getWidth(), getHeight()) & invalidatedArea;
    // Absolute position of the TextureMapper.
    Rect dirtyAreaAbsolute = dirtyArea;
    translateRectToAbsolute(dirtyAreaAbsolute);
    Rect absoluteRect = getAbsoluteRect();
    DisplayTransformation::transformDisplayToFrameBuffer(absoluteRect);
    // Transform rects to match framebuffer coordinates
    // This is needed if the display is rotated compared to the framebuffer
    DisplayTransformation::transformDisplayToFrameBuffer(dirtyArea, this->getRect());
    DisplayTransformation::transformDisplayToFrameBuffer(dirtyAreaAbsolute);
    // Get a pointer to the bitmap data, return if no bitmap found
    const uint16_t* textmap = (const uint16_t*)bitmap.getData();
    if (!textmap)
    {
        return;
    }
    float x0 = triangleXs[0];
    float x1 = triangleXs[1];
    float x2 = triangleXs[2];
    float x3 = triangleXs[3];
    float y0 = triangleYs[0];
    float y1 = triangleYs[1];
    float y2 = triangleYs[2];
    float y3 = triangleYs[3];
    DisplayTransformation::transformDisplayToFrameBuffer(x0, y0, this->getRect());
    DisplayTransformation::transformDisplayToFrameBuffer(x1, y1, this->getRect());
    DisplayTransformation::transformDisplayToFrameBuffer(x2, y2, this->getRect());
    DisplayTransformation::transformDisplayToFrameBuffer(x3, y3, this->getRect());
    const Point3D point0 = { floatToFixed28_4(x0), floatToFixed28_4(y0), triangleZs[0], triangleUs[0], triangleVs[0] };
    const Point3D point1 = { floatToFixed28_4(x1), floatToFixed28_4(y1), triangleZs[1], triangleUs[1], triangleVs[1] };
    const Point3D point2 = { floatToFixed28_4(x2), floatToFixed28_4(y2), triangleZs[2], triangleUs[2], triangleVs[2] };
    const Point3D point3 = { floatToFixed28_4(x3), floatToFixed28_4(y3), triangleZs[3], triangleUs[3], triangleVs[3] };
    const Point3D vertices[4] = { point0, point1, point2, point3 };
    const DrawingSurface dest = { fb, HAL::FRAME_BUFFER_WIDTH };
    const TextureSurface src = { textmap, bitmap.getExtraData(), bitmap.getWidth(), bitmap.getHeight(), bitmap.getWidth() };
    uint16_t subDivs = subDivisionSize;
    if (point0.Z == point1.Z && point1.Z == point2.Z) //lint !e777
    {
        subDivs = 0xFFFF; // Max: One sweep
    }
    HAL::lcd().drawTextureMapQuad(dest, vertices, src, absoluteRect, dirtyAreaAbsolute, lookupRenderVariant(), alpha, subDivs);
}
References touchgfx::floatToFixed28_4(), HAL::FRAME_BUFFER_WIDTH, Drawable::getAbsoluteRect(), Drawable::getHeight(), Drawable::getRect(), Drawable::getWidth(), HAL::lcd(), TextureMapper::lookupRenderVariant(), TextureMapper::subDivisionSize, DisplayTransformation::transformDisplayToFrameBuffer(), and Drawable::translateRectToAbsolute().
Referenced by TextureMapper::draw().
getBitmapPositionX()
virtual float getBitmapPositionX () const inline virtual
Gets bitmap position x coordinate.
Returns
The bitmap position x coordinate.
See also
setBitmapPosition
    {
        return xBitmapPosition;
    }
References TextureMapper::xBitmapPosition.
getBitmapPositionY()
virtual float getBitmapPositionY () const inline virtual
Gets bitmap position y coordinate.
Returns
The bitmap position y coordinate.
See also
setBitmapPosition
    {
        return yBitmapPosition;
    }
References TextureMapper::yBitmapPosition.
getBoundingRect()
Rect getBoundingRect () const protected
Gets bounding rectangle of the transformed bitmap. This is the smallest possible rectangle which covers the image of the bitmap after applying scale and rotation.
Returns
The bounding rectangle.
{
    // MIN and MAX are macros so do not insert them into each other
    float minXf = MIN(imageX0, imageX1);
    minXf = MIN(minXf, imageX2);
    minXf = floorf(MIN(minXf, imageX3));
    const int16_t minX = (int16_t)(MAX(0, minXf));
    float maxXf = MAX(imageX0, imageX1);
    maxXf = MAX(maxXf, imageX2);
    maxXf = ceilf(MAX(maxXf, imageX3));
    int16_t maxX = getWidth();
    maxX = (int16_t)(MIN(maxX, maxXf));
    float minYf = MIN(imageY0, imageY1);
    minYf = MIN(minYf, imageY2);
    minYf = floorf(MIN(minYf, imageY3));
    const int16_t minY = (int16_t)(MAX(0, minYf));
    float maxYf = MAX(imageY0, imageY1);
    maxYf = MAX(maxYf, imageY2);
    maxYf = ceilf(MAX(maxYf, imageY3));
    int16_t maxY = getHeight();
    maxY = (int16_t)(MIN(maxY, maxYf));
    return Rect(minX, minY, maxX - minX, maxY - minY);
}
References Drawable::getHeight(), Drawable::getWidth(), TextureMapper::imageX0, TextureMapper::imageX1, TextureMapper::imageX2, TextureMapper::imageX3, TextureMapper::imageY0, TextureMapper::imageY1, TextureMapper::imageY2, TextureMapper::imageY3, MAX, and MIN.
Referenced by TextureMapper::invalidateContent().
getCameraDistance()
virtual float getCameraDistance () const inline virtual
Gets camera distance.
Returns
The camera distance.
See also
setCameraDistance
    {
        return cameraDistance;
    }
References TextureMapper::cameraDistance.
Referenced by Gauge::setupNeedleTextureMapper().
getCameraX()
virtual float getCameraX () const inline virtual
Gets camera x coordinate.
Returns
The camera x coordinate.
See also
setCamera
    {
        return xCamera;
    }
References TextureMapper::xCamera.
getCameraY()
virtual float getCameraY () const inline virtual
Gets camera y coordinate.
Returns
The camera y coordinate.
See also
setCamera
    {
        return yCamera;
    }
References TextureMapper::yCamera.
getOrigoX()
virtual float getOrigoX () const inline virtual
Gets transformation origo x coordinate.
Returns
The transformation origo x coordinate.
See also
setOrigo
    {
        return xOrigo;
    }
References TextureMapper::xOrigo.
Referenced by Gauge::setupNeedleTextureMapper().
getOrigoY()
virtual float getOrigoY () const inline virtual
Gets transformation origo y coordinate.
Returns
The transformation origo y coordinate.
See also
setOrigo
    {
        return yOrigo;
    }
References TextureMapper::yOrigo.
Referenced by Gauge::setupNeedleTextureMapper().
getOrigoZ()
virtual float getOrigoZ () const inline virtual
Gets transformation origo z coordinate.
Returns
The transformation origo z coordinate.
See also
setOrigo
    {
        return zOrigo;
    }
References TextureMapper::zOrigo.
getRenderingAlgorithm()
virtual RenderingAlgorithm getRenderingAlgorithm () const inline virtual
Gets the algorithm used when rendering.
Returns
The algorithm used when rendering.
    {
        return currentRenderingAlgorithm;
    }
References TextureMapper::currentRenderingAlgorithm.
getScale()
virtual float getScale () const inline virtual
Gets the scale of the image.
Returns
The scale.
See also
setScale
    {
        return scale;
    }
References TextureMapper::scale.
getSolidRect()
Rect getSolidRect () const virtual
Get (the largest possible) rectangle that is guaranteed to be solid (opaque). This information is important, as any Drawable underneath the solid area does not need to be drawn.
Returns
The solid rectangle part of the Drawable.
Note
The rectangle returned must be relative to upper left corner of the Drawable, meaning that a completely solid widget should return the full size Rect(0, 0, getWidth(), getHeight()). If no area can be guaranteed to be solid, an empty Rect must be returned. Failing to return the correct rectangle may result in errors on the display.
Reimplemented from Image.
{
    return Rect();
}
getX0()
virtual float getX0 () const inline virtual
Get the x coordinate of the top left corner of the transformed bitmap.
Returns
The X0 coordinate.
    {
        return imageX0;
    }
References TextureMapper::imageX0.
getX1()
virtual float getX1 () const inline virtual
Get the x coordinate of the top right corner of the transformed bitmap.
Returns
The X1 coordinate.
    {
        return imageX1;
    }
References TextureMapper::imageX1.
getX2()
virtual float getX2 () const inline virtual
Get the x coordinate of the bottom right of the transformed bitmap.
Returns
The X2 coordinate.
    {
        return imageX2;
    }
References TextureMapper::imageX2.
getX3()
virtual float getX3 () const inline virtual
Get the x coordinate of the bottom left corner of the transformed bitmap.
Returns
The X3 coordinate.
    {
        return imageX3;
    }
References TextureMapper::imageX3.
getXAngle()
virtual float getXAngle () const inline virtual
Get the x angle in radians.
Returns
The x angle.
See also
updateXAngle
Note
Angles are given in radians, so a full circle is 2*PI.
    {
        return xAngle;
    }
References TextureMapper::xAngle.
getY0()
virtual float getY0 () const inline virtual
Get the y coordinate of the top left corner of the transformed bitmap.
Returns
The Y0 coordinate.
    {
        return imageY0;
    }
References TextureMapper::imageY0.
getY1()
virtual float getY1 () const inline virtual
Get the y coordinate of the top right corner of the transformed bitmap.
Returns
The Y1 coordinate.
    {
        return imageY1;
    }
References TextureMapper::imageY1.
getY2()
virtual float getY2 () const inline virtual
Get the y coordinate of the bottom right corner of the transformed bitmap.
Returns
The Y2 coordinate.
    {
        return imageY2;
    }
References TextureMapper::imageY2.
getY3()
virtual float getY3 () const inline virtual
Get the y coordinate of the bottom left corner of the transformed bitmap.
Returns
The Y3 coordinate.
    {
        return imageY3;
    }
References TextureMapper::imageY3.
getYAngle()
virtual float getYAngle () const inline virtual
Get the y angle in radians.
Returns
The y angle.
See also
updateYAngle
Note
Angles are given in radians, so a full circle is 2*PI.
    {
        return yAngle;
    }
References TextureMapper::yAngle.
getZ0()
virtual float getZ0 () const inline virtual
Get the z coordinate of the top left corner of the transformed bitmap.
Returns
The Z0 coordinate.
    {
        return imageZ0;
    }
References TextureMapper::imageZ0.
getZ1()
virtual float getZ1 () const inline virtual
Get the z coordinate of the top right corner of the transformed bitmap.
Returns
The Z1 coordinate.
    {
        return imageZ1;
    }
References TextureMapper::imageZ1.
getZ2()
virtual float getZ2 () const inline virtual
Get the z coordinate of the bottom right corner of the transformed bitmap.
Returns
The Z2 coordinate.
    {
        return imageZ2;
    }
References TextureMapper::imageZ2.
getZ3()
virtual float getZ3 () const inline virtual
Get the z coordinate of the bottom left corner of the transformed bitmap.
Returns
The Z3 coordinate.
    {
        return imageZ3;
    }
References TextureMapper::imageZ3.
getZAngle()
virtual float getZAngle () const inline virtual
Get the z angle in radians.
Returns
The z angle.
See also
updateZAngle
Note
Angles are given in radians, so a full circle is 2*PI.
    {
        return zAngle;
    }
References TextureMapper::zAngle.
Referenced by AnalogClock::updateClock().
invalidateContent()
virtual void invalidateContent () const inline virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from Image.
    {
        if (alpha > 0)
        {
            Rect r = getBoundingRect();
            invalidateRect(r);
        }
    }
References TextureMapper::getBoundingRect(), and Drawable::invalidateRect().
Referenced by TextureMapper::updateAngles(), and TextureMapper::updateScale().
lookupRenderVariant()
RenderingVariant lookupRenderVariant () const protected
Returns the rendering variant based on the bitmap format, alpha value and rendering algorithm.
Returns
The RenderingVariant.
{
    RenderingVariant renderVariant;
    if (currentRenderingAlgorithm == NEAREST_NEIGHBOR)
    {
        renderVariant = lookupNearestNeighborRenderVariant(bitmap);
    }
    else
    {
        renderVariant = lookupBilinearRenderVariant(bitmap);
    }
    return renderVariant;
}
References TextureMapper::currentRenderingAlgorithm, touchgfx::lookupBilinearRenderVariant(), touchgfx::lookupNearestNeighborRenderVariant(), and TextureMapper::NEAREST_NEIGHBOR.
Referenced by TextureMapper::drawQuad().
setAngles()
void setAngles (float newXAngle, float newYAngle, float newZAngle) virtual
Sets the angles in radians of the image.
Parameters
newXAngle The new x Angle.
newYAngle The new y Angle.
newZAngle The new x Angle.
See also
updateAngles, getXAngle, getYAngle, getZAngle
Note
The area covered by the image before/after changing the angles is NOT invalidated.
Angles are given in radians, so a full circle is 2*PI.
{
    xAngle = newXAngle;
    yAngle = newYAngle;
    zAngle = newZAngle;
    applyTransformation();
}
References TextureMapper::applyTransformation(), TextureMapper::xAngle, TextureMapper::yAngle, and TextureMapper::zAngle.
Referenced by TextureMapper::setXAngle(), TextureMapper::setYAngle(), TextureMapper::setZAngle(), and TextureMapper::updateAngles().
setBitmap()
void setBitmap (const Bitmap & bmp) virtual
Sets the bitmap for this TextureMapper and updates the width and height of this widget to match those of the Bitmap.
Parameters
bmp The bitmap instance.
Note
The user code must call invalidate() in order to update the image on the display.
Reimplemented from Image.
{
    Image::setBitmap(bmp);
    applyTransformation();
}
References TextureMapper::applyTransformation(), and Image::setBitmap().
Referenced by Gauge::setNeedle().
setBitmapPosition() [1/2]
virtual void setBitmapPosition (float x, float y) inline virtual
Sets the position of the bitmap within the TextureMapper. The bitmap is clipped with respect to the dimensions of the TextureMapper widget.
Parameters
x The x coordinate.
y The y coordinate.
See also
getBitmapPositionX, getBitmapPositionY
    {
        xBitmapPosition = x;
        yBitmapPosition = y;
        applyTransformation();
    }
References TextureMapper::applyTransformation(), TextureMapper::xBitmapPosition, and TextureMapper::yBitmapPosition.
Referenced by TextureMapper::setBitmapPosition(), and Gauge::setupNeedleTextureMapper().
setBitmapPosition() [2/2]
virtual void setBitmapPosition (int x, int y) inline virtual
Sets the position of the bitmap within the TextureMapper. The bitmap is clipped with respect to the dimensions of the TextureMapper widget.
Parameters
x The x coordinate.
y The y coordinate.
See also
getBitmapPositionX, getBitmapPositionY
    {
        setBitmapPosition((float)x, (float)y);
    }
References TextureMapper::setBitmapPosition().
setCamera()
virtual void setCamera (float x, float y) inline virtual
Sets the camera coordinate.
Parameters
x The x coordinate for the camera.
y The y coordinate for the camera.
See also
getCameraX, getCameraY
    {
        xCamera = x;
        yCamera = y;
        applyTransformation();
    }
References TextureMapper::applyTransformation(), TextureMapper::xCamera, and TextureMapper::yCamera.
Referenced by Gauge::setupNeedleTextureMapper().
setCameraDistance()
virtual void setCameraDistance (float d) inline virtual
Sets camera distance. If the given value is below TextureMapper::MINIMAL_CAMERA_DISTANCE, it will be set to TextureMapper::MINIMAL_CAMERA_DISTANCE.
Parameters
d The new camera distance.
See also
getCameraDistance
    {
        cameraDistance = MAX(d, MINIMAL_CAMERA_DISTANCE);
        applyTransformation();
    }
References TextureMapper::applyTransformation(), TextureMapper::cameraDistance, MAX, and TextureMapper::MINIMAL_CAMERA_DISTANCE.
Referenced by Gauge::setupNeedleTextureMapper().
setOrigo() [1/2]
virtual void setOrigo (float x, float y) inline virtual
Sets the transformation origo (center) in two dimensions. Leaves the z coordinate untouched.
Parameters
x The x coordinate.
y The y coordinate.
See also
getOrigoX, getOrigoY
    {
        xOrigo = x;
        yOrigo = y;
        applyTransformation();
    }
References TextureMapper::applyTransformation(), TextureMapper::xOrigo, and TextureMapper::yOrigo.
setOrigo() [2/2]
virtual void setOrigo (float x, float y, float z) inline virtual
Sets the transformation origo (center).
Parameters
x The x coordinate.
y The y coordinate.
z The z coordinate.
See also
getOrigoX, getOrigoY, getOrigoZ
    {
        xOrigo = x;
        yOrigo = y;
        zOrigo = z;
        applyTransformation();
    }
References TextureMapper::applyTransformation(), TextureMapper::xOrigo, TextureMapper::yOrigo, and TextureMapper::zOrigo.
Referenced by Gauge::setupNeedleTextureMapper().
setRenderingAlgorithm()
virtual void setRenderingAlgorithm (RenderingAlgorithm algorithm) inline virtual
Sets the render algorithm to be used. Default setting is NEAREST_NEIGHBOR.
Parameters
algorithm The algorithm to use when rendering.
    {
        currentRenderingAlgorithm = algorithm;
    }
References TextureMapper::currentRenderingAlgorithm.
Referenced by Gauge::setupNeedleTextureMapper(), and Gauge::setValue().
setScale()
void setScale (float newScale) virtual
Sets the scale of the image.
Parameters
newScale The new scale value.
See also
updateScale, getScale
{
    scale = newScale;
    applyTransformation();
}
References TextureMapper::applyTransformation().
Referenced by TextureMapper::updateScale().
setXAngle()
virtual void setXAngle (float newXAngle) inline virtual
Sets the x angle in radians.
Parameters
newXAngle The new x angle.
See also
setAngles, updateXAngle, getXAngle
Note
The area covered by the image before/after changing the angle is NOT invalidated.
Angles are given in radians, so a full circle is 2*PI.
    {
        setAngles(newXAngle, yAngle, zAngle);
    }
References TextureMapper::setAngles(), TextureMapper::yAngle, and TextureMapper::zAngle.
setYAngle()
virtual void setYAngle (float newYAngle) inline virtual
Sets the y angle in radians.
Parameters
newYAngle The new y angle.
See also
setAngles, updateYAngle, getYAngle
Note
The area covered by the image before/after changing the angle is NOT invalidated.
Angles are given in radians, so a full circle is 2*PI.
    {
        setAngles(xAngle, newYAngle, zAngle);
    }
References TextureMapper::setAngles(), TextureMapper::xAngle, and TextureMapper::zAngle.
setZAngle()
virtual void setZAngle (float newZAngle) inline virtual
Sets the z angle in radians.
Parameters
newZAngle The new z angle.
See also
setAngles, updateZAngle, getZAngle
Note
The area covered by the image before/after changing the angle is NOT invalidated.
Angles are given in radians, so a full circle is 2*PI.
    {
        setAngles(xAngle, yAngle, newZAngle);
    }
References TextureMapper::setAngles(), TextureMapper::xAngle, and TextureMapper::yAngle.
TOUCHGFX_DEPRECATED()
TOUCHGFX_DEPRECATED ("Please use invalidateContent() instead." , void invalidateBoundingRect() const)
Invalidate the bounding rectangle of the transformed bitmap.
See also
getBoundingRect
Deprecated
Please use invalidateContent() instead.
updateAngles()
void updateAngles (float newXAngle, float newYAngle, float newZAngle) virtual
Updates the angles in radians of the image. The area covered by the image before and after changing the angles is invalidated, which is the smallest required rectangle.
Parameters
newXAngle The new x Angle.
newYAngle The new y Angle.
newZAngle The new x Angle.
See also
setAngles, updateXAngle, updateYAngle, updateZAngle, getXAngle, getYAngle, getZAngle
Note
Angles are given in radians, so a full circle is 2*PI.
{
    invalidateContent();
    setAngles(newXAngle, newYAngle, newZAngle);
    invalidateContent();
}
References TextureMapper::invalidateContent(), and TextureMapper::setAngles().
Referenced by AnimationTextureMapper::handleTickEvent(), TextureMapper::updateXAngle(), TextureMapper::updateYAngle(), and TextureMapper::updateZAngle().
updateScale()
void updateScale (float newScale) virtual
Updates the scale of the image. This implies invalidating the area covered by the texture mapper.
Parameters
newScale The new scale value.
See also
setScale, getScale
{
    invalidateContent();
    setScale(newScale);
    invalidateContent();
}
References TextureMapper::invalidateContent(), and TextureMapper::setScale().
Referenced by AnimationTextureMapper::handleTickEvent().
updateXAngle()
virtual void updateXAngle (float newXAngle) inline virtual
Updates the x angle in radians.
Parameters
newXAngle The new x angle.
See also
updateAngles, getXAngle
Note
Angles are given in radians, so a full circle is 2*PI.
    {
        updateAngles(newXAngle, yAngle, zAngle);
    }
References TextureMapper::updateAngles(), TextureMapper::yAngle, and TextureMapper::zAngle.
updateYAngle()
virtual void updateYAngle (float newYAngle) inline virtual
Updates the y angle in radians.
Parameters
newYAngle The new y angle.
See also
updateAngles, getYAngle
Note
Angles are given in radians, so a full circle is 2*PI.
    {
        updateAngles(xAngle, newYAngle, zAngle);
    }
References TextureMapper::updateAngles(), TextureMapper::xAngle, and TextureMapper::zAngle.
updateZAngle()
virtual void updateZAngle (float newZAngle) inline virtual
Updates the z angle in radians.
Parameters
newZAngle The new z angle.
See also
updateAngles, getZAngle
Note
Angles are given in radians, so a full circle is 2*PI.
    {
        updateAngles(xAngle, yAngle, newZAngle);
    }
References TextureMapper::updateAngles(), TextureMapper::xAngle, and TextureMapper::yAngle.
Referenced by AnalogClock::AnalogClock(), Gauge::setValue(), and AnalogClock::updateClock().
Member Data Documentation
cameraDistance
float cameraDistance protected
The camera distance.
Referenced by TextureMapper::applyTransformation(), TextureMapper::getCameraDistance(), and TextureMapper::setCameraDistance().
currentRenderingAlgorithm
RenderingAlgorithm currentRenderingAlgorithm protected
The current rendering algorithm.
Referenced by TextureMapper::getRenderingAlgorithm(), TextureMapper::lookupRenderVariant(), and TextureMapper::setRenderingAlgorithm().
imageX0
float imageX0 protected
The coordinate for the image points.
Referenced by TextureMapper::applyTransformation(), TextureMapper::draw(), TextureMapper::getBoundingRect(), and TextureMapper::getX0().
imageX1
float imageX1 protected
The coordinate for the image points.
Referenced by TextureMapper::applyTransformation(), TextureMapper::draw(), TextureMapper::getBoundingRect(), and TextureMapper::getX1().
imageX2
float imageX2 protected
The coordinate for the image points.
Referenced by TextureMapper::applyTransformation(), TextureMapper::draw(), TextureMapper::getBoundingRect(), and TextureMapper::getX2().
imageX3
float imageX3 protected
The coordinate for the image points.
Referenced by TextureMapper::applyTransformation(), TextureMapper::draw(), TextureMapper::getBoundingRect(), and TextureMapper::getX3().
imageY0
float imageY0 protected
The coordinate for the image points.
Referenced by TextureMapper::applyTransformation(), TextureMapper::draw(), TextureMapper::getBoundingRect(), and TextureMapper::getY0().
imageY1
float imageY1 protected
The coordinate for the image points.
Referenced by TextureMapper::applyTransformation(), TextureMapper::draw(), TextureMapper::getBoundingRect(), and TextureMapper::getY1().
imageY2
float imageY2 protected
The coordinate for the image points.
Referenced by TextureMapper::applyTransformation(), TextureMapper::draw(), TextureMapper::getBoundingRect(), and TextureMapper::getY2().
imageY3
float imageY3 protected
The coordinate for the image points.
Referenced by TextureMapper::applyTransformation(), TextureMapper::draw(), TextureMapper::getBoundingRect(), and TextureMapper::getY3().
imageZ0
float imageZ0 protected
The coordinate for the image points.
Referenced by TextureMapper::applyTransformation(), TextureMapper::draw(), and TextureMapper::getZ0().
imageZ1
float imageZ1 protected
The coordinate for the image points.
Referenced by TextureMapper::applyTransformation(), TextureMapper::draw(), and TextureMapper::getZ1().
imageZ2
float imageZ2 protected
The coordinate for the image points.
Referenced by TextureMapper::applyTransformation(), TextureMapper::draw(), and TextureMapper::getZ2().
imageZ3
float imageZ3 protected
The coordinate for the image points.
Referenced by TextureMapper::applyTransformation(), TextureMapper::draw(), and TextureMapper::getZ3().
MINIMAL_CAMERA_DISTANCE
const int MINIMAL_CAMERA_DISTANCE = 1 static protected
The minimal camera distance.
Referenced by TextureMapper::setCameraDistance().
scale
float scale protected
The scale.
Referenced by TextureMapper::getScale(), AnimationTextureMapper::handleTickEvent(), and AnimationTextureMapper::startAnimation().
subDivisionSize
uint16_t subDivisionSize protected
The size of the affine sub divisions.
Referenced by TextureMapper::drawQuad().
xAngle
float xAngle protected
The angle x in radians.
Referenced by TextureMapper::applyTransformation(), TextureMapper::getXAngle(), AnimationTextureMapper::handleTickEvent(), TextureMapper::setAngles(), TextureMapper::setYAngle(), TextureMapper::setZAngle(), AnimationTextureMapper::startAnimation(), TextureMapper::updateYAngle(), and TextureMapper::updateZAngle().
xBitmapPosition
float xBitmapPosition protected
The bitmap position x.
Referenced by TextureMapper::applyTransformation(), TextureMapper::getBitmapPositionX(), and TextureMapper::setBitmapPosition().
xCamera
float xCamera protected
The camera x coordinate.
Referenced by TextureMapper::applyTransformation(), TextureMapper::getCameraX(), and TextureMapper::setCamera().
xOrigo
float xOrigo protected
The origo x coordinate.
Referenced by TextureMapper::applyTransformation(), TextureMapper::getOrigoX(), TextureMapper::setOrigo(), and TextureMapper::setOrigo().
yAngle
float yAngle protected
The angle y in radians.
Referenced by TextureMapper::applyTransformation(), TextureMapper::getYAngle(), AnimationTextureMapper::handleTickEvent(), TextureMapper::setAngles(), TextureMapper::setXAngle(), TextureMapper::setZAngle(), AnimationTextureMapper::startAnimation(), TextureMapper::updateXAngle(), and TextureMapper::updateZAngle().
yBitmapPosition
float yBitmapPosition protected
The bitmap position y.
Referenced by TextureMapper::applyTransformation(), TextureMapper::getBitmapPositionY(), and TextureMapper::setBitmapPosition().
yCamera
float yCamera protected
The camera y coordinate.
Referenced by TextureMapper::applyTransformation(), TextureMapper::getCameraY(), and TextureMapper::setCamera().
yOrigo
float yOrigo protected
The origo y coordinate.
Referenced by TextureMapper::applyTransformation(), TextureMapper::getOrigoY(), TextureMapper::setOrigo(), and TextureMapper::setOrigo().
zAngle
float zAngle protected
The angle z in radians.
Referenced by TextureMapper::applyTransformation(), TextureMapper::getZAngle(), AnimationTextureMapper::handleTickEvent(), TextureMapper::setAngles(), TextureMapper::setXAngle(), TextureMapper::setYAngle(), AnimationTextureMapper::startAnimation(), TextureMapper::updateXAngle(), and TextureMapper::updateYAngle().
zOrigo
float zOrigo protected
The origo z coordinate.
Referenced by TextureMapper::applyTransformation(), TextureMapper::getOrigoZ(), and TextureMapper::setOrigo().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/TextureMapper.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/TextureMapper.cpp