Battery Simulator Documentation: FontCache
FontCache
#include "FontCache.hpp"
Public Member Functions
FontCache ()
bool cacheLigatures (CachedFont *font, TypedText t, const Unicode::UnicodeChar *string)
bool cacheString (TypedText t, const Unicode::UnicodeChar *string)
void clear (bool keepGsubOrContextTable=false)
void close ()
const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, FontId font) const
uint32_t getMemoryUsage ()
void initializeCachedFont (TypedText t, CachedFont *font, bool loadGsubOrContextTable=false)
void open ()
void setMemory (uint8_t *memory, uint32_t size)
void setReader (FontDataReader *reader)
Static Public Member Functions
static const uint8_t * getPixelData (const GlyphNode *glyph)
static bool isCached (const GlyphNode *g)
Private Member Functions
void cacheData (GlyphNode *first)
bool cacheSortedString (TypedText t)
bool contains (Unicode::UnicodeChar unicode, FontId font) const
uint8_t * copyGlyph (uint8_t *top, Unicode::UnicodeChar unicode, FontId font, bool &outOfMemory)
bool createSortedLigatures (CachedFont *font, TypedText t, const Unicode::UnicodeChar *string,...)
bool createSortedString (const Unicode::UnicodeChar *string)
uint32_t getGlyphSize (const GlyphNode *gn)
void insert (Unicode::UnicodeChar unicode, FontId font, bool &outOfMemory)
void readData (void *out, uint32_t numberOfBytes)
void setPosition (uint32_t position)
bool sortSortedString (int n)
Private Attributes
uint8_t bpp
char buffer [MAX_BUFFER_SIZE]
uint8_t byteAlignRow
GlyphNode currentFileGlyphNode
uint16_t currentFileGlyphNumber
struct {
uint8_t * first
uint8_t * last
} fontTable [MAX(TypographyFontIndex::NUMBER_OF_FONTS, 1)]
uint32_t glyphDataOffset
uint8_t * gsubStart
uint8_t * memory
uint32_t memorySize
uint16_t numGlyphs
FontDataReader * reader
Unicode::UnicodeChar * sortedString
uint8_t * top
Static Private Attributes
static const uint32_t MAX_BUFFER_SIZE = 64
static const uint32_t SizeGlyphNode = 16
Detailed Description
Constructor & Destructor Documentation
FontCache()
FontCache ()
    : memorySize(0), memory(0), top(0), gsubStart(0), reader(0)
{
}
Member Function Documentation
cacheData()
void cacheData (GlyphNode * first) private
{
    GlyphNode* gn = first;
    while (gn)
    {
        uint8_t* p = (uint8_t*)gn;
        if (gn->dataOffset != 0xFFFFFFFF)
        {
            p += SizeGlyphNode;
            // Next pointer
            p += sizeof(void*);
            // Seek and copy
            setPosition(glyphDataOffset + gn->dataOffset);
            readData(p, getGlyphSize(gn));
            // Mark glyphNode as cached
            gn->dataOffset = 0xFFFFFFFF;
        }
        GlyphNode** next = (GlyphNode**)((uint8_t*)gn + SizeGlyphNode);
        gn = *next;
    }
}
References FontCache::first, FontCache::getGlyphSize(), FontCache::glyphDataOffset, FontCache::readData(), FontCache::setPosition(), and FontCache::SizeGlyphNode.
Referenced by FontCache::cacheSortedString().
cacheLigatures()
bool cacheLigatures (CachedFont * font, TypedText t, const Unicode::UnicodeChar * string)
{
    open();
    if (!createSortedLigatures(font, t, string, 0, 0))
    {
        close();
        return false;
    }
    const bool result = cacheSortedString(t);
    close();
    return result;
}
References FontCache::cacheSortedString(), FontCache::close(), FontCache::createSortedLigatures(), and FontCache::open().
cacheSortedString()
bool cacheSortedString (TypedText t) private
{
    setPosition(8); // Skip font index and size
    uint32_t glyphNodeOffset;
    uint32_t dummy;
    readData(&glyphNodeOffset, sizeof(uint32_t)); // offsetToTable
    readData(&dummy, sizeof(uint32_t));           // offsetToKerning
    readData(&glyphDataOffset, sizeof(uint32_t)); // offsetToGlyphs
    readData(&dummy, sizeof(uint32_t));           // offsetToGlyphs
    readData(&dummy, sizeof(uint32_t));           // offsetToArabicTable
    readData(&numGlyphs, sizeof(uint16_t));       // numberOfGlyphs
    FontId fontId = t.getFontId();                 // Get font index from typed text
    bpp = t.getFont()->getBitsPerPixel();          // Get BPP from standard font
    byteAlignRow = t.getFont()->getByteAlignRow(); // Get ByteAlign from font
    setPosition(glyphNodeOffset); // Go to glyph nodes for font
    currentFileGlyphNumber = 0;
    currentFileGlyphNode.unicode = 0; // Force reading of first glyph
    const Unicode::UnicodeChar* string = sortedString;
    Unicode::UnicodeChar last = 0;
    GlyphNode* firstNewGlyph = 0;
    bool outOfMemory = false;
    while (*string)
    {
        Unicode::UnicodeChar ch = *string;
        if (ch != last)
        {
            if (!contains(ch, fontId))
            {
                insert(ch, fontId, outOfMemory);
                if (outOfMemory)
                {
                    break;
                }
                if (firstNewGlyph == 0)
                {
                    firstNewGlyph = (GlyphNode*)fontTable[fontId].last;
                }
            }
        }
        last = ch;
        string++;
    }
    cacheData(firstNewGlyph);
    return !outOfMemory;
}
References FontCache::bpp, FontCache::byteAlignRow, FontCache::cacheData(), FontCache::contains(), FontCache::currentFileGlyphNode, FontCache::currentFileGlyphNumber, dummy, FontCache::fontTable, FontCache::glyphDataOffset, FontCache::insert(), FontCache::last, FontCache::readData(), FontCache::setPosition(), FontCache::sortedString, and GlyphNode::unicode.
Referenced by FontCache::cacheLigatures(), and FontCache::cacheString().
cacheString()
bool cacheString (TypedText t, const Unicode::UnicodeChar * string)
{
    open();
    if (!createSortedString(string))
    {
        close();
        return false;
    }
    const bool result = cacheSortedString(t);
    close();
    return result;
}
References FontCache::cacheSortedString(), FontCache::close(), FontCache::createSortedString(), and FontCache::open().
clear()
void clear (bool keepGsubOrContextTable = false)
{
    memset(fontTable, 0, sizeof(fontTable));
    // Top is beginning of memory, no glyphs are cached yet
    top = memory;
    if (!keepGsubOrContextTable)
    {
        // gsubStart points to end of memory (nothing loaded yet)
        gsubStart = memory + memorySize;
        // Round down to 32bit address
        gsubStart = (uint8_t*)((uintptr_t)gsubStart & ~(sizeof(void*) - 1));
    }
}
References FontCache::fontTable, FontCache::gsubStart, FontCache::memory, FontCache::memorySize, and touchgfx::memset().
Referenced by FontCache::setMemory().
close()
void close ()
{
    if (reader)
    {
        reader->close();
    }
}
References FontDataReader::close(), and FontCache::reader.
Referenced by FontCache::cacheLigatures(), FontCache::cacheString(), and FontCache::initializeCachedFont().
contains()
bool contains (Unicode::UnicodeChar unicode, FontId font) const private
{
    GlyphNode* g = (GlyphNode*)fontTable[font].first;
    while (g)
    {
        if (g->unicode == unicode)
        {
            return true;
        }
        GlyphNode** next = (GlyphNode**)((uint8_t*)g + SizeGlyphNode);
        g = *next;
    }
    return false;
}
References FontCache::fontTable, and FontCache::SizeGlyphNode.
Referenced by FontCache::cacheSortedString().
copyGlyph()
uint8_t * copyGlyph (uint8_t * top, Unicode::UnicodeChar unicode, FontId font, bool & outOfMemory) private
{
    while (currentFileGlyphNumber < numGlyphs && currentFileGlyphNode.unicode < unicode)
    {
        readData(&currentFileGlyphNode, sizeof(GlyphNode));
        currentFileGlyphNumber++;
    }
    if (currentFileGlyphNode.unicode != unicode)
    {
        // GlyphNode not found
        return top;
    }
    // GlyphNode found
    uint32_t glyphSize = getGlyphSize(&currentFileGlyphNode);
    const int alignment = sizeof(void*);
    glyphSize = (glyphSize + (alignment - 1)) & ~(alignment - 1);
    uint32_t requiredMem = SizeGlyphNode + sizeof(void*) + glyphSize; // GlyphNode + next ptr + glyph
    // Is space available before sortedString
    if (top + requiredMem > (uint8_t*)sortedString)
    {
        outOfMemory = true;
        return top;
    }
    *(GlyphNode*)top = currentFileGlyphNode;
    // Clear next pointer
    uint8_t** next = (uint8_t**)(top + SizeGlyphNode);
    *next = 0;
    top += requiredMem;
    return top;
}
References FontCache::currentFileGlyphNode, FontCache::currentFileGlyphNumber, FontCache::getGlyphSize(), FontCache::readData(), FontCache::SizeGlyphNode, FontCache::sortedString, FontCache::top, and GlyphNode::unicode.
Referenced by FontCache::insert().
createSortedLigatures()
bool createSortedLigatures (CachedFont * font, TypedText t, const Unicode::UnicodeChar * string, ...) private
{
    va_list pArg;
    va_start(pArg, string);
    TextProvider tp;
    tp.initialize(string, pArg, font->getGSUBTable(), font->getContextualFormsTable());
    va_end(pArg);
    Unicode::UnicodeChar ligature;
    sortedString = (Unicode::UnicodeChar*)(gsubStart);
    if ((uint8_t*)(sortedString - 1) < top)
    {
        return false;
    }
    *--sortedString = 0;
    int n = 0;
    while ((ligature = tp.getNextLigature(t.getTextDirection())) != 0)
    {
        if ((uint8_t*)(sortedString - 1) < top)
        {
            return false;
        }
        *--sortedString = ligature;
        n++;
    }
    return sortSortedString(n);
}
References CachedFont::getContextualFormsTable(), CachedFont::getGSUBTable(), TextProvider::getNextLigature(), FontCache::gsubStart, TextProvider::initialize(), FontCache::sortedString, and FontCache::sortSortedString().
Referenced by FontCache::cacheLigatures().
createSortedString()
bool createSortedString (const Unicode::UnicodeChar * string) private
{
    int length = Unicode::strlen(string);
    // Sorted string is allocated at end of buffer
    sortedString = (Unicode::UnicodeChar*)(gsubStart - (length + 1) * 2);
    if ((uint8_t*)sortedString < top)
    {
        // Unable to allocate string buffer in end of memory
        return false;
    }
    int n = 0;
    Unicode::UnicodeChar* uc = sortedString;
    while (*string)
    {
        *uc++ = *string++;
        n++;
    }
    *uc = 0;
    return sortSortedString(n);
}
References FontCache::gsubStart, FontCache::sortedString, FontCache::sortSortedString(), Unicode::strlen(), and FontCache::top.
Referenced by FontCache::cacheString().
getGlyph()
const GlyphNode * getGlyph (Unicode::UnicodeChar unicode, FontId font) const
{
    GlyphNode* g = (GlyphNode*)fontTable[font].first;
    while (g)
    {
        if (g->unicode == unicode)
        {
            return g;
        }
        GlyphNode** next = (GlyphNode**)((uint8_t*)g + SizeGlyphNode);
        g = *next;
    }
    return 0;
}
References FontCache::fontTable, and FontCache::SizeGlyphNode.
Referenced by CachedFont::getGlyph().
getGlyphSize()
uint32_t getGlyphSize (const GlyphNode * gn) inline private
    {
        if (byteAlignRow)
        {
            // Round up line width to byte boundary and multiply by height
            return (gn->width() * bpp + 7) / 8 * gn->height();
        }
        // Calculate number of pixels and round up to byte bounday
        return (gn->width() * gn->height() * bpp + 7) / 8;
    }
References FontCache::bpp, and FontCache::byteAlignRow.
Referenced by FontCache::cacheData(), and FontCache::copyGlyph().
getMemoryUsage()
uint32_t getMemoryUsage () inline
    {
        return memorySize - (gsubStart - top);
    }
References FontCache::gsubStart, FontCache::memorySize, and FontCache::top.
getPixelData()
static const uint8_t * getPixelData (const GlyphNode * glyph) inline static
    {
        return ((const uint8_t*)glyph) + SizeGlyphNode + sizeof(void*);
    }
References FontCache::SizeGlyphNode.
Referenced by CachedFont::getPixelData().
initializeCachedFont()
void initializeCachedFont (TypedText t, CachedFont * font, bool loadGsubOrContextTable = false)
{
    // Get font index from typed text
    FontId fontId = t.getFontId();
    // Reset to start of file
    open();
    setPosition(0);
    assert(sizeof(touchgfx::BinaryFontData) < MAX_BUFFER_SIZE);
    readData(buffer, sizeof(touchgfx::BinaryFontData));
    const struct touchgfx::BinaryFontData* binaryFontData = reinterpret_cast<const struct touchgfx::BinaryFontData*>(buffer);
    const Font** flashFonts = TypedTextDatabase::getFonts();
    const GeneratedFont* flashFont = static_cast<const GeneratedFont*>(flashFonts[fontId]);
    *font = CachedFont(reinterpret_cast<const struct touchgfx::BinaryFontData*>(buffer), fontId, this, flashFont);
    if (loadGsubOrContextTable && (binaryFontData->offsetToGSUB != 0))
    {
        setPosition(binaryFontData->offsetToGSUB);
        const uint32_t sizeOfGSUB = (binaryFontData->offsetToArabicTable != 0 ? binaryFontData->offsetToArabicTable : binaryFontData->sizeOfFontData) - binaryFontData->offsetToGSUB;
        if (top + sizeOfGSUB < gsubStart) // Room for this GSUB table
        {
            // Round down to aligned address
            uint8_t* const gsubPosition = (uint8_t*)((uintptr_t)(gsubStart - sizeOfGSUB) & ~(sizeof(void*) - 1));
            readData(gsubPosition, sizeOfGSUB);
            font->setGSUBTable(reinterpret_cast<uint16_t*>(gsubPosition));
            gsubStart = gsubPosition;
        }
        else
        {
            font->setGSUBTable(0);
        }
    }
    if (loadGsubOrContextTable && (binaryFontData->offsetToArabicTable != 0))
    {
        setPosition(binaryFontData->offsetToArabicTable);
        const uint32_t sizeTableData = binaryFontData->sizeOfFontData - binaryFontData->offsetToArabicTable;
        if (top + sizeTableData + sizeof(FontContextualFormsTable) < gsubStart) // Room for the ContextualFormsTables
        {
            // Allocate FontContextualFormsTable first
            gsubStart -= sizeof(FontContextualFormsTable);
            // Round down to 32bit address
            gsubStart = (uint8_t*)((uintptr_t)gsubStart & ~(sizeof(void*) - 1));
            FontContextualFormsTable* table = (FontContextualFormsTable*)gsubStart;
            font->setContextualFormsTable(table);
            gsubStart -= sizeTableData;
            readData(gsubStart, sizeTableData);
            // Set pointers in table
            const uint16_t* const base = (const uint16_t*)gsubStart;
            // First elements in binary font are offsets to arrays in 16bit words
            table->contextualForms4Long = (FontContextualFormsTable::arrayOf5UnicodesPtr)(base + base[0]);
            table->contextualForms3Long = (FontContextualFormsTable::arrayOf5UnicodesPtr)(base + base[1]);
            table->contextualForms2Long = (FontContextualFormsTable::arrayOf5UnicodesPtr)(base + base[2]);
            table->contextualForms0621_063a = (FontContextualFormsTable::arrayOf4UnicodesPtr)(base + base[3]);
            table->contextualForms0641_064a = (FontContextualFormsTable::arrayOf4UnicodesPtr)(base + base[4]);
            table->contextualForms06XX = (FontContextualFormsTable::arrayOf5UnicodesPtr)(base + base[5]);
            table->contextualForms4LongSize = base[6];
            table->contextualForms3LongSize = base[7];
            table->contextualForms2LongSize = base[8];
            table->contextualForms06XXSize = base[9];
        }
        else
        {
            font->setContextualFormsTable(0);
        }
    }
    close();
}
References FontCache::buffer, FontCache::close(), TypedTextDatabase::getFonts(), FontCache::gsubStart, FontCache::MAX_BUFFER_SIZE, FontCache::open(), FontCache::readData(), CachedFont::setContextualFormsTable(), CachedFont::setGSUBTable(), and FontCache::setPosition().
insert()
void insert (Unicode::UnicodeChar unicode, FontId font, bool & outOfMemory) private
{
    // Insert new glyphnode and glyph after last for font.
    uint8_t* oldTop = top;
    top = copyGlyph(top, unicode, font, outOfMemory);
    if (top == oldTop)
    {
        return;
    }
    if (fontTable[font].last == 0)
    {
        // First glyph
        fontTable[font].first = oldTop;
        fontTable[font].last = oldTop;
    }
    else
    {
        // Set next pointer of old last glyph
        uint8_t** old_next = (uint8_t**)(fontTable[font].last + SizeGlyphNode);
        *old_next = oldTop;
        // Save new glyph as last glyph
        fontTable[font].last = oldTop;
    }
}
References FontCache::copyGlyph(), Pair< T1, T2 >::first, FontCache::fontTable, FontCache::last, FontCache::SizeGlyphNode, and FontCache::top.
Referenced by FontCache::cacheSortedString().
isCached()
static bool isCached (const GlyphNode * g) inline static
    {
        return g->dataOffset == 0xFFFFFFFF;
    }
Referenced by CachedFont::getPixelData().
open()
void open ()
{
    if (reader)
    {
        reader->open();
    }
}
References FontDataReader::open(), and FontCache::reader.
Referenced by FontCache::cacheLigatures(), FontCache::cacheString(), and FontCache::initializeCachedFont().
readData()
void readData (void * out, uint32_t numberOfBytes) private
{
    if (reader)
    {
        reader->readData(out, numberOfBytes);
    }
}
References FontDataReader::readData(), and FontCache::reader.
Referenced by FontCache::cacheData(), FontCache::cacheSortedString(), FontCache::copyGlyph(), and FontCache::initializeCachedFont().
setMemory()
void setMemory (uint8_t * memory, uint32_t size)
{
    memory = _memory;
    memorySize = size;
    clear();
}
References FontCache::clear(), FontCache::memory, and FontCache::memorySize.
setPosition()
void setPosition (uint32_t position) private
{
    if (reader)
    {
        reader->setPosition(position);
    }
}
References FontCache::reader, and FontDataReader::setPosition().
Referenced by FontCache::cacheData(), FontCache::cacheSortedString(), and FontCache::initializeCachedFont().
setReader()
void setReader (FontDataReader * reader)
{
    reader = _reader;
}
References FontCache::reader.
sortSortedString()
bool sortSortedString (int n) private
{
    Unicode::UnicodeChar* uc = sortedString;
    for (int i = 0; i < n - 1; i++)
    {
        bool swapped = false;
        for (int j = 0; j < n - i - 1; j++)
        {
            if (uc[j] > uc[j + 1])
            {
                Unicode::UnicodeChar temp = uc[j];
                uc[j] = uc[j + 1];
                uc[j + 1] = temp;
                swapped = true;
            }
        }
        // If no two elements were swapped by inner loop, then break
        if (!swapped)
        {
            break;
        }
    }
    return true;
}
References FontCache::sortedString.
Referenced by FontCache::createSortedLigatures(), and FontCache::createSortedString().
Member Data Documentation
bpp
uint8_t bpp private
Referenced by FontCache::cacheSortedString(), and FontCache::getGlyphSize().
buffer
char buffer[MAX_BUFFER_SIZE] private
Referenced by FontCache::initializeCachedFont().
byteAlignRow
uint8_t byteAlignRow private
Referenced by FontCache::cacheSortedString(), and FontCache::getGlyphSize().
currentFileGlyphNode
GlyphNode currentFileGlyphNode private
Referenced by FontCache::cacheSortedString(), and FontCache::copyGlyph().
currentFileGlyphNumber
uint16_t currentFileGlyphNumber private
Referenced by FontCache::cacheSortedString(), and FontCache::copyGlyph().
first
uint8_t* first
Referenced by FontCache::cacheData().
[struct]
struct { ... } fontTable[MAX(TypographyFontIndex::NUMBER_OF_FONTS, 1)]
Referenced by FontCache::cacheSortedString(), FontCache::clear(), FontCache::contains(), FontCache::getGlyph(), and FontCache::insert().
glyphDataOffset
uint32_t glyphDataOffset private
Referenced by FontCache::cacheData(), and FontCache::cacheSortedString().
gsubStart
uint8_t* gsubStart private
Referenced by FontCache::clear(), FontCache::createSortedLigatures(), FontCache::createSortedString(), FontCache::getMemoryUsage(), and FontCache::initializeCachedFont().
last
uint8_t* last
Referenced by FontCache::cacheSortedString(), and FontCache::insert().
MAX_BUFFER_SIZE
const uint32_t MAX_BUFFER_SIZE = 64 static private
Referenced by FontCache::initializeCachedFont().
memory
uint8_t* memory private
Referenced by FontCache::clear(), and FontCache::setMemory().
memorySize
uint32_t memorySize private
Referenced by FontCache::clear(), FontCache::getMemoryUsage(), and FontCache::setMemory().
numGlyphs
uint16_t numGlyphs private
reader
FontDataReader* reader private
Referenced by FontCache::close(), FontCache::open(), FontCache::readData(), FontCache::setPosition(), and FontCache::setReader().
SizeGlyphNode
const uint32_t SizeGlyphNode = 16 static private
Referenced by FontCache::cacheData(), FontCache::contains(), FontCache::copyGlyph(), FontCache::getGlyph(), FontCache::getPixelData(), and FontCache::insert().
sortedString
Unicode::UnicodeChar* sortedString private
Referenced by FontCache::cacheSortedString(), FontCache::copyGlyph(), FontCache::createSortedLigatures(), FontCache::createSortedString(), and FontCache::sortSortedString().
top
uint8_t* top private
Referenced by FontCache::copyGlyph(), FontCache::createSortedString(), FontCache::getMemoryUsage(), and FontCache::insert().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/fonts/include/fonts/FontCache.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/fonts/src/FontCache.cpp