Battery Simulator Documentation: CacheableContainer
CacheableContainer
#include "CacheableContainer.hpp"
Public Member Functions
CacheableContainer ()
void enableCachedMode (bool enable)
uint8_t getAlpha () const
BitmapId getCacheBitmap () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isChildInvalidated () const
void setAlpha (uint8_t newAlpha)
void setCacheBitmap (BitmapId bitmapId)
bool setSolidRect (const Rect &solidRect) const
void updateCache ()
void updateCache (const Rect &rect)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Private Attributes
BitmapId cachedBitmapId
The BitmapId of the dynamic bitmap attached to the CacheableContainer.
CachedImage cachedImage
The CachedImage object used as a wrapper widget around the attached dynamic bitmap.
bool childWasInvalidated
A child widget has been invalidated. The flag is meaningful when isCachedMode is true.
bool isCachedMode
Cached mode whether enabled or disabled.
Additional Inherited Members
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A CacheableContainer can be seen as a regular Container, i.e. a Drawable that can have child nodes. The z-order of children is determined by the order in which Drawables are added to the container - the Drawable added last will be front-most on the screen.
The important difference is that a CacheableContainer can also render its content to a dynamic bitmap which can then be used as a texture in subsequent drawing operations, either as a simple Image or in a TextureMapper. If the bitmap format of the dynamic bitmap differs from the format of the current LCD, the LCD from drawing the bitmap must be setup using HAL::setAuxiliaryLCD().
See also
Container, Bitmap, Image, TextureMapper
Constructor & Destructor Documentation
CacheableContainer()
CacheableContainer ()
    : Container(),
      cachedBitmapId(BITMAP_INVALID),
      cachedImage(),
      isCachedMode(false),
      childWasInvalidated(false)
{
    // Set this Container as parent for the cachedImage. This will
    // make sure the cachedImage is clipped correctly.
    cachedImage.setParent(this);
    cachedImage.setXY(0, 0);
}
References CacheableContainer::cachedImage.
Member Function Documentation
enableCachedMode()
void enableCachedMode (bool enable)
Toggle cached mode on and off. The CacheableContainer behaves just like a regular Container when cached mode is turned off.
Parameters
enable Enable or disable cached mode.
{
    isCachedMode = enable;
}
References CacheableContainer::isCachedMode.
getAlpha()
uint8_t getAlpha () const inline
Gets the current alpha value of the widget. The alpha value is in range 255 (solid) to 0 (invisible).
Returns
The current alpha value.
See also
setAlpha
    {
        return cachedImage.getAlpha();
    }
References CacheableContainer::cachedImage.
Referenced by CacheableContainer::invalidateContent().
getCacheBitmap()
BitmapId getCacheBitmap () const
Get the dynamic bitmap used by the CacheableContainer.
Returns
the id of the assigned bitmap or BITMAP_INVALID if no bitmap has been assigned.
See also
setCacheBitmap
{
    return cachedBitmapId;
}
References CacheableContainer::cachedBitmapId.
invalidateContent()
virtual void invalidateContent () const inline virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from Drawable.
    {
        if (getAlpha() > 0)
        {
            Container::invalidateContent();
        }
    }
References CacheableContainer::getAlpha(), and Drawable::invalidateContent().
invalidateRect()
void invalidateRect (Rect & invalidatedArea) const virtual
Request that a subregion of this drawable is redrawn. Will recursively traverse the children. When this function returns, the specified invalidated area has been redrawn for all appropriate Drawables covering the region.
Parameters
[in] invalidatedArea The area of this drawable to redraw expressed in coordinates relative to its parent (e.g. to request a complete redraw, invalidatedArea will be (0, 0, width, height).
Reimplemented from Drawable.
{
    Container::invalidateRect(invalidatedArea);
    if (isCachedMode && (cachedBitmapId != BITMAP_INVALID))
    {
        const_cast<CacheableContainer*>(this)->childWasInvalidated = true;
    }
}
References touchgfx::BITMAP_INVALID, CacheableContainer::cachedBitmapId, CacheableContainer::childWasInvalidated, Drawable::invalidateRect(), and CacheableContainer::isCachedMode.
isChildInvalidated()
bool isChildInvalidated () const
Queries the CacheableContainer whether any child widget has been invalidated.
Returns
True if a child widget has been invalidated and false otherwise.
{
    return childWasInvalidated;
}
References CacheableContainer::childWasInvalidated.
setAlpha()
void setAlpha (uint8_t newAlpha) inline
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
The alpha is only applied when cached mode is enabled.
See also
enableCachedMode
    {
        cachedImage.setAlpha(newAlpha);
    }
References CacheableContainer::cachedImage.
setCacheBitmap()
void setCacheBitmap (BitmapId bitmapId)
Set the dynamic bitmap into which the container content will be rendered. The format of the bitmap must be the same as the current LCD or the same as the auxiliary LCD setup using HAL::setAuxiliaryLCD.
Parameters
bitmapId Id of the dynamic bitmap to serve as a render target.
See also
updateCache, getCacheBitmap, HAL::setAuxiliaryLCD
{
    const Bitmap bitmap(bitmapId);
    cachedBitmapId = BITMAP_INVALID;
    /* Accept only dynamic bitmaps */
    if (!Bitmap::dynamicBitmapGetAddress(bitmapId))
    {
        return;
    }
    /* Retrieve the auxiliary LCD implementation attached to HA */
    LCD* auxLCD = HAL::getInstance()->getAuxiliaryLCD();
    /* Dynamic bitmap and framebuffer should be of the same format */
    if (bitmap.getFormat() == HAL::lcd().framebufferFormat() ||
        (auxLCD && bitmap.getFormat() == auxLCD->framebufferFormat()))
    {
        cachedBitmapId = bitmapId;
        cachedImage.setBitmap(Bitmap(cachedBitmapId));
    }
}
References touchgfx::BITMAP_INVALID, CacheableContainer::cachedBitmapId, CacheableContainer::cachedImage, Bitmap::dynamicBitmapGetAddress(), HAL::getInstance(), and HAL::lcd().
setSolidRect()
bool setSolidRect (const Rect & solidRect) const
Set the solid area on the dynamic bitmap assigned to the CacheableContainer.
Parameters
[in] solidRect The rectangle of th CacheableContainer that is solid.
Returns
true if the operation succeeds, false otherwise.
{
    return Bitmap::dynamicBitmapSetSolidRect(cachedBitmapId, solidRect);
}
References CacheableContainer::cachedBitmapId, and Bitmap::dynamicBitmapSetSolidRect().
updateCache() [1/2]
void updateCache ()
Render the container into the attached dynamic bitmap.
See also
setCacheBitmap
{
    updateCache(Rect());
}
References CacheableContainer::updateCache().
Referenced by CacheableContainer::updateCache().
updateCache() [2/2]
void updateCache (const Rect & rect)
Render the container into the attached dynamic bitmap. Only the specified Rect region is updated.
Parameters
rect Region to update.
See also
setCacheBitmap
{
    if (isCachedMode && (cachedBitmapId != BITMAP_INVALID))
    {
        /* will call Container::draw(invalidatedArea) to render all widgets into the dynamic bitmap */
        HAL::getInstance()->drawDrawableInDynamicBitmap(*this, cachedBitmapId, invalidatedArea);
        childWasInvalidated = false;
    }
}
References touchgfx::BITMAP_INVALID, CacheableContainer::cachedBitmapId, CacheableContainer::childWasInvalidated, HAL::getInstance(), and CacheableContainer::isCachedMode.
Member Data Documentation
cachedBitmapId
BitmapId cachedBitmapId private
The BitmapId of the dynamic bitmap attached to the CacheableContainer.
Referenced by CacheableContainer::getCacheBitmap(), CacheableContainer::invalidateRect(), CacheableContainer::setCacheBitmap(), CacheableContainer::setSolidRect(), and CacheableContainer::updateCache().
cachedImage
CachedImage cachedImage private
The CachedImage object used as a wrapper widget around the attached dynamic bitmap.
Referenced by CacheableContainer::CacheableContainer(), CacheableContainer::getAlpha(), CacheableContainer::setAlpha(), and CacheableContainer::setCacheBitmap().
childWasInvalidated
bool childWasInvalidated private
A child widget has been invalidated. The flag is meaningful when isCachedMode is true.
Referenced by CacheableContainer::invalidateRect(), CacheableContainer::isChildInvalidated(), and CacheableContainer::updateCache().
isCachedMode
bool isCachedMode private
Cached mode whether enabled or disabled.
Referenced by CacheableContainer::enableCachedMode(), CacheableContainer::invalidateRect(), and CacheableContainer::updateCache().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/CacheableContainer.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/CacheableContainer.cpp