Battery Simulator Documentation: Texts
Texts
#include "Texts.hpp"
Public Member Functions
const Unicode::UnicodeChar * getText (TypedTextId id) const
Static Public Member Functions
static LanguageId getLanguage ()
static void setLanguage (LanguageId id)
static void setTranslation (LanguageId id, const void *translation)
Static Private Attributes
static LanguageId currentLanguage = static_cast<touchgfx::LanguageId>(0)
Detailed Description
Class for setting language and getting texts. The language set will determine which texts will be used in the application.
Member Function Documentation
getLanguage()
static LanguageId getLanguage () inline static
Gets the current language.
Returns
The id of the language.
    {
        return currentLanguage;
    }
References Texts::currentLanguage.
getText()
const touchgfx::Unicode::UnicodeChar * getText (TypedTextId id) const
Get text in the set language.
Parameters
id The id of the text to lookup.
Returns
The text.
See also
setLanguage
{
    return &currentLanguagePtr[currentLanguageIndices[id]];
}
References currentLanguageIndices, and currentLanguagePtr.
setLanguage()
void setLanguage (touchgfx::LanguageId id) static
Sets the current language for texts.
Parameters
id The id of the language.
{
    const touchgfx::TypedText::TypedTextData* currentLanguageTypedText = 0;
    if (id < 1)
    {
        if (languagesArray[id] != 0)
        {
            // Dynamic translation is added
            const TranslationHeader* translation = languagesArray[id];
            currentLanguagePtr = (const touchgfx::Unicode::UnicodeChar*)(((const uint8_t*)translation) + translation->offset_to_texts);
            currentLanguageIndices = (const uint32_t*)(((const uint8_t*)translation) + translation->offset_to_indices);
            currentLanguageTypedText = (const touchgfx::TypedText::TypedTextData*)(((const uint8_t*)translation) + translation->offset_to_typedtext);
        }
        else
        {
            // Compiled and linked in languages
            currentLanguagePtr = staticLanguageTexts[id];
            currentLanguageIndices = staticLanguageIndices[id];
            currentLanguageTypedText = typedTextDatabaseArray[id];
        }
    }
    if (currentLanguageTypedText)
    {
        currentLanguage = id;
        touchgfx::TypedText::registerTypedTextDatabase(currentLanguageTypedText,
                                                       TypedTextDatabase::getFonts(), TypedTextDatabase::getInstanceSize());
    }
}
References currentLanguageIndices, currentLanguagePtr, TypedTextDatabase::getFonts(), TypedTextDatabase::getInstanceSize(), languagesArray, TypedText::registerTypedTextDatabase(), staticLanguageIndices, staticLanguageTexts, and typedTextDatabaseArray.
Referenced by touchgfx::touchgfx_generic_init(), and touchgfx::touchgfx_init().
setTranslation()
void setTranslation (touchgfx::LanguageId id, const void * translation) static
Adds or replaces a translation. This function allows an application to add a translation at runtime.
Parameters
id The id of the language to add or replace.
translation A pointer to the translation in flash or RAM.
{
    languagesArray[id] = (const TranslationHeader*)translation;
}
References languagesArray.
Member Data Documentation
currentLanguage
touchgfx::LanguageId currentLanguage = static_cast<touchgfx::LanguageId>(0) static private
Referenced by Texts::getLanguage().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/Texts.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/texts/src/Texts.cpp