Battery Simulator Documentation: LCD8bpp_ABGR2222
LCD8bpp_ABGR2222
#include "LCD8bpp_ABGR2222.hpp"
Classes
class DrawTextureMapScanLineBase8
class TextureMapper_A4_BilinearInterpolation_GA
class TextureMapper_A4_NearestNeighbor_GA
class TextureMapper_ABGR2222_NonOpaque_BilinearInterpolation_GA
class TextureMapper_ABGR2222_NonOpaque_NearestNeighbor_GA
class TextureMapper_ABGR2222_Opaque_BilinearInterpolation_GA
class TextureMapper_ABGR2222_Opaque_NearestNeighbor_GA
class TextureMapper_ARGB8888_NonOpaque_BilinearInterpolation_GA
class TextureMapper_ARGB8888_NonOpaque_NearestNeighbor_GA
Public Member Functions
LCD8bpp_ABGR2222 ()
virtual uint8_t bitDepth () const
virtual void blitCopy (const uint16_t *sourceData, const Rect &source, const Rect &blitRect, uint8_t alpha, bool hasTransparentPixels)
virtual void blitCopy (const uint8_t *sourceData, Bitmap::BitmapFormat sourceFormat, const Rect &source, const Rect &blitRect, uint8_t alpha, bool hasTransparentPixels)
virtual void copyAreaFromTFTToClientBuffer (const Rect &region)
virtual uint16_t * copyFrameBufferRegionToMemory (const Rect &visRegion, const Rect &absRegion, const BitmapId bitmapId)
virtual Rect copyFrameBufferRegionToMemory (const Rect &visRegion, const Rect &absRegion, uint8_t *dst, int16_t dstWidth, int16_t dstHeight)
virtual void drawPartialBitmap (const Bitmap &bitmap, int16_t x, int16_t y, const Rect &rect, uint8_t alpha=255, bool useOptimized=true)
void enableTextureMapperA4 ()
void enableTextureMapperA4_BilinearInterpolation ()
void enableTextureMapperA4_NearestNeighbor ()
void enableTextureMapperABGR2222 ()
void enableTextureMapperABGR2222_BilinearInterpolation ()
void enableTextureMapperABGR2222_NearestNeighbor ()
void enableTextureMapperAll ()
void enableTextureMapperARGB8888 ()
void enableTextureMapperARGB8888_BilinearInterpolation ()
void enableTextureMapperARGB8888_NearestNeighbor ()
virtual void fillBuffer (uint8_t *const destination, uint16_t pixelStride, const Rect &rect, const colortype color, const uint8_t alpha)
virtual void fillRect (const Rect &rect, colortype color, uint8_t alpha=255)
virtual Bitmap::BitmapFormat framebufferFormat () const
virtual uint16_t framebufferStride () const
Public Member Functions inherited from LCD
LCD ()
virtual ~LCD ()
uint16_t * copyFrameBufferRegionToMemory (const Rect &region, const BitmapId bitmapId=BITMAP_ANIMATION_STORAGE)
void drawString (Rect widgetArea, const Rect &invalidatedArea, const StringVisuals &stringVisuals, const Unicode::UnicodeChar *format,...)
virtual void drawTextureMapQuad (const DrawingSurface &dest, const Point3D *vertices, const TextureSurface &texture, const Rect &absoluteRect, const Rect &dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha=255, uint16_t subDivisionSize=12)
virtual void drawTextureMapTriangle (const DrawingSurface &dest, const Point3D *vertices, const TextureSurface &texture, const Rect &absoluteRect, const Rect &dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha=255, uint16_t subDivisionSize=12)
colortype getDefaultColor () const
virtual void setDefaultColor (colortype color)
void setVectorFontRenderer (VectorFontRenderer *renderer)
virtual bool supportDynamicBitmapDrawing (const Bitmap::BitmapFormat format)
Static Public Member Functions
static FORCE_INLINE_FUNCTION uint8_t getAlphaFromNativeColor (uint8_t color)
static FORCE_INLINE_FUNCTION uint8_t getBlueFromNativeColor (uint8_t color)
static FORCE_INLINE_FUNCTION uint16_t getFramebufferStride ()
static FORCE_INLINE_FUNCTION uint8_t getGreenFromNativeColor (uint8_t color)
static FORCE_INLINE_FUNCTION uint8_t getNativeColor (colortype color)
static FORCE_INLINE_FUNCTION uint8_t getNativeColorFromRGB (uint8_t red, uint8_t green, uint8_t blue)
static FORCE_INLINE_FUNCTION uint8_t getRedFromNativeColor (uint8_t color)
Static Public Member Functions inherited from LCD
static FORCE_INLINE_FUNCTION uint8_t div255 (uint16_t num)
static FORCE_INLINE_FUNCTION uint32_t div255g (uint32_t pixelxAlpha)
static FORCE_INLINE_FUNCTION uint32_t div255rb (uint32_t pixelxAlpha)
Protected Member Functions
virtual void drawGlyph (uint16_t *wbuf16, Rect widgetArea, int16_t x, int16_t y, uint16_t offsetX, uint16_t offsetY, const Rect &invalidatedArea, const GlyphNode *glyph, const uint8_t *glyphData, uint8_t byteAlignRow, colortype color, uint8_t bitsPerPixel, uint8_t alpha, TextRotation rotation)
virtual DrawTextureMapScanLineBase * getTextureMapperDrawScanLine (const TextureSurface &texture, RenderingVariant renderVariant, uint8_t alpha)
Protected Member Functions inherited from LCD
void drawStringLTR (const Rect &widgetArea, const Rect &invalidatedArea, const StringVisuals &visuals, const Unicode::UnicodeChar *format, va_list pArg)
void drawStringRTL (const Rect &widgetArea, const Rect &invalidatedArea, const StringVisuals &visuals, const Unicode::UnicodeChar *format, va_list pArg)
virtual void drawTextureMapScanLine (const DrawingSurface &dest, const Gradients &gradients, const Edge *leftEdge, const Edge *rightEdge, const TextureSurface &texture, const Rect &absoluteRect, const Rect &dirtyAreaAbsolute, RenderingVariant renderVariant, uint8_t alpha, uint16_t subDivisionSize)
Static Protected Member Functions
static void blitCopyAlphaPerPixel (const uint16_t *sourceData16, const Rect &source, const Rect &blitRect, uint8_t alpha)
static void blitCopyARGB8888 (const uint32_t *sourceData, const Rect &source, const Rect &blitRect, uint8_t alpha)
static int nextLine (bool rotatedDisplay, TextRotation textRotation)
static int nextPixel (bool rotatedDisplay, TextRotation textRotation)
Static Protected Member Functions inherited from LCD
static FORCE_INLINE_FUNCTION uint8_t getAlphaFromA4 (const uint16_t *data, uint32_t offset)
static uint16_t getNumLines (TextProvider &textProvider, WideTextAction wideTextAction, TextDirection textDirection, const Font *font, int16_t width)
static int realX (const Rect &widgetArea, int16_t x, int16_t y, TextRotation rotation)
static int realY (const Rect &widgetArea, int16_t x, int16_t y, TextRotation rotation)
static void rotateRect (Rect &rect, const Rect &canvas, const TextRotation rotation)
static uint16_t stringWidth (TextProvider &textProvider, const Font &font, const int numChars, TextDirection textDirection)
Private Member Functions
FORCE_INLINE_FUNCTION uint32_t convertABGR2222toARGB8888 (colortype col) const
Static Private Member Functions
static FORCE_INLINE_FUNCTION uint8_t alphaBlend (const uint8_t r, const uint8_t g, const uint8_t b, const uint8_t alpha, const uint8_t fbr, const uint8_t fbg, const uint8_t fbb, const uint8_t ialpha)
static FORCE_INLINE_FUNCTION uint8_t bilinearInterpolate8 (uint8_t c00, uint8_t c10, uint8_t c01, uint8_t c11, uint8_t x, uint8_t y)
static FORCE_INLINE_FUNCTION uint8_t bilinearInterpolate8 (uint8_t c00, uint8_t c10, uint8_t x)
static FORCE_INLINE_FUNCTION uint32_t bilinearInterpolate888 (uint32_t c00, uint32_t c10, uint32_t c01, uint32_t c11, uint8_t x, uint8_t y)
static FORCE_INLINE_FUNCTION uint32_t convertABGR2222toRGB888 (uint8_t val)
static FORCE_INLINE_FUNCTION uint8_t convertRGB888toXBGR2222 (uint32_t val)
static FORCE_INLINE_FUNCTION uint32_t div255_888 (uint32_t val, uint8_t factor)
static FORCE_INLINE_FUNCTION uint32_t div255_888_FFcheck (uint32_t val, uint8_t factor)
Private Attributes
DrawTextureMapScanLineBase * textureMapper_A4_BilinearInterpolation_GA
DrawTextureMapScanLineBase * textureMapper_A4_NearestNeighbor_GA
DrawTextureMapScanLineBase * textureMapper_ABGR2222_NonOpaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase * textureMapper_ABGR2222_NonOpaque_NearestNeighbor_GA
DrawTextureMapScanLineBase * textureMapper_ABGR2222_Opaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase * textureMapper_ABGR2222_Opaque_NearestNeighbor_GA
DrawTextureMapScanLineBase * textureMapper_ARGB8888_NonOpaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase * textureMapper_ARGB8888_NonOpaque_NearestNeighbor_GA
Additional Inherited Members
Static Protected Attributes inherited from LCD
static colortype defaultColor
Default Color to use when displaying transparency-only elements, e.g. A4 bitmaps.
static const uint16_t newLine = 10
NewLine value.
Detailed Description
This class contains the various low-level drawing routines for drawing bitmaps, texts and rectangles on 16 bits per pixel displays.
See also
LCD
Note
All coordinates are expected to be in absolute coordinates!
Constructor & Destructor Documentation
LCD8bpp_ABGR2222()
LCD8bpp_ABGR2222 ()
Member Function Documentation
alphaBlend()
static FORCE_INLINE_FUNCTION uint8_t alphaBlend (const uint8_t r, const uint8_t g, const uint8_t b, const uint8_t alpha, const uint8_t fbr, const uint8_t fbg, const uint8_t fbb, const uint8_t ialpha) inline static private
    {
        return getNativeColorFromRGB(div255(r * alpha + fbr * ialpha), div255(g * alpha + fbg * ialpha), div255(b * alpha + fbb * ialpha));
    }
References LCD::div255(), and LCD8bpp_ABGR2222::getNativeColorFromRGB().
bilinearInterpolate8() [1/2]
static FORCE_INLINE_FUNCTION uint8_t bilinearInterpolate8 (uint8_t c00, uint8_t c10, uint8_t c01, uint8_t c11, uint8_t x, uint8_t y) inline static private
    {
        assert(x < 16 && y < 16);
        const uint16_t xy11 = x * y;
        const uint16_t xy10 = 16 * x - xy11;
        const uint16_t xy01 = 16 * y - xy11;
        const uint16_t xy00 = 256 - (xy11 + xy10 + xy01);
        return (c00 * xy00 + c10 * xy10 + c01 * xy01 + c11 * xy11) >> 8;
    }
bilinearInterpolate8() [2/2]
static FORCE_INLINE_FUNCTION uint8_t bilinearInterpolate8 (uint8_t c00, uint8_t c10, uint8_t x) inline static private
    {
        assert(x < 16);
        const uint16_t xy10 = 16 * x;
        const uint16_t xy00 = 256 - xy10;
        return (c00 * xy00 + c10 * xy10) >> 8;
    }
bilinearInterpolate888()
static FORCE_INLINE_FUNCTION uint32_t bilinearInterpolate888 (uint32_t c00, uint32_t c10, uint32_t c01, uint32_t c11, uint8_t x, uint8_t y) inline static private
    {
        assert(x < 16 && y < 16);
        const uint16_t xy11 = x * y;
        const uint16_t xy10 = 16 * x - xy11;
        const uint16_t xy01 = 16 * y - xy11;
        const uint16_t xy00 = 256 - (xy11 + xy10 + xy01);
        return ((((c00 & 0xFF00FF) * xy00 + (c10 & 0xFF00FF) * xy10 + (c01 & 0xFF00FF) * xy01 + (c11 & 0xFF00FF) * xy11) >> 8) & 0xFF00FF) |
               ((((c00 & 0x00FF00) * xy00 + (c10 & 0x00FF00) * xy10 + (c01 & 0x00FF00) * xy01 + (c11 & 0x00FF00) * xy11) >> 8) & 0x00FF00);
    }
bitDepth()
virtual uint8_t bitDepth () const inline virtual
Number of bits per pixel used by the display.
Returns
The number of bits per pixel.
Implements LCD.
    {
        return 8;
    }
blitCopy() [1/2]
virtual void blitCopy (const uint16_t * sourceData, const Rect & source, const Rect & blitRect, uint8_t alpha, bool hasTransparentPixels) virtual
Blits (directly copies) a block of data to the framebuffer, performing alpha blending (and tranparency keying) as specified. Performs a software blend if HAL does not support BLIT_COPY_WITH_ALPHA and alpha != 255 (solid).
Parameters
sourceData The source array pointer (points to the beginning of the data). The sourceData must be stored in a format suitable for the selected display.
source The position and dimensions of the source. The x and y of this rect should both be 0.
blitRect A rectangle describing what region of the sourceData is to be copied to the framebuffer.
alpha The alpha value to use for blending ranging from 0=invisible to 255=solid=no blending.
hasTransparentPixels If true, this data copy contains transparent pixels and require hardware support for that to be enabled.
Implements LCD.
blitCopy() [2/2]
virtual void blitCopy (const uint8_t * sourceData, Bitmap::BitmapFormat sourceFormat, const Rect & source, const Rect & blitRect, uint8_t alpha, bool hasTransparentPixels) virtual
Blits (directly copies) a block of data to the framebuffer, performing alpha blending (and tranparency keying) as specified. Performs a software blend if HAL does not support BLIT_COPY_WITH_ALPHA and alpha < 255 (solid).
If the display does not support the specified sourceFormat, an assert will be raised.
Parameters
sourceData The source array pointer (points to the beginning of the data). The sourceData must be stored in a format suitable for the selected display.
sourceFormat The bitmap format used in the source data.
source The position and dimensions of the source. The x and y of this rect should both be 0.
blitRect A rectangle describing what region of the sourceData is to be copied to the framebuffer.
alpha The alpha value to use for blending ranging from 0=invisible to 255=solid=no blending.
hasTransparentPixels If true, this data copy contains transparent pixels and require hardware support for that to be enabled.
Implements LCD.
blitCopyAlphaPerPixel()
static void blitCopyAlphaPerPixel (const uint16_t * sourceData16, const Rect & source, const Rect & blitRect, uint8_t alpha) static protected
Blit a 2D source-array to the framebuffer performing alpha-blending per pixel as specified Performs always a software blend.
Parameters
sourceData16 The source-array pointer (points to the beginning of the data). The sourceData must be stored as 8-bits ABGR2222 values.
source The location and dimensions of the source.
blitRect A rectangle describing what region is to be drawn.
alpha The alpha value to use for blending applied to the whole image (255 = solid, no blending)
blitCopyARGB8888()
static void blitCopyARGB8888 (const uint32_t * sourceData, const Rect & source, const Rect & blitRect, uint8_t alpha) static protected
Blit a 2D source-array to the framebuffer performing alpha-blending per pixel as specified if ARGB8888 is not supported by the DMA a software blend is performed.
Parameters
sourceData The source-array pointer (points to the beginning of the data). The sourceData must be stored as 32- bits ARGB8888 values.
source The location and dimensions of the source.
blitRect A rectangle describing what region is to be drawn.
alpha The alpha value to use for blending applied to the whole image (255 = solid, no blending)
convertABGR2222toARGB8888()
FORCE_INLINE_FUNCTION uint32_t convertABGR2222toARGB8888 (colortype col) const inline private
    {
        return (((col & 0xC0) << 18) | ((col & 0x03) << 16) | ((col & 0x0C) << 6) | ((col & 0x30) >> 4)) * 0x55;
    }
convertABGR2222toRGB888()
static FORCE_INLINE_FUNCTION uint32_t convertABGR2222toRGB888 (uint8_t val) inline static private
    {
        return (((val & 0x03) << 16) | ((val & 0x0C) << 6) | ((val & 0x30) >> 4)) * 0x55;
    }
convertRGB888toXBGR2222()
static FORCE_INLINE_FUNCTION uint8_t convertRGB888toXBGR2222 (uint32_t val) inline static private
    {
        val &= 0xC0C0C0;
        return (val >> 2) | (val >> 12) | (val >> 22);
    }
copyAreaFromTFTToClientBuffer()
virtual void copyAreaFromTFTToClientBuffer (const Rect & region) virtual
Copies part of the displayed framebuffer to current framebuffer. The region given is the absolute region on screen.
Parameters
region A rectangle describing what region of the displayed framebuffer is to be copied to the framebuffer.
Note
The copy is performed only when double buffering is enabled. Otherwise the given region in current framebuffer is left untouched.
Implements LCD.
copyFrameBufferRegionToMemory() [1/2]
virtual uint16_t * copyFrameBufferRegionToMemory (const Rect & visRegion, const Rect & absRegion, const BitmapId bitmapId) virtual
Copies part of the framebuffer to the data section of a bitmap. The bitmap must be a dynamic bitmap or animation storage (BITMAP_ANIMATION_STORAGE). The two regions given are the visible region and the absolute region on screen. This is used to copy only a part of the framebuffer. This might be the case if a SnapshotWidget is placed inside a Container where parts of the SnapshowWidget is outside the area defined by the Container. The visible region must be completely inside the absolute region.
Parameters
visRegion The visible region.
absRegion The absolute region.
bitmapId Identifier for the bitmap.
Returns
Null if it fails, else a pointer to the data in the given bitmap.
See also
blitCopy, copyFrameBufferRegionToMemory(const Rect&, const Rect&, uint8_t*, int16_t, int16_t)
Note
There is only one instance of animation storage. The content of the bitmap data /animation storage outside the given region is left untouched.
Implements LCD.
copyFrameBufferRegionToMemory() [2/2]
virtual Rect copyFrameBufferRegionToMemory (const Rect & visRegion, const Rect & absRegion, uint8_t * dst, int16_t dstWidth, int16_t dstHeight) virtual
Copies part of the framebuffer to memory. The memory is assumed to have the same format as the framebuffer. The two regions given are the visible region and the absolute region on screen. This is used to copy only a part of the framebuffer. This might be the case if a SnapshotWidget is placed inside a Container where parts of the SnapshowWidget is outside the area defined by the Container. The visible region must be completely inside the absolute region.
Parameters
visRegion The visible region.
absRegion The absolute region.
[in,out] dst Destination memory in same format as the framebuffer.
dstWidth Width of the destination.
dstHeight Height of the destination.
Returns
The rect that was actually copied to the destination buffer.
See also
blitCopy, copyFrameBufferRegionToMemory(const Rect&, const Rect&, const BitmapId)
Note
There is only one instance of animation storage. The content of the bitmap data /animation storage outside the given region is left untouched.
Implements LCD.
div255_888()
static FORCE_INLINE_FUNCTION uint32_t div255_888 (uint32_t val, uint8_t factor) inline static private
    {
        return div255rb((val & 0xFF00FF) * factor) | div255g((val & 0x00FF00) * factor);
    }
References LCD::div255g(), and LCD::div255rb().
Referenced by LCD8bpp_ABGR2222::div255_888_FFcheck().
div255_888_FFcheck()
static FORCE_INLINE_FUNCTION uint32_t div255_888_FFcheck (uint32_t val, uint8_t factor) inline static private
    {
        return factor < 0xFF ? div255_888(val, factor) : val;
    }
References LCD8bpp_ABGR2222::div255_888().
drawGlyph()
virtual void drawGlyph (uint16_t * wbuf16, Rect widgetArea, int16_t x, int16_t y, uint16_t offsetX, uint16_t offsetY, const Rect & invalidatedArea, const GlyphNode * glyph, const uint8_t * glyphData, uint8_t byteAlignRow, colortype color, uint8_t bitsPerPixel, uint8_t alpha, TextRotation rotation) protected virtual
Private version of draw-glyph with explicit destination buffer pointer argument. For all parameters (except the buffer pointer) see the public function drawString().
Parameters
[out] wbuf16 The destination (frame) buffer to draw to.
widgetArea The canvas to draw the glyph inside.
x Horizontal offset to start drawing the glyph.
y Vertical offset to start drawing the glyph.
offsetX Horizontal offset in the glyph to start drawing from.
offsetY Vertical offset in the glyph to start drawing from.
invalidatedArea The area to draw inside.
glyph Specifications of the glyph to draw.
glyphData Data containing the actual glyph (dense format)
byteAlignRow Each row of glyph data starts in a new byte.
color The color of the glyph.
bitsPerPixel Bit depth of the glyph.
alpha The transparency of the glyph.
rotation Rotation to do before drawing the glyph.
Implements LCD.
drawPartialBitmap()
virtual void drawPartialBitmap (const Bitmap & bitmap, int16_t x, int16_t y, const Rect & rect, uint8_t alpha = 255, bool useOptimized = true) virtual
Draws all (or a part) of a bitmap. The coordinates of the corner of the bitmap is given in (x, y) and rect describes which part of the bitmap should be drawn. The bitmap can be drawn as it is or more or less transparent depending on the value of alpha. The value of alpha is independent of the transparency of the individual pixels of the given bitmap.
Parameters
bitmap The bitmap to draw.
x The absolute x coordinate to place (0, 0) of the bitmap on the screen.
y The absolute y coordinate to place (0, 0) of the bitmap on the screen.
rect A rectangle describing what region of the bitmap is to be drawn.
alpha (Optional) Optional alpha value ranging from 0=invisible to 255=solid. Default is 255 (solid).
useOptimized (Optional) if false, do not attempt to substitute (parts of) this bitmap with faster fillrects.
Implements LCD.
enableTextureMapperA4()
void enableTextureMapperA4 ()
Enables the texture mappers for A4 image format. This allows drawing A4 images using Bilinear Interpolation and Nearest Neighbor algorithms.
See also
enableTextureMapperA4_BilinearInterpolation, enableTextureMapperA4_NearestNeighbor
enableTextureMapperA4_BilinearInterpolation()
void enableTextureMapperA4_BilinearInterpolation ()
Enables the texture mappers for A4 image format. This allows drawing A4 images using Bilinear Interpolation algorithm.
See also
enableTextureMapperA4, enableTextureMapperA4_NearestNeighbor
enableTextureMapperA4_NearestNeighbor()
void enableTextureMapperA4_NearestNeighbor ()
Enables the texture mappers for A4 image format. This allows drawing A4 images using Nearest Neighbor algorithm.
See also
enableTextureMapperA4, enableTextureMapperA4_BilinearInterpolation
enableTextureMapperABGR2222()
void enableTextureMapperABGR2222 ()
Enables the texture mappers for ABGR2222 image format. This allows drawing ABGR2222 images using Bilinear Interpolation and Nearest Neighbor algorithms.
See also
enableTextureMapperABGR2222_BilinearInterpolation, enableTextureMapperABGR2222_NearestNeighbor
enableTextureMapperABGR2222_BilinearInterpolation()
void enableTextureMapperABGR2222_BilinearInterpolation ()
Enables the texture mappers for ABGR2222 image format. This allows drawing ABGR2222 images using Bilinear Interpolation algorithm.
See also
enableTextureMapperABGR2222, enableTextureMapperABGR2222_NearestNeighbor
enableTextureMapperABGR2222_NearestNeighbor()
void enableTextureMapperABGR2222_NearestNeighbor ()
Enables the texture mappers for ABGR2222 image format. This allows drawing ABGR2222 images using Nearest Neighbor algorithm.
See also
enableTextureMapperABGR2222, enableTextureMapperABGR2222_BilinearInterpolation
enableTextureMapperAll()
void enableTextureMapperAll ()
Enables the texture mappers for all image formats. This allows drawing any image using Bilinear Interpolation and Nearest Neighbor algorithms, but might use a lot of memory for the drawing algorithms.
enableTextureMapperARGB8888()
void enableTextureMapperARGB8888 ()
Enables the texture mappers for ARGB8888 image format. This allows drawing ARGB8888 images using Bilinear Interpolation and Nearest Neighbor algorithms.
See also
enableTextureMapperARGB8888_BilinearInterpolation, enableTextureMapperARGB8888_NearestNeighbor
enableTextureMapperARGB8888_BilinearInterpolation()
void enableTextureMapperARGB8888_BilinearInterpolation ()
Enables the texture mappers for ARGB8888 image format. This allows drawing ARGB8888 images using Bilinear Interpolation algorithm.
See also
enableTextureMapperARGB8888, enableTextureMapperARGB8888_NearestNeighbor
enableTextureMapperARGB8888_NearestNeighbor()
void enableTextureMapperARGB8888_NearestNeighbor ()
Enables the texture mappers for ARGB8888 image format. This allows drawing ARGB8888 images using Nearest Neighbor algorithm.
See also
enableTextureMapperARGB8888, enableTextureMapperARGB8888_BilinearInterpolation
fillBuffer()
virtual void fillBuffer (uint8_t *const destination, uint16_t pixelStride, const Rect & rect, const colortype color, const uint8_t alpha) virtual
Draws a filled rectangle in destination memory using the specified color and opacity. The destination memory must have the same format as the display framebuffer. By default the rectangle will be drawn as a solid box. The rectangle can be drawn with transparency by specifying alpha from 0=invisible to 255=solid.
Parameters
[in] destination The start of the memory area to fill.
pixelStride The pixel stride, i.e. number of pixels in a row.
rect The rectangle to fill absolute coordinates.
color The rectangle color.
alpha The rectangle opacity, from 0=invisible to 255=solid.
Note
The pixelStride is rounded up to nearest whole bytes for displays with more than one pixel per byte (LCD1bpp, LCD2bpp and LCD4bpp)
Implements LCD.
fillRect()
virtual void fillRect (const Rect & rect, colortype color, uint8_t alpha = 255) virtual
Draws a filled rectangle in the framebuffer in the specified color and opacity. By default the rectangle will be drawn as a solid box. The rectangle can be drawn with transparency by specifying alpha from 0=invisible to 255=solid.
Parameters
rect The rectangle to draw in absolute display coordinates.
color The rectangle color.
alpha (Optional) The rectangle opacity, from 0=invisible to 255=solid.
See also
fillBuffer
Implements LCD.
framebufferFormat()
virtual Bitmap::BitmapFormat framebufferFormat () const inline virtual
Framebuffer format used by the display.
Returns
A Bitmap::BitmapFormat.
Implements LCD.
    {
        return Bitmap::ABGR2222;
    }
References Bitmap::ABGR2222.
framebufferStride()
virtual uint16_t framebufferStride () const inline virtual
Framebuffer stride in bytes. The distance (in bytes) from the start of one framebuffer row, to the next.
Returns
The number of bytes in one framebuffer row.
Implements LCD.
    {
        return getFramebufferStride();
    }
References LCD8bpp_ABGR2222::getFramebufferStride().
getAlphaFromNativeColor()
static FORCE_INLINE_FUNCTION uint8_t getAlphaFromNativeColor (uint8_t color) inline static
Gets alpha from color.
Parameters
color The color.
Returns
The alpha from color.
    {
        return ((color >> 6) & 0x03) * 0x55;
    }
getBlueFromNativeColor()
static FORCE_INLINE_FUNCTION uint8_t getBlueFromNativeColor (uint8_t color) inline static
Gets blue from color.
Parameters
color The color.
Returns
The blue from color.
    {
        return ((color >> 4) & 0x03) * 0x55;
    }
Referenced by AbstractPainterABGR2222::alphaBlend(), and AbstractPainterABGR2222::alphaBlend().
getFramebufferStride()
static FORCE_INLINE_FUNCTION uint16_t getFramebufferStride () inline static
Framebuffer stride in bytes. The distance (in bytes) from the start of one framebuffer row, to the next.
Returns
The number of bytes in one framebuffer row.
    {
        assert(HAL::FRAME_BUFFER_WIDTH > 0 && "HAL has not been initialized yet");
        return HAL::FRAME_BUFFER_WIDTH;
    }
References HAL::FRAME_BUFFER_WIDTH.
Referenced by LCD8bpp_ABGR2222::framebufferStride().
getGreenFromNativeColor()
static FORCE_INLINE_FUNCTION uint8_t getGreenFromNativeColor (uint8_t color) inline static
Gets green from color.
Parameters
color The color.
Returns
The green from color.
    {
        return ((color >> 2) & 0x03) * 0x55;
    }
Referenced by AbstractPainterABGR2222::alphaBlend(), and AbstractPainterABGR2222::alphaBlend().
getNativeColor()
static FORCE_INLINE_FUNCTION uint8_t getNativeColor (colortype color) inline static
Generates a color representation to be used on the LCD, based on 24 bit RGB values.
Parameters
color The color.
Returns
The color representation depending on LCD color format.
    {
        return 0xC0 | ((color >> 22) & 0x03) | ((color >> 12) & 0x0C) | ((color >> 2) & 0x30);
    }
Referenced by PainterABGR2222::setColor().
getNativeColorFromRGB()
static FORCE_INLINE_FUNCTION uint8_t getNativeColorFromRGB (uint8_t red, uint8_t green, uint8_t blue) inline static
Gets color from RGB.
Parameters
red The red.
green The green.
blue The blue.
Returns
The color from RGB.
    {
        return 0xC0 | ((blue & 0xC0) >> 2) | ((green & 0xC0) >> 4) | ((red & 0xC0) >> 6);
    }
Referenced by LCD8bpp_ABGR2222::alphaBlend(), and AbstractPainterABGR2222::alphaBlend().
getRedFromNativeColor()
static FORCE_INLINE_FUNCTION uint8_t getRedFromNativeColor (uint8_t color) inline static
Gets red from color.
Parameters
color The color.
Returns
The red from color.
    {
        return (color & 0x03) * 0x55;
    }
Referenced by AbstractPainterABGR2222::alphaBlend(), and AbstractPainterABGR2222::alphaBlend().
getTextureMapperDrawScanLine()
virtual DrawTextureMapScanLineBase * getTextureMapperDrawScanLine (const TextureSurface & texture, RenderingVariant renderVariant, uint8_t alpha) protected virtual
Gets pointer to object that can draw a scan line which allows for highly specialized and optimized implementation.
Parameters
texture The texture Surface.
renderVariant The render variant.
alpha The global alpha.
Returns
Null if it fails, else the pointer to the texture mapper draw scan line object.
Reimplemented from LCD.
nextLine()
static int nextLine (bool rotatedDisplay, TextRotation textRotation) static protected
Find out how much to advance in the display buffer to get to the next line.
Parameters
rotatedDisplay Is the display running in portrait mode?
textRotation Rotation to perform.
Returns
How much to advance to get to the next line.
nextPixel()
static int nextPixel (bool rotatedDisplay, TextRotation textRotation) static protected
Find out how much to advance in the display buffer to get to the next pixel.
Parameters
rotatedDisplay Is the display running in portrait mode?
textRotation Rotation to perform.
Returns
How much to advance to get to the next pixel.
Member Data Documentation
textureMapper_A4_BilinearInterpolation_GA
DrawTextureMapScanLineBase* textureMapper_A4_BilinearInterpolation_GA private
textureMapper_A4_NearestNeighbor_GA
DrawTextureMapScanLineBase* textureMapper_A4_NearestNeighbor_GA private
textureMapper_ABGR2222_NonOpaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase* textureMapper_ABGR2222_NonOpaque_BilinearInterpolation_GA private
textureMapper_ABGR2222_NonOpaque_NearestNeighbor_GA
DrawTextureMapScanLineBase* textureMapper_ABGR2222_NonOpaque_NearestNeighbor_GA private
textureMapper_ABGR2222_Opaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase* textureMapper_ABGR2222_Opaque_BilinearInterpolation_GA private
textureMapper_ABGR2222_Opaque_NearestNeighbor_GA
DrawTextureMapScanLineBase* textureMapper_ABGR2222_Opaque_NearestNeighbor_GA private
textureMapper_ARGB8888_NonOpaque_BilinearInterpolation_GA
DrawTextureMapScanLineBase* textureMapper_ARGB8888_NonOpaque_BilinearInterpolation_GA private
textureMapper_ARGB8888_NonOpaque_NearestNeighbor_GA
DrawTextureMapScanLineBase* textureMapper_ARGB8888_NonOpaque_NearestNeighbor_GA private
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/platform/driver/lcd/LCD8bpp_ABGR2222.hpp