Battery Simulator Documentation: AnimationTextureMapper
AnimationTextureMapper
#include "AnimationTextureMapper.hpp"
Classes
struct AnimationSetting
Public Types
enum AnimationParameter { X_ROTATION , Y_ROTATION , Z_ROTATION , SCALE }
Public Types inherited from TextureMapper
enum RenderingAlgorithm { NEAREST_NEIGHBOR , BILINEAR_INTERPOLATION }
Public Member Functions
AnimationTextureMapper ()
virtual void cancelAnimationTextureMapperAnimation ()
virtual uint16_t getAnimationStep ()
virtual void handleTickEvent ()
virtual bool isTextureMapperAnimationRunning () const
void setTextureMapperAnimationEndedAction (GenericCallback< const AnimationTextureMapper & > &callback)
void setTextureMapperAnimationStepAction (GenericCallback< const AnimationTextureMapper & > &callback)
virtual void setupAnimation (AnimationParameter parameter, float endValue, uint16_t duration, uint16_t delay, EasingEquation progressionEquation=&EasingEquations::linearEaseNone)
virtual void startAnimation ()
Public Member Functions inherited from TextureMapper
TextureMapper (const Bitmap &bmp=Bitmap())
virtual void draw (const Rect &invalidatedArea) const
virtual float getBitmapPositionX () const
virtual float getBitmapPositionY () const
virtual float getCameraDistance () const
virtual float getCameraX () const
virtual float getCameraY () const
virtual float getOrigoX () const
virtual float getOrigoY () const
virtual float getOrigoZ () const
virtual RenderingAlgorithm getRenderingAlgorithm () const
virtual float getScale () const
virtual Rect getSolidRect () const
virtual float getX0 () const
virtual float getX1 () const
virtual float getX2 () const
virtual float getX3 () const
virtual float getXAngle () const
virtual float getY0 () const
virtual float getY1 () const
virtual float getY2 () const
virtual float getY3 () const
virtual float getYAngle () const
virtual float getZ0 () const
virtual float getZ1 () const
virtual float getZ2 () const
virtual float getZ3 () const
virtual float getZAngle () const
virtual void invalidateContent () const
virtual void setAngles (float newXAngle, float newYAngle, float newZAngle)
virtual void setBitmap (const Bitmap &bmp)
virtual void setBitmapPosition (float x, float y)
virtual void setBitmapPosition (int x, int y)
virtual void setCamera (float x, float y)
virtual void setCameraDistance (float d)
virtual void setOrigo (float x, float y)
virtual void setOrigo (float x, float y, float z)
virtual void setRenderingAlgorithm (RenderingAlgorithm algorithm)
virtual void setScale (float newScale)
virtual void setXAngle (float newXAngle)
virtual void setYAngle (float newYAngle)
virtual void setZAngle (float newZAngle)
TOUCHGFX_DEPRECATED ("Please use invalidateContent() instead.", void invalidateBoundingRect() const)
virtual void updateAngles (float newXAngle, float newYAngle, float newZAngle)
virtual void updateScale (float newScale)
virtual void updateXAngle (float newXAngle)
virtual void updateYAngle (float newYAngle)
virtual void updateZAngle (float newZAngle)
Public Member Functions inherited from Image
Image (const Bitmap &bmp=Bitmap())
uint8_t getAlpha () const
Bitmap getBitmap () const
BitmapId getBitmapId () const
void setAlpha (uint8_t newAlpha)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Static Public Attributes
static const int NUMBER_OF_ANIMATION_PARAMETERS = SCALE + 1
Number of animation parameters.
Protected Attributes
uint16_t animationCounter
Counter that is equal to the current step in the animation.
bool animationRunning
Boolean that is true if the animation is running.
AnimationSetting animations [NUMBER_OF_ANIMATION_PARAMETERS]
Descriptions of the animation of specific animation parameters.
GenericCallback< const AnimationTextureMapper & > * textureMapperAnimationEndedCallback
Callback that is executed after the animation ends.
GenericCallback< const AnimationTextureMapper & > * textureMapperAnimationStepCallback
Callback that is executed after every step of the animation.
Protected Attributes inherited from TextureMapper
float cameraDistance
The camera distance.
RenderingAlgorithm currentRenderingAlgorithm
The current rendering algorithm.
float imageX0
The coordinate for the image points.
float imageX1
The coordinate for the image points.
float imageX2
The coordinate for the image points.
float imageX3
The coordinate for the image points.
float imageY0
The coordinate for the image points.
float imageY1
The coordinate for the image points.
float imageY2
The coordinate for the image points.
float imageY3
The coordinate for the image points.
float imageZ0
The coordinate for the image points.
float imageZ1
The coordinate for the image points.
float imageZ2
The coordinate for the image points.
float imageZ3
The coordinate for the image points.
float scale
The scale.
uint16_t subDivisionSize
The size of the affine sub divisions.
float xAngle
The angle x in radians.
float xBitmapPosition
The bitmap position x.
float xCamera
The camera x coordinate.
float xOrigo
The origo x coordinate.
float yAngle
The angle y in radians.
float yBitmapPosition
The bitmap position y.
float yCamera
The camera y coordinate.
float yOrigo
The origo y coordinate.
float zAngle
The angle z in radians.
float zOrigo
The origo z coordinate.
Protected Attributes inherited from Image
uint8_t alpha
The Alpha for this image.
Bitmap bitmap
The Bitmap to display.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Protected Member Functions inherited from TextureMapper
void applyTransformation ()
void drawQuad (const Rect &invalidatedArea, uint16_t *fb, const float *triangleXs, const float *triangleYs, const float *triangleZs, const float *triangleUs, const float *triangleVs) const
Rect getBoundingRect () const
RenderingVariant lookupRenderVariant () const
Static Protected Attributes inherited from TextureMapper
static const int MINIMAL_CAMERA_DISTANCE = 1
The minimal camera distance.
Detailed Description
A TextureMapper with animation capabilities. Note that the angles of the TextureMapper is normalized to lie in the range [0; 2PI[ at the beginning at the animation. The end angles should be relative to this and are limited to values in the range [-32.7; 32.7].
Member Enumeration Documentation
AnimationParameter
enum AnimationParameter
Values that represent different animation parameter.
Enumerator
X_ROTATION
Rotation around the X axis.
Y_ROTATION
Rotation around the Y axis.
Z_ROTATION
Rotation around the Z axis.
SCALE
Scaling of the image.
    {
        X_ROTATION,
        Y_ROTATION,
        Z_ROTATION,
        SCALE
    };
Constructor & Destructor Documentation
AnimationTextureMapper()
AnimationTextureMapper ()
    : TextureMapper(),
      textureMapperAnimationStepCallback(0),
      textureMapperAnimationEndedCallback(0),
      animationCounter(0),
      animationRunning(false)
{
    for (int i = 0; i < NUMBER_OF_ANIMATION_PARAMETERS; i++)
    {
        animations[i].animationActive = false;
    }
}
References AnimationTextureMapper::AnimationSetting::animationActive, AnimationTextureMapper::animations, and AnimationTextureMapper::NUMBER_OF_ANIMATION_PARAMETERS.
Member Function Documentation
cancelAnimationTextureMapperAnimation()
void cancelAnimationTextureMapperAnimation () virtual
Cancel the animation. Stops any running animation at the current position regardless of the progress made so far. Disables all animation parameters set using setupAnimation and mark the animation as stopped.
{
    Application::getInstance()->unregisterTimerWidget(this);
    animationRunning = false;
    for (int i = 0; i < NUMBER_OF_ANIMATION_PARAMETERS; i++)
    {
        animations[i].animationActive = false;
    }
}
References AnimationTextureMapper::AnimationSetting::animationActive, AnimationTextureMapper::animationRunning, AnimationTextureMapper::animations, Application::getInstance(), and AnimationTextureMapper::NUMBER_OF_ANIMATION_PARAMETERS.
Referenced by AnimationTextureMapper::handleTickEvent(), and AnalogClock::updateClock().
getAnimationStep()
uint16_t getAnimationStep () virtual
Gets the current animation step measured in ticks since the call to startAnimation(). The steps during the initial delay are also counted.
Returns
The current animation step.
{
    return animationCounter;
}
References AnimationTextureMapper::animationCounter.
handleTickEvent()
void handleTickEvent () virtual
Called periodically by the framework if the Drawable instance has subscribed to timer ticks.
See also
Application::registerTimerWidget
Reimplemented from Drawable.
{
    if (!animationRunning)
    {
        return;
    }
    bool newAngleAssigned = false;
    bool newScaleAssigned = false;
    bool activeAnimationExists = false;
    animationCounter++;
    float newXAngle = xAngle;
    float newYAngle = yAngle;
    float newZAngle = zAngle;
    float newScale = scale;
    for (int i = 0; i < NUMBER_OF_ANIMATION_PARAMETERS; i++)
    {
        if (!(animations[i].animationActive))
        {
            continue;
        }
        if (animationCounter >= animations[i].animationDelay)
        {
            // Adjust the used animationCounter for the startup delay
            const uint32_t actualAnimationCounter = animationCounter - animations[i].animationDelay;
            int directionModifier;
            int16_t distance;
            if (animations[i].animationEnd > animations[i].animationStart)
            {
                directionModifier = 1;
                distance = (int16_t)((animations[i].animationEnd - animations[i].animationStart) * 1000);
            }
            else
            {
                directionModifier = -1;
                distance = (int16_t)((animations[i].animationStart - animations[i].animationEnd) * 1000);
            }
            const float delta = (float)directionModifier * (animations[i].animationProgressionEquation(actualAnimationCounter, 0, distance, animations[i].animationDuration) / 1000.f);
            switch ((AnimationParameter)i)
            {
            case X_ROTATION:
                newXAngle = animations[X_ROTATION].animationStart + delta;
                newAngleAssigned = true;
                break;
            case Y_ROTATION:
                newYAngle = animations[Y_ROTATION].animationStart + delta;
                newAngleAssigned = true;
                break;
            case Z_ROTATION:
                newZAngle = animations[Z_ROTATION].animationStart + delta;
                newAngleAssigned = true;
                break;
            case SCALE:
                newScale = animations[SCALE].animationStart + delta;
                newScaleAssigned = true;
                break;
            }
        }
        if (animationCounter >= (uint32_t)(animations[i].animationDelay + animations[i].animationDuration))
        {
            animations[i].animationActive = false;
        }
        else
        {
            activeAnimationExists = true;
        }
    }
    if (newAngleAssigned || newScaleAssigned)
    {
        if (newAngleAssigned)
        {
            updateAngles(newXAngle, newYAngle, newZAngle);
        }
        if (newScaleAssigned)
        {
            updateScale(newScale);
        }
        if (textureMapperAnimationStepCallback && textureMapperAnimationStepCallback->isValid())
        {
            textureMapperAnimationStepCallback->execute(*this);
        }
    }
    if (!activeAnimationExists)
    {
        // End of animation
        cancelAnimationTextureMapperAnimation();
        if (textureMapperAnimationEndedCallback && textureMapperAnimationEndedCallback->isValid())
        {
            textureMapperAnimationEndedCallback->execute(*this);
        }
    }
}
References AnimationTextureMapper::AnimationSetting::animationActive, AnimationTextureMapper::animationCounter, AnimationTextureMapper::AnimationSetting::animationDelay, AnimationTextureMapper::AnimationSetting::animationDuration, AnimationTextureMapper::animationRunning, AnimationTextureMapper::animations, AnimationTextureMapper::AnimationSetting::animationStart, AnimationTextureMapper::cancelAnimationTextureMapperAnimation(), AnimationTextureMapper::NUMBER_OF_ANIMATION_PARAMETERS, AnimationTextureMapper::SCALE, TextureMapper::scale, AnimationTextureMapper::textureMapperAnimationEndedCallback, AnimationTextureMapper::textureMapperAnimationStepCallback, TextureMapper::updateAngles(), TextureMapper::updateScale(), AnimationTextureMapper::X_ROTATION, TextureMapper::xAngle, AnimationTextureMapper::Y_ROTATION, TextureMapper::yAngle, AnimationTextureMapper::Z_ROTATION, and TextureMapper::zAngle.
Referenced by AnimationTextureMapper::startAnimation().
isTextureMapperAnimationRunning()
bool isTextureMapperAnimationRunning () const virtual
Gets whether or not the animation is running.
Returns
true if the animation is running.
{
    return animationRunning;
}
References AnimationTextureMapper::animationRunning.
Referenced by AnalogClock::updateClock().
setTextureMapperAnimationEndedAction()
void setTextureMapperAnimationEndedAction (GenericCallback< const AnimationTextureMapper & > & callback)
Associates an action to be performed when the animation ends.
Parameters
callback The callback to be executed. The callback will be given a reference to the AnimationTextureMapper.
See also
GenericCallback
{
    textureMapperAnimationEndedCallback = &callback;
}
References AnimationTextureMapper::textureMapperAnimationEndedCallback.
setTextureMapperAnimationStepAction()
void setTextureMapperAnimationStepAction (GenericCallback< const AnimationTextureMapper & > & callback)
Associates an action to be performed for every step in the animation. Will not be called during the delay period.
Parameters
callback The callback to be executed. The callback will be given a reference to the AnimationTextureMapper.
See also
GenericCallback
{
    textureMapperAnimationStepCallback = &callback;
}
References AnimationTextureMapper::textureMapperAnimationStepCallback.
setupAnimation()
void setupAnimation (AnimationParameter parameter, float endValue, uint16_t duration, uint16_t delay, EasingEquation progressionEquation = &EasingEquations::linearEaseNone) virtual
Sets up the animation for a specific parameter (angle/scale) for the next animation. The specific parameter is chosen using the AnimationType enum. AnimationTypes that are not setup using this method will keep their value during the animation.
Parameters
parameter The parameter of the TextureMapper that should be animated.
endValue The end value for the parameter.
duration The duration for the animation of the parameter. Specified in ticks.
delay The delay before the animation of the parameter starts. Specified in ticks.
progressionEquation (Optional) the progression equation for the animation of this parameter. Default is EasingEquations::linearEaseNone.
{
    animations[parameter].animationActive = true;
    animations[parameter].animationEnd = endValue;
    animations[parameter].animationDuration = duration;
    animations[parameter].animationDelay = delay;
    animations[parameter].animationProgressionEquation = progressionEquation;
}
References AnimationTextureMapper::AnimationSetting::animationActive, AnimationTextureMapper::AnimationSetting::animationDelay, AnimationTextureMapper::AnimationSetting::animationDuration, AnimationTextureMapper::AnimationSetting::animationEnd, AnimationTextureMapper::AnimationSetting::animationProgressionEquation, and AnimationTextureMapper::animations.
Referenced by AnalogClock::updateClock().
startAnimation()
void startAnimation () virtual
Starts the animation from the current position to the specified end angles/scale, as specified by one or more calls to setupAnimation().
{
    if (!animationRunning)
    {
        Application::getInstance()->registerTimerWidget(this);
    }
    animationCounter = 0;
    animations[X_ROTATION].animationStart = xAngle;
    animations[Y_ROTATION].animationStart = yAngle;
    animations[Z_ROTATION].animationStart = zAngle;
    animations[SCALE].animationStart = scale;
    animationRunning = true;
    for (int i = 0; i < NUMBER_OF_ANIMATION_PARAMETERS; i++)
    {
        if (animations[i].animationActive && animations[i].animationDelay + animations[i].animationDuration > 0)
        {
            return; // Animation needs to run, return
        }
    }
    // No active animations or all active animations have zero steps, execute now!
    handleTickEvent();
}
References AnimationTextureMapper::animationCounter, AnimationTextureMapper::animationRunning, AnimationTextureMapper::animations, AnimationTextureMapper::AnimationSetting::animationStart, Application::getInstance(), AnimationTextureMapper::handleTickEvent(), AnimationTextureMapper::NUMBER_OF_ANIMATION_PARAMETERS, AnimationTextureMapper::SCALE, TextureMapper::scale, AnimationTextureMapper::X_ROTATION, TextureMapper::xAngle, AnimationTextureMapper::Y_ROTATION, TextureMapper::yAngle, AnimationTextureMapper::Z_ROTATION, and TextureMapper::zAngle.
Referenced by AnalogClock::updateClock().
Member Data Documentation
animationCounter
uint16_t animationCounter protected
Counter that is equal to the current step in the animation.
Referenced by AnimationTextureMapper::getAnimationStep(), AnimationTextureMapper::handleTickEvent(), and AnimationTextureMapper::startAnimation().
animationRunning
bool animationRunning protected
Boolean that is true if the animation is running.
Referenced by AnimationTextureMapper::cancelAnimationTextureMapperAnimation(), AnimationTextureMapper::handleTickEvent(), AnimationTextureMapper::isTextureMapperAnimationRunning(), and AnimationTextureMapper::startAnimation().
animations
AnimationSetting animations[NUMBER_OF_ANIMATION_PARAMETERS] protected
Descriptions of the animation of specific animation parameters.
Referenced by AnimationTextureMapper::AnimationTextureMapper(), AnimationTextureMapper::cancelAnimationTextureMapperAnimation(), AnimationTextureMapper::handleTickEvent(), AnimationTextureMapper::setupAnimation(), and AnimationTextureMapper::startAnimation().
NUMBER_OF_ANIMATION_PARAMETERS
const int NUMBER_OF_ANIMATION_PARAMETERS = SCALE + 1 static
Number of animation parameters.
Referenced by AnimationTextureMapper::AnimationTextureMapper(), AnimationTextureMapper::cancelAnimationTextureMapperAnimation(), AnimationTextureMapper::handleTickEvent(), and AnimationTextureMapper::startAnimation().
textureMapperAnimationEndedCallback
GenericCallback<const AnimationTextureMapper&>* textureMapperAnimationEndedCallback protected
Callback that is executed after the animation ends.
Referenced by AnimationTextureMapper::handleTickEvent(), and AnimationTextureMapper::setTextureMapperAnimationEndedAction().
textureMapperAnimationStepCallback
GenericCallback<const AnimationTextureMapper&>* textureMapperAnimationStepCallback protected
Callback that is executed after every step of the animation.
Referenced by AnimationTextureMapper::handleTickEvent(), and AnimationTextureMapper::setTextureMapperAnimationStepAction().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/AnimationTextureMapper.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/AnimationTextureMapper.cpp