Battery Simulator Documentation: Box
Box
#include "Box.hpp"
Public Member Functions
Box ()
Box (uint16_t width, uint16_t height, colortype boxColor, uint8_t boxAlpha=255)
virtual void draw (const Rect &area) const
FORCE_INLINE_FUNCTION uint8_t getAlpha () const
FORCE_INLINE_FUNCTION colortype getColor () const
virtual Rect getSolidRect () const
virtual void invalidateContent () const
void setAlpha (uint8_t newAlpha)
void setColor (colortype newColor)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
uint8_t alpha
The alpha value used for this Box.
colortype color
The fill color for this Box.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
Simple widget capable of showing a rectangle of a specific color and an optional alpha.
Constructor & Destructor Documentation
Box() [1/2]
Box () inline
Construct a new Box with a default alpha value of 255 (solid)
        : Widget(), alpha(255), color(0)
    {
    }
Box() [2/2]
Box (uint16_t width, uint16_t height, colortype boxColor, uint8_t boxAlpha = 255) inline
Construct a Box with the given size and color (and optionally alpha).
Parameters
width The width of the box.
height The height of the box.
boxColor The color of the box.
boxAlpha (Optional) The alpha of the box. Default is 255 (solid).
        : Widget(), alpha(boxAlpha), color(boxColor)
    {
        rect.width = width;
        rect.height = height;
    }
References Rect::height, Drawable::rect, and Rect::width.
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Implements Drawable.
Reimplemented in BoxWithBorder.
{
    Rect dirty = area;
    translateRectToAbsolute(dirty);
    HAL::lcd().fillRect(dirty, color, alpha);
}
References touchgfx::dirty, HAL::lcd(), and Drawable::translateRectToAbsolute().
Referenced by BoxWithBorder::draw().
getAlpha()
FORCE_INLINE_FUNCTION uint8_t getAlpha () const inline
Gets the current alpha value of the widget. The alpha value is in range 255 (solid) to 0 (invisible).
Returns
The current alpha value.
See also
setAlpha
    {
        return alpha;
    }
References Box::alpha.
Referenced by ModalWindow::getShadeAlpha().
getColor()
FORCE_INLINE_FUNCTION colortype getColor () const inline
Gets the current color of the Box.
Returns
The current color of the box.
See also
setColor, Color::getRed, Color::getGreen, Color::getRed
    {
        return color;
    }
References Box::color.
Referenced by BoxProgress::getColor(), and ModalWindow::getShadeColor().
getSolidRect()
Rect getSolidRect () const virtual
Get (the largest possible) rectangle that is guaranteed to be solid (opaque). This information is important, as any Drawable underneath the solid area does not need to be drawn.
Returns
The solid rectangle part of the Drawable.
Note
The rectangle returned must be relative to upper left corner of the Drawable, meaning that a completely solid widget should return the full size Rect(0, 0, getWidth(), getHeight()). If no area can be guaranteed to be solid, an empty Rect must be returned. Failing to return the correct rectangle may result in errors on the display.
Implements Drawable.
{
    Rect solidRect;
    if (alpha == 255)
    {
        solidRect.width = rect.width;
        solidRect.height = rect.height;
    }
    return solidRect;
}
References Rect::height, Drawable::rect, and Rect::width.
invalidateContent()
virtual void invalidateContent () const inline virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from Drawable.
    {
        if (alpha > 0)
        {
            Widget::invalidateContent();
        }
    }
References Drawable::invalidateContent().
setAlpha()
void setAlpha (uint8_t newAlpha) inline
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
    {
        alpha = newAlpha;
    }
Referenced by BoxWithBorderButtonStyle< T >::handleAlphaUpdated(), BoxProgress::setAlpha(), ScrollableContainer::setScrollbarsAlpha(), and ModalWindow::setShadeAlpha().
setColor()
void setColor (colortype newColor) inline
Sets the color of the Box.
Parameters
newColor The color of the box.
See also
getColor, Color::getColorFromRGB
    {
        color = newColor;
    }
Referenced by ModalWindow::ModalWindow(), Screen1ViewBase::Screen1ViewBase(), BoxWithBorderButtonStyle< T >::handlePressedUpdated(), BoxProgress::setColor(), ScrollableContainer::setScrollbarsColor(), and ModalWindow::setShadeColor().
Member Data Documentation
alpha
uint8_t alpha protected
The alpha value used for this Box.
Referenced by Box::getAlpha().
color
colortype color protected
The fill color for this Box.
Referenced by Box::getColor().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/Box.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/Box.cpp