Battery Simulator Documentation: DirectFrameBufferVideoController< no_streams, output_format >
DirectFrameBufferVideoController< no_streams, output_format >
#include "DirectFrameBufferVideoController.hpp"
Classes
class Stream
Public Member Functions
DirectFrameBufferVideoController ()
void addDecoder (MJPEGDecoder &decoder, uint32_t index)
void draw (const Handle handle, const touchgfx::Rect &invalidatedArea, const touchgfx::VideoWidget &widget)
uint32_t getCurrentFrameNumber (const Handle handle)
bool getIsPlaying (const Handle handle)
void getVideoInformation (const Handle handle, touchgfx::VideoInformation *data)
Handle registerVideoWidget (touchgfx::VideoWidget &widget)
void setCommand (const Handle handle, Command cmd, uint32_t param)
void setFrameRate (const Handle handle, uint32_t ui_frames, uint32_t video_frames)
void setVideoData (const Handle handle, const uint8_t *movie, const uint32_t length)
void setVideoData (const Handle handle, touchgfx::VideoDataReader &reader)
void setVideoFrameRateCompensation (const bool allow)
void unregisterVideoWidget (const Handle handle)
bool updateFrame (const Handle handle, touchgfx::VideoWidget &widget)
Public Member Functions inherited from VideoController
virtual ~VideoController ()
Private Member Functions
bool decodeForNextTick (Stream &stream)
Handle getFreeHandle ()
Private Attributes
bool allowSkipFrames
MJPEGDecoder * mjpegDecoders [no_streams]
Stream streams [no_streams]
Additional Inherited Members
Public Types inherited from VideoController
enum Command {
PLAY , PAUSE , SEEK , SHOW ,
STOP , SET_REPEAT
}
typedef uint32_t Handle
Static Public Member Functions inherited from VideoController
static VideoController & getInstance ()
Detailed Description
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format>
class DirectFrameBufferVideoController< no_streams, output_format >
Strategy: Decode directly into the framebuffer in draw. Tick will decide if we are going to a new frame.
Constructor & Destructor Documentation
DirectFrameBufferVideoController()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> DirectFrameBufferVideoController () inline
        : VideoController(), allowSkipFrames(true)
    {
        assert((no_streams > 0) && "Video: Number of streams zero!");
        // Clear arrays
        memset(mjpegDecoders, 0, sizeof(mjpegDecoders));
    }
References DirectFrameBufferVideoController< no_streams, output_format >::mjpegDecoders.
Member Function Documentation
addDecoder()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> void addDecoder (MJPEGDecoder & decoder, uint32_t index) inline
    {
        assert(index < no_streams);
        mjpegDecoders[index] = &decoder;
    }
References DirectFrameBufferVideoController< no_streams, output_format >::mjpegDecoders.
decodeForNextTick()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> bool decodeForNextTick (Stream & stream) inline private
Return true, if new video frame should be decoded for the next tick (keep video decode framerate low)
    {
        // Running in UI thread
        // Compare tickCount/frameNumber to frame_rate_ticks/frame_rate_video
        if ((stream.tickCount * stream.frame_rate_video) > (stream.frame_rate_ticks * stream.frameCount))
        {
            if (allowSkipFrames)
            {
                stream.skip_frames = (stream.tickCount * stream.frame_rate_video - stream.frame_rate_ticks * stream.frameCount) / stream.frame_rate_ticks;
                if (stream.skip_frames > 0)
                {
                    stream.skip_frames--;
                }
            }
            return true;
        }
        return false;
    }
References DirectFrameBufferVideoController< no_streams, output_format >::allowSkipFrames.
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::updateFrame().
draw()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> void draw (const Handle handle, const touchgfx::Rect & invalidatedArea, const touchgfx::VideoWidget & widget) inline virtual
Draw the video content.
Parameters
handle The stream handle.
invalidatedArea The area of the widget that must be redrawn.
widget Reference to the widget.
Implements VideoController.
    {
        assert(handle < no_streams);
        if (output_format != Bitmap::RGB565 && output_format != Bitmap::RGB888 && output_format != Bitmap::ARGB8888)
        {
            return;
        }
        if (mjpegDecoders[handle]->hasVideo())
        {
            uint8_t* wbuf = (uint8_t*)touchgfx::HAL::getInstance()->lockFrameBuffer();
            const touchgfx::Rect& absolute = widget.getAbsoluteRect();
            // Get frame buffer pointer to upper left of widget in framebuffer coordinates
            switch(output_format)
            {
                case Bitmap::RGB565:
                    wbuf += (absolute.x + absolute.y * touchgfx::HAL::FRAME_BUFFER_WIDTH) * 2;
                    break;
                case Bitmap::RGB888:
                    wbuf += (absolute.x + absolute.y * touchgfx::HAL::FRAME_BUFFER_WIDTH) * 3;
                    break;
                case Bitmap::ARGB8888:
                    wbuf += (absolute.x + absolute.y * touchgfx::HAL::FRAME_BUFFER_WIDTH) * 4;
                    break;
                default:
                    break;
            }
            // Decode relevant part of the frame to the framebuffer
            mjpegDecoders[handle]->decodeFrame(invalidatedArea, wbuf, touchgfx::HAL::FRAME_BUFFER_WIDTH);
            // Release frame buffer
            touchgfx::HAL::getInstance()->unlockFrameBuffer();
        }
    }
References MJPEGDecoder::decodeFrame(), HAL::FRAME_BUFFER_WIDTH, Drawable::getAbsoluteRect(), HAL::getInstance(), DirectFrameBufferVideoController< no_streams, output_format >::mjpegDecoders, Rect::x, and Rect::y.
getCurrentFrameNumber()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> uint32_t getCurrentFrameNumber (const Handle handle) inline virtual
Get the current frame number.
Parameters
handle The stream handle.
Returns
Return the current frame number.
Implements VideoController.
    {
        assert(handle < no_streams);
        Stream& stream = streams[handle];
        return stream.frameNumber;
    }
References DirectFrameBufferVideoController< no_streams, output_format >::Stream::frameNumber, and DirectFrameBufferVideoController< no_streams, output_format >::streams.
getFreeHandle()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> Handle getFreeHandle () inline private
    {
        for (uint32_t i = 0; i < no_streams; i++)
        {
            if (streams[i].isActive == false)
            {
                return static_cast<VideoController::Handle>(i);
            }
        }
        assert(0 && "Unable to find free video stream handle!");
        return static_cast<VideoController::Handle>(0);
    }
References DirectFrameBufferVideoController< no_streams, output_format >::streams.
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::registerVideoWidget().
getIsPlaying()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> bool getIsPlaying (const Handle handle) inline virtual
Check if the video stream is playing (not paused or stopped).
Parameters
handle The stream handle.
Returns
Returns true if the video is playing.
Implements VideoController.
    {
        assert(handle < no_streams);
        Stream& stream = streams[handle];
        return stream.isPlaying;
    }
References DirectFrameBufferVideoController< no_streams, output_format >::Stream::isPlaying, and DirectFrameBufferVideoController< no_streams, output_format >::streams.
getVideoInformation()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> void getVideoInformation (const Handle handle, touchgfx::VideoInformation * data) inline virtual
Get Video information.
Get information from the video data.
Parameters
handle The stream handle.
[in,out] data Pointer to VideoInformation where information should be stored.
Implements VideoController.
    {
        assert(handle < no_streams);
        mjpegDecoders[handle]->getVideoInfo(data);
    }
References MJPEGDecoder::getVideoInfo(), and DirectFrameBufferVideoController< no_streams, output_format >::mjpegDecoders.
registerVideoWidget()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> Handle registerVideoWidget (touchgfx::VideoWidget & widget) inline virtual
Register a VideoWidget to get a Handle.
Parameters
[in,out] widget The VideoWidget.
Returns
A video stream handle.
Implements VideoController.
    {
        // Find stream handle for Widget
        Handle handle = getFreeHandle();
        streams[handle].isActive = true;
        //Set Widget buffer format and address
        widget.setVideoBufferFormat(output_format, 0, 0);
        widget.setVideoBuffer((uint8_t*)0);
        return handle;
    }
References DirectFrameBufferVideoController< no_streams, output_format >::getFreeHandle(), DirectFrameBufferVideoController< no_streams, output_format >::Stream::isActive, VideoWidget::setVideoBuffer(), VideoWidget::setVideoBufferFormat(), and DirectFrameBufferVideoController< no_streams, output_format >::streams.
setCommand()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> void setCommand (const Handle handle, Command cmd, uint32_t param) inline virtual
Pass a command from the Widget to the Controller.
Parameters
handle The stream handle.
cmd The Command.
param A parameter.
Implements VideoController.
    {
        assert(handle < no_streams);
        Stream& stream = streams[handle];
        switch (cmd)
        {
        case PLAY:
            // Cannot Play without movie
            if (mjpegDecoders[handle]->hasVideo())
            {
                stream.isPlaying = true;
                stream.isShowingOneFrame = false;
                // Reset counters
                stream.frameCount = 0;
                stream.tickCount = 0;
                // If non-repeating video stopped at the end, kick to next frame
                if (!stream.repeat)
                {
                    MJPEGDecoder* const decoder = mjpegDecoders[handle];
                    if (decoder->getCurrentFrameNumber() == decoder->getNumberOfFrames())
                    {
                        decoder->gotoNextFrame();
                    }
                }
            }
            break;
        case PAUSE:
            stream.isPlaying = false;
            stream.isShowingOneFrame = false;
            break;
        case SEEK:
            stream.seek_to_frame = param;
            // Reset counters
            stream.frameCount = 0;
            stream.tickCount = 0;
            break;
        case SHOW:
            stream.seek_to_frame = param;
            stream.isShowingOneFrame = true;
            stream.doDecodeNextFrame = true;
            // Reset counters
            stream.frameCount = 0;
            stream.tickCount = 0;
            break;
        case STOP:
            stream.isPlaying = false;
            stream.isShowingOneFrame = false;
            stream.seek_to_frame = 1;
            // Reset counters
            stream.frameCount = 0;
            stream.tickCount = 0;
            break;
        case SET_REPEAT:
            stream.repeat = (param > 0);
            break;
        }
    }
References MJPEGDecoder::getCurrentFrameNumber(), MJPEGDecoder::getNumberOfFrames(), MJPEGDecoder::gotoNextFrame(), DirectFrameBufferVideoController< no_streams, output_format >::Stream::isPlaying, DirectFrameBufferVideoController< no_streams, output_format >::mjpegDecoders, VideoController::PAUSE, VideoController::PLAY, VideoController::SEEK, VideoController::SET_REPEAT, VideoController::SHOW, VideoController::STOP, and DirectFrameBufferVideoController< no_streams, output_format >::streams.
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::setVideoData(), and DirectFrameBufferVideoController< no_streams, output_format >::setVideoData().
setFrameRate()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> void setFrameRate (const Handle handle, uint32_t ui_frames, uint32_t video_frames) inline virtual
Set the framerate for video using a qoutient of screen frames /video frames.
To get 20 video frames pr second on a 60 fps display use video_frames = 20 and ui_frames = 60.
Parameters
handle The stream handle.
ui_frames Number of UI frames (divider)
video_frames Number of video_frames (dividend)
Implements VideoController.
    {
        assert(handle < no_streams);
        Stream& stream = streams[handle];
        // Reset counters
        stream.frameCount = 0;
        stream.tickCount = 0;
        // Save requested frame rate ratio
        stream.frame_rate_ticks = ui_frames;
        stream.frame_rate_video = video_frames;
    }
References DirectFrameBufferVideoController< no_streams, output_format >::Stream::frameCount, and DirectFrameBufferVideoController< no_streams, output_format >::streams.
setVideoData() [1/2]
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> void setVideoData (const Handle handle, const uint8_t * movie, const uint32_t length) inline virtual
Set the video data for the stream.
Parameters
handle The stream handle.
movie Pointer to the video data.
length Length of the video data.
Implements VideoController.
    {
        assert(handle < no_streams);
        // Reset decoder to first frame
        mjpegDecoders[handle]->setVideoData(movie, length);
        // Lower flag to show the first frame
        Stream& stream = streams[handle];
        stream.frameNumber = mjpegDecoders[handle]->getCurrentFrameNumber();
        stream.doDecodeNextFrame = false;
        // Stop playing
        setCommand(handle, PAUSE, 0);
    }
References DirectFrameBufferVideoController< no_streams, output_format >::Stream::frameNumber, MJPEGDecoder::getCurrentFrameNumber(), DirectFrameBufferVideoController< no_streams, output_format >::mjpegDecoders, VideoController::PAUSE, DirectFrameBufferVideoController< no_streams, output_format >::setCommand(), MJPEGDecoder::setVideoData(), and DirectFrameBufferVideoController< no_streams, output_format >::streams.
setVideoData() [2/2]
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> void setVideoData (const Handle handle, touchgfx::VideoDataReader & reader) inline virtual
Set the video data for the stream.
Parameters
handle The stream handle.
[in,out] reader Reference to a VideoDataReader object.
Implements VideoController.
    {
        assert(handle < no_streams);
        // Reset decoder to first frame
        mjpegDecoders[handle]->setVideoData(reader);
        // Lower flag to show the first frame
        Stream& stream = streams[handle];
        stream.frameNumber = mjpegDecoders[handle]->getCurrentFrameNumber();
        stream.doDecodeNextFrame = false;
        // Stop playing
        setCommand(handle, PAUSE, 0);
    }
References DirectFrameBufferVideoController< no_streams, output_format >::Stream::frameNumber, MJPEGDecoder::getCurrentFrameNumber(), DirectFrameBufferVideoController< no_streams, output_format >::mjpegDecoders, VideoController::PAUSE, DirectFrameBufferVideoController< no_streams, output_format >::setCommand(), MJPEGDecoder::setVideoData(), and DirectFrameBufferVideoController< no_streams, output_format >::streams.
setVideoFrameRateCompensation()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> void setVideoFrameRateCompensation (const bool allow) inline virtual
Allow skipping of video frames to compensate for long decoding times.
Parameters
allow true if compensation is allowed.
Implements VideoController.
    {
        allowSkipFrames = allow;
    }
References DirectFrameBufferVideoController< no_streams, output_format >::allowSkipFrames.
unregisterVideoWidget()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> void unregisterVideoWidget (const Handle handle) inline virtual
Unregister a VideoWidget to release the handle.
Parameters
handle The stream handle.
Implements VideoController.
    {
        streams[handle].isActive = false;
    }
References DirectFrameBufferVideoController< no_streams, output_format >::Stream::isActive, and DirectFrameBufferVideoController< no_streams, output_format >::streams.
updateFrame()
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> bool updateFrame (const Handle handle, touchgfx::VideoWidget & widget) inline virtual
Signal that the widget can be invalidated (tickEvent).
Parameters
handle The stream handle.
[in,out] widget The Widget.
Returns
Returns true if video has more frames (i.e. false on the last frame).
Implements VideoController.
    {
        assert(handle < no_streams);
        Stream& stream = streams[handle];
        bool hasMoreFrames = true;
        if (stream.isPlaying || stream.isShowingOneFrame)
        {
            // Increase tickCount
            stream.tickCount+=HAL::getInstance()->getLCDRefreshCount();
            // Lower flag
            stream.isShowingOneFrame = false;
            if (stream.doDecodeNextFrame)
            {
                MJPEGDecoder* const decoder = mjpegDecoders[handle];
                // Invalidate to get widget redrawn
                widget.invalidate();
                // Seek or increment video frame
                if (stream.seek_to_frame > 0)
                {
                    decoder->gotoFrame(stream.seek_to_frame);
                    hasMoreFrames = (stream.seek_to_frame < decoder->getNumberOfFrames());
                    stream.seek_to_frame = 0;
                }
                else
                {
                    if (stream.skip_frames > 0)
                    {
                        decoder->gotoFrame(decoder->getCurrentFrameNumber() + stream.skip_frames);
                        stream.frameCount += stream.skip_frames;
                        stream.skip_frames = 0;
                    }
                    if (stream.repeat)
                    {
                        hasMoreFrames = decoder->gotoNextFrame();
                    }
                    else
                    {
                        if (decoder->getCurrentFrameNumber() < decoder->getNumberOfFrames())
{
                            hasMoreFrames = decoder->gotoNextFrame();
                        }
                        else
{
                            stream.isPlaying = false;
                            hasMoreFrames = false;
                        }
                    }
                }
                stream.frameNumber = decoder->getCurrentFrameNumber();
                stream.frameCount++;
            }
            // Save decode status for next frame
            stream.doDecodeNextFrame = decodeForNextTick(stream);
        }
        return hasMoreFrames;
    }
References DirectFrameBufferVideoController< no_streams, output_format >::decodeForNextTick(), MJPEGDecoder::getCurrentFrameNumber(), MJPEGDecoder::getNumberOfFrames(), MJPEGDecoder::gotoFrame(), MJPEGDecoder::gotoNextFrame(), Drawable::invalidate(), DirectFrameBufferVideoController< no_streams, output_format >::mjpegDecoders, DirectFrameBufferVideoController< no_streams, output_format >::streams, and DirectFrameBufferVideoController< no_streams, output_format >::Stream::tickCount.
Member Data Documentation
allowSkipFrames
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> bool allowSkipFrames private
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::decodeForNextTick(), and DirectFrameBufferVideoController< no_streams, output_format >::setVideoFrameRateCompensation().
mjpegDecoders
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> MJPEGDecoder* mjpegDecoders[no_streams] private
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::DirectFrameBufferVideoController(), DirectFrameBufferVideoController< no_streams, output_format >::addDecoder(), DirectFrameBufferVideoController< no_streams, output_format >::draw(), DirectFrameBufferVideoController< no_streams, output_format >::getVideoInformation(), DirectFrameBufferVideoController< no_streams, output_format >::setCommand(), DirectFrameBufferVideoController< no_streams, output_format >::setVideoData(), DirectFrameBufferVideoController< no_streams, output_format >::setVideoData(), and DirectFrameBufferVideoController< no_streams, output_format >::updateFrame().
streams
template<uint32_t no_streams, touchgfx::Bitmap::BitmapFormat output_format> Stream streams[no_streams] private
Referenced by DirectFrameBufferVideoController< no_streams, output_format >::getCurrentFrameNumber(), DirectFrameBufferVideoController< no_streams, output_format >::getFreeHandle(), DirectFrameBufferVideoController< no_streams, output_format >::getIsPlaying(), DirectFrameBufferVideoController< no_streams, output_format >::registerVideoWidget(), DirectFrameBufferVideoController< no_streams, output_format >::setCommand(), DirectFrameBufferVideoController< no_streams, output_format >::setFrameRate(), DirectFrameBufferVideoController< no_streams, output_format >::setVideoData(), DirectFrameBufferVideoController< no_streams, output_format >::setVideoData(), DirectFrameBufferVideoController< no_streams, output_format >::unregisterVideoWidget(), and DirectFrameBufferVideoController< no_streams, output_format >::updateFrame().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/simulator/include/simulator/video/DirectFrameBufferVideoController.hpp