Battery Simulator Documentation: AbstractPainterBitmap
AbstractPainterBitmap
#include "AbstractPainterBitmap.hpp"
Public Member Functions
AbstractPainterBitmap (const Bitmap &bmp=Bitmap(BITMAP_INVALID))
virtual ~AbstractPainterBitmap ()
Bitmap getBitmap () const
void getOffset (int16_t &x, int16_t &y)
bool getTiled () const
virtual void setBitmap (const Bitmap &bmp)
virtual void setOffset (int16_t x, int16_t y)
virtual void setTiled (bool tiled)
Protected Member Functions
bool adjustBitmapXY (int16_t &bitmapX, int16_t &bitmapY, int16_t &offset, int16_t &count) const
void updateBitmapOffsets (int16_t widgetWidth) const
Protected Attributes
Bitmap bitmap
The bitmap to be used when painting.
const uint8_t * bitmapData
Pointer to the bitmap data.
Bitmap::BitmapFormat bitmapFormat
Copy of the bitmap format (for speed reasons)
Rect bitmapRect
Bitmap rectangle translated to framebuffer coordinates.
bool isTiled
True if bitmap should be tiled, false if not.
int16_t xOffset
The x offset of the bitmap.
int16_t yOffset
The y offset of the bitmap.
Private Attributes
int16_t xDelta
int16_t yDelta
Detailed Description
An abstract class for creating painter classes for drawing canvas widgets. All canvas widgets need a painter to fill the shape drawn with a CanvasWidgetRenderer. The painter must provide the color of a pixel on a given coordinate, which will the be blended into the framebuffer depending on the position of the canvas widget and the transparency of the given pixel.
The AbstractPainter also implements a function which will blend each pixel in a scanline snippet into the framebuffer, but for better performance, the function should be reimplemented in each painter.
Constructor & Destructor Documentation
AbstractPainterBitmap()
AbstractPainterBitmap (const Bitmap & bmp = Bitmap(BITMAP_INVALID)) inline
Constructor
Parameters
bmp (Optional) The bitmap to use in the painter.
        : bitmap(bmp), bitmapFormat(), bitmapRect(), bitmapData(0), xOffset(0), yOffset(0), isTiled(false)
    {
        setBitmap(bmp);
    }
References AbstractPainterBitmap::setBitmap().
~AbstractPainterBitmap()
virtual ~AbstractPainterBitmap () inline virtual
Destructor
    {
    }
Member Function Documentation
adjustBitmapXY()
bool adjustBitmapXY (int16_t & bitmapX, int16_t & bitmapY, int16_t & offset, int16_t & count) const inline protected
Adjust bitmap x and y. For a tiled bitmap painters, the coordinates are fixed to be inside the bitmap, for non-tiled bitmap painters, false is returned if the entire span (considering offset and count) is outside the bitmap - otherwise, the parameters are adjust to make sure that the requested number of pixels can be read from the bitmap at the given coordinate and count pixels ahead.
Parameters
[in,out] bitmapX The bitmap x coordinate.
[in,out] bitmapY The bitmap y coordinate.
[in,out] offset The pointer x coordinate.
[in,out] count Number of.
Returns
True if anything should be painted, false if nothing has to be painted.
    {
        bitmapX += xDelta;
        bitmapY += yDelta;
        if (isTiled)
        {
            bitmapX %= bitmapRect.width;
            if (bitmapX < 0)
            {
                bitmapX += bitmapRect.width;
            }
            bitmapY %= bitmapRect.height;
            if (bitmapY < 0)
            {
                bitmapY += bitmapRect.height;
            }
            return true;
        }
        if (bitmapX < 0)
        {
            if (bitmapX + count <= 0)
            {
                return false;
            }
            count += bitmapX;
            offset -= bitmapX;
            bitmapX = 0;
        }
        if ((bitmapX >= bitmapRect.width) || (bitmapY < 0) || (bitmapY >= bitmapRect.height))
        {
            return false;
        }
        if (bitmapX + (int)count > bitmapRect.width)
        {
            count = bitmapRect.width - bitmapX;
        }
        return true;
    }
References AbstractPainterBitmap::bitmapRect, Rect::height, AbstractPainterBitmap::isTiled, Rect::width, AbstractPainterBitmap::xDelta, and AbstractPainterBitmap::yDelta.
Referenced by PainterABGR2222Bitmap::paint(), PainterARGB2222Bitmap::paint(), PainterARGB8888Bitmap::paint(), PainterARGB8888L8Bitmap::paint(), PainterBGRA2222Bitmap::paint(), PainterBWBitmap::paint(), PainterGRAY2Bitmap::paint(), PainterGRAY4Bitmap::paint(), PainterRGB565Bitmap::paint(), PainterRGB565L8Bitmap::paint(), PainterRGB888Bitmap::paint(), PainterRGB888L8Bitmap::paint(), PainterRGBA2222Bitmap::paint(), PainterXRGB8888Bitmap::paint(), and PainterXRGB8888L8Bitmap::paint().
getBitmap()
Bitmap getBitmap () const inline
Gets the bitmap previously set using setBitmap().
Returns
The bitmap.
    {
        return bitmap;
    }
References AbstractPainterBitmap::bitmap.
getOffset()
void getOffset (int16_t & x, int16_t & y) inline
Gets the bitmap offset previously set using setOffset().
Parameters
[out] x The x coordinate.
[out] y The y coordinate.
    {
        x = xOffset;
        y = yOffset;
    }
References AbstractPainterBitmap::xOffset, and AbstractPainterBitmap::yOffset.
getTiled()
bool getTiled () const inline
Gets the tiled setting, previously set using setTiled().
Returns
True if the bitmap is tiled, false otherwise.
    {
        return isTiled;
    }
References AbstractPainterBitmap::isTiled.
setBitmap()
virtual void setBitmap (const Bitmap & bmp) inline virtual
Sets a bitmap to be used when drawing the CanvasWidget.
Parameters
bmp The bitmap.
Reimplemented in PainterABGR2222Bitmap, PainterARGB2222Bitmap, PainterARGB8888Bitmap, PainterARGB8888L8Bitmap, PainterBGRA2222Bitmap, PainterBWBitmap, PainterGRAY2Bitmap, PainterGRAY4Bitmap, PainterRGB565Bitmap, PainterRGB565L8Bitmap, PainterRGB888Bitmap, PainterRGB888L8Bitmap, PainterRGBA2222Bitmap, PainterXRGB8888Bitmap, and PainterXRGB8888L8Bitmap.
    {
        bitmap = bmp;
        bitmapFormat = bitmap.getFormat();
        bitmapRect = bitmap.getRect();
        DisplayTransformation::transformDisplayToFrameBuffer(bitmapRect);
        bitmapData = bitmap.getData();
    }
References AbstractPainterBitmap::bitmapData, AbstractPainterBitmap::bitmapFormat, AbstractPainterBitmap::bitmapRect, and DisplayTransformation::transformDisplayToFrameBuffer().
Referenced by AbstractPainterBitmap::AbstractPainterBitmap(), PainterABGR2222Bitmap::setBitmap(), PainterARGB2222Bitmap::setBitmap(), PainterARGB8888Bitmap::setBitmap(), PainterARGB8888L8Bitmap::setBitmap(), PainterBGRA2222Bitmap::setBitmap(), PainterBWBitmap::setBitmap(), PainterGRAY2Bitmap::setBitmap(), PainterGRAY4Bitmap::setBitmap(), PainterRGB565Bitmap::setBitmap(), PainterRGB565L8Bitmap::setBitmap(), PainterRGB888Bitmap::setBitmap(), PainterRGB888L8Bitmap::setBitmap(), PainterRGBA2222Bitmap::setBitmap(), PainterXRGB8888Bitmap::setBitmap(), and PainterXRGB8888L8Bitmap::setBitmap().
setOffset()
virtual void setOffset (int16_t x, int16_t y) inline virtual
Sets an offset for the bitmap used. The x and y coordinates specifies how far the bitmap should be moved to the right and down. This works for tiled bitmaps and non-tiled bitmaps.
Parameters
x The x coordinate.
y The y coordinate.
See also
setTiled
    {
        xOffset = x;
        yOffset = y;
    }
References AbstractPainterBitmap::xOffset, and AbstractPainterBitmap::yOffset.
setTiled()
virtual void setTiled (bool tiled) inline virtual
Instruct the painter to tile the bitmap specified. The bitmap will be tiled both horizontally and vertically.
Parameters
tiled True if tiled.
See also
setOffset
    {
        isTiled = tiled;
    }
References AbstractPainterBitmap::isTiled.
updateBitmapOffsets()
void updateBitmapOffsets (int16_t widgetWidth) const inline protected
Updates the bitmap offsets described by widgetWidth, these offset are used by bitmap painters adjust the coordinate position inside the widget.
Parameters
widgetWidth Width of the widget.
    {
        xDelta = (HAL::DISPLAY_ROTATION == rotate0) ? xOffset : yOffset;
        yDelta = (HAL::DISPLAY_ROTATION == rotate0) ? yOffset : -(xOffset + (widgetWidth - bitmap.getWidth()));
    }
References HAL::DISPLAY_ROTATION, touchgfx::rotate0, AbstractPainterBitmap::xDelta, AbstractPainterBitmap::xOffset, AbstractPainterBitmap::yDelta, and AbstractPainterBitmap::yOffset.
Referenced by PainterABGR2222Bitmap::setup(), PainterARGB2222Bitmap::setup(), PainterARGB8888Bitmap::setup(), PainterARGB8888L8Bitmap::setup(), PainterBGRA2222Bitmap::setup(), PainterBWBitmap::setup(), PainterGRAY2Bitmap::setup(), PainterGRAY4Bitmap::setup(), PainterRGB565Bitmap::setup(), PainterRGB565L8Bitmap::setup(), PainterRGB888Bitmap::setup(), PainterRGB888L8Bitmap::setup(), PainterRGBA2222Bitmap::setup(), PainterXRGB8888Bitmap::setup(), and PainterXRGB8888L8Bitmap::setup().
Member Data Documentation
bitmap
Bitmap bitmap protected
The bitmap to be used when painting.
Referenced by AbstractPainterBitmap::getBitmap().
bitmapData
const uint8_t* bitmapData protected
Pointer to the bitmap data.
Referenced by PainterABGR2222Bitmap::paint(), PainterARGB2222Bitmap::paint(), PainterARGB8888Bitmap::paint(), PainterARGB8888L8Bitmap::paint(), PainterBGRA2222Bitmap::paint(), PainterBWBitmap::paint(), PainterGRAY2Bitmap::paint(), PainterGRAY4Bitmap::paint(), PainterRGB565Bitmap::paint(), PainterRGB565L8Bitmap::paint(), PainterRGB888Bitmap::paint(), PainterRGB888L8Bitmap::paint(), PainterRGBA2222Bitmap::paint(), PainterXRGB8888Bitmap::paint(), PainterXRGB8888L8Bitmap::paint(), AbstractPainterBitmap::setBitmap(), PainterABGR2222Bitmap::setBitmap(), PainterARGB2222Bitmap::setBitmap(), PainterARGB8888Bitmap::setBitmap(), PainterARGB8888L8Bitmap::setBitmap(), PainterBGRA2222Bitmap::setBitmap(), PainterBWBitmap::setBitmap(), PainterGRAY2Bitmap::setBitmap(), PainterGRAY4Bitmap::setBitmap(), PainterRGB565Bitmap::setBitmap(), PainterRGB565L8Bitmap::setBitmap(), PainterRGB888Bitmap::setBitmap(), PainterRGB888L8Bitmap::setBitmap(), PainterRGBA2222Bitmap::setBitmap(), PainterXRGB8888Bitmap::setBitmap(), and PainterXRGB8888L8Bitmap::setBitmap().
bitmapFormat
Bitmap::BitmapFormat bitmapFormat protected
Copy of the bitmap format (for speed reasons)
Referenced by PainterARGB8888Bitmap::paint(), PainterBWBitmap::paint(), PainterRGB565Bitmap::paint(), PainterRGB888Bitmap::paint(), PainterXRGB8888Bitmap::paint(), AbstractPainterBitmap::setBitmap(), PainterABGR2222Bitmap::setBitmap(), PainterARGB2222Bitmap::setBitmap(), PainterARGB8888Bitmap::setBitmap(), PainterBWBitmap::setBitmap(), PainterRGB565Bitmap::setBitmap(), PainterRGB888Bitmap::setBitmap(), and PainterXRGB8888Bitmap::setBitmap().
bitmapRect
Rect bitmapRect protected
Bitmap rectangle translated to framebuffer coordinates.
Referenced by AbstractPainterBitmap::adjustBitmapXY(), PainterABGR2222Bitmap::paint(), PainterARGB2222Bitmap::paint(), PainterARGB8888Bitmap::paint(), PainterARGB8888L8Bitmap::paint(), PainterBGRA2222Bitmap::paint(), PainterBWBitmap::paint(), PainterGRAY2Bitmap::paint(), PainterGRAY4Bitmap::paint(), PainterRGB565Bitmap::paint(), PainterRGB565L8Bitmap::paint(), PainterRGB888Bitmap::paint(), PainterRGB888L8Bitmap::paint(), PainterRGBA2222Bitmap::paint(), PainterXRGB8888Bitmap::paint(), PainterXRGB8888L8Bitmap::paint(), and AbstractPainterBitmap::setBitmap().
isTiled
bool isTiled protected
True if bitmap should be tiled, false if not.
Referenced by AbstractPainterBitmap::adjustBitmapXY(), AbstractPainterBitmap::getTiled(), and AbstractPainterBitmap::setTiled().
xDelta
int16_t xDelta mutable private
Referenced by AbstractPainterBitmap::adjustBitmapXY(), and AbstractPainterBitmap::updateBitmapOffsets().
xOffset
int16_t xOffset protected
The x offset of the bitmap.
Referenced by AbstractPainterBitmap::getOffset(), AbstractPainterBitmap::setOffset(), and AbstractPainterBitmap::updateBitmapOffsets().
yDelta
int16_t yDelta mutable private
Referenced by AbstractPainterBitmap::adjustBitmapXY(), and AbstractPainterBitmap::updateBitmapOffsets().
yOffset
int16_t yOffset protected
The y offset of the bitmap.
Referenced by AbstractPainterBitmap::getOffset(), AbstractPainterBitmap::setOffset(), and AbstractPainterBitmap::updateBitmapOffsets().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/AbstractPainterBitmap.hpp