Battery Simulator Documentation: TextAreaWithWildcardBase
TextAreaWithWildcardBase
#include "TextAreaWithWildcard.hpp"
Public Member Functions
TextAreaWithWildcardBase ()
virtual void draw (const Rect &area) const
virtual void invalidateContent () const
Public Member Functions inherited from TextArea
TextArea ()
virtual int16_t calculateTextHeight (const Unicode::UnicodeChar *format,...) const
virtual Alignment getAlignment () const
uint8_t getAlpha () const
FORCE_INLINE_FUNCTION colortype getColor () const
FORCE_INLINE_FUNCTION uint8_t getIndentation ()
FORCE_INLINE_FUNCTION int16_t getLinespacing () const
TextRotation getRotation () const
virtual Rect getSolidRect () const
virtual int16_t getTextHeight () const
virtual uint16_t getTextWidth () const
const TypedText & getTypedText () const
WideTextAction getWideTextAction () const
virtual const Unicode::UnicodeChar * getWildcard1 () const
virtual const Unicode::UnicodeChar * getWildcard2 () const
void resizeHeightToCurrentText ()
void resizeHeightToCurrentTextWithRotation ()
void resizeToCurrentText ()
void resizeToCurrentTextWithAlignment ()
virtual void setAlpha (uint8_t newAlpha)
virtual void setBaselineY (int16_t baselineY)
FORCE_INLINE_FUNCTION void setColor (colortype newColor)
virtual void setHeight (int16_t height)
FORCE_INLINE_FUNCTION void setIndentation (uint8_t indent)
FORCE_INLINE_FUNCTION void setLinespacing (int16_t space)
FORCE_INLINE_FUNCTION void setRotation (const TextRotation textRotation)
void setTypedText (const TypedText &t)
FORCE_INLINE_FUNCTION void setWideTextAction (WideTextAction action)
virtual void setWidth (int16_t width)
virtual void setXBaselineY (int16_t x, int16_t baselineY)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
virtual TextArea::BoundingArea calculateBoundingArea () const
Additional Inherited Members
Protected Attributes inherited from TextArea
uint8_t alpha
The alpha to use.
BoundingArea boundingArea
Bounding area of this text area.
colortype color
The color to use for the text.
uint8_t indentation
The indentation of the text inside the text area.
int16_t linespace
The extra space between lines of text, measured in pixels.
TextRotation rotation
The text rotation to use in steps of 90 degrees.
TypedText typedText
The TypedText to display.
WideTextAction wideTextAction
What to do if the lines of text are wider than the text area.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Static Protected Attributes inherited from TextArea
static const uint16_t newLine = 10
NewLine value.
Detailed Description
Base class for TextArea with one or two wildcards.
See also
TextAreaWithOneWildcard, TextAreaWithTwoWildcards
Constructor & Destructor Documentation
TextAreaWithWildcardBase()
TextAreaWithWildcardBase () inline
        : TextArea()
    {
    }
Member Function Documentation
calculateBoundingArea()
virtual TextArea::BoundingArea calculateBoundingArea () const inline protected virtual
Calculates the minimum bounding rectangle of this text area and correlates it with the containing text, to get the bounding area. Note: The bounding rectangle is adjusted according to alignment and rotation.
Returns
The bounding area.
Reimplemented from TextArea.
    {
        return TextArea::BoundingArea();
    }
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Reimplemented from TextArea.
{
    if (typedText.hasValidId())
    {
        const Font* fontToDraw = typedText.getFont();
        if (fontToDraw != 0)
        {
            const LCD::StringVisuals visuals(fontToDraw, color, alpha, typedText.getAlignment(), linespace, rotation, typedText.getTextDirection(), indentation, wideTextAction);
            HAL::lcd().drawString(getAbsoluteRect(), area, visuals, typedText.getText(), getWildcard1(), getWildcard2());
        }
    }
}
References Drawable::getAbsoluteRect(), TypedText::getAlignment(), TypedText::getFont(), TypedText::getText(), TypedText::getTextDirection(), TextArea::getWildcard1(), TextArea::getWildcard2(), TypedText::hasValidId(), TextArea::indentation, HAL::lcd(), TextArea::linespace, TextArea::rotation, TextArea::typedText, and TextArea::wideTextAction.
invalidateContent()
virtual void invalidateContent () const inline virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from TextArea.
    {
        Widget::invalidateContent();
    }
References Drawable::invalidateContent().
Referenced by Keyboard::handleClickEvent(), DigitalClock::setColor(), DigitalClock::setTypedText(), TextProgress::setValue(), and DigitalClock::updateClock().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/TextAreaWithWildcard.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/TextAreaWithWildcard.cpp