Battery Simulator Documentation: Application
Application
#include "Application.hpp"
Classes
class TimerWidgets
Public Member Functions
virtual void appSwitchScreen (uint8_t screenId)
virtual void changeToStartScreen ()
void clearAllTimerWidgets ()
virtual void clearCachedAreas ()
void copyInvalidatedAreasFromTFTToClientBuffer ()
virtual void drawCachedAreas ()
const Vector< Rect, 8 > & getInvalidatedAreas ()
uint16_t getNumberOfRegisteredTimerWidgets () const
uint16_t getTimerWidgetCountForDrawable (const Drawable *w) const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleKeyEvent (uint8_t c)
virtual void handlePendingScreenTransition ()
virtual void handleTickEvent ()
virtual void invalidate ()
virtual void invalidateArea (Rect area)
void registerTimerWidget (Drawable *w)
virtual void requestRedraw ()
virtual void requestRedraw (Rect &rect)
virtual void switchScreen (Screen *newScreen)
void unregisterTimerWidget (const Drawable *w)
Public Member Functions inherited from UIEventListener
virtual ~UIEventListener ()
Static Public Member Functions
static Screen * getCurrentScreen ()
static DebugPrinter * getDebugPrinter ()
static Application * getInstance ()
static void invalidateDebugRegion ()
static void setDebugPrinter (DebugPrinter *printer)
static void setDebugString (const char *string)
Static Public Attributes
static const uint8_t MAX_TIMER_WIDGETS = 32
Maximum number of widgets receiving ticks.
static const uint16_t TICK_INTERVAL_MS = 10
Deprecated, do not use this constant. Tick interval depends on VSYNC of your target platform.
Protected Types
typedef Vector< Rect, 8 > RectVector_t
Type to ensure the same number of rects are in the Vector.
Protected Member Functions
Application ()
virtual void draw ()
virtual void draw (Rect &rect)
Protected Attributes
RectVector_t cachedDirtyAreas
When draw caching is enabled, these rects keeps track of the dirty screen area.
RectVector_t lastRects
The dirty areas from last frame that needs to be redrawn because we have swapped frame buffers.
Rect redraw
Rect describing application requested invalidate area.
class touchgfx::Application::TimerWidgets timerWidgets
The timer widgets.
bool transitionHandled
True if the transition is done and Screen::afterTransition has been called.
Static Protected Attributes
static Screen * currentScreen
Pointer to currently displayed Screen.
static Transition * currentTransition
Pointer to current transition.
static DebugPrinter * debugPrinter
Pointer to the DebugPrinter instance.
static Rect debugRegionInvalidRect
Invalidated Debug Region.
static Application * instance
Pointer to the instance of the Application-derived subclass.
Detailed Description
The Application class is the main interface for manipulating screen contents. It holds a pointer to the currently displayed Screen, and delegates draw requests and events to that Screen. Additionally it contains some global application settings.
Member Typedef Documentation
RectVector_t
typedef Vector<Rect, 8> RectVector_t protected
Type to ensure the same number of rects are in the Vector.
Constructor & Destructor Documentation
Application()
Application () protected
Protected constructor.
Member Function Documentation
appSwitchScreen()
virtual void appSwitchScreen (uint8_t screenId) inline virtual
An application specific function for switching screen. Overloading this can provide a means to switch screen from places that does not have access to a pointer to the new screen. Base implementation is empty.
Parameters
screenId An id that maps to the desired screen.
    {
        (void)screenId; // Unused variable
    }
References void().
changeToStartScreen()
virtual void changeToStartScreen () inline virtual
This function can be called to send your application back to the start screen. The simulator will call this function when F5 is pressed. To make this work, please implement this function in FrontendApplication.
Note
The application will not make a complete restart - if your Model contains data, this will not be reset, unless this is explicitly done in your FrontendApplication::changeToStartScreen().
Reimplemented in FrontendApplicationBase.
    {
    }
clearAllTimerWidgets()
void clearAllTimerWidgets () inline
Clears all currently registered timer widgets.
    {
        timerWidgets.clear();
    }
References Application::timerWidgets.
clearCachedAreas()
virtual void clearCachedAreas () virtual
Clears the cached areas so coming calls to invalidate are collected for future drawing.
See also
drawCachedAreas
copyInvalidatedAreasFromTFTToClientBuffer()
void copyInvalidatedAreasFromTFTToClientBuffer ()
This function copies the parts that were updated in the previous frame (in the TFT buffer) to the active framebuffer (client buffer).
This function only copies pixels in double buffering mode.
draw() [1/2]
virtual void draw () protected virtual
Initiate a draw operation of the entire screen. Standard implementation is to delegate draw request to the current Screen.
draw() [2/2]
virtual void draw (Rect & rect) protected virtual
Initiate a draw operation of the specified region of the screen. Standard implementation is to delegate draw request to the current Screen.
Parameters
[in] rect The area to draw.
Note
Unlike Widget::draw this is safe to call from user code as it will properly traverse widgets in z-order.
The coordinates given must be absolute coordinates.
drawCachedAreas()
virtual void drawCachedAreas () virtual
Draws all cached, invalidated areas on the screen.
See also
clearCachedAreas
getCurrentScreen()
static Screen * getCurrentScreen () inline static
Gets the current screen.
Returns
The current screen.
    {
        return currentScreen;
    }
References Application::currentScreen.
getDebugPrinter()
static DebugPrinter * getDebugPrinter () inline static
Returns the DebugPrinter object associated with the application.
Returns
DebugPrinter The DebugPrinter object.
    {
        return debugPrinter;
    }
References Application::debugPrinter.
getInstance()
static Application * getInstance () static
Gets the single instance application.
Returns
The instance of this application.
Referenced by SlideMenu::SlideMenu(), SwipeContainer::SwipeContainer(), VideoWidget::VideoWidget(), SlideMenu::~SlideMenu(), SwipeContainer::~SwipeContainer(), VideoWidget::~VideoWidget(), ScrollBase::animateToPosition(), Screen1ViewBase::application(), AnimationTextureMapper::cancelAnimationTextureMapperAnimation(), FadeAnimator< T >::cancelFadeAnimation(), MoveAnimator< T >::cancelMoveAnimation(), ZoomAnimationImage::cancelZoomAnimation(), RepeatButtonTrigger::handleClickEvent(), ScrollableContainer::handleClickEvent(), RepeatButton::handleClickEvent(), ScrollableContainer::handleGestureEvent(), AbstractProgressIndicator::handleTickEvent(), ScrollableContainer::handleTickEvent(), ScrollBase::handleTickEvent(), BlockTransition::handleTickEvent(), CoverTransition< templateDirection >::handleTickEvent(), WipeTransition< templateDirection >::handleTickEvent(), AnimatedImage::handleTickEvent(), TouchGFXGeneratedHAL::initialize(), Transition::invalidate(), FadeAnimator< T >::nextFadeAnimationStep(), MoveAnimator< T >::nextMoveAnimationStep(), AnimatedImage::pauseAnimation(), touchgfx::prepareTransition(), AnimationTextureMapper::startAnimation(), AnimatedImage::startAnimation(), FadeAnimator< T >::startFadeAnimation(), MoveAnimator< T >::startMoveAnimation(), ZoomAnimationImage::startTimerAndSetParameters(), ScrollBase::stopAnimation(), AnimatedImage::stopAnimation(), HALSDL2::taskEntry(), touchgfx::touchgfx_generic_init(), and AbstractProgressIndicator::updateValue().
getInvalidatedAreas()
const Vector< Rect, 8 > & getInvalidatedAreas () inline
Get list of the invalidated areas in the current frame. The list is cleared in the beginning of HAL::tick.
The list can be usefull on some platforms where the information can be used to reduce the amount of pixels sent to the display.
Returns
Const reference to the list.
    {
        return cachedDirtyAreas;
    }
References Application::cachedDirtyAreas.
getNumberOfRegisteredTimerWidgets()
uint16_t getNumberOfRegisteredTimerWidgets () const inline
gets the number of timer widgets that are registered and active.
Returns
The size of timerWidgets.
    {
        return timerWidgets.getNumberOfActiveTimerWidgets();
    }
References Application::timerWidgets.
getTimerWidgetCountForDrawable()
uint16_t getTimerWidgetCountForDrawable (const Drawable * w) const inline
Gets the number of timer events registered to a widget, i.e. how many times a drawable must be unregistered until it no longer receives timer ticks.
Parameters
w The widget to to get count from.
Returns
0 if the drawable is not registered as a timer widget, otherwise returns how many times the drawable is currently registered.
    {
        return timerWidgets.getCounter(w);
    }
References Application::timerWidgets.
handleClickEvent()
virtual void handleClickEvent (const ClickEvent & event) virtual
Handle a click event. Standard implementation is to delegate the event to the current screen. Called by the framework when a click is detected by some platform specific means.
Parameters
event The ClickEvent.
Reimplemented from UIEventListener.
handleDragEvent()
virtual void handleDragEvent (const DragEvent & event) virtual
Handle drag events. Called by the framework when a drag is detected by some platform specific means. Standard implementation is to delegate drag event to current screen.
Parameters
event The drag event, expressed in absolute coordinates.
Reimplemented from UIEventListener.
handleGestureEvent()
virtual void handleGestureEvent (const GestureEvent & event) virtual
Handle gestures. Called by the framework when a gesture is detected by some platform specific means. Standard implementation is to delegate drag event to current screen.
Parameters
event The gesture event.
Reimplemented from UIEventListener.
handleKeyEvent()
virtual void handleKeyEvent (uint8_t c) virtual
Handle an incoming character received by the HAL layer. Standard implementation delegates to current screen (which, in turn, does nothing).
Parameters
c The incoming character to handle.
Reimplemented from UIEventListener.
handlePendingScreenTransition()
virtual void handlePendingScreenTransition () virtual
Evaluates the pending Callback instances. If a callback is valid, it is executed and a Screen transition is executed. This base implementation is empty and does nothing.
Reimplemented from UIEventListener.
Reimplemented in MVPApplication.
handleTickEvent()
virtual void handleTickEvent () virtual
Handle tick. Standard implementation is to delegate tick to the widgets that have registered to receive one. Called by some platform specific means.
Reimplemented from UIEventListener.
Reimplemented in FrontendApplication.
Referenced by FrontendApplication::handleTickEvent().
invalidate()
virtual void invalidate () virtual
Invalidates the entire screen.
invalidateArea()
virtual void invalidateArea (Rect area) virtual
Invalidates the given area.
Parameters
area The area to invalidate.
invalidateDebugRegion()
static void invalidateDebugRegion () inline static
Sets the debug string to be displayed onscreen on top of the framebuffer.
    {
        if (debugPrinter)
        {
            debugRegionInvalidRect.expandToFit(debugPrinter->getRegion());
        }
    }
References Application::debugPrinter, and Application::debugRegionInvalidRect.
Referenced by Application::setDebugString().
registerTimerWidget()
void registerTimerWidget (Drawable * w) inline
Adds a widget to the list of widgets receiving ticks every frame (typically 16.67ms)
Parameters
[in] w The widget to add.
See also
unregisterTimerWidget
Note
The framework keeps track of the number of times a specific widget is registered.
    {
        timerWidgets.add(w);
    }
References Application::timerWidgets.
requestRedraw() [1/2]
virtual void requestRedraw () virtual
An application specific function for requesting redraw of entire screen.
requestRedraw() [2/2]
virtual void requestRedraw (Rect & rect) inline virtual
An application specific function for requesting redraw of given Rect.
Parameters
[in,out] rect The Rect that must be redrawn.
    {
        redraw = rect;
    }
References Application::redraw.
setDebugPrinter()
static void setDebugPrinter (DebugPrinter * printer) inline static
Sets the DebugPrinter object to be used by the application to print debug messages.
Parameters
[in] printer The debug printer to configure.
    {
        debugPrinter = printer;
    }
References Application::debugPrinter.
setDebugString()
static void setDebugString (const char * string) inline static
Sets the debug string to be displayed onscreen on top of the framebuffer.
Parameters
[in] string The debug string to display onscreen.
    {
        if (debugPrinter)
        {
            debugPrinter->setString(string);
            invalidateDebugRegion();
        }
    }
References Application::debugPrinter, and Application::invalidateDebugRegion().
switchScreen()
virtual void switchScreen (Screen * newScreen) virtual
Switch to another Screen. Will call tearDownScreen on current Screen before switching, and subsequently call setupScreen and draw automatically for the new Screen.
Parameters
[in] newScreen A pointer to the new screen.
unregisterTimerWidget()
void unregisterTimerWidget (const Drawable * w) inline
Removes a widget from the list of widgets receiving ticks every frame (typically 16.67ms) milliseconds.
Parameters
[in] w The widget to remove.
Note
If widget has been registered multiple times, an equal number of calls to unregister are required to stop widget from receiving tick events.
    {
        timerWidgets.remove(w);
    }
References Application::timerWidgets.
Member Data Documentation
cachedDirtyAreas
RectVector_t cachedDirtyAreas protected
When draw caching is enabled, these rects keeps track of the dirty screen area.
Referenced by Application::getInvalidatedAreas().
currentScreen
Screen* currentScreen static protected
Pointer to currently displayed Screen.
Referenced by Application::getCurrentScreen(), and FrontendApplicationBase::gotoScreen1ScreenNoTransitionImpl().
currentTransition
Transition* currentTransition static protected
Pointer to current transition.
Referenced by FrontendApplicationBase::gotoScreen1ScreenNoTransitionImpl().
debugPrinter
DebugPrinter* debugPrinter static protected
Pointer to the DebugPrinter instance.
Referenced by Application::getDebugPrinter(), Application::invalidateDebugRegion(), Application::setDebugPrinter(), and Application::setDebugString().
debugRegionInvalidRect
Rect debugRegionInvalidRect static protected
Invalidated Debug Region.
Referenced by Application::invalidateDebugRegion().
instance
Application* instance static protected
Pointer to the instance of the Application-derived subclass.
Note
Must be set by subclass constructor!
Referenced by MVPApplication::MVPApplication().
lastRects
RectVector_t lastRects protected
The dirty areas from last frame that needs to be redrawn because we have swapped frame buffers.
MAX_TIMER_WIDGETS
const uint8_t MAX_TIMER_WIDGETS = 32 static
Maximum number of widgets receiving ticks.
Remarks
Memory impact: x * (sizeof(Drawable*)+1)
redraw
Rect redraw protected
Rect describing application requested invalidate area.
Referenced by Application::requestRedraw().
TICK_INTERVAL_MS
const uint16_t TICK_INTERVAL_MS = 10 static
Deprecated, do not use this constant. Tick interval depends on VSYNC of your target platform.
timerWidgets
class touchgfx::Application::TimerWidgets timerWidgets protected
The timer widgets.
Referenced by Application::clearAllTimerWidgets(), Application::getNumberOfRegisteredTimerWidgets(), Application::getTimerWidgetCountForDrawable(), Application::registerTimerWidget(), and Application::unregisterTimerWidget().
transitionHandled
bool transitionHandled protected
True if the transition is done and Screen::afterTransition has been called.
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/Application.hpp