Battery Simulator Documentation: CWRUtil::Q10
CWRUtil::Q10
#include "CWRUtil.hpp"
Public Member Functions
Q10 ()
Q10 (int i)
operator int () const
Q15 operator* (const Q5 &q5) const
Q10 operator+ (const Q10 &q10) const
Q10 operator- () const
Q5 operator/ (const Q5 &q5) const
template<typename T >
T to () const
Private Attributes
int32_t v
Detailed Description
Defines a "floating point number" with 10 bits reserved for the fractional part of the decimal number. Q10 implements some simple arithmetic operations, most yielding a Q10 number and some yielding a Q5 number or a Q15 number as a result.
Q5*Q5=Q10, Q10/Q5=Q5, ...
See also
Q5, Q15
Constructor & Destructor Documentation
Q10() [1/2]
Q10 () inline
Initializes a new instance of the Q10 class.
            : v(0)
        {
        }
Referenced by CWRUtil::Q10::operator+(), and CWRUtil::Q10::operator-().
Q10() [2/2]
Q10 (int i) inline explicit
Constructor from integer. No conversion is done - the integer is assumed to already be in Q10 format.
Parameters
i int pre-formattet in Q10 format.
            : v(i)
        {
        }
Member Function Documentation
operator int()
operator int () const inline
Gets the Q10 as an integer without conversion.
Returns
The unconverted Q10 value.
        {
            return v;
        }
References CWRUtil::Q10::v.
operator*()
Q15 operator* (const Q5 & q5) const inline
Multiplication operator. The result is a Q15, not a Q10, for increased precision.
Parameters
q5 The Q5 to multiply this with.
Returns
The result of the operation.
        {
            return Q15(v * (int)q5);
        }
operator+()
Q10 operator+ (const Q10 & q10) const inline
Addition operator.
Parameters
q10 The Q10 to add to this.
Returns
The result of the operation.
        {
            return Q10(v + q10.v);
        }
References CWRUtil::Q10::Q10().
operator-()
Q10 operator- () const inline
Negation operator.
Returns
The negative value of this.
        {
            return Q10(-v);
        }
References CWRUtil::Q10::Q10().
operator/()
Q5 operator/ (const Q5 & q5) const inline
Division operator.
Parameters
q5 The Q5 to divide this by.
Returns
The result of the operation.
        {
            return Q5(v / (int)q5);
        }
to()
template<typename T > T to () const inline
Converts the Q10 value to an int or a float.
Convert the Q10 value to an integer by removing the 10 bits used for the fraction, or to a floating point value by dividing by 32 * 32, depending on the type specified as T.
Template Parameters
T Either int or float.
Returns
Q10 value as a type T.
        {
            return (T)(v / (Rasterizer::POLY_BASE_SIZE * Rasterizer::POLY_BASE_SIZE));
        }
Referenced by AbstractShape::getScale().
Member Data Documentation
v
int32_t v private
Referenced by CWRUtil::Q10::operator int().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/CWRUtil.hpp