Battery Simulator Documentation: Button
Button
#include "Button.hpp"
Public Member Functions
Button ()
virtual void draw (const Rect &invalidatedArea) const
uint8_t getAlpha () const
Bitmap getCurrentlyDisplayedBitmap () const
virtual Rect getSolidRect () const
virtual void invalidateContent () const
void setAlpha (uint8_t newAlpha)
virtual void setBitmaps (const Bitmap &bitmapReleased, const Bitmap &bitmapPressed)
Public Member Functions inherited from AbstractButton
AbstractButton ()
virtual void executeAction ()
virtual bool getPressedState () const
virtual void handleClickEvent (const ClickEvent &event)
void setAction (GenericCallback< const AbstractButton & > &callback)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
uint8_t alpha
The current alpha value. 255=solid, 0=invisible.
Bitmap down
The image to display when button is pressed.
Bitmap up
The image to display when button is released (normal state).
Protected Attributes inherited from AbstractButton
GenericCallback< const AbstractButton & > * action
The callback to be executed when this AbstractButton is clicked.
bool pressed
Is the button pressed or released? True if pressed.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
A button with two images. One image showing the unpressed button and one image showing the pressed state.
Constructor & Destructor Documentation
Button()
Button () inline
        : AbstractButton(), up(), down(), alpha(255)
    {
    }
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Implements Drawable.
Reimplemented in ButtonWithLabel, and ButtonWithIcon.
{
    const Bitmap bmp(pressed ? down : up);
    Rect dirty(0, 0, bmp.getWidth(), bmp.getHeight());
    dirty &= invalidatedArea;
    if ((bmp.getId() != BITMAP_INVALID) && !dirty.isEmpty())
    {
        Rect r;
        translateRectToAbsolute(r);
        HAL::lcd().drawPartialBitmap(bmp, r.x, r.y, dirty, alpha);
    }
}
References touchgfx::BITMAP_INVALID, touchgfx::dirty, Button::down, HAL::lcd(), AbstractButton::pressed, Drawable::translateRectToAbsolute(), and Button::up.
Referenced by ButtonWithLabel::draw(), and ButtonWithIcon::draw().
getAlpha()
uint8_t getAlpha () const inline
Gets the current alpha value of the widget. The alpha value is in range 255 (solid) to 0 (invisible).
Returns
The current alpha value.
See also
setAlpha
    {
        return alpha;
    }
References Button::alpha.
getCurrentlyDisplayedBitmap()
Bitmap getCurrentlyDisplayedBitmap () const inline
Gets currently displayed bitmap. This depends on the current state of the button, released (normal) or pressed.
Returns
The bitmap currently displayed.
    {
        return (pressed ? down : up);
    }
References Button::down, AbstractButton::pressed, and Button::up.
getSolidRect()
Rect getSolidRect () const virtual
Get (the largest possible) rectangle that is guaranteed to be solid (opaque). This information is important, as any Drawable underneath the solid area does not need to be drawn.
Returns
The solid rectangle part of the Drawable.
Note
The rectangle returned must be relative to upper left corner of the Drawable, meaning that a completely solid widget should return the full size Rect(0, 0, getWidth(), getHeight()). If no area can be guaranteed to be solid, an empty Rect must be returned. Failing to return the correct rectangle may result in errors on the display.
Implements Drawable.
{
    if (alpha < 255)
    {
        return Rect();
    }
    return (pressed ? down.getSolidRect() : up.getSolidRect());
}
References Button::down, Bitmap::getSolidRect(), AbstractButton::pressed, and Button::up.
invalidateContent()
virtual void invalidateContent () const inline virtual
Tell the framework that the contents of the Drawable needs to be redrawn. If the Drawable is invisible, nothing happens. Subclasses of Drawable are encouraged to implement this function and invalidate as little as possible, i.e. the smallest rectangle covering the visual element(s) drawn by the widget.
Reimplemented from Drawable.
    {
        if (alpha > 0)
        {
            Widget::invalidateContent();
        }
    }
References Drawable::invalidateContent().
setAlpha()
void setAlpha (uint8_t newAlpha) inline
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
    {
        alpha = newAlpha;
    }
setBitmaps()
void setBitmaps (const Bitmap & bitmapReleased, const Bitmap & bitmapPressed) virtual
Sets the two bitmaps used by this button. One bitmap for the released (normal) state and one bitmap for the pressed state. The images are expected to be of the same dimensions, and the Button is resized to the dimensions of the pressed Bitmap.
Parameters
bitmapReleased Bitmap to use when button is released.
bitmapPressed Bitmap to use when button is pressed.
Note
It is assumed that the dimensions of the bitmaps are the same. Unexpected (visual) behavior may be observed if the bitmaps are of different sizes.
The user code must call invalidate() in order to update the button on the display.
Reimplemented in ButtonWithIcon, and ToggleButton.
{
    up = bitmapReleased;
    down = bitmapPressed;
    // Adjust width and height of this widget to match bitmap. It is assumed
    // that the two bitmaps have same dimensions.
    Button::setWidthHeight(down);
}
References Button::down, Drawable::setWidthHeight(), and Button::up.
Referenced by ToggleButton::setBitmaps(), ButtonWithIcon::setBitmaps(), and SlideMenu::setup().
Member Data Documentation
alpha
uint8_t alpha protected
The current alpha value. 255=solid, 0=invisible.
Referenced by ButtonWithLabel::draw(), and Button::getAlpha().
down
Bitmap down protected
The image to display when button is pressed.
Referenced by Button::draw(), ToggleButton::forceState(), Button::getCurrentlyDisplayedBitmap(), Button::getSolidRect(), ToggleButton::handleClickEvent(), and Button::setBitmaps().
up
Bitmap up protected
The image to display when button is released (normal state).
Referenced by Button::draw(), ToggleButton::forceState(), Button::getCurrentlyDisplayedBitmap(), Button::getSolidRect(), ToggleButton::getState(), ToggleButton::handleClickEvent(), and Button::setBitmaps().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/Button.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/Button.cpp