Battery Simulator Documentation: ScrollBase
ScrollBase abstract
#include "ScrollBase.hpp"
Public Member Functions
ScrollBase ()
void allowHorizontalDrag (bool enable)
void allowVerticalDrag (bool enable)
virtual void animateToItem (int16_t itemIndex, int16_t animationSteps=-1)
uint16_t getAnimationSteps () const
virtual bool getCircular () const
uint16_t getDragAcceleration () const
virtual int16_t getDrawableMargin () const
virtual int16_t getDrawableSize () const
virtual bool getHorizontal () const
uint16_t getMaxSwipeItems () const
virtual int16_t getNumberOfItems () const
uint8_t getOvershootPercentage () const
uint16_t getSwipeAcceleration () const
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void initialize ()
bool isAnimating () const
virtual void itemChanged (int itemIndex)
void setAnimationEndedCallback (GenericCallback<> &callback)
void setAnimationSteps (int16_t steps)
virtual void setCircular (bool circular)
void setDragAcceleration (uint16_t acceleration)
virtual void setDrawableSize (int16_t drawableSize, int16_t drawableMargin)
void setEasingEquation (EasingEquation equation)
virtual void setHeight (int16_t height)
virtual void setHorizontal (bool horizontal)
void setItemPressedCallback (GenericCallback< int16_t > &callback)
void setItemSelectedCallback (GenericCallback< int16_t > &callback)
void setMaxSwipeItems (uint16_t maxItems)
virtual void setNumberOfItems (int16_t numberOfItems)
void setOvershootPercentage (uint8_t percentage)
void setSwipeAcceleration (uint16_t acceleration)
virtual void setWidth (int16_t width)
void stopAnimation ()
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Types
enum AnimationState { NO_ANIMATION , ANIMATING_GESTURE , ANIMATING_DRAG }
Protected Member Functions
virtual void animateToPosition (int32_t position, int16_t steps=-1)
virtual int32_t getNearestAlignedOffset (int32_t offset) const
int getNormalizedOffset (int offset) const
virtual int32_t getOffset () const
virtual int32_t getPositionForItem (int16_t itemIndex)=0
virtual int32_t keepOffsetInsideLimits (int32_t newOffset, int16_t overShoot) const =0
virtual void setOffset (int32_t offset)
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Protected Attributes
GenericCallback * animationEndedCallback
The animation ended callback.
AnimationState currentAnimationState
The current animation state.
uint16_t defaultAnimationSteps
The animation steps.
int16_t distanceBeforeAlignedItem
The distance before aligned item.
uint16_t dragAcceleration
The drag acceleration x10.
bool draggableX
Is the container draggable in the horizontal direction.
bool draggableY
Is the container draggable in the vertical direction.
EasingEquation easingEquation
The easing equation used for animation.
int gestureEnd
The gesture end.
int gestureStart
The gesture start.
int gestureStep
The current gesture step.
int gestureStepsTotal
The total gesture steps.
int32_t initialSwipeOffset
The initial swipe offset.
GenericCallback * itemLockedInCallback
The item locked in callback.
GenericCallback< int16_t > * itemPressedCallback
The item pressed callback.
GenericCallback< int16_t > * itemSelectedCallback
The item selected callback.
int16_t itemSize
Size of the item (including margin)
DrawableList list
The list.
uint16_t maxSwipeItems
The maximum swipe items.
int16_t numberOfDrawables
Number of drawables.
uint8_t overshootPercentage
The overshoot percentage when dragging.
uint16_t swipeAcceleration
The swipe acceleration x10.
int16_t xClick
The x coordinate of a click.
int16_t yClick
The y coordinate of a click.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
The ScrollBase class is an abstract class used for Widgets that needs to show (a lot of) elements in a DrawableList that can be scrolled. Due to memory limitations, this is implemented by re-using the Drawables in the DrawableList - once an element is moved off screen, it is filled with new content and moved to the other end and the of the scrolling list.
Lists can be horizontal or vertical and the can be circular (infinite scrolling).
See also
ScrollList, ScrollWheel, ScrollWheelWithSelectionStyle
ScrollWheelBase, DrawableList
Member Enumeration Documentation
AnimationState
enum AnimationState protected
Values that represent animation states.
Enumerator
NO_ANIMATION
No animation.
ANIMATING_GESTURE
Animating a gesture.
ANIMATING_DRAG
Animating a drag.
    {
        NO_ANIMATION,
        ANIMATING_GESTURE,
        ANIMATING_DRAG
    };
Constructor & Destructor Documentation
ScrollBase()
ScrollBase ()
    : Container(),
      list(),
      numberOfDrawables(0),
      distanceBeforeAlignedItem(0),
      itemSize(0),
      swipeAcceleration(10),
      dragAcceleration(10),
      maxSwipeItems(0),
      easingEquation(&EasingEquations::backEaseOut),
      defaultAnimationSteps(30),
      overshootPercentage(75),
      itemSelectedCallback(0),
      itemLockedInCallback(0),
      animationEndedCallback(0),
      itemPressedCallback(0),
      currentAnimationState(NO_ANIMATION),
      gestureStep(0),
      gestureStepsTotal(0),
      gestureStart(0),
      gestureEnd(0),
      xClick(0),
      yClick(0),
      initialSwipeOffset(0),
      draggableX(false),
      draggableY(false)
{
    Container::add(list);
    list.setXY(0, 0);
    list.setHorizontal(false);
    list.setCircular(false);
    setTouchable(true);
}
References Container::add(), ScrollBase::list, DrawableList::setCircular(), DrawableList::setHorizontal(), Drawable::setTouchable(), and Drawable::setXY().
Member Function Documentation
allowHorizontalDrag()
void allowHorizontalDrag (bool enable)
Enables horizontal scrolling to be passed to the children in the list (in case a child widget is able to handle drag events). By default, scrolling in either direction is disabled. This function can be used to explicitly (dis)allow scrolling in the horizontal direction.
Parameters
enable If true, horizontal scrolling is enabled. If false (default), scrolling is disabled.
{
    draggableX = enable;
}
References ScrollBase::draggableX.
Referenced by ScrollBase::setHorizontal().
allowVerticalDrag()
void allowVerticalDrag (bool enable)
Enables the vertical scroll.
Enables the vertical scroll to be passed to the children in the list (in case a child widget is able to handle drag events). By default, scrolling in either direction is disabled. This function can be used to explicitly (dis)allow scrolling in the vertical direction.
Parameters
enable If true, vertical scrolling is enabled. If false (default), scrolling is disabled.
{
    draggableY = enable;
}
References ScrollBase::draggableY.
Referenced by ScrollBase::setHorizontal().
animateToItem()
void animateToItem (int16_t itemIndex, int16_t animationSteps = -1) virtual
Go to a specific item, possibly with animation. The given item index is scrolled into view. If animationSteps is omitted, the default number of animation steps is used. If animationSteps is 0 no animation will be used, otherwise the number of animation steps specified is used.
Parameters
itemIndex Zero-based index of the item.
animationSteps (Optional) The steps to use for the animation. 0 means no animation. If omitted, default animation steps are used.
See also
setAnimationSteps
{
    const int32_t position = getPositionForItem(itemIndex);
    animateToPosition(position, animationSteps);
}
References ScrollBase::animateToPosition(), and ScrollBase::getPositionForItem().
animateToPosition()
void animateToPosition (int32_t position, int16_t steps = -1) protected virtual
Animate to a new position/offset using the given number of steps.
Parameters
position The new position.
steps (Optional) The steps.
Reimplemented in ScrollWheelBase.
{
    const int32_t currentPosition = getOffset();
    position = getNearestAlignedOffset(position);
    if (steps < 0)
    {
        steps = defaultAnimationSteps;
    }
    const int32_t distance = abs(position - currentPosition);
    steps = MIN(steps, distance);
    if (steps < 1)
    {
        setOffset(position);
        currentAnimationState = NO_ANIMATION;
    }
    else
    {
        gestureStart = currentPosition;
        gestureEnd = position;
        gestureStep = 0;
        gestureStepsTotal = steps;
        if (currentAnimationState != ANIMATING_GESTURE)
        {
            Application::getInstance()->registerTimerWidget(this);
            currentAnimationState = ANIMATING_GESTURE;
        }
    }
}
References touchgfx::abs(), ScrollBase::ANIMATING_GESTURE, ScrollBase::currentAnimationState, ScrollBase::defaultAnimationSteps, ScrollBase::gestureEnd, ScrollBase::gestureStart, ScrollBase::gestureStep, ScrollBase::gestureStepsTotal, Application::getInstance(), ScrollBase::getNearestAlignedOffset(), ScrollBase::getOffset(), MIN, ScrollBase::NO_ANIMATION, and ScrollBase::setOffset().
Referenced by ScrollBase::animateToItem(), ScrollWheelBase::animateToPosition(), ScrollList::handleClickEvent(), ScrollBase::handleGestureEvent(), ScrollBase::setNumberOfItems(), and ScrollList::setWindowSize().
getAnimationSteps()
uint16_t getAnimationSteps () const
Gets animation steps as set in setAnimationSteps.
Returns
The animation steps.
See also
setAnimationSteps, setEasingEquation
{
    return defaultAnimationSteps;
}
References ScrollBase::defaultAnimationSteps.
getCircular()
bool getCircular () const virtual
Gets the circular setting, previously set using setCircular().
Returns
True if the list is circular (infinite), false if the list is not circular (finite).
See also
DrawableList::getCircular, setCircular
{
    return list.getCircular();
}
References DrawableList::getCircular(), and ScrollBase::list.
Referenced by ScrollBase::getNearestAlignedOffset(), ScrollWheelBase::getPositionForItem(), ScrollList::handleClickEvent(), ScrollList::keepOffsetInsideLimits(), ScrollWheelBase::keepOffsetInsideLimits(), and ScrollBase::setNumberOfItems().
getDragAcceleration()
uint16_t getDragAcceleration () const
Gets drag acceleration (times 10).
Returns
The drag acceleration.
See also
setDragAcceleration
Note
The reason for multiplying the acceleration by 10 is to avoid introducing floating point arithmetic.
{
    return dragAcceleration;
}
References ScrollBase::dragAcceleration.
getDrawableMargin()
int16_t getDrawableMargin () const virtual
Gets drawable margin as set through the second parameter in most recent call to setDrawableSize().
Returns
The drawable margin.
See also
setDrawableSize
{
    return list.getDrawableMargin();
}
References DrawableList::getDrawableMargin(), and ScrollBase::list.
getDrawableSize()
int16_t getDrawableSize () const virtual
Gets drawable size as set through the first parameter in most recent call to setDrawableSize().
Returns
The drawable size.
See also
setDrawableSize
{
    return list.getDrawableSize();
}
References DrawableList::getDrawableSize(), and ScrollBase::list.
getHorizontal()
bool getHorizontal () const virtual
Gets the orientation of the drawables, previously set using setHorizontal().
Returns
True if it horizontal, false if it is vertical.
See also
DrawableList::getHorizontal, setHorizontal
{
    return list.getHorizontal();
}
References DrawableList::getHorizontal(), and ScrollBase::list.
Referenced by ScrollList::getPositionForItem(), ScrollList::handleClickEvent(), ScrollWheelBase::handleClickEvent(), ScrollBase::handleDragEvent(), ScrollWheelBase::handleDragEvent(), ScrollBase::handleGestureEvent(), ScrollWheelBase::handleGestureEvent(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), ScrollList::setHeight(), ScrollWheelWithSelectionStyle::setHeight(), ScrollList::setWidth(), ScrollWheelWithSelectionStyle::setWidth(), and ScrollList::setWindowSize().
getMaxSwipeItems()
uint16_t getMaxSwipeItems () const
Gets maximum swipe items as set by setMaxSwipeItems.
Returns
The maximum swipe items, 0 means "no limit".
See also
setMaxSwipeItems
{
    return maxSwipeItems;
}
References ScrollBase::maxSwipeItems.
getNearestAlignedOffset()
int32_t getNearestAlignedOffset (int32_t offset) const protected virtual
Gets nearest offset aligned to a multiple of itemSize.
Parameters
offset The offset.
Returns
The nearest aligned offset.
Reimplemented in ScrollList.
{
    if (itemSize == 0)
    {
        return offset;
    }
    if (getCircular())
    {
        if (offset < 0)
        {
            return (((offset - (itemSize / 2)) / itemSize) * itemSize);
        }
        return ((offset + (itemSize / 2)) / itemSize) * itemSize;
    }
    offset = keepOffsetInsideLimits(offset, 0);
    return ((offset - (itemSize / 2)) / itemSize) * itemSize;
}
References ScrollBase::getCircular(), ScrollBase::itemSize, and ScrollBase::keepOffsetInsideLimits().
Referenced by ScrollBase::animateToPosition(), ScrollWheelBase::animateToPosition(), and ScrollList::getNearestAlignedOffset().
getNormalizedOffset()
int getNormalizedOffset (int offset) const protected
Gets normalized offset from a given offset from 0 down to -numItems*itemSize.
Parameters
offset The offset.
Returns
The normalized offset.
{
    const int16_t numItems = getNumberOfItems();
    if (numItems == 0 || itemSize == 0)
    {
        return offset;
    }
    const int32_t listSize = numItems * itemSize;
    offset %= listSize;
    return offset > 0 ? offset - listSize : offset;
}
References ScrollBase::getNumberOfItems(), and ScrollBase::itemSize.
Referenced by ScrollList::getPositionForItem(), ScrollWheelBase::getSelectedItem(), and ScrollBase::handleTickEvent().
getNumberOfItems()
int16_t getNumberOfItems () const virtual
Gets number of items in the DrawableList, as previously set using setNumberOfItems().
Returns
The number of items.
See also
setNumberOfItems, DrawableList::getNumberOfItems
{
    return list.getNumberOfItems();
}
References DrawableList::getNumberOfItems(), and ScrollBase::list.
Referenced by ScrollBase::getNormalizedOffset(), ScrollWheelBase::getPositionForItem(), ScrollList::handleClickEvent(), ScrollList::keepOffsetInsideLimits(), ScrollWheelBase::keepOffsetInsideLimits(), ScrollBase::setNumberOfItems(), and ScrollWheelWithSelectionStyle::setNumberOfItems().
getOffset()
int32_t getOffset () const protected virtual
Gets display offset of first item.
Returns
The offset.
{
    return list.getOffset() - distanceBeforeAlignedItem;
}
References ScrollBase::distanceBeforeAlignedItem, DrawableList::getOffset(), and ScrollBase::list.
Referenced by ScrollBase::animateToPosition(), ScrollList::getPositionForItem(), ScrollWheelBase::getPositionForItem(), ScrollWheelBase::getSelectedItem(), ScrollList::handleClickEvent(), ScrollWheelBase::handleClickEvent(), ScrollBase::handleDragEvent(), ScrollWheelBase::handleDragEvent(), ScrollBase::handleGestureEvent(), ScrollWheelBase::handleGestureEvent(), ScrollBase::handleTickEvent(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), ScrollBase::setNumberOfItems(), ScrollList::setPadding(), ScrollWheelBase::setSelectedItemOffset(), ScrollList::setSnapping(), and ScrollList::setWindowSize().
getOvershootPercentage()
uint8_t getOvershootPercentage () const inline
Gets overshoot percentage, as previously set using setOvershootPercentage.
Returns
The overshoot percentage.
See also
setOvershootPercentage
    {
        return overshootPercentage;
    }
References ScrollBase::overshootPercentage.
getPositionForItem()
virtual int32_t getPositionForItem (int16_t itemIndex) protected pure virtual
Get the position for an item. The position should ensure that the item is in view as defined by the semantics of the actual scroll class. If the item is already in view, the current offset is returned and not the offset of the given item.
Parameters
itemIndex Zero-based index of the item.
Returns
The position for item.
Implemented in ScrollList, and ScrollWheelBase.
Referenced by ScrollBase::animateToItem().
getSwipeAcceleration()
uint16_t getSwipeAcceleration () const
Gets swipe acceleration (times 10).
Returns
The swipe acceleration.
See also
setSwipeAcceleration
Note
The reason for multiplying the acceleration by 10 is to avoid introducing floating point arithmetic.
{
    return swipeAcceleration;
}
References ScrollBase::swipeAcceleration.
handleDragEvent()
void handleDragEvent (const DragEvent & event) virtual
Defines the event handler interface for DragEvents. The default implementation ignores the event. The event is only received if the drawable is touchable and visible.
Parameters
event The DragEvent received from the HAL.
Reimplemented from Drawable.
Reimplemented in ScrollWheelBase.
{
    stopAnimation();
    currentAnimationState = ANIMATING_DRAG;
    int32_t newOffset = getOffset() + (getHorizontal() ? event.getDeltaX() : event.getDeltaY()) * dragAcceleration / 10;
    newOffset = keepOffsetInsideLimits(newOffset, muldiv(itemSize, overshootPercentage, 100));
    setOffset(newOffset);
}
References ScrollBase::ANIMATING_DRAG, ScrollBase::currentAnimationState, ScrollBase::dragAcceleration, ScrollBase::getHorizontal(), ScrollBase::getOffset(), ScrollBase::itemSize, ScrollBase::keepOffsetInsideLimits(), touchgfx::muldiv(), ScrollBase::overshootPercentage, ScrollBase::setOffset(), and ScrollBase::stopAnimation().
handleGestureEvent()
void handleGestureEvent (const GestureEvent & event) virtual
Defines the event handler interface for GestureEvents. The default implementation ignores the event. The event is only received if the Drawable is touchable and visible.
Parameters
event The GestureEvent received from the HAL.
Reimplemented from Drawable.
Reimplemented in ScrollWheelBase.
{
    if (event.getType() == (getHorizontal() ? GestureEvent::SWIPE_HORIZONTAL : GestureEvent::SWIPE_VERTICAL))
    {
        const int16_t velocity = abs(event.getVelocity());
        const int16_t direction = event.getVelocity() < 0 ? -1 : 1;
        int16_t steps = MAX(1, velocity - 4) * 7;
        int32_t newOffset = getOffset() + direction * steps * swipeAcceleration / 10;
        if (maxSwipeItems > 0)
        {
            const int32_t maxDistance = maxSwipeItems * itemSize;
            newOffset = MIN(newOffset, initialSwipeOffset + maxDistance);
            newOffset = MAX(newOffset, initialSwipeOffset - maxDistance);
        }
        newOffset = keepOffsetInsideLimits(newOffset, 0);
        steps = MIN(steps, defaultAnimationSteps);
        animateToPosition(newOffset, steps);
    }
}
References touchgfx::abs(), ScrollBase::animateToPosition(), ScrollBase::defaultAnimationSteps, ScrollBase::getHorizontal(), ScrollBase::getOffset(), ScrollBase::initialSwipeOffset, ScrollBase::itemSize, ScrollBase::keepOffsetInsideLimits(), MAX, ScrollBase::maxSwipeItems, MIN, GestureEvent::SWIPE_HORIZONTAL, GestureEvent::SWIPE_VERTICAL, and ScrollBase::swipeAcceleration.
handleTickEvent()
void handleTickEvent () virtual
Called periodically by the framework if the Drawable instance has subscribed to timer ticks.
See also
Application::registerTimerWidget
Reimplemented from Drawable.
{
    if (currentAnimationState == ANIMATING_GESTURE)
    {
        gestureStep++;
        const int newPosition = gestureStart + easingEquation(gestureStep, 0, gestureEnd - gestureStart, gestureStepsTotal);
        setOffset(newPosition);
        if (gestureStep > gestureStepsTotal)
        {
            currentAnimationState = NO_ANIMATION;
            gestureStep = 0;
            Application::getInstance()->unregisterTimerWidget(this);
            setOffset(getNormalizedOffset(gestureEnd));
            // Also adjust initialSwipeOffset in case it is being used.
            initialSwipeOffset += getOffset() - gestureEnd;
            // Item has settled, call back
            if (animationEndedCallback && animationEndedCallback->isValid())
            {
                animationEndedCallback->execute();
            }
        }
    }
}
References ScrollBase::ANIMATING_GESTURE, ScrollBase::animationEndedCallback, ScrollBase::currentAnimationState, ScrollBase::easingEquation, GenericCallback< T1, T2, T3 >::execute(), ScrollBase::gestureEnd, ScrollBase::gestureStart, ScrollBase::gestureStep, ScrollBase::gestureStepsTotal, Application::getInstance(), ScrollBase::getNormalizedOffset(), ScrollBase::getOffset(), ScrollBase::initialSwipeOffset, GenericCallback< T1, T2, T3 >::isValid(), ScrollBase::NO_ANIMATION, and ScrollBase::setOffset().
initialize()
virtual void initialize () inline virtual
Removed all drawables and initializes the content of these items.
Reimplemented in ScrollWheelWithSelectionStyle.
    {
        list.refreshDrawables();
    }
References ScrollBase::list, and DrawableList::refreshDrawables().
Referenced by ScrollWheelWithSelectionStyle::initialize().
isAnimating()
bool isAnimating () const
Query if an animation is ongoing. This can be good to know if getSelectedItem() is called, as the result might not be as expected if isAnimating() returns true, since the display is not showing the selected item in the right place yet.
Returns
true if animating, false if not.
{
    return currentAnimationState != NO_ANIMATION;
}
References ScrollBase::currentAnimationState, and ScrollBase::NO_ANIMATION.
itemChanged()
void itemChanged (int itemIndex) virtual
Inform the scroll list that the contents of an item has changed and force all drawables with the given item index to be updated via the callback provided. This is important as a circular list with very few items might display the same item more than once and all these items should be updated.
Parameters
itemIndex Zero-based index of the changed item.
Reimplemented in ScrollWheelWithSelectionStyle.
{
    list.itemChanged(itemIndex);
}
References DrawableList::itemChanged(), and ScrollBase::list.
Referenced by ScrollWheelWithSelectionStyle::itemChanged().
keepOffsetInsideLimits()
virtual int32_t keepOffsetInsideLimits (int32_t newOffset, int16_t overShoot) const protected pure virtual
Keep offset inside limits. Return the new offset that is inside the limits of the scroll list, with the overShoot value added at both ends of the list.
Parameters
newOffset The new offset.
overShoot The over shoot.
Returns
The new offset inside the limits.
Implemented in ScrollList, and ScrollWheelBase.
Referenced by ScrollBase::getNearestAlignedOffset(), ScrollBase::handleDragEvent(), ScrollBase::handleGestureEvent(), and ScrollBase::setNumberOfItems().
setAnimationEndedCallback()
void setAnimationEndedCallback (GenericCallback<> & callback)
Callback, called when the set animation ended.
Parameters
[in] callback The ended callback.
{
    animationEndedCallback = &callback;
}
References ScrollBase::animationEndedCallback.
setAnimationSteps()
void setAnimationSteps (int16_t steps)
Sets animation steps (in ticks) when moving to a new selected item. The default value is 30.
Parameters
steps The animation steps.
See also
setEasingEquation, getAnimationSteps
{
    defaultAnimationSteps = steps;
}
References ScrollBase::defaultAnimationSteps.
setCircular()
void setCircular (bool circular) virtual
Sets whether the list is circular (infinite) or not. A circular list is a list where the first drawable re-appears after the last item in the list - and the last item in the list appears before the first item in the list.
Parameters
circular True if the list should be circular, false if the list should not be circular.
See also
DrawableList::setCircular, getCircular
Reimplemented in ScrollWheelWithSelectionStyle.
{
    list.setCircular(circular);
}
References ScrollBase::list, and DrawableList::setCircular().
Referenced by ScrollWheelWithSelectionStyle::setCircular().
setDragAcceleration()
void setDragAcceleration (uint16_t acceleration)
Sets drag acceleration times 10, so "10" means "1", "15" means "1.5". 10 makes the containers follow the finger, higher values makes the containers move faster. This can often be useful if the list is very long.
Parameters
acceleration The drag acceleration.
See also
getDragAcceleration
Note
The reason for multiplying the acceleration by 10 is to avoid introducing floating point arithmetic.
{
    dragAcceleration = acceleration;
}
References ScrollBase::dragAcceleration.
setDrawableSize()
void setDrawableSize (int16_t drawableSize, int16_t drawableMargin) virtual
Sets drawables size. The drawable is is the size of each drawable in the list in the set direction of the list (this is enforced by the DrawableList class). The specified margin is added above and below each item for spacing. The entire size of an item is thus size + 2 * spacing.
For a horizontal list each element will be drawableSize high and have the same width as set using setWidth(). For a vertical list each element will be drawableSize wide and have the same height as set using setHeight().
Parameters
drawableSize The size of the drawable.
drawableMargin The margin around drawables (margin before and margin after).
See also
setWidth, setHeight, setHorizontal
Reimplemented in ScrollList, and ScrollWheelWithSelectionStyle.
{
    itemSize = drawableSize + drawableMargin * 2;
    list.setDrawableSize(drawableSize, drawableMargin);
}
References ScrollBase::itemSize, ScrollBase::list, and DrawableList::setDrawableSize().
Referenced by ScrollList::setDrawableSize(), and ScrollWheelWithSelectionStyle::setDrawableSize().
setEasingEquation()
void setEasingEquation (EasingEquation equation)
Sets easing equation when changing the selected item, for example via swipe or AnimateTo.
Parameters
equation The equation.
See also
setAnimationSteps, getAnimationSteps
{
    easingEquation = equation;
}
References ScrollBase::easingEquation.
setHeight()
void setHeight (int16_t height) virtual
Sets the height of this drawable.
Parameters
height The new height.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Also sets the height of the children.
Reimplemented from Drawable.
Reimplemented in ScrollList, and ScrollWheelWithSelectionStyle.
{
    Container::setHeight(height);
    list.setHeight(height);
}
References ScrollBase::list, DrawableList::setHeight(), and Drawable::setHeight().
Referenced by ScrollList::setHeight(), and ScrollWheelWithSelectionStyle::setHeight().
setHorizontal()
void setHorizontal (bool horizontal) virtual
Sets a horizontal or vertical layout. If parameter horizontal is set true, all drawables are arranged side by side. If horizontal is set false, the drawables are arranged above and below each other (vertically).
Parameters
horizontal True to align drawables horizontal, false to align drawables vertically.
See also
DrawableList::setHorizontal, getHorizontal
Note
Default value is false, i.e. vertical layout.
Reimplemented in ScrollWheelWithSelectionStyle.
{
    allowVerticalDrag(horizontal);
    allowHorizontalDrag(!horizontal);
    list.setHorizontal(horizontal);
}
References ScrollBase::allowHorizontalDrag(), ScrollBase::allowVerticalDrag(), ScrollBase::list, and DrawableList::setHorizontal().
Referenced by ScrollWheelBase::ScrollWheelBase(), and ScrollWheelWithSelectionStyle::setHorizontal().
setItemPressedCallback()
void setItemPressedCallback (GenericCallback< int16_t > & callback)
Set Callback which will be called when a item is pressed.
Parameters
[in] callback The callback.
{
    itemPressedCallback = &callback;
}
References ScrollBase::itemPressedCallback.
setItemSelectedCallback()
void setItemSelectedCallback (GenericCallback< int16_t > & callback)
Sets Callback which will be called when the selected item is clicked.
Parameters
[in] callback The callback.
{
    itemSelectedCallback = &callback;
}
References ScrollBase::itemSelectedCallback.
setMaxSwipeItems()
void setMaxSwipeItems (uint16_t maxItems)
Sets maximum swipe items. Often useful when there are e.g. five visible items on the screen and a swipe action should at most swipe the next/previous five items into view to achieve sort of a paging effect.
Parameters
maxItems The maximum items, 0 means "no limit" (which is also the default).
See also
getMaxSwipeItems
{
    maxSwipeItems = maxItems;
}
References ScrollBase::maxSwipeItems.
setNumberOfItems()
void setNumberOfItems (int16_t numberOfItems) virtual
Sets number of items in the DrawableList. This forces all drawables to be updated to ensure that the content is correct. For example a date selector might switch number of days between 28, 29, 30, and 31 depending on the month. A circular list might show 27-28-29-30-31 and might need to update this to show 27-28-1-2-3.
Parameters
numberOfItems Number of items.
Note
The DrawableList is refreshed to reflect the change.
Reimplemented in ScrollWheelWithSelectionStyle.
{
    if (numberOfItems != getNumberOfItems())
    {
        list.setNumberOfItems(numberOfItems);
        if (!getCircular())
        {
            animateToPosition(keepOffsetInsideLimits(getOffset(), 0));
        }
    }
}
References ScrollBase::animateToPosition(), ScrollBase::getCircular(), ScrollBase::getNumberOfItems(), ScrollBase::getOffset(), ScrollBase::keepOffsetInsideLimits(), ScrollBase::list, and DrawableList::setNumberOfItems().
Referenced by ScrollWheelWithSelectionStyle::setNumberOfItems().
setOffset()
void setOffset (int32_t offset) protected virtual
Sets display offset of first item.
Parameters
offset The offset.
Reimplemented in ScrollWheelWithSelectionStyle.
{
    list.setOffset(offset + distanceBeforeAlignedItem);
}
References ScrollBase::distanceBeforeAlignedItem, ScrollBase::list, and DrawableList::setOffset().
Referenced by ScrollBase::animateToPosition(), ScrollList::handleClickEvent(), ScrollBase::handleDragEvent(), ScrollWheelBase::handleDragEvent(), ScrollBase::handleTickEvent(), ScrollList::setDrawables(), ScrollWheel::setDrawables(), ScrollWheelWithSelectionStyle::setOffset(), ScrollList::setPadding(), ScrollWheelBase::setSelectedItemOffset(), ScrollList::setSnapping(), and ScrollBase::stopAnimation().
setOvershootPercentage()
void setOvershootPercentage (uint8_t percentage) inline
Sets overshoot percentage when dragging a non-circular list. This is the size relative to an item that can be dragged further than the actual list. Setting this to 50, it is possible to drag the list to show an empty space half the size of an item. Setting this to 0 prevents dragging further than the actual elements in the list.
Parameters
percentage The overshoot percentage.
See also
getOvershootPercentage
    {
        overshootPercentage = percentage;
    }
References ScrollBase::overshootPercentage.
setSwipeAcceleration()
void setSwipeAcceleration (uint16_t acceleration)
Sets swipe acceleration (times 10). Default value, if not set, is 10, i.e. 1.0.
Parameters
acceleration The acceleration times 10, so "9" means "0.9" and "75" means "7.5".
See also
getSwipeAcceleration
Note
The reason for multiplying the acceleration by 10 is to avoid introducing floating point arithmetic.
{
    swipeAcceleration = acceleration;
}
References ScrollBase::swipeAcceleration.
setWidth()
void setWidth (int16_t width) virtual
Sets the width of this drawable.
Parameters
width The new width.
Note
For most Drawable widgets, changing this does normally not automatically yield a redraw.
Also sets the width of the children.
Reimplemented from Drawable.
Reimplemented in ScrollList, and ScrollWheelWithSelectionStyle.
{
    Container::setWidth(width);
    list.setWidth(width);
}
References ScrollBase::list, DrawableList::setWidth(), and Drawable::setWidth().
Referenced by ScrollList::setWidth(), and ScrollWheelWithSelectionStyle::setWidth().
stopAnimation()
void stopAnimation ()
Stops an animation if one is ongoing. Immediately moves to the item which is being animated to.
{
    if (currentAnimationState == ANIMATING_GESTURE)
    {
        Application::getInstance()->unregisterTimerWidget(this);
        setOffset(gestureEnd);
    }
    currentAnimationState = NO_ANIMATION;
}
References ScrollBase::ANIMATING_GESTURE, ScrollBase::currentAnimationState, ScrollBase::gestureEnd, Application::getInstance(), ScrollBase::NO_ANIMATION, and ScrollBase::setOffset().
Referenced by ScrollBase::handleDragEvent(), ScrollList::setDrawables(), and ScrollWheel::setDrawables().
Member Data Documentation
animationEndedCallback
GenericCallback* animationEndedCallback protected
The animation ended callback.
Referenced by ScrollBase::handleTickEvent(), and ScrollBase::setAnimationEndedCallback().
currentAnimationState
AnimationState currentAnimationState protected
The current animation state.
Referenced by ScrollBase::animateToPosition(), ScrollWheelBase::getSelectedItem(), ScrollList::handleClickEvent(), ScrollWheelBase::handleClickEvent(), ScrollBase::handleDragEvent(), ScrollWheelBase::handleDragEvent(), ScrollBase::handleTickEvent(), ScrollBase::isAnimating(), ScrollWheelWithSelectionStyle::setDrawables(), and ScrollBase::stopAnimation().
defaultAnimationSteps
uint16_t defaultAnimationSteps protected
The animation steps.
Referenced by ScrollBase::animateToPosition(), ScrollBase::getAnimationSteps(), ScrollBase::handleGestureEvent(), and ScrollBase::setAnimationSteps().
distanceBeforeAlignedItem
int16_t distanceBeforeAlignedItem protected
The distance before aligned item.
Referenced by ScrollBase::getOffset(), ScrollList::getPaddingBefore(), ScrollList::getPositionForItem(), ScrollWheelBase::getSelectedItemOffset(), ScrollList::handleClickEvent(), ScrollWheelBase::handleClickEvent(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), ScrollWheelWithSelectionStyle::setDrawableSize(), ScrollBase::setOffset(), ScrollWheelWithSelectionStyle::setOffset(), ScrollList::setPadding(), ScrollWheelBase::setSelectedItemOffset(), and ScrollList::setWindowSize().
dragAcceleration
uint16_t dragAcceleration protected
The drag acceleration x10.
Referenced by ScrollBase::getDragAcceleration(), ScrollBase::handleDragEvent(), ScrollWheelBase::handleDragEvent(), and ScrollBase::setDragAcceleration().
draggableX
bool draggableX protected
Is the container draggable in the horizontal direction.
Referenced by ScrollBase::allowHorizontalDrag().
draggableY
bool draggableY protected
Is the container draggable in the vertical direction.
Referenced by ScrollBase::allowVerticalDrag().
easingEquation
EasingEquation easingEquation protected
The easing equation used for animation.
Referenced by ScrollBase::handleTickEvent(), and ScrollBase::setEasingEquation().
gestureEnd
int gestureEnd protected
The gesture end.
Referenced by ScrollBase::animateToPosition(), ScrollWheelBase::getSelectedItem(), ScrollBase::handleTickEvent(), and ScrollBase::stopAnimation().
gestureStart
int gestureStart protected
The gesture start.
Referenced by ScrollBase::animateToPosition(), and ScrollBase::handleTickEvent().
gestureStep
int gestureStep protected
The current gesture step.
Referenced by ScrollBase::animateToPosition(), and ScrollBase::handleTickEvent().
gestureStepsTotal
int gestureStepsTotal protected
The total gesture steps.
Referenced by ScrollBase::animateToPosition(), and ScrollBase::handleTickEvent().
initialSwipeOffset
int32_t initialSwipeOffset protected
The initial swipe offset.
Referenced by ScrollList::handleClickEvent(), ScrollWheelBase::handleClickEvent(), ScrollBase::handleGestureEvent(), ScrollWheelBase::handleGestureEvent(), and ScrollBase::handleTickEvent().
itemLockedInCallback
GenericCallback* itemLockedInCallback protected
The item locked in callback.
itemPressedCallback
GenericCallback<int16_t>* itemPressedCallback protected
The item pressed callback.
Referenced by ScrollList::handleClickEvent(), ScrollWheelBase::handleClickEvent(), and ScrollBase::setItemPressedCallback().
itemSelectedCallback
GenericCallback<int16_t>* itemSelectedCallback protected
The item selected callback.
Referenced by ScrollList::handleClickEvent(), ScrollWheelBase::handleClickEvent(), and ScrollBase::setItemSelectedCallback().
itemSize
int16_t itemSize protected
Size of the item (including margin)
Referenced by ScrollWheelBase::animateToPosition(), ScrollBase::getNearestAlignedOffset(), ScrollBase::getNormalizedOffset(), ScrollList::getPositionForItem(), ScrollWheelBase::getPositionForItem(), ScrollWheelBase::getSelectedItem(), ScrollList::handleClickEvent(), ScrollWheelBase::handleClickEvent(), ScrollBase::handleDragEvent(), ScrollBase::handleGestureEvent(), ScrollWheelBase::handleGestureEvent(), ScrollList::keepOffsetInsideLimits(), ScrollWheelBase::keepOffsetInsideLimits(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), ScrollBase::setDrawableSize(), ScrollWheelWithSelectionStyle::setOffset(), and ScrollList::setWindowSize().
list
DrawableList list protected
The list.
Referenced by ScrollBase::ScrollBase(), ScrollBase::getCircular(), ScrollBase::getDrawableMargin(), ScrollBase::getDrawableSize(), ScrollBase::getHorizontal(), ScrollList::getItem(), ScrollBase::getNumberOfItems(), ScrollBase::getOffset(), ScrollList::getPositionForItem(), ScrollBase::initialize(), ScrollBase::itemChanged(), ScrollWheelWithSelectionStyle::refreshDrawableListsLayout(), ScrollBase::setCircular(), ScrollList::setDrawables(), ScrollWheel::setDrawables(), ScrollBase::setDrawableSize(), ScrollBase::setHeight(), ScrollBase::setHorizontal(), ScrollBase::setNumberOfItems(), ScrollBase::setOffset(), ScrollList::setPadding(), and ScrollBase::setWidth().
maxSwipeItems
uint16_t maxSwipeItems protected
The maximum swipe items.
Referenced by ScrollBase::getMaxSwipeItems(), ScrollBase::handleGestureEvent(), ScrollWheelBase::handleGestureEvent(), and ScrollBase::setMaxSwipeItems().
numberOfDrawables
int16_t numberOfDrawables protected
Number of drawables.
Referenced by ScrollList::setDrawables(), and ScrollWheel::setDrawables().
overshootPercentage
uint8_t overshootPercentage protected
The overshoot percentage when dragging.
Referenced by ScrollBase::getOvershootPercentage(), ScrollBase::handleDragEvent(), ScrollWheelBase::handleDragEvent(), and ScrollBase::setOvershootPercentage().
swipeAcceleration
uint16_t swipeAcceleration protected
The swipe acceleration x10.
Referenced by ScrollBase::getSwipeAcceleration(), ScrollBase::handleGestureEvent(), ScrollWheelBase::handleGestureEvent(), and ScrollBase::setSwipeAcceleration().
xClick
int16_t xClick protected
The x coordinate of a click.
Referenced by ScrollList::handleClickEvent(), and ScrollWheelBase::handleClickEvent().
yClick
int16_t yClick protected
The y coordinate of a click.
Referenced by ScrollList::handleClickEvent(), and ScrollWheelBase::handleClickEvent().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/scrollers/ScrollBase.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/scrollers/ScrollBase.cpp