Battery Simulator Documentation: AbstractGraphElement
AbstractGraphElement abstract
#include "GraphElements.hpp"
Public Member Functions
AbstractGraphElement ()
virtual void invalidateGraphPointAt (int16_t index)=0
Public Member Functions inherited from CanvasWidget
CanvasWidget ()
virtual void draw (const Rect &invalidatedArea) const
virtual bool drawCanvasWidget (const Rect &invalidatedArea) const =0
virtual uint8_t getAlpha () const
virtual Rect getMinimalRect () const
const AbstractPainter * getPainter () const
virtual Rect getSolidRect () const
virtual void invalidate () const
virtual void setAlpha (uint8_t newAlpha)
void setPainter (const AbstractPainter &painter)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
FORCE_INLINE_FUNCTION int convertToGraphScaleX (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION int convertToGraphScaleY (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION AbstractDataGraph * getGraph () const
FORCE_INLINE_FUNCTION int getIndexToXAxis (const AbstractDataGraph *graph, const int valueScaled, const int labelScaled) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenXQ5 (const AbstractDataGraph *graph, int16_t index) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenYQ5 (const AbstractDataGraph *graph, int16_t index) const
bool isCenterInvisible (const AbstractDataGraph *graph, int16_t index) const
Rect rectAround (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5, CWRUtil::Q5 diameterQ5) const
Rect rectFromQ5Coordinates (CWRUtil::Q5 screenXminQ5, CWRUtil::Q5 screenYminQ5, CWRUtil::Q5 screenXmaxQ5, CWRUtil::Q5 screenYmaxQ5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 roundQ5 (CWRUtil::Q5 q5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenXQ5 (const AbstractDataGraph *graph, int x) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenYQ5 (const AbstractDataGraph *graph, int y) const
FORCE_INLINE_FUNCTION bool xScreenRangeToIndexRange (const AbstractDataGraph *graph, int16_t xMin, int16_t xMax, int16_t &indexMin, int16_t &indexMax) const
Additional Inherited Members
Protected Attributes inherited from CanvasWidget
uint8_t alpha
The Alpha for this CanvasWidget.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Detailed Description
An abstract graph element. Declares a couple of useful functions to help subclasses which use CWR (Canvas Widget Renderer).
Constructor & Destructor Documentation
AbstractGraphElement()
AbstractGraphElement () inline
Default constructor.
        : CanvasWidget()
    {
    }
Member Function Documentation
convertToGraphScaleX()
FORCE_INLINE_FUNCTION int convertToGraphScaleX (const AbstractDataGraph * graph, int value, int scale) const inline protected
Converts the value to the proper X scale of the graph.
Parameters
graph The graph.
value The value.
scale The scale.
Returns
The given data converted to a graph scale x coordinate.
    {
        return AbstractDataGraph::convertToNewScale(value, scale, graph->getScaleX());
    }
References AbstractDataGraph::convertToNewScale().
Referenced by GraphElementGridX::getCorrectlyScaledGridInterval(), and GraphLabelsX::getCorrectlyScaledLabelInterval().
convertToGraphScaleY()
FORCE_INLINE_FUNCTION int convertToGraphScaleY (const AbstractDataGraph * graph, int value, int scale) const inline protected
Converts the value to the proper Y scale of the graph.
Parameters
graph The graph.
value The value.
scale The scale.
Returns
The given data converted to a graph scale y coordinate.
    {
        return AbstractDataGraph::convertToNewScale(value, scale, graph->getScaleY());
    }
References AbstractDataGraph::convertToNewScale().
Referenced by GraphElementHistogram::draw(), GraphElementArea::drawCanvasWidget(), GraphElementGridY::getCorrectlyScaledGridInterval(), GraphLabelsY::getCorrectlyScaledLabelInterval(), GraphElementArea::invalidateGraphPointAt(), and GraphElementHistogram::invalidateGraphPointAt().
getGraph()
FORCE_INLINE_FUNCTION AbstractDataGraph * getGraph () const inline protected
Gets a pointer to the the graph containing the GraphElement.
Returns
A pointer to the graph.
    {
        return parent ? (AbstractDataGraph*)(parent->getParent()) : (AbstractDataGraph*)0;
    }
References Drawable::getParent(), and Drawable::parent.
Referenced by GraphElementGridBase::draw(), GraphElementVerticalGapLine::draw(), GraphElementHistogram::draw(), GraphElementBoxes::draw(), GraphLabelsBase::draw(), GraphTitle::draw(), GraphElementArea::drawCanvasWidget(), GraphElementLine::drawCanvasWidget(), GraphElementDots::drawCanvasWidget(), GraphElementDiamonds::drawCanvasWidget(), GraphElementArea::invalidateGraphPointAt(), GraphElementLine::invalidateGraphPointAt(), GraphElementVerticalGapLine::invalidateGraphPointAt(), GraphElementHistogram::invalidateGraphPointAt(), GraphElementBoxes::invalidateGraphPointAt(), GraphElementDots::invalidateGraphPointAt(), GraphElementDiamonds::invalidateGraphPointAt(), and GraphLabelsX::invalidateGraphPointAt().
getIndexToXAxis()
FORCE_INLINE_FUNCTION int getIndexToXAxis (const AbstractDataGraph * graph, const int valueScaled, const int labelScaled) const inline protected
Convert the given valueScaled (index) to x axis value.
Parameters
valueScaled The value scaled.
labelScaled The label scaled.
Returns
The x axis value.
Parameters
graph The graph.
Returns
The x axis value.
    {
        return graph->indexToXAxis(valueScaled, labelScaled);
    }
Referenced by GraphLabelsX::drawString(), and GraphLabelsX::invalidateGraphPointAt().
indexToScreenXQ5()
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenXQ5 (const AbstractDataGraph * graph, int16_t index) const inline protected
Gets screen x coordinate for a specific data point added to the graph.
Parameters
graph The graph.
index The index of the element to get the x coordinate for.
Returns
The screen x coordinate for the specific data point.
    {
        return graph->indexToScreenXQ5(index);
    }
Referenced by GraphElementVerticalGapLine::draw(), GraphElementHistogram::draw(), GraphElementBoxes::draw(), GraphElementArea::drawCanvasWidget(), GraphElementDots::drawCanvasWidget(), GraphElementDiamonds::drawCanvasWidget(), GraphElementLine::drawIndexRange(), GraphElementArea::invalidateGraphPointAt(), GraphElementLine::invalidateGraphPointAt(), GraphElementHistogram::invalidateGraphPointAt(), GraphElementBoxes::invalidateGraphPointAt(), GraphElementDots::invalidateGraphPointAt(), GraphElementDiamonds::invalidateGraphPointAt(), GraphElementVerticalGapLine::invalidateIndex(), and AbstractGraphElement::isCenterInvisible().
indexToScreenYQ5()
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenYQ5 (const AbstractDataGraph * graph, int16_t index) const inline protected
Gets screen y coordinate for a specific data point added to the graph.
Parameters
graph The graph.
index The index of the element to get the y coordinate for.
Returns
The screen x coordinate for the specific data point.
    {
        return graph->indexToScreenYQ5(index);
    }
Referenced by GraphElementHistogram::draw(), GraphElementBoxes::draw(), GraphElementArea::drawCanvasWidget(), GraphElementDots::drawCanvasWidget(), GraphElementDiamonds::drawCanvasWidget(), GraphElementLine::drawIndexRange(), GraphElementArea::invalidateGraphPointAt(), GraphElementLine::invalidateGraphPointAt(), GraphElementHistogram::invalidateGraphPointAt(), GraphElementBoxes::invalidateGraphPointAt(), GraphElementDots::invalidateGraphPointAt(), GraphElementDiamonds::invalidateGraphPointAt(), and AbstractGraphElement::isCenterInvisible().
invalidateGraphPointAt()
virtual void invalidateGraphPointAt (int16_t index) pure virtual
Invalidate the point at the given index. This allows a graph element to only invalidate the minimum rectangle required for the given index. The Graph will call this function before and after changing a point to ensure that both the old and the new area are redrawn (invalidated).
Parameters
index Zero-based index of the point.
Implemented in GraphElementArea, GraphElementLine, GraphElementVerticalGapLine, GraphElementHistogram, GraphElementBoxes, GraphElementDots, GraphElementDiamonds, GraphLabelsX, GraphElementGridBase, GraphLabelsBase, and GraphTitle.
isCenterInvisible()
bool isCenterInvisible (const AbstractDataGraph * graph, int16_t index) const protected
Query if the center of a given data point index is visible inside the graph area.
Parameters
graph The graph.
index The data point index.
Returns
True if center invisible, false if not.
{
    const int16_t screenXCenter = indexToScreenXQ5(graph, index).round();
    const int16_t screenYCenter = indexToScreenYQ5(graph, index).round();
    return screenXCenter < graph->getGraphAreaPaddingLeft() ||
           screenXCenter >= graph->getGraphAreaPaddingLeft() + graph->getGraphAreaWidth() ||
           screenYCenter < graph->getGraphAreaPaddingTop() ||
           screenYCenter >= graph->getGraphAreaPaddingTop() + graph->getGraphAreaHeight();
}
References AbstractGraphElement::indexToScreenXQ5(), AbstractGraphElement::indexToScreenYQ5(), and CWRUtil::Q5::round().
Referenced by GraphElementBoxes::draw(), GraphElementDots::drawCanvasWidget(), GraphElementDiamonds::drawCanvasWidget(), GraphElementBoxes::invalidateGraphPointAt(), GraphElementDots::invalidateGraphPointAt(), and GraphElementDiamonds::invalidateGraphPointAt().
rectAround()
Rect rectAround (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5, CWRUtil::Q5 diameterQ5) const protected
Find the screen rectangle around a given point with the specified diameter.
Parameters
xQ5 The screen x coordinate (in Q5).
yQ5 The screen y coordinate (in Q5).
diameterQ5 The diameter (in Q5).
Returns
A Rect containing the point (and diameter).
{
    const CWRUtil::Q5 d2Q5 = CWRUtil::Q5((int32_t)diameterQ5 + 1) / 2;
    return rectFromQ5Coordinates(xQ5 - d2Q5, yQ5 - d2Q5, xQ5 + d2Q5, yQ5 + d2Q5);
}
References AbstractGraphElement::rectFromQ5Coordinates().
Referenced by GraphElementDots::drawCanvasWidget(), GraphElementDiamonds::drawCanvasWidget(), GraphElementLine::invalidateGraphPointAt(), GraphElementDots::invalidateGraphPointAt(), and GraphElementDiamonds::invalidateGraphPointAt().
rectFromQ5Coordinates()
Rect rectFromQ5Coordinates (CWRUtil::Q5 screenXminQ5, CWRUtil::Q5 screenYminQ5, CWRUtil::Q5 screenXmaxQ5, CWRUtil::Q5 screenYmaxQ5) const protected
Find the screen rectangle containing the Q5 screen rectangle by rounding the coordinates up/down.
Parameters
screenXminQ5 The minimum screen x coordinate (in Q5).
screenYminQ5 The maximum screen y coordinate (in Q5).
screenXmaxQ5 The minimum screen x coordinate (in Q5).
screenYmaxQ5 The maximum screen y coordinate (in Q5).
Returns
A Rect containing the Q5 rectangle.
{
    if (screenXminQ5 > screenXmaxQ5)
    {
        const CWRUtil::Q5 tmp = screenXminQ5;
        screenXminQ5 = screenXmaxQ5;
        screenXmaxQ5 = tmp;
    }
    if (screenYminQ5 > screenYmaxQ5)
    {
        const CWRUtil::Q5 tmp = screenYminQ5;
        screenYminQ5 = screenYmaxQ5;
        screenYmaxQ5 = tmp;
    }
    const int16_t xMin = screenXminQ5.to<int>();
    const int16_t yMin = screenYminQ5.to<int>();
    const int16_t xMax = screenXmaxQ5.ceil();
    const int16_t yMax = screenYmaxQ5.ceil();
    return Rect(xMin, yMin, xMax - xMin, yMax - yMin);
}
Referenced by GraphElementArea::invalidateGraphPointAt(), GraphElementHistogram::invalidateGraphPointAt(), and AbstractGraphElement::rectAround().
roundQ5()
FORCE_INLINE_FUNCTION CWRUtil::Q5 roundQ5 (CWRUtil::Q5 q5) const inline protected
Round the given CWRUtil::Q5 to the nearest integer and return it as a CWRUtil::Q5 instead of an integer.
Parameters
q5 The CWRUtil::Q5 value to round.
Returns
The nearest integer as a CWRUtil::Q5 value.
    {
        return CWRUtil::toQ5(q5.round());
    }
References CWRUtil::toQ5().
Referenced by GraphElementArea::drawCanvasWidget(), GraphElementDots::drawCanvasWidget(), GraphElementDiamonds::drawCanvasWidget(), GraphElementLine::drawIndexRange(), and GraphElementArea::invalidateGraphPointAt().
valueToScreenXQ5()
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenXQ5 (const AbstractDataGraph * graph, int x) const inline protected
Gets graph screen x for x value.
Parameters
graph The graph.
x The x value.
Returns
The graph screen x for value.
    {
        return graph->valueToScreenXQ5(x);
    }
Referenced by GraphLabelsX::drawString(), GraphLabelsX::invalidateGraphPointAt(), and GraphElementGridX::valueToScreenQ5().
valueToScreenYQ5()
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenYQ5 (const AbstractDataGraph * graph, int y) const inline protected
Gets graph screen y for y value.
Parameters
graph The graph.
y The y value.
Returns
The graph screen y for value.
    {
        return graph->valueToScreenYQ5(y);
    }
Referenced by GraphElementHistogram::draw(), GraphElementArea::drawCanvasWidget(), GraphLabelsY::drawString(), GraphElementArea::invalidateGraphPointAt(), GraphElementHistogram::invalidateGraphPointAt(), and GraphElementGridY::valueToScreenQ5().
xScreenRangeToIndexRange()
FORCE_INLINE_FUNCTION bool xScreenRangeToIndexRange (const AbstractDataGraph * graph, int16_t xMin, int16_t xMax, int16_t & indexMin, int16_t & indexMax) const inline protected
Gets graph element range for screen x coordinate range.
Parameters
graph The graph.
xMin The low X.
xMax The high X.
[out] indexMin The low index.
[out] indexMax The high index.
Returns
True if it succeeds, false if it fails.
    {
        return graph->xScreenRangeToIndexRange(xMin, xMax, indexMin, indexMax);
    }
Referenced by GraphElementHistogram::draw(), GraphElementBoxes::draw(), GraphElementArea::drawCanvasWidget(), GraphElementLine::drawCanvasWidget(), GraphElementDots::drawCanvasWidget(), and GraphElementDiamonds::drawCanvasWidget().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/graph/GraphElements.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph/GraphElements.cpp