Battery Simulator Documentation: ScrollableContainer
ScrollableContainer
#include "ScrollableContainer.hpp"
Public Member Functions
ScrollableContainer ()
virtual void add (Drawable &d)
virtual void childGeometryChanged ()
virtual bool doScroll (int16_t deltaX, int16_t deltaY)
void enableHorizontalScroll (bool enable)
void enableVerticalScroll (bool enable)
virtual Rect getChildrenContainedArea () const
virtual Rect getContainedArea () const
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
uint16_t getScrollDurationSlowdown () const
uint16_t getScrollDurationSpeedup () const
int16_t getScrolledX () const
int16_t getScrolledY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void isScrollableXY (bool &scrollX, bool &scrollY)
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
void reset ()
void setMaxVelocity (uint16_t max)
void setScrollbarPadding (uint8_t padding)
void setScrollbarsAlpha (uint8_t alpha)
void setScrollbarsColor (colortype color)
void setScrollbarsPermanentlyVisible (bool permanentlyVisible=true)
void setScrollbarsVisible (bool newVisible)
void setScrollbarWidth (uint8_t width)
void setScrollDurationSlowdown (uint16_t slowdown)
void setScrollDurationSpeedup (uint16_t speedup)
void setScrollThreshold (int16_t t)
Public Member Functions inherited from Container
Container ()
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void invalidate () const
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Member Functions
Rect getXBorder (const Rect &xBar, const Rect &yBar) const
Rect getXScrollbar () const
Rect getYBorder (const Rect &xBar, const Rect &yBar) const
Rect getYScrollbar () const
void invalidateScrollbars ()
Protected Attributes
GestureEvent::GestureEventType accelDirection
The current direction (horizontal or vertical) of scroll.
bool animate
Is scroll animation currently active.
uint16_t animationCounter
Current step/tick in scroll animation.
int16_t beginningValue
Initial X or Y for calculated values in scroll animation.
int16_t fingerAdjustmentX
How much should the finger be adjusted horizontally.
int16_t fingerAdjustmentY
and how much vertically
bool hasIssuedCancelEvent
true if the pressed drawable has received cancel event
bool isPressed
Is the container currently pressed (maybe show scrollbars)
bool isScrolling
Is the container scrolling (i.e. has overcome the initial larger drag that is required to initiate a scroll).
Drawable * lastDraggableChild
The drawable child of this container which should receive drag events. Note that only drag events in directions which cannot be scrolled by this ScrollableContainer will be forwarded to children.
uint16_t maxVelocity
The maximum velocity of a scroll (due to a swipe)
Drawable * pressedDrawable
The drawable child of this container which received the last ClickEvent::PRESSED notification. When scrolling, send this drawable a CANCEL event if the new x/y coords no longer matches this drawable.
int16_t pressedX
The x coordinate where the last ClickEvent::PRESSED was received.
int16_t pressedY
The y coordinate where the last ClickEvent::PRESSED was received.
bool scrollableX
Is the container scrollable in the horizontal direction.
bool scrollableY
Is the container scrollable in the vertical direction.
uint8_t scrollbarAlpha
The scrollbar is semitransparent.
colortype scrollbarColor
The color of the scrollbar.
uint8_t scrollbarPadding
The amount of padding. The scrollbar will have a bit of space to the borders of the container.
bool scrollbarsPermanentlyVisible
Are scrollbars always visible.
bool scrollbarsVisible
Are scrollbars visible.
uint8_t scrollbarWidth
The width of the scrollbar.
uint16_t scrollDuration
Number of ticks the scroll animation should use.
uint16_t scrollDurationSlowdown
The scroll durations is divided by this number.
uint16_t scrollDurationSpeedup
The scroll durations is multipled by this number.
int16_t scrolledXDistance
The scrolled horizontal distance.
int16_t scrolledYDistance
The scrolled vertical distance.
int16_t scrollThreshold
The threshold which the first drag event received must exceed before scrolling. Default is 5.
int16_t targetValue
Target X or Y value for scroll animation.
Box xSlider
The horizontal scrollbar drawable.
Box ySlider
The vertical scrollbar drawable.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Static Protected Attributes
static const uint8_t SCROLLBAR_LINE = 0
The scrollbar line.
static const uint16_t SCROLLBAR_MAX_VELOCITY = 17
The (default) maximum velocity of a scroll due to a swipe.
static const uint16_t SCROLLBAR_MIN_VELOCITY = 5
The minimum velocity of a scroll due to a swipe.
Detailed Description
A ScrollableContainer is a container that allows its contents to be scrolled. It will intercept drag operations and move child nodes accordingly.
A standard Container will simply clip children that are either larger than the container itself, or children that extend beyond the borders of the container or children that are placed outside the borders of the container. A ScrollableContainer behaves much like a Container, except it enables the user to scroll the children and thereby act like a viewport. When the contents of the ScrollableContainer is scrollable, scrollbars can be seen near the edge of the ScrollableContainer.
See also
Container
Note
The ScrollableContainer will consume all DragEvents in the area covered by the container.
Constructor & Destructor Documentation
ScrollableContainer()
ScrollableContainer ()
    : Container(),
      scrollbarPadding(0),
      scrollbarWidth(2),
      scrollbarAlpha(120),
      scrollbarColor(Color::getColorFromRGB(0xFF, 0xFF, 0xFF)),
      maxVelocity(SCROLLBAR_MAX_VELOCITY),
      accelDirection(GestureEvent::SWIPE_HORIZONTAL),
      xSlider(0, 0, scrollbarColor, scrollbarAlpha),
      ySlider(0, 0, scrollbarColor, scrollbarAlpha),
      pressedDrawable(0),
      lastDraggableChild(0),
      scrolledXDistance(0),
      scrolledYDistance(0),
      scrollThreshold(5),
      pressedX(0),
      pressedY(0),
      isPressed(false),
      isScrolling(false),
      scrollableX(true),
      scrollableY(true),
      scrollbarsVisible(true),
      scrollbarsPermanentlyVisible(false),
      scrollDuration(0),
      beginningValue(0),
      targetValue(0),
      animationCounter(0),
      animate(false),
      fingerAdjustmentX(0),
      fingerAdjustmentY(0),
      hasIssuedCancelEvent(false),
      scrollDurationSpeedup(7),
      scrollDurationSlowdown(1)
{
    xSlider.setVisible(false);
    ySlider.setVisible(false);
    setTouchable(true);
}
References Drawable::setTouchable(), Drawable::setVisible(), ScrollableContainer::xSlider, and ScrollableContainer::ySlider.
Member Function Documentation
add()
void add (Drawable & d) virtual
Adds a Drawable instance as child to this Container. The Drawable added will be placed as the element to be drawn last, and thus appear on top of all previously added drawables in the Container.
Parameters
[in] d The Drawable to add.
Note
Never add a drawable more than once!
Reimplemented from Container.
{
    remove(xSlider);
    remove(ySlider);
    Container::add(d);
    Container::add(xSlider);
    Container::add(ySlider);
}
References Container::add(), Container::remove(), ScrollableContainer::xSlider, and ScrollableContainer::ySlider.
childGeometryChanged()
void childGeometryChanged () virtual
Used to signal that the size or position of one or more children have changed. This function can be called on parent nodes to signal that the size of one or more of its children have changed.
Reimplemented from Drawable.
{
    int deltaX = 0;
    int deltaY = 0;
    const Rect contained = getChildrenContainedArea();
    if (contained.y > 0)
    {
        // Make sure we haven't scrolled above the top
        deltaY = contained.y;
    }
    else if (contained.bottom() < rect.height)
    {
        // Make sure we haven't scrolled below the bottom
        deltaY = contained.bottom() - rect.height;
        if (contained.y > deltaY)
        {
            deltaY = contained.y;
        }
    }
    if (contained.x > 0)
    {
        // Make sure we haven't scrolled too far to the left
        deltaX = contained.x;
    }
    else if (contained.right() < rect.width)
    {
        // Make sure we haven't scrolled too far to the right
        deltaX = contained.right() - rect.width;
        if (contained.x > deltaX)
        {
            deltaX = contained.x;
        }
    }
    if (deltaX != 0 || deltaY != 0)
    {
        moveChildrenRelative(-deltaX, -deltaY);
        invalidateScrollbars();
    }
}
References ScrollableContainer::getChildrenContainedArea(), Rect::height, ScrollableContainer::invalidateScrollbars(), ScrollableContainer::moveChildrenRelative(), Drawable::rect, and Rect::width.
doScroll()
bool doScroll (int16_t deltaX, int16_t deltaY) virtual
Method to actually scroll the container. Passing negative values will scroll the items in the ScrollableContainer up / left, whereas positive values will scroll items down / right.
If the distance is larger than allowed, the deltas are adjusted down to make sure the contained items stay inside view.
Parameters
deltaX The horizontal amount to scroll.
deltaY The vertical amount to scroll.
Returns
did the container actually scroll. The call doScroll(0,0) will always return false.
{
    if (!deltaX && !deltaY)
    {
        return false;
    }
    bool couldScroll = false;
    const Rect contained = getContainedArea();
    if (contained.width > rect.width)
    {
        if (deltaX > 0)
        {
            if (contained.x + deltaX > 0)
            {
                deltaX = -contained.x;
            }
        }
        else if (deltaX < 0)
        {
            if (contained.right() + deltaX < rect.width)
            {
                deltaX = rect.width - contained.right();
            }
        }
    }
    else
    {
        deltaX = 0;
    }
    if (contained.height > rect.height)
    {
        if (deltaY > 0)
        {
            if (contained.y + deltaY > 0)
            {
                deltaY = -contained.y;
            }
        }
        else if (deltaY < 0)
        {
            if (contained.bottom() + deltaY < rect.height)
            {
                deltaY = rect.height - contained.bottom();
            }
        }
    }
    else
    {
        deltaY = 0;
    }
    if (deltaX || deltaY)
    {
        moveChildrenRelative(deltaX, deltaY);
        invalidateScrollbars();
        couldScroll = true;
    }
    return couldScroll;
}
References ScrollableContainer::getContainedArea(), Rect::height, ScrollableContainer::invalidateScrollbars(), ScrollableContainer::moveChildrenRelative(), Drawable::rect, and Rect::width.
Referenced by ScrollableContainer::handleDragEvent(), and ScrollableContainer::handleTickEvent().
enableHorizontalScroll()
void enableHorizontalScroll (bool enable) inline
Enables horizontal scrolling. By default, scrolling in either direction is enabled, provided that the content is larger than the size of the ScrollableContainer. This function can be used to explicitly (dis)allow horizontal scrolling, even if the content is larger than the container.
Parameters
enable If true (default), horizontal scrolling is enabled. If false, horizontal scrolling is disabled.
See also
enableVerticalScroll
    {
        scrollableX = enable;
    }
References ScrollableContainer::scrollableX.
enableVerticalScroll()
void enableVerticalScroll (bool enable) inline
Enables vertical scrolling. By default, scrolling in either direction is enabled, provided that the content is larger than the size of the ScrollableContainer. This function can be used to explicitly (dis)allow vertical scrolling, even if the content is larger than the container.
Parameters
enable If true (default), vertical scrolling is enabled. If false, vertical scrolling is disabled.
See also
enableHorizontalScroll
    {
        scrollableY = enable;
    }
References ScrollableContainer::scrollableY.
getChildrenContainedArea()
Rect getChildrenContainedArea () const virtual
Gets the area that contains all children added to the ScrollableContainer. The container itself and scrollbars are not considered in this operation.
Returns
The area containing only the children.
See also
getContainedArea
{
    Rect contained;
    for (Drawable* d = firstChild; d; d = d->getNextSibling())
    {
        if ((d != &xSlider) && (d != &ySlider) && (d->isVisible()))
        {
            contained.expandToFit(d->getRect());
        }
    }
    return contained;
}
References Container::firstChild, ScrollableContainer::xSlider, and ScrollableContainer::ySlider.
Referenced by ScrollableContainer::childGeometryChanged(), and ScrollableContainer::getContainedArea().
getContainedArea()
Rect getContainedArea () const virtual
Gets the area that contains all children added to the ScrollableContainer. The scrollbars are not considered in this operation. The area also includes the scrollableContainer itself.
Returns
The contained area.
See also
getChildrenContainedArea
Reimplemented from Container.
{
    Rect contained(0, 0, rect.width, rect.height);
    contained.expandToFit(getChildrenContainedArea());
    return contained;
}
References ScrollableContainer::getChildrenContainedArea(), Rect::height, Drawable::rect, and Rect::width.
Referenced by ScrollableContainer::doScroll(), ScrollableContainer::getXScrollbar(), ScrollableContainer::getYScrollbar(), ScrollableContainer::handleGestureEvent(), ScrollableContainer::handleTickEvent(), and ScrollableContainer::isScrollableXY().
getLastChild()
virtual void getLastChild (int16_t x, int16_t y, Drawable ** last) inline virtual
Gets the last child in the list of children in this Container. If this Container is touchable (isTouchable()), it will be passed back as the result. Otherwise all visible children are traversed recursively to find the Drawable that intersects with the given coordinate.
Parameters
x The x coordinate of the intersection.
y The y coordinate of the intersection.
[out] last out parameter in which the result is placed.
See also
isVisible, isTouchable, getLastChildNear
Reimplemented from Container.
    {
        if (isVisible())
        {
            if (isTouchable())
            {
                *last = this;
            }
            else
            {
                Container::getLastChild(x, y, last);
            }
        }
    }
References Container::getLastChild(), Drawable::isTouchable(), and Drawable::isVisible().
getScrollDurationSlowdown()
uint16_t getScrollDurationSlowdown () const
Gets scroll duration speedup divisor.
Returns
The scroll duration speedup divisor.
See also
setScrollDurationSlowdown
{
    return scrollDurationSlowdown;
}
References ScrollableContainer::scrollDurationSlowdown.
getScrollDurationSpeedup()
uint16_t getScrollDurationSpeedup () const
Gets scroll duration speedup multiplier.
Returns
The swipe acceleration.
See also
setScrollDurationSpeedup, getScrollDurationSlowdown
{
    return scrollDurationSpeedup;
}
References ScrollableContainer::scrollDurationSpeedup.
getScrolledX()
int16_t getScrolledX () const
Gets the distance scrolled for the x-axis.
Returns
the distance scrolled for the x-axis.
{
    return scrolledXDistance;
}
References ScrollableContainer::scrolledXDistance.
getScrolledY()
int16_t getScrolledY () const
Gets the distance scrolled for the y-axis.
Returns
the distance scrolled for the y-axis.
{
    return scrolledYDistance;
}
References ScrollableContainer::scrolledYDistance.
getXBorder()
Rect getXBorder (const Rect & xBar, const Rect & yBar) const protected
Gets the area where the horizontal scrollbar can move.
Parameters
xBar The current horizontal scrollbar, supplied for caching reasons.
yBar The current vertical scrollbar, supplied for caching reasons.
Returns
The area.
{
    Rect border;
    if (!xBar.isEmpty())
    {
        const int scrollSpace = (!yBar.isEmpty()) ? (2 * scrollbarPadding + scrollbarWidth + SCROLLBAR_LINE) : 0;
        border = Rect(scrollbarPadding, xBar.y - SCROLLBAR_LINE, rect.width - (2 * scrollbarPadding + scrollSpace), scrollbarWidth + 2 * SCROLLBAR_LINE);
    }
    return border;
}
References Drawable::rect, ScrollableContainer::SCROLLBAR_LINE, ScrollableContainer::scrollbarPadding, ScrollableContainer::scrollbarWidth, and Rect::width.
Referenced by ScrollableContainer::invalidateScrollbars().
getXScrollbar()
Rect getXScrollbar () const protected
Gets x coordinate of the scrollbar.
Returns
The horizontal scrollbar area.
{
    Rect res;
    if (scrollableX)
    {
        const Rect contained = getContainedArea();
        const int scrollSpace = (scrollableY && (contained.height > rect.height)) ? (2 * scrollbarPadding + scrollbarWidth + SCROLLBAR_LINE) : 0;
        if (contained.width > rect.width)
        {
            int leftPadding = (-1 * contained.x * rect.width) / contained.width;
            const int rightPadding = ((contained.right() - rect.width) * rect.width) / contained.width;
            const int startWidth = rect.width - (2 * scrollbarPadding + 2 * SCROLLBAR_LINE + scrollSpace);
            int width = startWidth;
            width -= (leftPadding + rightPadding);
            if (width < scrollbarWidth * 2)
            {
                // If the contained area is very large, the scrollbar width may become zero or even negative.
                const int diff = scrollbarWidth * 2 - width;
                width = scrollbarWidth * 2; // Force scrollbar width to a minimum
                // Distribute the deviation error based on current scrollbar X position (the amount subtracted from scrollbar xpos increases gradually).
                leftPadding -= (diff * leftPadding) / startWidth;
            }
            res = Rect(leftPadding + scrollbarPadding + SCROLLBAR_LINE, rect.height - (scrollbarWidth + scrollbarPadding + SCROLLBAR_LINE), width, scrollbarWidth);
        }
    }
    return res;
}
References ScrollableContainer::getContainedArea(), Rect::height, Drawable::rect, ScrollableContainer::scrollableX, ScrollableContainer::scrollableY, ScrollableContainer::SCROLLBAR_LINE, ScrollableContainer::scrollbarPadding, ScrollableContainer::scrollbarWidth, and Rect::width.
Referenced by ScrollableContainer::invalidateScrollbars().
getYBorder()
Rect getYBorder (const Rect & xBar, const Rect & yBar) const protected
Gets the area where the vertical scrollbar can move.
Parameters
xBar The current horizontal scrollbar, supplied for caching reasons.
yBar The current vertical scrollbar, supplied for caching reasons.
Returns
The area.
{
    Rect border;
    if (!yBar.isEmpty())
    {
        const int scrollSpace = (!xBar.isEmpty()) ? (2 * scrollbarPadding + scrollbarWidth + SCROLLBAR_LINE) : 0;
        border = Rect(yBar.x - SCROLLBAR_LINE, scrollbarPadding, scrollbarWidth + 2 * SCROLLBAR_LINE, rect.height - (2 * scrollbarPadding + scrollSpace));
    }
    return border;
}
References Rect::height, Drawable::rect, ScrollableContainer::SCROLLBAR_LINE, ScrollableContainer::scrollbarPadding, and ScrollableContainer::scrollbarWidth.
Referenced by ScrollableContainer::invalidateScrollbars().
getYScrollbar()
Rect getYScrollbar () const protected
Gets y coordinate of the scrollbar.
Returns
The vertical scrollbar area.
{
    Rect res;
    if (scrollableY)
    {
        const Rect contained = getContainedArea();
        const int scrollSpace = (scrollableX && (contained.width > rect.width)) ? (2 * scrollbarPadding + scrollbarWidth + SCROLLBAR_LINE) : 0;
        if (contained.height > rect.height)
        {
            int topPadding = (-1 * contained.y * rect.height) / contained.height;
            const int bottomPadding = ((contained.bottom() - rect.height) * rect.height) / contained.height;
            const int startHeight = rect.height - (2 * scrollbarPadding + 2 * SCROLLBAR_LINE + scrollSpace);
            int height = startHeight;
            height -= (topPadding + bottomPadding);
            if (height < scrollbarWidth * 2)
            {
                // If the contained area is very large, the scrollbar height may become zero or even negative.
                const int diff = scrollbarWidth * 2 - height;
                height = scrollbarWidth * 2; // Force scrollbar height to a minimum
                // Distribute the deviation error based on current scrollbar Y position (the amount subtracted from scrollbar ypos increases gradually).
                topPadding -= (diff * topPadding) / startHeight;
            }
            res = Rect(rect.width - (scrollbarWidth + scrollbarPadding + 2 * SCROLLBAR_LINE), topPadding + scrollbarPadding + SCROLLBAR_LINE, scrollbarWidth, height);
        }
    }
    return res;
}
References ScrollableContainer::getContainedArea(), Rect::height, Drawable::rect, ScrollableContainer::scrollableX, ScrollableContainer::scrollableY, ScrollableContainer::SCROLLBAR_LINE, ScrollableContainer::scrollbarPadding, ScrollableContainer::scrollbarWidth, and Rect::width.
Referenced by ScrollableContainer::invalidateScrollbars().
handleClickEvent()
void handleClickEvent (const ClickEvent & event) virtual
Defines the event handler interface for ClickEvents. The default implementation ignores the event. The event is only received if the Drawable is touchable and visible.
Parameters
event The ClickEvent received from the HAL.
Reimplemented from Drawable.
{
    if (event.getType() == ClickEvent::PRESSED)
    {
        isPressed = true;
        if (animate)
        {
            // Stop scroll animation
            animate = false;
            animationCounter = 0;
            Application::getInstance()->unregisterTimerWidget(this);
        }
        getLastChildNear(event.getX(), event.getY(), &pressedDrawable, &fingerAdjustmentX, &fingerAdjustmentY);
        if (pressedDrawable == this)
        {
            pressedDrawable = 0;
        }
        if (pressedDrawable)
        {
            hasIssuedCancelEvent = false;
            pressedX = event.getX();
            pressedY = event.getY();
            const Rect r = pressedDrawable->getAbsoluteRect();
            const Rect me = getAbsoluteRect();
            const ClickEvent relative(event.getType(), event.getX() + fingerAdjustmentX - (r.x - me.x), event.getY() + fingerAdjustmentY - (r.y - me.y));
            pressedDrawable->handleClickEvent(relative);
            lastDraggableChild = pressedDrawable;
        }
    }
    else if (event.getType() == ClickEvent::CANCEL)
    {
        return;
    }
    else // if (event.getType() == ClickEvent::RELEASED)
    {
        if (pressedDrawable)
        {
            const Rect r = pressedDrawable->getAbsoluteRect();
            const Rect me = getAbsoluteRect();
            const ClickEvent relative(event.getType(), event.getX() + fingerAdjustmentX - (r.x - me.x), event.getY() + fingerAdjustmentY - (r.y - me.y));
            pressedDrawable->handleClickEvent(relative);
        }
        pressedDrawable = 0;
        lastDraggableChild = 0;
        isPressed = false;
    }
    isScrolling = false;
    // Redraw scrollbars.
    xSlider.setVisible((isPressed && scrollbarsVisible) || scrollbarsPermanentlyVisible);
    ySlider.setVisible((isPressed && scrollbarsVisible) || scrollbarsPermanentlyVisible);
    invalidateScrollbars();
}
References ScrollableContainer::animate, ScrollableContainer::animationCounter, ClickEvent::CANCEL, ScrollableContainer::fingerAdjustmentX, ScrollableContainer::fingerAdjustmentY, Drawable::getAbsoluteRect(), Application::getInstance(), Container::getLastChildNear(), Drawable::handleClickEvent(), ScrollableContainer::hasIssuedCancelEvent, ScrollableContainer::invalidateScrollbars(), ScrollableContainer::isPressed, ScrollableContainer::isScrolling, ScrollableContainer::lastDraggableChild, ClickEvent::PRESSED, ScrollableContainer::pressedDrawable, ScrollableContainer::pressedX, ScrollableContainer::pressedY, ScrollableContainer::scrollbarsPermanentlyVisible, ScrollableContainer::scrollbarsVisible, Drawable::setVisible(), ScrollableContainer::xSlider, and ScrollableContainer::ySlider.
handleDragEvent()
void handleDragEvent (const DragEvent & event) virtual
Defines the event handler interface for DragEvents. The default implementation ignores the event. The event is only received if the drawable is touchable and visible.
Parameters
event The DragEvent received from the HAL.
Reimplemented from Drawable.
{
    DragEvent actualDrag = event;
    bool acceptInitialScroll = false;
    bool canScrollX = false;
    bool canScrollY = false;
    isScrollableXY(canScrollX, canScrollY);
    if ((pressedDrawable != 0) && (pressedDrawable != this))
    {
        // Also send this drag event to the appropriate child widget
        const Rect r = pressedDrawable->getAbsoluteRect();
        const Rect me = getAbsoluteRect();
        const int16_t oldX = event.getOldX() + fingerAdjustmentX - (r.x - me.x);
        const int16_t oldY = event.getOldY() + fingerAdjustmentY - (r.y - me.y);
        const int16_t newX = canScrollX ? oldX : event.getNewX() + fingerAdjustmentX - (r.x - me.x);
        const int16_t newY = canScrollY ? oldY : event.getNewY() + fingerAdjustmentY - (r.y - me.y);
        // but only in the direction(s) where the scrollable container itself
        // cannot scroll.
        if ((!canScrollX && newX != oldX) || (!canScrollY && newY != oldY))
        {
            const DragEvent relative(DragEvent::DRAGGED, oldX, oldY, newX, newY);
            pressedDrawable->handleDragEvent(relative);
        }
    }
    // If we are not currently scrolling, the drag event delta must
    // be larger than the threshold value, otherwise the event is ignored.
    if (!isScrolling)
    {
        // Only consider the delta in directions that are actually scrollable.
        // Note: Do not use the delta from received event since that only reflects
        // change since last drag. What we want to check here is if the total
        // delta from the point of click has now exceeded the threshold.
        actualDrag = DragEvent(DragEvent::DRAGGED, pressedX + fingerAdjustmentX, pressedY + fingerAdjustmentY, event.getNewX() + fingerAdjustmentX, event.getNewY() + fingerAdjustmentY);
        if (canScrollX)
        {
            // Can scroll in X.
            if (abs(actualDrag.getDeltaX()) > scrollThreshold)
            {
                acceptInitialScroll = true;
            }
        }
        if (canScrollY)
        {
            // Can scroll in Y.
            if (abs(actualDrag.getDeltaY()) > scrollThreshold)
            {
                acceptInitialScroll = true;
            }
        }
        if (acceptInitialScroll)
        {
            isScrolling = true;
        }
        else
        {
            // Discard this drag event. However, if the new coordinates no longer matches the drawable which received the PRESSED click event
            // issue a CANCEL event to that drawable.
            if (pressedDrawable && !hasIssuedCancelEvent)
            {
                Drawable* child = 0;
                Container::getLastChild(event.getNewX() + fingerAdjustmentX, event.getNewY() + fingerAdjustmentY, &child);
                if (pressedDrawable != child)
                {
                    const ClickEvent ce(ClickEvent::CANCEL, 0, 0);
                    pressedDrawable->handleClickEvent(ce);
                    hasIssuedCancelEvent = true;
                }
            }
            return;
        }
    }
    // Send cancel events to child in focus
    if (pressedDrawable && !hasIssuedCancelEvent)
    {
        const ClickEvent ce(ClickEvent::CANCEL, 0, 0);
        pressedDrawable->handleClickEvent(ce);
        hasIssuedCancelEvent = true;
    }
    int16_t deltaX = 0;
    int16_t deltaY = 0;
    if (scrollableX)
    {
        if (acceptInitialScroll)
        {
            // Initial drag which is past threshold, only scroll one pixel in initial event.
            if (actualDrag.getDeltaX() > 0)
            {
                deltaX = 1;
            }
            else if (actualDrag.getDeltaX() < 0)
            {
                deltaX = -1;
            }
        }
        else
        {
            // Scroll entire delta
            deltaX = actualDrag.getDeltaX();
        }
    }
    else
    {
        // Not scrollable
        deltaX = 0;
    }
    if (scrollableY)
    {
        if (acceptInitialScroll)
        {
            // Initial drag which is past threshold, only scroll one pixel in initial event.
            if (actualDrag.getDeltaY() > 0)
            {
                deltaY = 1;
            }
            else if (actualDrag.getDeltaY() < 0)
            {
                deltaY = -1;
            }
        }
        else
        {
            // Scroll entire delta
            deltaY = actualDrag.getDeltaY();
        }
    }
    else
    {
        // Not scrollable
        deltaY = 0;
    }
    doScroll(deltaX, deltaY);
}
References touchgfx::abs(), ClickEvent::CANCEL, ScrollableContainer::doScroll(), DragEvent::DRAGGED, ScrollableContainer::fingerAdjustmentX, ScrollableContainer::fingerAdjustmentY, Drawable::getAbsoluteRect(), Container::getLastChild(), Drawable::handleClickEvent(), Drawable::handleDragEvent(), ScrollableContainer::hasIssuedCancelEvent, ScrollableContainer::isScrollableXY(), ScrollableContainer::isScrolling, ScrollableContainer::pressedDrawable, ScrollableContainer::pressedX, ScrollableContainer::pressedY, ScrollableContainer::scrollableX, ScrollableContainer::scrollableY, and ScrollableContainer::scrollThreshold.
handleGestureEvent()
void handleGestureEvent (const GestureEvent & event) virtual
Defines the event handler interface for GestureEvents. The default implementation ignores the event. The event is only received if the Drawable is touchable and visible.
Parameters
event The GestureEvent received from the HAL.
Reimplemented from Drawable.
{
    bool canScrollX = false;
    bool canScrollY = false;
    isScrollableXY(canScrollX, canScrollY);
    if ((canScrollX && (event.getType() == GestureEvent::SWIPE_HORIZONTAL)) ||
        (canScrollY && (event.getType() == GestureEvent::SWIPE_VERTICAL)))
    {
        int16_t velocityAbsolute = abs(event.getVelocity());
        // Ignore gestures with velocity lower than threshold
        if (velocityAbsolute < scrollThreshold)
        {
            return;
        }
        // Force velocity within limits
        velocityAbsolute = MIN(velocityAbsolute, maxVelocity);
        velocityAbsolute = MAX(velocityAbsolute, SCROLLBAR_MIN_VELOCITY);
        // Try to set some reasonable values for how long the resulting scroll should be, and how many ticks is should take
        scrollDuration = velocityAbsolute * scrollDurationSpeedup / scrollDurationSlowdown;
        targetValue = ((event.getVelocity() > 0) ? 1 : -1) * (velocityAbsolute - 4) * 72;
        const int16_t distance = abs(targetValue);
        scrollDuration = MIN(scrollDuration, distance);
        // Get ready to animate scroll: Initialize values
        beginningValue = (event.getType() == GestureEvent::SWIPE_VERTICAL) ? getContainedArea().y : getContainedArea().x;
        animate = true;
        Application::getInstance()->registerTimerWidget(this);
        accelDirection = event.getType();
        if (pressedDrawable && !hasIssuedCancelEvent)
        {
            const ClickEvent ce(ClickEvent::CANCEL, 0, 0);
            pressedDrawable->handleClickEvent(ce);
            hasIssuedCancelEvent = true;
        }
    }
}
References touchgfx::abs(), ScrollableContainer::accelDirection, ScrollableContainer::animate, ScrollableContainer::beginningValue, ClickEvent::CANCEL, ScrollableContainer::getContainedArea(), Application::getInstance(), Drawable::handleClickEvent(), ScrollableContainer::hasIssuedCancelEvent, ScrollableContainer::isScrollableXY(), MAX, ScrollableContainer::maxVelocity, MIN, ScrollableContainer::pressedDrawable, ScrollableContainer::SCROLLBAR_MIN_VELOCITY, ScrollableContainer::scrollDuration, ScrollableContainer::scrollDurationSlowdown, ScrollableContainer::scrollDurationSpeedup, ScrollableContainer::scrollThreshold, GestureEvent::SWIPE_HORIZONTAL, GestureEvent::SWIPE_VERTICAL, and ScrollableContainer::targetValue.
handleTickEvent()
void handleTickEvent () virtual
Called periodically by the framework if the Drawable instance has subscribed to timer ticks.
See also
Application::registerTimerWidget
Reimplemented from Drawable.
{
    if (!animate)
    {
        return;
    }
    // Calculate new position or stop animation
    animationCounter++;
    if (animationCounter <= scrollDuration)
    {
        // Calculate value in [beginningValue ; (beginningValue+targetValue)]
        int16_t calculatedValue = EasingEquations::cubicEaseOut(animationCounter, beginningValue, targetValue, scrollDuration);
        // Note: Result of "calculatedValue & 1" is compiler dependent for negative values of calculatedValue
        if (calculatedValue % 2)
        {
            // Optimization: calculatedValue is odd, add 1/-1 to move drawables modulo 32 bits in framebuffer
            calculatedValue += (calculatedValue > 0) ? 1 : -1;
        }
        // Convert to delta value relative to current X or Y
        const int16_t scrollX = (accelDirection == GestureEvent::SWIPE_VERTICAL) ? 0 : (calculatedValue - getContainedArea().x);
        const int16_t scrollY = (accelDirection == GestureEvent::SWIPE_HORIZONTAL) ? 0 : (calculatedValue - getContainedArea().y);
        // Perform the actual animation step, stop animation if
        // scrolling was not possible (doScroll invalidates children)
        animate = doScroll(scrollX, scrollY);
    }
    else
    {
        animate = false;
    }
    if (!animate)
    {
        Application::getInstance()->unregisterTimerWidget(this);
        animationCounter = 0;
    }
}
References ScrollableContainer::accelDirection, ScrollableContainer::animate, ScrollableContainer::animationCounter, ScrollableContainer::beginningValue, EasingEquations::cubicEaseOut(), ScrollableContainer::doScroll(), ScrollableContainer::getContainedArea(), Application::getInstance(), ScrollableContainer::scrollDuration, GestureEvent::SWIPE_HORIZONTAL, GestureEvent::SWIPE_VERTICAL, and ScrollableContainer::targetValue.
invalidateScrollbars()
void invalidateScrollbars () protected
Invalidate the scrollbars.
{
    const Rect xBar = getXScrollbar();
    const Rect yBar = getYScrollbar();
    Rect xBorder = getXBorder(xBar, yBar);
    Rect yBorder = getYBorder(xBar, yBar);
    // The two if statements ensure that the two sliders are invalidated thereby hides them, before they are set to size zero.
    if (xSlider.getY() > xBorder.y)
    {
        xSlider.invalidate();
    }
    if (ySlider.getX() > yBorder.x)
    {
        ySlider.invalidate();
    }
    xSlider.setPosition(xBar.x, xBar.y, xBar.width, xBar.height);
    ySlider.setPosition(yBar.x, yBar.y, yBar.width, yBar.height);
    // x-/yBorder is given the coordinates zero and the witdh of the visiable area for the scrollable container,
    // to ensure that the entire area where for the scrollable bars is and have been is invalidated correct.
    xBorder.x = 0;
    xBorder.width = rect.width;
    yBorder.height = rect.height;
    yBorder.y = 0;
    if (!xBorder.isEmpty())
    {
        invalidateRect(xBorder);
    }
    if (!yBorder.isEmpty())
    {
        invalidateRect(yBorder);
    }
}
References Drawable::getX(), ScrollableContainer::getXBorder(), ScrollableContainer::getXScrollbar(), Drawable::getY(), ScrollableContainer::getYBorder(), ScrollableContainer::getYScrollbar(), Rect::height, Drawable::invalidate(), Drawable::invalidateRect(), Drawable::rect, Drawable::setPosition(), Rect::width, ScrollableContainer::xSlider, and ScrollableContainer::ySlider.
Referenced by ScrollableContainer::childGeometryChanged(), ScrollableContainer::doScroll(), ScrollableContainer::handleClickEvent(), ScrollableContainer::reset(), and ScrollableContainer::setScrollbarsPermanentlyVisible().
isScrollableXY()
virtual void isScrollableXY (bool & scrollX, bool & scrollY) inline virtual
Is the ClickableContainer scrollable in either direction? Takes the width of the contained elements into account and also checks to see if horizontal or vertical scrolling is allowed.
Parameters
[out] scrollX True if the container is able to scroll horizontally.
[out] scrollY True if the container is able to scroll vertically.
See also
enableHorizontalScroll, enableVerticalScroll
    {
        Rect contained = getContainedArea();
        scrollX = (scrollableX && (rect.width < contained.width));
        scrollY = (scrollableY && (rect.height < contained.height));
    }
References ScrollableContainer::getContainedArea(), Rect::height, Drawable::rect, ScrollableContainer::scrollableX, ScrollableContainer::scrollableY, and Rect::width.
Referenced by ScrollableContainer::handleDragEvent(), and ScrollableContainer::handleGestureEvent().
moveChildrenRelative()
void moveChildrenRelative (int16_t deltaX, int16_t deltaY) virtual
Calls moveRelative on all children.
Parameters
deltaX Horizontal displacement.
deltaY Vertical displacement.
Note
Takes care not to move the scrollbars, which are also children.
This function is scheduled to be deprecated. Use doScroll() instead.
Reimplemented from Container.
{
    for (Drawable* d = firstChild; d; d = d->getNextSibling())
    {
        if ((d != &xSlider) && (d != &ySlider))
        {
            d->moveRelative(deltaX, deltaY);
        }
    }
    scrolledXDistance += deltaX;
    scrolledYDistance += deltaY;
}
References Container::firstChild, ScrollableContainer::scrolledXDistance, ScrollableContainer::scrolledYDistance, ScrollableContainer::xSlider, and ScrollableContainer::ySlider.
Referenced by ScrollableContainer::childGeometryChanged(), ScrollableContainer::doScroll(), and ScrollableContainer::reset().
reset()
void reset ()
Resets the ScrollableContainer to its original state, before the user started dragging the contents. This reset the x/y coordinates of children to the position they were in before the first drag event was received.
{
    moveChildrenRelative(-scrolledXDistance, -scrolledYDistance);
    invalidateScrollbars();
}
References ScrollableContainer::invalidateScrollbars(), ScrollableContainer::moveChildrenRelative(), ScrollableContainer::scrolledXDistance, and ScrollableContainer::scrolledYDistance.
setMaxVelocity()
void setMaxVelocity (uint16_t max) inline
Sets the maximum velocity of a scroll due to a swipe. This can be used to force smooth scrolling by limiting the speed of any swipe gesture.
Parameters
max The maximum velocity of the scroll.
See also
GestureEvent::getVelocity
    {
        maxVelocity = max;
    }
References ScrollableContainer::maxVelocity.
setScrollbarPadding()
void setScrollbarPadding (uint8_t padding)
Sets the amount of space between the scrollbar and the edge of the ScrollableContainer.
Parameters
padding The padding.
{
    scrollbarPadding = padding;
}
References ScrollableContainer::scrollbarPadding.
setScrollbarsAlpha()
void setScrollbarsAlpha (uint8_t alpha)
Sets the alpha value (transparency) of the scrollbars.
Parameters
alpha The alpha value. 255 being completely solid, 0 being completely invisible.
{
    scrollbarAlpha = alpha;
    xSlider.setAlpha(scrollbarAlpha);
    ySlider.setAlpha(scrollbarAlpha);
}
References ScrollableContainer::scrollbarAlpha, Box::setAlpha(), ScrollableContainer::xSlider, and ScrollableContainer::ySlider.
setScrollbarsColor()
void setScrollbarsColor (colortype color)
Sets the color of the scrollbars.
Parameters
color The color of the box.
{
    scrollbarColor = color;
    xSlider.setColor(scrollbarColor);
    ySlider.setColor(scrollbarColor);
}
References ScrollableContainer::scrollbarColor, Box::setColor(), ScrollableContainer::xSlider, and ScrollableContainer::ySlider.
setScrollbarsPermanentlyVisible()
void setScrollbarsPermanentlyVisible (bool permanentlyVisible = true)
Make scrollbars permanently visible regardless of the size and position of the children of the ScrollableContainer. Normally the scrollbars are hidden and only shown when dragging the contents of the ScrollableContainer (unless prohibited using setScrollbarsVisible()).
Parameters
permanentlyVisible (Optional) True to show the scrollbars permanently, false for default behavior.
See also
setScrollbarsVisible
{
    scrollbarsPermanentlyVisible = permanentlyVisible;
    xSlider.setVisible(true);
    ySlider.setVisible(true);
    invalidateScrollbars();
}
References ScrollableContainer::invalidateScrollbars(), ScrollableContainer::scrollbarsPermanentlyVisible, Drawable::setVisible(), ScrollableContainer::xSlider, and ScrollableContainer::ySlider.
setScrollbarsVisible()
void setScrollbarsVisible (bool newVisible)
Sets the visibility of the scrollbars, when the scrollable area is pressed. By default the scrollbars are hidden, but shown when the contents of the ScrollableContainer is being dragged around. Using setScrollbarsVisible, it is possible to hide the scrollbars when dragging the contents.
Parameters
newVisible If true (default), the scrollbars are visible when scrollable area is pressed. If false, scrollbars are always hidden.
See also
setScrollbarsPermanentlyVisible
{
    scrollbarsVisible = newVisible;
}
References ScrollableContainer::scrollbarsVisible.
setScrollbarWidth()
void setScrollbarWidth (uint8_t width)
Sets the width of the scrollbar measured in pixels.
Parameters
width The width of the scrollbar.
{
    scrollbarWidth = width;
}
References ScrollableContainer::scrollbarWidth.
setScrollDurationSlowdown()
void setScrollDurationSlowdown (uint16_t slowdown)
Sets scroll duration speedup divisor. Default value is 1.
Parameters
slowdown The scroll duration speedup divisor.
See also
setScrollDurationSpeedup, getScrollDurationSlowdown
{
    scrollDurationSlowdown = MAX(1, slowdown);
}
References MAX, and ScrollableContainer::scrollDurationSlowdown.
setScrollDurationSpeedup()
void setScrollDurationSpeedup (uint16_t speedup)
Sets scroll duration speedup multiplier. Default value is 7 which gives a nice speedup on gestures.
Parameters
speedup The scroll duration speedup multiplier.
See also
getScrollDurationSpeedup, setScrollDurationSlowdown
{
    scrollDurationSpeedup = MAX(1, speedup);
}
References MAX, and ScrollableContainer::scrollDurationSpeedup.
setScrollThreshold()
void setScrollThreshold (int16_t t) inline
Change the threshold which the first drag event received must exceed before initiating a scroll. This can be used to avoid touching the screen and moving the finger only a few pixels resulting in the contents being scrolled.
Parameters
t The new threshold value.
Note
All subsequent scrolls will be processed regardless of threshold value until a ClickEvent::RELEASED is received.
    {
        scrollThreshold = t;
    }
References ScrollableContainer::scrollThreshold.
Member Data Documentation
accelDirection
GestureEvent::GestureEventType accelDirection protected
The current direction (horizontal or vertical) of scroll.
Referenced by ScrollableContainer::handleGestureEvent(), and ScrollableContainer::handleTickEvent().
animate
bool animate protected
Is scroll animation currently active.
Referenced by ScrollableContainer::handleClickEvent(), ScrollableContainer::handleGestureEvent(), and ScrollableContainer::handleTickEvent().
animationCounter
uint16_t animationCounter protected
Current step/tick in scroll animation.
Referenced by ScrollableContainer::handleClickEvent(), and ScrollableContainer::handleTickEvent().
beginningValue
int16_t beginningValue protected
Initial X or Y for calculated values in scroll animation.
Referenced by ScrollableContainer::handleGestureEvent(), and ScrollableContainer::handleTickEvent().
fingerAdjustmentX
int16_t fingerAdjustmentX protected
How much should the finger be adjusted horizontally.
Referenced by ScrollableContainer::handleClickEvent(), and ScrollableContainer::handleDragEvent().
fingerAdjustmentY
int16_t fingerAdjustmentY protected
and how much vertically
Referenced by ScrollableContainer::handleClickEvent(), and ScrollableContainer::handleDragEvent().
hasIssuedCancelEvent
bool hasIssuedCancelEvent protected
true if the pressed drawable has received cancel event
Referenced by ScrollableContainer::handleClickEvent(), ScrollableContainer::handleDragEvent(), and ScrollableContainer::handleGestureEvent().
isPressed
bool isPressed protected
Is the container currently pressed (maybe show scrollbars)
Referenced by ScrollableContainer::handleClickEvent().
isScrolling
bool isScrolling protected
Is the container scrolling (i.e. has overcome the initial larger drag that is required to initiate a scroll).
Referenced by ScrollableContainer::handleClickEvent(), and ScrollableContainer::handleDragEvent().
lastDraggableChild
Drawable* lastDraggableChild protected
The drawable child of this container which should receive drag events. Note that only drag events in directions which cannot be scrolled by this ScrollableContainer will be forwarded to children.
Referenced by ScrollableContainer::handleClickEvent().
maxVelocity
uint16_t maxVelocity protected
The maximum velocity of a scroll (due to a swipe)
Referenced by ScrollableContainer::handleGestureEvent(), and ScrollableContainer::setMaxVelocity().
pressedDrawable
Drawable* pressedDrawable protected
The drawable child of this container which received the last ClickEvent::PRESSED notification. When scrolling, send this drawable a CANCEL event if the new x/y coords no longer matches this drawable.
Referenced by ScrollableContainer::handleClickEvent(), ScrollableContainer::handleDragEvent(), and ScrollableContainer::handleGestureEvent().
pressedX
int16_t pressedX protected
The x coordinate where the last ClickEvent::PRESSED was received.
Referenced by ScrollableContainer::handleClickEvent(), and ScrollableContainer::handleDragEvent().
pressedY
int16_t pressedY protected
The y coordinate where the last ClickEvent::PRESSED was received.
Referenced by ScrollableContainer::handleClickEvent(), and ScrollableContainer::handleDragEvent().
scrollableX
bool scrollableX protected
Is the container scrollable in the horizontal direction.
Referenced by ScrollableContainer::enableHorizontalScroll(), ScrollableContainer::getXScrollbar(), ScrollableContainer::getYScrollbar(), ScrollableContainer::handleDragEvent(), and ScrollableContainer::isScrollableXY().
scrollableY
bool scrollableY protected
Is the container scrollable in the vertical direction.
Referenced by ScrollableContainer::enableVerticalScroll(), ScrollableContainer::getXScrollbar(), ScrollableContainer::getYScrollbar(), ScrollableContainer::handleDragEvent(), and ScrollableContainer::isScrollableXY().
SCROLLBAR_LINE
const uint8_t SCROLLBAR_LINE = 0 static protected
The scrollbar line.
Referenced by ScrollableContainer::getXBorder(), ScrollableContainer::getXScrollbar(), ScrollableContainer::getYBorder(), and ScrollableContainer::getYScrollbar().
SCROLLBAR_MAX_VELOCITY
const uint16_t SCROLLBAR_MAX_VELOCITY = 17 static protected
The (default) maximum velocity of a scroll due to a swipe.
SCROLLBAR_MIN_VELOCITY
const uint16_t SCROLLBAR_MIN_VELOCITY = 5 static protected
The minimum velocity of a scroll due to a swipe.
Referenced by ScrollableContainer::handleGestureEvent().
scrollbarAlpha
uint8_t scrollbarAlpha protected
The scrollbar is semitransparent.
Referenced by ScrollableContainer::setScrollbarsAlpha().
scrollbarColor
colortype scrollbarColor protected
The color of the scrollbar.
Referenced by ScrollableContainer::setScrollbarsColor().
scrollbarPadding
uint8_t scrollbarPadding protected
The amount of padding. The scrollbar will have a bit of space to the borders of the container.
Referenced by ScrollableContainer::getXBorder(), ScrollableContainer::getXScrollbar(), ScrollableContainer::getYBorder(), ScrollableContainer::getYScrollbar(), and ScrollableContainer::setScrollbarPadding().
scrollbarsPermanentlyVisible
bool scrollbarsPermanentlyVisible protected
Are scrollbars always visible.
Referenced by ScrollableContainer::handleClickEvent(), and ScrollableContainer::setScrollbarsPermanentlyVisible().
scrollbarsVisible
bool scrollbarsVisible protected
Are scrollbars visible.
Referenced by ScrollableContainer::handleClickEvent(), and ScrollableContainer::setScrollbarsVisible().
scrollbarWidth
uint8_t scrollbarWidth protected
The width of the scrollbar.
Referenced by ScrollableContainer::getXBorder(), ScrollableContainer::getXScrollbar(), ScrollableContainer::getYBorder(), ScrollableContainer::getYScrollbar(), and ScrollableContainer::setScrollbarWidth().
scrollDuration
uint16_t scrollDuration protected
Number of ticks the scroll animation should use.
Referenced by ScrollableContainer::handleGestureEvent(), and ScrollableContainer::handleTickEvent().
scrollDurationSlowdown
uint16_t scrollDurationSlowdown protected
The scroll durations is divided by this number.
Referenced by ScrollableContainer::getScrollDurationSlowdown(), ScrollableContainer::handleGestureEvent(), and ScrollableContainer::setScrollDurationSlowdown().
scrollDurationSpeedup
uint16_t scrollDurationSpeedup protected
The scroll durations is multipled by this number.
Referenced by ScrollableContainer::getScrollDurationSpeedup(), ScrollableContainer::handleGestureEvent(), and ScrollableContainer::setScrollDurationSpeedup().
scrolledXDistance
int16_t scrolledXDistance protected
The scrolled horizontal distance.
Referenced by ScrollableContainer::getScrolledX(), ScrollableContainer::moveChildrenRelative(), and ScrollableContainer::reset().
scrolledYDistance
int16_t scrolledYDistance protected
The scrolled vertical distance.
Referenced by ScrollableContainer::getScrolledY(), ScrollableContainer::moveChildrenRelative(), and ScrollableContainer::reset().
scrollThreshold
int16_t scrollThreshold protected
The threshold which the first drag event received must exceed before scrolling. Default is 5.
Referenced by ScrollableContainer::handleDragEvent(), ScrollableContainer::handleGestureEvent(), and ScrollableContainer::setScrollThreshold().
targetValue
int16_t targetValue protected
Target X or Y value for scroll animation.
Referenced by ScrollableContainer::handleGestureEvent(), and ScrollableContainer::handleTickEvent().
xSlider
Box xSlider protected
The horizontal scrollbar drawable.
Referenced by ScrollableContainer::ScrollableContainer(), ScrollableContainer::add(), ScrollableContainer::getChildrenContainedArea(), ScrollableContainer::handleClickEvent(), ScrollableContainer::invalidateScrollbars(), ScrollableContainer::moveChildrenRelative(), ScrollableContainer::setScrollbarsAlpha(), ScrollableContainer::setScrollbarsColor(), and ScrollableContainer::setScrollbarsPermanentlyVisible().
ySlider
Box ySlider protected
The vertical scrollbar drawable.
Referenced by ScrollableContainer::ScrollableContainer(), ScrollableContainer::add(), ScrollableContainer::getChildrenContainedArea(), ScrollableContainer::handleClickEvent(), ScrollableContainer::invalidateScrollbars(), ScrollableContainer::moveChildrenRelative(), ScrollableContainer::setScrollbarsAlpha(), ScrollableContainer::setScrollbarsColor(), and ScrollableContainer::setScrollbarsPermanentlyVisible().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/ScrollableContainer.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/ScrollableContainer.cpp