Battery Simulator Documentation: GraphElementHistogram
GraphElementHistogram
#include "GraphElements.hpp"
Public Member Functions
GraphElementHistogram ()
virtual void draw (const Rect &invalidatedArea) const
FORCE_INLINE_FUNCTION int16_t getBarOffset () const
FORCE_INLINE_FUNCTION uint16_t getBarWidth () const
FORCE_INLINE_FUNCTION float getBaselineAsFloat () const
FORCE_INLINE_FUNCTION int getBaselineAsInt () const
FORCE_INLINE_FUNCTION int getBaselineScaled () const
FORCE_INLINE_FUNCTION int getScale () const
virtual void invalidateGraphPointAt (int16_t index)
FORCE_INLINE_FUNCTION void setBarOffset (int16_t offset)
FORCE_INLINE_FUNCTION void setBarWidth (uint16_t width)
FORCE_INLINE_FUNCTION void setBaseline (float baseline)
FORCE_INLINE_FUNCTION void setBaseline (int baseline)
FORCE_INLINE_FUNCTION void setBaselineScaled (int baseline)
FORCE_INLINE_FUNCTION void setScale (int scale)
Public Member Functions inherited from AbstractGraphElementNoCWR
AbstractGraphElementNoCWR ()
virtual bool drawCanvasWidget (const Rect &) const
virtual colortype getColor () const
virtual void setColor (colortype newColor)
Public Member Functions inherited from AbstractGraphElement
AbstractGraphElement ()
Public Member Functions inherited from CanvasWidget
CanvasWidget ()
virtual uint8_t getAlpha () const
virtual Rect getMinimalRect () const
const AbstractPainter * getPainter () const
virtual Rect getSolidRect () const
virtual void invalidate () const
virtual void setAlpha (uint8_t newAlpha)
void setPainter (const AbstractPainter &painter)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
int16_t barOffset
The horizontal bar offset.
uint16_t barWidth
Width of each bar.
int dataScale
The scaling factor.
int yBaseline
The baseline.
Protected Attributes inherited from AbstractGraphElementNoCWR
colortype color
The currently assigned color.
Protected Attributes inherited from CanvasWidget
uint8_t alpha
The Alpha for this CanvasWidget.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Protected Member Functions inherited from AbstractGraphElementNoCWR
void normalizeRect (Rect &r) const
Protected Member Functions inherited from AbstractGraphElement
FORCE_INLINE_FUNCTION int convertToGraphScaleX (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION int convertToGraphScaleY (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION AbstractDataGraph * getGraph () const
FORCE_INLINE_FUNCTION int getIndexToXAxis (const AbstractDataGraph *graph, const int valueScaled, const int labelScaled) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenXQ5 (const AbstractDataGraph *graph, int16_t index) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenYQ5 (const AbstractDataGraph *graph, int16_t index) const
bool isCenterInvisible (const AbstractDataGraph *graph, int16_t index) const
Rect rectAround (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5, CWRUtil::Q5 diameterQ5) const
Rect rectFromQ5Coordinates (CWRUtil::Q5 screenXminQ5, CWRUtil::Q5 screenYminQ5, CWRUtil::Q5 screenXmaxQ5, CWRUtil::Q5 screenYmaxQ5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 roundQ5 (CWRUtil::Q5 q5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenXQ5 (const AbstractDataGraph *graph, int x) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenYQ5 (const AbstractDataGraph *graph, int y) const
FORCE_INLINE_FUNCTION bool xScreenRangeToIndexRange (const AbstractDataGraph *graph, int16_t xMin, int16_t xMax, int16_t &indexMin, int16_t &indexMax) const
Detailed Description
The GraphElementHistogram is used to draw blocks from the x axis to the data point in the graph. If more graphs are placed on top of each other, the histogram can be moved slightly to the left/right.
Note
Historgram boxes are drawn using LCD::fillRect for higher performance.
Constructor & Destructor Documentation
GraphElementHistogram()
GraphElementHistogram () inline
        : dataScale(1), yBaseline(0), barWidth(2), barOffset(0)
    {
    }
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draws the given invalidated area. If the underlying CanvasWidgetRenderer fail to render the widget (if the widget is too complex), the invalidated area is cut into smaller slices (horizontally) which are then drawn separately. If drawing a single raster line fails, that line is considered too complex and skipped (it is left blank/transparent) and drawing continues on the next raster line.
If drawing has failed at least once, which means that the number of horizontal lines draw has been reduced, the number of successfully drawn horizontal lines is remembered for the next invocation of draw(). A future call to draw() would then start off with the reduced number of horizontal lines to prevent potentially drawing the canvas widget in vain, as happened previously in draw().
Parameters
invalidatedArea The invalidated area.
See also
drawCanvasWidget
Note
Subclasses of CanvasWidget should implement drawCanvasWidget(), not draw().
The term "too complex" means that the size of the buffer (assigned to CanvasWidgetRenderer using CanvasWidgetRenderer::setupBuffer()) is too small.
Reimplemented from CanvasWidget.
{
    const AbstractDataGraph* graph = getGraph();
    const uint8_t a = LCD::div255(getAlpha() * graph->getAlpha());
    if (graph->getUsedCapacity() == 0 || barWidth == 0 || a == 0)
    {
        return; // Nothing to draw, everything is fine!
    }
    const int baseline = convertToGraphScaleY(graph, yBaseline, dataScale);
    const CWRUtil::Q5 barOffsetQ5 = CWRUtil::toQ5(barOffset);
    const CWRUtil::Q5 barWidthQ5 = CWRUtil::toQ5(barWidth);
    const CWRUtil::Q5 barWidthHalfQ5 = CWRUtil::Q5(((int)barWidthQ5 + 1) / 2);
    const int16_t barWidthHalf = barWidthHalfQ5.ceil();
    const int16_t screenYzero = valueToScreenYQ5(graph, baseline).round();
    int16_t indexMin;
    int16_t indexMax;
    if (!xScreenRangeToIndexRange(graph, invalidatedArea.x + barOffset - barWidthHalf, invalidatedArea.right() + barOffset + barWidthHalf, indexMin, indexMax))
    {
        return; // Nothing to draw, everything is fine!
    }
    const Rect invalidRect = Rect(0, graph->getGraphAreaPaddingTop(), graph->getGraphAreaWidthIncludingPadding(), graph->getGraphAreaHeight()) & invalidatedArea;
    for (int16_t index = indexMin; index <= indexMax; index++)
    {
        const int16_t screenX = (indexToScreenXQ5(graph, index) + barOffsetQ5 - barWidthHalfQ5).round();
        const int16_t screenY = indexToScreenYQ5(graph, index).round();
        Rect r(screenX, screenY, barWidth, screenYzero - screenY);
        normalizeRect(r);
        r &= invalidRect;
        if (!r.isEmpty())
        {
            translateRectToAbsolute(r);
            HAL::lcd().fillRect(r, color, a);
        }
    }
}
References GraphElementHistogram::barOffset, GraphElementHistogram::barWidth, AbstractGraphElement::convertToGraphScaleY(), GraphElementHistogram::dataScale, LCD::div255(), CanvasWidget::getAlpha(), AbstractGraphElement::getGraph(), AbstractGraphElement::indexToScreenXQ5(), AbstractGraphElement::indexToScreenYQ5(), HAL::lcd(), AbstractGraphElementNoCWR::normalizeRect(), CWRUtil::Q5::round(), CWRUtil::toQ5(), Drawable::translateRectToAbsolute(), AbstractGraphElement::valueToScreenYQ5(), AbstractGraphElement::xScreenRangeToIndexRange(), and GraphElementHistogram::yBaseline.
getBarOffset()
FORCE_INLINE_FUNCTION int16_t getBarOffset () const inline
Gets bar offset (horizontally). Bar offset can be used when there are two different histogram graphs on top of each other to prevent one histogram from covering the other.
Returns
The bar offset.
See also
setBarOffset
    {
        return barOffset;
    }
References GraphElementHistogram::barOffset.
getBarWidth()
FORCE_INLINE_FUNCTION uint16_t getBarWidth () const inline
Gets bar width of the histogram columns.
Returns
The bar width.
See also
setBarWidth
    {
        return barWidth;
    }
References GraphElementHistogram::barWidth.
getBaselineAsFloat()
FORCE_INLINE_FUNCTION float getBaselineAsFloat () const inline
Gets the base previously set using setBaseline.
Returns
The base value.
See also
setBaseline
    {
        return AbstractDataGraph::scaled2float(getBaselineScaled(), dataScale);
    }
References GraphElementHistogram::dataScale, GraphElementHistogram::getBaselineScaled(), and AbstractDataGraph::scaled2float().
getBaselineAsInt()
FORCE_INLINE_FUNCTION int getBaselineAsInt () const inline
Gets the base previously set using setBaseline.
Returns
The base value.
See also
setBaseline
    {
        return AbstractDataGraph::scaled2int(getBaselineScaled(), dataScale);
    }
References GraphElementHistogram::dataScale, GraphElementHistogram::getBaselineScaled(), and AbstractDataGraph::scaled2int().
getBaselineScaled()
FORCE_INLINE_FUNCTION int getBaselineScaled () const inline
Gets the base previously set using setBaseline.
Returns
The base value.
See also
setBaseline
Note
The baseline returned here is left unscaled.
    {
        return yBaseline;
    }
References GraphElementHistogram::yBaseline.
Referenced by GraphElementHistogram::getBaselineAsFloat(), and GraphElementHistogram::getBaselineAsInt().
getScale()
FORCE_INLINE_FUNCTION int getScale () const inline
Gets the scaling factor set using setScale.
Returns
The scaling factor.
See also
setScale
    {
        return dataScale;
    }
References GraphElementHistogram::dataScale.
invalidateGraphPointAt()
void invalidateGraphPointAt (int16_t index) virtual
Invalidate the point at the given index. This allows a graph element to only invalidate the minimum rectangle required for the given index. The Graph will call this function before and after changing a point to ensure that both the old and the new area are redrawn (invalidated).
Parameters
index Zero-based index of the point.
Implements AbstractGraphElement.
{
    const AbstractDataGraph* graph = getGraph();
    const CWRUtil::Q5 screenXQ5 = indexToScreenXQ5(graph, index);
    const CWRUtil::Q5 barWidthHalfQ5 = CWRUtil::Q5((int)CWRUtil::toQ5(barWidth) + 1) / 2;
    const CWRUtil::Q5 barOffsetQ5 = CWRUtil::toQ5(barOffset);
    const int baseline = convertToGraphScaleY(graph, yBaseline, dataScale);
    Rect dirty(rectFromQ5Coordinates(screenXQ5 + barOffsetQ5 - barWidthHalfQ5, indexToScreenYQ5(graph, index), screenXQ5 + barOffsetQ5 + barWidthHalfQ5, valueToScreenYQ5(graph, baseline)));
    dirty &= Rect(0, graph->getGraphAreaPaddingTop(), graph->getGraphAreaWidthIncludingPadding(), graph->getGraphAreaHeight());
    invalidateRect(dirty);
}
References GraphElementHistogram::barOffset, GraphElementHistogram::barWidth, AbstractGraphElement::convertToGraphScaleY(), GraphElementHistogram::dataScale, touchgfx::dirty, AbstractGraphElement::getGraph(), AbstractGraphElement::indexToScreenXQ5(), AbstractGraphElement::indexToScreenYQ5(), Drawable::invalidateRect(), AbstractGraphElement::rectFromQ5Coordinates(), CWRUtil::toQ5(), AbstractGraphElement::valueToScreenYQ5(), and GraphElementHistogram::yBaseline.
setBarOffset()
FORCE_INLINE_FUNCTION void setBarOffset (int16_t offset) inline
Sets bar offset (horizontally) in pixels. This can be used when there are two different histogram graphs on top of each other to prevent one histogram from covering the other.
Parameters
offset The offset.
See also
getBarOffset
    {
        barOffset = offset;
    }
References GraphElementHistogram::barOffset.
setBarWidth()
FORCE_INLINE_FUNCTION void setBarWidth (uint16_t width) inline
Sets bar width of each histogram column in pixels.
Parameters
width The width.
See also
getBarWidth
    {
        barWidth = width;
    }
References GraphElementHistogram::barWidth.
setBaseline() [1/2]
FORCE_INLINE_FUNCTION void setBaseline (float baseline) inline
Sets the base of the area drawn. Normally, the base is 0 which means that the area is drawn below positive y values and above negative y values. Setting the base to a very high number will cause the area above the graph to be drawn. Setting the base to a very low number will cause the area below the graph to be drawn (even for negative numbers, which are higher than the base value).
Parameters
baseline The base value.
See also
getBaselineAsInt, getBaselineAsFloat
    {
        setBaselineScaled(AbstractDataGraph::float2scaled(baseline, dataScale));
    }
References GraphElementHistogram::dataScale, AbstractDataGraph::float2scaled(), and GraphElementHistogram::setBaselineScaled().
setBaseline() [2/2]
FORCE_INLINE_FUNCTION void setBaseline (int baseline) inline
Sets the base of the area drawn. Normally, the base is 0 which means that the area is drawn below positive y values and above negative y values. Setting the base to a very high number will cause the area above the graph to be drawn. Setting the base to a very low number will cause the area below the graph to be drawn (even for negative numbers, which are higher than the base value).
Parameters
baseline The base value.
See also
getBaselineAsInt, getBaselineAsFloat
    {
        setBaselineScaled(baseline * dataScale);
    }
References GraphElementHistogram::dataScale, and GraphElementHistogram::setBaselineScaled().
setBaselineScaled()
FORCE_INLINE_FUNCTION void setBaselineScaled (int baseline) inline
Sets the base of the area drawn. Normally, the base is 0 which means that the area is drawn below positive y values and above negative y values. Setting the base to a very high number will cause the area above the graph to be drawn. Setting the base to a very low number will cause the area below the graph to be drawn (even for negative numbers, which are higher than the base value).
Parameters
baseline The base value.
See also
getBaselineAsInt, getBaselineAsFloat
Note
The baseline set here must already be scaled.
    {
        yBaseline = baseline;
    }
References GraphElementHistogram::yBaseline.
Referenced by GraphElementHistogram::setBaseline(), and GraphElementHistogram::setBaseline().
setScale()
FORCE_INLINE_FUNCTION void setScale (int scale) inline
Sets a scaling factor to be multiplied on the baseline. Any already set baseline will be updated to the new correctly scaled value. To avoid this, use setBaselineScaled() after setting scale.
Parameters
scale The scaling factor.
See also
getScale
    {
        assert(scale != 0);
        yBaseline = AbstractDataGraph::convertToNewScale(yBaseline, dataScale, scale);
        dataScale = scale;
    }
References AbstractDataGraph::convertToNewScale(), GraphElementHistogram::dataScale, and GraphElementHistogram::yBaseline.
Member Data Documentation
barOffset
int16_t barOffset protected
The horizontal bar offset.
Referenced by GraphElementHistogram::draw(), GraphElementHistogram::getBarOffset(), GraphElementHistogram::invalidateGraphPointAt(), and GraphElementHistogram::setBarOffset().
barWidth
uint16_t barWidth protected
Width of each bar.
Referenced by GraphElementHistogram::draw(), GraphElementHistogram::getBarWidth(), GraphElementHistogram::invalidateGraphPointAt(), and GraphElementHistogram::setBarWidth().
dataScale
int dataScale protected
The scaling factor.
Referenced by GraphElementHistogram::draw(), GraphElementHistogram::getBaselineAsFloat(), GraphElementHistogram::getBaselineAsInt(), GraphElementHistogram::getScale(), GraphElementHistogram::invalidateGraphPointAt(), GraphElementHistogram::setBaseline(), GraphElementHistogram::setBaseline(), and GraphElementHistogram::setScale().
yBaseline
int yBaseline protected
The baseline.
Referenced by GraphElementHistogram::draw(), GraphElementHistogram::getBaselineScaled(), GraphElementHistogram::invalidateGraphPointAt(), GraphElementHistogram::setBaselineScaled(), and GraphElementHistogram::setScale().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/graph/GraphElements.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph/GraphElements.cpp