Battery Simulator Documentation: GraphElementDiamonds
GraphElementDiamonds
#include "GraphElements.hpp"
Public Member Functions
GraphElementDiamonds ()
virtual bool drawCanvasWidget (const Rect &invalidatedArea) const
FORCE_INLINE_FUNCTION uint8_t getDiamondWidth () const
virtual void invalidateGraphPointAt (int16_t index)
FORCE_INLINE_FUNCTION void setDiamondWidth (uint8_t width)
Public Member Functions inherited from AbstractGraphElement
AbstractGraphElement ()
Public Member Functions inherited from CanvasWidget
CanvasWidget ()
virtual void draw (const Rect &invalidatedArea) const
virtual uint8_t getAlpha () const
virtual Rect getMinimalRect () const
const AbstractPainter * getPainter () const
virtual Rect getSolidRect () const
virtual void invalidate () const
virtual void setAlpha (uint8_t newAlpha)
void setPainter (const AbstractPainter &painter)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
uint8_t diamondWidth
Width of the diamond.
Protected Attributes inherited from CanvasWidget
uint8_t alpha
The Alpha for this CanvasWidget.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Protected Member Functions inherited from AbstractGraphElement
FORCE_INLINE_FUNCTION int convertToGraphScaleX (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION int convertToGraphScaleY (const AbstractDataGraph *graph, int value, int scale) const
FORCE_INLINE_FUNCTION AbstractDataGraph * getGraph () const
FORCE_INLINE_FUNCTION int getIndexToXAxis (const AbstractDataGraph *graph, const int valueScaled, const int labelScaled) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenXQ5 (const AbstractDataGraph *graph, int16_t index) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 indexToScreenYQ5 (const AbstractDataGraph *graph, int16_t index) const
bool isCenterInvisible (const AbstractDataGraph *graph, int16_t index) const
Rect rectAround (CWRUtil::Q5 xQ5, CWRUtil::Q5 yQ5, CWRUtil::Q5 diameterQ5) const
Rect rectFromQ5Coordinates (CWRUtil::Q5 screenXminQ5, CWRUtil::Q5 screenYminQ5, CWRUtil::Q5 screenXmaxQ5, CWRUtil::Q5 screenYmaxQ5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 roundQ5 (CWRUtil::Q5 q5) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenXQ5 (const AbstractDataGraph *graph, int x) const
FORCE_INLINE_FUNCTION CWRUtil::Q5 valueToScreenYQ5 (const AbstractDataGraph *graph, int y) const
FORCE_INLINE_FUNCTION bool xScreenRangeToIndexRange (const AbstractDataGraph *graph, int16_t xMin, int16_t xMax, int16_t &indexMin, int16_t &indexMax) const
Detailed Description
GraphElementDiamonds will draw a diamond (a square with the corners up/down/left/right) for every data point in graph.
Note
The Diamonds are drawn using Canvas Widget Renderer which is slower but produces much nicer graphics.
Constructor & Destructor Documentation
GraphElementDiamonds()
GraphElementDiamonds () inline
        : diamondWidth(2)
    {
    }
Member Function Documentation
drawCanvasWidget()
bool drawCanvasWidget (const Rect & invalidatedArea) const virtual
Draw canvas widget for the given invalidated area. Similar to draw(), but might be invoked several times with increasingly smaller areas to due to memory constraints from the underlying CanvasWidgetRenderer.
Parameters
invalidatedArea The invalidated area.
Returns
true if the widget was drawn properly, false if not.
See also
draw
Implements CanvasWidget.
{
    const AbstractDataGraph* graph = getGraph();
    if (graph->getUsedCapacity() == 0)
    {
        return true; // Nothing to draw, everything is fine!
    }
    const CWRUtil::Q5 diamondWidthQ5 = CWRUtil::toQ5(diamondWidth);
    const CWRUtil::Q5 dotWidthHalfQ5 = diamondWidthQ5 / 2;
    const uint16_t dotWidthHalf = CWRUtil::Q5(((int)diamondWidthQ5 + 1) / 2).ceil(); // Round up
    int16_t indexMin;
    int16_t indexMax;
    if (!xScreenRangeToIndexRange(graph, invalidatedArea.x - dotWidthHalf, invalidatedArea.right() + dotWidthHalf, indexMin, indexMax))
    {
        return true;
    }
    Canvas canvas(getPainter(), getAbsoluteRect(), invalidatedArea, getAlpha());
    for (int16_t index = indexMin; index <= indexMax; index++)
    {
        if (isCenterInvisible(graph, index))
        {
            continue;
        }
        const CWRUtil::Q5 screenXcenterQ5 = roundQ5(indexToScreenXQ5(graph, index));
        const CWRUtil::Q5 screenYcenterQ5 = roundQ5(indexToScreenYQ5(graph, index));
        const Rect dirty(rectAround(screenXcenterQ5, screenYcenterQ5, diamondWidthQ5) & invalidatedArea);
        if (!dirty.isEmpty())
        {
            canvas.moveTo(screenXcenterQ5 - dotWidthHalfQ5, screenYcenterQ5);
            canvas.lineTo(screenXcenterQ5, screenYcenterQ5 - dotWidthHalfQ5);
            canvas.lineTo(screenXcenterQ5 + dotWidthHalfQ5, screenYcenterQ5);
            canvas.lineTo(screenXcenterQ5, screenYcenterQ5 + dotWidthHalfQ5);
        }
    }
    return canvas.render(graph->getAlpha());
}
References CWRUtil::Q5::ceil(), GraphElementDiamonds::diamondWidth, touchgfx::dirty, Drawable::getAbsoluteRect(), CanvasWidget::getAlpha(), AbstractGraphElement::getGraph(), CanvasWidget::getPainter(), AbstractGraphElement::indexToScreenXQ5(), AbstractGraphElement::indexToScreenYQ5(), AbstractGraphElement::isCenterInvisible(), AbstractGraphElement::rectAround(), AbstractGraphElement::roundQ5(), CWRUtil::toQ5(), and AbstractGraphElement::xScreenRangeToIndexRange().
getDiamondWidth()
FORCE_INLINE_FUNCTION uint8_t getDiamondWidth () const inline
Gets diamond width.
Returns
The diamond width.
See also
setDiamondWidth
    {
        return diamondWidth;
    }
References GraphElementDiamonds::diamondWidth.
invalidateGraphPointAt()
void invalidateGraphPointAt (int16_t index) virtual
Invalidate the point at the given index. This allows a graph element to only invalidate the minimum rectangle required for the given index. The Graph will call this function before and after changing a point to ensure that both the old and the new area are redrawn (invalidated).
Parameters
index Zero-based index of the point.
Implements AbstractGraphElement.
{
    const AbstractDataGraph* graph = getGraph();
    if (isCenterInvisible(graph, index))
    {
        return;
    }
    Rect dirty(rectAround(indexToScreenXQ5(graph, index), indexToScreenYQ5(graph, index), CWRUtil::toQ5(diamondWidth)));
    invalidateRect(dirty);
}
References GraphElementDiamonds::diamondWidth, touchgfx::dirty, AbstractGraphElement::getGraph(), AbstractGraphElement::indexToScreenXQ5(), AbstractGraphElement::indexToScreenYQ5(), Drawable::invalidateRect(), AbstractGraphElement::isCenterInvisible(), AbstractGraphElement::rectAround(), and CWRUtil::toQ5().
setDiamondWidth()
FORCE_INLINE_FUNCTION void setDiamondWidth (uint8_t width) inline
Sets diamond width.
Parameters
width The width.
See also
getDiamondWidth
    {
        diamondWidth = width;
    }
References GraphElementDiamonds::diamondWidth.
Member Data Documentation
diamondWidth
uint8_t diamondWidth protected
Width of the diamond.
Referenced by GraphElementDiamonds::drawCanvasWidget(), GraphElementDiamonds::getDiamondWidth(), GraphElementDiamonds::invalidateGraphPointAt(), and GraphElementDiamonds::setDiamondWidth().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/graph/GraphElements.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph/GraphElements.cpp