Battery Simulator Documentation: LineProgress
LineProgress
#include "LineProgress.hpp"
Public Member Functions
LineProgress ()
virtual void getEnd (int &x, int &y) const
virtual Line::LINE_ENDING_STYLE getLineEndingStyle () const
virtual int getLineWidth () const
virtual void getStart (int &x, int &y) const
virtual void setAlpha (uint8_t newAlpha)
virtual void setEnd (int x, int y)
virtual void setLineEndingStyle (Line::LINE_ENDING_STYLE lineEndingStyle)
virtual void setLineWidth (int width)
virtual void setPainter (AbstractPainter &painter)
virtual void setProgressIndicatorPosition (int16_t x, int16_t y, int16_t width, int16_t height)
virtual void setStart (int x, int y)
virtual void setValue (int value)
Public Member Functions inherited from AbstractProgressIndicator
AbstractProgressIndicator ()
virtual uint8_t getAlpha () const
virtual uint16_t getProgress (uint16_t range=100) const
virtual int16_t getProgressIndicatorHeight () const
virtual int16_t getProgressIndicatorWidth () const
virtual int16_t getProgressIndicatorX () const
virtual int16_t getProgressIndicatorY () const
virtual void getRange (int &min, int &max) const
virtual void getRange (int &min, int &max, uint16_t &steps) const
virtual void getRange (int &min, int &max, uint16_t &steps, uint16_t &minStep) const
virtual int getValue () const
virtual void handleTickEvent ()
virtual void invalidateContent () const
virtual void setBackground (const Bitmap &bitmapBackground)
virtual void setEasingEquation (EasingEquation easingEquation)
virtual void setRange (int min, int max, uint16_t steps=0, uint16_t minStep=0)
void setValueSetAction (GenericCallback< const AbstractProgressIndicator & > &callback)
void setValueUpdatedAction (GenericCallback< const AbstractProgressIndicator & > &callback)
virtual void updateValue (int value, uint16_t duration)
Public Member Functions inherited from Container
Container ()
virtual void add (Drawable &d)
virtual bool contains (const Drawable &d)
virtual void draw (const Rect &invalidatedArea) const
virtual void forEachChild (GenericCallback< Drawable & > *function)
virtual Drawable * getFirstChild ()
virtual void getLastChild (int16_t x, int16_t y, Drawable **last)
virtual void getLastChildNear (int16_t x, int16_t y, Drawable **last, int16_t *fingerAdjustmentX, int16_t *fingerAdjustmentY)
virtual Rect getSolidRect () const
virtual void insert (Drawable *previous, Drawable &d)
virtual void remove (Drawable &d)
virtual void removeAll ()
virtual void unlink ()
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleClickEvent (const ClickEvent &event)
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
CWRUtil::Q5 endX
The end x coordinate.
CWRUtil::Q5 endY
The end y coordinate.
Line line
The line.
CWRUtil::Q5 startX
The start x coordinate.
CWRUtil::Q5 startY
The start y coordinate.
Protected Attributes inherited from AbstractProgressIndicator
int animationDuration
Duration of the animation.
int animationEndValue
The animation end value.
bool animationRunning
Is the animation running.
int animationStartValue
The animation start value.
int animationStep
The current animation step.
Image background
The background image.
int currentValue
The current value.
EasingEquation equation
The equation used in updateValue()
Container progressIndicatorContainer
The container that holds the actual progress indicator.
int rangeMax
The range maximum.
int rangeMin
The range minimum.
uint16_t rangeSteps
The range steps.
uint16_t rangeStepsMin
The range steps minimum.
GenericCallback< const AbstractProgressIndicator & > * valueSetCallback
New value assigned Callback.
GenericCallback< const AbstractProgressIndicator & > * valueUpdatedCallback
Animation ended Callback.
Protected Attributes inherited from Container
Drawable * firstChild
Pointer to the first child of this container. Subsequent children can be found through firstChild's nextSibling.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Additional Inherited Members
Protected Member Functions inherited from Container
virtual Rect getContainedArea () const
virtual void moveChildrenRelative (int16_t deltaX, int16_t deltaY)
Detailed Description
Using Line from CanvasWidgetRenderer, progress will be rendered as a line. This means that the user must create a painter for painting the circle. The line does not need to horizontal or vertical, but can start at any coordinate and finish at any coordinate.
Note
As LineProgress uses CanvasWidgetRenderer, it is important that a buffer is set up by calling CanvasWidgetRendere::setBuffer().
Constructor & Destructor Documentation
LineProgress()
LineProgress ()
    : AbstractProgressIndicator(), line(), startX(0), startY(0), endX(0), endY(0)
{
    progressIndicatorContainer.add(line);
    line.setPosition(0, 0, getWidth(), getHeight());
}
References Container::add(), Drawable::getHeight(), Drawable::getWidth(), LineProgress::line, AbstractProgressIndicator::progressIndicatorContainer, and Drawable::setPosition().
Member Function Documentation
getEnd()
void getEnd (int & x, int & y) const virtual
Gets the coordinates of the end point of the line. Beware that this is not the coordinates of the current progress of the line, but the coordinates when the line is at 100%.
Parameters
[out] x The x coordinate.
[out] y The y coordinate.
{
    x = endX.to<int>();
    y = endY.to<int>();
}
References LineProgress::endX, LineProgress::endY, and CWRUtil::Q5::to().
getLineEndingStyle()
Line::LINE_ENDING_STYLE getLineEndingStyle () const virtual
Gets line ending style.
Returns
The line ending style.
{
    return line.getLineEndingStyle();
}
References Line::getLineEndingStyle(), and LineProgress::line.
getLineWidth()
int getLineWidth () const virtual
Gets the line width.
Returns
The line width.
{
    int width;
    line.getLineWidth(width);
    return width;
}
References Line::getLineWidth(), and LineProgress::line.
getStart()
void getStart (int & x, int & y) const virtual
Gets the coordinates of the starting point of the line.
Parameters
[out] x The x coordinate.
[out] y The y coordinate.
{
    x = startX.to<int>();
    y = startY.to<int>();
}
References LineProgress::startX, LineProgress::startY, and CWRUtil::Q5::to().
setAlpha()
void setAlpha (uint8_t newAlpha) virtual
Sets the opacity (alpha value). This can be used to fade it away by gradually decreasing the alpha value from 255 (solid) to 0 (invisible).
Parameters
newAlpha The new alpha value. 255=solid, 0=invisible.
See also
getAlpha
Note
The user code must call invalidate() in order to update the display.
Reimplemented from AbstractProgressIndicator.
{
    AbstractProgressIndicator::setAlpha(newAlpha);
    line.setAlpha(newAlpha);
}
References LineProgress::line, AbstractProgressIndicator::setAlpha(), and CanvasWidget::setAlpha().
setEnd()
void setEnd (int x, int y) virtual
Sets the end point for the line. When progress is at 100%, the line will go from the coordinates set by setStart() to the coordinates set by setEnd()
Parameters
x The x coordinate of the end point.
y The y coordinate of the end point.
See also
setStart
{
    endX = CWRUtil::toQ5<int>(x);
    endY = CWRUtil::toQ5<int>(y);
}
References LineProgress::endX, and LineProgress::endY.
setLineEndingStyle()
void setLineEndingStyle (Line::LINE_ENDING_STYLE lineEndingStyle) virtual
Sets line ending style.
Parameters
lineEndingStyle The line ending style.
See also
Line::setLineEndingStyle
{
    line.setLineEndingStyle(lineEndingStyle);
}
References LineProgress::line, and Line::setLineEndingStyle().
setLineWidth()
void setLineWidth (int width) virtual
Sets the line width.
Parameters
width The width.
See also
Line::setLineWidth
{
    line.setLineWidth(width);
}
References LineProgress::line, and Line::setLineWidth().
setPainter()
void setPainter (AbstractPainter & painter) virtual
Sets a painter to be used for drawing the line. This can be any Painter, a simple single color painter, a bitmap painter or a custom painter.
Parameters
[in] painter The painter.
{
    line.setPainter(painter);
}
References LineProgress::line, and CanvasWidget::setPainter().
setProgressIndicatorPosition()
void setProgressIndicatorPosition (int16_t x, int16_t y, int16_t width, int16_t height) virtual
Sets the position and dimensions of the actual progress indicator relative to the background image.
Parameters
x The x coordinate.
y The y coordinate.
width The width of the box progress indicator.
height The height of the box progress indicator.
See also
getProgressIndicatorX, getProgressIndicatorY, getProgressIndicatorWidth, getProgressIndicatorHeight
Reimplemented from AbstractProgressIndicator.
{
    line.setPosition(0, 0, width, height);
    AbstractProgressIndicator::setProgressIndicatorPosition(x, y, width, height);
}
References LineProgress::line, Drawable::setPosition(), and AbstractProgressIndicator::setProgressIndicatorPosition().
setStart()
void setStart (int x, int y) virtual
Sets a starting point for the line.
Parameters
x The x coordinate of the start point.
y The y coordinate of the start point.
See also
setEnd
{
    startX = CWRUtil::toQ5<int>(x);
    startY = CWRUtil::toQ5<int>(y);
    line.setStart(x, y);
}
References LineProgress::line, Line::setStart(), LineProgress::startX, and LineProgress::startY.
setValue()
void setValue (int value) virtual
Sets the current value in the range (min..max) set by setRange(). Values lower than min are mapped to min, values higher than max are mapped to max. If a callback function has been set using setValueSetAction, that callback will be called (unless the new value is the same as the current value).
Parameters
value The value.
See also
getValue, updateValue, setValueSetAction
Note
if value is equal to the current value, nothing happens, and the callback will not be called.
Reimplemented from AbstractProgressIndicator.
{
    if (rangeSteps > 0)
    {
        AbstractProgressIndicator::setValue(value);
        const int progress = (int)AbstractProgressIndicator::getProgress(rangeSteps);
        CWRUtil::Q5 const r(rangeSteps);
        CWRUtil::Q5 const p(progress);
        CWRUtil::Q5 const x = startX + ((endX - startX) / r) * p;
        CWRUtil::Q5 const y = startY + ((endY - startY) / r) * p;
        line.updateEnd(x, y);
    }
}
References LineProgress::endX, LineProgress::endY, AbstractProgressIndicator::getProgress(), LineProgress::line, progress, AbstractProgressIndicator::rangeSteps, AbstractProgressIndicator::setValue(), LineProgress::startX, LineProgress::startY, and Line::updateEnd().
Member Data Documentation
endX
CWRUtil::Q5 endX protected
The end x coordinate.
Referenced by LineProgress::getEnd(), LineProgress::setEnd(), and LineProgress::setValue().
endY
CWRUtil::Q5 endY protected
The end y coordinate.
Referenced by LineProgress::getEnd(), LineProgress::setEnd(), and LineProgress::setValue().
line
Line line protected
The line.
Referenced by LineProgress::LineProgress(), LineProgress::getLineEndingStyle(), LineProgress::getLineWidth(), LineProgress::setAlpha(), LineProgress::setLineEndingStyle(), LineProgress::setLineWidth(), LineProgress::setPainter(), LineProgress::setProgressIndicatorPosition(), LineProgress::setStart(), and LineProgress::setValue().
startX
CWRUtil::Q5 startX protected
The start x coordinate.
Referenced by LineProgress::getStart(), LineProgress::setStart(), and LineProgress::setValue().
startY
CWRUtil::Q5 startY protected
The start y coordinate.
Referenced by LineProgress::getStart(), LineProgress::setStart(), and LineProgress::setValue().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/containers/progress_indicators/LineProgress.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/containers/progress_indicators/LineProgress.cpp