Battery Simulator Documentation: ButtonWithIcon
ButtonWithIcon
#include "ButtonWithIcon.hpp"
Public Member Functions
ButtonWithIcon ()
virtual void draw (const Rect &invalidatedArea) const
Bitmap getCurrentlyDisplayedIcon () const
int16_t getIconX () const
int16_t getIconY () const
virtual void setBitmaps (const Bitmap &newBackgroundReleased, const Bitmap &newBackgroundPressed, const Bitmap &newIconReleased, const Bitmap &newIconPressed)
void setIconX (int16_t x)
void setIconXY (int16_t x, int16_t y)
void setIconY (int16_t y)
Public Member Functions inherited from Button
Button ()
uint8_t getAlpha () const
Bitmap getCurrentlyDisplayedBitmap () const
virtual Rect getSolidRect () const
virtual void invalidateContent () const
void setAlpha (uint8_t newAlpha)
Public Member Functions inherited from AbstractButton
AbstractButton ()
virtual void executeAction ()
virtual bool getPressedState () const
virtual void handleClickEvent (const ClickEvent &event)
void setAction (GenericCallback< const AbstractButton & > &callback)
Public Member Functions inherited from Widget
virtual void getLastChild (int16_t, int16_t, Drawable **last)
Public Member Functions inherited from Drawable
Drawable ()
virtual ~Drawable ()
void center ()
void centerX ()
void centerY ()
virtual void childGeometryChanged ()
void drawToDynamicBitmap (BitmapId id)
void expand (int margin=0)
Rect getAbsoluteRect () const
virtual Drawable * getFirstChild ()
int16_t getHeight () const
Drawable * getNextSibling ()
Drawable * getParent () const
const Rect & getRect () const
virtual Rect getSolidRectAbsolute ()
virtual void getVisibleRect (Rect &rect) const
int16_t getWidth () const
int16_t getX () const
int16_t getY () const
virtual void handleDragEvent (const DragEvent &event)
virtual void handleGestureEvent (const GestureEvent &event)
virtual void handleTickEvent ()
virtual void invalidate () const
virtual void invalidateRect (Rect &invalidatedArea) const
bool isTouchable () const
bool isVisible () const
virtual void moveRelative (int16_t x, int16_t y)
virtual void moveTo (int16_t x, int16_t y)
virtual void setHeight (int16_t height)
void setPosition (const Drawable &drawable)
void setPosition (int16_t x, int16_t y, int16_t width, int16_t height)
void setTouchable (bool touch)
void setVisible (bool vis)
virtual void setWidth (int16_t width)
void setWidthHeight (const Bitmap &bitmap)
void setWidthHeight (const Drawable &drawable)
void setWidthHeight (const Rect &other)
void setWidthHeight (int16_t width, int16_t height)
virtual void setX (int16_t x)
void setXY (const Drawable &drawable)
void setXY (int16_t x, int16_t y)
virtual void setY (int16_t y)
virtual void translateRectToAbsolute (Rect &r) const
Protected Attributes
Bitmap iconPressed
Icon to display when button is pressed.
Bitmap iconReleased
Icon to display when button is not pressed.
int16_t iconX
x coordinate offset for icon.
int16_t iconY
y coordinate offset for icon.
Protected Attributes inherited from Button
uint8_t alpha
The current alpha value. 255=solid, 0=invisible.
Bitmap down
The image to display when button is pressed.
Bitmap up
The image to display when button is released (normal state).
Protected Attributes inherited from AbstractButton
GenericCallback< const AbstractButton & > * action
The callback to be executed when this AbstractButton is clicked.
bool pressed
Is the button pressed or released? True if pressed.
Protected Attributes inherited from Drawable
Drawable * nextSibling
Drawable * parent
Pointer to this drawable's parent.
Rect rect
bool touchable
True if this drawable should receive touch events.
bool visible
True if this drawable should be drawn.
Private Member Functions
virtual void setBitmaps (const Bitmap &, const Bitmap &)
Detailed Description
A Button that has a bitmap with an icon on top of it. It is possible to have two different icons depending on the current state of the button (released or pressed).
Typical use case could be a blue button with a released and a pressed image. Those images can be reused across several buttons. The ButtonWithIcon will then allow an image to superimposed on top of the blue button.
Constructor & Destructor Documentation
ButtonWithIcon()
ButtonWithIcon ()
    : Button(),
      iconReleased(),
      iconPressed(),
      iconX(0),
      iconY(0)
{
}
Member Function Documentation
draw()
void draw (const Rect & invalidatedArea) const virtual
Draw this drawable. It is a requirement that the draw implementation does not draw outside the region specified by invalidatedArea.
Parameters
invalidatedArea The sub-region of this drawable that needs to be redrawn, expressed in coordinates relative to its parent (e.g. for a complete redraw, invalidatedArea will be (0, 0, width, height).
Reimplemented from Button.
{
    Button::draw(invalidatedArea);
    const Bitmap bmp(pressed ? iconPressed : iconReleased);
    const Rect iconRect(iconX, iconY, bmp.getWidth(), bmp.getHeight());
    Rect dirty = invalidatedArea & iconRect;
    if ((bmp.getId() != BITMAP_INVALID) && !dirty.isEmpty())
    {
        Rect r;
        translateRectToAbsolute(r);
        dirty.x -= iconX;
        dirty.y -= iconY;
        HAL::lcd().drawPartialBitmap(bmp, r.x + iconX, r.y + iconY, dirty, alpha);
    }
}
References touchgfx::BITMAP_INVALID, touchgfx::dirty, Button::draw(), ButtonWithIcon::iconPressed, ButtonWithIcon::iconReleased, ButtonWithIcon::iconX, ButtonWithIcon::iconY, HAL::lcd(), AbstractButton::pressed, and Drawable::translateRectToAbsolute().
getCurrentlyDisplayedIcon()
Bitmap getCurrentlyDisplayedIcon () const inline
Gets currently displayed icon. This depends on the current state of the button, released (normal) or pressed.
Returns
The icon currently displayed.
    {
        return (pressed ? iconPressed : iconReleased);
    }
References ButtonWithIcon::iconPressed, ButtonWithIcon::iconReleased, and AbstractButton::pressed.
getIconX()
int16_t getIconX () const inline
Gets the x coordinate of the icon bitmap.
Returns
The x coordinate of the icon bitmap.
    {
        return iconX;
    }
References ButtonWithIcon::iconX.
getIconY()
int16_t getIconY () const inline
Gets the y coordinate of the icon bitmap.
Returns
The y coordinate of the icon bitmap.
    {
        return iconY;
    }
References ButtonWithIcon::iconY.
setBitmaps() [1/2]
virtual void setBitmaps (const Bitmap & bitmapReleased, const Bitmap & bitmapPressed) inline private virtual
Sets the two bitmaps used by this button. One bitmap for the released (normal) state and one bitmap for the pressed state. The images are expected to be of the same dimensions, and the Button is resized to the dimensions of the pressed Bitmap.
Parameters
bitmapReleased Bitmap to use when button is released.
bitmapPressed Bitmap to use when button is pressed.
Note
It is assumed that the dimensions of the bitmaps are the same. Unexpected (visual) behavior may be observed if the bitmaps are of different sizes.
The user code must call invalidate() in order to update the button on the display.
Reimplemented from Button.
    {
    }
setBitmaps() [2/2]
void setBitmaps (const Bitmap & newBackgroundReleased, const Bitmap & newBackgroundPressed, const Bitmap & newIconReleased, const Bitmap & newIconPressed) virtual
Sets the four bitmaps used by this button. The last two bitmaps are drawn on top of the first two, again depending on the current state of the Button. This means that when the button state is released (normal), the newIconReleased is drawn on top of the newBackgroundReleased, and when the button state is pressed, the newIconPressed is drawn on top of the newBackgroundPressed.
The default position if the icons is set to the center of the bitmaps. The two icons are assumed to have the same dimensions. The size of the released icon is used to position the icons centered on the Button.
Parameters
newBackgroundReleased Bitmap to use when button is released.
newBackgroundPressed Bitmap to use when button is pressed.
newIconReleased The bitmap for the icon in the released (normal) button state.
newIconPressed The bitmap for the icon in the pressed button state.
Note
The user code must call invalidate() in order to update the button on the display.
{
    Button::setBitmaps(newBackgroundReleased, newBackgroundPressed);
    iconReleased = newIconReleased;
    iconPressed = newIconPressed;
    iconX = (getWidth() / 2) - (newIconPressed.getWidth() / 2);
    iconY = (getHeight() / 2) - (newIconPressed.getHeight() / 2);
}
References Drawable::getHeight(), Drawable::getWidth(), ButtonWithIcon::iconPressed, ButtonWithIcon::iconReleased, ButtonWithIcon::iconX, ButtonWithIcon::iconY, and Button::setBitmaps().
setIconX()
void setIconX (int16_t x) inline
Sets the x coordinate of the icon bitmaps. The same x coordinate is used for both icons (released and pressed).
Parameters
x The new x value, relative to the background bitmap. A negative value is allowed.
Note
The user code must call invalidate() in order to update the button on the display.
The value set is overwritten on a subsequent call to setBitmaps.
    {
        iconX = x;
    }
References ButtonWithIcon::iconX.
Referenced by ButtonWithIcon::setIconXY().
setIconXY()
void setIconXY (int16_t x, int16_t y) inline
Sets the x and y coordinates of the icon bitmap. Same as calling setIconX and setIconY.
Parameters
x The new x value, relative to the background bitmap. A negative value is allowed.
y The new y value, relative to the background bitmap. A negative value is allowed.
Note
The user code must call invalidate() in order to update the button on the display.
The values set are overwritten on a subsequent call to setBitmaps.
    {
        setIconX(x);
        setIconY(y);
    }
References ButtonWithIcon::setIconX(), and ButtonWithIcon::setIconY().
setIconY()
void setIconY (int16_t y) inline
Sets the y coordinate of the icon bitmaps. The same y coordinate is used for both icons (released and pressed).
Parameters
y The new y value, relative to the background bitmap. A negative value is allowed.
Note
The user code must call invalidate() in order to update the button on the display.
The value set is overwritten on a subsequent call to setBitmaps.
    {
        iconY = y;
    }
References ButtonWithIcon::iconY.
Referenced by ButtonWithIcon::setIconXY().
Member Data Documentation
iconPressed
Bitmap iconPressed protected
Icon to display when button is pressed.
Referenced by ButtonWithIcon::draw(), ButtonWithIcon::getCurrentlyDisplayedIcon(), and ButtonWithIcon::setBitmaps().
iconReleased
Bitmap iconReleased protected
Icon to display when button is not pressed.
Referenced by ButtonWithIcon::draw(), ButtonWithIcon::getCurrentlyDisplayedIcon(), and ButtonWithIcon::setBitmaps().
iconX
int16_t iconX protected
x coordinate offset for icon.
Referenced by ButtonWithIcon::draw(), ButtonWithIcon::getIconX(), ButtonWithIcon::setBitmaps(), and ButtonWithIcon::setIconX().
iconY
int16_t iconY protected
y coordinate offset for icon.
Referenced by ButtonWithIcon::draw(), ButtonWithIcon::getIconY(), ButtonWithIcon::setBitmaps(), and ButtonWithIcon::setIconY().
The documentation for this class was generated from the following files:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/ButtonWithIcon.hpp
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/ButtonWithIcon.cpp