Battery Simulator Documentation: AbstractPainterColor
AbstractPainterColor
#include "AbstractPainterColor.hpp"
Public Member Functions
AbstractPainterColor (colortype color=0)
virtual ~AbstractPainterColor ()
colortype getColor () const
virtual void setColor (colortype color)
Protected Attributes
colortype painterColor
The color.
Detailed Description
An abstract class for creating painter classes for drawing canvas widgets. All canvas widgets need a painter to fill the shape drawn with a CanvasWidgetRenderer. The painter must provide the color of a pixel on a given coordinate, which will the be blended into the framebuffer depending on the position of the canvas widget and the transparency of the given pixel.
The AbstractPainter also implements a function which will blend each pixel in a scanline snippet into the framebuffer, but for better performance, the function should be reimplemented in each painter.
Constructor & Destructor Documentation
AbstractPainterColor()
AbstractPainterColor (colortype color = 0) inline
Constructor.
Parameters
color (Optional) The color to use in the painter.
    {
        setColor(color);
    }
References AbstractPainterColor::setColor().
~AbstractPainterColor()
virtual ~AbstractPainterColor () inline virtual
Destructor
    {
    }
Member Function Documentation
getColor()
colortype getColor () const inline
Gets the current color.
Returns
The color.
    {
        return painterColor;
    }
References AbstractPainterColor::painterColor.
setColor()
virtual void setColor (colortype color) inline virtual
Sets color to use when drawing the CanvasWidget.
Parameters
color The color.
Reimplemented in PainterABGR2222, PainterARGB2222, PainterARGB8888, PainterBGRA2222, PainterBW, PainterGRAY2, PainterGRAY4, PainterRGB565, PainterRGB888, PainterRGBA2222, and PainterXRGB8888.
    {
        painterColor = color;
    }
References AbstractPainterColor::painterColor.
Referenced by AbstractPainterColor::AbstractPainterColor(), PainterABGR2222::setColor(), PainterARGB2222::setColor(), PainterARGB8888::setColor(), PainterBGRA2222::setColor(), PainterBW::setColor(), PainterGRAY2::setColor(), PainterGRAY4::setColor(), PainterRGB565::setColor(), PainterRGB888::setColor(), PainterRGBA2222::setColor(), and PainterXRGB8888::setColor().
Member Data Documentation
painterColor
colortype painterColor protected
The color.
Referenced by AbstractPainterColor::getColor(), PainterARGB8888::paint(), PainterRGB565::paint(), PainterRGB888::paint(), PainterXRGB8888::paint(), AbstractPainterColor::setColor(), PainterABGR2222::setColor(), PainterARGB2222::setColor(), PainterBGRA2222::setColor(), PainterRGB565::setColor(), and PainterRGBA2222::setColor().
The documentation for this class was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/AbstractPainterColor.hpp