Battery Simulator Documentation: C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Core/Src/fdcan.c File Reference
fdcan.c File Reference
This file provides code for the configuration of the FDCAN instances.
#include "fdcan.h"
Functions
void HAL_FDCAN_MspDeInit (FDCAN_HandleTypeDef *fdcanHandle)
void HAL_FDCAN_MspInit (FDCAN_HandleTypeDef *fdcanHandle)
void MX_FDCAN1_Init (void)
void MX_FDCAN2_Init (void)
Variables
static uint32_t HAL_RCC_FDCAN_CLK_ENABLED =0
FDCAN_HandleTypeDef hfdcan1
FDCAN_HandleTypeDef hfdcan2
FDCAN_TxHeaderTypeDef TxHeader
Detailed Description
This file provides code for the configuration of the FDCAN instances.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file fdcan.c.
Function Documentation
HAL_FDCAN_MspDeInit()
void HAL_FDCAN_MspDeInit (FDCAN_HandleTypeDef * fdcanHandle)
{
  if(fdcanHandle->Instance==FDCAN1)
  {
  /* USER CODE BEGIN FDCAN1_MspDeInit 0 */
  /* USER CODE END FDCAN1_MspDeInit 0 */
    /* Peripheral clock disable */
    HAL_RCC_FDCAN_CLK_ENABLED--;
    if(HAL_RCC_FDCAN_CLK_ENABLED==0){
      __HAL_RCC_FDCAN_CLK_DISABLE();
    }
    HAL_GPIO_DeInit(FDCAN1_TX_GPIO_Port, FDCAN1_TX_Pin);
    HAL_GPIO_DeInit(FDCAN1_RX_GPIO_Port, FDCAN1_RX_Pin);
    /* FDCAN1 interrupt Deinit */
    HAL_NVIC_DisableIRQ(FDCAN1_IT0_IRQn);
  /* USER CODE BEGIN FDCAN1_MspDeInit 1 */
  /* USER CODE END FDCAN1_MspDeInit 1 */
  }
  else if(fdcanHandle->Instance==FDCAN2)
  {
  /* USER CODE BEGIN FDCAN2_MspDeInit 0 */
  /* USER CODE END FDCAN2_MspDeInit 0 */
    /* Peripheral clock disable */
    HAL_RCC_FDCAN_CLK_ENABLED--;
    if(HAL_RCC_FDCAN_CLK_ENABLED==0){
      __HAL_RCC_FDCAN_CLK_DISABLE();
    }
    HAL_GPIO_DeInit(GPIOB, FDCAN2_RX_Pin|FDCAN2_TX_Pin);
  /* USER CODE BEGIN FDCAN2_MspDeInit 1 */
  /* USER CODE END FDCAN2_MspDeInit 1 */
  }
}
References FDCAN1_RX_GPIO_Port, FDCAN1_RX_Pin, FDCAN1_TX_GPIO_Port, FDCAN1_TX_Pin, FDCAN2_RX_Pin, FDCAN2_TX_Pin, and HAL_RCC_FDCAN_CLK_ENABLED.
HAL_FDCAN_MspInit()
void HAL_FDCAN_MspInit (FDCAN_HandleTypeDef * fdcanHandle)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
  if(fdcanHandle->Instance==FDCAN1)
  {
  /* USER CODE BEGIN FDCAN1_MspInit 0 */
  /* USER CODE END FDCAN1_MspInit 0 */
    PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_FDCAN;
    PeriphClkInitStruct.FdcanClockSelection = RCC_FDCANCLKSOURCE_PLL;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK)
    {
      Error_Handler();
    }
    /* FDCAN1 clock enable */
    HAL_RCC_FDCAN_CLK_ENABLED++;
    if(HAL_RCC_FDCAN_CLK_ENABLED==1){
      __HAL_RCC_FDCAN_CLK_ENABLE();
    }
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    GPIO_InitStruct.Pin = FDCAN1_TX_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF9_FDCAN1;
    HAL_GPIO_Init(FDCAN1_TX_GPIO_Port, &GPIO_InitStruct);
    GPIO_InitStruct.Pin = FDCAN1_RX_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF9_FDCAN1;
    HAL_GPIO_Init(FDCAN1_RX_GPIO_Port, &GPIO_InitStruct);
    /* FDCAN1 interrupt Init */
    HAL_NVIC_SetPriority(FDCAN1_IT0_IRQn, 5, 0);
    HAL_NVIC_EnableIRQ(FDCAN1_IT0_IRQn);
  /* USER CODE BEGIN FDCAN1_MspInit 1 */
  /* USER CODE END FDCAN1_MspInit 1 */
  }
  else if(fdcanHandle->Instance==FDCAN2)
  {
  /* USER CODE BEGIN FDCAN2_MspInit 0 */
  /* USER CODE END FDCAN2_MspInit 0 */
    PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_FDCAN;
    PeriphClkInitStruct.FdcanClockSelection = RCC_FDCANCLKSOURCE_PLL;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK)
    {
      Error_Handler();
    }
    /* FDCAN2 clock enable */
    HAL_RCC_FDCAN_CLK_ENABLED++;
    if(HAL_RCC_FDCAN_CLK_ENABLED==1){
      __HAL_RCC_FDCAN_CLK_ENABLE();
    }
    __HAL_RCC_GPIOB_CLK_ENABLE();
    GPIO_InitStruct.Pin = FDCAN2_RX_Pin|FDCAN2_TX_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF9_FDCAN2;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
  /* USER CODE BEGIN FDCAN2_MspInit 1 */
  /* USER CODE END FDCAN2_MspInit 1 */
  }
}
References Error_Handler(), FDCAN1_RX_GPIO_Port, FDCAN1_RX_Pin, FDCAN1_TX_GPIO_Port, FDCAN1_TX_Pin, FDCAN2_RX_Pin, FDCAN2_TX_Pin, and HAL_RCC_FDCAN_CLK_ENABLED.
MX_FDCAN1_Init()
void MX_FDCAN1_Init (void)
{
  /* USER CODE BEGIN FDCAN1_Init 0 */
  /* USER CODE END FDCAN1_Init 0 */
  /* USER CODE BEGIN FDCAN1_Init 1 */
  /* USER CODE END FDCAN1_Init 1 */
  hfdcan1.Instance = FDCAN1;
  hfdcan1.Init.FrameFormat = FDCAN_FRAME_FD_NO_BRS;
  hfdcan1.Init.Mode = FDCAN_MODE_NORMAL;
  hfdcan1.Init.AutoRetransmission = ENABLE;
  hfdcan1.Init.TransmitPause = DISABLE;
  hfdcan1.Init.ProtocolException = DISABLE;
  hfdcan1.Init.NominalPrescaler = 1;
  hfdcan1.Init.NominalSyncJumpWidth = 2;
  hfdcan1.Init.NominalTimeSeg1 = 77;
  hfdcan1.Init.NominalTimeSeg2 = 2;
  hfdcan1.Init.DataPrescaler = 4;
  hfdcan1.Init.DataSyncJumpWidth = 3;
  hfdcan1.Init.DataTimeSeg1 = 16;
  hfdcan1.Init.DataTimeSeg2 = 3;
  hfdcan1.Init.MessageRAMOffset = 0;
  hfdcan1.Init.StdFiltersNbr = 1;
  hfdcan1.Init.ExtFiltersNbr = 0;
  hfdcan1.Init.RxFifo0ElmtsNbr = 1;
  hfdcan1.Init.RxFifo0ElmtSize = FDCAN_DATA_BYTES_8;
  hfdcan1.Init.RxFifo1ElmtsNbr = 0;
  hfdcan1.Init.RxFifo1ElmtSize = FDCAN_DATA_BYTES_8;
  hfdcan1.Init.RxBuffersNbr = 0;
  hfdcan1.Init.RxBufferSize = FDCAN_DATA_BYTES_8;
  hfdcan1.Init.TxEventsNbr = 0;
  hfdcan1.Init.TxBuffersNbr = 0;
  hfdcan1.Init.TxFifoQueueElmtsNbr = 1;
  hfdcan1.Init.TxFifoQueueMode = FDCAN_TX_FIFO_OPERATION;
  hfdcan1.Init.TxElmtSize = FDCAN_DATA_BYTES_8;
  if (HAL_FDCAN_Init(&hfdcan1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN FDCAN1_Init 2 */
  /*Filter Configuration*/
  FDCAN_FilterTypeDef sFilterConfig;
  sFilterConfig.IdType = FDCAN_STANDARD_ID;/*Use standard ID*/
  sFilterConfig.FilterIndex = 0; /*Use filter index 0*/
  sFilterConfig.FilterType = FDCAN_FILTER_MASK; /*Filter type Mask*/
  sFilterConfig.FilterConfig = FDCAN_FILTER_TO_RXFIFO0; /*Store the data to FIFO0*/
  sFilterConfig.FilterID1 = 0x07; /*Set the filer ID to be 0x07*/
  sFilterConfig.FilterID2 = 0x07;
  sFilterConfig.RxBufferIndex = 0; /*Rx buffer index of 0 since only 1 CAN-FD is used*/
  if (HAL_FDCAN_ConfigFilter(&hfdcan1, &sFilterConfig) != HAL_OK)
  {
    /* Filter configuration Error */
    Error_Handler();
  }
  if(HAL_FDCAN_Start(&hfdcan1)!= HAL_OK)
  {
      Error_Handler();
  }
  if (HAL_FDCAN_ActivateNotification(&hfdcan1, FDCAN_IT_RX_FIFO0_NEW_MESSAGE, 0) != HAL_OK)
  {
    /* Notification Error */
    Error_Handler();
  }
  /*Declare the TxHeader filer.*/
  TxHeader.Identifier = 0x10; /*Identifier of 0x10 for Riverdi 10.1.*/
  TxHeader.IdType = FDCAN_STANDARD_ID; /*Standard ID.*/
  TxHeader.TxFrameType = FDCAN_DATA_FRAME; /*Data frame.*/
  TxHeader.DataLength = FDCAN_DLC_BYTES_2; /*Data length of 2.*/
  TxHeader.ErrorStateIndicator = FDCAN_ESI_ACTIVE; /*Error state Indicator active.*/
  TxHeader.BitRateSwitch = FDCAN_BRS_OFF; /*Don't switch the bitrate.*/
  TxHeader.FDFormat = FDCAN_FD_CAN; /*Use the CAN-FD data frame.*/
  TxHeader.TxEventFifoControl = FDCAN_NO_TX_EVENTS; /*No Tx event.*/
  TxHeader.MessageMarker = 0; /*No need for Message Marker.*/
  /* USER CODE END FDCAN1_Init 2 */
}
References Error_Handler(), hfdcan1, and TxHeader.
Referenced by main().
MX_FDCAN2_Init()
void MX_FDCAN2_Init (void)
{
  /* USER CODE BEGIN FDCAN2_Init 0 */
  /* USER CODE END FDCAN2_Init 0 */
  /* USER CODE BEGIN FDCAN2_Init 1 */
  /* USER CODE END FDCAN2_Init 1 */
  hfdcan2.Instance = FDCAN2;
  hfdcan2.Init.FrameFormat = FDCAN_FRAME_CLASSIC;
  hfdcan2.Init.Mode = FDCAN_MODE_NORMAL;
  hfdcan2.Init.AutoRetransmission = DISABLE;
  hfdcan2.Init.TransmitPause = DISABLE;
  hfdcan2.Init.ProtocolException = DISABLE;
  hfdcan2.Init.NominalPrescaler = 16;
  hfdcan2.Init.NominalSyncJumpWidth = 1;
  hfdcan2.Init.NominalTimeSeg1 = 2;
  hfdcan2.Init.NominalTimeSeg2 = 2;
  hfdcan2.Init.DataPrescaler = 1;
  hfdcan2.Init.DataSyncJumpWidth = 1;
  hfdcan2.Init.DataTimeSeg1 = 1;
  hfdcan2.Init.DataTimeSeg2 = 1;
  hfdcan2.Init.MessageRAMOffset = 0;
  hfdcan2.Init.StdFiltersNbr = 0;
  hfdcan2.Init.ExtFiltersNbr = 0;
  hfdcan2.Init.RxFifo0ElmtsNbr = 0;
  hfdcan2.Init.RxFifo0ElmtSize = FDCAN_DATA_BYTES_8;
  hfdcan2.Init.RxFifo1ElmtsNbr = 0;
  hfdcan2.Init.RxFifo1ElmtSize = FDCAN_DATA_BYTES_8;
  hfdcan2.Init.RxBuffersNbr = 0;
  hfdcan2.Init.RxBufferSize = FDCAN_DATA_BYTES_8;
  hfdcan2.Init.TxEventsNbr = 0;
  hfdcan2.Init.TxBuffersNbr = 0;
  hfdcan2.Init.TxFifoQueueElmtsNbr = 0;
  hfdcan2.Init.TxFifoQueueMode = FDCAN_TX_FIFO_OPERATION;
  hfdcan2.Init.TxElmtSize = FDCAN_DATA_BYTES_8;
  if (HAL_FDCAN_Init(&hfdcan2) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN FDCAN2_Init 2 */
  /* USER CODE END FDCAN2_Init 2 */
}
References Error_Handler(), and hfdcan2.
Referenced by main().
Variable Documentation
HAL_RCC_FDCAN_CLK_ENABLED
uint32_t HAL_RCC_FDCAN_CLK_ENABLED =0 static
Referenced by HAL_FDCAN_MspDeInit(), and HAL_FDCAN_MspInit().
hfdcan1
FDCAN_HandleTypeDef hfdcan1
File Name : freertos.c Description : Code for freertos applications
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS. Instant of FDCANHandleTypedef
Referenced by FDCAN1_IT0_IRQHandler(), MX_FDCAN1_Init(), and StartCANFD_Task().
hfdcan2
FDCAN_HandleTypeDef hfdcan2
Referenced by MX_FDCAN2_Init().
TxHeader
FDCAN_TxHeaderTypeDef TxHeader extern
Tx Header of CAN-FD
Referenced by MX_FDCAN1_Init(), and StartCANFD_Task().