Battery Simulator Documentation: C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Core/Inc/fdcan.h File Reference
fdcan.h File Reference
This file contains all the function prototypes for the fdcan.c file.
#include "main.h"
#include "string.h"
Functions
void MX_FDCAN1_Init (void)
void MX_FDCAN2_Init (void)
Variables
FDCAN_HandleTypeDef hfdcan1
FDCAN_HandleTypeDef hfdcan2
Detailed Description
This file contains all the function prototypes for the fdcan.c file.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file fdcan.h.
Function Documentation
MX_FDCAN1_Init()
void MX_FDCAN1_Init (void)
{
  /* USER CODE BEGIN FDCAN1_Init 0 */
  /* USER CODE END FDCAN1_Init 0 */
  /* USER CODE BEGIN FDCAN1_Init 1 */
  /* USER CODE END FDCAN1_Init 1 */
  hfdcan1.Instance = FDCAN1;
  hfdcan1.Init.FrameFormat = FDCAN_FRAME_FD_NO_BRS;
  hfdcan1.Init.Mode = FDCAN_MODE_NORMAL;
  hfdcan1.Init.AutoRetransmission = ENABLE;
  hfdcan1.Init.TransmitPause = DISABLE;
  hfdcan1.Init.ProtocolException = DISABLE;
  hfdcan1.Init.NominalPrescaler = 1;
  hfdcan1.Init.NominalSyncJumpWidth = 2;
  hfdcan1.Init.NominalTimeSeg1 = 77;
  hfdcan1.Init.NominalTimeSeg2 = 2;
  hfdcan1.Init.DataPrescaler = 4;
  hfdcan1.Init.DataSyncJumpWidth = 3;
  hfdcan1.Init.DataTimeSeg1 = 16;
  hfdcan1.Init.DataTimeSeg2 = 3;
  hfdcan1.Init.MessageRAMOffset = 0;
  hfdcan1.Init.StdFiltersNbr = 1;
  hfdcan1.Init.ExtFiltersNbr = 0;
  hfdcan1.Init.RxFifo0ElmtsNbr = 1;
  hfdcan1.Init.RxFifo0ElmtSize = FDCAN_DATA_BYTES_8;
  hfdcan1.Init.RxFifo1ElmtsNbr = 0;
  hfdcan1.Init.RxFifo1ElmtSize = FDCAN_DATA_BYTES_8;
  hfdcan1.Init.RxBuffersNbr = 0;
  hfdcan1.Init.RxBufferSize = FDCAN_DATA_BYTES_8;
  hfdcan1.Init.TxEventsNbr = 0;
  hfdcan1.Init.TxBuffersNbr = 0;
  hfdcan1.Init.TxFifoQueueElmtsNbr = 1;
  hfdcan1.Init.TxFifoQueueMode = FDCAN_TX_FIFO_OPERATION;
  hfdcan1.Init.TxElmtSize = FDCAN_DATA_BYTES_8;
  if (HAL_FDCAN_Init(&hfdcan1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN FDCAN1_Init 2 */
  /*Filter Configuration*/
  FDCAN_FilterTypeDef sFilterConfig;
  sFilterConfig.IdType = FDCAN_STANDARD_ID;/*Use standard ID*/
  sFilterConfig.FilterIndex = 0; /*Use filter index 0*/
  sFilterConfig.FilterType = FDCAN_FILTER_MASK; /*Filter type Mask*/
  sFilterConfig.FilterConfig = FDCAN_FILTER_TO_RXFIFO0; /*Store the data to FIFO0*/
  sFilterConfig.FilterID1 = 0x07; /*Set the filer ID to be 0x07*/
  sFilterConfig.FilterID2 = 0x07;
  sFilterConfig.RxBufferIndex = 0; /*Rx buffer index of 0 since only 1 CAN-FD is used*/
  if (HAL_FDCAN_ConfigFilter(&hfdcan1, &sFilterConfig) != HAL_OK)
  {
    /* Filter configuration Error */
    Error_Handler();
  }
  if(HAL_FDCAN_Start(&hfdcan1)!= HAL_OK)
  {
      Error_Handler();
  }
  if (HAL_FDCAN_ActivateNotification(&hfdcan1, FDCAN_IT_RX_FIFO0_NEW_MESSAGE, 0) != HAL_OK)
  {
    /* Notification Error */
    Error_Handler();
  }
  /*Declare the TxHeader filer.*/
  TxHeader.Identifier = 0x10; /*Identifier of 0x10 for Riverdi 10.1.*/
  TxHeader.IdType = FDCAN_STANDARD_ID; /*Standard ID.*/
  TxHeader.TxFrameType = FDCAN_DATA_FRAME; /*Data frame.*/
  TxHeader.DataLength = FDCAN_DLC_BYTES_2; /*Data length of 2.*/
  TxHeader.ErrorStateIndicator = FDCAN_ESI_ACTIVE; /*Error state Indicator active.*/
  TxHeader.BitRateSwitch = FDCAN_BRS_OFF; /*Don't switch the bitrate.*/
  TxHeader.FDFormat = FDCAN_FD_CAN; /*Use the CAN-FD data frame.*/
  TxHeader.TxEventFifoControl = FDCAN_NO_TX_EVENTS; /*No Tx event.*/
  TxHeader.MessageMarker = 0; /*No need for Message Marker.*/
  /* USER CODE END FDCAN1_Init 2 */
}
References Error_Handler(), hfdcan1, and TxHeader.
Referenced by main().
MX_FDCAN2_Init()
void MX_FDCAN2_Init (void)
{
  /* USER CODE BEGIN FDCAN2_Init 0 */
  /* USER CODE END FDCAN2_Init 0 */
  /* USER CODE BEGIN FDCAN2_Init 1 */
  /* USER CODE END FDCAN2_Init 1 */
  hfdcan2.Instance = FDCAN2;
  hfdcan2.Init.FrameFormat = FDCAN_FRAME_CLASSIC;
  hfdcan2.Init.Mode = FDCAN_MODE_NORMAL;
  hfdcan2.Init.AutoRetransmission = DISABLE;
  hfdcan2.Init.TransmitPause = DISABLE;
  hfdcan2.Init.ProtocolException = DISABLE;
  hfdcan2.Init.NominalPrescaler = 16;
  hfdcan2.Init.NominalSyncJumpWidth = 1;
  hfdcan2.Init.NominalTimeSeg1 = 2;
  hfdcan2.Init.NominalTimeSeg2 = 2;
  hfdcan2.Init.DataPrescaler = 1;
  hfdcan2.Init.DataSyncJumpWidth = 1;
  hfdcan2.Init.DataTimeSeg1 = 1;
  hfdcan2.Init.DataTimeSeg2 = 1;
  hfdcan2.Init.MessageRAMOffset = 0;
  hfdcan2.Init.StdFiltersNbr = 0;
  hfdcan2.Init.ExtFiltersNbr = 0;
  hfdcan2.Init.RxFifo0ElmtsNbr = 0;
  hfdcan2.Init.RxFifo0ElmtSize = FDCAN_DATA_BYTES_8;
  hfdcan2.Init.RxFifo1ElmtsNbr = 0;
  hfdcan2.Init.RxFifo1ElmtSize = FDCAN_DATA_BYTES_8;
  hfdcan2.Init.RxBuffersNbr = 0;
  hfdcan2.Init.RxBufferSize = FDCAN_DATA_BYTES_8;
  hfdcan2.Init.TxEventsNbr = 0;
  hfdcan2.Init.TxBuffersNbr = 0;
  hfdcan2.Init.TxFifoQueueElmtsNbr = 0;
  hfdcan2.Init.TxFifoQueueMode = FDCAN_TX_FIFO_OPERATION;
  hfdcan2.Init.TxElmtSize = FDCAN_DATA_BYTES_8;
  if (HAL_FDCAN_Init(&hfdcan2) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN FDCAN2_Init 2 */
  /* USER CODE END FDCAN2_Init 2 */
}
References Error_Handler(), and hfdcan2.
Referenced by main().
Variable Documentation
hfdcan1
FDCAN_HandleTypeDef hfdcan1 extern
hfdcan2
FDCAN_HandleTypeDef hfdcan2 extern
Referenced by MX_FDCAN2_Init().