Battery Simulator Documentation: C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/TouchGFX/generated/simulator/include/simulator/mainBase.hpp File Reference
mainBase.hpp File Reference
#include <touchgfx/hal/HAL.hpp>
#include <touchgfx/lcd/LCD.hpp>
Functions
touchgfx::LCD & setupLCD ()
void setupSimulator (int argc, char **argv, touchgfx::HAL &hal)
void setupVideo (const char *videoFilename, const uint8_t **videoBuffer, uint32_t videoLength)
void setupVideoDecoder (touchgfx::HAL &hal)
Function Documentation
setupLCD()
touchgfx::LCD & setupLCD ()
{
    return lcd;
}
References lcd.
Referenced by WinMain().
setupSimulator()
void setupSimulator (int argc, char ** argv, touchgfx::HAL & hal)
{
    // Simulate hardware running at 60Hz generating a vsync every 16.6667 ms
    static_cast<touchgfx::HALSDL2&>(hal).setVsyncInterval(16.6667f);
    static_cast<touchgfx::HALSDL2&>(hal).setWindowTitle("BatterySimulator");
    // Initialize SDL
    bool sdl_init_result = static_cast<touchgfx::HALSDL2&>(hal).sdl_init(argc, argv);
    assert(sdl_init_result && "Error during SDL initialization");
    HAL::lcd().setVectorFontRenderer(&vectorFontRendererImpl);
}
References hal(), HAL::lcd(), and vectorFontRendererImpl.
Referenced by WinMain().
setupVideo()
void setupVideo (const char * videoFilename, const uint8_t ** videoBuffer, uint32_t videoLength)
{
    FILE *file = 0;
    fopen_s(&file, videoFileName, "rb");
    assert(file && "Unable to setupVideo.");
    *videoBuffer = (uint8_t*) malloc(videoLength + 1);
    fread(const_cast<uint8_t*>(*videoBuffer), 1, videoLength, file);
    fclose(file);
}
setupVideoDecoder()
void setupVideoDecoder (touchgfx::HAL & hal)
{
    for(int i = 0; i < 1; i++)
    {
        mjpegDecoders[i] = new SoftwareMJPEGDecoder((uint8_t*)lineBuffer);
        controller.addDecoder(*mjpegDecoders[i], i);
    }
}
References controller, lineBuffer, and mjpegDecoders.