Battery Simulator Documentation: touchgfx::paint::rgb565 Namespace Reference
touchgfx::paint::rgb565 Namespace Reference
Namespaces
namespace anonymous_namespace{PaintRGB565Impl.hpp}
Functions
FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t newpix, uint16_t bufpix, uint8_t alpha)
FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t R, uint16_t G, uint16_t B, uint16_t bufpix, uint8_t alpha)
FORCE_INLINE_FUNCTION uint16_t getNativeColor (colortype color)
void lineFromARGB8888 (uint16_t *const ptr, const uint32_t *const data, const unsigned count, const uint8_t alpha)
void lineFromColor (uint16_t *const ptr, const unsigned count, const uint32_t color, const uint8_t alpha, const uint32_t color565)
void lineFromL8ARGB8888 (uint16_t *const ptr, const uint8_t *const data, const unsigned count, const uint8_t alpha)
void lineFromL8RGB888 (uint16_t *const ptr, const uint8_t *const data, const unsigned count, const uint8_t alpha)
void lineFromRGB565 (uint16_t *const ptr, const uint16_t *const data, const unsigned count, const uint8_t alpha)
Function Documentation
alphaBlend() [1/2]
FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t newpix, uint16_t bufpix, uint8_t alpha)
Mix colors from a new pixel and a buffer pixel with the given alpha applied to the new pixel, and the inverse alpha applied to the buffer pixel.
Parameters
newpix The new pixel value.
bufpix The buffer pixel value.
alpha The alpha to apply to the new pixel.
Returns
The result of blending the two colors into a new color.
{
    return alphaBlend(newpix & RMASK, newpix & GMASK, newpix & BMASK, bufpix, alpha);
}
References alphaBlend(), touchgfx::BMASK, touchgfx::GMASK, and touchgfx::RMASK.
alphaBlend() [2/2]
FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t R, uint16_t G, uint16_t B, uint16_t bufpix, uint8_t alpha)
Mix colors from a new pixel and a buffer pixel with the given alpha applied to the new pixel, and the inverse alpha applied to the buffer pixel.
Parameters
R The red color (0-31 shifted into RMASK).
G The green color (0-63 shifted into GMASK).
B The blue color (0-31 shifted into BMASK).
bufpix The buffer pixel value.
alpha The alpha of the R,G,B.
Returns
The result of blending the two colors into a new color.
{
    const uint8_t ialpha = 0xFF - alpha;
    return (((R * alpha + (bufpix & RMASK) * ialpha) / 255) & RMASK) |
           (((G * alpha + (bufpix & GMASK) * ialpha) / 255) & GMASK) |
           (((B * alpha + (bufpix & BMASK) * ialpha) / 255) & BMASK);
}
References touchgfx::BMASK, touchgfx::GMASK, and touchgfx::RMASK.
Referenced by alphaBlend(), lineFromARGB8888(), lineFromColor(), lineFromL8ARGB8888(), and lineFromRGB565().
getNativeColor()
FORCE_INLINE_FUNCTION uint16_t getNativeColor (colortype color)
Generates a color representation to be used on the LCD, based on 24 bit RGB values.
Parameters
color The color.
Returns
The color representation depending on LCD color format.
{
    return ((color >> 8) & 0xF800) | ((color >> 5) & 0x07E0) | ((color >> 3) & 0x001F);
}
Referenced by lineFromARGB8888(), and lineFromL8ARGB8888().
lineFromARGB8888()
void lineFromARGB8888 (uint16_t *const ptr, const uint32_t *const data, const unsigned count, const uint8_t alpha)
Draw a horizontal line (one pixel high) using pixels from the given data pointer (ARGB8888 data).
Parameters
[in] ptr The pointer to the position in the framebuffer.
data The ARGB8888 data.
count Number of pixels to draw.
alpha The alpha.
{
    uint16_t* framebuffer = ptr;
    const uint32_t* bitmapPointer = data;
    const uint16_t* const chunkend = framebuffer + count;
    do
    {
        const uint8_t srcAlpha = (*bitmapPointer) >> 24;
        const uint8_t a = LCD::div255(alpha * srcAlpha);
        if (a == 0xFF)
        {
            *framebuffer = getNativeColor(*bitmapPointer);
        }
        else if (a)
        {
            const uint32_t newpix = *bitmapPointer;
            *framebuffer = alphaBlend((newpix >> 8) & RMASK, (newpix >> 5) & GMASK, (newpix >> 3) & BMASK, *framebuffer, a);
        }
        bitmapPointer++;
    } while (++framebuffer < chunkend);
}
References alphaBlend(), touchgfx::BMASK, LCD::div255(), getNativeColor(), touchgfx::GMASK, and touchgfx::RMASK.
Referenced by PainterRGB565Bitmap::paint().
lineFromColor()
void lineFromColor (uint16_t *const ptr, const unsigned count, const uint32_t color, const uint8_t alpha, const uint32_t color565)
Draw a horizontal line (one pixel high) using the given color.
Parameters
[in] ptr The pointer to the position in the framebuffer.
count Number of pixels to draw.
color The color.
alpha The alpha.
color565 The color565 (same as 'color' but in native format for speed reasons).
{
    uint16_t* framebuffer = ptr;
    const uint16_t* const lineEnd = framebuffer + count;
    if (alpha == 0xFF)
    {
        do
        {
            *framebuffer = color565;
        } while (++framebuffer < lineEnd);
    }
    else
    {
        do
        {
            *framebuffer = alphaBlend(color565, *framebuffer, alpha);
        } while (++framebuffer < lineEnd);
    }
}
References alphaBlend().
Referenced by PainterRGB565::paint().
lineFromL8ARGB8888()
void lineFromL8ARGB8888 (uint16_t *const ptr, const uint8_t *const data, const unsigned count, const uint8_t alpha)
Draw a horizontal line (one pixel high) using pixels from the given data pointer (L8ARGB8888 data).
Parameters
[in] ptr The pointer to the position in the framebuffer.
data The palette indices.
count Number of pixels to draw.
alpha The alpha.
{
    uint16_t* framebuffer = ptr;
    const uint8_t* bitmapPointer = data;
    const uint16_t* const chunkend = framebuffer + count;
    do
    {
        const uint32_t newpix = reinterpret_cast<const uint32_t*>(blendL8CLUT)[*bitmapPointer++];
        const uint8_t srcAlpha = newpix >> 24;
        const uint8_t a = LCD::div255(alpha * srcAlpha);
        if (a == 0xFF)
        {
            *framebuffer = getNativeColor(newpix);
        }
        else if (a)
        {
            *framebuffer = alphaBlend((newpix >> 8) & RMASK, (newpix >> 5) & GMASK, (newpix >> 3) & BMASK, *framebuffer, a);
        }
    } while (++framebuffer < chunkend);
}
References alphaBlend(), touchgfx::BMASK, LCD::div255(), getNativeColor(), touchgfx::GMASK, and touchgfx::RMASK.
Referenced by PainterRGB565L8Bitmap::paint().
lineFromL8RGB888()
void lineFromL8RGB888 (uint16_t *const ptr, const uint8_t *const data, const unsigned count, const uint8_t alpha)
Draw a horizontal line (one pixel high) using pixels from the given data pointer (L8RGB888 data).
Parameters
[in] ptr The pointer to the position in the framebuffer.
data The palette indices.
count Number of pixels to draw.
alpha The alpha.
{
    uint16_t* framebuffer = ptr;
    const uint8_t* bitmapPointer = data;
    const uint16_t* const chunkend = framebuffer + count;
    if (alpha == 0xFF)
    {
        do
        {
            const uint8_t* src = &blendL8CLUT[*bitmapPointer++ * 3];
            // Use alpha from covers directly
            const uint8_t blue = *src++;
            const uint8_t green = *src++;
            const uint8_t red = *src;
            *framebuffer = ((red << 8) & RMASK) | ((green << 3) & GMASK) | ((blue >> 3) & BMASK);
        } while (++framebuffer < chunkend);
    }
    else
    {
        do
        {
            const uint8_t* src = &blendL8CLUT[*bitmapPointer++ * 3];
            // Use alpha from covers directly
            const uint8_t blue = *src++;
            const uint8_t green = *src++;
            const uint8_t red = *src;
            const uint8_t ialpha = 0xFF - alpha;
            const uint16_t bufpix = *framebuffer;
            uint8_t fbr = Color::getRedFromRGB565(bufpix);
            uint8_t fbg = Color::getGreenFromRGB565(bufpix);
            uint8_t fbb = Color::getBlueFromRGB565(bufpix);
            *framebuffer = ((LCD::div255(red * alpha + fbr * ialpha) << 8) & RMASK) | ((LCD::div255(green * alpha + fbg * ialpha) << 3) & GMASK) | ((LCD::div255(blue * alpha + fbb * ialpha) >> 3) & BMASK);
        } while (++framebuffer < chunkend);
    }
}
References touchgfx::BMASK, LCD::div255(), Color::getBlueFromRGB565(), Color::getGreenFromRGB565(), Color::getRedFromRGB565(), touchgfx::GMASK, and touchgfx::RMASK.
Referenced by PainterRGB565L8Bitmap::paint().
lineFromRGB565()
void lineFromRGB565 (uint16_t *const ptr, const uint16_t *const data, const unsigned count, const uint8_t alpha)
Draw a horizontal line (one pixel high) using pixels from the given data pointer (RGB565 data).
Parameters
[in] ptr The pointer to the position in the framebuffer.
data The RGB565 data.
count Number of pixels to draw.
alpha The alpha.
{
    uint16_t* framebuffer = ptr;
    const uint16_t* bitmapPointer = data;
    const uint16_t* const chunkend = framebuffer + count;
    if (alpha == 0xFF)
    {
        do
        {
            *framebuffer = *bitmapPointer++;
        } while (++framebuffer < chunkend);
    }
    else
    {
        do
        {
            *framebuffer = alphaBlend(*bitmapPointer++, *framebuffer, alpha);
        } while (++framebuffer < chunkend);
    }
}
References alphaBlend().
Referenced by PainterRGB565Bitmap::paint().