Battery Simulator Documentation: touchgfx::paint Namespace Reference
touchgfx::paint Namespace Reference
Namespaces
namespace anonymous_namespace{PaintImpl.hpp}
namespace anonymous_namespace{STM32DMA.cpp}
namespace argb8888
namespace rgb565
namespace rgb888
Functions
void setL8Palette (const uint8_t *const data)
void tearDown (void)
Waits until previous DMA drawing operation has finished.
Function Documentation
setL8Palette()
void setL8Palette (const uint8_t *const data)
Sets L8 palette to be used by the painter. The content pointed to be parameter data depends on the actual L8 format. L8RGB8888 assumes data points to three bytes per palette index,. L8ARGB8888 assumes four bytes per palette index.
Parameters
data The palette data.
{
    blendL8CLUT = data;
}
Referenced by PainterARGB8888L8Bitmap::setup(), PainterRGB565L8Bitmap::setup(), and PainterRGB888L8Bitmap::setup().
tearDown()
void tearDown (void)
Waits until previous DMA drawing operation has finished.
Tear down painter - wait for pending draw operations to finish.
{
}
Referenced by PainterARGB8888::tearDown(), PainterARGB8888Bitmap::tearDown(), PainterARGB8888L8Bitmap::tearDown(), PainterRGB565::tearDown(), PainterRGB565Bitmap::tearDown(), PainterRGB565L8Bitmap::tearDown(), PainterRGB888::tearDown(), PainterRGB888Bitmap::tearDown(), and PainterRGB888L8Bitmap::tearDown().