Battery Simulator Documentation: touchgfx Namespace Reference
touchgfx Namespace Reference
Namespaces
namespace meta
namespace paint
Classes
class AbstractButton
class AbstractButtonContainer
class AbstractClock
class AbstractDataGraph
class AbstractDirectionProgress
class AbstractGraphDecoration
class AbstractGraphElement
class AbstractGraphElementNoCWR
class AbstractPainter
class AbstractPainterABGR2222
class AbstractPainterARGB2222
class AbstractPainterARGB8888
class AbstractPainterBGRA2222
class AbstractPainterBitmap
class AbstractPainterBW
class AbstractPainterColor
class AbstractPainterGRAY2
class AbstractPainterGRAY4
class AbstractPainterLinearGradient
class AbstractPainterRGB565
class AbstractPainterRGB888
class AbstractPainterRGBA2222
class AbstractPartition
class AbstractProgressIndicator
class AbstractShape
class AdjustElements
class AnalogClock
class AnimatedImage
class AnimatedImageButtonStyle
class AnimationTextureMapper
class Application
class BinaryFont
struct BinaryFontData
class Bitmap
struct BlitOp
class BlockTransition
class Box
class BoxProgress
class BoxWithBorder
class BoxWithBorderButtonStyle
class Button
class ButtonController
class Buttons
class ButtonWithIcon
class ButtonWithLabel
class CacheableContainer
class CachedFont
struct Callback
struct Callback< dest_type, T1, T2, void >
struct Callback< dest_type, T1, void, void >
struct Callback< dest_type, void, void, void >
class Canvas
class CanvasWidget
class CanvasWidgetRenderer
class Circle
class CircleProgress
class ClickButtonTrigger
class ClickEvent
class ClickListener
class Color
struct colortype
class ConstFont
class Container
class CoverTransition
struct CWRUtil
class CWRVectorRenderer
class CWRVectorRendererARGB8888
class CWRVectorRendererRGB565
class CWRVectorRendererRGB888
class DebugPrinter
class DigitalClock
class DisplayTransformation
class DMA_Interface
class DMA_Queue
class DragEvent
class Draggable
class Drawable
class DrawableList
class DrawableListItems
class DrawableListItemsInterface
struct DrawingSurface
class DynamicDataGraph
class EasingEquations
struct Edge
class Event
class FadeAnimator
class FlashDataReader
class Font
class FontCache
struct FontContextualFormsTable
class FontDataReader
class FontManager
class FontProvider
class FrameBufferAllocator
class FusedFont
class Gauge
class GeneratedFont
class GeneratedVectorFont
class GenericCallback
class GenericCallback< T1, T2, void >
class GenericCallback< T1, void, void >
class GenericCallback< void >
class GestureEvent
class Gestures
struct GlyphNode
class GPIO
struct Gradients
class Graph
class GraphData
class GraphElementArea
class GraphElementBoxes
class GraphElementDiamonds
class GraphElementDots
class GraphElementGridBase
class GraphElementGridX
class GraphElementGridY
class GraphElementHistogram
class GraphElementLine
class GraphElementVerticalGapLine
class GraphLabelsBase
class GraphLabelsX
class GraphLabelsY
class GraphScroll
class GraphScrollData
class GraphTitle
class GraphWrapAndClear
class GraphWrapAndClearData
class GraphWrapAndOverwrite
class GraphWrapAndOverwriteData
class HAL
class HALSDL2
class I2C
class I2CTouchController
class IconButtonStyle
class Image
class ImageButtonStyle
class ImageProgress
class InternalFlashFont
struct KerningNode
class Keyboard
class LCD
class LCD16bpp
class LCD16bppSerialFlash
class LCD16DebugPrinter
class LCD1bpp
class LCD1DebugPrinter
class LCD24bpp
class LCD24DebugPrinter
class LCD2bpp
class LCD2DebugPrinter
class LCD32bpp
class LCD32bpp_XRGB8888
class LCD32DebugPrinter
class LCD4bpp
class LCD4DebugPrinter
class LCD8ABGR2222DebugPrinter
class LCD8ARGB2222DebugPrinter
class LCD8BGRA2222DebugPrinter
class LCD8bpp_ABGR2222
class LCD8bpp_ARGB2222
class LCD8bpp_BGRA2222
class LCD8bpp_RGBA2222
class LCD8DebugPrinterBase
class LCD8RGBA2222DebugPrinter
class Line
class LineProgress
class ListLayout
class LockFreeDMA_Queue
struct LZW9DictionaryEntry
class ManyBlockAllocator
class Matrix3x3
class Matrix4x4
class MCUInstrumentation
class ModalWindow
class MoveAnimator
class MVPApplication
class MVPHeap
class NoDMA
class NoTouchController
class NoTransition
class OSWrappers
class PainterABGR2222
class PainterABGR2222Bitmap
class PainterARGB2222
class PainterARGB2222Bitmap
class PainterARGB8888
class PainterARGB8888Bitmap
class PainterARGB8888L8Bitmap
class PainterARGB8888LinearGradient
class PainterBGRA2222
class PainterBGRA2222Bitmap
class PainterBW
class PainterBWBitmap
class PainterGRAY2
class PainterGRAY2Bitmap
class PainterGRAY4
class PainterGRAY4Bitmap
class PainterRGB565
class PainterRGB565Bitmap
class PainterRGB565L8Bitmap
class PainterRGB565LinearGradient
class PainterRGB888
class PainterRGB888Bitmap
class PainterRGB888L8Bitmap
class PainterRGB888LinearGradient
class PainterRGBA2222
class PainterRGBA2222Bitmap
class PainterXRGB8888
class PainterXRGB8888Bitmap
class PainterXRGB8888L8Bitmap
struct Pair
class PartialFrameBufferManager
class Partition
class PixelDataWidget
struct Point
struct Point3D
class Point4
class Presenter
class Quadruple
class RadioButton
class RadioButtonGroup
class Rect
class RepeatButton
class RepeatButtonTrigger
class ScalableImage
class Screen
class ScrollableContainer
class ScrollBase
class ScrollList
class ScrollWheel
class ScrollWheelBase
class ScrollWheelWithSelectionStyle
class SDL2TouchController
class SDLTouchController
class Shape
class SlideMenu
class Slider
class SlideTransition
class Snapper
class SnapshotWidget
class StaticDataGraph
class SVGImage
class SwipeContainer
class TextArea
class TextAreaWithOneWildcard
class TextAreaWithTwoWildcards
class TextAreaWithWildcardBase
class TextButtonStyle
class TextProgress
class TextProvider
class Texts
class TextureMapper
struct TextureSurface
class TiledImage
class TiledImageButtonStyle
class ToggleButton
class ToggleButtonTrigger
class TouchArea
class TouchButtonTrigger
class TouchCalibration
class TouchController
class Transition
class TwoWildcardTextButtonStyle
class TypedText
class UIEventListener
class Unicode
class UnmappedDataFont
class Vector
class Vector4
struct VectorFontData
struct VectorFontNode
class VectorFontRenderer
class VectorFontRendererImpl
struct VectorKerningNode
class VectorRenderer
struct VGFixedColor
struct VGLinearGradient
struct VGObject
struct VGShape
class VideoController
class VideoDataReader
struct VideoInformation
class VideoWidget
class View
class Widget
class WildcardTextButtonStyle
class WipeTransition
class ZoomAnimationImage
Typedefs
typedef uint8_t Alignment
typedef AnimatedImageButtonStyle< ClickButtonTrigger > AnimatedImageClickButton
typedef AnimatedImageButtonStyle< RepeatButtonTrigger > AnimatedImageRepeatButton
typedef AnimatedImageButtonStyle< ToggleButtonTrigger > AnimatedImageToggleButton
typedef AnimatedImageButtonStyle< TouchButtonTrigger > AnimatedImageTouchButton
typedef uint16_t BitmapId
typedef BoxWithBorderButtonStyle< ClickButtonTrigger > BoxClickButton
typedef BoxWithBorderButtonStyle< RepeatButtonTrigger > BoxRepeatButton
typedef BoxWithBorderButtonStyle< ToggleButtonTrigger > BoxToggleButton
typedef BoxWithBorderButtonStyle< TouchButtonTrigger > BoxTouchButton
typedef int16_t(* EasingEquation) (uint16_t, int16_t, int16_t, uint16_t)
typedef int32_t fixed16_16
typedef int32_t fixed28_4
typedef uint16_t FontId
typedef IconButtonStyle< ClickButtonTrigger > IconClickButton
typedef ImageButtonStyle< IconButtonStyle< ClickButtonTrigger > > IconImageClickButton
typedef ImageButtonStyle< IconButtonStyle< RepeatButtonTrigger > > IconImageRepeatButton
typedef ImageButtonStyle< IconButtonStyle< ToggleButtonTrigger > > IconImageToggleButton
typedef ImageButtonStyle< IconButtonStyle< TouchButtonTrigger > > IconImageTouchButton
typedef IconButtonStyle< RepeatButtonTrigger > IconRepeatButton
typedef IconButtonStyle< ToggleButtonTrigger > IconToggleButton
typedef IconButtonStyle< TouchButtonTrigger > IconTouchButton
typedef ImageButtonStyle< ClickButtonTrigger > ImageClickButton
typedef ImageButtonStyle< RepeatButtonTrigger > ImageRepeatButton
typedef ImageButtonStyle< ToggleButtonTrigger > ImageToggleButton
typedef ImageButtonStyle< TouchButtonTrigger > ImageTouchButton
typedef uint16_t LanguageId
typedef uint16_t RenderingVariant
typedef TextButtonStyle< ClickButtonTrigger > TextClickButton
typedef uint8_t TextDirection
typedef TextButtonStyle< RepeatButtonTrigger > TextRepeatButton
typedef TextButtonStyle< ToggleButtonTrigger > TextToggleButton
typedef TextButtonStyle< TouchButtonTrigger > TextTouchButton
typedef TiledImageButtonStyle< ClickButtonTrigger > TiledImageClickButton
typedef TiledImageButtonStyle< RepeatButtonTrigger > TiledImageRepeatButton
typedef TiledImageButtonStyle< ToggleButtonTrigger > TiledImageToggleButton
typedef TiledImageButtonStyle< TouchButtonTrigger > TiledImageTouchButton
typedef TwoWildcardTextButtonStyle< ClickButtonTrigger > TwoWildcardTextClickButton
typedef TwoWildcardTextButtonStyle< RepeatButtonTrigger > TwoWildcardTextRepeatButton
typedef TwoWildcardTextButtonStyle< ToggleButtonTrigger > TwoWildcardTextToggleButton
typedef TwoWildcardTextButtonStyle< TouchButtonTrigger > TwoWildcardTextTouchButton
typedef uint16_t TypedTextId
typedef WildcardTextButtonStyle< ClickButtonTrigger > WildcardTextClickButton
typedef WildcardTextButtonStyle< RepeatButtonTrigger > WildcardTextRepeatButton
typedef WildcardTextButtonStyle< ToggleButtonTrigger > WildcardTextToggleButton
typedef WildcardTextButtonStyle< TouchButtonTrigger > WildcardTextTouchButton
Enumerations
enum BlitOperations {
BLIT_OP_COPY = 1 << 0 , BLIT_OP_FILL = 1 << 1 , BLIT_OP_COPY_WITH_ALPHA = 1 << 2 , BLIT_OP_FILL_WITH_ALPHA = 1 << 3 ,
BLIT_OP_COPY_WITH_TRANSPARENT_PIXELS = 1 << 4 , BLIT_OP_COPY_ARGB8888 = 1 << 5 , BLIT_OP_COPY_ARGB8888_WITH_ALPHA = 1 << 6 , BLIT_OP_COPY_L8 = 1 << 7 ,
BLIT_OP_COPY_A4 = 1 << 8 , BLIT_OP_COPY_A8 = 1 << 9 , BLIT_OP_COPY_16BIT = 1 << 10 , BLIT_OP_FILL_16BIT = 1 << 11
}
enum Direction { NORTH , SOUTH , EAST , WEST }
enum DisplayOrientation { ORIENTATION_LANDSCAPE , ORIENTATION_PORTRAIT }
enum DisplayRotation { rotate0 , rotate90 }
enum DMAType { DMA_TYPE_GENERIC , DMA_TYPE_CHROMART }
enum FrameBuffer { FB_PRIMARY , FB_SECONDARY , FB_TERTIARY }
enum GlyphFlags {
GLYPH_DATA_KERNINGTABLEPOS_BIT8_10 = 0x07 , GLYPH_DATA_WIDTH_BIT8 = 0x08 , GLYPH_DATA_HEIGHT_BIT8 = 0x10 , GLYPH_DATA_TOP_BIT8 = 0x20 ,
GLYPH_DATA_TOP_BIT9 = 0x40 , GLYPH_DATA_ADVANCE_BIT8 = 0x80
}
enum Gradient { GRADIENT_HORIZONTAL , GRADIENT_VERTICAL }
enum TextRotation { TEXT_ROTATE_0 , TEXT_ROTATE_90 , TEXT_ROTATE_180 , TEXT_ROTATE_270 }
enum VectorPrimitives {
VECTOR_PRIM_CLOSE = 0 , VECTOR_PRIM_MOVE = 1 , VECTOR_PRIM_LINE = 2 , VECTOR_PRIM_HLINE = 3 ,
VECTOR_PRIM_VLINE = 4 , VECTOR_PRIM_BEZIER_QUAD = 5 , VECTOR_PRIM_BEZIER_CUBIC = 6
}
enum VGColorMode { VG_NONE , VG_FIXED_COLOR , VG_LINEAR_GRADIENT }
enum VGFillMode { VG_FILL_EVEN_ODD , VG_FILL_NON_ZERO }
enum VGStrokeLineCap { VG_STROKE_LINECAP_BUTT , VG_STROKE_LINECAP_ROUND , VG_STROKE_LINECAP_SQUARE }
enum VGStrokeLineJoin { VG_STROKE_LINEJOIN_BEVEL , VG_STROKE_LINEJOIN_MITER , VG_STROKE_LINEJOIN_ROUND }
enum WideTextAction {
WIDE_TEXT_NONE , WIDE_TEXT_WORDWRAP , WIDE_TEXT_WORDWRAP_ELLIPSIS , WIDE_TEXT_WORDWRAP_ELLIPSIS_AFTER_SPACE ,
WIDE_TEXT_CHARWRAP , WIDE_TEXT_CHARWRAP_ELLIPSIS , WIDE_TEXT_CHARWRAP_DOUBLE_ELLIPSIS
}
Functions
template<typename T >
T abs (T d)
static FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t R, uint16_t G, uint16_t B, uint16_t bufpix, uint8_t alpha)
static uint16_t applyNoise (int x, int y, uint8_t r, uint8_t g, uint8_t b)
FORCE_INLINE_FUNCTION int32_t ceil28_4 (fixed28_4 value)
int32_t clz (int32_t x)
int32_t clzu (uint32_t x)
void fillBits (uint8_t *fb, int16_t startX, int16_t startY, int16_t stride, int32_t count, uint8_t color)
static FORCE_INLINE_FUNCTION void finalizeTransition (Screen *newScreen, Presenter *newPresenter, Transition *newTransition)
FORCE_INLINE_FUNCTION fixed28_4 fixed28_4Mul (fixed28_4 a, fixed28_4 b)
FORCE_INLINE_FUNCTION float fixed28_4ToFloat (fixed28_4 value)
FORCE_INLINE_FUNCTION fixed16_16 floatToFixed16_16 (float value)
FORCE_INLINE_FUNCTION fixed28_4 floatToFixed28_4 (float value)
FORCE_INLINE_FUNCTION void floorDivMod (int32_t numerator, int32_t denominator, int32_t &floor, int32_t &mod)
void FrameBufferAllocatorSignalBlockDrawn ()
void FrameBufferAllocatorWaitOnTransfer ()
template<typename T >
T gcd (T a, T b)
static FORCE_INLINE_FUNCTION uint16_t getNativeColor (colortype color)
static FORCE_INLINE_FUNCTION uint16_t getNativeColorFromRGB (uint8_t red, uint8_t green, uint8_t blue)
void hw_init ()
RenderingVariant lookupBilinearRenderVariant (const Bitmap &bitmap)
RenderingVariant lookupNearestNeighborRenderVariant (const Bitmap &bitmap)
template<class ScreenType , class PresenterType , class TransType , class ModelType >
PresenterType * makeTransition (Screen **currentScreen, Presenter **currentPresenter, MVPHeap &heap, Transition **currentTrans, ModelType *model)
void memset (void *data, uint8_t c, uint32_t size)
int32_t muldiv (int32_t factor1, int32_t factor2, int32_t divisor)
int32_t muldiv (int32_t factor1, int32_t factor2, int32_t divisor, int32_t &remainder)
uint32_t muldivu (uint32_t factor1, uint32_t factor2, uint32_t divisor, uint32_t &remainder)
Uint32 myTimerCallback2 (Uint32 interval, void *param)
Matrix4x4 operator* (const Matrix4x4 &multiplicand, const Matrix4x4 &multiplier)
Point4 operator* (const Matrix4x4 &multiplicand, const Point4 &multiplier)
static FORCE_INLINE_FUNCTION void prepareTransition (Screen **currentScreen, Presenter **currentPresenter, Transition **currentTrans)
static uint16_t random (int x, int y)
static void sdlCleanup2 ()
int shouldTransferBlock (uint16_t bottom)
template<typename T >
T sign (T d)
void simulator_enable_stdio ()
void simulator_printf (const char *format, va_list pArg)
template<class HALType >
HAL & touchgfx_generic_init (DMA_Interface &dma, LCD &display, TouchController &tc, int16_t width, int16_t height, uint16_t *bitmapCache, uint32_t bitmapCacheSize, uint32_t numberOfDynamicBitmaps=0)
void touchgfx_init ()
static int transferThreadFunc (void *ptr)
int transmitActive ()
void transmitBlock (const uint8_t *pixels, uint16_t x, uint16_t y, uint16_t w, uint16_t h)
Variables
static uint16_t * anim_store = NULL
const BitmapId BITMAP_ANIMATION_STORAGE = 0xFFFEU
A virtual id representing animation storage.
const BitmapId BITMAP_INVALID = 0xFFFFU
Define the bitmapId of an invalid bitmap.
const uint16_t BMASK = 0x001F
static const Alignment CENTER = 1
Text is centered horizontally.
static Rect dirty
static uint16_t * double_buf = NULL
static bool framebufferLocked = false
const uint16_t GMASK = 0x07E0
static uint16_t HALSDL2__FRAME_BUFFER_HEIGHT = 0
static uint16_t HALSDL2__FRAME_BUFFER_WIDTH = 0
static bool isAlive = true
static bool isConsoleAllocated = false
static const Alignment LEFT = 0
Text is left aligned.
static const float PI = 3.14159265358979323846f
PI.
static const uint16_t RenderingVariant_Alpha = 2
The rendering variant alpha bit value.
static const uint16_t RenderingVariant_Bilinear = 1
The rendering variant bilinear bit value.
static const uint16_t RenderingVariant_FormatShift = 2
The rendering variant format shift.
static const uint16_t RenderingVariant_NearestNeighbor = 0
The rendering variant nearest neighbor bit value.
static const uint16_t RenderingVariant_NoAlpha = 0
The rendering variant no alpha bit value.
static const Alignment RIGHT = 2
Text is right aligned.
const uint16_t RMASK = 0xF800
static SDL_mutex * s_FrameBufferLock = NULL
static int screenshotcount = 0
bool sdl_initialized = false
static SDL_sem * sem_transfer_done = 0
static SDL_sem * sem_transfer_ready = 0
static SDL_Renderer * simulatorRenderer = 0
static SDL_Window * simulatorWindow = 0
static uint16_t * single_buf = NULL
const uint16_t SVG_INVALID = 0xFFFFU
Define the svgId of an invalid SVG.
static const TextDirection TEXT_DIRECTION_LTR = 0
Text is written Left-To-Right, e.g. English.
static const TextDirection TEXT_DIRECTION_RTL = 1
Text is written Right-To-Left, e.g. Hebrew.
static uint16_t * tft = NULL
static uint8_t * tft_display24 = NULL
static bool tft_display24_allocated = false
static uint8_t * tft_framebuffer24 = NULL
static bool tft_framebuffer24_allocated = false
const TypedTextId TYPED_TEXT_INVALID = 0xFFFFU
The ID of an invalid text.
Detailed Description
The global touchgfx namespace. All TouchGFX framework classes and global functions are placed in this namespace.
Typedef Documentation
Alignment
typedef uint8_t Alignment
Defines an alignment type.
AnimatedImageClickButton
typedef AnimatedImageButtonStyle<ClickButtonTrigger> AnimatedImageClickButton
Defines an alias representing the animated image click button.
AnimatedImageRepeatButton
typedef AnimatedImageButtonStyle<RepeatButtonTrigger> AnimatedImageRepeatButton
Defines an alias representing the animated image repeat button.
AnimatedImageToggleButton
typedef AnimatedImageButtonStyle<ToggleButtonTrigger> AnimatedImageToggleButton
Defines an alias representing the animated image toggle button.
AnimatedImageTouchButton
typedef AnimatedImageButtonStyle<TouchButtonTrigger> AnimatedImageTouchButton
Defines an alias representing the animated image touch button.
BitmapId
typedef uint16_t BitmapId
This type shall be used by the application to define unique IDs for all bitmaps in the system. The application shall define bitmap IDs in the range [0, number of bitmaps - 1].
BoxClickButton
typedef BoxWithBorderButtonStyle<ClickButtonTrigger> BoxClickButton
Defines an alias representing the box click button.
BoxRepeatButton
typedef BoxWithBorderButtonStyle<RepeatButtonTrigger> BoxRepeatButton
Defines an alias representing the box repeat button.
BoxToggleButton
typedef BoxWithBorderButtonStyle<ToggleButtonTrigger> BoxToggleButton
Defines an alias representing the box toggle button.
BoxTouchButton
typedef BoxWithBorderButtonStyle<TouchButtonTrigger> BoxTouchButton
Defines an alias representing the box touch button.
EasingEquation
typedef int16_t(* EasingEquation) (uint16_t, int16_t, int16_t, uint16_t)
This function pointer typedef matches the signature for all easing equations. Thereby EasingEquation is a convenient shorthand for a pointer to any easing equation.
fixed16_16
typedef int32_t fixed16_16
A fixed point value using 16 bits for the decimal part and 16 bits for the integral part.
fixed28_4
typedef int32_t fixed28_4
A fixed point value using 4 bits for the decimal part and 28 bits for the integral part.
FontId
typedef uint16_t FontId
Defines an alias representing a Font ID.
IconClickButton
typedef IconButtonStyle<ClickButtonTrigger> IconClickButton
Defines an alias representing the icon click button.
IconImageClickButton
typedef ImageButtonStyle<IconButtonStyle<ClickButtonTrigger> > IconImageClickButton
Defines an alias representing the icon image click button.
IconImageRepeatButton
typedef ImageButtonStyle<IconButtonStyle<RepeatButtonTrigger> > IconImageRepeatButton
Defines an alias representing the icon image repeat button.
IconImageToggleButton
typedef ImageButtonStyle<IconButtonStyle<ToggleButtonTrigger> > IconImageToggleButton
Defines an alias representing the icon image toggle button.
IconImageTouchButton
typedef ImageButtonStyle<IconButtonStyle<TouchButtonTrigger> > IconImageTouchButton
Defines an alias representing the icon image touch button.
IconRepeatButton
typedef IconButtonStyle<RepeatButtonTrigger> IconRepeatButton
Defines an alias representing the icon repeat button.
IconToggleButton
typedef IconButtonStyle<ToggleButtonTrigger> IconToggleButton
Defines an alias representing the icon toggle button.
IconTouchButton
typedef IconButtonStyle<TouchButtonTrigger> IconTouchButton
Defines an alias representing the icon touch button.
ImageClickButton
typedef ImageButtonStyle<ClickButtonTrigger> ImageClickButton
Defines an alias representing the image click button.
ImageRepeatButton
typedef ImageButtonStyle<RepeatButtonTrigger> ImageRepeatButton
Defines an alias representing the image repeat button.
ImageToggleButton
typedef ImageButtonStyle<ToggleButtonTrigger> ImageToggleButton
Defines an alias representing the image toggle button.
ImageTouchButton
typedef ImageButtonStyle<TouchButtonTrigger> ImageTouchButton
Defines an alias representing the image touch button.
LanguageId
typedef uint16_t LanguageId
Language IDs generated by the text converter are uint16_t typedef'ed.
RenderingVariant
typedef uint16_t RenderingVariant
Describes a combination of rendering algorithm, image format, and alpha information. The lowest bit is 0 for "Nearest neighbor", 1 for "Bilinear". The next bit is "0" for "no alpha", "2" for "alpha". The rest is the Bitmap::Format shifted up by 2.
TextClickButton
typedef TextButtonStyle<ClickButtonTrigger> TextClickButton
Defines an alias representing the text click button.
TextDirection
typedef uint8_t TextDirection
Defines a the direction to write text.
TextRepeatButton
typedef TextButtonStyle<RepeatButtonTrigger> TextRepeatButton
Defines an alias representing the text repeat button.
TextToggleButton
typedef TextButtonStyle<ToggleButtonTrigger> TextToggleButton
Defines an alias representing the text toggle button.
TextTouchButton
typedef TextButtonStyle<TouchButtonTrigger> TextTouchButton
Defines an alias representing the text touch button.
TiledImageClickButton
typedef TiledImageButtonStyle<ClickButtonTrigger> TiledImageClickButton
Defines an alias representing the tiled image click button.
TiledImageRepeatButton
typedef TiledImageButtonStyle<RepeatButtonTrigger> TiledImageRepeatButton
Defines an alias representing the tiled image repeat button.
TiledImageToggleButton
typedef TiledImageButtonStyle<ToggleButtonTrigger> TiledImageToggleButton
Defines an alias representing the tiled image toggle button.
TiledImageTouchButton
typedef TiledImageButtonStyle<TouchButtonTrigger> TiledImageTouchButton
Defines an alias representing the tiled image touch button.
TwoWildcardTextClickButton
typedef TwoWildcardTextButtonStyle<ClickButtonTrigger> TwoWildcardTextClickButton
Defines an alias representing the wildcard text click button.
TwoWildcardTextRepeatButton
typedef TwoWildcardTextButtonStyle<RepeatButtonTrigger> TwoWildcardTextRepeatButton
Defines an alias representing the wildcard text repeat button.
TwoWildcardTextToggleButton
typedef TwoWildcardTextButtonStyle<ToggleButtonTrigger> TwoWildcardTextToggleButton
Defines an alias representing the wildcard text toggle button.
TwoWildcardTextTouchButton
typedef TwoWildcardTextButtonStyle<TouchButtonTrigger> TwoWildcardTextTouchButton
Defines an alias representing the wildcard text touch button.
TypedTextId
typedef uint16_t TypedTextId
Text IDs as generated by the text converter are simple uint16_t typedefs.
WildcardTextClickButton
typedef WildcardTextButtonStyle<ClickButtonTrigger> WildcardTextClickButton
Defines an alias representing the wildcard text click button.
WildcardTextRepeatButton
typedef WildcardTextButtonStyle<RepeatButtonTrigger> WildcardTextRepeatButton
Defines an alias representing the wildcard text repeat button.
WildcardTextToggleButton
typedef WildcardTextButtonStyle<ToggleButtonTrigger> WildcardTextToggleButton
Defines an alias representing the wildcard text toggle button.
WildcardTextTouchButton
typedef WildcardTextButtonStyle<TouchButtonTrigger> WildcardTextTouchButton
Defines an alias representing the wildcard text touch button.
Enumeration Type Documentation
BlitOperations
enum BlitOperations
The Blit Operations.
Enumerator
BLIT_OP_COPY
Copy the source to the destination.
BLIT_OP_FILL
Fill the destination with color.
BLIT_OP_COPY_WITH_ALPHA
Copy the source to the destination using the given alpha.
BLIT_OP_FILL_WITH_ALPHA
Fill the destination with color using the given alpha.
BLIT_OP_COPY_WITH_TRANSPARENT_PIXELS
Deprecated, ignored. (Copy the source to the destination, but not the transparent pixels)
BLIT_OP_COPY_ARGB8888
Copy the source to the destination, performing per-pixel alpha blending.
BLIT_OP_COPY_ARGB8888_WITH_ALPHA
Copy the source to the destination, performing per-pixel alpha blending and blending the result with an image-wide alpha.
BLIT_OP_COPY_L8
Copy the L8 source to the destination using the given alpha.
BLIT_OP_COPY_A4
Copy 4-bit source text to destination, performing per-pixel alpha blending.
BLIT_OP_COPY_A8
Copy 8-bit source text to destination, performing per-pixel alpha blending.
BLIT_OP_COPY_16BIT
Copy 16-bit regardless of frame buffer format.
BLIT_OP_FILL_16BIT
Fill 16-bit regardless of frame buffer format.
{
    BLIT_OP_COPY = 1 << 0,
    BLIT_OP_FILL = 1 << 1,
    BLIT_OP_COPY_WITH_ALPHA = 1 << 2,
    BLIT_OP_FILL_WITH_ALPHA = 1 << 3,
    BLIT_OP_COPY_WITH_TRANSPARENT_PIXELS = 1 << 4,
    BLIT_OP_COPY_ARGB8888 = 1 << 5,
    BLIT_OP_COPY_ARGB8888_WITH_ALPHA = 1 << 6,
    BLIT_OP_COPY_L8 = 1 << 7,
    BLIT_OP_COPY_A4 = 1 << 8,
    BLIT_OP_COPY_A8 = 1 << 9,
    BLIT_OP_COPY_16BIT = 1 << 10,
    BLIT_OP_FILL_16BIT = 1 << 11
};
Direction
enum Direction
Values that represent directions.
Enumerator
NORTH
An enum constant representing the north option.
SOUTH
An enum constant representing the south option.
EAST
An enum constant representing the east option.
WEST
An enum constant representing the west option.
{
    NORTH,
    SOUTH,
    EAST,
    WEST
};
DisplayOrientation
enum DisplayOrientation
Values that represent display orientations.
Enumerator
ORIENTATION_LANDSCAPE
The display has more pixels from left to right than from top to bottom.
ORIENTATION_PORTRAIT
The display has more pixels from top to bottom than from right to left.
{
    ORIENTATION_LANDSCAPE,
    ORIENTATION_PORTRAIT
};
DisplayRotation
enum DisplayRotation
Values that represent display rotations.
Enumerator
rotate0
The display is oriented like the framebuffer.
rotate90
The display is rotated 90 degrees compared to the framebuffer layout.
{
    rotate0,
    rotate90
};
DMAType
enum DMAType
Values that represent dma types.
Enumerator
DMA_TYPE_GENERIC
Generic DMA Implementation.
DMA_TYPE_CHROMART
ChromART hardware DMA Implementation.
{
    DMA_TYPE_GENERIC,
    DMA_TYPE_CHROMART
};
FrameBuffer
enum FrameBuffer
Values that represent frame buffers.
Enumerator
FB_PRIMARY
First framebuffer.
FB_SECONDARY
Second framebuffer.
FB_TERTIARY
Third framebuffer.
{
    FB_PRIMARY,
    FB_SECONDARY,
    FB_TERTIARY
};
GlyphFlags
enum GlyphFlags
Glyph flag definitions.
Enumerator
GLYPH_DATA_KERNINGTABLEPOS_BIT8_10
The 8th, 9th and 10th bit of the kerningTablePos.
GLYPH_DATA_WIDTH_BIT8
The 9th bit of "width".
GLYPH_DATA_HEIGHT_BIT8
The 9th bit of "height".
GLYPH_DATA_TOP_BIT8
The 9th bit of "top".
GLYPH_DATA_TOP_BIT9
The sign bit of "top".
GLYPH_DATA_ADVANCE_BIT8
The 9th bit of "advance".
{
    GLYPH_DATA_KERNINGTABLEPOS_BIT8_10 = 0x07,
    GLYPH_DATA_WIDTH_BIT8 = 0x08,
    GLYPH_DATA_HEIGHT_BIT8 = 0x10,
    GLYPH_DATA_TOP_BIT8 = 0x20,
    GLYPH_DATA_TOP_BIT9 = 0x40,
    GLYPH_DATA_ADVANCE_BIT8 = 0x80
};
Gradient
enum Gradient
Values that represent gradients.
Enumerator
GRADIENT_HORIZONTAL
Horizontal gradient.
GRADIENT_VERTICAL
Vertical gradient.
{
    GRADIENT_HORIZONTAL,
    GRADIENT_VERTICAL
};
TextRotation
enum TextRotation
Values that represent text rotations.
Enumerator
TEXT_ROTATE_0
Text is written from left to right.
TEXT_ROTATE_90
Text is written from top to bottom.
TEXT_ROTATE_180
Text is written from right to left (upside down)
TEXT_ROTATE_270
Text is written bottom to top.
{
    TEXT_ROTATE_0,
    TEXT_ROTATE_90,
    TEXT_ROTATE_180,
    TEXT_ROTATE_270
};
VectorPrimitives
enum VectorPrimitives
A list of the vector graphics primitives.
See also
VectorRenderer::drawPath
Enumerator
VECTOR_PRIM_CLOSE
Close the path.
VECTOR_PRIM_MOVE
Move to a point.
VECTOR_PRIM_LINE
Line to a point from current position.
VECTOR_PRIM_HLINE
Horizontal line to a point from current position.
VECTOR_PRIM_VLINE
Vertical line to a point from current position.
VECTOR_PRIM_BEZIER_QUAD
Quadratic Bezier (1 control point) curve to a point from the current position.
VECTOR_PRIM_BEZIER_CUBIC
Cubic Bezier (2 control points) curve to a point from the current position.
{
    VECTOR_PRIM_CLOSE = 0,
    VECTOR_PRIM_MOVE = 1,
    VECTOR_PRIM_LINE = 2,
    VECTOR_PRIM_HLINE = 3,
    VECTOR_PRIM_VLINE = 4,
    VECTOR_PRIM_BEZIER_QUAD = 5,
    VECTOR_PRIM_BEZIER_CUBIC = 6
};
VGColorMode
enum VGColorMode
A list of coloring modes. Each shape can have 2 coloring modes. One for filling and one for stroking.
Enumerator
VG_NONE
No coloring.
VG_FIXED_COLOR
Color with a fixed color in the whole shape.
VG_LINEAR_GRADIENT
Color using a linear gradient.
{
    VG_NONE,
    VG_FIXED_COLOR,
    VG_LINEAR_GRADIENT
};
VGFillMode
enum VGFillMode
A list of vector graphics polygon filling modes.
Enumerator
VG_FILL_EVEN_ODD
Fill the paths using the even-odd filling rule.
VG_FILL_NON_ZERO
Fill the paths using the non-zero filling rule.
{
    VG_FILL_EVEN_ODD,
    VG_FILL_NON_ZERO
};
VGStrokeLineCap
enum VGStrokeLineCap
Values that represent the different ways stroke lines can end. Butt is a simpe cut off, Round is a half circle and Square extends the line by half stroke width.
Enumerator
VG_STROKE_LINECAP_BUTT
VG_STROKE_LINECAP_ROUND
VG_STROKE_LINECAP_SQUARE
{
    VG_STROKE_LINECAP_BUTT,
    VG_STROKE_LINECAP_ROUND,
    VG_STROKE_LINECAP_SQUARE
};
VGStrokeLineJoin
enum VGStrokeLineJoin
Values that represent the different ways strokes lines can be joined. Bevel is a simple cut off, Miter extends into a spike (possibly falling back to Bevel if the miter limit for the stroke is exceeded) and Round is a circle arc.
Enumerator
VG_STROKE_LINEJOIN_BEVEL
VG_STROKE_LINEJOIN_MITER
VG_STROKE_LINEJOIN_ROUND
{
    VG_STROKE_LINEJOIN_BEVEL,
    VG_STROKE_LINEJOIN_MITER,
    VG_STROKE_LINEJOIN_ROUND
};
WideTextAction
enum WideTextAction
Values that represent wide text actions.
Enumerator
WIDE_TEXT_NONE
Do nothing, simply cut the text in the middle of any character that extends beyond the width of the TextArea.
WIDE_TEXT_WORDWRAP
Wrap between words, no ellipsis, keep wrapping lines.
WIDE_TEXT_WORDWRAP_ELLIPSIS
Wrap between words, ellipsis anywhere "Very long t...".
WIDE_TEXT_WORDWRAP_ELLIPSIS_AFTER_SPACE
Wrap between words, ellipsis only after space "Very long ...".
WIDE_TEXT_CHARWRAP
Wrap between any two characters, no ellipsis, keep wrapping lines.
WIDE_TEXT_CHARWRAP_ELLIPSIS
Wrap between any two characters, ellipsis anywhere, as used in Chinese.
WIDE_TEXT_CHARWRAP_DOUBLE_ELLIPSIS
Wrap between any two characters, double ellipsis anywhere, as used in Chinese.
{
    WIDE_TEXT_NONE,
    WIDE_TEXT_WORDWRAP,
    WIDE_TEXT_WORDWRAP_ELLIPSIS,
    WIDE_TEXT_WORDWRAP_ELLIPSIS_AFTER_SPACE,
    WIDE_TEXT_CHARWRAP,
    WIDE_TEXT_CHARWRAP_ELLIPSIS,
    WIDE_TEXT_CHARWRAP_DOUBLE_ELLIPSIS
};
Function Documentation
abs()
template<typename T > T abs (T d)
Simple implementation of the standard abs function.
Template Parameters
T The type on which to perform the abs.
Parameters
d The entity on which to perform the abs.
Returns
The absolute (non-negative) value of d.
{
    return (d < 0) ? -d : d;
}
Referenced by ScrollBase::animateToPosition(), GraphElementGridBase::draw(), Circle::drawCanvasWidget(), AbstractDataGraph::getNearestIndexForScreenX(), ScrollList::getPositionForItem(), ScrollWheelBase::getPositionForItem(), ScrollableContainer::handleDragEvent(), ScrollableContainer::handleGestureEvent(), ScrollBase::handleGestureEvent(), Line::invalidateContent(), CWRUtil::length(), Canvas::recursiveCubicBezier(), Canvas::recursiveQuadraticBezier(), GraphElementGridBase::setInterval(), GraphElementGridBase::setInterval(), GraphElementGridBase::setIntervalScaled(), GraphLabelsBase::setIntervalScaled(), CWRVectorRenderer::StrokeCanvas::setStroke(), BoxProgress::setValue(), ImageProgress::setValue(), Gauge::setValue(), and Line::updateCachedShape().
alphaBlend()
static FORCE_INLINE_FUNCTION uint16_t alphaBlend (uint16_t R, uint16_t G, uint16_t B, uint16_t bufpix, uint8_t alpha) static
{
    const uint8_t ialpha = 0xFF - alpha;
    return (((R * alpha + (bufpix & RMASK) * ialpha) / 255) & RMASK) |
           (((G * alpha + (bufpix & GMASK) * ialpha) / 255) & GMASK) |
           (((B * alpha + (bufpix & BMASK) * ialpha) / 255) & BMASK);
}
References BMASK, GMASK, and RMASK.
Referenced by PainterRGB565LinearGradient::paint().
applyNoise()
static uint16_t applyNoise (int x, int y, uint8_t r, uint8_t g, uint8_t b) static
{
    const uint16_t rounding = random(x, y);
    if (r < 0xF8)
    {
        r += rounding & 7;
    }
    if (g < 0xFC)
    {
        g += (rounding >> 3) & 3;
    }
    if (b < 0xF8)
    {
        b += (rounding >> 5) & 7;
    }
    return getNativeColorFromRGB(r, g, b);
}
References getNativeColorFromRGB(), and random().
Referenced by PainterRGB565LinearGradient::paint().
ceil28_4()
FORCE_INLINE_FUNCTION int32_t ceil28_4 (fixed28_4 value)
Round up a fixed28_4 value.
Parameters
value The fixed28_4 value.
Returns
The ceil result.
{
    int32_t returnValue;
    int32_t numerator = value - 1 + 16;
    if (numerator >= 0)
    {
        returnValue = numerator / 16;
    }
    else
    {
        // Deal with negative numerators correctly
        returnValue = -((-numerator) / 16);
        returnValue -= ((-numerator) % 16) ? 1 : 0;
    }
    return returnValue;
}
clz()
int32_t clz (int32_t x)
Count leading zeros in the binary representation of absolute value of the given int32_t.
Parameters
x The value to count the number of leading zeros in.
Returns
The number of leading zeros (from 0 to 31).
See also
clzu
clzu()
int32_t clzu (uint32_t x)
Count leading zeros in the binary representation of absolute value of the given uint32_t.
Parameters
x The value to count the number of leading zeros in.
Returns
The number of leading zeros (from 0 to 32).
See also
clz
fillBits()
void fillBits (uint8_t * fb, int16_t startX, int16_t startY, int16_t stride, int32_t count, uint8_t color)
Referenced by PainterBWBitmap::paint().
finalizeTransition()
static FORCE_INLINE_FUNCTION void finalizeTransition (Screen * newScreen, Presenter * newPresenter, Transition * newTransition) static
Finalize screen transition. Private helper function for makeTransition. Do not use.
Parameters
[in] newScreen If non-null, the new screen.
[in] newPresenter If non-null, the new presenter.
[in] newTransition If non-null, the new transition.
{
    newScreen->setupScreen();
    newPresenter->activate();
    newScreen->bindTransition(*newTransition);
    newTransition->init();
    newTransition->invalidate();
}
Referenced by makeTransition().
fixed28_4Mul()
FORCE_INLINE_FUNCTION fixed28_4 fixed28_4Mul (fixed28_4 a, fixed28_4 b)
Multiply two fixed28_4 numbers.
Parameters
a The fixed28_4 to process.
b The fixed28_4 to process.
Returns
the result.
{
    if (a == 0 || b == 0)
    {
        return 0;
    }
    if ((a * b) / b == a)
    {
        return (a * b) / 16;
    }
    // Rewrite "b = max_b * num_max_b + rem_b" so that a * max_b does not overflow.
    int sign = 1;
    if (b < 0)
    {
        sign = -sign;
        b = -b;
    }
    if (a < 0)
    {
        sign = -sign;
        a = -a;
    }
    if (a < b)
    {
        fixed28_4 tmp = a;
        a = b;
        b = tmp;
    }
    int32_t max_b = 0x7FFFFFFF / a;        // Max b value that can be multiplied with a without overflow
    int32_t num_max_b = b / max_b;         // How many times do we have to multiply with "max_b" to get to "b"
    int32_t rem_b = b - max_b * num_max_b; // plus some remainder.
    int32_t max_prod = a * max_b;
    int32_t result = sign * (num_max_b * (max_prod / 16) + (num_max_b * (max_prod % 16) + rem_b * a) / 16);
    return result;
}
References sign().
fixed28_4ToFloat()
FORCE_INLINE_FUNCTION float fixed28_4ToFloat (fixed28_4 value)
Convert fixed28_4 to float.
Parameters
value The fixed28_4 value.
Returns
The value as float.
{
    return (float)value / 16.0f;
}
floatToFixed16_16()
FORCE_INLINE_FUNCTION fixed16_16 floatToFixed16_16 (float value)
Convert float to fixed16_16.
Parameters
value The float value.
Returns
The value as fixed16_16.
{
    return (fixed16_16)(value * 65536);
}
Referenced by LCD::DrawTextureMapScanLineBase::drawTextureMapNextSubdivision().
floatToFixed28_4()
FORCE_INLINE_FUNCTION fixed28_4 floatToFixed28_4 (float value)
Convert float to fixed28_4.
Parameters
value The float value.
Returns
The value as fixed28_4.
{
    return (fixed28_4)(value * 16);
}
Referenced by TextureMapper::drawQuad().
floorDivMod()
FORCE_INLINE_FUNCTION void floorDivMod (int32_t numerator, int32_t denominator, int32_t & floor, int32_t & mod)
Divides two fixed28_4 numbers and returns the result as well as the remainder.
Parameters
numerator The numerator.
denominator The denominator.
[out] floor numerator/denominator.
[out] mod numerator%denominator.
{
    assert(denominator > 0); // We assume it's positive
    if (numerator >= 0)
    {
        // Positive case, C is okay
        floor = numerator / denominator;
        mod = numerator % denominator;
    }
    else
    {
        // Numerator is negative, do the right thing
        floor = -((-numerator) / denominator);
        mod = (-numerator) % denominator;
        if (mod)
        {
            // There is a remainder
            floor--;
            mod = denominator - mod;
        }
    }
}
FrameBufferAllocatorSignalBlockDrawn()
void FrameBufferAllocatorSignalBlockDrawn ()
Called by FrameBufferAllocator when a block is drawn and therefore ready for transfer. The LCD driver should use this method to start a transfer.
{
    // Signal transfer part
    if (SDL_SemValue(sem_transfer_ready) == 0)
    {
        SDL_SemPost(sem_transfer_ready);
    }
}
References SDL_SemPost(), SDL_SemValue(), and sem_transfer_ready.
Referenced by ManyBlockAllocator< block_size, blocks, bytes_pr_pixel >::markBlockReadyForTransfer().
FrameBufferAllocatorWaitOnTransfer()
void FrameBufferAllocatorWaitOnTransfer ()
Called by FrameBufferAllocator to wait for a LCD Transfer, when the allocator has no free blocks. The LCD driver can use this function to synchronize the UI thread with the transfer logic.
{
    SDL_SemWait(sem_transfer_done);
}
References SDL_SemWait(), and sem_transfer_done.
Referenced by ManyBlockAllocator< block_size, blocks, bytes_pr_pixel >::allocateBlock(), and HALSDL2::setTFTFrameBuffer().
gcd()
template<typename T > T gcd (T a, T b)
Find greatest common divisor of two given numbers.
Template Parameters
T Generic type parameter.
Parameters
a The first number.
b The second number.
Returns
The greatest common divisor.
{
    for (;;)
    {
        if (a == 0)
        {
            return b;
        }
        b %= a;
        if (b == 0)
        {
            return a;
        }
        a %= b;
    }
}
Referenced by Line::updateCachedShape().
getNativeColor()
static FORCE_INLINE_FUNCTION uint16_t getNativeColor (colortype color) static
{
    return ((color >> 8) & 0xF800) | ((color >> 5) & 0x07E0) | ((color >> 3) & 0x001F);
}
Referenced by PainterRGB565LinearGradient::paint().
getNativeColorFromRGB()
static FORCE_INLINE_FUNCTION uint16_t getNativeColorFromRGB (uint8_t red, uint8_t green, uint8_t blue) static
{
    return ((red << 8) & 0xF800) | ((green << 3) & 0x07E0) | ((blue >> 3) & 0x001F);
}
Referenced by applyNoise().
hw_init()
void hw_init ()
Function to perform generic hardware initialization of the board. This function prototype is only provided as a convention.
lookupBilinearRenderVariant()
RenderingVariant lookupBilinearRenderVariant (const Bitmap & bitmap)
Returns the associated bilinear render variant based on the bitmap format. This is used for quick determination of the type of bitmap during TextureMapper drawing.
Parameters
bitmap The bitmap.
Returns
A RenderingVariant based on the bitmap format.
Referenced by TextureMapper::lookupRenderVariant().
lookupNearestNeighborRenderVariant()
RenderingVariant lookupNearestNeighborRenderVariant (const Bitmap & bitmap)
Returns the associated nearest neighbor render variant based on the bitmap format. This is used for quick determination of the type of bitmap during TextureMapper drawing.
Parameters
bitmap The bitmap.
Returns
A RenderingVariant based on the bitmap format.
Referenced by TextureMapper::lookupRenderVariant().
makeTransition()
template<class ScreenType , class PresenterType , class TransType , class ModelType > PresenterType * makeTransition (Screen ** currentScreen, Presenter ** currentPresenter, MVPHeap & heap, Transition ** currentTrans, ModelType * model)
Function for effectuating a screen transition (i.e. makes the requested new presenter/view pair active). Once this function has returned, the new screen has been transitioned to. Due to the memory allocation strategy of using the same memory area for all screens, the old view/presenter will no longer exist when this function returns.
Will properly clean up old screen (tearDownScreen, Presenter::deactivate) and call setupScreen/activate on new view/presenter pair. Will also make sure the view, presenter and model are correctly bound to each other.
Template Parameters
ScreenType Class type for the View.
PresenterType Class type for the Presenter.
TransType Class type for the Transition.
ModelType Class type for the Model.
Parameters
[in] currentScreen Pointer to pointer to the current view.
[in] currentPresenter Pointer to pointer to the current presenter.
[in] heap Reference to the heap containing the memory storage in which to allocate.
[in] currentTrans Pointer to pointer to the current transition.
[in] model Pointer to model.
Returns
Pointer to the new Presenter of the requested type. Incidentally it will be the same value as the old presenter due to memory reuse.
{
    assert(sizeof(ScreenType) <= heap.screenStorage.element_size() && "View allocation error: Check that all views are added to FrontendHeap::ViewTypes");
    assert(sizeof(PresenterType) <= heap.presenterStorage.element_size() && "Presenter allocation error: Check that all presenters are added to FrontendHeap::PresenterTypes");
    assert(sizeof(TransType) <= heap.transitionStorage.element_size() && "Transition allocation error: Check that all transitions are added to FrontendHeap::TransitionTypes");
    prepareTransition(currentScreen, currentPresenter, currentTrans);
    TransType* newTransition = new (&heap.transitionStorage.at<TransType>(0)) TransType;
    ScreenType* newScreen = new (&heap.screenStorage.at<ScreenType>(0)) ScreenType;
    PresenterType* newPresenter = new (&heap.presenterStorage.at<PresenterType>(0)) PresenterType(*newScreen);
    *currentTrans = newTransition;
    *currentPresenter = newPresenter;
    *currentScreen = newScreen;
    model->bind(newPresenter);
    newPresenter->bind(model);
    newScreen->bind(*newPresenter);
    finalizeTransition((Screen*)newScreen, (Presenter*)newPresenter, (Transition*)newTransition);
    return newPresenter;
}
References finalizeTransition(), and prepareTransition().
memset()
void memset (void * data, uint8_t c, uint32_t size)
Simple implementation of the standard memset function. Will write the value of 'c' in 'size' consecutive bytes starting from 'data'.
Parameters
[out] data Address of data to set.
c Value to set.
size Number of bytes to set.
Referenced by FontCache::clear(), and HALSDL2::copyScreenshotToClipboard().
muldiv() [1/2]
int32_t muldiv (int32_t factor1, int32_t factor2, int32_t divisor)
Multiply and divide without causing overflow. Multiplying two large values and subsequently dividing the result with another large value might cause an overflow in the intermediate result. The function muldiv() will multiply factor1 and factor2 and divide the result by divisor without causing overflow (unless the final result would overflow). The remainder is used to round the result up or down.
Parameters
factor1 The first factor.
factor2 The second factor.
divisor The divisor.
Returns
(factor1 * factor2) / divisor rounded.
See also
muldiv(int32_t,int32_t,int32_t,int32_t&)
muldiv() [2/2]
int32_t muldiv (int32_t factor1, int32_t factor2, int32_t divisor, int32_t & remainder)
Multiply and divide without causing overflow. Multiplying two large values and subsequently dividing the result with another large value might cause an overflow in the intermediate result. The function muldiv() will multiply factor1 and factor2 and divide the result by divisor without causing overflow (unless the final result would overflow). The remainder from the division is returned.
Parameters
factor1 The first factor.
factor2 The second factor.
divisor The divisor.
[out] remainder The remainder.
Returns
(factor1 * factor2) / divisor.
See also
muldivu
Note
For large numbers close to the limit of int32_t, the calculation may not be correct.
Referenced by CWRUtil::_angle(), AbstractDataGraph::convertToNewScale(), AbstractProgressIndicator::getProgress(), ScrollBase::handleDragEvent(), CWRUtil::muldiv_toQ5(), CWRUtil::muldivQ10(), CWRUtil::muldivQ5(), CWRUtil::Q5::operator*(), Slider::positionToValue(), CWRUtil::sine(), and Slider::valueToPosition().
muldivu()
uint32_t muldivu (uint32_t factor1, uint32_t factor2, uint32_t divisor, uint32_t & remainder)
Multiply and divide without causing overflow. Multiplying two large values and subsequently dividing the result with another large value might cause an overflow in the intermediate result. The function muldiv() will multiply factor1 and factor2 and divide the result by divisor without causing overflow (unless the final result would overflow). The remainder from the division is returned.
Parameters
factor1 The first factor.
factor2 The second factor.
divisor The divisor.
[out] remainder The remainder.
Returns
(factor1 * factor2) / divisor.
See also
muldiv
Note
For large numbers close to the limit of uint32_t, the calculation may not be correct.
myTimerCallback2()
Uint32 myTimerCallback2 (Uint32 interval, void * param)
{
    SDL_Event event;
    SDL_UserEvent userevent;
    /* In this example, our callback pushes an SDL_USEREVENT event
     * into the queue, and causes ourself to be called again at the
     * same interval: */
    userevent.type = static_cast<Uint32>(SDL_USEREVENT);
    userevent.code = 0;
    userevent.data1 = 0;
    userevent.data2 = 0;
    event.type = static_cast<Uint32>(SDL_USEREVENT);
    event.user = userevent;
    SDL_PushEvent(&event);
    return interval;
}
References SDL_PushEvent(), and SDL_USEREVENT.
operator*() [1/2]
Matrix4x4 operator* (const Matrix4x4 & multiplicand, const Matrix4x4 & multiplier)
Multiplication operator.
Parameters
multiplicand The first value to multiply.
multiplier The second value to multiply.
Returns
The result of the operation.
operator*() [2/2]
Point4 operator* (const Matrix4x4 & multiplicand, const Point4 & multiplier)
Multiplication operator.
Parameters
multiplicand The first value to multiply.
multiplier The second value to multiply.
Returns
The result of the operation.
prepareTransition()
static FORCE_INLINE_FUNCTION void prepareTransition (Screen ** currentScreen, Presenter ** currentPresenter, Transition ** currentTrans) static
Prepare screen transition. Private helper function for makeTransition. Do not use.
Parameters
[in] currentScreen If non-null, the current screen.
[in] currentPresenter If non-null, the current presenter.
[in] currentTrans If non-null, the current transaction.
{
    Application::getInstance()->clearAllTimerWidgets();
    if (*currentTrans)
    {
        (*currentTrans)->tearDown();
    }
    if (*currentTrans)
    {
        (*currentTrans)->~Transition();
    }
    if (*currentScreen)
    {
        (*currentScreen)->tearDownScreen();
    }
    if (*currentPresenter)
    {
        (*currentPresenter)->deactivate();
    }
    if (*currentScreen)
    {
        (*currentScreen)->~Screen();
    }
    if (*currentPresenter)
    {
        (*currentPresenter)->~Presenter();
    }
}
References Application::getInstance().
Referenced by makeTransition().
random()
static uint16_t random (int x, int y) static
{
    const long long int a = 15485863LL * (static_cast<long long int>(x) * static_cast<long long int>(y));
    return (a * a * a % 2038074743LL) & 0xFFFF;
}
Referenced by applyNoise().
sdlCleanup2()
static void sdlCleanup2 () static
{
#if defined(WIN32) || defined(_WIN32)
    if (mainThreadHandle == GetCurrentThreadId())
#endif
    {
        if (sdl_initialized)
        {
            if (tft_display24_allocated)
            {
                delete tft_display24;
                tft_display24 = NULL;
                tft_display24_allocated = false;
            }
            if (tft_framebuffer24_allocated)
            {
                delete[] tft_framebuffer24;
                tft_framebuffer24 = NULL;
                tft_framebuffer24_allocated = false;
            }
            if (single_buf)
            {
                delete[] single_buf;
                single_buf = NULL;
            }
            if (double_buf)
            {
                delete[] double_buf;
                double_buf = NULL;
            }
            if (anim_store)
            {
                delete[] anim_store;
                anim_store = NULL;
            }
            if (sem_transfer_ready)
            {
                SDL_DestroySemaphore(sem_transfer_ready);
                sem_transfer_ready = 0;
            }
            if (sem_transfer_done)
            {
                SDL_DestroySemaphore(sem_transfer_done);
                sem_transfer_done = 0;
            }
            sdl_initialized = false; // Make sure we don't get in here again
            SDL_DestroyRenderer(simulatorRenderer);
            SDL_DestroyWindow(simulatorWindow);
            SDL_VideoQuit();
            SDL_Quit();
        }
    }
}
References anim_store, double_buf, NULL, SDL_DestroyRenderer(), SDL_DestroySemaphore(), SDL_DestroyWindow(), sdl_initialized, SDL_Quit(), SDL_VideoQuit(), sem_transfer_done, sem_transfer_ready, simulatorRenderer, simulatorWindow, single_buf, tft_display24, tft_display24_allocated, tft_framebuffer24, and tft_framebuffer24_allocated.
Referenced by HALSDL2::sdl_init().
shouldTransferBlock()
int shouldTransferBlock (uint16_t bottom)
Check if a Frame Buffer Block ending at bottom may be sent.
Parameters
bottom The bottom coordinate of the block to transfer.
Returns
Non zero if possible.
sign()
template<typename T > T sign (T d)
Simple implementation of the standard sign function.
Template Parameters
T The type on which to perform the sign.
Parameters
d The entity on which to perform the sign.
Returns
-1, +1 or 0 depending on the sign of the given value of d.
{
    return (d < 0) ? -1 : ((d > 0) ? 1 : 0);
}
Referenced by fixed28_4Mul().
simulator_enable_stdio()
void simulator_enable_stdio ()
Simulator enable stdio.
{
#ifdef __GNUC__
#define freopen_s(pFile, filename, mode, pStream) (((*(pFile)) = freopen((filename), (mode), (pStream))) == NULL)
#endif
    HALSDL2* hal = static_cast<HALSDL2*>(HAL::getInstance());
    if (hal->getConsoleVisible())
    {
        HWND consoleHwnd = GetConsoleWindow(); // Get handle of console window
        if (!consoleHwnd)                      // No console window yet?
        {
            HWND activeHwnd = GetActiveWindow(); // Remember which window is active
            AllocConsole(); // Allocate a new console
            isConsoleAllocated = true;
            consoleHwnd = GetConsoleWindow(); // Get handle of console window
            FILE* dummy;
            freopen_s(&dummy, "CONIN$", "r", stdin); // Redirect stdin/stdout/stderr to the new console
            freopen_s(&dummy, "CONOUT$", "w", stdout);
            freopen_s(&dummy, "CONOUT$", "w", stderr);
            SwitchToThisWindow(activeHwnd, true); // Switch back to the originally active window
        }
        if (consoleHwnd)
        {
            ShowWindow(consoleHwnd, SW_SHOW); // Show/hide it!
        }
    }
    else
    {
        HWND consoleHwnd = GetConsoleWindow(); // Get handle of console window
        if (consoleHwnd && isConsoleAllocated)
        {
            ShowWindow(consoleHwnd, SW_HIDE);
        }
    }
}
References dummy, HAL::getInstance(), hal(), and isConsoleAllocated.
Referenced by HALSDL2::setConsoleVisible(), HALSDL2::setWindowVisible(), and simulator_printf().
simulator_printf()
void simulator_printf (const char * format, va_list pArg)
Simulator printf.
Parameters
format Describes the format to use.
pArg The argument list.
{
    // Create a console window, if window is visible.
    simulator_enable_stdio();
    if (GetConsoleWindow())
    {
        vprintf(format, pArg);
    }
    HALSDL2* hal = static_cast<HALSDL2*>(HAL::getInstance());
    if (hal && hal->getPrintFile())
    {
        vfprintf(hal->getPrintFile(), format, pArg);
    }
}
References HAL::getInstance(), hal(), and simulator_enable_stdio().
touchgfx_generic_init()
template<class HALType > HAL & touchgfx_generic_init (DMA_Interface & dma, LCD & display, TouchController & tc, int16_t width, int16_t height, uint16_t * bitmapCache, uint32_t bitmapCacheSize, uint32_t numberOfDynamicBitmaps = 0)
@globalfn TouchGFX generic initialize.
Template Parameters
HALType The class type of the HAL subclass used for this port.
Parameters
[in] dma Reference to the DMA implementation object to use. Can be of type NoDMA to disable the use of DMA for rendering.
[in] display Reference to the LCD renderer implementation (subclass of LCD). Could be either LCD16bpp for RGB565 UIs, or LCD1bpp for monochrome UIs or LCD24bpp for 24bit displays using RGB888 UIs.
[in] tc Reference to the touch controller driver (or NoTouchController to disable touch input).
width The native display width of the actual display, in pixels. This value is irrespective of whether the concrete UI should be portrait or landscape mode. It must match what the display itself is configured as.
height The native display height of the actual display, in pixels. This value is irrespective of whether the concrete UI should be portrait or landscape mode. It must match what the display itself is configured as.
[in] bitmapCache Optional pointer to starting address of a memory region in which to place the bitmap cache. Usually in external RAM. Pass 0 if bitmap caching is not used.
bitmapCacheSize Size of bitmap cache in bytes. Pass 0 if bitmap cache is not used.
numberOfDynamicBitmaps (Optional) Number of dynamic bitmaps.
Returns
A reference to the allocated (and initialized) HAL object.
{
    HAL& hal = getHAL<HALType>(dma, display, tc, width, height);
    hal.initialize();
    Bitmap::registerBitmapDatabase(BitmapDatabase::getInstance(),
                                   BitmapDatabase::getInstanceSize(),
                                   bitmapCache,
                                   bitmapCacheSize,
                                   numberOfDynamicBitmaps);
    TypedText::registerTexts(&texts);
    Texts::setLanguage(0);
    FontManager::setFontProvider(&fontProvider);
    FrontendHeap::getInstance(); // We need to initialize the frontend heap.
    hal.registerEventListener(*(Application::getInstance()));
    return hal;
}
References display, dma, fontProvider, Application::getInstance(), BitmapDatabase::getInstance(), FrontendHeap::getInstance(), BitmapDatabase::getInstanceSize(), hal(), Bitmap::registerBitmapDatabase(), TypedText::registerTexts(), FontManager::setFontProvider(), Texts::setLanguage(), and texts.
touchgfx_init()
void touchgfx_init (void)
Function to perform touchgfx initialization. This function prototype is only provided as a convention.
{
    Bitmap::registerBitmapDatabase(BitmapDatabase::getInstance(), BitmapDatabase::getInstanceSize());
    TypedText::registerTexts(&texts);
    Texts::setLanguage(0);
    display.setVectorFontRenderer(&vectorFontRenderer);
    FontManager::setFontProvider(&fontProvider);
    FrontendHeap& heap = FrontendHeap::getInstance();
    /*
     * we need to obtain the reference above to initialize the frontend heap.
     */
    (void)heap;
    /*
     * Initialize TouchGFX
     */
    hal.initialize();
}
References display, fontProvider, BitmapDatabase::getInstance(), FrontendHeap::getInstance(), BitmapDatabase::getInstanceSize(), hal(), Bitmap::registerBitmapDatabase(), TypedText::registerTexts(), FontManager::setFontProvider(), Texts::setLanguage(), texts, vectorFontRenderer, and void().
transferThreadFunc()
static int transferThreadFunc (void * ptr) static
{
    FrameBufferAllocator* fbAllocator = HAL::getInstance()->getFrameBufferAllocator();
    Bitmap::BitmapFormat framebufferFormat = HAL::getInstance()->lcd().framebufferFormat();
    while (1)
    {
        // Wait for blocks to transfer
        SDL_SemWait(sem_transfer_ready);
        while (fbAllocator->hasBlockReadyForTransfer())
        {
            Rect transfer_rect;
            const uint8_t* src = fbAllocator->getBlockForTransfer(transfer_rect);
            // touchgfx_printf("transfer: (%d,%d w%d,h%d)\n", transfer_rect.x, transfer_rect.y, transfer_rect.width, transfer_rect.height);
            switch (framebufferFormat)
            {
            case Bitmap::RGB565:
                {
                    const uint16_t* src16 = (const uint16_t*)src;
                    uint16_t* dst16 = tft + transfer_rect.y * HALSDL2__FRAME_BUFFER_WIDTH + transfer_rect.x;
                    for (int srcY = 0; srcY < transfer_rect.height; srcY++)
                    {
                        for (int srcX = 0; srcX < transfer_rect.width; srcX++)
{
                            *dst16++ = *src16++;
                        }
                        dst16 += HALSDL2__FRAME_BUFFER_WIDTH - transfer_rect.width;
                    }
                    break;
                }
            case Bitmap::RGB888:
                {
                    uint8_t* dst = (uint8_t*)tft + (transfer_rect.y * HALSDL2__FRAME_BUFFER_WIDTH + transfer_rect.x) * 3;
                    for (int srcY = 0; srcY < transfer_rect.height; srcY++)
                    {
                        for (int srcX = 0; srcX < transfer_rect.width; srcX++)
{
                            *dst++ = *src++;
                            *dst++ = *src++;
                            *dst++ = *src++;
                        }
                        dst += (HALSDL2__FRAME_BUFFER_WIDTH - transfer_rect.width) * 3;
                    }
                    break;
                }
            default:
                assert(!"HALSDL2::REFRESH_STRATEGY_PARTIAL_FRAMEBUFFER only supports 16bit or 24bit framebuffer");
                break;
            }
            fbAllocator->freeBlockAfterTransfer();
        }
        // Signal drawing part
        if (SDL_SemValue(sem_transfer_done) == 0)
        {
            SDL_SemPost(sem_transfer_done);
        }
    }
}
References HAL::getInstance(), HALSDL2__FRAME_BUFFER_WIDTH, Bitmap::RGB565, Bitmap::RGB888, SDL_SemPost(), SDL_SemValue(), SDL_SemWait(), sem_transfer_done, sem_transfer_ready, and tft.
Referenced by HALSDL2::sdl_init().
transmitActive()
int transmitActive ()
Check if a Frame Buffer Block is being transmitted.
Returns
Non zero if possible.
transmitBlock()
void transmitBlock (const uint8_t * pixels, uint16_t x, uint16_t y, uint16_t w, uint16_t h)
Transmit a Frame Buffer Block.
Parameters
pixels Pointer to the pixel data.
x X coordinate of the block.
y Y coordinate of the block.
w Width of the block.
h Height of the block.
Variable Documentation
anim_store
uint16_t* anim_store = NULL static
Referenced by sdlCleanup2(), and HALSDL2::setFrameBufferSize().
BITMAP_ANIMATION_STORAGE
const BitmapId BITMAP_ANIMATION_STORAGE = 0xFFFEU
A virtual id representing animation storage.
Referenced by SnapshotWidget::makeSnapshot().
BITMAP_INVALID
const BitmapId BITMAP_INVALID = 0xFFFFU
Define the bitmapId of an invalid bitmap.
Referenced by Button::draw(), ButtonWithIcon::draw(), RadioButton::draw(), SnapshotWidget::draw(), SnapshotWidget::getSolidRect(), CacheableContainer::invalidateRect(), SnapshotWidget::makeSnapshot(), PainterABGR2222Bitmap::setBitmap(), PainterARGB2222Bitmap::setBitmap(), PainterARGB8888Bitmap::setBitmap(), PainterARGB8888L8Bitmap::setBitmap(), PainterBGRA2222Bitmap::setBitmap(), PainterBWBitmap::setBitmap(), PainterGRAY2Bitmap::setBitmap(), PainterGRAY4Bitmap::setBitmap(), PainterRGB565Bitmap::setBitmap(), PainterRGB565L8Bitmap::setBitmap(), PainterRGB888Bitmap::setBitmap(), PainterRGB888L8Bitmap::setBitmap(), PainterRGBA2222Bitmap::setBitmap(), PainterXRGB8888Bitmap::setBitmap(), PainterXRGB8888L8Bitmap::setBitmap(), CacheableContainer::setCacheBitmap(), SwipeContainer::PageIndicator::setNumberOfPages(), PainterABGR2222Bitmap::setup(), PainterARGB2222Bitmap::setup(), PainterARGB8888Bitmap::setup(), PainterARGB8888L8Bitmap::setup(), PainterBGRA2222Bitmap::setup(), PainterBWBitmap::setup(), PainterGRAY2Bitmap::setup(), PainterGRAY4Bitmap::setup(), PainterRGB565Bitmap::setup(), PainterRGB565L8Bitmap::setup(), PainterRGB888Bitmap::setup(), PainterRGB888L8Bitmap::setup(), PainterRGBA2222Bitmap::setup(), PainterXRGB8888Bitmap::setup(), PainterXRGB8888L8Bitmap::setup(), AnimatedImage::startAnimation(), and CacheableContainer::updateCache().
BMASK
const uint16_t BMASK = 0x001F
Referenced by touchgfx::paint::rgb565::alphaBlend(), touchgfx::paint::rgb565::alphaBlend(), alphaBlend(), touchgfx::paint::rgb565::lineFromARGB8888(), touchgfx::paint::rgb565::lineFromL8ARGB8888(), touchgfx::paint::rgb565::lineFromL8RGB888(), and PainterRGB565LinearGradient::paint().
CENTER
const Alignment CENTER = 1 static
Text is centered horizontally.
Referenced by TextArea::calculateBoundingArea(), Keyboard::draw(), and TextArea::resizeToCurrentTextWithAlignment().
dirty
Rect dirty static
Referenced by Box::draw(), BoxWithBorder::draw(), ButtonWithLabel::draw(), Button::draw(), ButtonWithIcon::draw(), GraphTitle::draw(), TiledImage::draw(), GraphElementDots::drawCanvasWidget(), GraphElementDiamonds::drawCanvasWidget(), GraphLabelsX::drawString(), GraphLabelsY::drawString(), HALSDL2::flushFrameBuffer(), GraphElementArea::invalidateGraphPointAt(), GraphElementLine::invalidateGraphPointAt(), GraphElementHistogram::invalidateGraphPointAt(), GraphElementBoxes::invalidateGraphPointAt(), GraphElementDots::invalidateGraphPointAt(), GraphElementDiamonds::invalidateGraphPointAt(), GraphLabelsX::invalidateGraphPointAt(), GraphElementVerticalGapLine::invalidateIndex(), and HALSDL2::setTFTFrameBuffer().
double_buf
uint16_t* double_buf = NULL static
Referenced by sdlCleanup2(), and HALSDL2::setFrameBufferSize().
framebufferLocked
bool framebufferLocked = false static
Referenced by OSWrappers::giveFrameBufferSemaphore(), OSWrappers::initialize(), and OSWrappers::takeFrameBufferSemaphore().
GMASK
const uint16_t GMASK = 0x07E0
Referenced by touchgfx::paint::rgb565::alphaBlend(), touchgfx::paint::rgb565::alphaBlend(), alphaBlend(), touchgfx::paint::rgb565::lineFromARGB8888(), touchgfx::paint::rgb565::lineFromL8ARGB8888(), touchgfx::paint::rgb565::lineFromL8RGB888(), and PainterRGB565LinearGradient::paint().
HALSDL2__FRAME_BUFFER_HEIGHT
uint16_t HALSDL2__FRAME_BUFFER_HEIGHT = 0 static
Referenced by HALSDL2::scaleTo24bpp(), and HALSDL2::setFrameBufferSize().
HALSDL2__FRAME_BUFFER_WIDTH
uint16_t HALSDL2__FRAME_BUFFER_WIDTH = 0 static
Referenced by HALSDL2::doRotate(), HALSDL2::scaleTo24bpp(), HALSDL2::setFrameBufferSize(), and transferThreadFunc().
isAlive
bool isAlive = true static
Referenced by HALSDL2::stopApplication(), and HALSDL2::taskEntry().
isConsoleAllocated
bool isConsoleAllocated = false static
Referenced by simulator_enable_stdio().
LEFT
const Alignment LEFT = 0 static
Text is left aligned.
Referenced by TextArea::calculateBoundingArea(), TextArea::getAlignment(), and TextArea::resizeToCurrentTextWithAlignment().
PI
const float PI = 3.14159265358979323846f static
PI.
Referenced by AnalogClock::convertHandValueToAngle(), Canvas::recursiveCubicBezier(), Canvas::recursiveQuadraticBezier(), Gauge::setValue(), and AnalogClock::updateClock().
RenderingVariant_Alpha
const uint16_t RenderingVariant_Alpha = 2 static
The rendering variant alpha bit value.
RenderingVariant_Bilinear
const uint16_t RenderingVariant_Bilinear = 1 static
The rendering variant bilinear bit value.
RenderingVariant_FormatShift
const uint16_t RenderingVariant_FormatShift = 2 static
The rendering variant format shift.
RenderingVariant_NearestNeighbor
const uint16_t RenderingVariant_NearestNeighbor = 0 static
The rendering variant nearest neighbor bit value.
RenderingVariant_NoAlpha
const uint16_t RenderingVariant_NoAlpha = 0 static
The rendering variant no alpha bit value.
RIGHT
const Alignment RIGHT = 2 static
Text is right aligned.
Referenced by TextArea::calculateBoundingArea(), and TextArea::resizeToCurrentTextWithAlignment().
RMASK
const uint16_t RMASK = 0xF800
Referenced by touchgfx::paint::rgb565::alphaBlend(), touchgfx::paint::rgb565::alphaBlend(), alphaBlend(), touchgfx::paint::rgb565::lineFromARGB8888(), touchgfx::paint::rgb565::lineFromL8ARGB8888(), touchgfx::paint::rgb565::lineFromL8RGB888(), and PainterRGB565LinearGradient::paint().
s_FrameBufferLock
SDL_mutex* s_FrameBufferLock = NULL static
Referenced by OSWrappers::deinitialize(), OSWrappers::giveFrameBufferSemaphore(), OSWrappers::initialize(), and OSWrappers::takeFrameBufferSemaphore().
screenshotcount
int screenshotcount = 0 static
Referenced by HALSDL2::saveNextScreenshots(), and HALSDL2::taskEntry().
sdl_initialized
bool sdl_initialized = false
Referenced by HALSDL2::loadSkin(), HALSDL2::sdl_init(), and sdlCleanup2().
sem_transfer_done
SDL_sem* sem_transfer_done = 0 static
Referenced by FrameBufferAllocatorWaitOnTransfer(), HALSDL2::sdl_init(), sdlCleanup2(), and transferThreadFunc().
sem_transfer_ready
SDL_sem* sem_transfer_ready = 0 static
Referenced by FrameBufferAllocatorSignalBlockDrawn(), HALSDL2::sdl_init(), sdlCleanup2(), and transferThreadFunc().
simulatorRenderer
SDL_Renderer* simulatorRenderer = 0 static
Referenced by HALSDL2::flushFrameBuffer(), HALSDL2::recreateWindow(), HALSDL2::renderLCD_FrameBufferToMemory(), HALSDL2::saveScreenshot(), and sdlCleanup2().
simulatorWindow
SDL_Window* simulatorWindow = 0 static
Referenced by HALSDL2::recreateWindow(), HALSDL2::saveScreenshot(), HALSDL2::sdl_init(), sdlCleanup2(), HALSDL2::taskEntry(), and HALSDL2::updateTitle().
single_buf
uint16_t* single_buf = NULL static
Referenced by sdlCleanup2(), and HALSDL2::setFrameBufferSize().
SVG_INVALID
const uint16_t SVG_INVALID = 0xFFFFU
Define the svgId of an invalid SVG.
Referenced by SVGImage::draw(), SVGImage::getImageHeight(), SVGImage::getImageWidth(), SVGImage::getTransformationMatrix(), SVGImage::invalidateContent(), SVGImage::resizeToCurrentSVG(), and SVGImage::setSVG().
TEXT_DIRECTION_LTR
const TextDirection TEXT_DIRECTION_LTR = 0 static
Text is written Left-To-Right, e.g. English.
Referenced by Font::getStringWidth().
TEXT_DIRECTION_RTL
const TextDirection TEXT_DIRECTION_RTL = 1 static
Text is written Right-To-Left, e.g. Hebrew.
tft
uint16_t* tft = NULL static
Referenced by HALSDL2::getTFTFrameBuffer(), HALSDL2::setFrameBufferSize(), HALSDL2::setTFTFrameBuffer(), and transferThreadFunc().
tft_display24
uint8_t* tft_display24 = NULL static
Referenced by HALSDL2::doRotate(), and sdlCleanup2().
tft_display24_allocated
bool tft_display24_allocated = false static
Referenced by HALSDL2::doRotate(), and sdlCleanup2().
tft_framebuffer24
uint8_t* tft_framebuffer24 = NULL static
Referenced by HALSDL2::scaleTo24bpp(), sdlCleanup2(), and HALSDL2::updateTitle().
tft_framebuffer24_allocated
bool tft_framebuffer24_allocated = false static
Referenced by HALSDL2::scaleTo24bpp(), and sdlCleanup2().
TYPED_TEXT_INVALID
const TypedTextId TYPED_TEXT_INVALID = 0xFFFFU
The ID of an invalid text.