Battery Simulator Documentation: TypedTextDatabase Namespace Reference
TypedTextDatabase Namespace Reference
Functions
const touchgfx::Font ** getFonts ()
const touchgfx::TypedText::TypedTextData * getInstance ()
const touchgfx::TypedText::TypedTextData * getInstance (touchgfx::LanguageId id)
uint16_t getInstanceSize ()
void resetFont (touchgfx::FontId fontId)
const touchgfx::Font * setFont (touchgfx::FontId fontId, const touchgfx::Font *)
Function Documentation
getFonts()
const touchgfx::Font ** getFonts ()
{
    return touchgfx_fonts;
}
References touchgfx_fonts.
Referenced by ApplicationFontProvider::getFont(), FontCache::initializeCachedFont(), and Texts::setLanguage().
getInstance() [1/2]
const touchgfx::TypedText::TypedTextData * getInstance ()
getInstance() [2/2]
const touchgfx::TypedText::TypedTextData * getInstance (touchgfx::LanguageId id)
{
    return typedTextDatabaseArray[id];
}
References typedTextDatabaseArray.
getInstanceSize()
uint16_t getInstanceSize ()
{
    return 0;
}
Referenced by Texts::setLanguage().
resetFont()
void resetFont (touchgfx::FontId fontId)
{
    switch (fontId)
    {
    case 0:
        touchgfx_fonts[0] = &(getFont_verdana_20_4bpp());
        break;
    case 1:
        touchgfx_fonts[1] = &(getFont_verdana_40_4bpp());
        break;
    case 2:
        touchgfx_fonts[2] = &(getFont_verdana_10_4bpp());
        break;
    }
}
References getFont_verdana_10_4bpp(), getFont_verdana_20_4bpp(), getFont_verdana_40_4bpp(), and touchgfx_fonts.
setFont()
const touchgfx::Font * setFont (touchgfx::FontId fontId, const touchgfx::Font * font)
{
    const touchgfx::Font* old = touchgfx_fonts[fontId];
    touchgfx_fonts[fontId] = font;
    return old;
}
References touchgfx_fonts.