Battery Simulator Documentation: SVGDatabase Namespace Reference
SVGDatabase Namespace Reference
Functions
const touchgfx::VGObject * getInstance ()
uint16_t getInstanceSize ()
Function Documentation
getInstance()
const touchgfx::VGObject * getInstance ()
{
    return (const touchgfx::VGObject*)0;
}
Referenced by SVGImage::draw(), SVGImage::getImageHeight(), SVGImage::getImageWidth(), SVGImage::invalidateContent(), and SVGImage::resizeToCurrentSVG().
getInstanceSize()
uint16_t getInstanceSize ()
{
    return 0;
}
Referenced by SVGImage::setSVG().