Battery Simulator Documentation: FontContextualFormsTable
FontContextualFormsTable
#include "Font.hpp"
Public Types
typedef const Unicode::UnicodeChar(* arrayOf4UnicodesPtr)[4]
typedef const Unicode::UnicodeChar(* arrayOf5UnicodesPtr)[5]
Public Attributes
const Unicode::UnicodeChar(* contextualForms0621_063a)[4]
Table of contextual forms for glyphs 0x0621 to 0x63A.
const Unicode::UnicodeChar(* contextualForms0641_064a)[4]
Table of contextual forms for glyphs 0x0641 to 0x64A.
const Unicode::UnicodeChar(* contextualForms06XX)[5]
Table of contextual forms for remaining glyphs 0x06XX.
uint16_t contextualForms06XXSize
Length of the table.
const Unicode::UnicodeChar(* contextualForms2Long)[5]
Table of contextual forms for sequences of 2 glyphs.
uint16_t contextualForms2LongSize
Length of the table.
const Unicode::UnicodeChar(* contextualForms3Long)[5]
Table of contextual forms for sequences of 3 glyphs.
uint16_t contextualForms3LongSize
Length of the table.
const Unicode::UnicodeChar(* contextualForms4Long)[5]
Table of contextual forms for sequences of 4 glyphs.
uint16_t contextualForms4LongSize
Length of the table.
Detailed Description
Structure providing information about the contextual forms available in a font.
Member Typedef Documentation
arrayOf4UnicodesPtr
typedef const Unicode::UnicodeChar(* arrayOf4UnicodesPtr)[4]
Defines pointer to array of 4 unicodes type
arrayOf5UnicodesPtr
typedef const Unicode::UnicodeChar(* arrayOf5UnicodesPtr)[5]
Defines pointer to array of 5 unicodes type
Member Data Documentation
contextualForms0621_063a
const Unicode::UnicodeChar(* contextualForms0621_063a)[4]
Table of contextual forms for glyphs 0x0621 to 0x63A.
Referenced by BinaryFont::setupContextualTable().
contextualForms0641_064a
const Unicode::UnicodeChar(* contextualForms0641_064a)[4]
Table of contextual forms for glyphs 0x0641 to 0x64A.
Referenced by BinaryFont::setupContextualTable().
contextualForms06XX
const Unicode::UnicodeChar(* contextualForms06XX)[5]
Table of contextual forms for remaining glyphs 0x06XX.
Referenced by BinaryFont::setupContextualTable().
contextualForms06XXSize
uint16_t contextualForms06XXSize
Length of the table.
Referenced by BinaryFont::setupContextualTable().
contextualForms2Long
const Unicode::UnicodeChar(* contextualForms2Long)[5]
Table of contextual forms for sequences of 2 glyphs.
Referenced by BinaryFont::setupContextualTable().
contextualForms2LongSize
uint16_t contextualForms2LongSize
Length of the table.
Referenced by BinaryFont::setupContextualTable().
contextualForms3Long
const Unicode::UnicodeChar(* contextualForms3Long)[5]
Table of contextual forms for sequences of 3 glyphs.
Referenced by BinaryFont::setupContextualTable().
contextualForms3LongSize
uint16_t contextualForms3LongSize
Length of the table.
Referenced by BinaryFont::setupContextualTable().
contextualForms4Long
const Unicode::UnicodeChar(* contextualForms4Long)[5]
Table of contextual forms for sequences of 4 glyphs.
Referenced by BinaryFont::setupContextualTable().
contextualForms4LongSize
uint16_t contextualForms4LongSize
Length of the table.
Referenced by BinaryFont::setupContextualTable().
The documentation for this struct was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/Font.hpp