Battery Simulator Documentation: CWRUtil
CWRUtil
#include "CWRUtil.hpp"
Classes
class Q10
class Q15
class Q5
Static Public Member Functions
static int angle (Q5 x, Q5 y)
static int angle (Q5 x, Q5 y, Q5 &d)
template<typename T >
static int angle (T x, T y)
template<typename T >
static int angle (T x, T y, T &d)
static int8_t arcsine (Q10 q10)
static Q15 cosine (int i)
static Q15 cosine (Q5 i)
static Q5 length (Q5 x, Q5 y)
static Q5 muldiv_toQ5 (int32_t factor1, int32_t factor2, int32_t divisor)
static Q5 muldivQ10 (Q10 factor1, Q10 factor2, Q10 divisor)
static Q5 muldivQ5 (Q5 factor1, Q5 factor2, Q5 divisor)
static Q5 mulQ5 (Q5 factor1, Q10 factor2)
static Q5 mulQ5 (Q5 factor1, Q5 factor2)
static Q15 sine (int i)
static Q15 sine (Q5 i)
static Q5 sqrtQ10 (Q10 value)
template<typename T >
static FORCE_INLINE_FUNCTION Q10 toQ10 (T value)
static FORCE_INLINE_FUNCTION Q5 toQ5 (Q5 value)
template<typename T >
static FORCE_INLINE_FUNCTION Q5 toQ5 (T value)
Static Private Member Functions
static int _angle (Q5 x, Q5 y, Q5 &d)
static uint32_t isqrt (uint32_t n)
Detailed Description
Helper classes and functions for CanvasWidget. A handful of utility functions can be found here. These include helper functions for converting between float, int and Q5/Q10/Q15 formats. There are also functions for calculating sin() and cos() in integers with a high number of bits (15) reserved for fraction. Having sin() and cos() pre-calculated in this way allows very fast drawing of circles without the need for floating point arithmetic.
Using Q5, which uses 32 bit value internally, numbers from -67108865 to +67108864.96875 with a precision of 1/32 = 0.03125 can be represented, as described in http://en.wikipedia.org/wiki/Q_%28number_format%29.
Doing arithmetic operations on Q5, Q10 and Q15 numbers is described in detail on http://en.wikipedia.org/wiki/Fixed-point_arithmetic.
Member Function Documentation
_angle()
static int _angle (Q5 x, Q5 y, Q5 & d) inline static private
    {
        assert(x >= 0 && y >= 0);
        // The sine table from 0-45 is more precise, so swap x/y to get the angle in that range
        if (x < y)
        {
            return 90 - _angle(y, x, d);
        }
        Q5 _1 = toQ5<int>(1); // Used to convert Q5->Q10->Q15
        d = length(x, y);
        if (d == 0)
        {
            return 0; // Error
        }
        int32_t remainder;
        Q10 dy = Q10(muldiv((int)y, (int)(_1 * _1), (int)d, remainder));
        return arcsine(dy);
    }
References CWRUtil::_angle(), CWRUtil::arcsine(), and touchgfx::muldiv().
Referenced by CWRUtil::_angle(), and CWRUtil::angle().
angle() [1/4]
static int angle (Q5 x, Q5 y) inline static
Find angle of a coordinate relative to (0,0).
Parameters
x The x coordinate.
y The y coordinate.
Returns
The angle of the coordinate.
    {
        Q5 dist;
        return angle(x, y, dist);
    }
angle() [2/4]
static int angle (Q5 x, Q5 y, Q5 & d) inline static
Find the angle of the coordinate (x, y) relative to (0, 0).
Parameters
x The x coordinate.
y The y coordinate.
[out] d The distance from (0,0) to (x,y).
Returns
The angle.
    {
        // Map to quadrant 1
        if (x >= 0)
        {
            if (y >= 0)
            {
                return 90 + _angle(x, y, d);
            }
            // y < 0
            return 90 - _angle(x, -y, d);
        }
        // x < 0
        if (y >= 0)
        {
            return 270 - _angle(-x, y, d);
        }
        // y < 0
        return 270 + _angle(-x, -y, d);
    }
References CWRUtil::_angle().
angle() [3/4]
template<typename T > static int angle (T x, T y) inline static
Find angle of a coordinate relative to (0,0).
Template Parameters
T Generic type parameter (int or float).
Parameters
x The x coordinate.
y The y coordinate.
Returns
The angle of the coordinate.
    {
        Q5 dist;
        return angle(toQ5<T>(x), toQ5<T>(y), dist);
    }
Referenced by Line::drawCanvasWidget().
angle() [4/4]
template<typename T > static int angle (T x, T y, T & d) inline static
Find angle of a coordinate relative to (0,0).
Template Parameters
T Generic type parameter (int or float).
Parameters
x The x coordinate.
y The y coordinate.
[out] d The distance from (0,0) to (x,y).
Returns
The angle of the coordinate.
    {
        Q5 dist;
        int a = angle(toQ5<T>(x), toQ5<T>(y), dist);
        d = dist.to<T>();
        return a;
    }
arcsine()
static int8_t arcsine (Q10 q10) inline static
Gets the arcsine of the given fraction (given as Q10). The function is most precise for angles 0-45. To limit memory requirements, values above sqrt(1/2) is calculated as 90-arcsine(sqrt(1-q10^2)). Internally.
Parameters
q10 The 10.
Returns
An int8_t.
    {
        const static uint8_t arcsineTable[91] = {
            0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 4, 5, 5, 6, 6,
            7, 7, 8, 8, 9, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13,
            14, 14, 14, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 20, 20,
            21, 21, 22, 22, 23, 23, 23, 24, 24, 25, 25, 26, 26, 27, 27,
            28, 28, 29, 29, 30, 31, 31, 32, 32, 33, 33, 34, 34, 35, 35,
            36, 36, 37, 38, 38, 39, 39, 40, 40, 41, 42, 42, 43, 43, 44, 45
        };
        if (q10 < 0)
        {
            return -arcsine(-q10);
        }
        if (q10 > toQ10<int>(1))
        {
            return 0; // error
        }
        // sqrt(1/2) as Q10 is "724" so if q10>724 calculate 90-arcsine(sqrt(1-q10^2))
        if ((int)q10 > 724)
        {
            return 90 - arcsine(Q10(isqrt((1 << (Rasterizer::POLY_BASE_SHIFT * 4)) - (int)q10 * (int)q10)));
        }
        int q7 = ((int)q10 + 3) >> 3; // Round Q10 to nearest Q7
        return arcsineTable[q7];
    }
References CWRUtil::arcsine(), and CWRUtil::isqrt().
Referenced by CWRUtil::_angle(), and CWRUtil::arcsine().
cosine() [1/2]
static Q15 cosine (int i) inline static
Find the value of cos(i) with 15 bits precision using the fact that cos(i)=sin(90-i).
Parameters
i the angle in degrees. The angle follows the angles of the clock, 0 being straight up and 90 being 3 o'clock.
Returns
the value of cos(i) with 15 bits precision on the fractional part.
See also
sine
    {
        return sine(90 - i);
    }
References CWRUtil::sine().
Referenced by Circle::drawCanvasWidget(), Line::drawCanvasWidget(), Circle::lineToXYAngleRadius2(), Circle::moveToAngleRadius2(), AbstractShape::updateAbstractShapeCache(), Line::updateLengthAndAngle(), Circle::updateMinMaxAngleLine(), and Circle::updateMinMaxAngleSolid().
cosine() [2/2]
static Q15 cosine (Q5 i) inline static
Find the value of cos(i) with 15 bits precision using the fact that cos(i)=sin(90-i).
Parameters
i the angle in degrees. The angle follows the angles of the clock, 0 being straight up and 90 being 3 o'clock.
Returns
the value of cos(i) with 15 bits precision on the fractional part.
See also
sine
    {
        return sine(toQ5<int>(90) - i);
    }
References CWRUtil::sine().
isqrt()
static uint32_t isqrt (uint32_t n) inline static private
    {
        uint32_t root = 0, bit, trial;
        bit = (n >= 0x10000) ? 1 << 30 : 1 << 14;
        do
        {
            trial = root + bit;
            if (n >= trial)
            {
                n -= trial;
                root = trial + bit;
            }
            root >>= 1;
            bit >>= 2;
        } while (bit);
        return root;
    }
Referenced by CWRUtil::arcsine(), and CWRUtil::sqrtQ10().
length()
static Q5 length (Q5 x, Q5 y) inline static
Find the length of a given distance x,y as sqrt(x*x+y*y) while avoiding overflow. The function uses sqrtQ10(Q10) as a helper function.
Parameters
x The x distance.
y The y distance.
Returns
The length of the vector (x,y).
See also
sqrtQ10
    {
        // Check if x*x or y*y is likely to overflow
        const int absx = abs((int)x);
        const int absy = abs((int)y);
        // Find a scaling factor to make the calulation overflow-safe
        const int factor = MAX(absx >> 14, absy >> 14);
        if (factor > 1)
        {
            // Recursive call on a smaller number
            return length(x / factor, y / factor) * factor;
        }
        return sqrtQ10(x * x + y * y);
    }
References touchgfx::abs(), MAX, and CWRUtil::sqrtQ10().
Referenced by GraphElementLine::drawIndexRange(), and Line::updateCachedShape().
muldiv_toQ5()
static Q5 muldiv_toQ5 (int32_t factor1, int32_t factor2, int32_t divisor) inline static
Multiply two integers and divide by an integer without overflowing the multiplication. The result is returned in a Q5 thus allowing a more precise calculation to be performed.
Parameters
factor1 The first factor.
factor2 The second factor.
divisor The divisor.
Returns
factor1 * factor2 / divisor as a Q5
    {
        int32_t remainder;
        int32_t result = muldiv(factor1, factor2, divisor, remainder);
        if (result >= 0)
        {
            return toQ5(result) + muldivQ5(Q5(Rasterizer::POLY_BASE_SIZE), Q5(remainder), Q5(divisor));
        }
        return toQ5(result) - muldivQ5(Q5(Rasterizer::POLY_BASE_SIZE), Q5(remainder), Q5(divisor));
    }
References touchgfx::muldiv(), CWRUtil::muldivQ5(), and CWRUtil::toQ5().
Referenced by AbstractDataGraph::valueToScreenXQ5(), and AbstractDataGraph::valueToScreenYQ5().
muldivQ10()
static Q5 muldivQ10 (Q10 factor1, Q10 factor2, Q10 divisor) inline static
Multiply two Q5's and divide by a Q5 without overflowing the multiplication (assuming that the final result can be stored in a Q5).
Parameters
factor1 The first factor.
factor2 The second factor.
divisor The divisor.
Returns
factor1 * factor2 / divisor.
    {
        int32_t remainder;
        return Q5(muldiv((int)factor1, (int)factor2, (int)divisor, remainder) / Rasterizer::POLY_BASE_SIZE);
    }
References touchgfx::muldiv().
Referenced by CWRUtil::mulQ5().
muldivQ5()
static Q5 muldivQ5 (Q5 factor1, Q5 factor2, Q5 divisor) inline static
Multiply two Q5's and divide by a Q5 without overflowing the multiplication (assuming that the final result can be stored in a Q5).
Parameters
factor1 The first factor.
factor2 The second factor.
divisor The divisor.
Returns
factor1 * factor2 / divisor.
    {
        return Q5(muldiv((int)factor1, (int)factor2, (int)divisor));
    }
References touchgfx::muldiv().
Referenced by GraphElementDots::drawCanvasWidget(), GraphElementLine::drawIndexRange(), CWRUtil::muldiv_toQ5(), CWRUtil::mulQ5(), Line::updateCachedShape(), DynamicDataGraph::xScreenRangeToIndexRange(), and StaticDataGraph::xScreenRangeToIndexRange().
mulQ5() [1/2]
static Q5 mulQ5 (Q5 factor1, Q10 factor2) inline static
Multiply one Q5 by a Q10 returning a new Q5 without overflowing.
Parameters
factor1 The first factor.
factor2 The second factor.
Returns
factor1 * factor2.
    {
        return muldivQ10(Q10((int)factor1 * Rasterizer::POLY_BASE_SIZE), factor2, toQ10<int>(1));
    }
References CWRUtil::muldivQ10().
mulQ5() [2/2]
static Q5 mulQ5 (Q5 factor1, Q5 factor2) inline static
Multiply two Q5's returning a new Q5 without overflowing.
Parameters
factor1 The first factor.
factor2 The second factor.
Returns
factor1 * factor2.
    {
        return muldivQ5(factor1, factor2, toQ5<int>(1));
    }
References CWRUtil::muldivQ5().
Referenced by AbstractShape::updateAbstractShapeCache().
sine() [1/2]
static Q15 sine (int i) inline static
Find the value of sin(i) with 15 bits precision. The returned value can be converted to a floating point number and divided by (1<<15) to get the rounded value of sin(i). By using this function, a complete circle can be drawn without the need for using floating point math.
Parameters
i the angle in degrees. The angle follows the angles of the clock, 0 being straight up and 90 being 3 o'clock.
Returns
the value of sin(i) with 15 bits precision on the fractional part.
    {
        const static uint16_t sineTable[91] = {
            0x0000, 0x023C, 0x0478, 0x06B3, 0x08EE, 0x0B28, 0x0D61, 0x0F99, 0x11D0, 0x1406,
            0x163A, 0x186C, 0x1A9D, 0x1CCB, 0x1EF7, 0x2121, 0x2348, 0x256C, 0x278E, 0x29AC,
            0x2BC7, 0x2DDF, 0x2FF3, 0x3203, 0x3410, 0x3618, 0x381D, 0x3A1C, 0x3C18, 0x3E0E,
            0x4000, 0x41ED, 0x43D4, 0x45B7, 0x4794, 0x496B, 0x4B3D, 0x4D08, 0x4ECE, 0x508E,
            0x5247, 0x53FA, 0x55A6, 0x574C, 0x58EB, 0x5A82, 0x5C13, 0x5D9D, 0x5F1F, 0x609A,
            0x620E, 0x637A, 0x64DE, 0x663A, 0x678E, 0x68DA, 0x6A1E, 0x6B5A, 0x6C8D, 0x6DB8,
            0x6EDA, 0x6FF4, 0x7104, 0x720D, 0x730C, 0x7402, 0x74EF, 0x75D3, 0x76AE, 0x7780,
            0x7848, 0x7907, 0x79BC, 0x7A68, 0x7B0B, 0x7BA3, 0x7C33, 0x7CB8, 0x7D34, 0x7DA6,
            0x7E0E, 0x7E6D, 0x7EC1, 0x7F0C, 0x7F4C, 0x7F83, 0x7FB0, 0x7FD3, 0x7FEC, 0x7FFB, 0x8000
        };
        i %= 360;
        if (i < 0)
        {
            i += 360;
        }
        if (i <= 90)
        {
            return Q15(sineTable[i]);
        }
        if (i <= 180)
        {
            return Q15(sineTable[180 - i]);
        }
        if (i <= 270)
        {
            return Q15(-int32_t(sineTable[i - 180]));
        }
        return Q15(-int32_t(sineTable[360 - i]));
    }
Referenced by CWRUtil::cosine(), CWRUtil::cosine(), Circle::drawCanvasWidget(), Line::drawCanvasWidget(), Circle::lineToXYAngleRadius2(), Circle::moveToAngleRadius2(), CWRUtil::sine(), AbstractShape::updateAbstractShapeCache(), Line::updateLengthAndAngle(), Circle::updateMinMaxAngleLine(), and Circle::updateMinMaxAngleSolid().
sine() [2/2]
static Q15 sine (Q5 i) inline static
Find the value of sin(i) with 15 bits precision. The returned value can be converted to a floating point number and divided by (1<<15) to get the rounded value of sin(i). By using this function, a complete circle can be drawn without the need for using floating point math.
If the given degree is not an integer, the value is approximated by interpolation between sin(floor(i)) and sin(ceil(i)).
Parameters
i the angle in degrees. The angle follows the angles of the clock, 0 being straight up and 90 being 3 o'clock.
Returns
the value of sin(i) with 15 bits precision on the fractional part.
    {
        Q5 _360 = toQ5<int>(360);
        i %= _360;
        if (i < 0)
        {
            i += _360;
        }
        int16_t fraction = i % Rasterizer::POLY_BASE_SIZE;
        Q15 sineLow = sine(i.to<int>());
        if (fraction == 0)
        {
            return sineLow;
        }
        Q15 sineHigh = sine(i.to<int>() + 1);
        int32_t remainder;
        return Q15(muldiv((int)(sineHigh - sineLow), fraction, Rasterizer::POLY_BASE_SIZE, remainder)) + sineLow;
    }
References touchgfx::muldiv(), CWRUtil::sine(), and CWRUtil::Q5::to().
sqrtQ10()
static Q5 sqrtQ10 (Q10 value) inline static
Find the square root of the given value. Consider using length to avoid possible overflow when calculating a length.
Parameters
value The value to find the square root of.
Returns
The square root of the given value.
See also
length
    {
        return Q5(isqrt(uint32_t((int)value)));
    }
References CWRUtil::isqrt().
Referenced by CWRUtil::length().
toQ10()
template<typename T > static FORCE_INLINE_FUNCTION Q10 toQ10 (T value) inline static
Convert an integer to a fixed point number. This is done by multiplying the floating point value by (1 << 10).
Template Parameters
T Should be either int or float.
Parameters
value the integer to convert.
Returns
the converted integer.
    {
        return Q10((int)(value * Rasterizer::POLY_BASE_SIZE * Rasterizer::POLY_BASE_SIZE));
    }
toQ5() [1/2]
static FORCE_INLINE_FUNCTION Q5 toQ5 (Q5 value) inline static
Convert a Q5 to itself. Allows toQ5 to be called with a variable that is already Q5.
Parameters
value the Q5.
Returns
the value passed.
    {
        return value;
    }
Referenced by GraphElementGridBase::draw(), GraphElementHistogram::draw(), GraphElementBoxes::draw(), GraphElementLine::drawCanvasWidget(), GraphElementDots::drawCanvasWidget(), GraphElementDiamonds::drawCanvasWidget(), GraphElementLine::drawIndexRange(), GraphScrollData::indexToXQ5(), GraphElementLine::invalidateGraphPointAt(), GraphElementHistogram::invalidateGraphPointAt(), GraphElementBoxes::invalidateGraphPointAt(), GraphElementDots::invalidateGraphPointAt(), GraphElementDiamonds::invalidateGraphPointAt(), CWRUtil::muldiv_toQ5(), CWRUtil::Q5::round(), AbstractGraphElement::roundQ5(), Circle::setArc(), Circle::setCenter(), Circle::setLineWidth(), Circle::setPixelCenter(), Circle::setRadius(), CircleProgress::setValue(), Circle::updateArc(), Circle::updateArcEnd(), Circle::updateArcStart(), AbstractDataGraph::valueToScreenXQ5(), AbstractDataGraph::valueToScreenYQ5(), DynamicDataGraph::xScreenRangeToIndexRange(), and StaticDataGraph::xScreenRangeToIndexRange().
toQ5() [2/2]
template<typename T > static FORCE_INLINE_FUNCTION Q5 toQ5 (T value) inline static
Convert an integer to a fixed point number. This is done by multiplying the floating point value by (1 << 5)
Template Parameters
T Should be either int or float.
Parameters
value the integer to convert.
Returns
the converted integer.
    {
        return Q5((int)(value * Rasterizer::POLY_BASE_SIZE));
    }
The documentation for this struct was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/widgets/canvas/CWRUtil.hpp