Battery Simulator Documentation: Callback< dest_type, T1, T2, T3 >
Callback< dest_type, T1, T2, T3 >
#include "Callback.hpp"
Public Member Functions
Callback ()
Callback (dest_type *pObject, void(dest_type::*pmemfun_3)(T1, T2, T3))
virtual void execute (T1 t1, T2 t2, T3 t3)
virtual bool isValid () const
Public Member Functions inherited from GenericCallback< T1, T2, T3 >
virtual ~GenericCallback ()
Private Attributes
void(dest_type::* pmemfun)(T1, T2, T3)
dest_type * pobject
Detailed Description
template<class dest_type, typename T1 = void, typename T2 = void, typename T3 = void>
struct touchgfx::Callback< dest_type, T1, T2, T3 >
A Callback is basically a wrapper of a pointer-to-member-function.
It is used for registering callbacks between widgets. For instance, a Button can be configured to call a member function when it is clicked.
The class is templated in order to provide the class type of the object in which the member function resides, and the argument types of the function to call.
The Callback class exists in four versions, for supporting member functions with 0, 1, 2 or 3 arguments. The compiler will infer which type to use automatically.
Template Parameters
dest_type The type of the class in which the member function resides.
T1 The type of the first argument in the member function, or void if none.
T2 The type of the second argument in the member function, or void if none.
T3 The type of the third argument in the member function, or void if none.
Note
The member function to call must return void. The function can have zero, one, two or three arguments of any type.
Constructor & Destructor Documentation
Callback() [1/2]
template<class dest_type , typename T1 = void, typename T2 = void, typename T3 = void> Callback () inline
Initializes a new instance of the Callback class.
        : pobject(0), pmemfun(0)
    {
    }
Callback() [2/2]
template<class dest_type , typename T1 = void, typename T2 = void, typename T3 = void> Callback (dest_type * pObject, void(dest_type::*)(T1, T2, T3) pmemfun_3) inline
Initializes a Callback with an object and a pointer to the member function in that object to call.
Initializes a Callback with an object and a pointer to the member function in that object to call.
Parameters
[in] pObject Pointer to the object on which the function should be called.
[in] pmemfun_3 Address of member function. This is the version where function takes three arguments.
        : pobject(pObject), pmemfun(pmemfun_3)
    {
    }
Member Function Documentation
execute()
template<class dest_type , typename T1 = void, typename T2 = void, typename T3 = void> virtual void execute (T1 t1, T2 t2, T3 t3) inline virtual
Calls the member function. Do not call execute unless isValid() returns true (ie. a pointer to the object and the function has been set).
Parameters
t1 This value will be passed as the first argument in the function call.
t2 This value will be passed as the second argument in the function call.
t3 This value will be passed as the third argument in the function call.
Implements GenericCallback< T1, T2, T3 >.
    {
        (pobject->*pmemfun)(t1, t2, t3);
    }
References Callback< dest_type, T1, T2, T3 >::pmemfun, and Callback< dest_type, T1, T2, T3 >::pobject.
isValid()
template<class dest_type , typename T1 = void, typename T2 = void, typename T3 = void> virtual bool isValid () const inline virtual
Function to check whether the Callback has been initialized with values.
Returns
true If the callback is valid (i.e. safe to call execute).
Implements GenericCallback< T1, T2, T3 >.
    {
        return (pobject != 0) && (pmemfun != 0);
    }
References Callback< dest_type, T1, T2, T3 >::pmemfun, and Callback< dest_type, T1, T2, T3 >::pobject.
Member Data Documentation
pmemfun
template<class dest_type , typename T1 = void, typename T2 = void, typename T3 = void> void(dest_type::* pmemfun) (T1, T2, T3) private
Referenced by Callback< dest_type, void, void, void >::execute(), Callback< dest_type, T1, void, void >::execute(), Callback< dest_type, T1, T2, void >::execute(), Callback< dest_type, T1, T2, T3 >::execute(), Callback< dest_type, T1, T2, T3 >::isValid(), Callback< dest_type, T1, T2, void >::isValid(), Callback< dest_type, T1, void, void >::isValid(), and Callback< dest_type, void, void, void >::isValid().
pobject
template<class dest_type , typename T1 = void, typename T2 = void, typename T3 = void> dest_type* pobject private
Referenced by Callback< dest_type, void, void, void >::execute(), Callback< dest_type, T1, void, void >::execute(), Callback< dest_type, T1, T2, void >::execute(), Callback< dest_type, T1, T2, T3 >::execute(), Callback< dest_type, T1, T2, T3 >::isValid(), Callback< dest_type, T1, T2, void >::isValid(), Callback< dest_type, T1, void, void >::isValid(), and Callback< dest_type, void, void, void >::isValid().
The documentation for this struct was generated from the following file:
C:/Users/hussamaldean/STM32CubeIDE/Riverdi/Riverdi_Displays/Riverdi7/BatterySimulator/CM7/Middlewares/ST/touchgfx/framework/include/touchgfx/Callback.hpp