################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Common/Src \
Core/Src \
Core/Startup \
Drivers/STM32H7xx_HAL_Driver \
FATFS/App \
FATFS/Target \
Middlewares/ST/STM32_USB_Host_Library \
Middlewares/Third_Party/FatFs \
Middlewares/Third_Party/FreeRTOS \
Middlewares/Third_Party/lvgl/demos/benchmark/assets \
Middlewares/Third_Party/lvgl/demos/benchmark \
Middlewares/Third_Party/lvgl/demos/flex_layout \
Middlewares/Third_Party/lvgl/demos/keypad_encoder \
Middlewares/Third_Party/lvgl/demos \
Middlewares/Third_Party/lvgl/demos/multilang/assets/avatars \
Middlewares/Third_Party/lvgl/demos/multilang/assets/emojis \
Middlewares/Third_Party/lvgl/demos/multilang/assets/fonts \
Middlewares/Third_Party/lvgl/demos/multilang/assets \
Middlewares/Third_Party/lvgl/demos/multilang \
Middlewares/Third_Party/lvgl/demos/music/assets \
Middlewares/Third_Party/lvgl/demos/music \
Middlewares/Third_Party/lvgl/demos/render/assets \
Middlewares/Third_Party/lvgl/demos/render \
Middlewares/Third_Party/lvgl/demos/scroll \
Middlewares/Third_Party/lvgl/demos/stress \
Middlewares/Third_Party/lvgl/demos/transform/assets \
Middlewares/Third_Party/lvgl/demos/transform \
Middlewares/Third_Party/lvgl/demos/vector_graphic/assets \
Middlewares/Third_Party/lvgl/demos/vector_graphic \
Middlewares/Third_Party/lvgl/demos/widgets/assets \
Middlewares/Third_Party/lvgl/demos/widgets \
Middlewares/Third_Party/lvgl/env_support/pikascript \
Middlewares/Third_Party/lvgl/env_support/rt-thread \
Middlewares/Third_Party/lvgl/env_support/rt-thread/squareline \
Middlewares/Third_Party/lvgl/examples/anim \
Middlewares/Third_Party/lvgl/examples/assets \
Middlewares/Third_Party/lvgl/examples/assets/emoji \
Middlewares/Third_Party/lvgl/examples/event \
Middlewares/Third_Party/lvgl/examples/get_started \
Middlewares/Third_Party/lvgl/examples/layouts/flex \
Middlewares/Third_Party/lvgl/examples/layouts/grid \
Middlewares/Third_Party/lvgl/examples/libs/barcode \
Middlewares/Third_Party/lvgl/examples/libs/bmp \
Middlewares/Third_Party/lvgl/examples/libs/ffmpeg \
Middlewares/Third_Party/lvgl/examples/libs/freetype \
Middlewares/Third_Party/lvgl/examples/libs/gif \
Middlewares/Third_Party/lvgl/examples/libs/libjpeg_turbo \
Middlewares/Third_Party/lvgl/examples/libs/libpng \
Middlewares/Third_Party/lvgl/examples/libs/lodepng \
Middlewares/Third_Party/lvgl/examples/libs/qrcode \
Middlewares/Third_Party/lvgl/examples/libs/rlottie \
Middlewares/Third_Party/lvgl/examples/libs/tiny_ttf \
Middlewares/Third_Party/lvgl/examples/libs/tjpgd \
Middlewares/Third_Party/lvgl/examples/others/file_explorer \
Middlewares/Third_Party/lvgl/examples/others/fragment \
Middlewares/Third_Party/lvgl/examples/others/gridnav \
Middlewares/Third_Party/lvgl/examples/others/ime \
Middlewares/Third_Party/lvgl/examples/others/imgfont \
Middlewares/Third_Party/lvgl/examples/others/monkey \
Middlewares/Third_Party/lvgl/examples/others/observer \
Middlewares/Third_Party/lvgl/examples/others/snapshot \
Middlewares/Third_Party/lvgl/examples/porting \
Middlewares/Third_Party/lvgl/examples/scroll \
Middlewares/Third_Party/lvgl/examples/styles \
Middlewares/Third_Party/lvgl/examples/widgets/animimg \
Middlewares/Third_Party/lvgl/examples/widgets/arc \
Middlewares/Third_Party/lvgl/examples/widgets/bar \
Middlewares/Third_Party/lvgl/examples/widgets/button \
Middlewares/Third_Party/lvgl/examples/widgets/buttonmatrix \
Middlewares/Third_Party/lvgl/examples/widgets/calendar \
Middlewares/Third_Party/lvgl/examples/widgets/canvas \
Middlewares/Third_Party/lvgl/examples/widgets/chart \
Middlewares/Third_Party/lvgl/examples/widgets/checkbox \
Middlewares/Third_Party/lvgl/examples/widgets/dropdown \
Middlewares/Third_Party/lvgl/examples/widgets/image \
Middlewares/Third_Party/lvgl/examples/widgets/imagebutton \
Middlewares/Third_Party/lvgl/examples/widgets/keyboard \
Middlewares/Third_Party/lvgl/examples/widgets/label \
Middlewares/Third_Party/lvgl/examples/widgets/led \
Middlewares/Third_Party/lvgl/examples/widgets/line \
Middlewares/Third_Party/lvgl/examples/widgets/list \
Middlewares/Third_Party/lvgl/examples/widgets/menu \
Middlewares/Third_Party/lvgl/examples/widgets/msgbox \
Middlewares/Third_Party/lvgl/examples/widgets/obj \
Middlewares/Third_Party/lvgl/examples/widgets/roller \
Middlewares/Third_Party/lvgl/examples/widgets/scale \
Middlewares/Third_Party/lvgl/examples/widgets/slider \
Middlewares/Third_Party/lvgl/examples/widgets/span \
Middlewares/Third_Party/lvgl/examples/widgets/spinbox \
Middlewares/Third_Party/lvgl/examples/widgets/spinner \
Middlewares/Third_Party/lvgl/examples/widgets/switch \
Middlewares/Third_Party/lvgl/examples/widgets/table \
Middlewares/Third_Party/lvgl/examples/widgets/tabview \
Middlewares/Third_Party/lvgl/examples/widgets/textarea \
Middlewares/Third_Party/lvgl/examples/widgets/tileview \
Middlewares/Third_Party/lvgl/examples/widgets/win \
Middlewares/Third_Party/lvgl/src/core \
Middlewares/Third_Party/lvgl/src/display \
Middlewares/Third_Party/lvgl/src/draw \
Middlewares/Third_Party/lvgl/src/draw/nxp/pxp \
Middlewares/Third_Party/lvgl/src/draw/nxp/vglite \
Middlewares/Third_Party/lvgl/src/draw/renesas/dave2d \
Middlewares/Third_Party/lvgl/src/draw/sdl \
Middlewares/Third_Party/lvgl/src/draw/sw/blend/helium \
Middlewares/Third_Party/lvgl/src/draw/sw/blend \
Middlewares/Third_Party/lvgl/src/draw/sw/blend/neon \
Middlewares/Third_Party/lvgl/src/draw/sw \
Middlewares/Third_Party/lvgl/src/draw/vg_lite \
Middlewares/Third_Party/lvgl/src/drivers/display/drm \
Middlewares/Third_Party/lvgl/src/drivers/display/fb \
Middlewares/Third_Party/lvgl/src/drivers/display/ili9341 \
Middlewares/Third_Party/lvgl/src/drivers/display/lcd \
Middlewares/Third_Party/lvgl/src/drivers/display/st7735 \
Middlewares/Third_Party/lvgl/src/drivers/display/st7789 \
Middlewares/Third_Party/lvgl/src/drivers/display/st7796 \
Middlewares/Third_Party/lvgl/src/drivers/evdev \
Middlewares/Third_Party/lvgl/src/drivers/libinput \
Middlewares/Third_Party/lvgl/src/drivers/nuttx \
Middlewares/Third_Party/lvgl/src/drivers/sdl \
Middlewares/Third_Party/lvgl/src/drivers/windows \
Middlewares/Third_Party/lvgl/src/drivers/x11 \
Middlewares/Third_Party/lvgl/src/font \
Middlewares/Third_Party/lvgl/src/indev \
Middlewares/Third_Party/lvgl/src/layouts/flex \
Middlewares/Third_Party/lvgl/src/layouts/grid \
Middlewares/Third_Party/lvgl/src/layouts \
Middlewares/Third_Party/lvgl/src/libs/barcode \
Middlewares/Third_Party/lvgl/src/libs/bin_decoder \
Middlewares/Third_Party/lvgl/src/libs/bmp \
Middlewares/Third_Party/lvgl/src/libs/ffmpeg \
Middlewares/Third_Party/lvgl/src/libs/freetype \
Middlewares/Third_Party/lvgl/src/libs/fsdrv \
Middlewares/Third_Party/lvgl/src/libs/gif \
Middlewares/Third_Party/lvgl/src/libs/libjpeg_turbo \
Middlewares/Third_Party/lvgl/src/libs/libpng \
Middlewares/Third_Party/lvgl/src/libs/lodepng \
Middlewares/Third_Party/lvgl/src/libs/lz4 \
Middlewares/Third_Party/lvgl/src/libs/qrcode \
Middlewares/Third_Party/lvgl/src/libs/rle \
Middlewares/Third_Party/lvgl/src/libs/rlottie \
Middlewares/Third_Party/lvgl/src/libs/tiny_ttf \
Middlewares/Third_Party/lvgl/src/libs/tjpgd \
Middlewares/Third_Party/lvgl/src \
Middlewares/Third_Party/lvgl/src/misc/cache \
Middlewares/Third_Party/lvgl/src/misc \
Middlewares/Third_Party/lvgl/src/osal \
Middlewares/Third_Party/lvgl/src/others/file_explorer \
Middlewares/Third_Party/lvgl/src/others/fragment \
Middlewares/Third_Party/lvgl/src/others/gridnav \
Middlewares/Third_Party/lvgl/src/others/ime \
Middlewares/Third_Party/lvgl/src/others/imgfont \
Middlewares/Third_Party/lvgl/src/others/monkey \
Middlewares/Third_Party/lvgl/src/others/observer \
Middlewares/Third_Party/lvgl/src/others/snapshot \
Middlewares/Third_Party/lvgl/src/others/sysmon \
Middlewares/Third_Party/lvgl/src/others/vg_lite_tvg \
Middlewares/Third_Party/lvgl/src/stdlib/builtin \
Middlewares/Third_Party/lvgl/src/stdlib/clib \
Middlewares/Third_Party/lvgl/src/stdlib \
Middlewares/Third_Party/lvgl/src/stdlib/micropython \
Middlewares/Third_Party/lvgl/src/stdlib/rtthread \
Middlewares/Third_Party/lvgl/src/themes/default \
Middlewares/Third_Party/lvgl/src/themes \
Middlewares/Third_Party/lvgl/src/themes/mono \
Middlewares/Third_Party/lvgl/src/themes/simple \
Middlewares/Third_Party/lvgl/src/tick \
Middlewares/Third_Party/lvgl/src/widgets/animimage \
Middlewares/Third_Party/lvgl/src/widgets/arc \
Middlewares/Third_Party/lvgl/src/widgets/bar \
Middlewares/Third_Party/lvgl/src/widgets/button \
Middlewares/Third_Party/lvgl/src/widgets/buttonmatrix \
Middlewares/Third_Party/lvgl/src/widgets/calendar \
Middlewares/Third_Party/lvgl/src/widgets/canvas \
Middlewares/Third_Party/lvgl/src/widgets/chart \
Middlewares/Third_Party/lvgl/src/widgets/checkbox \
Middlewares/Third_Party/lvgl/src/widgets/dropdown \
Middlewares/Third_Party/lvgl/src/widgets/image \
Middlewares/Third_Party/lvgl/src/widgets/imagebutton \
Middlewares/Third_Party/lvgl/src/widgets/keyboard \
Middlewares/Third_Party/lvgl/src/widgets/label \
Middlewares/Third_Party/lvgl/src/widgets/led \
Middlewares/Third_Party/lvgl/src/widgets/line \
Middlewares/Third_Party/lvgl/src/widgets/list \
Middlewares/Third_Party/lvgl/src/widgets/menu \
Middlewares/Third_Party/lvgl/src/widgets/msgbox \
Middlewares/Third_Party/lvgl/src/widgets/objx_templ \
Middlewares/Third_Party/lvgl/src/widgets/roller \
Middlewares/Third_Party/lvgl/src/widgets/scale \
Middlewares/Third_Party/lvgl/src/widgets/slider \
Middlewares/Third_Party/lvgl/src/widgets/span \
Middlewares/Third_Party/lvgl/src/widgets/spinbox \
Middlewares/Third_Party/lvgl/src/widgets/spinner \
Middlewares/Third_Party/lvgl/src/widgets/switch \
Middlewares/Third_Party/lvgl/src/widgets/table \
Middlewares/Third_Party/lvgl/src/widgets/tabview \
Middlewares/Third_Party/lvgl/src/widgets/textarea \
Middlewares/Third_Party/lvgl/src/widgets/tileview \
Middlewares/Third_Party/lvgl/src/widgets/win \
Middlewares/Third_Party/ui \
USB_HOST/App \
USB_HOST/Target \
Utilities \

